### ISSUE TITLE
OpenShift Registry: pull only possible on node which contains repository

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#6494] opened 2015-12-24 10:08 UTC
I have a clustered environment (1 master and 2 nodes) of Origin 1.1 on Centos 7 installed with ansible.
I have a secure registry which is using NFS.  By default it was on node1.
I was able to pull from node1 and from node2. But after a time it was only possbile to pull from node1. And not from node2 anymore. When I delete the registry pod, than it's recreated on node2. Than it's possible to pull from the registry on node2 but not on node1.

When I try to perform a manual login when the registry is on node 1:
It's possible to login on node1.
On node2 I get:
```
[centos]$ oc whoami -t
ft-VJ9mNAORN8DnwbLzHlqh3S_QLO4lroC_JXn0b7fg
[centos]$ docker login -u admin -e my.mail@mail.sdf \
> -p ft-VJ9mNAORN8DnwbLzHlqh3S_QLO4lroC_JXn0b7fg 172.30.152.xx:5000
Error response from daemon: invalid registry endpoint https://172.30.152.xx:5000/v0/: unable to ping registry endpoint https://172.30.152.xx:5000/v0/
v2 ping attempt failed with error: Get https://172.30.152.xx:5000/v2/: net/http: TLS handshake timeout
 v1 ping attempt failed with error: Get https://172.30.152.xx:5000/v1/_ping: net/http: TLS handshake timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.30.152.xx:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.30.152.xx:5000/ca.crt 
```
I have my certs in that folder.

When my registry is on node2:
I can login on node2
I can also login on node1. (but when I scale a pod 2 times it scales on node2 and it remains in pending state on node1). (but manually I can pull and push in both directions)

**Comment by lorenzvth7** [comment] 2015-12-28 10:56
Even after recreating a whole new cluster, I have the same issue..

**Comment by lorenzvth7** [comment] 2015-12-28 12:36
on the node where the registry is running I'm able to curl to the registry, but on the other node it takes a very long time before there will be a timeout.

This are the events in my webconsole 
```
Back-off pulling image 
```
and 
```
Failed to pull image "172.30.xx.xx:5000/test/test@sha256:019868732163ce018b0b3c4995583c951c2bac101864389adafbf3f6ddxxxx": Get https://172.30.xx.xx:5000/v2/: net/http: request canceled while waiting for connection
```

**Comment by lorenzvth7** [comment] 2015-12-29 14:58
UPDATE:
This issue is only appearing when I've also configured cluster-metrics in the openshift-infra project. Otherwise the registry is working fine. Very weird because I don't see a link between the cluster-metrics and a secure docker registry

**Comment by lorenzvth7** [comment] 2015-12-30 10:14
This issue only appears when I'm using a secure registry AND cluster metrics (heapster etc). I don't see the link between this components.

**Comment by smarterclayton** [comment] 2016-01-30 18:50
This is networking

**Comment by smarterclayton** [comment] 2016-01-30 18:51
Might be a docker daemon issue as well.

**Comment by Scyta1e** [comment] 2016-02-17 14:14
I can also reproduce the same issue using origin 1.1.1.1 on RHES 7.1, Docker 1.8.2. Metrics were only enabled on the cluster a few days ago, since then we've been plagued with the "net/http: request canceled while waiting for connection" error. 

Shutting down the metrics related pods instantly fixes the problem. Several other pods that had been cycling in ImagePullBackOff, on their next retry successfully pulled the image and launched without prompting.

Thanks lorenzvth7 for the pointer.

**Comment by pweil-** [comment] 2016-02-17 14:21
Hrm, this is the second item I've seen where shut down of metrics pods is fixing registry issues (other was an email thread). 

@jcantrill

**Comment by lorenzvth7** [comment] 2016-02-17 14:29
@Scyta1e @pweil- 
Tried it again recently. I set up a secure persisitent registry which was working fine. But after enabling cluster-metrics it wasn't possible anymore to push/pull images to the registry until I deleted the metrics-project. After that everything was working fine again.

**Comment by lorenzvth7** [comment] 2016-03-01 12:51
Created a new cluster today with secure registry and cluster metrics enabled. Everything seems to work fine now. Seems to be fixed?

**Comment by kargakis** [comment] 2016-04-04 16:24
Is this still an issue? @pweil- mind reassigning to someone closer to metrics?

**Comment by jcantrill** [comment] 2016-06-03 13:07
@pweil-  when you say "...shut down of metrics pods.." do you mean all the metrics pods?  @mwringe could there be something with heapster that is interfering here?

**Comment by mwringe** [comment] 2016-06-03 13:31
I fail to see how the metrics components could be causing the failure here, especially an error with the repository.

All the metrics components are run as separate containers and do not directly change anything specific to the OpenShift cluster. The only direct connections to the OpenShift cluster would be Heapster connecting to the master and each nodes '/stats' endpoint to gather metrics over REST. The Hawkular Metrics and Cassandra containers only accept metrics from Heapster (also over REST).

If accessing these REST endpoint is causing the issue then there has to be a bug somewhere in the OpenShift/Kubernetes code.

**Comment by pweil-** [comment] 2016-06-06 01:53
@jcantrill @mwringe it certainly could have been coincidence, just seemed odd that two folks reported cluster issues being resolved after removing the metrics components that were installed.  I don't have the email thread handy anymore, it has been too long.

@lorenzvth7 - since it has been a while, are you still able to reproduce this issue?

**Comment by lorenzvth7** [comment] 2016-06-06 18:49
@pweil- It's no issue anymore for me. Just upgrading to a newer OpenShift version (1.1 and later) did the job I think. Don't know if it's necessary but I still chose for a master which is also a node (unschedulable) if I want everything to work fine.

**Closed** 2016-06-06 18:51 UTC
Labels: component/imageregistry, component/networking, priority/P2
