### ISSUE TITLE
osadm registry --create puts it in the current project

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2540] opened 2015-05-27 20:09 UTC
I'm not certain if this is a bug or feature, but I'm leaning toward bug.

If you switch projects before creating a registry with osadm registry, it goes into that project, not default.

I may be wrong, but I don't think you can actually use a registry that's in a project. If I'm wrong and builds/deploys in a project can just start using it as a registry, it's *still* very surprising and confusing and should probably require the admin to be explicit that they want it in the project.

**Comment by liggitt** [comment] 2015-05-27 20:53
the registry always goes in a namespace... question is which one

**Comment by ncdc** [comment] 2015-05-27 20:59
We expect it in `default`

**Comment by liggitt** [comment] 2015-05-27 21:00
I don't like assuming it is in the default namespace. What depends on that?

**Comment by derekwaynecarr** [comment] 2015-05-27 21:00
It's possible we may not have rights to ```default``` in future deployment topologies.  Prefer it to be configurable as well.

**Comment by ncdc** [comment] 2015-05-27 21:10
@liggitt https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master.go#L156-L161

**Comment by liggitt** [comment] 2015-05-27 21:27
When did that go in? We shouldn't be getting that from an environment variable, that should be part of config. While were at it, so should the namespace we expect the registry service to be in, right?

**Comment by ncdc** [comment] 2015-05-27 22:50
@liggitt that's been in there for a long time

**Comment by liggitt** [comment] 2015-05-29 18:21
Related: https://github.com/openshift/origin/issues/2581

**Comment by liggitt** [comment] 2015-05-29 18:30
This is working as designed... registry, router, policy, and other commands use the current project. While there are things that currently assume the default namespace for the registry, that will not always be the case.

**Comment by sosiouxme** [comment] 2015-05-29 19:30
Well then I guess the only "bug" is that the user might have fiddled around with their config before creating the registry and will be surprised if it lands somewhere other than `default`. I wonder if we could just have it provide a nice message indicating whether it is or isn't in the `default` namespace and what that implies?

**Comment by derekwaynecarr** [comment] 2015-05-30 18:45
Since I have done this same thing as well, I agree current behavior can be confusing.  Is there a benefit to ever having more than one registry?   Should the server reject creation of one if not in desired namespace per configuration?

**Comment by smarterclayton** [comment] 2015-08-28 12:44
Yes, there is benefit to having multiple registries - we have people doing that today for running and hosting their own registries *on* openshift.

**Comment by smarterclayton** [comment] 2015-08-28 12:44
There's probably not benefit to running multiple registries in the default auth mode on openshift though.

**Comment by pweil-** [comment] 2016-04-04 16:44
We now have use cases of registries outside the default namespace, closing this as no longer valid.

**Comment by pweil-** [comment] 2016-04-04 16:44
misread, reopening

**Comment by smarterclayton** [comment] 2016-04-04 16:46
I think this is "working as designed".  We need to come back to larger registry config story but I don't think this is the right place for it.

**Closed by smarterclayton** 2016-04-04 16:46 UTC
Labels: area/usability, component/cli, component/imageregistry, kind/bug, priority/P3
