### ISSUE TITLE
Template parameter and project name

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#4609] opened 2015-09-10 08:45 UTC
Hello.

I need to use the project name in some fields of my template and I don't know if is possible to get the project name. For example:

```
parameters:
- name: PROJECT_NAME
    value: metadata.namespace
    description: Project name [required]
```

Thanks.

**Comment by liggitt** [comment] 2015-09-10 14:12
Duplicate of https://github.com/openshift/origin/issues/2778 ?

**Comment by bparees** [comment] 2015-09-30 06:48
I think this is different.  For this the way i think we want to solve it is to introduce generators that can generate values like "my namespace" and also generators that can take json-path expressions, ala the downward api.

**Comment by karelstriegel** [comment] 2016-03-11 07:32
+1

**Comment by tonyturino** [comment] 2017-06-16 19:02
I would find this useful as well

**Comment by bparees** [comment] 2017-06-16 19:10
this was turned into a trello card a while ago (still on our backlog): https://trello.com/c/zcRQFri0

closing this issue in deference to the card.

**Closed by bparees** 2017-06-16 19:10 UTC
Labels: component/composition, kind/enhancement, priority/P3

**Comment by J5Dev** [comment] 2018-06-08 12:11
Having seen the card, I felt I needed to add my support for this, as I am also in need of the ability to do this, for the exact reasons give anove.

Essentially I need to be able to supply env vars that point to certain services etc., such as

```
                 {
                    "name": "DB_HOST",
                    "value": "${DB_SERVICE_NAME}.${PROJECT_NAME}.svc"
                  },
```

This would be really useful to have
