### ISSUE TITLE
oc adm diagnostics

### ISSUE THREAD

**Issue by mangirdaz** [openshift/origin#13741] opened 2017-04-12 18:55 UTC
oc adm diagnostics for OCP Enterprise uses containers from docker.io

In most on-prem installations docker.io are blocked OR not even available.

Network test container should be hosted in RH registry when installing enterprise version.

**Comment by sosiouxme** [comment] 2017-05-25 21:17
I think this is this basically a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1439142
There's an open PR to address it: https://github.com/openshift/origin/pull/14364
Please follow one of those or reopen this if it has a wider scope than that work.

**Closed by sosiouxme** 2017-05-25 21:17 UTC
Labels: component/diagnostics, kind/bug
