### ISSUE TITLE
oc status doesn't show details of deployments

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12790] opened 2017-02-03 04:00 UTC
I swear we fixed this, but maybe we just tolerated it.

```
svc/prometheus (all nodes):30900 -> 9090
  pod/prometheus-3729295909-qd1wb runs prom/prometheus
```

deployment should show up here.

**Comment by juanvallejo** [comment] 2017-02-03 21:06
cc @deads2k

**Comment by smarterclayton** [comment] 2017-02-03 22:36
I may never have added it.

**Comment by kargakis** [comment] 2017-02-04 14:28
@mfojtik

**Comment by deads2k** [comment] 2017-02-06 13:22
> I may never have added it.

We never did.  @mfojtik or @soltysh had a pull for it as I recall.

**Comment by mfojtik** [comment] 2017-02-06 13:24
@deads2k I had (have?) but the problem with this was that there was too much duplication to handle both DeploymentConfig and Deployment (basically you have to copy&paste a large chunks of code). So we postponed it till we refactor how oc status works... 

Do we consider this a blocker for 1.5? I would love to work on this for 1.6 (not sure we have enough time for 1.5)

**Comment by soltysh** [comment] 2017-02-06 17:56
Ref: https://github.com/openshift/origin/pull/10490

**Comment by kargakis** [comment] 2017-09-17 22:43
Dupe of https://github.com/openshift/origin/issues/10411

**Closed by kargakis** 2017-09-17 22:43 UTC
Labels: component/apps, kind/enhancement, priority/P2
