### ISSUE TITLE
Pulling with digest reference failed from v2 registry

### ISSUE THREAD

**Issue by andrew-jones** [openshift/origin#4567] opened 2015-09-08 06:40 UTC
I have two build configs, one building an apache image on centos 7.  The other extending this apache image and installing php.

The apache image builds successfully and I can pull/run the image.  

The PHP Dockerfile contains,  

FROM 172.30.6.174:5000/softint/apache-centos7:latest 

Which is my private repo IP/namespace/image name:tag

My template for the php image builder looks like this,

    {
      "kind": "Template",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "php-dev",
        "creationTimestamp": null,
        "annotations": {
          "description": "Building php dev docker images for softint namespace"
        }
      },
      "objects": [
        {
          "kind": "ImageStream",
          "apiVersion": "v1beta3",
          "metadata": {
            "name": "php-dev",
            "creationTimestamp": null
          },
          "spec": {},
          "status": {
            "dockerImageRepository": ""
          }
        },
        {
          "kind": "ImageStream",
          "apiVersion": "v1beta3",
          "metadata": {
            "name": "apache-centos7",
            "creationTimestamp": null
          },
          "spec": {
            "dockerImageRepository": "172.30.6.174:5000/softint/apache-centos7"
          },
          "status": {
            "dockerImageRepository": ""
          }
        },
        {
          "kind": "BuildConfig",
          "apiVersion": "v1beta3",
          "metadata": {
            "name": "php-dev",
            "creationTimestamp": null,
            "labels": {
              "name": "php-dev"
            }
          },
          "spec": {
            "triggers": [
              {
                "type": "generic",
                "generic": {
                  "secret": "softints build trigger secret"
                }
              },
              {
                "type": "imageChange",
                "imageChange": {}
              },
              {
                "type": "ConfigChange"
              }
            ],
            "source": {
              "type": "Git",
              "git": {
                "uri": "git@bitbucket.org:myorg/docker.git"
              },
              "sourceSecret": {
                "name": "ssh-secret"
              },
              "contextDir": "php/dev"
            },
            "strategy": {
              "type": "Docker",
              "dockerStrategy": {
                "from": {
                  "kind": "ImageStreamTag",
                  "name": "apache-centos7:latest"
                }
              }
            },
            "output": {
              "to": {
                "kind": "ImageStreamTag",
                "name": "php-dev:latest"
              }
            },
            "resources": {}
          },
          "status": {
            "lastVersion": 0
          }
        }
      ],
      "labels": {
        "template": "php-dev-template"
      }
    }

The build kicks off, and almost immediately returns this error,

    [centos@172 ~]# oc logs -f php-dev-1-build
    I0908 06:28:49.151507       1 builder.go:95] Using 'ssh-privatekey' from secret 'ssh-secret'
    Step 0 : FROM 172.30.6.174:5000/softint/apache-centos7@sha256:265c60134148a79616c8cba17ba5411fae11218ed8b38acabce47bc6a5e7ec36
    F0908 06:28:50.810200       1 builder.go:47] Build error: pulling with digest reference failed from v2 registry

I've found a bug reported for Openshift Enterprise, 
https://bugzilla.redhat.com/show_bug.cgi?id=1255502

Also this (though I can't see any content), 
https://access.redhat.com/solutions/1599503

**Comment by andrew-jones** [comment] 2015-09-08 06:44
A question not related to the error, Is this the correct way to access images?  Externally I have a route to the registry, registry.myorg.com.au with auth that I can login to, pull/push too no problem.  I can tag registry.myorg.com.au/softint/php-dev:latest and push that to the registry.  Interally for building I can't seem to access registry.myorg.com.au, I'm guessing I need to authenticate but can't find any documentation on authing to a private docker registry during the build process.  Ideally, I could always use registry.myorg.com.au whether Im internal to OS or external in a dev env.

**Comment by bparees** [comment] 2015-09-09 16:20
here are the docs on how to setup docker credentials:
https://docs.openshift.org/latest/dev_guide/builds.html#using-docker-credentials-for-pushing-and-pulling-images

if your registry requires auth, perhaps that is why the pull is failing?

**Comment by ncdc** [comment] 2015-09-10 15:19
@andrew-jones is 172.30.6.174:5000 the integrated registry you deployed via `oadm registry`?

**Comment by amdonov** [comment] 2015-09-17 20:26
I'm fighting the same thing. Currently running 1.0.5. I'm using the integrated registry deployed via oadm registry. A copy of my failing build is included below. I've set the pullSecret to the value of  the pushSecret. The build fails with the same error as above, "pulling with digest reference failed from v2 registry". The registry complains that it didn't login. When I manually run docker pull to fetch the image and then retrigger the build, it runs successfully and pushes the updated image. Both the source and target image are in the same project. I'm using using the docker secrets that were created for the builder serviceaccount.

```javascript
{
    "kind": "Build",
    "apiVersion": "v1",
    "metadata": {
        "name": "dias-3-4581510590",
        "namespace": "mocks",
        "selfLink": "/oapi/v1/namespaces/mocks/builds/dias-3-4581510590",
        "uid": "5c9a6afb-5d76-11e5-be07-06e5f2bfc187",
        "resourceVersion": "55135",
        "creationTimestamp": "2015-09-17T19:57:44Z",
        "labels": {
            "app": "dias",
            "buildconfig": "dias"
        }
    },
    "spec": {
        "serviceAccount": "builder",
        "source": {
            "type": "Git",
            "git": {
                "uri": "git@gitlab.dpp.gfclab.com:/docker/dias.git"
            },
            "sourceSecret": {
                "name": "gitlabsecret"
            }
        },
        "strategy": {
            "type": "Docker",
            "dockerStrategy": {
                "from": {
                    "kind": "DockerImage",
                    "name": "172.30.63.116:5000/mocks/tomcat6@sha256:39a0ba9e84903070fff0e268a7bd7f389d7b4aa887f67fd875fc725aa8259593"
                },
                "pullSecret": {
                    "name": "builder-dockercfg-1rgjh"
                }
            }
        },
        "output": {
            "to": {
                "kind": "ImageStreamTag",
                "name": "dias:latest"
            },
            "pushSecret": {
                "name": "builder-dockercfg-1rgjh"
            }
        },
        "resources": {}
    },
    "status": {
        "phase": "Failed",
        "startTimestamp": "2015-09-17T19:57:45Z",
        "completionTimestamp": "2015-09-17T19:57:55Z",
        "duration": 10000000000,
        "config": {
            "kind": "BuildConfig",
            "namespace": "mocks",
            "name": "dias"
        }
    }
}
```

**Comment by ncdc** [comment] 2015-09-17 20:29
@amdonov can you `docker pull 172.30.63.116:5000/mocks/tomcat6@sha256:39a0ba9e84903070fff0e268a7bd7f389d7b4aa887f67fd875fc725aa8259593` after you've logged in to the registry?

/cc @miminar

**Comment by amdonov** [comment] 2015-09-17 20:31
Yes, and then the build works. However everytime the upstream image is changed, the downstream build kicks off again and fails until I manually pull it.

**Comment by ncdc** [comment] 2015-09-17 20:32
@amdonov can you paste the logs from the registry container from around the time the build fails to pull?

**Comment by amdonov** [comment] 2015-09-17 20:39
time="2015-09-17T20:39:13Z" level=debug msg="authorizing request" http.request.host="172.30.63.116:5000" http.request.id=84da5094-2181-45dd-86ae-5aef546da00f http.request.method=GET http.request.remoteaddr="10.1.1.1:60625" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
time="2015-09-17T20:39:13Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="172.30.63.116:5000" http.request.id=84da5094-2181-45dd-86ae-5aef546da00f http.request.method=GET http.request.remoteaddr="10.1.1.1:60625" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
10.1.1.1 - - [17/Sep/2015:20:39:13 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
time="2015-09-17T20:39:13Z" level=info msg="response completed" http.request.host="172.30.63.116:5000" http.request.id=84da5094-2181-45dd-86ae-5aef546da00f http.request.method=GET http.request.remoteaddr="10.1.1.1:60625" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.599588ms http.response.written=0 instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
time="2015-09-17T20:39:13Z" level=debug msg="authorizing request" http.request.host="172.30.63.116:5000" http.request.id=88786de2-eabd-4798-a161-fbf7c9513864 http.request.method=GET http.request.remoteaddr="10.1.1.1:60631" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
time="2015-09-17T20:39:13Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="172.30.63.116:5000" http.request.id=88786de2-eabd-4798-a161-fbf7c9513864 http.request.method=GET http.request.remoteaddr="10.1.1.1:60631" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
time="2015-09-17T20:39:13Z" level=info msg="response completed" http.request.host="172.30.63.116:5000" http.request.id=88786de2-eabd-4798-a161-fbf7c9513864 http.request.method=GET http.request.remoteaddr="10.1.1.1:60631" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.455708ms http.response.written=0 instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
10.1.1.1 - - [17/Sep/2015:20:39:13 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
time="2015-09-17T20:39:13Z" level=debug msg="authorizing request" http.request.host="172.30.63.116:5000" http.request.id=3565aa6c-5017-44d3-bbe0-0bed773b8393 http.request.method=GET http.request.remoteaddr="10.1.1.1:60633" http.request.uri="/v2/mocks/tomcat6/manifests/sha256:89e5ac2ee9034a7f913d41b1ba4bdc8749cf26f5159e568a0d63a5f051ffe40a" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 vars.name="mocks/tomcat6" vars.reference="sha256:89e5ac2ee9034a7f913d41b1ba4bdc8749cf26f5159e568a0d63a5f051ffe40a" 
time="2015-09-17T20:39:13Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="172.30.63.116:5000" http.request.id=3565aa6c-5017-44d3-bbe0-0bed773b8393 http.request.method=GET http.request.remoteaddr="10.1.1.1:60633" http.request.uri="/v2/mocks/tomcat6/manifests/sha256:89e5ac2ee9034a7f913d41b1ba4bdc8749cf26f5159e568a0d63a5f051ffe40a" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 vars.name="mocks/tomcat6" vars.reference="sha256:89e5ac2ee9034a7f913d41b1ba4bdc8749cf26f5159e568a0d63a5f051ffe40a" 
time="2015-09-17T20:39:13Z" level=info msg="response completed" http.request.host="172.30.63.116:5000" http.request.id=3565aa6c-5017-44d3-bbe0-0bed773b8393 http.request.method=GET http.request.remoteaddr="10.1.1.1:60633" http.request.uri="/v2/mocks/tomcat6/manifests/sha256:89e5ac2ee9034a7f913d41b1ba4bdc8749cf26f5159e568a0d63a5f051ffe40a" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.52698ms http.response.written=0 instance.id=8a7a5963-0d65-434c-bcad-c876a166d333 
10.1.1.1 - - [17/Sep/2015:20:39:13 +0000] "GET /v2/mocks/tomcat6/manifests/sha256:89e5ac2ee9034a7f913d41b1ba4bdc8749cf26f5159e568a0d63a5f051ffe40a HTTP/1.1" 401 172 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"

**Comment by ncdc** [comment] 2015-09-17 20:43
Ok, it's not using the secret, so the registry is returning 401 unauthorized.

@mfojtik @bparees do you have to do anything special to get the Docker build strategy to use pull secrets?

**Comment by bparees** [comment] 2015-09-17 20:44
@ncdc nope, as long as the secret exists on the service account the build will use it.

**Comment by ncdc** [comment] 2015-09-17 20:50
@bparees I dunno what's going on, then. This doesn't appear to be a registry issue. It looks like the secret isn't being used.

**Comment by mfojtik** [comment] 2015-09-17 20:55
if you add the private registry image to FROM in docker build and then
build it... I dont think the host docker have proper pull secrets.

**Comment by bparees** [comment] 2015-09-17 20:58
the logical conclusion would be that we're not finding a secret on the service account for the pull repository.

can you dump the secrets from your builder service account?

```$ oc get serviceaccount builder -o json```
```$ oc describe secret  <secret from above>```  ?  what we care about is the ip address in the values.

@mfojtik the builder has a From definition in it, that is what we should be using for the pull secret and substituting into the dockerfile.  if we aren't doing that, it's a bug in how we handle docker builds.

**Comment by bparees** [comment] 2015-09-17 21:04
@mfojtik https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L372-L374

**Comment by liggitt** [comment] 2015-09-17 21:15
There's been enough difficulty debugging this sort of issue that we should probably add better logging around the auto selection of pull secrets (at some verbosity level)

**Comment by bparees** [comment] 2015-09-17 21:19
@liggitt there are some: https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L506

**Comment by ncdc** [comment] 2015-09-17 23:12
@csrwng could this have something to do with the go-dockerclient auth config changes recently?

**Comment by csrwng** [comment] 2015-09-18 00:58
Yes this looks like the same issue, which should be fixed in master. One thing to note when debugging these issues is that docker pull is not the same as docker build because the format of the auth header is different. For pull only the relevant credentials are passed in, while for build, the entire map of credentials is passed.

**Comment by amdonov** [comment] 2015-09-18 01:01
Could you point to the relevant files/commits? I'd like to patch my install if possible.

**Comment by amdonov** [comment] 2015-09-18 01:22
Should I just update the go-dockerclien dependencyt?

**Comment by liggitt** [comment] 2015-09-18 01:23
https://github.com/openshift/origin/pull/4535/commits Was where origin got updated

**Comment by csrwng** [comment] 2015-09-18 01:43
The changes are originally here
https://github.com/fsouza/go-dockerclient/pull/365
And they were merged in origin here (along with other changes) 
https://github.com/openshift/origin/pull/4535

**Comment by amdonov** [comment] 2015-09-18 13:08
Thanks for the help. I upgraded to 1.0.6, and it fixed the problem.

**Comment by deanpeterson** [comment] 2015-09-21 20:21
I just ran into this too.  I am running a binary I built from source a week ago.  Do I need to upgrade to 1.0.6 too already?  This is the output of the docker registry log I am seeing: 

time="2015-09-21T19:58:29Z" level=debug msg="authorizing request" http.request.host="172.30.131.51:5000" http.request.id=94bd0dc2-aee3-42f9-916c-bc97ebdf64da http.request.method=GET http.request.remoteaddr="172.17.42.1:46916" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
172.17.42.1 - - [21/Sep/2015:19:58:29 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
time="2015-09-21T19:58:29Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="172.30.131.51:5000" http.request.id=94bd0dc2-aee3-42f9-916c-bc97ebdf64da http.request.method=GET http.request.remoteaddr="172.17.42.1:46916" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
time="2015-09-21T19:58:29Z" level=info msg="response completed" http.request.host="172.30.131.51:5000" http.request.id=94bd0dc2-aee3-42f9-916c-bc97ebdf64da http.request.method=GET http.request.remoteaddr="172.17.42.1:46916" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.217783ms http.response.written=0 instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
time="2015-09-21T19:58:29Z" level=debug msg="authorizing request" http.request.host="172.30.131.51:5000" http.request.id=69cc7d0a-e86d-4fef-bac0-304aea435f74 http.request.method=GET http.request.remoteaddr="172.17.42.1:46922" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
time="2015-09-21T19:58:29Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="172.30.131.51:5000" http.request.id=69cc7d0a-e86d-4fef-bac0-304aea435f74 http.request.method=GET http.request.remoteaddr="172.17.42.1:46922" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
time="2015-09-21T19:58:29Z" level=info msg="response completed" http.request.host="172.30.131.51:5000" http.request.id=69cc7d0a-e86d-4fef-bac0-304aea435f74 http.request.method=GET http.request.remoteaddr="172.17.42.1:46922" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.337315ms http.response.written=0 instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
172.17.42.1 - - [21/Sep/2015:19:58:29 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
time="2015-09-21T19:58:29Z" level=debug msg="authorizing request" http.request.host="172.30.131.51:5000" http.request.id=d9598634-2f6d-465a-a6fb-663c8f5dae71 http.request.method=GET http.request.remoteaddr="172.17.42.1:46924" http.request.uri="/v2/test/wildfly-jdk-8/manifests/sha256:cdc90bd3da840e2930d75cb694262ef5cfb23577e95c06fb0e7bded864d97bc6" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 vars.name="test/wildfly-jdk-8" vars.reference="sha256:cdc90bd3da840e2930d75cb694262ef5cfb23577e95c06fb0e7bded864d97bc6" 
time="2015-09-21T19:58:29Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="172.30.131.51:5000" http.request.id=d9598634-2f6d-465a-a6fb-663c8f5dae71 http.request.method=GET http.request.remoteaddr="172.17.42.1:46924" http.request.uri="/v2/test/wildfly-jdk-8/manifests/sha256:cdc90bd3da840e2930d75cb694262ef5cfb23577e95c06fb0e7bded864d97bc6" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 vars.name="test/wildfly-jdk-8" vars.reference="sha256:cdc90bd3da840e2930d75cb694262ef5cfb23577e95c06fb0e7bded864d97bc6" 
time="2015-09-21T19:58:29Z" level=info msg="response completed" http.request.host="172.30.131.51:5000" http.request.id=d9598634-2f6d-465a-a6fb-663c8f5dae71 http.request.method=GET http.request.remoteaddr="172.17.42.1:46924" http.request.uri="/v2/test/wildfly-jdk-8/manifests/sha256:cdc90bd3da840e2930d75cb694262ef5cfb23577e95c06fb0e7bded864d97bc6" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.728438ms http.response.written=0 instance.id=f759ce2a-f7b1-481f-95c8-a426432b21a0 
172.17.42.1 - - [21/Sep/2015:19:58:29 +0000] "GET /v2/test/wildfly-jdk-8/manifests/sha256:cdc90bd3da840e2930d75cb694262ef5cfb23577e95c06fb0e7bded864d97bc6 HTTP/1.1" 401 177 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"

**Comment by ncdc** [comment] 2015-09-21 20:24
@deanpeterson yes, if you're hitting the same issue/root cause.

**Comment by deanpeterson** [comment] 2015-09-21 20:56
The fix went into the master branch 17 days ago, yet I built from the master only 7 days ago and I am having this problem.

**Comment by deanpeterson** [comment] 2015-09-21 21:38
Well, that worked.  I downloaded the latest 1.0.6 binary and I am able to pull from the registry.

**Closed** 2015-10-16 18:19 UTC
Labels: component/imageregistry, priority/P2
