### ISSUE TITLE
[cluster-up] Timeout during provisioning of service catalog via cluster up too low

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#15875] opened 2017-08-20 09:21 UTC
Related to Minishift. See also https://github.com/minishift/minishift/issues/1252

**Comment by bparees** [comment] 2017-08-22 22:11
so again before bumping this blindly, can we gather some data from your env?  from the other issue:

Sure, so to get back on track have we gotten to the bottom of what is taking 10 mins your env? Again i'm happy to bump the timeout but i'd feel better first knowing if the issue is that the image was being pulled, or something else was blocking it from coming up? The 10 minute poll is looking for the "apiserver" deployment in the "service-catalog" namespace to have an available replica.

The deployment is pretty simple, so i'm surprised if the pod actually started running immediately, that it would take 10 mins to become available. Seems more likely something is stuck elsewhere. You should be able to "oc login" to the cluster as sys admin even while you're in that polling loop, and poke around at the deployment/pod. Doing it with logging+metrics might be best since that sounds like your easiest path to a recreate.

**Comment by shortsteps** [comment] 2017-08-31 14:22
I had the same issue on Ubuntu 14.04 - i7 8GB RAM with Minishift v.1.5.0, KVM and B2D iso. 
On my side it was a resource issue, increasing RAM and cpu dedicated to minishift the cluster successfully started (`minishift config set memory 6144 / minishift config set cpus 4`).

Here you are a report of my tests (while testing, only Skype and Firefox with a few windows opened were running).

`time MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --service-catalog --extra-clusterup-flags "--loglevel 10"`

**Test1**: default parameters (2GB RAM - 2vcpu) ---> time: 14mins FAILED
`I0831 15:54:16.763234   12591 round_trippers.go:405] POST https://192.168.42.81:8443/apis/servicecatalog.k8s.io/v1alpha1/brokers 504 Gateway Timeout in 30550 milliseconds
I0831 15:54:16.763298   12591 round_trippers.go:411] Response Headers:
I0831 15:54:16.763324   12591 round_trippers.go:414]     Cache-Control: no-store
I0831 15:54:16.763350   12591 round_trippers.go:414]     Content-Type: application/json
I0831 15:54:16.763371   12591 round_trippers.go:414]     Date: Thu, 31 Aug 2017 13:54:16 GMT
I0831 15:54:16.763391   12591 round_trippers.go:414]     Content-Length: 182
I0831 15:54:16.764410   12591 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within allowed duration","reason":"Timeout","details":{},"code":504}
I0831 15:54:16.764756   12591 servicecatalog.go:184] retrying registration after error Timeout: request did not complete within allowed duration
FAIL
   Error: failed to register broker with service catalog: timed out waiting for the condition
Error during 'cluster up' execution: Error starting the cluster.`

**Test2**: 4GB RAM - 2vcpu ---> time: 12mins FAILED (same error log)

**Test3**: 6GB RAM - 4vcpu ---> time: 8mins SUCCESSFUL 

Hope it can help!

**Comment by bparees** [comment] 2017-08-31 16:25
https://github.com/openshift/origin/pull/16069 makes some improvements in the TSB/SC startup logic that appears to have sped it up for me.  I'm going to close this issue w/ that PR but if you're still seeing issues after you pick it up, feel free to re-open.

**Closed** 2017-09-01 05:14 UTC
Labels: component/cluster-up, kind/bug, priority/P2
