### ISSUE TITLE
"Failed to pull image": if image trigger is set to "automatic: false", or image trigger doesn't exist.

### ISSUE THREAD

**Issue by livelace** [openshift/origin#8339] opened 2016-04-04 08:23 UTC
Subject. 

##### Version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

Configuration 1:

    triggers:
      - 
        type: "ConfigChange"
      - 
        type: "ImageChange"
        imageChangeParams:
          automatic: false
          containerNames:
            - "drweb-netcheck-nossl"
          from:
            kind: "ImageStreamTag"
            name: "testing-drweb-dss-ubuntu:11.0"

Configuration 2:

    triggers:
      - 
        type: "ConfigChange"

##### Current Result

11:21:47 AM	Warning	Failed 	Failed to pull image "testing-drweb-dss-ubuntu:11.0": Error: image library/testing-drweb-dss-ubuntu:11.0 not found
3 times in the last minute
11:21:44 AM	Normal	Pulling 	pulling image "testing-drweb-dss-ubuntu:11.0"
3 times in the last minute
11:21:31 AM	Normal	Back off 	Back-off pulling image "testing-drweb-dss-ubuntu:11.0"
2 times in the last minute
11:21:31 AM	Warning	Failed sync 	Error syncing pod, skipping: failed to "StartContainer" for "drweb-netcheck-nossl" with ImagePullBackOff: "Back-off pulling image \"testing-drweb-dss-ubuntu:11.0\""
2 times in the last minute
11:21:19 AM	Warning	Failed sync 	Error syncing pod, skipping: failed to "StartContainer" for "drweb-netcheck-nossl" with ErrImagePull: "Error: image library/testing-drweb-dss-ubuntu:11.0 not found"
2 times in the last minute
11:20:55 AM	Normal	Scheduled 	Successfully assigned testing-11.0-drweb-netcheck-nossl-1-k97ki to openshift-node1.i.drweb.ru

##### Expected Result

11:22:58 AM	Normal	Started 	Started container with docker id 84701fa7c191
11:22:57 AM	Normal	Created 	Created container with docker id 84701fa7c191
11:22:54 AM	Normal	Pulled 	Container image "172.30.208.158:5000/images/testing-drweb-dss-ubuntu@sha256:a8e3be0acaaf6076bda33a837b9eb8cb45c0bbd6f7f88d0ca40fe3309a061159" already present on machine
11:22:51 AM	Normal	Scheduled 	Successfully assigned testing-11.0-drweb-netcheck-nossl-1-f00kb to openshift-node1.i.drweb.ru

**Comment by soltysh** [comment] 2016-04-04 10:12
There's a fix in flight here: https://github.com/openshift/origin/pull/7439

**Comment by livelace** [comment] 2016-04-04 11:27
Ooh!  It's difficult for my understanding. I want simple thing :)

1. Have a DC with completely manual control. Containers should use ImageStreamTag. It's all.

**Comment by kargakis** [comment] 2016-04-04 16:11
@pweil- this is actually a dupe of https://github.com/openshift/origin/issues/6934

Assign that to me and close this issue.

**Comment by pweil-** [comment] 2016-04-04 16:30
assigned and updated priority to match this one.  Closing as dupe.

**Closed by pweil-** 2016-04-04 16:30 UTC
Labels: component/deployments, priority/P2
