### ISSUE TITLE
github.com/openshift/origin/test/cmd/idle/all.test/cmd/idle.sh:34: executing 'oc get pod -l app=idling-echo -o go-template='{{ len .items }}'' expecting any result and text '2'; re-trying every 0.2s until completion or 60.000s

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11875] opened 2016-11-10 18:36 UTC
```
FAILURE after 60.097s: test/cmd/idle.sh:34: executing 'oc get pod -l app=idling-echo -o go-template='{{ len .items }}'' expecting any result and text '2'; re-trying every 0.2s until completion or 60.000s: the command timed out
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/8444/consoleFull#-200691091856c25df4e4b05b79524e5d52

**Comment by knobunc** [comment] 2016-11-10 20:57
Dupe of https://github.com/openshift/origin/issues/10487

**Closed by knobunc** 2016-11-10 20:57 UTC
Labels: component/routing, kind/test-flake, priority/P1
