### ISSUE TITLE
Websocket failure when watching rolebindings, incorrect response code

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#10898] opened 2016-09-14 01:15 UTC
When attempting to watch `rolebindings`, the server responds with an incorrect response code when switching protocols:
```
ws.js:39 WebSocket connection to 'wss://10.245.2.2:8443/oapi/v1/namespaces/my-project/rolebindings?watch=true&access_token=<token>' failed: Error during WebSocket handshake: Unexpected response code: 200
```
The code should be `101` to signal the protocol change from `http` to `ws`.  

FWIW, I was initially watching `policybindings`, which do respond correctly with the `101`.

@jwforres 
@enj @liggitt @deads2k

**Comment by liggitt** [comment] 2016-09-14 01:17
Dupe of https://github.com/openshift/origin/issues/8518

**Closed by liggitt** 2016-09-14 01:17 UTC

**Comment by benjaminapetersen** [comment] 2016-09-14 01:29
Ah, good catch.
