### ISSUE TITLE
Flake: timeout of pkg/cmd/server/admin unit tests

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#8150] opened 2016-03-18 20:31 UTC
Unit tests for `pkg/cmd/server/admin` sometimes timeout:

```
panic: test timed out after 1m0s

goroutine 43 [running]:
testing.func·008()
	/usr/lib/golang/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive]:
testing.RunTests(0x19b5d60, 0x2052260, 0x2, 0x2, 0xc208057f01)
	/usr/lib/golang/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208175720, 0x2a085e0)
	/usr/lib/golang/src/testing/testing.go:485 +0xe1
main.main()
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_testmain.go:126 +0x382

goroutine 9 [syscall, 1 minutes]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x43

goroutine 42 [runnable]:
math/big.nat.norm(0xc208040c80, 0x11, 0x25, 0xc208105c20, 0x21, 0x24)
	/usr/lib/golang/src/math/big/nat.go:61
math/big.nat.divLarge(0xc208040c80, 0x10, 0x25, 0xc208105c20, 0x21, 0x24, 0xc208440c60, 0x20, 0x24, 0xc2083c2000, ...)
	/usr/lib/golang/src/math/big/nat.go:594 +0xfa0
math/big.nat.div(0xc208040c80, 0x10, 0x25, 0xc208105c20, 0x20, 0x24, 0xc208440c60, 0x20, 0x24, 0xc2083c2000, ...)
	/usr/lib/golang/src/math/big/nat.go:519 +0x3cc
math/big.nat.expNNWindowed(0xc208440c60, 0x20, 0x24, 0xc20846a1e0, 0x10, 0x14, 0xc20846a0a0, 0x10, 0x14, 0xc2083c2000, ...)
	/usr/lib/golang/src/math/big/nat.go:1351 +0xc97
math/big.nat.expNN(0xc208105c20, 0x10, 0x24, 0xc20846a1e0, 0x10, 0x14, 0xc20846a0a0, 0x10, 0x14, 0xc2083c2000, ...)
	/usr/lib/golang/src/math/big/nat.go:1260 +0x4f1
math/big.nat.probablyPrime(0xc2083c2000, 0x10, 0x14, 0x14, 0x5)
	/usr/lib/golang/src/math/big/nat.go:1445 +0x9d4
math/big.(*Int).ProbablyPrime(0xc208452020, 0x14, 0xc20800a680)
	/usr/lib/golang/src/math/big/int.go:741 +0x7c
crypto/rand.Prime(0x7f1888113678, 0xc20803cd20, 0x400, 0xc208452020, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rand/util.go:99 +0x654
crypto/rsa.GenerateMultiPrimeKey(0x7f1888113678, 0xc20803cd20, 0x2, 0x800, 0xc208292000, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:187 +0x2c9
crypto/rsa.GenerateKey(0x7f1888113678, 0xc20803cd20, 0x800, 0xc2081d0ea0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:145 +0x65
github.com/openshift/origin/pkg/cmd/server/crypto.NewKeyPair(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:338 +0xa6
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).MakeServerCert(0xc20816d140, 0xc2083bd6e0, 0x29, 0xc2083bd740, 0x29, 0xc20816c090, 0x7f1888124f28, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:251 +0x22d
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).EnsureServerCert(0xc20816d140, 0xc2083bd6e0, 0x29, 0xc2083bd740, 0x29, 0xc20816c090, 0x46d08c, 0x4ad4a0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:223 +0xe5
github.com/openshift/origin/pkg/cmd/server/admin.CreateServerCertOptions.CreateServerCert(0xc2083b7bc0, 0xc2083bd6e0, 0x29, 0xc2083bd740, 0x29, 0xc2081d1980, 0x1, 0x1, 0x0, 0x7f1888112400, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_servercert.go:143 +0x756
github.com/openshift/origin/pkg/cmd/server/admin.CreateNodeConfigOptions.MakeServerCert(0xc2083b7bc0, 0xc2083bd11b, 0x1e, 0x1668377, 0x7, 0xc2081d1980, 0x1, 0x1, 0x17146b0, 0x17, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:386 +0x235
github.com/openshift/origin/pkg/cmd/server/admin.CreateNodeConfigOptions.CreateNodeFolder(0xc2083b7bc0, 0xc2083bd11b, 0x1e, 0x1668377, 0x7, 0xc2081d1980, 0x1, 0x1, 0x17146b0, 0x17, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:285 +0x62a
github.com/openshift/origin/pkg/cmd/server/admin.func·014(0xc20817a200, 0xc208438990, 0x0, 0x9)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:73 +0x221
github.com/spf13/cobra.(*Command).execute(0xc20817a200, 0xc2084387e0, 0x9, 0x9, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0xb41
github.com/spf13/cobra.(*Command).ExecuteC(0xc20817a000, 0xc20817a200, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x635
github.com/spf13/cobra.(*Command).Execute(0xc20817a000, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x48
github.com/openshift/origin/pkg/cmd/server/admin.executeNodeConfig(0xc2084d7e58, 0x8, 0x8, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:107 +0x721
github.com/openshift/origin/pkg/cmd/server/admin.TestNodeConfigTLS(0xc2083f1440)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:45 +0x402
testing.tRunner(0xc2083f1440, 0x2052278)
	/usr/lib/golang/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:555 +0xd4e

goroutine 25 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x29fc700)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x99
created by github.com/golang/glog.init·1
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ca

goroutine 33 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
FAIL	github.com/openshift/origin/pkg/cmd/server/admin	60.505s
```

**Comment by liggitt** [comment] 2016-03-18 21:25
dupe of https://github.com/openshift/origin/issues/6801

**Closed** 2016-03-18 21:26 UTC
