### ISSUE TITLE
oc cluster up  cannot access master

### ISSUE THREAD

**Issue by steven166** [openshift/origin#12928] opened 2017-02-11 14:43 UTC
Setup oc cluster up on windows 10 with Docker for windows fails:
**Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://10.0.75.2:8443/healthz/ready**
When checking manually the the URL https://10.0.75.2:8443/healthz/ready, it returns 'ok'

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth
Unable to connect to the server: x509: certificate has expired or is not yet valid

##### Steps To Reproduce
1. Reset docker to factory default
2. add 172.30.0.0/16 to insecure registries
3. oc cluster up

##### Current Result
After the setup fails, the cluster seems to be up and the endpoint https://10.0.75.2:8443/healthz/ready returns 'ok'. But cannot login as system:admin (``oc login -u system:admin``) and templates are missing.
**setup output**
```
C:\Users\steve>oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 10.0.75.2 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://10.0.75.2:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0211 15:33:52.858235    4707 ensure.go:209] Created default security context constraint restricted
     I0211 15:33:52.859878    4707 ensure.go:209] Created default security context constraint anyuid
     I0211 15:33:52.862619    4707 ensure.go:209] Created default security context constraint hostnetwork
     I0211 15:33:53.234694    4707 trace.go:61] Trace "Create /oapi/v1/namespaces/default/rolebindings" (started 2017-02-11 15:33:52.8734095 +0000 UTC):
     [9.3µs] [9.3µs] About to convert to expected version
     [24.4µs] [15.1µs] Conversion done
     [355.8675ms] [355.8431ms] About to store object in database
     [361.1837ms] [5.3162ms] Object stored in database
     [361.2225ms] [38.8µs] Self-link added
     [361.2575ms] [35µs] END
```

##### Expected Result
Should be able to login as system:admin (``oc login -u system:admin``) and default templates should be there

##### Additional Information
```
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at 'C:\Users\steve/.kube/config'
[Note] Could not configure a client, so client diagnostics are limited to testing configuration and connection
[Note] Could not configure a client with cluster-admin permissions for the current server, so cluster diagnostics will be skipped

[Note] Running diagnostic: ConfigContexts[rob2/192-168-252-210:8443/admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'rob2/192-168-252-210:8443/admin':
       The server URL is 'https://192.168.252.210:8443'
       The user authentication is 'admin/192-168-252-210:8443'
       The current project is 'rob2'
       (*url.Error) Get https://192.168.252.210:8443/api: dial tcp 192.168.252.210:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

[Note] Running diagnostic: ConfigContexts[maxxton2/10-0-75-2:8443/admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'maxxton2/10-0-75-2:8443/admin':
       The server URL is 'https://10.0.75.2:8443'
       The user authentication is 'admin/10-0-75-2:8443'
       The current project is 'maxxton2'
       (*url.Error) Get https://10.0.75.2:8443/api: x509: certificate has expired or is not yet valid
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

[Note] Running diagnostic: ConfigContexts[openshift/10-0-75-2:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       The current client config context is 'openshift/10-0-75-2:8443/system:admin':
       The server URL is 'https://10.0.75.2:8443'
       The user authentication is 'system:admin/10-0-75-2:8443'
       The current project is 'openshift'
       (*url.Error) Get https://10.0.75.2:8443/api: x509: certificate has expired or is not yet valid
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

[Note] Running diagnostic: ConfigContexts[myproject/10-0-75-2:8443/developer]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'myproject/10-0-75-2:8443/developer':
       The server URL is 'https://10.0.75.2:8443'
       The user authentication is 'developer/10-0-75-2:8443'
       The current project is 'myproject'
       (*url.Error) Get https://10.0.75.2:8443/api: x509: certificate has expired or is not yet valid
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

[Note] Summary of diagnostics execution (version v1.4.1+3f9807a):
[Note] Errors seen: 5
```

**Comment by jorgemoralespou** [comment] 2017-02-16 09:20
@csrwng This happened to me today as well. I've been starting stoping clusters with no problems, and haven't changed anything in my wrapper. It's a fresh cluster.

![image](https://cloud.githubusercontent.com/assets/78350/23014975/73d2bf3c-f431-11e6-80b1-a05e2c4c7167.png)

**Comment by csrwng** [comment] 2017-02-21 18:18
@steven166 @jorgemoralespou it's possible that we're not waiting long enough for the master healthz endpoint to be ready and we're just timing out. Nothing in the last 10 lines of the log indicates that something went wrong.

We can try increasing the timeout and see if that resolves the issue.

**Comment by jorgemoralespou** [comment] 2017-02-21 21:33
@csrwng what is strange is that it had never happened to me before, but now suddenly happened twice. I tried again, and it worked.
Maybe have a retry instead of increasing the timeout, with an exponential backoff.

**Comment by csrwng** [comment] 2017-02-26 16:04
https://github.com/openshift/origin/pull/13112 fixes an issue where the real cause was not getting reported. So hopefully after that merges, we should be able to diagnose this better.

**Comment by bparees** [comment] 2017-06-27 17:52
@jorgemoralespou @steven166 can you reproduce this with the 3.6.0-alpha2 release now that https://github.com/openshift/origin/pull/13112 has merged and see if we can get some additional error information?

**Comment by steven166** [comment] 2017-06-27 18:38
Seems like I'm running into a different problem now. When I run oc cluster up, it tels me that it cannot communicate with Docker and it suggests to create a new machine. So when I run oc cluster up --create-machine it tells me that the following command fails:
```docker-machine.exe create --driver virtualbox --virtualbox-cpu-count 2 --virtualbox-memory 2048 --engine-insecure-registry 172.30.0.0/16 openshift```

So it seems like it wants to use virtualbox instead of hyperv. Is this a known issue?

**Comment by csrwng** [comment] 2017-06-27 18:43
@steven166 cluster up will only use the virtualbox driver when creating a docker machine. However, you can create one yourself with hyperv, then setup its environment `eval $(docker-machine env [name])`, and invoke cluster up.

**Comment by csrwng** [comment] 2017-06-27 18:44
Also if you have an existing docker machine, the fix may just be to setup the environment with `eval` as I mentioned above, such that `docker ps` works, then invoke cluster up.

**Comment by jorgemoralespou** [comment] 2017-06-27 19:38
@csrwng it happened very seldomly, so I'm in favour of closing it and I'll report again if it happens with newer clients.

**Closed** 2017-06-27 19:47 UTC
Labels: component/cluster-up, kind/question, priority/P3

**Comment by kennedyalexander** [comment] 2018-11-07 13:02
If you are coming across this again I was having exactly the same issue and found it was caused by my no-proxy config.  
This is the command I ran for powershell:
$env:no_proxy="$env:no_proxy,127.0.0.1"
Adding the Ip addresses that are uncontactable to my no-proxy list with this command fixed the issue.
