### ISSUE TITLE
Updating Secret Doesn't Kick of Deployment

### ISSUE THREAD

**Issue by bobbydeveaux** [openshift/origin#15472] opened 2017-07-26 12:45 UTC
When updating a secret using the `oc env` CLI - a new deployment is not fired off. When using `oc env` to update any other non-secret, a deployment *is* fired off.

##### Version
oc v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
Works:
If API_PASSWORD is not set, then this will trigger a new deployment
$ echo -n "password1" > password.txt
$ oc env dc/fe  --prefix=API_ --from=secret/api-password

Scenario1 doesn’t work:

If API_PASSWORD already exists, and I update the secret like so:
$ echo -n "password2" > password.txt
$ oc delete secret api-password 
$ oc secret new api-password password=password.txt

… and then call this:
$ oc env dc/fe  --prefix=API_ --from=secret/api-password

I get:
deploymentconfig "fe” updated

BUT - it didn’t create a new deployment.

Scenario2 does work:

If I do this:
$ oc delete secret api-password 
$ echo -n "password2" > password.txt
$ oc secret new api-password password=password.txt

# yuk
$ oc env dc/fe API_PASSWORD=temp

$ oc env dc/fe  --prefix=API_ --from=secret/api-password

This fires off 2 new deployments. One with the incorrect password of ‘temp’, and then another with the new correct password.

Surely, Scenario 1 should fire a new build? I’ve even tried with the `--overwrite=true` to ‘force’ it, but that made no difference.

##### Current Result
Scenario1 doesn't work

##### Expected Result
Scenario1 should work

**Comment by pweil-** [comment] 2017-07-26 19:14
cc @tnozicka

**Comment by mfojtik** [comment] 2017-07-27 08:25
@bobbydeveaux it seems like your are only updating the secret content (even if you re-create the secret with different content)... DC does not track the content of secrets so I guess instead of setting env env again, you should just call `oc rollout latest`

**Comment by wanghaoran1988** [comment] 2017-07-28 09:10
DC support configChange trigger and imageChange trigger, configChange means you change the spec of DC, changing the secrets are not a config change, it's not a bug in my mind, will close this, fell free to reopen if you have other things do discuss.

**Closed** 2017-07-28 09:10 UTC
Labels: component/cli, kind/bug, priority/P2
