### ISSUE TITLE
The '%2F' character in the source url in web console

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7175] opened 2016-02-10 12:24 UTC
![screen shot 2016-02-10 at 13 23 27](https://cloud.githubusercontent.com/assets/44136/12947125/99a53968-cff9-11e5-86c7-9ffa4d232de8.png)

This happens when I have build config with context dir and the branch other than master.

**Comment by mfojtik** [comment] 2016-02-10 12:25
@jhadvig @jwforres FYI

**Comment by jwforres** [comment] 2016-02-10 12:54
It's probably calling encodeURIComponent and encoding the slashes in the path, it still should call encode but then replace all the %2F with / again so you still maintain the path segments.

**Comment by liggitt** [comment] 2016-02-10 13:00
I'm not sure about encoding/replacing. Is it already supposed to be a valid URL subpath?

**Comment by liggitt** [comment] 2016-02-10 13:49
ah, it's just a directory, so it could have spaces... I think I've convinced myself that encode + replace %2F will work

**Comment by jwforres** [comment] 2016-02-11 14:37
bumping the priority up cause i'm betting these URLs are broken as is

**Comment by mfojtik** [comment] 2016-02-11 15:27
@jwforres they are not, or at least the browser can translate that character to '/' somehow ;-) It just looks ugly in console...

**Comment by jwforres** [comment] 2016-02-12 17:07
i cant recreate this with Source type or Docker type, if i specify a context dir and a ref i'm never getting the %2F and the code was already written to unencode those slashes.  @mfojtik can you export the BC you were using when you got this

**Comment by jhadvig** [comment] 2016-02-15 10:58
I've tried to reproduce this issue but without luck. Updated the `ruby-sample-build` BC with context dir  `test/dir` and the rendered link was correct.
![screenshot-18](https://cloud.githubusercontent.com/assets/1668218/13046812/51f95866-d3db-11e5-9a6b-2723cc64d011.png)

**Comment by jwforres** [comment] 2016-02-15 16:50
@mfojtik closing since we cant recreate this, if you see it again please export your BC

**Closed by jwforres** 2016-02-15 16:50 UTC
Labels: area/usability, component/web, kind/bug, priority/P2
