### ISSUE TITLE
oc status should indicate when imagestreams can't be imported

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5078] opened 2015-10-12 14:13 UTC
When an image stream import fails, oc status should let you know that its failed.  See the imagestream output here.

```
[root@cloud-enablement ~]# oc get is -o yaml -n openshift
apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: the repository "jboss-amq-6/amq62-openshift"
        was not found
    creationTimestamp: 2015-10-12T13:53:49Z
    name: jboss-amq-62
    namespace: openshift
    resourceVersion: "157375"
    selfLink: /oapi/v1/namespaces/openshift/imagestreams/jboss-amq-62
    uid: aa42bc58-70e8-11e5-912a-080027e21316
  spec:
    dockerImageRepository: registry.access.redhat.com/jboss-amq-6/amq62-openshift
    tags:
    - annotations:
        description: JBoss A-MQ 6.2 broker image.
        iconClass: icon-jboss
        supports: amq:6.2,messaging,xpaas:1.1
        tags: messaging,amq,jboss,xpaas
        version: "1.1"
      name: "1.1"
  status:
    dockerImageRepository: registry.access.redhat.com/jboss-amq-6/amq62-openshift
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: the repository "jboss-eap-6/eap64-openshift"
        was not found
    creationTimestamp: 2015-10-12T13:53:49Z
    name: jboss-eap64-openshift
    namespace: openshift
    resourceVersion: "157374"
    selfLink: /oapi/v1/namespaces/openshift/imagestreams/jboss-eap64-openshift
    uid: aa40f2dd-70e8-11e5-912a-080027e21316
  spec:
    dockerImageRepository: registry.access.redhat.com/jboss-eap-6/eap64-openshift
    tags:
    - annotations:
        description: JBoss EAP 6.4 S2I images.
        iconClass: icon-jboss
        sampleContextDir: kitchensink
        sampleRef: 6.4.x
        sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
        supports: eap:6.4,javaee:6,java:8,xpaas:1.1
        tags: builder,eap,javaee,java,jboss,xpaas
        version: "1.1"
      name: "1.1"
  status:
    dockerImageRepository: registry.access.redhat.com/jboss-eap-6/eap64-openshift
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: the repository "jboss-webserver-3/webserver30-tomcat7-openshift"
        was not found
    creationTimestamp: 2015-10-12T13:53:49Z
    name: jboss-webserver30-tomcat7-openshift
    namespace: openshift
    resourceVersion: "157371"
    selfLink: /oapi/v1/namespaces/openshift/imagestreams/jboss-webserver30-tomcat7-openshift
    uid: aa3e0f47-70e8-11e5-912a-080027e21316
  spec:
    dockerImageRepository: registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift
    tags:
    - annotations:
        description: JBoss Web Server 3.0 Tomcat 7 S2I images.
        iconClass: icon-jboss
        sampleContextDir: tomcat-websocket-chat
        sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts.git
        supports: tomcat7:3.0,tomcat:7,java:8,xpaas:1.1
        tags: builder,tomcat,tomcat7,java,jboss,xpaas
        version: "1.1"
      name: "1.1"
  status:
    dockerImageRepository: registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: the repository "jboss-webserver-3/webserver30-tomcat8-openshift"
        was not found
    creationTimestamp: 2015-10-12T13:53:49Z
    name: jboss-webserver30-tomcat8-openshift
    namespace: openshift
    resourceVersion: "157372"
    selfLink: /oapi/v1/namespaces/openshift/imagestreams/jboss-webserver30-tomcat8-openshift
    uid: aa3f90cb-70e8-11e5-912a-080027e21316
  spec:
    dockerImageRepository: registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift
    tags:
    - annotations:
        description: JBoss Web Server 3.0 Tomcat 8 S2I images.
        iconClass: icon-jboss
        sampleContextDir: tomcat-websocket-chat
        sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts.git
        supports: tomcat8:3.0,tomcat:8,java:8,xpaas:1.1
        tags: builder,tomcat,tomcat8,java,jboss,xpaas
        version: "1.1"
      name: "1.1"
  status:
    dockerImageRepository: registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift
kind: List
metadata: {}
[root@cloud-enablement ~]# 
```

**Comment by smarterclayton** [comment] 2016-01-30 07:05
This is now possible with status tag conditions

**Comment by bparees** [comment] 2017-10-13 20:02
dupe of https://github.com/openshift/origin/issues/6877

(yeah yours is older but that one asks for more)

**Closed by bparees** 2017-10-13 20:02 UTC
Labels: component/cli, component/imageregistry, kind/enhancement, priority/P3
