### ISSUE TITLE
Creation of resources via templates should support atomicity 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#4493] opened 2015-09-03 08:12 UTC
when a creating resources based on templates it can be that some of the resources will not be created due to various errors.  This results in partial resource creation. for example i might have a build config but no deployment config. Often this means a user having to jump into the CLI ad manually debug what was created and what was not(more often than not remove the created stuff and try the template again). it would be desired if the all the resources created from a template were atomic. Any resource that could not be create would mean the entire template creation is aborted.

**Comment by mfojtik** [comment] 2015-09-03 09:51
@ivanthelad can you provide some examples of failure? How can deploymentConfig be not created?

**Comment by ivanthelad** [comment] 2015-09-03 09:54
Hi, 
That was just an example. deploymentConfig creation could fail as perhaps it already exists. Perhaps it was not correctly removed last time.who knows :)
 
Point is the one resource will fail, while all the others will complete. i think the it would be more more predictable if an atomic approach was taken. Eg all or nothing

**Comment by liggitt** [comment] 2015-09-03 13:36
This is essentially a duplicate of https://github.com/openshift/origin/issues/2103

We're unlikely to get atomic creation from templates...
* There isn't currently transaction support in etcd
* Even if there was (it's in the works), the items are each created individually against the API, so a transaction would have to span multiple API requests
* Admission controllers make other modifications (like allocating quota) as objects are created, which would also have to be included in the transaction

**Closed by liggitt** 2015-09-03 13:36 UTC
