### ISSUE TITLE
oc delete all --all doesn't delete secrets

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3740] opened 2015-07-16 17:49 UTC
Doing a : 

     oc delete all --all

should delete everything I believe

but it seems that secrets are still there  :

<pre>
$ oc delete all --all
deploymentconfigs/gitserver
services/gitserver
pods/gitserver-1-deploy
$ oc get secret
NAME                       TYPE                                  DATA
builder-dockercfg-72ls9    kubernetes.io/dockercfg               1
[...]
</pre>

**Comment by liggitt** [comment] 2015-07-17 05:11
@smarterclayton what were the implications of changing what is included in the `all` alias?

**Comment by rassie** [comment] 2015-07-17 08:53
See https://github.com/openshift/origin/issues/3722#issuecomment-122000153 and https://github.com/openshift/origin/issues/3722#issuecomment-122059256

**Comment by kargakis** [comment] 2015-07-17 09:42
`all` expands to all the resources it aliases so it will expand to `buildConfigs,builds,imageStreams,deploymentConfigs,replicationControllers,routes,services,pods`. If you add something to that set expect that every `all` call will work with all those resources.

**Comment by smarterclayton** [comment] 2015-07-17 14:34
I think this is a feature, not a bug.

**Comment by christianh814** [comment] 2015-07-17 16:08
In my use case I wanted to get a whole "dump" 

```
oc get all -o json
```

But It doesn't really contain "all" so I would like to see "all" expanded to include "all"

**Comment by deads2k** [comment] 2015-07-17 16:16
> I think this is a feature, not a bug.

An inability to successfully run `oc export all --all -n foo | oc create -f -` because secrets and service accounts aren't exported is really annoying.

**Comment by kargakis** [comment] 2015-07-17 16:19
We should have something like `oc alias` and let the users create their own aliases of resources.

**Comment by liggitt** [comment] 2015-07-17 16:20
> We should have something like `oc alias` and let the users create their own aliases of resources.

Now *that* is a feature :)

**Comment by liggitt** [comment] 2015-07-17 16:23
> An inability to successfully run oc export all --all -n foo | oc create -f - because secrets and service accounts aren't exported is really annoying.

A service account secret isn't going to be portable between namespaces. I don't think a single resource alias is going to be able to capture the complexity of "export all the things I created, including secrets, ignoring the generated things specific to this namespace"

**Comment by deads2k** [comment] 2015-07-17 16:25
> A service account secret isn't going to be portable between namespaces. I don't think a single resource alias is going to be able to capture the complexity of "export all the things I created, including secrets, ignoring the generated things specific to this namespace"

I accept that, but you know where it leads.  Letting a user specify a resource they want to export, then build a dependency graph that contains only essential links, the pulling those resources, modifying them to limit external references, and exporting thosr...

**Comment by deads2k** [comment] 2015-07-17 16:25
Also, a pod exported without its matching service account can't be created.  Admission rejects it.

**Comment by smarterclayton** [comment] 2015-07-17 16:33
Pod export should probably purge the service account when everything
exported shares it

On Fri, Jul 17, 2015 at 12:25 PM, David Eads <notifications@github.com>
wrote:

> Also, a pod exported without its matching service account can't be
> created. Admission rejects it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3740#issuecomment-122332857>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment] 2015-07-17 16:33
And it should be possible to specify a service account on new-app / process

On Fri, Jul 17, 2015 at 12:33 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> Pod export should probably purge the service account when everything
> exported shares it
>
> On Fri, Jul 17, 2015 at 12:25 PM, David Eads <notifications@github.com>
> wrote:
>
>> Also, a pod exported without its matching service account can't be
>> created. Admission rejects it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/3740#issuecomment-122332857>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by christianh814** [comment] 2015-07-17 16:39
> > We should have something like oc alias and let the users create their own aliases of resources.

> Now that is a feature :)

+1

**Comment by smarterclayton** [comment] 2015-07-17 22:15
We won't delete secrets automatically (as part of the alias) because it would potentially impact external services.  We won't delete service accounts or policy for the same reason.

**Comment by bparees** [comment] 2015-07-20 02:03
it sounds to me like this is "working as designed", can it be closed?

**Comment by smarterclayton** [comment] 2015-07-20 02:58
We can probably hold it open for a little bit more discussion on whether
there are any other resource types that should be under "all", whether
anyone has a better name than "all", and I believe we need to spawn an
issue to track "oc delete all,secrets --all" not properly expanding all.

On Sun, Jul 19, 2015 at 10:03 PM, Ben Parees <notifications@github.com>
wrote:

> it sounds to me like this is "working as designed", can it be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3740#issuecomment-122729156>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-07-20 03:46
"some"?
"most"?

:)

**Comment by smarterclayton** [comment] 2015-07-20 03:48
"lots", "more", "yall"

On Jul 19, 2015, at 11:46 PM, Ben Parees <notifications@github.com> wrote:

"some"?
"most"?

:)
On Jul 19, 2015 22:58, "Clayton Coleman" <notifications@github.com> wrote:

> We can probably hold it open for a little bit more discussion on whether
> there are any other resource types that should be under "all", whether
> anyone has a better name than "all", and I believe we need to spawn an
> issue to track "oc delete all,secrets --all" not properly expanding all.
>
> On Sun, Jul 19, 2015 at 10:03 PM, Ben Parees <notifications@github.com>
> wrote:
>
> > it sounds to me like this is "working as designed", can it be closed?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openshift/origin/issues/3740#issuecomment-122729156
> >.
> >
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3740#issuecomment-122737144>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3740#issuecomment-122750077>.

**Comment by liggitt** [comment] 2015-07-20 03:50
'most-all

**Comment by smarterclayton** [comment] 2015-07-20 04:36
"almost-all-yall", "all" for short.

On Jul 19, 2015, at 11:50 PM, Jordan Liggitt <notifications@github.com>
wrote:

'most-all

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3740#issuecomment-122751137>.

**Comment by bparees** [comment] 2015-07-20 12:48
"many", "medley", "mixed assortment"

**Comment by smarterclayton** [comment] 2016-04-05 05:36
Closing as we have other issues tracking this.  We don't plan on adding secrets to "all" in the short term

**Closed by smarterclayton** 2016-04-05 05:36 UTC
Labels: component/cli, priority/P3
