### ISSUE TITLE
Can't stream build logs back

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#2236] opened 2015-05-14 09:18 UTC
Both `start build --follow` and `build-logs` will just exit and I 'll get the following error on the server:
```
2015/05/14 09:15:48 http: WriteHeader called with both Transfer-Encoding of "chunked" and a Content-Length of 0
```

**Comment by csrwng** [comment] 2015-05-14 19:10
@kargakis - I can't reproduce this locally. Can you add details of your env?

**Comment by kargakis** [comment] 2015-05-15 09:42
Not sure if it's of much help since my env is plain simple: I'm running OpenShift in vagrant, everytime following the sample-app flow.

**Comment by kargakis** [comment] 2015-05-15 12:48
I had asked @rhcarvalho to try and reproduce it as well but he wasn't able as well. It's very strange...

**Comment by csrwng** [comment] 2015-05-15 12:57
to troubleshoot, can you curl the log endpoint on a pod directly?
```
CERT_DIR=./openshift.local.config/master
curl --cert ${CERT_DIR}/admin.crt --key ${CERT_DIR}/admin.key --cacert ${CERT_DIR}/ca.crt https://127.0.0.1:8443/api/v1beta3/namespaces/[namespace]/pods/[podname]/log
```

**Comment by kargakis** [comment] 2015-05-15 13:09
Getting back the error I mentioned in the first post [in the server]

**Comment by csrwng** [comment] 2015-05-15 14:22
What if you curl the kubelet directly?
```
curl --cacert ${CERT_DIR}/ca.crt --cert ${CERT_DIR}/master.kubelet-client.crt --key ${CERT_DIR}/master.kubelet-client.key https://openshiftdev.local:10250/containerLogs/[namespace]/[podName]/[containerName]
```

**Comment by kargakis** [comment] 2015-05-15 14:42
@csrwng same error again

**Comment by csrwng** [comment] 2015-05-15 16:57
make sure you're doing a 'make clean' before building, seems like something in the kubelet

**Comment by bparees** [comment] 2015-05-18 13:19
closing due to inability to reproduce.

**Closed by bparees** 2015-05-18 13:19 UTC
Labels: component/build, component/logging, kind/bug, priority/P0

**Comment by wzheng1** [comment] 2015-05-21 10:52
@csrwng I tried to curl container log by following  "curl --cacert ${CERT_DIR}/ca.crt --cert ${CERT_DIR}/master.kubelet-client.crt --key ${CERT_DIR}/master.kubelet-client.key https://openshiftdev.local:10250/containerLogs/[namespace]/[podName]/[containerName]", and it returns "curl: (58) unable to load client key: -8178 (SEC_ERROR_BAD_KEY)". Could you please help on how to get the container log via RESTAPI? Thanks in advance!

**Comment by csrwng** [comment] 2015-05-21 13:53
@wzheng1 You may be getting the error due to your version of curl. If curl is not compiled with openssl, it can't understand the key format. You may need to convert the key beforehand. See https://github.com/openshift/origin/blob/master/hack/util.sh#L151-L161. Or just run a container like openshift/origin-base that has an curl+openssl and use that.

**Comment by kargakis** [comment] 2015-05-25 12:47
@csrwng fyi, seems like my problem had to do with the Docker and Go versions in Vagrant.

**Comment by wzheng1** [comment] 2015-05-28 10:32
@csrwng Thanks! It works now!
