### ISSUE TITLE
Permission problems after "oc rsync" on Windows

### ISSUE THREAD

**Issue by bdshadow** [openshift/origin#13864] opened 2017-04-22 21:20 UTC
##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Create jboss-eap70-openshift application using https://github.com/jboss-developer/jboss-eap-quickstarts.git
2. Try to run rsync:
```bash
c:\DevelopmentSuite\cdk\bin\oc.exe rsync --token=5OA58n-85GLZj2YjiYlqzG-ie_N9lm6tFdu5sKy2WsQ --server=https://10.1.2.2:8443 --insecure-skip-tls-verify=true --exclude='.git' --no-perms=true jboss-eap70-openshift-1-jlffc:/opt/eap/standalone/deployments/ -n project C:\Users\dbocharo\rsync
```

##### Current Result
```bash
Forwarding from 127.0.0.1:59973 -> 32065
Forwarding from [::1]:59973 -> 32065
Handling connection for 59973
receiving incremental file list

sent 113 bytes  received 842 bytes  1,910.00 bytes/sec
total size is 8,437,691  speedup is 8,835.28
rsync: opendir "/opt/eap/standalone/deployments/ROOT.war" (in root) failed: Permission denied (13)
rsync: send_files failed to open "/opt/eap/standalone/deployments/README.txt" (in root): Permission denied (13)
rsync: send_files failed to open "/opt/eap/standalone/deployments/ROOT.war.deployed" (in root): Permission denied (13)
rsync: send_files failed to open "/opt/eap/standalone/deployments/activemq-rar.rar" (in root): Permission denied (13)
rsync: send_files failed to open "/opt/eap/standalone/deployments/activemq-rar.rar.deployed" (in root): Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [generator=3.1.2]
error: exit status 23
```
1) Trying to open downloaded ROOT.war in the explorer gives: "You don't have permission to access this folder" -> click "Continue" as Administrator -> "You have been denied permission to access this folder"
2) Right-click on ROOT.war -> Properties -> Security tab: lists lots of extra lines in "Group or user names:" field, that usually are not listed for other usual directories.
3) Even setting full control for all users and groups doesn't help.

##### Expected Result
Directories are synced fine

##### Additional Information
1) As you can see ` --no-perms=true` is used, however, it doesn't help
2) [cwRsync ](https://www.itefix.net/content/cwrsync-free-edition) is installed as it is recommended in the [rsync docs](https://github.com/openshift/origin/blob/46585f4143f9d01714408757331c34dc4c679738/pkg/cmd/cli/cmd/rsync/rsync.go).
3) Tried from cygwin and standard windows cmd terminal with admin and not-admin rights
4) The actual problem is found in jboss tools, where we try to do [the following](https://github.com/openshift/openshift-restclient-java/blob/c725ccf1069b5e92aa58905e419992d0a945bb9e/src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java#L154) using the openshift instance created by cdk. We have 2 jiras created for this already: [JBIDE-22773](https://issues.jboss.org/browse/JBIDE-22773) and [JBIDE-22188](https://issues.jboss.org/browse/JBIDE-22188), but the problem is in `oc rsync`, because leads to the same errors, when running from cli.
Openshift version inside cdk: openshift v3.4.0.40; kubernetes v1.4.0+776c994.

**Comment by apupier** [comment] 2017-09-12 13:29
Do you have some news on the subject reported several months ago?
Do you need more information?
Do you have a workaround?

it seems to be blocking to provide hot deployment to OpenShift from Windows

**Comment by adietish** [comment] 2017-09-13 19:13
given that Windows is the biggest share in Eclipse users, this issue is rather critical. Can we have this up-prioritized, please?

**Comment by csrwng** [comment] 2017-09-19 15:06
@bdshadow the errors above seem to indicate that /opt/eap/standalone/deployments/ROOT.war, /opt/eap/standalone/deployments/README.txt, etc. are not accessible to the current user. Can you rsh into the container and access those files?

**Comment by fabianofranz** [comment] 2017-09-22 20:33
Increasing priority to investigate before the end of next sprint.

**Comment by fabianofranz** [comment] 2017-10-20 20:39
I was unable to reproduce this on 3.6.x using a similar environment: on Windows with cwRsync, tried with both EAP 7.0 and 7.1.

Since it's unlikely the fix will be ported to 1.4 I'm closing this, but feel free to reopen with more information about how to reproduce it if it still happens on a recent (3.5+) version.

**Comment by bdshadow** [comment] 2017-10-31 18:11
@fabianofranz  i'm still able to reproduce this issue. And we still have this problem in JBoss Tools. Here are the detailed exact steps.

1.  Download `openshift-origin-client-tools-v3.6.1-008f2d5-windows.zip` from https://github.com/openshift/origin/releases/tag/v3.6.1
2. Unpack the dowloaded zip, copy it to `C:\DevelopmentSuite\cdk\bin`

All next steps run in cygwin

3.  `cd` to `C:\DevelopmentSuite\cdk\bin` and `oc cluster up`
4. Open Openshift web console https://10.0.75.2:8443/console/project/myproject. `Add to Project` -> `WildFly 10.1-latest` -> `Git Repository URL` is a sample one: https://github.com/openshift/openshift-jee-sample.git, `Name` set "wildfly".
5. Wait until build is finished and pod is created.
6. Create all directories for the following path: `C:\eclipse_test-workspace\.metadata\.plugins\org.jboss.ide.eclipse.as.core\myproject@wildfly\deploy`.
7. oc rsync from pod to local: `oc.exe rsync --token=6m7w_g0eIcCjRmiX4qQ-BahlbVc1Q6-184Je1YilmMI --server=https://10.0.75.2:8443 --insecure-skip-tls-verify=true --exclude='.git' --no-perms=true wildfly-1-k28hd:/wildfly/standalone/deployments/ -n myproject C:/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy`
8. oc rsync from local back to pod: `oc.exe rsync --token=6m7w_g0eIcCjRmiX4qQ-BahlbVc1Q6-184Je1YilmMI --server=https://10.0.75.2:8443 --insecure-skip-tls-verify=true --exclude='.git' --no-perms=true C:/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy -n myproject wildfly-1-k28hd:/wildfly/standalone/deployments/`
and you'll have the following output:
```bash
sent 148 bytes  received 77 bytes  450.00 bytes/sec
total size is 31,105  speedup is 138.24
rsync: send_files failed to open "/cygdrive/c/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy/README.txt": Permission denied (13)
rsync: send_files failed to open "/cygdrive/c/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy/ROOT.war": Permission denied (13)
rsync: send_files failed to open "/cygdrive/c/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy/ROOT.war.deployed": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
error: exit status 23

```

**Comment by fabianofranz** [comment] 2017-10-31 21:52
Thanks @bdshadow for the detailed steps, working on it.

**Comment by fabianofranz** [comment] 2017-11-03 19:57
I followed exactly the steps provided but was still unable to reproduce the issue like specified. 
```
$ ./oc.exe rsync --token=ANCl2D5RSQ9XpTtI2YM_lj6nA-AU4WT2WPTnM6dKqcM --server=https://10.0.0.3:8443 --insecure-skip-tls-verify=true --exclude='.git' --no-perms=true C:/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy wildfly-1-4f7lw:/wildfly/standalone/deployments/
Forwarding from 127.0.0.1:50175 -> 42852
Forwarding from [::1]:50175 -> 42852
Handling connection for 50175
sending incremental file list

sent 112 bytes  received 16 bytes  256.00 bytes/sec
total size is 31,105  speedup is 243.01
```

It seems to me that according to the message you provided, the issue is much more related to the `rsync` binary not having permissions to the local directory than something related to `oc`. Could you make sure the `rync.exe` binary is in the path and that you can run some `rsync` command using the local files and directories in  "/cygdrive/c/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy"?

**Comment by apupier** [comment] 2017-11-09 15:27
I hit some permission denied issue when I have the rsync.exe from Development Suite 2.0.1 used in the path, I don't have this permission anymore when using the rsync from my cygwin install.
I found no differences between the 2 rsync.exe (same version, same size, same permissions...)
I think that it would worth searching in this direction (we don't have other track anyways , right?)

@bdshadow in your cmd terminal and in your cygwin terminal, can you try "where rsync"? Do you have the same rsync appearing first?
Can you also try the step 8 of your [previous comment](https://github.com/openshift/origin/issues/13864#issuecomment-340853408) in a cygwin terminal?

**Comment by apupier** [comment] 2018-01-23 15:20
with latest version of Jboss Tools (which will be released in few days) I still have a permission denied error:

> Could not sync C:\ws\withoutspace\.metadata\.plugins\org.jboss.ide.eclipse.as.core\test-fis-aurel7@camel-ose-springboot-xml\deploy to all pods running the service camel-ose-springboot-xml
> Syncing com.openshift.restclient.capability.resources.IRSyncable$LocalPeer@6f5f4a19 to com.openshift.restclient.capability.resources.IRSyncable$PodPeer@4e29c149 failed: rsync: opendir "/cygdrive/c/ws/withoutspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/test-fis-aurel7@camel-ose-springboot-xml/deploy/META-INF" failed: Permission denied (13)
> rsync: recv_generator: mkdir "/deployments/BOOT-INF/classes/META-INF" (in root) failed: Permission denied (13)

**Comment by apupier** [comment] 2018-01-23 16:02
> It seems to me that according to the message you provided, the issue is much more related to the rsync binary not having permissions to the local directory than something related to oc. Could you make sure the rync.exe binary is in the path and that you can run some rsync command using the local files and directories in "/cygdrive/c/eclipse_test-workspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproject@wildfly/deploy"?

```
Aurelien Pupier@DESKTOP-9NT300B /cygdrive/c/install/oc/openshift-origin-client-tools-v3.7.1-ab0f056-windows
$ where rsync
C:\cygwin64\bin\rsync.exe
C:\install\DevelopmentSuite-2.1\cygwin\bin\rsync.exe
C:\install\DevelopmentSuite-2.0.1\cygwin\bin\rsync.exe
C:\install\DevelopmentSuite-2.0\cygwin\bin\rsync.exe
```

```
Aurelien Pupier@DESKTOP-9NT300B /cygdrive/c/install/oc/openshift-origin-client-tools-v3.7.1-ab0f056-windows
$ rsync.exe /cygdrive/c/ws/withoutspace/.metadata/.plugins/org.jboss.ide.eclipse.as.core/test-fis-aurel7@camel-ose-springboot-xml/deploy/
drwxr-xr-x              0 2018/01/23 16:43:15 .
-rw-r--r--            509 2018/01/23 15:52:50 application.properties
-rw-r--r--            468 2018/01/23 15:52:50 logback.xml
d---rwx---              0 2018/01/23 16:43:15 META-INF
drwxr-xr-x              0 2018/01/23 16:43:11 org
drwxr-xr-x              0 2018/01/23 16:43:12 spring
```

**Closed** 2018-06-22 18:31 UTC
Labels: component/cli, help wanted, kind/bug, lifecycle/rotten, priority/P2
