### ISSUE TITLE
dial tcp: lookup kubernetes.default.svc.cluster.local: no such host

### ISSUE THREAD

**Issue by rawlingsj** [openshift/origin#3800] opened 2015-07-21 11:12 UTC
Using origin 1.0.3 we're unable to use the Kubernetes DNS service name...

```
2015/07/21 11:11:00 Get https://kubernetes.default.svc.cluster.local/api/v1/nodes: dial tcp: lookup kubernetes.default.svc.cluster.local: no such host
```

**Comment by rawlingsj** [comment] 2015-07-21 17:01
FWIW it looks like the master ip is not a nameserver.

```
[root@origin103 rawlingsj]# oc exec router-1-o3wk5 cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
search default.svc.cluster.local svc.cluster.local cluster.local openstacklocal novalocal
options ndots:5
```

**Comment by bparees** [comment] 2015-07-21 19:28
@smarterclayton thoughts?

**Comment by smarterclayton** [comment] 2015-07-21 19:37
@ncdc @eparis I don't remember anything upstream changing here?

Maybe a refactor in node initialization stopped setting DNS ip

**Comment by smarterclayton** [comment] 2015-07-21 19:45
Was this an all-in-one or a node with a config file? If config file, was DNS IP set?  We need an e2e test too which I'll add

**Comment by ncdc** [comment] 2015-07-21 19:45
I don't know what if anything changed the container resolv.conf file not getting the master set as the nameserver, but the ndots 5 option is new and makes the resolver consider anything with fewer than 5 dots a partial entry and it checks the search domains e.g. github.com.default.svc.cluster.local and so on.

**Comment by smarterclayton** [comment] 2015-07-21 19:46
Ah - we may want to dial that down then.  Is that the only reason?

On Jul 21, 2015, at 3:45 PM, Andy Goldstein <notifications@github.com>
wrote:

I don't know what if anything changed the container resolv.conf file not
getting the master set as the nameserver, but the ndots 5 option is new and
makes the resolver consider anything with fewer than 5 dots a partial entry
and it checks the search domains e.g. github.com.default.svc.cluster.local
and so on.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3800#issuecomment-123458897>.

**Comment by ncdc** [comment] 2015-07-21 19:47
I don't know if ndots is the root cause of this particular issue. It was something I talked with @jwhonce about related to DNS issues.

**Comment by rawlingsj** [comment] 2015-07-21 19:47
It seems environment specific.  I just tested 1.0.3 with our Vagrant image which is Centos 7.1 - this works.

The environment that is having the problem is RHEL 7.1 on OpenStack.

**Comment by smarterclayton** [comment] 2015-07-21 19:48
Interesting

On Jul 21, 2015, at 3:47 PM, James Rawlings <notifications@github.com>
wrote:

It seems environment specific. I just tested 1.0.3 with our Vagrant image
which is Centos 7.1 - this works.

The environment that is having the problem is RHEL 7.1 on OpenStack.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3800#issuecomment-123459336>.

**Comment by jimmidyson** [comment] 2015-07-21 19:52
I've just checked the node config & see that `dnsIP: ""`.

This is an all-in-one install. When openshift was first configured with `--write-config` I think that ipv6 was enabled (see openshift/origin#3813 which is from the same environment) - is that right @rawlingsj? I guess that could be the cause of this issue?

**Comment by rawlingsj** [comment] 2015-07-21 19:54
That's right @jimmidyson.

**Comment by rawlingsj** [comment] 2015-07-21 19:55
Both this and openshift/origin#3813 are issues on the same environment.

**Comment by smarterclayton** [comment] 2015-07-21 19:56
I think if we fix our "listen on v4 TCP"bug the IPv6 bug might go away

On Jul 21, 2015, at 3:54 PM, James Rawlings <notifications@github.com>
wrote:

That's right @jimmidyson <https://github.com/jimmidyson>.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3800#issuecomment-123460728>.

**Comment by eparis** [comment] 2015-07-23 15:10
Best of my knowledge upstream didn't screw with the node part. Seems like the kubelet has set `--cluster-domain=`, but not `--cluster-dns=`. Maybe you gave an ipv6 address for cluster-dns and that caused this, somehow?

**Comment by liggitt** [comment] 2015-07-23 15:58
The empty `dnsIP` in the node config will prevent node DNS usage. @sdodson, how is the installer setting that during `create-node-config`?

**Comment by sdodson** [comment] 2015-07-23 16:59
@liggitt from conversation above it sounds like this is an all in one install so I'm assuming ansible wasn't involved. @rawlingsj is that correct?

**Comment by sdodson** [comment] 2015-07-23 17:11
If this environment was deployed via ansible it should be the `openshift_ip` value of the first master, which defaults to system_facts['default_ipv4']['address']

**Comment by rawlingsj** [comment] 2015-07-24 06:30
@liggitt correct this was an all in one install and so I didn't use ansible.

**Comment by rawlingsj** [comment] 2015-07-24 06:31
@sdodson sorry message above was a reply to you..

correct this was an all in one install and so I didn't use ansible.

**Comment by liggitt** [comment] 2015-07-24 18:18
What was the full `--write-config` command? If you don't provide a `--master` arg, it should detect an IP address and use that as the master and as the node's `dnsIP`. If you provide a `--master` arg that is an IP, it should use that as both. If you provide a `--master` arg that is *not* an IP, then it doesn't know what to use for `dnsIP`, so it leaves it blank.

There's a magical envvar you can set (`OPENSHIFT_DNS_ADDR`) to tell it what IP to use for the node's `dnsIP` in that case, but there's no way to know that, or that you even need to set that.

I'll look into warning or surfacing that as an option

**Comment by smarterclayton** [comment] 2015-07-24 19:16
On the tcp binding side (stopping binding to ipv6 unless the user chooses)
i'm working on this now.  Are we closed on the other side (not having DNS
configured) and any changes we need for 3.0.1?

On Fri, Jul 24, 2015 at 2:18 PM, Jordan Liggitt <notifications@github.com>
wrote:

> What was the full --write-config command? If you don't provide a --master
> arg, it should detect an IP address and use that as the master and as the
> node's dnsIP. If you provide a --master arg that is an IP, it should use
> that as both. If you provide a --master arg that is *not* an IP, then it
> doesn't know what to use for dnsIP, so it leaves it blank.
>
> There's a magical envvar you can set (OPENSHIFT_DNS_ADDR) to tell it what
> IP to use for the node's dnsIP in that case, but there's no way to know
> that, or that you even need to set that.
>
> I'll look into warning or surfacing that as an option
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3800#issuecomment-124607461>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by sebastianfaulhaber** [comment] 2015-07-27 11:50
I was facing the same error message when spinning up any pod (master + node + DNS on the same machine). I enabled tracing for BIND with 
```
rndc querylog
tail -f /var/log/messages | grep -i named
```
...and found several ```...query 'master.openshift.local' denied...``` messages, since queries from the Kubernetes part were coming from a different subnet.

After making my DNS more permissive everything started to work fine. Maybe this is worth checking for your scenario as well.

**Comment by danmcp** [comment] 2015-08-19 15:45
@smarterclayton Bump

**Comment by smarterclayton** [comment] 2015-08-20 03:29
https://github.com/openshift/origin/pull/3912 defaults binding to ipv4 so the ipv6 problem should be gone now.  I also believe ansible is fixed(?).  We have seen an issue where periodically the service does not return an answer for a query, which is probably unrelated to these issues, but also has to be fixed.

**Comment by smarterclayton** [comment] 2015-12-18 18:15
I think this is now fixed with the recursive lookup fix (we failed occasionally due to timeouts, that has been resolved).

**Closed by smarterclayton** 2015-12-18 18:15 UTC
Labels: component/routing, kind/bug, priority/P2
