### ISSUE TITLE
S2I build fails without imagestream import

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4207] opened 2015-08-17 11:58 UTC
Issue
---
After update to latest origin and build it, S2I bulid(--strategy=source) can't work. Even though same command was worked with previous commit (I pulled it 72 hour ago).

Env
---
~~~
$ openshift version
openshift v1.0.4-237-g30861f3
kubernetes v1.1.0-alpha.0-1155-gb73c53c
$ docker version
Client version: 1.6.2.fc21
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): c3ca5bb/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2.fc21
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): c3ca5bb/1.6.2
OS/Arch (server): linux/amd64
~~~

Reproduce steps
---
0. `git pull <origin>` and `make build`
1. openshift start
2. Create registry and router
3. Create new application with this command:

    `oc new-app https://github.com/openshift/sti-php.git --context-dir=5.5/test/test-app -l app=php --strategy=source`

4. Build would be failed. Please see the result below.

Result
--
- Please see the entire build-logs [1]. It says.
~~~
W0817 11:31:08.149001       1 docker.go:303] Image does not contain a value for the io.openshift.s2i.scripts-url label
~~~

[1] Current failed log : https://paste.fedoraproject.org/255826/

Additional info
---
- Imagestream's tag shows too much TAGs[2].
[2] `oc get is` : https://paste.fedoraproject.org/255828/

- You can check previous successful log as well[3]
[3] Previous successful log: https://paste.fedoraproject.org/255540/

**Comment by mfojtik** [comment] 2015-08-17 12:24
@nak3 have you also updated the s2i builder image?

**Comment by nak3** [comment] 2015-08-17 12:27
@mfojtik 
No, I haven't. Should I update it? The s2i images in my env were:
~~~
$ docker images |grep builder
docker.io/openshift/origin-sti-builder                          latest                  5d6c5e3263ac        7 days ago           416.6 MB
docker.io/openshift/origin-docker-builder                       latest                  e42876100ffb        7 days ago           416.6 MB
docker.io/openshift/origin-sti-builder                          v1.0.4                  ac43dbcba9e5        2 weeks ago          412.2 MB
docker.io/openshift/origin-docker-builder                       v1.0.4                  ef3e7c089013        2 weeks ago          412.2 MB
docker.io/openshift/origin-sti-builder                          v1.0.0                  d61923fc9a93        7 weeks ago          375.3 MB
docker.io/openshift/origin-docker-builder                       v1.0.0                  0ef77b23a1c4        7 weeks ago          375.3 MB
~~~

**Comment by nak3** [comment] 2015-08-17 12:59
I tested after clean installation,and the result was almost same. 
https://paste.fedoraproject.org/255852/

**Comment by mfojtik** [comment] 2015-08-17 13:07
@nak3 can you also try to update the php image? 

cc @bparees

**Comment by nak3** [comment] 2015-08-17 14:08
@mfojtik  OK, I found the cause of this issue.

I forgot to create image-streams after update by hand like:

`oc create -f examples/image-streams/image-streams-centos7.json`

I can reproduce my reported issue by `oc delete is php`. And I could fix it with above command.

**Comment by nak3** [comment] 2015-08-17 14:13
So, ***import ImageStream*** is must to create new application from S2I?

**Comment by bparees** [comment] 2015-08-17 15:08
no that should not be mandatory, new-app should be locating the php image on dockerhub and creating the imagestream for you.  it sounds like maybe that was done but a new version of the image wasn't pulled down.  Not clear why creating the imagestream would change that or why deleting it un-changed that.

what does your non-working buildconfig look like?

**Comment by nak3** [comment] 2015-08-18 01:13
> what does your non-working buildconfig look like?

@bparees I tested it on OSE v3 as well and the result was same. Without imageStream, we failed to build by S2I. Please see buildConfig below.

* OSE v3 (v3.0.1.0-525-geddc479)

Non-working : https://paste.fedoraproject.org/256049/
Working     : https://paste.fedoraproject.org/256047/

* Origin (v1.0.4-286-g9dd0e51-dirty)
Non-working : https://paste.fedoraproject.org/256052/
Working     : https://paste.fedoraproject.org/256050/

**Comment by bparees** [comment] 2015-08-18 04:42
@csrwng I think you helped someone else with this issue...   because @nak3's app name is "php", if the imagestream doesn't exist, new-app creates the imagestream and points it to the dockerhub php image, which is not the right image to use as a builder.

then when the build runs, the imagestream resolves to the dockerhub library/php image and the s2i build fails.

Creating a new S2I builder with build config: "Builder Image:\t\tlibrary/php@sha256:0f841eb022205ca1dd762302c054b68bbf04621501cf3ead79a92b2ad1f293d8

was there an actual fix to be done here, or is the answer just "don't use php as the name of your app"?  i'm not 100% clear on why the buildconfig ends up using an imagestream for the builder as it does.  it should be using a DockerImage in this scenario (no imagestream exists for the php builder).


also @nak3 i think you transposed the "working" and "non-working" configs in your OSE examples.  but they look like what i'd expect in the Origin ones.

**Comment by bparees** [comment] 2015-08-18 04:44
actually i guess the appname isn't php, we're just setting up the From incorrectly, period.

**Comment by bparees** [comment] 2015-08-18 04:47
(ok so as i think about it this is probably working as designed...  we try to find a php image to build the app with, since there are no builder imagestreams we can't find one that way, so we just fall back to an image named "php" on dockerhub, which in this case is not the right answer.  the workaround would be to explicitly specify the builder image to use (openshift/php-55-centos7) when invoking new-app.  The question is, is the current behavior really what we want, where in all likelihood you end up with something that doesn't work?)

**Comment by nak3** [comment] 2015-08-18 06:29
> also @nak3 i think you transposed the "working" and "non-working" configs in your OSE examples. but they look like what i'd expect in the Origin ones.

Yes, sorry it was my mistake.

**Comment by bparees** [comment] 2015-09-11 04:02
@csrwng @smarterclayton can you weigh in on my last comment above?  personally i'm of the opinion that we should not be using random dockerhub images as s2i builders since there is almost zero chance of that resulting in a successful build.

**Comment by csrwng** [comment] 2015-09-11 04:10
@bparees I agree with you, it doesn't make sense for builder images. It makes more sense for things that you might want to deploy standalone (like mysql, mongo, etc). But even those, until we have user namespace support, are not likely to run right out of the box.

**Comment by bparees** [comment] 2015-09-11 04:48
oc new-app mongodb would be a different story, but this is a case where we tried to pick an s2i builder image for the source.

**Comment by deanpeterson** [comment] 2015-09-13 00:40
I have an imageSteam installed called mongodb using create -f image-streams.json.  When I try to run the mongodb-persistent-template.json it fails with the message: 

"Couldn't create initial deployment: DeploymentConfig "mongodb" is invalid: triggers[0].imageChange.from: invalid value 'mongodb', Details: imageStream "mongodb" not found"

I list out the imagestreams installed and mongodb is there.

**Comment by liggitt** [comment] 2015-09-13 00:49
Is the template set up to use the image stream from the openshift namespace?

**Comment by deanpeterson** [comment] 2015-09-13 00:55
Thanks @liggitt that was the problem.

**Comment by mfojtik** [comment] 2015-09-14 08:26
@nak3 @bparees can we close this issue?

**Comment by bparees** [comment] 2015-09-14 13:50
@mfojtik no, i want to use this issue to address this behavior:
```
(ok so as i think about it this is probably working as designed... we try to find a php image to build the app with, since there are no builder imagestreams we can't find one that way, so we just fall back to an image named "php" on dockerhub, which in this case is not the right answer. the workaround would be to explicitly specify the builder image to use (openshift/php-55-centos7) when invoking new-app. The question is, is the current behavior really what we want, where in all likelihood you end up with something that doesn't work?)
```

**Comment by smarterclayton** [comment] 2015-09-14 14:07
If you provided source, and only one image, and php on the docker hub is
not identified as a builder, then the command should fail, telling you that
you need to explicitly instruct us that we want to build using this image.

On Mon, Sep 14, 2015 at 9:50 AM, Ben Parees <notifications@github.com>
wrote:

> @mfojtik <https://github.com/mfojtik> no, i want to use this issue to
> address this behavior:
>
> (ok so as i think about it this is probably working as designed... we try to find a php image to build the app with, since there are no builder imagestreams we can't find one that way, so we just fall back to an image named "php" on dockerhub, which in this case is not the right answer. the workaround would be to explicitly specify the builder image to use (openshift/php-55-centos7) when invoking new-app. The question is, is the current behavior really what we want, where in all likelihood you end up with something that doesn't work?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4207#issuecomment-140081359>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-09-14 14:24
> If you provided source, and only one image, and php on the docker hub is not identified as a builder

by "one image" do you mean "no image"?  if you provide one image we're supposed to use that as the builder, if it's an s2i builder image, right?  if it's not an s2i builder image, i think we just deploy it by itself as a new DC independent of the source.

**Comment by smarterclayton** [comment] 2015-09-14 14:30
Scenarios:

    oc new-app IMAGE SOURCE

Should test image for whether it's builder - if it isn't, fail unless you
set --strategy=source.  The error message should tell you.

    oc new-app IMAGE

If it's a builder it should fail because you don't provide source.  If it's
not a builder, it will create a dc.  If you specify --strategy=docker or
source and don't specify a git uri, it should fail telling you you need a
URI.

    oc new-app SOURCE

If source is PHP type, it should substitute "php".  This should be
equivalent to oc new-app IMAGE SOURCE


On Mon, Sep 14, 2015 at 10:24 AM, Ben Parees <notifications@github.com>
wrote:

> If you provided source, and only one image, and php on the docker hub is
> not identified as a builder
>
> by "one image" do you mean "no image"? if you provide one image we're
> supposed to use that as the builder, if it's an s2i builder image, right?
> if it's not an s2i builder image, i think we just deploy it by itself as a
> new DC independent of the source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4207#issuecomment-140097391>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-09-14 17:18
>  oc new-app IMAGE SOURCE Should test image for whether it's builder - if it isn't, fail unless you set --strategy=source. The error message should tell you.

that's not compatible w/ the current behavior which is that if the IMAGE is not a builder, it constructs a DC for that image.  So are you ok with breaking the existing behavior for this?

this is the problem with all the guessing new-app tries to do about what your intentions might have been.  I think it would be better if new-app enforced that you be explicit about what you want.  If you want the image to be used as an s2i builder for the source, you should have to declare that via the ~ syntax.

if you want the image to be deployed independently from the source, then you don't tie them together (which is what happens today, unless the image happens to be a builder, in which case it's treated like you used the ~ operator).

**Comment by smarterclayton** [comment] 2015-09-14 19:25
> that's not compatible w/ the current behavior which is that if the IMAGE
is not a builder, it constructs a DC for that image. So are you ok with
breaking the existing behavior for this?

The current behavior is almost certainly wrong because the input is
ambiguous.  If the current code isn't properly highlighting that condition,
it got lost during one of the refactors (or never worked) but was intended
to behave that way.  Image + source as the only two arguments is only
unambiguous if the image is a builder or the user specified an explicit
strategy.

On Mon, Sep 14, 2015 at 1:18 PM, Ben Parees <notifications@github.com>
wrote:

> oc new-app IMAGE SOURCE Should test image for whether it's builder - if it
> isn't, fail unless you set --strategy=source. The error message should tell
> you.
>
> that's not compatible w/ the current behavior which is that if the IMAGE
> is not a builder, it constructs a DC for that image. So are you ok with
> breaking the existing behavior for this?
>
> this is the problem with all the guessing new-app tries to do about what
> your intentions might have been. I think it would be better if new-app
> enforced that you be explicit about what you want. If you want the image to
> be used as an s2i builder for the source, you should have to declare that
> via the ~ syntax.
>
> if you want the image to be deployed independently from the source, then
> you don't tie them together (which is what happens today, unless the image
> happens to be a builder, in which case it's treated like you used the ~
> operator).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4207#issuecomment-140148990>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-09-14 19:31
@csrwng sounds like we need a serious refactoring/revisiting of new-app behavior.

**Comment by csrwng** [comment] 2015-09-14 19:38
@bparees I think new-app's current behavior is in line with what @smarterclayton describes. No argument on the refactor, but in this case, I believe it's doing what it's intended to do:

```
# oc new-app https://github.com/openshift/sti-php.git --context-dir=5.5/test/test-app --docker-image=library/php
error: none of the images that match "php" can build source code - check whether this is the image you want to use, then use --strategy=source to build using source or --strategy=docker to treat this as a Docker base image and set up a layered Docker build
```

**Comment by bparees** [comment] 2015-09-14 20:02
@csrwng 
```oc new-app openshift/mysql-55-centos7 http://github.com/openshift/ruby-ex.git```

should not create a mysql DC based on what @smarterclayton said, at least that was my interpretation, because it's an ambiguous scenario, but that's what it does today.

Did I think mysql-55-centos7 was a builder that would be used w/ my source?  or was i expecting a separate DC for it?

I would argue that
```oc new-app openshift/ruby-20-centos7 http://github.com/openshift/ruby-ex.git```

is also ambiguous because maybe i expected a DC to be created, but because that image happens to be a builder, one wasn't.  which is why i'd prefer to see you *have* to specify the ~ if you want to use that image with that repo, and otherwise you always get a separate DC for the image (no relation to the repo)

**Comment by csrwng** [comment] 2015-09-14 20:28
So yes, based on @smarterclayton's statement above, then 
```
oc new-app openshift/mysql-55-centos7 http://github.com/openshift/ruby-ex.git
```
should result in an error saying that openshift/mysql-55-centos7 is not a builder. However, that's not what I think was intended in the code by @smarterclayton. The above line results in a dc getting created for mysql and a bc getting created for your ruby repo because mysql-55-centos7 is determined not to be a builder. 

As discussed, for the time being, what we can do is not rely on --strategy=source to allow you to force the use of an image that is not a builder as a builder. Instead, we would tell you to use the ~ syntax and warn you that you are not using a builder. @smarterclayton thoughts?

**Comment by smarterclayton** [comment] 2015-09-14 22:31
On Sep 14, 2015, at 4:28 PM, Cesar Wong <notifications@github.com> wrote:

So yes, based on @smarterclayton <https://github.com/smarterclayton>'s
statement above, then

oc new-app openshift/mysql-55-centos7 http://github.com/openshift/ruby-ex.git

should result in an error saying that openshift/mysql-55-centos7 is not a
builder. However, that's not what I think was intended in the code by
@smarterclayton <https://github.com/smarterclayton>. The above line results
in a dc getting created for mysql and a bc getting created for your ruby
repo because mysql-55-centos7 is determined not to be a builder.


Yeah, before we merged generate and new-app, the above was ambiguous and we
didn't do anything (no builder found).  When we added local source
detection, we started searching for "php" in this case.  I think this
should *not* resolve to the docker hub image "php" if it is not a builder.
The chain rules for source type resolution should require a builder at each
step - if we get to generic docker php and it is not a builder, we should
fail there (at the first found non-builder in the search tree) and tell the
user that they need to either explicitly say "php~source mysql" or choose
--strategy or use ~ to force mysql to be a builder.  The latter option is
probably better.


As discussed, for the time being, what we can do is not rely on
--strategy=source to allow you to force the use of an image that is not a
builder as a builder. Instead, we would tell you to use the ~ syntax and
warn you that you are not using a builder. @smarterclayton
<https://github.com/smarterclayton> thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4207#issuecomment-140196651>.

**Comment by bparees** [comment] 2015-09-15 01:49
> if we get to generic docker php and it is not a builder, we should fail there (at the first found non-builder in the search tree) and tell the user that they need to either explicitly say "php~source mysql" or choose --strategy or use ~ to force mysql to be a builder. 

i think that's what we do today, basically.  the problem is if a user runs:
"oc new-app http://somephp-repo --strategy=source"  they get the err @nak3 ran into which is that we locate the library/php image and try to do an s2 build with it, which will never work.

**Comment by smarterclayton** [comment] 2015-09-15 03:45
That's what --strategy=source means.  Force source strategy.  We could
display a warning saying the image you selected doesn't appear to be marked
as a builder (and describe what that is).

On Mon, Sep 14, 2015 at 9:49 PM, Ben Parees <notifications@github.com>
wrote:

> if we get to generic docker php and it is not a builder, we should fail
> there (at the first found non-builder in the search tree) and tell the user
> that they need to either explicitly say "php~source mysql" or choose
> --strategy or use ~ to force mysql to be a builder.
>
> i think that's what we do today, basically. the problem is if a user runs:
> "oc new-app http://somephp-repo --strategy=source" they get the err @nak3
> <https://github.com/nak3> ran into which is that we locate the
> library/php image and try to do an s2 build with it, which will never work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4207#issuecomment-140250424>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-09-15 12:32
The problem is it's not the image they selected, it's an image we selected
for them (library/php) that isn't a builder. We're basically guaranteeing
failure.

Ben Parees | OpenShift

**Comment by smarterclayton** [comment] 2015-09-15 21:37
No, it's something that doesn't *say* it's a builder.  That's not the same
thing.  I should be able to force new-app to build an s2i build on any
image on the docker hub, regardless of the metadata it has.  That's what
--source=strategy and ~ are doing.

On Tue, Sep 15, 2015 at 8:32 AM, Ben Parees <notifications@github.com>
wrote:

> The problem is it's not the image they selected, it's an image we selected
> for them (library/php) that isn't a builder. We're basically guaranteeing
> failure.
>
> Ben Parees | OpenShift
> On Sep 14, 2015 11:45 PM, "Clayton Coleman" <notifications@github.com>
> wrote:
>
> > That's what --strategy=source means. Force source strategy. We could
> > display a warning saying the image you selected doesn't appear to be
> marked
> > as a builder (and describe what that is).
> >
> > On Mon, Sep 14, 2015 at 9:49 PM, Ben Parees <notifications@github.com>
> > wrote:
> >
> > > if we get to generic docker php and it is not a builder, we should fail
> > > there (at the first found non-builder in the search tree) and tell the
> > user
> > > that they need to either explicitly say "php~source mysql" or choose
> > > --strategy or use ~ to force mysql to be a builder.
> > >
> > > i think that's what we do today, basically. the problem is if a user
> > runs:
> > > "oc new-app http://somephp-repo --strategy=source" they get the err
> > @nak3
> > > <https://github.com/nak3> ran into which is that we locate the
> > > library/php image and try to do an s2 build with it, which will never
> > work.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/openshift/origin/issues/4207#issuecomment-140250424
> > >.
> > >
> >
> >
> >
> > --
> > Clayton Coleman | Lead Engineer, OpenShift
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openshift/origin/issues/4207#issuecomment-140271660
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4207#issuecomment-140373293>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-09-15 22:35
@smarterclayton they said "please build this for me using a source strategy"

we said "ok, but i have no image that can actually do that, so i'm going to pick one that can't, and then let you find out when your build fails"

if they explicitly chose that image and said "use this image for a source build" sure, that's fine, but for us to go pick something that does not work seems like the wrong experience.

if we're going to default to something, why not default to "openshift/php-56-centos7" instead of "library/php"?  at least that would work.

**Comment by bparees** [comment] 2015-09-16 00:03
ok I talked to @smarterclayton and i think we agree on this much:

repo contains a docker file
```$ oc new-app http://somephprepo```
"we could not locate a php builder image for this repo, please specify an image.  non-builder candidate images include: library/php.  to use this image, specify oc new-app library/php~http://somephprepo --strategy=source"

```$ oc new-app http://somephprepo --strategy=source```
"we could not locate a php builder image for this repo, please specify an image.  non-builder candidate images include: library/php.  to use this image, specify oc new-app library/php~http://somephprepo --strategy=source"

This means for the case @nak3 hit, he would have gotten an error saying "the only image we found was library/php and it's not a builder, if you really really want to use it, run "oc new-app library/php~http://yourrepo --strategy=source"  (you have to both explicitly specify the image, and explicitly specify you want a source build)


```$ oc new-app library/php~http://somephprepo```
"library/php does not appear to be a builder image, if you want to use it as a builder image, specify --strategy=source"

```$ oc new-app library/php~http://somephprepo --strategy=source```
success(ish): creates a buildconfig using library/php and source strategy (and is going to fail)

```$ oc new-app http://somephprepo  --strategy=docker```
creates a build of type docker that's going to fail due to no dockerfile(?)  (we should probably make sure our builder doesn't panic if it can't find the dockerfile when doing substitution/appending but that's unrelated)

```$ oc new-app someimage~http://somephprepo  --strategy=docker```
creates a build of type docker that's going to fail due to no dockerfile(?)


repo with a dockerfile:
```$ oc new-app http://somedockerrepo```
creates a docker builder

```$ oc new-app someimage~http://somedockerrepo```
creates a docker builder with an explicit From of someimage

```$ oc new-app someimage~http://somedockerrepo  --strategy=docker```
creates a docker builder with an explicit From of someimage


Things i'm not sure we agree on:
```$ oc new-app someimage http://somephprepo --strategy=source```
I think any time you specify an image as a separate item from the repo, it should simply be created as its own DC and never used as the builder image for the repo, regardless of whether it is a builder or not, regardless of whether the user specified --strategy=source or not.

```$ oc new-app someimage http://somephprepo```
I think any time you specify an image as a separate item from the repo, it should simply be created as its own DC and never used as the builder image for the repo, regardless of whether it is a builder or not, regardless of whether the user specified --strategy=source or not.  (yes i'm repeating myself)

The current behavior, as i understand it, is "if you specifiy --strategy=source, we'll pretend "someimage" is a builder and use it as the builder for your buildconfig", similarly if you don't specifiy --strategy=source, but "someimage" is a builder, we'll use it as a builder for your buildconfig.  and if neither of those are true (it's not a builder and you don't specify strategy=source) then you get an unrelated DC for that image.

**Comment by nak3** [comment] 2015-09-25 02:17
OK, I understand. It is clear now.

But there is one thing to mention. It is technically impossible to create new application via **web console** now, because it forces us to select builder image or template with the console.

![without-imagestream](https://cloud.githubusercontent.com/assets/2138339/10091463/ad3f15ec-6376-11e5-8f08-ba0cbdd5a365.png)

It looks like it will not fix after merged this PR https://github.com/openshift/origin/pull/4684 I should probably mention in https://github.com/openshift/origin/pull/4684 though.

**Comment by bparees** [comment] 2015-09-25 02:55
@nak3 you can always add the builder image tag annotating to the imagestreamtag if you want it to show up in the webconsole as a builder image, so i'm not sure i follow your point?

**Comment by nak3** [comment] 2015-09-25 03:18
Sorry, my bad explanation.

I wanted to say that web console doesn't support this style to create new application.

  `$ oc new-app openshift/nodejs-010-centos7~https://github.com/openshift/nodejs-ex.git`

So, I think it means that we have to import imagestream before create new app in any case.

**Comment by bparees** [comment] 2015-10-06 12:51
@csrwng @smarterclayton https://github.com/openshift/origin/issues/4207#issuecomment-140584203 describes what i plan to implement in oc new-app this sprint.  comments/suggestions/complaints?

in particular @smarterclayton are you going to block this because it's going to change (break compatibility) the existing behavior of oc new-app with respect to what happens when you pass multiple images?

**Comment by csrwng** [comment] 2015-10-06 16:07
@bparees some questions/comments ... 

> $ oc new-app library/php~http://somephprepo --strategy=source
> success(ish): creates a buildconfig using library/php and source strategy (and is going to fail)

This *could* still be useful if we allowed you to specify your own scripts. Is that something we'd want to allow in the future?


> $ oc new-app someimage~http://somephprepo --strategy=docker
> creates a build of type docker that's going to fail due to no dockerfile(?)

This could also still be useful if we allow you to specify a local Dockerfile (maybe we should suggest it?)

> Things i'm not sure we agree on:
> $ oc new-app someimage http://somephprepo --strategy=source
> I think any time you specify an image as a separate item from the repo, it should simply be created as its own DC and never used as the builder image for the repo, regardless of whether it is a builder or not, regardless of whether the user specified --strategy=source or not.

If we detect that the image you specified is a builder and you specified a source repo, could we (instead of generating a dc + bc) tell you that you should specify image~repo if that's what you want?

**Comment by bparees** [comment] 2015-10-06 16:13
@csrwng 
1) could be.  since i'm not proposing throwing an error there (probably would report a warning though, that the build is going to fail, but they very explicitly asked for it), it could certainly be possible in the future.

2) same as (1)

3) again maybe as a warning.

**Comment by smarterclayton** [comment] 2015-10-06 18:30
I'm ok with 3 meaning "do something with php, and do something with some
image, but they aren't linked".  It's ok to break backwards compatibility.
A warning is good as long as the code to do it is well isolated.

**Comment by bparees** [comment] 2016-04-08 17:32
i'm going to consider https://github.com/openshift/origin/pull/8323 to resolve this, users will get warned if new-app selected an image which isn't an s2i builder and they will have to take explicit action if they still want to use it as if it is an s2i builder.

**Closed** 2016-04-29 20:38 UTC
Labels: component/build, component/cli, kind/bug, priority/P3
