### ISSUE TITLE
Provisioning the same template twice using the template broker results in cryptic error

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16513] opened 2017-09-22 17:27 UTC
> Provision call failed: Error deprovisioning ServiceInstance "test/mongodb-persistent-6sfx6" of ServiceClass "mongodb-persistent" at ServiceBroker "template-service-broker": ""

I assume it's trying to deprovision to clean up a failed provision? It's confusing, though, and the real error is lost. (Probably I already have resources with the same names in my project.)

Deleting the service instance later works

cc @pmorie @bparees @jim-minter @ncameronbritt 

```yaml
  conditions:
    - lastTransitionTime: '2017-09-22T17:19:28Z'
      message: >-
        Provision call failed: Error deprovisioning ServiceInstance
        "test/mongodb-persistent-6sfx6" of ServiceClass "mongodb-persistent" at
        ServiceBroker "template-service-broker": ""
      reason: ProvisionCallFailed
      status: 'False'
      type: Ready
    - lastTransitionTime: '2017-09-22T17:19:29Z'
      message: >-
        Provision call failed: Error deprovisioning ServiceInstance
        "test/mongodb-persistent-6sfx6" of ServiceClass "mongodb-persistent" at
        ServiceBroker "template-service-broker": ""
      reason: ProvisionCallFailed
      status: 'True'
      type: Failed
```

How it looks in the UI:

![openshift web console 2017-09-22 13-20-03](https://user-images.githubusercontent.com/1167259/30756693-bad8ea0a-9f99-11e7-9eca-3e919cb794ac.png)

**Comment by bparees** [comment] 2017-09-22 18:27
I think this is mostly an SC thing, but if it turns out the TSB is handling something wrong, @jim-minter can take care of it.

**Comment by jim-minter** [comment] 2017-09-27 18:03
> I assume it's trying to deprovision to clean up a failed provision? It's confusing, though, and the real error is lost. (Probably I already have resources with the same names in my project.)
>
> Deleting the service instance later works

This is mostly a duplicate of #16515.  The SC error message is wrong, and in fact deleting the service instance later doesn't work properly.

However, I note that the TSB has a more detailed error to hand which it could return to the SC in the LastOperation Description field.  I'm going to hijack this issue to work on that.

**Closed** 2017-09-28 11:17 UTC
Labels: area/usability, component/templateservicebroker, kind/bug, priority/P2
