### ISSUE TITLE
"cpu.shares: no such file or directory" error in e2e test - rc, dc, database pod, etc fail to start

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#7616] opened 2016-02-25 13:34 UTC
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5102/console

```
Running hack/../hack/../test/end-to-end/core.sh:200: executing 'oc logs dc/failing-dc-mid' expecting success and text 'test mid hook executed'...
FAILURE after 0.127s: hack/../hack/../test/end-to-end/core.sh:200: executing 'oc logs dc/failing-dc-mid' expecting success and text 'test mid hook executed': the output content test failed
There was no output from the command.
There was no error output from the command.
[...]
Stderr from the command:

go tool pprof: signal: broken pipe
/data/src/github.com/openshift/origin/hack/lib/log.sh: line 30: 29668 Terminated              sar -A -o "${binary_logfile}" 1 86400 > /dev/null 2> "${stderr_logfile}"
info: password for stats user admin has been set to bWNNyTQHdx
The import completed successfully.

!!! Error in hack/../hack/../test/end-to-end/../../hack/cmd_util.sh:195
	'return 1' exited with status 1
Call stack:
	1: hack/../hack/../test/end-to-end/../../hack/cmd_util.sh:195 os::cmd::expect_success_and_text(...)
	2: hack/../hack/../test/end-to-end/core.sh:200 main(...)
Exiting with status 1
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster
```

**Comment by smarterclayton** [comment] 2016-02-25 14:47
I think this is the first time I've seen this.

**Comment by smarterclayton** [comment] 2016-02-25 15:05
Not sure if this is related, but the container never starts:

```
I0225 07:28:08.539954     473 container.go:386] Start housekeeping for container "/system.slice/docker-c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57.scope"
E0225 07:28:08.540224     473 manager.go:1873] Error running pod "failing-dc-mid-1-deploy_test(503dd22a-db91-11e5-9ed3-0e652d436df1)" container "deployment": runContainer: API error (500): Cannot start container c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57.scope/cpu.shares: no such file or directory
E0225 07:28:08.540286     473 pod_workers.go:138] Error syncing pod 503dd22a-db91-11e5-9ed3-0e652d436df1, skipping: failed to "StartContainer" for "deployment" with RunContainerError: "runContainer: API error (500): Cannot start container c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57.scope/cpu.shares: no such file or directory\n"
I0225 07:28:08.540353     473 server.go:577] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"failing-dc-mid-1-deploy", UID:"503dd22a-db91-11e5-9ed3-0e652d436df1", APIVersion:"v1", ResourceVersion:"664", FieldPath:"spec.containers{deployment}"}): type: 'Warning' reason: 'Failed' Failed to start container with docker id c6d21444deb7 with error: API error (500): Cannot start container c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57.scope/cpu.shares: no such file or directory
I0225 07:28:08.540382     473 server.go:577] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"failing-dc-mid-1-deploy", UID:"503dd22a-db91-11e5-9ed3-0e652d436df1", APIVersion:"v1", ResourceVersion:"664", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "deployment" with RunContainerError: "runContainer: API error (500): Cannot start container c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-c6d21444deb7683205f69b73e0036e07e05598d54e47e5459d3d6af859408b57.scope/cpu.shares: no such file or directory\n"
I0225 07:28:08.657335     473 manager.go:1331] Container "8784d460e653120669f56085c4e5462664353358f25d1c08b9f4e365a0105132 test/failing-dc-2-deploy" exited after 202.851918ms
I0225 07:28:08.657335     473 manager.go:1331] Container "8784d460e653120669f56085c4e5462664353358f25d1c08b9f4e365a0105132 test/failing-dc-2-deploy" exited after 204.899194ms
W0225 07:28:08.657402     473 manager.go:1337] No ref for pod '"8784d460e653120669f56085c4e5462664353358f25d1c08b9f4e365a0105132 test/failing-dc-2-deploy"'
I
```

**Comment by smarterclayton** [comment] 2016-02-25 15:06
@mrunalp this *looks* like a race condition on the cgroup, which causes container start to fail.  I think this is RHEL 1.9.2 docker.  @derekwaynecarr

**Comment by smarterclayton** [comment] 2016-02-25 15:08
Bumping to p0 until we know whether this is a problem with Docker 1.9.2 or not, which would be a release blocker.

**Comment by kargakis** [comment] 2016-02-25 17:45
Cannot reproduce locally with docker 1.9.1. Doesn't look like a deployment issue...

**Comment by pweil-** [comment] 2016-02-25 17:46
@mrunalp - sending this your way for some deeper investigation since this isn't looking like a deployment issue.  

/cc @jwhonce

**Comment by derekwaynecarr** [comment] 2016-02-25 22:03
Is it possible to see the output of the following on a machine that has this issue:

```
$ cat /proc/$(pidof docker)/cgroup
10:perf_event:/
9:freezer:/
8:memory:/system.slice/docker.service
7:cpuset:/
6:blkio:/system.slice/docker.service
5:devices:/system.slice/docker.service
4:hugetlb:/
3:cpu,cpuacct:/system.slice/docker.service
2:net_cls,net_prio:/
1:name=systemd:/system.slice/docker.service
```

**Comment by derekwaynecarr** [comment] 2016-02-25 22:06
Sorry, I meant to see the output for the container that fails:

```
$ docker inspect -f '{{ .State.Pid }}' <container>
<pid>
cat /proc/6911/cgroup 
10:perf_event:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
9:freezer:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
8:memory:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
7:cpuset:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
6:blkio:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
5:devices:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
4:hugetlb:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
3:cpu,cpuacct:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
2:net_cls,net_prio:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
1:name=systemd:/system.slice/docker-5976e46340cc580265ac579e85712459a7a439a4a3956a48546df23296db4739.scope
```

**Comment by derekwaynecarr** [comment] 2016-02-25 22:07
Hmm... realizing that may be difficult if container never starts... will defer to @mrunalp

**Comment by smarterclayton** [comment] 2016-02-25 22:09
Probably would have to run tests over and over hoping to catch the
flake happening.  It seems rare - less than 1 in 100

**Comment by derekwaynecarr** [comment] 2016-02-25 22:13
This looked related... made me wonder if cpu,cpuacct and cpuacct,cpu were flipped...

```
$ sudo docker run --name test --rm busybox /bin/sh -c 'while true; do date; sleep 5; done'
...
$ sudo docker inspect -f '{{ .State.Pid }}' test
31524
$ cat /proc/31524/cgroup
10:perf_event:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
9:freezer:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
8:memory:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
7:cpuset:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
6:blkio:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
5:devices:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
4:hugetlb:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
3:cpu,cpuacct:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
2:net_cls,net_prio:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
1:name=systemd:/system.slice/docker-72123ae44bbc443e558392c15dbeaa49fc1944b523370663ead07ad64654fe1e.scope
$ ls /sys/fs/cgroup/
blkio  cpu  cpuacct  cpu,cpuacct  cpuset  devices  freezer  hugetlb  memory  net_cls  net_cls,net_prio  net_prio  perf_event  systemd
```

If it happens again, curious if the machine is showing a path on cpuacct,cpu instead of what is shown in /sys/fs/cgroup...

see: https://github.com/docker/docker/issues/9365

**Comment by derekwaynecarr** [comment] 2016-02-25 22:18
@smarterclayton - if it happens does it impact all containers on the box, or just random containers?

**Comment by smarterclayton** [comment] 2016-02-25 22:22
It was only this one test, so other e2e results succeeded.  This looks
like a race or other cgroup flake inside of docker on start, and
happens only rarely.  Was RHEL 7.2 - basically test pull request.

**Comment by mrunalp** [comment] 2016-02-25 23:17
Hmm, I will figure out some debugs that we can add to our docker to root cause this.

**Comment by ncdc** [comment] 2016-02-26 18:26
I have been able to report the cgroup file not found on f23, docker-1.9.1-6.git6ec29ef.fc23.x86_64.

In 1 terminal, I ran `stress -c 4`. In another terminal, I ran a single Kube e2e test (via ginkgo focus) in an endless loop until it failed. The test failed in this particular case because of the cgroup issue above.

**Comment by smarterclayton** [comment] 2016-03-06 00:42
Happened again https://ci.openshift.redhat.com/jenkins/job/origin_extended/707/console

```
Mar  5 16:20:50.810: INFO: event for sized-3-build: {kubelet 172.18.2.252} Created: Created container with docker id 46f49d8e02ab
Mar  5 16:20:50.810: INFO: event for sized-3-build: {kubelet 172.18.2.252} Failed: Failed to start container with docker id 46f49d8e02ab with error: API error (500): Cannot start container 46f49d8e02ab1a4a23d43fbfb09220697a2ca1300616c41f6cefedd3cc51fb76: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-46f49d8e02ab1a4a23d43fbfb09220697a2ca1300616c41f6cefedd3cc51fb76.scope/cpu.shares: no such file or directory

Mar  5 16:20:50.810: INFO: event for sized-3-build: {kubelet 172.18.2.252} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "docker-build" with RunContainerError: "runContainer: API error (500): Cannot start container 46f49d8e02ab1a4a23d43fbfb09220697a2ca1300616c41f6cefedd3cc51fb76: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-46f49d8e02ab1a4a23d43fbfb09220697a2ca1300616c41f6cefedd3cc51fb76.scope/cpu.shares: no such file or directory\n"
```

**Comment by ncdc** [comment] 2016-03-07 15:46
I still get this sporadically too. I think we need someone from the containers team to help us figure it out. cc @runcom @jwhonce @mrunalp 

Also, with https://github.com/kubernetes/kubernetes/pull/21349 upstream, the behavior changed such that the pod is immediately deemed Failed if a container fails to start. https://github.com/kubernetes/kubernetes/pull/22607 is an attempt at restoring the previous behavior (if a container fails to start, create another one to take its place).

**Comment by mrunalp** [comment] 2016-03-07 15:48
Thanks guys, I suspect an issue around dbus call to create the scope and will try to isolate that. Also, will have a PR ready to enable additional debugs in docker today.

**Comment by ncdc** [comment] 2016-03-07 15:49
@mrunalp sometimes I can repro quickly, sometimes not. If you would like me to try out a new build, just let me know. Thanks!

**Comment by mrunalp** [comment] 2016-03-07 15:50
Yes, will let you know once the PR is ready later today and we have a new build.

**Comment by mrunalp** [comment] 2016-03-07 20:01
@ncdc What version of systemd do you have?

**Comment by ncdc** [comment] 2016-03-07 20:03
@mrunalp systemd-222-14.fc23.x86_64

**Comment by mrunalp** [comment] 2016-03-07 20:05
@ncdc Thanks! It is looking like this may be a systemd issue as we are passing this as a property to start transient unit in systemd. https://github.com/projectatomic/docker/blob/fedora-1.9/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go#L187 I am debugging further.

**Comment by smarterclayton** [comment] 2016-03-07 22:38
Another
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5233/artifact/origin/artifacts/test-end-to-end-docker/logs/container-ruby-sample-build-1-build-sti-build.log

**Comment by mrunalp** [comment] 2016-03-08 00:13
I have created https://github.com/projectatomic/docker/pull/71 as a potential fix. Will work on getting an rpm for that to test.

**Comment by lsm5** [comment] 2016-03-08 16:40
could one of you please file an rhbz so we can include this in the docker advisory

**Comment by mrunalp** [comment] 2016-03-14 16:54
@lsm5 https://bugzilla.redhat.com/show_bug.cgi?id=1317616

**Comment by stevekuznetsov** [comment] 2016-03-17 15:11
related(??) e2e flake [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13076/console):
```
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster
info: password for stats user admin has been set to GDsFvYgQtB
Error from server: Timeout: timed out waiting for deployment test/failing-dc-mid-1 to start after 10s
!!! Error in hack/../hack/../test/end-to-end/core.sh:198
	'oc logs -f dc/failing-dc-mid' exited with status 1
```

**Comment by liggitt** [comment] 2016-03-17 15:16
> related(??) e2e flake

yup:
```
I0317 14:44:13.348760   20404 server.go:606] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"failing-dc-mid-1-deploy", UID:"b6b9badf-ec4e-11e5-ae8c-0e163dfb9171", APIVersion:"v1", ResourceVersion:"752", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 03e41d07b9d3c9149c9bb30be3dc5166a174b4311b567e5a1f3bb8e881da4a38: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-03e41d07b9d3c9149c9bb30be3dc5166a174b4311b567e5a1f3bb8e881da4a38.scope/cpu.shares: no such file or directory\n"
```

**Comment by liggitt** [comment] 2016-03-17 15:27
I'd love to add a failure indications for this. The message "cpu.shares: no such file or directory" in the /artifact/origin/artifacts/test-end-to-end-docker/logs/container-origin.log file is what to look for. Not sure failure indications can look in artifacts.

**Comment by stevekuznetsov** [comment] 2016-03-17 15:29
Is the `Error from server: User "e2e-user" cannot list all buildconfigs in the cluster` message always present? Should we just indicate on that?

**Comment by liggitt** [comment] 2016-03-17 15:29
that is unrelated

**Comment by mrunalp** [comment] 2016-03-17 19:24
@liggitt Are we archiving the systemd journal as well? It might be helpful to debug (especially if we are running into oom).

**Comment by liggitt** [comment] 2016-03-17 19:24
you can check under artifacts, but I don't think so

**Comment by smarterclayton** [comment] 2016-03-17 19:35
We are not.  Do you want a specific unit, or the entire journal?

**Comment by mrunalp** [comment] 2016-03-17 20:01
@smarterclayton The entire journal. That's where we can grep and search for ooms (that could be a possible race when cgroup.procs go missing).

**Comment by mrunalp** [comment] 2016-03-28 16:33
Can we close this issue if we aren't seeing this anymore with the new docker rpm?

**Closed** 2016-04-08 16:03 UTC
Labels: component/deployments, kind/test-flake, priority/P0
