### ISSUE TITLE
restart docker failed

### ISSUE THREAD

**Issue by rootfs** [openshift/origin#14172] opened 2017-05-12 16:10 UTC
in [test_pull_request_origin_extended_conformance_install](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/1987/consoleFull#181270559558b6e51eb7608a5981914356)
```
NOTIFIED HANDLER restart docker after updating ca trust
changed: [localhost] => {
    "changed": true, 
    "cmd": [
        "update-ca-trust"
    ], 
    "delta": "0:00:01.518595", 
    "end": "2017-05-12 11:35:13.803793", 
    "generated_timestamp": "2017-05-12 11:35:13.952238", 
    "rc": 0, 
    "start": "2017-05-12 11:35:12.285198", 
    "stderr": [], 
    "stdout": []
}

RUNNING HANDLER [openshift_node_certificates : restart docker after updating ca trust] ***
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-05-12 11:35:14.375432", 
    "msg": "Unable to restart service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"
}
META: ran handlers
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'

PLAY RECAP *********************************************************************
localhost                  : ok=451  changed=109  unreachable=0    failed=1   
```

**Comment by pweil-** [comment] 2017-05-12 16:52
duplicate of https://github.com/openshift/origin/issues/14161

**Closed by pweil-** 2017-05-12 16:52 UTC
Labels: component/install, kind/test-flake, priority/P1
