### ISSUE TITLE
Deployment hung / cancelled by early change

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9652] opened 2016-06-30 17:24 UTC
On master I ran 

```
oc cluster up
oc login -u system:admin
oc set env dc/docker-registry -n default REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true
```

in a block, and the first registry deployment was cancelled without a second one being created.  A new deployment was hit early.

I assume this is one of the upcoming fixes, but want to leave this open until that is fixed.

**Comment by smarterclayton** [comment] 2016-06-30 17:24
@kargakis

**Comment by kargakis** [comment] 2016-06-30 23:29
Is this different from https://github.com/openshift/origin/issues/9575?

**Comment by smarterclayton** [comment] 2016-07-01 00:05
Yes, in this case I did not get a second RC for 2 minutes.

**Comment by kargakis** [comment] 2016-07-01 08:54
I can't reproduce this on HEAD (note that https://github.com/openshift/origin/pull/9327 merged after you reported this). Can you try once more?
```
[vagrant@localhost origin]$ oc login -u system:admin
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
  * myproject
    openshift
    openshift-infra

Using project "myproject".
[vagrant@localhost origin]$ oc set env dc/docker-registry -n default REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true
deploymentconfig "docker-registry" updated
[vagrant@localhost origin]$ oc get po -n default
NAME                       READY     STATUS              RESTARTS   AGE
docker-registry-2-deploy   0/1       ContainerCreating   0          4s
router-1-deploy            0/1       Pending             0          14s
[vagrant@localhost origin]$ oc get rc -n default
NAME                DESIRED   CURRENT   AGE
docker-registry-1   0         0         20s
docker-registry-2   1         1         9s
router-1            0         0         20s
[vagrant@localhost origin]$ oc status -n default
In project default on server https://10.0.2.15:8443

svc/docker-registry - 172.30.64.167:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:latest 
    deployment #2 deployed 28 seconds ago - 1 pod
    deployment #1 failed 39 seconds ago: cancelled as a newer deployment was found running

svc/kubernetes - 172.30.0.1 ports 443, 53->8053, 53->8053

svc/router - 172.30.52.8 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:latest 
    deployment #1 running for 39 seconds - 1 pod

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

**Comment by smarterclayton** [comment] 2016-07-01 15:04
It was a flake, not consistent.  Will retry, but if we can't be sure of
this we may need better stress testing.

On Jul 1, 2016, at 1:54 AM, Michail Kargakis <notifications@github.com>
wrote:

I can't reproduce this on HEAD (note that #9327
<https://github.com/openshift/origin/pull/9327> merged after you reported
this). Can you try once more?

[vagrant@localhost origin]$ oc login -u system:admin
You have access to the following projects and can switch between them
with 'oc project <projectname>':

    default
  * myproject
    openshift
    openshift-infra

Using project "myproject".
[vagrant@localhost origin]$ oc set env dc/docker-registry -n default
REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true
deploymentconfig "docker-registry" updated
[vagrant@localhost origin]$ oc get po -n default
NAME                       READY     STATUS              RESTARTS   AGE
docker-registry-2-deploy   0/1       ContainerCreating   0          4s
router-1-deploy            0/1       Pending             0          14s
[vagrant@localhost origin]$ oc get rc -n default
NAME                DESIRED   CURRENT   AGE
docker-registry-1   0         0         20s
docker-registry-2   1         1         9s
router-1            0         0         20s
[vagrant@localhost origin]$ oc status -n default
In project default on server https://10.0.2.15:8443

svc/docker-registry - 172.30.64.167:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:latest
    deployment #2 deployed 28 seconds ago - 1 pod
    deployment #1 failed 39 seconds ago: cancelled as a newer
deployment was found running

svc/kubernetes - 172.30.0.1 ports 443, 53->8053, 53->8053

svc/router - 172.30.52.8 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:latest
    deployment #1 running for 39 seconds - 1 pod

View details with 'oc describe <resource>/<name>' or list everything
with 'oc get all'.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9652#issuecomment-229893742>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p83M00jXjQrvAcaSdzjxjcIbM31Jks5qRNW6gaJpZM4JCZBz>
.

**Comment by kargakis** [comment] 2016-07-01 16:33
I've opened https://github.com/openshift/origin/pull/9666

**Closed** 2016-07-02 01:33 UTC
Labels: component/deployments, priority/P1
