### ISSUE TITLE
503 Error downloading yum packages

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#12091] opened 2016-12-01 14:47 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/1857/console

Test flake when trying to download yum packages

##### Version
oc v1.3.0-rc1+1177067-1608-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. [test]

##### Current Result
```
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-24&arch=x86_64
The command '/bin/sh -c dnf -y update && dnf -y install docker glibc-langpack-en iptables openssh-clients openssh-server && dnf -y remove docker-v1.10-migrator glibc-all-langpacks selinux-policy-minimum && dnf clean all' returned a non-zero code: 1
```

##### Expected Result
success

**Comment by pweil-** [comment] 2016-12-01 15:37
dupe of https://github.com/openshift/origin/issues/11452 (fedora mirroring issues)

**Closed by pweil-** 2016-12-01 15:37 UTC
Labels: kind/test-flake
