### ISSUE TITLE
Increased registry disk usage

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9687] opened 2016-07-02 15:59 UTC
```
I0702 09:40:00.018090       1 glog.go:50] Authenticating Docker push with user "serviceaccount"
Pushing image 172.30.244.198:5000/extended-test-build-sti-labels-h7ybu-30x2g/test:latest ...
Pushed 0/11 layers, 0% complete
F0702 09:40:50.300479       1 helpers.go:107] error: build error: Failed to push image: Received unexpected HTTP status: 500 Internal Server Error
```

seen repeatedly here:
https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/326/consoleFull

**Comment by liggitt** [comment] 2016-07-03 03:19
Registry logs seem relevant:

time="2016-07-02T09:40:50.294841591Z" level=debug msg="filesystem.PutContent(\"/docker/registry/v2/repositories/extended-test-build-sti-labels-h7ybu-30x2g/test/_uploads/c9cefa44-351b-44fb-9a15-d0e8a9aa0559/startedat\")" go.version=go1.6.2 http.request.host="172.30.244.198:5000" http.request.id=bab6bf37-7255-44db-a05c-09b990be8e0e http.request.method=POST http.request.remoteaddr="172.18.10.217:55178" http.request.uri="/v2/extended-test-build-sti-labels-h7ybu-30x2g/test/blobs/uploads/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64" instance.id=c20a7dfe-3ae6-4c44-a886-7dc81b8d69ca trace.duration=140.985µs trace.file="/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=72f7c696-d5f2-4f02-97eb-c5748cdbe7dc trace.line=95 vars.name="extended-test-build-sti-labels-h7ybu-30x2g/test" 

time="2016-07-02T09:40:50.294939389Z" level=error msg="response completed with error" err.code=unknown err.detail="filesystem: mkdir /registry/docker/registry/v2/repositories/extended-test-build-sti-labels-h7ybu-30x2g: disk quota exceeded" err.message="unknown error" go.version=go1.6.2 http.request.host="172.30.244.198:5000" http.request.id=bab6bf37-7255-44db-a05c-09b990be8e0e http.request.method=POST http.request.remoteaddr="172.18.10.217:55178" http.request.uri="/v2/extended-test-build-sti-labels-h7ybu-30x2g/test/blobs/uploads/" http.request.useragent="docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=8.330966ms http.response.status=500 http.response.written=225 instance.id=c20a7dfe-3ae6-4c44-a886-7dc81b8d69ca vars.name="extended-test-build-sti-labels-h7ybu-30x2g/test" 




os/linux arch/amd64" instance.id=c20a7dfe-3ae6-4c44-a886-7dc81b8d69ca vars.name="extended-test-build-sti-labels-h7ybu-30x2g/test" 
172.18.10.217 - - [02/Jul/2016:09:40:50 +0000] "POST /v2/extended-test-build-sti-labels-h7ybu-30x2g/test/blobs/uploads/ HTTP/1.1" 500 225 "" "docker/1.10.3 go/go1.4.2 git-commit/7ffc8ee-unsupported kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64"
time

**Comment by bparees** [comment] 2016-07-03 03:51
thanks @liggitt 
I know @gabemontero fought disk quota exceeded issues previously on this test bucket, perhaps he can offer some insight if there is a value we need to bump up again.

**Comment by liggitt** [comment] 2016-07-03 04:03
Wonder if the registry is doing the right thing with shared layers or if it is re-storing them

**Comment by gabemontero** [comment] 2016-07-05 03:39
When last confronted with disk quota issues, after the [bump in allocation](https://github.com/openshift/origin/blob/master/test/extended/setup.sh#L103-L107), the test runs typically showed that the registry's volume never got above 30-something% full.  

So we are talking about an increase of 600 to 700 MiB in images stored in the registry if we are filling up the registry volume now.  I suppose that is conceivable, but my initial reaction would be along the lines of @liggitt 's ... something has changed negatively wrt how the images are stored.

@bparees - would could turn back on the [disk usage diagnostics](https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L115-L116) when the builds fail.  The `du` command in particular might shed some light for example on something like the re-storing of shared layers idea.

**Comment by bparees** [comment] 2016-07-05 03:43
> @bparees - would could turn back on the disk usage diagnostics when the builds fail. The du command in particular might shed some light for example on something like the re-storing of shared layers idea.

thanks @gabemontero, running an extended builds test here w/ the debug stuff enabled:
https://github.com/openshift/origin/pull/9696

**Comment by soltysh** [comment] 2016-07-06 09:28
I'll rise the priority to P1, since this is crucial to identify the root cause.

**Comment by legionus** [comment] 2016-07-27 13:58
I tested the old version of docker-registry (2.2) and new version (2.4 from master). I pushed  busybox image.

Old registry:
```
bash-4.2$ du -sh registry/
800K	registry/
```

New registry:
```
bash-4.2$ du -sh registry/
756K	registry/
```

Docker-registry itself doesn't compress anything. Compression occurs in the client.

**Comment by legionus** [comment] 2016-07-27 14:23
Here is the difference in objects:
```diff
--- old	2016-07-27 16:17:47.048264057 +0200
+++ new	2016-07-27 16:18:08.312264113 +0200
@@ -5,14 +5,6 @@
 registry/docker/registry/v2/repositories
 registry/docker/registry/v2/repositories/myproject
 registry/docker/registry/v2/repositories/myproject/busybox
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions/sha256
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions/sha256/48cb482d052bb7fde3d7c45f8dd2ca0cb79fff6454d2cd3e47020fc82561c1e2
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions/sha256/48cb482d052bb7fde3d7c45f8dd2ca0cb79fff6454d2cd3e47020fc82561c1e2/signatures
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions/sha256/48cb482d052bb7fde3d7c45f8dd2ca0cb79fff6454d2cd3e47020fc82561c1e2/signatures/sha256
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions/sha256/48cb482d052bb7fde3d7c45f8dd2ca0cb79fff6454d2cd3e47020fc82561c1e2/signatures/sha256/69adbdf3d689824f947572461a203f2ebd21da33e9869e4d16d0fe19f4554310
-registry/docker/registry/v2/repositories/myproject/busybox/_manifests/revisions/sha256/48cb482d052bb7fde3d7c45f8dd2ca0cb79fff6454d2cd3e47020fc82561c1e2/signatures/sha256/69adbdf3d689824f947572461a203f2ebd21da33e9869e4d16d0fe19f4554310/link
 registry/docker/registry/v2/repositories/myproject/busybox/_uploads
 registry/docker/registry/v2/repositories/myproject/busybox/_layers
 registry/docker/registry/v2/repositories/myproject/busybox/_layers/sha256
@@ -30,9 +22,6 @@
 registry/docker/registry/v2/blobs/sha256/a3
 registry/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
 registry/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data
-registry/docker/registry/v2/blobs/sha256/69
-registry/docker/registry/v2/blobs/sha256/69/69adbdf3d689824f947572461a203f2ebd21da33e9869e4d16d0fe19f4554310
-registry/docker/registry/v2/blobs/sha256/69/69adbdf3d689824f947572461a203f2ebd21da33e9869e4d16d0fe19f4554310/data
 registry/docker/registry/v2/blobs/sha256/8d
 registry/docker/registry/v2/blobs/sha256/8d/8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f
 registry/docker/registry/v2/blobs/sha256/8d/8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f/data
```

The missing BLOB is just a signature:
```json
{"header":{"jwk":{"crv":"P-256","kid":"JIF3:ZRON:ISMX:D3BR:UWGH:A7CY:5OFR:BHJX:HQZC:KAJH:4RQU:S6WW","kty":"EC","x":"IwIlfvNrMiQCbua8qxUHJ14k4yZrktV-pxy0KawSYlA","y":"LbwiC07Kb-HQllFicsdvrPNFa5211trVgSBp1ifKtHA"},"alg":"ES256"},"signature":"8VOYutjJP9ADCr3FSHj9em-G9DNto3DRBx0XL0SHSL0DSDp-bPNaLMSBw3_ffgzfzSSDIm2qI-VFgDA-MgsQsA","protected":"eyJmb3JtYXRMZW5ndGgiOjIwOTEsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNi0wNy0yN1QxNDoxMzowOVoifQ"}
```

All objects are the same size and the same a checksum. A method of storing and packing of objects has not changed between versions.

This means that the problem is not in the docker-registry.

**Comment by mfojtik** [comment] 2016-07-27 15:14
@soltysh this is not a regression or blocker it would be nice to get into the root cause, but I don't think we will have time to perform full investigation on this given the time frame we have.

**Comment by soltysh** [comment] 2016-07-28 11:38
It seemed significant right after we've switched to use the new registry. It forced us to increase the storage limits for our jenkins tests. Something has to be wrong, unless the problem magically disappeared. I'm not sure what's the current usage during our tests. I'm ok with lowering the prio for now. But investigation still should happen, imho.

**Comment by liggitt** [comment] 2016-07-28 13:44
I think it is a regression... we need positive proof that storage is doing the appropriate thing in cases like this:

* push image to crossmounttest1/foo, push image to crossmounttest1/bar
* pullthrough image from pullthroughtest1/foo (layers pulled from remote repo), push to pullthroughtest2/bar and pullthroughtest3/baz

**Comment by legionus** [comment] 2016-08-02 17:26
I checked two versions of the docker registry:
*  [v2.1.0] (https://github.com/openshift/origin/tree/77d6b243597e064d504c64fb571014afa23cd54b/pkg/dockerregistry/server)
* [v2.4.1](https://github.com/openshift/origin/tree/9ac692312a7e62c62ecb0cebb1581a138fd63d66/pkg/dockerregistry/server)

I used `test/extended/core.sh` and compared the size of the repository after its completion.

New:

```
$ oc logs docker-registry-1-lrpsv
time="2016-08-02T16:11:03.961292494Z" level=info msg="version=v2.4.1+unknown" 
time="2016-08-02T16:11:03.969825896Z" level=info msg="OpenShift middleware for storage driver initializing" 
time="2016-08-02T16:11:03.969897868Z" level=info msg="redis not configured" go.version=go1.6.3 instance.id=b0eb8418-6472-48d3-8291-0ef466152d33 
time="2016-08-02T16:11:03.976588689Z" level=info msg="Starting upload purge in 17m0s" go.version=go1.6.3 instance.id=b0eb8418-6472-48d3-8291-0ef466152d33 
time="2016-08-02T16:11:03.994061379Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.3 instance.id=b0eb8418-6472-48d3-8291-0ef466152d33 
time="2016-08-02T16:11:03.994102538Z" level=info msg="OpenShift registry middleware initializing" 
time="2016-08-02T16:11:03.994113671Z" level=info msg="Using Origin Auth handler" 
time="2016-08-02T16:11:03.995343809Z" level=debug msg="configured \"openshift\" access controller" go.version=go1.6.3 instance.id=b0eb8418-6472-48d3-8291-0ef466152d33 
time="2016-08-02T16:11:03.995602344Z" level=info msg="listening on :5000" go.version=go1.6.3 instance.id=b0eb8418-6472-48d3-8291-0ef466152d33 
172.17.0.1 - - [02/Aug/2016:16:11:07 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go-http-client/1.1"

$ oc rsh docker-registry-1-lrpsv du -sh /registry
151M	registry
```

Old:
```
$ oc logs docker-registry-1-id1od
time="2016-08-02T13:07:42.219469016Z" level=info msg="version=v2.1.0+unknown" 
time="2016-08-02T13:07:42.224204522Z" level=info msg="redis not configured" go.version=go1.6.3 instance.id=860087ca-8478-4fa9-b6ba-e55f87b99651 
time="2016-08-02T13:07:42.226737853Z" level=info msg="Starting upload purge in 56m0s" go.version=go1.6.3 instance.id=860087ca-8478-4fa9-b6ba-e55f87b99651 
time="2016-08-02T13:07:42.224251325Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.3 instance.id=860087ca-8478-4fa9-b6ba-e55f87b99651 
time="2016-08-02T13:07:42.227515346Z" level=info msg="Using Origin Auth handler" 
time="2016-08-02T13:07:42.228025112Z" level=debug msg="configured \"openshift\" access controller" go.version=go1.6.3 instance.id=860087ca-8478-4fa9-b6ba-e55f87b99651 
time="2016-08-02T13:07:42.228349534Z" level=info msg="listening on :5000" go.version=go1.6.3 instance.id=860087ca-8478-4fa9-b6ba-e55f87b99651 
172.17.0.1 - - [02/Aug/2016:13:07:50 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go-http-client/1.1"

$ oc rsh docker-registry-1-id1od du -sh /registry
151M	registry
```

But I got differences in the created directories. I think this is because of the support v2 schema.

**Comment by liggitt** [comment] 2016-08-02 19:12
does `test/extended/core.sh` include the images and builds extended tests?

**Comment by bparees** [comment] 2016-08-02 19:29
@liggitt yes assuming you don't specify any particular filter.

**Comment by liggitt** [comment] 2016-08-03 02:18
hmm, trying to square those usage numbers with @gabemontero's [comment](https://github.com/openshift/origin/issues/9687#issuecomment-230381591). @bparees, do you know if the extended tests clean up a lot of stuff in the registry when they're done? 151MB seems really low for all the test images we build

**Comment by bparees** [comment] 2016-08-03 02:57
We don't explicitly clean up anything that I know of.

Ben Parees | OpenShift

**Comment by gabemontero** [comment] 2016-08-03 03:10
That is my understanding wrt images as well.

Unless someone turned it off that i am unaware of (not at a computer at the
moment) the disk usage debug (df and du and docker info invocations) should
still be on.  We could see what the numbers look like from the next failed
test and compare with the numbers here.

**Comment by soltysh** [comment] 2016-08-03 09:11
> I used test/extended/core.sh and compared the size of the repository after its completion.

I'd suggest using `test/extended/conformance.sh`, conformance is being run during our tests, core iirc has smaller coverage.

**Comment by legionus** [comment] 2016-08-03 09:23
> I'd suggest using test/extended/conformance.sh, conformance is being run during our tests, core iirc has smaller coverage.

@soltysh  According to the [report](https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/326/consoleFull), it fell exactly in `test/extended/core.sh`.

**Comment by liggitt** [comment] 2016-08-03 13:55
if you've inspected the disk results and deduping/cross-linking is working as expected, I'm ok lowering this to p2

**Comment by legionus** [comment] 2016-08-03 14:19
@liggitt All I can say is that I don't see any difference in the amount of disk space after passing the `test/extended/core.sh` test (this test has reached the quota limit) on the old and new docker-registry.

**Comment by mfojtik** [comment] 2016-08-15 13:23
we investigated this and tried to reproduce ut with no luck, closing this until we have more reproducers.

**Closed by mfojtik** 2016-08-15 13:23 UTC
Labels: component/imageregistry, kind/test-flake, priority/P1
