### ISSUE TITLE
RESTARTS count of Pod is inaccurate

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4645] opened 2015-09-12 15:08 UTC
Env
---
~~~
$ openshift version
openshift v1.0.5-264-g11321c4
kubernetes v1.1.0-alpha.0-1605-g44c91b1
~~~~

Issue
---

- When I was watching RESTARS count of pod, the number decreased sometimes.

Reproduce steps
---

- step-1. Deploy mysql

~~~
oc new-app mysql
~~~

**NOTE:** Due to https://github.com/openshift/origin/issues/4644 , the pod will not start and repeat the restart.

- step-2. Check the RESTARTS count. 

eg. Please see below. It decreased from 16 -> 15 -> 14 -> 12.

~~~
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          6m
mysql-55-centos7-1-wd7d9    0/1       Running   16         6m
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          6m
mysql-55-centos7-1-wd7d9    0/1       Running   16         6m
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          6m
mysql-55-centos7-1-wd7d9    0/1       Running   15         6m
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          6m
mysql-55-centos7-1-wd7d9    0/1       Running   15         6m
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          7m
mysql-55-centos7-1-wd7d9    0/1       Running   14         7m
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          7m
mysql-55-centos7-1-wd7d9    0/1       Running   14         7m
knakayam@dhcp-217-81:/ssd/work$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          9m
mysql-55-centos7-1-wd7d9    0/1       Running   12         9m
~~~

**Comment by pweil-** [comment] 2015-10-16 18:17
@nak3 - this could have been caused by https://github.com/kubernetes/kubernetes/issues/13517 which we have since pulled in while rebasing.  Would you mind testing this again and confirming that your particular usecase is now fixed?

**Comment by pweil-** [comment] 2015-10-19 14:11
Tested with latest using a 1 second backoff (manually changed) and crashing mysql deployment.  Observed that the count only incremented.  I believe this is fixed.  @nak3 - please reopen if you disagree.

**Closed by pweil-** 2015-10-19 14:11 UTC
Labels: component/node, kind/bug, priority/P1

**Comment by nak3** [comment] 2015-10-20 01:17
@pweil- Sorry for my late reply. I also confirmed it and no problem for the close. Thank you for following up this report.
