### ISSUE TITLE
can not deploy app in second node "Error: build error: timeout while waiting for remote repository "https://github.com/bparees/openshift-jee-sample.git""

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin#9080] opened 2016-05-30 07:39 UTC
Hi , I have setup one master and two nodes origin environment using ansible. Version details are:

oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

I can deploy any app to node1 which is present on master instance. But whenever I try to deploy any app to node2 (using lables in project) , it always gives:

I0530 07:32:27.953895       1 docker.go:355] Using locally available image "openshift/wildfly-90-centos7@sha256:a46d11bce7a0aa72edb769ddcf3ca70ca9af3a7146e87296018c353cf3d0ce11"
I0530 07:32:27.953978       1 docker.go:475] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0530 07:32:27.954091       1 sti.go:140] Preparing to build topology/test-6:81eb658a
I0530 07:32:27.955010       1 source.go:197] Downloading "https://github.com/bparees/openshift-jee-sample.git" ...
I0530 07:32:43.955354       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build025578009
I0530 07:32:43.955630       1 fs.go:156] Removing directory '/tmp/s2i-build025578009'
F0530 07:32:43.956535       1 builder.go:204] Error: build error: timeout while waiting for remote repository "https://github.com/bparees/openshift-jee-sample.git"

I can deploy any app using docker strategy , but faced this only with source strategy.

Things I have tried are -
1) checked docker DNS, docker containers in node 2 can reach to internet and do git clone also.
2) I can also  pull docker image in node 2 and also git clone works fine.

Not sure what is the issue. Could anyone help ? 

Thanks in advance!

**Comment by priyanka5** [comment] 2016-06-03 06:51
@csrwng @bparees : any update on this? I still cant find the solution :( , would be very helpful if you can give some pointers , I will try to debug then . Thanks again!

**Comment by csrwng** [comment] 2016-06-03 12:59
@priyanka5 if the issue is a slow connection to github, a fix was merged last night with https://github.com/openshift/origin/pull/9124. Otherwise, i'd suspect a networking issue.

**Comment by priyanka5** [comment] 2016-06-06 06:35
@csrwng - thanks for the update, so I assume it is fixed in recent origin version right? I have below version already :

oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

should I update the version or is there a way to fix it in already installed version? 

Thanks a ton!

**Comment by bparees** [comment] 2016-06-10 04:43
@priyanka5 you will need to update, but we don't yet have a release that includes this fix.

**Comment by priyanka5** [comment] 2016-06-10 04:55
@bparees  - thanks , that what I was wondering. I deployed latest origin yesterday and still this error appears, hope this releases soon.

**Comment by priyanka5** [comment] 2016-06-16 06:59
@csrwng @bparees : Now I am running origin version:
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5

everything is OK but app deployment again gives this:

builder.go:204] Error: build error: timeout while waiting for remote repository "https://github.com/bparees/openshift-jee-sample.git" 

any idea? or could you please tell me the steps to debug.

Now a days I am seeing lot of challenges while testing origin installation through ansible, it used to work fine atleast with version 1.1.6.

**Comment by bparees** [comment] 2016-06-16 07:03
can you instantiate the jenkins template in your cluster, then use oc rsh to get a shell in the jenkins container?  from there, run "git clone https://github.com/bparees/openshift-jee-sample.git" and report your results.

**Comment by priyanka5** [comment] 2016-06-16 07:07
Hi @bparees - I have tried creating app using "oc new-app openshift/jenkins-1-centos7" but after going into container using oc rsh and then git clone. it gives permission denied are you a root user.

**Comment by priyanka5** [comment] 2016-06-16 07:35
Hi Ben @bparees - pasting exact result:

sh-4.2$ git clone https://github.com/bparees/openshift-jee-sample.git
fatal: could not create work tree dir 'openshift-jee-sample'.: Permission denied

**Comment by priyanka5** [comment] 2016-06-16 10:20
@ben @soltysh : In my VM NetworkManager was installed which was causing error time out during clone. I disabled it but now other problem came up. Docker registry pod is not able to connect to master which is causing build to fail as exactly this https://github.com/openshift/origin/issues/8010

would be really really helpful if you can help me on this?

thanks you so much for constantly helping.

**Comment by soltysh** [comment] 2016-06-16 12:32
@priyanka5 reading through the post, all that comes to my mind is networking issue. You should be able to rsh into the docker pod and check if you can access master healthz endpoint, like so: `curl http://<master_ip>:<master_port>/healthz`. Other option will be that service account didn't get created properly, but start with that.

**Comment by priyanka5** [comment] 2016-06-16 12:34
@soltysh : i tried that I could not curl on this from registry pod http://<master_ip>:<master_port>/healthz . it gives could not resolve hostname. How to set service account?

**Comment by soltysh** [comment] 2016-06-16 12:38
@priyanka5 if curl is not working it's networking issue still. No need to worry about service accounts in that case.

**Comment by priyanka5** [comment] 2016-06-16 12:39
@soltysh : thanks , how to debug any idea?

**Comment by soltysh** [comment] 2016-06-16 12:49
@priyanka5, sorry I'm not a network person, either [docs](https://docs.openshift.org/latest/install_config/index.html) or somebody from networking team (eg. @knobunc) will be able to help you out.

**Comment by csrwng** [comment] 2016-07-13 21:21
@priyanka5 is this still an issue?

**Comment by priyanka5** [comment] 2016-07-14 05:10
@csrwng yes its still there according to my last installation some days back. But you can close the issue, I will reopen if required.

**Closed** 2016-07-14 05:13 UTC
Labels: area/examples, component/networking, kind/question, priority/P2

**Comment by bkmagnetron** [comment] 2016-07-17 06:43
@priyanka5 @bparees @csrwng @soltysh  reopen the issue. I've installed Openshift Origin using Ansible.
```
# oc version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
```
log from build
```
I0717 06:30:03.649386       1 builder.go:57] Master version "v1.2.0", Builder version "v1.2.0"
I0717 06:30:03.716060       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0717 06:30:03.890806       1 sti.go:205] The value of ALLOWED_UIDS is [1-]
I0717 06:30:03.890843       1 sti.go:213] The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
I0717 06:30:03.902074       1 docker.go:355] Using locally available image "centos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15"
I0717 06:30:03.906015       1 sti.go:232] Creating a new S2I builder with build config: "Builder Name:\t\t\tPython 3.4\nBuilder Image:\t\t\tcentos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15\nBuilder Image Version:\t\te761571bb1bc910bda65674e0d43c4c3509a7823\nBuilder Base Version:\t\te178f1c\nSource:\t\t\t\tfile:///tmp/s2i-build680461441/upload/src\nOutput Image Tag:\t\tdjango-ex/django-example-2:ffd6400a\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAME=django-example-2,OPENSHIFT_BUILD_NAMESPACE=django-ex,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/django-ex.git,PIP_INDEX_URL=\nIncremental Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull Policy:\t\tif-not-present\nPrevious Image Pull Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered Build:\t\t\tdisabled\nWorkdir:\t\t\t/tmp/s2i-build680461441\nDocker NetworkMode:\t\tcontainer:3f83a7f33dd9a756ef3abc9939c6a51e22d0519bc97937403d75a9591d167843\nDocker Endpoint:\t\tunix:///var/run/docker.sock\n"
I0717 06:30:03.912004       1 docker.go:355] Using locally available image "centos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15"
I0717 06:30:03.923626       1 docker.go:355] Using locally available image "centos/python-34-centos7@sha256:e3ad517f317ad7a5d1939ab38e406825d2b51e9cc676df53825356fc18027c15"
I0717 06:30:03.923688       1 docker.go:475] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0717 06:30:03.923751       1 sti.go:140] Preparing to build django-ex/django-example-2:ffd6400a
I0717 06:30:04.081751       1 source.go:197] Downloading "https://github.com/openshift/django-ex.git" ...
I0717 06:30:20.081999       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build680461441
I0717 06:30:20.082028       1 fs.go:156] Removing directory '/tmp/s2i-build680461441'
F0717 06:30:20.082433       1 builder.go:204] Error: build error: timeout while waiting for remote repository "https://github.com/openshift/django-ex.git"
```

**Comment by bparees** [comment] 2016-07-18 01:12
@bkmagnetron that is likely, there are many possible causes of timeouts performing the git clone operation and networking/dns misconfiguring is a common one.

**Comment by Mangirdaz** [comment] 2016-07-18 15:19
@csrwng, I'm facing same..
o-bash-4.2$ oc version
oc v3.2.0.44
kubernetes v1.2.0-36-g4a3f9c5

sh-4.2$ curl https://./healthz --insecure     
ok                  
sh-4.2$ time curl https:///healthz --insecure                                                                                   
real    0m24.752s                                                               
user    0m0.063s                                                                
sys     0m0.104s                                                                
sh-4.2$ time curl https://openshift.default/healthz --insecure                  
curl: (6) Could not resolve host: openshift.default; Name or service not known  
real    0m23.523s                                                               
user    0m0.003s                                                                
sys     0m0.022s                                                                

I suspect skyDNS but need to check. Any hints?

**Comment by bparees** [comment] 2016-07-18 15:22
@sosiouxme do we have a CLI command that probes your network and DNS settings?  (ie spins up a pod and tries to check for external network access and DNS functionality)?

**Comment by bparees** [comment] 2016-07-18 15:24
and @Mangirdaz you should probably either piggby back on the new issue @bkmagnetron opened, or open your own issue.  This issue (the git timeouts being too short) is resolved, so any discussion here is going to muddy the waters.

**Comment by sosiouxme** [comment] 2016-07-19 21:16
There is a diagnostic that spins up a pod and tests some DNS functionality:
https://github.com/openshift/origin/blob/master/pkg/diagnostics/pod/dns.go

It could easily be modified to try to resolve an external name, or reach an
external address, but the complication is that I would not want the
diagnostic to constantly annoy people who actually want their network to be
sequestered from the internet.

**Comment by iamarshadameer** [comment] 2018-04-29 22:30
I am experiencing the same error
Using 5.2 VirtualBox
build error: timeout while waiting for remote repository.
Any help on resolving this issue?

**Comment by bparees** [comment] 2018-04-30 17:05
Generally this means either your VM can't reach the outside internet, or there's a networking config issue in your cluster.

I suggest you open a new issue against origin to request help investigating your configuration.

things you can do to help debug it:

1) oc rsh into a running pod and check if you can reach github.com from it
2) oc rsh into a running jenkins pod and try to do the git clone operation yourself
3) try git cloning a smaller repository

also I suppose I should ask what git repo you're trying to clone?  Is it public?  is it on github or a private server?  Please provide that information in the new issue you open.
