### ISSUE TITLE
Garbage collector deleted deployer pod prematurely

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#13995] opened 2017-05-02 14:10 UTC
Forking from https://github.com/openshift/origin/issues/13943#issuecomment-298450031

In at least 1 CI run, the kube garbage collector controller decided to delete the ipfailover-1-deploy pod shortly after it was created and scheduled to a node. It looks like it fell through to [here](https://github.com/openshift/origin/blob/e8d67d3ea07a726c1bbd34d5c0a86872c54567de/vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go#L358-L363) which resulted in the deletion.

cc @kargakis @mfojtik @smarterclayton @sttts @deads2k @liggitt @soltysh

**Comment by ncdc** [comment] 2017-05-02 14:11
Log file: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/1618/s3/download/scripts/test-end-to-end/logs/containers/origin.log

**Comment by kargakis** [comment] 2017-05-02 14:12
@mfojtik probably unrelated but I just realized that you set the DC ref into the deployer pods.. Should be the RC.

**Comment by mfojtik** [comment] 2017-05-02 14:12
hrm. i thought the deployer pods already have owner ref set.

**Comment by ncdc** [comment] 2017-05-02 14:14
It does, but GC couldn't find it?

**Comment by ncdc** [comment] 2017-05-02 14:14
I ran `oc delete ...; oadm ipfailover` in a loop and was not able to reproduce locally.

**Comment by mfojtik** [comment] 2017-05-29 08:16
@ncdc the https://github.com/openshift/origin/issues/13996 should properly set the owner reference for the deployer pod and also for the lifecycle pods.

@kargakis ok to close this or is there something left (besides dc->rc) ?

**Comment by kargakis** [comment] 2017-06-02 15:20
IIUC, the problem wasn't that we were setting the wrong Kind in the owner reference since the GC only cares about the UID. If that's correct, then this issue is not fixed?

**Comment by liggitt** [comment] 2017-06-02 15:35
> the GC only cares about the UID. If that's correct, then this issue is not fixed?

I don't think that is correct... GC cares about kind as well, right @deads2k ?

**Comment by kargakis** [comment] 2017-06-02 15:41
I am pretty sure we (@mfojtik and I) tested this and it was just the UID.

**Comment by deads2k** [comment] 2017-06-02 15:42
> I am pretty sure we (@mfojtik and I) tested this and it was just the UID.

If its just the UID, that sounds like a bug.

**Comment by mfojtik** [comment] 2017-06-06 08:11
@deads2k @kargakis I guess this was fixed in https://github.com/openshift/origin/pull/13996 can we close this?

**Comment by kargakis** [comment] 2017-06-06 08:12
> @deads2k @kargakis I guess this was fixed in #13996 can we close this?

IIUC, the problem wasn't that we were setting the wrong Kind in the owner reference since the GC only cares about the UID. If that's correct, then this issue is not fixed?

**Comment by mfojtik** [comment] 2017-06-06 08:20
@kargakis ah you're right. also I think I can reproduce this when I create the registry/router DC right after the master server starts, will dig deeper into this.

**Comment by mfojtik** [comment] 2017-06-06 09:01
@deads2k I did a little investigation as I can reproduce it when I run fresh new cluster and create the router right after it starts (so it might be cache issue).

What happens here is that the DC controller creates the RC "router-1" right after the server starts. Right after the "router-1-deploy" pod is created with the ownerRef set to the UUID of "router-1" RC.
Then GC decide to remove the "router-1" RC (for unknown reasons ;-). That means the "router-1-deploy" pod is also automatically deleted.
Then the DC controller recreate the RC "router-1" automatically, but since the deployer pod is now gone, it fails.

Relevant logs:
```
I0605 21:32:27.404937   31478 wrap.go:42] DELETE /api/v1/namespaces/default/replicationcontrollers/router-1: (4.472203ms) 200 [[openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/5115d70/system:serviceaccount:kube-system:generic-garbage-collector] 192.168.64.3:57376]
I0605 21:32:27.417135   31478 wrap.go:42] DELETE /api/v1/namespaces/default/pods/router-1-deploy: (4.681127ms) 200 [[openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/5115d70/system:serviceaccount:kube-system:generic-garbage-collector] 192.168.64.3:57376]
I0605 21:32:31.440483   31478 kubelet.go:1829] SyncLoop (DELETE, "api"): "router-1-deploy_default(ae4bcfb5-4a25-11e7-8329-a268e445cf32)"
I0605 21:32:31.450378   31478 kubelet.go:1829] SyncLoop (DELETE, "api"): "router-1-deploy_default(ae4bcfb5-4a25-11e7-8329-a268e445cf32)"
I0605 21:32:31.452215   31478 wrap.go:42] DELETE /api/v1/namespaces/default/pods/router-1-deploy: (5.924044ms) 200 [[openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/5115d70] 192.168.64.3:57373]
```

This is when the RC is gone:
```
I0605 21:32:27.412241   31478 garbagecollector.go:327] classify references of [v1/Pod, namespace: default, name: router-1-deploy, uid: ae4bcfb5-4a25-11e7-8329-a268e445cf32].
I0605 21:32:27.412268   31478 garbagecollector.go:373] delete object [v1/Pod, namespace: default, name: router-1-deploy, uid: ae4bcfb5-4a25-11e7-8329-a268e445cf32] with Default
```

The RC now have ownerRef to DC, so it should not be removed and also this failed before the RC has any ownerRef, so I assume there is a bug in GC and it is somehow related to the cache population.

**Comment by liggitt** [comment] 2017-06-06 16:40
@mfojtik what ownerRefs does the DC controller create the RC with?

**Comment by mfojtik** [comment] 2017-06-08 10:20
@liggitt 

```
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: router
      uid: dab1530b-4c33-11e7-80cd-a268e445cf32
```

But this was broken even before we set the ownerRef (the ownerRef to DC was added recently by @tnozicka )

**Comment by mfojtik** [comment] 2017-06-08 10:20
(the UUID is correct)

**Comment by mfojtik** [comment] 2017-06-08 10:29
@liggitt @deads2k for what is worth I also found this in logs:

```
I0608 12:27:19.896545    4273 garbagecollector.go:219] object 07d0f2ec-4c35-11e7-8bbb-a268e445cf32's owner v1/DeploymentConfig, router is not found
I0608 12:27:19.896555    4273 garbagecollector.go:327] classify references of [v1/ReplicationController, namespace: default, name: router-1, uid: 07d0f2ec-4c35-11e7-8bbb-a268e445cf32].
solid: []v1.OwnerReference(nil)
dangling: []v1.OwnerReference{v1.OwnerReference{APIVersion:"v1", Kind:"DeploymentConfig", Name:"router", UID:"07238217-4c35-11e7-8bbb-a268e445cf32", Controller:(*bool)(0xc425f163b0), BlockOwnerDeletion:(*bool)(0xc425f163b1)}}
waitingForDependentsDeletion: []v1.OwnerReference(nil)
```

Seems like the GC does not see that UUID (although without that DC exists the RC will never be created).

**Comment by smarterclayton** [comment] 2017-06-09 18:03
This is now P0 - it blew up a free-int deployment.

Some statements:

1. openshift-ansible upgrade didn't detect that deployment failed, kept going - @sdodson will look at
2. deployment ended up with a 0 scale deployment which is unacceptable - it should have rolled back and marked at previous scale
3. the GC issue shouldn't have happened

**Comment by smarterclayton** [comment] 2017-06-09 18:06
@jupierce has the data on 2 above

**Comment by smarterclayton** [comment] 2017-06-09 18:07
Fourth thing - we can't push to prod with this - what do we need to do to ensure we don't push to prod with this in place?

**Comment by jupierce** [comment] 2017-06-09 18:26
@smarterclayton Push to prod will not occur. It requires a final, manual approval by CD.

**Comment by jupierce** [comment] 2017-06-09 18:36
DC & RC yaml + events available: http://file.rdu.redhat.com/~jupierce/share/free-int-data.txt

**Comment by kargakis** [comment] 2017-06-09 18:42
Justin, can you post the API server logs too? It seems that all the posted
deployments failed due to missing deployers!

**Comment by smarterclayton** [comment] 2017-06-09 18:45
Also this is an HA etcd so it's extremely likely that race conditions happen - so it may be that this bug happens on *every* deployment, not just some.

**Comment by mfojtik** [comment] 2017-06-09 18:50
@kargakis https://github.com/openshift/origin/issues/13995#issuecomment-306425673 

in a nutshell:

1) controller create RC-1
2) controller create deployer-1
3) deployer-1 has ownerRef to RC-1
4) GC remove RC-1
5) controller create RC-1 again
6) deployer-1 now points to dead RC-1 UUID
7) GC remove deployer-1

We traced this with @sttts to the storage layer when the GC is trying to GET the DC (using dynamic client). This returns 404 and it **hits** the rest.go, so etcd is giving us 404.

**Comment by mfojtik** [comment] 2017-06-09 18:54
@kargakis @tnozicka does rollback require running deployer pod? if yes, we will be screwed that way as well. if not then i wonder why the rollback did not kicked in.

**Comment by kargakis** [comment] 2017-06-09 18:56
> We traced this with @sttts to the storage layer when the GC is trying to GET the DC (using dynamic client). This returns 404 and it hits the rest.go, so etcd is giving us 404.

So my initial guess (GC+dynamic client) wasn't off? :)

**Comment by mfojtik** [comment] 2017-06-09 18:57
@kargakis close enough, but it isn't dynamic client, we actually hit the REST endpoint and then storage gives us 404.

**Comment by smarterclayton** [comment] 2017-06-09 18:57
Yes, the quorum discussion will be to continue.

**Comment by kargakis** [comment] 2017-06-09 18:57
> @kargakis @tnozicka does rollback require running deployer pod? if yes, we will be screwed that way as well. if not then i wonder why the rollback did not kicked in.

Normal rollback, yes, automatic rollback in case of failure, no.

**Comment by mfojtik** [comment] 2017-06-09 18:57
@smarterclayton till we have quorum on quorum?

**Comment by mfojtik** [comment] 2017-06-09 18:58
@kargakis why automatic failure rollback did not kicked in? (you are more familiar with that code)

**Comment by kargakis** [comment] 2017-06-09 18:59
> @kargakis why automatic failure rollback did not kicked in? (you are more familiar with that code)

In the example you gave [here](https://github.com/openshift/origin/issues/13995#issuecomment-307470417)?

**Comment by mfojtik** [comment] 2017-06-09 19:00
@kargakis yes that is the problem we seeing in free-int, rolling back will at least allow us to proceed with upgrade (not sure in what state that will leave the prod)

**Comment by kargakis** [comment] 2017-06-09 19:01
In order for automatic rollback to work, a complete deployment needs to exist in the history of a DC.

**Comment by mfojtik** [comment] 2017-06-09 19:02
@kargakis `router-384` doesn't seems like an initial deployement.

**Comment by kargakis** [comment] 2017-06-09 19:11
@mfojtik not sure that's helpful. Do you have controller logs somewhere and the actual manifests? router-384 doesn't seem to be included in Justin's link.

**Comment by smarterclayton** [comment] 2017-06-09 19:25
All of the DCs already existed.

**Comment by mfojtik** [comment] 2017-06-09 19:34
@kargakis was answering the question of previous deployment needs to exists :-)

my question is why the automatic rollback on failure had not kicked in... 

don't have controller/api master logs, but it is easy to reproduce locally, just delete deployer pod in middle of the deployment. what @smarterclayton is saying is that in such case we should rollback automatically and not leave the deployment in failed state.

**Comment by jupierce** [comment] 2017-06-09 20:42
@kargakis Here is a snapshot of logs: http://file.rdu.redhat.com/~jupierce/share/free-int-logs.tgz

**Comment by smarterclayton** [comment] 2017-06-09 21:38
Let's spawn the "didn't rollback" as a separate high priority issue.

**Comment by kargakis** [comment] 2017-06-10 00:17
That's what I was going to suggest - opened https://github.com/openshift/origin/issues/14561

**Comment by kargakis** [comment] 2017-06-10 00:49
Two out of three controller manager instaces fail on leader election for more than 2 hours, from 18:10 up until 20:38(EOF) and there is an unusual amount of dropped watches and TLS handshake errors in the API servers.

**Comment by mfojtik** [comment] 2017-06-11 12:13
I wonder if we can enable more verbose logging in free-int, to see the REST requests at least which will give us timeline of events (why and by whom the RC/deployer was deleted)

**Comment by jupierce** [comment] 2017-06-11 12:30
Which RC? I deleted docker-registry RC in this environment before to force a redeployment. On June 8th sometime. This problem observed in free-int appears to be affecting all DCs, not just docker-registry.

**Comment by mfojtik** [comment] 2017-06-12 14:11
Seems like the wrong apiVersion in ownerRef was used: https://github.com/openshift/origin/issues/14582

**Comment by stevekuznetsov** [comment] 2017-06-12 15:11
Router/registry rollout confirmation for Ansible is here: https://github.com/openshift/openshift-ansible/pull/4402

**Closed** 2017-06-12 19:09 UTC
Labels: component/deployments, component/kubernetes, priority/P0
