### ISSUE TITLE
Jenkins failed to build binaries

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6067] opened 2015-11-24 21:28 UTC
`hack/update-generated-swagger-spec` flaked [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7443/console):
```
===== Verifying API Swagger Spec =====
Generating a fresh spec...
FAILURE: Generation of fresh spec failed:
/data/src/github.com/openshift/origin/hack/../hack/util.sh: line 28: openshift: command not found
[INFO] Creating certificates for the OpenShift server
/data/src/github.com/openshift/origin/hack/../hack/util.sh: line 82: openshift: command not found
!!! Error in /data/src/github.com/openshift/origin/hack/../hack/util.sh:82
	'openshift admin ca create-master-certs --overwrite=false --cert-dir="${MASTER_CONFIG_DIR}" --hostnames="${SERVER_HOSTNAME_LIST}" --master="${MASTER_ADDR}" --public-master="${API_SCHEME}://${PUBLIC_MASTER_HOST}:${API_PORT}"' exited with status 127
Call stack:
	1: /data/src/github.com/openshift/origin/hack/../hack/util.sh:82 configure_os_server(...)
	2: /data/src/github.com/openshift/origin/hack/update-generated-swagger-spec.sh:46 main(...)
Exiting with status 1
```

**Comment by deads2k** [comment] 2016-01-12 19:35
dupe of https://github.com/openshift/origin/issues/5627

**Closed by deads2k** 2016-01-12 19:35 UTC
Labels: kind/test-flake, priority/P2
