### ISSUE TITLE
FAILURE after 0.016s: test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default': the output content test failed

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9480] opened 2016-06-22 09:35 UTC
```
There was no error output from the command.
Running test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default'...
FAILURE after 0.016s: test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default': the output content test failed
Standard output from the command:
Waiting for pod test/cli-with-token-2 to be running, status is Pending, pod ready: false

There was no error output from the command.
!!! Error in /data/src/github.com/openshift/origin/test/end-to-end/../../hack/cmd_util.sh:230
	'return "${return_code}"' exited with status 1
Call stack:
	1: /data/src/github.com/openshift/origin/test/end-to-end/../../hack/cmd_util.sh:230 os::cmd::expect_success_and_text(...)
	2: /data/src/github.com/openshift/origin/test/end-to-end/core.sh:181 main(...)
Exiting with status 1
[INFO] Stacked plot for log subset "iops" written to /tmp/openshift/test-end-to-end-docker//logs/iops.pdf
[INFO] Stacked plot for log subset "paging" written to /tmp/openshift/test-end-to-end-docker//logs/paging.pdf
[INFO] Stacked plot for log subset "cpu" written to /tmp/openshift/test-end-to-end-docker//logs/cpu.pdf
[INFO] Stacked plot for log subset "queue" written to /tmp/openshift/test-end-to-end-docker//logs/queue.pdf
[INFO] Stacked plot for log subset "memory" written to /tmp/openshift/test-end-to-end-docker//logs/memory.pdf

[FAIL] !!!!! Test Failed !!!!

[INFO] Dumping container logs to /tmp/openshift/test-end-to-end-docker//logs
[INFO] Dumping all resources to /tmp/openshift/test-end-to-end-docker//logs/export_all.json
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2417/consoleFull
Probably a dupe of another issue but I couldn't find it. Assigning to @stevekuznetsov for triaging.

**Comment by stevekuznetsov** [comment] 2016-06-22 10:40
Looks like a dupe of https://github.com/openshift/origin/issues/9309

**Closed by stevekuznetsov** 2016-06-22 10:40 UTC
Labels: area/tests, kind/test-flake
