### ISSUE TITLE
Log websocket stays open after streaming log of stopped container

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14374] opened 2017-05-26 15:57 UTC
The web socket for the log does not close even though the pod is complete. In 1.5, the web socket would close after streaming the entire log.

Additionally, I think I've seen the web socket close immediately when there's no log content, even if the pod is still running. This is also a change from 1.5.

![screen shot 2017-05-26 at 10 03 48 am](https://cloud.githubusercontent.com/assets/1167259/26502163/af3b63dc-4209-11e7-8f48-725e0fb85573.png)

##### Version

```
$ oc version
oc v3.6.0-alpha.1+0bea328-833
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+4b3473a-839
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Open the browser developer tools.
2. Open a log for a complete pod in the web console.
3. View the Network -> WS tab to see the web socket is still open. The web console follow link and animated ellipses are visible because it is still streaming the logs.

@smarterclayton @liggitt @jwforres

**Comment by liggitt** [comment] 2017-05-26 16:00
> Additionally, I think I've seen the web socket close immediately when there's no log content, even if the pod is still running. This is also a change from 1.5.

That reminds me of https://github.com/kubernetes/kubernetes/pull/31446... I wonder if anything with the change to CRI changed header flushing behavior where the log request is returned

**Comment by spadgett** [comment] 2017-05-26 16:07
> Additionally, I think I've seen the web socket close immediately when there's no log content, even if the pod is still running. This is also a change from 1.5.

I just checked, and I seem to be wrong. I don't think this is a problem. But I can reliably reproduce the problem where the web socket doesn't close for complete pods.

**Comment by spadgett** [comment] 2017-05-26 16:09
The CLI doesn't terminate either following build logs for complete builds.

**Comment by liggitt** [comment] 2017-05-26 16:12
@soltysh @ncdc non-terminating "follow logs" API calls ring a bell for either of you?

**Comment by ncdc** [comment] 2017-05-26 16:14
@liggitt yes, without resolution - see #14148

**Comment by spadgett** [comment] 2017-05-26 16:18
Seeing events like these in my namespace.

```
5m        5m        1         nodejs-mongo-persistent-3-build   Pod                                                  Warning   FailedMount      kubelet, localhost     Unable to mount volumes for pod "nodejs-mongo-persistent-3-build_node(95abb30c-422d-11e7-823e-e21512668479)": timeout expired waiting for volumes to attach/mount for pod "node"/"nodejs-mongo-persistent-3-build". list of unattached/unmounted volumes=[docker-socket builder-dockercfg-fw54v-push builder-token-gm4vt]
5m        5m        1         nodejs-mongo-persistent-3-build   Pod                                                  Warning   FailedSync       kubelet, localhost     Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "node"/"nodejs-mongo-persistent-3-build". list of unattached/unmounted volumes=[docker-socket builder-dockercfg-fw54v-push builder-token-gm4vt]
```

**Comment by liggitt** [comment] 2017-05-26 16:33
closing as dupe of https://github.com/openshift/origin/issues/14148

**Closed by liggitt** 2017-05-26 16:33 UTC
Labels: component/logging, component/restapi, kind/bug
