### ISSUE TITLE
Can't build any docker images from git repositories that are based off of the CentOS Docker image

### ISSUE THREAD

**Issue by newswangerd** [openshift/origin#9834] opened 2016-07-13 22:07 UTC
Attempting to build docker images from Dockerfiles that extend the CentOS Docker image fail. I've attempted 3 repositories, all of which throw the same error when they reach the FROM centos part of the Dockerfile. Dockerfiles based off of Ubuntu seem to work fine.
##### Version

oc v1.3.0-alpha.2
kubernetes v1.3.0-alpha.1-331-g0522e63
##### Steps To Reproduce

oc new-project test
oc new-app https://github.com/SirTekno/centos-test
oc logs -f bc/centos-test

Also tried with: https://github.com/Unicon/shibboleth-idp-dockerized
##### Current Result

I0713 22:10:25.401600       1 source.go:197] Downloading "https://github.com/SirTekno/centos-test" ...
Step 1 : FROM centos@sha256:794a51dd9c12778b34a5f0ab76b974e772441e90ced95846ae6b3fed04bf74ce
Trying to pull repository docker.io/library/centos ... failed
F0713 22:10:26.785618       1 builder.go:204] Error: build error: manifest unknown: manifest unknown
##### Expected Result

Image should build and then exit.
##### Additional Information

Running from the attached Vagrantfile. (Note, I had to add the .txt file extension so that it would upload to github)

[Vagrantfile.txt](https://github.com/openshift/origin/files/362561/Vagrantfile.txt)

**Comment by bparees** [comment] 2016-07-14 14:02
This is a known issue with docker1.10 manifests.... @smarterclayton do we have an existing tracking issue we can dupe this against?

**Comment by SirTekno** [comment] 2016-07-14 14:07
I did some more tests and it looks like it's not pulling any of the base images with the FROM clause. Pulling images from the Docker Hub works, but building from it fails.

Works:
oc new-app tutum/hello-world

Fails:
oc new-app https://github.com/tutumcloud/hello-world

**Comment by bparees** [comment] 2016-07-14 14:11
@SirTekno try "centos/ruby-23-centos7" and see if you have the same issue, i don't think you will.

The difference is images pushed to dockerhub with a v1.9 docker client are fine, but if they were pushed with a v1.10 docker client, openshift is unable to pull them correctly right now.

**Comment by SirTekno** [comment] 2016-07-14 14:17
That seems to work. How can I tell which images were pushed with docker v1.9?

**Comment by bparees** [comment] 2016-07-14 14:21
that, i'm afraid, I do not know.  hopefully @smarterclayton or @soltysh can weigh in w/ that state of changes to openshift that will address this.

**Comment by SirTekno** [comment] 2016-07-14 14:57
Is there a way to deploy a local image to OpenShift? Whenever I try to deploy local images I always get an error.

I pulled the tutum/hello-world image, retagged it as local-test ran oc new-app local-test and got this:

```
I0714 14:39:35.111606       1 deployer.go:200] Deploying centos-test/local-test-1 for the first time (replicas: 1)
I0714 14:39:35.122925       1 recreate.go:126] Scaling centos-test/local-test-1 to 1 before performing acceptance check
I0714 14:39:37.159716       1 recreate.go:131] Performing acceptance check of centos-test/local-test-1
I0714 14:39:37.162421       1 lifecycle.go:445] Waiting 600 seconds for pods owned by deployment "centos-test/local-test-1" to become ready (checking every 1 seconds; 0 pods previously accepted)
F0714 14:49:37.163098       1 deployer.go:70] update acceptor rejected centos-test/local-test-1: pods for deployment "centos-test/local-test-1" took longer than 600 seconds to become ready
```

I create a local docker registry using the following guide: https://docs.docker.com/registry/deploying/, pushed my local-test image to it and got this error when I tried to deploy it to OpenShift with oc new-app localhost:5000/local-test.

`error: no match for "localhost:5000/local-test"`

**Comment by miminar** [comment] 2016-07-14 15:21
>That seems to work. How can I tell which images were pushed with docker v1.9?

@SirTekno If you have docker < 1.10, you can do a simple test.

1. pull by tag `docker pull hello-world`; Docker will print a manifest of pulled digest. E.g.:
   ```
    Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
    Status: Downloaded newer image for hello-world:latest
   ```

2. use the digest to pull the image by the ID: `docker pull hello-world@sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9`

If it fails with `manifest unknown: manifest unknown`, the manifest is of schema v2 (the image was published
with docker >= 1.10).

If you have docker >= 1.10, and older pre 3.3, you can:

1. the same as before

2. `oc import-image --from docker.io/hello-world@sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9 isname:tag`

You will see `import failed`.

**Comment by kamikazechaser** [comment] 2016-07-20 08:19
@SirTekno How exactly did you get Ubuntu working? Cause I get errors when trying to use a specific type of Ubuntu from the Public Docker Registry. Check out the exact problem here #9910

**Comment by SirTekno** [comment] 2016-07-20 13:14
The image that I was building with was using an older version of Ubuntu. If you want to test it you can do:

```
oc new-project test
oc new-app https://github.com/SirTekno/ubuntu-test --strategy=docker
```

That build the following Dockerfile, which does nothing more than prove that it's possible to build older images. I think that version of ubuntu was pushed 6 months ago.

```
FROM ubuntu:14.04.3
MAINTAINER David
```

I'm not sure we're trying to do the same thing. I've been having trouble building images, whereas it sounds like you're having trouble deploying pre-built images.

**Comment by debianmaster** [comment] 2016-08-05 15:38
i was able to deploy this type of images with  `oc run`  instead of `oc new-app`
just fyi

**Comment by jmarley** [comment] 2016-08-30 22:52
Is there any movement on this? Currently we are running into issues in the enterprise release.
Many thanks!
Jason

**Comment by bparees** [comment] 2016-08-30 22:58
@jmarley that is a different issue...   what registry is "jmarley:indigo-ros-base" supposed to be in?  and under what org/namespace?  since you didn't specify an org/namespace in your FROM, docker is looking for it in the "library" org.

**Comment by jmarley** [comment] 2016-08-30 23:43
@bparees good catch. I'm actually trying to work around this issue with the ROS images being build with docker 1.9 and OSE using docker 1.10. This is the error I'm getting

**Comment by bparees** [comment] 2016-08-31 00:01
@jmarley can you share your buildconfig definition?

**Comment by yoshiwaan** [comment] 2016-10-02 22:49
Not using a 'from imagestreamtag' section under the Docker strategy enabled me to work around this, although I'm pretty sure you lose upstream build triggers doing that.

**Comment by bparees** [comment] 2016-10-03 00:35
Yes both of those things are true. 

@smarterclayton  can this be closed (do we handle these manifests cleanly now?)

**Comment by metal3d** [comment] 2016-10-28 10:28
The problem is still here... with alpine image for example

**Comment by bparees** [comment] 2016-10-28 13:48
@metal3d are you seeing the manifest unknown problem or something else?  can you provide a log?  what origin/openshift release version are you on?

@mfojtik assigning to you since manifest issues are the imagestream domain.

**Comment by rudijs** [comment] 2016-11-01 15:03
@bparees @mfojtik  Hi Ben, Michal,

Seeing this issue as well.

We're using Docker 1.9
OpenShift Master: v1.1.4
Kubernetes Master: v1.2.0-origin-41-g91d3e75

We have a Dockerfile that wants to pull the official influxdb image:

```
Step 1 : FROM influxdb@sha256:68cad9db73b263e0a47cb39769a3f2998f7e127c6001a5bac5ff9be268d921bd
Trying to pull repository docker.io/library/influxdb ... failed
F1101 14:47:12.610360       1 builder.go:204] Error: build error: manifest unknown: manifest unknown
```

I don't have access to the OS running Openshift, but I believe is Centos7 w/ Selinux enforcing.

If there's any more information I can provide, please let me know.

Thanks.

**Comment by bparees** [comment] 2016-11-01 15:16
@rudijs can I see your buildconfig yaml?   there is a workaround you can apply, but the better solution would be to upgrade to a newer openshift version that properly handles the v2 manifests.

**Comment by rudijs** [comment] 2016-11-02 01:19
@bparees Hi Ben,

In my local dev it's not a problem using v1.3 (of course), it's the v1.1 in the datacenter that's the issue.

It's not so easy for them to upgrade - sadly.

I'd love to see the workaround and see if that can help.

Here's a build config:

```
apiVersion: v1
kind: BuildConfig
metadata:
  name: influxdb2
  namespace: api-monitoring-dev
  selfLink: /oapi/v1/namespaces/api-monitoring-dev/buildconfigs/influxdb2
  uid: 08cd7f65-a042-11e6-b56a-005056957fc1
  resourceVersion: '17419056'
  creationTimestamp: '2016-11-01T14:46:55Z'
  labels:
    build: influxdb2
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: vJT1GLWfNigp36MjmvHo
    -
      type: Generic
      generic:
        secret: ELTdsPvvvR_koUahO0_y
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChange:
        lastTriggeredImageID: 'influxdb@sha256:68cad9db73b263e0a47cb39769a3f2998f7e127c6001a5bac5ff9be268d921bd'
  source:
    type: Git
    git:
      uri: 'https://github.com/<redacted>/apifactory-tools.git'
      httpProxy: 'http://10.144.76.10:8080'
      httpsProxy: 'http://10.144.76.10:8080'
    contextDir: local-dev-stack/monitoring/influxdb
    sourceSecret:
      name: deployer-user-password
    secrets: []
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: api-monitoring-dev
        name: 'influxdb:0.13-alpine'
  output:
    to:
      kind: ImageStreamTag
      name: 'influxdb2:latest'
  resources: {  }
  postCommit: {  }
status:
  lastVersion: 2
```

**Comment by bparees** [comment] 2016-11-02 01:28
@rudijs the workaround is to change this:

```
from:
        kind: ImageStreamTag
        namespace: api-monitoring-dev
        name: 'influxdb:0.13-alpine'
```

to something like this:
```
from:
        kind: DockerImage
        name: 'docker.io/library/influxdb:latest'
```

But you will lose the ability to do imagechangetriggers on your buildconfig.  (your build will no longer be based on an imagestreamtag, it will be just directly referencing a particular docker pull spec)

**Comment by rudijs** [comment] 2016-11-02 01:59
@bparees OK great. I'll implement this shortly and reply with the results.

Thank you very muchly!

**Comment by rudijs** [comment] 2016-11-02 03:16
@bparees Ben,

Yep that's working OK now.

Here's some partial log output

```
Step 1 : FROM docker.io/influxdb
Trying to pull repository docker.io/library/influxdb ... Pulling from library/influxdb
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Pulling fs layer
Downloading [==================================================>]     32 B/32 B
Downloading
Verifying Checksum
Download complete
```

Thanks again.

**Comment by bparees** [comment] 2016-11-02 03:26
Great, glad we could get you going.

**Comment by rudijs** [comment] 2016-11-02 03:57
@bparees 

Can we also apply this to deployment configs?

In the case of 'oc new-app' that pulls and uses an image from hub.docker.com - no build.

Here's a sample for mongodb:

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mongo
  namespace: api-monitoring-dev
  selfLink: /oapi/v1/namespaces/api-monitoring-dev/deploymentconfigs/mongo
  uid: ca13efe6-a0af-11e6-b56a-005056957fc1
  resourceVersion: '17476271'
  creationTimestamp: '2016-11-02T03:52:35Z'
  labels:
    app: mongo
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {  }
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - mongo
        from:
          kind: ImageStreamTag
          name: 'mongo:latest'
        lastTriggeredImage: 'mongo@sha256:dc05aaadac3fc3a14147e9d68246a59d7b050ab373406d96096d3639387926bd'
  replicas: 1
  test: false
  selector:
    app: mongo
    deploymentconfig: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
        deploymentconfig: mongo
      annotations:
        openshift.io/container.mongo.image.entrypoint: '["/entrypoint.sh","mongod"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        -
          name: mongo-volume-1
          emptyDir: {  }
        -
          name: mongo-volume-2
          emptyDir: {  }
      containers:
        -
          name: mongo
          image: 'mongo@sha256:dc05aaadac3fc3a14147e9d68246a59d7b050ab373406d96096d3639387926bd'
          ports:
            -
              containerPort: 27017
              protocol: TCP
          resources: {  }
          volumeMounts:
            -
              name: mongo-volume-1
              mountPath: /data/configdb
            -
              name: mongo-volume-2
              mountPath: /data/db
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {  }
status:
  latestVersion: 1
  details:
    causes:
      -
        type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            name: 'mongo:latest'
```

**Comment by rudijs** [comment] 2016-11-02 04:18
@bparees Regarding the previous message, if we can do the work around in the deployment config a work around is to use a github repo with a simple docker file.

For example:

Not this: `oc new-app --name=mongo --docker-image=mongo:latest`

Do this: `oc new-app --name=mongo https://github.com/rudijs/os-mongodb.git`

And the github repo has a Dockerfile with one line `FROM mongo:latest`

**Comment by bparees** [comment] 2016-11-02 04:21
for the deploymentconfig you can do the same thing as the buildconfig..in that case you'd need to delete the imagechangetrigger section entirely, and then replace the template.spec.container.image field with the docker pull spec for the image you want to deploy (making sure to specify the openshift registry as part of the spec if it's an image that lives in the openshift registry as opposed to docker.io)

but there's nothing you can directly do w/ new-app to force that behavior, you'll have to edit the deploymentconfig after it is created, if you are creating things via new-app.

**Comment by rudijs** [comment] 2016-11-02 04:26
OK cool, I'm updating the wrong section then.

I'll try this out later today and report back here, useful for other who run into this as well.

**Comment by rudijs** [comment] 2016-11-02 06:28
@bparees Ben,

Yep all good for deployment config.

Example usage:

`oc new-app --name=mongo2 --docker-image=mongo:latest`

Then exactly as you've directed, edit the deployment config, remove the imagechangetrigger completely, and edit the template.spec.container.image to point to the registry (docker.io in this case)

```
    spec:
      volumes:
        -
          name: mongo2-volume-1
          emptyDir: {  }
        -
          name: mongo2-volume-2
          emptyDir: {  }
      containers:
        -
          name: mongo2
          image: 'docker.io/library/mongo:latest'
```

For launching an official image direct from hub.docker.com I prefer this method, no build config, just a deployment config.

I have the manifests issue in both build and deploy configs, so as of this moment the workaround fixes both cases.

Happy days again :-)

**Comment by bparees** [comment] 2016-11-02 12:44
Great!

Ben Parees | OpenShift

**Comment by rudijs** [comment] 2016-11-15 08:44
@bparees Hi Ben,

For launching an official image direct from hub.docker.com, I'm having trouble figuring out the URL to use to 'non-official' images like this: https://hub.docker.com/r/mhart/alpine-node/

docker.io/library/alpine-node won't work.

It's not so easy to find the source URL from dockers free registry.

Can I bother you to ask for any pro tip on how to find this out?

Cheers

**Comment by rudijs** [comment] 2016-11-15 09:42
@bparees Please disregard. The URL need is just docker.io/mhart/alpine-node:6

Just trial and error, then I found it.

**Comment by bparees** [comment] 2017-01-24 22:06
this seems resolved.

**Closed by bparees** 2017-01-24 22:06 UTC
Labels: component/build, kind/question, priority/P3
