### ISSUE TITLE
test/cmd/basicresources.sh:37: executing 'curl -k ${API_SCHEME}://${API_HOST}:${API_PORT}/version' expecting success and text 'v1\.3\.0\+57fb9ac': the output content test failed

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9844] opened 2016-07-14 10:59 UTC
```
FAILURE after 0.529s: test/cmd/basicresources.sh:37: executing 'curl -k ${API_SCHEME}://${API_HOST}:${API_PORT}/version' expecting success and text 'v1\.3\.0\+57fb9ac': the output content test failed
Standard output from the command:
{
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.0+57fb9ac",
  "gitCommit": "57fb9ac",
  "gitTreeState": "clean",
  "buildDate": "2016-07-14T09:51:15Z",
  "goVersion": "go1.6.2",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/3333/consoleFull
Not sure why this flaked but it did @deads2k

**Comment by deads2k** [comment] 2016-07-14 11:55
@stevekuznetsov told you flakes weird sometimes.

**Comment by stevekuznetsov** [comment] 2016-07-14 13:05
Dupe of #9371

**Closed by stevekuznetsov** 2016-07-14 13:05 UTC
Labels: area/tests, kind/test-flake, priority/P2
