### ISSUE TITLE
origin-custom-docker-builder doesn't work if docker version is different

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4390] opened 2015-08-27 07:12 UTC
Env:
---

~~~
$ openshift version
openshift v1.0.5-56-gd116340
kubernetes v1.1.0-alpha.0-1605-g44c91b1
~~~

~~~
$ docker version
Client version: 1.6.2.fc21
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): c3ca5bb/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2.fc21
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): c3ca5bb/1.6.2
OS/Arch (server): linux/amd64
~~~~
NOTE: This docker version is openshift host system's.

Issue:
---
* When we use differnet version between the docker client(inside origin-custom-docker-builder) and server(openshift running system), we can't build with origin-custom-docker-builder.
* As a workaround, we can modify `openshift/origin-base` of Dockerfile and rebuild it, but it is just temporary solution. (Because we need to keep same docker version of `openshift/origin-base`) Are there any way to avoid/fix this issue?

Reproduce steps:
---

* Step-1. Running docker 1.6 (1.6 has the Server API versoin as 1.18)

~~~
$ docker version |grep "Server API"
Server API version: 1.18
~~~~

* Step-2. Start openshift origin

* Step-3. Create template which has in `$ORIGIN/examples/sample-app/application-template-custombuild.json`

~~~
oc create -f examples/sample-app/application-template-custombuild.json
~~~

* Step-4. Create application

~~~
oc new-app --template=ruby-helloworld-sample
~~~

* Step-5. Check the build-log

~~~
$ oc build-logs ruby-sample-build-1
Sending build context to Docker daemon 79.87 kB
Sending build context to Docker daemon 
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

$ oc get build
NAME                  TYPE      STATUS     POD
ruby-sample-build-1   Custom    Failed     ruby-sample-build-1-build
~~~

**Comment by smarterclayton** [comment] 2015-08-28 11:58
@bparees this is pretty significant - could be our API calls (client library shouldn't fail like this), or the embedded docker command.

**Comment by smarterclayton** [comment] 2015-08-28 11:58
P1

**Comment by mfojtik** [comment] 2015-08-28 12:15
@smarterclayton @bparees I think this might have something with the go-dockerclient bump we did last week or so

**Comment by mfojtik** [comment] 2015-08-28 12:17
The `docker` binary inside the custom builder image is:

```console
[root@f1758f043436 /]# docker version
Client version: 1.7.1
Client API version: 1.19
```

**Comment by mfojtik** [comment] 2015-08-28 12:20
OK, I think I know what is going on here... the centos:centos7 version of docker has client API 1.19 while the Fedora 21 has docker api 1.18

**Comment by mfojtik** [comment] 2015-08-28 12:22
@smarterclayton @danmcp is there anyone we can contact regarding bumping the Fedora 21 docker version to match with centos 7?

**Comment by mfojtik** [comment] 2015-08-28 12:37
@lsm5 ping :-)

**Comment by lsm5** [comment] 2015-08-28 16:09
done, please get a +3 at https://bodhi.fedoraproject.org/updates/docker-io-1.8.1-2.git32b8b25.fc21 for expedited move to -updates

**Comment by nak3** [comment] 2015-08-28 17:16
I tested.

Good news: docker 1.8 has different api(1.20) from CentOS7 (1.18), but this error didn't happen.
Bad news : After S2I build with docker 1.8, it can't push to docker registry and build failed. I reported here https://github.com/openshift/origin/issues/4415

**Comment by bparees** [comment] 2015-08-29 01:55
So at the end of the day is there anything we can do here?  if go-dockerclient isn't backwards compatible to older docker api versions, i think we're pretty stuck, right? (other than ensuring people can update their older dockers)

**Comment by smarterclayton** [comment] 2015-08-29 12:04
Need to make go docker client backward compatible

On Aug 28, 2015, at 9:55 PM, Ben Parees <notifications@github.com> wrote:

So at the end of the day is there anything we can do here? if
go-dockerclient isn't backwards compatible to older docker api versions, i
think we're pretty stuck, right? (other than ensuring people can update
their older dockers)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4390#issuecomment-135927172>.

**Comment by mfojtik** [comment] 2015-09-02 18:14
@nak3 can you confirm the issue is now fixed? F21 should get docker 1.8 today

**Comment by nak3** [comment] 2015-09-02 23:59
@mfojtik 
docker 1.8 package is still testing status at this moment[1]. So, we got 1.7 package and  1.7 is supposed to be broken[2][3].

[1] https://bodhi.fedoraproject.org/updates/?packages=docker-io
[2]
~~~
# yum info docker-io |grep Version
Version     : 1.7.1
~~~
[3] http://post-office.corp.redhat.com/archives/aos-devel/2015-September/msg00009.html (internal)

MEMO: And if I update to 1.8, I think I will hit this issue https://github.com/openshift/origin/issues/4415

**Comment by lsm5** [comment] 2015-09-03 14:19
just a headsup, 1.8.1 will get pushed to stable sometime today (the push last night failed) because it got +3 karma, also @ncdc mentioned you're looking at fixing the openshift registry..so i'm hoping the registry issue won't be a pain anymore for 1.8.1??

**Comment by liggitt** [comment] 2015-09-03 14:22
The problem is actually with docker 1.8 using a new method that is not supported by older registries... the client should really be more backwards-compatible, but we're seeing if we can patch in support for the new method the 1.8 client expects

**Comment by smarterclayton** [comment] 2015-09-04 14:35
Isn't the client the thing we need to patch?  After all, doesn't this mean
custom builders won't work if Openshift isn't running on our patched
docker?  OpenShift has to run on bone stock Docker.

On Sep 3, 2015, at 10:22 AM, Jordan Liggitt <notifications@github.com>
wrote:

The problem is actually with docker 1.8 using a new method that is not
supported by older registries... the client should really be more
backwards-compatible, but we're seeing if we can patch in support for the
new method the 1.8 client expects

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4390#issuecomment-137464555>.

**Comment by ncdc** [comment] 2015-09-04 14:56
registry 2.0.0 works up to Docker 1.7.

registry 2.0.1 supports Docker 1.6 (presumably) through 1.8 (I've tested 1.7 and 1.8).

**Comment by nak3** [comment] 2015-09-07 15:39
@mfojtik I confirmed that the combination of origin-docker-registry and latest docker1.8 (F21) works without issue.

**Comment by liggitt** [comment] 2015-09-08 05:28
can this be closed?

**Comment by mfojtik** [comment] 2015-09-08 07:54
Yes, this now works on F21.

**Closed** 2015-09-08 15:41 UTC
