### ISSUE TITLE
deploymentconfigs paused should disable actions on deployments flakes because of panic

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#17873] opened 2017-12-19 11:39 UTC
```
[Feature:DeploymentConfig] deploymentconfigs paused [Conformance] 
  should disable actions on deployments [Suite:openshift/conformance/parallel]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:697

[BeforeEach] [Top Level]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:53
[BeforeEach] [Feature:DeploymentConfig] deploymentconfigs
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134
STEP: Creating a kubernetes client
Dec 18 17:45:43.201: INFO: >>> kubeConfig: /tmp/cluster-admin.kubeconfig
STEP: Building a namespace api object
goroutine 130 [running]:
runtime/debug.Stack(0x0, 0xc42189e840, 0x2d)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/openshift/origin/test/extended/util.FatalErr(0x37ddb20, 0xc42004a040)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:590 +0x26
github.com/openshift/origin/test/extended/util.(*CLI).ChangeUser(0xc421696460, 0xc42189e840, 0x2d, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:114 +0xdb
github.com/openshift/origin/test/extended/util.(*CLI).SetupProject(0xc421696460, 0xc42117e860, 0x14, 0x667d340, 0xc42110e1e0, 0xc4215c0fc0, 0x2, 0x3c33ac0, 0xc4207d19c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:160 +0x251
github.com/openshift/origin/test/extended/util.(*CLI).SetupProject-fm(0xc42117e860, 0x14, 0x667d340, 0xc42110e1e0, 0xc4215c0fc0, 0xc420038a01, 0x7f7c56c906c8, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:82 +0x5c
github.com/openshift/origin/test/extended/util.createTestingNS(0xc42117e860, 0x14, 0x667d340, 0xc42110e1e0, 0xc4215c0fc0, 0xead55233ea04277f, 0x26, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:204 +0x6c4
github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework.(*Framework).CreateNamespace(0xc42085a7e0, 0xc42117e860, 0x14, 0xc4215c0fc0, 0xc4218d6e08, 0xc42140ca80, 0xc42140c801)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:373 +0x79
github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework.(*Framework).BeforeEach(0xc42085a7e0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:187 +0x893
github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework.(*Framework).BeforeEach-fm()
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134 +0x2a
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420871140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 +0x9c
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc420871140, 0xc42002b300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:63 +0x13e
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc420e8ade0, 0x6616560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes/setup_nodes.go:14 +0x7f
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc420cf8d00, 0x0, 0x6616560, 0xc420070d20)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:158 +0x1d5
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc420cf8d00, 0x6616560, 0xc420070d20)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0xe3
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc42153c000, 0xc420cf8d00, 0x1)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x10d
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc42153c000, 0x4222901)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x32c
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc42153c000, 0x8)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:64 +0xdc
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc420076370, 0x7f7c56c53548, 0xc42063e870, 0x4066dfb, 0x8, 0xc420873560, 0x2, 0x2, 0x66530c0, 0xc420070d20, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x283
github.com/openshift/origin/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x661dc60, 0xc42063e870, 0x4066dfb, 0x8, 0xc420873540, 0x2, 0x2, 0x1)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:222 +0x276
github.com/openshift/origin/vendor/github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x661dc60, 0xc42063e870, 0x4066dfb, 0x8, 0xc420236370, 0x1, 0x1, 0x1)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:210 +0x282
github.com/openshift/origin/test/extended/util.ExecuteTest(0xc42063e870, 0x4066dfb, 0x8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:160 +0x40c
github.com/openshift/origin/test/extended.TestExtended(0xc42063e870)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/extended_test.go:34 +0x40
testing.tRunner(0xc42063e870, 0x4220500)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

Dec 18 17:45:47.886: INFO: EOF
[AfterEach] [Feature:DeploymentConfig] deploymentconfigs
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:62
[AfterEach] [Feature:DeploymentConfig] deploymentconfigs
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:135
STEP: Collecting events from namespace "extended-test-cli-deployment-cxxg9-2gv8m".
STEP: Found 0 events.
Dec 18 17:45:48.011: INFO: POD                        NODE                               PHASE    GRACE  CONDITIONS
Dec 18 17:45:48.011: INFO: docker-registry-1-deploy   ci-prtest-5a37c28-13192-ig-m-25zh  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:56 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:39 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:56 +0000 UTC  }]
Dec 18 17:45:48.011: INFO: docker-registry-1-rdz95    ci-prtest-5a37c28-13192-ig-m-25zh  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:39 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:39 +0000 UTC ContainersNotReady containers with unready status: [registry]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:39 +0000 UTC  }]
Dec 18 17:45:48.011: INFO: registry-console-1-deploy  ci-prtest-5a37c28-13192-ig-n-tz76  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:01 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:01 +0000 UTC ContainersNotReady containers with unready status: [deployment]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:01 +0000 UTC  }]
Dec 18 17:45:48.011: INFO: router-1-deploy                                               Pending         [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:43:31 +0000 UTC Unschedulable 0/4 nodes are available: 4 MatchNodeSelector.}]
Dec 18 17:45:48.011: INFO: bootstrap-autoapprover-0   ci-prtest-5a37c28-13192-ig-m-25zh  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:30 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:45:18 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:30 +0000 UTC  }]
Dec 18 17:45:48.011: INFO: 
Dec 18 17:45:48.059: INFO: 
Logging node info for node ci-prtest-5a37c28-13192-ig-m-25zh
Dec 18 17:45:48.108: INFO: Node Info: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:ci-prtest-5a37c28-13192-ig-m-25zh,GenerateName:,Namespace:,SelfLink:/api/v1/nodes/ci-prtest-5a37c28-13192-ig-m-25zh,UID:13719911-e41b-11e7-8547-42010a8e0004,ResourceVersion:1440,Generation:0,CreationTimestamp:2017-12-18 17:44:19 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/instance-type: n1-standard-2,beta.kubernetes.io/os: linux,failure-domain.beta.kubernetes.io/region: us-east1,failure-domain.beta.kubernetes.io/zone: us-east1-c,kubernetes.io/hostname: ci-prtest-5a37c28-13192-ig-m-25zh,role: infra,},Annotations:map[string]string{volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:NodeSpec{PodCIDR:,ExternalID:752385569909785112,ProviderID:gce://openshift-gce-devel-ci/us-east1-c/ci-prtest-5a37c28-13192-ig-m-25zh,Unschedulable:false,Taints:[],ConfigSource:nil,},Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7674347520 0} {<nil>}  BinarySI},pods: {{20 0} {<nil>} 20 DecimalSI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7569489920 0} {<nil>}  BinarySI},pods: {{20 0} {<nil>} 20 DecimalSI},},Phase:,Conditions:[{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:19 +0000 UTC RouteCreated openshift-sdn cleared kubelet-set NoRouteCreated} {OutOfDisk False 2017-12-18 17:45:40 +0000 UTC 2017-12-18 17:44:19 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-12-18 17:45:40 +0000 UTC 2017-12-18 17:44:19 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-12-18 17:45:40 +0000 UTC 2017-12-18 17:44:19 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready True 2017-12-18 17:45:40 +0000 UTC 2017-12-18 17:44:30 +0000 UTC KubeletReady kubelet is posting ready status}],Addresses:[{InternalIP 10.142.0.4} {ExternalIP 104.196.164.139} {Hostname ci-prtest-5a37c28-13192-ig-m-25zh}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:a5e33c925af5e4a12dfd1e6168cbc9d1,SystemUUID:E830E8A6-1FFF-C831-A4BC-28A18108B929,BootID:6474e9bf-b01c-483a-b6ea-b94f93031156,KernelVersion:3.10.0-693.11.1.el7.x86_64,OSImage:Red Hat Enterprise Linux Server 7.4 (Maipo),ContainerRuntimeVersion:docker://1.12.6,KubeletVersion:v1.8.1+0d5291c,KubeProxyVersion:v1.8.1+0d5291c,OperatingSystem:linux,Architecture:amd64,},Images:[{[docker.io/openshift/node@sha256:53f60230a465d731b8946c81af569c93e6d7b5187d58b907e5dbd7a71094c84c docker.io/openshift/node:v3.7.0-rc.0] 1279914095} {[docker.io/openshift/origin-pod@sha256:e1fb9c90b6f445e13c29d411c4926b370bc9e67a57ced9cbe6cf56598ff0d12d docker.io/openshift/origin-pod:v3.9.0-alpha.0] 224804012}],VolumesInUse:[],VolumesAttached:[],},}
Dec 18 17:45:48.109: INFO: 
Logging kubelet events for node ci-prtest-5a37c28-13192-ig-m-25zh
Dec 18 17:45:48.155: INFO: 
Logging pods the kubelet thinks is on node ci-prtest-5a37c28-13192-ig-m-25zh
Dec 18 17:45:48.243: INFO: docker-registry-1-deploy started at 2017-12-18 17:44:56 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:48.244: INFO: 	Container deployment ready: true, restart count 0
Dec 18 17:45:48.244: INFO: docker-registry-1-rdz95 started at 2017-12-18 17:45:39 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:48.244: INFO: 	Container registry ready: false, restart count 0
Dec 18 17:45:48.244: INFO: bootstrap-autoapprover-0 started at 2017-12-18 17:44:30 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:48.244: INFO: 	Container signer ready: true, restart count 0
W1218 17:45:48.281257   18624 metrics_grabber.go:81] Master node is not registered. Grabbing metrics from Scheduler, ControllerManager and ClusterAutoscaler is disabled.
Dec 18 17:45:48.419: INFO: 
Latency metrics for node ci-prtest-5a37c28-13192-ig-m-25zh
Dec 18 17:45:48.419: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:43.011098s}
Dec 18 17:45:48.419: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:43.011098s}
Dec 18 17:45:48.419: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.9 Latency:21.424644s}
Dec 18 17:45:48.419: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:21.424644s}
Dec 18 17:45:48.419: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.5 Latency:10.042549s}
Dec 18 17:45:48.419: INFO: 
Logging node info for node ci-prtest-5a37c28-13192-ig-n-thxc
Dec 18 17:45:48.468: INFO: Node Info: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:ci-prtest-5a37c28-13192-ig-n-thxc,GenerateName:,Namespace:,SelfLink:/api/v1/nodes/ci-prtest-5a37c28-13192-ig-n-thxc,UID:15b4f1ee-e41b-11e7-8547-42010a8e0004,ResourceVersion:1458,Generation:0,CreationTimestamp:2017-12-18 17:44:23 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/instance-type: n1-standard-2,beta.kubernetes.io/os: linux,failure-domain.beta.kubernetes.io/region: us-east1,failure-domain.beta.kubernetes.io/zone: us-east1-c,kubernetes.io/hostname: ci-prtest-5a37c28-13192-ig-n-thxc,role: app,},Annotations:map[string]string{volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:NodeSpec{PodCIDR:,ExternalID:6107411263407145496,ProviderID:gce://openshift-gce-devel-ci/us-east1-c/ci-prtest-5a37c28-13192-ig-n-thxc,Unschedulable:false,Taints:[],ConfigSource:nil,},Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7674347520 0} {<nil>}  BinarySI},pods: {{40 0} {<nil>} 40 DecimalSI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7569489920 0} {<nil>}  BinarySI},pods: {{40 0} {<nil>} 40 DecimalSI},},Phase:,Conditions:[{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:23 +0000 UTC RouteCreated openshift-sdn cleared kubelet-set NoRouteCreated} {OutOfDisk False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:23 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:23 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:23 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready True 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:33 +0000 UTC KubeletReady kubelet is posting ready status}],Addresses:[{InternalIP 10.142.0.3} {ExternalIP 35.227.97.223} {Hostname ci-prtest-5a37c28-13192-ig-n-thxc}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:a5e33c925af5e4a12dfd1e6168cbc9d1,SystemUUID:A8273937-E4C2-0827-E601-A3465EB6B7CE,BootID:54d262a8-11f7-495b-9f61-5ffeea5dc409,KernelVersion:3.10.0-693.11.1.el7.x86_64,OSImage:Red Hat Enterprise Linux Server 7.4 (Maipo),ContainerRuntimeVersion:docker://1.12.6,KubeletVersion:v1.8.1+0d5291c,KubeProxyVersion:v1.8.1+0d5291c,OperatingSystem:linux,Architecture:amd64,},Images:[],VolumesInUse:[],VolumesAttached:[],},}
Dec 18 17:45:48.468: INFO: 
Logging kubelet events for node ci-prtest-5a37c28-13192-ig-n-thxc
Dec 18 17:45:48.533: INFO: 
Logging pods the kubelet thinks is on node ci-prtest-5a37c28-13192-ig-n-thxc
Dec 18 17:45:48.726: INFO: service-t4xch started at 2017-12-18 17:45:48 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:48.726: INFO: 	Container service-t4xch-container ready: false, restart count 0
W1218 17:45:48.780335   18624 metrics_grabber.go:81] Master node is not registered. Grabbing metrics from Scheduler, ControllerManager and ClusterAutoscaler is disabled.
Dec 18 17:45:48.919: INFO: 
Latency metrics for node ci-prtest-5a37c28-13192-ig-n-thxc
Dec 18 17:45:48.919: INFO: 
Logging node info for node ci-prtest-5a37c28-13192-ig-n-tx2w
Dec 18 17:45:48.952: INFO: Node Info: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:ci-prtest-5a37c28-13192-ig-n-tx2w,GenerateName:,Namespace:,SelfLink:/api/v1/nodes/ci-prtest-5a37c28-13192-ig-n-tx2w,UID:13e16471-e41b-11e7-8547-42010a8e0004,ResourceVersion:1445,Generation:0,CreationTimestamp:2017-12-18 17:44:20 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/instance-type: n1-standard-2,beta.kubernetes.io/os: linux,failure-domain.beta.kubernetes.io/region: us-east1,failure-domain.beta.kubernetes.io/zone: us-east1-c,kubernetes.io/hostname: ci-prtest-5a37c28-13192-ig-n-tx2w,role: app,},Annotations:map[string]string{volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:NodeSpec{PodCIDR:,ExternalID:2940202817699856920,ProviderID:gce://openshift-gce-devel-ci/us-east1-c/ci-prtest-5a37c28-13192-ig-n-tx2w,Unschedulable:false,Taints:[],ConfigSource:nil,},Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7674347520 0} {<nil>}  BinarySI},pods: {{40 0} {<nil>} 40 DecimalSI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7569489920 0} {<nil>}  BinarySI},pods: {{40 0} {<nil>} 40 DecimalSI},},Phase:,Conditions:[{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:20 +0000 UTC RouteCreated openshift-sdn cleared kubelet-set NoRouteCreated} {OutOfDisk False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:20 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:20 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:20 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready True 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:30 +0000 UTC KubeletReady kubelet is posting ready status}],Addresses:[{InternalIP 10.142.0.2} {ExternalIP 35.185.104.59} {Hostname ci-prtest-5a37c28-13192-ig-n-tx2w}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:a5e33c925af5e4a12dfd1e6168cbc9d1,SystemUUID:E0786AEC-E271-FFA1-2DEA-830F1B358600,BootID:5166d81e-432c-4baf-b56c-134ea7401671,KernelVersion:3.10.0-693.11.1.el7.x86_64,OSImage:Red Hat Enterprise Linux Server 7.4 (Maipo),ContainerRuntimeVersion:docker://1.12.6,KubeletVersion:v1.8.1+0d5291c,KubeProxyVersion:v1.8.1+0d5291c,OperatingSystem:linux,Architecture:amd64,},Images:[],VolumesInUse:[],VolumesAttached:[],},}
Dec 18 17:45:48.952: INFO: 
Logging kubelet events for node ci-prtest-5a37c28-13192-ig-n-tx2w
Dec 18 17:45:48.986: INFO: 
Logging pods the kubelet thinks is on node ci-prtest-5a37c28-13192-ig-n-tx2w
Dec 18 17:45:49.120: INFO: pod-482c9b66-e41b-11e7-acf3-0e6c6937050e started at 2017-12-18 17:45:48 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:49.121: INFO: 	Container test-container ready: false, restart count 0
Dec 18 17:45:49.121: INFO: sysctl-486d9d35-e41b-11e7-afef-0e6c6937050e started at 2017-12-18 17:45:49 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:49.121: INFO: 	Container test-container ready: false, restart count 0
W1218 17:45:49.151860   18624 metrics_grabber.go:81] Master node is not registered. Grabbing metrics from Scheduler, ControllerManager and ClusterAutoscaler is disabled.
Dec 18 17:45:49.250: INFO: 
Latency metrics for node ci-prtest-5a37c28-13192-ig-n-tx2w
Dec 18 17:45:49.250: INFO: 
Logging node info for node ci-prtest-5a37c28-13192-ig-n-tz76
Dec 18 17:45:49.276: INFO: Node Info: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:ci-prtest-5a37c28-13192-ig-n-tz76,GenerateName:,Namespace:,SelfLink:/api/v1/nodes/ci-prtest-5a37c28-13192-ig-n-tz76,UID:13a31955-e41b-11e7-8547-42010a8e0004,ResourceVersion:1446,Generation:0,CreationTimestamp:2017-12-18 17:44:20 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/instance-type: n1-standard-2,beta.kubernetes.io/os: linux,failure-domain.beta.kubernetes.io/region: us-east1,failure-domain.beta.kubernetes.io/zone: us-east1-c,kubernetes.io/hostname: ci-prtest-5a37c28-13192-ig-n-tz76,role: app,},Annotations:map[string]string{volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:NodeSpec{PodCIDR:,ExternalID:7207263705428017688,ProviderID:gce://openshift-gce-devel-ci/us-east1-c/ci-prtest-5a37c28-13192-ig-n-tz76,Unschedulable:false,Taints:[],ConfigSource:nil,},Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7674347520 0} {<nil>}  BinarySI},pods: {{40 0} {<nil>} 40 DecimalSI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{7569489920 0} {<nil>}  BinarySI},pods: {{40 0} {<nil>} 40 DecimalSI},},Phase:,Conditions:[{NetworkUnavailable False 0001-01-01 00:00:00 +0000 UTC 2017-12-18 17:44:20 +0000 UTC RouteCreated openshift-sdn cleared kubelet-set NoRouteCreated} {OutOfDisk False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:20 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:20 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:20 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready True 2017-12-18 17:45:43 +0000 UTC 2017-12-18 17:44:30 +0000 UTC KubeletReady kubelet is posting ready status}],Addresses:[{InternalIP 10.142.0.5} {ExternalIP 35.196.241.230} {Hostname ci-prtest-5a37c28-13192-ig-n-tz76}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:a5e33c925af5e4a12dfd1e6168cbc9d1,SystemUUID:07A1C1E1-7D14-9541-6516-B74A1411A8DC,BootID:35651bf0-93a6-4ea0-957b-deb8ebb91039,KernelVersion:3.10.0-693.11.1.el7.x86_64,OSImage:Red Hat Enterprise Linux Server 7.4 (Maipo),ContainerRuntimeVersion:docker://1.12.6,KubeletVersion:v1.8.1+0d5291c,KubeProxyVersion:v1.8.1+0d5291c,OperatingSystem:linux,Architecture:amd64,},Images:[{[docker.io/openshift/origin-pod@sha256:e1fb9c90b6f445e13c29d411c4926b370bc9e67a57ced9cbe6cf56598ff0d12d docker.io/openshift/origin-pod:v3.9.0-alpha.0] 224804012}],VolumesInUse:[],VolumesAttached:[],},}
Dec 18 17:45:49.276: INFO: 
Logging kubelet events for node ci-prtest-5a37c28-13192-ig-n-tz76
Dec 18 17:45:49.307: INFO: 
Logging pods the kubelet thinks is on node ci-prtest-5a37c28-13192-ig-n-tz76
Dec 18 17:45:49.443: INFO: registry-console-1-deploy started at 2017-12-18 17:45:01 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:49.443: INFO: 	Container deployment ready: false, restart count 0
Dec 18 17:45:49.443: INFO: downwardapi-volume-489ea7e6-e41b-11e7-87c5-0e6c6937050e started at 2017-12-18 17:45:49 +0000 UTC (0+1 container statuses recorded)
Dec 18 17:45:49.443: INFO: 	Container client-container ready: false, restart count 0
Dec 18 17:45:49.443: INFO: pod-init-48b173e9-e41b-11e7-afe4-0e6c6937050e started at <nil> (0+0 container statuses recorded)
W1218 17:45:49.507344   18624 metrics_grabber.go:81] Master node is not registered. Grabbing metrics from Scheduler, ControllerManager and ClusterAutoscaler is disabled.
Dec 18 17:45:49.659: INFO: 
Latency metrics for node ci-prtest-5a37c28-13192-ig-n-tz76
STEP: Dumping a list of prepulled images on each node...
Dec 18 17:45:49.686: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready


• Failure in Spec Setup (BeforeEach) [6.505 seconds]
[Feature:DeploymentConfig] deploymentconfigs
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:37
  paused [Conformance] [BeforeEach]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:692
    should disable actions on deployments [Suite:openshift/conformance/parallel]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:697

    Dec 18 17:45:47.886: EOF
```
The full log is here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17856/test_pull_request_origin_extended_conformance_gce/13192/

**Comment by tnozicka** [comment] 2018-01-04 09:36
namespace setup failed
dupe of https://github.com/openshift/origin/issues/17805

**Closed by tnozicka** 2018-01-04 09:36 UTC
Labels: component/apps, kind/test-flake, priority/P1, sig/master
