### ISSUE TITLE
test flake: TestMultipleImageChangeBuildTriggers

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4473] opened 2015-09-02 17:14 UTC
https://s3.amazonaws.com/archive.travis-ci.org/jobs/78426985/log.txt

My travis test failed spuriously AFAICS:

```
E0902 16:32:41.993489   23601 errors.go:62] apiserver received an error that is not an api.Status: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexpected HTTP status code]) [0]
--- FAIL: TestMultipleImageChangeBuildTriggers-16 (18.63s)
	imagechange_buildtrigger_test.go:439: Couldn't create BuildConfig: BuildConfig "multi-image-trigger" is forbidden: namespace integration does not exist
FAIL
```

**Comment by sosiouxme** [comment] 2015-09-02 17:14
@deads2k

**Comment by liggitt** [comment] 2015-09-02 17:15
Looks like it may have been caused by:
```
apiserver received an error that is not an api.Status: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexpected HTTP status code])
```

**Comment by liggitt** [comment] 2015-09-02 17:17
At least one other test in that run failed with a similar error:
```
failed  TestOAuthDisabled
...
etcd.go:38] Unable delete key: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexpected HTTP status code]) [0]
```

**Comment by liggitt** [comment] 2016-02-12 00:30
dupe of https://github.com/openshift/origin/issues/4473

**Closed by liggitt** 2016-02-12 00:30 UTC
Labels: area/tests, kind/test-flake, priority/P3

**Comment by sosiouxme** [comment] 2016-02-12 15:58
errr.... dupe of itself? :)

**Comment by liggitt** [comment] 2016-02-12 16:00
heh... of https://github.com/openshift/origin/issues/6447
