### ISSUE TITLE
oc cluster up is health checking on wrong URL

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9100] opened 2016-05-31 21:48 UTC
cluster up detected I had two IPs - 10.0.2.15 and 10.1.2.2.  The first is not reachable from my machine (it's the internal VM IP), the second is reachable.  During setup cluster up detects that - at the end however, when it begins health checking for the API, it does so on 10.0.2.15, not the one I selected.

```
I0531 17:46:17.365285   60168 helper.go:177] Container exists = true, running = true
   Waiting for API server to start listening
I0531 17:46:17.568564   60168 net.go:105] Got error &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc820653830), Err:(*net.timeoutError)(0x2c70588)}, trying again: "10.0.2.15:8443"
I0531 17:46:18.773292   60168 net.go:105] Got error &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc8206b04b0
```

**Comment by smarterclayton** [comment] 2016-05-31 21:49
@csrwng I noticed this on master today, let me know if you need more trace (it finds both, selects the latter, uses it for intervening commands, but at the very end goes back to using the old one).

**Comment by smarterclayton** [comment] 2016-05-31 21:54
Actually, it looks like it's failing to detect the right one (it tests both, but selects the broken one).

**Comment by smarterclayton** [comment] 2016-05-31 21:54
Also, if public-hostname is an IP, that should be used as the server IP.

**Comment by csrwng** [comment] 2016-06-01 13:05
@smarterclayton what is your setup like? Are you using a vagrant box and running 'oc' from your mac? Also if you can, please include a --loglevel=5 trace of the 'oc cluster up' run.

**Comment by smarterclayton** [comment] 2016-06-01 16:36
Hrm, it only seems to happen when I'm having network trouble.  Can't
recreate it this morning.  I suspect something about the IP detection is
off.

**Comment by csrwng** [comment] 2016-06-19 00:09
@smarterclayton I have not been able to reproduce this. What do you want to do with it?

**Comment by csrwng** [comment] 2016-06-22 14:20
@bparees

**Comment by csrwng** [comment] 2016-08-02 14:04
@smarterclayton I'm closing this because I haven't been able to reproduce. If you can reproduce or have any new info on it, please reopen.

**Closed by csrwng** 2016-08-02 14:04 UTC
Labels: area/usability, priority/P2
