### ISSUE TITLE
very short build postcommit hooks result in a hang

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12587] opened 2017-01-20 15:55 UTC
Same issue as fixed in https://github.com/openshift/origin/pull/12223

When the postcommit hook is very short (eg just an echo statement) the container starts and completes before the attach happens, which exposes a race condition in docker:  https://github.com/docker/docker/issues/29285

from @jim-minter:
> I think our options are: a) don't stream container output, only retrieve it after container termination (that's what this PR did for oc cluster up); b) fix (or get fixed) the issue upstream in Docker.

**Comment by jim-minter** [comment] 2017-01-20 16:12
@spadgett do you happen to be able to get a goroutine dump of the builder, and of the docker daemon, when this happens?

kill -6 of the builder should get a dump.
kill -10 of the docker daemon should make it write out its dump as a log entry without dying

**Comment by jim-minter** [comment] 2017-01-20 16:12
@bparees assuming it's the same issue, presumably option a isn't really acceptable and this is a question of getting https://github.com/docker/docker/issues/29285 fixed?

**Comment by bparees** [comment] 2017-01-20 16:15
@jim-minter we could probably live with (a) until we can get (b).  The current situation is pretty bad, though admittedly it seems unlikely a customer using a postcommit hook for anything "real" would actually hit it.

**Comment by bparees** [comment] 2017-01-20 16:16
but yes, we absolutely want to apply pressure to getting (b).  Perhaps we can leverage some of our docker contributors from our side.

**Comment by spadgett** [comment] 2017-01-20 16:21
@jim-minter I can grab the dumps if you need, but should be easy to reproduce with a simple post commit script like `echo hello`. Let me know if you aren't seeing it.

**Comment by jim-minter** [comment] 2017-01-20 17:38
@spadgett, yes that would be useful. I've just tried to recreate it 10 times here and no luck. If you can send logs, it would hopefully mean I can prove it's the same issue.

**Comment by spadgett** [comment] 2017-01-20 17:38
Sure, I'll get you the logs.

**Comment by spadgett** [comment] 2017-01-20 17:51
Hm, maybe it only happens when the script has multiple lines? I was testing to see if we should have a multiline editor for script in the web console. @jim-minter You might try

```yaml
  postCommit:
    script: |-
      echo hello
      echo world
```

Here's log after `docker kill -s 6`. Let me know if that's not what you wanted.

```
Cloning "https://github.com/openshift/ruby-ex.git" ...
	Commit:	855ab2de53ff897a19e1055f7554c64d19e02c50 (Merge pull request #6 from aj07/typo)
	Author:	Ionut Palade <PI-Victor@users.noreply.github.com>
	Date:	Mon Dec 12 14:37:32 2016 +0100
---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --deployment --without development:test' ...
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/..
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Installing puma 3.4.0 with native extensions
Installing rack 1.6.4
Using bundler 1.10.6
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into ./bundle.
---> Cleaning up unused ruby gems ...
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Running post commit hook ...
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
hello
world
SIGABRT: abort
PC=0x462e11 m=0
goroutine 0 [idle]:
runtime.futex(0x7998030, 0x0, 0x0, 0x0, 0x0, 0x8b4c30, 0x0, 0x0, 0x7ffc36f37440, 0x411cf2, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0x7998030, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x7998030)
	/usr/local/go/src/runtime/lock_futex.go:145 +0x82
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1594 +0xad
runtime.findrunnable(0xc42001b500, 0x0)
	/usr/local/go/src/runtime/proc.go:2021 +0x228
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2120 +0x14c
runtime.park_m(0xc420001380)
	/usr/local/go/src/runtime/proc.go:2183 +0x123
runtime.mcall(0x7ffc36f375e0)
	/usr/local/go/src/runtime/asm_amd64.s:240 +0x5b
goroutine 1 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa8a659fc28, 0x72, 0x9)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420333fe0, 0x72, 0xc420be46f8, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420333fe0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420333f80, 0xc420f36000, 0x1000, 0x1000, 0x0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002aec0, 0xc420f36000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc420ef8960)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc420ef8960, 0x436e0a, 0xc4200001a0, 0x200000003, 0xc42001b500, 0xc4200001a0, 0xc420be48d0)
	/usr/local/go/src/bufio/bufio.go:330 +0xb5
net/http/internal.readChunkLine(0xc420ef8960, 0x6, 0x6, 0x0, 0x6, 0x2)
	/usr/local/go/src/net/http/internal/chunked.go:110 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc420ef7410)
	/usr/local/go/src/net/http/internal/chunked.go:47 +0x32
net/http/internal.(*chunkedReader).Read(0xc420ef7410, 0xc420f38000, 0x8009, 0x8009, 0x458680, 0xc420be49d8, 0xc420be49e0)
	/usr/local/go/src/net/http/internal/chunked.go:77 +0x7b
net/http.(*body).readLocked(0xc420be9a00, 0xc420f38000, 0x8009, 0x8009, 0x0, 0xc420be4b48, 0x0)
	/usr/local/go/src/net/http/transfer.go:651 +0x61
net/http.(*body).Read(0xc420be9a00, 0xc420f38000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:643 +0xf6
github.com/openshift/origin/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy.StdCopy(0x69fa0a0, 0xc42002a010, 0x69fa0a0, 0xc42002a018, 0x7fa8a65f0c68, 0xc420be9a00, 0xc42002aec0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:97 +0xf6
github.com/openshift/origin/vendor/github.com/fsouza/go-dockerclient.(*Client).stream(0xc420053950, 0x43fcd20, 0x3, 0xc4206a9800, 0x75, 0x0, 0x0, 0x0, 0x0, 0x69fa0a0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/fsouza/go-dockerclient/client.go:542 +0xa64
github.com/openshift/origin/vendor/github.com/fsouza/go-dockerclient.(*Client).Logs(0xc420053950, 0xc420bdc1c0, 0x40, 0x69fa0a0, 0xc42002a010, 0x69fa0a0, 0xc42002a018, 0x10101, 0x0, 0x0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/fsouza/go-dockerclient/container.go:1215 +0x211
github.com/openshift/origin/pkg/build/builder.dockerRun.func2(0xc400000008, 0x48dd988)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/dockerutil.go:187 +0x3be
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run(0xc420c755f0, 0xc420bdc200, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go:103 +0x109
github.com/openshift/origin/pkg/build/builder.dockerRun(0x6a3e3e0, 0xc420053950, 0xc420be9680, 0x3e, 0xc420286000, 0xc420f1a000, 0x0, 0x0, 0x69fa0a0, 0xc42002a010, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/dockerutil.go:204 +0x3de
github.com/openshift/origin/pkg/build/builder.execPostCommitHook(0x6a3e3e0, 0xc420053950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420668820, 0x15, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/common.go:156 +0x5a5
github.com/openshift/origin/pkg/build/builder.(*S2IBuilder).Build(0xc42025fab0, 0xc42025fab0, 0x79b87b0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/sti.go:276 +0x2006
github.com/openshift/origin/pkg/build/builder/cmd.s2iBuilder.Build(0x6a3e3e0, 0xc420053950, 0x4469634, 0x1b, 0x6a36440, 0xc4206383c0, 0xc42062ab00, 0x7fa8a6643c18, 0xc420638400, 0xc4204c1ad0, ...)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:210 +0x1b9
github.com/openshift/origin/pkg/build/builder/cmd.(*s2iBuilder).Build(0x79b87b0, 0x6a3e3e0, 0xc420053950, 0x4469634, 0x1b, 0x6a36440, 0xc4206383c0, 0xc42062ab00, 0x7fa8a6643c18, 0xc420638400, ...)
	<autogenerated>:3 +0xcf
github.com/openshift/origin/pkg/build/builder/cmd.(*builderConfig).execute(0xc4200a8a00, 0x69fb1e0, 0x79b87b0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:162 +0x2d5
github.com/openshift/origin/pkg/build/builder/cmd.runBuild(0x69fa0a0, 0xc42002a018, 0x69fb1e0, 0x79b87b0, 0x79b87b0, 0xc42002a018)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:218 +0x6a
github.com/openshift/origin/pkg/build/builder/cmd.RunS2IBuild(0x69fa0a0, 0xc42002a018, 0xc42002a018, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/build/builder/cmd/builder.go:228 +0x6c
github.com/openshift/origin/pkg/cmd/infra/builder.NewCommandS2IBuilder.func1(0xc4208166c0, 0xc420740e60, 0x0, 0x1)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/infra/builder/builder.go:36 +0x43
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208166c0, 0xc42000c2b0, 0x1, 0x1, 0xc4208166c0, 0xc42000c2b0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4208166c0, 0xc42002a008, 0xc42002a018, 0xc4208166c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4208166c0, 0x13, 0xc4208166c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:36 +0x196
goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 5 [chan receive, 2 minutes]:
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x7996bc0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/openshift/origin/vendor/github.com/golang/glog.init.1
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:410 +0x21d
goroutine 36 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
goroutine 86 [chan receive]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4208011c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x94
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xd2
goroutine 99 [chan receive]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc420801c20)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x94
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xd2
goroutine 113 [select]:
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0x48d3bb8, 0x12a05f200, 0x0, 0x1, 0xc420066120)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:100 +0x16e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0x48d3bb8, 0x12a05f200, 0xc420066120)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x4d
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/logs.InitLogs
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/logs/logs.go:50 +0xa8
goroutine 174 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa8a659ffe8, 0x72, 0x3)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42024f5d0, 0x72, 0xc420c0d6f0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42024f5d0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42024f570, 0xc420412000, 0x800, 0x800, 0x0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42017ca30, 0xc420412000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420845050, 0x69f93e0, 0xc42017ca30, 0x5, 0xc42017ca30, 0x28)
	/usr/local/go/src/crypto/tls/conn.go:476 +0x91
crypto/tls.(*Conn).readRecord(0xc4205e6700, 0x48dea17, 0xc4205e6808, 0xc4200001a0)
	/usr/local/go/src/crypto/tls/conn.go:578 +0xc4
crypto/tls.(*Conn).Read(0xc4205e6700, 0xc420c5a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1113 +0x116
net/http.(*persistConn).Read(0xc4203b4a00, 0xc420c5a000, 0x1000, 0x1000, 0x10a50e0, 0xc420c0db58, 0x40711d)
	/usr/local/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc420ba0360)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc420ba0360, 0x1, 0xc420c0dbbd, 0x1, 0x0, 0xc4200669c0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc4203b4a00)
	/usr/local/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9
goroutine 175 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc4203b4a00)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e
goroutine 178 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa8a659ff28, 0x72, 0x5)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42034b2c0, 0x72, 0xc420c099d0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42034b2c0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42034b260, 0xc420c9a000, 0x1000, 0x1000, 0x0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42017caa0, 0xc420c9a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420310400, 0xc420c9a000, 0x1000, 0x1000, 0x10a50e0, 0xc420c09b58, 0x40711d)
	/usr/local/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc420ba10e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc420ba10e0, 0x1, 0xc420c09bbd, 0x1, 0x0, 0xc420066e40, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420310400)
	/usr/local/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9
goroutine 179 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc420310400)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e
goroutine 183 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa8a659fe68, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42034b800, 0x72, 0xc420c0b9d0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42034b800, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42034b7a0, 0xc420ca8000, 0x1000, 0x1000, 0x0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42017cad8, 0xc420ca8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420310500, 0xc420ca8000, 0x1000, 0x1000, 0x10a50e0, 0xc420c0bb58, 0x40711d)
	/usr/local/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc420ba1aa0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc420ba1aa0, 0x1, 0xc420c0bbbd, 0x1, 0x0, 0xc420ba1f80, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420310500)
	/usr/local/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9
goroutine 184 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc420310500)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e
goroutine 190 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa8a659fda8, 0x72, 0x7)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420342d80, 0x72, 0xc420cd39d0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420342d80, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420342d20, 0xc420cd4000, 0x1000, 0x1000, 0x0, 0x6a01ce0, 0xc420018130)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42017cb38, 0xc420cd4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420310600, 0xc420cd4000, 0x1000, 0x1000, 0x30, 0xc420cd3b58, 0x43e80c)
	/usr/local/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc420cc27e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc420cc27e0, 0x1, 0x0, 0x1, 0x0, 0xc4200675c0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420310600)
	/usr/local/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9
goroutine 191 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc420310600)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e
goroutine 129 [select, 4 minutes, locked to thread]:
runtime.gopark(0x48de908, 0x0, 0x4402239, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420c20f30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420c20f30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 213 [chan receive, 4 minutes]:
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run.func2(0xc4200677a0, 0xc420c755f0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go:96 +0x57
created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go:101 +0xd9
rax    0xca
rbx    0x79970d0
rcx    0x462e13
rdx    0x0
rdi    0x7998030
rsi    0x0
rbp    0x7ffc36f37410
rsp    0x7ffc36f373c8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xc4206301a0
r14    0x4439f0
r15    0x4c4acf8
rip    0x462e11
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by jim-minter** [comment] 2017-01-20 19:03
Thanks @spadgett, certainly looks similar.  Could you get the goroutine dump for the docker daemon as well?

**Comment by jim-minter** [comment] 2017-01-20 19:03
(please!)

**Comment by jim-minter** [comment] 2017-01-25 16:47
https://github.com/docker/docker/pull/30446 submitted upstream.

**Comment by spadgett** [comment] 2017-01-26 01:02
@jim-minter sorry just following up to say I'm not able to reproduce any longer, so haven't been able to get a dump for docker daemon

**Comment by jim-minter** [comment] 2017-02-01 19:00
docker/docker#30446 has merged and rebuilds for fedora & rhel are in progress.  Using a version of docker with that patch should prevent this problem.

**Closed by jim-minter** 2017-02-01 19:00 UTC
Labels: component/build, kind/bug, priority/P2
