### ISSUE TITLE
Router stops pulling config

### ISSUE THREAD

**Issue by spinolacastro** [openshift/origin#7657] opened 2016-02-26 17:35 UTC
As far as i could debug, it only happens with 1.1.3 image, after a while running the router stop refreshing the config. Some requests returns 503 error and some works fine.
Looking up the stats page i could see lot of broken endpoints and missing too.

Router pods was running and accepting connections, here's the logs:

```
I0225 21:33:06.320921       1 router.go:161] Router is including routes in all namespaces
E0225 21:37:38.938909       1 ratelimiter.go:50] error reloading router: wait: no child processes
---
+ config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ haproxy_conf_dir=/var/lib/haproxy/conf
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_be.map -o /var/lib/haproxy/conf/os_edge_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_expose.map -o /var/lib/haproxy/conf/os_edge_http_expose.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_redirect.map -o /var/lib/haproxy/conf/os_edge_http_redirect.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_reencrypt.map -o /var/lib/haproxy/conf/os_reencrypt.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_sni_passthrough.map -o /var/lib/haproxy/conf/os_sni_passthrough.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_tcp_be.map -o /var/lib/haproxy/conf/os_tcp_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=276
+ '[' -n 276 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 276
E0225 21:37:40.752585       1 ratelimiter.go:50] error reloading router: wait: no child processes
```

Destroying the pod seems to solve the issue, i'll keep looking for more info.

@smarterclayton

**Comment by smarterclayton** [comment] 2016-02-26 17:46
I've seen this happen as well.

**Comment by smarterclayton** [comment] 2016-02-26 17:46
It looks like this happens after a rolling deployment of the router, but I haven't been able to repeatedly reproduce it.  It might be related to reloading the router going from 1.1.1/2 to 1.1.3.

**Comment by spinolacastro** [comment] 2016-02-26 19:34
I happened again, adding a few more information:
My setup has two routers  (one per node), both  containers has haproxy and openshift-router running and /var/lib/haproxy/conf is filled with files (haproxy.conf is not empty)

Logging into into the container and running /var/lib/haproxy/reload-haproxy doesn't seems to reproduce the error, i ran dozen of times without any issue.

**Comment by knobunc** [comment] 2016-03-02 14:17
@ramr Any thoughts?

**Comment by ramr** [comment] 2016-03-02 21:26
@spinolacastro , do you still have the container? Would be nice to have a debug of the processes running in the router container. 
On the node where the haproxy router docker container is running,  if you could please run this: 
```  
cid=<docker-container-id>  
docker logs "$cid"
sudo nsenter -m -u -n -i -p -t  $(sudo docker inspect --format "{{ .State.Pid }}" "$cid")  <<NSEOF
ps -ef | grep haproxy    
cat /var/lib/haproxy/run/haproxy.pid  
NSEOF
```   

I think I might know what is causing that no child process error - suspect its the pid which it originally tried to do a graceful reload which was wrong but would be good to confirm.  And this could cause the haproxy processes to just stack up and something's running using an older config and didn't ever get a signal to stop listening `SIGTTOU`. The `ps` listing should tell us that.  

Thanks.

**Comment by spinolacastro** [comment] 2016-03-02 21:45
@ramr Here's the output:

```
E0302 21:44:15.522599       1 ratelimiter.go:50] error reloading router: wait: no child processes
---
+ config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ haproxy_conf_dir=/var/lib/haproxy/conf
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_be.map -o /var/lib/haproxy/conf/os_edge_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_expose.map -o /var/lib/haproxy/conf/os_edge_http_expose.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_redirect.map -o /var/lib/haproxy/conf/os_edge_http_redirect.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_reencrypt.map -o /var/lib/haproxy/conf/os_reencrypt.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_sni_passthrough.map -o /var/lib/haproxy/conf/os_sni_passthrough.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_tcp_be.map -o /var/lib/haproxy/conf/os_tcp_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=30299
+ '[' -n 30299 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 30299



$nsenter -m -u -n -i -p -t  $(sudo docker inspect --format "{{ .State.Pid }}" "$cid")  <<NSEOFps -ef | grep haproxy
cat /var/lib/haproxy/run/haproxy.pid
NSEOF

root      30343      1  0 21:44 ?        00:00:00 /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 30332
root      30352  30344  0 21:44 ?        00:00:00 grep haproxy
30343


```

**Comment by ramr** [comment] 2016-03-02 21:50
@spinolacastro  - hmm, ok there's some mismatch on the error and pid  `30299` vs `30332`. So is this container still exhibiting the problem where haproxy has stopped refreshing the config?

**Comment by spinolacastro** [comment] 2016-03-02 22:11
Yes, it's still showing errors.
Looks like after a few errors it finally refreshes the daemon.

**Comment by ramr** [comment] 2016-03-03 05:42
Ok I think we are a lot more aggressive by default with the reloads in the 1.1.3 image and that may be causing these issues. 

@spinolacastro  do you mind checking if setting an env variable ala: 
`oc env dc router RELOAD_INTERVAL=5s`   or something like 2/3 seconds (2s or 3s)    
helps?  Replace the deployment config name `router` with your router's deployment config (default is named router).   Thanks.

**Comment by spinolacastro** [comment] 2016-03-03 12:43
@ramr Looks like it did the trick, i'll test a little further and let you know.

tks

**Comment by smarterclayton** [comment] 2016-03-03 14:32
Ram, and idea what the root cause is here?  This is probably p0

**Comment by ramr** [comment] 2016-03-03 19:36
@smarterclayton  if setting the reload interval worked then it confirms the suspicion that it was the aggressive reloads we are doing with the defaults (sorta timing related - read on ...) . 
In the previous version aka prior to adding support for a reload interval, we were watching for changes to the route and endpoint objects in the object datastore (etcd) and generating the template router (haproxy) config and reloading it in-band to that processing "thread" so from a timing perspective it was slower doing the reload. 
We now have a separate goroutine that does this processing out-of-band to the watch processing which would make the router reloads (reload-haproxy script) come in a lot faster compared to the in-band processing case previously. The default reload interval is 0 seconds or no rate limiting which means we do more reloads a lot more aggressively than before. That could/should be changed to at least be 1s. 
Do you have a preference on that value or would a higher wait time - e.g. 2 seconds be too onerous?

**Comment by smarterclayton** [comment] 2016-03-03 20:18
So i would expect us never to fail like this no matter what the reload
rate.  So stopping this from failing regardless would be my
preference.

**Comment by smarterclayton** [comment] 2016-03-03 20:22
Anything timing related is a pretty serious bug and should be
identitied and fixed.  For instance, if we're racing on reload with
haproxy, then we need to detect and address the race (return something
from reload which queues reload again).  Not just bump up the limit.

**Comment by ramr** [comment] 2016-03-03 21:09
So even if we return something from the reload that queues up the reload and then redo the reload (which is really akin to the previous case where we do the reload in-band to processing the routes and so are a wee bit slower) we could still get into a similar state because of how haproxy does reloads - granted it would lessen the impact as the interval of successive reloads would be higher but my point was that this is somewhat what the reload interval of non-zero would do. 0s is basically just not throttling and sending bursts of reloads in the default case which is just an easier way to recreate the same issue. 

IMHO, would suggest taking different approach here to get rid of the restarts (or make it sorta of a no-op really) for every route/endpoint modification. That is look at making the change more dynamic (for the case haproxy maybe use the lua scripting bits - did do something similar on that end with nginx). But for the interim, suggest putting in a reasonable default for the reload interval (!= 0s basically).

**Comment by smarterclayton** [comment] 2016-03-03 21:55
i'm fine with 5s as the default.

**Comment by smarterclayton** [comment] 2016-03-03 21:56
Here's my question - this looks like a flake in the reload script.
SHouldn't A) it be impossible for two reload scripts to run at a time and
b) to know that haproxy is ready?  In which case, I don't see how this
should be happening.

**Comment by smarterclayton** [comment] 2016-03-03 21:57
My assertion right now is that even if you sent 10 reload requests a
second, they shouldn't be returning until haproxy has loaded and is
successful, in which case the next one should be able to run.

**Comment by ramr** [comment] 2016-03-04 00:22
Created a PR for the default and set it to 5 seconds.  

As re: the other comments, the reload haproxy script just calls `haproxy -f $cfg -p $pidfile -sf <pid> ` which forks and creates a haproxy daemon and that will return before the server is actually ready. That daemonized process then processes the new config and sends a signal (SIGTTOU) to the old process to tell it to stop listening on the ports and gracefully bleed off the old connections and the daemonized process binds to the ports and uses the new config. So you could potentially have multiple reloads running.

**Comment by smarterclayton** [comment] 2016-03-04 01:01
But why is it failing?  Because the next reload happens before the new
process is ready?  I don't think we want to return from reload before the
new process is ready.

On Mar 3, 2016, at 7:22 PM, Ram Ranganathan <notifications@github.com>
wrote:

Created a PR for the default and set it to 5 seconds.

As re: the other comments, the reload haproxy script just calls haproxy -f
$cfg -p $pidfile -sf <pid> which forks and creates a haproxy daemon and
that will return before the server is actually ready. That daemonized
process then processes the new config and sends a signal (SIGTTOU) to the
old process to tell it to stop listening on the ports and gracefully bleed
off the old connections and the daemonized process binds to the ports and
uses the new config. So you could potentially have multiple reloads running.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/7657#issuecomment-192034006>.

**Comment by ramr** [comment] 2016-03-04 01:29
That's more than likely the case here. Just to tighten this up a bit more, I will add a few more checks - send a signal to all the currently running haproxy pids rather than the last one and wait to see that the new process is listening on port 80 (or the http service port) in the reload script. How's that sound?

**Comment by smarterclayton** [comment] 2016-03-04 02:26
Can we use the health check port if specified in the reload script?
Trying to think of what we would do in other routers like Apache.

**Comment by ramr** [comment] 2016-03-04 02:36
I actually started on a PR and did use the health port there as we do have it ... so yeah :^)

**Comment by spinolacastro** [comment] 2016-03-04 14:18
@ramr confirming that 5s of reload interval solved my issue.

**Comment by smarterclayton** [comment] 2016-03-04 14:22
Ram reason I think we have to solve this is for an online case with >50k
routes, if there is a CPU spike the router could fail to finish in the
reload deadline and then fail, causing an outage.  So I think we have to
fix this no matter what.

**Comment by ramr** [comment] 2016-03-04 19:46
@spinolacastro  thx for checking and confirming.

@smarterclayton so waiting in the reload-script for the new process to start listening on the healthz port would gate any subsequent reloads irrespective of the deadline as it would block any other reload from happening (there's a lock in the template infra router code calling this) Plus there is a liveness probe which would handle the unhealthy cases. Let me rework the current PR (close it and open a new one).

**Closed** 2016-03-12 07:36 UTC
Labels: component/routing, priority/P0
