### ISSUE TITLE
Upstream hostPath Conformance test consistently fails on clustered env. 

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#7670] opened 2016-02-26 22:26 UTC
This test has consistently fails. 

@jayunit100 please describe repo setup and details.  

/cc @pmorie 

xref: #6882

**Comment by jayunit100** [comment] 2016-02-26 22:59
Heres what ginkgo's logs are giving.  We can follow on my adding more color in a isolated test w / describes.
```
Feb 26 17:46:01.577: INFO: ERROR kubelet_docker_errors{operation_type="inspect_container"} => 2 @[0]
Feb 26 17:46:01.577: INFO: ERROR kubelet_docker_errors{operation_type="inspect_image"} => 3 @[0]
Feb 26 17:46:01.577: INFO: ERROR kubelet_docker_errors{operation_type="list_containers"} => 2 @[0]
Feb 26 17:46:01.577: INFO: ERROR kubelet_docker_errors{operation_type="stop_container"} => 19 @[0]
Feb 26 17:46:01.577: INFO: ERROR kubelet_docker_errors{operation_type="version"} => 2 @[0]
Feb 26 17:46:01.577: INFO: 
Latency metrics for node 192.1.7.99
Feb 26 17:46:01.577: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "e2e-tests-hostpath-k3ngs" for this suite.
Feb 26 17:46:07.587: INFO: Unknown ouptut type: . Skipping.
• Failure [256.744 seconds]
hostPath
/home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/host_path.go:89
  should support r/w [Conformance] [It]
  /home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/host_path.go:88

  Expected error:
      <*errors.errorString | 0xc82112fcc0>: {
          s: "pod 'pod-host-path-test' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:2016-02-26 17:41:55 -0500 EST FinishedAt:2016-02-26 17:41:56 -0500 EST ContainerID:docker://f13164b2d3dca33ff933184275e74a4abea9a380b749b10d1950b52c0562b82a}",
      }
      pod 'pod-host-path-test' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:2016-02-26 17:41:55 -0500 EST FinishedAt:2016-02-26 17:41:56 -0500 EST ContainerID:docker://f13164b2d3dca33ff933184275e74a4abea9a380b749b10d1950b52c0562b82a}
  not to have occurred
```

**Comment by jayunit100** [comment] 2016-02-26 23:05
Note that the *other* hostPath test `should give a volume correct mode` passes.

**Comment by jayunit100** [comment] 2016-02-26 23:12
don't see anything too broken looking in the pod? it just kinda dies... 

```
Name:           pod-host-path-test                                                                                                                                                                 [4/1984]
Namespace:      e2e-tests-hostpath-d0944
Image(s):       gcr.io/google_containers/mounttest:0.6,gcr.io/google_containers/mounttest:0.6
Node:           192.1.7.32/192.1.7.32
Start Time:     Fri, 26 Feb 2016 18:10:02 -0500
Labels:         <none>
Status:         Pending
Reason:
Message:
IP:
Controllers:    <none>
Containers:
  test-container-1:
    Container ID:
    Image:              gcr.io/google_containers/mounttest:0.6
    Image ID:
    Args:
      --new_file_0644=/test-volume/test-file
      --file_mode=/test-volume/test-file
    QoS Tier:
      cpu:              BestEffort
      memory:           BestEffort
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Environment Variables:
  test-container-2:
    Container ID:
    Image:              gcr.io/google_containers/mounttest:0.6
    Image ID:
    Args:
      --file_content_in_loop=/test-volume/test-file
      --retry_time=180
    QoS Tier:
      cpu:              BestEffort
      memory:           BestEffort
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         False 
Volumes:
  test-volume:
    Type:       HostPath (bare host directory volume)
    Path:       /tmp
  default-token-57s6j:
    Type:       Secret (a secret that should populate this volume)
    SecretName: default-token-57s6j
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath                           Type            Reason          Message
  ---------     --------        -----   ----                    -------------                           --------        ------          -------
  2s            2s              1       {default-scheduler }                                            Normal          Scheduled       Successfully assigned pod-host-path-test to 192.1.7.32
  0s            0s              1       {kubelet 192.1.7.32}    spec.containers{test-container-1}       Normal          Pulling         pulling image "gcr.io/google_containers/mounttest:0.6"
```

**Comment by jayunit100** [comment] 2016-03-02 17:25
I just Confirmed this  to be a SELinux blocking  on /tmp issue with @pmorie.  Will decide how to proceed in the parent ticket.

**Comment by childsb** [comment] 2016-03-16 15:21
Closing issue since this is environment / setup.

**Closed by childsb** 2016-03-16 15:21 UTC
Labels: area/tests, component/storage, priority/P3
