### ISSUE TITLE
Possible unit test flake (Travis) - remotecommand_test.go

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4483] opened 2015-09-02 19:53 UTC
https://travis-ci.org/openshift/origin/jobs/78437644

```
--- FAIL: TestRequestExecuteRemoteCommand-2 (0.10s)
	remotecommand_test.go:112: 2: stdin: expected "a", got ""
--- FAIL: TestRequestAttachRemoteCommand-2 (0.09s)
	remotecommand_test.go:238: 0: expected an error
```

**Comment by liggitt** [comment] 2015-09-02 19:54
dupe of https://github.com/openshift/origin/issues/4157
will be fixed by andy's PR in flight upstream

**Closed by liggitt** 2015-09-02 19:54 UTC
