### ISSUE TITLE
No route to host error

### ISSUE THREAD

**Issue by sebiwi** [openshift/origin#3175] opened 2015-06-15 08:28 UTC
As of friday, I can't deploy any containers. Every container deployment fails, and I get a no route to host error.

[centos@openshift ~]$ osc logs docker-registry-1
F0615 07:35:36.168965       1 deployer.go:65] Get https://hostname.com:8443/api/v1beta3/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp IP:8443: no route to host

oc get pod <pod> -o json : http://www.fpaste.org/231165/14340371/

I'm using CentOS Linux release 7.1.1503 (Core).

**Comment by sosiouxme** [comment] 2015-06-15 13:13
Probably a duplicate of https://github.com/openshift/origin/issues/3150 ?

**Comment by liggitt** [comment] 2015-06-15 13:14
"no route to host" has nothing to do with secrets...

**Comment by liggitt** [comment] 2015-06-15 13:16
are you literally seeing "hostname.com", or did you replace the actual hostname with that for the issue?

**Comment by sebiwi** [comment] 2015-06-15 13:17
I noticed this happens when openshift-ansible updates my docker version to 1.6. It doesn't happen with 1.5. 

@liggitt: I replaced the actual hostname.

**Comment by sebiwi** [comment] 2015-06-15 16:39
Actually, this happens after running the openshift-ansible config.yaml file from the byo playbook, and it doesn't matter which version of docker I have. I already tried installing 1.6.2 and containers keep failing the same way.

Even containers deployed outside openshift (`docker run -ti ubuntu bash`) have no connectivity whatsoever. The weird part is that I had no problems before running the playbook.

**Comment by rajatchopra** [comment] 2015-06-16 05:24
Brought up a new cluster with the latest code today and the cluster seems to run fine. Docker containers run on the nodes, outside of openshift are able to reach internet too.

@sebiwi Could you get some info from your cluster:
1. From the master, output of 'osc get nodes' ; 'osc get hostsubnets'
2. From one of the nodes, output of 'ip a' ; 'brctl show' ; 'ovs-ofctl -O OpenFlow13 dump-flows br0'
3. Also from one of the nodes, the config file that openshift-node runs with (check ps -aef | grep openshift and see what config file it is using)

**Comment by sebiwi** [comment] 2015-06-16 07:36
Actually I have a one node install. That means that both my master and my node are on the same host.

Info:
1. [centos@openshift ~]$ osc get nodes
NAME                     LABELS                                          STATUS
openshift.sca.octo.com   kubernetes.io/hostname=openshift.sca.octo.com   Ready
[centos@openshift ~]$ osc get hostsubnets
NAME                     HOST                     HOST IP       SUBNET
openshift.sca.octo.com   openshift.sca.octo.com   84.39.33.93   10.1.0.0/24

2. 
[centos@openshift ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:7f:e5:62:f0:69 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.4/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::7f:e5ff:fe62:f069/64 scope link 
       valid_lft forever preferred_lft forever
3: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN 
    link/ether 8a:b6:b7:08:8d:cd brd ff:ff:ff:ff:ff:ff
6188: vovsbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP 
    link/ether ea:6b:8c:7e:6a:ec brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e86b:8cff:fe7e:6aec/64 scope link 
       valid_lft forever preferred_lft forever
6189: vlinuxbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP 
    link/ether 56:ec:d1:f4:ce:11 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::54ec:d1ff:fef4:ce11/64 scope link 
       valid_lft forever preferred_lft forever
3934: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link 
       valid_lft forever preferred_lft forever
6779: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN 
    link/ether a2:c0:2d:77:6d:03 brd ff:ff:ff:ff:ff:ff
6816: br0: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN 
    link/ether 2e:f6:4e:d9:91:4b brd ff:ff:ff:ff:ff:ff
6817: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether 46:d4:15:dd:1d:74 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.1/24 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::44d4:15ff:fedd:1d74/64 scope link 
       valid_lft forever preferred_lft forever
6818: lbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1450 qdisc noqueue state DOWN 
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.1/24 scope global lbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::a8fb:eaff:fe76:5931/64 scope link 
       valid_lft forever preferred_lft forever

[centos@openshift ~]$ brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.56847afe9799	no		
lbr0		8000.000000000000	no	

[centos@openshift ~]$ sudo !!
sudo ovs-ofctl -O OpenFlow13 dump-flows br0
OFPST_FLOW reply (OF1.3) (xid=0x2):
 cookie=0x0, duration=54262.386s, table=0, n_packets=28, n_bytes=2080, priority=50 actions=output:2

3.
[centos@openshift ~]$ cat /etc/openshift/node/node-config.yaml 
allowDisabledDocker: false
apiVersion: v1
dnsDomain: cluster.local
dnsIP: 10.0.1.4
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
kind: NodeConfig
masterKubeConfig: node.kubeconfig
networkPluginName: redhat/openshift-ovs-subnet
nodeName: openshift.sca.octo.com
podManifestConfig: null
servingInfo:
  bindAddress: 0.0.0.0:10250
  certFile: server.crt
  clientCA: ca.crt
  keyFile: server.key
volumeDirectory: /var/lib/openshift/openshift.local.volumes

**Comment by rajatchopra** [comment] 2015-06-16 15:38
The openflow rules are not correct. This seems like an older version of the SDN/openshift. Will try the single node install today to see what could be missing.
Any chance you have older rpms for the sdn? We have seen that before. @sdodson how can we tell an installation has the latest rpm? And there was a rpm name change also, right?

**Comment by sebiwi** [comment] 2015-06-16 16:14
This has something to do with the latest RPM that came out on July 10. I modified the openshift-ansible version to use the previous version (openshift v0.4.2-177-g5953bc7) and it works fine. This is not the perfect solution, but I don't have any other way to keep my platform running.

When is the next rpm coming out? It is really behind the version on github.

**Comment by sdodson** [comment] 2015-06-16 17:32
@sebiwi You're talking about OpenShift Enterprise High Touch Beta, right?
Beta 4 was openshift-0.4.3.2-0.git.141.3a39f33 and you should remove `openshift-sdn-node` and `openshift-sdn-master` if they're installed and then install `openshift-sdn-ovs`.

**Comment by sdodson** [comment] 2015-06-16 17:37
@sebiwi Really, between betas we don't support upgrading, we expect everyone to do a complete re-install including reprovisioning hosts. If you cannot do that, this provides a pretty thorough copy/pastable set of steps to completely clean a host

https://github.com/openshift/training/blob/master/uninstall.md

**Comment by sebiwi** [comment] 2015-06-16 20:48
@sdodson I'm actually installing the latest available origin version, using the openshift-ansible playbooks, so I don't install those packages manually, they are installed automatically with ansible.

I am not trying to upgrade the openshift version. I remove every openshift file from my host before reinstalling, so I think it's safe to say that I'm installing on a completely clean host. And I made it work, by downgrading the version that openshift-ansible installs. 

So my guess is that there is a problem with the latest RPM available, the one that openshift-ansible installs by default when specifying "origin" as the installation type on the inventory file. I only tried this in an "all in one" installation, so I don't know if the problem still occurs with multiple hosts.

**Comment by rajatchopra** [comment] 2015-06-17 05:28
My single-node cluster works too. A simple grep on packages that have openshift in them yields this for me:
```
[root@ose3-master cloud-user]# rpm -qa | grep openshift
tuned-profiles-openshift-node-0.5.2.2-0.git.26.701be15.el7ose.x86_64
openshift-0.5.2.2-0.git.26.701be15.el7ose.x86_64
openshift-sdn-ovs-0.5.2.2-0.git.26.701be15.el7ose.x86_64
openshift-master-0.5.2.2-0.git.26.701be15.el7ose.x86_64
openshift-node-0.5.2.2-0.git.26.701be15.el7ose.x86_64
```
What is the output on yours?

**Comment by sudhirpandey** [comment] 2015-07-14 18:45
I have exact same issue
```
 oc logs docker-registry-1-deploy
 F0714 15:38:03.498581       1 deployer.go:63] couldn't get deployment default/docker-registry-1: Get https://ose3-master.example.com:8443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp: lookup ose3-master.example.com: no such host , 

```

All the nodes are able to resolve a the host name ose3-master.example.com, however on each node when free docker container as well as openshift ones are not able to resolve ose3-master.example.com, But they can reach master with IP address. I am provisioning this nodes with vagrant so, /etc/hosts on each nodes of cluster ie (master, node1 and node2) have  respective entries of hostname and Ipaddress so they are able to resolve, while the docker fired on nodes would not have those entries, Docker containers are also not able to resolve using (openshift) DNS running in master node. 

I also provisioned this setup using openshift-anisble. I was just trying openshift and am very new to it, so i was guessing either openshift-ansible or openshift dns internally would have taken care of this issue or should we take care of this issue by bringing up containers with /etc/hosts already having those entry.  Any kind of suggestion will be much helpful . Here are the details on each node.
Master:
```
openshift-master-1.0.0-0.git.4227.6ffebda.el7.centos.x86_64
openshift-1.0.0-0.git.4227.6ffebda.el7.centos.x86_64

oc get nodes
NAME                     LABELS                                          STATUS
ose3-node1.example.com   kubernetes.io/hostname=ose3-node1.example.com   Ready
ose3-node2.example.com   kubernetes.io/hostname=ose3-node2.example.com   Ready

oc get hostsubnets
ose3-node1.example.com   ose3-node1.example.com   192.168.100.200   10.1.0.0/24
ose3-node2.example.com   ose3-node2.example.com   192.168.100.201   10.1.1.0/24

 ```

Node1:
```
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:89:34:17 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 74738sec preferred_lft 74738sec
    inet6 fe80::a00:27ff:fe89:3417/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:a2:e7:32 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.200/24 brd 192.168.100.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fea2:e732/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
5: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN
    link/ether 46:3e:f5:dd:f0:0a brd ff:ff:ff:ff:ff:ff
6: br0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN
    link/ether ba:d2:59:a9:72:4f brd ff:ff:ff:ff:ff:ff
7: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether ea:a2:d6:96:24:63 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.1/24 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::e8a2:d6ff:fe96:2463/64 scope link
       valid_lft forever preferred_lft forever
8: vovsbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP
    link/ether f6:04:8f:03:30:84 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f404:8fff:fe03:3084/64 scope link
       valid_lft forever preferred_lft forever
9: vlinuxbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master lbr0 state UP
    link/ether 52:15:a1:15:bc:ea brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5015:a1ff:fe15:bcea/64 scope link
       valid_lft forever preferred_lft forever
10: lbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 52:15:a1:15:bc:ea brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.1/24 scope global lbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::1cb8:e6ff:fe55:a795/64 scope link
       valid_lft forever preferred_lft forever
28: veth28d2e08: <BROADCAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master lbr0 state UP
    link/ether 62:8b:61:7e:e4:cd brd ff:ff:ff:ff:ff:ff
    inet6 fe80::608b:61ff:fe7e:e4cd/64 scope link
       valid_lft forever preferred_lft forever
```
brctl show
```
bridge name	bridge id		STP enabled	interfaces
docker0		8000.56847afe9799	no
lbr0		8000.5215a115bcea	no		veth28d2e08
							vlinuxbr
```

ovs-ofctl -O OpenFlow13 dump-flows br0
```
OFPST_FLOW reply (OF1.3) (xid=0x2):
 cookie=0x0, duration=11255.488s, table=0, n_packets=3103, n_bytes=211600, priority=50 actions=output:2
 cookie=0x0, duration=11255.475s, table=0, n_packets=58, n_bytes=2436, priority=100,arp,arp_tpa=10.1.0.1 actions=output:2
 cookie=0x0, duration=11255.469s, table=0, n_packets=0, n_bytes=0, priority=100,ip,nw_dst=10.1.0.1 actions=output:2
 cookie=0xc0a864c9, duration=169.192s, table=0, n_packets=0, n_bytes=0, priority=100,arp,arp_tpa=10.1.1.0/24 actions=set_field:192.168.100.201->tun_dst,output:1
 cookie=0xc0a864c9, duration=169.197s, table=0, n_packets=0, n_bytes=0, priority=100,ip,nw_dst=10.1.1.0/24 actions=set_field:192.168.100.201->tun_dst,output:1
 cookie=0xc0a864c8, duration=169.211s, table=0, n_packets=3153, n_bytes=3806529, priority=75,ip,nw_dst=10.1.0.0/24 actions=output:9
 cookie=0xc0a864c8, duration=169.205s, table=0, n_packets=272, n_bytes=11424, priority=75,arp,arp_tpa=10.1.0.0/24 actions=output:9
```

/etc/openshift/node/node-config.yaml
```
allowDisabledDocker: false
apiVersion: v1
dnsDomain: cluster.local
dnsIP: 10.0.2.15
dockerConfig:
  execHandlerName: ""
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
kind: NodeConfig
masterKubeConfig: system:node:ose3-node1.example.com.kubeconfig
networkPluginName: redhat/openshift-ovs-subnet
nodeName: ose3-node1.example.com
podManifestConfig:
servingInfo:
  bindAddress: 0.0.0.0:10250
  certFile: server.crt
  clientCA: ca.crt
  keyFile: server.key
volumeDirectory: /var/lib/openshift/openshift.local.volumes
```

**Comment by sudhirpandey** [comment] 2015-08-03 16:26
This was because of DNS issue as expected, solved it by running dnsmasq in one of the node and modify the /etc/resolve.conf entry to contain the node IP(running dnsmasq)  in all other nodes.

**Comment by samsong8610** [comment] 2015-08-27 08:28
I have the same issue as @sudhirpandey ,but I found another method to solve this issue without using a local DNS service. You could still use hostnames like master.example.com in the ansible inventory file and overriding some host variables, openshift_ip=<your local ip> openshift_master_api_url=https://<your master local ip>:8443. The final inventory looks like below.

    [masters]
    master.example.com openshift_ip=<your master local ip> openshift_master_api_url=https://<your master local ip>:8443
    [nodes]
    node1.example.com openshift_ip=<your node1 local ip>

The master.server.crt only allow the api be accessed by using hostname, after some diving of the ansible code, openshift add a fact common.all_hostnames for the master.server.crt's SANS. So edit the set_aggregate_facts() in roles/openshift_facts/library/openshift_facts.py, add master node's local ip address in to all_hostnames list.

    def set_aggregate_facts(facts):
    ...
    if 'common' in facts:
    ...
        # Enable access api through IP address
        all_hostnames.add(facts['common']['ip'])
    ...

That's it, kick ansible to install.
Check the openshift-master.kubeconfig file, you can see the cluster server is named by https://your_master_local_ip:8443, which is the value of master.api_url.
Check the master.server.crt using `openssl x509 -in /etc/openshift/master/master.server.crt -text -noout |grep -A1 'Subject Alternative Name:' `, you can see your master local ip in the output as an IP address SANS.

**Comment by hodrigohamalho** [comment] 2015-09-30 23:12
@sudhirpandey you saved my day. thanks!

**Comment by smarterclayton** [comment] 2015-11-04 21:41
Closed due to age without prejudice

**Closed by smarterclayton** 2015-11-04 21:41 UTC
Labels: component/networking, kind/bug, priority/P2
