### ISSUE TITLE
oc status doesn't make the links between my build configs obvious

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#8338] opened 2016-04-04 00:05 UTC
bc/one makes a docker image that is used as the source for bc/two, but there's no reflection of that in the output.

A reflection of the build chain (one link each direction?) would be helpful.

Also, remind me to check to see if there's any sane way to indicate that a dc is doomed if it tries to scale up before scale down with a single node and a host port.  @kargakis.  oc status can't do it since users don't know about nodes.

**Comment by deads2k** [comment] 2016-04-04 00:06
@liggitt, no tagging on mobile?

**Comment by liggitt** [comment] 2016-04-04 00:25
Nope, need to request the desktop site

**Comment by kargakis** [comment] 2016-04-04 10:04
> Also, remind me to check to see if there's any sane way to indicate that a dc is doomed if it tries to scale up before scale down with a single node and a host port. @kargakis. oc status can't do it since users don't know about nodes.

I am wondering how can we communicate that to a user that cannot know the number of nodes otherwise.

Apart from simple scaling (which in terms of oc status would be a warning), another warning (or maybe error since it blocks deployments) would be a set maxSurge and no unavailability when nodes/pods (with host ports) == 1. Supposing we add such warnings.

**Comment by kargakis** [comment] 2016-04-19 15:02
Opened https://github.com/openshift/origin/issues/8559 for the second part of this issue.

**Comment by kargakis** [comment] 2016-04-20 13:14
Is this a dupe of https://github.com/openshift/origin/issues/6357?

**Comment by deads2k** [comment] 2016-04-20 13:43
> Is this a dupe of #6357?

Not quite.  I'll have `to` and `from` without any build-chain at all.

**Comment by gabemontero** [comment] 2016-06-15 19:05
Do we want the chains displayed as separate lines similar the `standaloneDC` / `standaloneImage` / `standalondRC` stuff, or somehow underneath the `describeDeploymentInServiceGroup` umbrella?

If a separate section, perhaps preceding the Errros/Warnings sections.  Something like:

```
Build Chains:
  * bc1 -> bc2
  * bc3 -> bc4
```

**Comment by bparees** [comment] 2016-06-20 20:41
is this going to deprecate the existing oadm build-chain tool?

**Comment by gabemontero** [comment] 2016-06-20 20:55
On Mon, Jun 20, 2016 at 4:41 PM, Ben Parees <notifications@github.com>
wrote:

> is this going to deprecate the existing oadm build-chain tool?
>
I would think "no" (I believe oadm build-chain has a more image stream
centric look), but this is the type of discussion
when we have the cli / UI alignment discussions ... I'll update the trello
card.

**Comment by gabemontero** [comment] 2016-06-23 17:24
A reader digest version of discussion in the pull:  there are broader concerns with aligning with the UI in how both build config dependencies (the essence of this issue) and pipelines in general (a superset of build config dependencies) are depicted via the CLI.

The https://trello.com/c/hHx4HrCG/966-integrate-pipeline-stages-into-oc-status card has been opened to track.

I'm leaving this issue and associated pull open for the time being.  At least from my perspective, it could serve as a tactical step forward that we want to merge in the interim as the above card progresses.

**Closed** 2016-08-09 22:39 UTC
Labels: component/build, component/cli, priority/P2
