### ISSUE TITLE
Role reconciliation issue on origin 3.6

### ISSUE THREAD

**Issue by zonArt** [openshift/origin#17196] opened 2017-11-06 14:07 UTC
Discussion began in issue #14904 and I'm now opening a new issue as suggested by @liggitt 
The problem is with clusterrole reconciliation (especially the "edit" one)

##### Version
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

##### Steps To Reproduce
1. Modify the `edit` clusterrole in openshift 1.5
2. Upgrade to openshift 3.6
3. Run the clusterrole reconciliation

##### Current Result
The modification done in openshift 1.5 is removed (making me think role reconciliation is working) but nothing more.

##### Expected Result
The modification done in openshift should be removed (that already the case as mentioned above) PLUS the `edit` clusterrole should be updated with setting `apiGroups` to their right value

##### Additional Information
With these `apiGroups` not up to date, it's impossible to use from fabric8-maven-plugin for instance and all the other REST API call on `/apis/<apiGroups whatever>`

Thanks in advance for your help

**Comment by liggitt** [comment] 2017-11-06 14:26
What version of oc are you using to do the reconciliation?

**Comment by enj** [comment] 2017-11-06 14:33
Also, what command did you run to reconcile?

**Comment by zonArt** [comment] 2017-11-06 14:50
Mmmmmh interesting yes, didn't realize `oc` version could influence the behavior.
@liggitt I ran it with oc 1.3 (way too old I agree)

@enj I tried the following command: `oc adm policy reconcile-cluster-role edit --confirm`

To complete a little the missing points:
The issue also happened when using the ansible scripts to upgrade from 1.5 to 3.6 (in this case I doubt that oc version matters)

**Comment by liggitt** [comment] 2017-11-06 14:53
> The issue also happened when using the ansible scripts to upgrade from 1.5 to 3.6 (in this case I doubt that oc version matters)

ansible uses oc reconcile commands, so it actually matters what version of oc you have

**Comment by zonArt** [comment] 2017-11-06 14:55
@liggitt Ok ok I wasn't aware about that (actually I could have had a closer look to what happens behind the scene sorry)

**Comment by simo5** [comment] 2017-11-06 14:57
@zonArt do you still have an issue or should we close ?

**Comment by zonArt** [comment] 2017-11-06 14:58
@simo5 I'll confirm that right away but as far as I notice it looks ok

**Comment by zonArt** [comment] 2017-11-06 15:56
@simo5 Everything is ok, it works much better with the right version of `oc` even if I don't really understand why using a different client's version changes the behavior of commands executed on the server.

**Comment by enj** [comment] 2017-11-06 17:21
@zonArt reconciliation is done by the client in all versions before 3.7.  Closing since this is not a bug.

**Closed by enj** 2017-11-06 17:21 UTC
