### ISSUE TITLE
osc create -f is not an atomic operation

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2103] opened 2015-05-06 20:30 UTC
Hi All, 
        The command "osc create -f" should be an atomic operation, I mean if it fails, it should delete all the objects created at the point of failure. let's see the following example:

[oseuser2@ose1 beta3]$ osc create  -f tomcat-full.json 
services/tomcatfull-http-service
Error: ReplicationController "tomcatfullController" is invalid: metadata.name: invalid value 'tomcatfullController': must have at most 253 characters and match regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
# Name is fixed ...

[oseuser2@ose1 beta3]$ vi tomcat-full.json 
# but some objects were created successfully during the last "osc create"

[oseuser2@ose1 beta3]$ osc create  -f tomcat-full.json 
Error: service "tomcatfull-http-service" already exists

NOTE: This situation is really confuse, I think if "osc create" fails it should delete all the objects created.

**Comment by liggitt** [comment] 2015-05-09 01:19
`create` of multiple items can't actually be atomic, and I don't think we should fake it by auto-deleting, for several reasons:
1. create and delete can be policied separately (e.g. you can create, but not delete)
2. controllers are watching and responding to objects (e.g. you create a replication controller, a controller loop immediately starts spawning pods)
3. things getting auto-created and deleted can make debugging problems hard

Seems like the right thing(s) to do would be:
1. Make it easy to issue a command to clean up things created from a template (#2152)
2. Make it easy to call `create -f` again and tolerate some things already existing (https://github.com/GoogleCloudPlatform/kubernetes/issues/6255)

**Comment by roldancer** [comment] 2015-05-10 20:25
Hi @liggitt , I agree with you,  it would be really useful if we had some command to clean up things create by a "osc create -f" for instance "osc deleteAll -f ".

**Comment by smarterclayton** [comment] 2015-05-11 06:00
You can xargs the output of create to delete.

Create should tolerate existing, it is an upstream bug that it stops halfway through that I have not yet debugged

**Comment by smarterclayton** [comment] 2015-05-11 06:01
It would be interesting if we could remember the previous command results and have an undo.

**Comment by roldancer** [comment] 2015-05-11 10:44
@smarterclayton, that would be interesting, I think OpenShift should give us some command or flag to undo a previous command, for instance the osadm create router, it creates several objects, some object must be deleted in a specific order, so I think an undo or deleteAll would be very useful.

**Comment by smarterclayton** [comment] 2017-01-23 03:55
Closing due to age, this is still working as intended even though in the future there may be better tools for this.

**Closed by smarterclayton** 2017-01-23 03:55 UTC
Labels: component/cli, kind/enhancement, priority/P3
