### ISSUE TITLE
devenv_ami failing on cross compile

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#11467] opened 2016-10-20 16:01 UTC
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/5209/console

```
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
# github.com/openshift/origin/vendor/github.com/apcera/gssapi
vendor/github.com/apcera/gssapi/buffer.go:9:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
[ERROR] PID 2356: hack/common.sh:251: `local -a binaries=("$@")` exited with status 1.
[INFO]      Stack Trace: 
[INFO]        1: hack/common.sh:251: `local -a binaries=("$@")`
[INFO]        2: hack/build-cross.sh:24: os::build::build_binaries
[INFO]   Exiting with code 1.
```

**Comment by enj** [comment] 2016-10-20 16:03
Did someone remove `krb5-devel`?

**Comment by enj** [comment] 2016-10-20 16:07
Hm that cannot be the issue since the logs say it was installed.

**Comment by enj** [comment] 2016-10-20 16:19
This seems to have failed intermittently in the past - perhaps we need the `CGO_ENABLED=1` and `CC=gc` flags?

**Comment by liggitt** [comment] 2016-10-20 17:28
where are you seeing intermittent failures on that?

**Comment by enj** [comment] 2016-10-20 18:15
In https://ci.openshift.redhat.com/jenkins/job/devenv_ami/bfa-proj-graphs/detailedgraphs both 5182 and 5198 failed on this yet prior and future builds did not.

**Comment by liggitt** [comment] 2016-10-24 15:36
Slicing by OS reveals more. If you just look at rhel7 builds:

First failing with this error:
* https://ci.openshift.redhat.com/jenkins/job/devenv_ami/5202/consoleFull
    * based on https://ci.openshift.redhat.com/jenkins/job/base_ami/2443/consoleFull
        * 852f1fe Merge pull request #11220 from jim-minter/issue10462

Last working:
* https://ci.openshift.redhat.com/jenkins/job/devenv_ami/5201/consoleFull
    * based on https://ci.openshift.redhat.com/jenkins/job/base_ami/2410/consoleFull
        * 8cff42a Merge pull request #11078 from juanvallejo/jvallejo/add-linebreak-between-resource-groups

`git diff 852f1fe 8cff42a --numstat` shows tito build changes related to ldflags in 606d5807b7e7b90f9351aad25c66976f3c405ddc

@tdawson, can you take a look at whether those changes could be causing this?

**Comment by enj** [comment] 2016-10-24 15:41
PR for reference: #11196

**Comment by tdawson** [comment] 2016-10-24 19:38
This might sound wierd, but I believe the problem is the change in epel from npm-1.3.6-5.el7 to npm-3.10.3-107.el7.

npm-3.10.3-107.el7 has only 3 dependencies.
npm-1.3.6-5.el7 had 125 dependencies, including krb5-devel.

krb5-devel is what you are missing.  Becasue npm always pulled in krb5-devel, you never specifically required it for anything.

**Comment by tdawson** [comment] 2016-10-24 19:48
Forget what I said in my comment above.  I was looking at the error in 5202, in a Docker build, and finding the solution in 2443, a Vagrant image build, which succeeded.

**Comment by enj** [comment] 2016-10-24 19:52
I just looked through the logs again with @stevekuznetsov and confirmed that while `krb5-libs` is installed, `krb5-devel` is NOT installed.  Perhaps we just need to specifically request that package in our builds?

**Comment by stevekuznetsov** [comment] 2016-10-24 20:01
A simple `yum list installed krb5-devel` on a EC2 instance running from the devenv will show you that the dependency is missing today.

**Comment by liggitt** [comment] 2016-10-24 20:59
so something like https://github.com/openshift/vagrant-openshift/pull/503 might fix it?

**Comment by stevekuznetsov** [comment] 2016-10-24 21:10
Should do

**Comment by liggitt** [comment] 2016-10-24 21:14
hopefully fixed by https://github.com/openshift/vagrant-openshift/pull/503
once we get a clean base_ami + dev_ami, we'll see

**Comment by enj** [comment] 2016-11-01 15:55
So this seems to be failing for other reasons now.  @stevekuznetsov PTAL

**Closed** 2016-11-01 16:39 UTC
Labels: component/auth, priority/P1

**Comment by mrsiano** [comment] 2017-12-20 16:03
I faced that issue on ec2 instance running oc versions 3.8
@mffiedler @jeremyeder
