### ISSUE TITLE
openshift router should support other protocols than HTTP/HTTPS

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#3415] opened 2015-06-24 09:33 UTC
we need to be able to access other protocols than HTTP/HTTPS via the OpenShift router so that we can access things like ActiveMQ, MQTT and so forth.

Previously in OpenShift 2.x this was added using a version of haproxy that supported SNI headers to do the routing. I'm guessing its a case of changing the haproxy configuration to support services using non-http transports?

**Comment by jstrachan** [comment] 2015-06-24 09:37
I noticed the port forwarding:
https://docs.openshift.org/latest/dev_guide/port_forwarding.html

does that work for any network protocol or only HTTP/SPDY based stuff?

also we kinda want to expose network services (not pods) so folks can access arbitrary network services (MQTT / AMQP) rather than individual pods.

**Comment by sosiouxme** [comment] 2015-09-05 03:40
If you create a route with passthrough TLS, you ought to be able to use it to front anything that offers a TLS-encrypted protocol (as long as the clients include the SNI extension in the header packet). So the SNI proxy is already basically done?

Having the router handle non-TLS-secured protocols (that somehow identify app by name as part of the protocol like HTTP) seems like a good idea.

**Comment by karelstriegel** [comment] 2016-07-13 08:25
This is the only missing feature that is blocking me to start rolling out OpenShift. I can't expect my users to always look up a dynamic port forwarding setup for being able to connect to services that do not use the http(s) protocol. 

Highly wanted feature !

**Comment by warmchang** [comment] 2016-08-25 02:10
Hi,
I saw the status of trello is "committed-3.3", Is it mean that this feature is available in ose 3.3 or origin 1.3?

**Comment by eparis** [comment] 2016-08-25 02:19
yes/both.  I'm going to close this issue based on the code in fbca710fca96dd68754b518981c728402ff755a0

**Closed by eparis** 2016-08-25 02:19 UTC
Labels: component/routing, kind/enhancement, priority/P2

**Comment by warmchang** [comment] 2016-08-25 06:25
@eparis It's very useful. Thanks! :100:

**Comment by karelstriegel** [comment] 2016-09-05 10:03
Can't wait to try it out !!! Thx a lot

**Comment by stobias123** [comment] 2016-11-22 17:30
Are there any docs available on how to use this functionality? I can't seem to find them

**Comment by marun** [comment] 2016-11-23 15:50
@stobias123 https://docs.openshift.com/container-platform/3.3/admin_guide/tcp_ingress_external_ports.html

**Comment by 0polar** [comment] 2018-02-02 10:15
Question: how to do this in OpenShift Online v3?

**Comment by wtrocki** [comment] 2018-02-02 10:24
@0polar I believe that's not possible as it requires admins to assign some public ports. 
Better to ask about that on StackOverflow.

Best to use port forwarding.

**Comment by jdelafon** [comment] 2019-05-22 08:02
But if for instance MQTT traffic arrives on port 1883, one cannot port forward, since `oc port-forward` only works on a Pod and the problem is having the traffic top reach the Pod?
