### ISSUE TITLE
Runtime error when logging out of Web Console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4538] opened 2015-09-04 19:01 UTC
> Cannot read property 'getToggleElement' of null

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9692237/ba9743b6-5315-11e5-9dce-dcc50c85a884.png)

@jwforres fyi

**Comment by spadgett** [comment] 2015-09-04 19:07
This doesn't prevent logout from succeeding. I only noticed because I had developer tools open.

**Comment by spadgett** [comment] 2015-09-04 20:58
Also happens on the console home (all projects page).

**Comment by spadgett** [comment] 2015-09-04 21:05
This happens on all pages.

**Comment by spadgett** [comment] 2015-09-04 21:21
Fixing this unfortunately results in increased flicker because the page redirects a few times on logout.

**Comment by liggitt** [comment] 2015-09-04 21:28
It redirects a few times now? Or with a fix?

**Comment by spadgett** [comment] 2015-09-04 22:42
After fixing the runtime error, there is one more intermediate logout page that flickers briefly before the you are logged out message.

**Comment by liggitt** [comment] 2015-09-04 23:50
Tag me for review on any modifications to the logout flow... there are some gotchas

**Comment by jwforres** [comment] 2015-10-20 15:07
This is caused by an upstream bug in bootstrap.js with a dropdown closing when we are navigating away.  This is not causing anything in the logout flow to fail so lowering the priority.

We should open a fix against bootstrap upstream.

**Closed** 2016-01-04 21:24 UTC
Labels: area/usability, component/web, kind/bug, priority/P3
