### ISSUE TITLE
[oc cluster up behind proxy] Failed to install "openshift-web-console-operator": timed out waiting for the condition.

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#20496] opened 2018-08-01 12:14 UTC
##### Version
```
$ ./oc version
oc v3.10.0-rc.0+745de5b-46
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
```
$ ./oc cluster up --http-proxy http://myproxy:3128 --no-proxy localhost,127.0.0.1,172.30.1.1
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Pulling image openshift/origin-control-plane:v3.10
Image pull complete
Pulling image openshift/origin-cli:v3.10
Pulled 1/4 layers, 28% complete
Pulled 2/4 layers, 51% complete
Pulled 3/4 layers, 80% complete
Pulled 4/4 layers, 100% complete
[...]
I0801 17:31:31.838764    3644 interface.go:41] Finished installing "sample-templates/mariadb" "sample-templates/postgresql" "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/sample pipeline" "sample-templates/mongodb" "sample-templates/django quickstart" "sample-templates/nodejs quickstart" "sample-templates/rails quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/mysql"
E0801 17:36:30.854286    3644 interface.go:34] Failed to install "openshift-web-console-operator": timed out waiting for the condition
I0801 17:36:30.854328    3644 interface.go:41] Finished installing "openshift-web-console-operator" "centos-imagestreams" "openshift-image-registry" "openshift-router" "sample-templates" "persistent-volumes
```

##### Current Result

```
E0801 17:36:30.854286    3644 interface.go:34] Failed to install "openshift-web-console-operator": timed out waiting for the condition
```

##### Expected Result
Should be passed behind the proxy.

##### Additional Information
```
$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-59.gitaf6b32b.fc28.x86_64
 Go version:      go1.10.2
 Git commit:      63758e0-unsupported
 Built:           Tue Jun 12 19:05:31 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-59.gitaf6b32b.fc28.x86_64
 Go version:      go1.10.2
 Git commit:      63758e0-unsupported
 Built:           Tue Jun 12 19:05:31 2018
 OS/Arch:         linux/amd64
 Experimental:    false

```

**Comment by jcajka** [comment] 2018-08-01 12:49
I have observed similar issue in fedora https://bugzilla.redhat.com/show_bug.cgi?id=1608505

**Comment by praveenkumar** [comment] 2018-08-08 11:56
@mfojtik Any update on this?

**Comment by LalatenduMohanty** [comment] 2018-08-09 13:33
> @praveenkumar does this happen even without the proxy set as what I have observed?

No it does not happen without proxy.

**Comment by LalatenduMohanty** [comment] 2018-08-09 13:40
@sferich888 Yes, Docker settings  mirror the cluster up settings for HTTP and HTTPS proxy. 

This is the original issue https://issues.jboss.org/projects/CDK/issues/CDK-329

We came to know about while testing CDK with OCP 3.10. CDK has proxy support for sometime now and this is more of a regression.

**Comment by gbraad** [comment] 2018-08-14 07:09
Reported as https://github.com/minishift/minishift/issues/2612. Only occurs with v3.10 and as mentioned, feels like a regression ... all my proxy tests for v3.9 work as expected, but fail for v3.10.

**Comment by LalatenduMohanty** [comment] 2018-08-20 04:59
Bugzilla against `oc cluster up` in OCP https://bugzilla.redhat.com/show_bug.cgi?id=1618311

**Comment by openshiftninja** [comment] 2018-08-31 15:09
Damn. This is a major blocker for those of use behind a proxy. It looks like you used to be able to do oc cluster up --version v3.x.x but that doesn't appear to be the case. Is there a quick way to start an older version until this is resolved?

**Comment by openshiftninja** [comment] 2018-08-31 15:19
How do you use an older version of OpenShift with oc cluster up until this gets fixed? I see the --image switch, but it isn't clear to me how to use it.

**Comment by praveenkumar** [comment] 2018-09-04 03:15
@openshiftninja I think to do that you need to use 3.9 oc binary to do cluster up there is no way you can get over this issue use 3.10 oc binary + cluster up.

**Comment by gbraad** [comment] 2018-09-19 08:15
The fix in upstream https://github.com/kubernetes/kubernetes/pull/68476 did not resolve this...

**Comment by jwforres** [comment] 2018-10-01 18:04
From the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1618311 it looks like the majority of issues have been fixed but there was one remaining issue around builds

@openshift/sig-developer-experience

**Comment by bparees** [comment] 2018-10-01 18:40
What is the actual issue we're trying to solve here?  Both this and the bug went through a number of discussions.  I'd like to close this and if there is a problem someone is still facing, please report the current problem.  The linked BZ was marked verified.

**Closed** 2019-03-01 08:27 UTC
Labels: lifecycle/rotten, sig/developer-experience
