### ISSUE TITLE
imagestream's image "built date" seems to pull the first layer

### ISSUE THREAD

**Issue by djdevin** [openshift/origin#15378] opened 2017-07-20 16:04 UTC
The imagestream says "latest" and was updated 3 minutes ago

![built-date-1](https://user-images.githubusercontent.com/418136/28426929-9ff8cdd8-6d42-11e7-8a68-277e37b141e9.png)

But clicking into it pulls the information of the lowest layer image and now says "a month ago"

![built-date-2](https://user-images.githubusercontent.com/418136/28426931-a23acd80-6d42-11e7-9b1d-9e471e4ca30b.png)

Maybe this is a bug, because the digests match, but the information does not:

![built-date-3](https://user-images.githubusercontent.com/418136/28427100-1d106650-6d43-11e7-9a3a-11e0141b2235.png)

##### Version

I tested this on Origin but also reproduced on OSO

OpenShift Master:
v1.5.1+7b451fc
Kubernetes Master:
v1.5.2+43a9be4

OpenShift Master:
v3.6.126.1 (online version 3.5.0.20)
Kubernetes Master:
v1.6.1+5115d708d7

##### Steps To Reproduce
1. Create a project with the PHP example (use the cakephp source)
2. Click into the image streams latest image

##### Current Result
Latest image stream image appears to show information about the base layer

##### Expected Result
Latest image stream image should show information about the top layer

**Comment by spadgett** [comment] 2017-07-20 17:10
Looks like the problem is here:

https://github.com/openshift/registry-image-widgets/blob/cd0ac574aeb21e672a4d4964a99933dcb608c858/views/image-body.html#L16-L19

@petervo Can you take a look?

**Comment by petervo** [comment] 2017-07-20 18:15
@djdevin  I'm not getting the same results but that's probably because I took different setup steps. Can you list the steps you took starting from a new project, either through the UI or from the command line.

**Comment by djdevin** [comment] 2017-07-21 14:12
Sure, either approach behaves the same way

1. Create project and app
```
oc new-project 15378
oc new-app https://github.com/openshift/cakephp-ex
```
2. Wait for the build to finish
3. Visit /console/project/15378/browse/images/cakephp-ex
4. Verify "Last updated 1 minute ago" and note the image hash
5. Click on "Latest" tag
6. Shows "Built a month ago"

**Comment by petervo** [comment] 2017-07-22 22:46
@djdevin, thanks. As you can see the image it getting a build-date label of 2017-06-23. And that's why that date is being displayed. 

@spadgett, Is this a bug for the registry code then? Or should we just change are code to ignore the build-date label?

**Comment by spadgett** [comment] 2017-07-27 11:53
> thanks. As you can see the image is getting a build-date label of 2017-06-23. And that's why that date is being displayed.

@bparees Is this expected?

**Comment by bparees** [comment] 2017-07-27 15:19
> @bparees Is this expected?

@spadgett it's expected when you're looking at the base layer and not the latest layer, which it seems is what's happening here?

**Comment by petervo** [comment] 2017-07-27 15:21
@bparees no it's not. The image has that label, not the layer. Are you saying we should ignore the image label?

**Comment by bparees** [comment] 2017-07-27 15:28
@petervo that label is produced by RCM when they built the base image which the app was built on top of, it's definitely not something that the openshift build process sets, so no, you should not rely on it.

**Comment by bparees** [comment] 2017-07-27 15:30
(or someone else is putting it in the base layer, I see the centos image has such a label also, but it's not us adding/updating it).

**Comment by petervo** [comment] 2017-07-27 15:31
@bparees, good to know. I thought it was set by openshift on each build. I'll change the code to reflect that.

**Comment by spadgett** [comment] 2017-09-06 18:18
Fixed by https://github.com/openshift/origin-web-console/pull/1989

**Closed by spadgett** 2017-09-06 18:18 UTC
Labels: component/web, kind/bug, priority/P2
