### ISSUE TITLE
[k8s.io] Proxy version v1should proxy through a service and a pod [Conformance]

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12296] opened 2016-12-18 16:01 UTC
https://ci.openshift.redhat.com/jenkins/view/AMIs/job/base_ami/2573/consoleFull#-104571999856cbb9a5e4b02b88ae8c2f77

```
STEP: Dumping a list of prepulled images on each node
Dec 16 23:52:09.544: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "e2e-tests-proxy-u460x" for this suite.
Dec 16 23:52:14.577: INFO: namespace: e2e-tests-proxy-u460x, resource: bindings, ignored listing per whitelist


• Failure [307.359 seconds]
[k8s.io] Proxy
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
  version v1
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/proxy.go:41
    should proxy through a service and a pod [Conformance] [It]
    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/proxy.go:280

    Expected error:
        <*errors.errorString | 0xc821781020>: {
            s: "Only 0 pods started out of 1",
        }
        Only 0 pods started out of 1
    not to have occurred

    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/proxy.go:156
```

**Comment by smarterclayton** [comment] 2017-01-23 03:42
Dupe of #11016

**Closed by smarterclayton** 2017-01-23 03:42 UTC
Labels: component/kubernetes, component/networking, kind/test-flake, priority/P1
