### ISSUE TITLE
After prune the images,  there are some residual files exits in the image registry 

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#12287] opened 2016-12-16 09:15 UTC
After prune the images,  there are some residual small files exits in the image registry directory.
##### Version
```
openshift v1.5.0-alpha.0+4cb1ce3-420
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

##### Steps To Reproduce
1. Create a project and build to push some images to the integrated registry.
2. delete the project
3. prune the images:
    ```
    oadm prune images --keep-younger-than=0h0m0s --confirm=true
    ````
4. check the registry directory.

##### Current Result
blobs are deleted,but some files about that images are still exits like:
```
$ find /registry/docker/registry/v2/repositories/haowang1
/registry/docker/registry/v2/repositories/haowang1
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_uploads
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/faa431ea319a097110edf697e3acd8838c31904afb66c8da8b2bf7185e4802d2
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/faa431ea319a097110edf697e3acd8838c31904afb66c8da8b2bf7185e4802d2/link
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/37e84b32f2760401a0cc6c2f1f525f106a4b2d7b85d1791bc9c301424e1eb258
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/37e84b32f2760401a0cc6c2f1f525f106a4b2d7b85d1791bc9c301424e1eb258/link
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/8c1d0ae4996e6f3fc9ef9f16511291061a1ad8d4e1bc40a372e3ea7d7581e028
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/8c1d0ae4996e6f3fc9ef9f16511291061a1ad8d4e1bc40a372e3ea7d7581e028/link
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/038c36eaf0bbde64b4fbeff865dcfba4bb7ca33cc2fb1b6148244b8536bff0e0
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/038c36eaf0bbde64b4fbeff865dcfba4bb7ca33cc2fb1b6148244b8536bff0e0/link
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/4ed95f5d9dd4f49e1dc5e2f64a51a2262a26aac23017099c1f6a908ccbe58771
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/4ed95f5d9dd4f49e1dc5e2f64a51a2262a26aac23017099c1f6a908ccbe58771/link
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/85dab2e0d129ed4c4f1da157574c0f5d66a54222d7ac2958093d01b00d487335
/registry/docker/registry/v2/repositories/haowang1/ruby-hello-world/_layers/sha256/85dab2e0d129ed4c4f1da157574c0f5d66a54222d7ac2958093d01b00d487335/link
```

##### Expected Result
the project already deleted, the images blobs are pruned, the sha files are useless should be deleted, it will be problem for the registry to have more and more useless files.

**Comment by wanghaoran1988** [comment] 2016-12-16 09:16
@miminar @legionus

**Comment by ncdc** [comment] 2016-12-19 17:43
This is really a dupe of https://github.com/openshift/origin/issues/3333#issuecomment-117214873

**Comment by legionus** [comment] 2018-02-06 17:10
Now you can use hard prune to cleanup the storage.

https://docs.openshift.org/latest/admin_guide/pruning_resources.html#hard-pruning-registry

**Closed by legionus** 2018-02-06 17:10 UTC
Labels: area/techdebt, component/imageregistry, priority/P2
