### ISSUE TITLE
deploymentconfigs with revision history limits flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11008] opened 2016-09-20 10:55 UTC
```
• Failure [226.186 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:729
  with revision history limits
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:678
    should never persist more old deployments than acceptable after being observed by the controller [Conformance] [It]
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:677

    Expected
        <int64>: 6
    to be >=
        <int>: 7

    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:675
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6216/consoleFull

**Comment by kargakis** [comment] 2016-09-20 11:40
The deployer pod for the 6th deployment never run (hence the 7th deployment is missing) - same symptom as the rest of the recent deployment flakes cc: @smarterclayton

**Comment by bparees** [comment] 2016-09-20 11:47
ok, feel free to close as a dupe.

**Comment by kargakis** [comment] 2016-09-20 13:05
Closing as dupe of https://github.com/openshift/origin/issues/10951

**Closed by kargakis** 2016-09-20 13:05 UTC
Labels: component/deployments, kind/test-flake, priority/P2
