### ISSUE TITLE
FailedSync: Error syncing pod, skipping failed to apply oom-score-adj to container

### ISSUE THREAD

**Issue by pecameron** [openshift/origin#8466] opened 2016-04-11 20:34 UTC
[TEST] fails in extended tests with:
Apr 11 13:40:43.112: INFO: At 2016-04-11 13:40:22 -0400 EDT - event for deployment-test-1-hook-pre: {kubelet 172.18.14.69} Created: Created container with docker id c097e409c7ab
Apr 11 13:40:43.112: INFO: At 2016-04-11 13:40:23 -0400 EDT - event for deployment-test-1-hook-pre: {kubelet 172.18.14.69} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "lifecycle" with RunContainerError: "failed to apply oom-score-adj to container \"open /proc/609/cgroup: no such file or directory\"- /k8s_lifecycle.9f3ce46a_deployment-test-1-hook-pre_extended-test-cli-deployment-6vyv7-tw4jj_76ae8142-000c-11e6-b84b-0e893c51d689_bfe56f02"

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by liggitt** [comment] 2016-04-11 20:36
dupe of https://github.com/openshift/origin/issues/8397?

**Comment by ncdc** [comment] 2016-04-12 12:00
This is a dupe and was fixed by #8412

**Closed by ncdc** 2016-04-12 12:00 UTC
Labels: kind/test-flake, priority/P2
