### ISSUE TITLE
'oc cluster up' console not accessible from chrome

### ISSUE THREAD

**Issue by mattf** [openshift/origin#12482] opened 2017-01-13 18:00 UTC
##### Version
oc v1.3.2
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://172.20.20.20:8443
openshift v1.3.2
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. oc cluster up
2. open console url in chrome (https://172.20.20.20:8443)

##### Current Result
![screenshot from 2017-01-13 12-54-44](https://cloud.githubusercontent.com/assets/112653/21939914/f554baa4-d98f-11e6-95ee-8adcdbe1c965.png)

##### Expected Result
a working console

##### Additional Information
google-chrome-stable-55.0.2883.87-1.x86_64
firefox-50.1.0-1.fc25.x86_64

firefox is willing to let me override the cert issue and access the console

**Comment by smarterclayton** [comment] 2017-01-13 19:27
@jwforres was this what we just fixed?

**Comment by jwforres** [comment] 2017-01-13 19:56
@smarterclayton if you mean the issue related to the rebase, then no the console was able to be loaded it just had an issue trying to load petsets which no longer existed.

I ran oc cluster up with --version=latest after the rebase landed the other day and I'm able to accept the cert in chrome just fine.  I'm on Chrome 55.0.2883.95 (64-bit)

The cert is the same cert you would get if you hit the API and not the console  @liggitt ?

**Comment by liggitt** [comment] 2017-01-13 20:02
> The cert is the same cert you would get if you hit the API and not the console @liggitt ?

Should be. What cert is being returned? `openssl s_client -showcerts -connect 172.20.20.20:8443`

**Comment by mattf** [comment] 2017-01-13 20:05
fyi, i've confirmed that --version=latest results in a NET::ERR_CERT_AUTHORITY_INVALID error from chome, which i am allowed to manually override.

**Comment by jwforres** [comment] 2017-01-16 13:42
Assigning to platform team, if there was an issue here it was with the certs for the whole master and wasn't specific to the console.

@mattf can you please re-run oc cluster up without --version=latest and run the command @liggitt requested https://github.com/openshift/origin/issues/12482#issuecomment-272533807

**Comment by mattf** [comment] 2017-01-16 19:36
$ oc version
oc v1.5.0-alpha.1+71d3fa9
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://172.17.0.1:8443
openshift v1.5.0-alpha.1+71d3fa9
kubernetes v1.4.0+776c994

(note i've moved to a new oc client since filing this issue)

$ oc cluster up 
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.5.0-alpha.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 172.17.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://172.17.0.1:8443
   You are logged in as:
       User:     developer
       Password: developer
   To login as administrator:
       oc login -u system:admin

(i'm a little concerned that it's using the docker0 interface:
$ ifconfig docker0 | head -n2
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0)

chrome reports ERR_SSL_SERVER_CERT_BAD_FORMAT


$ openssl s_client -showcerts -connect 172.17.0.1:8443  
CONNECTED(00000003)
depth=1 CN = openshift-signer@1468944829
verify error:num=19:self signed certificate in certificate chain
---
Certificate chain
 0 s:/CN=127.0.0.1
   i:/CN=openshift-signer@1468944829
-----BEGIN CERTIFICATE-----
MIIECzCCAvOgAwIBAgIBVzANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0Njg5NDQ4MjkwHhcNMTcwMTE2MTkyOTQ3WhcNMTkwMTE2
MTkyOTQ4WjAUMRIwEAYDVQQDEwkxMjcuMC4wLjEwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQChKbnXlD6mgp4gVJI9rwb5BMxk8PWE50lVERx/a2Uj7TkL
/albVYF3LtlpslJKzngiF6IHq6TOX+coqr/5CnIPDu3j9wFf1/Kj+UB7dJHlf34C
m9Y81qKm8Dku0gXALJMCoEa9V8P6lS6b3KkOuLYLpOwYlByUkUthPfHnQrQ39p1X
ZE6SCSlIzCBdGOazIfhu0ujNgDycmyeE8Ag4FZPWcIfJQ3hSza4rlN/xei0X2txE
dN96bbNN1zyZBrRZQb2TuqjXaKzxckBl1LeUv5iaAhvNRGSoc4N+UAFMBfoyPcyZ
AY1eXVncsvcUH6suCDpCDXJDvHRbMnpisg7lR/edAgMBAAGjggFUMIIBUDAOBgNV
HQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCC
ARkGA1UdEQSCARAwggEMggprdWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1bHSC
Fmt1YmVybmV0ZXMuZGVmYXVsdC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMu
Y2x1c3Rlci5sb2NhbIIJbG9jYWxob3N0gglvcGVuc2hpZnSCEW9wZW5zaGlmdC5k
ZWZhdWx0ghVvcGVuc2hpZnQuZGVmYXVsdC5zdmOCI29wZW5zaGlmdC5kZWZhdWx0
LnN2Yy5jbHVzdGVyLmxvY2FsggkxMjcuMC4wLjGCCjE3Mi4xNy4wLjGCCjE3Mi4z
MC4wLjGCDDE5Mi4xNjguMS41OYcEfwAAAYcErBEAAYcErB4AAYcEwKgBOzANBgkq
hkiG9w0BAQsFAAOCAQEAukMP+EbgbZVM6lN+oGCnJ7B3vAojLnVmxq+JTutIbChv
9uAvaJl/5jDHUkwEayVg/3TOo2nh58+cNrk2qfU8X+0evehKAl29JMU/wyLdifMh
GelCfkut+KrKALplqC1n0kamH1HVNx52Tc7pdl+au7iIrWrY9rcVLmZy8Fk8IZJs
INjpN3D1KzvrKXJqd3r4aYoTqAo1DgQ1G6LkDrL0eL/Lisl8kygzVDkQEtD2ldfP
U0PIBOteziDTBLt4edAnAHf0diqCKnvxFob/v7NVdeK7oZeAwgZZSSf+Jsnc5ImQ
uT4X7otjXlBZ+lbbwrjpuzMkKtdR1kw2p9OZN4ZLpw==
-----END CERTIFICATE-----
 1 s:/CN=openshift-signer@1468944829
   i:/CN=openshift-signer@1468944829
-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0Njg5NDQ4MjkwHhcNMTYwNzE5MTYxMzQ5WhcNMjEwNzE4
MTYxMzUwWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE0Njg5NDQ4Mjkw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLQqmS7g8bjsnj9evcVsBK
Xe8xCCiF39z/BKCTWbYNnDqn6txWxye/+vR5XjsVAjoMwTjK7vPm9//LnPuWelBV
A+/ySg+G6bjQd0LL8CASfdyugAbum32RMbuWwxeXAoHiOcpn7/rwQanPecj3wGjo
pj5eQOAUCR0loZueWqK1D8GX7xAKL7WfuN0iWKPOPfplpTnwijESqUyxRC2ZPGN2
IwowKUXPb1mwg7/3pYX6++noiMNECKcTFvM8pXejH5YdQJpW9D64xdkgoocF/vOC
HP6X+LB1geR/ASMnF44BxKmOpzWPSUF7QgJRzQ9GZsGWNq8dl/Ka8jN2GfEcjMkB
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQB1AbIFnuhChXQnWWw9wgzzLMOkiHL7Qy9Fs8i/qjKbcmZU
PovNxLsVMjX3+jErf8a3knrhmz7BNaJvLFh2Qrr/b840eNezqV936S4zD7l7LJhj
v2gqXXq23IZUYexubynJ1AYW2SMDhkGuBdHVm1O8cNXLIxCYLClueBpe1WLZAo0R
SKsyCIBpTouONOjhSsmbz45PRmd6c4A2v3g//Ih9juJB2ufUZ/YGyKCikCLUagDi
Sah+yuwhnpwjWe59U3sTJfGoD9alZ8kFIkzPsXxo4gkoykUiX4XeLFcq6t3Tvrsr
Tau85u8t4klHNg3Med87E86oWwEnHztFIEQIA6k7
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=127.0.0.1
issuer=/CN=openshift-signer@1468944829
---
Acceptable client certificate CA names
/CN=openshift-signer@1468944829
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA384
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2468 bytes and written 339 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: D420E2E7BB235E5ED2EE2B635D7D7BA434F67B076523D635B4EA87DDB698D431
    Session-ID-ctx: 
    Master-Key: 0C051396206C29017A5AB341B0E830DB0B51DCBA26D5147CEC4B64AEC0524BCA54CE2B665FB954A4820A64B7979C512D
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket:
    0000 - 61 21 a8 fe 92 67 6c bd-88 52 c8 d9 2c 8d 72 3a   a!...gl..R..,.r:
    0010 - c9 27 32 02 99 ee 3c be-58 9d ab da 8a 90 3a 53   .'2...<.X.....:S
    0020 - ca be fd c1 5c 32 78 bb-a2 67 82 82 57 a7 1b 52   ....\2x..g..W..R
    0030 - 3d 24 08 57 81 66 d9 3c-e7 03 97 a5 b3 5b 7e 57   =$.W.f.<.....[~W
    0040 - c5 a4 85 3b b2 48 30 bf-0a 74 b7 1a b1 c1 ff 66   ...;.H0..t.....f
    0050 - 21 9b 96 1e 4a d8 9e 06-07 c2 7d ce 13 eb 63 dc   !...J.....}...c.
    0060 - 6c 40 6c eb 13 49 ed e7-2f c6 dd d0 4f fe 06 b3   l@l..I../...O...
    0070 - 1c 2a 5e 46 38 9c 1d 31-                          .*^F8..1

    Start Time: 1484595319
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---
^C

**Comment by mattf** [comment] 2017-01-16 20:53
update - i appear to be able to get past this issue if i delete /var/lib/origin/openshift.local.config before 'oc cluster up'

maybe this is an issue of using an old config / generated cert? if so, this will be very non-obvious for users. on my system, i found 10 config directories dating back to july. if i happen to get an ip w/ a bad config this breaks, if i'm lucky and get a new ip it works...

**Comment by mfojtik** [comment] 2017-01-18 12:36
@php-coder PTAL (you recently touched the certificates ;-)

**Comment by php-coder** [comment] 2017-01-25 15:52
I couldn't reproduce it. Chrome shows me ERR_CERT_AUTHORITY_INVALID instead of ERR_SSL_SERVER_CERT_BAD_FORMAT. The latter means that we're using self-signed certificate that is possible to accept.

Does anybody have ideas on how to reproduce it? Which certificates I should replace, for example?

Maybe we should add option to `oc cluster up` for overwriting existing certificates? In this case, if such an error occurs next time we'll be able to just re-run with a special flag.

**Comment by php-coder** [comment] 2017-06-13 14:19
I'm closing this as can't reproduce. Reopen it if you will have more information.

**Closed by php-coder** 2017-06-13 14:19 UTC
Labels: component/auth, kind/bug, priority/P2
