### ISSUE TITLE
flake: oadm diagnostics doesn't run PodCheckDns

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10090] opened 2016-07-28 16:51 UTC
as seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/4140/consoleFull#-720211075762928fe4b031e1b25ced2a):

```
FAILURE after 5.943s: test/end-to-end/core.sh:291: executing 'oadm diagnostics DiagnosticPod --images='openshift/origin-${component}:1f6ade4'' expecting success and text 'Running diagnostic: PodCheckDns': the output content test failed
Standard output from the command:
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/tmp/openshift/test-end-to-end-docker//openshift.local.config/master/admin.kubeconfig'

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
Info:  Output from the diagnostic pod (image openshift/origin-deployer:1f6ade4):
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
       
[Note] Summary of diagnostics execution (version v1.3.0-alpha.2+1f6ade4):
[Note] Completed with no errors or warnings seen.

There was no error output from the command.
```

/cc @sosiouxme

**Comment by sosiouxme** [comment] 2016-07-29 13:41
Duplicate of https://github.com/openshift/origin/issues/9888 - thanks for the data point, I didn't have output to look at before.

**Comment by sosiouxme** [comment] 2016-07-29 13:41
I like your title better though.

**Closed** 2016-07-29 13:42 UTC
Labels: component/cli, component/diagnostics, kind/test-flake, priority/P2
