### ISSUE TITLE
github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:112: executing 'oc rollout status dc/docker-registry' expecting success

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13943] opened 2017-04-28 12:09 UTC
github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:112: executing 'oc rollout status dc/docker-registry' expecting success

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1001/

I haven't dug into this at all, just going through the queues.

**Comment by deads2k** [comment] 2017-04-28 12:11
failed again here https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1023/

**Comment by ncdc** [comment] 2017-04-28 18:32
Jobs 1001 and 1023 are missing logs, so we can't triage them. #13952, once merged, should get us the origin container log we need.

**Comment by brenton** [comment] 2017-05-01 19:25
@ncdc, I just linked another PR.  Is this the same failure? 

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/527/testReport/junit/github/com_openshift_origin_test_end-to-end_core/test_end_to_end_core_sh_88__executing__oc_rollout_status_dc_ipfailover__expecting_success/

**Comment by ncdc** [comment] 2017-05-01 19:35
@brenton it looks similar. I'll review the logs in a bit.

**Comment by ncdc** [comment] 2017-05-01 20:13
@brenton I can't say if the root cause is the same. In the job you linked, the kube garbage collector controller decided to delete the ipfailover-1-deploy pod shortly after it was created and scheduled to a node. I'm not sure why yet...

**Comment by ncdc** [comment] 2017-05-01 20:15
@brenton apparently it's getting garbage collected because it doesn't have any "solid" (still alive) owners. Still need to dig some more. cc @deads2k

**Comment by kargakis** [comment] 2017-05-01 22:30
> @brenton I can't say if the root cause is the same. In the job you linked, the kube garbage collector controller decided to delete the ipfailover-1-deploy pod shortly after it was created and scheduled to a node. I'm not sure why yet...

@mfojtik looks like it's caused by https://github.com/openshift/origin/pull/13582

**Comment by enj** [comment] 2017-05-03 18:03
Seen https://github.com/openshift/origin/issues/13927#issuecomment-298327688

**Comment by sttts** [comment] 2017-05-09 05:24
Who is working on this? @kargakis?

**Comment by mfojtik** [comment] 2017-05-09 08:09
@sttts do we have some log capture? seems like all logs are gone now :/

**Comment by sttts** [comment] 2017-05-09 08:38
@mfojtik no log here. Just asking because I am assigned, but everybody else but me has worked on this issue ;-)

**Comment by kargakis** [comment] 2017-05-09 08:39
@sttts no I am not

**Comment by mfojtik** [comment] 2017-05-10 09:13
@deads2k i managed to reproduce this locally using extended tests.

My theory is, that is is happening when the caches are not warmed or the GC controller is not fully initialized (?) as I can only reproduce this **shortly** after OpenShift master starts up.

**Comment by deads2k** [comment] 2017-05-10 11:43
> My theory is, that is is happening when the caches are not warmed or the GC controller is not fully initialized (?) as I can only reproduce this shortly after OpenShift master starts up.

Before deletion for an orphan, the GC controller does a live lookup here https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/operations.go#L64-L73 called from here https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go#L277-L281 and in the dangling check here: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go#L201-L204

**Comment by mfojtik** [comment] 2017-07-12 09:44
I believe this was fixed by: https://github.com/openshift/origin/pull/14582

**Closed by mfojtik** 2017-07-12 09:44 UTC
Labels: area/tests, component/deployments, kind/test-flake, priority/P1
