### ISSUE TITLE
ImageChange trigger is not taken into account with a custom strategy

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7143] opened 2016-02-09 10:58 UTC
I have a BuildConfig using a custom strategy.

Here is the interesting part 
```
- kind: BuildConfig
  spec:
    strategy:
      type: Custom
      customStrategy:
        from:
          kind: DockerImage
          name: company/builder:latest
        pullSecret:
          name: dockercfg
        forcePull: true
    triggers:
    - type: ImageChange
      from:
        kind: ImageStreamTag
        name: myapp:latest
```

When I look at the resource created with `oc get bc` :

```
        "triggers": [
            {
                "type": "ImageChange",
                "imageChange": {
                    "lastTriggeredImageID": "company/builder:latest"
                }
            }
        ],
```

It seems that my image change is silently overriden with an image change generated automatically by openshift from the docker image of my custom strategy.

I would appreciate to have two ImageChange trigger for a single BuildConfig.

**Comment by bparees** [comment] 2016-02-09 19:51
This is almost certainly a bug...  you are supposed to be able to have multiple ICTs and we definitely shouldn't be changing your existing ICT that you defined.

**Comment by bparees** [comment] 2016-02-09 20:07
i'm not able to reproduce this, can you provide a more explicit set of recreate steps, and also the output of "oc version"?

you can see my custom BC here:
https://gist.github.com/bparees/241698be85fea620a072

as you can see the output still shows a trigger pointing to a random imagestream.

and here is my BC w/ two triggers, one using the "default" imagestream (the one the strategy references) and one defining an explicit imagestream:
https://gist.github.com/bparees/6877fd44326ecb1b6350

**Comment by YannMoisan** [comment] 2016-02-10 08:59
```
❯❯❯ oc version
oc v1.1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4
```

**Comment by YannMoisan** [comment] 2016-02-10 09:18
ok. got it. my bad. The property imageChange was missing in my config !

**Comment by bparees** [comment] 2016-02-10 13:38
ah yes, sorry I missed that.  Can we close this?

**Comment by YannMoisan** [comment] 2016-02-10 14:25
yes. 

BTW, validation of yaml files could be very helpful.

**Comment by bparees** [comment] 2016-02-10 14:27
Yes i'll double check as to why specifying an ICT type, but no ICT body, did not trigger a validation error.

**Closed** 2016-02-10 14:26 UTC
Labels: component/build, priority/P2
