### ISSUE TITLE
oc client generates invalid docker-registry secrets

### ISSUE THREAD

**Issue by toredash** [openshift/origin#18059] opened 2018-01-11 09:13 UTC
At some point, openshift client started to create invalid secrets of type docker-registry. Previous versions of the client (v3.6.0-c4dd4cf) produces correct output.

I'm not sure if this is a client issue, or an issue with OpenShift using the supplied dockercfg in imagePullSecret. 

Relevant information:
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

Newer Docker versions seems to create a configuration file with an outer auths object, which OpenShift doesn't seem to support.

##### Version
oc v3.7.0+7ed6862

##### Steps To Reproduce
1. Verify what is generated with current client:
$ oc create secret docker-registry regsecret --docker-email="mail@mail.com" --docker-password="password" --docker-username="user" --docker-server="https://registry/" --dry-run  -o yaml | grep docker | cut -d":" -f2- | head -n 1 | base64 -D | jq '.'
{
  "auths": {
    "https://registry/": {
      "username": "user",
      "password": "password",
      "email": "mail@mail.com",
      "auth": "dXNlcjpwYXNzd29yZA=="
    }
  }
}

2. Do the same with previous client:
./openshift-origin-client-tools-v3.6.0-c4dd4cf-mac/oc create secret docker-registry regsecret --docker-email="mail@mail.com" --docker-password="password" --docker-username="user" --docker-server="https://registry/" --dry-run  -o yaml | grep docker | cut -d":" -f2- | head -n 1 | base64 -D | jq '.'
{
  "https://registry/": {
    "username": "user",
    "password": "password",
    "email": "mail@mail.com",
    "auth": "dXNlcjpwYXNzd29yZA=="
  }
}

##### Current Result
docker-registry secrets generated with client oc v3.7.0+7ed6862 produces a secret that is not usable with OpenShift, I've tested on two different servers:
$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server X
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server X
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Expected Result
oc client generating valid docker-registry secrets that the remote server is able to use

##### Additional Information
not relevant

**Comment by kargakis** [comment] 2018-01-11 10:08
@openshift/sig-developer-experience

**Comment by mfojtik** [comment] 2018-01-11 10:11
@kargakis this is 

/sig cli

actually and @soltysh is looking into this

**Comment by soltysh** [comment] 2018-01-11 15:38
This should be fixed for 3.7 in #18062.
3.8 is not affected.
master picked a fix in #18003

**Comment by simo5** [comment] 2018-01-31 16:48
@soltysh is this resolved? or is there a reason the issue is still open ?

**Comment by toredash** [comment] 2018-02-01 13:12
This issue is still present in oc v3.7.1+ab0f056

**Comment by soltysh** [comment] 2018-02-05 15:51
The fixed I linked was merged after that release, so this is fixed.

**Closed by soltysh** 2018-02-05 15:51 UTC
Labels: component/cli, priority/P2, sig/master
