### ISSUE TITLE
`osc new-app` setting up imageChange tag wrong?

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2767] opened 2015-06-03 20:13 UTC
`osc new-app mysql` and you'll get the following in the master logs:

`factory.go:68] couldn't create initial Deployment for DeploymentConfig demo/demo/mysql:0: DeploymentConfig "mysql" is invalid: triggers[1].imageChange.tag: invalid value 'latest': no image recorded for demo/mysql:latest`

I'm guessing this might prevent future deployments when the image changes.

**Comment by csrwng** [comment] 2015-06-04 18:02
@sosiouxme - I am not able to reproduce this with the latest master. If you still can, please include the json (or yaml) of the generated deployment config.

**Comment by sosiouxme** [comment] 2015-06-04 19:19
@csrwng I see it still with the most recent AWS vagrant image, running from systemd (`systemctl start openshift`) - don't know if you're looking at quite the same environment.

**Comment by csrwng** [comment] 2015-06-04 21:50
@sosiouxme - I was able to reproduce it in aws. The messsage happens because the deployment config trigger is processed before the image stream tags are populated. However, when the image stream tags get populated, the deployment proceeds as normal. This should be ok.

**Comment by sosiouxme** [comment] 2015-06-05 12:43
@csrwng Well then it's decidedly a p3. Or if you don't mind the message in the logs, I could just close this.

**Comment by csrwng** [comment] 2015-06-05 12:50
I think this is working as designed. So yeah, go ahead and close it.

**Closed** 2015-06-05 12:52 UTC
Labels: component/cli, kind/bug, priority/P2
