### ISSUE TITLE
Wildfly s2i build doesn't print any maven output until it completes?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9573] opened 2016-06-26 23:11 UTC
Ran an s2i build from openshift/wildfly-100-centos7@sha256:3d794405cca3676ca09f7b7798b1122fc9bf2e0c2b5bda6bf050b8e5542380b7 and didn't see any maven output until it had successfully completed.  Docker showed nothing.  

If there's some buffering setting turned on we need to turn it off - terrible build experience.

**Comment by bparees** [comment] 2016-06-27 00:26
that's not the behavior i observe....  i just ran a wildfly s2i build using the wildfly-100-centos7 image and it streamed the maven output to oc logs in realtime.

you want to give me an exact recreate?  (I tested on relatively current master).

we are passing -B (batch mode) to maven, but i think that just strips out the coloring, it shouldn't buffer anything.

**Comment by bparees** [comment] 2016-06-27 00:28
in fact i recall we explicitly added flush calls to s2i to deal w/ this.

**Comment by smarterclayton** [comment] 2016-06-27 00:43
Tried locally with latest master of everything (including sit-builder), on
a Docker 1.9.1 system.

**Comment by bparees** [comment] 2016-06-27 00:50
how was the buildconfig created and how are you viewing the logs?

**Comment by bparees** [comment] 2016-06-27 00:50
(and what source repo are you using)

**Comment by bparees** [comment] 2016-06-27 02:00
i rebuilt master (including all images) on a docker1.10 system and it worked as i'd expect.  I doubt docker1.9 is the difference (especially since i don't recall a time when this didn't work).

**Comment by smarterclayton** [comment] 2016-06-27 04:04
oc cluster up
oc new-project wildfly
Go to console, create newapp based on wildfly:latest, use the default Git
repo

See failures consistently.

**Comment by bparees** [comment] 2016-06-27 14:47
Sent you a vid-cap of it on my machine, seems to be working correctly to me.

**Comment by bparees** [comment] 2016-07-21 17:50
@smarterclayton are you still seeing this?  do you see it w/ any image other than wildfly?

**Comment by bparees** [comment] 2016-08-23 19:00
based on discussion this afternoon it sounds like this might be due to the websocket upgrade failure @jwforres mentioned?

but i'm not certain since the scenario @jwforres described would require you hit refresh before seeing the log output, and you didn't mention doing a refresh.

**Comment by liggitt** [comment] 2016-08-23 19:24
the upgrade failure is only being seen for pods that have no log output (c.f. https://github.com/openshift/origin/issues/10601)

**Comment by jwforres** [comment] 2016-08-23 19:25
yeah but if the builder was being pulled to his machine and took longer than the browser websocket timeout, than it would just look like it at failed

if the build output is just appearing suddenly (without a refresh) then its not the websocket issue

**Comment by bparees** [comment] 2016-08-23 19:47
@smarterclayton do you recall whether you were doing a refresh to see the logs?

**Comment by bparees** [comment] 2016-10-14 17:18
@rhcarvalho i've never been able to recreate this, i think if you also cannot recreate it, we should close it.  Or ask @smarterclayton if he is still seeing this.

**Comment by rhcarvalho** [comment] 2016-10-18 10:02
Steps:

1. In a terminal:

    ```console
    $ oc cluster up              # openshift/origin:v1.4.0-alpha.0
    $ oc new-project wildfly
    ```

2. In the Web Console:

    - Open project "wildfly"
    - Add to project
    - Create "wildfly:10.1 – latest" using the default repo

3. Follow side-by-side:

    - (Chrome) https://localhost:8443/console/project/wildfly/browse/builds/wild-test/wild-test-1?tab=logs
    - (terminal) `oc logs -f builds/wild-test-1`

Result:

All logs came out continuously, line by line. Both Web Console and CLI gave a similar and consistent experience.

The behavior described was **not reproducible**.


----------

@smarterclayton are you okay with closing this?

**Comment by smarterclayton** [comment] 2016-10-19 23:02
Yes

On Oct 18, 2016, at 6:02 AM, Rodolfo Carvalho <notifications@github.com>
wrote:

Steps:

   1.

   In a terminal:

   $ oc cluster up              # openshift/origin:v1.4.0-alpha.0
   $ oc new-project wildfly

   2.

   In the Web Console:
   - Open project "wildfly"
      - Add to project
      - Create "wildfly:10.1 – latest" using the default repo
   3.

   Follow side-by-side:
   - (Chrome)
      https://localhost:8443/console/project/wildfly/browse/builds/wild-test/wild-test-1?tab=logs
      - (terminal) oc logs -f builds/wild-test-1

Result:

All logs came out continuously, line by line. Both Web Console and CLI gave
a similar and consistent experience.

The behavior described was *not reproducible*.
------------------------------

@smarterclayton <https://github.com/smarterclayton> are you okay with
closing this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9573#issuecomment-254463146>,
or mute the thread

**Closed** 2016-10-20 08:35 UTC
Labels: component/build, priority/P3
