### ISSUE TITLE
TestAuthorizationResourceAccessReview flaked

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5681] opened 2015-11-04 05:11 UTC
```
[7.775168622s] [7.775072451s] END
--- FAIL: TestAuthorizationResourceAccessReview-2 (12.22s)
	authorization_test.go:298: unexpected error: namespaces "hammer-project" already exists
FAIL
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6850/

**Comment by liggitt** [comment] 2015-11-04 05:13
Seems like an etcd-related flake? Only way I could see that happening is if the cleanup at the start of the test failed. Might be related in that log:
```
2015/11/3 23:20:47 etcdmain: found invalid file/dir etcd.log under data dir /tmp/openshift-integration/etcd (Ignore this if you are upgrading etcd)
2015/11/3 23:20:47 etcdmain: listening for peers on http://127.0.0.1:47001
2015/11/3 23:20:47 etcdmain: listening for client requests on http://127.0.0.1:44001
2015/11/3 23:20:47 etcdserver: name = test
2015/11/3 23:20:47 etcdserver: data dir = /tmp/openshift-integration/etcd
2015/11/3 23:20:47 etcdserver: member dir = /tmp/openshift-integration/etcd/member
2015/11/3 23:20:47 etcdserver: heartbeat = 100ms
2015/11/3 23:20:47 etcdserver: election = 1000ms
2015/11/3 23:20:47 etcdserver: snapshot count = 10000
2015/11/3 23:20:47 etcdserver: advertise client URLs = http://127.0.0.1:44001
2015/11/3 23:20:47 etcdserver: initial advertise peer URLs = http://127.0.0.1:47001
2015/11/3 23:20:47 etcdserver: initial cluster = test=http://127.0.0.1:47001
2015/11/3 23:20:47 etcdserver: starting member 3b7eaae1345643c9 in cluster a176fdba55eb9204
2015/11/3 23:20:47 raft: 3b7eaae1345643c9 became follower at term 0
2015/11/3 23:20:47 raft: newRaft 3b7eaae1345643c9 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/11/3 23:20:47 raft: 3b7eaae1345643c9 became follower at term 1
2015/11/3 23:20:47 etcdserver: starting server... [version: 2.1.2, cluster version: to_be_decided]
2015/11/3 23:20:47 etcdserver: added local member 3b7eaae1345643c9 [http://127.0.0.1:47001] to cluster a176fdba55eb9204
2015/11/3 23:20:48 raft: 3b7eaae1345643c9 is starting a new election at term 1
2015/11/3 23:20:48 raft: 3b7eaae1345643c9 became candidate at term 2
2015/11/3 23:20:48 raft: 3b7eaae1345643c9 received vote from 3b7eaae1345643c9 at term 2
2015/11/3 23:20:48 raft: 3b7eaae1345643c9 became leader at term 2
2015/11/3 23:20:48 raft: raft.node: 3b7eaae1345643c9 elected leader 3b7eaae1345643c9 at term 2
2015/11/3 23:20:48 etcdserver: setting up the initial cluster version to 2.1.0
2015/11/3 23:20:48 etcdserver: set the initial cluster version to 2.1.0
2015/11/3 23:20:48 etcdserver: published {Name:test ClientURLs:[http://127.0.0.1:44001]} to cluster a176fdba55eb9204
2015/11/3 23:21:22 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/11/3 23:21:22 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/11/3 23:21:22 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/11/3 23:21:22 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/11/3 23:21:22 etcdhttp: got unexpected response error (etcdserver: request timed out)
```

**Comment by smarterclayton** [comment] 2015-11-04 05:16
Hrm the first message is expected - if it's missing that dir, it's also
printed.

**Comment by deads2k** [comment] 2016-01-12 19:32
dupe of https://github.com/openshift/origin/issues/6447

**Closed by deads2k** 2016-01-12 19:32 UTC
Labels: area/tests, kind/test-flake, priority/P2
