### ISSUE TITLE
should be able to retrieve and filter logs flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11776] opened 2016-11-04 13:42 UTC
```
• Failure [364.027 seconds]
[k8s.io] Kubectl client
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
  [k8s.io] Kubectl logs
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
    should be able to retrieve and filter logs [Conformance] [It]
    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/kubectl.go:843

    Nov  4 00:32:17.529: Verified 0 of 1 pods , error : timed out waiting for the condition

    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/kubectl.go:202
```

**Comment by ncdc** [comment] 2016-11-07 20:59
The test failure in 11763 was actually due to image pulling from gcr.io being too slow: 

```
Nov  4 00:32:17.052: INFO: At 2016-11-04 00:31:18 -0400 EDT - event for redis-master-o9hun: {kubelet 172.18.7.142} Failed: Failed to pull image "gcr.io/google_containers/redis:e2e": image pull failed for gcr.io/google_containers/redis:e2e, this may be because there are no credentials on this request.  details: (net/http: request canceled)
```

We might want to mark this as a dupe of #9444 (and retitle that one), and then actually finish the work to pre-pull images.

**Comment by derekwaynecarr** [comment] 2016-11-17 16:17
Closing based on https://github.com/openshift/origin/issues/11776#issuecomment-258960940

**Closed by derekwaynecarr** 2016-11-17 16:17 UTC
Labels: area/tests, kind/test-flake, priority/P2
