### ISSUE TITLE
`oc start-build` times out with chained binary builds

### ISSUE THREAD

**Issue by enj** [openshift/origin#10063] opened 2016-07-27 19:42 UTC
For #9800 I attempted to make a set of chained binary builds.  These would start with a base Fedora image, and then successively make changes in configuration.  I was unable to use `oc start-build` for anything other than the first step, and thus had to use `docker build` instead.
##### Version

```
openshift v1.3.0-alpha.2+0b34629
kubernetes v1.3.0+57fb9ac
etcd 2.3.0+git

oc v1.3.0-alpha.2+1173ef4-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
##### Steps To Reproduce

Create the following binary builds using build configs and Dockerfiles that reference them:
1. `Fedora:23` docker to image stream `Tag1`
2. Image stream `Tag1` to image stream `Tag2`

Use `oc start-build` to create both.
##### Current Result

`oc start-build` works for first build and timesouts on the second.

For #9800 the `openshift.log` showed

```
E0713 11:56:08.733511    8876 pod_workers.go:183] Error syncing pod 39165bf1-4907-11e6-8494-507b9dac97ff, skipping: timeout expired waiting for volumes to attach/mount for pod "fedora-gssapi-kerberos-1-build"/"gssapiproxy". list of unattached/unmounted volumes=[builder-dockercfg-a97gq-push]
```
##### Expected Result

Both builds are successful.

cc @liggitt @stevekuznetsov

**Comment by bparees** [comment] 2016-07-28 14:16
@pmorie this looks like a dupe of the volumes mounting problem.

**Comment by coreydaley** [comment] 2018-01-05 14:33
@enj, are you still having this issue with an up-to-date version of origin?

**Comment by bparees** [comment] 2018-01-17 20:51
closing based on age.

**Closed by bparees** 2018-01-17 20:51 UTC
Labels: area/techdebt, component/build, priority/P2
