### ISSUE TITLE
Master does not purge completed build containers

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1859] opened 2015-04-22 07:04 UTC
Wanted to clean my docker environment (by doing `docker rm` on all containers) after doing some builds with OpenShift: there was a couple build containers and a couple of pods. When I started master after the cleanup, it started all the pods and started building everything all over. Is this expected? If so, how should I purge all the containers?

#### Environment

```
$ docker ps -a
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS                    PORTS               NAMES
7d7b045a527b        buildroot:latest                  "dock --verbose insi   17 hours ago        Exited (0) 17 hours ago                       k8s_custom-build.c2565220_rsyslog-docker-20150421-150107_default_799e7613-e826-11e4-ab1c-fa163e1012c3_8ad66cd2
18ff6788612b        openshift/origin-pod:v0.3.3       "/pod"                 17 hours ago        Exited (0) 17 hours ago                       k8s_POD.8081d85a_rsyslog-docker-20150421-150107_default_799e7613-e826-11e4-ab1c-fa163e1012c3_88224ca2
a3d9d170d21f        buildroot:latest                  "dock --verbose insi   17 hours ago        Exited (0) 17 hours ago                       k8s_custom-build.248c5324_rsyslog-docker-20150421-144916_default_d1eaf208-e824-11e4-ab1c-fa163e1012c3_7db01433
1c69686e28e4        openshift/origin-pod:v0.3.3       "/pod"                 17 hours ago        Exited (0) 17 hours ago                       k8s_POD.8081d85a_rsyslog-docker-20150421-144916_default_d1eaf208-e824-11e4-ab1c-fa163e1012c3_0714a760
769b4f954efb        buildroot:latest                  "dock --verbose insi   18 hours ago        Exited (0) 18 hours ago                       k8s_custom-build.b6914d7e_rsyslog-docker-20150421-142545_default_88aa2207-e821-11e4-ab1c-fa163e1012c3_43cb1a7a
8cecdd462e99        openshift/origin-pod:v0.3.3       "/pod"                 18 hours ago        Exited (0) 18 hours ago                       k8s_POD.8081d85a_rsyslog-docker-20150421-142545_default_88aa2207-e821-11e4-ab1c-fa163e1012c3_72b10de6
4566ec9d2564        buildroot:latest                  "dock --verbose insi   18 hours ago        Exited (0) 18 hours ago                       k8s_custom-build.b7ec4d8b_rsyslog-docker-20150421-141246_default_b8317b55-e81f-11e4-ab1c-fa163e1012c3_52e5fcb9
35cdd993fca0        openshift/origin-pod:v0.3.3       "/pod"                 18 hours ago        Exited (0) 18 hours ago                       k8s_POD.8081d85a_rsyslog-docker-20150421-141246_default_b8317b55-e81f-11e4-ab1c-fa163e1012c3_9d874559
...
```
```
$ osc get builds
NAME                             TYPE                STATUS              POD
hello-world-20150420-171223      Custom              Failed              hello-world-20150420-171223
hello-world-20150420-172801      Custom              Complete            hello-world-20150420-172801
hello-world-20150420-173903      Custom              Complete            hello-world-20150420-173903
hello-world-20150420-174440      Custom              Complete            hello-world-20150420-174440
hello-world-20150420-174603      Custom              Complete            hello-world-20150420-174603
hello-world-20150421-084851      Custom              Complete            hello-world-20150421-084851
hello-world-20150421-085651      Custom              Complete            hello-world-20150421-085651
hello-world-20150421-123151      Custom              Complete            hello-world-20150421-123151
hello-world-20150421-123305      Custom              Complete            hello-world-20150421-123305
rsyslog-docker-20150421-125910   Custom              Failed              rsyslog-docker-20150421-125910
rsyslog-docker-20150421-125950   Custom              Failed              rsyslog-docker-20150421-125950
rsyslog-docker-20150421-133707   Custom              Complete            rsyslog-docker-20150421-133707
rsyslog-docker-20150421-141246   Custom              Complete            rsyslog-docker-20150421-141246
rsyslog-docker-20150421-142545   Custom              Complete            rsyslog-docker-20150421-142545
rsyslog-docker-20150421-144916   Custom              Complete            rsyslog-docker-20150421-144916
rsyslog-docker-20150421-150107   Custom              Complete            rsyslog-docker-20150421-150107
```

#### Steps to reproduce

1. stop (all-in-one) master
2. remove all docker containers (`docker rm -f $(docker ps -a -q)`)
3. start master

#### Actual result

master schedules all builds

#### Expected result

master does *NOT* schedule all builds

**Comment by mfojtik** [comment] 2015-04-22 08:31
@smarterclayton shouldn't kube purge old containers as part of the garbage collection? is this broken currently?

**Comment by soltysh** [comment] 2015-04-22 12:35
It should, based on comments from archived [trello](https://trello.com/c/1Zfnp9u1/497-garbage-collect-pods-used-for-builds) should be handled with https://github.com/GoogleCloudPlatform/kubernetes/issues/4731

**Comment by smarterclayton** [comment] 2015-04-22 15:04
@csrwng had looked at this.

----- Original Message -----

**Comment by TomasTomecek** [comment] 2015-04-22 15:23
so 0.4.3 should have that fix, right?

**Comment by smarterclayton** [comment] 2015-04-22 15:32
The code is there, but it's possible there's still a bug in it.

**Comment by TomasTomecek** [comment] 2015-04-23 06:53
My point with this issue was that master reschedules purged/stopped containers, not that master should reap old build containers -- I'll create another issue for that. Since the discussion already moved to the former problem, let's track it in this issue. Will also rename the issue.

**Comment by liggitt** [comment] 2015-05-09 01:52
@derekwaynecarr is the work you're looking at just to purge completed builds from the API, or does that also affect the containers?

**Comment by derekwaynecarr** [comment] 2015-05-12 01:45
I am looking at pruning builds from API via a CLI call.  I am also looking at allowing a pod to have a deadline on the node before being failed and having all its containers killed.  If a pod is failed or succeeded, the Kubelet filters it out.

For this issue, which is different, do we know if the pods produced by the build actually went into a succeeded or failed state?  If they didn't, and they were set to restart always, the Kubelet would restart it.

Will try to reproduce to see if it still exists.

**Comment by liggitt** [comment] 2015-05-12 01:48
What controls when a completed (failed or succeeded) container gets cleaned up by docker?

**Comment by smarterclayton** [comment] 2015-05-12 01:54
The kubelet garbage collector.  It's set to 10s, 100 containers, max five per.

**Comment by mmilata** [comment] 2015-05-14 16:21
@smarterclayton Does this mean that the GC runs every 10 seconds and tries to keep number of completed containers under 100? What do you mean by five per?

**Comment by smarterclayton** [comment] 2015-05-14 17:53
Here's how the policy is defined:


// Specified a policy for garbage collecting containers.
type ContainerGCPolicy struct {
	// Minimum age at which a container can be garbage collected, zero for no limit.
	MinAge time.Duration

	// Max number of dead containers any single pod (UID, container name) pair is
	// allowed to have, less than zero for no limit.
	MaxPerPodContainer int

	// Max number of total dead containers, less than zero for no limit.
	MaxContainers int
}

The defaults are 10 seconds, 5, and 100.  So a pod that is being restarted continuously, it should never have more than five containers in 'docker ps -a' that are terminated.

----- Original Message -----

**Comment by mmilata** [comment] 2015-05-14 18:04
@smarterclayton So in case of finished build pods which always have two containers, only the total maximum applies by default, right?

**Comment by smarterclayton** [comment] 2015-05-14 19:19
Correct, each finished build pod should only leave 2 containers each.  Once the pods are deleted those containers should be removed.

----- Original Message -----

**Comment by mmilata** [comment] 2015-05-14 20:54
Hmm, I played around with git version, created over 100 builds -> over 200 pods -> over 200 containers and it doesn't look like any got deleted.

https://mmilata.fedorapeople.org/osc_get_builds
https://mmilata.fedorapeople.org/osc_get_pods
https://mmilata.fedorapeople.org/docker_ps_a

**Comment by smarterclayton** [comment] 2015-05-14 21:04
Did you delete the pods?

----- Original Message -----

**Comment by mmilata** [comment] 2015-05-14 21:22
I didn't when posting the previous comment, however now I did and the containers are still there.

**Comment by csrwng** [comment] 2015-05-14 21:40
@smarterclayton @mmilata I found that the current code in origin is not purging terminated pods. However current code in kubernetes is. I would think that when we are rebased we will get whatever is broken fixed. Of course, we'll need to verify.

**Comment by smarterclayton** [comment] 2015-05-14 22:05
I rebased last night.  Is there a fix from today?

----- Original Message -----

**Comment by mmilata** [comment] 2015-05-15 13:11
Tried today with cc9bdf8 with 101 failed builds. Still no change:
```
# osc get builds | wc -l
102
# osc get pods | wc -l
203
# docker ps -a | wc -l
203
# osc get pods | grep -o "^[^ P]*" | xargs osc delete pod
(...)
# osc get pods | wc -l
1
# docker ps -a | wc -l
203
```

**Comment by csrwng** [comment] 2015-05-15 13:14
same here. @smarterclayton I'll take a look at our code, we may be configuring something differently than kube

**Comment by csrwng** [comment] 2015-05-15 15:16
So the issue is that we don't start the garbage collector like kube does:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/app/server.go#L694
However, I'm seeing errors when I do start it in the openshift all-in-one... digging a little further
```
E0515 15:02:54.047923    1118 kubelet.go:618] Container garbage collection failed: dial unix /var/run/docker.sock: resource temporarily unavailable
E0515 15:02:54.048026    1118 kubelet.go:624] Image garbage collection failed: invalid capacity 0 on device "" at mount point ""
```

**Comment by smarterclayton** [comment] 2015-05-19 20:25
Was merged with https://github.com/openshift/origin/pull/2323, will be in 0.5.2

**Closed by smarterclayton** 2015-05-19 20:25 UTC
Labels: component/build, kind/bug, priority/P1

**Comment by mmilata** [comment] 2015-05-20 09:32
Confirmed working, thank you!
