### ISSUE TITLE
template service broker e2e flakes

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15961] opened 2017-08-24 16:52 UTC
```
/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:368
Expected error:
    <*errors.errorString | 0xc420f49c60>: {
        s: "operation returned state failed",
    }
    operation returned state failed
not to have occurred
/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:148
```

and
```
/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_security.go:196
Expected error:
    <*errors.errorString | 0xc421bee430>: {
        s: "operation returned state failed",
    }
    operation returned state failed
not to have occurred
/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_security.go:161
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4725/#showFailuresLink

**Comment by deads2k** [comment] 2017-08-25 12:29
This appears to be fixed now.  What fixed it?

**Comment by deads2k** [comment] 2017-08-25 12:30
> This appears to be fixed now. What fixed it?

Oh, I found it.... https://github.com/openshift/origin/pull/15976

**Comment by deads2k** [comment] 2017-08-25 12:41
Looks like this started failing yesterday morning around build 4722 (https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_install_update).  Nothing leaps out from the commit history as weird (https://github.com/openshift/origin/commits/master).

What *is* weird is that our branch job seems to have worked fine on every level the bot pushed: https://deck-ci.svc.ci.openshift.org/?job=test_branch_origin_extended_conformance_install_update .  I see two possible theories: 
 1. Either @stevekuznetsov or @smarterclayton force pushes broke us.  This seems unlikely since both tested green.
 2. This test is relying on something external that I don't know of and that external thing broke.

**Comment by stevekuznetsov** [comment] 2017-08-25 13:20
What did we force push?

**Comment by bparees** [comment] 2017-08-25 14:56
> What did we force push?

nothing stuck out to me.

**Comment by deads2k** [comment] 2017-08-25 16:03
@stevekuznetsov is there a way to get `oc logs -p` on pods that have been restarted?  I'm betting this server is crashing and restarting.

**Comment by stevekuznetsov** [comment] 2017-08-25 16:07
Do the containers still have to be around for that? We should get all of the container logs (look at `os::cleanup::dump_container_logs`) on the system

**Comment by bparees** [comment] 2017-08-25 16:37
looks like i was wrong about this only failing in the upgrade env
it failed here too:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_templates/73/

**Comment by jim-minter** [comment] 2017-08-25 17:03
The extended test is failing because the templateinstance doesn't become ready within 1h.
At least part of the problem is that the PVC associated with the mysql pod is never binding, so the db doesn't deploy and the app never becomes ready.  Could something around the PV availability have changed?
I also don't like that the app DC immediately tries to deploy the built pod, then cancels the deployment and runs a second deployment.  I don't think this is a cause but it's fishy.  @mfojtik any thoughts?

**Comment by jim-minter** [comment] 2017-08-25 17:09
@stevekuznetsov where are the PVs set up for the cluster, how many are there, do they recycle? Could they be exhausted?

**Comment by jim-minter** [comment] 2017-08-25 17:11
@mfojtik is it intended that a DC with configtrigger + imagechangetrigger should deploy twice after image becomes available for first time?

**Comment by stevekuznetsov** [comment] 2017-08-25 19:24
@jim-minter we run with:

```yaml
osm_controller_args:
  enable-hostpath-provisioner:
    - "true"
```

@sdodson can explain how that ends up working re: how many get provisioned and what turnover looks like

**Comment by jim-minter** [comment] 2017-08-26 01:14
#15966 stops using PVs in these tests, hopefully that might resolve this.

**Closed** 2017-08-26 22:35 UTC
Labels: component/templateservicebroker, kind/test-flake, priority/P1
