### ISSUE TITLE
oc exec seems to have broken on 1.1.3: Content-Type specified (plain/text) must be 'application/json'

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#7881] opened 2016-03-09 10:30 UTC
I've been using `oc exec` alot to open bash shells inside containers to noodle around when things go wrong. Since moving to 1.1.3 it seems to have stopped working; it hangs with the message:
```
Content-Type specified (plain/text) must be 'application/json'

```
here's a debug output in case it helps
```
$ oc exec --loglevel=8 git-collector-cjb74 -it  bash
I0309 10:30:21.836628    9670 loader.go:242] Config loaded from file /root/.kube/config
I0309 10:30:21.837656    9670 loader.go:242] Config loaded from file /root/.kube/config
I0309 10:30:21.838828    9670 loader.go:242] Config loaded from file /root/.kube/config
I0309 10:30:21.839521    9670 loader.go:242] Config loaded from file /root/.kube/config
I0309 10:30:21.960741    9670 round_trippers.go:264] GET https://172.28.128.4:8443/api
I0309 10:30:21.961051    9670 round_trippers.go:271] Request Headers:
I0309 10:30:21.983567    9670 round_trippers.go:289] Response Status: 200 OK in 22 milliseconds
I0309 10:30:21.983605    9670 round_trippers.go:292] Response Headers:
I0309 10:30:21.983615    9670 round_trippers.go:295]     Cache-Control: no-store
I0309 10:30:21.983622    9670 round_trippers.go:295]     Content-Type: application/json
I0309 10:30:21.983628    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:21 GMT
I0309 10:30:21.983634    9670 round_trippers.go:295]     Content-Length: 69
I0309 10:30:21.983694    9670 request.go:878] Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1","v1beta3"]}
I0309 10:30:21.984193    9670 round_trippers.go:264] GET https://172.28.128.4:8443/apis
I0309 10:30:21.984220    9670 round_trippers.go:271] Request Headers:
I0309 10:30:21.985246    9670 round_trippers.go:289] Response Status: 200 OK in 1 milliseconds
I0309 10:30:21.985263    9670 round_trippers.go:292] Response Headers:
I0309 10:30:21.985268    9670 round_trippers.go:295]     Cache-Control: no-store
I0309 10:30:21.985272    9670 round_trippers.go:295]     Content-Type: application/json
I0309 10:30:21.985275    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:21 GMT
I0309 10:30:21.985279    9670 round_trippers.go:295]     Content-Length: 223
I0309 10:30:21.987045    9670 request.go:878] Response Body: {"kind":"APIGroupList","apiVersion":"v1","groups":[{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"}}]}
I0309 10:30:21.987573    9670 round_trippers.go:264] GET https://172.28.128.4:8443/api
I0309 10:30:21.987590    9670 round_trippers.go:271] Request Headers:
I0309 10:30:21.988375    9670 round_trippers.go:289] Response Status: 200 OK in 0 milliseconds
I0309 10:30:21.988388    9670 round_trippers.go:292] Response Headers:
I0309 10:30:21.988392    9670 round_trippers.go:295]     Content-Type: application/json
I0309 10:30:21.988396    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:21 GMT
I0309 10:30:21.988399    9670 round_trippers.go:295]     Content-Length: 69
I0309 10:30:21.988403    9670 round_trippers.go:295]     Cache-Control: no-store
I0309 10:30:21.988434    9670 request.go:878] Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1","v1beta3"]}
I0309 10:30:21.988526    9670 round_trippers.go:264] GET https://172.28.128.4:8443/apis
I0309 10:30:21.988533    9670 round_trippers.go:271] Request Headers:
I0309 10:30:21.989253    9670 round_trippers.go:289] Response Status: 200 OK in 0 milliseconds
I0309 10:30:21.989265    9670 round_trippers.go:292] Response Headers:
I0309 10:30:21.989269    9670 round_trippers.go:295]     Cache-Control: no-store
I0309 10:30:21.989273    9670 round_trippers.go:295]     Content-Type: application/json
I0309 10:30:21.989276    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:21 GMT
I0309 10:30:21.989280    9670 round_trippers.go:295]     Content-Length: 223
I0309 10:30:21.989294    9670 request.go:878] Response Body: {"kind":"APIGroupList","apiVersion":"v1","groups":[{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"}}]}
I0309 10:30:21.989559    9670 round_trippers.go:264] GET https://172.28.128.4:8443/api/v1/namespaces/default/pods/git-collector-cjb74
I0309 10:30:21.989567    9670 round_trippers.go:271] Request Headers:
I0309 10:30:21.989571    9670 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/f0cd09a
I0309 10:30:21.991409    9670 round_trippers.go:289] Response Status: 200 OK in 1 milliseconds
I0309 10:30:21.991420    9670 round_trippers.go:292] Response Headers:
I0309 10:30:21.991424    9670 round_trippers.go:295]     Cache-Control: no-store
I0309 10:30:21.991428    9670 round_trippers.go:295]     Content-Type: application/json
I0309 10:30:21.991431    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:21 GMT
I0309 10:30:21.991454    9670 request.go:878] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"git-collector-cjb74","generateName":"git-collector-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/git-collector-cjb74","uid":"86c46f09-e5de-11e5-8307-08002778481b","resourceVersion":"10094","creationTimestamp":"2016-03-09T10:06:01Z","labels":{"group":"io.fabric8.devops.apps","project":"gitCollector","provider":"fabric8","version":"2.2.123-SNAPSHOT"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"git-collector\",\"uid\":\"1a4687eb-e5c9-11e5-8307-08002778481b\",\"apiVersion\":\"v1\",\"resourceVersion\":\"10082\"}}\n","openshift.io/scc":"restricted"}},"spec":{"volumes":[{"name":"fabric8-token-an3el","secret":{"secretName":"fabric8-token-an3el"}}],"containers":[{"name":"git-collector","image":"fabric8/git-collector:2.2.123-SNAPSHOT","ports":[{"name":"jolokia","containerPort":8778,"protocol":"TCP"}],"env":[{"name":"KUBERNETES_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"resources":{},"volumeMounts":[{"name":"fabric8-token-an3el","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false,"seLinuxOptions":{"level":"s0:c1,c0"}}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","host":"172.28.128.4","serviceAccountName":"fabric8","serviceAccount":"fabric8","nodeName":"172.28.128.4","securityContext":{"seLinuxOptions":{"level":"s0:c1,c0"}},"imagePullSecrets":[{"name":"fabric8-dockercfg-ij08s"}]},"status":{"phase":"Running","conditions":[{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2016-03-09T10:06:02Z"}],"hostIP":"172.28.128.4","podIP":"172.17.0.8","startTime":"2016-03-09T10:06:01Z","containerStatuses":[{"name":"git-collector","state":{"running":{"startedAt":"2016-03-09T10:06:02Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"fabric8/git-collector:2.2.123-SNAPSHOT","imageID":"docker://sha256:fdf263dec9518dceacc0452b119a18caee9f888602ffb1a1f9e1c0119dbbc1b6","containerID":"docker://1ab5d524f7048302084ae52ce990783b831669dc1153ed105279c86767e0b94f"}]}}
I0309 10:30:21.992261    9670 exec.go:182] defaulting container name to git-collector
I0309 10:30:22.119082    9670 round_trippers.go:264] POST https://172.28.128.4:8443/api/v1/namespaces/default/pods/git-collector-cjb74/exec?command=bash&container=git-collector&container=git-collector&stderr=true&stdin=true&stdout=true&tty=true
I0309 10:30:22.119109    9670 round_trippers.go:271] Request Headers:
I0309 10:30:22.119113    9670 round_trippers.go:274]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0309 10:30:22.119117    9670 round_trippers.go:274]     X-Stream-Protocol-Version: channel.k8s.io
I0309 10:30:22.119125    9670 round_trippers.go:264] POST https://172.28.128.4:8443/api/v1/namespaces/default/pods/git-collector-cjb74/exec?command=bash&container=git-collector&container=git-collector&stderr=true&stdin=true&stdout=true&tty=true
I0309 10:30:22.119129    9670 round_trippers.go:271] Request Headers:
I0309 10:30:22.119132    9670 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/f0cd09a
I0309 10:30:22.119136    9670 round_trippers.go:274]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0309 10:30:22.119140    9670 round_trippers.go:274]     X-Stream-Protocol-Version: channel.k8s.io
I0309 10:30:22.168112    9670 round_trippers.go:289] Response Status: 101 Switching Protocols in 48 milliseconds
I0309 10:30:22.168133    9670 round_trippers.go:292] Response Headers:
I0309 10:30:22.168138    9670 round_trippers.go:295]     Connection: Upgrade
I0309 10:30:22.168142    9670 round_trippers.go:295]     Upgrade: SPDY/3.1
I0309 10:30:22.168146    9670 round_trippers.go:295]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0309 10:30:22.168149    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:22 GMT
I0309 10:30:22.168154    9670 round_trippers.go:289] Response Status: 101 Switching Protocols in 49 milliseconds
I0309 10:30:22.168158    9670 round_trippers.go:292] Response Headers:
I0309 10:30:22.168161    9670 round_trippers.go:295]     Connection: Upgrade
I0309 10:30:22.168165    9670 round_trippers.go:295]     Upgrade: SPDY/3.1
I0309 10:30:22.168168    9670 round_trippers.go:295]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0309 10:30:22.168172    9670 round_trippers.go:295]     Date: Wed, 09 Mar 2016 10:30:22 GMT
Content-Type specified (plain/text) must be 'application/json'
```

**Comment by jstrachan** [comment] 2016-03-09 10:55
Looks like the Terminal tab in the OpenShift console has the same issue

**Comment by kargakis** [comment] 2016-03-09 10:58
Dupe of https://github.com/openshift/origin/issues/7873

**Closed** 2016-03-09 14:53 UTC
