### ISSUE TITLE
"oc observe --resync-period=1s …" without "--names" panics

### ISSUE THREAD

**Issue by hansmi** [openshift/origin#17571] opened 2017-12-04 12:10 UTC
Specifying `--resync-period` for `oc observe` without `--names` and `--delete` leads to a panic. The usage output (`-h`) says that `--names` is required, but one would expect an error message rather than a panic.

##### Version
```
# oc version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://[…]:8443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. `oc -n default observe --resync-period=1s pod`
2. Wait ~1 second

##### Current Result
```
# oc -n default observe --resync-period=1s pod
# 2017-12-04T13:02:17+01:00 Sync started
[…]
# 2017-12-04T13:02:17+01:00 Sync 120301941      "" default router-12-vx2l8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1313c09]

goroutine 30 [running]:
panic(0x37ffd80, 0xc420014100)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Resync(0xc420fbd800, 0x0, 0x0)
        /builddir/build/BUILD/atomic-openshift-git-0.0b9377a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:542 +0x79
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc4202da648, 0xc42000c240, 0xc421152540, 0xc421135680, 0xc4211524e0, 0xc4202da650)
        /builddir/build/BUILD/atomic-openshift-git-0.0b9377a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/reflector.go:277 +0x183
created by github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
        /builddir/build/BUILD/atomic-openshift-git-0.0b9377a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/reflector.go:285 +0x520
```

##### Expected Result
Error message and/or usage output.

**Comment by mjudeikis** [comment] 2017-12-04 17:51
Cant recreate on 3.8+
```
mjudeiki@redhat ~]$ oc -n default observe --resync-period=1s pod
# 2017-12-04T17:36:00Z Sync started
# 2017-12-04T17:36:00Z Sync 1086        "" default docker-registry-1-mjfln
# 2017-12-04T17:36:00Z Sync 974 "" default persistent-volume-setup-6zqhm
# 2017-12-04T17:36:00Z Sync 1223        "" default router-1-nswd7
# 2017-12-04T17:36:01Z Sync     "" default docker-registry-1-mjfln
# 2017-12-04T17:36:01Z Sync     "" default persistent-volume-setup-6zqhm
# 2017-12-04T17:36:01Z Sync     "" default router-1-nswd7
# 2017-12-04T17:36:02Z Sync     "" default docker-registry-1-mjfln
# 2017-12-04T17:36:02Z Sync     "" default persistent-volume-setup-6zqhm
# 2017-12-04T17:36:02Z Sync     "" default router-1-nswd7
```

Confirmed it works as expected in 3.7: 
```
[mjudeiki@redhat ~]$ oc_3.7.0 -n default observe --resync-period=1s pod
# 2017-12-04T17:50:33Z Sync started
# 2017-12-04T17:50:33Z Sync 1111        "" default docker-registry-1-pc0hk
# 2017-12-04T17:50:33Z Sync 1324        "" default persistent-volume-setup-7h5c2
# 2017-12-04T17:50:33Z Sync 1176        "" default router-1-lwcvw
# 2017-12-04T17:50:34Z Sync     "" default docker-registry-1-pc0hk
# 2017-12-04T17:50:34Z Sync     "" default persistent-volume-setup-7h5c2
# 2017-12-04T17:50:34Z Sync     "" default router-1-lwcvw
# 2017-12-04T17:50:35Z Sync     "" default docker-registry-1-pc0hk
# 2017-12-04T17:50:35Z Sync     "" default persistent-volume-setup-7h5c2
# 2017-12-04T17:50:35Z Sync     "" default router-1-lwcvw
```


on  3.6.1 confirmed: 
```
mjudeiki@redhat ~]$ oc_3.6.1 -n default observe --resync-period=1s pod
# 2017-12-04T17:48:17Z Sync started
# 2017-12-04T17:48:17Z Sync 1111        "" default docker-registry-1-pc0hk
# 2017-12-04T17:48:17Z Sync 1324        "" default persistent-volume-setup-7h5c2
# 2017-12-04T17:48:17Z Sync 1176        "" default router-1-lwcvw
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13132c9]

goroutine 100 [running]:
panic(0x37fe920, 0xc4200140b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Resync(0xc42136acc0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:542 +0x79
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc420036650, 0xc42000c1e0, 0xc4214d4120, 0xc4212a4a20, 0xc4214d40c0, 0xc420036658)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/reflector.go:277 +0x183
created by github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/reflector.go:285 +0x520
[mjudeiki@redhat ~]$
```

**Comment by mjudeikis** [comment] 2017-12-04 17:53
Closing, as fixed in next release. 3.6<->3.7 clients are compatible. Please reopen if you need something else.

**Comment by mjudeikis** [comment] 2017-12-04 17:53
@pweil do we need to have this if it works?

**Comment by pweil-** [comment] 2017-12-04 17:58
@juanvallejo since this is a panic I'll let you make the call on whether you think it's worth fixing 3.6.x.  Lowering priority though.

**Comment by juanvallejo** [comment] 2017-12-04 19:45
@pweil- Sure, opened a pick of the [upstream fix](https://github.com/kubernetes/kubernetes/pull/53830) against the release-3.6 branch: https://github.com/openshift/origin/pull/17582

**Closed** 2018-08-02 13:59 UTC
Labels: component/cli, kind/bug, lifecycle/rotten, priority/P2
