### ISSUE TITLE
osadm registry should be able to update the registry

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2458] opened 2015-05-22 18:05 UTC
Messed up my credentials, had no way to update the registry short of deletion and recreate.

**Comment by smarterclayton** [comment] 2015-05-22 18:16
Needs to be a flag that allows that

**Comment by ncdc** [comment] 2015-05-22 18:22
--update?

**Comment by sosiouxme** [comment] 2015-05-22 23:14
But you just said it was P3 :) https://github.com/openshift/origin/issues/1175

**Comment by stevekuznetsov** [comment] 2015-11-05 02:35
Dupe of https://github.com/openshift/origin/issues/1175

**Comment by fabianofranz** [comment] 2016-03-01 14:46
Dupe of https://github.com/openshift/origin/issues/1175

**Closed by fabianofranz** 2016-03-01 14:46 UTC
Labels: component/cli, component/imageregistry, kind/bug, priority/P3
