### ISSUE TITLE
Unable to edit image

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9232] opened 2016-06-08 20:09 UTC
Try editing an image

```
$ oc edit image <SHA>
```

When you change something, you get

```
A copy of your changes has been stored to "/var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T/oc-edit-aeu4l.yaml"
error: unable to find api field in struct RawExtension for the json field "ContainerConfig"
```

which comes from LookupPatchMeta trying to traverse down into the Image field (which is an opaque blob).

We should fix this, because it could also apply to other types in the future.

**Comment by smarterclayton** [comment] 2016-06-08 20:10
@kargakis @fabianofranz this is an example of where strategic merge patch can't work in some of our objects.

**Comment by kargakis** [comment] 2016-06-09 14:31
Not a P1 though

**Comment by smarterclayton** [comment] 2016-06-09 14:31
Depends - can I edit templates?  Or are those broken as wel.

**Comment by smarterclayton** [comment] 2016-06-09 14:32
Also policy rules (not sure which other ones are involved).

**Comment by kargakis** [comment] 2016-06-09 14:36
> Depends - can I edit templates? Or are those broken as wel.

Just tested and editing a template works fine.

**Comment by smarterclayton** [comment] 2016-06-09 17:12
It's really disturbing that this fails then.  Agree its not p1

**Comment by kargakis** [comment] 2016-06-18 12:12
Moving to @fabianofranz since I won't get to it any time soon

**Comment by jkaurredhat** [comment] 2017-08-17 12:26
This also fails for annotate : 

while editing image,
oc annotate --overwrite image sha256:c48070e4d8ec99d81170664aa8938dc2152e3c2fe4297bc511131e24f3ad6489 images.openshift.io/deny-execution=false

i get error:
Error from server: unable to find api field in struct RawExtension for the json field "Parent" or 
Error from server: unable to find api field in struct RawExtension for the json field "Id" or
Error from server: unable to find api field in struct RawExtension for the json field "config"

OCP 3.4

**Comment by smarterclayton** [comment] 2017-08-17 17:33
Annotate failing is a pretty high priority.

**Comment by mfojtik** [comment] 2017-08-21 08:58
@smarterclayton i cannot reproduce this on the latest master (guess it was fixed?). Is this 3.4 only?

**Comment by mfojtik** [comment] 2017-08-21 09:00
@smarterclayton @kargakis @soltysh seems like we need to backport https://github.com/openshift/origin/pull/12731 to 3.4?

**Comment by soltysh** [comment] 2017-08-25 12:07
I'm closing this, since master has the fix in https://github.com/openshift/origin/pull/12731 and 3.4 as well.

**Closed by soltysh** 2017-08-25 12:07 UTC
Labels: component/cli, needs-upstream, priority/P1
