### ISSUE TITLE
test/cmd/newapp flakes on finding mysql image

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8433] opened 2016-04-08 19:48 UTC
Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/14320/console):
```
FAILURE after 0.330s: test/cmd/newapp.sh:143: executing 'oc new-app --dry-run --docker-image=mysql' expecting success and text 'This image declares volumes': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
error: no match for "mysql"
```

**Comment by smarterclayton** [comment] 2016-04-20 17:40
Dupe of https://github.com/openshift/origin/issues/7429

**Closed by smarterclayton** 2016-04-20 17:40 UTC
Labels: kind/test-flake, priority/P2
