### ISSUE TITLE
extended test: openshift mongo ephemeral consistently failing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8367] opened 2016-04-06 02:22 UTC
```
• Failure [905.914 seconds]
[images][mongodb] openshift mongodb image
/data/src/github.com/openshift/origin/test/extended/images/mongodb_ephemeral.go:61
  creating from a template
  /data/src/github.com/openshift/origin/test/extended/images/mongodb_ephemeral.go:59
    should process and create the "/data/src/github.com/openshift/origin/examples/db-templates/mongodb-ephemeral-template.json" template [It]
    /data/src/github.com/openshift/origin/test/extended/images/mongodb_ephemeral.go:58

    Expected error:
        <*errors.errorString | 0xc208dce050>: {
            s: "timed out waiting for deployment \"mongodb\" after 15m0s",
        }
        timed out waiting for deployment "mongodb" after 15m0s
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/images/mongodb_ephemeral.go:29
```

Has not passed once in the last 5-10 runs, probably not a flake.

**Comment by bparees** [comment] 2016-04-06 02:46
@php-coder you might want to pull @mfojtik in also since it might be the new readiness check that is causing the deployment failure.

**Comment by mfojtik** [comment] 2016-04-06 09:33
@bparees I've just tested mongo ephemeral locally and it passes the health checks and deploys successfully... wonder if this is rhel7 or centos7 image (going to get rhel7 image to make sure).

**Comment by bparees** [comment] 2016-04-06 12:39
@mfojtik i think our extended tests usually run on the centos imagestreams.

**Comment by php-coder** [comment] 2016-04-06 14:27
I couldn't reproduce it too on my laptop.

**Comment by bparees** [comment] 2016-04-06 14:29
at a minimum maybe add some more debug to the test case, doing an oc describe on the pods and deployments so we can see where it got stuck if it continues to fail. Perhaps waitforadeployment should always do that.

**Comment by php-coder** [comment] 2016-04-06 14:35
When test fails ginkgo should print all steps that were executed with their results. Sometimes these steps should be enough.

@smarterclayton could you provide the full trace or point to the place where I can find it?

**Comment by bparees** [comment] 2016-04-06 14:38
@php-coder those steps are just going to show that we kept checking the oc deployment status and it never read complete.  it won't tell us anything useful about the actual details of the deployment status, i don't think.

there is a full etcd dump that's provided w/ the failure, that could provide more details on the state.

and the logs are in these runs:
https://ci.openshift.redhat.com/jenkins/job/origin_extended/795/

**Comment by smarterclayton** [comment] 2016-04-06 14:52
Also remember that XFS quota is enabled on the extended servers, so it's
possible that your test is writing too much data.

**Comment by php-coder** [comment] 2016-04-06 14:53
@bparees Thank you for the logs! In the steps I see that `router-1-deploy` pod in the `Failed` state:
```
STEP: Collecting events from namespace "extended-test-mongodb-create-5llas-i53es".
Apr  5 23:01:05.342: INFO: POD                      NODE           PHASE      GRACE  CONDITIONS
Apr  5 23:01:05.342: INFO: docker-registry-1-jc1cb  172.18.14.189  Running           [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-04-05 22:29:25 -0400 EDT  }]
Apr  5 23:01:05.342: INFO: router-1-deploy          172.18.14.189  Failed            []
```
Is it possible that this pod affecting this and other failed tests?

**Comment by bparees** [comment] 2016-04-06 14:55
It wouldn't affect this test, but the fact that it also failed is a sign something was very unhealthy about the cluster.

**Comment by smarterclayton** [comment] 2016-04-18 19:57
Is this still failing?

**Comment by bparees** [comment] 2016-04-18 20:15
yes, looks like it recently failed here waiting for deployment:
https://ci.openshift.redhat.com/jenkins/job/origin_extended/818/testReport/junit/%28root%29/Extended/_images__mongodb__openshift_mongodb_image_creating_from_a_template_should_process_and_create_the___data_src_github_com_openshift_origin_examples_db_templates_mongodb_ephemeral_template_json__template/

**Comment by smarterclayton** [comment] 2016-04-23 00:24
Failing again, I'm going to kick it out of the suite unless we know why https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended/lastCompletedBuild/consoleFull

**Comment by bparees** [comment] 2016-04-25 01:29
well it failed waiting for deployment again, so either there's an issue with the readiness check ( @mfojtik ) or there's a legitimate deployment problem.

**Comment by smarterclayton** [comment] 2016-04-25 02:22
Did it fail to import the image?  @ironcladlou on deployment

**Comment by bparees** [comment] 2016-04-25 03:34
I don't think we know currently, but that would be a good thing to add debug for, @php-coder

**Comment by smarterclayton** [comment] 2016-04-25 03:48
You can check by looking at the openshift server log in that time period -
it would tell you whether an import failed.

**Comment by ironcladlou** [comment] 2016-04-25 15:31
FWIW, locally with `master` on f23:

```console
$ EXTENDED_TEST_PATH=test/extended/ _output/local/bin/linux/amd64/extended.test -ginkgo.focus="openshift mongodb image" -ginkgo.v

• [SLOW TEST:143.068 seconds]
[images][mongodb] openshift mongodb image
/home/dmace/Projects/go/origin/src/github.com/openshift/origin/test/extended/images/mongodb_ephemeral.go:61
  creating from a template
  /home/dmace/Projects/go/origin/src/github.com/openshift/origin/test/extended/images/mongodb_ephemeral.go:59
    should process and create the "examples/db-templates/mongodb-ephemeral-template.json" template

Ran 1 of 387 Specs in 143.085 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 386 Skipped PASS

```

**Comment by smarterclayton** [comment] 2016-04-25 15:36
What waits does this code have?  Is there something in mongo itself that is
waiting and then can fail (thus resulting in other failures)?

**Comment by smarterclayton** [comment] 2016-05-09 16:26
Still seeing this - this is a persistent flake at this point.  If we can't figure out what is going on, I'm going to disable the test.

**Comment by mfojtik** [comment] 2016-05-09 16:33
@smarterclayton I think @php-coder identified the problem (admin user creation failed for mongo).... @php-coder ?

**Comment by php-coder** [comment] 2016-05-09 16:42
@mfojtik @mfojtik That was a bug that appears only for replication but this is a different story -- it's a flake, because I was unable to reproduce it on my environment.

**Comment by bparees** [comment] 2016-05-09 16:44
@php-coder have you been able to add any additional debug to help determine the deployment failure reason?

**Comment by php-coder** [comment] 2016-05-09 16:53
We had a quick conversation with @bparees in the IRC and decided that tomorrow I'll look at this issue more detailed and fix it or add debug output.

**Comment by php-coder** [comment] 2016-05-11 10:32
I found out that test started to fail after dda90ccb39a505d676deab0f2c2864e6d8229ae3 commit.

@kargakis Maybe do you know what/where I should update to fix this problem?

**Comment by php-coder** [comment] 2016-05-11 10:45
The error is:
```
E0511 10:38:19.804466   26193 pod_workers.go:138] Error syncing pod 77e26f32-1764-11e6-86ef-080027242396, skipping: failed to "StartContainer" for "mongodb" with ErrImagePull: "Error: image library/mongodb:latest not found"
```

**Comment by mfojtik** [comment] 2016-05-11 10:57
@kargakis @php-coder I don't see any obvious relation between that commit and the failure other than the imagestream is not resolved properly which results into library/mongodb

**Comment by kargakis** [comment] 2016-05-11 11:01
@php-coder the commit you linked to was actually merged a couple of days ago: https://github.com/openshift/origin/pull/7149

**Comment by php-coder** [comment] 2016-05-11 12:33
@kargakis I was unable to reproduce original bug before, but after this commit the test fails on my computer each time. After reverting this commit test passes. Maybe this commit add another problem or it just converts flake to the reproducible issue.

**Comment by kargakis** [comment] 2016-05-11 13:50
Looking

**Comment by php-coder** [comment] 2016-05-11 14:00
@kargakis Thank you! Command for reproducing: `./test/extended/core.sh --focus="openshift mongodb image" -ginkgo.v` Also here is the tests: [mongodb_ephemeral.go](https://github.com/openshift/origin/blob/master/test/extended/images/mongodb_ephemeral.go) and template that test uses: [mongodb-ephemeral-template.json](https://github.com/openshift/origin/blob/master/examples/db-templates/mongodb-ephemeral-template.json)

**Comment by kargakis** [comment] 2016-05-11 14:10
You don't need to run the test suite,
```
oc create -f
https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json
-n openshift
oc new-app -f examples/db-templates/mongodb-ephemeral-template.json
```
is enough. The problem is because the image stream tag in the dc is never
resolved and the deployment never starts. Still not sure why it's special
here as opposed to other image change triggers.
I think it's high time I factor the generator out.

**Comment by smarterclayton** [comment] 2016-05-11 17:04
Does the image stream import fail?

On May 11, 2016, at 10:10 AM, Michail Kargakis <notifications@github.com>
wrote:

You don't need to run the test suite,
```
oc create -f
https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json
-n openshift
oc new-app -f examples/db-templates/mongodb-ephemeral-template.json
```
is enough. The problem is because the image stream tag in the dc is never
resolved and the deployment never starts. Still not sure why it's special
here as opposed to other image change triggers.
I think it's high time I factor the generator out.

On Wed, May 11, 2016 at 4:00 PM, Vyacheslav Semushin <
notifications@github.com> wrote:

> @kargakis <https://github.com/kargakis> Thank you! Command for
> reproducing: ./test/extended/core.sh --focus="openshift mongodb image"
> -ginkgo.v Also here is the tests: mongodb_ephemeral.go
> <
https://github.com/openshift/origin/blob/master/test/extended/images/mongodb_ephemeral.go
>
> and template that test uses: mongodb-ephemeral-template.json
> <
https://github.com/openshift/origin/blob/master/examples/db-templates/mongodb-ephemeral-template.json
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/8367#issuecomment-218468063>
>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/8367#issuecomment-218470941>

**Comment by kargakis** [comment] 2016-05-11 17:43
Nah, automatic was set to false and the image was never resolving to the full spec. Did this test ever work?

**Comment by php-coder** [comment] 2016-05-11 20:32
>Did this test ever work?

Yes, of course.

Thank you for a help and the good work!

**Closed** 2016-05-12 08:53 UTC
Labels: area/tests, component/image, kind/bug, priority/P1
