### ISSUE TITLE
Value of weight doesn't get updated after editing multi-service route

### ISSUE THREAD

**Issue by nichochen** [openshift/origin#11263] opened 2016-10-07 14:50 UTC
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
v1.3.0

##### Steps To Reproduce
1. create a route associates with 2 services, service A and B
2. set weight for service A and B to 10 and 100 respectively
3. save and create the route
4. edit the route and update the weight for service A and B to 50 and 100 respectively
5. click save 
6. after clicking save, user will be navigated back to the route detail info page. The value of  weight for service A and B remain 10 and 100.
7. refresh the page and the value of weights got refreshed and corrected.

##### Current Result
The value of weight doesn't get updated accordingly.

##### Expected Result
The value should be updated accordingly.

**Comment by jwforres** [comment] 2016-10-10 12:42
actually @spadgett this sounds like the issue we fixed in data service that we backported for 3.3.1 already

**Comment by jwforres** [comment] 2016-10-10 12:45
Yeah given that the issue is fixed after a refresh I'm positive this is an issue that has been fixed already https://github.com/openshift/origin-web-console/pull/516

**Closed by jwforres** 2016-10-10 12:45 UTC
Labels: component/routing, component/web, priority/P2
