### ISSUE TITLE
"osc get all" doesn't prefix elements

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2720] opened 2015-06-03 01:10 UTC
```
[joe@ose3-master beta4]$ osc get all
NAME      TYPE      SOURCE
NAME      TYPE      STATUS    POD
NAME      DOCKER REPO   TAGS      UPDATED
NAME      TRIGGERS   LATEST VERSION
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
NAME                    HOST/PORT                               PATH      SERVICE                   LABELS
hello-openshift-route   hello-openshift.cloudapps.example.com             hello-openshift-service   
NAME                      LABELS    SELECTOR               IP(S)            PORT(S)
hello-openshift-service   <none>    name=hello-openshift   172.30.197.132   27017/TCP
POD               IP         CONTAINER(S)      IMAGE(S)                           HOST                                   LABELS                 STATUS    CREATED          MESSAGE
hello-openshift   10.1.1.2                                                        ose3-node1.example.com/192.168.133.3   name=hello-openshift   Running   About a minute   
                             hello-openshift   openshift/hello-openshift:v0.4.3
```

Each set of resources should be prefixed by its type. For example:

````
Routes
NAME                    HOST/PORT                               PATH      SERVICE                   LABELS
hello-openshift-route   hello-openshift.cloudapps.example.com             hello-openshift-service   
```

```
[joe@ose3-master beta4]$ osc version
osc v0.5.2.2-18-gbf80a71
kubernetes v0.17.1-804-g496be63
```

**Comment by kargakis** [comment] 2015-06-03 09:45
https://github.com/openshift/origin/issues/2354

**Comment by liggitt** [comment] 2015-06-18 18:47
dupe of #2354

**Closed by liggitt** 2015-06-18 18:47 UTC
Labels: area/usability, component/cli, priority/P3
