### ISSUE TITLE
No indication that BuildConfig target output repo doesn't exist

### ISSUE THREAD

**Issue by stefwalter** [openshift/origin#4362] opened 2015-08-25 15:28 UTC
If I create a BuildConfig and specify an "output" repository that does not exist, then the build hangs in phase *New* with no indication of why that's the case.

**Comment by stefwalter** [comment] 2015-08-25 15:29
Following the build looks like this:

```
[root@openshiftdev examples]# oc start-build ruby-sample-build --follow
ruby-sample-build-4
error: error getting logs: Timeout: timed out waiting for Build default/ruby-sample-build-4
```

**Comment by stefwalter** [comment] 2015-08-25 15:30
Example of such waiting builds: https://gist.github.com/stefwalter/fee1458b460967368628

The image streams defined: https://gist.github.com/stefwalter/25b542736b594b855525 (ie: missing the origin-ruby-sample stream)

**Comment by smarterclayton** [comment] 2015-08-28 12:04
oc status should tell you.  Also, this is a dupe of another issue we have to reflect build status in the status field.

**Comment by soltysh** [comment] 2015-08-31 10:02
I think you're referring to #3847

**Comment by rhcarvalho** [comment] 2015-09-29 15:52
I just reproduced this, working on a fix (to update build status message appropriately).

**Closed** 2015-10-01 11:17 UTC
Labels: component/build, kind/bug, priority/P2
