### ISSUE TITLE
image import flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#6917] opened 2016-01-29 23:10 UTC
FAILURE after 30.370s: hack/../test/cmd/images.sh:92: executing 'oc import-image mysql:5.6' expecting success and text 'sha256:': the command returned the wrong error code; the output content test failed

from:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/9778/

**Comment by kargakis** [comment] 2016-01-29 23:23
dupe of https://github.com/openshift/origin/issues/6081?

**Comment by bparees** [comment] 2016-01-29 23:28
failure mode looks slightly different but not sure.  will let @pweil- decide.

but i did link this issue from the new jenkins failure-analysis tool, so if we dupe it, we should update jenkins with the right link.

**Comment by smarterclayton** [comment] 2016-01-30 07:11
This is running at the same time as generate/app/cmd, it's likely it's either a timeout from docker, or resource starvation ourselves.  The serve disconnects our import attempt.  We may want to request a longer import window for new-app if that is actually the case, or fail faster on some attempts.

**Comment by smarterclayton** [comment] 2016-01-31 22:04
The timeout leads me to believe either the docker hub or our connection to the hub is significantly delayed (the hub is slow, but not *that* slow).  Things to test:

1. What's exact cause of the delay (probably the Hub, need to be sure)
2. If it's the Hub, find out the percentage of the times the delay happens
3. Decide whether we want a shorter timeout on image import and to make failures on the Hub *not* cause partial match (instead, timeout on fetching from a docker registry only gets shown if there are no other failures and no exact matches)
4. Consider having a shorter timeout on the server side for Hub import and do a retry (can't use the Go lang http.Client to do client side timeout until we drop support for Go 1.4)
5. Consider caching import responses from public remote repositories on the server side for a brief window of time - would have the added benefit of speeding up test cmd and anyone who is frequently importing the same public image across multiple namespaces on the server.

**Comment by smarterclayton** [comment] 2016-02-02 03:58
Bizarrely #6670 seems to fix the flakes (now that jordan fixed the disk io issue)

**Comment by smarterclayton** [comment] 2016-02-04 02:46
Have not seen this since 6670 merged.  Have seen a few newapp unit test stalls, but not the same scenario as before.

**Comment by bparees** [comment] 2016-02-04 04:43
But we don't know why that fixed it?   I'm happy to close this, but..  :/

**Comment by smarterclayton** [comment] 2016-02-04 05:00
No need to close yet - but it's not our most common flake now

**Comment by smarterclayton** [comment] 2016-02-05 22:53
I am still not seeing this.  I'm going to close and reopen if it comes up.

**Closed by smarterclayton** 2016-02-05 22:53 UTC
Labels: component/imageregistry, kind/test-flake, priority/P2
