### ISSUE TITLE
Permissions 0640 for '/var/run/secrets/openshift.io/source/ssh-privatekey' are too open.

### ISSUE THREAD

**Issue by righteousjester** [openshift/origin#19062] opened 2018-03-22 14:32 UTC
Buildconfig using ssh key for authentication into git repo fails to initalise with the following error:

```
Init Containers:
  git-clone:
    Container ID:	docker://f03570a1905eff112e82b7f660f872405c6a494310ee310e738ccf75fa5c9627
    Image:		openshift/origin-docker-builder:v3.7.0
    Image ID:		docker-pullable://docker.io/openshift/origin-docker-builder@sha256:62c00f1f713646be8b4f1c901899577062531409327575df572a416bf5a22208
    Port:		<none>
    Command:
      openshift-git-clone
    Args:
      --loglevel=0
    State:	Terminated
      Reason:	Error
      Message:	Cloning "git@mygitserver.com:myapp/kafka-stream-framework.git" ...
error: Warning: Permanently added 'mygitserver.com,10.132.14.15' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0640 for '/var/run/secrets/openshift.io/source/ssh-privatekey' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/var/run/secrets/openshift.io/source/ssh-privatekey": bad permissions
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

##### Version
```
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1. oc new-app git@mygitserver.com:myapp/kafka-stream-framework.git#remotes/origin/first_version --strategy=docker --source-secret=git -n myproject

##### Current Result
Build fails

```
oc get po
NAME                             READY     STATUS       RESTARTS   AGE
kafka-stream-framework-1-build   0/1       Init:Error   0          1h
kafka-stream-framework-2-build   0/1       Init:Error   0          54m
```

##### Expected Result
Build to start

**Comment by liggitt** [comment] 2018-03-22 18:53
duplicate of #16424

**Closed by liggitt** 2018-03-22 18:53 UTC
