### ISSUE TITLE
Jenkins Integration Test Flake: TestBuildOutputCycleDetection

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8576] opened 2016-04-20 16:25 UTC
Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/222/

```
--- FAIL: TestBuildOutputCycleDetection-2 (0.47s)
	newapp_test.go:1340: successful build from dockerfile with identical input and output image references with warning: unexpected error: no match for "centos"
```

**Comment by smarterclayton** [comment] 2016-04-20 17:39
This is a dupe of #8558

**Closed by smarterclayton** 2016-04-20 17:39 UTC
Labels: kind/test-flake, priority/P2

**Comment by stevekuznetsov** [comment] 2016-04-20 17:55
@smarterclayton you linked a PR of yours... not an issue. what's the correct dupe? Nothing comes up with a  `TestBuildOutputCycleDetection` search.

**Comment by smarterclayton** [comment] 2016-04-20 17:59
Follow the PR chain.  It was unable to import an image.
