### ISSUE TITLE
S2I build should not fail when group set in USER of Dockerfile.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#8568] opened 2016-04-20 03:53 UTC
It appears that S2I uid validation for an S2I builder may assume that the USER directive in a Dockerfile will only ever be set to a single integer value.

The USER directive can though also be provided a group. For example:

```
USER 1001:100
```

There is no reason why providing a group as either an integer or named group should stop S2I working as it is only the user that it needs to validate.

There may be reasons related to permissions in an S2I builder that someone doesn't want to use gid 0 and so wants to override it with USER.

##### Version

```
$ oc version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5
```

##### Steps To Reproduce

Possibly take an S2I builder and change USER from ``1001`` to ``1001:0`` or ``1001:100``.

##### Current Result

```
Error: build error: image "..." must specify a user that is numeric and within the range of allowed users
```

##### Expected Result

Shouldn't fail.

##### Additional Information

Build log.

```
I0420 03:37:18.503535       1 builder.go:46] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"ipython-minibook-2","namespace":"snakes","selfLink":"/oapi/v1/namespaces/snakes/builds/ipython-minibook-2","uid":"2d31855f-06a9-11e6-82ff-525400659b2e","resourceVersion":"8832","creationTimestamp":"2016-04-20T03:37:15Z","labels":{"app":"ipython-minibook","buildconfig":"ipython-minibook","openshift.io/build-config.name":"ipython-minibook"},"annotations":{"openshift.io/build.number":"2"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/rossant/ipython-minibook.git"},"secrets":[]},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4"},"pullSecret":{"name":"builder-dockercfg-ft7zu"},"env":[{"name":"BUILD_LOGLEVEL","value":"8"}],"scripts":"https://raw.githubusercontent.com/GrahamDumpleton/openshift3-jupyter-stacks/master/s2i-bootstrap"}},"output":{"to":{"kind":"DockerImage","name":"172.30.240.125:5000/snakes/ipython-minibook:latest"},"pushSecret":{"name":"builder-dockercfg-ft7zu"}},"resources":{},"postCommit":{}},"status":{"phase":"New","outputDockerImageReference":"172.30.240.125:5000/snakes/ipython-minibook:latest","config":{"kind":"BuildConfig","namespace":"snakes","name":"ipython-minibook"}}}
 
W0420 03:37:18.513480       1 builder.go:55] Master version "v1.1.6-48-g561e4fa" does not match Builder image version "v1.1.6-38-g6ecbaaf"
I0420 03:37:18.515266       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0420 03:37:18.534008       1 sti.go:199] With force pull false, setting policies to if-not-present
I0420 03:37:18.534154       1 sti.go:205] The value of ALLOWED_UIDS is [1-]
I0420 03:37:18.534179       1 sti.go:213] The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
I0420 03:37:18.537305       1 cfg.go:45] Locating docker auth for image 172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4 and type PULL_DOCKERCFG_PATH
I0420 03:37:18.537449       1 cfg.go:111] Using Docker authentication configuration in '/var/run/secrets/openshift.io/pull/.dockercfg'
I0420 03:37:18.537726       1 cfg.go:83] Using serviceaccount user for Docker authentication for image 172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4
I0420 03:37:18.537739       1 cfg.go:45] Locating docker auth for image 172.30.240.125:5000/snakes/ipython-minibook:latest and type PUSH_DOCKERCFG_PATH
I0420 03:37:18.537766       1 cfg.go:111] Using Docker authentication configuration in '/var/run/secrets/openshift.io/push/.dockercfg'
I0420 03:37:18.537985       1 cfg.go:83] Using serviceaccount user for Docker authentication for image 172.30.240.125:5000/snakes/ipython-minibook:latest
I0420 03:37:18.557050       1 docker.go:355] Using locally available image "172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4"
I0420 03:37:18.568761       1 sti.go:232] Creating a new S2I builder with build config: "Builder Image:\t\t\t172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4\nSource:\t\t\t\tfile:///tmp/s2i-build255736058/upload/src\nOutput Image Tag:\t\tsnakes/ipython-minibook-2:56544937\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAMESPACE=snakes,OPENSHIFT_BUILD_SOURCE=https://github.com/rossant/ipython-minibook.git,BUILD_LOGLEVEL=8,OPENSHIFT_BUILD_NAME=ipython-minibook-2\nIncremental Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull Policy:\t\tif-not-present\nPrevious Image Pull Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered Build:\t\t\tdisabled\nS2I Scripts URL:\t\thttps://raw.githubusercontent.com/GrahamDumpleton/openshift3-jupyter-stacks/master/s2i-bootstrap\nWorkdir:\t\t\t/tmp/s2i-build255736058\nDocker NetworkMode:\t\tcontainer:d4566a5682840f1232524dfeed5ccb29a025a6b896255168c1c13dc5c354b316\nDocker Endpoint:\t\tunix:///var/run/docker.sock\nDocker Pull Config:\t\t/var/run/secrets/openshift.io/pull\nDocker Pull User:\t\tserviceaccount\n"
I0420 03:37:18.579852       1 docker.go:355] Using locally available image "172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4"
F0420 03:37:18.604576       1 builder.go:204] Error: build error: image "172.30.240.125:5000/snakes/jupyter-minimal-notebook@sha256:db964642d58cacf231de8619965d4da3a9025054ce7be14efbb0c4aabfa88ed4" must specify a user that is numeric and within the range of allowed users
End of log Go to top
```

**Comment by GrahamDumpleton** [comment] 2016-04-20 23:54
Any idea how complicated this may be to fix and how long it would take?

In trying to get Jupyter Notebooks working out of the box with the official images, this may well end up being the primary blocker. That is, they rely on the user the container runs as being in ``users`` group for file system permissions.

I don't necessarily think they get it totally right as the don't actually specify the group in the ``USER`` of the ``Dockerfile`` so it ends up running with group of ``root`` anyway.

In trying to get them to make changes though I want to limit what they need to change, and adding ``users`` in ``USER`` as group is probably the simplest but S2I builder appears not to look that being done.

Otherwise I have to convince them that they made a poor decision and switch their user to use group of ``root`` and ensure all file system permissions are set up for group ``root`` instead. This is going to be a much harder sell as they even advertise in documentation how they use ``users`` as group and so is quite possible that existing users of the images may be dependent on that. Thus impossible to change.

If that happens, we could never have support for Jupyter Notebooks out of the box from the authors of the images and would be forced to use a shim layer on top to fix up things as I am doing in:

* https://github.com/GrahamDumpleton/openshift3-jupyter-stacks

I want to aim for having working Jupyter images from the provider working by PyCon US which is about a month away. So if changes needed in OpenShift, would need to get into at least Origin by then.

**Comment by bparees** [comment] 2016-04-21 13:21
i'm guessing it should be fairly easy to add `\d+:{0,1}\d*` to the list of supported regexes (ok i'm not positive on that syntax, but you get the idea), though i am wondering if it exposes any additional risk for users masquerading 1001:100 as uid 0.

**Comment by bparees** [comment] 2016-04-21 13:26
@GrahamDumpleton would you need this in 3.2 or origin is fine?

**Comment by jawnsy** [comment] 2016-04-21 16:33
Just adding a reference to the PR that fixes this: https://github.com/openshift/source-to-image/pull/471

**Comment by bparees** [comment] 2016-04-21 16:39
@jawnsy that PR does not fix this since this issue is against origin.  we will need to do a bump of the s2i deps in origin (after that PR merges) to pick up the change before this is fixed.

**Comment by jawnsy** [comment] 2016-04-21 16:43
@bparees Fair enough, it's only half the fix, with the dependency bump being the remaining half.

**Comment by GrahamDumpleton** [comment] 2016-04-21 21:51
Having it in Origin is fine. Right this minute happy that is an S2I fix. If can just get new s2i binary with change I can test on straight Docker whether that will be sufficient for me to get Jupyter working with minimal changes.

**Comment by GrahamDumpleton** [comment] 2016-04-21 23:46
Based on some tests I don't think this change will actually be enough.

The next problem is how Docker works when the ``-u`` option is supplied.

If a ``Dockerfile`` for an S2I builder used:

```
USER 1001:100
```

When you do a straight ``docker run`` then the identity of the user on the container will be:

```
$ docker run -it --rm -e HOME=/home/jovyan -p 8888:8888 my-minimal-notebook id
uid=1001 gid=100(users) groups=100(users)
```

So is inherited from the ``USER`` meta data from Docker image.

If however you supply the ``-u`` option, as OpenShift would do to force it to use a random uid, you get:

```
$ docker run -it --rm -u 10000 -e HOME=/home/jovyan -p 8888:8888 my-minimal-notebook id
uid=10000 gid=0(root) groups=0(root)
```

That is, even though a group wasn't specified by the ``-u`` option to ``docker run``, it overrides the group set in the Docker image meta data and sets it as gid of 0.

If we are going to support the notion that an S2I builder could be setup to want to be run with a different specified group, then it would be necessary for the OpenShift deployer image to retrieve from the ``USER`` meta data of the image the group if specified, and supply that explicitly when the Docker image is run.

Thus would need to extract ``100`` as the group and run as:

```
$ docker run -it --rm -u 10000:100 -e HOME=/home/jovyan -p 8888:8888 my-minimal-notebook id
uid=10000 gid=100(users) groups=100(users)
```

This seems to be the only way to preserve the intent of the S2I builder author that the final application image must still run as a specific group.

This issue probably also applies to non S2I builder images as well. In other words, when a Docker image is run straight from Docker Hub. We should always be using the group specified in the Docker image meta data, if supplied, even though we are setting to random uid.

**Comment by GrahamDumpleton** [comment] 2016-04-22 00:45
Taken this latter issue to aos-devel to try and get wider comment.

**Comment by bparees** [comment] 2016-04-25 00:43
sounds like the second half of this problem is a more general openshift/k8s/docker issue that can't be solved here anyway, so we should proceed w/ the fix @csrwng is preparing, to at least address the parts we(devex) can control.

**Comment by bparees** [comment] 2016-06-10 04:36
@csrwng please confirm the s2i changes have made it into origin and close this.

we can open a new issue that we need to explicitly set the group based on what is in the USER metadata, when launching images in s2i.

**Comment by csrwng** [comment] 2016-06-10 14:07
confirmed

**Closed by csrwng** 2016-06-10 14:07 UTC
Labels: component/build, priority/P2
