### ISSUE TITLE
OSC GET <multiple elements>

### ISSUE THREAD

**Issue by joeburke30** [openshift/origin#2648] opened 2015-06-01 17:39 UTC
osc get pods,services,routes,dc,bc  
PRODUCES:
NAME      TYPE      SOURCE
NAME      TRIGGERS       LATEST VERSION
router    ConfigChange   2
POD              IP         CONTAINER(S)   IMAGE(S)                                                                 HOST                                      LABELS                                                      STATUS    CREATED
router-2-wcjjz   10.1.0.2   router         registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.4.3.2   ose3-master.example.com/192.168.163.138   deployment=router-2,deploymentconfig=router,router=router   Running   20 hours
NAME      HOST/PORT   PATH      SERVICE   LABELS
NAME            LABELS                                    SELECTOR        IP             PORT(S)
kubernetes      component=apiserver,provider=kubernetes   <none>          172.30.17.2    443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes   <none>          172.30.17.1    80/TCP
router          router=router                             router=router   172.30.17.27   80/TCP

NAME as a group category is confusing here.
Recommend that you use: POD, SERVICE, BuildConfig, DeploymentConfig etc.  in stead of name.

**Comment by fabianofranz** [comment] 2016-03-01 14:54
Dupe of https://github.com/openshift/origin/issues/2354

**Closed by fabianofranz** 2016-03-01 14:54 UTC
Labels: component/cli, kind/enhancement, priority/P3
