### ISSUE TITLE
Define behavior when builder image does not exist

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#341] opened 2014-11-05 15:36 UTC
There are a couple of issues to sort out for when the builder image doesn't exist:

1.  How many attempts should be made to pull the image?
2.  How long should we wait between attempts?
3.  What should happen to the build if the builder image can't be pulled?  Should we retry the whole action at some later point?

Changes to pull policy will probably touch upstream.

**Comment by dtschan** [comment] 2015-06-04 09:52
The user should also be informed that there are problems pulling the builder image, including which image the build tries to fetch from which registry. Preferably through the Web Console and through `osc build-logs`. I hit this issue while working with a custom builder on OpenShift Enterprise 3 Beta 3. The build just hung in the pending state and it took me a while to figure out that it couldn't fetch the builder image because of a typo.

**Comment by bparees** [comment] 2015-08-21 03:14
To clarify I think this is only applicable to custom builders.  for s2i and docker type builds, the build will fail as soon as the builder image can't be pulled during the build process.

for a custom build, k8s will continue to try to create the pod forever, i guess.

**Comment by smarterclayton** [comment] 2015-08-28 12:55
There should probably a timeout on custom-build that is defaulted high and user settable.  Do we have build timeouts yet?

**Comment by mfojtik** [comment] 2015-08-28 12:58
@smarterclayton is there a way to tell k8s to timeout when creating a Pod (image not found) ?

**Comment by smarterclayton** [comment] 2015-08-28 12:59
If not there should be.  I don't think waiting forever for a run once pod
makes sense.  Need to be able to set a total deadline.  Derek may know more
about what upstream has planned @derekwaynecarr

On Aug 28, 2015, at 9:58 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> is there a way to tell
k8s to timeout when creating a Pod (image not found) ?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/341#issuecomment-135767835>.

**Comment by soltysh** [comment] 2015-08-28 13:02
Yes there is PodSpec.ActiveDeadlineSeconds, which defines "Optional duration in seconds relative to the StartTime that the pod may be active on a node before the system actively tries to terminate the pod; value must be positive integer". This should do the trick AFAIK.

**Comment by mfojtik** [comment] 2015-08-28 13:04
@soltysh I think it should be aware of the Pod state. I don't want kill the Pod that is already running (for a long time...). This might be solution to timeout long builds.

I believe we are talking here about failing the Pod (and the Build) that is not able to fetch the image for N seconds (configurable).

**Comment by smarterclayton** [comment] 2015-08-28 13:05
It doesn't take into account pull time by design

On Aug 28, 2015, at 10:02 AM, Maciej Szulik <notifications@github.com>
wrote:

Yes there is PodSpec.ActiveDeadlineSeconds, which defines "Optional
duration in seconds relative to the StartTime that the pod may be active on
a node before the system actively tries to terminate the pod; value must be
positive integer". This should do the trick AFAIK.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/341#issuecomment-135768506>.

**Comment by mfojtik** [comment] 2015-08-28 13:08
@smarterclayton isn't think something we can solve in OpenShift Build? I mean if the build controller start a Pod, it controller can set a watcher to watch that Pod. If the state of the Pod is pending for very long time (and the reason is the image does not exists), you can fail the Build (and remove the Pod).

**Comment by smarterclayton** [comment] 2015-08-28 13:21
It applies to jobs and run once pods in general.  Did we add a new timeout
field to Jobs for overall execution?  That would apply to builds I think.
We could do the check in builds, I just want to be sure that is intentional.

On Aug 28, 2015, at 10:08 AM, Michal Fojtik <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> isn't think something
we can solve in OpenShift Build? I mean if the build controller start a
Pod, it controller can set a watcher to watch that Pod. If the state of the
Pod is pending for very long time (and the reason is the image does not
exists), you can fail the Build (and remove the Pod).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/341#issuecomment-135769980>.

**Comment by bparees** [comment] 2015-08-28 13:31
Could, probably shouldn't. This should be a platform capability that
applies to run once pods in general, as @smarterclayton implies.

Ben Parees | OpenShift

**Comment by soltysh** [comment] 2015-08-28 14:12
> It applies to jobs and run once pods in general. Did we add a new timeout field to Jobs for overall execution? That would apply to builds I think. We could do the check in builds, I just want to be sure that is intentional.

It was suggested to be removed and use Pod's ActiveDeadlineSeconds instead, but it's left as a future extensions. Once I'm done with the basic jobs, I'll try to bring back that discussion and start implementing the idea.

**Comment by derekwaynecarr** [comment] 2015-08-28 15:32
@smarterclayton - ActiveDeadlineSeconds does include pull time.  A pod is active based on the kubelet's first observation of it being assigned to its node.  It will then pull image and start container.  In the synch loop for Kubelet, it will see the pod and check if its exceeded its active deadline even if the container has not yet started.  The pod is marked as failed.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2407

**Comment by smarterclayton** [comment] 2015-08-28 15:36
Ok, so then we're ok with just ADS on builds.

On Fri, Aug 28, 2015 at 12:32 PM, Derek Carr <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> -
> ActiveDeadlineSeconds does include pull time. A pod is active based on the
> kubelet's first observation of it being assigned to its node. It will then
> pull image and start container. In the synch loop for Kubelet, it will see
> the pod and check if its exceeded its active deadline even if the container
> has not yet started. The pod is marked as failed.
>
>
> https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2407
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/341#issuecomment-135807629>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-08-29 02:01
What determines when the pod is "active"?  once "docker run" has been handed off?

**Comment by smarterclayton** [comment] 2015-08-30 21:58
As Derek stated, based on the time when a kubelet first observes the pod.

On Fri, Aug 28, 2015 at 11:01 PM, Ben Parees <notifications@github.com>
wrote:

> What determines when the pod is "active"? once "docker run" has been
> handed off?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/341#issuecomment-135927414>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment] 2015-08-31 00:40
@smarterclayton yeah so it doesn't solve this problem does it?

what we want:
timer that expires if the pod is not "running" within a certain period of time.

what we have:
timer that expires if the pod is not assigned to a node within a certain period of time.

Given that activedeadline doesn't even include the pull time, it can't handle the situation where the image doesn't exist.  it's a scheduling timeout.

**Comment by smarterclayton** [comment] 2015-08-31 05:02
ADS handles from when the pod is scheduled - which means it includes pull
time.

I don't know what timer you're referring to, but if you have a timer that
handles something being scheduled, we have both timeouts.

On Sun, Aug 30, 2015 at 9:40 PM, Ben Parees <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> yeah so it doesn't
> solve this problem does it?
>
> what we want:
> timer that expires if the pod is not "running" within a certain period of
> time.
>
> what we have:
> timer that expires if the pod is not assigned to a node within a certain
> period of time.
>
> Given that activedeadline doesn't even include the pull time, it can't
> handle the situation where the image doesn't exist. it's a scheduling
> timeout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/341#issuecomment-136223037>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by soltysh** [comment] 2015-08-31 08:33
I agree with @smarterclayton ADS is perfectly fine for us. The only pull that will happen is the pull for the builder image (not counting the actual build process deps), which in case of a Source or Docker build should be available, or downloading it should not even be taken under consideration. This means the time is mostly consumed for the build process itself, which is fine. In the Custom builder case the total amount of build is the time of pulling the builder + the actual build, which works perfectly fine imho. We will rarely fail with downloading the first two, whereas with the last it's perfectly ok to return user an error with information: timeout launching the build, please check the availability of your builder image.

**Comment by bparees** [comment] 2015-08-31 14:03
I misread @derekwaynecarr's comment as saying pull time is NOT included.  So yes i partly agree this could be used, except it still sounds like it's also going to include the run time of the build, which is problematic since we can't really pick a useful default given the potential range of build times (anywhere from a few minutes for a normal build to hours for a build that is doing some sort of unit testing as part of the build).  And forcing users to configure it if they have long builds seems annoying.

So we still want a timer that tracks from:  "pod was created" to "container is running".  (ie similar to a readiness check except it has nothing to do with routing).  Do we have something like that?  Is ActiveDeadlineSeconds that thing and I'm still misunderstanding?

and @soltysh raises a good point that all of this really only applies to custom builders.  for s2i+docker builders, the "image is not available/found" issue is going to occur inside the builder container, after the pod is "running" and it's going to cause an immediate failure of the build (hopefully with a decent error message).

**Comment by soltysh** [comment] 2015-08-31 14:06
What I'd prefer is, us providing user with sane default but still allowing users to redefine that. So you can have your cake and eat it too :wink:

**Comment by bparees** [comment] 2015-08-31 23:53
@soltysh To accomplish the original goal of this issue, we need a timer that caps "time until the container is running" not "time until the container completes"

that's not to say capping build execution time is not also a useful feature, but that is not what this issue is(was) about, and I don't think we should solve the original issue by using what amounts to a hack (capping total execution time)

**Comment by smarterclayton** [comment] 2015-09-01 01:12
I keep thinking we should just be communicating the status to the user.  A user who knows that the image doesn't exist yet can make their own decision to cancel.  Adding all of these timers doesn't actually improve the users comprehension of the status of the system.

If we had the build controller update the status of the build to "waiting for input image" with a reason and message, wouldn't that solve this just as well *and* give user feedback instantly (not just minutes later).

**Comment by bparees** [comment] 2015-09-01 01:44
sounds reasonable to me.


On Mon, Aug 31, 2015 at 9:12 PM, Clayton Coleman <notifications@github.com>
wrote:

> I keep thinking we should just be communicating the status to the user. A
> user who knows that the image doesn't exist yet can make their own decision
> to cancel. Adding all of these timers doesn't actually improve the users
> comprehension of the status of the system.
>
> If we had the build controller update the status of the build to "waiting
> for input image" with a reason and message, wouldn't that solve this just
> as well *and* give user feedback instantly (not just minutes later).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/341#issuecomment-136541983>.
>



-- 
Ben Parees | OpenShift

**Comment by soltysh** [comment] 2015-09-01 08:28
:+1: we can use the events mechanism more verbally, since currently we use it only to notify about two errors ([here](https://github.com/openshift/origin/blob/master/pkg/build/controller/controller.go#L147) and [here](https://github.com/openshift/origin/blob/master/pkg/build/controller/controller.go#L185)), as it is advised in [k8s convetions](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#events): "Events are complementary to status information"

**Comment by mfojtik** [comment] 2015-09-01 09:05
@soltysh the challenge will be to sort out the events from the builds that are relevant for the user and display them in the `oc get builds` screen.

**Comment by soltysh** [comment] 2015-09-01 09:15
IIRC, `oc get builds` does not returns events, `oc describe build` does for particular build, which makes sense, additionally they are sorted by time. All we need to do is to make sure to provide there some usable information, keeping in mind not to overwhelm users with information on the other hand :wink:

**Comment by smarterclayton** [comment] 2015-09-01 12:53
I'm not proposing events.  I'm proposing status updates to the build, just
like we do for pods.

On Sep 1, 2015, at 5:05 AM, Michal Fojtik <notifications@github.com> wrote:

@soltysh <https://github.com/soltysh> the challenge will be to sort out the
events from the builds that are relevant for the user and display them in
the oc get builds screen.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/341#issuecomment-136641930>.

**Comment by bparees** [comment] 2015-09-29 15:25
@rhcarvalho assigning to you for the "update status" portion of this, related to the other issue you're working.

@soltysh i assume the "how long should we try to pull the image for" bit of this will be covered by your ADS feature.

**Comment by soltysh** [comment] 2015-09-29 16:10
> @soltysh i assume the "how long should we try to pull the image for" bit of this will be covered by your ADS feature.

correct

**Comment by rhcarvalho** [comment] 2015-10-22 08:16
@bparees I believe "my portion" here will be concluded when https://github.com/openshift/origin/pull/4909 merges. The other related, merged, PR was https://github.com/openshift/origin/pull/4872.

**Comment by soltysh** [comment] 2015-10-22 11:37
@bparees I see both of the aforementioned PRs are in, so I assume we're ok with closing this issue?

**Comment by bparees** [comment] 2015-10-22 17:46
yeah, @pmorie we will now abandon a build after the ActiveDeadlineSeconds value expires, if you set one (default is forever).

and oc get build will show you more information about what the build is trying to do.

**Closed by bparees** 2015-10-22 17:46 UTC
Labels: component/build, kind/bug, priority/P3
