### ISSUE TITLE
[localhost] openshift_web_console : Verify that the web console is running

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18569] opened 2018-02-12 09:34 UTC
See: https://openshift-gce-devel.appspot.com//build/origin-ci-test/pr-logs/pull/18524/test_pull_request_origin_extended_conformance_install/7274/

```
Web Console Install        : In Progress (0:06:22)
	This phase can be restarted by running: playbooks/openshift-web-console/config.yml
```

```
fatal: [localhost]: FAILED! => {
    "attempts": 60, 
    "changed": false, 
    "cmd": [
        "curl", 
        "-k", 
        "https://webconsole.openshift-web-console.svc/healthz"
    ], 
    "delta": "0:00:01.037439", 
    "end": "2018-02-12 07:30:14.341591", 
    "generated_timestamp": "2018-02-12 07:30:14.367970", 
    "msg": "non-zero return code", 
    "rc": 7, 
    "start": "2018-02-12 07:30:13.304152", 
    "stderr": [
        "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", 
        "                                 Dload  Upload   Total   Spent    Left  Speed", 
        "", 
        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", 
        "  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to webconsole.openshift-web-console.svc:443; Connection refused"
    ], 
    "stdout": []
}
```

Flaked 40 times in last 10 days, marking as P0. The controller logs for webconsole deployment: https://gist.github.com/mfojtik/4206e4d49253dba05137d0159345eef3

**Comment by mfojtik** [comment] 2018-02-12 09:50
@spadgett @tnozicka according to controller logs I can see that the replica set reached 1 replica and there is no indication of deployment error. I would help if we can dump the `oc get all --all` when this happen to see what state the console pods are.

**Comment by tnozicka** [comment] 2018-02-12 10:22
I see this failure permanently blocking 3.7 https://github.com/openshift/origin/pull/18524
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18524/test_pull_request_origin_extended_conformance_gce/16046/

**Comment by tnozicka** [comment] 2018-02-12 10:56
still looking into it but can this new health check be failing? https://github.com/openshift/origin/pull/18411/files

**Comment by tnozicka** [comment] 2018-02-12 11:46
I didn't see anything broken on controller side for this in master logs; looks like the pod there, just not up.

**Comment by spadgett** [comment] 2018-02-12 13:48
The webconsole container is crash looping.

> Error syncing pod b309476d-0fc5-11e8-9b1a-0e908b42fe1e ("webconsole-1461709481-4ntbk_openshift-web-console(b309476d-0fc5-11e8-9b1a-0e908b42fe1e)"), skipping: failed to "StartContainer" for "webconsole" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=webconsole pod=webconsole-1461709481-4ntbk_openshift-web-console(b309476d-0fc5-11e8-9b1a-0e908b42fe1e)"

We need the console container logs to debug. @stevekuznetsov do you know if the console container logs are available or if that is something we can capture?

Typically the container would crash loop either because:

1. The console config is bad and fails validation on startup, or
2. The console can't connect to the API server to determine if the template service broker is enabled.

I'm considering disabling (2) and trying to determine if the TSB is enabled by looking at the service classes in the browser.

cc @deads2k 

> still looking into it but can this new health check be failing? 

I don't think it's the health check. The console was periodically flaking before that change. Would that result in CrashLoopBackOff status?

> I see this failure permanently blocking 3.7

We shouldn't be trying to install the console in the 3.7 branch :(  That will always fail.

**Comment by deads2k** [comment] 2018-02-12 13:51
> I'm considering disabling (2) and trying to determine if the TSB is enabled by looking at the service classes in the browser.

You could also update to not fail if the check fails on a non-404.  The error ought to be in your logs though.

**Comment by spadgett** [comment] 2018-02-12 14:06
I plan to 

1. Remove or relax the TSB check so it won't crash loop the pod. I'd like to do this check on the client anyway so that we catch when TSB is enabled after the console pod starts.
2. Add some additional logging to openshift-ansible when the console install fails like the tail of the container log to make these problems easier to troubleshoot.

**Comment by spadgett** [comment] 2018-02-12 21:07
The five PRs to change the TSB discovery are

https://github.com/openshift/origin-web-catalog/pull/642
https://github.com/openshift/origin-web-console/pull/2800
https://github.com/openshift/origin-web-console-server/pull/31
https://github.com/openshift/origin/pull/18580
https://github.com/openshift/openshift-ansible/pull/7120

It's not clear if this is the cause of the flake without container logs, but it's a change we wanted to make anyway and makes things simpler.

**Comment by spadgett** [comment] 2018-02-13 15:05
We won't be able to confidently know we've fixed this or troubleshoot future problems without having the console pod logs when install fails. @stevekuznetsov can you help with that?

/assign @stevekuznetsov

**Comment by spadgett** [comment] 2018-02-13 17:49
I have an openshift-ansible PR open to log more details when console install fails:

https://github.com/openshift/openshift-ansible/pull/7132

**Comment by stevekuznetsov** [comment] 2018-02-13 23:34
@sdodson do we want to grab logs in the installer if this fails or do we want this only for the CI?

**Comment by spadgett** [comment] 2018-02-16 18:47
> do we want to grab logs in the installer if this fails or do we want this only for the CI?

I'll defer to @sdodson but it might make sense just to add it to the installer. This would help anyone troubleshoot console install failures. For instance, if I set an incorrect `openshift_web_console_prefix` it would be clear that the install failed because the image couldn't be pulled. Today I'd just see the message in the description with no hints on how to troubleshoot.

**Comment by spadgett** [comment] 2018-02-20 21:01
I don't see any instances of this in snowstorm in the last 48 hours. @mfojtik let me know if I'm looking at it correctly. Note that openshift/origin-web-console-server#31 recently merged, which could have fixed the problem.

openshift/openshift-ansible#7132 is in the merge queue and should give us more detail if it happens again.

**Comment by spadgett** [comment] 2018-02-20 21:03
https://github.com/openshift/openshift-ansible/pull/7108 also disables the console install for releases before 3.9.

Closing this issue.

/close

**Closed by spadgett** 2018-02-20 21:03 UTC
Labels: component/web, kind/test-flake, priority/P0, sig/user-interface
