### ISSUE TITLE
extended [Conformance] flake: should deploy based on a status version bump

### ISSUE THREAD

**Issue by miminar** [openshift/origin#9951] opened 2016-07-20 13:08 UTC
```
• Failure [77.901 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:603
  generation
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:389
    should deploy based on a status version bump [Conformance] [It]
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:388

    Expected error:
        <*errors.errorString | 0xc8200ce140>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:357
------------------------------
[volumes] Test local storage quota FSGroup local storage quota 
  should be applied to XFS filesystem when a pod is created
  /data/src/github.com/openshift/origin/test/extended/localquota/local_fsgroup_quota.go:149
```

See related [job 3740](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3740/consoleFull).

**Comment by smarterclayton** [comment] 2016-07-25 22:32
Dupe of #9680

**Closed by smarterclayton** 2016-07-25 22:32 UTC
Labels: kind/test-flake, priority/P2
