### ISSUE TITLE
TestSimpleImageChangeBuildTriggerFromImageStreamTagCustomWithConfigChange

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14348] opened 2017-05-25 13:00 UTC
Stacktrace:
```
=== RUN   TestSimpleImageChangeBuildTriggerFromImageStreamTagCustomWithConfigChange
masterAddr: "127.0.0.1:12000"
Created project integration
--- FAIL: TestSimpleImageChangeBuildTriggerFromImageStreamTagCustomWithConfigChange (7.50s)
	imagechange_buildtrigger_test.go:313: expected watch event type MODIFIED, got DELETED
	etcd.go:126: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-runtime.call32.json"
FAIL
```

First occured in https://github.com/openshift/origin/pull/14345

**Comment by gabemontero** [comment] 2017-05-25 14:28
confirmed intermittent ... just rebased/rebuilt and did not turn up after a few runs on master

and agree that changes in https://github.com/openshift/origin/pull/14345 seem unrelated

**Comment by gabemontero** [comment] 2017-05-26 20:38
@bparees would the image pruning issue with the build extended tests you mentioned in scrum this AM have any bearing here?

Perhaps an images was pruned and that generated the DELETED event?

**Comment by bparees** [comment] 2017-05-26 20:40
i don't think so.  pruning an image off the node should not have any effect on the existing of the imagestreamtag.

**Comment by gabemontero** [comment] 2017-05-30 20:41
@mfojtik - is the `/tmp/openshift/test-integration/etcd-dump-runtime.call32.json` from the failed run salvageable ?

**Comment by gabemontero** [comment] 2017-05-30 21:03
OK, the debug I was getting ready to add was added by @smarterclayton via https://github.com/openshift/origin/pull/14351 as part of debugging https://github.com/openshift/origin/issues/14208 a few days ago.

In that flake, a DELETE event was received unexpectedly as well.

@mfojtik @smarterclayton - is there enough similarity in these watch related tests to claim this bug is a duplicate of https://github.com/openshift/origin/pull/14351 ?

If not, then at this point we sit tight until there is another instance with the added debug, and go from there.

**Comment by mfojtik** [comment] 2017-05-31 09:48
@gabemontero sure, feel free to bump this to P2

**Comment by gabemontero** [comment] 2017-05-31 13:37
thx @mfojtik

**Comment by gabemontero** [comment] 2017-10-02 18:15
shall we close due to age?

**Comment by bparees** [comment] 2017-10-02 18:24
seems reasonable, certainly haven't seen it in forever and i think the code has changed too.

**Closed by bparees** 2017-10-02 18:24 UTC
Labels: kind/test-flake, priority/P2
