### ISSUE TITLE
Docker Registry HTTP API V2 no longer requires default namespace

### ISSUE THREAD

**Issue by twaugh** [openshift/origin#6711] opened 2016-01-19 09:19 UTC
It is possible for a Docker pullspec to have the form registry/repository, with no namespace component.

For V1, the prefix "library/" is added to the repository name if it does not specify a namespace.

However, for V2 this is not necessary, as a "bare" repository name is allowed by the registry API. Adding this prefix causes some V2 content to be unavailable unless it is published as "library/repository".

I think this is where the prefix is added:
https://github.com/openshift/origin/blob/master/pkg/image/api/helper.go#L64

To clarify, I'm seeing this happen when adding ImageStreams like:

```
{
    "kind": "ImageStream",
    "apiVersion": "v1",
    "metadata": {
        "name": "busybox",
        "namespace": "default"
    },
    "spec": {
        "dockerImageRepository": "my.registry.name/busybox"
    }
}
```

**Comment by kargakis** [comment] 2016-01-19 10:00
cc @miminar @soltysh @smarterclayton @ncdc

**Comment by soltysh** [comment] 2016-01-19 10:45
This is already discussed in #6570

**Comment by miminar** [comment] 2016-01-19 12:07
`library/` prefix shall be added only for Docker hub as [suggested](https://github.com/openshift/origin/issues/6570#issuecomment-171146108) by Andy. That's also what Docker daemon does.

**Comment by pweil-** [comment] 2016-01-19 15:28
closing as a duplicate of https://github.com/openshift/origin/issues/6570

**Closed by pweil-** 2016-01-19 15:28 UTC
