### ISSUE TITLE
RPM spec builds need to use hack/build-cross.sh

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10027] opened 2016-07-25 22:24 UTC
For consistency and supportability, the details of how the binaries build needs to be part of the origin source repo, not a separate set of scripts.  We need to identify any gaps or requirements from the RPM side and then fix them in build-cross.sh.  I can answer any questions regarding it, especially if there are specific reasons why it's not used, and help fix them.

@sdodson @tdawson

**Comment by smarterclayton** [comment] 2016-07-25 22:25
Brew needs to be using it as well.

**Comment by tdawson** [comment] 2016-07-25 22:52
I believe it wasn't being used because originally the scripts were pulling lots of things down during the builds.  I don't think that is the case nowdays.
Do you think it's early enough in the 1.3 timeframe for us to try it?
I would love to give the spec file a major overhaul, possibly pulling in a few other issues as well.

**Comment by smarterclayton** [comment] 2016-07-26 00:10
Possibly.  I suspect that if build-cross doesn't work we'll know fast.

On Jul 25, 2016, at 6:52 PM, Troy Dawson <notifications@github.com> wrote:

I believe it wasn't being used because originally the scripts were pulling
lots of things down during the builds. I don't think that is the case
nowdays.
Do you think it's early enough in the 1.3 timeframe for us to try it?
I would love to give the spec file a major overhaul, possibly pulling in a
few other issues as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10027#issuecomment-235110812>,
or mute the thread

**Comment by tdawson** [comment] 2016-07-26 13:46
Because I never use the scripts, I need some guidance.
What commands do you expect me to run to get the binaries built in an rpm?
Should I be able to just do
./hack/build-cross.sh
Or do I need to setup various variables first?

**Comment by smarterclayton** [comment] 2016-07-26 13:59
hack/build-cross.sh + creating the os-version-defs file (format is in
hack/common.sh) *should* be everything you need.  You can override
platforms if you want.

I suspect there may be things around static file compilation that crop up,
and possibly the whole "golang is a fiery mess".

**Comment by tdawson** [comment] 2016-07-26 15:01
Question on os-version-defs
The format is not in common.sh, or if it is, I'm not finding it.
I cannot find any documentation on it, nor an example.
How do I generate it?  Or, can you give me an example of one.

**Comment by smarterclayton** [comment] 2016-07-26 19:20
# Saves the environment flags to $1
function os::build::save_version_vars() {
  local version_file=${1-}
  [[ -n ${version_file} ]] || {
    echo "!!! Internal error.  No file specified in
os::build::save_version_vars"
    return 1
  }

  cat <<EOF >"${version_file}"
OS_GIT_COMMIT='${OS_GIT_COMMIT-}'
OS_GIT_TREE_STATE='${OS_GIT_TREE_STATE-}'
OS_GIT_VERSION='${OS_GIT_VERSION-}'
OS_GIT_MAJOR='${OS_GIT_MAJOR-}'
OS_GIT_MINOR='${OS_GIT_MINOR-}'
KUBE_GIT_COMMIT='${KUBE_GIT_COMMIT-}'
KUBE_GIT_VERSION='${KUBE_GIT_VERSION-}'
EOF
}

**Comment by smarterclayton** [comment] 2016-07-26 19:21
Call   os::build::get_version_vars first

**Comment by tdawson** [comment] 2016-07-28 22:44
I've made a quick little script and done some experimenting.

```
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
OS_ROOT=$(dirname "${BASH_SOURCE}")/..
source "${OS_ROOT}/hack/lib/init.sh"
os::build::get_version_vars
os::build::save_version_vars os-version-defs
```

The problem is that the rpm tarball doesn't have the .git directory, so the scripts can't get any of the OS_GIT variables.
I believe I can use tito to setup those variables in the rpm spec file, just like it does the ldflags.
That should get the scripts working during rpmbuild.  After that, we'll see what's next.

On a related issue, I've found most of this out while working on automatically generating the man files.
#9407

**Comment by tdawson** [comment] 2016-08-09 20:37
I've made alot of progress on the rpm spec using the hack scripts, but I've run into a problem that I can't figure out without getting really messy.

When running the hack/build-cross.sh script as a regular user I get the following error(s).  Not all at once.  I'll get one, temp fix it, get the next, temp fix ... and so on.

```
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/darwin_amd64: permission denied
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/linux_386: permission denied
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/linux_amd64_cgo: permission denied
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/windows_amd64: permission denied

```
These errors are fixed by making the directories (as root) and setting permissions to 777 on the directories.

But this is a huge problem in rpm building, especially in a mock environment like koji or brew.  The rpm isn't built as a root user.

I have tried adding "-pkgdir _output/pkgdir" to various go commands in the hack scripts, but that is where things get really messy.

What do people think is the proper way to fix this problem?

**Comment by smarterclayton** [comment] 2016-08-09 21:20
This is because (I think) that the cgo flags aren't properly compatible
with the golang packages from us.  Try commenting out the -installsuffix
flag in common.sh

On Aug 9, 2016, at 4:37 PM, Troy Dawson <notifications@github.com> wrote:

I've made alot of progress on the rpm spec using the hack scripts, but I've
run into a problem that I can't figure out without getting really messy.

When running the hack/build-cross.sh script as a regular user I get the
following error(s). Not all at once. I'll get one, temp fix it, get the
next, temp fix ... and so on.

go install runtime/internal/sys: mkdir
/usr/lib/golang/pkg/darwin_amd64: permission denied
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/linux_386:
permission denied
go install runtime/internal/sys: mkdir
/usr/lib/golang/pkg/linux_amd64_cgo: permission denied
go install runtime/internal/sys: mkdir
/usr/lib/golang/pkg/windows_amd64: permission denied


These errors are fixed by making the directories (as root) and setting
permissions to 777 on the directories.

But this is a huge problem in rpm building, especially in a mock
environment like koji or brew. The rpm isn't built as a root user.

I have tried adding "-pkgdir _output/pkgdir" to various go commands in the
hack scripts, but that is where things get really messy.

What do people think is the proper way to fix this problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10027#issuecomment-238683096>,
or mute the thread

**Comment by tdawson** [comment] 2016-08-10 14:54
I've tried several variations of commenting out -installsuffix, removing it, changing CGO_ENABLED=0 to CGO_ENABLED=1, all with no luck.

**Comment by smarterclayton** [comment] 2016-08-10 15:09
@ncdc were you the one who debugged this before?

**Comment by smarterclayton** [comment] 2016-08-10 15:10
Or @vbatts?

**Comment by ncdc** [comment] 2016-08-10 15:15
I ran into this but figured out a way around whatever it was that I was doing at the time. I never resolved the problem.

**Comment by ncdc** [comment] 2016-08-10 15:16
The problem is we don't have RPMs that include the other runtimes.

**Comment by sdodson** [comment] 2016-08-10 15:31
https://bugzilla.redhat.com/show_bug.cgi?id=1350010 but was CLOSED NOTABUG :frowning:

**Comment by tdawson** [comment] 2016-08-11 14:25
Progress thus far:
1) I created a golang-pkg rpm that has all the golang-pkg's that was in the golang 1.4.2 rpm's.  I'm hoping that we can get those back into the official 1.6 rpm, but I'm preparing for that taking a long time.

2) With those installed, the script then failed because it was trying to build with those languages with an _mco extension (pkg/linux_amd64_cgo).  I got around that by removing -installsuffix=cgo from hack/common.sh

3) I have now run into the following issue that I don't understand.  This is after we have successfully built openshift and oc for all the supported platforms.

```
++ Building go targets for linux/amd64: images/pod cmd/dockerregistry cmd/gitserver examples/hello-openshift examples/deployment
go install -tags include_gcs -a  -ldflag -X github.com/openshift/origin/pkg/version.majorFromGit=1 -X github.com/openshift/origin/pkg/version.minorFromGit=3+ -X github.com/openshift/origin/pkg/version.versionFromGit= -X github.com/openshift/origin/pkg/version.commitFromGit=9150947 -X github.com/openshift/origin/pkg/version.buildDate=2016-08-11T13:16:59Z -X github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/version.gitCommit=57fb9ac -X github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.3.0+57fb9ac -X github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/version.buildDate=2016-08-11T13:16:59Z -X github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean github.com/openshift/origin/images/pod github.com/openshift/origin/cmd/dockerregistry github.com/openshift/origin/cmd/gitserver github.com/openshift/origin/examples/hello-openshift github.com/openshift/origin/examples/deployment
go install runtime/internal/sys: open /usr/lib/golang/pkg/linux_amd64/runtime/internal/sys.a: permission denied
[ERROR] PID 2767: hack/common.sh:326: `GOOS=${platform%/*} GOARCH=${platform##*/} go install "${goflags[@]:+${goflags[@]}}" "${platform_goflags[@]:+${platform_goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]}"` exited with status 1.
[INFO]          Stack Trace: 
[INFO]            1: hack/common.sh:326: `GOOS=${platform%/*} GOARCH=${platform##*/} go install "${goflags[@]:+${goflags[@]}}" "${platform_goflags[@]:+${platform_goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]}"`
[INFO]            2: hack/common.sh:264: os::build::internal::build_binaries
[INFO]            3: hack/common.sh:250: os::build::build_binaries
[INFO]            4: hack/build-cross.sh:34: os::build::build_static_binaries
[INFO]   Exiting with code 1.
[ERROR] PID 2341: hack/common.sh:261: `local -a binaries=("$@")` exited with status 1.
[INFO]          Stack Trace: 
[INFO]            1: hack/common.sh:261: `local -a binaries=("$@")`
[INFO]            2: hack/common.sh:250: os::build::build_binaries
[INFO]            3: hack/build-cross.sh:34: os::build::build_static_binaries
[INFO]   Exiting with code 1.
```
I have verified that  /usr/lib/golang/pkg/linux_amd64/runtime/internal/sys.a is there, that it is world readable.  I tried changing it to world executable, just incase, but that didn't work.  Things are acting like they want to expand sys.a in the global directory, but that seems like an odd thing to do.

Does this ring a bell with anyone?

**Comment by tdawson** [comment] 2016-08-11 14:30
So, as a test, I did chmod 777  /usr/lib/golang/pkg/linux_amd64/runtime/internal/

This worked, and it moved onto the same error on another file in a different directory.

**Comment by tdawson** [comment] 2016-08-12 16:54
Solved (Final Solution):

I added "-pkgdir ${GOPATH}/src/${OS_GO_PACKAGE}" to the go install in common.h.

Previously when I had added -pkgdir to go install, I had picked my own directory.  This time I put in what we are setting go_pkg_dir to locally.  Since the two pkg directories match, everyone is happy.

I don't even need to have the golang-pkg rpm's installed.

I still have a few more tweeks in the rpm spec file (mainly getting the binaries from their new location) but I hopefully will have a pull request soon.

**Comment by tdawson** [comment] 2016-08-12 21:51
The only issue I have left is extended.test

We are currently generating it in the rpm by doing
`go test -c -o _build/bin/extended.test -ldflags "%{ldflags}" %{import_path}/test/extended`

I have tried building it using 
`hack/build-go.sh test/extended`
but that doesn't seem to work.

**Comment by liggitt** [comment] 2016-08-12 21:53
`hack/build-go.sh test/extended/extended.test`

**Comment by tdawson** [comment] 2016-08-12 22:58
That was the final piece of the puzzle, thank you. 

Pull request here: #10398

**Comment by tdawson** [comment] 2016-08-19 21:35
Marking this closed wtih the pull request merged.

**Closed by tdawson** 2016-08-19 21:35 UTC
Labels: area/infrastructure, priority/P2

**Comment by smarterclayton** [comment] 2016-08-19 22:36
Thanks for making this happen Troy, will hopefully smooth further bumps out.
