### ISSUE TITLE
Failing to load metrics: oc cluster up --metrics  not working

### ISSUE THREAD

**Issue by zmhassan** [openshift/origin#13310] opened 2017-03-08 18:00 UTC
When starting up `oc cluster up --metrics` the images for hawkular metrics fail to start up:

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. oc cluster up --metrics
2. oc project openshift-infra
2. oc get pods

##### Current Result
```bash
bash-3.2$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
metrics-deployer-pod-2wncv   0/1       Error     0          6m
metrics-deployer-pod-3lfw5   0/1       Error     0          5m
metrics-deployer-pod-6nqws   0/1       Error     0          4m
metrics-deployer-pod-ch85d   0/1       Error     0          3m
metrics-deployer-pod-gw209   0/1       Error     0          3m
metrics-deployer-pod-hdhdg   0/1       Error     0          5m
metrics-deployer-pod-k04t9   0/1       Error     0          7m
metrics-deployer-pod-lf1g8   0/1       Error     0          4m
metrics-deployer-pod-m7x1h   0/1       Error     0          3m
metrics-deployer-pod-p8dwt   0/1       Error     0          2m
metrics-deployer-pod-r163d   0/1       Error     0          2m
metrics-deployer-pod-rp7hv   0/1       Error     0          5m
metrics-deployer-pod-vlfz0   0/1       Error     0          5m
metrics-deployer-pod-xcxz8   0/1       Error     0          4m
metrics-deployer-pod-zftsl   0/1       Error     0          4m
```
```bash
bash-3.2$ oc describe pod metrics-deployer-pod-2wncvo```bash 
 FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  1m            1m              1       {default-scheduler }                    Normal          Scheduled       Successfully assigned metrics-deployer-pod-2wncv to 192.168.65.2
  1m            1m              1       {kubelet 192.168.65.2}                  Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "Failed to check docker api version: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""

  1m    1m      1       {kubelet 192.168.65.2}  spec.containers{deployer}       Normal  Pulled          Container image "openshift/origin-metrics-deployer:v1.5.0-alpha.3" already present on machine
  1m    1m      1       {kubelet 192.168.65.2}  spec.containers{deployer}       Normal  Created         Created container with docker id d29cd99e658b; Security:[seccomp=unconfined]
  1m    1m      1       {kubelet 192.168.65.2}  spec.containers{deployer}       Normal  Started         Started container with docker id d29cd99e658b
  1m    1m      1       {kubelet 192.168.65.2}                                  Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "deployer" with RunContainerError: "Failed to check docker api version: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""
```

##### Expected Result
Pods should be running
##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment] 2017-03-08 18:36
```
Error syncing pod, skipping: failed to "StartContainer" for "deployer" with RunContainerError: "Failed to check docker api version: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""
```
duplicate of https://github.com/openshift/origin/issues/13281

**Closed by pweil-** 2017-03-08 18:36 UTC
