### ISSUE TITLE
The osc edit shows errors on non-existing lines

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2685] opened 2015-06-02 12:41 UTC
When I `osc edit` something and I make a mistake the comment on top gives me the exact line in the YAML where I made the mistake... However it reads the original content from server and all my changes are lost (first problem) and it points me to line that does not exists...

**Comment by mfojtik** [comment] 2015-06-02 12:41
@smarterclayton @kargakis FYI

**Comment by smarterclayton** [comment] 2015-06-02 13:13
What actual mistake did you make?

**Comment by mfojtik** [comment] 2015-06-02 13:31
@smarterclayton indentation error (i hope)

**Comment by smarterclayton** [comment] 2015-06-02 15:37
If those things fail we shouldn't be requerying the server or updating what the user sent.

**Comment by kargakis** [comment] 2015-06-09 12:56
I have managed to fix the first problem. Regarding the second, the problem is that the indentation error returned which reports the line number gets invalidated since we go on adding it to the file (minimum two more lines hence wrong line number in the next iteration). I see two solutions to this: 1) add a placeholder for errors or 2) parse the error message and replace the line number with the new one. Even though the first approach doesn't scale, currently `oc edit` doesn't report something more than those two extra lines and it feels less hacky than 2. Thoughts?

Also another issue I found out while playing around with this is that on syntax errors such as a misspelling of a resource, `oc edit` doesn't report anything but exits. I guess we should report to the user those errors as well and keep the session open.

**Comment by kargakis** [comment] 2015-06-09 13:05
The comparison of the original and edited file is also broken because it takes into account comments. I have it fixed locally.

**Comment by smarterclayton** [comment] 2015-06-09 13:10
I think this is going to have to be post 3.0.

----- Original Message -----

**Comment by fabianofranz** [comment] 2015-09-28 18:17
@kargakis is this fixed already?

**Comment by kargakis** [comment] 2015-09-28 19:04
> @kargakis is this fixed already?

The first part of it is fixed in https://github.com/openshift/origin/pull/2993

**Closed** 2016-01-28 12:04 UTC
Labels: component/cli, kind/bug, priority/P3
