### ISSUE TITLE
[Feature:DeploymentConfig] deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment [Suite:openshift/conformance/parallel]

### ISSUE THREAD

**Issue by enj** [openshift/origin#17696] opened 2017-12-08 18:01 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17617/test_pull_request_origin_extended_conformance_gce/12598/

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:188
2017-12-07 23:04:17.348365697 +0000 UTC: Deployer pod invariant broken! More than one unterminated deployer pod exists for DC extended-test-cli-deployment-ffkld-lssr4/deployment-simple!
		List of unterminated pods: ([]*v1.Pod)[<*>(0xc420be6000)&Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:deployment-simple-2-deploy,GenerateName:,Namespace:extended-test-cli-deployment-ffkld-lssr4,SelfLink:/api/v1/namespaces/extended-test-cli-deployment-ffkld-lssr4/pods/deployment-simple-2-deploy,UID:ecf709c8-dba2-11e7-a6e7-42010a8e0002,ResourceVersion:19223,Generation:0,CreationTimestamp:2017-12-07 23:04:06 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{openshift.io/deployer-pod-for.name: deployment-simple-2,},Annotations:map[string]string{openshift.io/deployment-config.name: deployment-simple,openshift.io/deployment.name: deployment-simple-2,openshift.io/scc: restricted,},OwnerReferences:[{v1 ReplicationController deployment-simple-2 ecf46720-dba2-11e7-a6e7-42010a8e0002 <nil> <nil>}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[{deployer-token-2zgkk {nil nil nil nil nil SecretVolumeSource{SecretName:deployer-token-2zgkk,Items:[],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{deployment openshift/origin-deployer:v3.9.0-alpha.0 [] []  [] [] [{KUBERNETES_MASTER https://ci-prtest-5a37c28-12598-ig-m-xzfq:8443 nil} {OPENSHIFT_MASTER https://ci-prtest-5a37c28-12598-ig-m-xzfq:8443 nil} {BEARER_TOKEN_FILE /var/run/secrets/kubernetes.io/serviceaccount/token nil} {OPENSHIFT_CA_DATA -----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE1MTI2ODcyNjkwHhcNMTcxMjA3MjI1NDI4WhcNMjIxMjA2
MjI1NDI5WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MTI2ODcyNjkw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4Rnvb1PuGTNPgPyw5mmtO
c/tNQU7Jl1zsGphG5WHI42pY/jH2Kj6GbS3R4eYwg9V/JQfDDJ4C9qcF1riMPvr3
nXGOy7ERZ4BpSZMiveFxAJuwHdNP0iBFdIXVPvuQT4MP0Y1yecSm2mSfyxFpTlAz
CJ0cEMTB2DhxZPhdRuPU0O558kidQ3pi6zRFQRTy0p/vicpXikHcHimeiM048NmR
/Inh+7qZm4mt0MsabaJiYQue1uLfg17tCkPFN2ujD3DCbBEUqwLu6SUHs7Pu2385
I5YDIUrOiEhJk8vL35Yhzx3tOGi2YNJ/PCSuhIWWNE2/Gu3T/FN9n5hCbUs1fItf
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQCRwwAMuiWyDanZOoak+tiAMDDCfR4FKFxe2rmDJ7+QXxTc
sLb/bkbZEIvg8hlGWAlI6RG9yRYUt7+I+eDc9tQyjnBgHOgv1SfUVoM/j4+KZUty
CFertWcC4mxj2EcceFZVd8BrwtdZB+Z0aLz83jAVxmveUrfFA4OmWBmgORqDg0vK
bg13A1pyo8lTrLp31HFgcELpFcXKtfhqEjHUhjdP279rEDTN20J2Whyi5BwNfx5c
dCSjN2j7s63ew9A9tO486Q/EwWkBF2krEz+bL4YKGLRgdh6Kc7IEpqiHUUJxjTeT
r3CQFQWdrxYwIMEeiG3ufGZiELIgKno9VIpIRHdU
-----END CERTIFICATE-----
 nil} {OPENSHIFT_DEPLOYMENT_NAME deployment-simple-2 nil} {OPENSHIFT_DEPLOYMENT_NAMESPACE extended-test-cli-deployment-ffkld-lssr4 nil}] {map[] map[]} [{deployer-token-2zgkk true /var/run/secrets/kubernetes.io/serviceaccount  <nil>}] nil nil nil /dev/termination-log File IfNotPresent SecurityContext{Capabilities:&Capabilities{Add:[],Drop:[KILL MKNOD SETGID SETUID],},Privileged:*false,SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0:c43,c42,},RunAsUser:*1001890000,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} false false false}],RestartPolicy:Never,TerminationGracePeriodSeconds:*10,ActiveDeadlineSeconds:*21600,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{role: app,},ServiceAccountName:deployer,DeprecatedServiceAccount:deployer,NodeName:ci-prtest-5a37c28-12598-ig-n-48p4,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0:c43,c42,},RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:*1001890000,},ImagePullSecrets:[{deployer-dockercfg-rlhwg}],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[],HostAliases:[],PriorityClassName:,Priority:nil,},Status:PodStatus{Phase:Pending,Conditions:[{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-12-07 23:04:06 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-12-07 23:04:06 +0000 UTC ContainersNotReady containers with unready status: [deployment]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-12-07 23:04:06 +0000 UTC  }],Message:,Reason:,HostIP:10.142.0.4,PodIP:,StartTime:2017-12-07 23:04:06 +0000 UTC,ContainerStatuses:[{deployment {ContainerStateWaiting{Reason:ContainerCreating,Message:,} nil nil} {nil nil nil} false 0 openshift/origin-deployer:v3.9.0-alpha.0  }],QOSClass:BestEffort,InitContainerStatuses:[],},} <*>(0xc420be6380)&Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:deployment-simple-1-deploy,GenerateName:,Namespace:extended-test-cli-deployment-ffkld-lssr4,SelfLink:/api/v1/namespaces/extended-test-cli-deployment-ffkld-lssr4/pods/deployment-simple-1-deploy,UID:f366f09d-dba2-11e7-a6e7-42010a8e0002,ResourceVersion:19670,Generation:0,CreationTimestamp:2017-12-07 23:04:17 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{openshift.io/deployer-pod-for.name: deployment-simple-1,},Annotations:map[string]string{openshift.io/deployment-config.name: deployment-simple,openshift.io/deployment.name: deployment-simple-1,openshift.io/scc: restricted,},OwnerReferences:[{v1 ReplicationController deployment-simple-1 e492364f-dba2-11e7-a6e7-42010a8e0002 <nil> <nil>}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[{deployer-token-2zgkk {nil nil nil nil nil SecretVolumeSource{SecretName:deployer-token-2zgkk,Items:[],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{deployment openshift/origin-deployer:v3.9.0-alpha.0 [] []  [] [] [{KUBERNETES_MASTER https://ci-prtest-5a37c28-12598-ig-m-xzfq:8443 nil} {OPENSHIFT_MASTER https://ci-prtest-5a37c28-12598-ig-m-xzfq:8443 nil} {BEARER_TOKEN_FILE /var/run/secrets/kubernetes.io/serviceaccount/token nil} {OPENSHIFT_CA_DATA -----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE1MTI2ODcyNjkwHhcNMTcxMjA3MjI1NDI4WhcNMjIxMjA2
MjI1NDI5WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MTI2ODcyNjkw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4Rnvb1PuGTNPgPyw5mmtO
c/tNQU7Jl1zsGphG5WHI42pY/jH2Kj6GbS3R4eYwg9V/JQfDDJ4C9qcF1riMPvr3
nXGOy7ERZ4BpSZMiveFxAJuwHdNP0iBFdIXVPvuQT4MP0Y1yecSm2mSfyxFpTlAz
CJ0cEMTB2DhxZPhdRuPU0O558kidQ3pi6zRFQRTy0p/vicpXikHcHimeiM048NmR
/Inh+7qZm4mt0MsabaJiYQue1uLfg17tCkPFN2ujD3DCbBEUqwLu6SUHs7Pu2385
I5YDIUrOiEhJk8vL35Yhzx3tOGi2YNJ/PCSuhIWWNE2/Gu3T/FN9n5hCbUs1fItf
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQCRwwAMuiWyDanZOoak+tiAMDDCfR4FKFxe2rmDJ7+QXxTc
sLb/bkbZEIvg8hlGWAlI6RG9yRYUt7+I+eDc9tQyjnBgHOgv1SfUVoM/j4+KZUty
CFertWcC4mxj2EcceFZVd8BrwtdZB+Z0aLz83jAVxmveUrfFA4OmWBmgORqDg0vK
bg13A1pyo8lTrLp31HFgcELpFcXKtfhqEjHUhjdP279rEDTN20J2Whyi5BwNfx5c
dCSjN2j7s63ew9A9tO486Q/EwWkBF2krEz+bL4YKGLRgdh6Kc7IEpqiHUUJxjTeT
r3CQFQWdrxYwIMEeiG3ufGZiELIgKno9VIpIRHdU
-----END CERTIFICATE-----
 nil} {OPENSHIFT_DEPLOYMENT_NAME deployment-simple-1 nil} {OPENSHIFT_DEPLOYMENT_NAMESPACE extended-test-cli-deployment-ffkld-lssr4 nil}] {map[] map[]} [{deployer-token-2zgkk true /var/run/secrets/kubernetes.io/serviceaccount  <nil>}] nil nil nil /dev/termination-log File IfNotPresent SecurityContext{Capabilities:&Capabilities{Add:[],Drop:[KILL MKNOD SETGID SETUID],},Privileged:*false,SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0:c43,c42,},RunAsUser:*1001890000,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} false false false}],RestartPolicy:Never,TerminationGracePeriodSeconds:*10,ActiveDeadlineSeconds:*21600,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{role: app,},ServiceAccountName:deployer,DeprecatedServiceAccount:deployer,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0:c43,c42,},RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:*1001890000,},ImagePullSecrets:[{deployer-dockercfg-rlhwg}],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[],HostAliases:[],PriorityClassName:,Priority:nil,},Status:PodStatus{Phase:Pending,Conditions:[],Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[],QOSClass:BestEffort,InitContainerStatuses:[],},}]
	
Expected
    <int>: 2
to be <=
    <int>: 1
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/util.go:698
```

**Comment by enj** [comment] 2017-12-08 18:01
cc @bparees

**Comment by bparees** [comment] 2017-12-08 18:06
dupe of https://github.com/openshift/origin/issues/17581

**Closed by bparees** 2017-12-08 18:06 UTC
Labels: kind/test-flake
