### ISSUE TITLE
oc run --attach doesn't display shell prompt

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6898] opened 2016-01-29 14:26 UTC
Running this successfully starts a pod and attaches, but I have to hit `<return>` before the shell prompt appears:
```
oc run --restart=Never --attach --stdin --tty --image busybox busybox /bin/sh
```

**Comment by ncdc** [comment] 2016-01-29 14:36
```
$ oc version
oc v1.1.1-289-g1b24a8d
kubernetes v1.2.0-alpha.4-851-g4a65fa1

$ oc run --restart=Never --attach --stdin --tty --image busybox busybox /bin/sh
Waiting for pod default/busybox to be running, status is Pending, pod ready: false

Hit enter for command prompt
<I hit enter here>
/ # ls
bin   dev   etc   home  proc  root  run   sys   tmp   usr   var
/ # exit
```

@liggitt seems to be working as designed?

**Comment by ncdc** [comment] 2016-01-29 14:40
Ah, I see you added the `Hit enter` suggestion. I'll look into the upstream code.

**Comment by liggitt** [comment] 2016-01-29 14:40
weird, I don't see the "Hit enter for command prompt" text. just saw that came in with the rebase.

**Comment by liggitt** [comment] 2016-01-29 14:41
curious why that is needed, though

**Comment by ncdc** [comment] 2016-01-29 14:41
Not really sure - I haven't been involved with attach.

**Comment by liggitt** [comment] 2016-01-29 14:55
with the suggestion present I'm ok closing this an moving upstream as a low-priority issue

**Comment by ncdc** [comment] 2016-01-29 15:27
Turns out to be a Docker bug. This will fix it: https://github.com/docker/docker/compare/master...ncdc:resize-after-attach

**Comment by ncdc** [comment] 2016-01-29 15:34
Reproducer with Docker:

```
$ docker create --name bbox -it busybox
$ docker start bbox
$ docker attach bbox
<need to hit enter or resize the window to see the prompt>
```

Compare to:

```
$ docker run --rm -it busybox
<get prompt w/o resizing or hitting enter>
```

**Comment by ncdc** [comment] 2016-01-29 15:48
https://github.com/docker/docker/pull/19835

**Comment by ncdc** [comment] 2016-06-04 00:24
This will be fixed once https://github.com/kubernetes/kubernetes/pull/25273 is merged upstream and then pulled downstream here

**Comment by ncdc** [comment] 2016-08-25 14:42
This is now in Origin

**Closed by ncdc** 2016-08-25 14:42 UTC
Labels: component/cli, kind/bug, priority/P2
