### ISSUE TITLE
Allow namespace admin to create label on the namespace

### ISSUE THREAD

**Issue by xavierbaude** [openshift/origin#18512] opened 2018-02-07 20:40 UTC
I try by different way to allow a "self-provisioner" to set label -and only label- on his namespace. 
The idea is to let a admin user to set label and some script do certain job like : monitoring, node-selector, ingresspolicy... with a habilitation control.

What I only found is to create a ClusterRole like: 

```
apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user who can set labels on the project.
  name: label-project
rules:
- apiGroups:
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - patch
```
But by this method, the user can modify everything on a namespace.
I also tried:
```
  resources:
  - namespaces/labels
```
```
  resources:
  - namespaces/metadata/labels
```
combined with
```
  verbs:
  - patch
```
```
  verbs:
  - create
```
```
  verbs:
  - label
```
with no success. Do you have any idea ?

**Comment by xavierbaude** [comment] 2018-02-07 21:10
#10315

**Comment by jwforres** [comment] 2018-02-08 18:51
@openshift/sig-master

**Comment by liggitt** [comment] 2018-02-08 23:22
Labels on namespaces are used for applying cluster level policy. It is unlikely control over those labels will be given to namespace constrained users.

**Comment by enj** [comment] 2018-02-11 20:04
Duplicate of #3819

**Closed by enj** 2018-02-11 20:04 UTC
Labels: kind/enhancement, sig/master
