### ISSUE TITLE
[Source 2 Image Build] Timeout during commiting container  

### ISSUE THREAD

**Issue by obuisson** [openshift/origin#13488] opened 2017-03-21 18:06 UTC
Hello,

I have just setup a new openshift cluster and I try to import an existing s2i app. Each build failed because of a timeout during the "Commit Image" step. 
From docker perspective, the resulting image appears after 10/15 minutes but Openshift timeout after 2 minutes, so the build failed. 

The build of this apps is correct on the previous openshift cluster. 

I think I have this bug (https://bugzilla.redhat.com/show_bug.cgi?id=1391665) but I don't know how to fix it. 

Is there a plan to update the "origin-sti-builder" docker image with this fix ? 

Thanks

##### Version
$ oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.xxxxx.xxxx.xxx:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

$ docker info
Containers: 20
 Running: 4
 Paused: 0
 Stopped: 16
Images: 21
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 67.64 GB
 Data Space Total: 213.7 GB
 Data Space Available: 146 GB
 Metadata Space Used: 6.136 MB
 Metadata Space Total: 536.9 MB
 Metadata Space Available: 530.7 MB
 Thin Pool Minimum Free Space: 21.37 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 15.51 GiB
Name: osnode2.xxxxxxxx.xxxx.xxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

##### Additional Information
0321 17:17:53.657506       1 docker.go:1105] Committing container with dockerOpts: {Reference:myapp/myservice-20:bdb3f66e Comment: Author: Changes:[] Pause:false Config:0xc420be7200}, config: {Hostname: Domainname: User:1001 AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] Tty:false OpenStdin:false StdinOnce:false Env:[OPENSHIFT_BUILD_NAME=myapp-20 OPENSHIFT_BUILD_NAMESPACE=myapp OPENSHIFT_BUILD_SOURCE=git@gitlab.xxxxxx.xxx.xxx:MYAPP/MyService.git ENVIRONMENT=production BUILD_LOGLEVEL=5] Cmd:[/usr/libexec/s2i/run] ArgsEscaped:false Image: Volumes:map[] WorkingDir: Entrypoint:[container-entrypoint] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[io.openshift.build.commit.date:Fri Mar 3 18:55:52 2017 +0100 io.openshift.build.commit.id:4d332b8cb797ad7831322f0e75d52ba216a03d75 io.openshift.build.commit.ref:master io.openshift.build.commit.message:commit build io.openshift.build.source-location:git@gitlab.xxxxx.xxx.xxx:MYAPP/MyService.git name:CentOS Base Image license:GPLv2 vendor:CentOS io.openshift.build.image:172.30.216.17:5000/openshift/nodejs-myapp@sha256:59dcb150390756390a127e738db42f896e2fec70aa1f74408eaef9cd01e92996 io.openshift.builder-base-version:fa7ba54 io.openshift.tags:builder,nodejs io.openshift.s2i.scripts-url:image:///usr/libexec/s2i io.openshift.build.commit.author:John Doe<john.doe@example.Com> build-date:20160906 io.k8s.description:Platform for building Node js applications io.k8s.display-name:myapp/myservice-20:bdb3f66e io.s2i.scripts-url:image:///usr/libexec/s2i] StopSignal:}
I0321 17:19:53.657831       1 sti.go:375] error: Execution of post execute step failed
I0321 17:19:53.657916       1 docker.go:948] Removing container "39401fd3de7f480a99e381128fc91c06537240b5eb23a9267b2c11a906504121" ...
I0321 17:19:53.670149       1 docker.go:950] warning: Failed to remove container "39401fd3de7f480a99e381128fc91c06537240b5eb23a9267b2c11a906504121": Error response from daemon: {"message":"Driver devicemapper failed to remove root filesystem 39401fd3de7f480a99e381128fc91c06537240b5eb23a9267b2c11a906504121: failed to remove device 079755fd019c49456cf9c31461037a1d8651ce8b47a7a27b83ffe902a931519b:Device is Busy"}
I0321 17:19:53.670835       1 cleanup.go:33] Removing temporary directory /tmp/s2i-build759113578
I0321 17:19:53.670898       1 fs.go:159] Removing directory '/tmp/s2i-build759113578'
F0321 17:19:54.128452       1 helpers.go:115] error: build error: building myapp/myservice-20:bdb3f66e failed when committing the image due to error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by debianmaster** [comment] 2017-03-21 21:34
did you try restarting  docker `systemctl restart docker` ?

**Comment by obuisson** [comment] 2017-03-22 09:47
Hello,

I have try to restart docker several times and also reboot the node without any changes

**Comment by pweil-** [comment] 2017-03-23 17:10
@obuisson this looks similar to https://github.com/openshift/origin/issues/13515#issuecomment-288608775. 

Can you give the latest RC a go and see if that fixes it for you?  Thanks.

**Comment by bparees** [comment] 2017-03-23 17:12
> Is there a plan to update the "origin-sti-builder" docker image with this fix ?

the image is updated, for 1.5.  You could try using the 1.5 version of the image but i can't make promises about its compatibility with a 1.4 cluster.

**Comment by bparees** [comment] 2017-03-23 17:13
closing this as a dupe of https://github.com/openshift/origin/issues/13515

**Closed by bparees** 2017-03-23 17:13 UTC
Labels: component/build, kind/bug, priority/P2
