### ISSUE TITLE
Unit test panic

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6738] opened 2016-01-20 14:23 UTC
```
panic: test timed out after 1m0s

goroutine 26 [running]:
testing.func·008()
	/usr/lib/golang/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive]:
testing.RunTests(0x18a2d78, 0x1efcf80, 0x2, 0x2, 0xc208057e01)
	/usr/lib/golang/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc20802fb80, 0x28b1960)
	/usr/lib/golang/src/testing/testing.go:485 +0xe1
main.main()
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_testmain.go:126 +0x382

goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x28a6420)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x99
created by github.com/golang/glog.init·1
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ca

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 20 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x43

goroutine 25 [runnable]:
math/big.nat.norm(0xc208122240, 0x11, 0x24, 0xc208122360, 0x21, 0x24)
	/usr/lib/golang/src/math/big/nat.go:61
math/big.nat.divLarge(0xc208122240, 0x10, 0x24, 0xc208122360, 0x21, 0x24, 0xc208122120, 0x20, 0x24, 0xc208100000, ...)
	/usr/lib/golang/src/math/big/nat.go:594 +0xfa0
math/big.nat.div(0xc208122240, 0x10, 0x24, 0xc208122360, 0x20, 0x24, 0xc208122120, 0x20, 0x24, 0xc208100000, ...)
	/usr/lib/golang/src/math/big/nat.go:519 +0x3cc
math/big.nat.expNNWindowed(0xc208122120, 0x20, 0x24, 0xc208100f00, 0x10, 0x14, 0xc208100b40, 0x10, 0x14, 0xc208100000, ...)
	/usr/lib/golang/src/math/big/nat.go:1356 +0xe43
math/big.nat.expNN(0xc208100fa0, 0x10, 0x14, 0xc208100f00, 0x10, 0x14, 0xc208100b40, 0x10, 0x14, 0xc208100000, ...)
	/usr/lib/golang/src/math/big/nat.go:1260 +0x4f1
math/big.nat.probablyPrime(0xc208100000, 0x10, 0x14, 0x14, 0x14)
	/usr/lib/golang/src/math/big/nat.go:1445 +0x9d4
math/big.(*Int).ProbablyPrime(0xc2080e2000, 0x14, 0xc2080e2020)
	/usr/lib/golang/src/math/big/int.go:741 +0x7c
crypto/rand.Prime(0x7f7b0493c278, 0xc20803c300, 0x400, 0xc2080e2000, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rand/util.go:99 +0x654
crypto/rsa.GenerateMultiPrimeKey(0x7f7b0493c278, 0xc20803c300, 0x2, 0x800, 0xc208245860, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:187 +0x2c9
crypto/rsa.GenerateKey(0x7f7b0493c278, 0xc20803c300, 0x800, 0xc208385a40, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:145 +0x65
github.com/openshift/origin/pkg/cmd/server/crypto.NewKeyPair(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:338 +0xa6
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).MakeClientCertificate(0xc208354a50, 0xc20832d2f0, 0x30, 0xc20832d350, 0x30, 0x7f7b0494eb90, 0xc208357a00, 0x439bf9, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:284 +0x35b
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).EnsureClientCertificate(0xc208354a50, 0xc20832d2f0, 0x30, 0xc20832d350, 0x30, 0x7f7b0494eb90, 0xc208357a00, 0x7, 0x7, 0x0, ...)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:267 +0xeb
github.com/openshift/origin/pkg/cmd/server/admin.CreateClientCertOptions.CreateClientCert(0xc2081ecbc0, 0xc20832d2f0, 0x30, 0xc20832d350, 0x30, 0xc208210a80, 0x13, 0xc20819a1b0, 0x1, 0x1, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_clientcert.go:85 +0x8fd
github.com/openshift/origin/pkg/cmd/server/admin.CreateNodeConfigOptions.MakeClientCert(0xc2081ecbc0, 0xc20832cc6b, 0x1e, 0x15777b7, 0x7, 0xc20819a150, 0x1, 0x1, 0x161abf0, 0x17, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:345 +0x30e
github.com/openshift/origin/pkg/cmd/server/admin.CreateNodeConfigOptions.CreateNodeFolder(0xc2081ecbc0, 0xc20832cc6b, 0x1e, 0x15777b7, 0x7, 0xc20819a150, 0x1, 0x1, 0x161abf0, 0x17, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:278 +0x4f1
github.com/openshift/origin/pkg/cmd/server/admin.func·014(0xc208070a00, 0xc2082e0750, 0x0, 0x9)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:73 +0x221
github.com/spf13/cobra.(*Command).execute(0xc208070a00, 0xc2082e05a0, 0x9, 0x9, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0xb41
github.com/spf13/cobra.(*Command).ExecuteC(0xc208070600, 0xc208070a00, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x635
github.com/spf13/cobra.(*Command).Execute(0xc208070600, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x48
github.com/openshift/origin/pkg/cmd/server/admin.executeNodeConfig(0xc2083c3e58, 0x8, 0x8, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:107 +0x721
github.com/openshift/origin/pkg/cmd/server/admin.TestNodeConfigTLS(0xc20835e000)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:45 +0x402
testing.tRunner(0xc20835e000, 0x1efcf98)
	/usr/lib/golang/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:555 +0xd4e
FAIL	github.com/openshift/origin/pkg/cmd/server/admin	60.493s
```
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4673/consoleFull

**Comment by bparees** [comment] 2016-01-20 15:43
@deads2k looks like you last touched TestNodeConfigTLS.

also we need a component for "cluster config" i think.

**Comment by liggitt** [comment] 2016-01-20 15:44
dupe of #6687

**Closed by liggitt** 2016-01-20 15:44 UTC
Labels: area/tests, kind/bug, kind/test-flake, priority/P2
