### ISSUE TITLE
NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod

### ISSUE THREAD

**Issue by dgoodwin** [openshift/origin#4823] opened 2015-09-28 13:48 UTC
I am testing fully containerized installations with separate master / node.  After deploying a router I get this error message every 10 seconds on the aos-node container where my router landed:

I0928 09:00:50.733647   16875 docker.go:156] Pulling image REDACTED-haproxy-router:v3.0.2.100 without credentials
E0928 09:01:38.190049   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
E0928 09:01:38.226292   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
E0928 09:01:38.276413   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
I0928 09:01:38.916821   16875 roundrobin.go:263] LoadBalancerRR: Setting endpoints for default/default-router:80-tcp to [192.168.133.3:80]
E0928 09:01:44.764580   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
E0928 09:01:44.796739   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
I0928 09:01:44.842904   16875 manager.go:1180] Killing container with id "03e58846de9466d536b17ce043aec5cae11732127696fcb7c8d09874d3e9d295"
W0928 09:01:45.876090   16875 kubelet.go:1359] Orphaned volume "e53c334f-65e0-11e5-a700-5254004c34bf/deployer-token-zgzc3" found, tearing down volume
E0928 09:01:45.904756   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
E0928 09:01:45.923193   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1
E0928 09:01:55.940162   16875 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-ffbn2' - exit status 1

The node container in question has:

[root@node1 openshift]# rpm -qa | grep openshift
tuned-profiles-atomic-openshift-node-3.0.2.100-0.git.7.37c6444.el7aos.x86_64
atomic-openshift-node-3.0.2.100-0.git.7.37c6444.el7aos.x86_64
atomic-openshift-3.0.2.100-0.git.7.37c6444.el7aos.x86_64
atomic-openshift-sdn-ovs-3.0.2.100-0.git.7.37c6444.el7aos.x86_64

My node container has the patch applied from https://github.com/openshift/openshift-sdn/pull/149 but the issue is still present.

I noticed someone hit this on an SME list this weekend as well, can provide link out of band.

Ping @danwinship in case you know what might be up!

Please let me know if there's more info I can provide.

**Comment by danwinship** [comment] 2015-09-28 13:58
openshift/openshift-sdn#149 only affects the multitenant plugin. openshift/openshift-sdn#144 was the patch for the single-tenant plugin. Do you have that too?

**Comment by dgoodwin** [comment] 2015-09-28 14:21
No I do not seem to have that patch applied. I will investigate if we've not yet pulled that into our builds and close issue, thanks!

**Comment by dgoodwin** [comment] 2015-09-28 16:01
Apologies, not sure how but I was mistaken, my node does seem to have this patch applied.

Verified in: /usr/libexec/kubernetes/kubelet-plugins/net/exec/redhat~openshift-ovs-subnet/openshift-ovs-subnet 

So something still seems to be amiss @danwinship

**Comment by danwinship** [comment] 2015-09-28 16:16
Can you try running with --loglevel=5? (One way to do that would be to edit the command line in /usr/lib/systemd/system/openshift-node.service and then restart the node.)

That should make it log the output of the status script before the'failed on the status hook' message

**Comment by dgoodwin** [comment] 2015-09-28 17:42
http://fpaste.org/272316/46210814/

**Comment by danwinship** [comment] 2015-09-28 18:12
`I0928 13:40:07.689984    2529 exec.go:149] Status 'exec' network plugin output: , exit status 1`

ok, not very useful.

So, what does `docker inspect` return for the container in question? (specifically, I want to know what `docker inspect --format "{{.NetworkSettings.IPAddress}}"` returns, but I'm pretty sure at this point that the answer is "nothing", so I want to see what actually is there...)

**Comment by dgoodwin** [comment] 2015-09-28 18:47
You are correct it indeed returns nothing for both my aos-node container and the router container.

Full inspect output from router container: http://fpaste.org/272337/44346593/

FWIW the guest these containers is on has two network interfaces with IPv4 addresses.

**Comment by danwinship** [comment] 2015-09-29 14:53
> I am testing fully containerized installations

Ah, just noticed this part... OK, so something is causing the NetworkSettings part of the docker inspect output to not get set correctly in this case. (I assume the container *does* actually have an IP address, it's just that docker isn't aware of it for some reason.) So either (a) this is a problem at a lower level than openshift-sdn, and needs to be fixed there, or (b) this is somehow inherent to the fully-containerized use case, and we need to teach openshift-sdn some other way to get the container IP address in this case (which would be... ?)

**Comment by dgoodwin** [comment] 2015-09-29 17:40
Digging some more, it appears it's not a docker specific issue, on the same atomic host I can reproduce see empty IPAddress in my aos-node container, but not in a random centos container I started myself.

-bash-4.2# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED              STATUS              PORTS               NAMES
653496eca45f        centos:6            "bash"                 About a minute ago   Up About a minute                       desperate_einstein   
00edaf8a2296        aos-node            "/usr/local/bin/aos-   10 minutes ago       Up 10 minutes                           aos-node             
-bash-4.2# docker inspect 653496eca45f | grep IPA
        "IPAddress": "10.1.1.4",
        "SecondaryIPAddresses": null,
-bash-4.2# docker inspect 00edaf8a2296 | grep IPA
        "IPAddress": "",
        "SecondaryIPAddresses": null,
-bash-4.2# 

Digging further into what this container might be doing wrong now.

**Comment by dgoodwin** [comment] 2015-09-29 17:45
Found it, it's caused by launching docker run with --net=host, as opposed to the default which is probably bridge. From the aos-node Dockerfile:

LABEL RUN docker run -d --name NAME --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v /etc/openshift-master:/etc/openshift:Z -v /var/lib/openshift:/var/lib/openshift:z -e HOST_HOSTNAME=$(hostname) -p 53:53 -p 53:53/udp -p 4001:4001 -p 7001:7001 -p 8443:8443 IMAGE

In this scenario there is no IP address assigned to the container. (which sounds like it might be correct) I didn't write this portion of the aos-node container but it's likely a requirement for the OVS stuff it has to do, I can check with Peter in any case.

Does this feel like an issue with how we're parsing that IP address in the plugin? Any other ways we could get it or perhaps handle this scenario gracefully?

**Comment by danwinship** [comment] 2015-09-29 17:50
If it's using --net=host then every container would have the same IP as the host itself... unless you're nesting containers in containers or something? I guess I'd need to know more about how the whole setup works.

Anyway, the goal is that the Status hook should return the IP address that refers specifically to that pod. Any way its gets that is fine...

**Comment by dgoodwin** [comment] 2015-09-29 18:15
Sorry I'm getting a little confused, forgot it was a pod container originally, I noticed it on several of my containers so have been testing it there.

Back to my reproducer environment:

$ docker logs aos-node
E0929 14:08:45.852713    2566 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'default-router-1-vkydm' - exit status 1
^C#

$ docker ps
CONTAINER ID        IMAGE                                                                               COMMAND                CREATED             STATUS              PORTS               NAMES
6b847fb433e3        rcm-img-docker01.build.eng.bos.redhat.com:5001/aos3/aos-haproxy-router:v3.0.2.100   "/usr/bin/openshift-   12 minutes ago      Up 12 minutes                           k8s_router.d4693273_default-router-1-vkydm_default_5210ecce-66b8-11e5-834b-5254004c34bf_9f64087d   
2af81560185e        rcm-img-docker01.build.eng.bos.redhat.com:5001/aos3/aos-pod:v3.0.2.100              "/pod"                 13 minutes ago      Up 13 minutes                           k8s_POD.b8c7e1e3_default-router-1-vkydm_default_5210ecce-66b8-11e5-834b-5254004c34bf_df93bce9      
c11d70cf3ad6        aos-node                                                                            "/usr/local/bin/aos-   30 hours ago        Up 13 minutes                           aos-node                                                                                           
$ docker logs 6b847fb433e3  
I0929 13:56:13.506781       1 router.go:119] Router is including routes in all namespaces
$ docker inspect 6b847fb433e3 | grep IPA
        "IPAddress": "",
        "SecondaryIPAddresses": null,
$ docker inspect 2af81560185e | grep IPA
        "IPAddress": "",
        "SecondaryIPAddresses": null,

So neither my pod nor the router container return an IPAddress.

**Comment by pravisankar** [comment] 2015-09-29 18:27
Looks like an issue with openshift-sdn code.
flat/multitenant status hook should handle --net=host case. Something like
Status() {
    ipaddr=$(docker inspect --format "{{.NetworkSettings.IPAddress}}" ${net_container})
    network_mode=$(docker inspect --format "{{.HostConfig.NetworkMode}}" ${net_container})
    if [ "${network_mode}" == "host" ]; then
       return k8s status object with hostIP
    else
       return k8s status object with $ipaddr
    fi
}

**Comment by dgoodwin** [comment] 2015-09-29 18:30
I think the aos3/aos-haproxy-router may be an example of a container which launches with this non-bridged networking mode, and the sdn plugin script probably needs to do as @pravisankar  suggests above to acommodate. 

[root@master openshift]# oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
default-router-1-vkydm    1/1       Running   0          3h
docker-registry-1-gi3vv   1/1       Running   0          3h
[root@master openshift]# oc describe pod default-router-1-vkydm | grep IP 
IP:                             192.168.133.4

^^ this is the pod's host's IP

[root@master openshift]# oc describe pod docker-registry-1-gi3vv | grep IP
IP:                             10.1.1.3

^^ normal SDN IP

**Comment by spinolacastro** [comment] 2015-10-09 13:01
I can confirm the errors on origin 1.0.6 and multitenant plugin. Despite the errors, all system seems to work.

**Comment by albertomolina** [comment] 2015-10-11 09:22
@dgoodwin I don't know if it's related to this, but I was facing exactly the same issue installing OpenShift on OpenStack and finally the issue was caused by the network driver. 

Due to a previous adjustments, our OpenStack instances were not using network virtio drivers and then I found this: https://github.com/openshift/origin/issues/3612#issuecomment-120043094

Turning on network virtio driver for OpenStack instances makes router error messages go away.

**Comment by roldancer** [comment] 2015-10-11 09:59
I have the some problem using OpenSHift Enterprise Edition 3.0.2,

**Comment by jkaurredhat** [comment] 2015-10-14 07:14
This issue is  seen in Openshift Enterprise 3.0.2 environment.

**Comment by pravisankar** [comment] 2015-10-15 21:28
Fixed in https://github.com/openshift/openshift-sdn/pull/170 and https://github.com/openshift/openshift-sdn/pull/175

**Closed** 2015-10-22 19:37 UTC
Labels: component/networking, kind/bug, priority/P1
