### ISSUE TITLE
TestAuthorizationResolution resource conflict

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5683] opened 2015-11-04 06:41 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6871/console
```
--- FAIL: TestAuthorizationResolution-2 (12.81s)
	authorization_test.go:129: unexpected error: clusterpolicybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

**Comment by deads2k** [comment] 2016-01-12 19:29
dupe of https://github.com/openshift/origin/issues/6447

**Closed by deads2k** 2016-01-12 19:29 UTC
Labels: area/tests, kind/test-flake, priority/P2
