### ISSUE TITLE
An Ansible task failed to complete (etcd)

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13594] opened 2017-03-31 14:52 UTC
```
TASK [etcd : Enable etcd] ******************************************************
task path: /usr/share/ansible/openshift-ansible/roles/etcd/tasks/main.yml:122
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unable to start service etcd: Job for etcd.service failed because the control process exited with error code. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"
}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'

PLAY RECAP *********************************************************************
localhost                  : ok=151  changed=42   unreachable=0    failed=1   

++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: INSTALL ORIGIN ##########
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/721/consoleFull

**Comment by stevekuznetsov** [comment] 2017-03-31 15:05
```
systemd[1]: Starting Etcd Server...
etcd[23985]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://172.18.13.217:2379
etcd[23985]: recognized and used environment variable ETCD_CA_FILE=/etc/etcd/ca.crt
etcd[23985]: recognized and used environment variable ETCD_CERT_FILE=/etc/etcd/server.crt
etcd[23985]: recognized and used environment variable ETCD_DEBUG=True
etcd[23985]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=2500
etcd[23985]: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=500
etcd[23985]: recognized and used environment variable ETCD_KEY_FILE=/etc/etcd/server.key
etcd[23985]: recognized and used environment variable ETCD_PEER_CA_FILE=/etc/etcd/ca.crt
systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start Etcd Server.
systemd[1]: Unit etcd.service entered failed state.
systemd[1]: etcd.service failed.
```

@sdodson something's wrong with `etcd` vars

**Comment by stevekuznetsov** [comment] 2017-03-31 15:20
The changes to the jobs have been reverted.

**Comment by carljmosca** [comment] 2017-04-29 16:10
Which branch has this fix?  I have tried master and revert-3955-fix_etcd_path.

With the latter, I get a "path /etc/etcd/./server.crt does not exist" error.

**Comment by stevekuznetsov** [comment] 2017-04-29 21:14
This error was ultimately caused by a permissions issue on the etcd data directory. I'm not sure that what you saw was this issue. Could you please create an issue with logs from your run and we'll take a look.

The issue Ben posted about was reverted, then ultimately fixed in https://github.com/openshift/aos-cd-jobs/pull/199

**Closed by stevekuznetsov** 2017-04-29 21:14 UTC
Labels: component/install, kind/test-flake, priority/P2
