### ISSUE TITLE
Verify Requirements: [localhost] openshift_health_check (Not all of the required packages are available at their requested version: docker:1.12)

### ISSUE THREAD

**Issue by dmage** [openshift/origin#16143] opened 2017-09-05 14:55 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16140/test_pull_request_origin_extended_conformance_install_update/5407/?log#log

/kind test-flake

**Comment by enj** [comment] 2017-09-05 15:32
@stevekuznetsov @jupierce @sdodson seeing this a lot.

**Comment by stevekuznetsov** [comment] 2017-09-05 15:35
Was blocking the queue. I have disabled the check in https://github.com/openshift/aos-cd-jobs/commit/9b402118edf1ea094c8c1a0ed125700e0d4ad776 so we should see this stop affecting PRs.

**Comment by sosiouxme** [comment] 2017-09-07 14:45
@stevekuznetsov with https://github.com/openshift/openshift-ansible/pull/5299 merged could you re-enable the check? Might want to unleash it on openshift-ansible first as we didn't really have a good way to test that this fixes CI other than running a CI job.

**Comment by stevekuznetsov** [comment] 2017-09-07 17:17
@sosiouxme can you make the revert PR in aos-cd-jobs? There is a blurb in the README about how you would test changes to the inventory in a canary job.

**Comment by sosiouxme** [comment] 2017-09-07 21:06
@stevekuznetsov are you referring to https://github.com/openshift/aos-cd-jobs/#custom-xml-generator-configuration-under-sjb ? Looks like it describes running test jobs there but not obvious to me how to use a different `checks.yml` in such a job.

**Comment by stevekuznetsov** [comment] 2017-09-07 21:51
> If changes are being made to the files under `sjb/` in this repository, it is not enough to copy a job configuration and run it to test the changes. Instead, it will be necessary to mark the copied job as syncing a pull request for `aos-cd-jobs` using the `type` field on the repository as per [the spec](./sjb/syntax.md#sync_repos). Then, when running your copied job, configure it at run-time to merge in your pull request by entering in your pull request number in the appropriate parameter field in the Jenkins UI when starting the job.

**Comment by smarterclayton** [comment] 2017-09-09 19:17
Probably unrelated, but similar symptom.  Starting sept 7th seeing same failure but due to yum metadata

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16256/test_pull_request_origin_extended_conformance_install_update/5714/?log

```
Failure summary:

  1. Host:     localhost
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_storage":
               Some dependencies are required in order to query docker storage on host:
               Unable to install required packages on this host:
                   python-docker-py
               Failure talking to yum: failure: repodata/98cd8fe00600d7fe9af1e7fdee23d6de6819634daa9e063f96afa1956d511103-primary.sqlite.bz2 from li: [Errno 256] No more mirrors to try.
               https://mirror.ops.rhcloud.com/libra/rhel-7-libra/x86_64/repodata/98cd8fe00600d7fe9af1e7fdee23d6de6819634daa9e063f96afa1956d511103-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
               https://use-mirror2.ops.rhcloud.com/libra/rhel-7-libra/x86_64/repodata/98cd8fe00600d7fe9af1e7fdee23d6de6819634daa9e063f96afa1956d511103-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
               https://use-mirror1.ops.rhcloud.com/libra/rhel-7-libra/x86_64/repodata/98cd8fe00600d7fe9af1e7fdee23d6de6819634daa9e063f96afa1956d511103-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
               https://euw-mirror1.ops.rhcloud.com/libra/rhel-7-libra/x86_64/repodata/98cd8fe00600d7fe9af1e7fdee23d6de6819634daa9e063f96afa1956d511103-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by sosiouxme** [comment] 2017-09-12 15:46
That one might benefit from retries https://github.com/openshift/openshift-ansible/pull/5125

Or not, if the remote repo is actually broken at the time, or the problem is local yum metadata (I've considered running a `yum clean all` on first yum failure just in case).

That's unrelated though... this particular check started failing consistently due to our CI environment and I have yet to get it working the way I expect in that circumstance. Since the check has been disabled for now and isn't blocking queues, I would rather prioritize other bugs.

**Comment by sosiouxme** [comment] 2017-09-21 14:01
Check reinstated with https://github.com/openshift/aos-cd-jobs/pull/614 - reopen if this pops up again.

**Closed by sosiouxme** 2017-09-21 14:01 UTC
Labels: kind/test-flake, priority/P2
