### ISSUE TITLE
Application creation failed on local cluster running on docker version 17.03.1-ce

### ISSUE THREAD

**Issue by shrutikamendhe** [openshift/origin#13695] opened 2017-04-10 05:52 UTC
I have install Docker for Window on my local Windows 10 machine. Currently, docker version 17.03.1-ce is running on my system. 

Next I have downloaded and installed oc binary version v1.5.0-rc.0+49a4a7a on my system and run `oc cluster up` command to running OpenShift cluster on my local system.

On browser, I logged in to OpenShift Web Console using developer account and created application.

But application creation failed. It seems that the current cluster is not supporting for docker version 17.03.1-ce.

##### Version
oc version
![image](https://cloud.githubusercontent.com/assets/9589742/24847556/439352d2-1ddf-11e7-92a0-26056c6c2f7e.png)

![image](https://cloud.githubusercontent.com/assets/9589742/24847572/55023650-1ddf-11e7-817e-abf788ac916a.png)

##### Steps To Reproduce
1. Install Docker for windows version 17.03.1-ce
2. Install OC binary version v1.5.0-rc.0+49a4a7a
3. Once cluster is up, login to web console
4. Create application using any Template 

##### Current Result
Getting below error ->
![image](https://cloud.githubusercontent.com/assets/9589742/24847521/092c2894-1ddf-11e7-9e38-d2fcb0198034.png)

**Comment by debianmaster** [comment] 2017-04-10 06:11
Use latest oc binary 

https://github.com/openshift/origin/releases/download/v3.6.0-alpha.0/openshift-origin-client-tools-v3.6.0-alpha.0-0343989-windows.zip   

this should have fix

**Comment by pweil-** [comment] 2017-04-10 12:44
duplicate of https://github.com/openshift/origin/issues/13281

**Closed by pweil-** 2017-04-10 12:44 UTC
