### ISSUE TITLE
Spec file shows v.0.0.1

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7418] opened 2016-02-18 14:57 UTC
Should the spec file package be "v0.0.0.1" ? Thats what its currently giving me:

`Building package [v0.0.1]` ...

**Comment by sdodson** [comment] 2016-02-18 20:07
@danmcp I believe this should be closed as a dupe of #7219 we need to treat RPM artifacts as a first class citizen and that's being discussed there.

**Closed** 2016-02-18 20:09 UTC
Labels: component/install, priority/P2
