### ISSUE TITLE
Error recording event for DaemonSet

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#7437] opened 2016-02-18 21:00 UTC
Using commit 1def47c, create a DaemonSet, and you'll see this:

```
E0218 14:52:38.756848    9067 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"hello-daemonset.14342144c29ee503", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"DaemonSet", Namespace:"default", Name:"hello-daemonset", UID:"28c15ebb-d679-11e5-bac2-001c42de2c3c", APIVersion:"extensions", ResourceVersion:"731", FieldPath:""}, Reason:"SuccessfulDelete", Message:"Deleted pod: hello-daemonset-hdboj", Source:api.EventSource{Component:"daemon-set", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63591421958, nsec:754198787, loc:(*time.Location)(0x582d200)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63591421958, nsec:754198787, loc:(*time.Location)(0x582d200)}}, Count:1, Type:"Normal"}': 'Event "hello-daemonset.14342144c29ee503" is invalid: involvedObject.kind: Invalid value: "DaemonSet": couldn't check whether namespace is allowed: [[[[[[[[[[no kind named {"" "DaemonSet"} is registered in versions ["extensions"], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]], no kind named {"" "DaemonSet"} is registered in versions ["extensions"]]' (will not retry!)
```

**Comment by ncdc** [comment] 2016-02-18 21:01
cc @deads2k

**Comment by pweil-** [comment] 2016-02-19 21:12
@deads2k  this is being caused by the `isNamespacedKind` check in `ValidateEvent`.  It is returning an error on https://github.com/pweil-/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/events.go#L70 because it cannot find the `DaemonSet` restmapping.  

Are we ready to drop that commit (it is marked as drop) or maybe there is something not being registered correctly?  Here is what I see:

```
groupVersion: extensions
group: returns empty from apiutil.GetGroup
g: ends up with &{v1 [v1 v1beta3] <nil> {} MultiRESTMapper{
```

I was able to revert to the upstream version of `events.go` and the even validates and is saved correctly but I notice that they are only escaping Nodes as namespace scoped items and are doing it directly in the code rather than looking for groups.

**Comment by pweil-** [comment] 2016-02-19 21:14
relevant commit that introduced this and was carried in the last rebase as well https://github.com/openshift/origin/commit/2585d8905f34be3be68b8c5d007d7f557e524466

**Comment by pweil-** [comment] 2016-02-23 15:01
since @deads2k has been out - @liggitt do you have any insight to this?  I can change the validation method but don't want to lose anything critical.

**Comment by pweil-** [comment] 2016-02-26 13:33
@deads2k  bump - WDYT?

**Comment by deads2k** [comment] 2016-02-26 15:56
> @deads2k bump - WDYT?

Fixable and on my list after figuring out why template processing for namespace values is getting cleared.

**Comment by pweil-** [comment] 2016-02-26 15:59
Reassigning then.  Thanks.

**Closed** 2016-02-29 19:12 UTC
Labels: priority/P1
