### ISSUE TITLE
Finalize Kube items

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2233] opened 2015-05-14 00:02 UTC
Unmerged/open issues upstream:

- [ ] GoogleCloudPlatform/kubernetes#2630
- [x] GoogleCloudPlatform/kubernetes#5093
- [ ] GoogleCloudPlatform/kubernetes#7372
- [ ] GoogleCloudPlatform/kubernetes#7893
- [x] GoogleCloudPlatform/kubernetes#8119
- [x] GoogleCloudPlatform/kubernetes#8203
- [x] GoogleCloudPlatform/kubernetes#8607
- [ ] GoogleCloudPlatform/kubernetes#8890
- [x] GoogleCloudPlatform/kubernetes#9384

**Comment by derekwaynecarr** [comment] 2015-05-14 00:23
https://github.com/GoogleCloudPlatform/kubernetes/pull/7868

Needed to time box rogue build pods and deployments from running "forever".

**Comment by pweil-** [comment] 2015-05-14 01:10
https://github.com/GoogleCloudPlatform/kubernetes/pull/7893

Required to provide security context constraints at a cluster level to allow definition of UID allocation, SELinux labels, service account permissions, and user permissions.

https://github.com/GoogleCloudPlatform/kubernetes/pull/8203

Supporting PR to allow admission controllers to be aware of `UserInfo`

**Comment by ironcladlou** [comment] 2015-05-14 12:01
https://github.com/GoogleCloudPlatform/kubernetes/pull/7868 is also the foundation of user-initiated depoyment cancellation.

**Comment by brenton** [comment] 2015-05-14 12:24
It would be great to have this fixed: https://github.com/GoogleCloudPlatform/kubernetes/issues/7370

The short of it is that because there's no locking or retrying around the iptables initialization code there is a case that can happen on OpenShift startup where the iptables rules for the kube-proxy will never be initialized.  You'll typically only see this if you are running the SDN and launch it the same time the kube-proxy starts up.  It's easy to reproduce by grabbing the lock with gdb while the kube-proxy tries to initialize itself.  Once it fails it will never reinitialize the rules.

**Comment by liggitt** [comment] 2015-05-14 17:29
https://github.com/GoogleCloudPlatform/kubernetes/pull/8257

We'll want this so we can run the controller to ensure two service accounts exist per namespace:
* "default", with some read-only level of access, maybe to services/endpoints/imageStreams in the namespace, etc.
* "builder", with additional write access to imageStreams in the namespace

**Comment by csrwng** [comment] 2015-05-14 17:41
https://github.com/GoogleCloudPlatform/kubernetes/pull/8233

If we allow you to exec to pods in your project, we should not let you exec into build pods (or anything else that's privileged) that basically give you root access to the node.

**Comment by smarterclayton** [comment] 2015-05-14 17:42
We need more than this for 3.0 though - we need this to be an escalation check, right?  Just want to clarify that we don't physically need this change - we need the other one.

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-05-15 03:23
Brenton pleas spawn an issue in our repo for the proxy lock, I'll port my upstream change and add the loop

**Comment by deads2k** [comment] 2015-05-15 13:04
https://github.com/GoogleCloudPlatform/kubernetes/pull/8072
https://github.com/GoogleCloudPlatform/kubernetes/pull/7974
https://github.com/GoogleCloudPlatform/kubernetes/pull/7966

All of these are related to attaching image pull secrets to pods.  Once these settle, there will be follow-on for pull secrets in service accounts.

**Comment by brenton** [comment] 2015-05-15 13:11
@smarterclayton, I just opened https://github.com/openshift/origin/issues/2266.  I set the priority to P0 but feel free to change it if that's not right.

**Comment by derekwaynecarr** [comment] 2015-05-15 14:29
https://github.com/GoogleCloudPlatform/kubernetes/pull/7372

Needed to ensure that we do not have dangling folders for each resource type after namespace deletion.  Enables ability to delete entire collection in etcd for a namespace.

**Comment by pmorie** [comment] 2015-05-15 15:14
I am trying to get https://github.com/GoogleCloudPlatform/kubernetes/pull/7936 and related changes in but we may need to carry it as a patch for 1 release.

**Comment by deads2k** [comment] 2015-05-20 19:18
pull secrets on service accounts: https://github.com/GoogleCloudPlatform/kubernetes/pull/8582

**Comment by timothysc** [comment] 2015-05-21 16:30
perf regression - https://github.com/GoogleCloudPlatform/kubernetes/issues/8119

**Comment by deads2k** [comment] 2015-05-26 19:18
still waiting on GoogleCloudPlatform/kubernetes#8582.  Supposedly I'm just waiting on a few other in the merge queue ahead of me.

**Comment by pmorie** [comment] 2015-05-26 19:20
Env expansion: have acheived LGTM status on https://github.com/GoogleCloudPlatform/kubernetes/pull/8149 but awaiting merge

**Comment by pweil-** [comment] 2015-05-26 19:21
Security Context Constraints update:

https://github.com/GoogleCloudPlatform/kubernetes/pull/7893 is expected to be carried as a patch, we have not had adequate feedback for this to be merged

https://github.com/GoogleCloudPlatform/kubernetes/pull/8203 has been merged into upstream

https://github.com/GoogleCloudPlatform/kubernetes/pull/8607 is required by SCC but is already in OpenShift as an upstream patch with https://github.com/openshift/origin/pull/2345

**Comment by markturansky** [comment] 2015-05-26 19:37
These two PRs fix the CanSupport func for most PersistentVolume implementations.  The volume plugins won't work in PV without them.

https://github.com/GoogleCloudPlatform/kubernetes/pull/8688
https://github.com/GoogleCloudPlatform/kubernetes/pull/8732


PV Recycler (basic "rm -rf" scrub of NFS volumes):

https://github.com/GoogleCloudPlatform/kubernetes/pull/8334

**Comment by pmorie** [comment] 2015-05-27 02:58
Found a nit that needs to be fixed in https://github.com/GoogleCloudPlatform/kubernetes/pull/8149 and self-unLGTM'd.  hopefully this will get in tomorrow.

**Comment by pmorie** [comment] 2015-05-27 04:50
Lgtm status re-acheived

**Comment by pmorie** [comment] 2015-05-27 16:18
https://github.com/GoogleCloudPlatform/kubernetes/pull/8149 is merged
https://github.com/GoogleCloudPlatform/kubernetes/pull/8582 is merged

**Comment by markturansky** [comment] 2015-05-27 16:30
GoogleCloudPlatform/kubernetes#8688 merged
GoogleCloudPlatform/kubernetes#8732 merged

**Comment by ncdc** [comment] 2015-05-27 16:41
Add support for pluggable Docker exec handlers: https://github.com/GoogleCloudPlatform/kubernetes/pull/8864

**Comment by derekwaynecarr** [comment] 2015-05-27 18:43
Stop setting contianer.Requests since not supported in 1.0 as part of LimitRanger:
https://github.com/GoogleCloudPlatform/kubernetes/pull/8875

**Comment by abhgupta** [comment] 2015-05-27 22:45
Allowing ActiveDeadlineSeconds to be updated for a pod: https://github.com/GoogleCloudPlatform/kubernetes/pull/8890

Added UPSTREAM patch in the meantime: https://github.com/openshift/origin/pull/2546

**Comment by derekwaynecarr** [comment] 2015-05-28 20:33
Fix latency conditions in NamespaceExists admission plugin:
https://github.com/GoogleCloudPlatform/kubernetes/pull/8696

**Comment by derekwaynecarr** [comment] 2015-06-02 03:34
Fix bug in quota describe output:
https://github.com/GoogleCloudPlatform/kubernetes/pull/9099

**Comment by markturansky** [comment] 2015-06-02 03:41
Just a few.

https://github.com/GoogleCloudPlatform/kubernetes/pull/9069 (bug fix)
https://github.com/GoogleCloudPlatform/kubernetes/pull/9018 (PV Recycler)
https://github.com/GoogleCloudPlatform/kubernetes/pull/9020 (PV Recycler)
https://github.com/GoogleCloudPlatform/kubernetes/pull/9021 (PV Recycler)
https://github.com/GoogleCloudPlatform/kubernetes/pull/9024 (PV Recycler)

**Comment by smarterclayton** [comment] 2015-06-03 17:01
At this point I'm not planning on doing another rebase.  If this is a problem for you let me know right now.

**Comment by smarterclayton** [comment] 2015-06-03 17:06
https://github.com/GoogleCloudPlatform/kubernetes/issues/2630 is must have fixed

**Comment by smarterclayton** [comment] 2015-06-03 17:24
@pmorie please take point on 2630 (even if someone else fixes).

**Comment by derekwaynecarr** [comment] 2015-06-04 03:04
https://github.com/GoogleCloudPlatform/kubernetes/pull/9235

Racing between delete controllers could cause project deletion to take O(minutes)
As part of this, need to update Origin namespace controller to also ignore item not found errors.

**Comment by derekwaynecarr** [comment] 2015-06-05 13:13
Show resource limits in CLI
https://github.com/GoogleCloudPlatform/kubernetes/pull/9304

**Comment by smarterclayton** [comment] 2015-06-05 14:34
Everyone on this list - you need to be getting your UPSTREAMS in to OpenShift master soon.  Be sure to document your upstream patches well so that the next time we do a rebase I can decode what the causes are.

----- Original Message -----

**Comment by ncdc** [comment] 2015-06-05 14:56
Pluggable exec is in.

**Comment by pweil-** [comment] 2015-06-05 16:18
Submitted https://github.com/openshift/origin/pull/2856 for https://github.com/GoogleCloudPlatform/kubernetes/pull/7893

**Comment by pmorie** [comment] 2015-06-05 21:45
We need an upstream patch for https://github.com/GoogleCloudPlatform/kubernetes/pull/5093.

**Comment by derekwaynecarr** [comment] 2015-06-06 01:30
https://github.com/GoogleCloudPlatform/kubernetes/issues/8814

**Comment by derekwaynecarr** [comment] 2015-06-06 01:30
https://github.com/GoogleCloudPlatform/kubernetes/pull/9358

**Comment by sdminonne** [comment] 2015-06-08 10:12
Just added https://github.com/openshift/origin/pull/2917 for https://github.com/GoogleCloudPlatform/kubernetes/pull/5093

**Comment by derekwaynecarr** [comment] 2015-06-08 20:25
Clean up of get pods output to be readable.
https://github.com/GoogleCloudPlatform/kubernetes/pull/9032

**Comment by mnagy** [comment] 2015-06-09 08:59
Without https://github.com/GoogleCloudPlatform/kubernetes/pull/8688 and https://github.com/GoogleCloudPlatform/kubernetes/pull/8732, PVCs are not working properly. @markturansky @smarterclayton is there a plan to cherry pick these?

**Comment by markturansky** [comment] 2015-06-09 13:05
@mnagy on it.

**Comment by markturansky** [comment] 2015-06-09 14:51
@mnagy confirmed #8688 is already in OpenShift.  Please tell me otherwise if you can't run NFS as a PV.

**Comment by mnagy** [comment] 2015-06-09 15:03
@markturansky I didn't try, but I can't see the `spec.PersistentVolumeSource.NFS != nil` condition from #8688 in here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/volume/nfs/nfs.go#L55

**Comment by markturansky** [comment] 2015-06-09 16:11
@mnagy i'm crossing too many streams.  You are right and I made a PR to add to OS. #3002.

**Comment by pmorie** [comment] 2015-06-09 21:09
https://github.com/GoogleCloudPlatform/kubernetes/pull/9384

**Comment by derekwaynecarr** [comment] 2015-06-09 21:32
Disable pretty printing
https://github.com/GoogleCloudPlatform/kubernetes/pull/9361

**Comment by smarterclayton** [comment] 2015-06-11 03:14
Are all the ports done here?  Please consolidate your lists and mark merged items as complete.  Need to know the remaining items.

**Comment by liggitt** [comment] 2015-06-11 03:19
are you wanting to know whether they've merged to origin or to kube upstream (or both)?

**Comment by smarterclayton** [comment] 2015-06-11 03:29
Only origin matters right now

**Comment by derekwaynecarr** [comment] 2015-06-13 02:11
May also be related to scheduler issues I was seeing in scale testing.

https://github.com/GoogleCloudPlatform/kubernetes/pull/9613

**Comment by smarterclayton** [comment] 2015-06-13 21:13
Let's cherry pick this - we use a lot more run once pods.

**Comment by derekwaynecarr** [comment] 2015-06-16 03:17
https://github.com/GoogleCloudPlatform/kubernetes/pull/9765

**Comment by derekwaynecarr** [comment] 2015-06-16 03:22
Reducing load against docker is a good thing to do.  https://github.com/GoogleCloudPlatform/kubernetes/pull/9809

**Comment by smarterclayton** [comment] 2015-06-16 03:53
Whichever of us gets to this tomorrow should grab both of those.  May be the last we get.

**Comment by ncdc** [comment] 2015-06-16 14:42
> Reducing load against docker is a good thing to do

Except for the aforementioned fact that the runtime cache hammers Docker with 20 list containers calls every 10 seconds.

**Comment by smarterclayton** [comment] 2015-06-16 20:39
But the runtime cache is already in use, so you're paying that cost already.

**Comment by smarterclayton** [comment] 2015-06-17 04:12
We're out of time.  Anything remaining should be spawned as issues if critical and we'll triage individually.

**Comment by liggitt** [comment] 2015-07-18 03:17
Swept through and marked merged/resolved issues we've picked up fixes for. Noted open issues in the PR description

**Comment by ncdc** [comment] 2015-10-12 20:49
Closing. Will start a new issue to track the next batch.

**Closed by ncdc** 2015-10-12 20:49 UTC
Labels: dependency/kubernetes
