### ISSUE TITLE
[sig-storage] Projected should update labels on modification [Conformance] [Suite:openshift/conformance/parallel] [Suite:k8s] 2m26s

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#17770] opened 2017-12-13 23:19 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17749/test_pull_request_origin_extended_conformance_install/4039/

```
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    
to contain substring
    <string>: key3="value3"
```

@openshift/sig-storage

**Comment by bparees** [comment] 2017-12-21 02:06
not sure why the prefix is different but this sure seems like a dupe of https://github.com/openshift/origin/issues/17697

**Closed by bparees** 2017-12-21 02:06 UTC
Labels: kind/test-flake, sig/storage
