### ISSUE TITLE
Latest docker CE version kubelet failed to "StartContainer" for StatefulSet

### ISSUE THREAD

**Issue by kcd83** [openshift/origin#13520] opened 2017-03-23 03:42 UTC
kubelet failed to parse docker version "17.03.0-ce" when creating a StatefulSet pod

##### Version
```
oc v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://10.0.75.2:8443
openshift v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
```
On docker for windows
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

##### Steps To Reproduce
1. Launch oc cluster up and provision persistent volumes
2. Create StatefulSet as per https://wesmorgan.svbtle.com/rabbitmq-cluster-on-kubernetes-with-statefulsets

When developing locally comment out annotation `volume.alpha.kubernetes.io/storage-class: anything` as that doesn't seem to match with host_only pc
`oc process -f .\rabbit.yaml -o yaml | oc create -f -`

##### Current Result

Pod starts and binds persistent storage but `oc describe pod/rabbitmq-0` shows a docker version parse error
```
20s           7s              2       {kubelet localhost}                     Warning         FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""
```
##### Expected Result

StatefulSet Pod to start

##### Additional Information
Looks similar to https://github.com/openshift/origin/issues/13281

**Comment by kcd83** [comment] 2017-03-23 04:18
I tried the tip to use and older version
```
oc cluster up --host-data-dir=/mydata --version=v1.5.0-alpha.3
```
And I noticed persistent volumes are created by default this time `oc get pv`, yay!

I seem to get much further, possibly onto an unrelated issue.

```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  21s           21s             2       {default-scheduler }                    Warning         FailedScheduling        SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected.
  20s           20s             1       {default-scheduler }                    Normal          Scheduled               Successfully assigned rabbitmq-0 to localhost
  19s           19s             1       {kubelet localhost}                     Warning         FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "Failed to check docker api version: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""

  19s   18s     2       {kubelet localhost}                                     Warning MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  18s   18s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Pulled                  Container image "rabbitmq:3.6.6-management-alpine" already present on machine
  18s   18s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Created                 Created container with docker id a04cc087f738; Security:[seccomp=unconfined]
  18s   18s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Started                 Started container with docker id a04cc087f738
  18s   18s     1       {kubelet localhost}     spec.containers{rabbitmq}       Warning FailedPostStartHook
```

And later

```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  1m            1m              2       {default-scheduler }                    Warning         FailedScheduling        SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected.
  1m            1m              1       {default-scheduler }                    Normal          Scheduled               Successfully assigned rabbitmq-0 to localhost
  1m            1m              1       {kubelet localhost}                     Warning         FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "Failed to check docker api version: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""

  1m    1m      1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Started         Started container with docker id a04cc087f738
  1m    1m      1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Created         Created container with docker id a04cc087f738; Security:[seccomp=unconfined]
  54s   54s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Created         Created container with docker id c2bc3062b97b; Security:[seccomp=unconfined]
  54s   54s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Killing         Killing container with docker id a04cc087f738: PostStart handler: Error executing in Docker Container: 2
  53s   53s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Started         Started container with docker id c2bc3062b97b
  54s   23s     2       {kubelet localhost}                                     Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "rabbitmq" with RunContainerError: "PostStart handler: Error executing in Docker Container: 2"

  23s   23s     1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Killing         Killing container with docker id c2bc3062b97b: PostStart handler: Error executing in Docker Container: 2
  22s   21s     2       {kubelet localhost}     spec.containers{rabbitmq}       Warning BackOff         Back-off restarting failed docker container
  22s   21s     2       {kubelet localhost}                                     Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "rabbitmq" with CrashLoopBackOff: "Back-off 10s restarting failed container=rabbitmq pod=rabbitmq-0_myproject(15099c37-0f7f-11e7-8c9a-ca45074d1115)"

  1m    7s      4       {kubelet localhost}                                     Warning MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  1m    7s      3       {kubelet localhost}     spec.containers{rabbitmq}       Warning FailedPostStartHook
  1m    7s      3       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Pulled                  Container image "rabbitmq:3.6.6-management-alpine" already present on machine
  7s    7s      1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Created                 Created container with docker id d4c2ceb15c2b; Security:[seccomp=unconfined]
  7s    7s      1       {kubelet localhost}     spec.containers{rabbitmq}       Normal  Started                 Started container with docker id d4c2ceb15c2b
```

**Comment by pweil-** [comment] 2017-03-23 16:58
Agree that this looks like a duplicate of https://github.com/openshift/origin/issues/13281.  If you find other issues in the hook debugging please feel free to open new items.  Thanks!

**Closed by pweil-** 2017-03-23 16:58 UTC

**Comment by mbn18** [comment] 2017-04-14 07:07
Got stuck on the first tutorial.

OS: Fedora25

Version:

	oc v3.6.0-alpha.1+7044e57-29
	kubernetes v1.5.2+43a9be4
	features: Basic-Auth GSSAPI Kerberos SPNEGO

	Server https://192.168.1.100:8443
	openshift v3.6.0-alpha.1+7044e57-29
	kubernetes v1.5.2+43a9be4

The error:

>Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.04.0-ce\": illegal zero-prefixed version component \"04\" in \"17.04.0-ce\""

Tutorial worked on:

	oc v1.4.1+3f9807a
	kubernetes v1.4.0+776c994
	features: Basic-Auth GSSAPI Kerberos SPNEGO

	Server https://192.168.1.100:8443
	openshift v1.4.1+3f9807a
	kubernetes v1.4.0+776c994
