### ISSUE TITLE
Namespaces SelfLink broken

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12841] opened 2017-02-06 22:17 UTC
```
$ oc version
oc v1.5.0-alpha.2+8955ad7-388
kubernetes v1.5.2+43a9be4
features: Basic-Auth
$ oc create namespace test
namespace "test" created
$ oc get namespace test -o jsonpath={.metadata.selfLink}
/api/v1/namespacestest
```

Seems bad. Maybe came in with the rebase? /cc @ncdc @liggitt

**Comment by liggitt** [comment] 2017-02-06 22:18
dupe of https://github.com/openshift/origin/issues/12553

**Closed by liggitt** 2017-02-06 22:18 UTC
Labels: component/restapi, priority/P1
