### ISSUE TITLE
Deployment extended test fails "Command deploy is deprecated"

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#19543] opened 2018-04-27 18:14 UTC
Test flake - gcp test fails with following message:

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:546
Expected
    <string>: Command "deploy" is deprecated, Use the `rollout latest` and `rollout cancel` commands instead.
to contain substring
    <string>: --> pre: Running hook pod ...
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:559
```

Link to failing test: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19532/test_pull_request_origin_extended_conformance_gce/19691/

**Comment by gabemontero** [comment] 2018-04-27 18:27
@openshift/sig-master

**Comment by mfojtik** [comment] 2018-04-27 18:48
known, this is the test loosing the parts from log...

**Comment by liggitt** [comment] 2018-04-27 18:54
same issue as https://github.com/openshift/origin/issues/13980 ?

**Comment by adambkaplan** [comment] 2018-05-03 19:14
@mfojtik @liggitt close as duplicate?

**Comment by liggitt** [comment] 2018-05-03 19:40
/close
duplicate of #13980

**Closed by liggitt** 2018-05-03 19:40 UTC
Labels: kind/test-flake, sig/master
