### ISSUE TITLE
Image limits to tags not applies

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9376] opened 2016-06-16 13:47 UTC
Similarly to #9375.

##### Version
```
oc v1.3.0-alpha.1-379-g662753c
kubernetes v1.3.0-alpha.3-599-g2746284
```

##### Steps To Reproduce
Create following limits, purposefully low, but this time just `openshift.io/image-tags`:
```
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "images"
spec:
  limits:
    - type: openshift.io/Image
      max:
        storage: 100Mi 
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 1
```

Push image to integrated registry, I've used `openshift/origin-pod`.
Currently I have one image, having single tag and within the storage size.

oc edit is/origin-pod and add 2nd tag, like so:
```
  tags:
  - name: "3.5"
    from:
      kind: DockerImage
      name: openshift/python-34-centos7:latest
```

oc describe that is gives me:
```
...
latest	<pushed>				22 minutes ago	172.30.252.121:5000/test/origin-pod@sha256:f5d7c2975de6fb...	<same>
3.5	openshift/python-34-centos7:latest	6 minutes ago	openshift/python-34-centos7@sha256:ca0cabc43b8b98...		<same>
```

Why was I able to add 2nd tag to that image stream? Shouldn't `openshift.io/image-tag` stop me from doing that?

**Comment by miminar** [comment] 2016-06-17 12:56
@soltysh as documented in related [docs PR](https://github.com/openshift/openshift-docs/pull/1850/files#diff-64e8dd2de02857927723c20336bb447bR306), `openshift.io/image-tags` doesn't restrict pushed to internal registry. You can do it with `openshift.io/images`.

Unfortunately the docs PR isn't merged yet. I hope it will be understandable once there and with proper rendering.

**Comment by soltysh** [comment] 2016-06-20 09:12
@miminar I didn't do any pushes, I've just edited the image stream spec. Shouldn't that limit stop me from doing that? If not, what's the purpose of it?

**Comment by miminar** [comment] 2016-06-20 09:41
@soltysh I see, in that case, it should have stopped you. I'll look into it. Thanks.

**Comment by mfojtik** [comment] 2016-08-02 10:31
@deads2k FYI (is this the IS quota issue you was referring to yesterday?)

**Comment by deads2k** [comment] 2016-08-02 11:41
> @deads2k FYI (is this the IS quota issue you was referring to yesterday?)

Yeah, it looked to missing the wiring needed to make it work.

**Comment by miminar** [comment] 2016-08-17 10:36
I cannot reproduce. @soltysh perhaps you looked just in to IS.Status. Note that `openshift.io/image-tags` applies only to tags in IS.Spec. When I try to add another tag to IS.Spec, I see:


```
oc get -o json is busybox | jq '.spec.tags  |= . + [{"name": "3.5", "from": {"kind":"DockerImage", "name":"openshift/python-34-centos7:latest"}}]'
{
  "kind": "ImageStream",
  "apiVersion": "v1",
  ...
  "spec": {
    "tags": [
      {
        "name": "centos",
        "annotations": null,
        "from": {
          "kind": "DockerImage",
          "name": "centos/perl-520-centos7:latest"
        },
        "generation": 11,
        "importPolicy": {}
      },
      {
        "name": "3.5",
        "from": {
          "kind": "DockerImage",
          "name": "openshift/python-34-centos7:latest"
        }
      }
    ]
  },
  ...

$ oc get -o json is busybox | jq '.spec.tags  |= . + [{"name": "3.5", "from": {"kind":"DockerImage", "name":"openshift/python-34-centos7:latest"}}]' | oc replace -f -
The ImageStream "busybox" is invalid.
imageStream: Forbidden: ImageStream "busybox" is forbidden: requested usage of openshift.io/image-tags exceeds the maximum limit per openshift.io/ImageStream (2 > 1)
```

**Closed by miminar** 2016-08-17 10:36 UTC
Labels: component/imageregistry, priority/P2
