### ISSUE TITLE
Asset tests broken - URI is not defined errors

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#6651] opened 2016-01-13 23:55 UTC
Getting errors like:

```
1)  unauthenticated user should be able to log in
  - UnknownError: unknown error: [$injector:modulerr] Failed to instantiate module openshiftConsole due to:
ReferenceError: URI is not defined
```

Seems to be on every test/merge that makes it to asset e2e tests

@liggitt @spadgett in case you can investigate before I can

**Comment by jwforres** [comment] 2016-01-13 23:58
Last PR that merged had no ui changes, so I suspect it is some npm or bower dep that has been modified and wasn't version locked

**Comment by csrwng** [comment] 2016-01-14 00:49
My PR has no UI changes and it's failing with the same error

**Comment by spadgett** [comment] 2016-01-14 00:51
I can't reproduce locally clean installing assets.

**Comment by liggitt** [comment] 2016-01-14 00:51
Yeah, the whole queue is affected. I'll look into it in a few minutes if no one else grabs it

**Comment by liggitt** [comment] 2016-01-14 00:52
Maybe the cached compiled assets in Jenkins bit us

**Comment by jwforres** [comment] 2016-01-14 01:01
Yeah it has to be something specific in Jenkins env because I can't
reproduce it locally either

**Comment by jwforres** [comment] 2016-01-14 04:18
Confirmed it was a bad base_ami, not sure what exactly caused the URI.js bower_component to only get partially extracted to the file system.

Latest base_ami and devenv_ami are fine so queue should be unblocked now.

**Comment by liggitt** [comment] 2016-01-14 04:27
fixed in https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3143/
tests in https://github.com/openshift/vagrant-openshift/issues/382 should prevent it from happening again

**Closed by liggitt** 2016-01-14 04:27 UTC
Labels: component/web, kind/test-flake, priority/P2
