### ISSUE TITLE
Container logs: EACCES: Permission denied - /var/log/es-containers.log.pos

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#8358] opened 2016-04-05 12:16 UTC
##### Version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
Followed [https://docs.openshift.org/latest/install_config/aggregate_logging.html](url)

##### Current Result
Possible to access Kibana webconsole but showing:
No results found

##### Expected Result
Showing logs

##### Additional Information
The logs of the pods are normal except the logs of my fluentd pods:
```
2016-04-05 12:10:58 +0000 [error]: fluentd main process died unexpectedly. restarting.
2016-04-05 12:11:03 +0000 [error]: unexpected error error_class=Errno::EACCES error=#<Errno::EACCES: Permission denied - /var/log/es-containers.log.pos>
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/plugin/in_tail.rb:97:in `initialize'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/plugin/in_tail.rb:97:in `open'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/plugin/in_tail.rb:97:in `start'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/root_agent.rb:115:in `block in start'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/root_agent.rb:114:in `each'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/root_agent.rb:114:in `start'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/engine.rb:237:in `start'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/engine.rb:187:in `run'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:564:in `run_engine'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:156:in `block in start'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:360:in `call'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:360:in `main_process'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:333:in `block in supervise'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:332:in `fork'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:332:in `supervise'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/supervisor.rb:150:in `start'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2016-04-05 12:11:03 +0000 [error]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-04-05 12:11:03 +0000 [error]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/gems/fluentd-0.12.22/bin/fluentd:5:in `<top (required)>'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/bin/fluentd:23:in `load'
  2016-04-05 12:11:03 +0000 [error]: /opt/app-root/src/bin/fluentd:23:in `<main>'
2016-04-05 12:11:04 +0000 [error]: fluentd main process died unexpectedly. restarting.
```

**Comment by sosiouxme** [comment] 2016-04-05 15:30
This is a duplicate of https://github.com/openshift/origin-aggregated-logging/issues/89

Short term fix is to use the `privileged` SCC instead of `hostmount-anyuid`.

**Comment by lorenzvth7** [comment] 2016-04-05 16:55
Tried the short term fix but without success:
`oc edit scc privileged`

```
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:management-infra:management-admin
- system:serviceaccount:default:router
- system:serviceaccount:default:registry
- system:serviceaccount:logging:aggregated-logging-fluentd
```
and

`oc edit oc edit scc hostmount-anyuid `

```
...
priority: null
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:pv-recycler-controller
```

**Comment by sosiouxme** [comment] 2016-04-05 18:44
I should have said re-create fluentd pods. The context is set on the pod definition so you'll get the same thing with a simple restart. Please delete them and let them be re-created.

**Comment by lorenzvth7** [comment] 2016-04-05 19:26
@sosiouxme I've deleted them, they were recreated automatically. But same error.

**Comment by lorenzvth7** [comment] 2016-04-05 19:46
Pod details of a fluentd pod
```
Pod

Name
    logging-fluentd-yo8v3
Namespace
    logging
Created
    Apr 5, 2016 9:42:53 PM
Restart policy
    Always
Service account
    aggregated-logging-fluentd

Status

Phase
    Running
Node
    ip-172-xx-xx-xx.eu-central-1.compute.internal (172.xx.xx.xx)
IP on node
    10.1.2.2 

Container Statuses

Name
    fluentd-elasticsearch
State
    Running since Apr 5, 2016 9:42:57 PM 
Ready
    true
Restart Count
    0

Containers

Name
    fluentd-elasticsearch
Image
    docker.io/openshift/origin-logging-fluentd:latest
Ports
    none
Env vars
    ES_CA=/etc/fluent/keys/ca
    ES_CLIENT_CERT=/etc/fluent/keys/cert
    ES_CLIENT_KEY=/etc/fluent/keys/key
    ES_COPY=false
    ES_COPY_CA=
    ES_COPY_CLIENT_CERT=
    ES_COPY_CLIENT_KEY=
    ES_COPY_HOST=
    ES_COPY_PASSWORD=
    ES_COPY_PORT=
    ES_COPY_SCHEME=https
    ES_COPY_USERNAME=
    ES_HOST=logging-es
    ES_PORT=9200
    K8S_HOST_URL=https://kubernetes.default.svc.cluster.local
    OPS_CA=/etc/fluent/keys/ca
    OPS_CLIENT_CERT=/etc/fluent/keys/cert
    OPS_CLIENT_KEY=/etc/fluent/keys/key
    OPS_COPY_CA=
    OPS_COPY_CLIENT_CERT=
    OPS_COPY_CLIENT_KEY=
    OPS_COPY_HOST=
    OPS_COPY_PASSWORD=
    OPS_COPY_PORT=
    OPS_COPY_SCHEME=https
    OPS_COPY_USERNAME=
    OPS_HOST=logging-es
    OPS_PORT=9200

Volumes

Name
    varlog
Type
    host path
Path
    /var/log

Name
    varlibdockercontainers
Type
    host path
Path
    /var/lib/docker/containers

Name
    certs

Name
    dockerhostname
Type
    host path
Path
    /etc/hostname

Name
    aggregated-logging-fluentd-token-ojgxy

Labels

component
    fluentd
provider
    openshift

Annotations

kubernetes.io/created-by
    {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"logging","name":"logging-fl... 
openshift.io/scc
    privileged
```

**Comment by sosiouxme** [comment] 2016-04-05 20:07
I don't know what's going on, then, will have to investigate further.
Sorry. In the meantime, `setenforce 0` should get it working.

**Comment by lorenzvth7** [comment] 2016-04-05 20:14
@sosiouxme Where do I have to put that command?
Okay, I've this error on both environments I have. I've reproduced all the steps which I've performed in the mailing list.

**Comment by elyscape** [comment] 2016-04-05 20:33
Try deleting and recreating the `logging-fluentd` daemonset.

**Comment by lorenzvth7** [comment] 2016-04-05 20:39
@elyscape How can you delete a role. I tried the following but did not seem to work:
```
$ oc delete role daemonset-admin
role "daemonset-admin" deleted
$ oc process logging-deployer-account-template -n openshift      | oc create -f -
Error from server: serviceaccounts "logging-deployer" already exists
Error from server: role "oauth-editor" already exists
Error from server: role "daemonset-admin" already exists
```

**Comment by lorenzvth7** [comment] 2016-04-05 20:40
@elyscape How can you delete a role. I tried the following but did not seem to work:
```
$ oc delete role daemonset-admin
role "daemonset-admin" deleted
$ oc process logging-deployer-account-template -n openshift      | oc create -f -
Error from server: serviceaccounts "logging-deployer" already exists
Error from server: role "oauth-editor" already exists
Error from server: role "daemonset-admin" already exists
```

**Comment by lorenzvth7** [comment] 2016-04-05 20:59
@elyscape I've deleted the daemonset:
```
oc delete clusterrole daemonset-admin
clusterrole "daemonset-admin" deleted
$ oc process logging-deployer-account-template -n openshift      | oc create -f -
clusterrole "daemonset-admin" created
```
I've deleted my fluentd pods and they were recreated but still the same error :/

**Comment by lorenzvth7** [comment] 2016-04-05 21:32
@elyscape I tried it this way. But still the same error.
```
oc process -n logging logging-fluentd-template | \
  oc create -n logging -f -
```

**Comment by elyscape** [comment] 2016-04-05 22:13
Run `oc get pods --selector=logging-infra=fluentd -o yaml` and paste the results here, after filtering out any sensitive information.

**Comment by lorenzvth7** [comment] 2016-04-05 22:21
@elyscape 

```
$ oc get pods --selector=logging-infra=fluentd -o yaml
apiVersion: v1
items: []
kind: List
metadata: {}
$ oc get pods
NAME                          READY     STATUS      RESTARTS   AGE
logging-curator-1-i7q3n       1/1       Running     0          56m
logging-deployer-d3pd4        0/1       Completed   0          1h
logging-es-ta7qnvl6-1-n83qz   1/1       Running     0          56m
logging-fluentd-0h73s         1/1       Running     0          37m
logging-fluentd-qgh63         1/1       Running     0          37m
logging-kibana-1-z94jt        2/2       Running     0          56m
```

**Comment by lorenzvth7** [comment] 2016-04-05 22:27
@elyscape I assume you wanted something like this. This is the yaml of a pod which is giving the error:

```
apiVersion: v1
kind: Pod
metadata:
  name: logging-fluentd-0h73s
  generateName: logging-fluentd-
  namespace: logging
  selfLink: /api/v1/namespaces/logging/pods/logging-fluentd-0h73s
  uid: 4d355c13-fb77-11e5-b9a5-0274c5f45222
  resourceVersion: '527689'
  creationTimestamp: '2016-04-05T21:42:31Z'
  labels:
    component: fluentd
    provider: openshift
  annotations:
    kubernetes.io/created-by: "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"DaemonSet\",\"namespace\":\"logging\",\"name\":\"logging-fluentd\",\"uid\":\"4d335654-fb77-11e5-b9a5-0274c5f45271\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"52720\"}}\n"
    openshift.io/scc: privileged
spec:
  volumes:
    -
      name: varlog
      hostPath:
        path: /var/log
    -
      name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    -
      name: certs
      secret:
        secretName: logging-fluentd
    -
      name: dockerhostname
      hostPath:
        path: /etc/hostname
    -
      name: aggregated-logging-fluentd-token-xtr2X
      secret:
        secretName: aggregated-logging-fluentd-token-xtr2X
  containers:
    -
      name: fluentd-elasticsearch
      image: 'docker.io/openshift/origin-logging-fluentd:latest'
      env:
        -
          name: K8S_HOST_URL
          value: 'https://kubernetes.default.svc.cluster.local'
        -
          name: ES_HOST
          value: logging-es
        -
          name: ES_PORT
          value: '9200'
        -
          name: ES_CLIENT_CERT
          value: /etc/fluent/keys/cert
        -
          name: ES_CLIENT_KEY
          value: /etc/fluent/keys/key
        -
          name: ES_CA
          value: /etc/fluent/keys/ca
        -
          name: OPS_HOST
          value: logging-es
        -
          name: OPS_PORT
          value: '9200'
        -
          name: OPS_CLIENT_CERT
          value: /etc/fluent/keys/cert
        -
          name: OPS_CLIENT_KEY
          value: /etc/fluent/keys/key
        -
          name: OPS_CA
          value: /etc/fluent/keys/ca
        -
          name: ES_COPY
          value: 'false'
        -
          name: ES_COPY_HOST
        -
          name: ES_COPY_PORT
        -
          name: ES_COPY_SCHEME
          value: https
        -
          name: ES_COPY_CLIENT_CERT
        -
          name: ES_COPY_CLIENT_KEY
        -
          name: ES_COPY_CA
        -
          name: ES_COPY_USERNAME
        -
          name: ES_COPY_PASSWORD
        -
          name: OPS_COPY_HOST
        -
          name: OPS_COPY_PORT
        -
          name: OPS_COPY_SCHEME
          value: https
        -
          name: OPS_COPY_CLIENT_CERT
        -
          name: OPS_COPY_CLIENT_KEY
        -
          name: OPS_COPY_CA
        -
          name: OPS_COPY_USERNAME
        -
          name: OPS_COPY_PASSWORD
      resources:
        limits:
          cpu: 100m
        requests:
          cpu: 100m
      volumeMounts:
        -
          name: varlog
          mountPath: /var/log
        -
          name: varlibdockercontainers
          readOnly: true
          mountPath: /var/lib/docker/containers
        -
          name: certs
          readOnly: true
          mountPath: /etc/fluent/keys
        -
          name: dockerhostname
          readOnly: true
          mountPath: /etc/docker-hostname
        -
          name: aggregated-logging-fluentd-token-xtr2y
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      imagePullPolicy: Always
      securityContext:
        privileged: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  nodeSelector:
    logging-infra-fluentd: 'true'
  host: ip-172-XX-XX-XX.XX-XX-1.compute.internal
  serviceAccountName: aggregated-logging-fluentd
  serviceAccount: aggregated-logging-fluentd
  nodeName: ip-172-XX-XX-XX.XX-XX-1.compute.internal
  securityContext: {  }
  imagePullSecrets:
    -
      name: aggregated-logging-fluentd-dockercfg-jn8s8
status:
  phase: Running
  conditions:
    -
      type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2016-04-05T21:42:36Z'
  hostIP: 172.XX.XX.XX
  podIP: 10.1.0.6
  startTime: '2016-04-05T21:42:32Z'
  containerStatuses:
    -
      name: fluentd-elasticsearch
      state:
        running:
          startedAt: '2016-04-05T21:42:36Z'
      lastState: {  }
      ready: true
      restartCount: 0
      image: 'docker.io/openshift/origin-logging-fluentd:latest'
      imageID: 'docker://f841fe531e980e970d69b353bf49ec8f69dd13f88dccfdaff578d91f0fa58e63'
      containerID: 'docker://9adaa447d343c62cc5d88a17ec18d05ff24a10f56154ea4d5539c488a66f2122'
```

**Comment by elyscape** [comment] 2016-04-06 00:09
Okay, the problem is most likely that the container is being executed as an SELinux type that doesn't have access to the log files, just by default. One way to deal with this is to create a custom SELinux type that has access and then assigning that to the `logging-fluentd` daemonset.

The code for the type is:
```
policy_module(container_logger, 1.0.0)

virt_sandbox_domain_template(container_logger)
##############################
# virt_sandbox_net_domain(container_logger_t)
gen_require(`
 attribute   sandbox_net_domain;
')

typeattribute container_logger_t sandbox_net_domain;
##############################
logging_manage_all_logs(container_logger_t)

# necessary until Docker fixes the log type
docker_read_lib_files(container_logger_t)
```
This is based on [this blog post](https://www.projectatomic.io/blog/2016/03/selinux-and-docker-part-2/).

Put this in a file named `container_logger.te`. Then, on a system with the `selinux-policy-devel` package installed, run `make -f /usr/share/selinux/devel/Makefile container_logger.pp` while in the same directory. Once it completes, copy the resultant `container_logger.pp` file to all of your OpenShift nodes and run `semodule -i container_logger.pp` on each.

Once you've done this, you can assign it to the `aggregated-logging-fluentd` service account. The way I've been doing this is to remove it from the `privileged` SCC and adding a new one with the following definition:
```yaml
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'container-logger provides all the features of the
      restricted SCC but allows host mounts and any UID by a pod, which runs as the
      container_logger_t SELinux type.  This is primarily used by the log aggregation
      system. WARNING: this SCC allows host file system access as any UID, including
      UID 0.  Grant with caution.'
  creationTimestamp: null
  name: container-logger
priority: null
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  seLinuxOptions:
    type: container_logger_t
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:logging:aggregated-logging-fluentd
```
Then delete your existing pods and you should be good to go.

**Comment by sosiouxme** [comment] 2016-04-06 00:14
it's a clusterrole. oc delete clusterrole daemonset-admin.

don't worry about running that each time though or getting all of it to
succeed if you do.

**Comment by sosiouxme** [comment] 2016-04-06 00:14
Run `setenforce 0` on any nodes.

This does however remove the protection of SELinux.

**Comment by lorenzvth7** [comment] 2016-04-06 06:13
@elyscape Any idea what could be the issue for this behaviour? I've just a basic centos7 of Amazon EC2. So I don't really like to add additional configuration to let this work.

**Comment by elyscape** [comment] 2016-04-06 06:23
Run `oc debug ds/logging-fluentd -- cat /proc/self/attr/current` and paste the output.

**Comment by lorenzvth7** [comment] 2016-04-06 06:33
@elyscape 
```
$ oc debug ds/logging-fluentd -- cat /proc/self/attr/current
error: cannot debug logging-fluentd: cannot attach to extensions/__internal, Kind=DaemonSet: not implemented
$ oc get ds
NAME              CONTAINER(S)            IMAGE(S)                                            SELECTOR                                         NODE-SELECTOR
logging-fluentd   fluentd-elasticsearch   docker.io/openshift/origin-logging-fluentd:latest   component in (fluentd),provider in (openshift)   logging-infra-fluentd=true
```

**Comment by elyscape** [comment] 2016-04-06 06:42
Run `oc get pods --selector=logging-infra=fluentd`, choose one of them, and then run: `oc debug pod/$THATPODNAME -- cat /proc/self/attr/current` and paste the output.

**Comment by lorenzvth7** [comment] 2016-04-06 06:45
@elyscape 
```

$ oc debug pod/logging-fluentd-80xzt -- cat /proc/self/attr/current
Debugging with pod/debug-logging-fluentd-80xzt, original command: <image entrypoint>
Waiting for pod to start ...
system_u:system_r:svirt_lxc_net_t:s0:c216,c576

Removing debug pod ...
```

**Comment by elyscape** [comment] 2016-04-06 06:47
Yup. The problem was what I thought: it's being run under the `svirt_lsc_net_t` SELinux type, which doesn't have access to `var_log_t`. If you don't want to disable SELinux, you'll need to follow the instructions for creating a new SELinux type that I posted above.

**Comment by lorenzvth7** [comment] 2016-04-06 07:04
@elyscape Okay will try. What is the reason it's using that SELinux Type? Is it default for an OS or?

**Comment by elyscape** [comment] 2016-04-06 07:28
Why what?

**Comment by lorenzvth7** [comment] 2016-04-06 07:30
@elyscape Sorry, it's a bit confusing why I have tis problem and I did not see it for other OpenShift users.
After some research I found some things like this `chcon -Rt svirt_sandbox_file_t /var/lib/openshift/openshift.local.volumes/` for people who also had selinux issues.
But my selinux knowledge is too minimal to understand.

**Comment by elyscape** [comment] 2016-04-06 07:46
Ah, gotcha. I don't know about in earlier versions of OpenShift but, at least with the current version, all new users will be affected by this. We're working on it in openshift/origin-aggregated-logging#89.

**Comment by lorenzvth7** [comment] 2016-04-06 08:14
@elyscape thanks for the info. But the other users are able to use the 'workaround' `Or, as an alternative, does everything still work out if we just keep fluentd in the privileged SCC?"` which isn't working for me?

**Comment by elyscape** [comment] 2016-04-06 08:25
That I don't know. I went with the route I described here.

**Comment by sosiouxme** [comment] 2016-07-05 15:56
Origin BZ is https://bugzilla.redhat.com/show_bug.cgi?id=1322604

**Closed** 2016-09-19 13:32 UTC
Labels: component/logging, priority/P2
