### ISSUE TITLE
Image signature corrupt when verifying using invalid key

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#15082] opened 2017-07-06 16:11 UTC
When a signature verification saved with a valid public key, then saved using an invalid public key, the signature gets corrupted and cannot be verified again.

Related to #15081 

##### Version
```
$ oc version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Push and sign an image

        $ sudo GNUPGHOME=/home/aweiteka/.gnupg atomic --debug push \
        --sign-by aweiteka@redhat.com --type atomic --insecure \
        172.30.1.1:5000/prod/rhel-atomic:latest
2. Verify image signature with **valid** key and save

        $ oc adm verify-image-signature \
        sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7 \
        --expected-identity 172.30.1.1:5000/prod/rhel-atomic:latest \
        --public-key /home/aweiteka/.gnupg/aweiteka-redhat.pub --save
        image "sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7" identity is now confirmed (signed by GPG key "0EEB7F8664E11092")
3. Verify with **invalid** key, removing verification fields

        $ oc adm verify-image-signature sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 --expected-identity 172.30.1.1:5000/myproject/rhel-atomic:latest --public-key /home/aweiteka/.gnupg/aweiteka.pub --save
        error verifying signature sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7@fd1003165d73616db42a7d6ba45cbc50 for image sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 (verification status will be removed): signature rejected: Invalid GPG signature: (*packet.Signature)(nil)
4. Verify with valid key again

        $ oc adm verify-image-signature sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 --expected-identity 172.30.1.1:5000/myproject/rhel-atomic:latest --public-key /home/aweiteka/.gnupg/aweiteka-redhat.pub --save

##### Current Result

With `--save` flag:
```
error verifying signature  for image sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 (verification status will be removed): signature rejected: EOF
The Image "sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7" is invalid:
* signatures[0].metadata.name: Required value: name or generateName is required
* signatures[0].metadata.name: Invalid value: "": name must be of format <imageName>@<signatureName>
* signatures[0].type: Required value
* signatures[0].content: Required value
```

Without `--save` flag:
```
error verifying signature  for image sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 (verification status will be removed): signature rejected: EOF
```

##### Expected Result

```
image "sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7" identity is now confirmed (signed by GPG key "0EEB7F8664E11092")
```

##### Workaround

Re-push and sign image then verify

##### Additional Information

OUTPUT: https://paste.fedoraproject.org/paste/8TiqcJT4j4d2IEUmCJFk7Q

**Comment by mfojtik** [comment] 2017-10-27 09:50
duplicate of https://github.com/openshift/origin/issues/16301

**Closed by mfojtik** 2017-10-27 09:50 UTC
Labels: component/image, kind/bug, priority/P2
