### ISSUE TITLE
oc new-build running language detection when shouldn't.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#17704] opened 2017-12-09 10:07 UTC
If I run:

```
oc new-build --strategy source --image-stream parts-builder --code https://github.com/jupyter-on-openshift/jupyter-notebook-builder --context-dir parts-catalog/python-3.6
```

then ``oc new-build`` should not be doing language detection as I have explicitly told it source strategy is to be used and what the image stream for the builder is.

It is instead pulling down the repo and then giving error:

```
error: No language matched the source repository
```

If instead use:

```
oc new-build parts-builder~https://github.com/jupyter-on-openshift/jupyter-notebook-builder --context-dir parts-catalog/python-3.6
```

it works fine and creates the build.

The latter doesn't even attempt to pull down the git repo locally.

Can't see why language detection should be triggered in the first case.

##### Version

```
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce

I was using my own S2I builder above, but you can see it even running:

```
oc new-build --strategy source --image-stream python --code https://github.com/jupyter-on-openshift/jupyter-notebook-builder --context-dir parts-catalog/python-3.6
```

##### Current Result

Pulls down git repo and runs language detection, which fails with:

```
error: No language matched the source repository
```

##### Expected Result

Should now that since provide ``--strategy`` and ``--image-stream`` and ``--code`` that language detection should not be necessary and so doesn't need to pull down repo locally either.

##### Additional Information

Also existed as problem in 3.6.

**Comment by bparees** [comment] 2017-12-11 19:47
dupe of https://bugzilla.redhat.com/show_bug.cgi?id=1470374

**Closed by bparees** 2017-12-11 19:47 UTC
Labels: component/build, kind/enhancement, priority/P2
