### ISSUE TITLE
examples/sample-app fails to deploy

### ISSUE THREAD

**Issue by grdryn** [openshift/origin#3820] opened 2015-07-22 09:46 UTC
Hi,

I appear to be having the same issue as #3177 (which was closed, but I don't see a concrete solution there).

I've gotten to step 12 in the README.md for the sample app:

```
[vagrant@ose1 sample-app]$ oc new-app application-template-stibuild.json
services/frontend
routes/route-edge
imagestreams/origin-ruby-sample
imagestreams/ruby-20-centos7
buildconfigs/ruby-sample-build
deploymentconfigs/frontend
services/database
deploymentconfigs/database
Service "frontend" created at 172.30.38.159 with port mappings 5432->8080.
A build was created - you can run `oc start-build ruby-sample-build` to start it.
Service "database" created at 172.30.204.146 with port mappings 5434->3306.
Run 'oc status' to view your app.
```

When I look in the web dashboard, I see that in 'Browse'->'events', that there's a 'failedCreate' on 'deploymentConfig' for the 'frontend'. Here's what `oc describe dc frontend` gives me:

```
[vagrant@ose1 sample-app]$ oc describe dc frontend
Name:       frontend
Created:    25 minutes ago
Labels:     template=application-template-stibuild
Latest Version: Not deployed
Triggers:   Image(origin-ruby-sample@latest, auto=true), Config
Strategy:   Rolling
          Pre-deployment hook (pod type, failure policy: Abort)
            Container:  ruby-helloworld
            Command:    /bin/true
            Env:    CUSTOM_VAR1=custom_value1
          Post-deployment hook (pod type, failure policy: Ignore)
            Container:  ruby-helloworld
            Command:    /bin/false
            Env:    CUSTOM_VAR2=custom_value2
Template:
            Selector:   name=frontend
            Replicas:   2
            Containers:
                NAME        IMAGE           ENV
                ruby-helloworld origin-ruby-sample  ADMIN_PASSWORD=k5DUMHrc,ADMIN_USERNAME=adminKYY,MYSQL_DATABASE=root,MYSQL_PASSWORD=srOM0GHr,MYSQL_USER=userBU3
Latest Deployment:  <none>
Events:
  FirstSeen             LastSeen            Count   From        SubobjectPath   Reason      Message
  Wed, 22 Jul 2015 09:08:43 +0000   Wed, 22 Jul 2015 09:33:28 +0000 14  {deployer }         failedCreate    Couldn't create initial deployment: DeploymentConfig "frontend" is invalid: triggers[0].imageChange.tag: invalid value 'latest': no image recorded for test/origin-ruby-sample:latest
```

I'm running the [latest all-in-one release from here](https://github.com/openshift/origin/releases/tag/v1.0.3), in a CentOS7 virtual machine, with `docker-1.6.2-14.el7.centos.x86_64`.

I'm not sure if it's relevant, but I've cloned the origin repo, and I'm dealing with the `examples/sample-app` directory at commit 6ce414638e372cf38fb82e95b327afcb989cc9d4.

Does anyone have any idea what could be wrong here? Thanks in advance.
## 

Semi-related, in the same VM I've also run the openshift docker image instead of the all-in-one bundle, but the sample app fails for me at a different point there. From what I remember it was complaining that it was getting a 'connection refused' from github.com for the ruby-hello-world repo or something. I have a feeling that for some reason inside the container that was attempting this, github.com was resolving to 127.0.0.1 or something. I could be wildly wrong on this.

_Edit:_ for this second issue with the origin docker image scenario, I believe I've managed to get this to work once, but I'm not able to get back to that state. Here's the error that I usually hit:

```
[vagrant@ose3 ~]$ oc build-logs ruby-sample-build-1
E0722 16:36:20.196340       1 git.go:127] fatal: unable to connect to github.com:
E0722 16:36:20.197359       1 git.go:127] github.com[0: 127.0.0.1]: errno=Connection refused
E0722 16:36:20.197369       1 git.go:127] 
F0722 16:36:20.199618       1 builder.go:65] Build error: exit status 128
```

Doing a `docker inspect` on the failed build container shows the following under `HostConfig`:

```
"Dns": [
            "10.0.2.15",
            "8.8.8.8"
        ],
```

Again, I'm not sure if this is a dns issue.

**Comment by deanpeterson** [comment] 2015-07-22 17:49
Could this be a case of needing to run this in your terminal to switch to http instead of git for urls:  

git config --global url."https://".insteadOf git://

**Comment by bparees** [comment] 2015-07-22 20:19
i have seen cases where docker containers can't resolve any hosts until the dockerdaemon gets restarted.  your github issue sounds like that.  next time you're in that state, try running a container manually on the host (docker run -it centos /bin/sh") and see if you can resolve/ping hosts from inside it.

As for your first issue, the deployment won't succeed until your build successfully runs.  did you run a build?  did it succeed?  (if you don't run a build explicitly, one will be kicked off in a minute or two after you create the buildconfig, due to the imagechangetrigger)

**Comment by grdryn** [comment] 2015-07-23 09:49
Thanks for the replies guys.

@deanpeterson If you're referring to the second issue, I don't think so, it's not a case of me manually trying to access github over any of those protocols, this is happening as part of the automated process inside the container.

@bparees sez:
> next time you're in that state, try running a container manually on the host (docker run -it centos /bin/sh") and see if you can resolve/ping hosts from inside it.

I've tried that just now, and I can ping hosts fine from within this new CentOS container. Again, not sure if it's related (since I don't know what it means really), but `Dns` property under `HostConfig` for this container is different from the container that the build failed inside. The new one has:

    "Dns": null

For this dockerized case, I also sometimes see a slightly different error message, but it's still 'Connection refused':

```
[root@ose3 openshift]# oc build-logs ruby-sample-build-1
E0723 08:51:35.647503       1 git.go:127] fatal: unable to access 'https://github.com/openshift/ruby-hello-world.git/': Failed connect to github.com:443; Connection refused
F0723 08:51:35.652534       1 builder.go:65] Build error: exit status 128
```

> As for your first issue, the deployment won't succeed until your build successfully runs. did you run a build? did it succeed?

A build appears to get run after I execute `oc new-app -f application-template-stibuild.json`. Does that sound accurate?

**Comment by bparees** [comment] 2015-07-23 13:43
yes i'd expect a build to run within a minute or two after you run that oc new-app command.

So the fundamental issue here is your build is failing because the container (the one performing the build steps) running in your openshift environment is unable to access github.com.

i'm not sure where to go from there, is there any proxy or firewall that might be blocking the connection to 443?

you can define a proxy to use for git cloning if necessary:
https://docs.openshift.org/latest/dev_guide/builds.html#using-a-proxy-for-git-cloning

**Comment by grdryn** [comment] 2015-07-24 09:42
@bparees Thanks for your continued help with this! :)

So now I'm having the same issue (can't contact github) from both the docker image, and the aio build. But it worked fine with an older VM that I was linked to that was used for some workshop. I compared that to my one, and the biggest difference was that it was using v1.0.0, whereas mine was using 1.0.3.

I tried the 1.0.0 release on my VM, and that worked! I tried the released between those two: 1.0.1 works, 1.0.2 doesn't. I get the same results for both the aio build and the docker image for the different releases.

I don't know how I was getting a different problem originally with the aio build when I opened this issue. I'd think we can rule out networking/proxy issues with the VM or my host though, right?

**Comment by bparees** [comment] 2015-07-24 17:06
@grdryn are you saying that when you put origin v1.0.2 on your VM, containers run via "docker run" cannot access github, but when you put v1.0.1 on, they can?

those two things should have nothing to do with each other...

**Comment by grdryn** [comment] 2015-07-24 22:44
@bparees not exactly. In all cases, containers run via `docker run` work fine. The difference between `v1.0.1` and `v1.0.2` is that a build of the stibuild example in `examples/sample-app` will fail on `v1.0.2` (either with `oc new-app application-template-stibuild.json` or afterwards with `oc start-build ruby-sample-app`).

The logs of the build container say that it was a problem accessing github.com. I see two message variations that are quite similar: the one from my original posting here, and the one from my first comment after that.

**Comment by bparees** [comment] 2015-07-25 00:12
Hm.  if you just run an image (eg one of our database images) on your openshift environment, and use "oc exec" to enter the container (or docker exec), can you check if those containers have external network access?

and if not, please take a look at /etc/resolv.conf.

@jwhonce this is starting to sound like the DNS problem you had, did you find a resolution?

**Comment by grdryn** [comment] 2015-07-28 12:00
@bparees Hi, thanks again for your help. To try to give as much information as possible, I've now created a clean VM, and run v1.0.1, checked the container connectivity, the cleaned up, run v.1.0.2 and checked again.

v1.0.1 can curl external addresses, but v1.0.2 cannot. Here's the /etc/resolv.conf from a container in v1.0.2:

```
[vagrant@ose3 1.0.2]$ sudo docker exec -it k8s_ruby-helloworld-database.ecc5d29b_database-1-futah_test_53bd4fd7-3516-11e5-82e7-080027893417_1968d5d8 bash
bash-4.2$ cat /etc/resolv.conf 
nameserver 10.0.2.15
nameserver 10.0.2.3
search test.svc.cluster.local svc.cluster.local cluster.local redhat.com
options ndots:5
```

This is almost the same as the /etc/resolv.conf, except it has the added `options ndots:5` at the end.

Here's the /etc/resolv.conf from the VM:
```
[vagrant@ose3 1.0.1]$ cat /etc/resolv.conf 
# Generated by NetworkManager
search redhat.com feedhenry.me
nameserver 10.0.2.3
```

I can curl the running openshift just fine from within the container:

```
bash-4.2$ curl -k https://192.168.33.12:8443
{
  "paths": [
    "/api",
    "/api/v1beta3",
    "/api/v1",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/ready",
    "/osapi",
    "/osapi/v1beta3",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}
```

But I can't curl github or google or anything else:

```
bash-4.2$ curl https://github.com
curl: (7) Failed connect to github.com:443; Connection refused

bash-4.2$ curl -k https://google.com
curl: (7) Failed connect to google.com:443; Connection refused
```

It appears to be the second nameserver (10.0.2.3, which is the one that the VM has, it doesn't have 10.0.2.15) in the resolv.conf file that resolves github.com:
```
bash-4.2$ dig @10.0.2.15 github.com A

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.2 <<>> @10.0.2.15 github.com A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 22794
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;github.com.                    IN      A

;; Query time: 0 msec
;; SERVER: 10.0.2.15#53(10.0.2.15)
;; WHEN: Tue Jul 28 10:52:10 UTC 2015
;; MSG SIZE  rcvd: 28

bash-4.2$ dig @10.0.2.3 github.com A 

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.2 <<>> @10.0.2.3 github.com A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54062
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             15      IN      A       192.30.252.130

;; Query time: 22 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Tue Jul 28 10:52:22 UTC 2015
;; MSG SIZE  rcvd: 55
```

So external addresses can be looked up with dig, but still get the 'connection refused' error.

**Comment by bparees** [comment] 2015-07-28 14:07
@ramr @knobunc @rajatchopra possible SDN issue here?

**Comment by knobunc** [comment] 2015-07-28 18:09
What does the routing table (route -n) inside the container show?

**Comment by grdryn** [comment] 2015-07-28 20:32
@knobunc `route` isn't installed in these containers, and I don't seem to be able to switch to root user to install it (and passwd isn't installed, so I can't reset root pass). `routel` is installed, does that give the same info (I've never used either)?

Here's what `routel` prints:
```
[vagrant@ose3 1.0.2]$ sudo docker exec -it k8s_ruby-helloworld-database.28f0d1ae_database-1-jqwj6_test_26c5c265-3564-11e5-9df7-080027893417_23b19229 bash
bash-4.2$ routel
         target            gateway          source    proto    scope    dev tbl
        default        172.17.42.1                                     eth0 
    172.17.0.0/ 16                      172.17.0.6   kernel     link   eth0 
      127.0.0.0          broadcast       127.0.0.1   kernel     link     lo local
     127.0.0.0/ 8            local       127.0.0.1   kernel     host     lo local
      127.0.0.1              local       127.0.0.1   kernel     host     lo local
127.255.255.255          broadcast       127.0.0.1   kernel     link     lo local
     172.17.0.0          broadcast      172.17.0.6   kernel     link   eth0 local
     172.17.0.6              local      172.17.0.6   kernel     host   eth0 local
 172.17.255.255          broadcast      172.17.0.6   kernel     link   eth0 local
        fe80::/ 64                                   kernel            eth0 
        default        unreachable                   kernel              lo unspec
            ::1              local                     none              lo local
fe80::42:acff:fe11:6              local                     none              lo local
        ff00::/ 8                                                      eth0 local
        default        unreachable                   kernel              lo unspec
```

Thanks for any insights that you can provide!

**Comment by knobunc** [comment] 2015-07-29 12:52
Huh, I never new about the routel command... interesting. Well found!  What does "ip a" and "ip route" show from both inside and outside the container?  Also, can you give me the output from:
  iptables -L
  iptables -L -t nat
  sysctl net.ipv4.ip_forward
(from the host, outside the container)

**Comment by grdryn** [comment] 2015-07-30 14:25
@knobunc I just found that routel command while looking for route...I had never used either of them! :)

I've now moved on to a RHEL 7.1 VM, instead of a CentOS one, with the same issue. Here's the info that you've asked for:

Inside the container:
```
bash-4.2$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
15: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:06 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.6/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:6/64 scope link 
       valid_lft forever preferred_lft forever


bash-4.2$ ip route
default via 172.17.42.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.6
```

Outside the container:
```
[root@ose3 origin-1.0.3]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:fe:50:88 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 78423sec preferred_lft 78423sec
    inet6 fe80::a00:27ff:fefe:5088/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:25:73:df brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.12/24 brd 192.168.33.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe25:73df/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link 
       valid_lft forever preferred_lft forever
8: veth57768c4: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP 
    link/ether 06:13:d1:8a:92:5d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::413:d1ff:fe8a:925d/64 scope link 
       valid_lft forever preferred_lft forever
16: vethe52aa2e: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP 
    link/ether 36:24:ae:64:9c:7a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3424:aeff:fe64:9c7a/64 scope link 
       valid_lft forever preferred_lft forever


[root@ose3 origin-1.0.3]# ip route
default via 10.0.2.2 dev enp0s3  proto static  metric 100 
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15  metric 100 
169.254.0.0/16 dev enp0s8  scope link  metric 1003 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1 
192.168.33.0/24 dev enp0s8  proto kernel  scope link  src 192.168.33.12 


[root@ose3 origin-1.0.3]# sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         


[root@ose3 origin-1.0.3]# sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-PORTALS-CONTAINER  all  --  anywhere             anywhere             /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
KUBE-NODEPORT-CONTAINER  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-PORTALS-HOST  all  --  anywhere             anywhere             /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
KUBE-NODEPORT-HOST  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain KUBE-NODEPORT-CONTAINER (1 references)
target     prot opt source               destination         

Chain KUBE-NODEPORT-HOST (1 references)
target     prot opt source               destination         

Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             172.30.0.1           /* default/kubernetes: */ tcp dpt:https redir ports 40004
REDIRECT   tcp  --  anywhere             172.30.188.15        /* default/docker-registry:5000-tcp */ tcp dpt:commplex-main redir ports 35661
REDIRECT   tcp  --  anywhere             172.30.48.77         /* test/frontend:web */ tcp dpt:postgres redir ports 34539
REDIRECT   tcp  --  anywhere             172.30.92.23         /* test/database:db */ tcp dpt:sgi-arrayd redir ports 55622

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             172.30.0.1           /* default/kubernetes: */ tcp dpt:https to:10.0.2.15:40004
DNAT       tcp  --  anywhere             172.30.188.15        /* default/docker-registry:5000-tcp */ tcp dpt:commplex-main to:10.0.2.15:35661
DNAT       tcp  --  anywhere             172.30.48.77         /* test/frontend:web */ tcp dpt:postgres to:10.0.2.15:34539
DNAT       tcp  --  anywhere             172.30.92.23         /* test/database:db */ tcp dpt:sgi-arrayd to:10.0.2.15:55622


[root@ose3 origin-1.0.3]# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

**Comment by grdryn** [comment] 2015-07-30 14:27
I've just tried v1.0.4, and this issue still occurs.

For reference, here's what those ip commands show in a centos container that I've run independently on the same vm:

```
[root@8c6b3245b25a /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
33: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:0f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.15/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:f/64 scope link 
       valid_lft forever preferred_lft forever


[root@8c6b3245b25a /]# ip route
default via 172.17.42.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.15
```

**Comment by waynedovey** [comment] 2015-08-25 00:33
Hello All, what's the latest on this bug? It's a bit of a show stopper? Do you have any suggested workarounds please?

**Comment by rajatchopra** [comment] 2015-08-25 01:47
The inside of the container looks okay. You may want to double check by
ping on an IP address (say Google.com).
If the ping to an external IP address did not work then it's an sdn issue.
Could you print the output of this command from the host:
ovs-ofctl -O OpenFlow13 dump-flows br0

/Rajat

**Comment by nak3** [comment] 2015-08-26 03:02
@grdryn ran OpenShift as standalone mode, so I think it is not related to SDN.
Also I heard that @waynedovey hit same issue with cluster mode, but he could do `git clone <SAME_GIT_URL>` from another container.

Then, the strangest thing is that this error was disappeared after @waynedovey downgraded to OSEv3.0.0.1 from v3.0.1.0.
Additionally, I tested with @grdryn's close environment(CentOS Linux release 7.1.1503/docker-1.7.1-108.el7.centos.x86_64/openshift v1.0.4-466-g2424366), but it worked without any problem.

This issue is really strange and hard to debug.

@bparees
Can you add more debug option to the S2I code? For example, we can add `GIT_CURL_VERBOSE=1` like:

`GIT_CURL_VERBOSE=1  git clone <GIT_URL>`

**Comment by bparees** [comment] 2015-08-26 03:41
@nak3 it might be faster to just create a custom builder image that does the clone with any debug you want.  updating s2i and then rebasing openshift is gonna take a couple days and i have a number of other items on my plate right now.

**Comment by bparees** [comment] 2015-08-26 03:43
> Also I heard that @waynedovey hit same issue with cluster mode, but he could do git clone <SAME_GIT_URL> from another container.

another container running in k8s, or a container run manually via docker run?

**Comment by nak3** [comment] 2015-08-26 04:00
> another container running in k8s, or a container run manually via docker run?

I asked this, so it was a container ran manually via docker run.

~~~
# docker run -i -t rhel7/rhel-tools /bin/bash
# git clone <GIT_URL>
~~~

**Comment by nak3** [comment] 2015-08-26 04:01
@bparees 

> @nak3 it might be faster to just create a custom builder image that does the clone with any debug you want. updating s2i and then rebasing openshift is gonna take a couple days and i have a number of other items on my plate right now.

OK, I see. We try it.

**Comment by nak3** [comment] 2015-08-27 15:28
@grdryn

Could you please test with this sample app and custom-builder? You can run by:

~~~
oc new-app --file=https://gist.githubusercontent.com/nak3/cddfcec4027c1c720a88/raw/f6707c244e3e4daed1052b7a0b78942f80cfa97b/builder-gitclone-test.json -l app=gitclone
~~~
And please check build-log by `oc build-log `. 

This will not build any app, but it will test only `git clone`. Please check the [source](https://github.com/nak3/custom-builder-for-test/tree/master/custom-builder-gitclone)


**NOTE** After the test, you can delete by
~~~
oc delete all -l app=gitclone
~~~

**Comment by nak3** [comment] 2015-08-30 10:15
I updated more sophisticated builder to debug.

https://github.com/nak3/custom-builder-for-test/tree/master/custom-builder-debug

@grdryn Please use this one, if you can.

```
oc create -f https://raw.githubusercontent.com/nak3/custom-builder-for-test/master/custom-builder-debug/assets/ruby-hello-world.json
```

**Comment by grdryn** [comment] 2015-08-30 17:47
@nak3 I'll try to find time to try that this week, thanks :)

**Comment by eiktyrner** [comment] 2015-09-02 15:23
I've just started testing this 5 minutes ago and I ran into similar problems. For me it turned out that it couldn't connect to the docker registry. Maybe you've already confirmed this but otherwise try running

       $ openshift admin registry

**Comment by nak3** [comment] 2015-10-15 03:42
FYI: we resolve this issue on our environment. The root cause of this issue was DNS setting.I wrote the KCS, please refer https://access.redhat.com/solutions/1990683 

@grdryn Your guess (`ndots:5`) in https://github.com/openshift/origin/issues/3820#issuecomment-125574546 was correct. The reason why we couldn't confirm the root cause is `dig` and `nslookup` behavior was different. `dig` could work with `ndots:5` by using wrong DNS setting, but `nslookup` couldn't. And `nslookup` revealed the issue.

**Comment by ibotty** [comment] 2015-12-23 12:15
@nak3, can you please copy the gist of the solution here?

**Comment by nak3** [comment] 2015-12-28 09:41
The solution is setup of DNS.
@ibotty 
If your OpenShift host is xxx.example.com, then setup DNS as

`*.clooudapps.example.com 192.168.133.10`

Do ***NOT*** set as

`*.example.com 192.168.133.10`

Also, Do ***NOT*** add search path clooudapps.example.com in your `/etc/resolv.conf`.

`search example.com clooudapps.example.com`

The doc of this part might help you - https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html#debugging-pod-egress

**Comment by ibotty** [comment] 2016-01-06 09:16
Thank you. I have a different issue, unfortunately.

**Comment by smarterclayton** [comment] 2017-01-23 04:04
Closing due to age.

**Closed by smarterclayton** 2017-01-23 04:04 UTC
Labels: component/networking, priority/P2

**Comment by micheleberg** [comment] 2019-10-10 15:38
When I had this same error, it turned out that my Secret Key in OpenShift didn't match the deploy key I'd created in github.  As soon as I fixed that, it was fine.
