### ISSUE TITLE
oc cluster up: Error: ports in use: [80 443 8443 10250 53 8053]

### ISSUE THREAD

**Issue by MikeDepies** [openshift/origin#19084] opened 2018-03-24 04:17 UTC
I have a physical server on site that I've attempted to install openshift on. It's running ontop of vmware in a centos VM. 

I followed Grant Shipley's instructions and used his centos github repo. I now have openshift installed but am unable to get 'oc cluster up' to work. 

##### Version
[root@localhost ~]# oc version
oc v3.7.1+282e43f-42
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console.10.10.80.90:8443
openshift v3.7.1+282e43f-42
kubernetes v1.7.6+a08f5eeb62

1. oc cluster up

##### Current Result
Starting OpenShift using openshift/origin:v3.7.1 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.7.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [80 443 8443 10250 53 8053]

##### Expected Result
a successful oc start

**Comment by mfojtik** [comment] 2018-03-26 10:42
@MikeDepies are those ports available in that VM?

**Comment by jwforres** [comment] 2018-03-27 15:06
@openshift/sig-master

**Comment by muheric** [comment] 2018-05-29 21:41
Hello guys,

Still I am not able to fix this problem of ports, when I perform "OC CLUSTER UP" I get the error 

-- Checking for available ports ... FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [8443 10250 53 8053]

How to get rid of it? 

Thanks for your help

**Comment by akram** [comment] 2018-06-04 13:45
@coreydaley #11600 ?

**Comment by mirekphd** [comment] 2018-06-12 14:37
In my case OpenShift's port 8443 was taken as a result of previous SSL port forwardings, which left over a running sshd daemon on that port. The bug seems to affect a wide range of OpehShift versions: I reproduced it for precompiled oc builds v3.7.2 to v3.9.0 (with corresponding Docker Hub imagers of openshift/origin) .

The workaround is to find the PID of the process using this port and kill the process:
```sh
# Release the default OpenShift port (8443) if used by another process (Error: ports in use: [8443]):
sudo yum install psmisc
fuser -v 8443/tcp
kill <PID returned by fuser>
oc cluster up
```

**Comment by malmo1** [comment] 2018-06-13 04:51
The openshift version, I am using is 

sudo openshift version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

and when I try to start openshift using **sudo openshift start** , i get 

66913 server.go:869] Started kubelet v1.6.1+5115d708d7
I0613 04:42:27.454391   66913 server.go:127] Starting to listen on 0.0.0.0:10250
I0613 04:42:27.457608   66913 server.go:298] Adding debug handlers to kubelet server.
F0613 04:42:27.460157   66913 server.go:138] listen tcp 0.0.0.0:10250: bind: address already in use

when I try to get the oc cluster up, I get the issue of  with the ports

 sudo oc cluster up
Starting OpenShift using openshift/origin:v3.6.1 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [80 443 8443 10250 53 8053]

the fuser -v 8443/tcp does not return anything. so looks like the port are free.
But sudo netstat -pan | grep 8443

LISTEN      2732/openshift
tcp        0           ESTABLISHED 2732/openshift
tcp        0           ESTABLISHED 2732/openshift
tcp        0           ESTABLISHED 2732/openshift
tcp        0           ESTABLISHED 2732/openshift
tcp        0           ESTABLISHED 2732/openshift
tcp        0           ESTABLISHED 2732/openshift
tcp        0          ESTABLISHED 2732/openshift
tcp        0          ESTABLISHED 2732/openshift
tcp        0          ESTABLISHED 2732/openshift
tcp        0          ESTABLISHED 3121/openshift

all of these are associated with the Openshift.

Not sure what is going wrong

**Comment by pmc-sstaehle** [comment] 2018-09-13 12:51
/remove-lifecycle stale

Same here. Running oc cluster up returns the error: error: a port needed by OpenShift is not available
There is no further information which ports is meant by being in use. Has anybody been successful in resolving this issue?

**Comment by tnozicka** [comment] 2018-09-13 13:10
Are you reproducing this with a latest cluster up?

What does `sudo netstat -tulpn` show on your machine?

**Comment by pmc-sstaehle** [comment] 2018-09-13 13:19
@tnozicka, sorry my fault. I discovered that there was a kubernetes cluster set up which i did not know. Just resetted it and the problem is fixed for me.

**Comment by soltysh** [comment] 2018-09-14 10:52
Closing based on previous comment.
/close

**Closed by soltysh** 2018-09-14 10:52 UTC
Labels: kind/question, sig/master

**Comment by hendrata** [comment] 2018-09-19 04:46
you can try this step :
1. **systemctl stop atomic-openshift-node.service**
2. **systemctl stop atomic-openshift-master-controllers.service**
3. **systemctl stop atomic-openshift-master-api.service**

Adn then re-run :
**oc cluster up**

**Comment by hendrata** [comment] 2018-09-19 04:47
You can try this step :
1. **systemctl stop atomic-openshift-node.service**
2. **systemctl stop atomic-openshift-master-controllers.service**
3. **systemctl stop atomic-openshift-master-api.service**

And then re-run :
**oc cluster up**

**Comment by mdditt2000** [comment] 2019-12-17 23:18
Restarted docker

[root@ose-3-11-master openshift-3-11]# oc cluster up
Getting a Docker client ...
Checking if image registry.redhat.io/openshift3/ose-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
**error: a port needed by OpenShift is not available**

[root@ose-3-11-master openshift-3-11]# systemctl restart docker
[root@ose-3-11-master openshift-3-11]# oc cluster up

Now works
