### ISSUE TITLE
oc in windows: cli help wraps awkwardly in default windows console

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#5336] opened 2015-10-22 17:06 UTC
Although you can change the layout of a windows console, the default is 80 chars wide. With this default, the help and examples for most oc cli commands wrap awkwardly (here's part of oc --help):

```
Developer and Administrator Client

This client exposes commands for managing your applications, as well as lower le
vel
tools to interact with each component of your system.

To create a new application, you can use the example app source. Login to your s
erver and then
run new-app:

  $ oc login
  $ oc new-app openshift/ruby-20-centos7~https://github.com/openshift/ruby-hello
-world.git

This will create an application based on the Docker image 'openshift/ruby-20-cen
tos7' that builds
the source code at 'github.com/openshift/ruby-hello-world.git'. A build will sta
rt automatically and
a deployment will start as soon as the build finishes.

Once your application is deployed, use the status, get, and describe commands to
 see more about
the created components:

  $ oc status
  $ oc describe deploymentconfig ruby-hello-world
  $ oc get pods

You'll be able to view the deployed application on the IP and port of the servic
e that new-app
created for you.
```

**Comment by csrwng** [comment] 2015-10-22 17:09
@fabianofranz @jwforres

**Comment by fabianofranz** [comment] 2015-10-22 17:22
@liggitt please tag and assign to me.

**Comment by mkumatag** [comment] 2016-09-08 08:30
Was looking into, help messages are created with raw string literals and printing even the newlines in it which doesn't really supports any escape chars in it.

So I'm wondering what is best solution here?
- Do we need to convert these raw string literals to interpreted string literals
- Or do we have any other solution which will allow us to have newline escape char?

**Comment by fabianofranz** [comment] 2016-09-08 21:11
Note that this doesn't happen only on Windows, it's just worse because the default wide is lower. But if you resize your terminal window on Linux to a smaller size, at some point it becomes reproducible. 

I don't think we would move away from using raw string literals. We should just change how we build them. For example, in the default explain output of `oc`: we should have line breaks where they are really wanted like [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cli.go#L46-L50), but not have it in paragraphs like [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cli.go#L51-L53) to limit the max width we want to use to display long chunks of text. Not that our flags descriptions already do that.

Paragraphs should just be a long string line without additional line breaks, and the terminal would be responsible to wrap it according to the windows size. If we still want to limit the max size to avoid really wide content if your terminal is very large, we should do it globally and dynamically with something that detects the usable screen width and is responsible for wrapping when char width is larger than the max. We did that in past for `rhc`, not sure if it's doable in Go.

**Comment by fabianofranz** [comment] 2016-09-08 21:15
For reference, here's how we did it in `rhc`

https://github.com/openshift/rhc/blob/master/lib/rhc/cli.rb#L16-L24

**Comment by fabianofranz** [comment] 2016-09-08 21:15
@juanvallejo FYI

**Comment by fabianofranz** [comment] 2016-09-08 21:18
Looks doable, there are a few strategies in Go:

https://rosettacode.org/wiki/Terminal_control/Dimensions#Go

**Comment by fabianofranz** [comment] 2016-10-20 18:07
Fixed in https://github.com/openshift/origin/pull/10993

**Closed by fabianofranz** 2016-10-20 18:07 UTC
Labels: area/usability, component/cli, help-wanted, kind/bug, priority/P3
