### ISSUE TITLE
WebUI: Need a way to tell while version of service is running for problem reporting

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#4798] opened 2015-09-25 13:52 UTC
Currently an end user, especially from the Web Console, can't determine what version of the server software they are running. This is useful in scenarios when an end user need to report an issue or when they are trying to understand what features are available. It would be even more useful if that version identifier was a hyperlink to release notes about the release such as OpenShift Enterprise 3.0.2.

**Comment by liggitt** [comment] 2015-09-25 13:53
dupe of https://github.com/openshift/origin/issues/2281

**Closed by liggitt** 2015-09-25 13:53 UTC
