### ISSUE TITLE
[flake] TestImageStreamImportDockerHub SIGSEGV

### ISSUE THREAD

**Issue by dcbw** [openshift/origin#16312] opened 2017-09-12 21:08 UTC
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/16303/test_pull_request_origin_integration/7509/build-log.txt

```
    --- PASS: TestIntegration/TestNewAppListAndSearch (0.54s)
In suite "github.com/openshift/origin/test/integration/runner", test case "TestImageStreamImportDockerHub" failed:
    		=== RUN   TestImageStreamImportDockerHub
    		I0912 20:53:02.116775   30905 credentials.go:55] asked to provide RefreshToken for https://auth.docker.io/token
    		I0912 20:53:02.116810   30905 credentials.go:50] asked to provide Basic credentials for https://auth.docker.io/token
    		--- FAIL: TestImageStreamImportDockerHub (0.37s)
    		panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    			panic: runtime error: invalid memory address or nil pointer dereference
    		[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2fe20e9]
    		
    		goroutine 64 [running]:
    		testing.tRunner.func1(0xc420f21d40)
    			/usr/lib/golang/src/testing/testing.go:622 +0x29d
    		panic(0x4d3c360, 0xcbf0730)
    			/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
    		github.com/openshift/origin/pkg/image/importer.(*ImageStreamImporter).importImages(0xc420f29480, 0x7fe71b553970, 0xc420070e28, 0xcc299c0, 0xc420365f00, 0xc420a4d080, 0xcc8fe80, 0xeb554e8)
    			/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/image/importer/importer.go:181 +0xc89
    		github.com/openshift/origin/pkg/image/importer.(*ImageStreamImporter).Import(0xc420f29480, 0x7fe71b553970, 0xc420070e28, 0xc420a4d080, 0xc420070e28, 0x0)
    			/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/image/importer/importer.go:93 +0xf3
    		github.com/openshift/origin/test/integration.TestImageStreamImportDockerHub.func1(0xc000000000000, 0xc)
    			/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/integration/imageimporter_test.go:819 +0xf5
    		github.com/openshift/origin/test/integration.retryOnErrors(0xc420f21d40, 0xc420f29440, 0x4, 0x4, 0xc4212a5d88, 0x4, 0x4)
    			/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/integration/dockerregistryclient_test.go:57 +0x3c
    		github.com/openshift/origin/test/integration.retryWhenUnreachable(0xc420f21d40, 0xc42003bd88, 0x0, 0x0, 0x0, 0xc420f195a0, 0x0)
    			/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/integration/dockerregistryclient_test.go:82 +0x102
    		github.com/openshift/origin/test/integration.TestImageStreamImportDockerHub(0xc420f21d40)
    			/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/integration/imageimporter_test.go:831 +0x400
    		testing.tRunner(0xc420f21d40, 0x591a938)
    			/usr/lib/golang/src/testing/testing.go:657 +0x96
    		created by testing.(*T).Run
    			/usr/lib/golang/src/testing/testing.go:697 +0x2ca
```

**Comment by bparees** [comment] 2017-09-13 04:53
seen again here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/7533/

**Comment by bparees** [comment] 2017-09-13 04:55
(looks like the same panic nuked 3 different tests in that run)

**Comment by dcbw** [comment] 2017-09-13 13:27
It seems like this flake is killing most of the open PRs...

**Comment by bparees** [comment] 2017-09-13 13:45
this is being tracked (with explanation of the cause) here: https://github.com/openshift/origin/issues/16323

closing this one as a dupe.

**Closed by bparees** 2017-09-13 13:45 UTC
Labels: component/image, kind/test-flake, priority/P1
