### ISSUE TITLE
Extended.deploymentconfigs when run iteratively should immediately start a new deployment [Conformance]

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#9701] opened 2016-07-05 13:55 UTC
```
Stacktrace

/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:181
Expected error:
    <*errors.errorString | 0xc820067f50>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2970/testReport/junit/(root)/Extended/deploymentconfigs_when_run_iteratively_should_immediately_start_a_new_deployment__Conformance_/

**Comment by bparees** [comment] 2016-07-05 17:50
recurred: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2987/consoleFull

**Comment by kargakis** [comment] 2016-07-05 18:56
Dupe of https://github.com/openshift/origin/issues/9681

**Closed by kargakis** 2016-07-05 18:56 UTC
Labels: component/deployments, kind/test-flake
