### ISSUE TITLE
start-build --from-dir --follow doesn't push output until build completes?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15215] opened 2017-07-14 19:25 UTC
```
$ oc start-build --follow --from-dir=../oauth-proxy/ oauth-proxy-binary
Uploading directory "../oauth-proxy" as binary input for the build ...
```

long pause, no output

```
build "oauth-proxy-binary-3" started
Receiving source from STDIN as archive ...
--> FROM openshift/origin-release:golang-1.7
--> COPY . /go/src/github.com/openshift/oauth-proxy
--> RUN cd /go/src/github.com/openshift/oauth-proxy &&     CGO_ENABLED=0 go build -a -tags netgo .
--> ENV "OPENSHIFT_BUILD_NAME"="oauth-proxy-binary-3" "OPENSHIFT_BUILD_NAMESPACE"="myproject"
--> LABEL "io.openshift.build.name"="oauth-proxy-binary-3" "io.openshift.build.namespace"="myproject"
--> Committing changes to myproject/oauth-proxy-binary-3:f54f2759 ...
--> Done
Pushing image 172.30.1.1:5000/myproject/oauth-proxy:binaries ...
Pushed 5/6 layers, 84% complete
Pushed 6/6 layers, 100% complete
Push successful
```

all at once.

**Comment by bparees** [comment] 2017-07-14 19:32
yeah, confirmed.  weirdly doing an `oc logs build/foo -f` in another window streams the logs while the start-build console remains hung until the end.  So something about start-build's handling of binary launches is not attaching to the stream properly, i guess?

**Comment by bparees** [comment] 2017-07-14 20:20
i think this is blocked by https://github.com/kubernetes/kubernetes/issues/44448

Currently instantiatebinary streams both stdin(to send in the binary content) and stdout (because it's required by the aforementioned issue).  

https://github.com/openshift/origin/blob/master/pkg/build/registry/buildconfiginstantiate/rest.go#L249-L257

The streamer won't exit until stdout terminates, which occurs when the build finishes.

If we don't want to be blocked by that issue, we need a streamer that will terminate as soon as stdin is complete and not wait for stdout.  If that's something we think upstream would be amenable to, i'm willing to do it, but otherwise we should wait until https://github.com/kubernetes/kubernetes/issues/44448 is resolved and then just remove the stderr/stdout streams from rest.go.

**Comment by bparees** [comment] 2017-07-14 20:24
or maybe we could hack up a version of ioutil.Discard which implements ReadFrom and immediately returns an EOF.  Not sure the implications of leaving the other end of the stream hanging if we did that, though.

**Comment by bparees** [comment] 2017-07-14 20:50
looks like that won't work because io first tries to use the src as a WriteTo before trying the dest as a ReadFrom, and i guess our src supports WriteTo.

**Comment by soltysh** [comment] 2017-10-13 18:06
Just hit this, until this gets resolved can we inform user about it (a warning at the beginning). I've personally thought that my build got stuck, I didn't hit ctrl+c but checked builds on other console.

**Comment by soltysh** [comment] 2017-10-17 06:49
There's a simple workaround this problem, run the start build command in background and stream logs:
```
oc start-build mybuild --from-dir=. &>/dev/null &
oc logs bc/mybuild -f
```

**Comment by jorgemoralespou** [comment] 2017-11-22 17:40
@bparees Since the blocker was fixed and merged Sept 24th, can we fix this?

**Comment by bparees** [comment] 2017-11-22 19:53
@jorgemoralespou thanks for noticing.  PR opened.

**Comment by jorgemoralespou** [comment] 2017-11-22 20:02
It was @soltysh fault as he gave me a blog mentioning his workaround, and I hated the fact we need to workaround, so looked at it. I love not to write about workarounds and hacks.

**Closed** 2017-12-07 14:06 UTC
Labels: component/build, kind/bug, priority/P2
