### ISSUE TITLE
Build fails with Cannot start container: lstat /dev/dm-15: no such file or directory

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8307] opened 2016-03-30 21:40 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13798/console

to get data out of the etcd dump:

in terminal 1:
```
$ curl https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13798/artifact/origin/artifacts/test-end-to-end-docker/artifacts/etcd_dump.json > etcd_dump.json
$ rm -fr $TMPDIR/openshift-integration
$ godep go run tools/testdebug/load_etcd_dump.go --allow-all=true etcd_dump.json
```

in terminal 2:
```
$ export KUBECONFIG=$TMPDIR/openshift-integration/openshift.local.config/master/admin.kubeconfig

$ oc describe pod ruby-sample-build-1-build -n test
Name:		ruby-sample-build-1-build
Namespace:	test
Node:		ip-172-18-2-11.ec2.internal/172.18.2.11
Start Time:	Wed, 30 Mar 2016 15:36:18 -0400
Labels:		openshift.io/build.name=ruby-sample-build-1
Status:		Failed
IP:		172.17.0.6
Controllers:	<none>
Containers:
  sti-build:
    Container ID:	docker://8949070236d42c410993e7d9a9cd8e490407b5104b17440cd46d35002968d179
    Image:		openshift/origin-sti-builder:7a85866
    Image ID:		docker://ef20bff555edcedb3dabebc5118ac28e50f7916a72d17d79003b8afca0c9f61e
    Port:		
    Args:
      --loglevel=4
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Terminated
      Reason:		ContainerCannotRun
      Message:		lstat /dev/dm-15: no such file or directory
      Exit Code:	-1
      Started:		Wed, 30 Mar 2016 15:36:22 -0400
      Finished:		Wed, 30 Mar 2016 15:36:22 -0400
    Ready:		False
    Restart Count:	0
    Environment Variables:
      BUILD:	{"kind":"Build","apiVersion":"v1","metadata":{"name":"ruby-sample-build-1","namespace":"test","selfLink":"/oapi/v1/namespaces/test/builds/ruby-sample-build-1","uid":"ac6b6395-f6ae-11e5-820a-0e92c2081ecf","resourceVersion":"884","creationTimestamp":"2016-03-30T19:36:18Z","labels":{"buildconfig":"ruby-sample-build","name":"ruby-sample-build","openshift.io/build-config.name":"ruby-sample-build","template":"application-template-stibuild"},"annotations":{"openshift.io/build.number":"1"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/ruby-hello-world.git"},"secrets":null},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"centos/ruby-22-centos7@sha256:990326b8ad8c4ae2619b24d019b7871bb10ab08c41e9d5b19d0b72cb0200e28c"},"env":[{"name":"EXAMPLE","value":"sample-app"}]}},"output":{"to":{"kind":"DockerImage","name":"172.30.48.22:5000/test/origin-ruby-sample:latest"},"pushSecret":{"name":"builder-dockercfg-ocuv8"}},"resources":{},"postCommit":{"args":["bundle","exec","rake","test"]}},"status":{"phase":"New","outputDockerImageReference":"172.30.48.22:5000/test/origin-ruby-sample:latest","config":{"kind":"BuildConfig","namespace":"test","name":"ruby-sample-build"}}}

      BUILD_LOGLEVEL:		4
      SOURCE_REPOSITORY:	https://github.com/openshift/ruby-hello-world.git
      SOURCE_URI:		https://github.com/openshift/ruby-hello-world.git
      ORIGIN_VERSION:		v1.1.5-26-g7a85866
      ALLOWED_UIDS:		1-
      DROP_CAPS:		KILL,MKNOD,SETGID,SETUID,SYS_CHROOT
      PUSH_DOCKERCFG_PATH:	/var/run/secrets/openshift.io/push
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  docker-socket:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/docker.sock
  builder-dockercfg-ocuv8-push:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-dockercfg-ocuv8
  builder-token-ei70u:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-token-ei70u
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  1h		1h		1	{default-scheduler }							Normal		Scheduled	Successfully assigned ruby-sample-build-1-build to ip-172-18-2-11.ec2.internal
  1h		1h		1	{kubelet ip-172-18-2-11.ec2.internal}	spec.containers{sti-build}	Normal		Pulled		Container image "openshift/origin-sti-builder:7a85866" already present on machine
  1h		1h		1	{kubelet ip-172-18-2-11.ec2.internal}	spec.containers{sti-build}	Normal		Created		Created container with docker id 8949070236d4
  1h		1h		1	{kubelet ip-172-18-2-11.ec2.internal}	spec.containers{sti-build}	Warning		Failed		Failed to start container with docker id 8949070236d4 with error: API error (500): Cannot start container 8949070236d42c410993e7d9a9cd8e490407b5104b17440cd46d35002968d179: lstat /dev/dm-15: no such file or directory

  1h	1h	1	{kubelet ip-172-18-2-11.ec2.internal}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "sti-build" with RunContainerError: "runContainer: API error (500): Cannot start container 8949070236d42c410993e7d9a9cd8e490407b5104b17440cd46d35002968d179: lstat /dev/dm-15: no such file or directory\n"
```

**Comment by smarterclayton** [comment] 2016-03-30 22:32
@mrunalp

**Comment by mrunalp** [comment] 2016-03-30 22:52
@rhvgoyal Looks like an issue with device-mapper. Could you take a look?

**Comment by kargakis** [comment] 2016-03-31 12:29
Would be nice to document these steps somewhere

**Comment by rhvgoyal** [comment] 2016-04-01 13:15
Where are the journal logs from the node. I can't seem to find those. Also is this issue reproducible? Looking for some simple steps to reproduce it.

I am wondering if this is some kind of udev race where device node /dev/ has not shown up yet.

**Comment by smarterclayton** [comment] 2016-04-01 15:46
sudo journalctl -eu openshift-node usually.

**Comment by danmcp** [comment] 2016-10-28 21:09
Closing since no one has reported this in a long time.

**Closed by danmcp** 2016-10-28 21:09 UTC
Labels: area/infrastructure, component/build, kind/test-flake, priority/P2
