### ISSUE TITLE
conformance install is solid red in build step

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#20101] opened 2018-06-26 17:20 UTC
Since AWS came back up conformance_install has been red: https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_install

It's failing on messages like this:
```
[openshift/origin-template-service-broker] unable to copy transient context into container: stat images/template-service-broker/go/src/github.com/openshift/origin/_output/local/releases/rpms: no such file or directory
```

**Comment by deads2k** [comment] 2018-06-26 17:23
also 
1. https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_install
2. builds https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_builds
3. E2E https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_end_to_end
4. cluster up https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_clusterup

I probably don't need to list every jenkins job.

@smarterclayton @stevekuznetsov any ideas?

**Comment by stevekuznetsov** [comment] 2018-06-26 22:00
Should be fixed by https://github.com/openshift/imagebuilder/pull/82 once a new AMI is build with that `imagebuilder` code and marked as ready

**Comment by smarterclayton** [comment] 2018-06-27 00:32
Was a regression in imagebuilder.  Fixed, and we need more tests there.



On Jun 26, 2018, at 1:23 PM, David Eads <notifications@github.com> wrote:

also

   1.
   https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_install
   2. builds
   https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_builds
   3. E2E
   https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_end_to_end
   4. cluster up
   https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_clusterup

I probably don't need to list every jenkins job.

@smarterclayton <https://github.com/smarterclayton> @stevekuznetsov
<https://github.com/stevekuznetsov> any ideas?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/20101#issuecomment-400396305>,
or mute the thread

**Closed** 2018-06-27 18:31 UTC
Labels: priority/P0
