### ISSUE TITLE
Audit failures due to no context

### ISSUE THREAD

**Issue by enj** [openshift/origin#17718] opened 2017-12-11 23:43 UTC
```
authn_audit.go:43] failed to create audit event: no context found for request
errors.go:84] failed to create audit event
```

@eparis can provide better logs, but this is all the data I have.

cc @smarterclayton

**Comment by soltysh** [comment] 2017-12-14 08:28
@enj this is not a bug, but a consequence of the avalanche of the problems we've seen during that time. I'm going to close this for now, since I can't figure out what would be the situation when this can actually happen. Feel free to re-open if you don't agree.

**Closed by soltysh** 2017-12-14 08:28 UTC
Labels: priority/P1, sig/master
