### ISSUE TITLE
hack/test-cmd.sh:232: executing 'openshift ex validate node-config /tmp/openshift/test-cmd//openshift.local.config/node-172.18.1.9/node-config.yaml' expecting success and text 'SUCCESS': the output content test failed

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9847] opened 2016-07-14 12:40 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/3337/console
```
FAILURE after 0.668s: hack/test-cmd.sh:232: executing 'openshift ex validate node-config /tmp/openshift/test-cmd//openshift.local.config/node-172.18.1.9/node-config.yaml' expecting success and text 'SUCCESS': the output content test failed
Standard output from the command:
SUCCESS: Validation succeded for file: /tmp/openshift/test-cmd//openshift.local.config/node-172.18.1.9/node-config.yaml
```
Not sure why the failure indicator didn't work here.

@stevekuznetsov

**Comment by liggitt** [comment] 2016-07-14 12:54
dupe of https://github.com/openshift/origin/issues/9840

**Closed by liggitt** 2016-07-14 12:54 UTC
Labels: area/tests, kind/test-flake, priority/P2
