### ISSUE TITLE
problem with oc login

### ISSUE THREAD

**Issue by maxPowelll** [openshift/origin#17776] opened 2017-12-14 09:30 UTC
Hi

when I try to login with oc login I always obatein the same request

Server [https://localhost:8443]: https://github.com/xxxxx/yyyy
error: invalid character '<' looking for beginning of value - verify you have provided the correct host and port and that the server is currently running.
error: invalid character '<' looking for beginning of value

I need help please

Thanks

**Comment by mfojtik** [comment] 2017-12-14 10:26
@maxPowelll can you provide the exact command you use for login? Seems like the server/port is wrong and you are hitting the HTML page.

**Comment by maxPowelll** [comment] 2017-12-14 10:32
Hi

I use simply oc login

C:\Users\tomas.varea>oc login
Server [https://localhost:8443]: https://github.com/maxPowelll/checkmovil
error: invalid character '<' looking for beginning of value - verify you have provided the correct host and port and that the server is currently running.
error: invalid character '<' looking for beginning of value

Thanks

**Comment by jfchevrette** [comment] 2017-12-17 16:08
@maxPowelll the Server parameter has to correspond to your OpenShift API server endpoint. Usually that is 'https://localhost:8443' when connecting to a local cluster provisioned with 'oc cluster up'.

**Comment by abhinav1592** [comment] 2017-12-20 20:18
facing same issue..

**Comment by juanvallejo** [comment] 2018-01-08 16:30
@maxPowelll 

> C:\Users\tomas.varea>oc login
> Server [https://localhost:8443]: https://github.com/maxPowelll/checkmovil

You are providing a github repo as your OpenShift server address, not sure if just a typo in your comment. In any case, like @jfchevrette mentioned, make sure that the server address you specify corresponds to an OpenShift server.

**Comment by sujeshchirackkal** [comment] 2018-01-18 10:18
I had a similar issue for the cluster which I set up locally. 

`oc login https://192.168.99.101:8443 --insecure-skip-tls-verify=true` this worked fine for me where as the error was thrown when I tried `oc login https://192.168.99.101:8443/console --insecure-skip-tls-verify=true` It has to be the exact server address. removing /console did work for me

**Comment by juanvallejo** [comment] 2018-02-06 15:24
Closing as I am assuming the issue is the one described in https://github.com/openshift/origin/issues/17776#issuecomment-356017565

Please re-open if that's not the case.

**Closed by juanvallejo** 2018-02-06 15:24 UTC
Labels: component/cli, kind/question, priority/P2

**Comment by bendavidpaz** [comment] 2018-12-11 23:39
Hm?  The reference to another thread refers to this thread so I am going to mention the same issue here.

/usr/local/bin/oc login https://server.domain.com:8443 -u=**** -p=**** -n=default --insecure-skip-tls-verify
error: invalid character 'T' looking for beginning of value - verify you have provided the correct host and port and that the server is currently running.
error: invalid character 'T' looking for beginning of value

Is there a known solution or cause to this issue,

Please advise where to find the resolution.

**Comment by veterr** [comment] 2020-06-29 17:03
You can also see your correct login command from "Copy login command" menu option in UI. For Openshift 4.2 it is something like - 
oc login --server=https://server.domain.com:8443
