### ISSUE TITLE
router not redeploying on change under specific conditions

### ISSUE THREAD

**Issue by ashcrow** [openshift/origin#2955] opened 2015-06-08 19:15 UTC
While running through [the router section of the beta docs](https://github.com/openshift/training/blob/master/beta-3-setup.md#creating-the-router) a few of ran into a problem with the router not bumping it's version *if* the initial router deployment fails. If the initial router deployment succeeds as expected the issue doesn't seem to occur. I'll do my best to recall from memory the steps that caused the problem. I'll try to get someone else to verify the steps tomorrow morning.

### Scenario 1
1. Have the router fail to deploy at [this point in the directions](https://github.com/openshift/training/blob/master/beta-3-setup.md#creating-the-router)
2. Delete the router service and deploymentConfig
3. Create the router again
4. Note that the the router stays in pending and does not get deployed
5. Check the logs to see that the router wasn't deployed due to the version not being bumped

### Scenario 2
1. Have the router fail to deploy at [this point in the directions](https://github.com/openshift/training/blob/master/beta-3-setup.md#creating-the-router)
2. ```osc edit deploymentConfigs/router``` and fix what caused the failure
3. Save and close the file.
4. Note that the the router stays in pending and does not get deployed
5. Check the logs to see that the router wasn't deployed due to the version not being bumped

**Comment by pweil-** [comment] 2015-06-08 20:13
cc @ironcladlou - looks like maybe a deployment issue here

**Comment by ironcladlou** [comment] 2015-06-09 01:03
What build revision of origin? I don't have issue references handy at the moment but this sounds like a problem fixed last week with deploymentConfig delete and stop issues @abhgupta and I committed.

**Comment by brenton** [comment] 2015-06-09 12:36
If Steve was using beta3 then it's a fairly old version of Origin (from about a month ago or so).  I'd highly recommend trying with beta4 now that it's out if that's an option.  @ashcrow, Any chance you could try again with https://github.com/openshift/training/blob/master/beta-4-setup.md ?

**Comment by ashcrow** [comment] 2015-06-09 12:45
@brenton Yeah I was using beta3. @ljozsa is going to go through again with beta4 and see if he hits the problem there as well. He'll report back to this issue once he gets to the router portion.

**Comment by miminar** [comment] 2015-06-09 12:45
I had the same issue. Will try it with beta4 later this week.

**Comment by ncdc** [comment] 2015-06-09 20:06
@ironcladlou @smarterclayton @danmcp unable to reproduce on master

**Closed** 2015-06-09 20:11 UTC
Labels: component/deployments, kind/bug, priority/P1
