### ISSUE TITLE
No error when fail to get build logs in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5468] opened 2015-10-28 19:21 UTC
For old builds, there is no error when we fail to get the build log. The web console displays an empty log.

/cc @jwforres @benjaminapetersen

**Comment by jwforres** [comment] 2015-10-28 19:26
Second issue is a duplicate of https://github.com/openshift/origin/issues/5456

**Comment by benjaminapetersen** [comment] 2015-11-02 21:29
@jwforres @spadgett I believe this one is done per the above merged PR.

**Comment by jwforres** [comment] 2015-11-02 21:44
@benjaminapetersen nope its still an issue, the websocket isn't returning an error like it should and is allow the connection to be upgraded

**Comment by benjaminapetersen** [comment] 2015-11-02 21:54
aaah. thats right. my bad.  was just looking at tpl and seeing changes already.

**Closed** 2015-11-03 17:03 UTC
Labels: component/web, kind/bug, priority/P2
