### ISSUE TITLE
deploymentconfigs with multiple image change triggers test flake

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#11641] opened 2016-10-28 14:05 UTC
conformance test flake: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/7973/consoleFull#38955804356cbb9a5e4b02b88ae8c2f77

```
[Fail] deploymentconfigs [BeforeEach] with multiple image change triggers [Conformance] should run a successful deployment with a trigger used by different containers 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:223
```

##### Version
oc v1.3.0-rc1+0403599-958-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4

**Comment by kargakis** [comment] 2016-10-28 15:43
```
• Failure in Spec Setup (BeforeEach) [1.631 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:827
  with multiple image change triggers [Conformance] [BeforeEach]
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:327
    should run a successful deployment with a trigger used by different containers
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:326

    Expected error:
        <*errors.StatusError | 0xc8214ac980>: {
            ErrStatus: {
                TypeMeta: {Kind: "Status", APIVersion: "v1"},
                ListMeta: {SelfLink: "", ResourceVersion: ""},
                Status: "Failure",
                Message: "project \"extended-test-cli-deployment-vpf3u-atc1i\" already exists",
                Reason: "AlreadyExists",
                Details: {
                    Name: "extended-test-cli-deployment-vpf3u-atc1i",
                    Group: "",
                    Kind: "project",
                    Causes: nil,
                    RetryAfterSeconds: 0,
                },
                Code: 409,
            },
        }
        project "extended-test-cli-deployment-vpf3u-atc1i" already exists
    not to have occurred

    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:223
```
Dupe of https://github.com/openshift/origin/issues/11557

**Closed** 2016-10-28 15:57 UTC
Labels: kind/test-flake
