### ISSUE TITLE
flake in test/cmd/images: imagestream already exists

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6461] opened 2015-12-22 14:18 UTC
flake on `test/cmd/images` [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8060/console):
```
FAILURE after 10.875s: hack/../test/cmd/images.sh:125: executing 'oc tag mysql:latest tagtest3:latest tagtest4:latest --alias' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: imageStream "tagtest3" already exists
[FAIL] !!!!! Test Failed !!!!
```

**Comment by deads2k** [comment] 2016-01-12 19:16
dupe of https://github.com/openshift/origin/issues/6447

**Closed by deads2k** 2016-01-12 19:16 UTC
Labels: kind/test-flake, priority/P2
