### ISSUE TITLE
Bug with deleting lots of namespaces and then restarting

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4228] opened 2015-08-18 02:53 UTC
Seeing this:

```
0817 22:52:10.746225   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:10.905300   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.045314   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.195400   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.375315   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.545337   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.695276   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.815329   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:11.925373   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.045335   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.165469   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.285890   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.395327   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.515427   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.635354   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
0817 22:52:12.785430   25024 namespace_controller.go:67] namespaces "user18-smoke" cannot be updated: the object has been modified; please app
```

after deleting 50 projects and then restarting the master while deletion was ongoing.

**Comment by smarterclayton** [comment] 2015-08-18 02:55
I was apparently able to wedge the namespace controller.

**Comment by smarterclayton** [comment] 2015-08-18 02:56
Don't seem to be able to recover from this.

**Comment by smarterclayton** [comment] 2015-08-18 02:59
```
Ignoring bootstrap policy file because cluster policy found
0817 22:56:37.040798   25568 ensure.go:74] Added [system:serviceaccount:openshift-infra:build-controller] users to the system:build-controller
0817 22:56:37.086042   25568 ensure.go:74] Added [system:serviceaccount:openshift-infra:deployment-controller] users to the system:deployment-
0817 22:56:37.345800   25568 ensure.go:74] Added [system:serviceaccount:openshift-infra:replication-controller] users to the system:replicatio
0817 22:56:37.346892   25568 start_master.go:382] Using images from "openshift3/ose-<component>:v3.0.1.0"
015/08/17 22:56:37 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
015/08/17 22:56:37 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
0817 22:56:37.448131   25568 run_components.go:164] OpenShift DNS listening at 0.0.0.0:53
0817 22:56:37.448514   25568 start_master.go:396] Master controllers starting (*)
0817 22:56:37.448557   25568 run_components.go:72] Started Service Account Manager
ift Master.
0817 22:56:37.626074   25568 run_components.go:103] Started Service Account Token Manager
0817 22:56:37.626116   25568 run_components.go:122] Started Service Account Pull Secret Controllers
0817 22:56:38.377934   25568 tokens_controller.go:151] Secret "build-controller-token-z5r9r" is forbidden: Unable to create new content in nam
0817 22:56:38.404243   25568 create_dockercfg_secrets.go:108] Secret "build-controller-token-tn08s" is forbidden: Unable to create new content
0817 22:56:38.422087   25568 create_dockercfg_secrets.go:108] Secret "deployment-controller-token-a5r04" is forbidden: Unable to create new co
0817 22:56:38.424920   25568 create_dockercfg_secrets.go:108] Secret "replication-controller-token-jx085" is forbidden: Unable to create new c
0817 22:56:38.430318   25568 tokens_controller.go:151] Secret "deployment-controller-token-a8rm0" is forbidden: Unable to create new content i
0817 22:56:38.440754   25568 tokens_controller.go:151] Secret "replication-controller-token-dwsq1" is forbidden: Unable to create new content 
0817 22:57:07.530073   25568 start_master.go:408] Could not get client for replication controller: Could not get token for openshift-infra/rep
er.service: main process exited, code=exited, status=255/n/a
```

**Comment by smarterclayton** [comment] 2015-08-18 02:59
That's the master dying after 50 seconds or so

**Comment by liggitt** [comment] 2015-08-18 04:19
did you delete the openshift-infra project?

**Comment by liggitt** [comment] 2015-08-18 04:19
not getting a token for one of the infra clients is indicative of that... might be a dupe of https://github.com/openshift/origin/issues/3274

**Comment by smarterclayton** [comment] 2015-08-18 12:11
Yes, but also Kube system.  Wasn't sure whether the lock up was total.  We
should probably for now protect against delete of a white list of projects
and let namespace delete cover them.

On Aug 18, 2015, at 12:19 AM, Jordan Liggitt <notifications@github.com>
wrote:

did you delete the openshift-infra project?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4228#issuecomment-132068804>.

**Comment by liggitt** [comment] 2015-08-18 14:40
The primary issue is our namespace cleaner controller not getting started in the correct order. Once that is started in the first controller group, a couple server restarts would clear the issue.

Agree we want to make it harder to delete default/system/openshift-infra accidentally, but not sure the cleanest way to do so

**Comment by smarterclayton** [comment] 2015-08-18 15:23
I found it useful as an admin to naturally want to oc delete projects
-all.  I at least think of them as "user projects" which we don't have a
clear name for.

On Tue, Aug 18, 2015 at 10:40 AM, Jordan Liggitt <notifications@github.com>
wrote:

> The primary issue is our namespace cleaner controller not getting started
> in the correct order. Once that is started in the first controller group, a
> couple server restarts would clear the issue.
>
> Agree we want to make it harder to delete default/system/openshift-infra
> accidentally, but not sure the cleanest way to do so
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4228#issuecomment-132235181>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment] 2015-08-18 15:34
Closing as dupe of #3274

**Closed by liggitt** 2015-08-18 15:34 UTC
Labels: component/master, kind/bug
