### ISSUE TITLE
odd 'oc' strace

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#6977] opened 2016-02-02 20:31 UTC
In validating master vertical scaling the cluster loader utility repeated calls `oc` command in a tight loop.    The performance of the operation seemed to take a long time and was very noticeable when running hundreds of operations.  I was hoping to run pprof, but it appears it's not enabled on the oc command. 

Further inspection of the strace is odd, because it looks to be doing a bunch of weird things I don't have an explanation for.  On average it can run ~.6<x<.9 seconds per invocation. 

strace of `oc get rc --all-namespaces` https://paste.fedoraproject.org/317659/44444861/
also: https://paste.fedoraproject.org/317656/45444396/

/cc @jeremyeder @abhgupta @tiwillia

**Comment by jeremyeder** [comment] 2016-02-02 20:40
A delay happens every time sched_yield gets called.  Look specifically line 340 of the strace.

![image 6](https://cloud.githubusercontent.com/assets/1919640/12763564/154ecab2-c9c3-11e5-8c02-4967a6a568ad.png)

I think each "step up" corresponds to a sched_yield call, which seems to come from go-dockerclient which gets godep'd into kube.  Why it's getting delayed and actually calling sched_yield...is this a delay in getting a token?

**Comment by timothysc** [comment] 2016-02-02 20:41
Which is slightly insane, b/c that should be nowhere in the call-path from client <> server.

**Comment by jeremyeder** [comment] 2016-02-02 20:44
@elvirkuric I thought everything that pbench did was moved to using "watches" for just this specific reason.

15:12:27.093563 execve("/usr/bin/oc", ["oc", "get", "rc", "--all-namespaces"], [/* 27 vars */]) = 0

Thoughts ?

**Comment by smarterclayton** [comment] 2016-02-03 13:40
Pprof should be enabled on oc the same way it is enabled on masters - OPENSHIFT_PROFILE=cpu - but if you're calling the repeatedly it won't be great.

Hot loop oc calls are dominated by TLS negotiation and elliptic curve in go, and some upstream bugs that require negotiating the available API versions too often.

**Comment by timothysc** [comment] 2016-02-03 17:25
I dumped the profile, and it's dominated by tls.  

```
(pprof) top100  
550ms of 550ms total (  100%)
Showing top 100 nodes out of 190 (cum >= 370ms)
      flat  flat%   sum%        cum   cum%
     110ms 20.00% 20.00%      110ms 20.00%  math/big.divWW
      70ms 12.73% 32.73%      320ms 58.18%  math/big.nat.divLarge
      50ms  9.09% 41.82%       50ms  9.09%  math/big.addMulVVW
      50ms  9.09% 50.91%       50ms  9.09%  math/big.subVV
      40ms  7.27% 58.18%       40ms  7.27%  math/big.mulAddVWW
      20ms  3.64% 61.82%       20ms  3.64%  math/big.shlVU
      10ms  1.82% 63.64%       10ms  1.82%  MCentral_Grow
      10ms  1.82% 65.45%       10ms  1.82%  crypto/cipher.(*gcm).mul
      10ms  1.82% 67.27%       10ms  1.82%  crypto/elliptic.p256ReduceDegree
      10ms  1.82% 69.09%       10ms  1.82%  crypto/x509.ParseCertificate
```

However, there are still the oddities in the strace behavior such as stating all useradd and adduser programs.

**Comment by smarterclayton** [comment] 2016-02-03 17:46
user add/groupadd are coming from fsouza-godockerclient on init.  We should remove that - it's stupid.

**Comment by smarterclayton** [comment] 2016-02-03 17:46
Sorry, it's coming from `docker/pkg/idtools` on init

**Comment by smarterclayton** [comment] 2016-02-03 17:48
The TLS is a dupe of https://github.com/openshift/origin/issues/2304

**Comment by timothysc** [comment] 2016-02-03 17:53
@jeremyeder - 

The hand-shake overhead forces some tooling choices for the long haul.  Converting cluster-loader examples to straight up e2es, unless upstream decides to support a repl like env.

**Comment by smarterclayton** [comment] 2016-02-03 17:54
Just run a local proxy.

On Wed, Feb 3, 2016 at 12:53 PM, Timothy St. Clair <notifications@github.com

**Comment by fabianofranz** [comment] 2016-02-12 23:42
I'm going to propose a lazy init of the [useradd/groupadd checks](https://github.com/docker/docker/blob/master/pkg/idtools/usergroupadd_linux.go#L34-L46) to address that part of the issue.

**Comment by smarterclayton** [comment] 2016-02-20 07:09
https://github.com/cloudflare/go/issues/8 Implies EC optimization a made it to go 1.6, so there's some hope on the horizon

**Comment by smarterclayton** [comment] 2016-03-21 22:59
EC optimization in 1.6 was a massive CPU reduction for our CLI tests, but I don't think it'll help the server tests if we've already fixed connection reuse.

**Comment by liggitt** [comment] 2016-03-22 01:05
It'll help any tests that are simulating lots of clients

**Comment by timothysc** [comment] 2016-03-23 19:50
xref: https://golang.org/doc/go1.6#performance

**Comment by smarterclayton** [comment] 2017-01-23 04:20
Closing due to age.

**Closed by smarterclayton** 2017-01-23 04:20 UTC
Labels: area/performance, component/cli, priority/P2
