### ISSUE TITLE
Flake in new build hook

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7322] opened 2016-02-15 23:10 UTC
```
Running hack/../test/cmd/builds.sh:81: executing 'oc patch bc/busybox -p '{"spec":{"postCommit":{"script":"echo hello $1","args":["world"],"command":null}}}'' expecting success...
FAILURE after 0.402s: hack/../test/cmd/builds.sh:81: executing 'oc patch bc/busybox -p '{"spec":{"postCommit":{"script":"echo hello $1","args":["world"],"command":null}}}'' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: unable to find api field in struct BuildConfig for the json field "metadata"
ok  	github.com/openshift/origin/pkg/cmd/cli/cmd	0.110s
```

**Comment by smarterclayton** [comment] 2016-02-15 23:10
@bparees fyi

**Comment by bparees** [comment] 2016-02-15 23:14
dupe of https://github.com/openshift/origin/issues/6435 ?

**Comment by sosiouxme** [comment] 2016-02-16 19:24
Think I got the same thing here https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11002/consoleFull

**Comment by bparees** [comment] 2016-02-16 19:34
@sosiouxme yes looks the same.  but i'm closing this in deference to #6435.

**Closed** 2016-02-16 19:34 UTC
Labels: area/tests, component/build, kind/test-flake, priority/P2
