### ISSUE TITLE
panic starting shared informer

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15035] opened 2017-07-04 19:15 UTC
```
I0704 14:25:49.346171   23086 start_master.go:764] Started "disruption"
I0704 14:25:49.346182   23086 start_master.go:754] Starting "certificatesigningrequests"
E0704 14:25:49.346204   23086 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:383
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:311
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:130
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/controller.go:192
<autogenerated>:54
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/shared_informer.go:547
/usr/local/go/src/runtime/asm_amd64.s:2086
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x199f0cb]

goroutine 26867 [running]:
panic(0x4671740, 0xc420010150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x4671740, 0xc420010150)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption.(*DisruptionController).getPdbForPod(0xc42acf0000, 0xc4235d1200, 0x17)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:383 +0x5b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption.(*DisruptionController).addPod(0xc42acf0000, 0x4e195c0, 0xc4235d1200)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:311 +0x10f
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption.(*DisruptionController).(github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption.addPod)-fm(0x4e195c0, 0xc4235d1200)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:130 +0x3e
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc4396c2d40, 0xc4396c2d60, 0xc4396c2d70, 0x4e195c0, 0xc4235d1200)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/controller.go:192 +0x49
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc43b302f80, 0x4e195c0, 0xc4235d1200)
	<autogenerated>:54 +0x78
github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc42dbfee70, 0xc4200e4d20)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/shared_informer.go:547 +0x3db
created by github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache.(*sharedIndexInformer).AddEventHandlerWithResyncPeriod
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/cache/shared_informer.go:327 +0x357
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4149/

**Comment by bparees** [comment] 2017-07-04 19:16
possible this is just a test flake (setup issue) but it should be initially triaged as something more significant, i think.

**Comment by smarterclayton** [comment] 2017-07-04 19:33
@mfojtik this could be a memory race (use before initialization goroutine completes), not sure how else this can happen

**Comment by mfojtik** [comment] 2017-07-04 20:16
yeah, seems like the pdbLister is `nil` which is pretty weird... do we wait for the shared informers to be initialized before we start the PDB controllers?

i'm off for vacation tomorrow, so probably won't have traffic to investigate closer.

**Comment by ironcladlou** [comment] 2017-07-11 13:01
A quick scan of the controller code shows the controller accepts a shared informer (a PodInformer) and adds an event handler which relies on state that isn't initialized until *after* the event handler is added. Because the informer lifecycle isn't managed by the controller, it seems the handler could be invoked before the handler's dependent state is initialized.

I wouldn't be surprised if the race exists for other handlers attached to PodInformer or PodDisruptionBudgetInformer.

Will try to get a simple reproducer going today before I'm out on PTO tomorrow.

**Comment by ironcladlou** [comment] 2017-07-11 13:50
Looks like most/all of the controllers are [started and run in goroutines](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L306) prior to [shared informer startup](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L492) (see [the disruption controller](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/policy.go#L41) specifically).

Since NewDisruptionController is executed in a goroutine, it seems at least *possible* that `sharedInformers.Start` could be called between AddEventHandlerWithResyncPeriod and the state assignment. Unlikely, but possible.

**Comment by ironcladlou** [comment] 2017-07-11 15:14
I think there's a subtle but critical flaw in my assessment: the async executions are like `go New().Run()` which means `New` is executed in the calling goroutine and `Run` is executed in a new goroutine. This means the struct should be fully initialized and event handlers added synchronously before informers can be started.

Pretty sure that invalidates my theory.

**Comment by ironcladlou** [comment] 2017-07-11 15:19
The next line of inquiry: is one of the controllers themselves starting a SharedInformer?

**Comment by ironcladlou** [comment] 2017-07-11 19:22
The error seems to imply that a SharedInformer for Pod was started before the call to NewDisruptionController, but so far I can't reason through how that could be possible in either the upstream or origin controller init code. Shifting focus to reproducing.

**Comment by ironcladlou** [comment] 2017-07-11 19:44
It just dawned on me that the original issue was reported in the context of an integration test, which can do [all sorts of potentially hazardous things](https://github.com/openshift/origin/blob/master/test/integration/buildcontroller_test.go#L162) with informers during custom controller bootstrapping logic. The original linked job is long gone, but it seems entirely possible the issue is some custom code in a test's setup as @bparees originally suggested.

**Comment by ironcladlou** [comment] 2017-07-11 20:25
One more note for anybody else picking this up later: based on the reported stack trace, the controller init occurred via [start_master.go](https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/start_master.go#L389), which in the context of an integration test could be invoked via [StartConfiguredMasterWithOptions](https://github.com/openshift/origin/blob/master/test/util/server/server.go#L345), which doesn't provide the caller with any apparent means to influence/inject the Informers created internally within `start_master.go`. So, I'm not even sure yet how any test bootstrapping code might be responsible.

**Comment by mfojtik** [comment] 2017-07-12 07:52
@ironcladlou thanks, I can pick this up and review the integration bootstrapping, it seems like we are just lucky that the tests are running... Also I would not consider this a blocker if this is just an integration test bootstrapping issue. @smarterclayton agree?

**Comment by smarterclayton** [comment] 2017-07-12 16:30
Agree

**Comment by ironcladlou** [comment] 2017-07-17 13:21
Thanks. Wish I had more log context for this one: if anybody notices it again before we solve, please try and get the full logs here.

**Comment by ironcladlou** [comment] 2017-08-25 14:33
The fix for https://github.com/kubernetes/kubernetes/issues/51013 will probably solve this.

**Comment by ironcladlou** [comment] 2017-10-05 18:59
Pretty sure this is resolved by:

https://github.com/kubernetes/kubernetes/pull/44408/commits/e63fcf708d104bf6c69033ca0e2321bd826c2b40
https://github.com/kubernetes/kubernetes/pull/51633 (xref https://github.com/openshift/origin/pull/16617)

Please re-open if it happens again.

**Closed by ironcladlou** 2017-10-05 18:59 UTC
Labels: component/restapi, kind/bug, priority/P2
