### ISSUE TITLE
Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should adopt matching orphans and release non-matching pods

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15408] opened 2017-07-21 16:10 UTC
```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/statefulset.go:214
Jul 21 09:42:08.288: Failed waiting for pods to enter running: timed out waiting for the condition
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:303
```
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1334/

@mfojtik @tnozicka @smarterclayton @gnufied

**Comment by bparees** [comment] 2017-07-23 02:21
seeing this repeatedly in https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1349 which is a merge into 3.6.

**Comment by bparees** [comment] 2017-07-23 13:56
every merge attempt on #15366 has hit this, it seems permanently broken in the 3.6 branch.

**Comment by tnozicka** [comment] 2017-07-24 13:27
```
ul 21 09:52:09.648: INFO: At 2017-07-21 09:32:08 -0400 EDT - event for datadir-ss-0: {persistentvolume-controller } ProvisioningFailed: Failed to provision volume with StorageClass "standard": Failed to get AWS Cloud Provider. GetCloudProvider returned &{0xc420a92000 0xc420cd4cc0 openshift-gce-devel-ci us-central1 us-central1-a [us-central1-f us-central1-b us-central1-c us-central1-a] https://www.googleapis.com/compute/v1/projects/openshift-gce-devel-ci/global/networks/ci-prtest-5a37c28-4591-ocp-network [ci-prtest-5a37c28-4591-ocp] ci-prtest-5a37c28-4591- true 0xc4216c12d0} instead
```
closing as dupe of https://github.com/openshift/origin/issues/15401 They all seem to be because of storage provisioning failed

**Closed by tnozicka** 2017-07-24 13:27 UTC
Labels: component/deployments, kind/test-flake, priority/P0
