### ISSUE TITLE
integration flake:  TestTriggers_imageChange_nonAutomatic

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9246] opened 2016-06-09 11:53 UTC
```
I0608 16:00:43.810862   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:43.810884   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:43.810892   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:44.310872   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:44.310931   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:44.310938   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:44.810826   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:44.810863   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:44.810870   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:45.310885   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:45.310923   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:45.310929   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:45.810863   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:45.810900   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:45.810907   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:46.310828   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:46.310865   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:46.310871   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:46.810854   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:46.810888   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:46.810895   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:47.310865   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:47.310902   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:47.310909   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:47.810850   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:47.810887   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:47.810894   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:48.310891   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:48.310928   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:48.310935   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:48.810862   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:48.810899   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:48.810906   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:49.310850   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:49.310887   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:49.310894   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:49.810863   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:49.810898   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:49.810904   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:50.310855   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:50.310891   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:50.310897   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:50.810844   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:50.810880   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:50.810888   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:51.310855   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:51.310892   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:51.310899   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:51.810862   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:51.810898   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:51.810905   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:52.310862   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:52.310898   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:52.310905   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:52.810862   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:52.810897   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:52.810904   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:53.310864   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:53.310901   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:53.310908   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:53.810849   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:53.810886   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:53.810892   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:54.310863   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:54.310900   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:54.310907   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:54.810863   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:54.810899   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:54.810905   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:55.310863   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:55.310901   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:55.310907   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:55.810866   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:55.810903   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:55.810909   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:56.310864   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:56.310901   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:56.310908   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:56.810865   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:56.810901   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:56.810908   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:57.310846   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:57.310884   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:57.310892   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:57.810861   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:57.810898   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:57.810904   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:58.310865   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:58.310903   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:58.310910   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:58.810861   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:58.810898   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:00:58.810905   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:59.310862   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:59.310899   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:00:59.310906   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:00:59.810853   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:00:59.810891   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:00:59.810898   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:00.310866   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:00.310903   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:00.310909   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:00.810880   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:00.810916   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:00.810923   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:01.310863   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:01.310901   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:01.310909   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:01.810863   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:01.810900   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:01.810907   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:02.310859   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:02.310894   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:02.310900   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:02.810850   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:02.810886   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:02.810893   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:03.310855   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:03.310894   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:03.310900   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:03.810866   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:03.810903   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:03.810911   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:04.310862   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:04.310898   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:04.310905   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:04.810865   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:04.810901   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:04.810908   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:05.310862   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:05.310899   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:05.310907   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:05.810873   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:05.810911   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:05.810917   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:06.310861   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:06.310896   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:06.310902   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:06.810857   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:06.810884   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:06.810891   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:07.310859   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:07.310889   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:07.310895   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:07.810863   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:07.810899   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:07.810906   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:08.310867   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:08.310906   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:08.310913   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:08.810883   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:08.810919   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:08.810926   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:09.310876   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:09.310914   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:09.310920   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:09.810866   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:09.810902   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:09.810908   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:10.310856   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:10.310892   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:10.310899   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:10.810846   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:10.810882   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:10.810889   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:11.310856   29782 scheduler.go:74] DEBUG: scheduler: queue (0):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:11.310883   29782 scheduler.go:79] DEBUG: scheduler: position: 1 3
I0608 16:01:11.310889   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:11.810883   29782 scheduler.go:74] DEBUG: scheduler: queue (1):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:11.810920   29782 scheduler.go:79] DEBUG: scheduler: position: 2 3
I0608 16:01:11.810927   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
I0608 16:01:12.310865   29782 scheduler.go:74] DEBUG: scheduler: queue (2):
 []controller.bucket{controller.bucket{}, controller.bucket{}, controller.bucket{}}
I0608 16:01:12.310901   29782 scheduler.go:79] DEBUG: scheduler: position: 0 3
I0608 16:01:12.310908   29782 scheduler.go:56] DEBUG: scheduler: waiting for limit
--- FAIL: TestTriggers_imageChange_nonAutomatic (35.79s)
	deploy_trigger_test.go:246: Waiting for image stream mapping to be reflected in the image stream status...
	deploy_trigger_test.go:259: Still waiting for latest tag status update on imagestream "test-image-stream"
	deploy_trigger_test.go:281: Waiting for the initial deploymentconfig update in response to the imagestream update
	deploy_trigger_test.go:304: timed out waiting for the image update to happen
FAIL
```

**Comment by kargakis** [comment] 2016-06-09 12:01
Dupe of https://github.com/openshift/origin/issues/9239

**Comment by stevekuznetsov** [comment] 2016-06-09 12:02
I swear to God the search bar is useless

**Closed by kargakis** 2016-06-09 12:01 UTC
Labels: component/deployments, kind/test-flake, priority/P2

**Comment by stevekuznetsov** [comment] 2016-06-09 12:03
![screenshot from 2016-06-09 08-02-49](https://cloud.githubusercontent.com/assets/7328370/15929055/959785e2-2e18-11e6-9f17-ab78f0af9caf.png)
