### ISSUE TITLE
test/cmd/router: error: router could not be created; service account "router" is not allowed to access the host network on nodes

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9161] opened 2016-06-03 14:22 UTC
Output [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1478/testReport/junit/github/com_openshift_origin_test_cmd_router/test_cmd_router_sh_29__executing__oadm_router___dry_run__o_yaml__expecting_failure_and_text__name/):
```
=== BEGIN TEST CASE ===
test/cmd/router.sh:29: executing 'oadm router --dry-run -o yaml' expecting failure and text 'name: router'
FAILURE after 0.451s: test/cmd/router.sh:29: executing 'oadm router --dry-run -o yaml' expecting failure and text 'name: router': the output content test failed
Standard output from the command:
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: router
- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    name: router-router-role
  roleRef:
    kind: ClusterRole
    name: system:router
  subjects:
  - kind: ServiceAccount
    name: router
    namespace: cmd-router
  userNames:
  - system:serviceaccount:cmd-router:router
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      router: router
    name: router
  spec:
    replicas: 1
    selector:
      router: router
    strategy:
      resources: {}
      rollingParams:
        maxSurge: 0
        maxUnavailable: 25%
        updatePercent: -25
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          router: router
      spec:
        containers:
        - env:
          - name: ROUTER_EXTERNAL_HOST_HOSTNAME
          - name: ROUTER_EXTERNAL_HOST_HTTPS_VSERVER
          - name: ROUTER_EXTERNAL_HOST_HTTP_VSERVER
          - name: ROUTER_EXTERNAL_HOST_INSECURE
            value: "false"
          - name: ROUTER_EXTERNAL_HOST_PARTITION_PATH
          - name: ROUTER_EXTERNAL_HOST_PASSWORD
          - name: ROUTER_EXTERNAL_HOST_PRIVKEY
            value: /etc/secret-volume/router.pem
          - name: ROUTER_EXTERNAL_HOST_USERNAME
          - name: ROUTER_SERVICE_HTTPS_PORT
            value: "443"
          - name: ROUTER_SERVICE_HTTP_PORT
            value: "80"
          - name: ROUTER_SERVICE_NAME
            value: router
          - name: ROUTER_SERVICE_NAMESPACE
            value: cmd-router
          - name: ROUTER_SUBDOMAIN
          - name: STATS_PASSWORD
            value: zM4krxmquP
          - name: STATS_PORT
            value: "1936"
          - name: STATS_USERNAME
            value: admin
          image: openshift/origin-haproxy-router:v1.3.0-alpha.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              host: localhost
              path: /healthz
              port: 1936
            initialDelaySeconds: 10
          name: router
          ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 1936
            name: stats
            protocol: TCP
          readinessProbe:
            httpGet:
              host: localhost
              path: /healthz
              port: 1936
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        hostNetwork: true
        securityContext: {}
        serviceAccount: router
        serviceAccountName: router
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      router: router
    name: router
  spec:
    ports:
    - name: 80-tcp
      port: 80
      targetPort: 80
    - name: 443-tcp
      port: 443
      targetPort: 443
    - name: 1936-tcp
      port: 1936
      protocol: TCP
      targetPort: 1936
    selector:
      router: router
  status:
    loadBalancer: {}
kind: List
metadata: {}

Standard error from the command:
error: router could not be created; service account "router" is not allowed to access the host network on nodes, grant access with oadm policy add-scc-to-user hostnetwork -z router
=== END TEST CASE ===
```

Looks like `os::cmd` also mis-characterized the failure condition.

/cc @smarterclayton

**Comment by liggitt** [comment] 2016-06-03 14:28
dupe of #9129?

**Closed** 2016-06-03 14:29 UTC
Labels: area/tests, component/routing, kind/test-flake, priority/P2
