### ISSUE TITLE
triple-click on build commandline in console results in highlighting whole screen

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1630] opened 2015-04-07 20:13 UTC
![screenshot from 2015-04-07 16 13 10](https://cloud.githubusercontent.com/assets/94413/7032504/117d8bea-dd41-11e4-94de-fd43af3374dd.png)

This is a little inconvenient for copy/paste.

**Comment by liggitt** [comment] 2015-05-08 01:50
@spadgett low priority, but there might be something simple we can do (make it block-level, etc)

**Comment by spadgett** [comment] 2015-05-08 20:02
I can't reproduce on Chrome (OS X). @thoraxe can you confirm this is still a problem?

**Comment by thoraxe** [comment] 2015-05-08 21:17
I haven't tried to install the latest builds recently due to installer issues. I'll try again on Monday.

**Comment by thoraxe** [comment] 2015-05-15 21:14
Still haven't gotten to it. Probably another week or so :-/

**Comment by spadgett** [comment] 2015-06-03 21:03
@thoraxe can you verify? We've added a copy-to-clipboard button for this URL, so the UI has changed since your screenshot.

**Comment by liggitt** [comment] 2015-06-03 21:07
closing, reopen if needed :)

**Closed by liggitt** 2015-06-03 21:07 UTC
Labels: component/web, kind/bug, priority/P3

**Comment by thoraxe** [comment] 2015-06-08 15:31
For example, triple-click on a build name highlights an entire line and not just the text
![screenshot from 2015-06-08 11 30 43](https://cloud.githubusercontent.com/assets/94413/8038506/e5143f92-0dd1-11e5-8837-3e2cf82b8253.png)

This is kind of annoying to paste into a CLI in order to perhaps watch the build...

This is really minor but still.

**Comment by liggitt** [comment] 2015-06-08 15:36
What happens when you paste that? Unlikely to fix this.
