### ISSUE TITLE
Extended.deploymentconfigs viewing rollout history should print the rollout history flake

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10989] opened 2016-09-19 11:25 UTC
Seen: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6173/testReport/junit/(root)/Extended/deploymentconfigs_viewing_rollout_history_should_print_the_rollout_history__Conformance_/

```console
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:387
Expected
    <string>: deploymentconfigs "deployment-simple"
    REVISION	STATUS		CAUSE
    1		Complete	caused by a config change
    2		Pending		caused by a config change
to contain substring
    <string>: 2		Complete	caused by a config change
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:386
```

**Comment by kargakis** [comment] 2016-09-19 12:38
Dupe of https://github.com/openshift/origin/issues/10951

**Closed by kargakis** 2016-09-19 12:38 UTC
Labels: area/tests, component/deployments, kind/test-flake, priority/P2
