### ISSUE TITLE
oc logs leaves my bash prompt red

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5184] opened 2015-10-18 20:32 UTC
When I'm tailing logs and something turns the output red, the console stays that way.

@smarterclayton is there some way to use the built-in reset?

**Comment by smarterclayton** [comment] 2015-10-18 21:30
Depends, we can definitely write a reset at the end but we have to be
careful that doesn't mess up scripted interactions

On Oct 18, 2015, at 4:32 PM, David Eads <notifications@github.com> wrote:

When I'm tailing logs and something turns the output red, the console stays
that way.

@smarterclayton <https://github.com/smarterclayton> is there some way to
use the built-in reset?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5184>.

**Comment by fabianofranz** [comment] 2015-11-02 21:45
I've been unable to reproduce this even in situations where it should theoretically happen:

![screenshot from 2015-11-02 16-41-57](https://cloud.githubusercontent.com/assets/158611/10895168/bddc3038-8180-11e5-8869-44c2b40cbd87.png)

![screenshot from 2015-11-02 16-39-19](https://cloud.githubusercontent.com/assets/158611/10895164/b8e6ff68-8180-11e5-85e2-7c2d5e313284.png)

So any additional information would be appreciated - e.g. @deads2k terminal and shell name?

If I still can't reproduce I'll suggest to lower the priority.

**Comment by liggitt** [comment] 2015-11-02 21:48
that's because you are special and have a shell prompt that includes ansi color sequences
us poor folk that have normal boring shell prompts get left with color overrun from the command

**Comment by fabianofranz** [comment] 2015-11-02 21:55
@liggitt I tested with `xterm -cm` and couldn't reproduce anyway, so that seemed not to be the issue. Do you have it happening in your terminal?

**Comment by smarterclayton** [comment] 2015-11-02 22:02
I've seen it happen as jordan noted.

**Comment by fabianofranz** [comment] 2015-11-02 22:14
Can be reproduced with something like

```
PS1='[\u@\h \W]\$ '
```

`xterm -cm` actually eats all ansi sequences which is why it can't be reproduced that way. Working on a fix.

**Comment by fabianofranz** [comment] 2015-11-02 23:53
Here is a proposal, let me know what you think: https://github.com/openshift/origin/pull/5617. I'll open it upstream when we have an agreement.

**Comment by liggitt** [comment] 2015-11-10 14:18
@fabianofranz did you ever see what `ssh`, etc, do with ansi color resetting? If `ssh` doesn't handle it, I don't feel strongly that we should.

**Comment by fabianofranz** [comment] 2015-11-10 20:44
@liggitt Neither `ssh` (from the OpenSSH source) nor `tail.c` (from both GNU and FreeBSD repos) do it. This can be tested easily by running `printf '\x1b[31m'` in a ssh session: after you exit, the console is still red.

**Comment by liggitt** [comment] 2015-11-10 20:51
then we shouldn't either, imo

**Comment by deads2k** [comment] 2015-11-10 21:02
> then we shouldn't either, imo

If a thousand people do a foolish thing....

**Comment by smarterclayton** [comment] 2015-11-10 23:18
Lrn2sttyreset

On Nov 10, 2015, at 1:03 PM, David Eads <notifications@github.com> wrote:

then we shouldn't either, imo

If a thousand people do a foolish thing....

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5184#issuecomment-155564897>.

**Comment by pweil-** [comment] 2017-06-26 09:50
closing due to age

**Closed by pweil-** 2017-06-26 09:50 UTC
Labels: component/cli, component/logging, priority/P2
