### ISSUE TITLE
rsync fails when oc not in "standard" path

### ISSUE THREAD

**Issue by caruccio** [openshift/origin#7787] opened 2016-03-04 12:18 UTC
Trying to rsync files to my pod, but rsync fails complaining it can't exec oc.

Steps to reproduce:

```
$ printenv PATH
~/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:

$ type oc
oc is hashed (/Users/mateus/bin/oc)

$ rsync --version
rsync  version 2.6.9  protocol version 29
Copyright (C) 1996-2006 by Andrew Tridgell, Wayne Davison, and others.
<http://rsync.samba.org/>
Capabilities: 64-bit files, socketpairs, hard links, symlinks, batchfiles,
              inplace, IPv6, 64-bit system inums, 64-bit internal inums

$ oc rsync $PWD/bkp postgresql-1-8yfrd:/tmp
rsync: Failed to exec oc: No such file or directory (2)
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/pipe.c(86) [sender=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
error: exit status 14

$ sudo ln -s /Users/mateus/bin/oc /usr/bin/
Password:

$ oc rsync $PWD/bkp postgresql-1-8yfrd:/tmp
building file list ... done
bkp/
bkp/backup.sql.gz

sent 72421777 bytes  received 48 bytes  96241.63 bytes/sec
total size is 72412814  speedup is 1.00
```

**Comment by csrwng** [comment] 2016-03-04 13:33
@caruccio can you include the output of ```oc version``` and when running rsync (without the /usr/bin symlink) can you specify ```--loglevel=5``` and include the output?

On my Mac, I have oc in a non-standard path and oc rsync works ok. I want to understand what's different in your case.

**Comment by caruccio** [comment] 2016-03-04 13:39
Here it is:

```$ oc version
oc v1.1.3
kubernetes v1.2.0-origin

$ type oc
oc is hashed (/Users/mateus/bin/oc)

$ oc rsync ~/Downloads/bkp postgresql-4-vb0su:/var/lib/pgsql/data/ --loglevel=5
I0304 10:36:03.615350    1202 loader.go:242] Config loaded from file /Users/mateus/.kube/config
I0304 10:36:03.621847    1202 loader.go:242] Config loaded from file /Users/mateus/.kube/config
I0304 10:36:03.626873    1202 util.go:48] Found parent command: oc
I0304 10:36:03.626900    1202 util.go:54] Setting root command to: oc
I0304 10:36:03.626909    1202 util.go:59] The sibling command is: oc rsh
I0304 10:36:03.626931    1202 copyrsync.go:44] Rsh command: oc rsh --loglevel=5
I0304 10:36:03.632656    1202 loader.go:242] Config loaded from file /Users/mateus/.kube/config
I0304 10:36:03.635254    1202 loader.go:242] Config loaded from file /Users/mateus/.kube/config
I0304 10:36:05.647153    1202 copyrsync.go:65] Copying files with rsync
I0304 10:36:05.648961    1202 execlocal.go:19] Local executor running command: rsync -a --blocking-io --omit-dir-times --numeric-ids -v -e oc rsh --loglevel=5 /Users/mateus/Downloads/bkp postgresql-4-vb0su:/var/lib/pgsql/data/
I0304 10:36:05.666314    1202 execlocal.go:26] Error from local command execution: exit status 14
I0304 10:36:05.666363    1202 execremote.go:28] Remote executor running command: rsync --version
I0304 10:36:05.717620    1202 exec.go:182] defaulting container name to postgresql
I0304 10:36:08.040660    1202 util.go:24]
rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
I0304 10:36:08.040737    1202 util.go:25] error: <nil>
rsync: Failed to exec oc: No such file or directory (2)
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/pipe.c(86) [sender=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
F0304 10:36:08.042721    1202 helpers.go:104] error: exit status 14
```

**Comment by csrwng** [comment] 2016-03-04 15:57
Thanks, one more test... if you execute the command from the log:
```
rsync -a --blocking-io --omit-dir-times --numeric-ids -v -e "oc rsh" /Users/mateus/Downloads/bkp postgresql-4-vb0su:/var/lib/pgsql/data/
```

do you get the same error? It seems that somehow your rsync command is not getting the same path as your shell.

**Comment by caruccio** [comment] 2016-03-04 16:45
No, it works as expected.
Also it works as root., same `$PATH`, same `~/bin/oc`.
Don't known if this means something, but I've disabled System Integrity Protection.

**Comment by csrwng** [comment] 2016-08-01 19:01
@caruccio are you still seeing this issue? I've not been able to reproduce locally with any config I've tried. One thing that occurred to me was to look at your rsync binary ... is it a symlink? does it have a suid bit set?

**Comment by caruccio** [comment] 2016-08-01 19:08
Nope, just the plain rsync shipped with MacOS:

$ stat /usr/bin/rsync
16777220 60244249 -rwxr-xr-x 1 root wheel 0 294704 "Jun 17 19:01:00 2016" "Jan 14 00:05:45 2016" "Jan 21 13:10:20 2016" "Jan 14 00:05:45 2016" 4096 336 0x80020 /usr/bin/rsync

Maybe rsync resets PATH?

**Comment by csrwng** [comment] 2016-08-01 19:31
Not that I could tell... I've tried putting the oc binary in different locations and rsync can always find it.

**Comment by csrwng** [comment] 2016-08-04 18:43
@caruccio it occurred to me that maybe the path is not exported ? before running 'oc rsync' can you run 'export PATH'? (I'm running out of ideas ... I definitely cannot reproduce). Or maybe an alias? (just run 'alias' to see if there's one related to oc or rsync defined)

**Comment by csrwng** [comment] 2016-11-03 16:22
Closing due to age, please reopen if new info available.

**Closed by csrwng** 2016-11-03 16:22 UTC
Labels: component/cli, component/internal-tools, priority/P2
