### ISSUE TITLE
Build stuck in status New in openshift v1.4.1

### ISSUE THREAD

**Issue by jppoulain** [openshift/origin#19836] opened 2018-05-24 15:41 UTC
When running a build, the status stays in "New" status. No log is displayed.

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://paas.pleiade.fr:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Select the project to build
2. Click "Build"

##### Current Result
Nothing happens

##### Expected Result
Project should build

##### Additional Information

Attached : 
[ocAdmDiagnostics.txt](https://github.com/openshift/origin/files/2036068/ocAdmDiagnostics.txt)
[ocDescribeBuild.txt](https://github.com/openshift/origin/files/2036069/ocDescribeBuild.txt)

**Comment by jwforres** [comment] 2018-05-24 18:57
@openshift/sig-developer-experience

**Comment by bparees** [comment] 2018-05-24 19:03
claims to be "running for 2s" so i suspect the status is just being updated incorrectly.  we had issues around this before and they've been fixed in more recent origin versions.

can you look at the build pod: `cervintest-28-build`  ?  is it complete?  can you look at its logs?

**Comment by robenj** [comment] 2018-05-24 19:18
I work with jppoulain, the build is always with duration 1 or 2s, even if created many hours before. It state is always new, there is no event, no pod created, no node assignment, no logs in the web console and with command line we have timeout waiting for log. This issue appear 6 days ago and it's for all builds and all projects, we run this version of openshit since one year and it's the first time this append.

**Comment by bparees** [comment] 2018-05-24 19:32
i'd strongly recommend you upgrade as even if there is a bug here, we aren't going to backport a fix to origin 1.4.1 at this point.

That said, the next thing to investigate would be your controller logs, you'll need to up the loglevel to 5 and reproduce the issue so we can see what the build controller is doing w/ respect to the build.

**Comment by robenj** [comment] 2018-05-24 19:45
I don't find how to up the controller log level in the documentation, can you tell me how I can do this

**Comment by bparees** [comment] 2018-05-24 19:48
pass --loglevel=5 to the master process on startup.

**Comment by robenj** [comment] 2018-05-24 20:17
Thanks a lot for your help, controllers restart solve the problem, I don't now what was the problem because we looked controllers log yesterday (with default log level) and we didn't found anything. We will consider upgrade the cluster, You can close this issue.

**Comment by bparees** [comment] 2018-05-24 20:26
glad it's working again, sorry we won't be able to determine why the controllers stopped running.

/close

**Closed by bparees** 2018-05-24 20:26 UTC
Labels: sig/developer-experience
