### ISSUE TITLE
Occasional access denied error after creating project in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6193] opened 2015-12-04 15:03 UTC
On rare occasions, I see an access denied error after creating a project. Going back to the projects list, I can see and select the new project, so the project was created.

@deads2k @liggitt Is the UI navigating to the new project before the user is granted access?

/cc @jwforres

**Comment by liggitt** [comment] 2015-12-04 15:32
does the navigate happen prior to the project request call completing?

**Comment by spadgett** [comment] 2015-12-04 15:42
It happens after project request completes.

https://github.com/openshift/origin/blob/master/assets/app/scripts/controllers/createProject.js#L18-L38

**Comment by spadgett** [comment] 2015-12-04 15:45
For what it's worth, I've only seen this once or twice.

**Comment by deads2k** [comment] 2015-12-04 15:54
There is a policy cache that needs to be updated before the request will succeed.  If the problem is the cache, I can think of three solutions:

 1. Client waits until it has access (super ugly).
 1. ProjectRequest doesn't return for the min of X seconds or the authorizer thinks that the user has rights to the project (moderately ugly)
 1. Authorizer gets a chain that allows a certain number of live re-lookups per user per minute. (not awful, but makes RARs unreliable)

**Comment by spadgett** [comment] 2016-03-09 01:49
Just saw this again. It's still an issue although rare.

/cc @jwforres

**Comment by liggitt** [comment] 2016-06-20 15:22
fixed by https://github.com/openshift/origin/pull/8587

**Closed by liggitt** 2016-06-20 15:22 UTC
Labels: component/auth, kind/bug, priority/P2
