### ISSUE TITLE
oc ex dockerbuild issues tracker

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#8710] opened 2016-05-02 18:37 UTC
@smarterclayton few improvements after playing with dockerbuild on various images:
- We should print the instruction on default loglevel, otherwise you might wait for some time and have no idea what is executed.
- Maybe provide `-t` option to make it compatible with docker build
- I assume the FROM image pulling is muted as well, we should display progress bar or message
- It would be nice if we can mark some steps as parallel :-) (like a special comment in dockerfile saying that we don't have to wait to previous instruction to finish (apply for downloading/installing stuff you don't care about order).
- In the end, it should print the name if the docker image that was build?
- We should error and cancel the build when instruction fail (add `RUN bar` into dockerfile... it will complain about error but happily continue)

**Comment by mfojtik** [comment] 2016-05-02 18:39
@smarterclayton if some of these makes sense, I can help fixing them.

**Comment by smarterclayton** [comment] 2016-05-02 18:54
They do, let's gather some feedback over the next few days and see
what else people have before we go to the next step.

**Comment by vbehar** [comment] 2016-05-03 07:32
Hi, just started playing with it, and noticed that the MAINTAINER instruction is ignored.

**Comment by vbehar** [comment] 2016-05-03 07:36
+1 for printing the instruction at the default level. It's what people are used to see when building images, and it helps to know what is going on.

**Comment by mfojtik** [comment] 2016-05-03 11:53
Another small issue:

```console
[root@localhost test]# oc ex dockerbuild . test
error: API error (500): Error parsing reference: "scratch-nIUg8YGE2B_auGAYso-ZdA==" is not a valid repository/tag
[root@localhost test]# cat Dockerfile
FROM scratch
ADD foo /foo
```

**Comment by smarterclayton** [comment] 2016-05-03 16:55
The issues reported by Gabe include not pulling by default (which may be
ok, since the goal here isn't necessarily to reproduce the docker build
command, but needs to be investigated) and potentially not handling short
names correctly (which again, may be ok because the goal isn't the arg
compatible docker build command)

**Comment by smarterclayton** [comment] 2016-05-03 17:51
- We should error and cancel the build when instruction fail (add
RUN bar into
   dockerfile... it will complain about error but happily continue)

Is not expected, can you submit a fix?

**Comment by smarterclayton** [comment] 2016-05-03 17:53
I have a few more fixes for the other issues.  The goal is not to be a
docker build equivalent - it's merely to provide a test platform for
verifying use cases.  I like parallelization, but we should think about
that later.

**Comment by gabemontero** [comment] 2016-05-06 16:57
BTW, I'm still seeing some issues with building from scratch locally.  After a periodic purge of the images stored in my local docker daemon, I now cannot run build-base-images.

Here's a [gist](https://gist.github.com/gabemontero/87ba425c964893320b5161005f03901f)

Looking at a build running on ci.openshift I have running right now, if it is pre-populating the docker daemon with a set of centos/openshift images, I'm missing it.

**Comment by gabemontero** [comment] 2016-05-06 18:47
After updating build-base-images.sh to add `--loglevel=8` to the `oc ex dockerbuild`, it looked like things choked on finding centos:centos7.

I manually pulled that down, and the re-run of build-base-images.sh was successful.

**Comment by smarterclayton** [comment] 2016-05-06 19:48
Should be fixed in Michal's https://github.com/openshift/origin/pull/8770

**Closed** 2018-04-07 16:51 UTC
Labels: component/cli, kind/enhancement, lifecycle/rotten, priority/P3
