### ISSUE TITLE
TestTriggers_imageChange_nonAutomatic test flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9239] opened 2016-06-09 03:57 UTC
```
--- FAIL: TestTriggers_imageChange_nonAutomatic (35.75s)
	deploy_trigger_test.go:246: Waiting for image stream mapping to be reflected in the image stream status...
	deploy_trigger_test.go:259: Still waiting for latest tag status update on imagestream "test-image-stream"
	deploy_trigger_test.go:281: Waiting for the initial deploymentconfig update in response to the imagestream update
	deploy_trigger_test.go:304: timed out waiting for the image update to happen
FAIL
```

as seen here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1712/console

**Comment by stevekuznetsov** [comment] 2016-06-09 12:04
@mfojtik full debug output is in the other (closed) issue for when you look at this

**Comment by mfojtik** [comment] 2016-06-09 12:05
it is in @kargakis hands now :-)

**Comment by stevekuznetsov** [comment] 2016-06-09 12:06
dupe of https://github.com/openshift/origin/issues/9213

**Closed by stevekuznetsov** 2016-06-09 12:06 UTC
Labels: component/deployments, kind/test-flake, priority/P2
