### ISSUE TITLE
HAProxy Router reboot many times 

### ISSUE THREAD

**Issue by geovanaSouza** [openshift/origin#8921] opened 2016-05-18 15:10 UTC
##### Steps To Reproduce
1. I installed OpenShift Router through the ansible playbook https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_hosted
2. The router restarts several times after that.
3. In the log shows this before restart:

Checking HAProxy /healthz on port 1936 ...
HAProxy port 1936 health check ok : 0 retry attempt(s).
fatal error: concurrent map read and map write

```
goroutine 54 [running]:
runtime.throw(0x38e04e0, 0x21)
        /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8207cf8f0 sp=0xc8207cf8d8
runtime.mapaccess2(0x2820680, 0xc820628840, 0xc820344fb0, 0x20, 0x84f2ee)
        /usr/local/go/src/runtime/hashmap.go:343 +0x5a fp=0xc8207cf938 sp=0xc8207cf8f0
reflect.mapaccess(0x2820680, 0xc820628840, 0xc820344fb0, 0xc820628840)
        /usr/local/go/src/runtime/hashmap.go:993 +0x35 fp=0xc8207cf968 sp=0xc8207cf938
reflect.Value.MapIndex(0x2820680, 0xc820628840, 0x15, 0x2828680, 0xc820344fb0, 0x98, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:1041 +0x14a fp=0xc8207cf9f0 sp=0xc8207cf968
encoding/json.(*mapEncoder).encode(0xc82002c3f0, 0xc820712c60, 0x2820680, 0xc820628840, 0x15, 0x0)
        /usr/local/go/src/encoding/json/encode.go:622 +0x2ec fp=0xc8207cfae0 sp=0xc8207cf9f0
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc820712c60, 0x2820680, 0xc820628840, 0x15, 0xc820628800)
        /usr/local/go/src/encoding/json/encode.go:632 +0x51 fp=0xc8207cfb18 sp=0xc8207cfae0
encoding/json.(*encodeState).reflectValue(0xc820712c60, 0x2820680, 0xc820628840, 0x15)
        /usr/local/go/src/encoding/json/encode.go:301 +0x6b fp=0xc8207cfb48 sp=0xc8207cfb18
encoding/json.(*encodeState).marshal(0xc820712c60, 0x2820680, 0xc820628840, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:274 +0xa9 fp=0xc8207cfb90 sp=0xc8207cfb48
encoding/json.Marshal(0x2820680, 0xc820628840, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:139 +0x84 fp=0xc8207cfbc8 sp=0xc8207cfb90
encoding/json.MarshalIndent(0x2820680, 0xc820628840, 0x0, 0x0, 0x3562cd8, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/encoding/json/encode.go:148 +0x64 fp=0xc8207cfc50 sp=0xc8207cfbc8
github.com/openshift/origin/pkg/router/template.(*templateRouter).writeState(0xc8203bcc30, 0x0, 0x0)
        /go/src/github.com/openshift/origin/pkg/router/template/router.go:245 +0x83 fp=0xc8207cfd68 sp=0xc8207cfc50
github.com/openshift/origin/pkg/router/template.(*templateRouter).commitAndReload(0xc8203bcc30, 0x0, 0x0)
        /go/src/github.com/openshift/origin/pkg/router/template/router.go:226 +0xd1 fp=0xc8207cfdd0 sp=0xc8207cfd68
github.com/openshift/origin/pkg/router/template.(*templateRouter).(github.com/openshift/origin/pkg/router/template.commitAndReload)-fm(0x0, 0x0)
        /go/src/github.com/openshift/origin/pkg/router/template/router.go:157 +0x2e fp=0xc8207cfdf0 sp=0xc8207cfdd0
github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).handleOne(0xc820628750, 0x33272e0, 0xc820628750)
        /go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:49 +0x48 fp=0xc8207cfe28 sp=0xc8207cfdf0
github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).RunUntil.func1()
        /go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:42 +0x6a fp=0xc8207cfe70 sp=0xc8207cfe28
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc82023bf10)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b fp=0xc8207cfea0 sp=0xc8207cfe70
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc82023bf10, 0x0, 0x0, 0xc820461b00)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68 fp=0xc8207cff60 sp=0xc8207cfea0
k8s.io/kubernetes/pkg/util/wait.Until(0xc82023bf10, 0x0, 0xc820461b00)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e fp=0xc8207cff88 sp=0xc8207cff60
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8207cff90 sp=0xc8207cff88
created by github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).RunUntil
        /go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:42 +0x7d

goroutine 1 [select (no cases), 60 minutes]:
github.com/openshift/origin/pkg/cmd/infra/router.(*TemplateRouterOptions).Run(0xc82005b500, 0x0, 0x0)
        /go/src/github.com/openshift/origin/pkg/cmd/infra/router/template.go:203 +0x85e
github.com/openshift/origin/pkg/cmd/infra/router.NewCommandTemplateRouter.func1(0xc82016aa00, 0x5b9a280, 0x0, 0x0)
        /go/src/github.com/openshift/origin/pkg/cmd/infra/router/template.go:111 +0x1ad
github.com/spf13/cobra.(*Command).execute(0xc82016aa00, 0xc82006a140, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc82016aa00, 0xc82016aa00, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x53f
github.com/spf13/cobra.(*Command).Execute(0xc82016aa00, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
main.main()
        /go/src/github.com/openshift/origin/cmd/openshift/openshift.go:27 +0x180

goroutine 17 [syscall, 60 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive, 2 minutes]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5b72140)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 7 [syscall, 10 minutes]:
os/signal.signal_recv(0x7f45d119c050)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 199 [select]:
net/http.(*persistConn).readLoop(0xc8202f00d0)
        /usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 55 [select]:
net/http.(*persistConn).roundTrip(0xc820348750, 0xc8203449f0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8203dc3c0, 0xc820a9ddc0, 0xa, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:320 +0x9bb
k8s.io/kubernetes/pkg/client/transport.(*userAgentRoundTripper).RoundTrip(0xc820665680, 0xc820a9ddc0, 0xc820665680, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:89 +0x130
net/http.send(0xc820a9dce0, 0x7f45d11ec078, 0xc820665680, 0x0, 0x0, 0x0, 0xc8209eb260, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc8206614d0, 0xc820a9dce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc8206614d0, 0xc820a9dce0, 0x3e677f8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc8206614d0, 0xc820a9dce0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:188 +0xff
k8s.io/kubernetes/pkg/client/restclient.(*Request).Watch(0xc8205a03c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/restclient/request.go:649 +0x288
github.com/openshift/origin/pkg/client.(*routes).Watch(0xc8209a89a0, 0x0, 0x0, 0x0, 0x0, 0x7f45d11ebdf0, 0xc8204cf140, 0x7f45d11ebe30, 0xc8204cf160, 0x0, ...)
        /go/src/github.com/openshift/origin/pkg/client/routes.go:92 +0x1b2
github.com/openshift/origin/pkg/router/controller/factory.(*routeLW).Watch(0xc820662a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/openshift/origin/pkg/router/controller/factory/factory.go:236 +0x12f
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc820533a40, 0xc820066e40, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:263 +0xb83
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x2c
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8201e7c80)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8201e7c80, 0x3b9aca00, 0x0, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc8201e7c80, 0x3b9aca00, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x84

goroutine 56 [runnable]:
net/http.(*persistConn).roundTrip(0xc8202f00d0, 0xc8207a9f10, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8203dc3c0, 0xc820a2ea80, 0xa, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:320 +0x9bb
k8s.io/kubernetes/pkg/client/transport.(*userAgentRoundTripper).RoundTrip(0xc820664f40, 0xc820a2ea80, 0xc820664f40, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:89 +0x130
net/http.send(0xc820a2e9a0, 0x7f45d11ec078, 0xc820664f40, 0x0, 0x0, 0x0, 0xc8206b94a0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc8206612c0, 0xc820a2e9a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc8206612c0, 0xc820a2e9a0, 0x3e677f8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc8206612c0, 0xc820a2e9a0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:188 +0xff
k8s.io/kubernetes/pkg/client/restclient.(*Request).Watch(0xc82051ec80, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/restclient/request.go:649 +0x288
k8s.io/kubernetes/pkg/client/unversioned.(*endpoints).Watch(0xc820a2ad20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/endpoints.go:88 +0x1b2
github.com/openshift/origin/pkg/router/controller/factory.(*endpointsLW).Watch(0xc820662ac0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/openshift/origin/pkg/router/controller/factory/factory.go:257 +0x12f
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc820533ae0, 0xc820066e40, 0x0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:263 +0xb83
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x2c
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8201e7ca0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8201e7ca0, 0x3b9aca00, 0x0, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc8201e7ca0, 0x3b9aca00, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x84

goroutine 57 [runnable]:
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8201e7ce0, 0x0, 0x0, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:74 +0x13c
k8s.io/kubernetes/pkg/util/wait.Until(0xc8201e7ce0, 0x0, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/util/wait.Forever(0xc8201e7ce0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:41 +0x37
created by github.com/openshift/origin/pkg/router/controller.(*RouterController).Run
        /go/src/github.com/openshift/origin/pkg/router/controller/controller.go:46 +0x1da

goroutine 58 [runnable]:
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8201e7cf0, 0x0, 0x0, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:74 +0x13c
k8s.io/kubernetes/pkg/util/wait.Until(0xc8201e7cf0, 0x0, 0xc820066e40)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/util/wait.Forever(0xc8201e7cf0, 0x0)
        /go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:41 +0x37
created by github.com/openshift/origin/pkg/router/controller.(*RouterController).Run
        /go/src/github.com/openshift/origin/pkg/router/controller/controller.go:47 +0x239

goroutine 59 [chan receive, 10 minutes]:
github.com/openshift/origin/pkg/util/proc.StartReaper.func1()
        /go/src/github.com/openshift/origin/pkg/util/proc/reaper.go:23 +0x193
created by github.com/openshift/origin/pkg/util/proc.StartReaper
        /go/src/github.com/openshift/origin/pkg/util/proc/reaper.go:35 +0x79

goroutine 60 [select, 60 minutes, locked to thread]:
runtime.gopark(0x3e67cf8, 0xc820025f28, 0x3573d80, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820025f28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820025f28)
        /usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 177 [IO wait]:
net.runtime_pollWait(0x7f45d111f570, 0x72, 0xc820718000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82051a610, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82051a610, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82051a5b0, 0xc820718000, 0x8000, 0x8000, 0x0, 0x7f45d119c028, 0xc82006a080)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820080550, 0xc820718000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8209bc2d0, 0x7f45d11ec618, 0xc820080550, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820642c00, 0x3e67e17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820642c00, 0xc820a04000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7f45d1169e80, 0xc820642c00, 0xc8203487b8, 0xc820a04000, 0x1000, 0x1000, 0x405963, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8209be280, 0xc820a04000, 0x1000, 0x1000, 0xc8207cdd0d, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8208e02a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8208e02a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820348750)
        /usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 242 [select]:
net/http.(*persistConn).writeLoop(0xc820348750)
        /usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 200 [select]:
net/http.(*persistConn).writeLoop(0xc8202f00d0)
        /usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:854 +0x10cb
```

##### Version
openshift version
openshift v1.1.6
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

oc version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

Version Imager Router:
Image: openshift/origin-haproxy-router:v1.1.6

**Comment by Miciah** [comment] 2016-05-18 20:24
This looks like a duplicate of https://github.com/openshift/origin/issues/8825.

**Comment by knobunc** [comment] 2016-05-19 12:48
This is a duplicate of #8825 and a PR has been merged to resolve it.  Thanks.

**Closed by knobunc** 2016-05-19 12:48 UTC
Labels: component/routing, kind/question, priority/P2
