### ISSUE TITLE
Travis govet failing on master

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6852] opened 2016-01-27 18:12 UTC
https://travis-ci.org/openshift/origin/builds/105224486

**Comment by smarterclayton** [comment] 2016-01-27 18:12
@stevekuznetsov

**Comment by stevekuznetsov** [comment] 2016-01-27 18:15
`pkg/gitserver` is whitelisted at [this line](https://github.com/openshift/origin/blob/master/hack/verify-govet.sh#L59). Thoughts on why it would intermittently be tested anyway? We've seen one other failure like this on Travis. Have we ever seen it on Jenkins?

**Comment by smarterclayton** [comment] 2016-01-27 18:17
Bash sucking?

**Comment by stevekuznetsov** [comment] 2016-01-27 18:58
Interesting theory, I hadn't considered that.

**Comment by kargakis** [comment] 2016-02-23 13:31
Seeing this every now and then: https://travis-ci.org/openshift/origin/jobs/111182050

**Comment by stevekuznetsov** [comment] 2016-02-24 14:07
Couldn't reproduce, starting work to remove the whitelist which will remove this issue: https://github.com/openshift/origin/pull/7586#issuecomment-188268334

**Comment by stevekuznetsov** [comment] 2016-03-15 13:40
@smarterclayton @kargakis have you seen this lately?

**Comment by kargakis** [comment] 2016-03-15 13:47
nope

**Comment by smarterclayton** [comment] 2016-03-15 13:52
It was probably squirreliness upstream.

**Comment by stevekuznetsov** [comment] 2016-03-15 14:10
@smarterclayton should we close this issue, then?

**Comment by kargakis** [comment] 2016-03-23 15:25
Back from the dead
https://travis-ci.org/openshift/origin/jobs/117978753

**Comment by stevekuznetsov** [comment] 2016-03-23 18:59
@smarterclayton @danmcp can this get a flake tag, please?

**Comment by stevekuznetsov** [comment] 2016-03-23 19:00
@kargakis were any of those files it flagged new in the PR? If they're in a new subdir of the repo, the blacklist won't catch them and the expected behavior is to refactor to remove the shadowing.

**Comment by kargakis** [comment] 2016-03-23 22:29
@stevekuznetsov nope, I didn't touch any of those.

**Comment by stevekuznetsov** [comment] 2016-11-01 15:48
Let's keep this issue open to track this flake. It's on Travis, so it's not a P1 as it doesn't block anything.

**Comment by stevekuznetsov** [comment] 2016-11-01 16:39
This is a test flake but does not occur on Jenkins, so we should not be using this flake to re-trigger Jenkins runs, ergo the tag drop.

**Comment by stevekuznetsov** [comment] 2017-04-08 17:11
It has been fixed.

**Closed by stevekuznetsov** 2017-04-08 17:11 UTC
Labels: area/tests, priority/P2
