### ISSUE TITLE
deploymentconfigs with test deployments [It] should run a deployment to completion and then scale to zero [Conformance]

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9225] opened 2016-06-08 14:32 UTC
```
   8821 Jun 08 08:16:37 ESC[91mESC[1m• Failure [21.385 seconds]ESC[0m
   8822 Jun 08 08:16:37 deploymentconfigs
   8823 Jun 08 08:16:37 ESC[90m/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:213ESC[0m
   8824 Jun 08 08:16:37   with test deployments
   8825 Jun 08 08:16:37   ESC[90m/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:189ESC[0m
   8826 Jun 08 08:16:37     ESC[91mESC[1mshould run a deployment to completion and then scale to zero [Conformance] [It]ESC[0m
   8827 Jun 08 08:16:37     ESC[90m/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:188ESC[0m
   8828 Jun 08 08:16:37 
   8829 Jun 08 08:16:37     ESC[91mExpected
   8830 Jun 08 08:16:37         <string>: --> pre: Running hook pod ...
   8831 Jun 08 08:16:37         test pre hook executed
   8832 Jun 08 08:16:37         --> pre: Success
   8833 Jun 08 08:16:37         --> Scaling deployment-test-1 to 2
   8834 Jun 08 08:16:37         --> Waiting up to 10m0s for pods in deployment deployment-test-1 to become ready
   8835 Jun 08 08:16:37     to contain substring
   8836 Jun 08 08:16:37         <string>: --> SuccessESC[0m
   8837 Jun 08 08:16:37 
   8838 Jun 08 08:16:37     /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:146

  12449 Jun 08 08:29:06 ESC[91mESC[1m[Fail] ESC[0mESC[90mdeploymentconfigs ESC[0mESC[0mwith test deployments ESC[0mESC[91mESC[1m[It] should run a deployment to completion and then scale to zero [Conformance] ESC[0m
  12450 Jun 08 08:29:06 ESC[37m/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:146ESC[0m
```

**Comment by kargakis** [comment] 2016-06-08 14:54
Dupe of https://github.com/openshift/origin/issues/9195

**Closed by kargakis** 2016-06-08 14:54 UTC
Labels: component/deployments, kind/test-flake, priority/P2
