### ISSUE TITLE
Problem oc new-app

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#3783] opened 2015-07-20 09:16 UTC
Hi All,
    Why I get the error "multiple images or templates matched "registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift"  when I try to create a container via new-app?

is this a bug?

[root@ose1 ~]# docker search 'registry.access.redhat.com/jboss'
INDEX        NAME                                                                             DESCRIPTION                STARS     OFFICIAL   AUTOMATED
redhat.com   registry.access.redhat.com/jboss-amq-6-openshift3_beta/amq-openshift             JBoss A-MQ 6.2 OpenShift   0                    
redhat.com   registry.access.redhat.com/jboss-amq-6/amq-openshift                             JBoss A-MQ 6.2 OpenShift   0                    
redhat.com   registry.access.redhat.com/jboss-eap-6-openshift3_beta/eap-openshift             JBoss EAP 6.4 OpenShift    0                    
redhat.com   registry.access.redhat.com/jboss-eap-6/eap-openshift                             JBoss EAP 6.4 OpenShift    0                    
redhat.com   registry.access.redhat.com/jboss-webserver-3-openshift3_beta/tomcat7-openshift   JBoss JWS 3.0 OpenShift    0                    
redhat.com   registry.access.redhat.com/jboss-webserver-3-openshift3_beta/tomcat8-openshift   JBoss JWS 3.0 OpenShift    0                    
redhat.com   registry.access.redhat.com/jboss-webserver-3/tomcat7-openshift                   JBoss JWS 3.0 OpenShift    0                    
redhat.com   registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift                   JBoss JWS 3.0 OpenShift    0                    

[root@ose1 ~]# oc new-app registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift --name=tomcat20  --loglevel=5

I0720 05:12:37.135492   24438 templatelookup.go:35] checking template demo1/registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift
I0720 05:12:37.160711   24438 templatelookup.go:35] checking template openshift/registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift
I0720 05:12:37.161511   24438 componentref.go:260] Errors occurred during resolution: []error{(*errors.errorString)(0xc20837edc0), errors.aggregate{(*errors.errorString)(0xc20837e2f0)}}
I0720 05:12:37.161582   24438 imagelookup.go:48] checking local Docker daemon for "registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift"
I0720 05:12:37.262510   24438 imagelookup.go:260] partial match on "docker.io/tomcat:8.0.23" with 0.750000
I0720 05:12:37.262544   24438 imagelookup.go:260] partial match on "docker.io/tomcat:latest" with 0.500000
I0720 05:12:37.262564   24438 imagelookup.go:149] checking Docker registry for "registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift"
I0720 05:12:37.262588   24438 client.go:228] Getting repository jboss-webserver-3/tomcat8-openshift from {https  <nil> registry.access.redhat.com   }
F0720 05:12:37.273302   24438 newapp.go:88] error: multiple images or templates matched "registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift": 2

But if you execute docker pull, it finds the docker image ...

[root@ose1 ~]# docker pull registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift
Trying to pull repository registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift ...
6b851f2a44a5: Downloading 89.65 MB
65de4a13fc7c: Download complete 
0d963ee49ded: Download complete 
6f8fe9f531a1: Download complete 
d8c884c5a957: Download complete 

Any idea?

**Comment by bparees** [comment] 2015-07-20 20:07
duplicate of https://github.com/openshift/origin/issues/3335

**Closed by bparees** 2015-07-20 20:07 UTC
Labels: component/build

**Comment by rkhshan** [comment] 2018-01-03 20:20
try

$ oc new-app registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat8-openshift

The URL that ur using doesn't seem to be exist.
