### ISSUE TITLE
manifest blob unknown: blob unknown to registry error (again)

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12542] opened 2017-01-18 17:01 UTC
#12537 ran into the manifest blob unknown: blob unknown to registry error again:

this was testing current master + an additional commit which removes  'yum -y install httpd' from test/extended/builds/dockerfile.go to speed things up (https://github.com/jim-minter/origin/tree/jenkinstestfix)

https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/995/consoleFull#-169259343956c60d7be4b02b88ae8c268b

```
  build logs : 2017-01-18T12:39:36.474008000Z Pulling image centos@sha256:c577af3197aacedf79c5a204cd7f493c8e07ffbce7f88f7600bf19c688c38799 ...
2017-01-18T12:39:36.650516000Z Step 1 : FROM centos@sha256:c577af3197aacedf79c5a204cd7f493c8e07ffbce7f88f7600bf19c688c38799
2017-01-18T12:39:36.650843000Z  ---> 67591570dd29
2017-01-18T12:39:36.651058000Z Step 2 : USER 1001
2017-01-18T12:39:40.936912000Z  ---> Running in 20479de09099
2017-01-18T12:39:44.585073000Z  ---> 82b8e35cb1ee
2017-01-18T12:39:45.005057000Z Removing intermediate container 20479de09099
2017-01-18T12:39:45.005310000Z Step 3 : ENV "OPENSHIFT_BUILD_NAME" "centos-1" "OPENSHIFT_BUILD_NAMESPACE" "extended-test-build-dockerfile-env-cs1gt-z1qcz"
2017-01-18T12:39:45.221442000Z  ---> Running in 416a27210f67
2017-01-18T12:39:46.300809000Z  ---> 0ef6e0921778
2017-01-18T12:39:46.719561000Z Removing intermediate container 416a27210f67
2017-01-18T12:39:46.721511000Z Successfully built 0ef6e0921778
2017-01-18T12:39:46.730325000Z Pushing image 172.30.164.197:5000/extended-test-build-dockerfile-env-cs1gt-z1qcz/centos:latest ...
2017-01-18T12:39:47.589026000Z Registry server Address: 
2017-01-18T12:39:47.589274000Z Registry server User Name: serviceaccount
2017-01-18T12:39:47.589489000Z Registry server Email: serviceaccount@example.org
2017-01-18T12:39:47.589706000Z Registry server Password: <<non-empty>>
2017-01-18T12:39:47.589909000Z error: build error: Failed to push image: manifest blob unknown: blob unknown to registry
```

**Comment by mfojtik** [comment] 2017-01-31 16:42
@miminar any update on this? I think there are ~4 BZ reported for this.

**Comment by miminar** [comment] 2017-02-01 09:15
@mfojtik not yet, but it looks grave. Bump priority?

**Comment by legionus** [comment] 2017-02-03 15:57
@miminar @mfojtik The investigation revealed that docker checks whether the digest, but received an error (404) do not trying to upload it to the dockerregistry. 

https://bugzilla.redhat.com/show_bug.cgi?id=1417242 -- I think that this error is quite the same.

**Comment by legionus** [comment] 2017-02-06 11:59
docker client crashes during the upload process. So, not all layers are pushed.
Looks like https://github.com/docker/docker/issues/9132

```
time="2017-02-06T12:32:11.012070591+01:00" level=debug msg="Trying to push 172.30.35.27:5000/extended-test-build-dockerfile-env-jdrxk-9mwc1/centos to http://172.30.35.27:5000 v2" 
time="2017-02-06T12:32:11.015439642+01:00" level=debug msg="Pushing repository: 172.30.35.27:5000/extended-test-build-dockerfile-env-jdrxk-9mwc1/centos:latest" 
time="2017-02-06T12:32:11.018016175+01:00" level=debug msg="Checking for presence of layer sha256:34e7b85d83e48a22bd5dfa2b6b9ee9565b7ef672f09b3d2409c61635f9bca4db (sha256:45a2e645736c4c66ef34acce2407ded21f7a9b231199d3b92d6c9776df264729) in 172.30.35.27:5000/extended-test-build-dockerfile-env-jdrxk-9mwc1/centos" 
time="2017-02-06T12:32:11.026713904+01:00" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2017-02-06T12:32:11.763425147+01:00" level=debug msg="Calling GET /v1.24/containers/json?all=1&limit=0" 
time="2017-02-06T12:32:11.763946111+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:12.282974680+01:00" level=debug msg="Calling GET /v1.24/containers/json?limit=0" 
time="2017-02-06T12:32:12.283119894+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:12.284229947+01:00" level=debug msg="Calling GET /v1.24/containers/json?limit=0" 
time="2017-02-06T12:32:12.284303248+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:12.461029352+01:00" level=debug msg="Calling GET /v1.24/version" 
time="2017-02-06T12:32:12.461152917+01:00" level=debug msg="{Action=version, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:12.765255804+01:00" level=debug msg="Calling GET /v1.24/containers/json?all=1&limit=0" 
time="2017-02-06T12:32:12.765373883+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:12.771826633+01:00" level=debug msg="Checking for presence of layer sha256:34e7b85d83e48a22bd5dfa2b6b9ee9565b7ef672f09b3d2409c61635f9bca4db (sha256:17385548ba54dd00b2b73dc106749019fcc0cc5641317c97766f14647d06ad6e) in 172.30.35.27:5000/extended-test-build-dockerfile-env-jdrxk-9mwc1/centos" 
time="2017-02-06T12:32:13.766793736+01:00" level=debug msg="Calling GET /v1.24/containers/json?all=1&limit=0" 
time="2017-02-06T12:32:13.766915568+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:14.283004038+01:00" level=debug msg="Calling GET /v1.24/containers/json?limit=0" 
time="2017-02-06T12:32:14.283586767+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:14.284603858+01:00" level=debug msg="Calling GET /v1.24/containers/json?limit=0" 
time="2017-02-06T12:32:14.284673892+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
time="2017-02-06T12:32:14.469765072+01:00" level=warning msg="failed to upload schema2 manifest: manifest invalid: manifest invalid - falling back to schema1" 
time="2017-02-06T12:32:14.768305410+01:00" level=debug msg="Calling GET /v1.24/containers/json?all=1&limit=0" 
time="2017-02-06T12:32:14.768446253+01:00" level=debug msg="{Action=json, Username=legion, LoginUID=1000, PID=8847}" 
2017-02-06 12:32:15.511041 I | http: panic serving @: could not find ':' in digest: 
goroutine 485 [running]:
net/http.(*conn).serve.func1(0xc4209ce100)
	/usr/lib/golang/src/net/http/server.go:1491 +0x12a
panic(0x163bc80, 0xc4211ede00)
	/usr/lib/golang/src/runtime/panic.go:458 +0x243
github.com/docker/distribution/digest.Digest.sepIndex(0x0, 0x0, 0xc4216a4b40)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/vendor/src/github.com/docker/distribution/digest/digest.go:135 +0xec
github.com/docker/distribution/digest.Digest.Hex(0x0, 0x0, 0x135, 0x1d1)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/vendor/src/github.com/docker/distribution/digest/digest.go:124 +0x35
github.com/docker/distribution/manifest/schema1.(*configManifestBuilder).Build(0xc42091cd20, 0x7f2070670940, 0xc420d10840, 0x7f2070670940, 0xc420d10840, 0x70, 0x16f4720)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/vendor/src/github.com/docker/distribution/manifest/schema1/config_builder.go:136 +0x2ac
github.com/docker/docker/distribution.manifestFromBuilder(0x220ecc0, 0xc420d10840, 0x2206ec0, 0xc42091cd20, 0xc4214a26f0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/distribution/push_v2.go:261 +0x120
github.com/docker/docker/distribution.(*v2Pusher).pushV2Tag(0xc4209cec00, 0x220ecc0, 0xc420d10840, 0x2212220, 0xc4213e1460, 0xc420878910, 0x47, 0x0, 0x0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/distribution/push_v2.go:216 +0x199a
github.com/docker/docker/distribution.(*v2Pusher).pushV2Repository(0xc4209cec00, 0x220ecc0, 0xc420d10840, 0x0, 0xc4209ce400)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/distribution/push_v2.go:102 +0x5f4
github.com/docker/docker/distribution.(*v2Pusher).Push(0xc4209cec00, 0x220ecc0, 0xc420d10840, 0xc4209ce400, 0x2)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/distribution/push_v2.go:83 +0x33b
github.com/docker/docker/distribution.Push(0x220ecc0, 0xc420d10840, 0x7f20762252e8, 0xc4213e1460, 0xc42152e640, 0xc4211ccd80, 0xc4211cce40)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/distribution/push.go:166 +0x616
github.com/docker/docker/daemon.(*Daemon).PushImage(0xc420383ba0, 0x220ecc0, 0xc420d10840, 0xc4217e996d, 0x47, 0xc4217e99be, 0x6, 0xc420dbf1d0, 0xc420dbf350, 0x21f8100, ...)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/daemon/image_push.go:55 +0x363
github.com/docker/docker/api/server/router/image.(*imageRouter).postImagesPush(0xc4205019c0, 0x220ecc0, 0xc420d10700, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0x0, 0x0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/router/image/image_routes.go:148 +0x55b
github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/docker/docker/api/server/router/image.postImagesPush)-fm(0x220ecc0, 0xc420d10700, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0xc4213e11a0, 0x10)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/router/image/image.go:44 +0x69
github.com/docker/docker/api/server/router.cancellableHandler.func1(0x220ed80, 0xc420dbf1a0, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0x0, 0x0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/router/local.go:84 +0x104
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x220ed80, 0xc420dbf170, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0x4248e8, 0xc4213e0eb0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x73c
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x220ed00, 0xc4200126f8, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0xc4213e0d80, 0xc4213e0c50)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x272
github.com/docker/docker/api/server/middleware.AuditMiddleware.WrapHandler.func1(0x220ed00, 0xc4200126f8, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0x756ea15a6a3515, 0xc420493a10)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/middleware/audit_linux.go:27 +0x9d
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x220ed00, 0xc4200126f8, 0x220b480, 0xc421444750, 0xc421266000, 0xc420dbef00, 0xc420493bb0, 0x8)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x9bf
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x220b480, 0xc421444750, 0xc421266000)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/server.go:146 +0xc5
net/http.HandlerFunc.ServeHTTP(0xc420269720, 0x220b480, 0xc421444750, 0xc421266000)
	/usr/lib/golang/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420465770, 0x220b480, 0xc421444750, 0xc421266000)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/vendor/src/github.com/gorilla/mux/mux.go:98 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4209fe940, 0x220b480, 0xc421444750, 0xc421266000)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/_build/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4203f6980, 0x220b480, 0xc421444750, 0xc421266000)
	/usr/lib/golang/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4209ce100, 0x220d1c0, 0xc420d104c0)
	/usr/lib/golang/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2293 +0x44d
time="2017-02-06T12:32:15.717464216+01:00" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"40c7f6c0197ad850019e7c5deac00e11f38a11709b19046a310bffe6b2841546\", Status:0x1, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc420d3db70)}"
```

**My Docker info:**
```
$ docker version
Client:
 Version:         1.12.2
 API version:     1.24
 Package version: docker-common-1.12.2-5.git8f1975c.fc25.x86_64
 Go version:      go1.7.1
 Git commit:      8f1975c/1.12.2
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.2
 API version:     1.24
 Package version: docker-common-1.12.2-5.git8f1975c.fc25.x86_64
 Go version:      go1.7.1
 Git commit:      8f1975c/1.12.2
 Built:           
 OS/Arch:         linux/amd64
```

**Jenkins uses:**
```
+ vagrant ssh -c 'sudo docker version'
Client:
 Version:         1.12.2-rc2
 API version:     1.24
 Package version: docker-common-1.12.2-5.el7.x86_64
 Go version:      go1.6.2
 Git commit:      19dbe35
 Built:           Mon Oct 17 11:44:51 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.2-rc2
 API version:     1.24
 Package version: docker-common-1.12.2-5.el7.x86_64
 Go version:      go1.6.2
 Git commit:      19dbe35
 Built:           Mon Oct 17 11:44:51 2016
 OS/Arch:         linux/amd64
```

I have not tested the fix: https://github.com/docker/docker/pull/28966

**Comment by legionus** [comment] 2017-02-06 12:06
@jwhonce I have a test that reproduces the problem 100%.

**Comment by miminar** [comment] 2017-02-06 14:42
@legionus This is known (see https://bugzilla.redhat.com/show_bug.cgi?id=1410434). And fixed both in [upstream](https://github.com/docker/docker/issues/28596) and in [rhel](https://github.com/projectatomic/docker/commit/047e51b797564227b0bf26f3aa448f563bea5c71).

**Comment by legionus** [comment] 2017-02-07 11:36
@mfojtik @miminar  So we can close this issue.

**Comment by mfojtik** [comment] 2017-02-07 12:02
@legionus I would leave this open as a tracker for upstream issue.

**Comment by coreydaley** [comment] 2017-02-27 15:50
Still having this issue (https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/949), docker is now version 1.12.6 on the ami (ami-15904d03)

**Comment by miminar** [comment] 2017-08-09 11:15
The upstream and RH issues have been fixed a long time ago. If we see another `blob unknown to registry`, let's open a new issue.

**Closed by miminar** 2017-08-09 11:15 UTC
Labels: component/imageregistry, kind/bug, priority/P2

**Comment by davistran86** [comment] 2017-09-15 10:13
Hi guys, I also got this error today:

> Pushing image docker-registry.default.svc:5000/demo/nodejs:latest ...
> Pushed 0/9 layers, 22% complete
> Pushed 1/9 layers, 21% complete
> Pushed 2/9 layers, 38% complete
> Pushed 3/9 layers, 51% complete
> Pushed 4/9 layers, 62% complete
> Pushed 4/9 layers, 68% complete
> Registry server Address:
> Registry server User Name: serviceaccount
> Registry server Email: serviceaccount@example.org
> Registry server Password: <<non-empty>>
> error: build error: Failed to push image: blob upload unknown

**Comment by YuLimin** [comment] 2021-04-28 09:11
add OCP project name as image name, such as the default project like :

docker-registry.default.svc:5000/default/<yourimagename>:<version>
