### ISSUE TITLE
Cancelling a deployment hung for 2 minutes and then did nothing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9575] opened 2016-06-27 02:08 UTC
Ran oc cluster up, then almost immediately switched to the default project and ran:

```
oc cluster up
oc login -u system:admin
oc project default
oc set env dc/docker-registry REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true
```

The pod was killed but no new pod launched until the next sync window.  So looks like we still have some races.

```
oc status
In project default on server https://10.1.2.2:8443

svc/docker-registry - 172.30.71.66:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:latest
    deployment #2 pending on update
    deployment #1 pending (cancelling) about a minute ago

svc/kubernetes - 172.30.0.1 ports 443, 53->8053, 53->8053

svc/router - 172.30.112.40 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:latest
    deployment #1 deployed about a minute ago - 1 pod

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
○ oc get pods
NAME             READY     STATUS    RESTARTS   AGE
router-1-2kszt   1/1       Running   0          50s
○ oc get rc
NAME                DESIRED   CURRENT   AGE
docker-registry-1   0         0         1m
router-1            1         1         1m
```

@kargakis

**Comment by kargakis** [comment] 2016-06-27 11:20
@smarterclayton can you reproduce this on HEAD? What do you mean by "and then did nothing"? Didn't it start the second deployment after those two minutes? I have been aware of this issue that's why https://github.com/openshift/origin/pull/9327.

Template is updated amid a rollout ->
Old deployment is cancelled by the dc controller -> 
Old deployment is marked as pending by the deployment controller and the old deployer is deleted -> 
Old deployment is resynced in the next interval and transitioned from Pending to Failed due to missing deployer

Deployer pod deletion should requeue the deployment, that's what's added in https://github.com/openshift/origin/pull/9327

**Comment by smarterclayton** [comment] 2016-06-27 13:50
Ok, then good, dupe this on that.

**Closed** 2016-06-30 18:34 UTC
Labels: component/deployments, priority/P1
