### ISSUE TITLE
Old deployment shown in topology view, but not overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5091] opened 2015-10-12 18:53 UTC
We hide replication controllers that have no pods in the overview, but show them in the topology view. This might be confusing for users since it's inconsistent. Also, there could be dozens of old deployments, resulting in a busy graph.

/cc @stefwalter @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment] 2015-10-12 19:06
Here's a screenshot example.  Its a nice purple ferris wheel looking thing. 

![screen shot 2015-10-12 at 3 05 17 pm](https://cloud.githubusercontent.com/assets/280512/10436157/abfcbbc4-70f2-11e5-9676-815f5cc0aaa3.png)

**Comment by liggitt** [comment] 2015-10-12 19:10
it's... beautiful....

**Comment by jwforres** [comment] 2015-10-12 20:05
assigning to myself only because we have to have an owner for anything P2 or above and it wont let me assign it to @stefwalter  ( @danmcp know why this is? )

**Comment by danmcp** [comment] 2015-10-12 20:17
@jwforres @stefwalter Hasn't been added to origin yet.  I can do so on request.

**Comment by stefwalter** [comment] 2015-10-19 09:14
@spadgett Could you provide a full step by step reproducer? I need to be able to get from the state of an empty Vagrant Openshift instance to the state you reported in this bug.

**Comment by liggitt** [comment] 2015-10-19 13:31
pretty sure you can do anything that creates a deployment config (`oc new-app`, or `create from source` in the UI), then repeatedly `Start deployment` from that config to scale down old replication controllers.

**Comment by jwforres** [comment] 2015-10-29 12:53
@stefwalter 

Create the sample app
```
oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-stibuild.json
```
Wait for the first build to finish until you see pods on the overview.  Then go to Browse -> Deployments and click on the "frontend" deployment config (go to the config not the deployment number link).  There should be a "Deploy" button under the Triggers section.  Click that to create a new deployment.  Wait for it to say Deployed in the status in the table below, the button should become enabled again, you can do that a couple times.  Then go back to overview and go to the topology view, should see a bunch of RCs with no pods around the frontend deployment config.

@spadgett just added some filters for deployments to know whether they should be shown on the overview (is it the latest deployment, does it have pods, etc) should help with this.

**Comment by stefwalter** [comment] 2015-11-02 16:39
Just an update, I'm having trouble reproducing this, builds just fail for me on openshift master. Tried a couple times since @jwforres posted the reproducer. Will try to diagnose when I have extra time:

```
[vagrant@openshiftdev origin]$ oc get builds --namespace=5019
NAME                  TYPE      FROM      STATUS                          STARTED   DURATION
ruby-sample-build-1   Source    Git       Failed (ExceededRetryTimeout)             
[vagrant@openshiftdev origin]$ oc build-logs --namespace=5019 ruby-sample-build-1
The pod ruby-sample-build-1-build for build ruby-sample-build-1 could not be found.  Therefore build logs cannot be retrieved.
```

**Closed** 2015-12-01 21:57 UTC
Labels: area/usability, component/web, kind/bug, priority/P2
