### ISSUE TITLE
Provide better loggin in case network scripts are failing.

### ISSUE THREAD

**Issue by smil2k** [openshift/origin#9121] opened 2016-06-01 20:57 UTC
Sometimes I see the pods are fails to terminate for a certain time. In the logs the node says that it had problems with the network. Still in order to be able to properly see what is the problem, I would need to restart the node in debug mode, which is not desired on prod machines.

##### Version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. wait for a teardown / configure error 

##### Current Result

jún 01 22:51:23 bla origin-node[1802]: E0601 22:51:23.990678    1802 kubelet.go:2248] Failed killing the pod "standalone-all-19-deploy": failed to "TeardownNetwork" for "standalone-all-19-deploy_platform" with TeardownNetworkError: "Failed to teardown network for pod \"8e008e66-283a-11e6-ad25-000c298cc5cd\" using network plugins \"redhat/openshift-ovs-subnet\": exit status 1"

##### Expected Result

I would like to see the output of the network plugin in this case. I can see it in case I set the loglevel higher, but no point seeing all the fuzz this level produces just to know why it is failing sometimes.

**Comment by sferich888** [comment] 2016-08-28 20:37
This may be a duplicate of #8450

**Comment by knobunc** [comment] 2016-08-29 14:58
Unfortunately, that error message is generated whenever the netowkring teardown script is called twice, or if the resources were never properly set up.  However, the error itself looks dire, but is harmless.  The root cause of the problem is somewhere else.

https://bugzilla.redhat.com/show_bug.cgi?id=1333393 is tracking the issue.

**Closed by knobunc** 2016-08-29 14:58 UTC
Labels: area/usability, component/networking, priority/P2

**Comment by smil2k** [comment] 2016-08-30 09:13
Thank you, but my point was that the error messages are swallowed which is a terrible practice. The referenced bug does not plan to address this!

Please reopen!

Cheers,

Tamas
