### ISSUE TITLE
Flake in cmd test

### ISSUE THREAD

**Issue by miminar** [openshift/origin#6435] opened 2015-12-21 11:51 UTC
With an error like this:

    Running hack/../test/cmd/builds.sh:81: executing 'oc patch bc/ruby-sample-build -p '{"spec":{"output":{"to":{"name":"origin-ruby-sample:latest"}}}}'' expecting success...
    FAILURE after 0.285s: hack/../test/cmd/builds.sh:81: executing 'oc patch bc/ruby-sample-build -p '{"spec":{"output":{"to":{"name":"origin-ruby-sample:latest"}}}}'' expecting success: the command returned the wrong error code
    There was no output from the command.
    Standard error from the command:
    Error from server: unable to find api field in struct BuildConfig for the json field "metadata"
    [FAIL] !!!!! Test Failed !!!!

Occured in PRs #6335 ([build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8027/consoleFull)), #6409 ([build](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7986/consoleFull)).

**Comment by deads2k** [comment] 2015-12-21 16:23
Does anyone see how this can flake?

https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/third_party/forked/json/fields.go#L33-L57

**Comment by deads2k** [comment] 2015-12-21 16:26
@liggitt @smarterclayton I'm not seeing the potential for inconsistent results.

**Comment by kargakis** [comment] 2015-12-21 17:43
:alien:

**Comment by rhcarvalho** [comment] 2016-01-08 16:16
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8336/console in #6587

**Comment by smarterclayton** [comment] 2016-02-05 23:04
Scary, but have not seen this since then.

**Comment by bparees** [comment] 2016-02-05 23:47
@smarterclayton did you mean to reopen it?

**Comment by smarterclayton** [comment] 2016-02-06 03:10
I saw it had a recent entry and decided to leave it open for a bit
longer.  I want to catalog all the flakes and see what we can do to
make it easier to figure out when flakes are happening and search for
approximate counts.  Failure causes is leaving something to be desired
right now.

**Comment by bparees** [comment] 2016-02-16 19:39
as seen in #7322 this seems to be becoming a popular flake.  @deads2k i'm having a hard time seeing how this is build specific.

W/o knowing much about how patch works, the only suspicious thing I see is that this cache might get corrupt/stale/empty?
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/third_party/forked/json/fields.go#L34

**Comment by smarterclayton** [comment] 2016-02-18 22:29
Happened again today.

**Comment by smarterclayton** [comment] 2016-02-18 22:29
This is almost certainly a serious bug somewhere, moving to p1

**Comment by bparees** [comment] 2016-02-19 21:15
just running patch in a loop i can't make this happen, there must be some additional factors (eg load on etcd causing a timeout somewhere)

**Comment by bparees** [comment] 2016-02-26 20:52
I can't recreate this even when running patch in a loop while running test-cmd against my cluster in the background.  I'm open to other suggestions but at this point i don't have any great ideas.  Perhaps someone more intimate w/ the patch/etcd/storage flows would be better suited to take a look.

**Comment by smarterclayton** [comment] 2016-02-26 21:09
Run the unit tests to saturate CPU.  I don't think test-cmd is CPU bound.

**Comment by smarterclayton** [comment] 2016-02-26 21:10
Or stress -c 4

**Comment by bparees** [comment] 2016-02-26 21:32
nada.  3k successful patch operations while running stress and test-cmd in the background.

**Comment by smarterclayton** [comment] 2016-02-26 22:44
So then is this another sort of flake, not a CPU one?  Such as an etcd timeout?

**Comment by bparees** [comment] 2016-02-26 23:09
it's possible, i'm going to have a hard time causing disk latency on my SSD, so i'll have to move to amazon or something.

**Comment by smarterclayton** [comment] 2016-02-26 23:49
You may be able to simulate network latency with a tool - I've seen
some like that.  I think it's possible to inject arbitrary process
delays as well (force a process to pause for random periods of time on
syscalls)

**Comment by liggitt** [comment] 2016-02-29 17:58
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12027/console

```
FAILURE after 0.858s: hack/../test/cmd/basicresources.sh:119: executing 'oc set probe dc test-deployment-config --liveness --open-tcp=8080' expecting success and text 'updated': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
error: unable to find api field in struct DeploymentConfig for the json field "metadata"
```

**Comment by bparees** [comment] 2016-02-29 18:21
yay. it's not just buildconfig :)

**Comment by smarterclayton** [comment] 2016-03-12 15:38
This is happening on anything using patch, which means it affects a good slice of our commands.  This is P0 because it can result in non-deterministic behavior of admin scripting or tools in production.

**Comment by ncdc** [comment] 2016-03-16 19:31
Moar debugging:

```
E0316 15:31:04.477647   10772 errors.go:63] apiserver received an error that is not an unversioned.Status: unable to find api field in struct BuildConfig for the json field "metadata"
ANDY fields=[]json.field{json.field{name:"kind", nameBytes:[]uint8{0x6b, 0x69, 0x6e, 0x64}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{0, 0}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"apiVersion", nameBytes:[]uint8{0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{0, 1}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"name", nameBytes:[]uint8{0x6e, 0x61, 0x6d, 0x65}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 0}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"generateName", nameBytes:[]uint8{0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 1}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"namespace", nameBytes:[]uint8{0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 2}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"selfLink", nameBytes:[]uint8{0x73, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x6e, 0x6b}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 3}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"uid", nameBytes:[]uint8{0x75, 0x69, 0x64}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 4}, typ:(*reflect.rtype)(0x26ea380), omitEmpty:true, quoted:false}, json.field{name:"resourceVersion", nameBytes:[]uint8{0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 5}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, json.field{name:"generation", nameBytes:[]uint8{0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 6}, typ:(*reflect.rtype)(0x26e5d80), omitEmpty:true, quoted:false}, json.field{name:"creationTimestamp", nameBytes:[]uint8{0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 7}, typ:(*reflect.rtype)(0x33d2c00), omitEmpty:true, quoted:false}, json.field{name:"deletionTimestamp", nameBytes:[]uint8{0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 8}, typ:(*reflect.rtype)(0x33d2c00), omitEmpty:true, quoted:false}, json.field{name:"deletionGracePeriodSeconds", nameBytes:[]uint8{0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 9}, typ:(*reflect.rtype)(0x26e5d80), omitEmpty:true, quoted:false}, json.field{name:"labels", nameBytes:[]uint8{0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 10}, typ:(*reflect.rtype)(0x26da380), omitEmpty:true, quoted:false}, json.field{name:"annotations", nameBytes:[]uint8{0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 11}, typ:(*reflect.rtype)(0x26da380), omitEmpty:true, quoted:false}, json.field{name:"Spec", nameBytes:[]uint8{0x53, 0x70, 0x65, 0x63}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:false, index:[]int{2}, typ:(*reflect.rtype)(0x2eec940), omitEmpty:false, quoted:false}, json.field{name:"Status", nameBytes:[]uint8{0x53, 0x74, 0x61, 0x74, 0x75, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:false, index:[]int{3}, typ:(*reflect.rtype)(0x2e06b60), omitEmpty:false, quoted:false}}
```

**Comment by ncdc** [comment] 2016-03-16 19:32
Fun times converting hex to ascii :)

**Comment by ncdc** [comment] 2016-03-16 19:35
Easier to read:

```
fields=[]
{
{name:"kind", nameBytes:[]uint8{0x6b, 0x69, 0x6e, 0x64}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{0, 0}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"apiVersion", nameBytes:[]uint8{0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{0, 1}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"name", nameBytes:[]uint8{0x6e, 0x61, 0x6d, 0x65}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 0}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"generateName", nameBytes:[]uint8{0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 1}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"namespace", nameBytes:[]uint8{0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 2}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"selfLink", nameBytes:[]uint8{0x73, 0x65, 0x6c, 0x66, 0x4c, 0x69, 0x6e, 0x6b}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 3}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"uid", nameBytes:[]uint8{0x75, 0x69, 0x64}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 4}, typ:(*reflect.rtype)(0x26ea380), omitEmpty:true, quoted:false}, 
{name:"resourceVersion", nameBytes:[]uint8{0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 5}, typ:(*reflect.rtype)(0x26eb680), omitEmpty:true, quoted:false}, 
{name:"generation", nameBytes:[]uint8{0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e}, equalFold:(func([]uint8, []uint8) bool)(0x1ccad00), tag:true, index:[]int{1, 6}, typ:(*reflect.rtype)(0x26e5d80), omitEmpty:true, quoted:false}, 
{name:"creationTimestamp", nameBytes:[]uint8{0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 7}, typ:(*reflect.rtype)(0x33d2c00), omitEmpty:true, quoted:false}, 
{name:"deletionTimestamp", nameBytes:[]uint8{0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 8}, typ:(*reflect.rtype)(0x33d2c00), omitEmpty:true, quoted:false}, 
{name:"deletionGracePeriodSeconds", nameBytes:[]uint8{0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 9}, typ:(*reflect.rtype)(0x26e5d80), omitEmpty:true, quoted:false}, 
{name:"labels", nameBytes:[]uint8{0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 10}, typ:(*reflect.rtype)(0x26da380), omitEmpty:true, quoted:false}, 
{name:"annotations", nameBytes:[]uint8{0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:true, index:[]int{1, 11}, typ:(*reflect.rtype)(0x26da380), omitEmpty:true, quoted:false}, 
{name:"Spec", nameBytes:[]uint8{0x53, 0x70, 0x65, 0x63}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:false, index:[]int{2}, typ:(*reflect.rtype)(0x2eec940), omitEmpty:false, quoted:false}, 
{name:"Status", nameBytes:[]uint8{0x53, 0x74, 0x61, 0x74, 0x75, 0x73}, equalFold:(func([]uint8, []uint8) bool)(0x1ccaa00), tag:false, index:[]int{3}, typ:(*reflect.rtype)(0x2e06b60), omitEmpty:false, quoted:false}}
```

**Comment by ncdc** [comment] 2016-03-16 20:49
Gist with debugging using https://github.com/ncdc/origin/tree/flake/6435: https://gist.github.com/ncdc/1806bab78c1fd5fd759b

**Comment by ncdc** [comment] 2016-03-16 20:53
My current theory is that most of the time it will determine the fields for a type, cache them, and reuse them, but it appears that when the tests flake, it's maybe because it's using an internal type that doesn't have json tags, instead of an external type that does. Not sure why...

**Comment by aveshagarwal** [comment] 2016-03-17 15:57
I am not sure about root cause, but also as @ncdc said that it is surely because internal types dont have json tags. However, I am confused by the different json imports in upstream kube: pkg/util/strategicpatch/patch.go has "encoding/json"

and in latest origin repo: Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/patch.go:
"k8s.io/kubernetes/pkg/util/json"

**Comment by aveshagarwal** [comment] 2016-03-17 15:58
Not sure if that is intention, because otherwise I dont see any different in that files other than that import.

**Comment by liggitt** [comment] 2016-03-17 15:59
We're carrying a commit with an upstream PR that fixes a bug with lossy numeric conversion

**Comment by ncdc** [comment] 2016-03-17 16:11
I can confirm that this is flaking because the object that is passed to LookupPatchMetadata is e.g. api.BuildConfig, not v1.BuildConfig.

**Comment by smarterclayton** [comment] 2016-03-17 16:37
Which should never happen, which probably means something else is seriously
wrong.

**Comment by liggitt** [comment] 2016-03-17 16:43
is this client side or server side (or both)?

**Comment by ncdc** [comment] 2016-03-17 16:47
```
panic: ANDY t=api.BuildConfig

goroutine 31504 [running]:
k8s.io/kubernetes/third_party/forked/json.LookupPatchMetadata(0x7ff49ec650a8, 0x30c1dc0, 0xc825d2ba10, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/third_party/forked/json/fields.go:59 +0x728
k8s.io/kubernetes/pkg/util/strategicpatch.diffMaps(0xc8269b6660, 0xc8269b6d50, 0x7ff49ec650a8, 0x30c1dc0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/patch.go:206 +0xb36
k8s.io/kubernetes/pkg/util/strategicpatch.CreateTwoWayMergePatch(0xc821d87880, 0x360, 0x360, 0xc822512800, 0x3c8, 0x3c8, 0x335b4e0, 0xc822a72d20, 0x0, 0x0, ...)
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/patch.go:142 +0x345
k8s.io/kubernetes/pkg/util/strategicpatch.CreateStrategicMergePatch(0xc821d87880, 0x360, 0x360, 0xc822512800, 0x3c8, 0x3c8, 0x335b4e0, 0xc822a72d20, 0x0, 0x0, ...)
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/patch.go:115 +0xc3
k8s.io/kubernetes/pkg/apiserver.patchResource.func1(0x0, 0x0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:570 +0x462
k8s.io/kubernetes/pkg/apiserver.finishRequest.func1(0xc823ca1260, 0xc82141bae0, 0xc823ca1200, 0xc823ca11a0)
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:915 +0xec
created by k8s.io/kubernetes/pkg/apiserver.finishRequest
        /home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:920 +0xf1
```

**Comment by ncdc** [comment] 2016-03-17 16:47
Server

**Comment by ncdc** [comment] 2016-03-17 16:51
This is from commit 7e38050 with some extra logging I added to fields.go

**Comment by liggitt** [comment] 2016-03-17 17:09
opened https://github.com/openshift/origin/pull/8098 to use versioned object when recomputing patches

**Comment by ncdc** [comment] 2016-03-17 17:37
@liggitt's fix seems to nail it

**Comment by bparees** [comment] 2016-03-17 17:44
assigning to Andy since he deserves the credit for chasing this down.

**Comment by ncdc** [comment] 2016-03-17 19:36
Catch @liggitt, you're it!

**Closed** 2016-03-19 00:09 UTC
Labels: kind/test-flake, priority/P0
