### ISSUE TITLE
test/cmd/admin.sh: error getting client flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8946] opened 2016-05-19 18:44 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1002/consoleFull#116506536856c25df4e4b05b79524e5d52
```
registry daemonset: ok
Running test/cmd/admin.sh:309: executing 'oadm registry --dry-run' expecting failure and text 'does not exist'...
FAILURE after 1.047s: test/cmd/admin.sh:309: executing 'oadm registry --dry-run' expecting failure and text 'does not exist': the output content test failed
There was no output from the command.
Standard error from the command:
error: error getting client: Get https://127.0.0.1:28443/api: dial tcp 127.0.0.1:28443: connection refused
!!! Error in /data/src/github.com/openshift/origin/test/cmd/../../hack/cmd_util.sh:225
	'return "${return_code}"' exited with status 1
Call stack:
	1: /data/src/github.com/openshift/origin/test/cmd/../../hack/cmd_util.sh:225 os::cmd::expect_failure_and_text(...)
	2: /data/src/github.com/openshift/origin/test/cmd/admin.sh:309 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:339
```
Just after the daemon set test which looks suspicious

cc: @pweil- @deads2k

**Comment by pweil-** [comment] 2016-05-19 19:03
I'd be more suspicious if it was saying that the registry already exists.  Error dialing the local host though seems unrelated.  I'll see if I can reproduce it.

**Comment by deads2k** [comment] 2016-05-19 19:05
> I'd be more suspicious if it was saying that the registry already exists. Error dialing the local host seems unrelated though. I'll see if I can reproduce it.

Server panic doing something with the daemonset: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1002/artifact/origin/artifacts/test-cmd/logs/openshift.log

**Comment by pweil-** [comment] 2016-05-19 21:22
The DS controller is not handling DeletedFinalStateUnknown in the delete func of its store.  Submitted https://github.com/kubernetes/kubernetes/pull/25913

**Comment by pweil-** [comment] 2016-09-21 09:29
https://github.com/kubernetes/kubernetes/pull/25913 was merged upstream and has since been pulled in via rebasing to correctly handle `DeletedFinalStateUnknown`

**Closed by pweil-** 2016-09-21 09:29 UTC
Labels: area/tests, kind/test-flake, priority/P2
