### ISSUE TITLE
GCS registry driver not working

### ISSUE THREAD

**Issue by bdurrow** [openshift/origin#10659] opened 2016-08-26 04:31 UTC
#10640 doesn't appear to fix my problem.  I added comments about how I was able to get it working in that PR.

**Comment by mfojtik** [comment] 2016-08-26 08:29
@bdurrow I just talked to the QA guys and they were able to verify this fix (they are able to push images into GCS backend).

**Comment by mfojtik** [comment] 2016-08-26 08:30
@bdurrow are you using 2.4.0 registry (the one we have in `vendor/github.com/docker/distribution/registry` ?

**Comment by mfojtik** [comment] 2016-08-26 11:59
@bdurrow I believe your fix is right as mentioned in the original pull request and it fixes the "root cause" of this. However, the upstream PR is meant to be for Docker Registry 2.5.0 where we use Docker Registry 2.4.0 internally. I'm not sure why the the https://github.com/openshift/origin/pull/10640 does not fix the problem with pushing for you, but it should address this issue for 2.4.0 registry. Once we bump the version to 2.5.0, we will get the fix you propose.

**Comment by bdurrow** [comment] 2016-08-26 14:36
As I just mentioned in #10640 I tried with the image that I assume included this fix and I still got an error (Not the same error as before the fix).  I tried to only pull from upstream PRs that were compatible for 2.4.0.  Upstream has an unmerged PR against 2.4.0 but it has been polluted with other commits when the submitter pulled master into their feature branch.  My environment is made from release-1.2 with the exception of the registry which now works with the origin-docker-registry image I made using the method described.  I know that mixing and matching like this is not supported but the risk seems smaller to do it that way than using 1.3.0-alpha for all the components.

**Comment by mfojtik** [comment] 2016-08-29 09:31
This is not fixed (https://bugzilla.redhat.com/show_bug.cgi?id=1370045)
@bdurrow the fix you proposed will be part of 2.5.0 registry (or 2.6.0 even).

**Closed by mfojtik** 2016-08-29 09:31 UTC
Labels: component/imageregistry, kind/question, priority/P2
