### ISSUE TITLE
Flake: github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:385

### ISSUE THREAD

**Issue by jpeeler** [openshift/origin#15387] opened 2017-07-20 21:22 UTC
github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:385: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration'

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4532/consoleFull
```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:385: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration'
FAILURE after 0.015s: test/end-to-end/core.sh:385: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
If you don't see a command prompt, try pressing enter.
In project test on server https://172.30.0.1:443

pod/cli-with-token runs openshift/origin:2cbeda7

1 warning identified, use 'openshift cli status -v' to see details.

There was no error output from the command.
=== END TEST CASE ===
```

**Comment by liggitt** [comment] 2017-07-21 05:49
dupe of https://github.com/openshift/origin/issues/14897

**Closed by liggitt** 2017-07-21 05:49 UTC
Labels: kind/test-flake
