### ISSUE TITLE
[image_ecosystem][ruby][Slow] hot deploy for openshift ruby image Rails example should work with hot deploy [Suite:openshift]

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#18448] opened 2018-02-05 18:08 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18440/test_pull_request_origin_extended_image_ecosystem/511/

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/s2i_ruby.go:46
Expected error:
    <*errors.errorString | 0xc420234760>: {s: "not progressing"}
    not progressing
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/s2i_ruby.go:62
```

/kind test-flake
/priority p1
/assign @bparees

**Comment by bparees** [comment] 2018-02-05 18:14
postgres failed to deploy due to:
```
 message: 'devmapper: Error activating devmapper device for ''4310c37b85962b06ab305a8212c1fde0946f2087ba745d823807f7c176bea859'':
            devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run
```

and the ruby deploy depends on reaching the DB.

so that makes this a dupe of: https://github.com/openshift/origin/issues/17787

**Closed by bparees** 2018-02-05 18:14 UTC
Labels: kind/test-flake, priority/P1
