### ISSUE TITLE
openshift start -> determining wrong IP addresses

### ISSUE THREAD

**Issue by wfrank2509** [openshift/origin#6326] opened 2015-12-15 18:30 UTC
Hello everybody, 
I am using a clean CentOS 7.1 and all openshift install prerequisites are meet. I get connectivity problems using the Docker and Binary installation.

First I noticed that when I launch openshift the wrong IP address for master is determined. I need to provide a SCOPE peer <GATEWAY> in my network eth0 settings for the hosting provider (Hetzner). Actually openshift uses the Gateway IP instead of the one of my server.

I got around that issue using a custom master-config.yaml and setting the master and public-master options when starting openshift. 

Now the issue is that Kubernetes creates iptables rules still with destination to the gateway instead of the real server. This causes the nodes to be inaccessible.

E.g. 
-A KUBE-PORTALS-HOST -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:https" -m tcp --dport 443 -j DNAT --to-destination 176.x.x.225:33790

Can you point me to the place where these IPs are determined so that I could possibly fix it and provide a pull request or is there a way to override/configure the IP used for the port forward?

Thank you,
Wolfgang

**Comment by deads2k** [comment] 2015-12-15 21:04
It's chosen here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go#L144, called from here https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/node.go#L220 and it ends up here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go#L462.

The upstream code is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/userspace/proxier.go#L145 and still very similar.

**Comment by deads2k** [comment] 2015-12-15 21:12
hmm... Actually I'm not sure if its the `hostIP` or the `listenIP` that ends up as the target of the rule.  If its the the `listenIP`, you can probably set it by tweaking your `node-config.yaml`

**Comment by wfrank2509** [comment] 2015-12-16 09:45
Thank you. Yes it looks like a kubernetes related issue with specific network setups. I will try to address the issue in the upstream project and take a further look how to resolve the issue by myself if possible.

**Comment by dlbewley** [comment] 2015-12-21 18:57
I think I experienced the same or similar problem.

Recent OSE 3.1 install on RHEL7.2 was working initially, but at some point the Host IP of the master changed somehow. This broke the SDN, and made the router and registry unreachable from the rest of the cluster.

It took a while to discover that `oc get hostsubnet` returned the `tun0` 10.1.3.1 address as the hostip of the master instead of the address on `eth0`. 

Fix was to `oc edit hostsubnet` and adjust the entry by hand to reflect the public IP of the master node.

Still not clear on root cause. It might be worth noting I'm using DHCP on `eth0`.

**Comment by tompson** [comment] 2016-02-19 21:14
I get exactly the same problem when trying to run openshift on our Hetzner server @wfrank2509 

did you find a solution?

**Comment by wfrank2509** [comment] 2016-02-20 00:25
Not yet. Heard rumor that installing via Ainsible gives more/other choices for configuration that might work.

**Comment by danwinship** [comment] 2016-02-20 17:31
#7310 merged in a change (https://github.com/openshift/openshift-sdn/pull/256) to how openshift-sdn determines the node's IP address, which might fix this problem.

**Comment by tompson** [comment] 2016-03-27 19:58
this problem does not exist anymore with v1.1.4

**Closed** 2016-03-30 12:09 UTC
Labels: component/networking, kind/question, priority/P3
