### ISSUE TITLE
Proxy settings for Docker are omitted

### ISSUE THREAD

**Issue by bahho** [openshift/origin#10849] opened 2016-09-08 13:04 UTC
I am using the all in one virtual machine behind a corporate proxy server with authorization. 
I cannot create a new app in OpenShift using a Docker image if I am behind a proxy.

I have set the environment variables for oc and the terminal: 
- http_proxy
  -https_proxy
  -HTTP_PROXY
  -HTTPS_PROXY

for docker -as described in the documentation- put the lines

[Service]
Environment="HTTP_PROXY=http://uname:pass@serverip:port/"

into the file
 /etc/systemd/system/docker.service.d/http-proxy.conf

reloaded daemon and restarted docker service.

I can pull the image from the Docker Hub, but cannot use it with oc, since it is still trying -for some reason- to connect to the internet and the proxy settings are not effective.

When I disconnect my computer from the company network and use my cellphone's hotspot instead, it works. 

I have tried this with all in one VM, running openshift as a container and downloading the binaries from github. All the same.

Putting aside the fact that proxy settings for Docker won't work, why does oc try to establish a connection to the hub even though I want to use a local image?
## OpenShift info

oc v1.3.0-alpha.3+bbeb2f3
kubernetes v1.3.0+507d3a7
features: Basic-Auth
## Docker info 

 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
##### Steps To Reproduce
1. docker pull hello-world
2. oc login -u admin
3. oc new-project helloworld-project
4. oc new-app docker.io/hello-world --name=helloworld-app
##### Current Result

error: can't look up Docker image "docker.io/hello-world": Internal error occurred: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: no such host
error: no match for "docker.io/hello-world"
The 'oc new-app' command will match arguments to the following types:
1. Images tagged into image streams in the current project or the 'openshift' project
   - if you don't specify a tag, we'll add ':latest'
2. Images in the Docker Hub, on remote registries, or on the local Docker engine
3. Templates in the current project or the 'openshift' project
4. Git repository URLs or local paths that point to Git repositories
   --allow-missing-images can be used to point to an image that does not exist yet.
   See 'oc new-app -h' for examples.
##### Expected Result

[root@localhost ~]# oc new-app docker.io/hello-world --name=helloworld-app
--> Found Docker image c54a2cc (9 weeks old) from docker.io for "docker.io/hello-world"
    \* An image stream will be created as "helloworld-app:latest" that will track this image
    \* This image will be deployed in deployment config "helloworld-app"
    \* The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/helloworld-app --port=[port]' later
    \* WARNING: Image "docker.io/hello-world" runs as the 'root' user which may not be permitted by your cluster administrator
--> Creating resources with label app=helloworld-app ...
    imagestream "helloworld-app" created
    deploymentconfig "helloworld-app" created
--> Success
    Run 'oc status' to view your app.

**Comment by detiber** [comment] 2016-09-08 15:48
@sdodson have you done any work in support of the vagrant-based all-in-one VM?

**Comment by sdodson** [comment] 2016-09-08 16:00
@detiber No, I have not.
@bahho That's a failure to connect to the dns server, I think docker has problems when the dns server has changed on the host since it was last restarted. Can you try restarting docker once the vm is up and running on the network that requires the proxy server? see https://github.com/docker/docker/issues/18842  You may have other problems, but I think this error is un-related to proxy config.

**Comment by bahho** [comment] 2016-09-09 08:44
Hi @sdodson, 
I had already tried that, with same result. 
Putting the ip in the hosts files so that it is resolved, wont solve the issue either.

**Comment by sdodson** [comment] 2016-09-09 12:17
So, from this host this works?
`dig +short @10.0.2.3 registry-1.docker.io`
What's the content of /etc/resolv.conf ?

**Comment by bahho** [comment] 2016-09-09 12:30
`dig +short @10.0.2.3 registry-1.docker.io ` 
returns nothing, but this
`dig  @10.0.2.3 registry-1.docker.io` 
returns:

> 
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @10.0.2.3 registry-1.docker.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 54277
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;registry-1.docker.io.          IN      A
;; AUTHORITY SECTION:
.                       289     IN      SOA     ***(edited)*** 1 21600 3600 604800 600
;; Query time: 9 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Thu Sep 08 07:31:17 EDT 2016
;; MSG SIZE  rcvd: 123


in /etc/resolve.conf  I have:

> nameserver 10.0.2.3

**Comment by sdodson** [comment] 2016-09-09 13:43
So 10.0.2.3 is returning NXDOMAIN, what's 10.0.2.3? If that's the host's ip and it's running dnsmasq can you dig into that config in /etc/dnsmasq.d/ ?

@csrwng Should `oc new-app` be forcing a pull of an image that exists already?

**Comment by csrwng** [comment] 2016-09-09 14:18
So the issue is that `oc new-app` will rely on the master to do an image import and retrieve metadata from the registry. The problem is likely that the openshift master process doesn't know about the proxy. Whenever starting the OpenShift master, make sure that HTTP_PROXY and HTTPS_PROXY are set.

**Comment by sdodson** [comment] 2016-09-09 17:09
@csrwng thanks

@bahho I'm still suspicious about the NXDOMAIN response, but in order to make sure the master and node have the right environment variables set, not just docker, can you read through https://docs.openshift.org/latest/install_config/http_proxies.html#configuring-hosts-for-proxies Also, when you say all in one vm, can you clarify what you mean by that? There's been a few different versions of an all in one vm made available.

**Comment by bahho** [comment] 2016-09-13 20:01
@cgwalters  thanks. That might be the problem. I have tried the setting the proxy variables on a machine where I installed and start openshift manually: that seem to work. But the all-in-one-VM still can't connect.   I had the environment variables set at startup, so that the openshift master process would know about the proxy. That did not work, Then I tried stopping the openshift process and restart it manually having defined the env. variables. It still won't work. 

@sdodson I have  a pretty up-to-date all-in-one VM. I downloaded and installed vagrant and VM 10-15 days ago.
I have vagrant 1.8.5 
and the VM has CentOS Linux release 7.2.1511 (Core)

**Comment by a609716** [comment] 2017-01-15 19:34
hello, i have the same problem, have you find a solution? thank you in advance

**Comment by a609716** [comment] 2017-01-18 11:25
hello, 3 days after, i find the solution :

1.	Add the proxy environment variables in the OpenShift VM  control files:
sudo vi  /etc/sysconfig/origin , **this file will be created if doesn't exist**
add your proxy:
NO_PROXY=localhost,127.0.0.1,10.2.2.2
HTTP_PROXY=http://proxy.example.com:80
HTTPS_PROXY=http://proxy.example.com:80
and save.
2.	 Edit the proxy environment variables in the origin.service files:
sudo vi /etc/systemd/system/origin.service
Add the following line: EnvironmentFile=/etc/sysconfig/origin and save.
3.	Flush changes:
sudo systemctl daemon-reload
sudo systemctl restart origin
systemctl status origin

**Comment by sdodson** [comment] 2017-01-20 17:07
The solution in the last comment seems accurate. I don't know who maintains the all in one VM but I don't think it's built out of this repo or using openshift-ansible so I'm going to close this.

**Closed by sdodson** 2017-01-20 17:07 UTC
Labels: component/install, kind/question, priority/P2
