### ISSUE TITLE
oc scale not working correctly with replicationcontrollers

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#13230] opened 2017-03-03 19:48 UTC
Using oc scale rc <name> --replicas=0 does not properly scale down.  Another pod is immediately created

Also does not work using --replicas=1, as the additional pods are momentarily created then deleted

##### Version
oc v1.5.0-alpha.3+ad8ea70-212-dirty
kubernetes v1.5.2+43a9be4
features: Basic-Auth

openshift v1.5.0-alpha.3+ad8ea70-212-dirty
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. oc new-app -f https://raw.githubusercontent.com/openshift/rails-ex/master/openshift/templates/rails-postgresql.json
2. oc scale rc rails-postgresql-example-1 --replicas=0

##### Current Result
Scaling up: momentarily creates additional pods then deletes them, leaving the count the original value
Scaling down: deletes the pod then immediately creates a new one
##### Expected Result
Scaling up: should keep the new pods
Scaling down: should remove the pods

**Comment by kargakis** [comment] 2017-03-03 20:39
This is how deployments work in Openshift: 
https://docs.openshift.org/latest/dev_guide/deployments/how_deployments_work.html

**Comment by coreydaley** [comment] 2017-03-03 20:40
@kargakis oc scale rc used to work correctly (as we have not changed the test lately), so what changed?
Is this a new intended behavior?

**Comment by kargakis** [comment] 2017-03-03 20:42
What version did you migrate from?

**Comment by coreydaley** [comment] 2017-03-03 20:44
This is the failure we are seeing: https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/868/consoleFull#142853098456cbb9a5e4b02b88ae8c2f77

**Comment by kargakis** [comment] 2017-03-03 20:57
DCs were always controlling the size of the underlying RCs so it seems that this test has worked by chance in the past because it is racing with the deployer pod. The test shoud simply operate on the dc and not on the rc because operating on the rc won't have the desired effect most of the time I would say. Also the newly created pod when you scale down is containing the updated env so you could potentially just drop the scale up command but I would still suggest using a dc instead of an rc. We have some nice utilities to work with DCs.

**Comment by kargakis** [comment] 2017-03-03 20:59
https://github.com/openshift/origin/blob/master/test/extended/deployments/util.go

**Comment by bparees** [comment] 2017-03-04 04:08
> DCs were always controlling the size of the underlying RCs so it seems that this test has worked by chance in the past because it is racing with the deployer pod. The test shoud simply operate on the dc and not on the rc because operating on the rc won't have the desired effect most of the time I would say.

I won't disagree the test should be changed ( @coreydaley please go ahead and update the test to scale the DC instead, and maybe do a grep to see if we're doing the same thing elsewhere) but something definitely changed about this behavior recently because until yesterday we did not see any flakes on this and now it seems consistently reproducible, so the DC behavior is acting more immediately on the RC change than it used to (which is not necessarily a bug, just saying something changed).

Also it seems like surprising behavior to allow a user to make a change to the RC that is immediately ovewritten with no feedback.  A warning that you're changing an RC that's managed by a DC(and thus your change will be immediately reverted) would be helpful.

@smarterclayton this is the issue i mentioned to you.

**Comment by kargakis** [comment] 2017-03-04 11:57
DCs not acting on RCs immediately was a bug that got fixed once we switched to informers (I think it was 1.3). I am not aware of any recent change to DC that would affect this, as a matter of fact I am not aware of any (behavior changing) recent change to DCs at all. cc: @mfojtik 

> Also it seems like surprising behavior to allow a user to make a change to the RC that is immediately ovewritten with no feedback. A warning that you're changing an RC that's managed by a DC(and thus your change will be immediately reverted) would be helpful.

This is not related only to DCs->RCs but to any kind of parent-child object relationship I guess. Worth thinking about is that the child management may be delegated to any custom process. Are we going to warn then? What if the custom process is us? Are we going to warn in the cli, UI, or api? Ideally this could be an event emitted by the dc controller but can the dc controller separate between illegal scaling and a normal scaling event (I think we could identify this in the rc update resource handler).

**Comment by kargakis** [comment] 2017-03-05 11:04
Then another question is, is an event discoverable enough to warn users? I don't think we can just hardcode a warning in `oc scale` because we then need to hardcode it in every mutating command.

**Comment by mfojtik** [comment] 2017-03-06 09:21
> DCs not acting on RCs immediately was a bug that got fixed once we switched to informers (I think it was 1.3). I am not aware of any recent change to DC that would affect this, as a matter of fact I am not aware of any (behavior changing) recent change to DCs at all. cc: @mfojtik

That is correct, there were not behavioral changes to DC for 1.5 AFAIK.

> This is not related only to DCs->RCs but to any kind of parent-child object relationship I guess.
Worth thinking about is that the child management may be delegated to any custom process. Are we going to warn then? What if the custom process is us? Are we going to warn in the cli, UI, or api? Ideally this could be an event emitted by the dc controller but can the dc controller separate between illegal scaling and a normal scaling event (I think we could identify this in the rc update resource handler).

So this ultimately boils down to forbiding scale of RC that is managed by a DC, which is pretty hard problem to solve. We can make an admission controller that will revoke any attempt to scale the RC.

@kargakis are you suggesting that we detect the external changes to RC that is managed by DC and in case such change is found, we are going to emit the event informing user that we rolled that change back (iow. you scale RC managed by DC, we scale it back) ?

@jwforres do we allow to scale up the RC in web console separately from the DC or we are forbiding users to click in up/down buttons when the RC is managed by DC (we can detect that by observing the annotation).
If we do this in web console, perhaps we can do it in `oc scale` as well. Just add "pre-check" that if the RC has the annotation, we forbid to scale or throw an warning at minimum.

**Comment by jwforres** [comment] 2017-03-06 13:24
In the console if it is the latest RC for a DC we do actually show the up/down arrows, but when the use clicks it we perform the scale action against the DC not the RC. Older RCs we disable the arrows completely.

**Closed** 2017-03-06 21:42 UTC
Labels: area/usability, component/deployments, priority/P2
