### ISSUE TITLE
High log rate and container throughput causes node failure

### ISSUE THREAD

**Issue by markusdd** [openshift/origin#23499] opened 2019-07-28 21:45 UTC
We are on a cluster with 4 worker nodes (full blown bare metal  24 core servers, SSDs, 2GBit link aggregation using teamd) for CI jobs, 1 dispatcher node which runs only a single gitlab-runner instance (a VM) and a master node (also a VM). Everything is on latest greatest CentOS7, all updates applied.

We are experiencing bad instabilities, which usually end up with nodes going into NotReady state, cause is lost network connection. This only happens on the 4 workers. I have been digging through logs for weeks now, as our Zabbix monitoring does not provide any reason why this happens. There is enough disk space and RAM, no excessive IO wait, no excessive context switching. From one moment to another, the nodes lose connection and become unresponsive. If you use the server remote consoles (HP ilo), you find they are perfectly fine, but networking crashed.

Then I found this:

Jul 28 10:55:35 slpcih01.XXXXXXX.com systemd-journal[60837]: Permanent journal is using 8.0G (max allowed 8.0G, trying to leave 4.0G free of 282.9G available → current limit 8.0G).
Jul 28 10:55:37 slpcih01.XXXXXXX.com systemd-journal[60837]: Journal started
Jul 28 10:55:37 slpcih01.XXXXXXX.com kernel: device vethf5f267ee left promiscuous mode
Jul 28 10:55:37 slpcih01.XXXXXXX.com kernel: device veth8a838ecb left promiscuous mode
Jul 28 10:55:36 slpcih01.commsolid.com rsyslogd[60843]:  [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="60843" x-info="http://www.rsyslog.com"] start
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: Unit lvm2-lvmetad.service entered failed state.
Jul 28 10:55:36 slpcih01.commsolid.com NetworkManager[60840]: <info>  [1564304136.3854] NetworkManager (version 1.12.0-10.el7_6) is starting... (after a restart)
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: lvm2-lvmetad.service failed.
Jul 28 10:55:36 slpcih01.commsolid.com NetworkManager[60840]: <info>  [1564304136.3856] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 10-slaves-order.conf)
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: rsyslog.service: main process exited, code=killed, status=9/KILL
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: Unit rsyslog.service entered failed state.
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: rsyslog.service failed.
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: systemd-logind.service: main process exited, code=killed, status=9/KILL
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: Unit systemd-logind.service entered failed state.
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: systemd-logind.service failed.
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: systemd-journald.service: main process exited, code=killed, status=9/KILL
Jul 28 10:55:29 slpcih01.commsolid.com systemd[1]: Unit systemd-journald.service entered failed state.
Jul 28 10:55:37 slpcih01.commsolid.com systemd[1]: origin-node.service holdoff time over, scheduling restart.
Jul 28 10:55:37 slpcih01.commsolid.com systemd[1]: Started D-Bus System Message Bus.
Jul 28 10:55:37 slpcih01.commsolid.com systemd-udevd[60851]: starting version 219
Jul 28 10:55:39 slpcih01.commsolid.com dbus[60852]: [system] Successfully activated service 'org.freedesktop.systemd1'
Jul 28 10:55:39 slpcih01.commsolid.com NetworkManager[60840]: <info>  [1564304139.6225] bus-manager: acquired D-Bus service "org.freedesktop.NetworkManager"
Jul 28 10:55:39 slpcih01.commsolid.com NetworkManager[60840]: <info>  [1564304139.6231] manager[0x55f271fc7020]: monitoring kernel firmware directory '/lib/firmware'.
Jul 28 10:55:39 slpcih01.commsolid.com systemd[1]: Stopped OpenShift Node.

What then follows is basically half a system reboot, central services like systemd seem to fail, also NetworkManager crashes and restarts.

##### Version
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://XXXXXXXXXXXXXXXXXXXXXXX:8443
openshift v3.11.0+d72920c-223
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
good question, it just happens after some time 

##### Current Result
after a few hours to days above errors appear and nodes fail

##### Expected Result
stability

I suspect this happens because journald goes crazy when it's space flows over, dragging the system down with it. Question is why this log overflow happens in the first place. We have quite a bit of container throughput on this cluster with a lot of build jobs and network based tests that communicate to our lab. So it's not that an app or jobs starts and lives there for a few hours, usually a jobs lifetime is anywhere from 10min to 30min max. . Maybe this causes more log throughput than expected.

Any recommendation how to fix this? These instabilities are heavily affecting our automated testing and I'm kind of clueless what to do now.

**Comment by BostjanBozic** [comment] 2019-11-16 10:07
I am experiencing exactly the same issue, version `openshift v3.11.0+62803d0-1`.

Been digging around the issue, but so far the only thing I found is what you mentioned - half of the system goes down for no apparent reason.
In our case what happens at the same time that pods are actually not rescheduled on this node, but are kept in error state (we are using `cri-o` underneath, though it might have to do with GlusterFS service not restarting).

Did you so far find any workaround for this?

**Comment by BostjanBozic** [comment] 2019-11-28 09:01
What happened in our case in the end was extremely high CPU utilization on particular worker node. This in the end causes `cri-o` to fail, which due to bug sends SIGTERM to all processes in root namespace:

`Correct, cri-o should not be sending SIGKILL to all root namespace processes. This was treated as a high severity bug and has already been addressed in an updated version of cri-o. cri-o-1.11.14-2 contains the patch to correct this behavior, so please update to that version to avoid hitting this issue again in the future.`

Unfortunatelly this cri-o update has not yet been merged into OKD 3.11 branch.

**Comment by david9991** [comment] 2020-02-03 08:19
Exactly same issue here, many of my system service KILLed without any reason, it happens almost everyday. And it's may be easier to reproduce by execute `kubectl delete pods xxx --force --grace-period=0`. I am using Clear Linux.

**Comment by david9991** [comment] 2020-02-03 08:21
@markusdd Have you got it solved?

**Closed** 2020-07-06 12:26 UTC
Labels: lifecycle/rotten

**Comment by andresmmujica** [comment] 2020-09-20 01:11
it's happening here too.

It seems caused by the journal reaching its storage limit causing havoc among other services
