### ISSUE TITLE
Unable to start `docker.io/openshift/origin-docker-registry:v1.0.4`

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#3983] opened 2015-08-03 11:37 UTC
I'm not able to start the OpenShift registry using the v1.0.4 release tag:

```console
[root@openshiftdev openshift]# docker run -it docker.io/openshift/origin-docker-registry:v1.0.4 /bin/sh
exec: "/bin/sh": stat /bin/sh: no such file or directory
FATA[0000] Error response from daemon: Cannot start container 4802db12ff15f922b661851616783db2b680914d3a04a7b6560df0b0cf3fba9f: [8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory 
```

However, if I docker pull the latest image, I get it working:

```console
[root@openshiftdev openshift]# docker run -it docker.io/openshift/origin-docker-registry /bin/sh
sh-4.2#
```

**Comment by pweil-** [comment] 2015-10-16 18:33
@mfojtik  - wasn't able to reproduce this locally, still an issue for you?

```
[pweil@localhost origin]$ docker run -it docker.io/openshift/origin-docker-registry:v1.0.4 /bin/sh
Unable to find image 'docker.io/openshift/origin-docker-registry:v1.0.4' locally
v1.0.4: Pulling from openshift/origin-docker-registry

472b01985f3a: Pull complete 
e284753a83fa: Pull complete 
1c2fa2da4127: Pull complete 
9709b0ee6315: Pull complete 
037c0752d511: Pull complete 
47692bb02038: Pull complete 
2536d61f7fd3: Pull complete 
57763c53fdf1: Pull complete 
a5c39c44a38c: Already exists 
f1b10cd84249: Already exists 
c852f6d61e65: Already exists 
7322fbe74aa5: Already exists 
Digest: sha256:48695b5041435e78c1e39a66b6c2c9783f454fa59d2dd9612b3db71ca92bf4d8
Status: Downloaded newer image for openshift/origin-docker-registry:v1.0.4
sh-4.2# 
```

**Comment by pweil-** [comment] 2016-04-04 16:54
closing due to age

**Closed by pweil-** 2016-04-04 16:54 UTC
Labels: component/imageregistry, kind/bug, priority/P2
