### ISSUE TITLE
Flake TestRouterDuplications

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#13708] opened 2017-04-11 08:56 UTC
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/989/consoleFull

```
--- FAIL: TestRouterDuplications (2.35s)
	router_test.go:837: Unable to validate both routes in a duplicate service scenario.  Resp 1: %!s(<nil>), Resp 2: Get http://0.0.0.0: read tcp 127.0.0.1:33922->127.0.0.1:80: read: connection reset by peer
```

**Comment by detiber** [comment] 2017-06-28 03:09
I'm seeing this failure as well as others on ppc64le and aarch64 tests with golang-1.8. I think the issue is caused by only testing the api server /healthz endpoint instead of /healthz/ready. I suspect that the issue is more prevalent in my environment because of peculiarities of the environments I'm running on.

I'm testing a fix for this currently.

**Comment by kargakis** [comment] 2017-10-13 11:05
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16840/test_pull_request_origin_end_to_end/4132/

**Closed** 2018-04-23 23:29 UTC
Labels: component/networking, kind/test-flake, lifecycle/rotten, priority/P1
