### ISSUE TITLE
s2i build with a quota extended test flake

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#8707] opened 2016-05-02 13:22 UTC
Extended.[builds][Conformance] s2i build with a quota Building from a template should create an s2i build with a quota and run it

Can be seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/710/consoleText

The relevant part of the logs:

```
...
        I0502 12:51:11.372743       1 sti.go:583] MEMORY=209715200
        I0502 12:51:11.373543       1 sti.go:583] MEMORYSWAP=209715200
        I0502 12:51:11.374877       1 sti.go:583] QUOTA=-1
        I0502 12:51:11.375617       1 sti.go:583] SHARES=61
        I0502 12:51:11.376372       1 sti.go:583] PERIOD=100000
```

It expect `QUOTA=6000`. 

This is pretty regular flake.

**Comment by bparees** [comment] 2016-05-02 14:02
dupe of https://github.com/openshift/origin/issues/8427
@mrunalp fyi.

**Comment by mfojtik** [comment] 2016-05-02 14:26
@bparees I swear I used search :-)

**Closed** 2017-04-13 20:33 UTC
Labels: component/build, kind/test-flake, priority/P2
