### ISSUE TITLE
Various extended build tests fail to get build pods scheduled

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#15615] opened 2017-08-02 20:04 UTC
With the https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/148/ extended builds test run, a series of build failed

With these:

  Extended.[builds][Slow] openshift pipeline build Blue-green pipeline Blue-green pipeline should build and complete successfully
    Extended.[builds][Slow] starting a build using CLI binary builds should accept --from-repo as input
    Extended.[builds][quota][Slow] docker build with a quota Building from a template should create a docker build with a quota and run it
    Extended.[builds][Slow] build can have Dockerfile input being created from new-build should be able to start a build from Dockerfile with FROM reference to scratch

With each, we see some common threads
1) the pod for the build stuck in pending state, such as 

```
 Pending           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-08-02 10:37:40 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-08-02 10:37:40 -0400 EDT ContainersNotReady containers with unready status: [sti-build]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-08-02 10:37:40 -0400 EDT  }]
```

2) and in the node log, we see this an error message of the form:

```
Aug 02 10:37:41 ip-172-18-3-102.ec2.internal origin-node[32525]: W0802 10:37:41.327276   32525 helpers.go:432] Couldn't load Docker cofig. If sandbox image "openshift/origin-pod:13715b8" is in a private registry, this will cause further errors. Error: couldn't find valid .dockercfg after checking in [/.docker .docker]
Aug 02 10:37:41 ip-172-18-3-102.ec2.internal origin-node[32525]: I0802 10:37:41.327403   32525 kube_docker_client.go:331] Stop pulling image "openshift/origin-pod:13715b8": "Trying to pull repository docker.io/openshift/origin-pod ... "
Aug 02 10:37:41 ip-172-18-3-102.ec2.internal origin-node[32525]: E0802 10:37:41.327540   32525 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = unable to pull sandbox image "openshift/origin-pod:13715b8": manifest unknown: manifest unknown
Aug 02 10:37:41 ip-172-18-3-102.ec2.internal origin-node[32525]: E0802 10:37:41.327583   32525 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "nodejs-mongodb-example-2-build_extended-test-jenkins-pipeline-0rr49-j3s4x(22be5d69-7790-11e7-8626-0ed7f38fc706)" failed: rpc error: code = 2 desc = unable to pull sandbox image "openshift/origin-pod:13715b8": manifest unknown: manifest unknown
Aug 02 10:37:41 ip-172-18-3-102.ec2.internal origin-node[32525]: E0802 10:37:41.327598   32525 kuberuntime_manager.go:618] createPodSandbox for pod "nodejs-mongodb-example-2-build_extended-test-jenkins-pipeline-0rr49-j3s4x(22be5d69-7790-11e7-8626-0ed7f38fc706)" failed: rpc error: code = 2 desc = unable to pull sandbox image "openshift/origin-pod:13715b8": manifest unknown: manifest unknown
Aug 02 10:37:41 ip-172-18-3-102.ec2.internal origin-node[32525]: E0802 10:37:41.327632   32525 pod_workers.go:182] Error syncing pod 22be5d69-7790-11e7-8626-0ed7f38fc706 ("nodejs-mongodb-example-2-build_extended-test-jenkins-pipeline-0rr49-j3s4x(22be5d69-7790-11e7-8626-0ed7f38fc706)"), skipping: failed to "CreatePodSandbox" for "nodejs-mongodb-example-2-build_extended-test-jenkins-pipeline-0rr49-j3s4x(22be5d69-7790-11e7-8626-0ed7f38fc706)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nodejs-mongodb-example-2-build_extended-test-jenkins-pipeline-0rr49-j3s4x(22be5d69-7790-11e7-8626-0ed7f38fc706)\" failed: rpc error: code = 2 desc = unable to pull sandbox image \"openshift/origin-pod:13715b8\": manifest unknown: manifest unknown"

```

    Extended.[builds][Slow] openshift pipeline build Pipeline using jenkins-client-plugin should build and complete successfully

was not exactly the same, but very similar ... the jenkins deploy was stuck in container creating, but the same manifest unknown sequence occurred on the node

lastly, as a point of reference, we had had at least 6 successful runs in a row with this test suite prior to this run.

@openshift/devex @mfojtik @miminar @dmage

**Comment by gabemontero** [comment] 2017-08-03 14:32
fyi the extended build job last night, https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/149/display/redirect, did not experience this issue

**Comment by bparees** [comment] 2017-08-23 18:35
haven't seen this in a while, i'm going to optimistically close it.  there is another open issue for pods getting stuck in containercreate, which also might have been the root cause of this.

**Closed by bparees** 2017-08-23 18:35 UTC
Labels: component/deployments, component/imageregistry, kind/test-flake, priority/P1, sig/developer-experience
