### ISSUE TITLE
Extended.[networking][router] openshift routers The HAProxy router should override the route host with a custom value

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12322] opened 2016-12-21 21:27 UTC
```
/data/src/github.com/openshift/origin/test/extended/router/scoped.go:133
Expected error:
    <*errors.errorString | 0xc8200dd5d0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/data/src/github.com/openshift/origin/test/extended/router/scoped.go:95
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9773

**Comment by bparees** [comment] 2017-01-21 23:44
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10491/

**Comment by smarterclayton** [comment] 2017-01-23 03:42
Dupe of #11016

**Closed by smarterclayton** 2017-01-23 03:42 UTC
Labels: component/networking, kind/test-flake, priority/P1
