### ISSUE TITLE
UI flake on protractor

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6495] opened 2015-12-24 14:54 UTC
seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8102/console):
```
Running "protractor:chrome" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
>> /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
>>       throw error;
>>             ^
>> Error: Timed out waiting for the WebDriver server at http://172.18.3.143:59957/wd/hub
>>     at Error (<anonymous>)
>>     at onResponse (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:87:11)
>>     at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:42:21
>>     at /data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
>>     at ClientRequest.<anonymous> (/data/src/github.com/openshift/origin/assets/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:7)
>>     at ClientRequest.emit (events.js:95:17)
>>     at Socket.socketErrorListener (http.js:1552:9)
>>     at Socket.emit (events.js:95:17)
>>     at net.js:441:14
>>     at process._tickCallback (node.js:442:13)
Fatal error: protractor exited with code: 8
```

**Comment by liggitt** [comment] 2015-12-24 15:46
Dupe of https://github.com/openshift/origin/issues/6053

**Closed by liggitt** 2015-12-24 15:46 UTC
