### ISSUE TITLE
oc get all output is weirdly formatted

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3620] opened 2015-07-07 19:26 UTC
currently `oc get all` looks like this : 

<img width="1398" alt="2015-07-07__21-24-18" src="https://cloud.githubusercontent.com/assets/98980/8555180/9024428c-24ee-11e5-90f0-f22483bafb90.png">

I think this could use some (cosmetic formatting alignment) love

**Comment by liggitt** [comment] 2015-07-07 19:28
dupe of https://github.com/openshift/origin/issues/2354

**Closed by liggitt** 2015-07-07 19:28 UTC
