### ISSUE TITLE
Build logs for completed builds are broken

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1115] opened 2015-02-23 20:16 UTC
https://github.com/GoogleCloudPlatform/kubernetes/pull/4373 looks like it has a very aggressive check (only running containers can be shown), which means you can't see logs for completed pods.  I think we need to figure out upstream how to be able to run "the logs for pod X for the last attempt".  @bparees can you assign someone to this to look into it?

**Comment by smarterclayton** [comment] 2015-02-23 20:17
```
$ osc build-logs 425ff2a9-bb98-11e4-804b-080027ce4245
Internal Error: container "sti-build" is not ready.
```

**Comment by ncdc** [comment] 2015-02-23 20:18
Also see https://github.com/GoogleCloudPlatform/kubernetes/issues/4640

**Comment by bparees** [comment] 2015-02-23 20:44
@smarterclayton how close are we to having a centralized log store?  that is really the right answer here and would also free us from the "we can never remove a completed pod" constraint we currently operate under.

**Comment by ncdc** [comment] 2015-02-23 20:45
@bparees talk to @jwhonce and also see https://trello.com/c/keg2JJOq/278-8-log-retrieval-metrics-beta3

**Comment by smarterclayton** [comment] 2015-02-23 20:52
I think we'll always (3.x) want to be able to go to the nodes for active and recent logs.  There's a latency issue involved with centralized logs, as well as access control, complexity of config, etc.

----- Original Message -----

**Comment by bparees** [comment] 2015-02-23 22:31
With upstream reverting the breakage, build-logs should work again.  For the longer term question of how pod logs should be handled in general, i think that's better handled by the infrastructure team.. @jwhonce ?

**Comment by brenton** [comment] 2015-03-03 20:53
@thoraxe, this is what you were hitting.

**Comment by kargakis** [comment] 2015-03-10 12:40
This has been fixed now

**Comment by TomasTomecek** [comment] 2015-03-10 12:54
is this part of 0.4.1?

**Comment by kargakis** [comment] 2015-03-10 12:57
> is this part of 0.4.1?

Yes. See https://github.com/openshift/origin/releases/tag/v0.4.1
It was an upstream problem
> Rebased on top of Kube 0.11

**Comment by TomasTomecek** [comment] 2015-03-10 13:11
> It was an upstream problem

I asked because I was lazy to dig in origin's or k8s' git.

**Comment by brenton** [comment] 2015-03-10 13:33
@jianlinliu, we should have an OSE 0.4.1 build soon.  Can you have someone at a regression test for this case so we verify it in beta3?

**Comment by thoraxe** [comment] 2015-03-10 13:56
So is this not in 0.4.0?

**Comment by brenton** [comment] 2015-03-10 14:43
@thoraxe, correct.  The logs for running builds should at least work for OSE v0.4 now that the permissions problem was resolved.

**Comment by brenton** [comment] 2015-03-18 19:28
This has been fixed.

**Closed by brenton** 2015-03-18 19:28 UTC
Labels: bug
