### ISSUE TITLE
JenkinsFile in private repos unusable even source secret provide in Pipeline build configs

### ISSUE THREAD

**Issue by sudhirpandey** [openshift/origin#11667] opened 2016-10-31 16:49 UTC
[provide a description of the issue]
We have a JenkinsPipeline file in a private app repo. We creating pipelines , the jekins instance in openshift responsible for the pipeline cannot check out the pipeline , hence the buid fails
##### Version
[provide output of the `openshift version` or `oc version` command]
origin 1.3.0
oc 1.3.0
##### Steps To Reproduce
create a pipeline from secured repo
```
apiVersion: v1
kind: BuildConfig
metadata:
  name: app-pipeline
  labels:
    name: app-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "app-pipeline", "namespace": "ci", "kind": "DeploymentConfig"}]'
spec:
  source:
    type: "Git"
    git:
      uri: "git@bitbucket.org:org/app.git"
    sourceSecret:
      name: bitbucketsecret
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy: {}
  output:
  resources:
  postCommit:
```

Run the pipeline
```
oc get builds
NAME                       TYPE              FROM         STATUS    STARTED          DURATION
app-pipeline-1   JenkinsPipeline   Git@master   Failed    15 minutes ago   1s
```
##### Current Result
first build 
```
Fetching upstream changes from git@bitbucket.org:org/app.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress git@bitbucket.org:org/app.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress git@bitbucket.org:org/aoo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Host key verification failed.
```

After fixing the key issue after manually going into jenkins pod. We get this 

2nd build
```Failed to connect to repository : Command "git -c core.askpass=true ls-remote -h git@bitbucket.org:org/app.git HEAD" returned status code 128:
stdout:
stderr: Permission denied (publickey).
fatal: Could not read from remote repository.
```
##### Expected Result
should have loaded the key in pod (some how) and used the key in jenkins job thus created.

Is the pipeline jenkinsfile only supposed to be used from public repo with https:// and no credentials at the moment.

**Comment by bparees** [comment] 2016-10-31 18:04
dupe of https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/101

**Closed by bparees** 2016-10-31 18:04 UTC
Labels: component/build
