### ISSUE TITLE
oc cluster up. Issues when creating new project from template

### ISSUE THREAD

**Issue by samlabs821** [openshift/origin#10354] opened 2016-08-11 12:20 UTC
after running oc cluster up, all seems working normally. But I have created new project from template. The source code is also from github. This should build a project, while getting this error on all attempts:

error: cannot connect to the server: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

Can anyone explain how should things work. Didn't found in docs

Version 1.3.0.alpha.3
Fedora 24

**Comment by liggitt** [comment] 2016-08-11 12:22
sounds like a dupe of https://github.com/openshift/origin/issues/10215

**Closed by liggitt** 2016-08-11 12:22 UTC
