### ISSUE TITLE
Improve build validation error message

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6993] opened 2016-02-03 13:42 UTC
Some validation error messages include complex Go structs that are hard to understand by an end user.
## Reproducing the problem

Try to create a BuildConfig with multiple strategies:

``` console
$ oc create -f - <<EOF
{
  "kind": "List",
  "apiVersion": "v1",
  "metadata": {},
  "items": [
    {
      "kind": "BuildConfig",
      "apiVersion": "v1",
      "metadata": {
        "name": "busybox"
      },
      "spec": {
        "source": {
          "type": "Dockerfile",
          "dockerfile": "FROM busybox:1"
        },
        "strategy": {
          "type": "Docker",
          "dockerStrategy": {
            "from": {
              "kind": "ImageStreamTag",
              "name": "busybox:1"
            }
          },
          "sourceStrategy": {
            "forcePull": true
          }
        },
        "output": {
          "to": {
              "kind": "ImageStreamTag",
              "name": "busybox:latest"
          }
        }
      }
    }
  ]
}
EOF
The BuildConfig "busybox" is invalid.
spec.strategy: invalid value '<*>(0xc210a3fe90){DockerStrategy:<*>(0xc21131ae60){From:<*>(0xc208fd68c0){Kind:ImageStreamTag Namespace: Name:busybox:1 UID: APIVersion: ResourceVersion: FieldPath:} PullSecret:<nil> NoCache:false Env:<nil> ForcePull:false DockerfilePath:} SourceStrategy:<*>(0xc208dc2000){From:{Kind:ImageStreamTag Namespace: Name: UID: APIVersion: ResourceVersion: FieldPath:} PullSecret:<nil> Env:<nil> Scripts: Incremental:false ForcePull:true} CustomStrategy:<nil>}', Details: must provide a value for exactly one of sourceStrategy, customStrategy, or dockerStrategy
```

The error message shows up in any place that uses the API, including but not limited to `oc create`, `oc new-app`, `oc edit`, `oc patch`, etc.
## Possible offenders

```
./pkg/cmd/server/api/validation/validation.go
./pkg/template/api/validation/validation.go
./pkg/user/api/validation/validation.go
./pkg/image/api/validation/validation.go
./pkg/project/api/validation/validation.go
./pkg/project/admission/requestlimit/validation.go
./pkg/route/api/validation/validation.go
./pkg/sdn/api/validation/validation.go
./pkg/oauth/api/validation/validation.go
./pkg/deploy/api/validation/validation.go
./pkg/api/validation/validation.go
./pkg/authorization/api/validation/validation.go
./pkg/build/api/validation/validation.go
./pkg/build/admission/defaults/validation.go
```

Example:
https://github.com/openshift/origin/blob/master/pkg/build/api/validation/validation.go#L395

``` Go
field.Invalid(fldPath, strategy, "must provide a value for exactly one of sourceStrategy, customStrategy, or dockerStrategy")
```

Passing `strategy *buildapi.BuildStrategy` to `field.Invalid` results in an error message that includes ugly Go-specific string format for structs, pointers, etc.
## Proposal

Improve the message to have more readable information, perhaps rendering the invalid field as JSON.

The extra challenge would be to make the JSON rendered in the right API version using `runtime.Codec`. Using that is not straight forward because it is meant to convert top-level API objects across versions, and not arbitrary subparts of a top-level object. IOW, you can convert an `api.Build` to `v1.Build`, but not an `api.BuildStrategy` taken out of a build spec.

**Comment by rhcarvalho** [comment] 2016-02-03 13:42
@bparees FYI

**Comment by bparees** [comment] 2016-02-03 15:42
Can you provide a little more detail on how to recreate this?  what did you change in the BC?

but yeah, we should clean that up.

**Comment by php-coder** [comment] 2016-02-03 15:50
It looks pretty similar to #6926 
@kargakis Does #6959 fix this issue too?

**Comment by kargakis** [comment] 2016-02-03 15:50
Yes, this is a dupe of #6926

**Comment by bparees** [comment] 2016-02-03 19:00
closing as dupe.  thanks for researching @php-coder and @kargakis

**Comment by rhcarvalho** [comment] 2016-02-03 21:09
It is not a dupe. @bparees, can you please reopen it?

My issue is that in several error messages we dump Go structs, that have no
relation with the API format (JSON/YAML). In extremely ugly cases we are
even printing pointers, which just makes no sense.

It is not related to oc edit, as I emphasized, perhaps not enough, in the
original issue description.

To reproduce it, you can for example create a buildconfig and define both
dockerStrategy and sourceStrategy. The validation for strategy will return
an error with includes the Go %#v of build.Spec.Strategy, which makes
little sense to an API user.

**Comment by rhcarvalho** [comment] 2016-02-04 09:44
I've updated the issue description to include a more detailed example how to reproduce the problem.

**Comment by rhcarvalho** [comment] 2016-02-04 10:00
Looking at https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go, seems that in upstream they never use `field.Invalid` with a compound type.

For most usages I looked at, the second argument is always a string or number.

Cases when the problem is on a compound value, `""` is used: [pkg/api/validation/validation.go#L989](https://github.com/kubernetes/kubernetes/blob/0952dcd349d95b895894fb7133591c3126819944/pkg/api/validation/validation.go#L989)
```Go
	} else if numSources != 1 {
		allErrs = append(allErrs, field.Invalid(fldPath, "", "may not have more than one field specified at a time"))
	}
```


For the record, here's a place where Kube will generate an ugly message with a Go struct: [api/validation/validation.go#L1305](https://github.com/kubernetes/kubernetes/blob/0952dcd349d95b895894fb7133591c3126819944/pkg/api/validation/validation.go#L1305)

**Comment by rhcarvalho** [comment] 2016-07-25 12:31
@sttts, coincidentally I saw this today. This is a report on error messages that include Go structs, we were talking about it last week :)

**Closed** 2018-04-15 23:07 UTC
Labels: area/usability, component/build, lifecycle/rotten, priority/P3
