### ISSUE TITLE
[Feature:Builds] forcePull should affect pulling builder images obj conflict

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#17836] opened 2017-12-15 20:26 UTC
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:72
  
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:76
    ForcePull test case execution s2i [Suite:openshift/conformance/parallel] [BeforeEach]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:113

    Expected error:
        <*util.ExitError | 0xc4219604b0>: {
            Cmd: "oc adm --config=/tmp/cluster-admin.kubeconfig --namespace=extended-test-forcepull-pvzc4-9lxqb policy remove-cluster-role-from-user system:build-strategy-custom extended-test-forcepull-pvzc4-9lxqb-user",
            StdErr: "Error from server (Conflict): Operation cannot be fulfilled on clusterrolebindings.authorization.openshift.io \"system:build-strategy-custom\": the object has been modified; please apply your changes to the latest version and try again",
            ExitError: {
                ProcessState: {
                    pid: 18728,
                    status: 256,
                    rusage: {
                        Utime: {Sec: 0, Usec: 236823},
                        Stime: {Sec: 0, Usec: 30278},
                        Maxrss: 62468,
                        Ixrss: 0,
                        Idrss: 0,
                        Isrss: 0,
                        Minflt: 14803,
                        Majflt: 0,
                        Nswap: 0,
                        Inblock: 0,
                        Oublock: 0,
                        Msgsnd: 0,
                        Msgrcv: 0,
                        Nsignals: 0,
                        Nvcsw: 1663,
                        Nivcsw: 7,
                    },
                },
                Stderr: nil,
            },
        }
        exit status 1
    not to have occurred

    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:90

**Comment by bparees** [comment] 2017-12-15 23:07
dupe of https://github.com/openshift/origin/issues/17596

**Closed by bparees** 2017-12-15 23:07 UTC
Labels: component/build, kind/test-flake, priority/P2
