### ISSUE TITLE
Deployer container fails with "Cannot start container ... [8] System error: no such file or directory"

### ISSUE THREAD

**Issue by getrostt** [openshift/origin#4561] opened 2015-09-07 14:28 UTC
I installed Openshift Origin an CentOs7. When I create a registry using the following command:

```
oadm registry --config=/etc/openshift/master/admin.kubeconfig --credentials=/etc/openshift/master/openshift-registry.kubeconfig --service-account=registry
```

The command `oc get pods` has the following result:

```
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy   0/1       API error (404): Cannot start container 7a9afc172f18037f005ed481619052b2d89fcf3c0eca7de4d20e914ea937a166: [8] System error: no such file or directory
                           9         4m
```

Despite the situation described in [#2579](https://github.com/openshift/origin/issues/2579), I can run the docker image manually without errors using:

```
# docker run -it docker.io/openshift/origin-docker-registry
INFO[0000] version=v2.0.0+unknown                       
INFO[0000] redis not configured                          instance.id=75341005-906d-4989-803b-cee18716e125
INFO[0000] using inmemory layerinfo cache                instance.id=75341005-906d-4989-803b-cee18716e125
INFO[0000] Using Origin Auth handler                    
INFO[0000] Starting upload purge in 40m0s                instance.id=75341005-906d-4989-803b-cee18716e125
INFO[0000] listening on :5000                            instance.id=75341005-906d-4989-803b-cee18716e125
```

I am stuck where to look for the error? 

Regards,
Tobias

**Comment by y0no** [comment] 2015-09-23 14:29
Anything new on this issue ?

**Comment by vbatts** [comment] 2015-10-05 15:33
looks again like a binary may not have been statically linked, and could be failing to resolve something like libc.so.
like ejacobs and i found with the hello-openshift image. It will bubble up the same kind of "System error: no such file or directory" error.

**Comment by jwhonce** [comment] 2015-10-19 14:53
@y0no ^^ Does @vbatts comment apply?

**Comment by samsong8610** [comment] 2015-10-19 15:26
The pod docker-registry-1-deploy is the container to deploy registry, not registry itself.Have you ever deleted docker-registry-1-deploy and try to `oadm registry` again?
BTW, dose the service account registry exist? Try `oc get sa registry`.

**Comment by sbadakhc** [comment] 2015-11-28 02:24
I'm seeing the same issue with Openshift 3.1.  I can confirm the service account exists.
```
oc get sa 
NAME       SECRETS   AGE
builder    2         1h
default    2         1h
deployer   2         1h
registry   2         1h
router     3         1h
```

**Comment by pweil-** [comment] 2017-06-26 09:43
closing due to age.

**Closed by pweil-** 2017-06-26 09:43 UTC
Labels: component/imageregistry, priority/P2
