### ISSUE TITLE
[networking][router] openshift routers override the route host with a custom value flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11775] opened 2016-11-04 13:40 UTC
```
• Failure [174.405 seconds]
[networking][router] openshift routers
/data/src/github.com/openshift/origin/test/extended/router/scoped.go:135
  The HAProxy router
  /data/src/github.com/openshift/origin/test/extended/router/scoped.go:134
    should override the route host with a custom value [It]
    /data/src/github.com/openshift/origin/test/extended/router/scoped.go:133

    Expected error:
        <*errors.errorString | 0xc8200d3780>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/router/scoped.go:95
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8302/consoleFull#46994394856cbb9a5e4b02b88ae8c2f77

**Comment by knobunc** [comment] 2016-11-04 14:02
Looking back a hair more:

```
Nov  4 00:31:35.313: INFO: {Operation:remove_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:22.082175s}
Nov  4 00:31:35.313: INFO: {Operation:sync Method:pod_worker_latency_microseconds Quantile:0.99 Latency:16.187525s}
Nov  4 00:31:35.313: INFO: {Operation:sync Method:pod_worker_latency_microseconds Quantile:0.9 Latency:16.187525s}
STEP: Dumping a list of prepulled images on each node
Nov  4 00:31:35.316: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "extended-test-scoped-router-yk79x-hvyqw" for this suite.
Nov  4 00:32:20.393: INFO: namespace: extended-test-scoped-router-yk79x-hvyqw, resource: bindings, ignored listing per whitelist
```

The "INFO: Waiting up to 1m0s for all nodes to be ready" string seems to be the culprit, and that is common to many other flakes:
  https://github.com/openshift/origin/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Waiting%20up%20to%201m0s%20for%20all%20nodes%20to%20be%20ready

**Comment by knobunc** [comment] 2016-11-07 20:13
Can't reproduce and it's not happening after the initial flurry.  Dropping the priority.

**Comment by bparees** [comment] 2016-11-24 03:35
@knobunc just hit it again here https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/11666/

**Comment by bparees** [comment] 2016-11-24 03:36
or more specifically, here https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8858/

**Comment by stevekuznetsov** [comment] 2016-11-24 20:35
@knobunc this has continued to occur, don't feel like the priority drop should stay

**Comment by knobunc** [comment] 2016-11-29 18:22
Based on the information in @bparees' log, we are not starting the router-override pod within the 2 minute budget.  I think this is a dupe of https://github.com/openshift/origin/issues/11016

**Closed by knobunc** 2016-11-29 18:22 UTC
Labels: component/networking, kind/test-flake, priority/P1
