### ISSUE TITLE
Regression: Invalid selfLink for PersistentVolume

### ISSUE THREAD

**Issue by stefwalter** [openshift/origin#13881] opened 2017-04-25 07:08 UTC
The ```"metadata"``` ```"selfLink"``` field for ```PersistentVolume``` has invalid URLs in openshift v1.5.0+031cbe4

This was detected by the Cockpit integration tests, and breaks Cockpit functionality related to modifying of persistent volumes.

CC @petervo

##### Version

```
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```

##### Steps To Reproduce

```
# echo '{ "kind": "PersistentVolume","apiVersion": "v1","metadata": {"name": "fc-volume"},"spec": {"capacity": {"storage": "5Gi"},"fc": {"targetWWNs": ["target1"],"fsType": "ext4","lun": 1},"accessModes": ["ReadWriteMany"],"persistentVolumeReclaimPolicy": "Recycle"}}' | oc create -f -
# oc get pv fc-volume
```

##### Current Result

```
        "selfLink": "/api/v1/persistentvolumesfc-volume",
```

##### Expected Result

```
        "selfLink": "/api/v1/persistentvolumes/fc-volume",
```

**Comment by stefwalter** [comment] 2017-04-25 07:08
CC @dperpeet Is this worth creating a bugzilla bug for?

**Comment by stefwalter** [comment] 2017-04-25 07:08
Diagnostics:

```
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'default/10-111-112-101:8443/system:admin'

[Note] Running diagnostic: ConfigContexts[/10-111-112-101:8443/scruffy]
       Description: Validate client config context is complete and has connectivity
       
Info:  For client config context '/10-111-112-101:8443/scruffy':
       The server URL is 'https://10.111.112.101:8443'
       The user authentication is 'scruffy/10-111-112-101:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [marmalade pizzazz]
       
[Note] Running diagnostic: ConfigContexts[default/10-111-112-101:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
Info:  The current client config context is 'default/10-111-112-101:8443/system:admin':
       The server URL is 'https://10.111.112.101:8443'
       The user authentication is 'system:admin/10-111-112-101:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [default kube-system marmalade openshift openshift-infra pizzazz]
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
WARN:  [DCli2006 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:134]
       Timed out preparing diagnostic pod logs for streaming, so this diagnostic cannot run.
       It is likely that the image 'openshift/origin-deployer:v1.5.0' was not pulled and running yet.
       Last error: (*errors.StatusError[2]) Get https://f1.cockpit.lan:10250/containerLogs/default/pod-diagnostic-test-6xs88/pod-diagnostics?follow=true&limitBytes=1024000: dial tcp: lookup f1.cockpit.lan on [::1]:53: read udp [::1]:41417->[::1]:53: read: connection refused
       
[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
WARN:  [DNet2002 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:81]
       Skipping network diagnostics check. Reason: Not using openshift network plugin.
       
[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No master config file was provided
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
WARN:  [DClu1010 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:263]
       Failed to read the logs for the "docker-registry-1-c4rql" pod belonging to
       the "docker-registry" service. This is not a problem by itself but
       prevents diagnostics from looking for errors in those logs. The
       error encountered was:
       (*errors.StatusError) Get https://f1.cockpit.lan:10250/containerLogs/default/docker-registry-1-c4rql/registry: dial tcp: lookup f1.cockpit.lan on [::1]:53: read udp [::1]:45926->[::1]:53: read: connection refused
       
WARN:  [DClu1014 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:316]
       The "docker-registry" service exists with 1 associated pod(s), but there
       are 0 endpoints in the "docker-registry" service.
       This mismatch likely indicates a system bug, and builds and
       deployments that require the registry may fail sporadically.
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions
       
[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router
       
WARN:  [DClu2001 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:129]
       There is no "router" DeploymentConfig. The router may have been named
       something different, in which case this warning may be ignored.
       
       A router is not strictly required; however it is needed for accessing
       pods from external networks and its absence likely indicates an incomplete
       installation of the cluster.
       
       Use the 'oadm router' command to create a router.
       
[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)
       
Info:  Found a node with same IP as master: f1.cockpit.lan

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.
       
[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master
       
[Note] Skipping diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config
       Because: No master config file was detected
       
[Note] Summary of diagnostics execution (version v1.5.0+031cbe4):
[Note] Warnings seen: 5
```

**Comment by dperpeet** [comment] 2017-04-25 08:18
> CC @dperpeet Is this worth creating a bugzilla bug for?

I think it is

**Comment by stefwalter** [comment] 2017-04-25 08:23
> I think it is

Is there an easy way to map Openshift Origin versions to Openshift Container Platform versions?

**Comment by mfojtik** [comment] 2017-04-25 08:57
@dperpeet @stefwalter this is already reported in BZ and low priority... (you should not use the selfLinks for anything anyway).

**Comment by petervo** [comment] 2017-04-25 13:13
@mfojtik Do you have a link?

I would argue that since this breaks documented API, that for better or worse is already in use in the wild, fixing it is fairly important.

**Comment by enj** [comment] 2017-04-25 13:26
Dupe of #12553

**Closed by enj** 2017-04-25 13:26 UTC

**Comment by stefwalter** [comment] 2017-04-25 13:30
> you should not use the selfLinks for anything anyway

Could you provide a reference for that? Is there a list for which parts of the Openshift and/or Kubernetes API are deprecated and will be removed?
