### ISSUE TITLE
Deployer node selection should be more configurable

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#13874] opened 2017-04-24 15:33 UTC
The use case is not realistic yet, but will likely be needed eventually:
   I'm trying to run a pod in a Windows node, with a node selector of `beta.kubernetes.io/os: windows`. However, I want the deployer pod to run on a linux node, therefore it cannot inherit the node selector of the thing it's trying to deploy.

**Comment by csrwng** [comment] 2017-04-24 15:34
@kargakis

**Comment by kargakis** [comment] 2017-04-24 16:02
Similar rfe but for customizing tolerations: https://bugzilla.redhat.com/show_bug.cgi?id=1436357

cc: @mfojtik for prioritizing

**Comment by smarterclayton** [comment] 2017-04-25 05:06
Sigh...

**Comment by kargakis** [comment] 2017-05-02 15:24
Dupe of https://github.com/openshift/origin/issues/3507 but I am closing the older issue.

Copying over @ironcladlou's comment:

> The node selector assigned to the deployer pod is inherited from the deployment config template. This is a problem when:
> 1. The deployment's target nodes aren't available, causing the deployment to fail even though the deployment might be schedulable on other nodes.
> 2. The deployer pod has different resource requirements than the the deployment

> There's currently no escape hatch for a user to proceed: either a.) the deployer pod and the deployment template lack a node selector, or b) the deployer pod and the deployment template must share a node selector. We should consider making this more flexible. Some ideas:
> 1. Allow the deployer inheritance to be disabled with a boolean on the deployment config
> 2. Provide an explicit deployer node selector field on the deployment config
> 3. Both 1 and 2

**Comment by kargakis** [comment] 2017-05-02 15:27
@tnozicka @mfojtik we may want to think about using a separate pod template in the DeploymentStrategy.

**Closed** 2018-04-14 05:04 UTC
Labels: component/apps, kind/enhancement, lifecycle/rotten, priority/P2
