### ISSUE TITLE
Ugly CLI error during osc new-app

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1853] opened 2015-04-22 01:08 UTC
```
$ osc new-app openshift/ruby-20-centos7~https://github.com/ryanj/node-echo.git
Error: "/osapi/v1beta1/templates/openshift/ruby-20-centos7?namespace=satellite-content-2" is forbidden because test cannot get on templates/ruby-20-centos7 with name "openshift" in satellite-content-2
```

**Comment by smarterclayton** [comment] 2015-04-22 01:09
We should nuke that URL in the message - it adds nothing for the end user.  Since status can add a cause we should try to keep the message short an succinct.

@deads2k

**Comment by bparees** [comment] 2015-04-27 13:12
also is "name" really "namespace" at the end of that message?

**Comment by bparees** [comment] 2015-04-27 13:12
would also help to say "user test" not just "test" (assuming "test" is a user here...)

**Comment by deads2k** [comment] 2015-04-27 13:12
> also is "name" really "namespace" at the end of that message?

No, it is really name.

**Comment by bparees** [comment] 2015-04-27 13:14
ok so it's the name of what?

what exactly is this message telling me?  why were we even trying to get a template here?  I would have assumed openshift/ruby-20-centos7 referred to an imagestream or an image, not a template, particularly given that it's being combined with a source url.

**Comment by smarterclayton** [comment] 2015-04-27 13:15
Templates can be combined with source urls.

----- Original Message -----

**Comment by deads2k** [comment] 2015-04-27 13:17
I don't know why the calling code decided to get a template and I suspect that the calling code has busted objectmeta validation, but it's requesting this: `/osapi/v1beta1/templates/openshift/ruby-20-centos7?namespace=satellite-content-2` (look, a reason to keep it).

In that url, it is looking `osapi` objects, in the `v1beta1` version, with a resource type of `templates`, using a name `openshift`, with a subresource `ruby-20-centos7`, in the namespace `satellite-content2`.    That's just a straight reading of the url.  Why the cli tool is requesting that is a question for the guy who wrote that cli command.

**Comment by bparees** [comment] 2015-04-27 13:19
@smarterclayton what's the outcome when you combine a template with a source url?  what does the source url get combined with?  (if the template contains no Builder imagestream?  if the template contains 2 builder imagestreams?  if the template contains no source-uri section?  if it contains 2?)

**Comment by smarterclayton** [comment] 2015-04-27 13:22
If the template has a single build with a source url.  All other cases are ambiguous and we return an error.

----- Original Message -----

**Comment by bparees** [comment] 2015-04-27 13:22
@deads2k then i would expect it to say simply "cannot get on templates/openshift/ruby-20-centos7"

or else i'd expect it to say "cannot get on subresource "ruby-20-centos7" of resource named "openshift" of type "template" or something like that.

**Comment by smarterclayton** [comment] 2015-04-27 13:23
----- Original Message -----
> I don't know why the calling code decided to get a template and I suspect
> that the calling code has busted objectmeta validation, but it's requesting
> this:
> `/osapi/v1beta1/templates/openshift/ruby-20-centos7?namespace=satellite-content-2`
> (look, a reason to keep it).

No.  Because not a single person would understand that.

It was because the code that looked at the namespace openshift didn't properly handle forbidden errors, which is now fixed.

> 
> In that url, it is looking `osapi` objects, in the `v1beta1` version, with a
> resource type of `templates`, using a name `openshift`, with a subresource
> `ruby-20-centos7`, in the namespace `satellite-content2`.    That's just a
> straight reading of the url.  Why the cli tool is requesting that is a
> question for the guy who wrote that cli command.

When we correctly identify the url type, we shouldn't show the URL.  We should reserve showing the URL for when we don't recognize the type.

**Comment by deads2k** [comment] 2015-04-27 13:25
> No.  Because not a single person would understand that.

You're saying, "if it didn't help Ben, it won't help anyone"?  :)

**Comment by smarterclayton** [comment] 2015-04-27 13:31
Exactly.

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-04-27 13:34
Ugh, subresource is also something no one will understand (although we want an experienced person to know that its a subresource).

**Comment by bparees** [comment] 2015-04-27 14:05
to be fair, i ignored the content of the url because the original suggestion was it should be eliminated, so i tried to parse the error w/o referring to it :)

**Comment by bparees** [comment] 2015-04-27 14:07
how about  "cannot get on resource "openshift/ruby-20-centos7" of type "template""

**Comment by deads2k** [comment] 2015-04-27 14:08
The resource in this case `template/ruby-20-centos7`

**Comment by smarterclayton** [comment] 2015-04-27 14:13
Maybe we're trying to hard to make a sentence.  User needs to know they don't have permission to access something, and the generic verbs don't work well anyway (get / post / put).  The goal needs to be to describe to the user as accurately as possible what failed.  I think we need to make this more sophisticated in general and stop trying to make the generic sentence work

----- Original Message -----

**Comment by deads2k** [comment] 2015-05-15 18:30
dupe of https://github.com/openshift/origin/issues/1558

**Closed** 2015-05-15 18:56 UTC
Labels: area/usability, component/cli, priority/P2
