### ISSUE TITLE
[k8s.io] Projected should update labels on modification [Conformance] [sig-storage] [Suite:openshift/conformance/parallel] [Suite:k8s]

### ISSUE THREAD

**Issue by enj** [openshift/origin#17697] opened 2017-12-08 18:05 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17617/test_pull_request_origin_extended_conformance_install/3778/

```
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/projected.go:864
Timed out after 120.000s.
Expected
    <string>: content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    
to contain substring
    <string>: key3="value3"
    
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/projected.go:863
```

Maybe related to https://github.com/kubernetes/kubernetes/issues/44227 ?

**Comment by bparees** [comment] 2017-12-21 02:06
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17314/test_pull_request_origin_extended_conformance_install/4489/

**Comment by simo5** [comment] 2018-01-05 20:08
I just hit this one twice in a row.
@childsb @ingvagabund any ETA to fix it ?

**Comment by michaelgugino** [comment] 2018-01-10 15:35
We see this on about 40% of openshift-ansible runs.  It's really tanking CI performance for us.  I think this should be a P1.

**Comment by dcbw** [comment] 2018-01-23 19:04
Dupe of https://github.com/openshift/origin/issues/17556 ?

**Comment by bparees** [comment] 2018-01-23 22:49
looks like it.

**Comment by bparees** [comment] 2018-01-23 22:50
wait, one is annotations and one is labels.  *might* be the same, but it's two different tests.

**Comment by bparees** [comment] 2018-01-23 22:50
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18250/test_pull_request_origin_extended_conformance_install/6185/

**Comment by smarterclayton** [comment] 2018-01-24 16:03
I'm closing in favor of the centralized one #17697

**Closed by smarterclayton** 2018-01-24 16:03 UTC
Labels: kind/test-flake, priority/P1, sig/storage
