### ISSUE TITLE
"oc rsh" does not scale to terminal size

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#10859] opened 2016-09-09 09:14 UTC
When doing `oc rsh` I always get terminal with 80 columns even my outer terminal has about 190. This also causes long commands to be undreadable when pasted from clipboard.
##### Version

``` bash
$ oc version
oc v1.3.0-rc1+31f2273-dirty
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://192.168.42.42:8443
openshift v1.3.0-alpha.3+7f59726
kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce
1. Have a terminal window with width of more than 80 columns
2. $ tput cols
3. $ oc rsh <some pod>
4. pod $ tput cols
##### Current Result

Number of columns differ in an outer terminal and when using `oc rsh`.
##### Expected Result

The terminal should be of same size.

**Comment by fabianofranz** [comment] 2016-09-09 15:45
@ncdc is there anything we need to adjust in `rsh` to have the same resizing behavior of `exec`?

**Comment by ncdc** [comment] 2016-09-09 15:47
@fabianofranz this should have been fixed by #9529

**Comment by ncdc** [comment] 2016-09-09 15:52
cc @jwendell

**Comment by ncdc** [comment] 2016-09-09 15:52
@tnozicka what image are you using?

**Comment by tnozicka** [comment] 2016-09-09 16:15
@ncdc I was testing with openshift/jenkins-1-centos7:latest

**Comment by ncdc** [comment] 2016-09-09 17:13
I'm unable to reproduce the issue

**Comment by tnozicka** [comment] 2016-09-09 20:58
Btw. I am running zsh on my laptop, not bash; if it helps.

**Comment by juanvallejo** [comment] 2016-09-12 20:38
Tested using `zsh` as well. Here are my results:

0. Have a terminal window with width of more than 80 columns
1. `$ tput cols`
 - `238`
2. `oc rsh <mypod>`
3. `<mypod>$ tput cols`
 - `80`
4. *resize terminal window to any size, then resize back to initial size*
5. `<mypod>$ tput cols`
 - `238`

From what I can tell, `oc rsh` does not pick up the updated terminal size until *after* the terminal window is resized at least once after executing `oc rsh`.

**Comment by ncdc** [comment] 2016-09-12 20:42
The terminal resizing code we added to 1.3 does a resize +1/-1 behind the
scenes to simulate you resizing the window, as that's needed for the
container to recognize you've detached and reattached and the screen size
might be different. Can you test with bash vs zsh and see if maybe this is
a zsh thing?

**Comment by juanvallejo** [comment] 2016-09-12 20:51
@ncdc 
> Can you test with bash vs zsh and see if maybe this is
> a zsh thing?

Tested with bash 4.3.42 (GNU bash, version 4.3.42(1)-release (x86_64-redhat-linux-gnu))
Same results as zsh, `oc rsh` does not pickup actual terminal size until it is resized *after* executing `oc rsh`.

zsh version: `zsh 5.1.1 (x86_64-redhat-linux-gnu)`
oc version: 
```
oc v1.3.0-alpha.0+340de34-dirty
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-alpha.0+b89b290-dirty
kubernetes v1.3.0+507d3a7
```

Additionally, when I run `tput` through `oc exec` in `zsh` and `bash`, I receive the following output:
`$ oc exec <mypod> -- /bin/sh -c "tput cols"`
```
tput: No value for $TERM and no -T specified
error: error executing remote command: error executing command in container: Error executing in Docker Container: 2
```

**Comment by ncdc** [comment] 2016-09-12 21:00
Ok, when I tested it last, with bash, no resizing was necessary. I will retest tonight/tomorrow.

Your `oc exec` example above is missing the `-t` tty flag. Additionally, if you container in your pod wasn't created with tty=true, then you'll have to set `TERM` as part of your exec session.

BTW, what docker version and what image were you testing with?

**Comment by juanvallejo** [comment] 2016-09-12 22:16
@ncdc 
> BTW, what docker version and what image were you testing with?

Docker version: `Docker version 1.12.1, build 23cf638`
Pod image: `openshift/mysql-55-centos7:latest`

**Comment by juanvallejo** [comment] 2018-03-12 15:21
This is fixed in latest master.

**Closed by juanvallejo** 2018-03-12 15:21 UTC
Labels: component/cli, lifecycle/rotten, priority/P2

**Comment by phmarek** [comment] 2022-09-09 08:34
Using `oc 4.8.0-202204211825.p0.g41ff67e.assembly.stream-41ff67e`, running `oc debug` (and `oc exec`, etc.) have a wrong initial terminal size.

`strace ... oc debug ... -n ... --image ... --tty -- bash -l` shows

```strace
1179437 10:25:58.050476 ioctl(1, TIOCGWINSZ <unfinished ...>
1179431 10:25:58.050503 <... nanosleep resumed>NULL) = 0
1179437 10:25:58.050529 <... ioctl resumed>, {ws_row=24, ws_col=80, ws_xpixel=804, ws_ypixel=532}) = 0
```

so the local terminal size is correctly seen as `80`, yet a `tput cols` in the remote shell says `81`.
Perhaps the `size-1` got lost somewhere, and only `size+1` is still there?

Manually changing the font size in my `xterm` is enough to get the correct `tput lines` and `tput cols` outputs.

(Locally: `xterm=372-1`, no `screen` or `tmux`, though that shouldn't make any difference - the reported size in the `TIOCGWINSZ` is correct, after all)
