### ISSUE TITLE
oc idle -n myproject --all selecting the current namespace

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#11850] opened 2016-11-09 01:48 UTC
The command `oc idle -n myproject --all` is idling the resources in the current project and myproject

##### Version
openshift/origin:latest

##### Steps To Reproduce

Start pod openshift/origin in the project infra with the following serviceaccount

```
oc create serviceaccount openshift-idler
oc adm policy add-cluster-role-to-user edit system:serviceaccount:infra:openshift-idler
oc adm policy add-cluster-role-to-user view system:serviceaccount:infra:openshift-idler
```

run command

`oc idle -n myproject --all`

##### Current Result

Idles resources in myproject and infra

##### Expected Result

Idles resources only in myproject

**Comment by andrewklau** [comment] 2016-11-09 02:43
Issue was KUBECONFIG was not writable. The error message does not show unless you explicitly switch project.

Setting KUBECONFIG to a location that the user can write to fixes the issue.

**Comment by liggitt** [comment] 2016-11-09 03:11
Idle should respect the namespace parameter regardless of kubeconfig.

**Comment by fabianofranz** [comment] 2016-11-09 20:55
I could not reproduce this issue. Even with a not writable KUBECONFIG the `oc idle` command respected the `-n` flag correctly. 

```
$ oc deploy dc/ruby-ex -n myproject
ruby-ex deployment #1 deployed 42 minutes ago - 1 pod

$ oc deploy dc/ruby-ex -n myproject2
ruby-ex deployment #1 deployed 34 minutes ago - 1 pod

$ oc project
Using project "myproject2" on server "https://192.168.2.200:8443".

$ oc idle --all -n myproject
Marked service myproject/ruby-ex to unidle resource DeploymentConfig myproject/ruby-ex (unidle to 1 replicas)
Idled DeploymentConfig myproject/ruby-ex

$ oc deploy dc/ruby-ex -n myproject
ruby-ex deployment #1 deployed 42 minutes ago - 0 pods

$ oc deploy dc/ruby-ex -n myproject2
ruby-ex deployment #1 deployed 34 minutes ago - 1 pod
```

I'm closing this issue, feel free to reopen if it still happens with more information about how it can be reproduced.

**Closed by fabianofranz** 2016-11-09 20:55 UTC
Labels: component/cli, kind/bug, priority/P1

**Comment by andrewklau** [comment] 2016-11-09 21:47
@fabianofranz perhaps a serviceaccount permission issue? 

These are the steps I did to reproduce on both 1.3.1 and latest

```
oc create serviceaccount openshift-idler

oc adm policy add-cluster-role-to-user edit system:serviceaccount:project1:openshift-idler
oc adm policy add-cluster-role-to-user view system:serviceaccount:project1:openshift-idler

oc create -f https://raw.githubusercontent.com/ausnimbus/docker-openshift-idler/master/openshift-idler.yaml

oc rsh openshift-idler
rm /tmp/.kubeconfig
oc idle -n project2 --all
```
