### ISSUE TITLE
Builds are taking very long time using s2i on stage Committing container with dockerOpts

### ISSUE THREAD

**Issue by sudhirpandey** [openshift/origin#12688] opened 2017-01-27 11:08 UTC
We have a node js app that takes a lot of time to be build, we have tried to debug what is going through setting the buildlog level to 5, and it seems  state below is taking more than 10 mins of build time

```
I0127 10:19:45.093109 docker.go:882] Committing container with dockerOpts: {Container:19894b2ef099af2eb517473936ec6c4c28ba434c54223c51f416725cf46c9368 Repository:core-dev/corefront-react-60 Tag:01b90f3b Message: Author: Run:0xc8201c6380}, config: {Hostname: Domainname: User:1001 Memory:0 MemorySwap:0 MemoryReservation:0 KernelMemory:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:false AttachStderr:false PortSpecs:[] ExposedPorts:map[] StopSignal: Tty:false OpenStdin:false StdinOnce:false Env:...

I0127 10:29:58.694961       1 postexecutorstep.go:362] Executing step: report success

```
The behaviour is when it reaches `Committing container with dockerOpts: ` the build just waits there for a while (10min) and then
The actual push to docker internal registry is fast though. the size of image is 700MB and  takes less than 1min 30 second to push

```
017-01-27T10:09:28.119833401Z Pushing image..
2017-01-27T10:09:30.261744464Z Pushed 3/4 layers, 75% complete
2017-01-27T10:10:00.279807764Z Pushed 3/4 layers, 85% complete
2017-01-27T10:10:30.300929201Z Pushed 3/4 layers, 94% complete
2017-01-27T10:11:00.339765099Z Pushed 3/4 layers, 100% complete
2017-01-27T10:11:12.875903596Z Pushed 4/4 layers, 100% complete
2017-01-27T10:11:13.328136709Z Push successful
```
So i am just wondering what is happening on the above stage and see which component is not behaving right.

We have couple of other apps that does not show this behavior at all.

##### Version
```
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4

docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.14.x86_64
 Go version:      go1.6.2
 Git commit:      5206701-unsupported
 Built:           Mon Aug 29 14:00:01 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.14.x86_64
 Go version:      go1.6.2
 Git commit:      5206701-unsupported
 Built:           Mon Aug 29 14:00:01 2016
 OS/Arch:         linux/amd64
```

##### Expected Result
The build show have completed in less than 3 min.

**Comment by bparees** [comment] 2017-01-30 15:17
it's literally doing a docker commit.  Can you give us steps to reproduce with your repo?  Is it possible your nodejs build is landing on a different node than your other builds and you have an unhealthy docker daemon?

**Comment by bparees** [comment] 2017-02-07 23:55
closing due to lack of information, will reopen if requested information is provided.

**Closed by bparees** 2017-02-07 23:55 UTC
Labels: component/build, kind/bug, priority/P2
