### ISSUE TITLE
[flake] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/event/etcd.TestDelete

### ISSUE THREAD

**Issue by eparis** [openshift/origin#13485] opened 2017-03-21 15:25 UTC
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/165/testReport/junit/github.com_openshift_origin_vendor_k8s/io_kubernetes_pkg_registry_core_event_etcd/TestDelete/
```
=== RUN   TestDelete
2017-03-21 14:22:30.955023 I | integration: launching 4536839067055683264 (unix://localhost:45368390670556832640)
2017-03-21 14:22:30.956182 I | etcdserver: name = 4536839067055683264
2017-03-21 14:22:30.956267 I | etcdserver: data dir = /openshifttmp/etcd197674038
2017-03-21 14:22:30.956327 I | etcdserver: member dir = /openshifttmp/etcd197674038/member
2017-03-21 14:22:30.956381 I | etcdserver: heartbeat = 10ms
2017-03-21 14:22:30.956426 I | etcdserver: election = 100ms
2017-03-21 14:22:30.956475 I | etcdserver: snapshot count = 0
2017-03-21 14:22:30.956530 I | etcdserver: advertise client URLs = unix://127.0.0.1:2100616715
2017-03-21 14:22:30.956597 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:2100516715
2017-03-21 14:22:30.956673 I | etcdserver: initial cluster = 4536839067055683264=unix://127.0.0.1:2100516715
2017-03-21 14:22:30.983490 I | etcdserver: starting member 7f1526f1c0b24cac in cluster b6f9385f6c39d8e8
2017-03-21 14:22:30.983630 I | raft: 7f1526f1c0b24cac became follower at term 0
2017-03-21 14:22:30.983724 I | raft: newRaft 7f1526f1c0b24cac [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-03-21 14:22:30.983817 I | raft: 7f1526f1c0b24cac became follower at term 1
unexpected fault address 0xc420e80000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc420e80000 pc=0x1681fc5]

goroutine 305 [running]:
runtime.throw(0x1abef59, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4205f4fe8 sp=0xc4205f4fc8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4205f5040 sp=0xc4205f4fe8
github.com/openshift/origin/vendor/github.com/boltdb/bolt.(*node).write(0xc420268380, 0xc420e7fff0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/boltdb/bolt/node.go:205 +0x195 fp=0xc4205f51d8 sp=0xc4205f5040
github.com/openshift/origin/vendor/github.com/boltdb/bolt.(*Bucket).write(0xc4205f5348, 0x68, 0x3, 0x7fb25c004077)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/boltdb/bolt/bucket.go:598 +0x11f fp=0xc4205f5238 sp=0xc4205f51d8
github.com/openshift/origin/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc420330b78, 0x24713a6, 0x3, 0x3, 0x7fb4f0021958, 0xc420e7f300, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/boltdb/bolt/bucket.go:181 +0x545 fp=0xc4205f5390 sp=0xc4205f5238
github.com/openshift/origin/vendor/github.com/boltdb/bolt.(*Tx).CreateBucket(0xc420330b60, 0x24713a6, 0x3, 0x3, 0x60c3de, 0xc420e7f300, 0xc4205f5478)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/boltdb/bolt/tx.go:108 +0x61 fp=0xc4205f53f0 sp=0xc4205f5390
github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).UnsafeCreateBucket(0xc420e7f300, 0x24713a6, 0x3, 0x3)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:53 +0xa4 fp=0xc4205f54a0 sp=0xc4205f53f0
github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc.NewStore(0x248e480, 0xc420b232c0, 0x248fe20, 0xc420b23f80, 0x2473f40, 0xc420206dd8, 0x1c43c80)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/kvstore.go:116 +0x3d6 fp=0xc4205f5568 sp=0xc4205f54a0
github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc.newWatchableStore(0x248e480, 0xc420b232c0, 0x248fe20, 0xc420b23f80, 0x2473f40, 0xc420206dd8, 0xc420b23f80)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:73 +0x92 fp=0xc4205f5608 sp=0xc4205f5568
github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc.New(0x248e480, 0xc420b232c0, 0x248fe20, 0xc420b23f80, 0x2473f40, 0xc420206dd8, 0x2490140, 0xc420b237a0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:68 +0x6f fp=0xc4205f5658 sp=0xc4205f5608
github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc420e7b200, 0xc420206dc0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/etcdserver/server.go:448 +0x1a4a fp=0xc4205f5cc0 sp=0xc4205f5658
github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.(*member).Launch(0xc420e7b200, 0x0, 0xc420a537a0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/cluster.go:593 +0x1d1 fp=0xc4205f5f58 sp=0xc4205f5cc0
github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.(*cluster).Launch.func1(0xc420b22f60, 0xc420e7b200)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/cluster.go:159 +0x39 fp=0xc4205f5f90 sp=0xc4205f5f58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4205f5f98 sp=0xc4205f5f90
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.(*cluster).Launch
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/cluster.go:160 +0xe9

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42039c180, 0x1ac4e8f, 0xa, 0x1c49df8, 0x4c0601)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc42039c180)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc42039c180, 0xc420229d20)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x1c4a090, 0x24d70e0, 0x3, 0x3, 0x0)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420229ef0, 0x30)
	/usr/local/go/src/testing/testing.go:743 +0x130
main.main()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/event/etcd/_test/_testmain.go:104 +0x2f9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 34 [chan receive]:
github.com/openshift/origin/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x24e5120)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:879 +0x9e
created by github.com/openshift/origin/vendor/github.com/golang/glog.init.1
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/golang/glog/glog.go:410 +0x23b

goroutine 45 [chan receive]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc42039a9a0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0xb5
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x125

goroutine 303 [chan receive]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.(*cluster).Launch(0xc420e7ec00, 0xc42061a180)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/cluster.go:163 +0x17b
github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.NewClusterV3(0xc42061a180, 0xc4204b3b00, 0x51b601)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/cluster.go:841 +0x13e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing.NewUnsecuredEtcd3TestClientServer(0xc42061a180, 0x101c4204b3580, 0x15)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:315 +0xd0
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage(0xc42061a180, 0x0, 0x0, 0x0, 0xc400000000)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:40 +0x51
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/event/etcd.newStorage(0xc42061a180, 0xc42005c9c0, 0x0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/event/etcd/etcd_test.go:32 +0x63
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/event/etcd.TestDelete(0xc42061a180)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/registry/core/event/etcd/etcd_test.go:90 +0x40
testing.tRunner(0xc42061a180, 0x1c49df8)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530

goroutine 7 [chan receive]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc420446520)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0xb5
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x125

goroutine 340 [syscall]:
syscall.Syscall6(0x11d, 0xa, 0x0, 0x0, 0x3d09000, 0x0, 0x0, 0x1, 0xc420088aa8, 0xc420a6cd80)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Fallocate(0xa, 0x0, 0x0, 0x3d09000, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:399 +0x80
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/fileutil.preallocExtend(0xc420088aa0, 0x3d09000, 0x0, 0xc420088aa8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/fileutil/preallocate_unix.go:26 +0x68
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/fileutil.Preallocate(0xc420088aa0, 0x3d09000, 0x1, 0xc400000180, 0xc420088aa8)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/fileutil/preallocate.go:26 +0x50
github.com/openshift/origin/vendor/github.com/coreos/etcd/wal.(*filePipeline).alloc(0xc4201e0240, 0x1c4a678, 0xc420b235c0, 0x248e500)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/wal/file_pipeline.go:72 +0x2dc
github.com/openshift/origin/vendor/github.com/coreos/etcd/wal.(*filePipeline).run(0xc4201e0240)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/wal/file_pipeline.go:84 +0x9f
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/wal.newFilePipeline
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/wal/file_pipeline.go:47 +0x1e8

goroutine 342 [runnable]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/lease.(*lessor).runLoop(0xc420b23f80)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/lease/lessor.go:422
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/lease.newLessor
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/lease/lessor.go:169 +0x2da

goroutine 304 [IO wait]:
net.runtime_pollWait(0x7fb4f474a090, 0x72, 0x413a23)
	/usr/local/go/src/runtime/netpoll.go:160 +0x5e
net.(*pollDesc).wait(0xc420563870, 0x72, 0x4102d8, 0x1942c20)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x5b
net.(*pollDesc).waitRead(0xc420563870, 0x247c380, 0xc42007a080)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x42
net.(*netFD).accept(0xc420563810, 0x0, 0x2479bc0, 0xc420e7f2a0)
	/usr/local/go/src/net/fd_unix.go:419 +0x2b8
net.(*UnixListener).accept(0xc420e7f120, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:158 +0x51
net.(*UnixListener).Accept(0xc420e7f120, 0xc420acbf30, 0xc420acbf40, 0x45c150, 0xc420acbf30)
	/usr/local/go/src/net/unixsock.go:229 +0x50
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/transport.(*unixListener).Accept(0xc4203dc100, 0x1c43c58, 0xc420b22f00, 0x38d2368800495851, 0xed0632e26)
	<autogenerated>:91 +0x69
github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.(*bridge).serveListen(0xc420b22f00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/bridge.go:90 +0x91
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/integration.newBridge
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/integration/bridge.go:54 +0x466

goroutine 341 [select]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/raft.(*node).run(0xc420b237a0, 0xc420344e10)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/raft/node.go:309 +0x134a
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/raft.StartNode
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/raft/node.go:206 +0x800

goroutine 339 [select]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc420b232c0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:193 +0x26b
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/backend.newBackend
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:119 +0x29e

goroutine 343 [runnable]:
github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc42064a120)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:130
created by github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x2e8
```

**Comment by smarterclayton** [comment] 2017-03-21 17:12
Boom!

**Comment by smarterclayton** [comment] 2017-03-21 17:14
https://github.com/boltdb/bolt/issues/661

**Comment by derekwaynecarr** [comment] 2017-03-22 14:30
isnt this a duplicate of the same basic problem exposed:
https://github.com/openshift/origin/issues/13068

**Comment by smarterclayton** [comment] 2017-03-22 16:18
yeah, dupe

**Closed by smarterclayton** 2017-03-22 16:18 UTC
Labels: component/kubernetes, kind/test-flake, priority/P1
