### ISSUE TITLE
kubectl negotiate is too aggressive

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4053] opened 2015-08-07 22:38 UTC
There are CLI commands that don't require connecting to the server, but kubectl clientcache _always_ hits the server in its initialization phase.  We should only negotiate during login, and be able to bypass the clientcache behavior.

@deads2k

**Comment by liggitt** [comment] 2015-08-07 22:44
Dupe of https://github.com/openshift/origin/issues/3997

**Comment by smarterclayton** [comment] 2015-08-07 22:53
Mines better

**Comment by liggitt** [comment] 2015-08-07 22:58
Closing either one is fine

**Comment by smarterclayton** [comment] 2015-08-07 22:59
I don't care

On Aug 7, 2015, at 6:58 PM, Jordan Liggitt <notifications@github.com> wrote:

Closing either one is fine

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4053#issuecomment-128853467>.

**Comment by smarterclayton** [comment] 2015-08-23 20:25
What's awesome is *every* *single* cli command in a remote zone having to negotiate.  Fun.

```
I0823 16:24:54.818004   38106 debugging.go:120] GET https://openshift-master.rio.openshift3roadshow.com:8443/api 200 OK in 662 milliseconds
I0823 16:24:54.980968   38106 debugging.go:120] GET https://openshift-master.rio.openshift3roadshow.com:8443/oapi/v1/namespaces/demo/buildconfigs 200 OK in 162 milliseconds
I0823 16:24:55.145529   38106 debugging.go:120] GET https://openshift-master.rio.openshift3roadshow.com:8443/oapi/v1/namespaces/demo/builds 200 OK in 163 milliseconds
```

**Comment by fabianofranz** [comment] 2015-09-08 19:24
Not fun.

**Comment by deads2k** [comment] 2015-09-08 19:38
> Not fun.

After my chart-ware, I promise.

**Comment by deads2k** [comment] 2015-09-10 12:49
Turns out this is bigger than a breadbox.  The api-version is used to create the codec used by the RESTClient and that codec is exposed and used.  Some refactoring could move the negotiation later in the cycle to allow some commands to run without a server, but that doesn't really satisfy the "stop negotiating every time" problem.  To satisfy that with the current information, I'd have to be able to re-encode requests and replay them based on API server responses that are less than specific.

I've opened https://github.com/kubernetes/kubernetes/issues/13794 to try to find another way.

**Comment by liggitt** [comment] 2015-10-20 15:20
This is much worse now that `oc` uses negotiate.

**Comment by derekwaynecarr** [comment] 2015-10-20 15:25
This should be P0, all CLI interactions block ;-)

**Comment by liggitt** [comment] 2015-10-20 16:57
block on all commands fixed in https://github.com/openshift/origin/pull/5230

**Closed** 2018-04-06 04:45 UTC
Labels: component/cli, lifecycle/rotten, priority/P2
