### ISSUE TITLE
Cannot add more than one label when creating app

### ISSUE THREAD

**Issue by joeburke30** [openshift/origin#2650] opened 2015-06-01 17:40 UTC
in UI only,   Can only add one label.   Would like to be able to add multiples.

**Comment by liggitt** [comment] 2015-06-01 17:41
should be able to add multiple

**Comment by liggitt** [comment] 2015-06-02 15:14
@spadgett can you reproduce?

**Comment by spadgett** [comment] 2015-06-02 15:15
@joeburke30 I wasn't able to reproduce. What browser are you using?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/7939335/8901bd6e-0918-11e5-8161-b9187d8442ef.png)

**Comment by spadgett** [comment] 2015-06-17 15:15
@joeburke30 still seeing this?

**Comment by spadgett** [comment] 2015-06-29 15:01
@joeburke30 Any chance you were creating two labels with the same name? See #3436

**Comment by jwforres** [comment] 2015-09-03 20:46
Closing since this was not recreatable

**Closed by jwforres** 2015-09-03 20:46 UTC
Labels: component/web, kind/bug, priority/P3
