### ISSUE TITLE
Build logs streaming gets stuck after a while

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/origin#14252] opened 2017-05-19 09:17 UTC
Build logs streaming gets stuck after a while

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server xxxxxxxxx
openshift v3.4.1.10
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Start a build either from the GUI or from oc tool
2. Run oc logs -f to see the build logs

##### Current Result
The logs start streaming in the console but after a while it stops printing new logs and it gets stuck, even after the build has finished successfully

##### Expected Result
The build logs are streamed continuously in the console until the build finishes either successfully or with failure. Then the oc logs command exits

##### Additional Information
It happens the same if you follow build logs in Web console. After a while it stops printing new logs and you have to reload the page in order to see the new logs.

**Comment by jwforres** [comment] 2017-05-19 11:28
@GolanTrevize10 just confirming, you see the logs get stuck when you follow them on the CLI as well? Or you only see the logs get stuck in the console.

This sounds similar to what we were seeing yesterday @spadgett

**Comment by GolanTrevize10** [comment] 2017-05-19 11:44
The logs get stuck in both in the console and in the CLI, and they both get stuck in the same point.

**Comment by jwforres** [comment] 2017-05-19 12:52
given this is happening to both of the clients I suspect this is a server-side issue with either builds or pod logs.  just realized this was reported against 3.4 too.

**Comment by bparees** [comment] 2017-05-19 15:46
@jwforres what were you seeing yesterday?  i'd much rather chase this on master code... :)

**Comment by jwforres** [comment] 2017-05-19 16:06
@bparees yesterday's issue might be different, @spadgett was seeing the build completing but the websocket was never closing. It looked like we were getting the full log back though.  Whereas on this issue it sounds like the log streaming is actually getting stuck partway.

**Comment by bparees** [comment] 2017-05-19 17:41
@ncdc @gabemontero was the log hanging issue you guys were talking about something that could stretch back to 3.4, or was it a more recent regression?

**Comment by ncdc** [comment] 2017-05-19 17:47
@bparees I don't know how far back what @gabemontero was looking at might go. I'm not aware of any specific problem with following logs (that doesn't mean there isn't one, however).

**Comment by gabemontero** [comment] 2017-05-19 17:49
I only started noticing it during 3.6 development.

**Comment by ncdc** [comment] 2017-05-19 17:52
And that was after the kube 1.6 rebase merged, wasn't it? Or before?

**Comment by gabemontero** [comment] 2017-05-19 18:11
On Fri, May 19, 2017 at 1:53 PM, Andy Goldstein <notifications@github.com>
wrote:

> And that was after the kube 1.6 rebase merged, wasn't it? Or before?
>

Yep only started noticing after the 1.6 rebase landed.

**Comment by bparees** [comment] 2017-07-07 01:12
i haven't heard any further reporting of this so i'm going to close it under the assumption the underlying issue has been fixed in kube, but @GolanTrevize10 @jwforres @spadgett @gabemontero if any of you are aware of it still being an issue, please reopen and we'll try to investigate.

**Closed by bparees** 2017-07-07 01:12 UTC
Labels: component/build, kind/bug, priority/P2

**Comment by GolanTrevize10** [comment] 2017-07-12 14:49
It is still and issue. Will it be solved in new version of Openshift? Btw, with jenkins plugin it seems it works correctly.

**Comment by bparees** [comment] 2017-07-12 14:57
my "haven't heard any further reporting" referred to against our master (which is about to ship as v3.6).  So that is my assumption, that it is resolved in 3.6.

**Comment by gabemontero** [comment] 2017-07-12 15:00
The log streaming went through a fair amount of overhaul with OpenShift 3.6, both with the k8s 3.6 rebase followed by some specific fixes stemming from that rebase, so it is certainly reasonable to assume things have changed.

It is also important to note that the docker version and log drivers have bearing on the behavior of `oc logs -f`

WRT the jenkins plugin, since it is not based on `oc` (unlike the jenkins client plugin), it is not a surprise that the behavior might differ, at least in as much as the client side of the equation impacts the behavior.

**Comment by GolanTrevize10** [comment] 2017-07-12 15:00
Can anybody confirm that?
