### ISSUE TITLE
oc start-build is not giving error when using --from-build against binary build

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#6750] opened 2016-01-20 22:25 UTC
Bringing this over from aos-devel. The summary from there seems to be that underlying issues are:

1 - ``oc start-build --from-build`` when referencing a prior build that used ``--from-dir`` should error and not try and build anything.
2 - There should be a timeout on how long builder will wait for source code injected due to ``--from-dir``.

Steps to illustrate issue.

1 - First up I am loading an image stream. I could have avoided this by using a different example, but it is what I was working with and where problem arose so was easier to to go with it.

```
    oc create -f https://raw.githubusercontent.com/GrahamDumpleton/s2i-lektor/master/lektor.json
```

This is going to load an image stream for a custom S2I builder called 'lektor'.

2 - Create an application using the custom S2I builder called 'lektor'. Am using a Git repository URL as input source for the S2I builder.

```
    oc new-app lektor:1.1~https://github.com/GrahamDumpleton/lektor-empty-site.git --name blog
    oc expose service blog
```

This will create the working application and expose it.

It will have created a build configuration definition for 'blog'. It will create an initial build called 'blog-1'.

3 - Now start a new build using 'oc start-build' using '--from-build', referring to 'blog-1'. Because haven't changed anything, we didn't need to use '--from-build' against a build, and could have just referred to the 'blog' build configuration, but just want to show it will actually work.

```
    oc start-build --from-build blog-1
```

This should create a new build called 'blog-2'.

4 - Checkout the Git repository we used as input to the S2I builder.

```
    git clone https://github.com/GrahamDumpleton/lektor-empty-site.git
```

5 - Trigger a new build but have it use the source files from the Git checkout. Presuming your are in the top directory of the Git repository use:

```
    oc start-build blog --from-dir .
```

This works and if you had changed a file such as:

```
   content/contents.lr
```

you would see the changes in the site when deployed.

This should create a new build called 'blog-3'.

6 - Trigger a new build using '--from-build' and have it refer to the build using '--from-dir'.

```
    oc start-build --from-build blog-3 --follow
```

This never finishes building and appears to hang (still not stopped after many hours). The last line being:

```
I0119 18:45:53.425309       1 source.go:118] Receiving source from STDIN as archive
```

The full logs show:

```
$ oc start-build --from-build blog-3 --follow
blog-4
I0119 18:45:53.390962       1 sti.go:163] The value of ALLOWED_UIDS is [1-]
I0119 18:45:53.394060       1 cfg.go:44] Locating docker auth for image docker.io/grahamdumpleton/s2i-lektor@sha256:a95cedcb2cd9d42b882ad7b276ffbbbbe82acfc57ab8a695043e2083590b3dda and type PULL_DOCKERCFG_PATH
I0119 18:45:53.394443       1 cfg.go:52] Problem accessing /root/.docker/config.json: stat /root/.docker/config.json: no such file or directory
I0119 18:45:53.394468       1 cfg.go:44] Locating docker auth for image 172.30.137.21:5000/start-build-tests/blog:latest and type PUSH_DOCKERCFG_PATH
I0119 18:45:53.394657       1 cfg.go:66] Using serviceaccount user for Docker authentication for image 172.30.137.21:5000/start-build-tests/blog:latest
I0119 18:45:53.399790       1 docker.go:213] Image docker.io/grahamdumpleton/s2i-lektor@sha256:a95cedcb2cd9d42b882ad7b276ffbbbbe82acfc57ab8a695043e2083590b3dda available locally
I0119 18:45:53.399883       1 sti.go:185] Creating a new S2I builder with build config: "Builder Name:\t\tApache/mod_wsgi (Python 2.7)\nBuilder Image:\t\tdocker.io/grahamdumpleton/s2i-lektor@sha256:a95cedcb2cd9d42b882ad7b276ffbbbbe82acfc57ab8a695043e2083590b3dda\nSource:\t\t\tfile:///tmp/s2i-build679436057/upload/src#d6a6170e37271d0b99470dcf99d5b6402cee4fad\nOutput Image Tag:\t172.30.137.21:5000/start-build-tests/blog:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=blog-4,OPENSHIFT_BUILD_NAMESPACE=start-build-tests\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build679436057\nDocker NetworkMode:\tcontainer:dacb7e57f7f9456373c61fbe1d59194c389e0cccca2aa636f5c381aece809df6\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0119 18:45:53.410366       1 docker.go:213] Image docker.io/grahamdumpleton/s2i-lektor@sha256:a95cedcb2cd9d42b882ad7b276ffbbbbe82acfc57ab8a695043e2083590b3dda available locally
I0119 18:45:53.422429       1 sti.go:136] Preparing to build 172.30.137.21:5000/start-build-tests/blog:latest
I0119 18:45:53.425309       1 source.go:118] Receiving source from STDIN as archive
```

**Comment by bparees** [comment] 2016-07-11 14:40
dupe of https://github.com/openshift/origin/issues/9261

**Closed by bparees** 2016-07-11 14:40 UTC
Labels: component/build, kind/bug, priority/P3
