### ISSUE TITLE
hack/build-images.sh is not working

### ISSUE THREAD

**Issue by mkumatag** [openshift/origin#8129] opened 2016-03-18 16:19 UTC
hack/build-images.sh is not working failing with following error while building image for openshift/origin

--- openshift/origin ---
Sending build context to Docker daemon 125.6 MB
Step 1 : FROM openshift/origin-base
latest: Pulling from openshift/origin-base
a3ed95caeb02: Already exists 
196355c4b639: Already exists 
36364ada1e03: Pull complete 
074be8d06254: Pull complete 
Digest: sha256:ea8c7399bc754f62ebd21bd5cc8e5a31faed3960e75cfcd97ee36defd9320334
Status: Downloaded newer image for openshift/origin-base:latest
 ---> 1f128ec0132f
Step 2 : RUN mkdir -p /var/lib/origin
 ---> Running in be7cec879f8b
 ---> fa3a5872f682
Removing intermediate container be7cec879f8b
Step 3 : ADD bin/openshift /usr/bin/openshift
 ---> 505b4e0c5f57
Removing intermediate container 880ec6c6afd0
Step 4 : RUN ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift
 ---> Running in 141ddf1d875b
Failed to set capabilities on file `/usr/bin/openshift' (Operation not supported)
usage: setcap [-q] [-v](-r|-|<caps) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
The command '/bin/sh -c ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift' returned a non-zero code: 1
!!! Error in hack/build-images.sh:91
    'docker build -t $1:latest $2' exited with status 1
Call stack:
    1: hack/build-images.sh:91 image(...)
    2: hack/build-images.sh:103 main(...)
Exiting with status 1
root@jupiter-vm309:~/go/src/github.com/openshift/origin#
##### Version

checked out v1.1.4
root@jupiter-vm309:~/go/src/github.com/openshift/origin# git branch
- (HEAD detached at v1.1.4)
  master
  root@jupiter-vm309:~/go/src/github.com/openshift/origin# 
##### Steps To Reproduce
1. checkout v1.1.4 code
2. hack/build-images.sh
##### Current Result

Build is failing with:
--- openshift/origin ---
Sending build context to Docker daemon 125.6 MB
Step 1 : FROM openshift/origin-base
latest: Pulling from openshift/origin-base
a3ed95caeb02: Already exists 
196355c4b639: Already exists 
36364ada1e03: Pull complete 
074be8d06254: Pull complete 
Digest: sha256:ea8c7399bc754f62ebd21bd5cc8e5a31faed3960e75cfcd97ee36defd9320334
Status: Downloaded newer image for openshift/origin-base:latest
 ---> 1f128ec0132f
Step 2 : RUN mkdir -p /var/lib/origin
 ---> Running in be7cec879f8b
 ---> fa3a5872f682
Removing intermediate container be7cec879f8b
Step 3 : ADD bin/openshift /usr/bin/openshift
 ---> 505b4e0c5f57
Removing intermediate container 880ec6c6afd0
Step 4 : RUN ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift
 ---> Running in 141ddf1d875b
Failed to set capabilities on file `/usr/bin/openshift' (Operation not supported)
usage: setcap [-q] [-v](-r|-|<caps) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
The command '/bin/sh -c ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift' returned a non-zero code: 1
!!! Error in hack/build-images.sh:91
    'docker build -t $1:latest $2' exited with status 1
Call stack:
    1: hack/build-images.sh:91 image(...)
    2: hack/build-images.sh:103 main(...)
Exiting with status 1
root@jupiter-vm309:~/go/src/github.com/openshift/origin#
##### Expected Result

Instead of this it should build the images properly
##### Additional Information

[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by stevekuznetsov** [comment] 2016-03-18 18:17
I can't seem to reproduce this locally with 
```
$ git checkout 3941102b8a022b5f2d9ec2c94d1f13d519fa9c31 && hack/build-release.sh && hack/build-images.sh
....
--- openshift/origin ---
Sending build context to Docker daemon 125.6 MB
Step 0 : FROM openshift/origin-base
 ---> 5203ffeaece3
Step 1 : RUN mkdir -p /var/lib/origin
 ---> Using cache
 ---> 9e63abce8461
Step 2 : ADD bin/openshift /usr/bin/openshift
 ---> f424b79dfbb5
Removing intermediate container 7124be8be041
Step 3 : RUN ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift
 ---> Running in 04c99f792771
 ---> 2f5d51906034
Removing intermediate container 04c99f792771
Step 4 : ENV HOME /root
 ---> Running in 4fc63468fa1e
 ---> e5c693185ec7
Removing intermediate container 4fc63468fa1e
Step 5 : ENV OPENSHIFT_CONTAINERIZED true
 ---> Running in 537e79bb2919
 ---> c14205961df7
Removing intermediate container 537e79bb2919
Step 6 : ENV KUBECONFIG /var/lib/origin/openshift.local.config/master/admin.kubeconfig
 ---> Running in 8bd8fd5fb063
 ---> d94f991fe3d4
Removing intermediate container 8bd8fd5fb063
Step 7 : WORKDIR /var/lib/origin
 ---> Running in da0f9a700d66
 ---> 06ec3bc0d5ec
Removing intermediate container da0f9a700d66
Step 8 : EXPOSE 8443 53
 ---> Running in 07c90d55cbd7
 ---> a37a2e8c2c86
Removing intermediate container 07c90d55cbd7
Step 9 : ENTRYPOINT /usr/bin/openshift
 ---> Running in a09a62f954b7
 ---> 2e987e4febee
Removing intermediate container a09a62f954b7
Successfully built 2e987e4febee
Removing images/origin/bin/openshift
--- openshift/origin took 22 seconds ---
...
```

Seems like the invocation of `setcap` is the same. Can you use the 1.1.4 images pushed to the Docker Hub, or do you need to build your own?

**Comment by mkumatag** [comment] 2016-03-18 19:11
This is what I've on the system, I did a ```make clean build``` before running ```build-release and build-images```

```
root@jupiter-vm309:~/go/src/github.com/openshift/origin# git branch
* (HEAD detached at v1.1.4)
  master
root@jupiter-vm309:~/go/src/github.com/openshift/origin#
root@jupiter-vm309:~/go/src/github.com/openshift/origin# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
<none>                     <none>              505b4e0c5f57        2 hours ago         401.5 MB
openshift/openvswitch      3941102             f9d62339fa17        2 hours ago         228.1 MB
openshift/openvswitch      latest              f9d62339fa17        2 hours ago         228.1 MB
openshift/origin-pod       3941102             e12ece79ed6b        2 hours ago         1.105 MB
openshift/origin-pod       latest              e12ece79ed6b        2 hours ago         1.105 MB
openshift/origin-base      latest              1f128ec0132f        5 hours ago         276 MB
openshift/origin-release   latest              a57c391cd8d6        21 hours ago        719.5 MB
centos                     centos7             d0e7f81ca65c        2 weeks ago         196.6 MB
hello-world                latest              690ed74de00f        5 months ago        960 B
root@jupiter-vm309:~/go/src/github.com/openshift/origin# 
```

**Comment by kargakis** [comment] 2016-03-18 21:20
@mkumatag try `make release`

**Comment by mkumatag** [comment] 2016-03-19 09:46
yes, I cleaned all the images from machine and did that. But failed.

```
--- openshift/origin ---
Sending build context to Docker daemon 125.6 MB
Step 1 : FROM openshift/origin-base
latest: Pulling from openshift/origin-base
a3ed95caeb02: Already exists 
196355c4b639: Already exists 
bd509e175e59: Pull complete 
598f3d9bc4ef: Pull complete 
Digest: sha256:d5392d0bc0e78e1e2a52fc069e98a4341c5cfc32fc0b94797125c24d3454b0d6
Status: Downloaded newer image for openshift/origin-base:latest
 ---> 6d4fa833e508
Step 2 : RUN mkdir -p /var/lib/origin
 ---> Running in 24018ba9f6bb
 ---> b309685b1cba
Removing intermediate container 24018ba9f6bb
Step 3 : ADD bin/openshift /usr/bin/openshift
 ---> fdab62592907
Removing intermediate container 72a1ae9c1b66
Step 4 : RUN ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift
 ---> Running in 20629b407700
Failed to set capabilities on file `/usr/bin/openshift' (Operation not supported)
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
The command '/bin/sh -c ln -s /usr/bin/openshift /usr/bin/oc &&     ln -s /usr/bin/openshift /usr/bin/oadm &&     ln -s /usr/bin/openshift /usr/bin/osc &&     ln -s /usr/bin/openshift /usr/bin/osadm &&     ln -s /usr/bin/openshift /usr/bin/kubectl &&     ln -s /usr/bin/openshift /usr/bin/openshift-deploy &&     ln -s /usr/bin/openshift /usr/bin/openshift-docker-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-sti-build &&     ln -s /usr/bin/openshift /usr/bin/openshift-f5-router &&     setcap 'cap_net_bind_service=ep' /usr/bin/openshift' returned a non-zero code: 1
!!! Error in hack/build-images.sh:91
	'docker build -t $1:latest $2' exited with status 1
Call stack:
	1: hack/build-images.sh:91 image(...)
	2: hack/build-images.sh:103 main(...)
Exiting with status 1
Makefile:149: recipe for target 'release' failed
make: *** [release] Error 1
root@jupiter-vm309:~/go/src/github.com/openshift/origin#
```

**Comment by stevekuznetsov** [comment] 2016-03-19 12:52
@smarterclayton any thoughts on this?

**Comment by kargakis** [comment] 2016-03-19 13:49
@mkumatag what OS and kernel version are you running on? See http://stackoverflow.com/a/414258 for more info.

**Comment by mkumatag** [comment] 2016-03-21 05:22
This is what I have in openshift/origin-base:

```
ubuntu@jupiter-vm309:~$ docker run -ti openshift/origin-base /bin/bash
[root@1cbe80ca6513 /]# 
[root@1cbe80ca6513 /]# cat /etc/*release*
CentOS Linux release 7.2.1511 (Core) 
Derived from Red Hat Enterprise Linux 7.2 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core) 
CentOS Linux release 7.2.1511 (Core) 
cpe:/o:centos:centos:7

[root@1cbe80ca6513 /]# uname -a
Linux 1cbe80ca6513 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@1cbe80ca6513 /]# 
```

**Comment by smarterclayton** [comment] 2017-01-23 04:20
Closing due to age.

**Closed by smarterclayton** 2017-01-23 04:20 UTC
Labels: priority/P3
