### ISSUE TITLE
osc describe "never" returns data

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1364] opened 2015-03-18 19:05 UTC
It never seems to return, although I haven't waited more than 5 minutes:

```
osc get service
oNAME                LABELS                                   SELECTOR            IP                  PORT
database            template=application-template-stibuild   name=database       172.30.17.83        5434
frontend            template=application-template-stibuild   name=frontend       172.30.17.233       5432

osc describe service frontend
```

At this point, it just seems to be hung.

**Comment by thoraxe** [comment] 2015-03-18 19:05
```
osc v0.4.1-165-gd642df7
kubernetes v0.11.0-330-g6241a21
```

**Comment by derekwaynecarr** [comment] 2015-03-18 19:08
As for why this is hung, not sure, but for clarity:

osc describe service frontend

results in:
get the service [should not be hanging since you were able to list them]
get the endpoints for that service [could be hanging depending on pod cache]
get the events related to that service [could be hanging depending on volume of events in etcd]

**Comment by thoraxe** [comment] 2015-03-18 19:43
It's not just "describe service".

```
osc describe pod  database-1-m22za
```

Hangs.

`osc describe route` seems to work instantly. `osc describe build` does, too.

So, something is up.

**Comment by thoraxe** [comment] 2015-03-19 13:53
`describe quota` hangs as well.

**Comment by thesteve0** [comment] 2015-03-23 05:31
Seeing the same thing so my issue might be a bug. I also notice that osc is at 100% CPU once I enter this command.

**Comment by soltysh** [comment] 2015-03-23 10:05
Linking https://github.com/openshift/origin/issues/1410

**Comment by mfojtik** [comment] 2015-03-23 10:05
describe secrets as well... I think there is some endless loop inside openshift cli itself (when I shot server it does not exits)

**Comment by mfojtik** [comment] 2015-03-23 10:08
it hangs after readin config:

```console
open("/root/.config/openshift/.config", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
futex(0x3052c50, FUTEX_WAIT, 0, NULL)   = 0
epoll_wait(4, {}, 128, 0)               = 0
futex(0x3052c50, FUTEX_WAIT, 0, NULL^CProcess 2338 detached
 <detached ...>

```

**Comment by smarterclayton** [comment] 2015-03-23 12:38
Ctrl+\ is your friend

**Comment by fabianofranz** [comment] 2015-03-23 15:59
Core dumpof `osc describe service docker-registry`: http://ur1.ca/jytsk
FYI @deads2k

**Comment by ncdc** [comment] 2015-03-23 16:01
Here's 1 from me: https://gist.github.com/ncdc/e6854a29a10f54fd3a94

I added a `fmt.Println` to https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/transport.go#L149 and I see it printing out infinitely

**Comment by fabianofranz** [comment] 2015-03-23 16:04
@liggitt might be of your interest too.

**Comment by deads2k** [comment] 2015-03-23 17:04
I think it's caused by the anonymous inclusion of a kubecmd.Factory and then overwriting some methods and wanting to delegate others.  

@smarterclayton spot where we really want inheritance and instead ended up with anonymous composition?

**Comment by smarterclayton** [comment] 2015-03-23 17:05
Haha

----- Original Message -----

**Comment by fabianofranz** [comment] 2015-03-23 17:28
Fixed in https://github.com/openshift/origin/pull/1414

**Closed** 2015-03-23 17:39 UTC
Labels: bug
