### ISSUE TITLE
Flake in e2e waiting for build 

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5520] opened 2015-10-30 11:11 UTC
Found in #5490, the full log is here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6427/consoleFull

**Comment by danmcp** [comment] 2015-11-02 14:38
@soltysh Please provide the error in the issue.

**Comment by soltysh** [comment] 2015-11-02 14:43
It looks like a timeout on a build:
```
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep -i complete'
!!! Error in hack/../test/end-to-end/../../hack/util.sh:272
	'return 1' exited with status 1
Call stack:
	1: hack/../test/end-to-end/../../hack/util.sh:272 os::build:wait_for_end(...)
	2: hack/../test/end-to-end/core.sh:142 main(...)
Exiting with status 1

[FAIL] !!!!! Test Failed !!!!
```

**Comment by bparees** [comment] 2015-11-02 15:30
no it returned early, so the build failed:
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep -i complete'

closing as a dupe of https://github.com/openshift/origin/issues/5511

**Closed by bparees** 2015-11-02 15:30 UTC
Labels: kind/test-flake, priority/P2
