### ISSUE TITLE
Test flake: 'User "e2e-user" cannot list all buildconfigs in the cluster' and other errors

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#6149] opened 2015-12-01 16:48 UTC
```
Error from server: User "system:anonymous" cannot list pods in project "default"
Dry run enabled - no modifications will be made. Add --confirm to remove images
Error from server: Role "cluster-status" not found
Error from server: Role "cluster-status" not found
Error from server: Role "cluster-status" not found
Error from server: Role "cluster-status" not found
Error from server: RoleBinding "cluster-status-binding" not found
Error from server: RoleBinding "cluster-status-binding" not found
error: router "router" does not exist (no service)
error: docker-registry "docker-registry" does not exist (no service).
Error from server: securitycontextconstraints "restricted" not found
Error from server: securitycontextconstraints "restricted" not found
go tool pprof: signal: broken pipe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    87  100    87    0     0     91      0 --:--:-- --:--:-- --:--:--    91
100    87  100    87    0     0     91      0 --:--:-- --:--:-- --:--:--    91

real	9m47.289s
user	9m7.747s
sys	0m16.105s
!!! Error in hack/../test/end-to-end/core.sh:161
	'out=$(oc run cli-with-token-2 --attach --env=POD_NAMESPACE=test --image=openshift/origin:${TAG} --restart=Never -- cli whoami --loglevel=4 2>&1)' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:161 main(...)
Exiting with status 1
Error from server: User "e2e-user" cannot list all buildconfigs in the cluster
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4195/console

**Comment by jwforres** [comment] 2015-12-01 16:50
cc @liggitt @deads2k

**Comment by eparis** [comment] 2015-12-18 12:40
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4398/console

looks like another dupe?

**Comment by liggitt** [comment] 2015-12-22 14:25
We really need the output of this command:
```
out=$(oc run cli-with-token --attach --env=POD_NAMESPACE=test --image=openshift/origin:${TAG} --restart=Never -- cli status --loglevel=4 2>&1)
echo "${out}"
```
it is failing with exit code 1, but we never see the output because the failure exits early

**Comment by liggitt** [comment] 2015-12-23 17:58
https://github.com/openshift/origin/pull/6483 will capture output, which should help

**Comment by kargakis** [comment] 2015-12-23 18:16
> We really need the output of this command:
> 
> out=$(oc run cli-with-token --attach --env=POD_NAMESPACE=test --image=openshift/origin:${TAG} --restart=Never -- cli status --loglevel=4 2>&1)
> echo "${out}"
> 
> it is failing with exit code 1, but we never see the output because the failure exits early

Hm, I don't think `oc run` currently supports handling commands after dashes. It is fixed upstream but still not in Origin (will be brought in with the rebase).

**Comment by kargakis** [comment] 2015-12-23 18:18
Also [--attach](https://github.com/openshift/origin/blob/0d4de0b1801e8c58a28c8bcd9d12b5d0c46de1cb/pkg/cmd/util/clientcmd/factory.go#L322-L353) may be an offender here. The dc will be generated, created, and then --attach will try to get it w/o checking if it is NotFound.

**Comment by liggitt** [comment] 2015-12-23 18:35
`--restart=Never` skips the dc generation and just makes a pod

**Comment by liggitt** [comment] 2015-12-23 20:44
finally captured log at https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4475/artifact/origin/artifacts/e2e/logs/cli-with-token2.log
closing as dupe of https://github.com/openshift/origin/issues/6447

**Closed by liggitt** 2015-12-23 20:44 UTC
Labels: component/auth, kind/test-flake, priority/P2
