### ISSUE TITLE
test-end-to-end-docker.sh:66: executing 'oc cluster status' timed out

### ISSUE THREAD

**Issue by enj** [openshift/origin#14823] opened 2017-06-22 11:32 UTC
Seen https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/2484/

```
Regression

github.com/openshift/origin/test/setup/start-oc_cluster_up.hack/test-end-to-end-docker.sh:66: executing 'oc cluster status' expecting success; re-trying every 10s until completion or 300.000s (from github.com_openshift_origin_test_setup_start-oc_cluster_up)
Failing for the past 1 build (Since Failed#2484 )
Took 5 min 9 sec.
Error Message

the command timed out
```

<details>
<summary> Stacktrace </summary>

```
=== BEGIN TEST CASE ===
hack/test-end-to-end-docker.sh:66: executing 'oc cluster status' expecting success; re-trying every 10s until completion or 300.000s
FAILURE after 309.941s: hack/test-end-to-end-docker.sh:66: executing 'oc cluster status' expecting success; re-trying every 10s until completion or 300.000s: the command timed out
Standard output from the command:
The OpenShift cluster was started 13 seconds ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready
Notice: Router is not yet ready
Notice: Persistent volumes are not yet ready

Notice: 3 OpenShift component(s) are not yet ready (see above)
The OpenShift cluster was started 25 seconds ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready
Notice: Router is not yet ready
Notice: Persistent volumes are not yet ready

Notice: 3 OpenShift component(s) are not yet ready (see above)
The OpenShift cluster was started 37 seconds ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready
Notice: Router is not yet ready
Notice: Persistent volumes are not yet ready

Notice: 3 OpenShift component(s) are not yet ready (see above)
The OpenShift cluster was started 48 seconds ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready
Notice: Persistent volumes are not yet ready

Notice: 2 OpenShift component(s) are not yet ready (see above)
The OpenShift cluster was started about a minute ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready
Notice: Persistent volumes are not yet ready

Notice: 2 OpenShift component(s) are not yet ready (see above)
The OpenShift cluster was started about a minute ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready

Notice: 1 OpenShift component(s) are not yet ready (see above)
... repeated 5 times
The OpenShift cluster was started 2 minutes ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready

Notice: 1 OpenShift component(s) are not yet ready (see above)
... repeated 5 times
The OpenShift cluster was started 3 minutes ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready

Notice: 1 OpenShift component(s) are not yet ready (see above)
... repeated 5 times
The OpenShift cluster was started 4 minutes ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready

Notice: 1 OpenShift component(s) are not yet ready (see above)
... repeated 5 times
The OpenShift cluster was started 5 minutes ago

Web console URL: https://127.0.0.1:8443

Config is at host directory /var/lib/origin/openshift.local.config
Volumes are at host directory 
Persistent volumes are at host directory /var/lib/origin/openshift.local.pv
Data is at host directory /tmp/openshift/test-end-to-end/volumes/etcd

Notice: Docker registry is not yet ready

Notice: 1 OpenShift component(s) are not yet ready (see above)
... repeated 2 times
Standard error from the command:
=== END TEST CASE ===
```

</details>

**Comment by csrwng** [comment] 2017-06-27 18:16
The issue is not cluster up, but rather that the registry never starts (The deployer dies and never deploys the registry)

**Comment by mfojtik** [comment] 2017-06-28 10:20
next time this happen we need to scrub the deploy logs to see why it died

**Comment by mfojtik** [comment] 2017-10-11 13:33
Closing due to age.

**Closed by mfojtik** 2017-10-11 13:33 UTC
Labels: component/composition, kind/test-flake, priority/P2
