### ISSUE TITLE
Certs for the router issued for *.router.default.svc.cluster.local

### ISSUE THREAD

**Issue by ghost** [openshift/origin#20716] opened 2018-08-21 16:42 UTC
In 3.9 I was able to grab ca.crt from `/var/lib/origin/openshift.local.config/master/ca.crt` and add it to Chrome authorities so that it doe snot yell about unknown authority. 

Now I can see that cert for webconsole is issued for 127.0.0.1 but router cert is for ` *.router.default.svc.cluster.local`

![image](https://user-images.githubusercontent.com/5337267/44415898-2dee8680-a57a-11e8-9cb6-fa81fdbdf422.png)

![image](https://user-images.githubusercontent.com/5337267/44415877-24fdb500-a57a-11e8-88ba-5d63194abda2.png)

Is it possible to make sure https routes are trusted by browser in 3.10 and they are issued as wildcard for my routing suffix?

This is how it looks like in 3.9

![image](https://user-images.githubusercontent.com/5337267/44416741-64c59c00-a57c-11e8-8d23-04db0a9b29ba.png)

##### Version
3.10

Cluster started: `oc cluster up --routing-suffix=$IP.nip.io --public-hostname=$IP`

**Comment by eivantsov** [comment] 2018-11-19 17:53
Still actual for 3.11

**Comment by rhopp** [comment] 2018-12-12 13:39
Could this be duplicate of https://github.com/openshift/origin/issues/19844?
In that issue, it was decided to tackle that issue on "user" side ([in that case on minishift side - they created a minishift addon just for this purpose](https://github.com/minishift/minishift/blob/master/addons/registry-route/registry-route.addon))

**Comment by eivantsov** [comment] 2018-12-12 15:20
Yes, ut is, but in my case the workaround does not wirk, since i am interested in all tls routes rather than a specific one

**Comment by secondsun** [comment] 2019-01-17 10:39
I'm working on getting integr8ly running on minishift (https://github.com/integr8ly/installation).  This issue is hitting me when che is provisioned and is trying to connect to the internal keycloak server.  Che is importing the certificate form the server.  It fails because even though the CA is trusted by the JVM running che, the certificate CN is for the *.router.default.svc.cluster.local instead of for 192.foo.bar.baz.nip.io even though that is the name that is actually being exposed.

**Comment by eivantsov** [comment] 2019-02-02 11:47
Still actual for 4.0. Is this going to be fixed or should it be considered as expected behavior? I mean should I generate PEM for my router just after the installation and update router with it?

With 4.0 I see:

![image](https://user-images.githubusercontent.com/5337267/52163854-0f77e400-26f1-11e9-8cac-cac34d587827.png)

**Comment by Miciah** [comment] 2019-05-03 16:52
> Still actual for 4.0. Is this going to be fixed or should it be considered as expected behavior?

With https://github.com/openshift/cluster-ingress-operator/pull/109, the ingress operator will generate a self-signed default certificate if the administrator does not provide a custom default certificate.  This operator-generated certificate should have the right CN, but since it is self-signed, external clients will not trust it.

> I mean should I generate PEM for my router just after the installation and update router with it?

Ideally, yes.  The operator-generated, self-signed default certificate is sufficient to get OpenShift Console and OAuth authentication working, but on a production cluster, the administrator should configure the router with a certificate signed by a trusted CA so that external clients can trust the router.

**Closed** 2021-06-01 19:20 UTC
Labels: lifecycle/rotten, sig/network-edge
