### ISSUE TITLE
Create Node.js app from GitHub broken.  Error: "Service xyz is invalid: spec.ports: required value"

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#2216] opened 2015-05-13 14:42 UTC
Using https://github.com/openshift/nodejs-example and imageStreams/nodejs-010-centos7 I observe the following error (this has worked for weeks):

![create-app-failed](https://cloud.githubusercontent.com/assets/727196/7612921/bdc98472-f95b-11e4-8a7c-198c82caadbe.png)

```
  "major": "0",
  "minor": "16.2+",
  "gitVersion": "v0.16.2-338-gc07896e",
  "gitCommit": "c07896e",
```

The 422 response body:

```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "Service \"nodejs-example\" is invalid: spec.ports: required value",
  "reason": "Invalid",
  "details": {
    "id": "nodejs-example",
    "kind": "Service",
    "causes": [
      {
        "reason": "FieldValueRequired",
        "message": "spec.ports: required value",
        "field": "spec.ports"
      }
    ]
  },
  "code": 422
}
```

The 422 error shows a little more detail in the JavaScript console

```
GET https://localhost:8443/osapi/v1beta1/buildConfigs/nodejs-example?namespace=openshift 403 (Forbidden)a @ vendor.js:4994v @ vendor.js:4925$get.j @ vendor.js:4860i @ vendor.js:5547(anonymous function) @ vendor.js:5555$get.l.$eval @ vendor.js:5835$get.l.$digest @ vendor.js:5792$get.l.$apply @ vendor.js:5857(anonymous function) @ vendor.js:9609_.event.dispatch @ vendor.js:2048_.event.add.q.handle @ vendor.js:2011
vendor.js:4994 GET https://localhost:8443/osapi/v1beta1/routes/nodejs-example?namespace=openshift 403 (Forbidden)a @ vendor.js:4994v @ vendor.js:4925$get.j @ vendor.js:4860i @ vendor.js:5547(anonymous function) @ vendor.js:5555$get.l.$eval @ vendor.js:5835$get.l.$digest @ vendor.js:5792$get.l.$apply @ vendor.js:5857(anonymous function) @ vendor.js:9609_.event.dispatch @ vendor.js:2048_.event.add.q.handle @ vendor.js:2011
vendor.js:4994 GET https://localhost:8443/osapi/v1beta1/deploymentConfigs/nodejs-example?namespace=openshift 403 (Forbidden)a @ vendor.js:4994v @ vendor.js:4925$get.j @ vendor.js:4860i @ vendor.js:5547(anonymous function) @ vendor.js:5555$get.l.$eval @ vendor.js:5835$get.l.$digest @ vendor.js:5792$get.l.$apply @ vendor.js:5857(anonymous function) @ vendor.js:9609_.event.dispatch @ vendor.js:2048_.event.add.q.handle @ vendor.js:2011
vendor.js:4994 GET https://localhost:8443/osapi/v1beta1/imageRepositories/nodejs-example?namespace=openshift 404 (Not Found)a @ vendor.js:4994v @ vendor.js:4925$get.j @ vendor.js:4860i @ vendor.js:5547(anonymous function) @ vendor.js:5555$get.l.$eval @ vendor.js:5835$get.l.$digest @ vendor.js:5792$get.l.$apply @ vendor.js:5857(anonymous function) @ vendor.js:9609_.event.dispatch @ vendor.js:2048_.event.add.q.handle @ vendor.js:2011
vendor.js:4994 GET https://localhost:8443/api/v1beta3/namespaces/openshift/services/nodejs-example 403 (Forbidden)a @ vendor.js:4994v @ vendor.js:4925$get.j @ vendor.js:4860i @ vendor.js:5547(anonymous function) @ vendor.js:5555$get.l.$eval @ vendor.js:5835$get.l.$digest @ vendor.js:5792$get.l.$apply @ vendor.js:5857(anonymous function) @ vendor.js:9609_.event.dispatch @ vendor.js:2048_.event.add.q.handle @ vendor.js:2011
vendor.js:4994 POST https://localhost:8443/api/v1beta3/namespaces/p4/services 422 (status code 422)
```

/cc @spadgett

**Comment by sspeiche** [comment] 2015-05-13 20:19
This is blocking me from doing much of anything, including getting some demos recorded for upcoming conference.  Wondering if @jcantrill has any thoughts on it?

**Comment by spadgett** [comment] 2015-05-13 21:10
I'm seeing the same error as @sspeiche creating from source repositories. I'm also seeing a similar error creating from templates.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7621186/cfb6300e-f992-11e4-89e4-652648261c94.png)

**Comment by jcantrill** [comment] 2015-05-14 12:15
@spadgett your error looks like either a change in deployment configs that is not addressed by the UI flow or a scenario we did not account for.  It would also mean the template most likely was not crafted correctly.  Can you please provide more details about your issue?  You may even wish to spin it off since the template flow is different then the 'new-app flow'. @sspeiche your error would imply there is an issue with the generation code.  You can see the generated JSON in the web console log if you are able to flip the UI logging to debug.  I'll  investigate.

**Comment by jcantrill** [comment] 2015-05-14 13:20
@sspeiche The issue is the the generation tool was unable to find the exposed ports for the image.  It looks like the info on the imagestreamtag moved.  I'll work on fixing.

**Comment by spadgett** [comment] 2015-05-14 13:56
@jcantrill I'm using `examples/sample-app/application-template-stibuild.json`

```
osc create -f examples/sample-app/application-template-stibuild.json -n project1
```

Then I created from a template in the web console taking all of the defaults.

**Comment by jcantrill** [comment] 2015-05-14 15:49
@sspeiche https://github.com/openshift/origin/pull/2241

**Comment by smarterclayton** [comment] 2015-05-15 03:15
Please verify

**Comment by jcantrill** [comment] 2015-05-15 12:34
@smarterclayton please verify what?

**Comment by sspeiche** [comment] 2015-05-15 17:37
@jcantrill @smarterclayton I just pulled image from docker hub and things work now.  So perhaps you can consider it verified.  Thanks!

**Closed** 2015-05-19 20:07 UTC
Labels: component/master, kind/bug, priority/P1
