### ISSUE TITLE
[ ERR] Gave up waiting for: '[[ "$(curl -s -X POST http://${FRONTEND_IP}:5432/keys/foo -d value=1337)" = "Key created" ]]'

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#9512] opened 2016-06-23 14:36 UTC
from e2e: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2370

```
[INFO] Waiting for command to finish: '[[ "$(curl -s -X POST http://${FRONTEND_IP}:5432/keys/foo -d value=1337)" = "Key created" ]]'...
[ ERR] Gave up waiting for: '[[ "$(curl -s -X POST http://${FRONTEND_IP}:5432/keys/foo -d value=1337)" = "Key created" ]]'
[ERROR] PID 31876: test/end-to-end/core.sh:306: `return 1` exited with status 1.
```

**Comment by deads2k** [comment] 2016-06-23 14:44
@bparees are you familiar with the e2e app?  My look at the logs suggests that it should be successfully POSTing.

**Comment by bparees** [comment] 2016-06-23 14:49
yeah, it's not obvious to me.  based on the output it appears the curl request never even got to the app (the wait_for_command timed out on the curl, it didn't return a failure code).  

if we have container logs for the app pod, that might shed some light, but given that the welcome page returned successfully it seems like the app is working, unless the DB connection failed.

**Comment by deads2k** [comment] 2016-06-23 14:51
> if we have container logs for the app pod, that might shed some light, but given that the welcome page returned successfully it seems like the app is working, unless the DB connection failed.

Those are attached to the jenkins job under status and labeled with the container names.  There are actually two pods started and they both seem to be getting the POSTs.

**Comment by smarterclayton** [comment] 2016-06-23 14:52
Hrm, I've never seen that one fail before (or not in months).

**Comment by bparees** [comment] 2016-06-23 14:52
yeah was just looking at the posts...  sure looks like the app is getting the post and responding with a 200.  No idea why curl isn't getting that response back.

**Comment by deads2k** [comment] 2016-06-23 14:54
> Hrm, I've never seen that one fail before (or not in months).

It was triggering the SCC flake issue people started linking recently, so something broke.

**Comment by kargakis** [comment] 2016-06-29 22:22
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2657/consoleFull

**Comment by kargakis** [comment] 2016-06-30 11:22
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2679/consoleFull

**Comment by gabemontero** [comment] 2016-06-30 18:37
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2701/console

**Comment by bparees** [comment] 2016-07-01 19:00
i've been seeing this one a lot the last couple days.  I don't feel totally convinced by my service proxy theory, but I'm not sure what else it could be.  Per @deads2k suggestion i'm going to update the curl command to report what it is getting back, in case that offers more insight.

**Comment by bparees** [comment] 2016-07-01 19:12
attempting to recreate w/ full shell debug here:
https://github.com/openshift/origin/pull/9676

**Comment by bparees** [comment] 2016-07-02 13:09
further debugging on this issue has revealed we're getting back "key updated" instead of "key created" because apparently one of the earlier curl commands actually succeeded in creating the key, despite curl returning an RC=7(??).

will see if i can tighten up the logic that's testing the responses.

**Comment by deads2k** [comment] 2016-07-05 14:01
Still happening: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2854/

@stevekuznetsov @bparees suggested you.

**Comment by bparees** [comment] 2016-07-05 14:04
dupe of https://github.com/openshift/origin/issues/9685

**Closed by bparees** 2016-07-05 14:04 UTC
Labels: kind/test-flake, priority/P2
