### ISSUE TITLE
TestAuthorizationResolution flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9528] opened 2016-06-23 21:47 UTC
```
--- FAIL: TestAuthorizationResolution (3.35s)
	authorization_test.go:244: unexpected error: role "with-group" not found
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2409/console

**Comment by kargakis** [comment] 2016-06-23 21:48
Probably related
```
FAILURE after 0.233s: test/cmd/admin.sh:247: executing 'oc create -f test/extended/testdata/roles/policy-clusterroles.yaml' expecting success: the command returned the wrong error code
Standard output from the command:
clusterrole "basic-user2" created

Standard error from the command:
Error from server: role "basic-user2" not found
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/2404/consoleFull

**Comment by kargakis** [comment] 2016-06-23 22:02
And another one: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2413/consoleFull

**Comment by liggitt** [comment] 2016-06-23 22:42
Probably caused by https://github.com/openshift/origin/pull/9516 and fixed by https://github.com/openshift/origin/pull/9523

**Closed** 2016-06-24 06:38 UTC
Labels: area/tests, component/auth, kind/test-flake
