### ISSUE TITLE
Flake in extended test suite (etcd member has no leader)

### ISSUE THREAD

**Issue by miminar** [openshift/origin#7332] opened 2016-02-16 06:48 UTC
[INFO] Success running command: '[[ "$(oc get endpoints docker-registry --output-version=v1 --template="{{ if .subsets }}{{ len .subsets }}{{ else }}0{{ end }}" --config=${ADMIN_KUBECONFIG} || echo "0")" != "0" ]]' after 5 seconds
    [INFO] Installing the router
    serviceaccount "router" created
    Error from server: error when replacing "STDIN": error #0: client: etcd member https://172.18.9.140:4001 has no leader
    !!! Error in /data/src/github.com/openshift/origin/hack/util.sh:592
        'oc replace scc privileged -f - --config="${ADMIN_KUBECONFIG}"' exited with status 0 0 1
    Call stack:
        1: /data/src/github.com/openshift/origin/hack/util.sh:592 install_router(...)
        2: test/extended/core.sh:71 main(...)
    Exiting with status 1

Observable in #7128 ([job 10939](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/10939/consoleFull)).

**Comment by liggitt** [comment] 2016-02-16 06:49
dupe of https://github.com/openshift/origin/issues/7243

**Closed by liggitt** 2016-02-16 06:49 UTC

**Comment by liggitt** [comment] 2016-02-16 06:50
we have some flake cause tracking in place... check the jenkins job overview page first :)
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/10939/

**Comment by miminar** [comment] 2016-02-16 06:52
Ahh, cool. Didn't know that. Do you ever sleep by the way? :-)
