### ISSUE TITLE
Another caller has already initialized the resource

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#5679] opened 2015-11-04 00:22 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6790/console

E1103 19:15:39.322456   24879 serviceaccounts_controller.go:218] serviceaccounts "default" already exists
E1103 19:15:39.322784   24879 create_dockercfg_secrets.go:109] secrets "build-controller-token-6mk35" already exists
E1103 19:15:39.325543   24879 tokens_controller.go:156] secrets "build-controller-token-3c31q" already exists
F1103 19:15:39.327992   24879 run_components.go:390] Unable to initialize namespaces: unable to persist the updated namespace UID allocations: uidallocation "" cannot be updated: another caller has already initialized the resource

**Comment by ncdc** [comment] 2015-12-04 02:25
Similar failure, from https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4236/consoleFull:

```
F1203 13:59:18.599912   26267 controller.go:87] Unable to perform initial service nodePort check: unable to persist the updated port allocations: servicenodeportallocation "" cannot be updated: another caller has already initialized the resource
```

**Comment by smarterclayton** [comment] 2015-12-04 04:28
I bet this is the core controllers in the master racing with the allocator
block.  Which sucks.

On Dec 3, 2015, at 9:25 PM, Andy Goldstein <notifications@github.com> wrote:

Similar failure, from
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4236/consoleFull
:

F1203 13:59:18.599912   26267 controller.go:87] Unable to perform
initial service nodePort check: unable to persist the updated port
allocations: servicenodeportallocation "" cannot be updated: another
caller has already initialized the resource

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5679#issuecomment-161852797>.

**Comment by deads2k** [comment] 2016-01-12 19:31
dupe of https://github.com/openshift/origin/issues/6447

This could happen when the create against etcd succeeds, but the etcd server responds back with a failure, the next (automatic) attempt fails because the allocation has already created the entry in etcd.

**Closed by deads2k** 2016-01-12 19:31 UTC
Labels: kind/test-flake, priority/P2
