### ISSUE TITLE
Unable to get deployment logs for multi container pods

### ISSUE THREAD

**Issue by jhellar** [openshift/origin#10186] opened 2016-08-03 14:38 UTC
When there are multiple containers in pod `oc logs` fails for deploymentconfigs for that pod and it is not possible to specify the container with -c parameter.
##### Version

oc v3.2.0.20
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. oc logs dc/name_of_pod_with_multiple_containers -c name_of_container
##### Current Result

Error from server: a container name must be specified for pod ..., choose one of: [... ...]
##### Expected Result

logs...

**Comment by rhcarvalho** [comment] 2016-08-03 14:52
Thanks @jhellar.

Looks like this is fixed on a more recent version, may be broken in OSE 3.2

In any case, I have steps to reproduce the issue:

```console
$ oc version
oc v1.3.0-alpha.2-267-g2fe486f-dirty
kubernetes v1.3.0-alpha.3-599-g2746284
$ cat dc-multi-container.json 
{
  "kind": "DeploymentConfig",
  "apiVersion": "v1",
  "metadata": {
    "name": "test-dc",
    "creationTimestamp": null
  },
  "spec": {
    "strategy": {
      "type": "Rolling"
    },
    "triggers": [
      {
        "type": "ConfigChange"
      }
    ],
    "replicas": 1,
    "selector": {
      "name": "test-dc"
    },
    "template": {
      "metadata": {
        "labels": {
          "name": "test-dc"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "busybox",
            "image": "busybox:latest"
          },
          {
            "name": "alpine",
            "image": "alpine:latest"
          }
        ]
      }
    }
  }
}
$ oc create -f dc-multi-container.json 
deploymentconfig "test-dc" created
$ oc logs dc/test-dc
--> Scaling test-dc-1 to 1
--> Waiting up to 10m0s for pods in deployment test-dc-1 to become ready
```

@jhellar could you please confirm what output you get when running the steps above?

**Comment by jhellar** [comment] 2016-08-03 14:56
@rhcarvalho I can confirm that it works.

oc logs dc/test-dc
I0802 14:23:28.411933       1 deployer.go:200] Deploying core/test-dc-1 for the first time (replicas: 1)
I0802 14:23:28.430979       1 recreate.go:126] Scaling core/test-dc-1 to 1 before performing acceptance check
I0802 14:23:30.486809       1 recreate.go:131] Performing acceptance check of core/test-dc-1
I0802 14:23:30.486882       1 lifecycle.go:445] Waiting 600 seconds for pods owned by deployment "core/test-dc-1" to become ready (checking every 1 seconds; 0 pods previously accepted)

**Comment by rhcarvalho** [comment] 2016-08-10 14:56
@jhellar could you find a way to reproduce this?

**Comment by rhcarvalho** [comment] 2016-08-11 13:00
Talking with @jhellar on IRC, he mentioned that `oc logs dc/test-dc` works before the pod is in running state.

After the deployment finishes, the same command stops working, and the error incorrectly tells us to choose a pod:

```
$ oc logs dc/test-dc
Error from server: a container name must be specified for pod test-dc-1-t63xy,
choose one of: [busybox alpine]
```

But:

```
$ oc logs -c alpine dc/test-dc
Error from server: a container name must be specified for pod test-dc-1-t63xy, choose one of: [busybox alpine]
```

And since we want the deployment logs, it shouldn't ask for a container.

----------

I've updated my comment above with steps to reproduce the issue.

**Comment by rhcarvalho** [comment] 2016-08-12 08:44
I've updated the title to better reflect the issue.

**Comment by mfojtik** [comment] 2016-08-12 11:42
I'm looking at this

**Comment by mfojtik** [comment] 2016-08-12 11:53
And I think I found the problem ;-)

**Comment by mfojtik** [comment] 2016-08-24 12:39
Reopening because the change was reverted (it breaks the API backward compatibility for UI).

**Comment by taisph** [comment] 2017-07-21 15:36
Does this issue affect pod replicas as well? I am only seeing one pod's log output using `oc logs -f dc/app`.

**Comment by kargakis** [comment] 2018-01-25 14:14
@mfojtik fixed now?

**Closed** 2018-06-25 00:32 UTC
Labels: component/cli, kind/bug, lifecycle/rotten, priority/P2
