### ISSUE TITLE
what's happening？？？

### ISSUE THREAD

**Issue by pennpeng** [openshift/origin#19013] opened 2018-03-17 05:04 UTC
## i install 3.7.1 use the testing repo `https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin37/`，but....

```
(1/2): origin-3.7.1-1.el7.git.0.0a2d6a1.x86_64.rpm                                                                                 |  68 MB  00:38:04     
(2/2): origin-clients-3.7.1-1.el7.git.0.0a2d6a1.x86_64.rpm                                                                         |  33 MB  00:00:15     
----------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                      26 kB/s | 102 MB  01:05:55     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : origin-clients-3.7.1-1.el7.git.0.0a2d6a1.x86_64                                                                                        1/2 
  Installing : origin-3.7.1-1.el7.git.0.0a2d6a1.x86_64                                                                                                2/2 
  Verifying  : origin-3.7.1-1.el7.git.0.0a2d6a1.x86_64                                                                                                1/2 
  Verifying  : origin-clients-3.7.1-1.el7.git.0.0a2d6a1.x86_64                                                                                        2/2 

Installed:
  origin.x86_64 0:3.7.1-1.el7.git.0.0a2d6a1                                                                                                               

Dependency Installed:
  origin-clients.x86_64 0:3.7.1-1.el7.git.0.0a2d6a1                                                                                                       

Complete!
[root@node2 yum.repos.d]# 
[root@node2 yum.repos.d]# 
[root@node2 yum.repos.d]# oc version
oc v3.10.0-alpha.0+0a2d6a1-65
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

```

**Comment by jfchevrette** [comment] 2018-03-19 15:30
I have also reported the issue here: https://bugs.centos.org/view.php?id=14594

**Comment by tdudgeon** [comment] 2018-03-19 16:03
See also https://github.com/openshift/openshift-ansible/issues/7567

**Comment by tdawson** [comment] 2018-03-20 02:58
There was a problem with the released centos 3.7.1 packages.
They have been rebuilt, and passed our initial tests. They should be in the released centos repositories in a few days.

**Comment by jwforres** [comment] 2018-03-20 14:26
@openshift/sig-cluster-lifecycle

**Comment by tdawson** [comment] 2018-03-21 13:09
The updated origin-3.7.1-2.el7 is now available in all the regular repositories.
This problem should be fixed now.

**Comment by jperville** [comment] 2018-03-21 13:32
@tdawson can you yank the broken version from the repositories? It is seriously broken and should not be installed, even if the version is explicitly specified.

**Comment by DanyC97** [comment] 2018-04-19 11:02
@jperville any chance you can try re-deploy and see if you still any issues?

As @tdawson said that should be fixed, we do apologize for the inconvenience that have caused.

Also note that new origin rpms have been released yesterday - fyi.

_Please close this issue if the problem is fixed, thank you_

**Comment by tdawson** [comment] 2018-04-26 16:11
I am marking this issue closed because it looks like we've resolved this a few weeks ago.
If you continue to have problems, please re-open, or create a new issue.

**Closed by tdawson** 2018-04-26 16:11 UTC
Labels: kind/bug, priority/P1, sig/cluster-lifecycle

**Comment by tdudgeon** [comment] 2018-04-26 19:48
Yes, this has been resolved.
