### ISSUE TITLE
deployed EFK error

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#6502] opened 2015-12-27 15:22 UTC
Hello,
when i deployed the openshift-EFK[1] ,that are error for this ,such as
![error](https://cloud.githubusercontent.com/assets/12937669/12010763/88d75400-acee-11e5-917d-e26e4d4a5bb6.png)

[ERROR][com.floragunn.searchguard.service.SearchGuardConfigService] [N'Gabthoth] Try to refresh security configuration but it failed due to org.elasticsearch.action.NoShardAvailableActionException: [.searchguard.logging-es-p6lpl6ud-1-w5pjk][4] null

thank you!
[1] https://docs.openshift.org/latest/install_config/aggregate_logging.html

**Comment by jcantrill** [comment] 2016-01-05 14:44
duplicate of https://github.com/openshift/origin-aggregated-logging/issues/35

**Closed by jcantrill** 2016-01-05 14:44 UTC
Labels: component/logging, priority/P2
