### ISSUE TITLE
Jenkins pipeline reports error and fails to start build after restart?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16501] opened 2017-09-22 04:07 UTC
Jenkins was stopped due to a docker crash, and then when it restarted I created a bc that launched a pipeline build in OpenShift, but the build didn't start in Jenkins.  Instead I saw

```
Sep 22, 2017 4:03:23 AM io.fabric8.jenkins.openshiftsync.BuildWatcher$1 doRun
SEVERE: Failed to load initial Builds: java.lang.NullPointerException
java.lang.NullPointerException
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.onInitialBuilds(BuildWatcher.java:154)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:80)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

in the jenkins logs.  v3.7.0-alpha.1 using 

```
oc new-app -f https://raw.githubusercontent.com/openshift/release/master/tools/build/build-tools.yaml
```

**Comment by smarterclayton** [comment] 2017-09-22 04:12
Actually it never builds.  Just sits there watching forever, even after deleting the pod.

**Comment by smarterclayton** [comment] 2017-09-22 04:14
Jenkins takes an abnormally long time to shut down it seems (logs report its shutting down, but pod still in terminating).  Shim process not shutting down?

**Comment by smarterclayton** [comment] 2017-09-22 04:16
Also, does the jenkins template have owner ref cross linking (probably from service)?

**Comment by goraxe** [comment] 2017-09-22 23:13
Seeing the same here, I'm using a fresh minishift.  I'm seeing a slightly different error during the Initial build sync 

```
SEVERE: Failed to load initial Builds: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default/apis/build.openshift.io/v1/namespaces/myproject/builds?fieldSelector=status%3DNew. Message: No field label conversion function found for version: build.openshift.io/v1. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=No field label conversion function found for version: build.openshift.io/v1, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
--
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default/apis/build.openshift.io/v1/namespaces/myproject/builds?fieldSelector=status%3DNew. Message: No field label conversion function found for version: build.openshift.io/v1. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=No field label conversion function found for version: build.openshift.io/v1, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
  | at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:97)
  | at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
  | at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by goraxe** [comment] 2017-09-22 23:23
I dropped down a version of openshift-sync -> http://updates.jenkins-ci.org/download/plugins/openshift-sync/0.1.28/openshift-sync.hpi .  That seems to have done the trick.

**Comment by bparees** [comment] 2017-09-23 14:22
@gabemontero has made some fixes in this space recently, it would be worth seeing if the jenkins:latest image has these issues for you.  Barring that, I'll let him weigh in.

> Also, does the jenkins template have owner ref cross linking (probably from service)?

cross linking between what and what?  the jenkins service as the owner of the jenkins deployment config?  vice versa?  both?

Anyway the answer i'm pretty sure is no, we don't set up any ownerrefs in our templates.

And i'm still not convinced I want my jenkins DC to be deleted if i delete my jenkins service, if that is the linking you're asking for.

**Comment by gabemontero** [comment] 2017-09-24 16:17
Some initial housekeeping:  for @smarterclayton 's NPE, which as  @goraxe noted would be caused by the io.fabric8.kubernetes.client.KubernetesClientException he noted, I'll elaborate / diagnose / resolve more in https://github.com/openshift/jenkins-sync-plugin/issues/173; quick summary, either our bump in fabric8 version between v0.1.29 and v0.1.28 of sync plugin caused an issue, or a recent 3.7 level openshift changed has broken something with the latter fabric8.

Most likely a short term solution will be to bump back down the fabric8 level, but I want to understand the particulars a bit more before doing that.

@bparees - fyi v0.1.29 of sync plugin is what is in the absolute latest jenkins image, and is the latest sync plugin change.  Nothing to date has been dropped since cutitng v0.1.29.

Let's use this issue to track the cross link discussion to conclusion, as well as cross ref with the sync-plugin issue.

Lastly, as to the delay in Jenkins shutting down @smarterclayton, nothing of the kind is reported that I am aware of.  I'll see if it is a generic item I can reproduce locally, but if you happened to save the jenkins pod logs when it occurred, that would be ideal

**Comment by gabemontero** [comment] 2017-09-25 17:54
Some updates:

1) the NPE/KubernetesClientException stems from an openshift/origin problem in 3.6 / 3.7-alpha that @deads2k told us about; details in https://github.com/openshift/jenkins-sync-plugin/issues/173, but short term we are reverting the fabric8 version, and @deads2k is backporting a recent 3.7 fix to 3.6 - once that is shipped, we can see about bumping fabric8 again

2) I toyed around a bit with scaling jenkins down in the middle of various tasks, but the jenkins pod always terminated quickly; @smarterclayton - if you a precise recipe for repro, or jenkins pod logs when it occurs, let me know

Still leaving this open pending progress on 2) and a comeback from @smarterclayton to @bparees response on the owner ref stuff

**Comment by gabemontero** [comment] 2017-09-25 18:44
https://github.com/openshift/jenkins/pull/387 will update the openshift jenkins centos image with v0.1.30 of the sync plugin

**Comment by bparees** [comment] 2017-10-06 18:33
Just to recap:

1) NPE has been resolved
2) Slow shutdown could not be recreated
3) Request for ownerref linking between components in the jenkins template needs more info (And probably a separate issue) if we're going to pursue it.

closing.

**Closed by bparees** 2017-10-06 18:33 UTC
Labels: component/build, priority/P3
