### ISSUE TITLE
Should be able to overwrite (change type) of volume in oc volume

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3542] opened 2015-07-01 21:16 UTC
A dc existed with type emptyDir and mount path /var/run/openshift.  I should be able to overwrite it without specifying a name (in this case, because it's not ambiguous)

```
$ oc volume dc/master --add -m /var/run/openshift/ --secret-name=openshift-master --type=secret --overwrite
Generated volume name: 1c1d6339-2036-11e5-a89c-7831c1b76042
error: deploymentconfigs/master volume mount '/var/run/openshift/' already exists for container 'origin'
```

Should have overwrote the mount type because there was only one mount and my input wasn't ambiguous

**Comment by bparees** [comment] 2015-07-22 19:57
dupe of https://bugzilla.redhat.com/show_bug.cgi?id=1245571 ?

**Closed** 2015-07-23 14:27 UTC
Labels: area/usability, component/deployments, kind/enhancement, priority/P1
