### ISSUE TITLE
adding code via web console doesn't automatically start a build

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2723] opened 2015-06-03 01:34 UTC
It's been more than 60 seconds and a build has not been automatically started since I've added code via the web console.

Should it have?

```
[root@ose3-master beta4]# osc version
osc v0.5.2.2-18-gbf80a71
kubernetes v0.17.1-804-g496be63
```

**Comment by liggitt** [comment] 2015-06-03 01:35
What do you mean by "added code via the web console". Created from a source repository?

**Comment by thoraxe** [comment] 2015-06-03 02:09
Yes. Specifying a source repository through the create dialogue in the console.

**Comment by liggitt** [comment] 2015-06-03 04:01
@bparees what is helpful to get to debug this? dumps of buildconfig and imagestreams for the project?

**Comment by bparees** [comment] 2015-06-03 12:29
i don't think we'd expect a build at all in that scenario.  The reason you get a build when you do the new-app and template flows is because those flows define a new imagestream which then gets populated by importing from the docker registry.

that import is effectively an "image change" so it triggers the image change trigger on the build.

but when you do new from source, you're referencing an existing imagestream as your builder image, so there's not going to be an immediate imagestream update to trigger a build.

so at the moment this is "working as designed".

Whether that design point is right or not, i guess i'm less convinced...it does seem likely we'd want to immediately kick off a bulid when you create something via this path, but we'd have to do it explicitly.

**Comment by thoraxe** [comment] 2015-06-03 12:35
If "new-app" creates a build automatically when pointed at source then the web console should as well. A user would expect the same behavior(s).

**Comment by liggitt** [comment] 2015-06-03 13:22
yeah, I thought the web "from source" flow did the same thing as `new-app`... as best as I can tell, it's creating an image stream as well.

**Comment by bparees** [comment] 2015-06-03 13:24
I thought about this some more..a couple corrections.
1) new-app does create an imagestream if you pick an arbitrary image as your builder instead of an imagestream
2) the webconsole flow does not because it forces you to pick an existing imagestream, you can pick an arbitrary image
3) even if the imagestream does already exist (case 2) you will probably get a build within 2 minutes of creation because we do a full-resync every 2 minutes and at that point we'll see that there's an imagestream for which we have not run the build.  

So my first question is... is that what you're seeing?  build does run *eventually* just not immediately?

**Comment by thoraxe** [comment] 2015-06-03 13:26
I haven't tested recently but for beta3 it didn't happen within 5 minutes.

I can try it again at some point, but I'm blocked on both router and SDN issues so I'm not spending much time on OSE right now

**Comment by bparees** [comment] 2015-06-03 13:42
@thoraxe ok if you see it again, osc get is -o json,  osc get buildconfig -o json, osc get builds -o json
(from the right namespaces of course).  and only check after about 2 minutes.

**Comment by spadgett** [comment] 2015-06-04 12:52
@thoraxe can you retest with the latest Web Console? I've noticed recently (in the last week or so) that builds are running automatically when creating from a source repository when they didn't used to. I just tested the openshift/nodejs-ex example builds automatically using the node.js builder image, and it worked.

@bparees any idea what changed?

**Comment by thoraxe** [comment] 2015-06-04 13:53
```
osc v0.5.2.2-22-g84b1674-dirty
kubernetes v0.17.1-804-g496be63
```

I am at 4 minutes and there has been no build started yet. How much longer should I wait?

**Comment by liggitt** [comment] 2015-06-04 13:54
2 minutes should start it. dump the bits ben asked for?

**Comment by thoraxe** [comment] 2015-06-04 13:59
@bparees  After ~5 minutes:

The image stream of the app that was created in the project:
```JSON
{
    "kind": "ImageStream",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "ruby-example",
        "namespace": "sinatra",
        "selfLink": "/osapi/v1beta3/namespaces/sinatra/imagestreams/ruby-example",
        "uid": "8818df21-0ac0-11e5-aaf4-525400b33d1d",
        "resourceVersion": "1070",
        "creationTimestamp": "2015-06-04T13:49:33Z",
        "labels": {
            "generatedby": "OpenShiftWebConsole",
            "name": "ruby-example"
        }
    },
    "spec": {},
    "status": {
        "dockerImageRepository": "172.30.156.126:5000/sinatra/ruby-example"
    }
}
```

The buildconfig in the project:
```JSON
{
    "kind": "BuildConfig",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "ruby-example",
        "namespace": "sinatra",
        "selfLink": "/osapi/v1beta3/namespaces/sinatra/buildconfigs/ruby-example",
        "uid": "8819332d-0ac0-11e5-aaf4-525400b33d1d",
        "resourceVersion": "1071",
        "creationTimestamp": "2015-06-04T13:49:33Z",
        "labels": {
            "generatedby": "OpenShiftWebConsole",
            "name": "ruby-example"
        }
    },
    "spec": {
        "triggers": [
            {
                "type": "generic",
                "generic": {
                    "secret": "e2798e4d7164381e"
                }
            },
            {
                "type": "github",
                "github": {
                    "secret": "70163ce4a0ce7d44"
                }
            },
            {
                "type": "imageChange",
                "imageChange": {}
            }
        ],
        "source": {
            "type": "Git",
            "git": {
                "uri": "https://github.com/openshift/simple-openshift-sinatra-sti",
                "ref": "master"
            }
        },
        "strategy": {
            "type": "Source",
            "sourceStrategy": {
                "from": {
                    "kind": "DockerImage",
                    "name": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest"
                },
                "incremental": true
            }
        },
        "output": {
            "to": {
                "kind": "ImageStreamTag",
                "name": "ruby-example:latest"
            }
        },
        "resources": {}
    },
    "status": {
        "lastVersion": 0
    }
}
```

The builds (there are none):
```
[joe@ose3-master beta4]$ osc get build
NAME      TYPE      STATUS    POD
```

The image stream of the builder, which is in the openshift namespace/project:
```JSON
{
    "kind": "ImageStream",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "ruby",
        "namespace": "openshift",
        "selfLink": "/osapi/v1beta3/namespaces/openshift/imagestreams/ruby",
        "uid": "6b287251-0ac0-11e5-aaf4-525400b33d1d",
        "resourceVersion": "1015",
        "creationTimestamp": "2015-06-04T13:48:45Z",
        "annotations": {
            "openshift.io/image.dockerRepositoryCheck": "2015-06-04T13:48:46Z",
            "openshift.io/image.insecureRepository": "true"
        }
    },
    "spec": {
        "dockerImageRepository": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7",
        "tags": [
            {
                "name": "latest",
                "annotations": {
                    "description": "Build and run Ruby 2.0 applications",
                    "iconClass": "icon-ruby",
                    "tags": "builder,ruby",
                    "version": "2.0"
                }
            }
        ]
    },
    "status": {
        "dockerImageRepository": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7",
        "tags": [
            {
                "tag": "latest",
                "items": [
                    {
                        "created": "2015-06-04T13:48:46Z",
                        "dockerImageReference": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest",
                        "image": "95172cd475107436110b0631af4ce28de3335da3b3a01f6e9ff5359d55fcf75e"
                    }
                ]
            }
        ]
    }
}
```

**Comment by liggitt** [comment] 2015-06-04 14:06
the output ImageStream might need "latest" in the spec.tags... not sure if that being missing would prevent the build from running

**Comment by liggitt** [comment] 2015-06-04 14:06
@spadgett can you take a look?

**Comment by liggitt** [comment] 2015-06-04 14:06
(and compare the results of the UI create-from-source with the command line new-app)

**Comment by bparees** [comment] 2015-06-04 19:43
@thoraxe you're not referencing an imagestream as your builder image, so there won't be an imagestream update that can trigger your build.  you're using DockerImage as your reference, which is basically a static reference to a docker pull spec.

 "strategy": {
            "type": "Source",
            "sourceStrategy": {
                "from": {
                    "kind": "DockerImage",
                    "name": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest"
                },
                "incremental": true
            }
        },

compare with:
https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L129

@sspeiche fyi.

**Comment by sspeiche** [comment] 2015-06-04 21:02
Made that change in https://github.com/openshift/nodejs-ex/blob/master/openshift/nodejs-template.json and confirmed it worked.  Thanks @bparees

**Comment by thoraxe** [comment] 2015-06-04 21:11
@bparees I'm not doing anything -- OpenShift is setting all of this up because I'm just using the web console.

The only thing that exists prior to me typing my git repo url in the box is the rhel7 imagestream.

Are you saying that we need to update the builder imagestream definitions?

**Comment by liggitt** [comment] 2015-06-04 21:12
also, did the CLI new-app behave differently given the same inputs? if so, we'd like them to be consistent

**Comment by thoraxe** [comment] 2015-06-04 21:13
I don't know - I haven't tried it with new-app. I can.

**Comment by bparees** [comment] 2015-06-04 21:16
@thoraxe no it sounds like we're not creating the right reference in the buildconfig object when we construct it.  you're picking an imagestream and then we're for some reason not defining the buildconfig to reference that imagestream, we're setting it up to reference a dockerimage instead.

**Comment by bparees** [comment] 2015-06-04 21:22
@csrwng can you make sure osc new-app doesn't have this problem too?  the buildconfig it creates should reference an ImageStreamTag, not a DockerImage for the builder ref.

**Comment by liggitt** [comment] 2015-06-04 21:25
@thoraxe what version are you running? on 6/2 the UI made this change to the generated build config:
```
           strategy: {
-            type: "STI",
-            stiStrategy: {
-              image: dockerSpec
+            type: "Source",
+            sourceStrategy: {
+              from: {
+                kind: "ImageStreamTag",
+                name: input.imageName + ":" + input.imageTag,
+                namespace: input.namespace
+              }
             }
-          }
-        },
```

**Comment by liggitt** [comment] 2015-06-04 21:26
I think that should be a correct ImageStreamTag-based build config now

**Comment by thoraxe** [comment] 2015-06-05 15:32
I just noticed that adding items via the CLI does not automatically start a build. For example, the application sti template (slightly modified) as follows:

```JSON

{
  "kind": "Template",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "quickstart-keyvalue-application",
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3",
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"
    }
  },
  "objects": [
    {
      "kind": "Service",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "frontend",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "web",
            "protocol": "TCP",
            "port": 5432,
            "targetPort": 8080,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "frontend"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },
    {
      "kind": "Route",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "route-edge",
        "creationTimestamp": null
      },
      "spec": {
        "host": "integrated.cloudapps.example.com",
        "to": {
          "kind": "Service",
          "name": "frontend"
        }
      },
      "status": {}
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "ruby-sample",
        "creationTimestamp": null
      },
      "spec": {},
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "ruby-20-rhel7",
        "creationTimestamp": null
      },
      "spec": {
        "dockerImageRepository": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7"
      },
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "BuildConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "ruby-sample-build",
        "creationTimestamp": null,
        "labels": {
          "name": "ruby-sample-build"
        }
      },
      "spec": {
        "triggers": [
          {
            "type": "github",
            "github": {
              "secret": "secret101"
            }
          },
          {
            "type": "generic",
            "generic": {
              "secret": "secret101"
            }
          },
          {
            "type": "imageChange",
            "imageChange": {}
          }
        ],
        "source": {
          "type": "Git",
          "git": {
            "uri": "git://github.com/openshift/ruby-hello-world.git",
            "ref": "beta4"
          }
        },
        "strategy": {
          "type": "Source",
          "sourceStrategy": {
            "from": {
              "kind": "ImageStreamTag",
              "name": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest"
            },
            "incremental": true
          }
        },
        "output": {
          "to": {
            "kind": "ImageStreamTag",
            "name": "ruby-sample:latest"
          }
        },
        "resources": {}
      },
      "status": {
        "lastVersion": 0
      }
    },
    {
      "kind": "DeploymentConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "frontend",
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ImageChange",
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "ruby-helloworld"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "ruby-sample:latest"
              },
              "lastTriggeredImage": ""
            }
          },
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 2,
        "selector": {
          "name": "frontend"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "frontend"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld",
                "image": "ruby-sample",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "ADMIN_USERNAME",
                    "value": "${ADMIN_USERNAME}"
                  },
                  {
                    "name": "ADMIN_PASSWORD",
                    "value": "${ADMIN_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    },
    {
      "kind": "Service",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "database",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "db",
            "protocol": "TCP",
            "port": 5434,
            "targetPort": 3306,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "database"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },
    {
      "kind": "DeploymentConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "database",
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 1,
        "selector": {
          "name": "database"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "database"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld-database",
                "image": "registry.access.redhat.com/openshift3_beta/mysql-55-rhel7:latest",
                "ports": [
                  {
                    "containerPort": 3306,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "Always",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    }
  ],
  "parameters": [
    {
      "name": "ADMIN_USERNAME",
      "description": "administrator username",
      "generate": "expression",
      "from": "admin[A-Z0-9]{3}"
    },
    {
      "name": "ADMIN_PASSWORD",
      "description": "administrator password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MYSQL_USER",
      "description": "database username",
      "generate": "expression",
      "from": "user[A-Z0-9]{3}"
    },
    {
      "name": "MYSQL_PASSWORD",
      "description": "database password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MYSQL_DATABASE",
      "description": "database name",
      "value": "root"
    }
  ],
  "labels": {
    "template": "application-template-stibuild"
  }
}
```

`osc process -f template.json | osc create -f -`

This will deploy the DB but a build never appears to start.

**Comment by thoraxe** [comment] 2015-06-05 15:32
wait, i might have a bad buildconfig...

**Comment by bparees** [comment] 2015-06-05 19:33
@thoraxe yeah your from reference is not valid there.  you've got the wrong imagestreamtag name i believe.

whatever happened with your original issue?  did you update to newer code like @liggitt suggested?  i'd like to get this closed.

**Comment by spadgett** [comment] 2015-06-08 15:30
@liggit I see the following build config different when created by the web console vs command line. (The build did start automatically for me in the web console.)

* Web console adds labels `generatedBy` and `name`
* Web console adds `"ref": "master"` to `spec.source.git`
* Source strategy is a bit different

Web console:

```
    "strategy": {
      "type": "Source",
      "sourceStrategy": {
        "from": {
          "kind": "ImageStreamTag",
          "name": "nodejs-010-centos7:latest"
        }
      }
    }
```

Command line:

```
    "strategy": {
      "type": "Source",
      "sourceStrategy": {
        "from": {
          "kind": "ImageStreamTag",
          "name": "nodejs-010-centos7:latest"
        }
      }
    }
```

This is the command I ran:

> oc new-app openshift/nodejs-010-centos7~https://github.com/openshift/nodejs-ex

**Comment by liggitt** [comment] 2015-06-08 15:32
I think master is the default ref for builds. Labels shouldn't matter. Strategy you plaster looks identical.

**Comment by thoraxe** [comment] 2015-06-08 15:58
I'm also noticing this when processing a template and creating it from CLI:

```json

{
    "kind": "Config",
    "apiVersion": "v1beta1",
    "metadata": {
        "creationTimestamp": null
    },
    "items": [
        {
            "apiVersion": "v1beta1",
            "containerPort": 8080,
            "id": "frontend",
            "kind": "Service",
            "port": 5432,
            "selector": {
                "name": "frontend"
            }
        },
        {
            "apiVersion": "v1beta1",
            "host": "wiring.cloudapps.example.com",
            "id": "sample-app-secure",
            "kind": "Route",
            "metadata": {
                "labels": {
                    "template": "application-template-stibuild"
                },
                "name": "route-edge"
            },
            "serviceName": "frontend"
        },
        {
            "apiVersion": "v1beta1",
            "kind": "ImageStream",
            "metadata": {
                "labels": {
                    "template": "application-template-stibuild"
                },
                "name": "origin-ruby-sample"
            }
        },
        {
            "apiVersion": "v1beta1",
            "kind": "ImageStream",
            "metadata": {
                "labels": {
                    "template": "application-template-stibuild"
                },
                "name": "ruby-20-centos7"
            },
            "spec": {
                "dockerImageRepository": "openshift/ruby-20-centos7"
            }
        },
        {
            "apiVersion": "v1beta1",
            "kind": "BuildConfig",
            "metadata": {
                "labels": {
                    "name": "ruby-sample-build",
                    "template": "application-template-stibuild"
                },
                "name": "ruby-sample-build"
            },
            "parameters": {
                "output": {
                    "to": {
                        "name": "origin-ruby-sample"
                    }
                },
                "source": {
                    "git": {
                        "ref": "beta4",
                        "uri": "git://github.com/openshift/ruby-hello-world.git"
                    },
                    "type": "Git"
                },
                "strategy": {
                    "stiStrategy": {
                        "image": "openshift/ruby-20-centos7"
                    },
                    "type": "STI"
                }
            },
            "triggers": [
                {
                    "github": {
                        "secret": "secret101"
                    },
                    "type": "github"
                },
                {
                    "generic": {
                        "secret": "secret101"
                    },
                    "type": "generic"
                },
                {
                    "imageChange": {
                        "from": {
                            "name": "ruby-20-centos7"
                        },
                        "image": "openshift/ruby-20-centos7",
                        "tag": "latest"
                    },
                    "type": "imageChange"
                }
            ]
        },
        {
            "apiVersion": "v1beta1",
            "kind": "DeploymentConfig",
            "metadata": {
                "labels": {
                    "template": "application-template-stibuild"
                },
                "name": "frontend"
            },
            "template": {
                "controllerTemplate": {
                    "podTemplate": {
                        "desiredState": {
                            "manifest": {
                                "containers": [
                                    {
                                        "env": [
                                            {
                                                "name": "ADMIN_USERNAME",
                                                "value": "adminAAM"
                                            },
                                            {
                                                "name": "ADMIN_PASSWORD",
                                                "value": "vpawLtdk"
                                            },
                                            {
                                                "name": "MYSQL_USER",
                                                "value": "userFTS"
                                            },
                                            {
                                                "name": "MYSQL_PASSWORD",
                                                "value": "VlMbI24Y"
                                            },
                                            {
                                                "name": "MYSQL_DATABASE",
                                                "value": "root"
                                            }
                                        ],
                                        "image": "origin-ruby-sample",
                                        "name": "ruby-helloworld",
                                        "ports": [
                                            {
                                                "containerPort": 8080
                                            }
                                        ]
                                    }
                                ],
                                "version": "v1beta1"
                            }
                        },
                        "labels": {
                            "name": "frontend"
                        }
                    },
                    "replicaSelector": {
                        "name": "frontend"
                    },
                    "replicas": 1
                },
                "strategy": {
                    "recreateParams": {},
                    "type": "Recreate"
                }
            },
            "triggers": [
                {
                    "imageChangeParams": {
                        "automatic": true,
                        "containerNames": [
                            "ruby-helloworld"
                        ],
                        "from": {
                            "name": "origin-ruby-sample"
                        },
                        "tag": "latest"
                    },
                    "type": "ImageChange"
                }
            ]
        }
    ]
}
```

**Comment by spadgett** [comment] 2015-06-08 16:39
@liggitt yep, pasted the wrong thing.

Here's web.

```
    "strategy": {
      "type": "Source",
      "sourceStrategy": {
        "from": {
          "kind": "ImageStreamTag",
          "namespace": "project1",
          "name": "nodejs:latest"
        }
      }
    }
```

**Comment by liggitt** [comment] 2015-06-08 16:47
a missing namespace in a from ImageStreamTag defaults to the current namespace, I believe... so if that is in project1, that should be equivalent. what do the definitions of the nodejs (or nodejs-10-centos7? not sure why that was different in the latest paste) imagestreams look like (CLI vs UI)?

**Comment by liggitt** [comment] 2015-06-08 16:50
This issue is getting tough to follow. Can someone clarify the following:
1. Is the issue reproducible from a clean state in the web console? Can you pastebin the build config and image streams?
2. Is the issue reproducible from a clean state in the CLI? Can you pastebin the build config and image streams?

**Comment by bparees** [comment] 2015-06-08 16:51
+! @liggitt

**Comment by spadgett** [comment] 2015-06-08 17:01
@liggitt @bparees FWIW, I have not been able to reproduce this issue in the web console or command line.

@thoraxe ?

**Comment by liggitt** [comment] 2015-06-08 17:03
Are you using image streams in a shared namespace or in the project?

**Comment by spadgett** [comment] 2015-06-08 18:25
@liggitt I've tested both. Automatic builds were triggered both ways.

**Comment by bparees** [comment] 2015-06-08 18:30
thanks @spadgett.  i'm closing this.

**Closed by bparees** 2015-06-08 18:30 UTC
Labels: component/build, component/web, kind/bug, priority/P2
