### ISSUE TITLE
Deployment failing since upgrade to 1.1.6

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#8450] opened 2016-04-11 10:29 UTC
After upgrade from 1.1.3 to 1.1.6 we got 

##### Version
1.1.6

##### Steps To Reproduce
1. create new app

##### Current Result
```
Cannot update deployment 123601-32/redmine-app-1 status to Pending: replicationcontrollers "redmine-app-1" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Error syncing pod, skipping: failed to "TeardownNetwork" for "redmine-1-build_123601-32" with TeardownNetworkError: "Failed to teardown network for pod \"fc9e40d3-ffc5-11e5-9cfc-386077264a54\" using network plugins \"redhat/openshift-ovs-subnet\": exit status 1"
```

##### Expected Result

Deploy passing.

##### Additional Information
```
$ oadm diagnostics
WARN:  [DCli2006 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:134]
       Timed out preparing diagnostic pod logs for streaming, so this diagnostic cannot run.
       It is likely that the image 'openshift/origin-deployer:v1.1.6' was not pulled and running yet.
       Last error: (*errors.StatusError[2]) container "pod-diagnostics" in pod "pod-diagnostic-test-gv42i" is waiting to start: ContainerCreating
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
WARN:  [DClu1012 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:274]
       The pod logs for the "docker-registry-1-9hk8v" pod belonging to
       the "docker-registry" service indicated unknown errors.
       This could result in problems with builds or deployments.
       Please examine the log entries to determine if there might be
       any related problems:
       
       time="2016-04-11T07:12:04.248849776Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.6 http.request.host=
"172.30.203.199:5000" http.request.id=fab97f54-51f4-4041-9e4e-f5cdfe53b2c0 http.request.method=GET http.request.remoteaddr="10.3.1.1:52080" http.request.uri="/v2/" http.req
uest.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" instance.id=b8ae31b3-a163-405e-855d-35200ad32c2a 
       time="2016-04-11T07:12:42.707307323Z" level=error msg="response completed with error" err.code="BLOB_UNKNOWN" err.detail=sha256:5f70bf18a086007016e948b04aed3b82103a3
6bea41755b6cddfaf10ace3c6ef err.message="blob unknown to registry" go.version=go1.6 http.request.host="172.30.203.199:5000" http.request.id=1d79e30f-6b32-4f01-b4d8-073a08a4
6c81 http.request.method=HEAD http.request.remoteaddr="10.3.1.1:52131" http.request.uri="/v2/masi/redmine/blobs/sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfa
f10ace3c6ef" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf
-8" http.response.duration=12.633175ms http.response.status=404 http.response.written=157 instance.id=b8ae31b3-a163-405e-855d-35200ad32c2a vars.digest="sha256:5f70bf18a0860
07016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef" vars.name="masi/redmine" 
       time="2016-04-11T07:12:42.841086259Z" level=error msg="response completed with error" err.code="BLOB_UNKNOWN" err.detail=sha256:83c391c56a2e47062f5c5808ac94686ed5c9d
4fa5f1f0e91b5d30d3a14a626ee err.message="blob unknown to registry" go.version=go1.6 http.request.host="172.30.203.199:5000" http.request.id=8a3b9fd0-c5d3-4c1f-830f-0a997c4c
a363 http.request.method=HEAD http.request.remoteaddr="10.3.1.1:52136" http.request.uri="/v2/masi/redmine/blobs/sha256:83c391c56a2e47062f5c5808ac94686ed5c9d4fa5f1f0e91b5d30
d3a14a626ee" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf
-8" http.response.duration=12.087671ms http.response.status=404 http.response.written=157 instance.id=b8ae31b3-a163-405e-855d-35200ad32c2a vars.digest="sha256:83c391c56a2e4
7062f5c5808ac94686ed5c9d4fa5f1f0e91b5d30d3a14a626ee" vars.name="masi/redmine" 
       time="2016-04-11T07:14:26.325472007Z" level=error msg="response completed with error" err.code="BLOB_UNKNOWN" err.detail=sha256:ea2e5214b9849142cd9187bf7d139c10a5d15
945d697c1e5dad4b155031c66e8 err.message="blob unknown to registry" go.version=go1.6 http.request.host="172.30.203.199:5000" http.request.id=17817d4d-4188-41b2-8c45-a3286601
d3d3 http.request.method=HEAD http.request.remoteaddr="10.3.1.1:52268" http.request.uri="/v2/masi/redmine/blobs/sha256:ea2e5214b9849142cd9187bf7d139c10a5d15945d697c1e5dad4b
155031c66e8" http.request.useragent="docker/1.9.1 go/go1.4.2 kernel/3.10.0-327.13.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf
-8" http.response.duration=12.552035ms http.response.status=404 http.response.written=157 instance.id=b8ae31b3-a163-405e-855d-35200ad32c2a vars.digest="sha256:ea2e5214b9849
142cd9187bf7d139c10a5d15945d697c1e5dad4b155031c66e8" vars.name="masi/redmine" 
```

**Comment by david-strejc** [comment] 2016-04-11 12:26
We have found, that this may be connected to:

https://bugzilla.redhat.com/show_bug.cgi?id=1322077

and we are trying this updated script:

https://github.com/pravisankar/openshift-sdn/blob/8cc73975cd49847e59a0d079e116113ce8344584/plugins/osdn/ovs/bin/openshift-sdn-ovs

I will have additional info soon.

**Comment by kargakis** [comment] 2016-04-11 12:27
@pweil- seems like a networking issue

**Comment by david-strejc** [comment] 2016-04-11 12:30
I don't know if this is the case but I've found that issue in bugzilla - so I am reporting it here and my college will try to update installation with script I've posted and we will see if this helps.

**Comment by kargakis** [comment] 2016-04-11 12:32
@david-strejc in the diagnostics it is reported that you may be missing the latest deployer image

**Comment by david-strejc** [comment] 2016-04-11 12:45
But this is fresh installation I've made using openshift-ansible.

**Comment by pweil-** [comment] 2016-04-15 20:08
@knobunc is this the same as https://bugzilla.redhat.com/show_bug.cgi?id=1322077 that was fixed in https://github.com/openshift/openshift-sdn/pull/277 ?

**Comment by kargakis** [comment] 2016-08-26 21:55
@david-strejc is this still an issue?

**Comment by knobunc** [comment] 2016-08-29 14:58
Unfortunately, that error message is generated whenever the netowkring teardown script is called twice, or if the resources were never properly set up.  However, the error itself looks dire, but is harmless.  The root cause of the problem is somewhere else.

https://bugzilla.redhat.com/show_bug.cgi?id=1333393 is tracking the issue.

**Closed by knobunc** 2016-08-29 14:58 UTC
Labels: component/deployments, component/networking, kind/bug, priority/P2
