### ISSUE TITLE
Service link on route page doesn't link to service

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6342] opened 2015-12-16 15:01 UTC
This link is wrong. It links back to the route you're already looking at.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/11844275/df3f8702-a3db-11e5-8fc2-12d0e8a3dbe2.png)

@jwforres Please assign to me. I'm working in this code already.

**Comment by jwforres** [comment] 2015-12-16 15:26
@spadgett also looks like a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1291559

**Closed** 2015-12-16 23:23 UTC
Labels: area/usability, component/web, kind/bug, priority/P2
