### ISSUE TITLE
docker build using a pull secret Building from a template should create a docker build that pulls using a secret run it

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12007] opened 2016-11-23 14:05 UTC
### Extended.[builds][pullsecret][Conformance] docker build using a pull secret Building from a template should create a docker build that pulls using a secret run it

Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8838/testReport/junit/(root)/Extended/_builds__pullsecret__Conformance__docker_build_using_a_pull_secret_Building_from_a_template_should_create_a_docker_build_that_pulls_using_a_secret_run_it/) in [this job](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8838/)

```
/data/src/github.com/openshift/origin/test/extended/builds/docker_pullsecret.go:48
Expected
    <bool>: false
to be true
/data/src/github.com/openshift/origin/test/extended/builds/docker_pullsecret.go:41
```

**Comment by bparees** [comment] 2016-11-23 14:26
looks like a registry issue:
```
2016-11-22T22:59:12.736978000Z Successfully built 84ff1257879c
2016-11-22T22:59:12.760573000Z Pushing image 172.30.153.38:5000/extended-test-docker-build-pullsecret-jt7vn-saoxh/image1:latest ...
2016-11-22T22:59:17.392481000Z Registry server Address: 
2016-11-22T22:59:17.392786000Z Registry server User Name: serviceaccount
2016-11-22T22:59:17.393058000Z Registry server Email: serviceaccount@example.org
2016-11-22T22:59:17.393318000Z Registry server Password: <<non-empty>>
2016-11-22T22:59:17.393586000Z error: build error: Failed to push image: Error: Status 404 trying to push repository extended-test-docker-build-pullsecret-jt7vn-saoxh/image1: "404 page not found\n"
```

note that we dump some registry pod info here and the filesystem looks pretty full, but i don't see that causing a 404:

```
Nov 22 17:59:24.393: INFO: Running 'oc exec --config=/tmp/extended-test-docker-build-pullsecret-jt7vn-saoxh-user.kubeconfig --namespace=extended-test-docker-build-pullsecret-jt7vn-saoxh -n default docker-registry-1-z017o df --config /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig'


 df from registry pod: 
Filesystem                                                                                         1K-blocks     Used Available Use% Mounted on
/dev/mapper/docker-202:2-33888628-33b56421827c5be7467b9b65760e25093e3533d79cf8230ab8d0242a5ecd7803  10474496   411548  10062948   4% /
tmpfs                                                                                                8002656        0   8002656   0% /dev
tmpfs                                                                                                8002656        0   8002656   0% /sys/fs/cgroup
/dev/mapper/docker--vg-openshift--xfs--vol--dir                                                      5212160    33076   5179084   1% /registry
/dev/xvda2                                                                                          26202092 16463532   9738560  63% /run/secrets
shm                                                                                                    65536        0     65536   0% /dev/shm
tmpfs                                                                                                8002656       16   8002640   1% /run/secrets/kubernetes.io/serviceaccount
```

**Comment by miminar** [comment] 2016-11-25 13:14
Running the extended test alone in a loop, I cannot reproduce it locally. Trying whole conformance suite now.

**Comment by miminar** [comment] 2016-11-25 16:42
The conformance suite takes like forever on my end. I didn't manage to reproduce in a first run taking 1 and half hour. The second is running twice that time without hitting the test in question.

I'll rather focus on collecting more info in jenkins.

**Comment by miminar** [comment] 2016-11-28 08:24
Since I failed to reproduce locally, I fixed an extended cleanup to let us collect openshift and registry log in the jenkins. Please review #12037 

The referenced job terminated with:

```
[INFO] Stacked plot for log subset "memory" written to /tmp/openshift/test-extended/core/logs/memory.pdf
/data/src/github.com/openshift/origin/test/extended/setup.sh: line 45: cleanup_openshift: command not found
```

**Comment by miminar** [comment] 2016-11-28 11:27
Is this really a P1? So far no luck hitting this in my previous 2 attempts in jenkins.

**Comment by stevekuznetsov** [comment] 2016-11-28 14:21
@bparees @danmcp do we have some tangible guidelines for prioritizing this?

**Comment by danmcp** [comment] 2016-11-28 14:32
@stevekuznetsov If it's not happening frequently (> 2%) then it can move to a P2.

**Comment by miminar** [comment] 2016-12-06 14:47
I failed to reproduce in jenkins in 10 out of 10 runs. I'm postponing investigation until someone hits this.

**Comment by eparis** [comment] 2017-03-15 00:43
Seems like I've hit this twice today...
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/216/ is one of them...

**Comment by smarterclayton** [comment] 2017-03-21 21:27
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_gce/127/testReport/junit/(root)/Extended/_builds__pullsecret__Conformance__docker_build_using_a_pull_secret_Building_from_a_template_should_create_a_docker_build_that_pulls_using_a_secret_run_it/

**Comment by miminar** [comment] 2017-03-27 07:35
I wish there were registry logs available for gce runs.

**Comment by smarterclayton** [comment] 2017-03-27 16:07
Pull requests welcome!  :)

**Comment by miminar** [comment] 2017-03-28 10:29
Here you go: #13557

**Comment by csrwng** [comment] 2017-04-07 16:45
New failure https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/629/

**Comment by bparees** [comment] 2017-10-25 20:19
most recent flake didn't include the logs, so i can't determine if it was really a recurrence of this issue or not.  Otherwise i've not seen/heard evidence that this is still an issue.  Closing and someone can open a new flake w/ logs if it's still happening.

**Closed by bparees** 2017-10-25 20:19 UTC
Labels: component/build, component/imageregistry, kind/test-flake, priority/P2
