### ISSUE TITLE
openshift-api issues breaking cluster

### ISSUE THREAD

**Issue by kikisdeliveryservice** [openshift/origin#21612] opened 2018-12-04 21:01 UTC
There are currently openshift-api issues that are breaking cluster to become unusable.

##### Steps To Reproduce
1. run the installer to get a cluster running
2. see the failures

##### Current Result
openshift-apiserver is down with various connection refused errors:
`E1204 19:21:10.940510       1 memcache.go:147] couldn't get resource list for samplesoperator.config.openshift.io/v1alpha1: Get https://172.30.0.1:443/apis/samplesoperator.config.openshift.io/v1alpha1?timeout=32s: dial tcp 172.30.0.1:443: connect: connection refused
E1204 19:21:10.948714       1 memcache.go:147] couldn't get resource list for servicecertsigner.config.openshift.io/v1alpha1: Get https://172.30.0.1:443/apis/servicecertsigner.config.openshift.io/v1alpha1?timeout=32s: dial tcp 172.30.0.1:443: connect: connection refused
E1204 19:21:10.953465       1 memcache.go:147] couldn't get resource list for tuned.openshift.io/v1alpha1: Get https://172.30.0.1:443/apis/tuned.openshift.io/v1alpha1?timeout=32s: dial tcp 172.30.0.1:443: connect: connection refused
E1204 19:21:11.805850       1 reflector.go:136] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.RoleBinding: Get https://172.30.0.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
E1204 19:21:11.818657       1 reflector.go:136] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.LimitRange: Get https://172.30.0.1:443/api/v1/limitranges?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
E1204 19:21:11.818742       1 reflector.go:136] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Service: Get https://172.30.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
`
Cannot ssh into master, tcp/connection errors throughout pods, for a time oc and kubectl commands also not working.  Eventually most of the pods break with CrashLoopError.

##### Expected Result
I don't expect any errors.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by ashcrow** [comment] 2018-12-04 21:12
This issue came out of a conversation with @deads2k and @brancz.

**Comment by deads2k** [comment] 2018-12-04 21:13
When your server comes back up (it will crash and try to recover) quickly run

```
oc label ns openshift-monitoring 'openshift.io/run-level=1'
oc create quota -nopenshift-monitoring stoppods --hard=pods=0
oc -n openshift-monitoring delete pods --all
```

And you should end up with a stable cluster.  Just one without any monitoring

**Comment by derekwaynecarr** [comment] 2018-12-04 22:02
we can bump domain memory for masters to 4Gi
https://github.com/openshift/installer/blob/ee73f72017bdfe681629e8d3f41cb5ae1d5b4775/pkg/asset/machines/libvirt/machines.go#L70

@openshift/sig-cloud

**Comment by wking** [comment] 2018-12-05 19:47
> we can bump domain memory for masters to 4Gi
> https://github.com/openshift/installer/blob/ee73f72017bdfe681629e8d3f41cb5ae1d5b4775/pkg/asset/machines/libvirt/machines.go#L70

Currently only the installer provisions masters (because once the cluster is running you'd need manual intervention to attach new etcd nodes).  And installer-launched masters got bumped to 4GB in openshift/installer#785 (just landed).

**Comment by wking** [comment] 2018-12-08 08:07
The current API instability may be a symptom of some underlying master instability.  I don't know what's going on yet, but in a recent CI run, there was a running die-off of pods before the machine-config daemon pulled the plug and rebooted the node.  Notes for the MCD part in openshift/machine-config-operator#224.  Notes on etcd-member (the first pod to die) in openshift/installer#844.  I don't know what's going on there, but I can certainly see occasional master reboots causing connectivity issues like [these][1].

[1]: https://github.com/openshift/origin/issues/21612#issuecomment-445067206

**Comment by wking** [comment] 2018-12-14 06:16
I think this might have been resolved by openshift/machine-config-operator#225.  Can anyone still reproduce?  If not, can we close this?

**Comment by mslovy** [comment] 2019-01-04 16:36
I still see the similar error in origin-template-service-broker


E0104 16:14:25.634855       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
--
  | E0104 16:15:56.017707       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:16:26.196299       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:18:26.868674       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | W0104 16:19:11.850715       1 reflector.go:272] github.com/openshift/client-go/template/informers/externalversions/factory.go:101: watch of *v1.Template ended with: The resourceVersion for the provided watch is too old.
  | E0104 16:19:27.129940       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:20:57.681989       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:21:27.845002       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:21:57.932396       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:23:28.291818       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:25:28.747637       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:26:59.112399       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:27:59.312813       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | W0104 16:28:04.023096       1 reflector.go:272] github.com/openshift/client-go/template/informers/externalversions/factory.go:101: watch of *v1.Template ended with: The resourceVersion for the provided watch is too old.
  | E0104 16:31:30.049245       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:32:30.262111       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:33:00.432617       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:35:00.870254       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
  | E0104 16:36:01.147749       1 memcache.go:147] couldn't get resource list for servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request

**Closed** 2019-06-04 01:17 UTC
Labels: kind/bug, lifecycle/rotten

**Comment by dlakatos847** [comment] 2019-08-06 08:54
Issue still present with v3.11 on OpenSuSE Tw.
