### ISSUE TITLE
FINISHED STAGE: FAILURE: RECORD THE STARTING METADATA

### ISSUE THREAD

**Issue by legionus** [openshift/origin#16428] opened 2017-09-19 10:02 UTC
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/221/consoleFull#77791197358b6e51eb7608a5981914356

```
########## STARTING STAGE: RECORD THE STARTING METADATA ##########
+ [[ -s /var/lib/jenkins/jobs/test_branch_origin_extended_image_ecosystem/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_branch_origin_extended_image_ecosystem/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/0e3f679e82df3bdf38d58b2189a4c43db1916eb1
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/0e3f679e82df3bdf38d58b2189a4c43db1916eb1
++ export PATH=/var/lib/jenkins/origin-ci-tool/0e3f679e82df3bdf38d58b2189a4c43db1916eb1/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/0e3f679e82df3bdf38d58b2189a4c43db1916eb1/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_image_ecosystem/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_image_ecosystem/workspace/.config
++ mktemp
+ script=/tmp/tmp.mYYmuegPVd
+ cat
+ chmod +x /tmp/tmp.mYYmuegPVd
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.mYYmuegPVd openshiftdevel:/tmp/tmp.mYYmuegPVd
ssh_exchange_identification: read: Connection reset by peer
lost connection
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: RECORD THE STARTING METADATA [00h 00m 00s] ##########
Build step 'Execute shell' marked build as failure
```

**Comment by bparees** [comment] 2017-09-19 13:45
looks like a dupe of https://github.com/openshift/origin/issues/14771

which is basically "Aws infrastructure is flaky" so it probably won't get resolved, @stevekuznetsov ?

**Closed by bparees** 2017-09-19 13:45 UTC
Labels: kind/test-flake
