### ISSUE TITLE
ImageStreamImage creationTimestamp is null

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#12051] opened 2016-11-29 12:47 UTC
```console
[@dev] .../openshift/origin # oc get isimage ruby-ex@sha256:816f64caa697980f45cb2e9d69d78c8f3839e6668a72752daa87e5f124befdf4
NAME                                                                              DOCKER REF                                                                                                UPDATED         IMAGENAME
ruby-ex@sha256:816f64caa697980f45cb2e9d69d78c8f3839e6668a72752daa87e5f124befdf4   172.30.167.99:5000/test/ruby-ex@sha256:816f64caa697980f45cb2e9d69d78c8f3839e6668a72752daa87e5f124befdf4   292 years ago   sha256:816f64caa697980f45cb2e9d69d78c8f3839e6668a72752daa87e5f124befdf4
```

It seems like this image was last updated by the spanish inquisition :-)

**Comment by ncdc** [comment] 2016-11-29 21:42
Is this a dupe of #11914 ?

**Closed** 2016-11-30 11:45 UTC
Labels: component/image, kind/bug, priority/P3

**Comment by mfojtik** [comment] 2016-11-30 13:36
@ncdc yep, I will close that one as well.
