### ISSUE TITLE
openshift.io/image.insecureRepository applies only to first tag in an ImageStream?

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#8965] opened 2016-05-20 18:15 UTC
Perhaps I'm misinterpreting the documentation [here](https://docs.openshift.org/latest/dev_guide/managing_images.html#insecure-registries), but it reads as if I can specify openshift.io/image.insecureRepository annotation at the ImageStream level and it should apply to all tags or I could specify an importPolicy for each tag. However in practice I'm finding that it only applies to the first and further it only successfully imports after running `oc import-image`.

##### Version
openshift v1.3.0-alpha.0-619-g2dde6d7
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0
oc v1.3.0-alpha.0-619-g2dde6d7
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
1. oc create -n openshift -f https://gist.githubusercontent.com/sdodson/f2ba3519bfa7bc66f35edaf749468e19/raw/663d3e7c68738eed106c4f476b767991f01a3eea/php-is.json
2. oc describe is php

##### Current Result
no images imported, however if I run `oc import-image -n openshift php` the first one imports but others do not.

```
oc import-image -n openshift php
The import completed successfully.

Name:                   php
Namespace:              openshift
Created:                9 minutes ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2016-05-20T18:10:49Z
                        openshift.io/image.insecureRepository=true
Docker Pull Spec:       <none>

Tag     Spec                                                                                    Created                 PullSpec                                                                        Image
latest  5.6                                                                                     Less than a second ago  registry.example.com:8888/rhscl/php-56-rhel7:latest  bbfc4eb8005bacd9fc006995ed9b9548bb0478d8d65cf4c4cbdb605a177e7b2e
5.6    registry.example.com:8888/rhscl/php-56-rhel7:latest !        Less than a second ago  <same>                                                                          bbfc4eb8005bacd9fc006995ed9b9548bb0478d8d65cf4c4cbdb605a177e7b2e
5.5     registry.example.com:8888/openshift3/php-55-rhel7:latest     9 minutes ago                                                                                           import failed: this repository is HTTP only and requires the insecu...
```

##### Expected Result
All tags imported from an insecure registry.

**Comment by sdodson** [comment] 2016-05-20 18:16
@soltysh FYI

**Comment by soltysh** [comment] 2016-05-20 19:50
This is cause by `oc import-image php` which by default picks only single tag to import, if none is passed, `latest` is used. To properly import all tags `--all` flag should be used, but that might not quite work and it's on my next todo list. I'll assign this bug to myself and will tackle those sometime next week.

**Comment by soltysh** [comment] 2016-05-20 19:53
I'll close this as not a bug but I'll create a new one to track the `--all` not working.

**Closed by soltysh** 2016-05-20 19:53 UTC
Labels: component/image, priority/P2
