### ISSUE TITLE
First push to a docker registry from latest fails with 404

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9419] opened 2016-06-18 22:38 UTC
On latest:

```
oc cluster up
oc new-project example
oc new-app cakephp-mysql-example
oc logs -f bc/cakephp-mysql-example
<no image is pushed, but build succeeds>
```

Server returns 404 to the PUT. 

```
time="2016-06-18T22:34:30.102351918Z" level=info msg="version=v2.1.0+unknown"
time="2016-06-18T22:34:30.112852425Z" level=info msg="redis not configured" go.version=go1.6 instance.id=1941a3f9-9b64-42f2-a486-1a4a0e689c63
time="2016-06-18T22:34:30.113149933Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6 instance.id=1941a3f9-9b64-42f2-a486-1a4a0e689c63
time="2016-06-18T22:34:30.113229827Z" level=info msg="Using Origin Auth handler"
time="2016-06-18T22:34:30.114934145Z" level=debug msg="configured \"openshift\" access controller" go.version=go1.6 instance.id=1941a3f9-9b64-42f2-a486-1a4a0e689c63
time="2016-06-18T22:34:30.115220479Z" level=info msg="listening on :5000" go.version=go1.6 instance.id=1941a3f9-9b64-42f2-a486-1a4a0e689c63
time="2016-06-18T22:34:30.114640268Z" level=info msg="Starting upload purge in 44m0s" go.version=go1.6 instance.id=1941a3f9-9b64-42f2-a486-1a4a0e689c63
172.17.0.1 - - [18/Jun/2016:22:34:46 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.17.0.1 - - [18/Jun/2016:22:34:46 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go-http-client/1.1"
10.0.2.15 - - [18/Jun/2016:22:34:46 +0000] "PUT /v1/repositories/example/cakephp-mysql-example/ HTTP/1.1" 404 19 "" "docker/1.9.1 go/go1.5.3 kernel/4.2.3-300.fc23.x86_64 os/linux arch/amd64"
```

Is this a race condition in the registry (some data it needs is not available yet)?

Subsequent builds and pushes work fine.

**Comment by smarterclayton** [comment] 2016-06-19 00:53
This was `docker-1.9.1-5.git64eb95e.fc22.x86_64`.

**Comment by kargakis** [comment] 2016-06-21 11:44
I think this is because sometimes the registry crashloopbacks: http://pastebin.com/Me3P5DAw
The build completes, but in the meantime the registry is restarted. `oc cluster up` should wait for the registry deployment to complete before finishing provisioning. cc: @csrwng @legionus

**Comment by kargakis** [comment] 2016-06-21 12:00
Note that I am running with 2.4 but I have observed this crashloopback in the registry in our current version too

**Comment by csrwng** [comment] 2016-06-21 15:14
The false build success has been fixed with https://github.com/openshift/origin/pull/9421


> oc cluster up should wait for the registry deployment to complete before finishing provisioning.

@kargakis not sure this is the best approach. For most cases, I think it's better for `oc cluster up` to let you interact with the system as quickly as possible. If it takes longer to start, it's going to become less useful to people. If the registry is crashing on first deploy, we should look into that. On the build side, we need to ensure we retry within reason to push an image.

**Comment by kargakis** [comment] 2016-06-21 15:18
The issue is probably a too fast liveness probe. @legionus is looking at it.

**Comment by kargakis** [comment] 2016-06-21 15:18
cc: @mfojtik

**Comment by bparees** [comment] 2017-10-13 21:55
i'm not sure if changes were made ( @legionus ?) but here's the new liveness probe:

```
livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
```

which means 10s initial delay + 2 failures at 10s each, before the 3rd failure will cause a restart.  So 30s seems like sufficient time to get the registry up and running.

Between that and not hearing more reports of crashlooping registries, i'm going to consider this closed (either because the timeout did get increased and no one closed this issue, or because the newer registry now starts fast enough that those intervals are appropriate).

**Closed by bparees** 2017-10-13 21:55 UTC
Labels: component/imageregistry, priority/P2
