### ISSUE TITLE
Unable to restart cluster (macOS+docker for mac)

### ISSUE THREAD

**Issue by the-destro** [openshift/origin#11399] opened 2016-10-17 17:38 UTC
The process for "restarting" an existing cluster is not clear/not working. doing a
##### Version

oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth
##### Steps To Reproduce
1. Create fresh cluster with `oc cluster up`
2. Exit docker for mac
3. Re-launch docker for mac
4. Origin is not restarted and `oc cluster up` fails with

```
$ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ...
   Deleted existing OpenShift container
-- Checking for openshift/origin:v1.3.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... FAIL
   Error: cannot determine a server IP to use
   Caused By:
     Error: could not determine local IP address to use
     Caused By:
       Error: cannnot start simple server on Docker host
       Caused By:
         Error: cannot start container a86301bdfa70f853d787447cc2815a6357afdea02ba79177a6598ec89d407c3c
         Caused By:
           Error: API error (500): {"message":"driver failed programming external connectivity on endpoint prickly_sammet (079351e7692c0bb5c539f0521bc777093ecf3a841ccaf6b5d766324c16ec1325): Error starting userland proxy: Bind for 0.0.0.0:8443 failed: port is already allocated"}
```
##### Current Result

Fail to restart
##### Expected Result

should restart on daemon restart

**Comment by csrwng** [comment] 2016-10-18 11:35
@the-destro please run 'oc cluster down' before running 'cluster up' again. The problem is that socat is likely running and causing a port conflict.

**Comment by the-destro** [comment] 2016-10-18 22:57
@csrwng that will only bring up a brand new cluster and will wipe out the old(at least that is the behavior for me)

**Comment by csrwng** [comment] 2016-10-19 10:49
@the-destro I see, so what you want to do is restart without losing your data?
There's 2 options: 
1) Just store your data/config in a host directory (--host-data-dir=/local/dir and --use-existing-config) when bringing up your cluster. That way, you can 'oc cluster down' and 'oc cluster up' and you don't lose your data or config.

2) Do a simple docker stop and start of the origin container (`docker stop origin && docker start origin`)

**Comment by the-destro** [comment] 2016-10-24 16:36
so, if I restart the docker daemon via docker for mac, and then try and do the docker start origin I get ```docker start origin
Error response from daemon: linux mounts: Path /var/lib/origin/openshift.local.volumes is mounted on /var but it is not a shared mount.
Error: failed to start containers: origin``` 

Using the --host-data-dir as you suggested does preserve state so it looks like option #1 is the one that I need. It may be good, btw, to maybe have oc do a check on cluster up so it doesn't run into that socat issue?

**Comment by csrwng** [comment] 2016-10-24 19:06
> It may be good, btw, to maybe have oc do a check on cluster up so it doesn't run into that socat issue?

@the-destro it does do one when starting up... not really sure why it didn't work in your case:
https://github.com/openshift/origin/blob/d50865b227ea3acbd5b51ef86c6e6eb79740ddb1/pkg/bootstrap/docker/openshift/helper_unix.go#L62

**Comment by csrwng** [comment] 2016-11-03 13:31
@the-destro are you still having an issue or is it ok to close this one?

**Comment by the-destro** [comment] 2016-11-04 18:04
I guess close for now. It is not a great user experience but I can write some wrappers around it to make sure everything works correctly

**Closed** 2016-11-05 11:13 UTC
Labels: component/cli, priority/P2
