### ISSUE TITLE
Build does not trigger automatically when image already exists:

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13773] opened 2017-04-14 21:59 UTC
The following build config should be triggered immediately if `prometheus:binaries` exists, but it does not.

```
  apiVersion: v1
  kind: BuildConfig
  metadata:
    name: prometheus
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: prometheus:latest
    source:
      images:
      - from:
          kind: ImageStreamTag
          name: prometheus:binaries
        paths:
        - destinationDir: .
          sourcePath: /go/src/github.com/prometheus/prometheus
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: busybox:latest
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: prometheus:binaries
      type: ImageChange
```

**Comment by smarterclayton** [comment] 2017-04-14 21:59
It looks like it waits for the next resync interval

**Comment by smarterclayton** [comment] 2017-04-14 22:00
Maybe this is fixed by generic image trigger controller, but I want to understand whether this is related to 3.6.0-alpha.0 code or not.

**Comment by bparees** [comment] 2017-04-15 00:11
it's not surprising to me since the imagechange logic is edge triggered by imagechange events (or the resync), not buildconfig change events which is what this would fall under, and if the imagestreamtag already exists, then we won't get an event until we resync.

it's probably historically gone unnoticed since most new buildconfigs get triggered by their configchangetrigger anyway, but i guess if you have an existing buildconfig and add an imagechangetrigger, i guess you could hit this.

@csrwng is reworking our buildcontroller this sprint, perhaps this is something he can address as part of that.

anyway i don't think it's a regression in 3.6.

**Comment by csrwng** [comment] 2017-04-26 14:32
@bparees this would have to be addressed in the rework of the buildconfig controller, not the build controller. But I assume we'll be tackling that next.

**Comment by csrwng** [comment] 2017-06-27 20:01
This was addressed by the image trigger controller

**Closed by csrwng** 2017-06-27 20:01 UTC
Labels: component/build, priority/P2
