### ISSUE TITLE
rolling deployment fails if no previous pods exists 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#6181] opened 2015-12-03 12:30 UTC
A Rolling deployment fails if the previous RC does not have a pod deployed.  This case can occur when a prvious pod deployment fails to deploy for application reasons. this will block openshift from performing further deployments. 
To reproduce .
  - Create a basic application, new-app
  - Scale down a deployments pods to zero
  - Perform a "deploy" 

Openshift should not fail on deployment when no previous pods are present. 

I1201 00:45:35.825356       1 deployer.go:198] Deploying from dev/qa-test-1 to dev/qa-test-2 (replicas: 0)
2
I1201 00:45:36.919250       1 rolling.go:232] RollingUpdater: Continuing update with existing controller qa-test-2.
3
F1201 00:45:36.931130       1 deployer.go:65] one of maxSurge or maxUnavailable must be specified

**Comment by kargakis** [comment] 2015-12-03 12:33
Dupe of https://github.com/openshift/origin/issues/5787

**Closed** 2015-12-04 15:05 UTC
