### ISSUE TITLE
Unable to create from template in UI

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1953] opened 2015-04-28 17:31 UTC
To reproduce, import this template:

```
osc create -f https://raw.githubusercontent.com/mfojtik/origin/zookeeper_example/examples/zookeeper/zookeeper_config.json
```

Then navigate to UI and hit Create/Browse all templates. Choose 'zookeeper' template and click 'Select template'. The next screen shows no Images. If you click on 'Create' nothing happens.

@csrwng

**Comment by mfojtik** [comment] 2015-04-28 17:52
I made the template more robust (deploymentConfig, BC, imageStream)... still no luck

https://gist.github.com/mfojtik/26cab7d9437e6ec02221

**Comment by mfojtik** [comment] 2015-04-28 18:05
FYI, it seems like the problem is that this template use v1beta3 podTemplate with 'spec' which UI has problems to parse... cc @jwforres

**Comment by mfojtik** [comment] 2015-04-28 18:15
(negative, just tried to switch the template to v1beta1 podTemplate, same issue...)

**Comment by spadgett** [comment] 2015-05-04 12:53
@mfojtik Is this the error you're seeing?

```
Cannot create deploymentConfig zookeeper-1. deploymentConfig "zookeeper-1" is invalid: [template.controllerTemplate.selector: required value, template.controllerTemplate.template.spec.containers: required value]
```

Does this command work for you?

```
$ osc new-app zookeeper
```

I'm not able to test the command line because I'm seeing the error in #2016.

**Comment by spadgett** [comment] 2015-05-04 14:24
@mfojtik Comparing your template to the ruby hello world sample, I was able to edit your template and make it work.

https://gist.github.com/spadgett/63d298818825e61cb8e7

Let me know if you believe your JSON should work. The web console is simply passing the JSON for each item in the template to the server, so I don't think the problem is in that layer if there's a bug here.

**Comment by danmcp** [comment] 2015-05-18 20:11
@mfojtik ^^

**Comment by danmcp** [comment] 2015-05-28 19:14
Closing due to age without prejudice.

**Closed by danmcp** 2015-05-28 19:14 UTC
Labels: component/web, kind/bug, priority/P2
