### ISSUE TITLE
 [Feature:DeploymentConfig] deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16929] opened 2017-10-18 11:18 UTC
```
/tmp/openshift/build-rpm-release/tito/rpmbuild-originaSQW3g/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:142
Expected error:
    <*errors.errorString | 0xc4215922d0>: {
        s: "found multiple running deployments: [deployment-simple-1 deployment-simple-2]",
    }
    found multiple running deployments: [deployment-simple-1 deployment-simple-2]
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originaSQW3g/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:131
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16924/test_pull_request_origin_extended_conformance_gce/9899/

**Comment by bparees** [comment] 2017-10-18 15:00
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16925/test_pull_request_origin_extended_conformance_gce/9905/

**Comment by tnozicka** [comment] 2017-10-18 16:15
dupe of https://github.com/openshift/origin/issues/16870
but I'll keep it open for now so people can easily find it

**Comment by sdodson** [comment] 2017-10-20 19:13
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/5821/test_pull_request_openshift_ansible_extended_conformance_install/1461/

**Comment by tnozicka** [comment] 2017-10-31 13:47
It has been confirmed to be caused by https://github.com/openshift/origin/issues/17011 which is now fixed

**Closed by tnozicka** 2017-10-31 13:47 UTC
Labels: component/apps, kind/test-flake, priority/P1
