### ISSUE TITLE
Extended.idling and unidling unidling should work with TCP (when fully idled) [Conformance] [local]

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#15016] opened 2017-07-03 13:24 UTC
log:
```
/go/src/github.com/openshift/origin/test/extended/idling/idling.go:311
Expected error:
    <*util.ExitError | 0xc4215270b0>: {
        Cmd: "oc idle --config=/tmp/extended-test-cli-idling-pbzq2-k8rm5-user.kubeconfig --namespace=extended-test-cli-idling-pbzq2-k8rm5 --resource-names-file /tmp/openshift-extended-tests/idling-services-501111418",
        StdErr: "error: unable to mark service \"extended-test-cli-idling-pbzq2-k8rm5/idling-echo\" as idled: endpoints \"idling-echo\" is forbidden: endpoint address 10.128.0.155 is not allowedDeploymentConfig \"extended-test-cli-idling-pbzq2-k8rm5/idling-echo\" has been idled",
```

**Comment by sosiouxme** [comment] 2017-07-12 02:02
duplicate of https://github.com/openshift/origin/issues/10773 ?

**Comment by bparees** [comment] 2017-07-13 16:02
yes

**Closed by bparees** 2017-07-13 16:02 UTC
Labels: component/networking, kind/test-flake, priority/P1
