### ISSUE TITLE
Integration Test Flake: TestRegistryClientDockerHubV2

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8798] opened 2016-05-09 17:02 UTC
```
Running TestRegistryClientDockerHubV2...
failed  TestRegistryClientDockerHubV2
I0509 12:37:44.110282   20462 plugins.go:41] Registered credential provider "google-jwt-key"
I0509 12:37:44.110356   20462 plugins.go:41] Registered credential provider "google-dockercfg"
I0509 12:37:44.110366   20462 plugins.go:41] Registered credential provider "google-dockercfg-url"
I0509 12:37:44.110374   20462 plugins.go:41] Registered credential provider "google-container-registry"
I0509 12:37:44.110386   20462 plugins.go:62] Registered admission plugin "NamespaceLifecycle"
I0509 12:37:44.110815   20462 plugins.go:62] Registered admission plugin "SecurityContextDeny"
I0509 12:37:44.110836   20462 plugins.go:62] Registered admission plugin "ResourceQuota"
I0509 12:37:44.110846   20462 plugins.go:62] Registered admission plugin "PersistentVolumeLabel"
I0509 12:37:44.110857   20462 plugins.go:62] Registered admission plugin "NamespaceExists"
I0509 12:37:44.110865   20462 plugins.go:62] Registered admission plugin "NamespaceAutoProvision"
I0509 12:37:44.110875   20462 plugins.go:62] Registered admission plugin "LimitRanger"
I0509 12:37:44.111398   20462 plugins.go:62] Registered admission plugin "InitialResources"
I0509 12:37:44.111415   20462 plugins.go:62] Registered admission plugin "DenyEscalatingExec"
I0509 12:37:44.111423   20462 plugins.go:62] Registered admission plugin "DenyExecOnPrivileged"
I0509 12:37:44.111430   20462 plugins.go:62] Registered admission plugin "AlwaysDeny"
I0509 12:37:44.111438   20462 plugins.go:62] Registered admission plugin "AlwaysPullImages"
I0509 12:37:44.111447   20462 plugins.go:62] Registered admission plugin "AlwaysAdmit"
I0509 12:37:44.111463   20462 plugins.go:62] Registered admission plugin "SecurityContextConstraint"
I0509 12:37:44.111472   20462 plugins.go:62] Registered admission plugin "SCCExecRestrictions"
I0509 12:37:44.111490   20462 plugins.go:62] Registered admission plugin "PodNodeConstraints"
I0509 12:37:44.111506   20462 plugins.go:62] Registered admission plugin "RunOnceDuration"
I0509 12:37:44.111516   20462 plugins.go:62] Registered admission plugin "OriginResourceQuota"
I0509 12:37:44.111551   20462 plugins.go:62] Registered admission plugin "ClusterResourceOverride"
I0509 12:37:44.111565   20462 plugins.go:62] Registered admission plugin "ProjectRequestLimit"
I0509 12:37:44.111575   20462 plugins.go:62] Registered admission plugin "OriginPodNodeEnvironment"
I0509 12:37:44.111587   20462 plugins.go:62] Registered admission plugin "OriginNamespaceLifecycle"
I0509 12:37:44.111598   20462 plugins.go:62] Registered admission plugin "BuildByStrategy"
I0509 12:37:44.111608   20462 plugins.go:62] Registered admission plugin "BuildOverrides"
I0509 12:37:44.111621   20462 plugins.go:62] Registered admission plugin "BuildDefaults"
I0509 12:37:44.145000   20462 client.go:320] Found registry v2 API at https://registry-1.docker.io/v2/
I0509 12:37:54.204694   20462 client.go:567] unable to find tagged image at "https://registry-1.docker.io/v2/kubernetes/guestbook/manifests/latest", 404 map[Strict-Transport-Security:[max-age=31536000] Content-Type:[application/json; charset=utf-8] Docker-Distribution-Api-Version:[registry/2.0] Date:[Mon, 09 May 2016 16:37:54 GMT] Content-Length:[296]]: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"DriverName":"s3","Enclosed":{"Op":"Get","URL":"https://s3-external-1.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/repositories/kubernetes/guestbook/_manifests/tags/latest/current/link","Err":{}}}}]}
--- FAIL: TestRegistryClientDockerHubV2-2 (10.09s)
	dockerregistryclient_test.go:149: tag "latest" has not been set on repository "kubernetes/guestbook"
FAIL
```

Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/769/consoleFull#25640336156bf4006e4b05b79524e5923)

**Comment by smarterclayton** [comment] 2016-05-10 04:30
Dupe of #8444

**Closed by smarterclayton** 2016-05-10 04:30 UTC
Labels: kind/test-flake, priority/P2

**Comment by stevekuznetsov** [comment] 2016-05-10 16:35
We need a better way to optimize flake search results...

**Comment by smarterclayton** [comment] 2016-05-10 16:38
I think it was closed at the time you opened this - I reopened it.
