### ISSUE TITLE
test/end-to-end/core.sh:376: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12558] opened 2017-01-19 13:00 UTC
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10167/consoleFull:

```
FAILURE after 0.223s: test/end-to-end/core.sh:375: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
NAME                 READY     STATUS    RESTARTS   AGE
kubectl-with-token   1/1       Running   0          5s
```

**Comment by stevekuznetsov** [comment] 2017-01-19 13:03
@ncdc  this is from your changes https://github.com/openshift/origin/commit/b74c59fea91f93be9fafd36b148d84b73f248df3 in the rebase

**Comment by ncdc** [comment] 2017-01-19 14:26
@stevekuznetsov I'm confused - is this flakey now, or always failing? We have had numerous green test runs in the rebase PR and after.

**Comment by ncdc** [comment] 2017-01-19 14:27
Also, the output displayed above is what I'd expect to see from `oc get pod`, not `oc logs`.

**Comment by stevekuznetsov** [comment] 2017-01-19 22:15
@ncdc this is flakey

**Comment by soltysh** [comment] 2017-01-20 12:17
@stevekuznetsov no it is not 😝 I bet it's just your imagination ;)

**Comment by stevekuznetsov** [comment] 2017-01-20 12:33
Yes when I dream, my imagination comes up with P1 flakes :)

**Comment by ncdc** [comment] 2017-01-20 15:09
I don't think this is actually fixed yet

**Comment by soltysh** [comment] 2017-01-20 15:10
I was about to do the same 👍

**Comment by bparees** [comment] 2017-01-21 15:35
fresh logs if anyone needs them:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10366

**Comment by liggitt** [comment] 2017-01-21 15:38
I'm sure it's an issue capturing stderr from the container, not an issue of using in-cluster config or not, since the process in the pod would have no other way of reaching the API successfully

**Comment by bparees** [comment] 2017-01-21 23:47
this is rapidly becoming one of those cases where if we don't have a fix in the merge queue, we should have a PR to disable the test in the merge queue.

**Comment by soltysh** [comment] 2017-01-23 13:39
I'm inclined to un-comment the lines getting these contents from the file and not from `oc logs`. Looking at artifacts from [this run](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10416/s3/) `cli-with-token.log` has:
```
Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
I0123 12:38:48.132068       1 merged_client_builder.go:122] Using in-cluster configuration
I0123 12:38:48.132794       1 merged_client_builder.go:122] Using in-cluster configuration
I0123 12:38:48.165141       1 cached_discovery.go:123] failed to write cache to /root/.kube/172.30.0.1_443/servergroups.json due to mkdir /root/.kube: permission denied
I0123 12:38:48.165725       1 merged_client_builder.go:122] Using in-cluster configuration
I0123 12:38:48.165987       1 merged_client_builder.go:122] Using in-cluster configuration
I0123 12:38:48.166305       1 merged_client_builder.go:145] Using in-cluster namespace
In project test on server https://172.30.0.1:443

pod/cli-with-token runs openshift/origin:3a6d724

1 warning identified, use 'openshift cli status -v' to see details.
Waiting for pod test/cli-with-token to terminate, status is Running
```
Whereas the output of `container-cli-with-token-cli-with-token.log` (which is `docker logs` dump on cleanup) has:
```
In project test on server https://172.30.0.1:443
pod/cli-with-token runs openshift/origin:3a6d724
1 warning identified, use 'openshift cli status -v' to see details.
```

I'm checking successful runs to compare the two, though to be more convinced if that's the case.

**Comment by soltysh** [comment] 2017-01-23 13:48
There's one another difference between successful and failed one:
```
If you don't see a command prompt, try pressing enter.
```
from [here](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/attach.go#L225), @ncdc since you authored attach, iirc, does this looks familiar somehow?

**Comment by ncdc** [comment] 2017-01-23 13:50
I don't really see why that particular line would have any bearing on success or failure, unfortunately

**Comment by stevekuznetsov** [comment] 2017-01-23 13:51
> I'm inclined to un-comment the lines getting these contents from the file

Not sure I understand why

**Comment by liggitt** [comment] 2017-01-23 13:52
the logs we stream from the run are subject to flakes with the way docker attaches to get logs

the issue was reported in https://github.com/openshift/origin/issues/9309

the fix is tracked in https://github.com/openshift/origin/issues/11240

switching back to the file will just get us a different set of flakes

**Comment by soltysh** [comment] 2017-01-23 13:52
I'm actually thinking about checking both, from my investigation I've seen that line appearing in that log file more frequently than not.

**Comment by liggitt** [comment] 2017-01-23 13:52
best two out of three? :(

**Comment by ncdc** [comment] 2017-01-23 13:53
@liggitt the attach issues should only be affecting the end of the log file, though.

**Comment by soltysh** [comment] 2017-01-23 13:53
@liggitt one in ten that I checked.

**Comment by soltysh** [comment] 2017-02-01 10:00
This still looks like a problem, over the past week the stat looks like this: 

| date | count |
|:-------:|:-------:|
| Jan 25 | 15 |
| Jan 26 | 13 |
| Jan 27 | 11 |
| Jan 28 | 3 |
| Jan 29 | 2 |
| Jan 30 | 5 |
| Jan 31 | 10 |

I'll try to add some more logging into the places to maybe get some more information what's going on during this.

**Comment by soltysh** [comment] 2017-02-01 11:02
Interestingly only [core.sh:363](https://github.com/openshift/origin/blob/4bba8614afca53f72d0fd51de80a28d59dabae1f/test/end-to-end/core.sh#L363) fails consistently.

**Comment by pweil-** [comment] 2017-02-08 15:54
bump @soltysh

**Comment by soltysh** [comment] 2017-02-08 20:03
@pweil- I'm on it, chasing the flake in #12749

**Comment by soltysh** [comment] 2017-02-09 13:26
I confirmed my current suspicion, have a look at [this log](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/11132/consoleFull) search for `core.sh:363`, I've added logs starting from `status.go` file all the way down to `clientcache.go`, but the logs do not show anything. It looks like `glog.V(4)` is not appearing at all for this particular usecase, not sure why, yet.

**Comment by soltysh** [comment] 2017-02-14 13:35
Interestingly since the switch to the new jenkins process I can't seem to reproduce the error. See https://github.com/openshift/origin/pull/12749#issuecomment-276919653 for the current state, everything below the big line is run using the new infra. I'm inclined to revert the change and let it live for a while and see if it can be reproduced. If the current run is successful I'll open a PR reverting the parts that added to bypass the failure.

**Comment by stevekuznetsov** [comment] 2017-02-14 14:51
Docker upgrade from the `base_ami` using Vagrant to that using `oct` immediately comes to mind. I believe the `base_ami` from Vagrant is still at 1.12.2 whereas the new infra uses 1.12.5.

**Comment by soltysh** [comment] 2017-02-15 10:21
Specifically 1.12.2-rc2 vs 1.12.5. I've checked if @ncdc change landed there, but it doesn't look like it did. Only starting from docker 1.12.6. Anyway, since I can't find any failures since the new infra I'm going to revert the changes to the state before and keep my eyes open.

**Comment by soltysh** [comment] 2017-02-20 12:43
Now I have a [proof](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration_future/294/consoleFull) that the `glog` does not log sometimes:

```
11:49:17 Standard output from the command:
11:49:17 Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
11:49:17 Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
11:49:17 About to read the loglevel
11:49:17 Loglevel is &{loglevel  Set the level of log output (0-10) 4 0 true   false  map[]}
11:49:17 In project test on server https://172.30.0.1:443
11:49:17 pod/cli-with-token runs openshift/origin:bc8d655
11:49:17 1 warning identified, use 'openshift cli status -v' to see details.
11:49:17 
11:49:17 There was no error output from the command.
11:49:17 
```

Generally, I've added logs everywhere from `status.go` all the way down to `clientcache.go` and sometimes it wasn't even shown. I've additionally added regular `fmt.Printf` just before `glog` and the print statements are printed, showing the loglevel is set to 4 (as expected) but the next line after that print should be from glog and it's not there. So this looks like a problem with glog itself, not docker not showing output. @smarterclayton @deads2k any ideas? Should I start debugging glog and try to find out the root cause, or we should think about changing how this test is executed?

**Comment by deads2k** [comment] 2017-02-20 12:46
@soltysh do we ever defer the flush on whatever command you're running?

**Comment by deads2k** [comment] 2017-02-20 12:46
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/logs/logs.go#L55

**Comment by soltysh** [comment] 2017-02-20 13:02
It looks like we are: https://github.com/openshift/origin/blob/master/cmd/oc/oc.go#L25 and https://github.com/openshift/origin/blob/master/cmd/openshift/openshift.go#L25

**Comment by soltysh** [comment] 2017-02-22 16:05
This test is not a blocker bug for release 1.5, since currently we disabled erroring this test and most importantly it doesn't fail always, only sometimes. I'm still actively investigating what's causing that, glog is not printing the expected output, but only sometimes. Having said all that I'm lowering priority to P2 for that.

**Comment by soltysh** [comment] 2017-02-24 13:55
OK, this log:
```
07:00:58 About to read the loglevel
07:00:58 Loglevel is &{loglevel  Set the level of log output (0-10) 4 0 true   false  map[]}
07:00:58 In project test on server https://172.30.0.1:443
07:00:58 pod/cli-with-token runs openshift/origin:c8871ed
07:00:58 1 warning identified, use 'openshift cli status -v' to see details.
07:00:58 Flushing logs...
```
Clearly show the flush is happening, but the logs are still not there.

**Comment by soltysh** [comment] 2017-03-14 10:24
We're still seeing this problem, although Steve recently hidden those failures in https://github.com/openshift/origin/pull/13346.

**Comment by smarterclayton** [comment] 2017-03-14 19:08
This is still high priority to triage.

**Comment by ncdc** [comment] 2017-03-14 19:12
Is there any chance there's something (such as flush) that's running in a goroutine that isn't allowed to run to completion before the process exits?

**Comment by smarterclayton** [comment] 2017-03-14 20:01
The process exits when all goroutines terminate.

**Comment by ncdc** [comment] 2017-03-14 20:05
It exits when the main func exits, regardless of the status of other goroutines, unless something changed?

**Comment by smarterclayton** [comment] 2017-03-14 20:11
Yeah, I was thinking about tests.

**Comment by smarterclayton** [comment] 2017-03-14 20:12
Flush has to be a defer, for sure.

  defer logs.FlushLogs()

**Comment by ncdc** [comment] 2017-03-14 20:12
But this is running oc/kubectl in a pod and having it print to stdout/stderr. So it's possible (but I'm guessing highly unlikely) that something could be running in a goroutine that doesn't finish before main exits.

**Comment by soltysh** [comment] 2017-03-14 20:25
We do defer flush, see https://github.com/openshift/origin/blob/master/cmd/oc/oc.go#L25 and https://github.com/openshift/origin/blob/master/cmd/openshift/openshift.go#L25. I've double checked that, it's being invoked at the end as expected.

**Comment by ncdc** [comment] 2017-03-14 20:27
So we're flushing, it's getting called, and we're still missing the output sometimes?

**Comment by ncdc** [comment] 2017-03-14 20:28
Have we ever reproduced this when running oc outside of a docker container?

**Comment by soltysh** [comment] 2017-03-14 20:29
I was never ever able to reproduce this locally, and I've tried different combinations. While in jenkins the rate was ever other, every third. I haven't tried in docker, though. I'd have to give it a try.

**Comment by smarterclayton** [comment] 2017-03-14 20:34
Are you running RHEL Docker locally?

**Comment by soltysh** [comment] 2017-03-14 20:35
> Are you running RHEL Docker locally?

Nope.

**Comment by ncdc** [comment] 2017-03-14 20:35
When this fails in jenkins, do we ever see this when running oc outside of a pod/container, or only when inside?

**Comment by soltysh** [comment] 2017-03-14 20:37
That is running oc inside pod, we're testing injecting tokens.

**Comment by ncdc** [comment] 2017-03-14 20:37
I think we need to try to repro locally (in a pod) and if it does flake, switch the docker logging driver to jsonfile and see if it still flakes.

**Comment by stevekuznetsov** [comment] 2017-03-15 11:47
Definitely use `projectatomic/docker` as well -- the tests are on https://mirror.openshift.com/enterprise/rhel/dockertested/x86_64/os/Packages/docker-1.12.6-13.el7.x86_64.rpm

**Comment by soltysh** [comment] 2017-03-15 12:18
Heh, I've spin up AWS instance (mainly to address ^), I've reach 1000 iteration - still no luck :(

**Comment by stevekuznetsov** [comment] 2017-03-15 12:42
What's your iteration block?

**Comment by soltysh** [comment] 2017-03-16 13:59
I've cut `test/end-to-end/core.sh` so that only that test is run and it's pretty reproducable, about 25% chance of hitting the error. I'll go with Andy's proposal right now, switching to jsonfile for logging driver.

**Comment by soltysh** [comment] 2017-03-16 15:56
I'm using following [core.sh](https://github.com/soltysh/origin/blob/issue_12558_logs/test/end-to-end/core.sh). With that and switching to `json-file` log driver for docker I was not able to reproduce the problem (reached clean 55 runs). After talking with Andy a bit more on IRC, he suggested I should look for the possibility the journald is rate-limiting the output, I'll go back to `journald` driver and see what I'm getting around those failures.

**Comment by stevekuznetsov** [comment] 2017-03-16 16:50
@smarterclayton do we have a "fix" for this for customers when they say they are losing logs? If not, then we will need to change how the tests work to not rely on logs

**Comment by ncdc** [comment] 2017-03-16 16:52
They either have to change the journal's rate limiting settings or switch to json-file

**Comment by soltysh** [comment] 2017-03-16 16:59
Yup, so far it looks like it's rate-limitting fault, I've turned it off entirely setting `RateLimitBurst=0` per [this suggestion](https://www.freedesktop.org/software/systemd/man/journald.conf.html#RateLimitIntervalSec=) and I have clear 13 runs so far, I'll let it go for a while and will report back. @stevekuznetsov is little worried that if we turn this off on all AMIs, we'll get buried with the amount of logs, so I'm digging more if we can disable that only for docker.

**Comment by soltysh** [comment] 2017-03-16 19:58
Final confirmation, I've reached 97 successful runs without the rate limiter.

**Comment by ncdc** [comment] 2017-03-16 20:03
Thank goodness!

**Comment by soltysh** [comment] 2017-03-16 20:05
Now the only question is, do we want that limit turned off entirely in our AMIs or selectively. I'm guessing the latter, I need to figure out how much possible is that, but it looks like we'll have to set it up temporarily inside our tests, which is kinda hacky. Still digging into best possible solution.

**Comment by smarterclayton** [comment] 2017-03-16 22:53
I feel like the rate limiter is working against what Kubernetes is supposed
to provide.  The problem is journald, that it is a single point of
contention, and that we aren't isolating container workloads from each
other.  We shouldn't need journald rate limiting off to get perfect
fidelity logs from OpenShift/Kube.

**Comment by stevekuznetsov** [comment] 2017-03-17 11:59
Maybe the `journald` log driver could be set up differently? /cc @runcom

**Comment by smarterclayton** [comment] 2017-03-17 13:42
It's mostly that journald isn't designed to be antagonistic multi-tenant -
more like cooperative.  So this is more of a journald design problem.

On Mar 17, 2017, at 7:59 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Maybe the journald log driver could be set up differently? /cc @runcom
<https://github.com/runcom>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12558#issuecomment-287336370>,
or mute the thread

**Comment by soltysh** [comment] 2017-03-23 12:33
> So this is more of a journald design problem.

I don't think we'll be able to address this one 😉 Anyway, while scrolling through [our docs](https://docs.openshift.org/latest/install_config/aggregate_logging_sizing.html#install-config-aggregate-logging-sizing-guidelines-rate-limiting) I see we're suggesting cluster operators to tweak the journald default settings, in that case I'm proposing to apply that values to our test infra. @stevekuznetsov agreed?

**Comment by stevekuznetsov** [comment] 2017-03-23 12:43
We need to figure out what we are doing with the `test/end-to-end/core.sh` test. We're likely getting that setup for free on any tests running against a cluster started with `openshift-ansible`. So I agree in that we need to use the installer more and by doing so i hope we get this for free.

/cc @sdodson

**Comment by soltysh** [comment] 2017-03-23 12:49
The main problem here is that we're running [dockerized version](https://github.com/openshift/origin/blob/6a7ea04f27450f5cc18c9452d37c3b4dabfe3134/hack/test-end-to-end.sh#L10-L17) of end-to-end test by default, unless explicitly stated otherwise. This results in all messages coming from pods and master coming from single service - docker, which eventually gets rate limited.

**Comment by stevekuznetsov** [comment] 2017-03-23 12:53
We can use the `openshift-ansible` installer to make a containerized install to run this against if there is specific merit to doing it that way.

**Comment by smarterclayton** [comment] 2017-03-23 14:14
We have to fix this issue - why as a user should I not get my logs?  Or
certainly why shouldn't I get all logs?

**Comment by soltysh** [comment] 2017-03-23 14:15
I've filled in the issue to fix our tests for now, I'll work with @sdodson about addressing this problem in ansible as well.

**Comment by soltysh** [comment] 2017-04-07 08:15
This was reverted in #13665, b/c it was causing #13662. I'll re-open my fix and dig what's going on in there.

**Closed** 2017-06-07 17:08 UTC
Labels: component/cli, kind/post-rebase, kind/test-flake, priority/P0
