### ISSUE TITLE
idling and unidling unidling should work with TCP (when fully idled) [Conformance] [local] 37s

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15988] opened 2017-08-25 17:20 UTC
idling and unidling unidling should work with TCP (when fully idled) [Conformance] [local] 37s

```
/go/src/github.com/openshift/origin/test/extended/idling/idling.go:311
Expected error:
    <*util.ExitError | 0xc4214bb770>: {
        Cmd: "oc idle --config=/tmp/extended-test-cli-idling-b83q8-v2t0d-user.kubeconfig --namespace=extended-test-cli-idling-b83q8-v2t0d --resource-names-file /tmp/openshift-extended-tests/idling-services-058776213",
        StdErr: "error: unable to mark service \"extended-test-cli-idling-b83q8-v2t0d/idling-echo\" as idled: Operation cannot be fulfilled on endpoints \"idling-echo\": there is a meaningful conflict (firstResourceVersion: \"19452\", currentResourceVersion: \"19474\"):\n diff1={\"metadata\":{\"resourceVersion\":\"19474\"},\"subsets\":[{\"addresses\":[{\"ip\":\"10.128.1.11\",\"nodeName\":\"ip-172-18-0-115.ec2.internal\",\"targetRef\":{\"kind\":\"Pod\",\"name\":\"idling-echo-1-lw4j7\",\"namespace\":\"extended-test-cli-idling-b83q8-v2t0d\",\"resourceVersion\":\"19451\",\"uid\":\"701a9df8-89b4-11e7-9c78-0e46bf80eec8\"}},{\"ip\":\"10.128.1.12\",\"nodeName\":\"ip-172-18-0-115.ec2.internal\",\"targetRef\":{\"kind\":\"Pod\",\"name\":\"idling-echo-1-rch59\",\"namespace\":\"extended-test-cli-idling-b83q8-v2t0d\",\"resourceVersion\":\"19472\",\"uid\":\"701a85c1-89b4-11e7-9c78-0e46bf80eec8\"}}],\"ports\":[{\"name\":\"udp-echo\",\"port\":3090,\"protocol\":\"UDP\"},{\"name\":\"tcp-echo\",\"port\":8675,\"protocol\":\"TCP\"}]}]}\n, diff2={\"Subsets\":null,\"apiVersion\":\"v1\",\"creationTimestamp\":null,\"kind\":\"Endpoints\",\"labels\":null,\"metadata\":{\"annotations\":{\"idling.alpha.openshift.io/idled-at\":\"2017-08-25T16:43:13Z\",\"idling.alpha.openshift.io/unidle-targets\":\"[{\\\"kind\\\":\\\"DeploymentConfig\\\",\\\"name\\\":\\\"idling-echo\\\",\\\"replicas\\\":2}]\"},\"creationTimestamp\":\"2017-08-25T16:42:48Z\",\"labels\":{\"app\":\"idling-echo\"},\"name\":\"idling-echo\",\"namespace\":\"extended-test-cli-idling-b83q8-v2t0d\",\"resourceVersion\":\"19452\",\"selfLink\":\"/api/v1/namespaces/extended-test-cli-idling-b83q8-v2t0d/endpoints/idling-echo\",\"uid\":\"6d7bca41-89b4-11e7-9c78-0e46bf80eec8\"},\"name\":null,\"namespace\":null,\"resourceVersion\":null,\"selfLink\":null,\"subsets\":[{\"addresses\":[{\"ip\":\"10.128.1.11\",\"nodeName\":\"ip-172-18-0-115.ec2.internal\",\"targetRef\":{\"kind\":\"Pod\",\"name\":\"idling-echo-1-lw4j7\",\"namespace\":\"extended-test-cli-idling-b83q8-v2t0d\",\"resourceVersion\":\"19451\",\"uid\":\"701a9df8-89b4-11e7-9c78-0e46bf80eec8\"}}],\"ports\":[{\"name\":\"udp-echo\",\"port\":3090,\"protocol\":\"UDP\"},{\"name\":\"tcp-echo\",\"port\":8675,\"protocol\":\"TCP\"}]}],\"uid\":null}\nDeploymentConfig \"extended-test-cli-idling-b83q8-v2t0d/idling-echo\" has been idled",
        ExitError: {
            ProcessState: {
                pid: 42151,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 228246},
                    Stime: {Sec: 0, Usec: 34130},
                    Maxrss: 50292,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 14225,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 977,
                    Nivcsw: 21,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/go/src/github.com/openshift/origin/test/extended/idling/idling.go:287
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15985/test_pull_request_origin_extended_conformance_install_update/4846/

**Comment by sosiouxme** [comment] 2017-08-30 13:46
Is this a dupe of https://github.com/openshift/origin/issues/10773 ?

**Comment by tnozicka** [comment] 2017-08-31 18:15
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16061/test_pull_request_origin_extended_conformance_install_update/5201/

**Comment by DirectXMan12** [comment] 2017-09-06 18:28
> Is this a dupe of #10773 ?

No, I think it's a slightly different failure -- we've managed to race with something between `oc idle` fetching the object and submitting the patch.

**Comment by kargakis** [comment] 2017-09-11 10:22
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16277/test_pull_request_origin_extended_conformance_install_update/5834/

**Comment by bparees** [comment] 2017-10-12 14:57
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16818/test_pull_request_origin_extended_conformance_install_update/7760/

**Closed** 2018-04-23 23:29 UTC
Labels: component/kubernetes, kind/test-flake, lifecycle/rotten, priority/P1
