### ISSUE TITLE
OpenShift Origin: Wordpress Example: AH00558: apache2 Error

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#6075] opened 2015-11-25 08:25 UTC
I'm deploying a wordpress-app which is using a MySQL-database with OpenShift Origin. I'm using this example: https://github.com/openshift/origin/tree/master/examples/wordpress
```
openshift v1.0.8-1-g8f1868d
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2
```

I'm using NFS for my MySQL-database. It's deploying fine. So everything is running and OpenShift does not show errors. I'm creating a route to my frontend (wordpress). But when I want to visit the app I get a:
```
503 Service Unavailable
No server available to handle the request. 
```
When I try to curl to the OpenShift service of my frontend I even don't get an output. The docker logs of my wordpress-container are showing the following:
```
warning: both WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP found
  Connecting to WORDPRESS_DB_HOST (mysql)
  instead of the linked mysql container
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.1.1.32. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.1.1.32. Set the 'ServerName' directive globally to suppress this message
[Tue Nov 24 10:09:12.475692 2015] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.15 configured -- resuming normal operations
[Tue Nov 24 10:09:12.475721 2015] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```
I read about it and it's possible to fix the issue by changing:
```
ServerName localhost   
```
in either ```httpd.conf``` or ```apache2.conf``` in ```/etc/apache2``` 

But I don't want to change files in my container manually. I already did the installation/configuration of this wordpress-app a few times on Origin 1.6 and it was working fine. So it's not clear for me why it's not working at the moment. Is there someone with an explanation or solution?

**Comment by rhcarvalho** [comment] 2015-12-01 16:44
Hi, @lorenzvth7 could you describe how you configured the route/router?

The log output doesn't look like an error, just stating that apache2 is running.
I suspect the problem is just you're unable to reach the application through the route.

Have you tried accessing the service without the route, does it work?

**Comment by rhcarvalho** [comment] 2015-12-18 10:44
@lorenzvth7 is this still an issue for you? If not, could you please close it?

**Closed** 2015-12-18 12:03 UTC
Labels: area/examples, priority/P2
