### ISSUE TITLE
once project quota is applied, builds and deploys fail due to lack of resource limits defined on them

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2821] opened 2015-06-04 19:47 UTC
https://gist.github.com/thoraxe/e710285417247fc4e1a9

**Comment by thoraxe** [comment] 2015-06-04 19:52
```
  Thu, 04 Jun 2015 15:40:12 -0400       Thu, 04 Jun 2015 15:40:31 -0400 6       {deployer }                     failedCreate    Error creating deployer pod for sinatra/ruby-example-2: Pod "ruby-example-2-deploy" is forbidden: Limited to 512Mi memory, but pod has no specified memory limit
```

So the issue is actually with the deployer pod, not the application pod.

The deployer pod doesn't seem to be created with a memory limit, and this project has a quota, so openshift seems to be refusing to schedule the **deployer**.

**Comment by ironcladlou** [comment] 2015-06-04 19:56
This would also apply to build pods, deployer pods, and hook pods.

**Comment by thoraxe** [comment] 2015-06-04 19:57
The same thing happens when you try to start a build in a project with a quota:

```
[joe@ose3-master beta4]$ osc get build
NAME             TYPE      STATUS     POD
ruby-example-1   Source    Complete   ruby-example-1-build
ruby-example-2   Source    New        ruby-example-2-build
[joe@ose3-master beta4]$ osc describe build ruby-example-2
Name:                   ruby-example-2
Created:                35 seconds ago
Labels:                 buildconfig=ruby-example,generatedby=OpenShiftWebConsole,name=ruby-example
Build Config:           ruby-example
Status:                 New
Duration:               waiting for 35s
Build Pod:              ruby-example-2-build
Strategy:               Source
Image Reference:        DockerImage registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest
Incremental Build:      yes
Source Type:            Git
URL:                    https://github.com/openshift/simple-openshift-sinatra-sti
Ref:                    master
Output to:              ruby-example:latest
Output Spec:            <none>
Events:
  FirstSeen                             LastSeen                        Count   From                    SubobjectPath   Reason          Message
  Thu, 04 Jun 2015 15:54:49 -0400       Thu, 04 Jun 2015 15:54:49 -0400 1       {build-controller }                     failedCreate    Error creating: Pod "ruby-example-2-build" is forbidden: Limited to 512Mi memory, but pod has no specified memory limit

```

So the issue appears to be that none of our "infra" pods are being launched within the namespace with any limits.

**Comment by danmcp** [comment] 2015-06-05 14:12
@derekwaynecarr FYI

**Comment by danmcp** [comment] 2015-06-05 14:13
@bparees @csrwng FYI

**Comment by derekwaynecarr** [comment] 2015-06-05 14:32
@thoraxe - Is there a LimitRange in your project that specifies defaults?

see the example: https://github.com/GoogleCloudPlatform/kubernetes/pull/9264

I know I just tested this on upstream and defaults are getting picked up fine on any pod in the namespace that did not specify resource limits, will make sure there was no regression in OpenShift.

**Comment by derekwaynecarr** [comment] 2015-06-05 14:33
@thoraxe - it is possible to set resources on a deployer pod, see the template in this example that sets limits on the frontend deployer.

https://github.com/openshift/origin/tree/master/examples/project-quota

**Comment by derekwaynecarr** [comment] 2015-06-05 17:53
This is a good reason why deployed and build pods should go in a namespace that is not subject to quota longer term.

**Comment by bparees** [comment] 2015-11-17 23:10
pretty sure this is resolved since as @derekwaynecarr illustrated, you can set limits on deployment pods and build pods, as well as automatically picking up the project default limits.

@derekwaynecarr any reason not to close it?

**Comment by thoraxe** [comment] 2015-11-18 01:46
This is really old. I don't think it applies any longer. I believe it can be closed.

**Closed** 2015-11-18 04:08 UTC
Labels: component/build, component/deployments, kind/question, priority/P3
