### ISSUE TITLE
build successfully finished but push failed due to out-of-disk-space but build not marked as failed

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2206] opened 2015-05-12 21:05 UTC
A beta tester reported:

1) they did a build
2) the build was successful (eg the maven build did not error or fail)
3) the host holding the registry was out of disk space, and the push of the resulting image did not succeed
4) the status of the build was not shown as "failed"

**Comment by sdodson** [comment] 2015-05-12 21:38
Dupe of https://github.com/openshift/origin/issues/1818 ? I think the build shouldn't be marked as a success unless the image is pushed successfully.

**Comment by thoraxe** [comment] 2015-05-12 21:43
Probably?

**Comment by danmcp** [comment] 2015-05-14 19:02
Closing as dup.

**Closed by danmcp** 2015-05-14 19:02 UTC
Labels: component/build, kind/bug, priority/P2
