### ISSUE TITLE
Unprocessed template output in web UI pages

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2640] opened 2015-06-01 15:33 UTC
![selection_015](https://cloud.githubusercontent.com/assets/88819/7916425/02758512-0884-11e5-8091-9817508a37fe.png)

@liggitt FYI

**Comment by liggitt** [comment] 2015-06-01 15:51
```
Error: [$injector:unpr] Unknown provider: projectOverviewURLFilterProvider <- projectOverviewURLFilter
```

**Comment by rhcarvalho** [comment] 2015-06-01 17:36
For I don't know what reason I'm not observing that anymore... if nobody can reproduce it we can close this issue.

**Comment by liggitt** [comment] 2015-06-01 17:37
we can't reproduce... closing, can reopen if you see it again

**Closed by liggitt** 2015-06-01 17:37 UTC
Labels: component/web, kind/bug, priority/P2
