### ISSUE TITLE
rsync fails when writing to a mysql container

### ISSUE THREAD

**Issue by Tocacar** [openshift/origin#10374] opened 2016-08-12 10:30 UTC
I cannot rsync a database dump file (mysql) from my local machine (Mac Yosemite, rsync version 2.6.9  protocol version 29) to my running MySQL ephemeral pod.
##### Version

oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce

```
oc rsync /Users/myuser/file.sql podName:/home
```
##### Current Result

`error: path /Users/myuser/file.sql must point to a directory`
##### Expected Result

The file should successfully transfer to pod's MySQL container
##### Additional Information

I found #7787 and tried a modified version of the advice on there, which is the following command:

```
rsync -a --blocking-io --omit-dir-times --numeric-ids -v -e "oc rsh" /Users/myuser/file.sql podName:/home
```

...which gave me the following output

```
building file list ... done
file.sql
rsync: mkstemp "/home/.file.sql.iPcBjP" failed: Permission denied (13)

sent 7086960 bytes  received 42 bytes  4724668.00 bytes/sec
total size is 7086000  speedup is 1.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
```

In the Openshift Online web console (I'm running the Vagrant all-in-one installation), I went to the pod and in the Terminal tab and ran:

![screen shot 2016-08-12 at 11 27 48](https://cloud.githubusercontent.com/assets/878754/17619830/d90b8ff0-607f-11e6-894e-4bee6619f88c.png)

Then I ran whoami and see that my user is mysql.

Unfortunately, as this user I cannot create any new directories, so I'm wondering if this is the problem (the rsync command on the container is being run by mysql which doesn't have permission to write the file to the filesystem)?

**Comment by bparees** [comment] 2016-08-12 15:06
i think there are at least two problems.  one is that you can't copy the files to the location you're trying to copy them to, because you're a random user within the container (a random user that we map to the "mysql" username) which means you don't own /home.  copy the files to /tmp instead.

The other is that you're trying to copy a file when you have to copy a directory.  i'm not sure why that restriction is in place, perhaps @csrwng can enlighten us, but in the meantime, specify the dir containing the file, not the file itself, as the source for copying.

**Comment by csrwng** [comment] 2016-08-12 15:28
@bparees - it's been a while but I believe it had to do with parity between the rsync and tar copy methods.

**Comment by csrwng** [comment] 2017-01-26 20:51
This is working as designed. Closing and opening a feature request on Trello. (to rsync single files)

**Closed by csrwng** 2017-01-26 20:51 UTC
Labels: component/image, priority/P2
