### ISSUE TITLE
Can't switch back to "ConfigMap" resource in the UI (stays on whatever other resource I was on)

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8659] opened 2016-04-27 23:15 UTC
ConfigMap was the first in the list, switched to Templates, couldn't go back.

Saw this in the console window, not sure if it's at the same time though:

```
vendor.js:5310 TypeError: Cannot read property 'by' of undefined
    at Object.<anonymous> (scripts.js:3402)
    at k (vendor.js:1749)
    at Object.l.fireWith (vendor.js:1791)
    at Object.l.fire (vendor.js:1794)
    at l._listOpComplete (scripts.js:1068)
    at scripts.js:1050
    at vendor.js:4879
    at i (vendor.js:5556)
    at vendor.js:5564
    at l.$eval (vendor.js:5844)
```

**Comment by jwforres** [comment] 2016-04-28 12:25
yeah thats caused by the issue derek is fixing where config maps werent returning the empty array for items

**Comment by jwforres** [comment] 2016-04-28 12:26
@derekwaynecarr when do you think that fix will be in origin?

**Comment by jwforres** [comment] 2016-04-28 12:29
dup'ing this on the bug QE opened https://bugzilla.redhat.com/show_bug.cgi?id=1331324

**Closed by jwforres** 2016-04-28 12:29 UTC
Labels: component/web, priority/P1
