### ISSUE TITLE
oc status doesn't show me the context directory for build

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6332] opened 2015-12-16 01:07 UTC
`oc status` doesn't show me the context directory for build, only the repo URL.

**Comment by smarterclayton** [comment] 2015-12-16 18:23
I don't think I care?  Context dir is for describe usually.

**Comment by deads2k** [comment] 2015-12-16 19:56
> I don't think I care? Context dir is for describe usually.

One repo with two dockerbuilds, one for a base image, the other applying configuration on that base image, results in `oc status` looking crazy because it says that two buildconfigs are building the same thing.

**Comment by smarterclayton** [comment] 2015-12-16 20:21
That line is already so long.  I guess a subline heading isn't terrible,
but again I question how common context dir is.  It's probably only
relevant when you build the same repo twice with a different context  dir -
that happens like never.  Knowing that there *is* a context dir might be ok.

**Comment by deads2k** [comment] 2015-12-17 14:08
"Why does @deads2k keep using our product wrong, doesn't he know anything about it?"

**Comment by smarterclayton** [comment] 2015-12-17 17:43
David is an advanced user, he's expected to work a little harder because we
give him more flexibility :)

**Comment by smarterclayton** [comment] 2015-12-17 17:43
Designing for advanced users is hard.  Designing for novice users is
harder.  Designing for novice AND advanced users is the hardest problem
ever :)

**Comment by gabemontero** [comment] 2016-12-08 17:49
This is easy enough to add, but given the concern for the length of lines with `oc status` (a concern which has only increased based on my interpretation of commentary in other PRs) and the additional information which has been added since this was opened (I added additional information based on other enhancement requests back in June), I'm inclined to punt and close this out.

Opinions / dissent / agreement ?

**Comment by smarterclayton** [comment] 2016-12-08 18:57
I'd just recommend ensuring that oc describe build and oc describe build
config prominently place the context dir, and that the UI also prominently
places them.  Users are expected to us describe to get more details.

**Comment by gabemontero** [comment] 2016-12-08 21:40
Confirmed:  ctx dir clearly displayed for `oc describe build`, `oc describe bc`, and UI display of builds.

Closing out.

**Closed by gabemontero** 2016-12-08 21:40 UTC
Labels: area/usability, component/cli, priority/P3
