### ISSUE TITLE
templates should be able to encode to base64 (to generate secrets)

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#6693] opened 2016-01-18 10:34 UTC
I don't know, whether that can be done without adding something like filters to the template language. That would be unfortunate.

**Comment by mfojtik** [comment] 2016-01-18 12:33
@ibotty you mean to have special parameter that encodes the value to base64?

**Comment by liggitt** [comment] 2016-01-18 13:03
Dupe of https://github.com/openshift/origin/issues/3946

Fix could be something like https://github.com/openshift/origin/pull/6141

**Closed by liggitt** 2016-01-18 13:03 UTC

**Comment by ibotty** [comment] 2016-01-18 15:58
@mfojtik, I need a mean to encode a string as base64. How it's done is not important to me (Of course I do have an opinion). I would have thought, a filter like in ansible (jinja2) would be the most flexible and nice way. But @liggitt is right. it's a dupe of #3946. I am partial to the pull request #6141 (it is similar to ansible) and it would meet my requirement.
