### ISSUE TITLE
`oc cluster up --version` fails with invalid chars in patch number

### ISSUE THREAD

**Issue by goern** [openshift/origin#14540] opened 2017-06-09 10:19 UTC
With 1.5.1 I used `oc cluser up` to start different versions of OpenShift, with 3.6.0-alpha.2 this breaks.

##### Version
```
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. `oc cluster up --version=v3.5.5.15 --image="registry.access.redhat.com/openshift3/ose"`

##### Current Result
```
$ oc cluster up --version=v3.5.5.15 --image="registry.access.redhat.com/openshift3/ose" 
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.5.5.15 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.5.5.15 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
FAIL
   Error: could not update OpenShift configuration
   Caused By:
     Error: Invalid character(s) found in patch number "5.15"
```
##### Expected Result
an OpenShift cluster based on images tagged with 3.5.5.15 is started.

##### Additional Information
n/a

**Comment by pweil-** [comment] 2017-06-09 17:56
dupe of https://github.com/openshift/origin/issues/13815

**Closed by pweil-** 2017-06-09 17:56 UTC
