### ISSUE TITLE
Flake: bootstrap policy failure

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4295] opened 2015-08-20 18:54 UTC
```
failed  TestBootstrapPolicyOverwritePolicyCommand
masterAddr: "127.0.0.1:8443"
dnsAddr: "127.0.0.1:8053"
I0820 17:43:05.992281   23021 create_mastercerts.go:135] Creating all certs with: admin.CreateMasterCertsOptions{CertDir:"/tmp/openshift-integration/openshift.local.config/master", SignerName:"openshift-signer@1440092585", Hostnames:util.StringList{"127.0.0.1", "kubernetes", "kubernetes.default", "kubernetes.default.svc", "kubernetes.default.svc.cluster.local", "localhost", "openshift", "openshift.default", "openshift.default.svc", "openshift.default.svc.cluster.local"}, APIServerURL:"https://127.0.0.1:8443", PublicAPIServerURL:"https://127.0.0.1:8443", Overwrite:false, Output:(*os.File)(0xc208062010)}
I0820 17:43:05.992382   23021 create_signercert.go:96] Creating a signer cert with: admin.CreateSignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", Name:"openshift-signer@1440092585", Output:(*os.File)(0xc208062010), Overwrite:false}
I0820 17:43:06.130467   23021 create_signercert.go:108] Keeping existing CA cert at /tmp/openshift-integration/openshift.local.config/master/ca.crt and key at /tmp/openshift-integration/openshift.local.config/master/ca.key
I0820 17:43:06.130636   23021 create_servercert.go:106] Creating a server cert with: admin.CreateServerCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/master.server.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/master.server.key", Hostnames:util.StringList{"127.0.0.1", "kubernetes", "kubernetes.default", "kubernetes.default.svc", "kubernetes.default.svc.cluster.local", "localhost", "openshift", "openshift.default", "openshift.default.svc", "openshift.default.svc.cluster.local"}, Overwrite:false, Output:(*os.File)(0xc208062010)}
I0820 17:43:06.130713   23021 create_clientcert.go:53] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-master.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-master.key", User:"system:openshift-master", Groups:util.StringList{"system:masters"}, Overwrite:false, Output:(*os.File)(0xc208062010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:1, sema:0x0}, ca:(*crypto.CA)(nil)}
I0820 17:43:06.130829   23021 create_keypair.go:89] Creating a key pair with: admin.CreateKeyPairOptions{PublicKeyFile:"/tmp/openshift-integration/openshift.local.config/master/serviceaccounts.public.key", PrivateKeyFile:"/tmp/openshift-integration/openshift.local.config/master/serviceaccounts.private.key", Overwrite:false, Output:(*os.File)(0xc208062010)}
I0820 17:43:06.130857   23021 create_keypair.go:93] Keeping existing private key file /tmp/openshift-integration/openshift.local.config/master/serviceaccounts.private.key
I0820 17:43:06.130554   23021 create_clientcert.go:53] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/master.kubelet-client.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/master.kubelet-client.key", User:"system:master", Groups:util.StringList{}, Overwrite:false, Output:(*os.File)(0xc208062010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:5, sema:0x0}, ca:(*crypto.CA)(nil)}
I0820 17:43:06.130556   23021 create_clientcert.go:53] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/master.etcd-client.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/master.etcd-client.key", User:"system:master", Groups:util.StringList{}, Overwrite:false, Output:(*os.File)(0xc208062010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:9, sema:0x0}, ca:(*crypto.CA)(nil)}
I0820 17:43:06.501439   23021 create_clientcert.go:71] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/master.kubelet-client.crt and key at /tmp/openshift-integration/openshift.local.config/master/master.kubelet-client.key
I0820 17:43:06.532231   23021 create_clientcert.go:71] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/master.etcd-client.crt and key at /tmp/openshift-integration/openshift.local.config/master/master.etcd-client.key
I0820 17:43:06.555500   23021 crypto.go:210] Found existing server certificate in /tmp/openshift-integration/openshift.local.config/master/master.server.crt
I0820 17:43:06.555526   23021 create_servercert.go:123] Keeping existing server certificate at /tmp/openshift-integration/openshift.local.config/master/master.server.crt, key at /tmp/openshift-integration/openshift.local.config/master/master.server.key
I0820 17:43:06.555536   23021 create_servercert.go:106] Creating a server cert with: admin.CreateServerCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/master.server.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/master.server.key", Hostnames:util.StringList{"127.0.0.1", "kubernetes", "kubernetes.default", "kubernetes.default.svc", "kubernetes.default.svc.cluster.local", "localhost", "openshift", "openshift.default", "openshift.default.svc", "openshift.default.svc.cluster.local"}, Overwrite:false, Output:(*os.File)(0xc208062010)}
I0820 17:43:06.576532   23021 create_clientcert.go:71] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/openshift-master.crt and key at /tmp/openshift-integration/openshift.local.config/master/openshift-master.key
I0820 17:43:06.576579   23021 create_kubeconfig.go:132] creating a .kubeconfig with: admin.CreateKubeConfigOptions{APIServerURL:"https://127.0.0.1:8443", PublicAPIServerURL:"https://127.0.0.1:8443", APIServerCAFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-master.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-master.key", ContextNamespace:"default", KubeConfigFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-master.kubeconfig", Output:(*os.File)(0xc208062010)}
I0820 17:43:06.697189   23021 crypto.go:210] Found existing server certificate in /tmp/openshift-integration/openshift.local.config/master/master.server.crt
I0820 17:43:06.697233   23021 create_servercert.go:123] Keeping existing server certificate at /tmp/openshift-integration/openshift.local.config/master/master.server.crt, key at /tmp/openshift-integration/openshift.local.config/master/master.server.key
I0820 17:43:06.697249   23021 create_servercert.go:106] Creating a server cert with: admin.CreateServerCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/etcd.server.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/etcd.server.key", Hostnames:util.StringList{"127.0.0.1", "kubernetes", "kubernetes.default", "kubernetes.default.svc", "kubernetes.default.svc.cluster.local", "localhost", "openshift", "openshift.default", "openshift.default.svc", "openshift.default.svc.cluster.local"}, Overwrite:false, Output:(*os.File)(0xc208062010)}
I0820 17:43:06.716687   23021 create_kubeconfig.go:206] Generating 'system:openshift-master/127-0-0-1:8443' API client config as /tmp/openshift-integration/openshift.local.config/master/openshift-master.kubeconfig
I0820 17:43:06.718322   23021 create_clientcert.go:53] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/admin.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/admin.key", User:"system:admin", Groups:util.StringList{"system:cluster-admins"}, Overwrite:false, Output:(*os.File)(0xc208062010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:0, sema:0x0}, ca:(*crypto.CA)(0xc20837a840)}
I0820 17:43:06.835504   23021 crypto.go:210] Found existing server certificate in /tmp/openshift-integration/openshift.local.config/master/etcd.server.crt
I0820 17:43:06.835548   23021 create_servercert.go:123] Keeping existing server certificate at /tmp/openshift-integration/openshift.local.config/master/etcd.server.crt, key at /tmp/openshift-integration/openshift.local.config/master/etcd.server.key
I0820 17:43:06.855778   23021 create_clientcert.go:71] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/admin.crt and key at /tmp/openshift-integration/openshift.local.config/master/admin.key
I0820 17:43:06.855813   23021 create_kubeconfig.go:132] creating a .kubeconfig with: admin.CreateKubeConfigOptions{APIServerURL:"https://127.0.0.1:8443", PublicAPIServerURL:"https://127.0.0.1:8443", APIServerCAFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", CertFile:"/tmp/openshift-integration/openshift.local.config/master/admin.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/admin.key", ContextNamespace:"default", KubeConfigFile:"/tmp/openshift-integration/openshift.local.config/master/admin.kubeconfig", Output:(*os.File)(0xc208062010)}
I0820 17:43:06.989446   23021 create_kubeconfig.go:206] Generating 'system:admin/127-0-0-1:8443' API client config as /tmp/openshift-integration/openshift.local.config/master/admin.kubeconfig
I0820 17:43:06.990629   23021 create_clientcert.go:53] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-router.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-router.key", User:"system:openshift-router", Groups:util.StringList{"system:routers"}, Overwrite:false, Output:(*os.File)(0xc208062010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:0, sema:0x0}, ca:(*crypto.CA)(0xc20837a840)}
I0820 17:43:07.121813   23021 create_clientcert.go:71] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/openshift-router.crt and key at /tmp/openshift-integration/openshift.local.config/master/openshift-router.key
I0820 17:43:07.121855   23021 create_kubeconfig.go:132] creating a .kubeconfig with: admin.CreateKubeConfigOptions{APIServerURL:"https://127.0.0.1:8443", PublicAPIServerURL:"https://127.0.0.1:8443", APIServerCAFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-router.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-router.key", ContextNamespace:"default", KubeConfigFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-router.kubeconfig", Output:(*os.File)(0xc208062010)}
I0820 17:43:07.252612   23021 create_kubeconfig.go:206] Generating 'system:openshift-router/127-0-0-1:8443' API client config as /tmp/openshift-integration/openshift.local.config/master/openshift-router.kubeconfig
I0820 17:43:07.253772   23021 create_clientcert.go:53] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080cf300), CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.key", User:"system:openshift-registry", Groups:util.StringList{"system:registries"}, Overwrite:false, Output:(*os.File)(0xc208062010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:0, sema:0x0}, ca:(*crypto.CA)(0xc20837a840)}
I0820 17:43:07.385185   23021 create_clientcert.go:71] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt and key at /tmp/openshift-integration/openshift.local.config/master/openshift-registry.key
I0820 17:43:07.385229   23021 create_kubeconfig.go:132] creating a .kubeconfig with: admin.CreateKubeConfigOptions{APIServerURL:"https://127.0.0.1:8443", PublicAPIServerURL:"https://127.0.0.1:8443", APIServerCAFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.key", ContextNamespace:"default", KubeConfigFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.kubeconfig", Output:(*os.File)(0xc208062010)}
I0820 17:43:07.516690   23021 create_kubeconfig.go:206] Generating 'system:openshift-registry/127-0-0-1:8443' API client config as /tmp/openshift-integration/openshift.local.config/master/openshift-registry.kubeconfig
I0820 17:43:07.800314   23021 plugins.go:70] No cloud provider specified.
I0820 17:43:07.800464   23021 start_master.go:375] Starting master on 127.0.0.1:8443 (unknown)
I0820 17:43:07.800484   23021 start_master.go:376] Public master address is https://127.0.0.1:8443
I0820 17:43:07.800509   23021 start_master.go:380] Using images from "openshift/origin-<component>:"
E0820 17:43:07.800712   23021 reflector.go:180] pkg/admission/namespace/exists/admission.go:101: Failed to list *api.Namespace: Get https://127.0.0.1:8443/api/v1/namespaces: dial tcp 127.0.0.1:8443: connection refused
E0820 17:43:07.800868   23021 reflector.go:180] pkg/admission/namespace/lifecycle/admission.go:107: Failed to list *api.Namespace: Get https://127.0.0.1:8443/api/v1/namespaces: dial tcp 127.0.0.1:8443: connection refused
E0820 17:43:07.801038   23021 reflector.go:180] pkg/admission/serviceaccount/admission.go:107: Failed to list *api.Secret: Get https://127.0.0.1:8443/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 127.0.0.1:8443: connection refused
E0820 17:43:07.801091   23021 reflector.go:180] pkg/admission/serviceaccount/admission.go:93: Failed to list *api.ServiceAccount: Get https://127.0.0.1:8443/api/v1/serviceaccounts: dial tcp 127.0.0.1:8443: connection refused
E0820 17:43:07.801348   23021 reflector.go:180] pkg/admission/limitranger/admission.go:102: Failed to list *api.LimitRange: Get https://127.0.0.1:8443/api/v1/limitranges: dial tcp 127.0.0.1:8443: connection refused
E0820 17:43:07.801395   23021 reflector.go:180] pkg/security/admission/admission.go:59: Failed to list *api.SecurityContextConstraints: Get https://127.0.0.1:8443/api/v1/securitycontextconstraints: dial tcp 127.0.0.1:8443: connection refused
E0820 17:43:07.801230   23021 reflector.go:180] pkg/admission/resourcequota/admission.go:59: Failed to list *api.ResourceQuota: Get https://127.0.0.1:8443/api/v1/resourcequotas: dial tcp 127.0.0.1:8443: connection refused
I0820 17:43:07.801545   23021 run_components.go:178] Using default project node label selector: 
I0820 17:43:07.801780   23021 master.go:270] Setting master service IP to "172.30.0.1" (read-write).
E0820 17:43:07.804270   23021 reflector.go:180] pkg/project/cache/cache.go:102: Failed to list *api.Namespace: Get https://127.0.0.1:8443/api/v1/namespaces: dial tcp 127.0.0.1:8443: connection refused
W0820 17:43:07.842069   23021 controller.go:212] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{127.0.0.1 <nil>}] [{ 8443 TCP}]}]}
I0820 17:43:07.980992   23021 plugin.go:28] Route plugin initialized with suffix=router.default.svc.cluster.local
I0820 17:43:08.041543   23021 master.go:228] Started Kubernetes API at 127.0.0.1:8443/api/v1beta3 (deprecated)
I0820 17:43:08.041586   23021 master.go:228] Started Kubernetes API at 127.0.0.1:8443/api/v1
I0820 17:43:08.041597   23021 master.go:228] Started Origin API at 127.0.0.1:8443/osapi/v1beta3
I0820 17:43:08.041607   23021 master.go:228] Started Origin API at 127.0.0.1:8443/oapi/v1
I0820 17:43:08.041617   23021 master.go:228] Started OAuth2 API at 127.0.0.1:8443/oauth
I0820 17:43:08.041627   23021 master.go:228] Started Login endpoint at 127.0.0.1:8443/login
I0820 17:43:08.041636   23021 master.go:228] Started Web Console 127.0.0.1:8443/console/
I0820 17:43:08.041646   23021 master.go:228] Started Swagger Schema API at 127.0.0.1:8443/swaggerapi/
I0820 17:43:08.041652   23021 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp4", Addr:(*net.TCPAddr)(0xc208ccf350), Err:0x6f}, trying again: "127.0.0.1:8443"
I0820 17:43:08.141946   23021 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp4", Addr:(*net.TCPAddr)(0xc208eda030), Err:0x6f}, trying again: "127.0.0.1:8443"
I0820 17:43:08.256230   23021 ensure.go:85] No cluster policy found.  Creating bootstrap policy based on: /tmp/openshift-integration/openshift.local.config/master/policy.json
I0820 17:43:08.256369   23021 decoder.go:141] decoding stream as JSON
I0820 17:43:08.580710   23021 ensure.go:162] No security context constraints detected, adding defaults
E0820 17:43:08.686960   23021 ensure.go:147] Error recording adding service account roles to default namespace: namespaces "default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
I0820 17:43:08.736174   23021 ensure.go:74] Added [system:serviceaccount:openshift-infra:build-controller] users to the system:build-controller cluster role: <nil>
I0820 17:43:08.783628   23021 ensure.go:74] Added [system:serviceaccount:openshift-infra:deployment-controller] users to the system:deployment-controller cluster role: <nil>
I0820 17:43:09.027957   23021 ensure.go:74] Added [system:serviceaccount:openshift-infra:replication-controller] users to the system:replication-controller cluster role: <nil>
W0820 17:43:09.031376   23021 run_components.go:158] Binding DNS on port 8053 instead of 53 (you may need to run as root and update your config), using 127.0.0.1:8053 which will not resolve from all locations
I0820 17:43:09.031684   23021 net.go:102] Got error &net.OpError{Op:"dial", Net:"tcp", Addr:(*net.TCPAddr)(0xc2098df8f0), Err:0x6f}, trying again: "127.0.0.1:8053"
2015/08/20 17:43:09 skydns: ready for queries on cluster.local. for tcp4://127.0.0.1:8053 [rcache 0]
2015/08/20 17:43:09 skydns: ready for queries on cluster.local. for udp4://127.0.0.1:8053 [rcache 0]
I0820 17:43:09.132006   23021 run_components.go:173] DNS listening at 127.0.0.1:8053
I0820 17:43:09.143565   23021 start_master.go:506] Controllers starting (*)
I0820 17:43:09.143621   23021 run_components.go:73] Started Service Account Manager
E0820 17:43:09.172188   23021 serviceaccounts_controller.go:215] serviceaccounts "deployer" already exists
I0820 17:43:09.440498   23021 run_components.go:104] Started Service Account Token Manager
I0820 17:43:09.443580   23021 run_components.go:123] Started Service Account Pull Secret Controllers
E0820 17:43:09.444127   23021 reflector.go:180] /usr/local/go/src/runtime/asm_amd64.s:2232: Failed to list *api.Secret: [role "system:oauth-token-deleter" not found, role "system:webhook" not found, role "basic-user" not found, role "self-provisioner" not found, role "system:master" not found, role "cluster-status" not found]
E0820 17:43:09.444986   23021 reflector.go:180] /usr/local/go/src/runtime/asm_amd64.s:2232: Failed to list *api.Secret: [role "basic-user" not found, role "self-provisioner" not found, role "system:master" not found, role "cluster-status" not found, role "system:oauth-token-deleter" not found, role "system:webhook" not found]
E0820 17:43:09.445091   23021 reflector.go:180] /usr/local/go/src/runtime/asm_amd64.s:2232: Failed to list *api.Service: [role "system:webhook" not found, role "system:oauth-token-deleter" not found, role "system:master" not found, role "basic-user" not found, role "self-provisioner" not found, role "cluster-status" not found]
F0820 17:43:09.445097   23021 run_components.go:377] Unable to initialize namespaces: unable to refresh the security allocation UID blocks: [role "system:master" not found, role "basic-user" not found, role "self-provisioner" not found, role "cluster-status" not found, role "system:oauth-token-deleter" not found, role "system:webhook" not found]
E0820 17:43:09.443391   23021 reflector.go:209] /usr/local/go/src/runtime/asm_amd64.s:2232: Failed to watch *api.ServiceAccount: [role "cluster-status" not found, role "system:oauth-token-deleter" not found, role "system:webhook" not found, role "self-provisioner" not found, role "system:master" not found, role "basic-user" not found]
E0820 17:43:09.443510   23021 tokens_controller.go:151] [role "system:oauth-token-deleter" not found, role "system:webhook" not found, role "self-provisioner" not found, role "system:master" not found, role "basic-user" not found, role "cluster-status" not found]
E0820 17:43:09.442228   23021 reflector.go:209] /usr/local/go/src/runtime/asm_amd64.s:2232: Failed to watch *api.Secret: [role "cluster-status" not found, role "system:oauth-token-deleter" not found, role "system:webhook" not found, role "basic-user" not found, role "self-provisioner" not found, role "system:master" not found]
E0820 17:43:09.450786   23021 reflector.go:180] /usr/local/go/src/runtime/asm_amd64.s:2232: Failed to list *api.ServiceAccount: [role "system:oauth-token-deleter" not found, role "system:webhook" not found, role "basic-user" not found, role "self-provisioner" not found, role "system:master" not found, role "cluster-status" not found]
```

@deads2k

**Comment by liggitt** [comment] 2015-08-20 18:57
dupe of #4278

**Closed by liggitt** 2015-08-20 18:57 UTC
Labels: area/tests, kind/test-flake
