### ISSUE TITLE
service account "router" is not allowed to access the host network on nodes

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9129] opened 2016-06-02 08:18 UTC
```
FAILURE after 0.589s: test/cmd/router.sh:29: executing 'oadm router --dry-run -o yaml' expecting failure and text 'name: router': the output content test failed
Standard output from the command:
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: router
<- snip ->
Standard error from the command:
error: router could not be created; service account "router" is not allowed to access the host network on nodes, grant access with oadm policy add-scc-to-user hostnetwork -z router
=== END TEST CASE ===
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1392/console

**Comment by danmcp** [comment] 2016-06-03 10:10
@knobunc

**Comment by stevekuznetsov** [comment] 2016-07-07 13:36
dupe of #9371

**Closed by stevekuznetsov** 2016-07-07 13:36 UTC
Labels: area/tests, kind/test-flake, priority/P2
