### ISSUE TITLE
Test flake: cover: internal error: block XXX overlaps block XXX

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11142] opened 2016-09-28 18:32 UTC
```
# cover github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient
cover: internal error: block 268 overlaps block 270
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:#27803,#27927 /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:#27848,#27867
```

Test:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/6487

**Comment by csrwng** [comment] 2016-09-28 18:33
@stevekuznetsov fyi

**Comment by stevekuznetsov** [comment] 2016-09-28 19:12
dupe of https://github.com/golang/go/issues/16540

**Closed by stevekuznetsov** 2016-09-28 19:12 UTC
Labels: kind/test-flake, priority/P2
