### ISSUE TITLE
working deployment listed as failed in oc status

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4955] opened 2015-10-05 20:02 UTC
@ironcladlou I suspect this is due to pruning of completed pods.  The deployment is actually quite happy, but the deployer pod is no longer present

```
In project openldap on server https://10.13.137.230:8443

service/openldap-server - 172.30.119.140:389
  dc/openldap-server deploys istag/openldap-testenv:latest <-
    docker build of git://github.com/openshift/origin.git#master through bc/openldap 
    #1 deployment failed 14 minutes ago: The deployment failed as the deployer pod no longer exists - 1 pod

To see more, use 'oc describe <resource>/<name>'.
You can use 'oc get all' to see a list of other objects.
```

```yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2015-10-05T19:43:33Z
  name: openldap-server
  namespace: openldap
  resourceVersion: "314"
  selfLink: /oapi/v1/namespaces/openldap/deploymentconfigs/openldap-server
  uid: 5cadf284-6b99-11e5-b96d-28d2447dc82b
spec:
  replicas: 1
  selector:
    name: openldap-server
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: openldap-server
    spec:
      containers:
      - image: 172.30.19.162:5000/openldap/openldap-testenv@sha256:d5279388d60511c11804460c19e6693c1af3eb3f9d4cc26ac37e97ccb069c975
        imagePullPolicy: IfNotPresent
        name: openldap-server
        ports:
        - containerPort: 389
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - openldap-server
      from:
        kind: ImageStreamTag
        name: openldap-testenv:latest
      lastTriggeredImage: 172.30.19.162:5000/openldap/openldap-testenv@sha256:d5279388d60511c11804460c19e6693c1af3eb3f9d4cc26ac37e97ccb069c975
    type: ImageChange
  - type: ConfigChange
status:
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: 172.30.19.162:5000/openldap/openldap-testenv:latest
      type: ImageChange
  latestVersion: 1

```

**Comment by ironcladlou** [comment] 2015-10-05 20:16
Dupe of #4942

**Closed** 2015-10-06 12:59 UTC
