### ISSUE TITLE
Extended cl.go tests fails to define all template parameters

### ISSUE THREAD

**Issue by jmencak** [openshift/origin#17068] opened 2017-10-27 13:26 UTC
##### Version
$ git describe
v3.7.0-alpha.1-494-g7bb08c04da

##### Steps To Reproduce
1. extended.test --ginkgo.focus="Load cluster" --viper-config=config/stress-mb

##### Current Result
Only the first template parameter 'RUN: mb' is overrriden during the extended test run:
Oct 27 14:56:14.777: INFO: Running 'oc new-app --config=/tmp/extended-test-cl-jgpj6-hg8kn-user.kubeconfig --namespace=cll0 centos-stress-template -p RUN=mb'

##### Expected Result
All template parameters defined.

##### Config files

- stress-mb.yaml

      # e2e specific vars
      provider: local
      # delete namespace after exec
      deletenamespace: true
      # Cluster loader specific part
      ClusterLoader:
        projects:
          - num: 1
            basename: cll
            tuning: default
            routes: wlg-targets
            templates:
              - num: 1
                file: quickstarts/stress/stress-pod.json
                parameters:
                  RUN: mb
                  PLACEMENT: test
                  MB_DELAY: 100
                  MB_TARGETS: ^cakephp-
                  MB_CONNS_PER_TARGET: 1
                  MB_KA_REQUESTS: 100
                  MB_TLS_SESSION_REUSE: y
                  MB_RAMP_UP: 60
                  URL_PATH: /
        tuningsets: 
          - name: default
            pods:
              stepping:
                stepsize: 5
                pause: 3      # seconds
                timeout: 300  # seconds
              ratelimit:
                delay: 100    # milliseconds
            templates:
              stepping: 
                stepsize: 2
                pause: 2      # seconds
                timeout: 120  # seconds
              ratelimit: 
                delay: 200    # milliseconds

- https://raw.githubusercontent.com/openshift/svt/master/openshift_scalability/content/quickstarts/stress/stress-pod.json

@sjug /cc @jeremyeder

**Comment by sjug** [comment] 2017-10-27 14:05
The problem is the yaml is getting unmashalled to a struct which doesn't match the parameters [snip](https://github.com/openshift/origin/blob/master/test/extended/cluster/context.go#L40-L46).

**Comment by sjug** [comment] 2017-10-27 16:07
Fixed by https://github.com/openshift/origin/pull/17072

**Closed** 2017-12-21 14:34 UTC
Labels: area/tests, component/internal-tools, priority/P2, size/S
