### ISSUE TITLE
E2E Flakes Waiting on RC

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8078] opened 2016-03-17 01:30 UTC
This is a good candidate for JSONPath (#8004):
```
FAILURE after 59.600s: hack/../hack/../test/end-to-end/core.sh:239: executing 'oc get rc/test-deployment-config-1 -o yaml' expecting any result and text 'Complete'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.name: test-deployment-config-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: test-deployment-config
    openshift.io/deployment.phase: Pending
    openshift.io/deployment.replicas: "0"
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"test-deployment-config","namespace":"test","selfLink":"/oapi/v1/namespaces/test/deploymentconfigs/test-deployment-config","uid":"940d2ddd-ebc5-11e5-9a94-0e5bc7d2ab21","resourceVersion":"1057","creationTimestamp":"2016-03-16T22:22:32Z"},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":10,"post":{"failurePolicy":"Ignore","tagImages":[{"containerName":"ruby-helloworld","to":{"kind":"ImageStreamTag","name":"origin-ruby-sample:deployed"}}]}},"resources":{}},"triggers":[{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"name":"test-deployment"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"test-deployment"}},"spec":{"volumes":[{"name":"vol1","emptyDir":{}}],"containers":[{"name":"ruby-helloworld","image":"openshift/origin-pod","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"100m","memory":"3Gi"}},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}}},"status":{"latestVersion":1,"details":{"causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: 2016-03-16T22:22:33Z
  generation: 1
  labels:
    openshift.io/deployment-config.name: test-deployment-config
  name: test-deployment-config-1
  namespace: test
  resourceVersion: "1066"
  selfLink: /api/v1/namespaces/test/replicationcontrollers/test-deployment-config-1
  uid: 9414b615-ebc5-11e5-9a94-0e5bc7d2ab21
spec:
  replicas: 0
  selector:
    deployment: test-deployment-config-1
    deploymentconfig: test-deployment-config
    name: test-deployment
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: test-deployment-config
        openshift.io/deployment.name: test-deployment-config-1
      creationTimestamp: null
      labels:
        deployment: test-deployment-config-1
        deploymentconfig: test-deployment-config
        name: test-deployment
    spec:
      containers:
      - image: openshift/origin-pod
        imagePullPolicy: IfNotPresent
        name: ruby-helloworld
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: vol1
status:
  observedGeneration: 1
  replicas: 0
... repeated 7 times
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.name: test-deployment-config-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: test-deployment-config
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"test-deployment-config","namespace":"test","selfLink":"/oapi/v1/namespaces/test/deploymentconfigs/test-deployment-config","uid":"940d2ddd-ebc5-11e5-9a94-0e5bc7d2ab21","resourceVersion":"1057","creationTimestamp":"2016-03-16T22:22:32Z"},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":10,"post":{"failurePolicy":"Ignore","tagImages":[{"containerName":"ruby-helloworld","to":{"kind":"ImageStreamTag","name":"origin-ruby-sample:deployed"}}]}},"resources":{}},"triggers":[{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"name":"test-deployment"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"test-deployment"}},"spec":{"volumes":[{"name":"vol1","emptyDir":{}}],"containers":[{"name":"ruby-helloworld","image":"openshift/origin-pod","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"100m","memory":"3Gi"}},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}}},"status":{"latestVersion":1,"details":{"causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: 2016-03-16T22:22:33Z
  generation: 1
  labels:
    openshift.io/deployment-config.name: test-deployment-config
  name: test-deployment-config-1
  namespace: test
  resourceVersion: "1086"
  selfLink: /api/v1/namespaces/test/replicationcontrollers/test-deployment-config-1
  uid: 9414b615-ebc5-11e5-9a94-0e5bc7d2ab21
spec:
  replicas: 0
  selector:
    deployment: test-deployment-config-1
    deploymentconfig: test-deployment-config
    name: test-deployment
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: test-deployment-config
        openshift.io/deployment.name: test-deployment-config-1
      creationTimestamp: null
      labels:
        deployment: test-deployment-config-1
        deploymentconfig: test-deployment-config
        name: test-deployment
    spec:
      containers:
      - image: openshift/origin-pod
        imagePullPolicy: IfNotPresent
        name: ruby-helloworld
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: vol1
status:
  observedGeneration: 1
  replicas: 0
... repeated 178 times
There was no error output from the command.
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5343/consoleFull#-65141768856cf27b1e4b0ecce0b4ec162

**Comment by liggitt** [comment] 2016-03-17 06:53
@ironcladlou seeing this a lot. what field in the RC is expected to contain "Complete" after the DC scale?

**Comment by kargakis** [comment] 2016-03-17 09:23
dupe of https://github.com/openshift/origin/issues/8040

**Comment by stevekuznetsov** [comment] 2016-03-17 12:19
@gabemontero do you have a failure management filter set up to point to #8040?

**Comment by gabemontero** [comment] 2016-03-17 15:02
@stevekuznetsov never heard of failure management filters before you mentioned it.  Just learned I should log onto our Jenkins and take a look.

**Comment by stevekuznetsov** [comment] 2016-03-17 15:10
@gabemontero since I've got one set up and pointing to this issue maybe you can close yours as a dupe?

**Comment by gabemontero** [comment] 2016-03-17 15:18
@stevekuznetsov will do.

**Comment by smarterclayton** [comment] 2016-04-22 18:15
This is fixed, it was a race in the DC

**Comment by kargakis** [comment] 2016-06-24 14:58
This is back, @smarterclayton what race were you talking about?
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2442/console

**Comment by kargakis** [comment] 2016-07-15 20:42
@stevekuznetsov can you make this print the RC the last time it is retried instead of 178 times before?

**Comment by kargakis** [comment] 2016-07-15 20:43
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3410/consoleFull

**Comment by stevekuznetsov** [comment] 2016-07-18 16:45
> @stevekuznetsov can you make this print the RC the last time it is retried instead of 178 times before?

The output shows you every single piece of output that we got in the run, squashed to no repeat outputs that are identical. I don't think in the general case it makes sense to show only the oldest output.

**Comment by kargakis** [comment] 2016-07-19 08:09
Not the oldest but the latest - I am not sure if for 178 repeats the object
stays exactly the same but you probably know better.

**Comment by stevekuznetsov** [comment] 2016-07-19 11:43
Right, sorry. The output will show every unique output, so if it's squashed and tells you it happened 178 times or whatever, the output those 178 times was identical. We also honor chronology, so X X Y Y X X Z will become 2X 2Y 2X Z. You'll always see the output in time order, and if in that order it's repeated, we won't double print it.

**Comment by kargakis** [comment] 2016-08-22 10:06
I am going to move this test in the extended suite (that's where it should be in the first place)

**Closed** 2016-08-22 22:20 UTC
Labels: kind/test-flake, priority/P2
