### ISSUE TITLE
Too much whitespace in new-app description

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13492] opened 2017-03-21 21:07 UTC
This wasn't happening earlier in the release.

```
$ oc new-app --template=kube-system/heapster-standalone
--> Deploying template "kube-system/heapster-standalone" for "kube-system/heapster-standalone" to project myproject

     Heapster Metrics (Standalone)
     ---------
     A simple metrics solution for an OpenShift cluster. Expects to be installed in the 'kube-system' namespace.



     * With parameters:
        * MASTER_URL=https://kubernetes.default.svc
        * IMAGE_PREFIX=openshift/origin-
        * IMAGE_VERSION=latest
        * METRIC_RESOLUTION=15s
        * STARTUP_TIMEOUT=500
        * NAMESPACE=kube-system
```

**Comment by bparees** [comment] 2017-03-21 21:10
you sure at least some of those newlines are in the template description?  I only see 2:

```
$ oc new-app -f application-template-stibuild.json 
--> Deploying template "brokersdk/ruby-helloworld-sample" for "application-template-stibuild.json" to project brokersdk

     ruby-helloworld-sample
     ---------
     This example shows how to create a simple ruby application in openshift origin v3


     * With parameters:
```

**Comment by smarterclayton** [comment] 2017-03-22 01:19
This looks wrong: https://github.com/openshift/origin/pull/13380

**Comment by bparees** [comment] 2017-03-22 01:54
> This looks wrong: #13380

@smarterclayton is that what you intended to link?  it seems unrelated to this issue so i don't know if you're saying that PR (retrying pull image actions) is also wrong or you linked the wrong thing.

**Comment by bparees** [comment] 2017-03-22 02:11
the only recent change that might affect the output is this:
https://github.com/openshift/origin/blame/master/pkg/generate/app/cmd/template.go#L44

perhaps the decode is injecting an empty message field in the result object that results in extra newlines being printed out.

**Comment by smarterclayton** [comment] 2017-03-22 16:20
An empty message field should be ignored I think (if it's only whitespace).

**Comment by bparees** [comment] 2017-03-22 17:04
@smarterclayton yeah should be, the current code doesn't do that (just checks for len(0))

**Comment by gabemontero** [comment] 2017-03-24 19:26
There is a new line in the text being returned by `description := result.Annotations["description"]` at https://github.com/openshift/origin/blob/master/pkg/generate/app/cmd/template.go#L72

I confirmed by adding a temporary glog.V(0).Infof("Descr is %s additional text", description) ... the "additional text" was on a different line

Additional lines are inserted by https://github.com/openshift/origin/blob/master/pkg/generate/app/cmd/template.go#L80 and https://github.com/openshift/origin/blob/master/pkg/generate/app/cmd/template.go#L86 in this particular example.

There were no injections from the decode stuff that I could find.

Removing https://github.com/openshift/origin/blob/master/pkg/generate/app/cmd/template.go#L86 seems like a no brainer to me.  It does look less awkward with just that change.  

Do we want to chase down the new line in the annotation?  In theory, we could make some of the `fmt.Fprintln(out)` conditional based on some analysis of the `\n` in the strings printed ... but perhaps that is excessive.

**Comment by bparees** [comment] 2017-03-24 19:49
> There were no injections from the decode stuff that I could find.

yeah in hindsight the decode is only operating on the objects, not the template fields themselves.  but i see no other reason for this to have changed.

I do think it makes sense to just print the newline if the string itself does not end in a newline.

but i'm still not seeing how clayton's example gets to 3 blank lines:

somedescription\n  (field value includes a newline)
blank (from fmt.Println after printing the description)
blank (from fmt.Println after printing message+description)
blank (from ???  possibly from printing an empty message?)
* with parameters blah blah

your proposal would get us down to 2 blanks, but we really should be at one.

(assuming i'm reading all this correctly)

**Comment by gabemontero** [comment] 2017-03-24 20:24
On Fri, Mar 24, 2017 at 3:49 PM, Ben Parees <notifications@github.com>
wrote:

> There were no injections from the decode stuff that I could find.
>
> yeah in hindsight the decode is only operating on the objects, not the
> template fields themselves. but i see no other reason for this to have
> changed.
>
> I do think it makes sense to just print the newline if the string itself
> does not end in a newline.
>
> but i'm still not seeing how clayton's example gets to 3 blank lines:
>
> somedescription\n (field value includes a newline)
> blank (from fmt.Println after printing the description)
> blank (from fmt.Println after printing message+description)
> blank (from ??? possibly from printing an empty message?)
>
There was no blank from an empty message ... confirmed via trace we did not
go
down that path.

I think the `formatString` function is adding something as well, but have
not confirmed that
yet.  That path changed earlier this year (the commit was created in late
Jan, but of course it
could have merged later).

But I wanted some feedback before going too far down one path vs. another.
If I read you right,
you are amenable to analyzing the description, etc. for new-lines and
adjusting newlines this
code path inserts accordingly.  I'll start down hat path.

**Comment by gabemontero** [comment] 2017-03-24 20:52
Yep `formatString` is also adding additional lines.  Hope to have something to review before EOB today.

**Comment by gabemontero** [comment] 2017-03-24 20:56
Also, upon further review, I *think* `formatString` is trying to account for whether the string ends with a new line.

Between the fix I have there, plus the removal on one unneeded `fmt.Fprintf(out)` we should be good.

**Closed** 2017-03-27 19:39 UTC
Labels: area/usability, component/cli, priority/P2
