### ISSUE TITLE
[Feature:Builds] forcePull should affect pulling builder images ForcePull test case execution s2i [Suite:openshift/conformance/parallel] 11s

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17900] opened 2017-12-20 16:38 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17827/test_pull_request_origin_extended_conformance_gce/13358/

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:78
Expected error:
    <*util.ExitError | 0xc4208508d0>: {
        Cmd: "oc adm --config=/tmp/cluster-admin.kubeconfig --namespace=extended-test-forcepull-4cfmf-fzgvg policy remove-cluster-role-from-user system:build-strategy-custom extended-test-forcepull-4cfmf-fzgvg-user",
        StdErr: "Error from server (Conflict): Operation cannot be fulfilled on clusterrolebindings.authorization.openshift.io \"system:build-strategy-custom\": the object has been modified; please apply your changes to the latest version and try again",
        ExitError: {
            ProcessState: {
                pid: 19026,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 233562},
                    Stime: {Sec: 0, Usec: 24352},
                    Maxrss: 61948,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 14822,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 1567,
                    Nivcsw: 8,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:90
```

**Comment by bparees** [comment] 2017-12-21 00:38
dupe of https://github.com/openshift/origin/issues/17596

**Closed by bparees** 2017-12-21 00:38 UTC
Labels: component/build, kind/test-flake, priority/P1
