### ISSUE TITLE
Registry: after 'atomic install atomic-registry-install' atomic-registry-master has failed message

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#11490] opened 2016-10-21 18:29 UTC
After 'atomic install atomic-registry-install' atomic-registry-master has failed message

```
Oct 21 14:12:29 katello.example.com atomic-registry-master[19649]: I1021 18:12:29.937888       1 scheduler.go:100] Failed to schedule pod: default/docker-registry-1-deploy
```

I was told this was harmless but is disconcerting to see that in the journalctl constantly repeating every 10 seconds or so.
##### Version

docker.io/projectatomic/atomic-registry-install:latest
##### Steps To Reproduce
1. atomic install docker.io/projectatomic/atomic-registry-install:latest
2. journalctl -fu atomic-registry-master
##### Current Result

Failed message every 10 seconds or so
##### Expected Result

No failed messages

**Comment by aweiteka** [comment] 2016-10-24 12:13
@thomasmckay this should have been resolved by #11470 and #10706. Can you confirm?

**Comment by thomasmckay** [comment] 2016-10-24 13:29
@aweiteka I still see this on a fresh install from docker.io

**Comment by Syffs** [comment] 2016-12-23 00:51
+1

**Comment by aweiteka** [comment] 2017-01-03 14:16
Old issue. Unable to reproduce. Please re-open if necessary.

**Closed by aweiteka** 2017-01-03 14:16 UTC
Labels: component/imageregistry, component/install, priority/P2
