### ISSUE TITLE
Openshift 1.4.0+ release archive for linux extracts with `+` instead of `-` in directory name

### ISSUE THREAD

**Issue by budhrg** [openshift/origin#12663] opened 2017-01-25 11:32 UTC
##### Version
1.4.0+

##### Steps To Reproduce
1. Download https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz
2. Untar it

##### Current Result
After untar, folder creates with `+` instead of `-` after version as `openshift-origin-client-tools-v1.4.1+3f9807a-linux-64bit`

##### Expected Result
Expecting `openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit` after untar.

##### Additional Information
- Not the case with Mac or Windows archives
- Breaking minishift `oc` caching too https://github.com/minishift/minishift/issues/331.

Would like to know, is there any strategy change here for Linux or some kind of regression?

**Comment by pweil-** [comment] 2017-01-25 15:50
duplicate of https://github.com/openshift/origin/issues/12576

**Closed by pweil-** 2017-01-25 15:50 UTC
