### ISSUE TITLE
Building OpenShift took longer than before

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1044] opened 2015-02-17 10:00 UTC
I've noticed this last week, the `./hack/build-go.sh` is taking a bit more than it was before. I wonder if there were some changes in the way we build or something I can turn off to make it build faster.

With 'make clean':

```
 ~/go/src/github.com/openshift/origin → time make
hack/build-go.sh 
++ Building go targets for linux/amd64:  cmd/openshift
++ Placing binaries

real	0m12.931s
user	0m27.710s
sys	0m3.890s
```

It used to be ~5s before. @smarterclayton any ideas?

**Comment by smarterclayton** [comment] 2015-02-17 18:56
ask dan mace

----- Original Message -----

**Comment by mfojtik** [comment] 2015-02-19 13:45
@ironcladlou ^^

**Comment by ironcladlou** [comment] 2015-02-19 15:17
Couldn't reproduce yet on OSX.

**Comment by smarterclayton** [comment] 2015-02-19 16:21
I haven't noticed a significant reversion - we should still be doing a single go install to build the binary, so either it's something changed related to that, or the size of the binary / things we compile dramatically increased.

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-02-20 01:36
@ironcladlou this is why:

```
$ hack/build-go.sh 
++ Building go targets for darwin/amd64: images/pod examples/hello-openshift cmd/openshift
++ Placing binaries
```

**Comment by ironcladlou** [comment] 2015-02-20 13:53
Clean build is 19s for me, incremental is 5s.  Of course adding more targets increases the size.

Two things we could do:

1. Only build image binaries during make-release (I don't like this: you won't know you broke stuff until you run make-release)
2. Just run `hack/build-go.sh cmd/openshift` if you only want to build the openshift binary.

Thoughts?

**Comment by mfojtik** [comment] 2015-02-20 13:58
@ironcladlou 2) is ~ 12s for me which is reasonable :-) thank for this hint

**Comment by smarterclayton** [comment] 2015-02-20 16:33
----- Original Message -----
> Clean build is 19s for me, incremental is 5s.  Of course adding more targets
> increases the size.
> 
> Two things we could do:
> 
> 1. Only build image binaries during make-release (I don't like this: you
> won't know you broke stuff until you run make-release)

No one ever changes those.  I'd prefer you make this change.

**Comment by ironcladlou** [comment] 2015-03-04 18:29
@smarterclayton Please assign this one to me.

**Closed** 2015-03-06 15:21 UTC
Labels: bug

**Comment by kargakis** [comment] 2015-05-04 11:46
Why is this closed? Building the latest master now takes about half a minute...
```
$ time make build
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift
++ Placing binaries

real	0m33.458s
user	0m57.875s
sys	0m11.161s
```

**Comment by ironcladlou** [comment] 2015-05-04 14:33
@kargakis At the time, performance was sufficiently improved and so the issue was closed. Can you open a new issue with this info and also machine/environment specifics?
