### ISSUE TITLE
UI submits all template objects to v1 API, regardless of object API version

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4410] opened 2015-08-28 14:55 UTC
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1261076

Seen in the Zookeeper template (which currently uses v1beta3).

```
[vagrant@openshiftdev origin]$ oc create -f examples/zookeeper/ -n openshift
template "zookeeper" created
```

Try to use it in the Web Console. You'll see errors.

<img width="704" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/9549258/0e2e7754-4d73-11e5-81b7-da3d047bd068.png">

**Comment by spadgett** [comment] 2015-08-28 14:56
No errors on the command line.

```
[vagrant@openshiftdev origin]$ oc new-app zookeeper -n project4
imagestreams/zookeeper-346-jdk7
services/zookeeper
services/zookeeper-1
services/zookeeper-2
services/zookeeper-3
pods/zookeeper-1
pods/zookeeper-2
pods/zookeeper-3
Service "zookeeper" created at 172.30.151.34 with port mappings 2181.
Service "zookeeper-1" created at 172.30.189.86 with port mappings 2181->2181, 2888->2888, 3888->3888.
Service "zookeeper-2" created at 172.30.30.8 with port mappings 2181->2181, 2888->2888, 3888->3888.
Service "zookeeper-3" created at 172.30.121.149 with port mappings 2181->2181, 2888->2888, 3888->3888.
Run 'oc status' to view your app.
```

**Comment by mfojtik** [comment] 2015-08-28 15:04
I have to update the template. @bparees can you assign this to me?

**Comment by liggitt** [comment] 2015-08-28 15:05
Caused by https://github.com/openshift/origin/issues/4173

All objects HAVE to be submitted to the right version endpoint, which means every client either has to be able to convert to the API version they want to submit to (which is what the CLI does) or know the right endpoints for every API version they want to support in lists/templates

**Comment by liggitt** [comment] 2015-08-28 15:06
If the UI locks to a particular API version, that means all templates have to also be locked to that version, which seems impossible to enforce/maintain. @smarterclayton this feels like a problem the upstream API design will make worse...

**Comment by liggitt** [comment] 2015-08-28 15:06
@mfojtik open a separate issue for updating the template... this issue should be used to solve the general problem of the UI submitting all objects to the v1 endpoint

**Comment by mfojtik** [comment] 2015-08-28 15:08
@liggitt done, now you can assign the issue I made to me ;-)

**Comment by smarterclayton** [comment] 2015-08-28 15:24
Should the UI then not be locking to v1?

On Fri, Aug 28, 2015 at 12:06 PM, Jordan Liggitt <notifications@github.com>
wrote:

> @mfojtik <https://github.com/mfojtik> open a separate issue for updating
> the template... this issue should be used to solve the general problem of
> the UI submitting all objects to the v1 endpoint
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4410#issuecomment-135799390>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment] 2015-08-28 15:25
I kind of agree though that inflexibilty in what you expect is bad.

On Fri, Aug 28, 2015 at 12:24 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> Should the UI then not be locking to v1?
>
> On Fri, Aug 28, 2015 at 12:06 PM, Jordan Liggitt <notifications@github.com
> > wrote:
>
>> @mfojtik <https://github.com/mfojtik> open a separate issue for updating
>> the template... this issue should be used to solve the general problem of
>> the UI submitting all objects to the v1 endpoint
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/4410#issuecomment-135799390>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment] 2015-08-28 15:33
> Should the UI then not be locking to v1?

There is zero chance the UI will have conversion logic, so it has to pick a version of the API to read from and write to for objects it is expecting to deal with the contents of.

Templates are sort of a special case, the UI just iterates through the list, looks at the type, and ships it off to the origin or k8s API without looking at any of the other fields. Now, it would have to also look at the apiVersion and make that part of the URL (including the weirdness of origin v1beta3 being at a different context). Yuck.

**Comment by smarterclayton** [comment] 2015-08-28 15:36
Wait... templates don't convert versions.

On Fri, Aug 28, 2015 at 12:33 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Should the UI then not be locking to v1?
>
> There is zero chance the UI will have conversion logic, so it has to pick
> a version of the API to read from and write to for objects it is expecting
> to deal with the contents of.
>
> Templates are sort of a special case, the UI just iterates through the
> list, looks at the type, and ships it off to the origin or k8s API without
> looking at any of the other fields. Now, it would have to also look at the
> apiVersion and make that part of the URL (including the weirdness of origin
> v1beta3 being at a different context). Yuck.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4410#issuecomment-135807761>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment] 2015-08-28 15:37
You get back a list of objects from the /process endpoint in the same
version you sent them.

On Fri, Aug 28, 2015 at 12:36 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> Wait... templates don't convert versions.
>
> On Fri, Aug 28, 2015 at 12:33 PM, Jordan Liggitt <notifications@github.com
> > wrote:
>
>> Should the UI then not be locking to v1?
>>
>> There is zero chance the UI will have conversion logic, so it has to pick
>> a version of the API to read from and write to for objects it is expecting
>> to deal with the contents of.
>>
>> Templates are sort of a special case, the UI just iterates through the
>> list, looks at the type, and ships it off to the origin or k8s API without
>> looking at any of the other fields. Now, it would have to also look at the
>> apiVersion and make that part of the URL (including the weirdness of origin
>> v1beta3 being at a different context). Yuck.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/4410#issuecomment-135807761>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment] 2015-08-28 15:38
Right. The UI reads a stored template containing v1beta3 objects, submits it for processing as-is, gets back v1beta3 objects, and now needs to know all the api+version endpoints that will ever exist

**Comment by smarterclayton** [comment] 2015-08-28 15:46
Certainly it needs to know the same thing the CLI needs and that any other
generic tool needs.  Eclipse needs it as well.

On Fri, Aug 28, 2015 at 12:38 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Right. The UI reads a stored template containing v1beta3 objects, submits
> it for processing as-is, gets back v1beta3 objects, and now needs to know
> all the api+version endpoints that will ever exist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4410#issuecomment-135809155>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by spadgett** [comment] 2015-08-28 18:17
>  The UI reads a stored template containing v1beta3 objects, submits it for processing as-is, gets back v1beta3 objects, and now needs to know all the api+version endpoints that will ever exist

We could support up to a version like v1 so we don't guess at future endpoints. Handling context changes like `osapi` -> `oapi` is a bit annoying, otherwise it's just changing one path segment.

**Comment by liggitt** [comment] 2015-08-28 18:21
You think it's just one path segment. Just wait until you see what upstream has in store

**Comment by spadgett** [comment] 2015-08-28 18:40
Ha. Can't wait :)

So what are the alternatives? Have /process convert for us? Lock to a version?

**Comment by liggitt** [comment] 2015-08-28 18:41
I think we have to take the api version in the object and plug it into the URL, but you can't assume it's a single path segment

**Comment by liggitt** [comment] 2015-08-28 18:42
should also probably do some basic validation to make sure it doesn't contain backsteps

**Closed** 2015-09-08 20:13 UTC
Labels: component/web, kind/bug, priority/P1
