### ISSUE TITLE
Logging into Openshift Internal Docker Registry - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by pratapnanda** [openshift/origin#21236] opened 2018-10-12 10:20 UTC
[provide a description of the issue]
Trying to login into Docker and push an image to Openshift's internal Docker-Registry but can't seem to successfully login as it complains that the certificate is signed by unknown authority

I have gone through many solution in GitHub but no solution worked for me

I have created a folder with name "docker-registry-default.test.tc.ocp.xxx.corp" inside /etc/docker/certs.d/ . And then i have copied my certificate file inside this .Then i have restarted my docker daemon  from my client .Still the same issue there.

Now i don't understand the further action needs to be taken .struggling with this issue since last 7 days .
Really appreciated if someone can help me 

====>+ oc login https://master.test.tc.ocp.xxx.corp:8443 -u **** -p **** --insecure-skip-tls-verify=true
Login successful.

====>+ docker info
Containers: 43
 Running: 15
 Paused: 0
 Stopped: 28
Images: 79
Server Version: 1.13.1

====>
+ oc get pods
NAME                             READY     STATUS    RESTARTS   AGE
api-gateway-server-2-c62l8       1/1       Running   2          16d
config-server-2-5bqxm            1/1       Running   0          16d

======>++ oc whoami -t
======>+ docker login -p F1WR8Yd0G0o_PBZx-Bd0n-1hiZH7miZWssvZCfNsX_Y -e unused -u unused docker-registry-default.test.tc.ocp.xxx.corp
Flag --email has been deprecated, will be removed in 1.14.
Error response from daemon: Get https://docker-registry-default.test.tc.ocp.xxx.corp/v1/users/: x509: certificate signed by unknown authority
##### Version
Openshift Origin 3.7

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Current Result
Error response from daemon: Get https://docker-registry-default.test.tc.ocp.xxx.corp/v1/users/: x509: certificate signed by unknown authority
##### Expected Result
successfully login

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by arewm** [comment] 2019-02-08 17:09
Is this a duplicate of https://github.com/openshift/origin/issues/16500 ?

**Closed** 2019-04-09 22:42 UTC
Labels: lifecycle/rotten
