### ISSUE TITLE
extended k8s failure: port forward

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5382] opened 2015-10-24 17:17 UTC
```
STEP: Destroying namespace "e2e-tests-port-forwarding-l3f9k" for this suite.
• Failure [11.305 seconds]
Port forwarding With a server that expects no client request [It] should support a client that connects, sends no data, and disconnects [Conformance] 
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/portforward.go:221

  Oct 24 02:13:50.312: Failed to parse kubectl port-forward output: F1024 02:13:50.312226   18834 portforward.go:116] Unable to execute command because pod is not running. Current status=Failed
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/portforward.go:102
```

from jenkins: https://ci.openshift.redhat.com/jenkins/job/origin_extended/196/consoleFull

@smarterclayton @deads2k

**Comment by smarterclayton** [comment] 2015-10-24 18:40
@ncdc this is the flake I mentioned

On Oct 24, 2015, at 1:17 PM, Ben Parees <notifications@github.com> wrote:

STEP: Destroying namespace "e2e-tests-port-forwarding-l3f9k" for this suite.
• Failure [11.305 seconds]
Port forwarding With a server that expects no client request [It]
should support a client that connects, sends no data, and disconnects
[Conformance]
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/portforward.go:221

  Oct 24 02:13:50.312: Failed to parse kubectl port-forward output:
F1024 02:13:50.312226   18834 portforward.go:116] Unable to execute
command because pod is not running. Current status=Failed
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/portforward.go:102

from jenkins:
https://ci.openshift.redhat.com/jenkins/job/origin_extended/196/consoleFull

@smarterclayton <https://github.com/smarterclayton> @deads2k
<https://github.com/deads2k>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5382>.

**Comment by smarterclayton** [comment] 2015-10-25 22:28
Disabled it for now.

**Comment by ncdc** [comment] 2015-10-26 15:03
This is failing because the restricted SCC doesn't allow containers to bind to low ports, and the portforwardtester image wants to bind to 80.

**Comment by pweil-** [comment] 2015-10-26 15:07
This is something we ran into with the router as well.  If the pod is validating under the restricted SCC and running as non-root the executable must be granted `cap_net_bind_service` in order to bind to the low ports in the container.  

We discussed a proposal to add namespace hinting about SCCs to influence the sort order of which SCC will be tried first.  This sounds like a test candidate assuming the user who is creating the pod has access to the privileged SCC.  I am writing up the proposal, just currently working on getting feedback completed for volume security pieces.

**Comment by liggitt** [comment] 2015-10-26 15:09
we should probably update the SCCs for the kube extended tests. we could delete the `restricted` SCC and add system:authenticated to the privileged one to mimic the kube environment

**Comment by smarterclayton** [comment] 2015-10-26 15:24
All Kube extended tests are running under privileged SCC already, so no,
it's not :)

**Comment by smarterclayton** [comment] 2015-10-26 15:24
Unless you mean the pod service account.

**Comment by ncdc** [comment] 2015-10-26 15:25
Something is denying the container from binding to port 80...

**Comment by smarterclayton** [comment] 2015-10-26 15:25
If the pod itself needs to be uid 0 this is the bug I opened against Paul
where we are "defaulting" the uid range, not allowing the image default to
work  https://github.com/openshift/origin/issues/5317 covers this and is p1.

**Comment by ncdc** [comment] 2015-10-26 15:26
For this particular e2e test, there is no user set in the pod definition or the Dockerfile.

**Comment by smarterclayton** [comment] 2015-10-26 15:27
Yes, and our SCC mechanism is "wrong" in that it sets a UID on the docker
image (denying root) when it should allow the image default because
privileged lets you runasany.  If we're confident this is bind to 80, we
should dupe this against 5317

**Comment by ncdc** [comment] 2015-10-26 15:28
I am 100% certain this is denying bind to 80

**Comment by smarterclayton** [comment] 2015-10-26 15:31
Dupe of #5317

**Comment by liggitt** [comment] 2015-10-26 15:40
the user running the tests is in both privileged and restricted, right? we want them only in privileged

**Comment by pweil-** [comment] 2015-10-26 15:45
Yes.  What has been proposed is to change the ordering of the SCC sorting such that you run with a more privileged SCC if you have access to it rather than the most restrictive SCC.  This could be a simple reversal of the current sort but we'd also like to incorporate some namespace hinting to give a little more control over what should be tried first.

**Comment by smarterclayton** [comment] 2015-10-26 16:32
The core problem: "it is impossible to run an image in OpenShift as the
user defined by the image if you have access to a SCC that is range
limited".

**Comment by stevekuznetsov** [comment] 2016-11-09 21:02
Looks like we hit this [again](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8519/testReport/junit/(root)/Extended/_k8s_io__Port_forwarding__k8s_io__With_a_server_that_expects_a_client_request_should_support_a_client_that_connects__sends_no_data__and_disconnects__Conformance_/)? Did we change some SCC definitions?  /cc @ncdc @deads2k @liggitt

**Comment by ncdc** [comment] 2016-11-09 21:13
@stevekuznetsov pretty sure what you linked is just #11662

**Closed by ncdc** 2016-11-09 21:13 UTC
Labels: kind/test-flake

**Comment by stevekuznetsov** [comment] 2016-11-09 21:17
Terrible search-fu... should leave that up to the bots :)
