### ISSUE TITLE
End-To-End flake waiting for database pod to be running

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8041] opened 2016-03-16 13:10 UTC
flake on `e2e` [here](https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5323/consoleFull#100957321356cf27b1e4b0ecce0b4ec162):
```
FAILURE after 59.900s: hack/../hack/../test/end-to-end/core.sh:25: executing 'oc get -n test pods -l name=database' expecting any result and text 'Running'; re-trying every 0.2s until completion or 60.000s: the command timed out
There was no output from the command.
There was no error output from the command.
!!! Error in hack/../hack/../test/end-to-end/../../hack/cmd_util.sh:503
	'return 1' exited with status 1
```

/cc @deads2k

**Comment by bparees** [comment] 2016-03-17 18:05
There's not much magic here.  We instantiated a template which defines a DC for the database pod and apparently that pod never got created.  Should start w/ the deployments team, maybe we need to add some debug that probes the states of the deploymentconfigs when this fails.

**Comment by liggitt** [comment] 2016-03-17 18:52
Same cpu.shares issue in the origin.log:
```
E0315 18:53:53.097110     917 manager.go:1873] Error running pod "database-1-hook-mid_test(409b20f6-eadf-11e5-90d5-0ea2e8c232ed)" container "lifecycle": runContainer: API error (500): Cannot start container 01620fb8150f0501518408e2a21ea12550ccb7c34918c84c11176ac93ef60113: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-01620fb8150f0501518408e2a21ea12550ccb7c34918c84c11176ac93ef60113.scope/cpu.shares: no such file or directory
```

**Comment by bparees** [comment] 2016-03-17 18:56
@mrunalp ^^^

**Comment by mrunalp** [comment] 2016-03-17 18:59
@bparees Thanks! Can we dupe these to one ore two issues?
There are two classes:
1. Like #7616 
2. Like #7927 
I have created potentail fixes for both which should be available as rpm updates.

**Comment by mrunalp** [comment] 2016-03-17 19:09
Can we check if we have docker version docker-1.9.1-23.el7 running?

**Comment by bparees** [comment] 2016-03-17 19:10
```
$ docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-19.el7.x86_64
 Go version:      go1.4.2
 Git commit:      185277d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-19.el7.x86_64
 Go version:      go1.4.2
 Git commit:      185277d/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

**Comment by mrunalp** [comment] 2016-03-17 19:10
@bparees thanks, the version needs to be updated. I am not sure who does that.

**Comment by bparees** [comment] 2016-03-17 19:10
@mrunalp should happen the next time we build a base ami.

**Comment by mrunalp** [comment] 2016-03-17 19:11
@bparees @liggitt One more question. When a pod fails to start because of a cgroups issue, is there an attempt made to restart it? (I would think that the kubelet should be doing it.)

**Comment by bparees** [comment] 2016-03-17 19:12
@mrunalp we build the base ami yesterday and it picked up 19, when did 23 drop?

**Comment by bparees** [comment] 2016-03-17 19:12
@mrunalp i don't think it will attempt to restart it if there's no replication controller around it.

**Comment by bparees** [comment] 2016-03-17 19:18
dupe of https://github.com/openshift/origin/issues/7616

**Closed by bparees** 2016-03-17 19:18 UTC
Labels: kind/test-flake, priority/P2
