### ISSUE TITLE
daemonset test flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#8647] opened 2016-04-27 12:27 UTC
```
• Failure [730.538 seconds]
[k8s.io] Daemon set [Serial]
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework.go:420
  should run and stop simple daemon [It]
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/daemon_set.go:144

  Expected error:
      <*errors.errorString | 0xc20802b6e0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/daemon_set.go:120
```
from: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/491/console

**Comment by smarterclayton** [comment] 2016-04-27 12:53
@pweil- @ncdc can you have someone look at this?  This *could* be a cleanup issue (I notice there are "overcommit" pods still scheduled, maybe from a previous job).  This should be in the serial execution path (where we run them one at a time because they have [Serial])

**Comment by pweil-** [comment] 2016-04-27 13:13
Looks like it's occurring during ns cleanup timing out with remaining pods.  Seems to also have occurrred on the latency tests.  From the linked console:

```
STEP: Destroying namespace "e2e-tests-svc-latency-i3i1h" for this suite.
Apr 26 23:25:41.518: INFO: Pod e2e-tests-svc-latency-i3i1h svc-latency-rc-4m8kg on node 172.18.4.31 remains, has deletion timestamp 2016-04-26 23:21:11 -0400 EDT
Apr 26 23:25:41.518: FAIL: Couldn't delete ns "e2e-tests-svc-latency-i3i1h": namespace e2e-tests-svc-latency-i3i1h was not deleted within limit: timed out waiting for the condition, pods remaining: [svc-latency-rc-4m8kg]

... snip ...

STEP: Destroying namespace "e2e-tests-daemonsets-61m4o" for this suite.
Apr 26 23:37:52.055: INFO: Pod e2e-tests-daemonsets-61m4o daemon-set-xpldy on node 172.18.4.31 remains, has deletion timestamp 2016-04-26 23:26:17 -0400 EDT
Apr 26 23:37:52.056: FAIL: Couldn't delete ns "e2e-tests-daemonsets-61m4o": namespace e2e-tests-daemonsets-61m4o was not deleted within limit: timed out waiting for the condition, pods remaining: [daemon-set-xpldy]
```

Still investigating.

**Comment by smarterclayton** [comment] 2016-04-27 13:15
Could this be the leaky namespace issue that QE reported this morning?
 @derekwaynecarr

**Comment by ncdc** [comment] 2016-04-27 13:16
@smarterclayton link?

**Comment by smarterclayton** [comment] 2016-04-27 13:39
Bug 1322538: Project delete leads to unexpected items in namespace and
causes reliability cluster to eventually go
unusable [ASSIGNED][Kubernetes][unspecified][high][Regression]

**Comment by ncdc** [comment] 2016-04-27 13:49
That bug is https://github.com/kubernetes/kubernetes/issues/24819

**Comment by aveshagarwal** [comment] 2016-04-27 15:28
@pweil- said that he might be busy, so I am starting to look into it.

**Comment by pweil-** [comment] 2016-04-27 15:43
still looking, just have some meetings this afternoon.  Thanks for the help @aveshagarwal, much appreciated!

**Comment by aveshagarwal** [comment] 2016-04-27 16:26
It seems that this flake is not specific to daemon sets, as I see so many other failures in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/491/console all related to not able to delete ns (errors" FAIL: Couldn't delete ns...").

**Comment by aveshagarwal** [comment] 2016-04-27 17:10
The first failure I see:

```
Apr 26 21:59:23.544: FAIL: Couldn't delete ns "e2e-tests-sched-pred-ckcnm": namespace e2e-tests-sched-pred-ckcnm was not deleted within limit: timed out waiting for the condition, pods remaining: [overcommit-0 overcommit-1 overcommit-2 overcommit-3]
```

One common failure I see:

```
Apr 26 21:52:23.501: INFO: router-1-deploy          172.18.4.31  Failed          []
```

**Comment by aveshagarwal** [comment] 2016-04-27 17:18
Just listing here to understand the impact/cause of these errors:

```
I0426 21:42:23.499905   14160 meta.go:46] Calling Accessor on non-internal object: *api.PodList
I0426 21:49:36.514984   14160 reflector.go:411] k8s.io/kubernetes/test/e2e/util.go:244: Watch close - *api.Pod total 3 items received
Apr 26 21:52:23.485: INFO: Unexpected error occurred: Timeout while waiting for pods with labels "startPodsID=49d8f1ff-0c19-11e6-95d6-0e0dc6d572a3" to be running
I0426 21:52:23.489963   14160 request.go:766] Error in request: resource name may not be empty
```

**Comment by aveshagarwal** [comment] 2016-04-27 17:46
And also the issues with left over pods:

```
Apr 26 21:59:23.544: INFO: Pod e2e-tests-sched-pred-ckcnm overcommit-0 on node 172.18.4.31 remains, has deletion timestamp 2016-04-26 21:54:53 -0400 EDT
```

**Comment by aveshagarwal** [comment] 2016-04-27 18:55
I wonder why a namespace created in one test is being cleaned up in other tests and making them fail? It seems that once a namespace clean up fails in one test, it is causing failures of all subsequent tests.

**Comment by aveshagarwal** [comment] 2016-04-27 21:18
It seems weird that a pod (svc-latency-rc-4m8kg) left over from `Service endpoints latency` test with ns `e2e-tests-svc-latency-i3i1h` is  visible in the event logs of ` Daemon set [Serial] ` with different ns `e2e-tests-daemonsets-61m4o`. Seems like a bug to me.

**Comment by aveshagarwal** [comment] 2016-04-27 21:23
What is happening with DS test is that its pod `daemon-set-xpldy` in ns `e2e-tests-daemonsets-61m4o` is always in pending phase. There is a successful delete event too:

```
Apr 26 23:30:51.826: INFO: At 2016-04-26 23:25:49 -0400 EDT - event for daemon-set: {daemon-set } SuccessfulDelete: Deleted pod: daemon-set-xpldy
```

But why the pod is still on the node after almost 12 minutes is a mystery to me:

```
Apr 26 23:37:52.055: INFO: Pod e2e-tests-daemonsets-61m4o daemon-set-xpldy on node 172.18.4.31 remains, has deletion timestamp 2016-04-26 23:26:17 -0400 EDT
```

And this is causing the namespace to linger and the test to time out/fail.

**Comment by pweil-** [comment] 2016-09-21 08:39
this flake hasn't been referenced in some time.  Closing for now

**Closed by pweil-** 2016-09-21 08:39 UTC
Labels: component/kubernetes, kind/test-flake, priority/P2
