### ISSUE TITLE
Jenkins plugin: options for Trigger Openshift Build

### ISSUE THREAD

**Issue by anhnguyenbk** [openshift/origin#10888] opened 2016-09-13 05:37 UTC
I using external Jenkins for build server and OpenShift just for binary deployment.
I  want to trigger Openshift `start-build` with `war` file from Jenkins build stage. 

Could I use options `--from-file` in Trigger Openshift Build or another way?

Thanks.

**Comment by bparees** [comment] 2016-09-13 11:30
dupe of https://github.com/openshift/jenkins-plugin/issues/64
and trello'd: https://trello.com/c/kJrtI2kF

**Closed by bparees** 2016-09-13 11:30 UTC
Labels: component/build, kind/question, priority/P2
