### ISSUE TITLE
oadm router test flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9557] opened 2016-06-24 19:53 UTC
```
=== BEGIN TEST CASE ===
test/cmd/router.sh:46: executing 'oadm router --dry-run --host-network=false --host-ports=false --secrets-as-env --credentials=${KUBECONFIG} -o yaml' expecting success and text 'OPENSHIFT_MASTER'
FAILURE after 0.888s: test/cmd/router.sh:46: executing 'oadm router --dry-run --host-network=false --host-ports=false --secrets-as-env --credentials=${KUBECONFIG} -o yaml' expecting success and text 'OPENSHIFT_MASTER': the output content test failed
```

as seen in:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/2465/console

**Comment by knobunc** [comment] 2016-06-24 20:01
@weliang1 Please take a look

**Comment by weliang1** [comment] 2016-06-27 19:10
Run hack/test-cmd.sh test/cmd/router.sh several times, but I can not reproduce above issue.
Here is my test log: https://paste.fedoraproject.org/385643/05448414/

**Comment by weliang1** [comment] 2016-06-28 20:29
Debug router.sh script and manually run router.sh line 46, the output will show OPENSHIFT_MASTER

SUCCESS after 0.112s: test/cmd/router.sh:42: executing 'oadm router --dry-run --host-network=false --host-ports=false -o yaml' expecting success and not text 'host: localhost'
SUCCESS after 0.122s: test/cmd/router.sh:44: executing 'oadm router --dry-run --host-network=false --host-ports=false -o yaml' expecting success and not text 'OPENSHIFT_MASTER'
bash-4.2# oadm router --dry-run --host-network=false --host-ports=false --secrets-as-env -o yaml | grep MASTER
bash-4.2# 
bash-4.2# oadm router --dry-run --host-network=false --host-ports=false --secrets-as-env --credentials=${KUBECONFIG} -o yaml | grep MASTER
Flag --credentials has been deprecated, use --service-account to specify the service account the router will use to make API calls
          - name: OPENSHIFT_MASTER
bash-4.2# oadm router --dry-run --host-network=false --host-ports=false --secrets-as-env --credentials=${KUBECONFIG} -o yaml | grep MASTER
Flag --credentials has been deprecated, use --service-account to specify the service account the router will use to make API calls
          - name: OPENSHIFT_MASTER
bash-4.2#

**Comment by liggitt** [comment] 2016-07-07 04:30
@stevekuznetsov odd failure where the content test is reporting failure, but the actual output seems to contain what we were expecting (https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/2943/console):

```
FAILURE after 0.857s: test/cmd/router.sh:36: executing 'oadm router --dry-run --host-network=false -o yaml' expecting failure and text 'containerPort: 80': the output content test failed
Standard output from the command:
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: router
- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    name: router-router-role
  roleRef:
    kind: ClusterRole
    name: system:router
  subjects:
  - kind: ServiceAccount
    name: router
    namespace: cmd-router
  userNames:
  - system:serviceaccount:cmd-router:router
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      router: router
    name: router
  spec:
    replicas: 1
    selector:
      router: router
    strategy:
      resources: {}
      rollingParams:
        maxSurge: 0
        maxUnavailable: 25%
        updatePercent: -25
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          router: router
      spec:
        containers:
        - env:
          - name: ROUTER_EXTERNAL_HOST_HOSTNAME
          - name: ROUTER_EXTERNAL_HOST_HTTPS_VSERVER
          - name: ROUTER_EXTERNAL_HOST_HTTP_VSERVER
          - name: ROUTER_EXTERNAL_HOST_INSECURE
            value: "false"
          - name: ROUTER_EXTERNAL_HOST_PARTITION_PATH
          - name: ROUTER_EXTERNAL_HOST_PASSWORD
          - name: ROUTER_EXTERNAL_HOST_PRIVKEY
            value: /etc/secret-volume/router.pem
          - name: ROUTER_EXTERNAL_HOST_USERNAME
          - name: ROUTER_SERVICE_HTTPS_PORT
            value: "443"
          - name: ROUTER_SERVICE_HTTP_PORT
            value: "80"
          - name: ROUTER_SERVICE_NAME
            value: router
          - name: ROUTER_SERVICE_NAMESPACE
            value: cmd-router
          - name: ROUTER_SUBDOMAIN
          - name: STATS_PASSWORD
            value: kTqAYwiyJG
          - name: STATS_PORT
            value: "1936"
          - name: STATS_USERNAME
            value: admin
          image: openshift/origin-haproxy-router:v1.3.0-alpha.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1936
            initialDelaySeconds: 10
          name: router
          ports:
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
          - containerPort: 1936
            hostPort: 1936
            name: stats
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1936
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        securityContext: {}
        serviceAccount: router
        serviceAccountName: router
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      router: router
    name: router
  spec:
    ports:
    - name: 80-tcp
      port: 80
      targetPort: 80
    - name: 443-tcp
      port: 443
      targetPort: 443
    - name: 1936-tcp
      port: 1936
      protocol: TCP
      targetPort: 1936
    selector:
      router: router
  status:
    loadBalancer: {}
kind: List
metadata: {}

Standard error from the command:
error: router could not be created; service account "router" is not allowed to access host ports on nodes, grant access with oadm policy add-scc-to-user hostnetwork -z router
```

**Comment by kargakis** [comment] 2016-07-07 13:08
Dupe of https://github.com/openshift/origin/issues/9129?

**Comment by stevekuznetsov** [comment] 2016-07-07 13:32
@liggitt yeah, #9371 tracks that -- there *was* a failure, we're just printing the wrong cause for it

**Comment by stevekuznetsov** [comment] 2016-07-07 13:40
#9371 has been renamed since the flake I saw that made me open it was actually the same as this ... it's very interesting that we seem to only be hitting it with these router tests... is there something weird about the yaml? We're doing a `grep -Eq` on the files containing `std{err,out}` from the command, so perhaps there's some weird encoding / hidden char something going on? 

I'm pretty sure this is a dupe of #9371 now

**Closed by stevekuznetsov** 2016-07-07 13:40 UTC
Labels: component/routing, kind/test-flake, priority/P2
