### ISSUE TITLE
Issues with control plane on fresh deployment

### ISSUE THREAD

**Issue by shaunmp** [openshift/origin#21639] opened 2018-12-10 10:44 UTC
Hi All, 

On a fresh install of OKD v3.11 - on CentOS 7.6.1810 - it appears each master/etcd node has three failing pods (see screenshot of one node below). 

In my installation, I did install CRI-O using the following inventory variables:

openshift_use_crio=True
openshift_crio_enable_docker_gc=True

![image](https://user-images.githubusercontent.com/6645109/49727264-e411e380-fcc3-11e8-9aff-bb5b0c8796ea.png)

Each pod is failing for similar reasons, trying to bind to a port already in use:

ie:
F1210 10:38:49.663529       1 start_api.go:68] failed to create listener: failed to listen on 0.0.0.0:8443: listen tcp4 0.0.0.0:8443: bind: address already in use

or

2018-12-10 10:39:03.914874 C | etcdmain: listen tcp 192.168.25.21:2380: bind: address already in use

I'm not familiar with CRI-O (hence this lab deployment) and checking crictl ps returns this:

[root@master-01 ~]# crictl ps
W1210 21:41:38.234986    1535 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
FATA[0000] listing containers failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable

runc list shows multiple pods running through:

[root@master-01 ~]# runc list
ID                                                                 PID         STATUS      BUNDLE                                                                                                                 CREATED                          OWNER
37dc815b84453ee475a2486f4e8944fef575a12f71b299dd2b99a1ca6a3084c8   9416        running     /run/containers/storage/overlay-containers/37dc815b84453ee475a2486f4e8944fef575a12f71b299dd2b99a1ca6a3084c8/userdata   2018-12-10T08:57:07.45622029Z    root
...
...

Note though, the cluster appears to be otherwise working fine. No issues as far as I've found and cluster health is marked healthy/all nodes ready. 

Cluster has 3 master nodes with colocated etcd. 

##### Version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0

**Comment by shaunmp** [comment] 2018-12-11 10:56
That crictl ps issue was only one the one master, looks like the .sock file had vanished. Restarting crio succeeded (in returning correct output, not the overall issue).

**Comment by imcsk8** [comment] 2019-01-16 00:10
It seems like the problem didn't persist, can i close this issue?

**Comment by shaunmp** [comment] 2019-01-22 09:15
Sorry, to clarify, the: 
[root@master-01 ~]# crictl ps
W1210 21:41:38.234986 1535 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
FATA[0000] listing containers failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable

issue can be ignored. The control plane pods still being stuck in CrashLoopBackOff is still occuring.

**Comment by sdodsley** [comment] 2019-03-28 19:28
I am seeing a similar issue with OpenShift 3.11 on RHEL 7.6. 
What is the resolution?

**Comment by shaunmp** [comment] 2019-03-28 20:15
I never fixed the issue itself, unfortunately. I did get around it by simply uninstalling cri-o on each of the hosts, after which it appeared to work without issue.

**Comment by sdodsley** [comment] 2019-03-28 20:25
Sadly I want to use CRI-O so I sort of need to work out the root cause. Oh well. More digging to do unless anyone else here can shed some light...

**Closed** 2019-08-25 23:58 UTC
Labels: lifecycle/rotten
