### ISSUE TITLE
Starting origin server breaks with unable to read certificate-authority

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#11520] opened 2016-10-24 11:02 UTC
This error is somehow random but it started to happen on master today (24/Oct) and it worked without any problems three days ago.

Basically, I use this command to write master config:

```
$   openshift start --public-master=https://${ip}:8443 --etcd-dir=/tmp/etcd  --latest-images \
    --write-config=openshift.local.config \
    --loglevel=10 \
    --create-certs \
    --volume-dir=volumes "$@" &> server-config.log
```

For a 'master' branch, this exits with:

```
error: unable to read certificate-authority /var/lib/openshift/openshift.local.config/master/ca.crt for 192-168-64-3:8443 due to open /var/lib/openshift/openshift.local.config/master/ca.crt: no such file or directory
```

Note, that ` /var/lib/openshift` directory exists and I have all rights to write to it. Also the `openshift.local.config/master` directory does not exists at all (that command used to create it).

The box base OS is Centos7, the Go version is 1.7.3 (but 1.7.1 gave me same behavior). 
I tried to go back in history, but the behavior seems to be either random or I'm starting to be crazy, because it worked for commits 3-4 days ago and then when I tried to make clean build again on that commit it breaks again.

**Comment by mfojtik** [comment] 2016-10-24 12:12
OK, I found what is causing this. Before the existence of old `/root/.kube` directory did not prevented  `openshift start --write-config` to succeed. But somehow, it does now. That directory needs to be removed when starting a new server. 

I think this might be related to change of TLS version required where the certificate in /root/.kube pointed/has old version.

**Comment by liggitt** [comment] 2016-10-24 12:26
TLS version has nothing to do with cert files on disk

**Comment by liggitt** [comment] 2016-10-24 12:30
possibly related to https://github.com/openshift/origin/issues/11513 constructing clients in command setup

**Comment by mfojtik** [comment] 2016-10-24 12:34
@liggitt I was blaming TLS because that looked like the only "suspicious" change since Friday.

**Comment by mfojtik** [comment] 2016-10-24 12:51
@fabianofranz feel free to close this as dupe if you think it is duplicate.

**Comment by fabianofranz** [comment] 2016-10-24 13:35
@mfojtik can you check if https://github.com/openshift/origin/pull/11525 fixes it?

**Comment by mfojtik** [comment] 2016-10-24 14:12
@fabianofranz fixed. thanks!

**Comment by fabianofranz** [comment] 2016-10-24 14:36
Dupe of https://github.com/openshift/origin/issues/11513.

**Closed by fabianofranz** 2016-10-24 14:36 UTC
Labels: priority/P3
