### ISSUE TITLE
oc delete all --all didn't

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17411] opened 2017-11-21 17:02 UTC
Tried to run oc delete all --all, it used to delete services, no longer does.  On 3.7 GA, cleared cache and tried again, got this list:

```
I1121 12:01:01.121968   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/oapi/v1/namespaces/openshift-devops-monitor/buildconfigs?includeUninitialized=true 200 OK in 108 milliseconds
I1121 12:01:01.152870   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/oapi/v1/namespaces/openshift-devops-monitor/builds?includeUninitialized=true 200 OK in 30 milliseconds
I1121 12:01:01.187394   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/oapi/v1/namespaces/openshift-devops-monitor/imagestreams?includeUninitialized=true 200 OK in 34 milliseconds
I1121 12:01:01.221588   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/oapi/v1/namespaces/openshift-devops-monitor/deploymentconfigs?includeUninitialized=true 200 OK in 33 milliseconds
I1121 12:01:01.251014   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/oapi/v1/namespaces/openshift-devops-monitor/routes?includeUninitialized=true 200 OK in 29 milliseconds
I1121 12:01:01.282229   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/extensions/v1beta1/namespaces/openshift-devops-monitor/deployments?includeUninitialized=true 200 OK in 31 milliseconds
I1121 12:01:01.311499   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/extensions/v1beta1/namespaces/openshift-devops-monitor/replicasets?includeUninitialized=true 200 OK in 29 milliseconds
I1121 12:01:01.343239   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/apps/v1beta1/namespaces/openshift-devops-monitor/deployments?includeUninitialized=true 200 OK in 31 milliseconds
I1121 12:01:01.374212   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/apps/v1beta1/namespaces/openshift-devops-monitor/statefulsets?includeUninitialized=true 200 OK in 30 milliseconds
I1121 12:01:01.482545   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/autoscaling/v1/namespaces/openshift-devops-monitor/horizontalpodautoscalers?includeUninitialized=true 200 OK in 108 milliseconds
I1121 12:01:01.517479   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/batch/v1/namespaces/openshift-devops-monitor/jobs?includeUninitialized=true 200 OK in 34 milliseconds
I1121 12:01:01.547597   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/batch/v2alpha1/namespaces/openshift-devops-monitor/cronjobs?includeUninitialized=true 200 OK in 29 milliseconds
I1121 12:01:01.578669   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/batch/v2alpha1/namespaces/openshift-devops-monitor/scheduledjobs?includeUninitialized=true 200 OK in 30 milliseconds
I1121 12:01:01.608176   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/apps.openshift.io/v1/namespaces/openshift-devops-monitor/deploymentconfigs?includeUninitialized=true 200 OK in 29 milliseconds
I1121 12:01:01.647689   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/build.openshift.io/v1/namespaces/openshift-devops-monitor/buildconfigs?includeUninitialized=true 200 OK in 39 milliseconds
I1121 12:01:03.171952   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/build.openshift.io/v1/namespaces/openshift-devops-monitor/builds?includeUninitialized=true 200 OK in 1524 milliseconds
I1121 12:01:03.920046   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/image.openshift.io/v1/namespaces/openshift-devops-monitor/imagestreams?includeUninitialized=true 200 OK in 747 milliseconds
I1121 12:01:03.996908   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/apis/route.openshift.io/v1/namespaces/openshift-devops-monitor/routes?includeUninitialized=true 200 OK in 76 milliseconds
I1121 12:01:04.028279   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/api/v1/namespaces/openshift-devops-monitor/pods?includeUninitialized=true 200 OK in 31 milliseconds
I1121 12:01:04.065654   27066 round_trippers.go:436] GET https://api.starter-us-east-1.openshift.com:443/api/v1/namespaces/openshift-devops-monitor/replicationcontrollers?includeUninitialized=true 200 OK in 37 milliseconds
```

At minimum it's missing services.

**Comment by smarterclayton** [comment] 2017-11-21 17:03
This is master oc against 3.7 server, not sure if it's broken in GA oc.  @fabianofranz

**Comment by fabianofranz** [comment] 2017-11-21 18:28
I confirmed it fails with master `oc` and not in 3.7 `oc`.

**Comment by smarterclayton** [comment] 2017-11-22 01:16
Dropping priority, although it's would still obviously be must fix for 3.8

**Comment by fabianofranz** [comment] 2017-11-22 02:49
@smarterclayton fix is here: https://github.com/openshift/ose/pull/931

**Comment by mfojtik** [comment] 2017-11-23 09:24
@fabianofranz are you going to fix this in master as well?

**Comment by fabianofranz** [comment] 2017-11-24 19:53
> @fabianofranz are you going to fix this in master as well?

@mfojtik Master doesn't need it since this is already in the latest rebase. I opened it for `release-3.7` in origin: https://github.com/openshift/origin/pull/17454.

**Comment by fabianofranz** [comment] 2017-11-24 19:55
So

https://github.com/openshift/ose/pull/931 OSE fix
https://github.com/openshift/origin/pull/17454 origin fix

Feel free to close if we're maintaining a release in only one instead of both repos.

**Comment by fabianofranz** [comment] 2017-12-05 20:27
Fixed in Origin and OSE by the 2 PR's linked.

**Closed by fabianofranz** 2017-12-05 20:27 UTC
Labels: component/cli, priority/P2, sig/master
