### ISSUE TITLE
Build cancelled when pod is not created never goes into cancelled

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1596] opened 2015-04-06 01:30 UTC
Created a build on a mac (no Docker installed, which means pod never runs).  Build goes into running status.  Tried to cancel the build, but the status is not updated.  Pod doesn't exist, so build should be able to be cancelled and go into the cancelled state.

```
 osc get builds sinatra-app-example-1 -o yaml
apiVersion: v1beta1
cancelled: true
kind: Build
metadata:
  creationTimestamp: 2015-04-04T22:11:26Z
  labels:
    buildconfig: sinatra-app-example
  name: sinatra-app-example-1
  namespace: default
  resourceVersion: "29769"
  selfLink: /osapi/v1beta1/builds/sinatra-app-example-1?namespace=default
  uid: 89923a3a-db17-11e4-adc0-7831c1b76042
parameters:
  output:
    to:
      kind: ImageStream
      name: sinatra-app-example
  source:
    git:
      uri: git://github.com/mfojtik/sinatra-app-example
    type: Git
  strategy:
    stiStrategy:
      builderImage: openshift/ruby-20-centos7
      clean: true
      image: openshift/ruby-20-centos7
    type: STI
startTimestamp: 2015-04-04T22:11:31Z
status: Running
```

Pod has been deleted at this point.

**Comment by soltysh** [comment] 2015-04-07 14:24
I just tried to reproduce that, but I just stopped docker service. It worked without any problems, the build was canceled. Can you try that once again?

**Comment by danmcp** [comment] 2015-05-11 21:14
Closing due to age without prejudice.

**Closed by danmcp** 2015-05-11 21:14 UTC
Labels: component/build, kind/bug, priority/P2
