### ISSUE TITLE
test/end-to-end/core.sh:385: executing oc get pods -l openshift.io/deployer-pod.type=hook-post

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#13097] opened 2017-02-24 10:07 UTC
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration_future/519/consoleFull:

```
18:37:59 Standard error from the command:
18:37:59 Running test/end-to-end/core.sh:385: executing 'oc get pods -l openshift.io/deployer-pod.type=hook-post -o jsonpath={.items[*].status.phase}' expecting any result and text '^Succeeded$'; re-trying every 0.2s until completion or 60.000s...
18:38:59 
FAILURE after 59.438s: test/end-to-end/core.sh:385: executing 'oc get pods -l openshift.io/deployer-pod.type=hook-post -o jsonpath={.items[*].status.phase}' expecting any result and text '^Succeeded$'; re-trying every 0.2s until completion or 60.000s: the command timed out
18:38:59 Standard output from the command:
18:38:59 Pending
18:38:59 ... repeated 62 times
18:38:59 Standard error from the command:
18:38:59 No resources found.
18:38:59 ... repeated 89 times
18:38:59 
[ERROR] PID 32407: hack/lib/cmd.sh:618: `return "${return_code}"` exited with status 1.
```

Though, I wonder if this is related to #11016, @mfojtik wdyt?

**Comment by stevekuznetsov** [comment] 2017-02-25 19:29
Saw this on a different container in e2e -- #11016 may be the culprit, not sure it has anything to do with which specific container failed.

**Comment by mfojtik** [comment] 2017-02-27 09:11
Seems like timeout when starting the deployer pod which can be related to docker slowness. I want to hunt down these cases for 1.6, I don't think this should block 1.5 release.

**Comment by mfojtik** [comment] 2017-03-24 09:42
@soltysh 27 days since this happened last time... I'm bumping this to P2, but wonder if we can just close it as there seems to be no reproducers recently.

**Comment by soltysh** [comment] 2017-03-24 12:38
@mfojtik it didn't happen, b/c it's [explicitly disabled](https://github.com/openshift/origin/blob/367a8d337f89f63ade38bdb49026468eae6c7c5c/test/end-to-end/core.sh#L381-L404) it even has my nick in it 😉 But fix is in flight, and this needs to be addressed asap, so I'm back with priority.

**Comment by soltysh** [comment] 2017-03-24 12:39
My bad, ignore my last comment, that's wrong issue, sorry for the noise.

**Comment by mfojtik** [comment] 2017-07-12 09:52
Closing due to age.

**Closed by mfojtik** 2017-07-12 09:52 UTC
Labels: component/deployments, kind/test-flake, priority/P2
