### ISSUE TITLE
Test failure for all scheduling predicates tests

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13553] opened 2017-03-28 09:19 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/658/#showFailuresLink

**Comment by stevekuznetsov** [comment] 2017-03-29 01:43
This is usually namespace termination problems on the serial stuff... I thought we had an issue around here somewhere for it

```
Mar 27 18:24:17.955: INFO: Waiting for terminating namespaces to be deleted...
Mar 27 18:24:17.957: INFO: Unexpected error occurred: Namespace e2e-tests-init-container-hx6md is active
```

**Comment by stevekuznetsov** [comment] 2017-03-29 01:45
dupe of https://github.com/openshift/origin/issues/13536

**Closed by stevekuznetsov** 2017-03-29 01:45 UTC
Labels: area/tests, kind/test-flake, priority/P2
