### ISSUE TITLE
Can't sync imagestreamtag with docker hub image tag 

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin#3980] opened 2015-08-03 08:25 UTC
Use-case:
After add some tags on dockerhub I can use "oc import-image" to sync the tag in imagestream. But when delete some tags on dockerhub the tags can't be deleted in imagestream.

**Comment by ncdc** [comment] 2015-08-24 20:28
Importing is a one-way import; it's not a two-way sync, and it's only additive. #3485 is the issue for being able to delete image stream tags.

**Comment by pweil-** [comment] 2015-10-05 13:15
Closing as dupe of https://github.com/openshift/origin/issues/3980 which will add delete ability.

**Closed by pweil-** 2015-10-05 13:15 UTC
Labels: component/imageregistry, priority/P2
