### ISSUE TITLE
conformance test flake

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#9850] opened 2016-07-14 13:45 UTC
I can't actually tell what flaked. It's in the conformance test. My change is to delete something in docs so I'm pretty sure it's not the PR.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3427/console

```
[ERROR] PID 24763: test/extended/conformance.sh:63: `return $out` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/extended/conformance.sh:63: `return $out`
[INFO]   Exiting with code 1.
```

**Comment by kargakis** [comment] 2016-07-15 22:36
Dupe of https://github.com/openshift/origin/issues/8427

**Closed by kargakis** 2016-07-15 22:36 UTC
Labels: kind/test-flake, priority/P2
