### ISSUE TITLE
flake: timeout in hack/test-go.sh

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#7734] opened 2016-03-02 14:23 UTC
Seen in https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5167/console:

```
ok  	github.com/openshift/origin/pkg/cmd/recycle	0.102s	coverage: 69.6% of statements
panic: test timed out after 1m0s

goroutine 28 [running]:
testing.func·008()
	/usr/lib/golang/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive]:
testing.RunTests(0x1a2cc90, 0x21599e0, 0x2, 0x2, 0xc20805b901)
	/usr/lib/golang/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208051ea0, 0x2b10420)
	/usr/lib/golang/src/testing/testing.go:485 +0xe1
main.main()
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_testmain.go:134 +0x382

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x2b04920)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x99
created by github.com/golang/glog.init·1
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ca

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [syscall, 1 minutes]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x43

goroutine 27 [runnable]:
math/big.nat.norm(0xc208075040, 0x20, 0x25, 0xc2080aaa20, 0x10, 0x24)
	/usr/lib/golang/src/math/big/nat.go:61
math/big.nat.mul(0xc208075040, 0x20, 0x25, 0xc2080aaa20, 0x10, 0x24, 0xc2080aaa20, 0x10, 0x24, 0x0, ...)
	/usr/lib/golang/src/math/big/nat.go:402 +0x4da
math/big.nat.expNNWindowed(0xc2080aaa20, 0x10, 0x24, 0xc2083723c0, 0x10, 0x14, 0xc208372280, 0x10, 0x14, 0xc208372000, ...)
	/usr/lib/golang/src/math/big/nat.go:1359 +0xf10
math/big.nat.expNN(0xc208372460, 0x10, 0x14, 0xc2083723c0, 0x10, 0x14, 0xc208372280, 0x10, 0x14, 0xc208372000, ...)
	/usr/lib/golang/src/math/big/nat.go:1260 +0x4f1
math/big.nat.probablyPrime(0xc208372000, 0x10, 0x14, 0x14, 0x5)
	/usr/lib/golang/src/math/big/nat.go:1445 +0x9d4
math/big.(*Int).ProbablyPrime(0xc2083da000, 0x14, 0xc20800a920)
	/usr/lib/golang/src/math/big/int.go:741 +0x7c
crypto/rand.Prime(0x7fa6110da4f8, 0xc20803d590, 0x400, 0xc2083da000, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rand/util.go:99 +0x654
crypto/rsa.GenerateMultiPrimeKey(0x7fa6110da4f8, 0xc20803d590, 0x2, 0x800, 0xc208224ea0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:187 +0x2c9
crypto/rsa.GenerateKey(0x7fa6110da4f8, 0xc20803d590, 0x800, 0xc208426c90, 0x0, 0x0)
	/usr/lib/golang/src/crypto/rsa/rsa.go:145 +0x65
github.com/openshift/origin/pkg/cmd/server/crypto.NewKeyPair(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:344 +0xa6
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).MakeServerCert(0xc20825e840, 0xc2084255f0, 0x29, 0xc208425650, 0x29, 0xc20825e780, 0x7fa6110dce68, 0x0, 0x0)
	/data/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:251 +0x22d
github.com/openshift/origin/pkg/cmd/server/crypto.(*CA).EnsureServerCert(0xc20825e840, 0xc2084255f0, 0x29, 0xc208425650, 0x29, 0xc20825e780, 0x46d37c, 0x4adf70, 0x0, 0x0)
	/data/src/github.com/openshift/origin/pkg/cmd/server/crypto/crypto.go:223 +0xe5
github.com/openshift/origin/pkg/cmd/server/admin.CreateServerCertOptions.CreateServerCert(0xc208354f40, 0xc2084255f0, 0x29, 0xc208425650, 0x29, 0xc208427630, 0x1, 0x1, 0x0, 0x7fa6110da130, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_servercert.go:143 +0x756
github.com/openshift/origin/pkg/cmd/server/admin.CreateNodeConfigOptions.MakeServerCert(0xc208354f40, 0xc20842502b, 0x1e, 0x1697e37, 0x7, 0xc208427630, 0x1, 0x1, 0x1748030, 0x17, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:387 +0x235
github.com/openshift/origin/pkg/cmd/server/admin.CreateNodeConfigOptions.CreateNodeFolder(0xc208354f40, 0xc20842502b, 0x1e, 0x1697e37, 0x7, 0xc208427630, 0x1, 0x1, 0x1748030, 0x17, ...)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:286 +0x62a
github.com/openshift/origin/pkg/cmd/server/admin.func·015(0xc208077200, 0xc2084c0480, 0x0, 0x9)
	github.com/openshift/origin/pkg/cmd/server/admin/_test/_obj_test/create_nodeconfig.go:74 +0x221
github.com/spf13/cobra.(*Command).execute(0xc208077200, 0xc2084c02d0, 0x9, 0x9, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0xb41
github.com/spf13/cobra.(*Command).ExecuteC(0xc208076000, 0xc208077200, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x635
github.com/spf13/cobra.(*Command).Execute(0xc208076000, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x48
github.com/openshift/origin/pkg/cmd/server/admin.executeNodeConfig(0xc20837de58, 0x8, 0x8, 0x0, 0x0)
	/data/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:111 +0x721
github.com/openshift/origin/pkg/cmd/server/admin.TestNodeConfigTLS(0xc208067710)
	/data/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:49 +0x402
testing.tRunner(0xc208067710, 0x21599f8)
	/usr/lib/golang/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:555 +0xd4e
FAIL	github.com/openshift/origin/pkg/cmd/server/admin	60.611s
```

**Comment by kargakis** [comment] 2016-03-02 15:33
Relevant issues involving that package: https://github.com/openshift/origin/issues/6176, https://github.com/openshift/origin/issues/6801

**Comment by liggitt** [comment] 2016-03-02 15:34
dupe of https://github.com/openshift/origin/issues/6801

**Closed** 2016-03-02 15:35 UTC
Labels: area/tests, kind/test-flake, priority/P2
