### ISSUE TITLE
Error messages from ACL are really, really confusing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13445] opened 2017-03-19 19:56 UTC
```
$ oc project myproject
Already on project "myproject" on server "https://10.1.2.2:8443".
$ oc new-build -D $'FROM centos:centos7\nCMD /bin/sleep\n' test
--> Found Docker image be5b4a9 (3 days old) from Docker Hub for "centos:centos7"

    * An image stream will be created as "centos:centos7" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "origin:latest"
      * Every time "centos:centos7" changes a new build will be triggered

--> Creating resources with label build=origin ...
    error: User "developer" cannot create image.openshift.io.imagestreams in project "default"
    error: User "developer" cannot create image.openshift.io.imagestreams in project "default"
    error: User "developer" cannot create build.openshift.io.buildconfigs in project "default"
--> Failed
```

That isn't right at all.  

@mfojtik @bparees

**Comment by smarterclayton** [comment] 2017-03-19 19:57
Also, that error is pretty terrible.

**Comment by smarterclayton** [comment] 2017-03-19 19:58
From a brand new oc cluster up.

**Comment by mfojtik** [comment] 2017-03-19 19:59
@smarterclayton why it is creating imagestreams and buildconfigs in project "default"?

**Comment by smarterclayton** [comment] 2017-03-19 19:59
That's the bug - it looks like it isn't recognizing those resources as being namespaced, possibly.

**Comment by mfojtik** [comment] 2017-03-19 20:01
@smarterclayton i doubt that something like that will pass the tests, also I don't think it is really hitting the "/apis" endpoint (`oc` still use the legacy client).

agree on the error is terrible, I will try to fix the source of it.

**Comment by smarterclayton** [comment] 2017-03-19 20:02
oc is not using the legacy client here - with `--loglevel=8`:

```
I0319 16:01:42.833320   84936 request.go:559] Request Body: "{\"kind\":\"ImageStream\",\"apiVersion\":\"image.openshift.io/v1\",\"metadata\":{\"name\":\"centos\",\"creationTimestamp\":null,\"labels\":{\"build\":\"origin\"},\"annotations\":{\"openshift.io/generated-by\":\"OpenShiftNewBuild\"}},\"spec\":{\"dockerImageRepository\":\"centos\"},\"status\":{\"dockerImageRepository\":\"\"}}\n"
I0319 16:01:42.833354   84936 round_trippers.go:296] POST https://10.1.2.2:8443/apis/image.openshift.io/v1/namespaces/default/imagestreams
```

**Comment by mfojtik** [comment] 2017-03-19 20:03
interesting, must be discovery...

**Comment by smarterclayton** [comment] 2017-03-19 20:06
I think the problem is the `test` argument being interpreted as a directory, and somehow deciding to create things in default.  That's a ben problem.

If you can look at making that message better in a separate issue I would appreciate it - it's pretty confusing and I know what it's trying to tell me.

**Comment by mfojtik** [comment] 2017-03-19 20:08
@smarterclayton there are many places where the messages contain the API group... i can sweep them all the try to fix or we can put some fix in upstream. We discussed with @sttts that something like "HumanName()" used in all errors reported (404, etc.) would make the messages much nicer...

**Comment by smarterclayton** [comment] 2017-03-19 20:08
Hrm, no, that's not it.  This is really weird.  oc cluster up vs a GCE cluster behave differently.

**Comment by smarterclayton** [comment] 2017-03-19 20:09
@mfojtik the order alone is really confusing - builds.....buildconfigs.

**Comment by smarterclayton** [comment] 2017-03-19 20:09
Well, new-build is broken somehow.

**Comment by mfojtik** [comment] 2017-03-19 20:10
@smarterclayton what images you use? openshift/origin:v1.5.0-alpha.3 ?

**Comment by smarterclayton** [comment] 2017-03-19 20:10
BAH.  Never mind, it was environment variables set that caused in-cluster config to be used.  That's fixed.

**Comment by smarterclayton** [comment] 2017-03-19 20:10
Repurposing this to just be the error messages.

**Comment by mfojtik** [comment] 2017-03-19 20:12
@smarterclayton 

https://github.com/mfojtik/origin/blob/4ee21451a56f70b258967fa9c222c9779e94be15/pkg/authorization/authorizer/messages.go#L34

this explains the api group prefix instead of suffix.

**Comment by smarterclayton** [comment] 2017-03-19 20:15
```
oc get build test-1-build -o yaml
Error from server (NotFound): builds.build.openshift.io "test-1-build" not found
```

Yeah this is better ^

**Comment by enj** [comment] 2017-03-20 11:42
Duplicate of #13155

**Closed** 2017-03-23 10:21 UTC
Labels: area/usability, priority/P2
