### ISSUE TITLE
oc export does not respect imagestreams original source

### ISSUE THREAD

**Issue by ThomasSteinbach** [openshift/origin#16531] opened 2017-09-25 11:53 UTC
The YAML export of an image stream replaces the source URL of the external registry by the URL of the internal registry. Thus images won't be pulled correctly after importing the export on another OpenShift cluster.

##### Version

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-10-52-101-57.eu-central-1.compute.internal:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. create imgestream from external repository
2. `oc export is -o yaml > export.yaml`

##### Current Result

The exported imagestream points to the internal registry:

```
- kind: ImageStream
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: <external-registry>/my/image:17.08
      from:
        kind: DockerImage
        name: <internal-registry>:5000/my/image:17.08
```

##### Expected Result

The exported imagestreams should point to the original external registry:

```
- kind: ImageStream
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: <external-registry>/my/image:17.08
      from:
        kind: DockerImage
        name: <external-registry>/my/image:17.08
```

**Comment by bparees** [comment] 2017-09-25 18:59
Can I see the original imagestream definition you used to create this IS?

**Comment by ThomasSteinbach** [comment] 2017-09-26 07:28
The image stream was automatically created when creating a new app with

`oc new-app dockerhub.replaced.domain.org/myproject/myimage:17.08`

Here the image stream yaml when editing the existing image stream:

```
apiVersion: v1
kind: ImageStream
metadata:
  name: myimage
  namespace: myproject
  selfLink: /oapi/v1/namespaces/myproject/imagestreams/myimage
  uid: e45f3191-8429-11e7-9588-0631305206e3
  resourceVersion: '733706'
  generation: 5
  creationTimestamp: '2017-08-18T15:28:31Z'
  labels:
    app: myimage
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: '2017-09-25T13:08:08Z'
spec:
  tags:
    - name: '17.08'
      annotations:
        openshift.io/imported-from: 'dockerhub.replaced.domain.org/myproject/myimage:17.08'
      from:
        kind: DockerImage
        name: 'dockerhub.replaced.domain.org/myproject/myimage:17.08'
      generation: 5
      importPolicy: {}
      referencePolicy:
        type: Source
status:
  dockerImageRepository: '172.30.253.134:5000/myproject/myimage'
  tags:
    - tag: '17.08'
      items:
        - created: '2017-09-25T13:08:08Z'
          dockerImageReference: >-
            dockerhub.replaced.domain.org/myproject/myimage@sha256:c77de78a89cee4a61993e6dc04ad894defe7f8596e9eedb686e2097aeb79da23
          image: >-
            sha256:c77de78a89cee4a61993e6dc04ad894defe7f8596e9eedb686e2097aeb79da23
          generation: 5
        - created: '2017-08-30T09:38:32Z'
          dockerImageReference: >-
            dockerhub.replaced.domain.org/myproject/myimage@sha256:5ad3b462e649dd9d44bd8cc96e463796e6d70ef12ceb378099f00506d2eb25af
          image: >-
            sha256:5ad3b462e649dd9d44bd8cc96e463796e6d70ef12ceb378099f00506d2eb25af
          generation: 4
        - created: '2017-08-23T13:27:34Z'
          dockerImageReference: >-
            dockerhub.replaced.domain.org/myproject/myimage@sha256:1fdd7fbbbf51d2e45fbe43bb3d3b2d56bb1e601b7d2cfd662852edf3b6e6cbe2
          image: >-
            sha256:1fdd7fbbbf51d2e45fbe43bb3d3b2d56bb1e601b7d2cfd662852edf3b6e6cbe2
          generation: 3
        - created: '2017-08-18T15:28:32Z'
          dockerImageReference: >-
            dockerhub.replaced.domain.org/myproject/myimage@sha256:66751ea7041f0745705a7ea738a27fbe6734415f098a5c676e2a171d1c0dbe89
          image: >-
            sha256:66751ea7041f0745705a7ea738a27fbe6734415f098a5c676e2a171d1c0dbe89
          generation: 2
```

**Comment by bparees** [comment] 2017-09-26 15:23
Thanks, I agree that it makes no sense for export to change the value.  @soltysh was there an intention behind this behavior?

**Comment by soltysh** [comment] 2017-09-28 10:54
Yes it's intended, see https://github.com/openshift/origin/issues/15492#issuecomment-319630623. I'm closing this as a duplicate of that.

**Comment by ThomasSteinbach** [comment] 2017-09-28 11:18
I think I have not understand the reasoning, why the external repository URL becomes replaced by the internal repository URL. If another admin in my company is importing my exported project, how did he get to know where to retrieve the images from? I cannot see that the current behavior will avoid more problems than it leads to confusion. Could you please clarify for me how another admin would proceed when importing/using the export? Thanx in advance.

**Comment by soltysh** [comment] 2017-09-28 14:39
The problem is portability, when you export image we assume you want to point to a particular image the IS is currently pointing to, this not necessarily can be the latest image the spec is pointing to. For that export will contain the pull spec pointing to internal registry so that the remote end could read exactly the same metadata. But for that you need to either expose the internal docker registry so it's reachable by the other cluster or eventually you can use `oc get -o yaml` instead to get the exact definition you want to.

**Comment by ThomasSteinbach** [comment] 2017-09-28 15:28
> we assume you want to point to a particular image the IS is currently pointing to, this not necessarily can be the latest image the spec is pointing to

Pointing to an exact build of an image sound like a good idea. Especially as the ImageStream caches old builds from the external registry.

However isn't there a better solution which preserves the exact build the IS is pointing to as well as the external registry? I don't know if it is technically possible to retrieve builds from an external docker registry which tags have changed meanwhile.

**Comment by bparees** [comment] 2017-09-28 15:57
+1, @soltysh your referenced comment talks about the case where the imagestreamtags are created as a result of a push to the internal registry, but that's not the case here, this is an imagestreamtag that's defined as a reference to an external registry.  Why, when exporting it, would we change what it references?

**Comment by soltysh** [comment] 2017-09-29 09:20
> Why, when exporting it, would we change what it references?

You want to make sure you use the exact same reference of an image. I've published A.1 on some external registry, and created an IS using it. In the mean time, I've pushed some changes, so now A.2 is available, but IS is still pointing to A.1. I do export with spec pointing to A, and import it on 2nd cluster, which actually imports A.2, because that's the current available one. You might end up with a broken application, because the changes between A.1 and A.2 are significant. Now, you might start wonder why there are differences, what has happened, etcd. We want to save you that pain using the status, not spec. If you want spec, do `oc get is -o yaml`, like I said before.

**Comment by bparees** [comment] 2017-10-02 19:06
> We want to save you that pain using the status,

You haven't saved me any pain because now you've given me an IS that can't possibly work in my second cluster because it's referencing an internal ip address of my first cluster.

**Comment by soltysh** [comment] 2017-10-03 11:59
Hmmm... none of the approaches is ideal, to be honest. We went with this one as a convenience, but I feel the other options has similar pros and cons as this one.

**Comment by bparees** [comment] 2017-10-03 13:56
> Hmmm... none of the approaches is ideal, to be honest. We went with this one as a convenience, but I feel the other options has similar pros and cons as this one.

Yeah, well that's why i reopened the issue  :)  Seems like we need to think about it some more.  We've been having other discussions around resource export behavior as well, @csrwng probably has some opinions.

**Comment by csrwng** [comment] 2017-10-03 14:24
sorry closed by mistake :)
Exporting the reference to the internal registry seems of very limited use to me. It would make sense if we exported the actual binary for the image (as I would like for us to do when exporting for backup/copy). But other than that, maybe it should contain the reference only if there's a public registry endpoint configured?

**Comment by bparees** [comment] 2018-01-19 23:22
part of https://trello.com/c/wGB9TRJS

**Closed by bparees** 2018-01-19 23:22 UTC
Labels: component/cli, component/image, kind/bug, priority/P2
