### ISSUE TITLE
FAILURE after 59.343s: test/end-to-end/core.sh:21: executing 'oc get -n test pods -l name=database' expecting any result and text 'Running'; re-trying every 0.2s until completion or 60.000s: the command timed out

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9767] opened 2016-07-11 12:30 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3091/consoleFull

**Comment by ncdc** [comment] 2016-07-11 16:24
A bit more info in #9775, so I'm closing this one.

**Comment by jsafrane** [comment] 2016-11-18 08:20
I hit this error today: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/8564/console

```
Running test/end-to-end/core.sh:15: executing 'oc get -n test pods -l name=database' expecting any result and text 'Running'; re-trying every 0.2s until completion or 60.000s...
FAILURE after 59.251s: test/end-to-end/core.sh:15: executing 'oc get -n test pods -l name=database' expecting any result and text 'Running'; re-trying every 0.2s until completion or 60.000s: the command timed out
There was no output from the command.
There was no error output from the command.
[ERROR] PID 28467: hack/lib/cmd.sh:603: `return "${return_code}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/cmd.sh:603: `return "${return_code}"`
[INFO] 		  2: test/end-to-end/core.sh:15: os::cmd::try_until_text
[INFO] 		  3: test/end-to-end/core.sh:396: wait_for_app
[INFO]   Exiting with code 1.
```

IMO, the root cause may be different than #9775.

**Closed** 2017-01-23 03:35 UTC
Labels: area/tests, component/deployments, kind/test-flake, priority/P2
