### ISSUE TITLE
extended test output incorrect: should run a deployment to completion and then scale to zero

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12497] opened 2017-01-16 04:58 UTC
https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/57/testReport/junit/(root)/Extended/deploymentconfigs_with_test_deployments__Conformance__should_run_a_deployment_to_completion_and_then_scale_to_zero/

Extended.deploymentconfigs with test deployments [Conformance] should run a deployment to completion and then scale to zero (from (empty))

```
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:285
Expected
    <string>: Flag --latest has been deprecated, use 'oc rollout latest' instead
    Started deployment #3
to contain substring
    <string>: deployment-test-3 up to 1
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:280
```

**Comment by smarterclayton** [comment] 2017-01-16 04:58
@mfojtik

**Comment by ncdc** [comment] 2017-01-16 12:09
I wonder if this is the journald log driver issue

**Comment by mfojtik** [comment] 2017-01-16 15:30
@kargakis this issue itself seems a dupe of https://github.com/openshift/origin/issues/11887

I think @smarterclayton pointing out the `(from (empty))` here, @stevekuznetsov any idea?

**Comment by ncdc** [comment] 2017-01-16 15:38
The reason I asked if this was the journald log driver issue is because if you have a container that is supposed to output something like this:

```
line 1
line 2
line 3
```

and your test expects to see `line 3`, due to a possible race condition in docker's journald logging driver, you might not see `line 3` during `docker logs -f` / `oc logs -f`.

**Comment by smarterclayton** [comment] 2017-01-16 16:03
Not from empty - thats's separate and known.

**Comment by bparees** [comment] 2017-01-21 15:36
closing as dupe of https://github.com/openshift/origin/issues/11887

**Closed by bparees** 2017-01-21 15:36 UTC
Labels: component/deployments, kind/test-flake, priority/P1
