### ISSUE TITLE
curl: (6) Could not resolve host: copr.fedoraproject.org; Name or service not known

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#9388] opened 2016-06-16 19:44 UTC
Identifies problem as "Image build failed"
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2195/

##### Version
```
oc v1.3.0-alpha.0-1069-g7a9be8b-dirty
kubernetes v1.3.0-alpha.3-599-g2746284
```

##### Steps To Reproduce
[test]

##### Current Result
```
curl: (6) Could not resolve host: copr.fedoraproject.org; Name or service not known
!!! Error in hack/build-images.sh:64
	'"${oc}" ex dockerbuild $2 $1' exited with status 1
```

**Comment by stevekuznetsov** [comment] 2016-06-16 19:53
Most likely related to #9379

**Comment by mfojtik** [comment] 2016-06-17 07:20
@stevekuznetsov yes, it is s dupe of that one. closing this.

**Closed by mfojtik** 2016-06-17 07:20 UTC
Labels: area/infrastructure, kind/test-flake
