### ISSUE TITLE
flake: Unable to perform initial IP allocation check

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#7662] opened 2016-02-26 20:30 UTC
Seen in https://github.com/openshift/origin/pull/7581, full log is [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11922/consoleFull):
```
I0226 12:23:40.346034   15960 interface.go:248] Default route transits interface "eth0"
I0226 12:23:40.346171   15960 interface.go:93] Interface eth0 is up
I0226 12:23:40.346242   15960 interface.go:138] Interface "eth0" has 2 addresses :[172.18.12.56/20 fe80::c37:39ff:fecd:3c9b/64].
I0226 12:23:40.346270   15960 interface.go:105] Checking addr  172.18.12.56/20.
I0226 12:23:40.346280   15960 interface.go:114] IP found 172.18.12.56
I0226 12:23:40.346297   15960 interface.go:144] valid IPv4 address for interface "eth0" found as 172.18.12.56.
I0226 12:23:40.346308   15960 interface.go:254] Choosing IP 172.18.12.56 
I0226 12:23:40.346327   15960 master_config.go:222] Will report 172.18.12.56 as public IP address.
I0226 12:23:40.346358   15960 start_master.go:378] Starting master on 127.0.0.1:12000 (unknown)
I0226 12:23:40.346369   15960 start_master.go:379] Public master address is https://127.0.0.1:12000
I0226 12:23:40.346387   15960 start_master.go:383] Using images from "openshift/origin-<component>:"
I0226 12:23:40.347154   15960 run_components.go:189] Using default project node label selector: 
I0226 12:23:40.347395   15960 genericapiserver.go:337] Setting GenericAPIServer service IP to "172.30.0.1" (read-write).
F0226 12:23:45.576909   15960 controller.go:86] Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: error #0: client: etcd member http://127.0.0.1:44914 has no leader
Running TestAuthorizationResourceAccessReview...
```

**Comment by rhcarvalho** [comment] 2016-02-29 17:47
Seen again in #7697, https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12029/console

**Comment by liggitt** [comment] 2016-02-29 19:52
Seen in https://github.com/openshift/origin/pull/7608 https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12033/console

**Comment by liggitt** [comment] 2016-03-01 19:31
seen in https://github.com/openshift/origin/pull/5756 https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12092/console

**Comment by soltysh** [comment] 2016-03-02 09:35
seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12098/console

**Comment by deads2k** [comment] 2016-03-02 12:52
Dupe of https://github.com/openshift/origin/issues/7243 (failed to propose).  See `error #0: client: etcd member http://127.0.0.1:44914 has no leader` and the `etcdhttp: got unexpected response error (etcdserver: request timed out)`.  It's also the first indication on status (https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12092/) including a link to the flake.

**Closed by deads2k** 2016-03-02 12:52 UTC
Labels: kind/test-flake, priority/P2
