### ISSUE TITLE
build-logs for running build tells me "build not found"

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1714] opened 2015-04-13 21:01 UTC
```
[root@ose3-master openshift-ansible]# osc get build -n sinatra
NAME                             TYPE      STATUS    POD
simple-openshift-sinatra-sti-1   STI       Running   simple-openshift-sinatra-sti-1
[root@ose3-master openshift-ansible]# osc build-logs -n sinatra simple-openshift-sinatra-sti-1
Error from server: Build: not found 'simple-openshift-sinatra-sti-1'
```

```
osc version
osc v0.4.3.1
kubernetes v0.14.1-582-gb12d75d
```

**Comment by brenton** [comment] 2015-04-14 13:35
@abhgupta, please excuse the noise.  I thought this was a different issue.

@bparees, any idea who could investigate this?

**Comment by bparees** [comment] 2015-04-14 14:54
@kargakis you've been in this space relatively recently, can you take a look?

**Comment by smarterclayton** [comment] 2015-04-14 21:31
This is a dupe of an existing issue, but started with the last rebase.

**Comment by kargakis** [comment] 2015-04-14 22:03
> @kargakis you've been in this space relatively recently, can you take a look?

Sure, will do tomorrow.

**Comment by kargakis** [comment] 2015-04-15 13:19
Hmm, doesn't seem I can reproduce this in the current master neither with [build-logs](http://pastebin.com/CJj4Xhwt) nor with [start-build --follow](http://pastebin.com/BLuuedUh)

**Comment by smarterclayton** [comment] 2015-04-15 13:24
Try commenting out the set +e I added to test end to end.

It looks like it happens after builds complete.

**Comment by kargakis** [comment] 2015-04-16 10:41
@thoraxe can you 

1) get the build-logs from a build in the default namespace?
2) process a template in another namespace than default?
eg. openshift cli process -n test -f examples/sample-app/application-template-stibuild.json

**Comment by sdodson** [comment] 2015-04-16 14:34
Both the default and a created namespace works as 'system:openshift-client' user. I suspect this is a user permissoins issue, it doesn't work as 'joe' which is a user defined via htpasswd identity provider.

Default namespace -- works
```
osc process -f examples/sample-app/application-template-stibuild.json > test.json
osc create -f test.json 
osc get builds
osc build-logs ruby-sample-build-1
```
Make a new namespace, re-test -- works
```
openshift admin new-project --admin=system:openshift-client issue1714
osc create -n issue1714 -f test.json 
osc get builds -n issue1714
osc build-logs -n issue1714 ruby-sample-build-1
```

Here it is as 'joe'
```
[joe@ose3 ~]$ osc login
Already logged into "https://ose3.os1.phx2.redhat.com:8443" as "joe".
Using project "sinatra"
[joe@ose3 ~]$ osc create -f test.json 
services/frontend
routes/route-edge
imageStreams/origin-ruby-sample
imageStreams/ruby-20-centos7
buildConfigs/ruby-sample-build
deploymentConfigs/frontend
services/database
deploymentConfigs/database
[joe@ose3 ~]$ osc get builds
NAME                             TYPE      STATUS     POD
ruby-sample-build-1              STI       Running    ruby-sample-build-1
simple-openshift-sinatra-sti-1   STI       Complete   simple-openshift-sinatra-sti-1
[joe@ose3 ~]$ osc build-logs ruby-sample-build-1
Error from server: "/osapi/v1beta1/proxy/buildLogs/ruby-sample-build-1?namespace=sinatra" is forbidden because joe cannot proxy on buildLogs with name "ruby-sample-build-1" in sinatra
```

**Comment by smarterclayton** [comment] 2015-04-16 15:31
@csrwng please get involved here as well

**Comment by csrwng** [comment] 2015-04-16 19:28
So the issue is that because we are now using the proxy to get at the build logs, we're exposing an issue in the Kubernetes proxy. It is responding with a 301 because the original request doesn't end with a "/" in the path, but the location in the 301 response doesn't include parameters that were passed in the original response, so we lose the namespace parameter:
A request to 
```
https://10.0.2.15:8443/osapi/v1beta1/proxy/buildLogs/simple-openshift-sinatra-sti-1?namespace=project1
```
results in a 301 like:
```
HTTP/1.1 301 Moved Permanently
Location: /osapi/v1beta1/proxy/buildLogs/simple-openshift-sinatra-sti-1/
```
which doesn't include the namespace param.
Offending code is here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/proxy.go#L197-L201

I'll submit a fix for the proxy upstream and switch the origin build logs to use the new log sub-resource.

**Comment by csrwng** [comment] 2015-04-17 20:09
Fixed with https://github.com/openshift/origin/pull/1784

**Closed** 2015-04-17 21:13 UTC
Labels: bug

**Comment by brenton** [comment] 2015-04-20 15:24
@csrwng, even after pulling in https://github.com/openshift/origin/pull/1784 I'm seeing:

~~~
# osc build-logs simple-openshift-sinatra-sti-1
Error from server: "/osapi/v1beta1/proxy/buildLogs/simple-openshift-sinatra-sti-1?namespace=sinatra" is forbidden because joe cannot proxy on buildLogs with name "simple-openshift-sinatra-sti-1" in sinatra
~~~

Joe is the admin for the sinatra project.

**Comment by brenton** [comment] 2015-04-20 15:32
cesar explains the fix for me in more detail.  It this actually working as expected with the known current issue of only the admin's being able to access logs.
