### ISSUE TITLE
flake: jenkins-plugin test connection test

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#17488] opened 2017-11-27 23:42 UTC
```/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:698
Expected error:
    <*errors.errorString | 0xc420f020b0>: {
        s: "Expecting 'Connection unsuccessful', Got: ",
    }
    Expecting 'Connection unsuccessful', Got: 
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/jenkins_plugin.go:696

**Comment by jim-minter** [comment] 2017-11-27 23:42
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/294/testReport/junit/(root)/Extended/_image_ecosystem__jenkins__Slow__openshift_pipeline_plugin_jenkins_plugin_test_context___jenkins_plugin_test_connection_test__Suite_openshift_/

**Comment by jim-minter** [comment] 2017-11-27 23:42
@gabemontero I'm not seeing the wood for the trees on this one - any chance you could help take a look?

**Comment by gabemontero** [comment] 2017-11-28 14:28
can do @jim-minter - on today's to-do list

**Comment by gabemontero** [comment] 2017-11-28 15:19
About to try locally ... especially if this is happening consistently, I suspect that something at the http level on api master changed slightly and the plugin is not getting what it previously expected on a bad url request for testing the connection to the api server.

**Comment by jim-minter** [comment] 2017-11-28 15:25
seems it's the part where it tries to connect to https://1.2.3.4 that's the issue?  looking at jenkins_plugin.go:690 it's possible that if a non-200 was returned, it'd be masked by lines 693-695?

**Comment by gabemontero** [comment] 2017-11-28 15:26
Though this looks off as well:

```
STEP: Creating new jenkins item: test-build-job
Posting to Jenkins resource: "http://172.30.245.201:80/createItem?name=test-build-job"
STEP: trigger test connection logic, check for success
Posting to Jenkins resource: "http://172.30.245.201:80/job/test-build-job/descriptorByName/com.openshift.jenkins.plugins.pipeline.OpenShiftBuilder/testConnection"
STEP: trigger test connection logic, check for failure
Posting to Jenkins resource: "http://172.30.245.201:80/job/test-build-job/descriptorByName/com.openshift.jenkins.plugins.pipeline.OpenShiftBuilder/testConnection"
```

The check for success url and check for failure url are the same ... the failure one should be mangled, no?

Will need to refresh my memory more on this test.  Run it locally as well with some debug.

**Comment by jim-minter** [comment] 2017-11-28 15:30
The difference is the body part which is posted and not logged.

**Comment by gabemontero** [comment] 2017-11-28 15:55
yeah was trying to reconcile that before leaving for our scrum ... now remember - we post to the jenkins url, which posts (using the body data) to the master url ... I was originally expecting the bogus body from the test to show up in that output I pasted previously

anyway, some `git blame` invocations reveal none of the test paths here have changed in a while ... I doubt that it is a test case issue that had been previously working incorrectly for a long time (and rather some rebase change in behavior per my original speculation), but will try with some added debug and confirm

**Comment by gabemontero** [comment] 2017-11-28 16:50
So there is an option "c" :-)

Running the scenario from the browser in Jenkins, as well as running the extended test locally against an updated origin/master work.

The key difference so far from my run and the logs from the test failure was the absence, in the ci test run failure, of the java stack trace expected when we attempt to test the connection with the bogus https url in the body.

This could imply a number of things:
- the http post did not get to jenkins and/or the plugin's endpoint for this
- the attempt within jenkins from the plugin to connect with the api master timed out or failed in some unexpected fashion.

Next step as I see it ... does some additional explicit logging during the test connection step make sense (at first blush I think it it reasonable).  Add that in, then monitor subsequent runs.

Given my success locally, I'm leaning towards lowering the priority, but let's hang tight for a few days, leave the priority as is, and see if this persists or not.

**Comment by gabemontero** [comment] 2017-11-28 17:10
Another possibility on cause could be container memory usage and/or JVM heap.  I explicitly did not bump the container memory for the jenkins_plugin.go tests (like what had to be done for the pipeline.go tests) since they were not exhibiting the same container memory pressure as a result of pipelines forking the oc command.  The old plugin simply makes direct http rest calls to the master.

It could be that over time, memory consumption has creeped up in this scenario (new jenkins versions, new plugin versions, whatever) and we are not hitting some memory induced flakiness.

Something to keep in mind if this persists, where we add the memory monitoring back in.  I'm inclined to just try new plugin logging first (much less chatty).

**Comment by gabemontero** [comment] 2017-11-29 15:00
fyi, the overnight image_eco run was clean last night ... this issue did not pop up

**Comment by gabemontero** [comment] 2017-12-06 15:09
This has still not reoccurred.  Lowering down the p2.  Should be cutting a plugin release with the diagnostic PR today or tomorrow.

**Comment by gabemontero** [comment] 2017-12-07 19:31
centos image has the diagnostic update 

given intermittent nature of this one (i believe it has only happened the one time that lead to the opening of this issue) closing this out ... if we see again, we can open a new issue and should have diags to better drill down the root cause

**Closed by gabemontero** 2017-12-07 19:31 UTC
Labels: area/tests, kind/test-flake, priority/P2
