### ISSUE TITLE
oc start-build --follow leaves my console red

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5185] opened 2015-10-18 20:36 UTC
When I'm tailing logs and something turns the output red and exits, the console stays that way.

@bparees I don't think this is a dupe of `oc logs` (https://github.com/openshift/origin/issues/5184).  As I recall, you don't delegate directly.

**Comment by bparees** [comment] 2015-10-18 21:31
yeah build-logs is invoking the api itself to get the logs.  one more reason to get rid of it.

**Comment by kargakis** [comment] 2015-10-19 15:27
I think this is a dupe. All, `oc logs` (for builds), `oc start-build -f`, and `oc build-logs` use the same api call ...

https://github.com/openshift/origin/blob/4a646e0a07feb55408e0abe4ec83c628a6c0b5ea/pkg/cmd/cli/cmd/buildlogs.go#L88
https://github.com/openshift/origin/blob/4a646e0a07feb55408e0abe4ec83c628a6c0b5ea/pkg/cmd/cli/cmd/startbuild.go#L172
https://github.com/openshift/origin/blob/4a646e0a07feb55408e0abe4ec83c628a6c0b5ea/pkg/cmd/cli/cmd/logs.go#L179

@deads2k can you reproduce this with `oc logs` but not against a build?

**Comment by deads2k** [comment] 2015-10-19 15:29
> I think this is a dupe. All, oc logs (for builds), oc start-build -f, and oc build-logs use the same api call ...

I wouldn't expect an API call to do anything with the terminal.  Messing with terminal state belongs to the command.

**Comment by kargakis** [comment] 2015-10-19 15:58
> I wouldn't expect an API call to do anything with the terminal. Messing with terminal state belongs to the command.

All I am saying is these commands have no difference in how they function, and I cannot see how this isn't a dupe of https://github.com/openshift/origin/issues/5184

**Comment by bparees** [comment] 2015-11-09 21:47
agree with @kargakis, the issue is presumably in the content being streamed by the api and it looks like the fix is going to fix the content being streamed (append a closing sequence), so closing this as a dupe.

**Comment by deads2k** [comment] 2015-11-10 13:41
> agree with @kargakis, the issue is presumably in the content being streamed by the api and it looks like the fix is going to fix the content being streamed (append a closing sequence), so closing this as a dupe

I don't think that mutating container logs in the server API before handing them back to the client makes sense.  A diff between what I get from container logs and the server logs API should be empty.  Also, there's no guarantee that the client will even get the last response from the server.  In such a case, it shouldn't just leave my terminal red.

@fabianofranz You're working on a server-side pull to mutate the returned logs?

**Comment by bparees** [comment] 2015-11-10 13:48
closing since this is still a dupe of https://github.com/openshift/origin/issues/5184

if you want to debate the solution, you can debate it there.

**Closed by bparees** 2015-11-10 13:48 UTC
Labels: component/build, component/logging, kind/bug, priority/P3

**Comment by fabianofranz** [comment] 2015-11-10 14:10
@deads2k My initial proposal (although I still want to review it to something clear) is to do it in the client, not server-side. Trap the signals + defer and print a ASCII color reset before exiting.
