### ISSUE TITLE
Retrieve images in the origin-node family fails w/ no active account selected

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#18306] opened 2018-01-26 16:15 UTC
During test_pull_request_origin_extended_conformance_gce

```
TASK [Retrieve images in the origin-node family] *******************************
Friday 26 January 2018  15:59:30 +0000 (0:00:00.019)       0:00:00.102 ******** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["gcloud", "--project", "openshift-gce-devel-ci", "compute", "images", "list", "--filter=family=origin-node", "--format=json", "--sort-by", "~creationTimestamp"], "delta": "0:00:02.527088", "end": "2018-01-26 15:59:34.186943", "msg": "non-zero return code", "rc": 1, "start": "2018-01-26 15:59:31.659855", "stderr": "ERROR: (gcloud.compute.images.list) You do not currently have an active account selected.\nPlease run:\n\n  $ gcloud auth login\n\nto obtain new credentials, or if you have already logged in with a\ndifferent account:\n\n  $ gcloud config set account ACCOUNT\n\nto select an already authenticated account to use.", "stderr_lines": ["ERROR: (gcloud.compute.images.list) You do not currently have an active account selected.", "Please run:", "", "  $ gcloud auth login", "", "to obtain new credentials, or if you have already logged in with a", "different account:", "", "  $ gcloud config set account ACCOUNT", "", "to select an already authenticated account to use."], "stdout": "", "stdout_lines": []}
```

**Comment by sjenning** [comment] 2018-01-26 16:59
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18286/test_pull_request_origin_extended_conformance_gce/15064/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18274/test_pull_request_origin_extended_conformance_gce/15065/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18295/test_pull_request_origin_extended_conformance_gce/15066/

**Comment by smarterclayton** [comment] 2018-01-26 17:09
This is due to another bug in sjb we haven't tracked down.  I'm manually stomping this until we figure out the cause.

**Comment by smarterclayton** [comment] 2018-01-26 17:10
@stevekuznetsov this is the issue with sjb syncing in a post step from a different job that I pinged you about.  We don't need an immediate fix (I'm just updating the job everytime someone syncs), but could keep happening.

**Comment by stevekuznetsov** [comment] 2018-01-26 18:32
I noticed in my latest PR that you had a mis-configured XML checked in for that job in SJB ... can you make sure you're rebased on master and regenerating it from the latest congfig?

**Comment by smarterclayton** [comment] 2018-01-27 23:15
I corrected the underlying issue (pull request jobs inheriting from branch jobs) in https://github.com/openshift/aos-cd-jobs/pull/1039

**Closed by smarterclayton** 2018-01-27 23:15 UTC
Labels: kind/test-flake, priority/P1
