### ISSUE TITLE
Openshift Dashboard showing wrong build/commit ID for deployment

### ISSUE THREAD

**Issue by danni** [openshift/origin#7055] opened 2016-02-05 02:38 UTC
My Openshift dashboard is stuck showing build #1 (with the commit message for build #1) and the old image id in the dashboard for my deployment. However it also states that the deploy redeployed 4 hours ago from an image change. `oc describe pod ...` is showing the right (current) image as is `oc describe dc ...`

**Comment by liggitt** [comment] 2016-02-05 02:47
Dupe of https://github.com/openshift/origin/issues/6919 ? What version are you running?

**Comment by danni** [comment] 2016-02-05 03:00
Looks like it could be.

```
openshift v1.1.1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2
```

**Comment by liggitt** [comment] 2016-02-05 03:02
Looks like it. Fixed in https://github.com/openshift/origin/pull/6945, slated for 1.1.1.2

**Closed by liggitt** 2016-02-05 03:02 UTC
