### ISSUE TITLE
Current 1.5.0-alpha 3+cf7e336   - Docker version error

### ISSUE THREAD

**Issue by DarkBlaez** [openshift/origin#13297] opened 2017-03-08 04:48 UTC
[provide a description of the issue]
oc cluster up   fails to complete and errors
##### Version
oc v1.5.0-alpha.3+cf7e336
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

Running on Centos 7
##### Steps To Reproduce
1. oc cluster up

##### Current Result
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... FAIL
   Error: Minor number must not contain leading zeroes "03"

##### Expected Result
Expect process to continue and launch

I thought I saw a thread where this was reported under OSX but suppose to be fixed in this oc release. However, it still appears in this current release as referenced above.

Thanks
DB

**Comment by iteeconsulting** [comment] 2017-03-08 08:16
Seems we need to build oc client from master. Please see: https://github.com/openshift/origin/issues/13219#issuecomment-284282835

**Comment by pweil-** [comment] 2017-03-08 18:56
duplicate of https://github.com/openshift/origin/issues/13219

**Closed by pweil-** 2017-03-08 18:56 UTC
