### ISSUE TITLE
'make check' fails when 'Verifying Generated Bootstrap Bindata'

### ISSUE THREAD

**Issue by marun** [openshift/origin#10108] opened 2016-07-29 15:53 UTC
'make check' fails when 'Verifying Generated Bootstrap Bindata'

##### Version
master

##### Steps To Reproduce
1. clone origin repo
2. make check

##### Current Result
```
<snip>
===== Verifying Generated Bootstrap Bindata =====
Generating bootstrap bindata...
FAILURE: Generation of fresh bindata failed:
go-bindata/main.go:15:2: cannot find package "github.com/jteeuwen/go-bindata" in any of:
        /usr/lib/golang/src/github.com/jteeuwen/go-bindata (from $GOROOT)
        ($GOPATH not set)
</snip>
```

##### Expected Result
make check completes without failure. 

cc: @dcbw @knobunc

**Comment by jwforres** [comment] 2016-08-01 11:41
I dont think this is the console, I think this is the embedded templates for oc cluster up @bparees ?

**Comment by bparees** [comment] 2016-08-01 12:34
yeah it's for oc cluster up, but jtweeuwen/go-bindata is vendored into origin, so it should be found.  works fine for me building off master.

**Comment by jwforres** [comment] 2016-08-01 12:36
On a fresh clone of origin the go-bindata binary doesn't exist, it has to
be built. Guessing make check isn't doing that

**Comment by bparees** [comment] 2016-08-01 12:43
The failure is that it couldn't find the package, doesn't sound like an issue with finding the actual binary.  In fact i think it's trying to build the binary and fails.  Also that GOPATH looks wrong
@marun can you add a "-x" to hack/verify-bootstrap-bindata.sh and hack/gen-bootstrap-bindata.sh and run again?

(also are you able to run hack/gen-bootstrap-bindata.sh successfully by hand?)

**Comment by dcbw** [comment] 2016-08-01 17:29
@bparees running hack/gen-bootstrap-bindata.sh fails immediately with the same error.

**Comment by dcbw** [comment] 2016-08-01 17:35
@bparees @jwforres adding this to hack/gen-bootstrap-data.sh

```
 OS_ROOT=$(dirname "${BASH_SOURCE}")/..
 source "${OS_ROOT}/hack/lib/init.sh"
 os::log::stacktrace::install
+os::build::setup_env
```

seems to do the trick.  Since that script is trying to build stuff, it needs setup_env() to set GOPATH and other stuff like like a 'make build' does, I think.

**Comment by csrwng** [comment] 2016-08-02 18:11
@dcbw what version of go are you using ? For whatever reason I can't reproduce (RHEL or OS X) using go1.6 and go1.6.3:

```
$ go version
go version go1.6.3 darwin/amd64
$ make clean
rm -rf _output
$ hack/gen-bootstrap-bindata.sh
hack/gen-bootstrap-bindata.sh took 0 seconds
```

**Comment by dcbw** [comment] 2016-08-05 21:23
@csrwng golang-1.6.2-1.fc24.x86_64

**Comment by dcbw** [comment] 2016-08-05 21:30
@csrwng I think it really is a build env problem.

hack/gen-bootstrap-data.sh tries to build something with Go:

```
pushd vendor/github.com/jteeuwen/go-bindata > /dev/null
  go install ./...
popd > /dev/null
```

and for that to actually work correctly the environment needs to be set up like hack/build-go.sh sets it up.  Just sourcing ${OS_ROOT}/hack/lib/init.sh doesn't cut it, we need the full setup_env() call to ensure GOPATH is set correctly.  I never have GOPATH set in my shell because I have many Go projects and don't want them to cross-pollute each other, that's what 'make' is for and that's why setup_env() exists.

I think any of the scripts that call 'go install' will need setup_env() called, like hack/godep-restore.sh and others.

**Comment by coreydaley** [comment] 2016-10-19 16:12
Verified this issue and tested the solution proposed by @dcbw, which is verified working.
PR incoming shortly after make check finishes running

@csrwng Is it possible that you already had go-bindata in your PATH and also in your GOPATH?
I ran into an issue at first where I had included GOPATH/bin in my PATH, and then unset my GOPATH.  So the go-bindata binary was in my PATH, but not available in my GOPATH, which is an unlikely scenario.

**Comment by csrwng** [comment] 2016-10-19 18:11
@coreydaley Yeah, I don't think I had tested without GOPATH set. I tried it recently and was able to reproduce, hence sent it to you :)

**Comment by coreydaley** [comment] 2016-10-19 19:03
Opened PR #11450

**Comment by coreydaley** [comment] 2016-10-20 15:07
PR has been merged

**Closed by coreydaley** 2016-10-20 15:07 UTC
Labels: component/composition, priority/P2
