### ISSUE TITLE
Direct executed build should wait until tag exists

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16497] opened 2017-09-21 22:17 UTC
Looking at cesar's builds here https://github.com/openshift/release/tree/master/cluster/ci/origin/config  when I run them on 3.7.0-alpha.1 builds are starting before the :src tag is created, which should not happen.

Not sure if this is a regression or it never worked, or didn't work in that build.

**Comment by smarterclayton** [comment] 2017-09-21 22:18
```
test-service-catalog         Docker                  Failed (GenericBuildFailed)   37 seconds ago   26s
test-sti-builder             Docker                  Pending
$ oc logs build/test-service-catalog
Pulling image "test:src" ...
error: error pulling image test:src: unauthorized: authentication required
```

If `test:src` does not exist the build should not have been started.

**Comment by bparees** [comment] 2017-09-23 14:34
"test:src" is a dockerimagereference, not an imagestream reference, from what I see?

If you do an imagestream reference we will iterate until we can successfully resolve the value.  If you do a direct docker image reference, we are just going to run and hope for the best, and I think that's the right thing to do.

**Comment by smarterclayton** [comment] 2017-09-23 19:26
Yeah, I thought it was a tag.  The build should be using tags instead.

**Comment by bparees** [comment] 2017-09-23 19:35
so close this and fix the build definitions to use an IST instead?

**Comment by bparees** [comment] 2017-09-25 18:58
this is caused by the build using dockerimage refs, not imagestreamtags.

**Closed by bparees** 2017-09-25 18:58 UTC
Labels: component/build, priority/P1
