### ISSUE TITLE
Using terminal in an SCL based image i have to know to run scl enable to be in the right environment

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#10298] opened 2016-08-09 14:27 UTC
When I'm using the web console terminal as a ruby developer (or any other base image that has scl-ized stuff installed, like Gems) I have no idea i need to run the command to scl enable to actually be able to test things in the correct “environment” that everything has at runtime.  

For example in the ruby env I open the terminal and run irb to test something, then I dont have the same Gems available that I would have if I ran scl enable ( what the runtime of my container already does )

**Comment by jwforres** [comment] 2016-08-09 14:28
@bparees want to discuss what we could do to make this better for users

**Comment by bparees** [comment] 2016-08-09 15:10
we've got issues open with the scl team to make the scl stuff more "auto enabled", but it's supposed to already be mostly auto enabled today for all the scenarios we could figure out how to cover.  if you oc rsh into a running ruby container, ruby itself should already be scl enabled.  Is that not the case for you?  I'm wondering if the web console is connecting in a different way that bypasses our scl enablement logic.

**Comment by jwforres** [comment] 2016-08-09 15:23
This is the logic for the pod/exec we create in the container-terminal
https://github.com/kubernetes-ui/container-terminal/blob/master/container-terminal.js#L145

we are setting the command to /bin/sh -i

**Comment by jwforres** [comment] 2016-08-09 15:25
What I saw was: I added mongo to my Gemfile, ran a build, exec'ed into the
new pod, when i ran irb and tried to require 'mongo' it failed.

**Comment by bparees** [comment] 2016-08-09 20:58
this is caused by us installing the gem files into a specific directory which irb doesn't include by default.

**Comment by bparees** [comment] 2016-09-07 15:30
closing in deference to https://github.com/sclorg/s2i-ruby-container/issues/115

**Closed by bparees** 2016-09-07 15:30 UTC
Labels: area/usability, component/build, component/web, kind/enhancement, priority/P2
