### ISSUE TITLE
TestProjectRequestError

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17781] opened 2017-12-14 13:22 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_integration/11977/#githubcomopenshiftorigintestintegrationrunner-testintegrationtestprojectrequesterror
<details>

```
runner_test.go:124: FAILED TestProjectRequestError, retrying:

project_request_test.go:116: ADDED &core.Namespace{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"testns", GenerateName:"", Namespace:"", SelfLink:"/api/v1/namespaces/testns", UID:"36178a89-e0b1-11e7-9eca-0242ac110002", ResourceVersion:"297", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63648840537, loc:(*time.Location)(0x112dfb40)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"openshift.io/description":"", "openshift.io/display-name":"", "openshift.io/requester":"system:admin"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.NamespaceSpec{Finalizers:[]core.FinalizerName{"openshift.io/origin", "kubernetes"}}, Status:core.NamespaceStatus{Phase:"Active"}}
project_request_test.go:116: MODIFIED &core.Namespace{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"testns", GenerateName:"", Namespace:"", SelfLink:"/api/v1/namespaces/testns", UID:"36178a89-e0b1-11e7-9eca-0242ac110002", ResourceVersion:"304", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63648840537, loc:(*time.Location)(0x112dfb40)}}, DeletionTimestamp:(*v1.Time)(0xc42ad5e140), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"openshift.io/description":"", "openshift.io/display-name":"", "openshift.io/requester":"system:admin"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.NamespaceSpec{Finalizers:[]core.FinalizerName{"openshift.io/origin", "kubernetes"}}, Status:core.NamespaceStatus{Phase:"Terminating"}}
project_request_test.go:116: MODIFIED &core.Namespace{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"testns", GenerateName:"", Namespace:"", SelfLink:"/api/v1/namespaces/testns", UID:"36178a89-e0b1-11e7-9eca-0242ac110002", ResourceVersion:"461", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63648840537, loc:(*time.Location)(0x112dfb40)}}, DeletionTimestamp:(*v1.Time)(0xc4270035a0), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"openshift.io/display-name":"", "openshift.io/requester":"system:admin", "openshift.io/description":""}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.NamespaceSpec{Finalizers:[]core.FinalizerName{"kubernetes"}}, Status:core.NamespaceStatus{Phase:"Terminating"}}
project_request_test.go:116: MODIFIED &core.Namespace{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"testns", GenerateName:"", Namespace:"", SelfLink:"/api/v1/namespaces/testns", UID:"36178a89-e0b1-11e7-9eca-0242ac110002", ResourceVersion:"516", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63648840537, loc:(*time.Location)(0x112dfb40)}}, DeletionTimestamp:(*v1.Time)(0xc427e6d620), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"openshift.io/description":"", "openshift.io/display-name":"", "openshift.io/requester":"system:admin", "openshift.io/sa.scc.mcs":"s0:c8,c2", "openshift.io/sa.scc.supplemental-groups":"1000060000/10000", "openshift.io/sa.scc.uid-range":"1000060000/10000"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.NamespaceSpec{Finalizers:[]core.FinalizerName{"kubernetes"}}, Status:core.NamespaceStatus{Phase:"Terminating"}}
project_request_test.go:118: expected 1 namespace to be added and deleted, got 1 added / 0 deleted
project_request_test.go:135: Expected namespace to be gone, got &core.Namespace{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"testns", GenerateName:"", Namespace:"", SelfLink:"/api/v1/namespaces/testns", UID:"36178a89-e0b1-11e7-9eca-0242ac110002", ResourceVersion:"516", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63648840537, loc:(*time.Location)(0x112dfb40)}}, DeletionTimestamp:(*v1.Time)(0xc43352e0e0), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"openshift.io/description":"", "openshift.io/display-name":"", "openshift.io/requester":"system:admin", "openshift.io/sa.scc.mcs":"s0:c8,c2", "openshift.io/sa.scc.supplemental-groups":"1000060000/10000", "openshift.io/sa.scc.uid-range":"1000060000/10000"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.NamespaceSpec{Finalizers:[]core.FinalizerName{"kubernetes"}}, Status:core.NamespaceStatus{Phase:"Terminating"}}, <nil>
etcd.go:140: dumping etcd to "/tmp/openshift/test-integration/tmp-testprojectrequesterror632880318/etcd-dump-TestProjectRequestError-v2.json"
```
</details>

/assign @mfojtik 
/sig master
/area tests

**Comment by deads2k** [comment] 2017-12-15 18:11
same as https://github.com/openshift/origin/issues/17780 ?

**Comment by soltysh** [comment] 2018-01-03 16:41
Closing as dupe of #17780

**Closed by soltysh** 2018-01-03 16:41 UTC
Labels: area/tests, priority/P2, sig/master
