### ISSUE TITLE
oc cluster up, expose secure registry - can't login remotely

### ISSUE THREAD

**Issue by eformat** [openshift/origin#10406] opened 2016-08-14 03:29 UTC
when using oc cluster up, then exposing a secure docker registry, you can docker login OK from the host where openshift is running, but when you try remotely it appears to be looking for the internal registry kube service address for the auth token:

Error response from daemon: no successful auth challenge for https://docker-registry.192.168.137.2.xip.io/v2/ - errors: [Get https://172.30.160.178:5000/openshift/token?account=developer: dial tcp 172.30.160.178:5000: i/o timeout]

when using curl (see additional info below) the www-authenticate header is set as:
**< www-authenticate:Bearer realm="https://172.30.160.178:5000/openshift/token"**

and in a working openshift 3.2 environment it is set with:
**Www-Authenticate: Basic realm=openshift,error="authorization header with basic token required"**

##### Version
ose:~$ oc version
oc v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.137.2:8443
openshift v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7

##### Steps To Reproduce
1. start openshift on fully patched centos.7 vm 

ose:~$ uname -a
Linux ose 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ose:~$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

using:

wget https://github.com/openshift/origin/releases/download/v1.3.0-alpha.3/openshift-origin-client-tools-v1.3.0-alpha.3-7998ae4-linux-64bit.tar.gz
tar xzvf openshift-origin-client-tools-v1.3.0-alpha.3-7998ae4-linux-64bit.tar.gz
ln -sf /root/openshift-origin-client-tools-v1.3.0-alpha.3-7998ae4-linux-64bit/oc /usr/local/bin/oc
chmod 755 /root/openshift-origin-client-tools-v1.3.0-alpha.3-7998ae4-linux-64bit/oc
oc cluster up --use-existing-config --host-data-dir=/var/tmp/etcd --skip-registry-check=true

2. expose registry as per openshift documentation

ose:~$ oc get route
NAME       HOST/PORT                              PATH      SERVICE           TERMINATION   LABELS
registry   docker-registry.192.168.137.2.xip.io             docker-registry   passthrough   

ose:~$ oc logs docker-registry-6-exiy1 | grep tls
time="2016-08-13T00:48:26.851987281Z" level=info msg="listening on :5000, tls" go.version=go1.6.3 instance.id=3031407f-8e6a-4524-99a4-46885094d164 

3. try logging in

virt:~$ oc login -u developer --server=https://192.168.137.2:8443 --insecure-skip-tls-verify=true -p developer
Login successful.

docker login -u developer -e dev@dev.com -p `oc whoami -t` docker-registry.192.168.137.2.xip.io
Error response from daemon: no successful auth challenge for https://docker-registry.192.168.137.2.xip.io/v2/ - errors: [Get https://172.30.160.178:5000/openshift/token?account=developer: dial tcp 172.30.160.178:5000: i/o timeout]

##### Current Result

docker login -u developer -e dev@dev.com -p `oc whoami -t` docker-registry.192.168.137.2.xip.io
Error response from daemon: no successful auth challenge for https://docker-registry.192.168.137.2.xip.io/v2/ - errors: [Get https://172.30.160.178:5000/openshift/token?account=developer: dial tcp 172.30.160.178:5000: i/o timeout]

##### Expected Result

works OK locally:

ose:~$ oc login -u developer --server=https://192.168.137.2:8443 --insecure-skip-tls-verify=true -p developer
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * gogs
    jenkins
    monster-monolith
    myproject
    nexus
    pipelineproject
    sonarqube

Using project "gogs".
ose:~$ docker login -u developer -e dev@dev.com -p `oc whoami -t` docker-registry.192.168.137.2.xip.io
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded
ose:~$ 

##### Additional Information

docker pod logs, show this when attempting to login from remote host:

       time="2016-08-14T03:19:10.897819311Z" level=error msg="error authorizing context: authorization header required" go.version=go1.6.3 http.request.host=docker-registry.192.168.137.2.xip.io http.request.id=fdfaf377-6d93-4164-a130-7e7c5504e5b9 http.request.method=GET http.request.remoteaddr="172.17.0.1:56120" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.6.3 kernel/4.6.5-300.fc24.x86_64 os/linux arch/amd64" instance.id=3031407f-8e6a-4524-99a4-46885094d164

from the remote machine, curl suggests the bearer realm is set with internal ip ?

virt:~$ curl -k -vvv https://docker-registry.192.168.137.2.xip.io/v2/
*   Trying 192.168.137.2...
* Connected to docker-registry.192.168.137.2.xip.io (192.168.137.2) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* ALPN, server accepted to use h2
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=172.30.160.178
* 	start date: Aug 03 22:34:55 2016 GMT
* 	expire date: Aug 03 22:34:56 2018 GMT
* 	common name: 172.30.160.178
* 	issuer: CN=openshift-signer@1469220090
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55dd066ffcd0)
> GET /v2/ HTTP/1.1
> Host: docker-registry.192.168.137.2.xip.io
> User-Agent: curl/7.47.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2.0 401
< content-type:application/json; charset=utf-8
< docker-distribution-api-version:registry/2.0
< www-authenticate:Bearer realm="https://172.30.160.178:5000/openshift/token"
< content-length:87
< date:Sun, 14 Aug 2016 03:24:02 GMT
< 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
* Connection #0 to host docker-registry.192.168.137.2.xip.io left intact

**Comment by liggitt** [comment] 2016-08-14 04:23
Dupe of https://github.com/openshift/origin/issues/10193

**Closed by liggitt** 2016-08-14 04:23 UTC

**Comment by JasonGiedymin** [comment] 2017-01-13 18:20
I still have this issue. Unless the docs are wrong?
On a Mac, did a oc cluster up --docker-machine and then did the expose. Maybe someone can do a quick up and expose - showing me what commands they used?
