### ISSUE TITLE
new-app cmd test flake: "ruby-sample-build-1" not found

### ISSUE THREAD

**Issue by miminar** [openshift/origin#14022] opened 2017-05-03 12:07 UTC
```
Running test/cmd/newapp.sh:348: executing 'oc delete all -l app=helloworld' expecting success...
FAILURE after 2.513s: test/cmd/newapp.sh:348: executing 'oc delete all -l app=helloworld' expecting success: the command returned the wrong error code
Standard output from the command:
buildconfig "ruby-sample-build" deleted
imagestream "origin-ruby-sample" deleted
imagestream "ruby-22-centos7" deleted
deploymentconfig "database" deleted
deploymentconfig "frontend" deleted
route "route-edge" deleted
service "database" deleted
service "frontend" deleted
Standard error from the command:
Error from server (NotFound): builds.build.openshift.io "ruby-sample-build-1" not found
[ERROR] PID 1257: hack/lib/cmd.sh:241: `return "${return_code}"` exited with status 1.
```

Happened in jenkins: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1106/consoleFull#181393306558b6e51eb7608a5981914356

**Comment by ncdc** [comment] 2017-05-05 16:02
I'm seeing 3 different user-agents trying to delete this build:

```
I0503 09:35:01.008615    7462 wrap.go:75] DELETE /oapi/v1/namespaces/cmd-newapp/builds/ruby-sample-build-1: (8.67483ms) 200 [[oc/v3.6.0 (linux/amd64) openshift/77b2372] 127.0.0.1:36680]
I0503 09:35:04.573531    7462 wrap.go:75] DELETE /apis/build.openshift.io/v1/namespaces/cmd-newapp/builds/ruby-sample-build-1: (4.748445ms) 200 [[openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/5115d70/generic-garbage-collector] 127.0.0.1:57210]
I0503 09:35:04.575813    7462 wrap.go:75] DELETE /oapi/v1/namespaces/cmd-newapp/builds/ruby-sample-build-1: (4.749881ms) 404 [[oc/v1.6.1+5115d708d7 (linux/amd64) kubernetes/5115d70] 127.0.0.1:36688]
```

1 is presumably the `oc` that issued `oc delete all ...`. 2 is the garbage collector. 3 is ... ? The user-agent string looks like what you'd see for kubectl (v1.6.1 instead of v3.6.0).

I've tried to reproduce locally a couple of times and have not hit this yet. Any thoughts what's going on here @deads2k @liggitt @kargakis @sttts ?

**Comment by deads2k** [comment] 2017-05-08 12:26
> I've tried to reproduce locally a couple of times and have not hit this yet. Any thoughts what's going on here @deads2k @liggitt @kargakis @sttts ?

Namespace cleanup?

**Comment by ncdc** [comment] 2017-05-15 15:20
> Namespace cleanup?

Wouldn't you expect to see a service account name in the user-agent string for that?

**Comment by kargakis** [comment] 2017-09-15 08:56
Seeing this in a different place now:
```
FAILURE after 2.416s: test/cmd/admin.sh:365: executing 'oc delete all -l build=sti' expecting success: the command returned the wrong error code
Standard output from the command:
buildconfig "ruby-sample-build" deleted
imagestream "origin-ruby-sample" deleted
imagestream "ruby-22-centos7" deleted
deploymentconfig "database" deleted
deploymentconfig "frontend" deleted
route "route-edge" deleted
service "database" deleted
service "frontend" deleted
Standard error from the command:
Error from server (NotFound): builds "ruby-sample-build-1" not found
```

This issue has no owner 
/assign @bparees @mfojtik

 I am not sure who owns this, you can fight for it.

**Comment by bparees** [comment] 2017-09-15 16:07
@kargakis this really seems like a bug in the CLI, no?  It looks like it selects all the objects first, then iterates over deleting them, but thanks to GC(presumably?) some of the objects it initially selected are deleted by the time the code tries to delete them.

Seems like oc delete should ignore (or warn?) failures like that.

**Comment by kargakis** [comment] 2017-09-15 16:10
cc: @fabianofranz @juanvallejo

**Comment by bparees** [comment] 2017-09-15 16:10
I should also note when I ran this it didn't even report deleting a build:
```
)$ oc delete all -l build=sti
buildconfig "ruby-sample-build" deleted
imagestream "origin-ruby-sample" deleted
imagestream "ruby-22-centos7" deleted
deploymentconfig "database" deleted
deploymentconfig "frontend" deleted
route "route-edge" deleted
service "database" deleted
service "frontend" deleted
```

but one did exist before i ran the delete:
```
$ oc get builds -l build=sti
NAME                  TYPE      FROM          STATUS    STARTED          DURATION
ruby-sample-build-1   Source    Git@022d87e   Running   12 seconds ago   
```

**Comment by bparees** [comment] 2017-09-15 16:13
Hm, or perhaps this error is coming from the delete cascade logic for builds.

**Comment by bparees** [comment] 2017-09-15 16:24
if it was the build reaper we should have seen this:
https://github.com/openshift/origin/blob/master/pkg/build/cmd/reaper.go#L131-L136

so i'm inclined to think it's still something in the core delete code path.

**Comment by juanvallejo** [comment] 2017-09-15 16:48
I believe the error is being returned [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/delete.go#L287) in the ReapResult func. Maybe we could add the `--ignore-not-found` flag to the test?

**Comment by bparees** [comment] 2017-09-15 16:53
it seems like bad behavior for oc delete to return an error when it fails to delete something that it (or a reaper) deleted.  i shouldn't have to specify --ignore-not-found to work around that.  (it was found, it's just that two things deleted it?)

**Comment by bparees** [comment] 2017-10-02 19:18
@juanvallejo @fabianofranz bump. thoughts?  ^^

**Comment by juanvallejo** [comment] 2017-10-02 19:41
@bparees 
> it seems like bad behavior for oc delete to return an error when it fails to delete something that it (or a reaper) deleted. i shouldn't have to specify --ignore-not-found to work around that. (it was found, it's just that two things deleted it?)

I agree, a solution could be to ignore resources that are not found by default and have a flag that explicitly asks the command to fail: `--ensure-found` or something similar. We would probably have to deprecate the `--ensure-not-found` flag first, however. wdyt?

**Comment by bparees** [comment] 2017-10-02 20:03
It sounds reasonable (I assume you meant to say deprecate `--ignore-not-found`) to me.

**Comment by bparees** [comment] 2017-10-09 20:43
assigning to cli team since I think this is a bug in oc delete behavior as discussed above.

**Comment by juanvallejo** [comment] 2017-10-11 21:03
@deads2k I can go ahead and open a PR that deprecates the `--ignore-not-found` flag, although the overall change of having `delete` ignore resources no longer available would introduce new behavior to the command. Wanted to get your opinion / approval of going ahead with this change

**Comment by liggitt** [comment] 2017-10-11 21:11
`--ignore-not-found` is intended to handle cases where I asked to delete `foo` and `foo` doesn't exist. If, in the course of deleting `foo`, a reaper is involved, which does a list of objects, and in iterating over those objects to delete them, one is subsequently missing, it should automatically tolerate a `not found` error

**Comment by bparees** [comment] 2017-10-11 21:17
per my earlier comment, i don't think the reaper actually got the error in this case because it would print a warning:
https://github.com/openshift/origin/blob/master/pkg/build/cmd/reaper.go#L131-L136

however it's possible the main oc delete codepath tried to delete something that was already deleted by the reaper?  (Goes back to my original theory that oc delete first creates a list of all the objects it wants to delete, then it starts deleting them.... when it deletes the buildconfig, the reaper runs (with no error), then the oc delete logic continues on to delete the builds that it listed earlier and hits the not found because the reaper already removed them).

**Closed** 2018-04-23 17:29 UTC
Labels: component/cli, kind/bug, lifecycle/rotten, priority/P2
