### ISSUE TITLE
openshift ('oc cluster up') doesn't recover after system crash/hard reset

### ISSUE THREAD

**Issue by oprudkyi** [openshift/origin#13891] opened 2017-04-25 17:23 UTC
when local cluster is running ('oc cluster up' ) and there happens system crash/hard reset then sometime cluster can't recover.

i.e. 'oc cluster up  --use-existing-config ...' works and every running pod is restored as well. but deploying stops to work

```
3:27:33 PM	Warning	Failed mount 	MountVolume.SetUp failed for volume "kubernetes.io/secret/3e2059f5-28e9-11e7-b257-74d02b8fa488-deployer-token-cs56t" (spec.Name: "deployer-token-cs56t") pod "3e2059f5-28e9-11e7-b257-74d02b8fa488" (UID: "3e2059f5-28e9-11e7-b257-74d02b8fa488") with: exit status 32
8 times in the last 
```

it seems like OpenShift stops creating new pods folders in volumes/pods(set via 	--host-volumes-dir) 

i.e. for above logs there no  volumes/pods/3e2059f5-28e9-11e7-b257-74d02b8fa488 folder.
but if I create such folder manually (basically copy other pod folder with correct name) then deployment works (though there same problems with newly deployed pod) 
 

##### Version
opensuse 42.1

Version

oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.16.0.2:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

as well this affected 1.4.1

##### Steps To Reproduce
I got this 2-3 times in few months (OS crashed seems unrelated to OpenShift by self)

**Comment by csrwng** [comment] 2017-06-27 19:54
@oprudkyi is this still an issue with the latest version of the oc client?

**Comment by oprudkyi** [comment] 2017-07-08 18:17
Hi @csrwng 
I've not seen such error for long time (though I've updated to more recent kernel/opensuse) 
probably  this error happens only for 4.1.* Linux kernel and does not affect version 4.4.* of kernel

**Comment by csrwng** [comment] 2017-07-10 13:49
I will close this then since it doesn't seem to be a problem at the moment, please reopen if it can be reproduced.

**Closed by csrwng** 2017-07-10 13:49 UTC
Labels: component/cluster-up, kind/bug, priority/P2
