### ISSUE TITLE
oc new-app fails with ssh git repo

### ISSUE THREAD

**Issue by zuaresc** [openshift/origin#14761] opened 2017-06-19 21:26 UTC
When executing `oc new-app git@github.com:some-org/repo.git` the command fails due to improperly trying to parse the URL.

##### Version
oc version 1.5.1
git version 2.13.1

##### Steps To Reproduce
1. Run `oc new-app` against a public git repo using ssh rather than https.

##### Current Result
```
I0619 17:08:17.416194   95999 sourcelookup.go:82] git@github.com:some-org/repo.git is not a valid url: parse git@github.com:some-org/repo.git: first path segment in URL cannot contain colon
I0619 17:08:17.416238   95999 newapp.go:234] treating git@github.com:some-org/repo.git as a component ref
```

When using the `ssh://` prefix, a failure still occurs due to `git ls-remote` failing due to the inclusion of the `ssh://` prefix.

```
I0619 17:18:50.727399   96602 repository.go:367] Executing  git ls-remote ssh://git@github.com:some-org/repo.git
I0619 17:18:50.766855   96602 repository.go:435] Error executing command: exit status 128
I0619 17:18:50.766952   96602 sourcelookup.go:88] could not list git remotes for ssh://git@github.com:some-org/repo.git: ssh: Could not resolve hostname git@github.com:some-org: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
I0619 17:18:50.766991   96602 newapp.go:234] treating ssh://git@github.com:some-org/repo.git as a component ref
```

##### Expected Result
To create a new app from the git repo.

**Comment by zuaresc** [comment] 2017-06-20 12:12
I realize that this works with a `/` rather than a `:` after the FQDN. I had assumed the normal `git clone` syntax would be used.

**Comment by bparees** [comment] 2017-06-20 12:35
it should be using normal git clone syntax, I think we need to look into this further.

**Comment by bparees** [comment] 2017-06-20 13:51
we also need to update https://stackoverflow.com/questions/44652848/openshift-build-from-git-repo w/ whatever resolution we reach.

**Comment by coreydaley** [comment] 2017-06-20 15:44
@zuaresc Can you give this a try with OpenShift Origin v3.6.x ?  It looks like both issues have been corrected in the newest version.  You can download the newest version here: https://github.com/openshift/origin/releases

**Comment by zuaresc** [comment] 2017-06-20 18:55
@coreydaley I was able to confirm that `oc new-build git@github.com:some-org/repo.git` works with `oc v3.6.0-alpha.2+3c221d5` as expected. 

Note that `oc new-build ssh://git@github.com:some-org/repo.git` does not work and yields the same error I mentioned before.

**Comment by coreydaley** [comment] 2017-06-20 18:57
The oc new-build command worked fine for me but I'm building from source, so it's possible that the release doesn't have the fix for that one in it yet.

**Comment by coreydaley** [comment] 2017-06-20 19:00
Ok, i see the issue in the second example.

**Comment by coreydaley** [comment] 2017-06-20 19:16
@zuaresc 
It looks like ssh://git@github.com:username/repo.git is not a supported syntax for git, which we are using git ls-remote (which is where it is failing).

From the git-clone man page:

```
An alternative scp-like syntax may also be used with the ssh protocol:

       ·   [user@]host.xz:path/to/repo.git/

       This syntax is only recognized if there are no slashes before the first colon. This helps differentiate a local path that contains a colon. For example the local
       path foo:bar could be specified as an absolute path or ./foo:bar to avoid being misinterpreted as an ssh url.
```

**Comment by coreydaley** [comment] 2017-06-22 01:06
@zuaresc 
It looks like it's a git thing according to the man page, of which I pasted the related snippet.

I'm going to close this issue but feel free to re-open it if you think it is not resolved and we can discuss further.

**Closed by coreydaley** 2017-06-22 01:06 UTC
Labels: component/build, kind/question, priority/P2

**Comment by antonin07130** [comment] 2017-11-20 00:20
Hi, seems like it does not work for gitlab urls : steps to reproduce :
```bash
➜  oc new-app git@gitlab.forge.orange-labs.fr:fcng1847/timelost.git

error: Errors occurred while determining argument types:

git@gitlab.forge.orange-labs.fr:fcng1847/timelost.git as a Git repository URL:  parse git@gitlab.forge.orange-labs.fr:fcng1847/timelost.git:
```

**Comment by antonin07130** [comment] 2017-11-20 00:21
Additional information :
```
oc version                                                                                   
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://XXXXXXXXXX
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
```

**Comment by shake** [comment] 2018-03-05 05:40
I also have the same problem.

gitlab only support http, not support ssh,
