### ISSUE TITLE
CLI 'osc log' (singular) not aligned with plural forms of 'osc build-logs' and 'docker logs'

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1820] opened 2015-04-20 20:35 UTC
Noticed that I'm often accidentally typing "logs" and noticed in a demo as well.  It would be good to be consistent with various "logs" comments (at least accept "logs" in addition to "log")

**Comment by ncdc** [comment] 2015-04-20 20:45
Dupe of #1639

**Comment by liggitt** [comment] 2015-05-08 02:09
closing as dupe

**Closed by liggitt** 2015-05-08 02:09 UTC
