### ISSUE TITLE
Unable to create HTTP and HTTPS routes that point to the same host but different services or backend ports

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4848] opened 2015-09-29 15:29 UTC
It looks like the new route uniqueness code that went in recently may be preventing the valid use case of having a secure and unsecure route for the same host.  

Testing with unsecure and edge route:

```
[vagrant@openshiftdev openshift]$ oadm router --credentials="$KUBECONFIG" --service-account="default"
password for stats user admin has been set to skr6DjtK3G
deploymentconfigs/router
services/router

[vagrant@openshiftdev ~]$ git clone https://github.com/pweil-/hello-nginx-docker
[vagrant@openshiftdev ~]$ oc create -f hello-nginx-docker/openshift/nginx_pod.json 
pod "hello-nginx-docker" created
[vagrant@openshiftdev ~]$ oc create -f hello-nginx-docker/openshift/unsecure/service.json 
service "hello-nginx-http" created
[vagrant@openshiftdev ~]$ oc create -f hello-nginx-docker/openshift/unsecure/route.json 
route "route-unsecure" created
[vagrant@openshiftdev ~]$ curl -H Host:www.example.com 0.0.0.0
Hello World

[vagrant@openshiftdev ~]$ oc create -f hello-nginx-docker/openshift/edge/route.json 

[vagrant@openshiftdev ~]$ oc exec router-1-fexe1 -- cat /var/lib/haproxy/conf/os_edge_http_be.map
[vagrant@openshiftdev ~]$ oc exec router-1-fexe1 -- cat /var/lib/haproxy/conf/os_http_be.map
www.example.com default_route-unsecure
[vagrant@openshiftdev ~]$ oc exec router-1-fexe1 -- cat /var/lib/haproxy/conf/haproxy.config
<snip>
##-------------- app level backends ----------------


        
            
                
backend be_http_default_route-unsecure
                
  mode http
  option redispatch
  option forwardfor
  balance leastconn
  timeout check 5000ms
  http-request set-header X-Forwarded-Host %[req.hdr(host)]
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  
    cookie OPENSHIFT_default_route-unsecure_SERVERID insert indirect nocache httponly
    http-request set-header X-Forwarded-Proto http
  
  http-request set-header Forwarded for=%[src],host=%[req.hdr(host)],proto=%[req.hdr(X-Forwarded-Proto)]
                
  server 172.17.0.5:80 172.17.0.5:80 check inter 5000ms cookie 172.17.0.5:80
``

**Comment by ramr** [comment] 2015-10-06 06:55
@smarterclayton looks like this is some functionality that we don't have now with the duplicate routes code.  So one possible fix I can see for this is to add a check to ```unique_host.go for HandleRoute``` to check route type (secure/unsecure) and reject duplicates only if older and for the same type of route. That sound ok?

**Comment by smarterclayton** [comment] 2015-10-06 18:27
Do we *have* to support this use case?  Use case is?

**Comment by ramr** [comment] 2015-10-06 18:33
@pweil-  may be able to better explain what his use case was.
 
But I can sorta see some use cases here where someone wants to create 2 routes - one secure and one unsecured for the same host and serve protected content via the secure route (https://www.example.com) but serve all the assets (javascript/images/css etc) via the unsecured path.  Or even create two different types of routes (secured/unsecured) to say always force to https (the http one is just a redirector).

**Comment by pweil-** [comment] 2015-10-06 18:34
Use case is defining both `http://mysite.com` and `https://mysite.com` where I allow a portion of my site to be unsecure.  For instance a web app that allows you to go to their marketing area without https but uses https for the actual app itself.

The alternative here is to make the whole app secure if you need portion of the app secure.  Not terrible but a bit inconvenient.  Might be able to get around it by using path based routes.

**Comment by smarterclayton** [comment] 2015-10-06 18:40
Why would I need two routes for that?

**Comment by pweil-** [comment] 2015-10-06 18:42
> Why would I need two routes for that?

You do not get unsecure access by default when you define a secure route.  The resulting haproxy config is essentially the same but you will not have an entry in the unsecure map file.  That was intentional since we can't assume you want both http and https access if you ask for https.

**Comment by smarterclayton** [comment] 2015-10-06 18:43
Then we should add a flag to enable that in the TLS mode.  Or a constant.

**Comment by pweil-** [comment] 2015-10-06 18:43
> Then we should add a flag to enable that in the TLS mode. Or a constant.

you type faster than me

**Comment by smarterclayton** [comment] 2015-10-06 18:55
There have been two discussed modes.  Expose HTTP, Redirect to HTTPS.  So a
constant option `Insecure` which is one of `Redirect`, `Expose`, or
`None`|`Disabled` that is valid on terminate (and maybe in the future
passthrough).

**Comment by ramr** [comment] 2015-10-06 19:34
Ok - this is starting to sound more like an enhancement then (can we label it as such). I'll work on it but have a few other bugs to get done before this.

**Comment by pweil-** [comment] 2015-10-06 19:37
We allowed it before so it may be viewed a regression.  I would vote for leaving it high priority unless someone else thinks that it won't cause issues if it doesn't happen to get done.

**Comment by smarterclayton** [comment] 2015-10-06 20:39
They can argue it with me - fine for leaving it high priority though.

**Comment by knrc** [comment] 2015-10-16 16:52
@smarterclayton We have been relying on this behaviour within the middleware images since we can expose both HTTP and HTTPS endpoints, or indeed TLS protocols.  The secure endpoint is not necessarily a redirect of the insecure endpoint, they can deliver different content.

We definitely view this as a bug/regression as we can no longer expose our services on the same host.

**Comment by smarterclayton** [comment] 2015-10-16 19:53
Do you today deliver different content for 80 and 443?

On Oct 16, 2015, at 12:52 PM, knrc <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> We have been relying on
this behaviour within the middleware images since we can expose both HTTP
and HTTPS endpoints, or indeed TLS protocols. The secure endpoint is not
necessarily a redirect of the insecure endpoint, they can deliver different
content.

We definitely view this as a bug/regression as we can no longer expose our
services on the same host.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4848#issuecomment-148767349>.

**Comment by knrc** [comment] 2015-10-20 18:15
@smarterclayton Yes, delivering different content is possible with the current images and is a choice made by the application

**Comment by smarterclayton** [comment] 2015-10-20 18:38
What content is delivered?  We're debating taking away that flexibility for
simplicity and ease of use (for the easier cases), I need a strong use case
to justify keeping it.

**Comment by knrc** [comment] 2015-10-20 18:52
@smarterclayton That's completely up to the application.  For example EAP exposes an http and an https connector and a customer's application can choose which they wish to be exposed through, i.e. they may decide to expose one part through http://<host>/path and a second part through https://<host>/path.

This behaviour existed in previous releases, we could expose both http and https endpoints through the same hostname.

**Comment by smarterclayton** [comment] 2015-10-20 19:03
Why do you need those to go to two different services?  We're not proposing
removing support for both http and HTTPS on the same backend.  We can
definitely fix that support.

On Oct 20, 2015, at 2:52 PM, knrc <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> That's completely up to
the application. For example EAP exposes an http and an https connector and
a customer's application can choose which they wish to be exposed through,
i.e. they may decide to expose one part through http:///path and a second
part through https:///path.

This behaviour existed in previous releases, we could expose both http and
https endpoints through the same hostname.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4848#issuecomment-149666056>.

**Comment by knrc** [comment] 2015-10-20 19:12
@smarterclayton Perhaps I've misunderstood then, I thought you were looking for justification for having a secure and non-secure route for the same DNS hostname in order to expose different content on 80 and 443.

If we continue to support both 80/443 with the same DNS hostname, and that the content served is distinct, then you can ignore my comments :)

**Comment by smarterclayton** [comment] 2015-11-04 15:53
For 1.1 we support sending both 443 and 80 to the same backend port with https://github.com/openshift/origin/pull/5224 for edge terminated routes.  Allowing users to target different ports under the same hostname with different backend services is not going to make 1.1 (OSE 3.1) and will have to be planned as part of integration with upstream Ingress.  It's not impossible to support, but it's harder, so we'll need more time to debug it.

**Comment by gravis** [comment] 2015-11-14 21:54
#5224 fits our needs for now. I don't see a use-case where http would be serving content different from https. And if it was the case, it's probably worth creating a dedicated service for that, with a dedicated route.
The `insecureEdgeTerminationPolicy` covers most of the needs I think.

**Comment by smarterclayton** [comment] 2015-11-14 22:04
Great - if that changes please let us know

On Nov 14, 2015, at 4:54 PM, Philippe Lafoucrière <notifications@github.com>
wrote:

#5224 <https://github.com/openshift/origin/pull/5224> fits our needs for
now. I don't see a use-case where http would be serving content different
from https. And if it was the case, it's probably worth creating a
dedicated service for that, with a dedicated route.
The insecureEdgeTerminationPolicy covers most of the needs I think.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4848#issuecomment-156748617>.

**Comment by knobunc** [comment] 2016-06-10 17:32
@smarterclayton @pweil given the lack of commentary since #5224 landed, any opposition to closing this issue?

**Comment by smarterclayton** [comment] 2016-06-10 18:40
Can you link to the trello card for enabling ingress?  With ingress we
should have a unified solution (since a single ingress can be multiple
routes)

**Comment by knobunc** [comment] 2016-06-10 19:26
The "investigate upstream ingress" card is https://trello.com/c/UKmBGUi2/147-5-look-at-upstream-ingress-and-work-out-how-our-ingress-story-changes-e-g-does-the-router-go-away-change-what-traffic-ingress-sp

**Comment by pweil-** [comment] 2016-06-13 13:06
> given the lack of commentary since #5224 landed, any opposition to closing this issue

The only nuance to this would be the "different service" portion as #5224 only allows the same service.  If that isn't considered an important use case (don't think I have heard anyone asking for it) then I'm fine with closing this.

**Comment by smarterclayton** [comment] 2016-06-13 15:31
I think the ingress use case covers that as well.

**Closed** 2016-06-13 15:36 UTC
Labels: area/compatibility, component/routing, kind/bug, kind/enhancement, priority/P2
