### ISSUE TITLE
[extended] images: s2i: perl Dancer example [It] should work with hot deploy 

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5728] opened 2015-11-05 10:04 UTC
```console
 Failure [125.759 seconds]
images: s2i: perl Dancer example [It] should work with hot deploy 
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/s2i_perl.go:74

  Expected error:
      <*errors.errorString | 0xc2081380b0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/s2i_perl.go:34
------------------------------
    fail    images: s2i: perl Dancer example should work with hot deploy (2m5.758943984s)
```

@mnagy @bparees is this fixed? (appears in origin_extended build from yesterday)

**Comment by mnagy** [comment] 2015-11-05 12:11
@bparees please assign this to me, thanks

**Comment by mnagy** [comment] 2015-11-09 13:14
@mfojtik I couldn't reproduce this. But it seems it timed-out on build. The code has 20 minutes limit for waiting. It took me on my laptop 17 minutes. This seems a lot just to build an image for the test. I think it would be better if we changed the image from dancer to something else.

**Comment by mnagy** [comment] 2015-11-09 13:20
I will up the timeout for now and create a different issue to change the test to use something else that's not so time demanding, we don't want to have 20+ minute build time just for the hot deploy test. Plus we're testing Dancer in the sample repo test.

**Closed** 2015-11-14 01:23 UTC
Labels: priority/P2
