### ISSUE TITLE
test/cmd/builds.sh:64: multiple images or templates matched "openshift/origin:v1.1"

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8436] opened 2016-04-09 02:44 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/14357/console

```
FAILURE after 0.333s: test/cmd/builds.sh:64: executing 'oc new-build -D $'FROM openshift/origin:v1.1\nENV ok=1' --to origin-name-test --name origin-test2' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: multiple images or templates matched "openshift/origin:v1.1": 42
```

**Comment by smarterclayton** [comment] 2016-04-20 17:40
Dupe of https://github.com/openshift/origin/issues/7429

**Closed by smarterclayton** 2016-04-20 17:40 UTC
Labels: area/tests, kind/test-flake, priority/P2
