### ISSUE TITLE
e2e flake: [k8s.io] SchedulerPredicates [Serial] [It] validates that NodeSelector is respected if not matching [Conformance]

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#13731] opened 2017-04-12 10:13 UTC
```
[It] validates that NodeSelector is respected if not matching [Conformance]
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:234
STEP: Trying to schedule Pod with nonempty NodeSelector.
Apr 12 03:53:48.764: INFO: Timed out after 10m0s waiting for stable cluster.
[AfterEach] [k8s.io] SchedulerPredicates [Serial]
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:142
STEP: Collecting events from namespace "e2e-tests-sched-pred-kqwmt".
STEP: Found 0 events.
Apr 12 03:53:48.772: INFO: POD                                                        NODE                           PHASE    GRACE  CONDITIONS
Apr 12 03:53:48.772: INFO: docker-registry-2-zk5zl                                    ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:57 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:10:06 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:57 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: registry-console-1-t98mv                                   ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:43 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:53 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:43 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: router-2-hrx4g                                             ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:55 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:10:15 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:09:55 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: restricted-pod                                                                            Pending         [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:28 -0400 EDT Unschedulable }]
Apr 12 03:53:48.772: INFO: with-labels                                                ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:51 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:53 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:51 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: still-no-tolerations                                       ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:31 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:33 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:31 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: with-label-a5fcc535-1f53-11e7-ad75-0e3090256d22            ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:58 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:01 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:58 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: with-podantiaffinity-a7b00b51-1f53-11e7-ad75-0e3090256d22  ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:01 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:03 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:43:01 -0400 EDT  }]
Apr 12 03:53:48.772: INFO: svc-latency-rc-ft7t3                                       ip-172-18-11-224.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:06 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:08 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-04-12 03:42:06 -0400 EDT  }]
Apr 12 03:53:48.773: INFO: 
Apr 12 03:53:48.774: INFO: 
Logging node info for node ip-172-18-11-224.ec2.internal
Apr 12 03:53:48.776: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
Apr 12 03:53:48.776: INFO: 
Logging kubelet events for node ip-172-18-11-224.ec2.internal
Apr 12 03:53:48.778: INFO: 
Logging pods the kubelet thinks is on node ip-172-18-11-224.ec2.internal
Apr 12 03:53:48.784: INFO: docker-registry-2-zk5zl started at 2017-04-12 03:09:57 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container registry ready: true, restart count 0
Apr 12 03:53:48.784: INFO: with-labels started at 2017-04-12 03:42:51 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container pfpod ready: true, restart count 0
Apr 12 03:53:48.784: INFO: with-label-a5fcc535-1f53-11e7-ad75-0e3090256d22 started at 2017-04-12 03:42:58 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container pfpod ready: true, restart count 0
Apr 12 03:53:48.784: INFO: with-podantiaffinity-a7b00b51-1f53-11e7-ad75-0e3090256d22 started at 2017-04-12 03:43:01 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container pfpod ready: true, restart count 0
Apr 12 03:53:48.784: INFO: still-no-tolerations started at 2017-04-12 03:43:31 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container pfpod ready: true, restart count 0
Apr 12 03:53:48.784: INFO: registry-console-1-t98mv started at 2017-04-12 03:09:43 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container registry-console ready: true, restart count 0
Apr 12 03:53:48.784: INFO: router-2-hrx4g started at 2017-04-12 03:09:55 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container router ready: true, restart count 0
Apr 12 03:53:48.784: INFO: svc-latency-rc-ft7t3 started at 2017-04-12 03:42:06 -0400 EDT (0+1 container statuses recorded)
Apr 12 03:53:48.784: INFO: 	Container svc-latency-rc ready: true, restart count 0
W0412 03:53:48.786731   24139 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
Apr 12 03:53:48.973: INFO: 
Latency metrics for node ip-172-18-11-224.ec2.internal
STEP: Dumping a list of prepulled images on each node
Apr 12 03:53:48.974: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "e2e-tests-sched-pred-kqwmt" for this suite.
Apr 12 03:53:59.054: INFO: namespace: e2e-tests-sched-pred-kqwmt, resource: bindings, ignored listing per whitelist
[AfterEach] [k8s.io] SchedulerPredicates [Serial]
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:67
I0412 03:53:59.071676   24139 request.go:769] Error in request: resource name may not be empty

• Failure [612.111 seconds]
[k8s.io] SchedulerPredicates [Serial]
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:826
  validates that NodeSelector is respected if not matching [Conformance] [It]
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:234

  Apr 12 03:53:48.764: Timed out after 10m0s waiting for stable cluster.

  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:4726
------------------------------
SS

Summarizing 1 Failure:

[Fail] [k8s.io] SchedulerPredicates [Serial] [It] validates that NodeSelector is respected if not matching [Conformance] 
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_update/41/console
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/205/

Observed in https://github.com/openshift/openshift-ansible/pull/3757

----

Similar to:
https://github.com/openshift/origin/issues/9397
https://github.com/openshift/origin/issues/10182
https://github.com/openshift/origin/issues/13536

**Comment by aveshagarwal** [comment] 2017-12-12 18:53
it is duplicate of https://github.com/openshift/origin/issues/17682 so closing this.

**Closed by aveshagarwal** 2017-12-12 18:53 UTC
Labels: component/kubernetes, kind/test-flake, priority/P1
