### ISSUE TITLE
Query on /healtz causes an exception

### ISSUE THREAD

**Issue by mmahut** [openshift/origin#5114] opened 2015-10-14 11:31 UTC
When trying to query /healtz, I get error 500.

Affected versions:

```
openshift v3.0.2.0-17-g701346b
kubernetes v1.1.0-alpha.0-1605-g44c91b1
```
and
```
openshift v3.0.0.1-5-g279b678
kubernetes v0.17.1-804-g496be63
```

The backtrace:

```
I1014 07:28:09.224628    2309 server.go:588] GET /healthz: (1.072197ms) 500
goroutine 1664585 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209fb69c0, 0x1f4)
/builddir/build/BUILD/openshift-git-4.eab4c86/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/l
net/http.Error(0x7f7136f803d8, 0xc209fb69c0, 0xc2098a7680, 0x9e, 0x1f4)
/usr/lib/golang/src/net/http/server.go:1274 +0x9a fp=0xc208adda58 sp=0xc208add9c8
github.com/GoogleCloudPlatform/kubernetes/pkg/healthz.func·002(0x7f7136f803d8, 0xc209fb69c0, 0xc20a8cb040)
/builddir/build/BUILD/openshift-git-4.eab4c86/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/healthz/h
net/http.HandlerFunc.ServeHTTP(0xc208420210, 0x7f7136f803d8, 0xc209fb69c0, 0xc20a8cb040)
/usr/lib/golang/src/net/http/server.go:1265 +0x41 fp=0xc208addc08 sp=0xc208addbe8
net/http.(*ServeMux).ServeHTTP(0xc2083cbcb0, 0x7f7136f803d8, 0xc209fb69c0, 0xc20a8cb040)
/usr/lib/golang/src/net/http/server.go:1541 +0x17d fp=0xc208addc60 sp=0xc208addc08
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc208517300, 0x7f7136f803a0, 0xc208460460, 0xc2
/builddir/build/BUILD/openshift-git-4.eab4c86/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/s
net/http.serverHandler.ServeHTTP(0xc2081543c0, 0x7f7136f803a0, 0xc208460460, 0xc20a8cb040)
/usr/lib/golang/src/net/http/server.go:1703 +0x19a fp=0xc208addd08 sp=0xc208addcb0
net/http.(*conn).serve(0xc2084603c0)
/usr/lib/golang/src/net/http/server.go:1204 +0xb57 fp=0xc208addfd8 sp=0xc208addd08
runtime.goexit()
/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208addfe0 sp=0xc208addfd8
created by net/http.(*Server).Serve
/usr/lib/golang/src/net/http/server.go:1751 +0x35e
[[Wget/1.14 (linux-gnu)] 127.0.0.1:39479]

```

**Comment by mmahut** [comment] 2015-10-14 11:37
Please note /healtz/ping works fine.

**Comment by liggitt** [comment] 2015-10-14 11:39
Is this healthz on the kubelet or API server?

**Comment by mmahut** [comment] 2015-10-14 11:44
@liggitt this is on the openshift-node (kubelet).

**Comment by stevekuznetsov** [comment] 2015-10-15 03:50
I think this is a dupe of #4069. I have a stale beach that fixes this. I will revisit tomorrow.

**Comment by stevekuznetsov** [comment] 2015-10-15 03:50
Please assign me

**Comment by stevekuznetsov** [comment] 2015-10-15 12:42
This is on node, not master, I was incorrect.

**Comment by liggitt** [comment] 2015-12-09 15:10
@mmahut, are you still seeing this?

**Comment by liggitt** [comment] 2016-04-22 02:51
closing since I can't reproduce this, and due to age. please reopen if you still see this

**Closed by liggitt** 2016-04-22 02:51 UTC
Labels: component/restapi, kind/bug, priority/P2
