### ISSUE TITLE
osc log not working

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1734] opened 2015-04-14 18:36 UTC
```
osc log router-1-9y1sh
Error: 404 Not Found while accessing https://ose3-master.example.com:8443/api/v1beta3/proxy/minions/ose3-master.example.com/containerLogs/default/router-1-9y1sh/router?follow=false: 404: Page Not Found
```

This is true for any running pod.

```
osc v0.4.3.2
kubernetes v0.14.1-582-gb12d75d
```

**Comment by kargakis** [comment] 2015-04-14 22:21
This is an upstream issue. @smarterclayton is it related with [this](https://github.com/openshift/origin/issues/1714) and the latest Kube rebase?

**Comment by csrwng** [comment] 2015-04-15 13:31
The issue is that we're still using "minions" instead of "nodes" after switching to v1beta3 for the proxy call. It was fixed with this PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/6701
@smarterclayton should we cherry-pick that fix?

**Comment by smarterclayton** [comment] 2015-04-15 14:12
Yes

**Comment by csrwng** [comment] 2015-04-15 18:42
Fixed with https://github.com/openshift/origin/pull/1749

**Closed** 2015-04-16 15:10 UTC
Labels: bug

**Comment by sdodson** [comment] 2015-04-16 15:12
@csrwng confirmed, looks fixed.
