### ISSUE TITLE
server doesn't have a resource type "scc"

### ISSUE THREAD

**Issue by DanyC97** [openshift/origin#18302] opened 2018-01-26 12:48 UTC
Running Origin 3.7

```
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://370-lb1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

and being logged as `system` user with `cluster-admin` it seems i'm not longer able to run 

```
oc get scc
the server doesn't have a resource type "scc"
```
however using `oc get securitycontextconstraints` works.
Please note that i have not deployed serviceCatalog like is been mentioned [here](https://bugzilla.redhat.com/show_bug.cgi?id=1525014)

any idea why this changed behavior ?

**Comment by DanyC97** [comment] 2018-01-27 17:59
i've also run `oc get scc --loglevel=6` and i got everything captured in [here](https://hastebin.com/rokaleduxi.cs)

any help would be much appreciated

**Comment by DanyC97** [comment] 2018-01-27 18:02
and with `loglevel=8` i see

```
0127 17:59:58.803299   50713 round_trippers.go:383] GET https://370-lb1:8443/apis/grafana.com/v1
I0127 17:59:58.803355   50713 round_trippers.go:390] Request Headers:
I0127 17:59:58.803381   50713 round_trippers.go:393]     User-Agent: oc/v1.7.6+a08f5eeb62 (linux/amd64) kubernetes/c84beff
I0127 17:59:58.803402   50713 round_trippers.go:393]     Accept: application/json, */*
I0127 17:59:58.803424   50713 round_trippers.go:393]     Authorization: Bearer eCdbclJrLDrvv8e3ViLnUBz5h6UPanBEtCgze4IpGzI
I0127 17:59:58.805236   50713 round_trippers.go:408] Response Status: 404 Not Found in 1 milliseconds
I0127 17:59:58.805283   50713 round_trippers.go:411] Response Headers:
I0127 17:59:58.805307   50713 round_trippers.go:414]     Cache-Control: no-store
I0127 17:59:58.805329   50713 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I0127 17:59:58.805346   50713 round_trippers.go:414]     X-Content-Type-Options: nosniff
I0127 17:59:58.805365   50713 round_trippers.go:414]     Content-Length: 19
I0127 17:59:58.805384   50713 round_trippers.go:414]     Date: Sat, 27 Jan 2018 17:59:58 GMT
I0127 17:59:58.805419   50713 request.go:994] Response Body: 404 page not found
I0127 17:59:58.805555   50713 request.go:1196] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0127 17:59:58.805600   50713 cached_discovery.go:79] skipped caching discovery info due to the server could not find the requested resource
I0127 17:59:58.805669   50713 round_trippers.go:383] GET https://370-lb1:8443/apis/prometheus.io/v1
I0127 17:59:58.805701   50713 round_trippers.go:390] Request Headers:
I0127 17:59:58.805721   50713 round_trippers.go:393]     Accept: application/json, */*
I0127 17:59:58.805742   50713 round_trippers.go:393]     User-Agent: oc/v1.7.6+a08f5eeb62 (linux/amd64) kubernetes/c84beff
I0127 17:59:58.805763   50713 round_trippers.go:393]     Authorization: Bearer eCdbclJrLDrvv8e3ViLnUBz5h6UPanBEtCgze4IpGzI
I0127 17:59:58.807419   50713 round_trippers.go:408] Response Status: 404 Not Found in 1 milliseconds
I0127 17:59:58.807471   50713 round_trippers.go:411] Response Headers:
I0127 17:59:58.807494   50713 round_trippers.go:414]     Cache-Control: no-store
I0127 17:59:58.807515   50713 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I0127 17:59:58.807535   50713 round_trippers.go:414]     X-Content-Type-Options: nosniff
I0127 17:59:58.807562   50713 round_trippers.go:414]     Content-Length: 19
I0127 17:59:58.807588   50713 round_trippers.go:414]     Date: Sat, 27 Jan 2018 17:59:58 GMT
I0127 17:59:58.807636   50713 request.go:994] Response Body: 404 page not found
I0127 17:59:58.807766   50713 request.go:1196] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

is this the real issue ?  or is just red herring ...

**Comment by php-coder** [comment] 2018-01-29 14:29
I unable to reproduce it locally :(

@soltysh Do you have any pointers/ideas?

**Comment by soltysh** [comment] 2018-01-30 09:22
Yes, this might be related to https://bugzilla.redhat.com/show_bug.cgi?id=1525014 and https://github.com/openshift/origin/issues/17952

**Comment by php-coder** [comment] 2018-01-30 16:47
@DanyC97 Is your cluster was upgraded from 3.6 or it's a fresh installation? Also in the output I see complain about non-existent prometheus.io/v1 and grafana.com/v1 api groups. Are these third party resources or are they somehow related to service catalog? Do you know why they don't exist?

**Comment by DanyC97** [comment] 2018-02-01 10:58
@php-coder the cluster is a green deployment of 3.7, no upgrade from 3.6.
the non-existent groups they are due to service catalog which i have not enabled it however i don't know why they exist ...

i'll redeploy the cluster again and triple check ...

**Comment by DanyC97** [comment] 2018-02-08 18:16
@php-coder  i can confirm after a new cluster was deployed that i get the same behavior as mentioned above.

any chance you guys can look into this please ?

**Comment by php-coder** [comment] 2018-02-13 14:27
@DanyC97 How did you install your cluster? Did you use ansible installer? What OS do you have on the nodes?

If you can provide an access to your cluster, let me know, this will streamline the process.

**Comment by php-coder** [comment] 2018-02-13 14:38
> the non-existent groups they are due to service catalog which i have not enabled it however i don't know why they exist ...

@DanyC97 as this information could be related, all the additional details also could help. Could you share installer configuration, for example? (of course, don't forget to mask all the sensitive information)

**Comment by DanyC97** [comment] 2018-02-13 23:25
@php-coder see below:

> OS on the nodes
```
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

```

>Did you use ansible installer
yes

Regarding access to cluster, i can setup a webex if that works for you, i'm in Europe. will that work for you ?

**Comment by php-coder** [comment] 2018-02-14 17:39
@DanyC97 Could you share installer configuration? And is there a special reason of why you're using 3.7 instead of 3.7.1?

**Comment by DanyC97** [comment] 2018-02-14 22:51
@php-coder i'd love to use 3.7.1 but the rpms are not available in CentOS repo unfortunately. If you can help on that i'll move to 3.7.1 in a blink of an eye ;)

I'll sanitize and share the inventory file shortly

**Comment by php-coder** [comment] 2018-02-23 13:35
As there is workaround and not so many people affected by this, I'm lowering priority to P2.

**Comment by php-coder** [comment] 2018-02-23 13:37
@DanyC97 Do [these steps](https://bugzilla.redhat.com/show_bug.cgi?id=1525014#c12) work for you?

**Comment by php-coder** [comment] 2018-02-23 13:51
> the non-existent groups they are due to service catalog which i have not enabled it however i don't know why they exist ...

I don't know whether service catalog enabled by default or it's not. Perhaps, if you don't use it, you have to explicitly disable it.

@openshift/team-service-catalog @sdodson Is the Service Catalog is enabled by default in installer (and if yes, from what version)?

**Comment by sdodson** [comment] 2018-02-23 21:01
> @openshift/team-service-catalog @sdodson Is the Service Catalog is enabled by default in installer (and if yes, from what version)?

Yes it's enabled by default in 3.7 onwards.

**Comment by DanyC97** [comment] 2018-03-02 11:37
thanks @php-coder @sdodson for your help.

@php-coder those steps are not needed for me as i've disabled the catalog during deployment.
since then i've try to reproduce it by redeploying many times and i never got the same behviour again. there is s'thing fishy but since i can't reproduce it after dozen of re-deployments am happy to close it.

**Comment by DanyC97** [comment] 2018-03-02 11:38
up to you if you want to keep it open in case it might help someone from your team looking at the debug log  where is clear that is failing to parse the output hence it bombs out.

How you get there is _unknown_

**Comment by php-coder** [comment] 2018-03-02 11:46
@DanyC97 Thanks for feedback! Let's close it then.

/close

**Closed by php-coder** 2018-03-02 11:46 UTC
Labels: component/service-catalog, kind/bug, priority/P2

**Comment by wujm2017** [comment] 2018-03-15 08:41
i have  deployed serviceCatalog(v3.7.0 default is have servicecatalog enable),but i  "oc get scc" ,is show "server doesn't have a resource type "scc"",,,,pls help me ,thanks

**Comment by php-coder** [comment] 2018-03-15 09:05
@elenckb https://github.com/openshift/origin/issues/18302#issuecomment-368010802

**Comment by elenckb** [comment] 2018-04-02 10:34
@php-coder  This problem has not been solved.  the cluster is deployment of 3.7.0 , no upgrade from 3.6,

**Comment by jpeeler** [comment] 2018-04-02 13:47
While I can appreciate the woes of RPMs not being updated, this problem has been fixed several months ago. If you use an ansible installer after 3.7.23, you should find the issue resolved. You could try using a tag from the openshift/openshift-ansible repo, however if you want to stick with using RPMs use the openshift-ansible git package. I see as of this moment 3.7.35 is available: http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin37/
