### ISSUE TITLE
Templatebroker fails to get clients in HA master mode?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15415] opened 2017-07-22 18:57 UTC
```
:68] Template service broker: failed to initialize clients: Could not get token for openshift-infra/template-service-broker
p: TLS handshake error from 127.0.0.1:57164: remote error: tls: bad certificate
```

Saw this from the controllers when configuring an HA master with template broker on in master branch.

**Comment by jim-minter** [comment] 2017-07-31 15:58
dupe of #15405

**Closed by jim-minter** 2017-07-31 15:58 UTC
