### ISSUE TITLE
oc policy add-role-to-user doesn't help me find what are the valid roles

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#9409] opened 2016-06-17 20:18 UTC
To help with usability of the `oc policy add-role-to-user` it would be helpful if it guided you to find what valid roles there are.

##### Version
oc version
oc v1.3.0-alpha.1-411-g13d4b7e-dirty
kubernetes v1.3.0-alpha.3-599-g2746284

##### Steps To Reproduce

I'd expect either this command:
` oc policy add-role-to-user -h`
or this command
`oc policy add-role-to-user`
to help me to know how to provide a valid next argument.

Though the help text doesnt' tell me and leaving the option off doesn't help me
```
$ oc policy add-role-to-user
error: you must specify a role
See 'oc policy add-role-to-user -h' for help and examples.
```

**Comment by mfojtik** [comment] 2016-09-08 11:14
dupe of: https://github.com/openshift/origin/issues/10282

**Closed by mfojtik** 2016-09-08 11:14 UTC
Labels: component/auth, component/cli, kind/enhancement, priority/P2
