### ISSUE TITLE
post deployment hooks are concatenated

### ISSUE THREAD

**Issue by djdevin** [openshift/origin#12681] opened 2017-01-26 18:07 UTC
I set up a deployment configuration with some post-deploy commands, but they are concatenated:

![commands](https://cloud.githubusercontent.com/assets/418136/22343936/02ecade2-e3c8-11e6-9e22-434afbdbb381.png)

The resulting output from the deploy indicates it isn't running the commands separately:

```
--> post: Running hook pod ...
one two
--> post: Success
```

##### Version
OpenShift Master:
v1.4.1+3f9807a
Kubernetes Master:
v1.4.0+776c994

##### Steps To Reproduce
1. Set up a DC with multiple post-deploy commands

##### Current Result
1. Commands are concatenated, the final command is "echo one two" instead of "echo && one && two" or breaks.

##### Expected Result
1. Commands should be run individually

**Comment by djdevin** [comment] 2017-01-26 18:10
Might help more, this was using the multiline command (linebreaks appear not to work)

```
container_linux.go:247: starting container process caused "exec: \"drush -l client -y updb --cache-clear=0\\ndrush -l client -y cc all\\ndrush -l client -y fra\": executable file not found in $PATH"
```

**Comment by spadgett** [comment] 2017-01-31 13:07
@djdevin This is working as intended, although I agree it's confusing. You're building a command argument by argument. The editor lets you specify arguments with spaces and special characters without worrying about escaping. It's meant to be one command, though.

We'll see if we can make it more intuitive.

**Comment by jwforres** [comment] 2017-02-02 18:21
Closing since this is being tracked in the web console repo https://github.com/openshift/origin-web-console/issues/1192

**Closed by jwforres** 2017-02-02 18:21 UTC
Labels: area/usability, component/deployments, component/web, kind/bug, priority/P2
