### ISSUE TITLE
[flake] ci/openshift-jenkins/integration TestScopedProjectAccess failure

### ISSUE THREAD

**Issue by dcbw** [openshift/origin#16703] opened 2017-10-05 17:02 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16661/test_pull_request_origin_integration/8912/

**Comment by mfojtik** [comment] 2017-10-11 13:14
Briefly looking at the log, it seems like we observed addition of project "four" (as seen in events) but for some reason List() does not returned it back. The "allBobConfig" permits viewing all projects in cluster.

@deads2k @liggitt any clues?

**Comment by bparees** [comment] 2017-10-11 19:46
dupe of https://github.com/openshift/origin/issues/16716
(this one was older but the other one is a p0)

**Closed by bparees** 2017-10-11 19:46 UTC
Labels: component/kubernetes, kind/test-flake, priority/P1
