### ISSUE TITLE
[deployment config] stuck endlessly creating pods that will error

### ISSUE THREAD

**Issue by rawlingsj** [openshift/origin#1214] opened 2015-03-03 20:24 UTC
I've got a deployment config that is deploying an image however there's an error in the pod when it's starting.  At first I didn't notice it but after a while I checked and I had thousands of Exited containers, this causes high CPU usage by docker and eventually my machine became unresponsive.

Would there be any value in having a max number of deployment attempts attribute or something else to protect against this?  There may already be something but I've had a look but couldn't see anything.

**Comment by smarterclayton** [comment] 2015-03-06 05:14
I think that's reasonable.

**Comment by ironcladlou** [comment] 2015-03-06 14:40
@rawlingsj 

Thanks for the use case. Do you mean that your deployment config contains a pod template which references a docker image which will always error when a container using that image is started?

**Comment by rawlingsj** [comment] 2015-03-08 00:06
hi @ironcladlou, yes it's as you've described.  If it helps the build config I'm using is below which you should be able to run.  Just getting to grips with it all so there's every chance there's something in the way I've set up the triggers that's causing the problem, but if that's the case there maybe something we can do to protect against this endless loop.

```json
{
   "annotations":{
      "description":"fabric8 v2 and openshift v3 example"
   },
   "apiVersion":"v1beta1",
   "kind":"List",
   "items":[
      {
         "apiVersion":"v1beta1",
         "kind":"BuildConfig",
         "metadata":{
            "labels":{
               "container":"java",
               "group":"quickstarts"
            },
            "name":"camel-cdi-build"
         },
         "parameters":{
            "output":{
          "to": {
            "name": "example-camel-cdi"
          }
            },
            "source":{
               "git":{
                  "uri":"https://github.com/rawlingsj/example-camel-cdi.git"
               },
               "type":"Git"
            },
            "strategy":{
               "stiStrategy":{
                  "builderImage":"fabric8/java-main"
               },
               "type":"STI"
            }
         },
         "triggers":[
            {
               "github":{
                  "secret":"secret101"
               },
               "type":"github"
            },
            {
               "generic":{
                  "secret":"secret101"
               },
               "type":"generic"
            }
         ]
      },
      {
         "apiVersion":"v1beta1",

         "kind":"ImageRepository",
         "metadata":{
            "labels":{
              "name":"example-camel-cdi"
            },
            "name":"example-camel-cdi"
         }
      },
      {
         "apiVersion":"v1beta2",
         "containerPort":8778,
         "id":"camel-cdi-service",
         "metadata":{
            "name":"camel-cdi-service"
         },
         "kind":"Service",
         "port":8778,
         "selector":{
            "container":"java",
            "group":"quickstarts"
         }
      },
      {
         "apiVersion":"v1beta1",
         "kind":"DeploymentConfig",
         "metadata":{
            "name":"camel-cdi-deploy-config"
         },
         "template":{
            "controllerTemplate":{
               "podTemplate":{
                  "desiredState":{
                     "manifest":{
                        "containers":[
                           {
                              "image":"example-camel-cdi",
                              "name":"example-camel-cdi",
                              "ports":[
                                 {
                                    "containerPort":8778
                                 }
                              ]
                           }
                        ],
                        "version":"test"
                     }
                  },
                  "labels":{
                     "container":"java",
                     "group":"quickstarts"
                  }
               },
               "replicaSelector":{
                  "container":"java",
                  "group":"quickstarts"
               },
               "replicas":1
            },
            "strategy":{
               "type":"Recreate"
            }
         },
         "triggers":[
            {
               "type":"ImageChange",
               "imageChangeParams":{
                  "automatic":true,
                  "containerNames":[
                     "example-camel-cdi"
                  ],
                  "from": {
                     "name": "example-camel-cdi"
                  },
                  "tag":"latest"
               }
            }
         ]
      }
   ]
}
```

**Comment by ironcladlou** [comment] 2015-03-09 14:18
@pmorie @smarterclayton @bparees 

I haven't yet tried to reproduce this use case, but I can imagine that if a build succeeds and produces a new image which can't actually be used to run containers for whatever reason, the following would happen:

1. Deployment is triggered based on new tag
2. Deployment strategy turns up the replicas for the new deployment
3. Kubelet spins up containers
4. Containers fail, Kubelet retries forever based on RestartPolicy
5. A mountain of dead containers is produced

The current Recreate deployment strategy isn't concerned with whether the pods in the deployment ever enter a ready state. Replica counts are juggled and that's the end of the strategy's responsibilities.

Should the strategy take on the responsibility of waiting for *N* pods to become ready, where *N* is the deployment template's replica count? This still doesn't solve the following:

1. Pods in a ready state aren't necessarily solvent- only user defined health checks can make that determination
2. If the pods are spinning due to failing containers, only a RestartPolicy or the deletion of the deployment can short circuit the spinning
  1. If a RestartPolicy is applied to the deployment template, I believe we can detect terminal states for the pods and could then at least know that the deployment itself has failed.
    1. At this point we have lots of tricky issues with failure modes as described with hook failures in #1224.
  2. Without a RestartPolicy, how can the deployment controller decide when a pod has no chance of ever entering a ready state? I don't know that the deployment controllers can make that decision without more API to signal things like maximum times to wait for pod readiness.

Are there any aspects of this I haven't covered, or some simple solution I haven't thought of?

**Comment by smarterclayton** [comment] 2015-03-09 14:25
----- Original Message -----
> @pmorie @smarterclayton @bparees
> 
> I haven't yet tried to reproduce this use case, but I can imagine that if a
> build succeeds and produces a new image which can't actually be used to run
> containers for whatever reason, the following would happen:
> 
> 1. Deployment is triggered based on new tag
> 2. Deployment strategy turns up the replicas for the new deployment
> 3. Kubelet spins up containers
> 4. Containers fail, Kubelet retries forever based on RestartPolicy
> 5. A mountain of dead containers is produced

5 is a flaw in the Kubelet.

> 
> The current Recreate deployment strategy isn't concerned with whether the
> pods in the deployment ever enter a ready state. Replica counts are juggled
> and that's the end of the strategy's responsibilities.
> 
> Should the strategy take on the responsibility of waiting for *N* pods to
> become ready, where *N* is the deployment template's replica count? This
> still doesn't solve the following:
> 
> 1. Pods in a ready state aren't necessarily solvent- only user defined health
> checks can make that determination
> 2. If the pods are spinning due to failing containers, only a RestartPolicy
> or the deletion of the deployment can short circuit the spinning
>   1. If a RestartPolicy is applied to the deployment template, I believe we
>   can detect terminal states for the pods and could then at least know that
>   the deployment itself has failed.
>     1. At this point we have lots of tricky issues with failure modes as
>     described with hook failures in #1224.

It's the Kubelet's decision to control this behavior and mark pods as not ready or perm failed.  The replication controllers should recognize perm failed.  The deployment process will eventually need to recognize perm failed.  At a minimum, the deployment process needs to observe the rollout of the deployment for failure-like behavior and fail fast (readiness, timeouts).  For recreate.... there's not much you can do (intentionally).  For rolling update, this has to work.

>   2. Without a RestartPolicy, how can the deployment controller decide when a
>   pod has no chance of ever entering a ready state? I don't know that the
>   deployment controllers can make that decision without more API to signal
>   things like maximum times to wait for pod readiness.

All service containers have a restart policy.  Maximum wait for readiness is a part of any imperative process that mutates pods, so it's not unreasonable that should exist.

**Comment by ironcladlou** [comment] 2015-03-09 14:36
>>5. A mountain of dead containers is produced

>5 is a flaw in the Kubelet.

Okay, so dead container accumulation is beside the point.

>It's the Kubelet's decision to control this behavior and mark pods as not ready or perm failed.  The replication controllers should recognize perm failed.  The deployment process will eventually need to recognize perm failed.  At a minimum, the deployment process needs to observe the rollout of the deployment for failure-like behavior and fail fast (readiness, timeouts).  For recreate.... there's not much you can do (intentionally).  For rolling update, this has to work.

... 

>All service containers have a restart policy.  Maximum wait for readiness is a part of any imperative process that mutates pods, so it's not unreasonable that should exist.

Should this issue basically serve as a use case for rolling deployment? I agree that the rolling strategy will need to start taking terminal states into account and also deal with failure modes arising from failed pods.

**Comment by smarterclayton** [comment] 2015-03-10 21:39
Yes, and the primary mechanism needs to be the upstream rolling update code (let's get the behavior right there).

**Comment by rawlingsj** [comment] 2015-04-01 12:10
Not sure if this is the same problem but the same effect occurs if a replication controller is created which starts a pod that errors when launching.  The failed pod is left 'Exited' and 30 seconds later a new pod is scheduled.

Also even if the replication controller is deleted the pods are still endlessly scheduled. 

Thought it might be related to this issue but happy to raise another one here or upstream if more appropriate.

**Comment by smarterclayton** [comment] 2015-04-01 13:49
Hrm, it might be something to raise upstream.  I'm not sure.

**Comment by rawlingsj** [comment] 2015-04-01 14:04
ok thanks @smarterclayton raised https://github.com/GoogleCloudPlatform/kubernetes/issues/6291

**Comment by danmcp** [comment] 2015-05-11 23:11
Closed in response to upstream.

**Closed by danmcp** 2015-05-11 23:11 UTC
Labels: kind/bug

**Comment by sdodson** [comment] 2015-05-12 13:02
https://github.com/GoogleCloudPlatform/kubernetes/issues/4121
