### ISSUE TITLE
test_branch_origin_extended_image_ecosystem basic deploy timeout

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#16662] opened 2017-10-03 17:29 UTC
See https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/237/display/redirect from the devexp overnight ext test runs

Basic launch of jenkins via the jenkins-ephemeral template (https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/jenkins-ephemeral-template.json) timed out.

When looking at the post failure diagnostic dump, these series of events caught our eye, with the deploy pod stuck in pending:

```
STEP: Found 4 events.
Oct  3 16:00:25.240: INFO: At 2017-10-03 15:45:24 +0000 UTC - event for jenkins: {deploymentconfig-controller } DeploymentCreated: Created new replication controller "jenkins-1" for version 1
Oct  3 16:00:25.240: INFO: At 2017-10-03 15:45:24 +0000 UTC - event for jenkins-1-deploy: {default-scheduler } Scheduled: Successfully assigned jenkins-1-deploy to ip-172-18-11-139.ec2.internal
Oct  3 16:00:25.240: INFO: At 2017-10-03 15:45:24 +0000 UTC - event for jenkins-1-deploy: {kubelet ip-172-18-11-139.ec2.internal} SuccessfulMountVolume: MountVolume.SetUp succeeded for volume "deployer-token-t0d81" 
Oct  3 16:00:25.240: INFO: At 2017-10-03 15:45:25 +0000 UTC - event for jenkins-1-deploy: {kubelet ip-172-18-11-139.ec2.internal} FailedSync: Error syncing pod
Oct  3 16:00:25.244: INFO: POD                       NODE                           PHASE    GRACE  CONDITIONS
Oct  3 16:00:25.244: INFO: docker-registry-1-95kcb   ip-172-18-11-139.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:42:56 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:43:16 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:42:56 +0000 UTC  }]
Oct  3 16:00:25.244: INFO: registry-console-1-pdh27  ip-172-18-11-139.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:43:34 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:44:44 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:43:33 +0000 UTC  }]
Oct  3 16:00:25.244: INFO: router-1-2fw5t            ip-172-18-11-139.ec2.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:42:08 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:42:28 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 14:42:08 +0000 UTC  }]
Oct  3 16:00:25.244: INFO: jenkins-1-deploy          ip-172-18-11-139.ec2.internal  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 15:45:24 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-10-03 15:45:24 +0000 UTC ContainersNotReady containers with unready status: [deployment]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-03 15:45:24 +0000 UTC  }]

```

when looking at the node logs, see a ton of these:

```
E1003 16:14:33.047405   29126 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "jenkins-1-deploy_extended-test-jenkins-plugin-mxkc5-g0k49-jenkins(df041c02-a851-11e7-83d9-0e3a6aed2fa0)" failed: rpc error: code = 2 desc = unable to pull sandbox image "openshift/origin-pod:c199797": manifest unknown: manifest unknown
```

env/space issue?  garbage collection cleaned up something it shouldn't have ?
@openshift/devex @mfojtik @stevekuznetsov FYI

**Comment by stevekuznetsov** [comment] 2017-10-03 18:02
`manifest unknown: manifest unknown` makes me think @mfojtik

**Comment by mfojtik** [comment] 2017-10-11 13:22
wrong, @bparees problem now :-)

**Comment by bparees** [comment] 2017-10-11 14:05
as discussed on irc, the issue here is that the origin-pod image is supposed to be available locally (it was built by the CI process).  It's not supposed to be in a registry, so the pull failure is not a surprise.

the problem is that the local image was apparently not available (which caused the pull attempt to happen).

So what needs to be investigated is what caused the pod image to be deleted from the local system.  Previously this was determined to be an image GC issue, so assigning to @sjenning, but he'll want to talk to @derekwaynecarr who investigated these issues previously.

Of course the short term fix could be to increase the storage on the machines @stevekuznetsov 

But we really don't want GC deleting infrastructure images if it can be helped.

**Comment by mfojtik** [comment] 2017-10-11 14:07
@sjenning likely need an whitelist of images the kubelet should never delete (like origin-pod or deployer?)

**Comment by stevekuznetsov** [comment] 2017-10-11 14:09
If we have more recent logs we can check the `journald` output for image GC messages

**Comment by sjenning** [comment] 2017-11-29 16:49
@mfojtik any whitelisting would have to be a nasty carry patch.

We also have this https://github.com/openshift/origin/issues/17352.

Should we just configure the instances with larger disks if we are hitting GC and NodeDiskPressure?

**Comment by stevekuznetsov** [comment] 2017-11-29 17:04
Have we hit this recently? Do we have logs? If not we can close...

**Comment by bparees** [comment] 2017-11-29 17:11
@stevekuznetsov if we don't have logs, then i don't want this closed w/o updates that will ensure next time we *do* have the logs we need to investigate it.

**Comment by sjenning** [comment] 2017-12-01 19:00
@aveshagarwal PTAL

**Comment by aveshagarwal** [comment] 2018-01-31 18:51
I can not open the original link https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/237/display/redirect

Do we still want to keep it open? Not sure if the issue occurred again. If not, is it ok to close this?

**Comment by bparees** [comment] 2018-01-31 18:57
this was most likely caused by image gc which has been resolved by increasing storage, we can close it.

**Closed by bparees** 2018-01-31 18:57 UTC
Labels: area/infrastructure, component/apps, kind/test-flake, priority/P1
