### ISSUE TITLE
Rename docker-registry to registry

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8849] opened 2016-05-11 20:58 UTC
Deserves its own issue.

cc: @miminar @legionus @smarterclayton @aweiteka @soltysh

**Comment by smarterclayton** [comment] 2016-05-11 21:00
Yes.

**Comment by detiber** [comment] 2016-07-06 17:24
Is this something we are still looking to address for 1.3/3.3?

**Comment by smarterclayton** [comment] 2016-07-07 05:43
I don't see it happening at this point.  We need to get the DNS stuff set
up first - as part of that, we'll want to lock the name.  The problem is
that we may want to move the registry to a different namespace at that
point.

**Comment by detiber** [comment] 2016-07-07 16:02
@smarterclayton thanks for the clarification, it would be nice to have a reserved IP for the registry service as well to more easily manage the NO_PROXY configs.

**Comment by sanapir** [comment] 2017-05-17 20:13
Apparently there is some discussion to DNS being put into this in #8849.

**Comment by bparees** [comment] 2018-02-06 17:17
the ship has pretty clearly sailed on this one. closing.

**Closed by bparees** 2018-02-06 17:17 UTC
Labels: component/imageregistry, priority/P2

**Comment by miminar** [comment] 2018-02-16 10:47
This gives us opportunity to:

1. make a new deployment(config)/registry for quay
2. deprecate dc/docker-registry
3. profit

:smile:

**Comment by smarterclayton** [comment] 2018-02-16 19:58
We aren't going to be removing the integrated registry anytime soon.
However, we may just move to an operator model to deploy the registry
component in which case the migration can potentially be handled in that.
