### ISSUE TITLE
Fix or skip upstream extended tests

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6882] opened 2016-01-28 16:59 UTC
Extracted from https://github.com/openshift/origin/pull/6320

- resolve SCC issues in e2e tests that create privileged resources in BeforeEach (specifically e2e/kubectl.go)
- Proxy version v1 [It] should proxy to cadvisor [Conformance] test/e2e/proxy.go:277 (fails previously)
- [Example] ClusterDns [It] should create pod that uses dns [Conformance] test/e2e/example_cluster_dns.go:155 (new test)
- Networking [It] should provide Internet connection for containers [Conformance] test/e2e/networking.go:79 (fails previously)
- Kubelet regular resource usage tracking [It] for 0 pods per node over 20m0s te2e/kubelet_perf.go:137 (new test)
- Kubelet regular resource usage tracking [It] for 40 pods per node over 20m0s test/e2e/kubelet_perf.go:71(new test)
- KubeProxy [It] should test kube-proxy test/e2e/kubeproxy.go:439 (was skipped previously)

**Comment by timothysc** [comment] 2016-02-01 17:33
Here is my current list against a deployed cluster of origin/master as of last Thursday: 

https://paste.fedoraproject.org/317200/54347808/

34 Tests are failing, still TBD which ones we can ignore.

**Comment by timothysc** [comment] 2016-02-01 20:19
On inspection, a fair number of pods are failing to run during testing with similar errors...

$ sudo docker logs 3bfa2ba69d65
2016/02/01 20:11:20 listen tcp :80: bind: permission denied

**Comment by jayunit100** [comment] 2016-02-09 23:00
`test-origin --extended core -d --skip-check --skip-image-cleanup`   appears to be the command being run here.  I can also repro via running e2e's the 'normal' way.

**Comment by jayunit100** [comment] 2016-02-13 17:12
Looks to me like these are whittled down to a few Selinux and Storage tests now... 

```
 Extended Core.Security Context [Feature:SecurityContext] should support volume SELinux relabeling	55 sec	1
 Extended Core.Security Context [Feature:SecurityContext] should support volume SELinux relabeling when using hostIPC	1 min 56 sec	1
 Extended Core.Security Context [Feature:SecurityContext] should support volume SELinux relabeling when using hostPID	34 sec	1
 Extended Core.Volumes [Feature:Volumes] GlusterFS should be mountable	6 min 1 sec	1
 Extended Core.Volumes [Feature:Volumes] iSCSI should be mountable	5 min 50 sec	1
 Extended Core.Volumes [Feature:Volumes] Ceph RBD should be mountable	5 min 45 sec	1
 Extended Core.[jenkins] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test case execution	
```

**Comment by jayunit100** [comment] 2016-02-14 16:48
Also, found flakes in some of the Storage tests #7291 .  These might cause some problems in the future if we dont skip or make them robust.

**Comment by soltysh** [comment] 2016-02-25 10:44
Since upstream PR got merged we can start addressing this issue, @deads2k @liggitt @pweil- @kargakis whoever will be doing next rebase drop [UPSTREAM: 12221: Allow custom namespace creation in e2e framework](https://github.com/pweil-/kubernetes/commit/055d8eccf9942063113b174b98535f82618327db) commit, I'll help updating the necessary code to use the right approach here.

**Comment by timothysc** [comment] 2016-02-26 22:23
@jayunit100 Please update with your latest results on this ticket and link new issues to this one.

**Comment by jayunit100** [comment] 2016-02-26 23:32
On my current cluster, here's what seem to fail. 
- [ hostPath: Conformance test failing consistently ]
- [ ConfigMap: should be consumable via environment variable] 
- [ Kubelet: regular resource usage tracking  ]
- [ NodeOutOfDisk: runs out of disk space ]
- [ KubeProxy: should test kube-proxy ]
- [ Proxy: version v1 [It] should proxy to cadvisor Conformance ]

( we should check off the ones we dont care about / already skip / fail only in fragile configuration/large clusters )

**Comment by liggitt** [comment] 2016-02-27 02:44
> Proxy: version v1 [It] should proxy to cadvisor Conformance 

we disable unsecured cadvisor network access

**Comment by timothysc** [comment] 2016-02-29 15:02
> All of the deployment tests

Until there is parity I think this will still remain.

**Comment by jayunit100** [comment] 2016-03-07 16:03
These two are the last two bits for getting it all working.   7820 is now merged, so just 22613...

- https://github.com/openshift/origin/pull/7820
- https://github.com/kubernetes/kubernetes/pull/22613 
merge

So I think we can close soon.  I'll of course doublecheck the CI .

**Comment by jayunit100** [comment] 2016-03-09 19:34
ok folks, I'm pretty sure *we can finally close this.*  There may be a new issue that popped up or pops up, but the overall first pass is done and there is no test listed in here which isnt now either skipped or fixed......

**Comment by jayunit100** [comment] 2016-03-09 20:03
@liggitt  i mean to say, im assuming https://github.com/openshift/origin/issues/7903 <- this is a good placeholder, and we could close this ticket since there is alot of noise in it, and all the tests that were causing problems now appear to be working with the SCC/hostPath non-Conformance annotations/Volumes nonnginx mods.

**Comment by jayunit100** [comment] 2016-03-09 20:13
@liggitt  ok, currently we have four failing extended tests on master.
```
    Extended Core.Services should serve a basic endpoint from pods [Conformance]
    Extended Core.EmptyDir volumes should support (non-root,0666,tmpfs) [Conformance]
    Extended Core.Kubectl client Kubectl label should update the label on a resource [Conformance]
    Extended Core.EmptyDir wrapper volumes should becomes running
```
- ive confirmed all emptyDir tests passing on OSE, so those are probably flake.
- Kubectl/service basic endpoint Im not sure about.
But the list is significantly lower now, and i dont see any overlap with this and the original issue.

**Comment by sgallagher** [comment] 2016-04-12 13:02
@jayunit100 @liggitt 
Just to confirm, the following are the remaining tests that need investigation:
```
    Extended Core.Services should serve a basic endpoint from pods [Conformance]
    Extended Core.EmptyDir volumes should support (non-root,0666,tmpfs) [Conformance]
    Extended Core.Kubectl client Kubectl label should update the label on a resource [Conformance]
    Extended Core.EmptyDir wrapper volumes should becomes running
```

**Comment by jayunit100** [comment] 2016-04-12 15:05
Yes these are new failures  which are sort of different then the original issue.  Should we close this and carry on in #7903 ?

**Comment by sgallagher** [comment] 2016-04-12 15:22
@jayunit100 
OK, this was assigned to me the other day, so I was trying to get a handle on what it entailed, but it looks like #7903 is in your court?

@pweil- Should I keep working on this, split the work with @jayunit100 or other?

**Comment by pweil-** [comment] 2016-04-12 15:27
No need for two of the same thing.  Let's consolidate.  Feel free to split the work if necessary.  

Closing in favor of #7903

**Closed by pweil-** 2016-04-12 15:27 UTC
Labels: area/techdebt, area/tests, priority/P2
