### ISSUE TITLE
e2e container exec failure flake

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6444] opened 2015-12-21 15:37 UTC
Flake in e2e [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8032/console):
```
[INFO] Running a CLI command in a container using the service account
Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
Error attaching, falling back to logs: error executing remote command: Error executing command in container: container not found ("cli-with-token")
I1221 15:24:52.828412       1 factory.go:103] Using in-cluster configuration
I1221 15:24:52.843709       1 factory.go:103] Using in-cluster configuration
I1221 15:24:52.845512       1 factory.go:103] Using in-cluster configuration
In project test on server https://172.30.0.1:443

2 warnings identified, use 'oc status -v' to see details.

[FAIL] !!!!! Test Failed !!!!
```

**Comment by liggitt** [comment] 2015-12-23 17:33
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8032/console
Error was:
```
Error from server: 501: All the given peers are not reachable (failed to propose on members [https://172.18.9.207:4001] twice [last error: Unexpected HTTP status code]) [0]
!!! Error in hack/../test/end-to-end/core.sh:160
	'oc delete pod cli-with-token' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:160 main(...)
Exiting with status 1
```
Probably the same issue as https://github.com/openshift/origin/issues/6447, but in e2e

**Comment by liggitt** [comment] 2015-12-23 20:43
finally captured log at https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4475/artifact/origin/artifacts/e2e/logs/cli-with-token2.log
closing as dupe of #6447

**Closed by liggitt** 2015-12-23 20:43 UTC
Labels: kind/test-flake
