### ISSUE TITLE
haproxy router does not set proxy headers

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4549] opened 2015-09-05 12:49 UTC
Reverse proxies for apps should set headers so the application can create correct self-references. The example that spurred investigation here is running Jenkins on OpenShift. Per [this commit](https://github.com/jenkinsci/jenkins/commit/5bad446dd51d31efd60538eab5c87bdde57114e9) Jenkins was made to respond to `X-Forwarded-Port`, `X-Forwarded-Proto`, and  `X-Forwarded-Host`, which are the previous de facto standard proxy headers.  As of openshift/origin-haproxy-router:v1.0.4 none of these are set on a proxy request. haproxy-router should set these as well as the `Forwarded` header from the new [official standard](http://tools.ietf.org/html/rfc7239).

To view the headers being passed via an OpenShift router, you can set up a simple server to show the headers like https://github.com/sosiouxme/example-header-server for example:

```
oc new-app --docker-image=sosiouxme/header-server:v0.1
git clone https://github.com/sosiouxme/example-header-server.git
cd example-header-server
oc process -f route-template.yaml -v SERVER_KEY="$(cat server.key)",SERVER_CERT="$(cat server.crt)",HOSTNAME=header-server.apps.dev.example.com | oc create -f -
```

Visiting the route with `curl -k` shows no evidence of forwarding headers, e.g.:

```
host: header-server.apps.dev.example.com
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
dnt: 1
accept-encoding: gzip, deflate, sdch
accept-language: en-US,en;q=0.8
```

**Comment by bparees** [comment] 2015-09-05 13:26
dupe of https://github.com/openshift/origin/issues/4378 ?

**Comment by sosiouxme** [comment] 2015-09-05 20:42
I'd rather say that issue is a symptom of this one. The goal is not just fixing Jenkins but fixing any app depending on these headers.

**Comment by bparees** [comment] 2015-09-07 18:08
@sosiouxme that's why i pasted your email about solving the problem properly by adding the headers in the router.

**Comment by sosiouxme** [comment] 2015-09-08 12:38
@bparees Dupe implies one should probably be closed. I think this issue states the generic goal and test case clearly. Should we keep the other one around just for confirming it fixes Jenkins or merge one into the other?  I just want to ensure we attempt to supply all the headers I mentioned in this issue.

**Comment by bparees** [comment] 2015-09-08 13:49
This issue is breaking jenkins, so we need to ensure the following Jenkins scenario is fixed before closing this:

"It seems like the router is somehow messing up with the Jenkins example we have. When you create the Jenkins example from the template and then you navigate to "jenkins.ci.router.default.svc.cluster.local" ('ci' is the project name) a login screen pops up. When you login, you're redirected from https to http. To fix it, you have to manually rewrite the URL in browser to start with "https://" (and you're logged in). This also happens on several places in Jenkins UI (Manage Jenkins, etc...)..."

**Comment by bparees** [comment] 2015-09-08 13:50
@sosiouxme done, i closed the other one.

**Closed** 2015-09-18 20:22 UTC
Labels: component/routing, priority/P2
