### ISSUE TITLE
Connection closed by remote host

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12988] opened 2017-02-16 12:13 UTC
@stevekuznetsov you're gonna loooooove me for testing the infra 😉 

Here's another one, especially for you https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check_future/232/consoleFull:

```
12:21:25 Running test/cmd/observe.sh:22: executing 'oc observe services --once --all-namespaces' expecting success and text 'default kubernetes'...
17:03:40 Connection to 172.18.9.221 closed by remote host.
17:03:40 Build step 'Execute shell' marked build as failure
17:03:40 [PostBuildScript] - Execution post build scripts.
17:03:40 [workspace@4] $ /bin/bash /tmp/hudson4353713187509519942.sh
17:03:40 ~/jobs/test_pull_requests_origin_check_future/workspace@4 ~/jobs/test_pull_requests_origin_check_future/workspace@4
```

**Comment by stevekuznetsov** [comment] 2017-02-16 13:39
Dupe of https://github.com/openshift/origin/issues/12930

**Closed by stevekuznetsov** 2017-02-16 13:39 UTC
Labels: area/infrastructure, area/tests, kind/test-flake, priority/P2
