### ISSUE TITLE
connection between client and proxy breaks when client is receiving logs

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#2348] opened 2015-05-19 12:32 UTC
We are using httpd as proxy between client and master. Here's the configuration:

```
SetEnv proxy-sendchunked 1
ProxyRequests Off
<Location "/">
    ProxyPass https://127.0.0.1:8443/ connectiontimeout=300 timeout=3000
    ProxyPassReverse https://127.0.0.1:8443/
</Location>
```

Unfortunately, when we are fetching logs, the connection tends to break when pod is stuck on some operation which doesn't produce logs (therefore I thought it's timeout). Then I looked into httpd's logs and saw some errors there:

```
[Tue May 19 08:13:48.613935 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (data-IMMORTAL): 2 bytes
[Tue May 19 08:13:48.613940 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(103): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (data-IMMORTAL): \r\n
[Tue May 19 08:13:48.613954 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(140): [remote 127.0.0.1:8443] mod_dumpio: dumpio_in [getline-nonblocking] 0 readbytes
[Tue May 19 08:13:48.613964 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_in (data-TRANSIENT): 2 bytes
[Tue May 19 08:13:48.613968 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(103): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_in (data-TRANSIENT): \r\n
[Tue May 19 08:13:48.613973 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(140): [remote 127.0.0.1:8443] mod_dumpio: dumpio_in [getline-nonblocking] 0 readbytes
[Tue May 19 08:13:48.613978 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_in (data-TRANSIENT): 3 bytes
[Tue May 19 08:13:48.613982 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(103): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_in (data-TRANSIENT): 0\r\n
[Tue May 19 08:13:48.613988 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(140): [remote 127.0.0.1:8443] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[Tue May 19 08:13:48.613992 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_in (data-TRANSIENT): 2 bytes
[Tue May 19 08:13:48.613996 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(103): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_in (data-TRANSIENT): \r\n
[Tue May 19 08:13:48.614004 2015] [proxy:debug] [pid 14952] proxy_util.c(2215): AH00943: https: has released connection for (127.0.0.1)
[Tue May 19 08:13:48.614011 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(164): [client 10.3.14.233:56997] mod_dumpio: dumpio_out
[Tue May 19 08:13:48.614015 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (data-IMMORTAL): 5 bytes
[Tue May 19 08:13:48.614019 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(103): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (data-IMMORTAL): 0\r\n\r\n
[Tue May 19 08:13:48.614023 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (metadata-EOS): 0 bytes
[Tue May 19 08:13:48.614490 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(164): [client 10.3.14.233:56997] mod_dumpio: dumpio_out
[Tue May 19 08:13:48.614509 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (metadata-EOR): 0 bytes
[Tue May 19 08:13:48.614570 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(140): [client 10.3.14.233:56997] mod_dumpio: dumpio_in [speculative-nonblocking] 1 readbytes
[Tue May 19 08:13:48.614581 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(164): [client 10.3.14.233:56997] mod_dumpio: dumpio_out
[Tue May 19 08:13:48.614586 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (metadata-FLUSH): 0 bytes
[Tue May 19 08:13:48.614600 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(140): [client 10.3.14.233:56997] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[Tue May 19 08:13:48.618103 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(164): [client 10.3.14.233:56997] mod_dumpio: dumpio_out
[Tue May 19 08:13:48.618119 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (metadata-FLUSH): 0 bytes
[Tue May 19 08:13:48.618124 2015] [dumpio:trace7] [pid 14952] mod_dumpio.c(63): [client 10.3.14.233:56997] mod_dumpio:  dumpio_out (metadata-EOC): 0 bytes
[Tue May 19 08:15:44.168840 2015] [ssl:info] [pid 14922] [remote 127.0.0.1:8443] AH01992: SSL library error 1 reading data
[Tue May 19 08:15:44.169071 2015] [ssl:info] [pid 14922] SSL Library Error: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
[Tue May 19 08:15:44.169098 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(151): [remote 127.0.0.1:8443] mod_dumpio: dumpio_in - 20014
[Tue May 19 08:15:44.169118 2015] [http:info] [pid 14922] (20014)Internal error: [remote 127.0.0.1:8443] AH01590: Error reading chunk--
[Tue May 19 08:15:44.169186 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(164): [remote 127.0.0.1:8443] mod_dumpio: dumpio_out
[Tue May 19 08:15:44.169200 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_out (metadata-ERROR): 0 bytes
[Tue May 19 08:15:44.169212 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [remote 127.0.0.1:8443] mod_dumpio:  dumpio_out (metadata-EOS): 0 bytes
[Tue May 19 08:15:44.169383 2015] [proxy:debug] [pid 14922] proxy_util.c(2215): AH00943: HTTPS: has released connection for (127.0.0.1)
[Tue May 19 08:15:44.169441 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(164): [client 10.34.4.200:36793] mod_dumpio: dumpio_out
[Tue May 19 08:15:44.169456 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (data-IMMORTAL): 5 bytes
[Tue May 19 08:15:44.169470 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(103): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (data-IMMORTAL): 0\r\n\r\n
[Tue May 19 08:15:44.169484 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (metadata-EOS): 0 bytes
[Tue May 19 08:15:44.169597 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(164): [client 10.34.4.200:36793] mod_dumpio: dumpio_out
[Tue May 19 08:15:44.170306 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (metadata-EOR): 0 bytes
[Tue May 19 08:15:44.170424 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(164): [client 10.34.4.200:36793] mod_dumpio: dumpio_out
[Tue May 19 08:15:44.170436 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (metadata-FLUSH): 0 bytes
[Tue May 19 08:15:44.170456 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(164): [client 10.34.4.200:36793] mod_dumpio: dumpio_out
[Tue May 19 08:15:44.170466 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (metadata-FLUSH): 0 bytes
[Tue May 19 08:15:44.170476 2015] [dumpio:trace7] [pid 14922] mod_dumpio.c(63): [client 10.34.4.200:36793] mod_dumpio:  dumpio_out (metadata-EOC): 0 bytes
```

Is it possible that master is sendind invalid chunks to proxy?

```
Internal error: [remote 127.0.0.1:8443] AH01590: Error reading chunk--
```

Here are last lines on client:

```
2015-05-19T12:09:41.491795466Z 2015-05-19 08:09:41,488 - dock.plugins.squash - INFO - Saving image 43cd32a73f3584bd03202d14980320d640f490ed8d77d4dcc6b56801d89e2b06 to /tmp/tmp-docker-squash-q06lc9/image.tar file...
2015-05-19T12:09:41.491795466Z 2015-05-19 08:09:41,488 - dock.plugins.squash - DEBUG - Try #1...
* Closing connection 0
2015-05-19 14:15:45,874 - osbs.http - DEBUG - closing curl multi: 139780675401648
```

**Comment by brenton** [comment] 2015-05-19 13:06
I'll take a look to see if I can reproduce and capture some packets to see where the problem exists.  Thanks for filing this.

**Comment by TomasTomecek** [comment] 2015-05-19 13:28
I can provide access to the VM if needed.

**Comment by brenton** [comment] 2015-05-19 13:44
How long do you usually have to wait?

**Comment by TomasTomecek** [comment] 2015-05-19 17:42
if I look at timestamps in the log above, it looks like ~116 seconds

**Comment by TomasTomecek** [comment] 2015-05-19 17:44
I think I should reproduce it without proxy: we'll know then if the issue is in master, httpd or libcurl

**Comment by brenton** [comment] 2015-05-19 18:00
Here's what I'm seeing:

* As the admin I can run `osc log -f` and follow a pod's logs indefinitely.  In my environment the Admin accesses the Master directly
* As a normal user I try the same and it ends after exactly 1 minute.  In my apache logs I see:

~~~
[Tue May 19 13:49:05.853590 2015] [ssl:info] [pid 11027] (70014)End of file found: [client 192.168.133.2:46306] AH01991: SSL input filter read failed.
~~~

That's a little different then your situation.  I haven't reproduced the `AH01590: Error reading chunk--` problem yet.  Various suggestions for avoiding the default or catch-all VirtualHosts did not solve that problem for me.

When I perform a TCP dump I see `TCP Previous segment not catpured` errors just before the connection dies.  I'm still trying to make sense out of this.

**Comment by TomasTomecek** [comment] 2015-05-19 18:14
looks like we may need some help from an apache guru

**Comment by brenton** [comment] 2015-05-19 19:11
I'm thinking I should ignore the `TCP Previous segment not catpured` errors for now.  It seems as if they are caused by the tcpdump not processing packets as fast as the kernel sends them.  I tuned a few networking knobs and was able to get the percentage of dropped packages in the capture much lower.  When I did that I didn't see the same TCP errors at the end of the capture.

**Comment by brenton** [comment] 2015-05-19 19:58
I finally stumbled across ` SetEnv proxy-sendchunked 1` and now I see you already have that in your configuration.  With that set before my proxypass directives I now see:

~~~
[Tue May 19 15:33:50.212787 2015] [http:info] [pid 11897] (70007)The timeout specified has expired: [remote 192.168.133.2:8080] AH01590: Error reading chunk
~~~

That's closer to the error you're seeing.  So far I'm able to tail logs through the proxy however long I set the `ProxyTimeout` so I think things are working as expected.  I'll see if QE has hit this.

**Comment by TomasTomecek** [comment] 2015-05-19 20:24
This is the reason I used `proxy-sendchunked`:

    Setting proxy-sendcl ensures maximum compatibility with upstream servers
    by always sending the Content-Length, while setting proxy-sendchunked
    minimizes resource usage by using chunked encoding.
http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#request-bodies

I increased `timeout` in `ProxyPass` in hope that it will get rid of the problem and didn't realize there's also `ProxyTimeout`. Do you know what the relation is between those two? Docs are not really helpful:

```
# timeout

Connection timeout in seconds. The number of seconds Apache httpd waits for data
sent by / to the backend.
```

```
# ProxyTimeout

This directive allows a user to specifiy a timeout on proxy requests. This is
useful when you have a slow/buggy appserver which hangs, and you would rather
just return a timeout and fail gracefully instead of waiting however long it takes
the server to return.
```

Anyway, thanks a lot for tracing this down!

**Comment by brenton** [comment] 2015-05-19 20:28
I think they actually have the same effect.  `ProxyTimeout` probably has a larger scope.  I will be surprised if that setting improves your situation.

**Comment by TomasTomecek** [comment] 2015-05-19 20:30
Will check out when I get to work tomorrow.

**Comment by TomasTomecek** [comment] 2015-05-20 06:06
Am pretty puzzled: ran two builds, one displayed all logs, the other one errored out on the `Error reading chunk`. Will test more. Used this setup:
```
    ProxyTimeout 6666
    <Location "/">
        ProxyPass https://127.0.0.1:8443/ connectiontimeout=30 timeout=6000
        ProxyPassReverse https://127.0.0.1:8443/
    </Location>
```

**Comment by TomasTomecek** [comment] 2015-05-22 07:11
After a couple of days this is happening quite often. I'm using origin 0.4.4. On Monday I'm planning to play with 0.5.2. Will report whether the issue persists.

**Comment by brenton** [comment] 2015-05-22 12:14
Thanks for the update.

**Comment by brenton** [comment] 2015-05-22 20:14
I looked in to this some more today.  I think I'm seeing the same problem as you with fairly recent Origin code built with go 1.4.2.  The weird thing is that every time I run the test with curl it ends right around the 5 minute mark:

~~~
# time curl -ivs --raw -k --cert /root/config/master/admin.crt --key /root/config/master/admin.key "https://192.168.133.100:8443/api/v1beta3/namespaces/demo/pods/simple-openshift-sinatra-sti-2-8to7k/log?container=simple-openshift-sinatra-sti&follow=true&previous=false" > /dev/null; date
* About to connect() to 192.168.133.100 port 8443 (#0)
*   Trying 192.168.133.100...
* Connected to 192.168.133.100 (192.168.133.100) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
*       subject: CN=system:admin,O=system:cluster-admins
*       start date: May 10 18:12:14 2015 GMT
*       expire date: May 09 18:12:15 2016 GMT
*       common name: system:admin
*       issuer: CN=openshift-signer@1431281525
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=127.0.0.1
*       start date: May 10 18:12:09 2015 GMT
*       expire date: May 09 18:12:10 2016 GMT
*       common name: 127.0.0.1
*       issuer: CN=openshift-signer@1431281525
> GET /api/v1beta3/namespaces/demo/pods/simple-openshift-sinatra-sti-2-8to7k/log?container=simple-openshift-sinatra-sti&follow=true&previous=false HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.133.100:8443
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 22 May 2015 19:39:13 GMT
< Transfer-Encoding: chunked
<
{ [data not shown]

* transfer closed with outstanding read data remaining
* Closing connection 0

real    5m3.049s
user    0m0.145s
sys     0m0.068s
Fri May 22 15:44:16 EDT 2015
~~~

While I'm running this test I'm basically hitting the application in another process to generate log messages.

**Comment by brenton** [comment] 2015-05-22 20:15
Oddly enough I just ran the same test against a kubernetes instance and say the same results only it happened after 10 minutes.  There has to be a configuration setting somewhere.

~~~
time curl -ivs --raw "http://127.0.0.1:8080/api/v1beta3/namespaces/default/pods/nginx/log?container=nginx&follow=true&previous=false" > /dev/null; date &
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /api/v1beta3/namespaces/default/pods/nginx/log?container=nginx&follow=true&previous=false HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 22 May 2015 20:03:04 GMT
< Transfer-Encoding: chunked
<
{ [data not shown]



* transfer closed with outstanding read data remaining
* Closing connection 0

real    10m0.974s
user    0m0.017s
sys     0m0.022s

~~~

**Comment by TomasTomecek** [comment] 2015-05-22 23:30
This looks very close to what I'm seeing.

**Comment by TomasTomecek** [comment] 2015-05-26 09:07
I reproduced this with `0.5.2`.

Since Fedora/RHEL curl maintainer is sitting next to me, I discussed this issue with him. According to error from pycurl `pycurl.error: (18, 'NSS: client certificate not found (nickname not specified)')`, it looks like that master asks for client certificate after a period of time (which is a valid request according to TLS spec).

Could this be related to configuration of authorization? Also, can we raise priority on this? It's not technically a blocker for us, but it's annoying.

**Comment by brenton** [comment] 2015-05-26 14:27
@TomasTomecek, in your last comment about reproducing on 0.5.2 were you hitting the master directly or via apache?  It seemed to me like we've identified there is at least one problem with the Master's SSL connection that triggers this.

Did you ever try running `time`? I'm curious if you saw the same behavior I did where it would break after almost exactly 5 minutes.

**Comment by TomasTomecek** [comment] 2015-05-26 16:46
Ah, I'm already off the work. Totally forgot to comment. I tried some requests and all of them took less than 5 minutes, therefore I haven't hit this.

**Comment by TomasTomecek** [comment] 2015-05-27 11:28
```
osbs   build   0.42s user 0.30s system 0% cpu 5:12.94 total
```
Request was initiated at:
```
2015-05-27 13:19:47,999 - osbs.http - DEBUG - raw headers: u'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nDate: Wed, 27 May 2015 11:19:46 GMT\r\nTransfer-Encoding: chunked'
```
It failed here:
```
2015-05-27 13:24:51,082 - osbs.http - DEBUG - no more handles, quiting curl multi
```

**Comment by brenton** [comment] 2015-05-27 13:25
In your comment from a day ago were to testing by hitting the Master directly?  I'm assuming in your last comment you were going through Apache.

**Comment by TomasTomecek** [comment] 2015-05-27 17:59
no, I switched my setup to go to master directly; so all my comments for like 7 days are after hitting master directly

**Comment by brenton** [comment] 2015-05-27 18:17
Thanks.  I'm finishing up another bug right now and plan to spend the rest of the day on this.

**Comment by vbatts** [comment] 2015-05-28 20:33
poking around to reproduce with a simplest example, and not seeing this. https://github.com/vbatts/tls-example

**Comment by brenton** [comment] 2015-05-29 14:22
As best I can tell the problem is somehow related to this line of code: https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master.go#L517

However, it's not as simple as just changing that value.  It seems as if the timeout only comes in to play while my pod is actively generating logs.  If it's not doing anything I can use curl to follow the logs "forever".  If in another terminal I access the application constantly to generate logs that timeout will be hit and it will kill my connection.  It doesn't seem related to the amount of data being logged.  When I hit the timeout I'm generating about 3 lines of output every 5 seconds.

**Comment by TomasTomecek** [comment] 2015-05-29 17:55
Is `osc` affected too?

**Comment by brenton** [comment] 2015-05-29 18:24
Yes.  I first hit the problem with `osc log` and the curl request I made was the exact same request `osc` was running.  I noticed the same behavior in Kubernetes and just filed https://github.com/GoogleCloudPlatform/kubernetes/issues/9013

**Comment by brenton** [comment] 2015-06-01 13:15
@smarterclayton, The short of this seems related to the design discussions in Kubernetes about watches timing out after 5 minutes and requiring clients to reconnect and resume where they left off.  

Shouldn't we have `osc log` work that way and handling reconnecting behind the scenes?

**Comment by smarterclayton** [comment] 2015-06-01 13:25
Hrm.  We don't have a great story about this today.  I don't want to leave connections open forever, 5 minutes is arbitrarily chosen, but reasonable.

----- Original Message -----

**Comment by brenton** [comment] 2015-06-01 13:49
@smarterclayton, If we aren't going to address this in Origin my vote would be to close this and either open a card or use the upstream issue I filed to track the work in Kubernetes.  Originally I thought this was related to the Apache proxy in front which is why I grabbed it.  Feel free to re-open this if you think otherwise.

**Closed by brenton** 2015-06-01 13:49 UTC
Labels: component/logging, kind/bug, priority/P2
