### ISSUE TITLE
Test flake TestImageStreamMappingCreate

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5444] opened 2015-10-28 01:20 UTC
```
--- FAIL: TestImageStreamMappingCreate-2 (6.23s)
	imagestream_test.go:215: unexpected error: imageStream "test" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
FAIL
```

Likely due to image stream changes.

**Comment by deads2k** [comment] 2015-10-28 15:11
Looks like a dupe of https://github.com/openshift/origin/issues/5421

**Comment by soltysh** [comment] 2015-10-29 11:00
#5421 was resolved with #5455 please close.

**Comment by deads2k** [comment] 2015-10-29 11:44
resolved with #5455

**Closed by deads2k** 2015-10-29 11:44 UTC
Labels: kind/test-flake
