### ISSUE TITLE
Align oadm manage-node --evacuate and kubectl drain command

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#11309] opened 2016-10-11 08:48 UTC
We use `oadm manage-node --evacuate` to remove pods from node that is planned for maintenance. Upstream has `kubectl drain` to do exactly the same. It would be nice to align the two.

@smarterclayton ideas, objections?

**Comment by mfojtik** [comment] 2016-11-07 09:07
@soltysh closing as dupe of https://github.com/openshift/origin/issues/11310

**Closed by mfojtik** 2016-11-07 09:07 UTC
Labels: area/techdebt, component/kubernetes, kind/enhancement, priority/P2
