### ISSUE TITLE
BuildDefaults don't show up in Environment of BuildConfigs or Builds

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#8663] opened 2016-04-28 15:15 UTC
It's fairly opaque to end users that there are BuildDefaults or BuildOverrides being defined for them. It'd be nice if these were somehow displayed in the Environment section of BuildConfigs and Builds.
##### Version

oc v3.2.0.20
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. Provision an environment with BuildDefaults admission controller defined.
2. Create a buildconfig, build it.
##### Current Result

Injected values such as HTTPS_PROXY and HTTP_PROXY are not visible in the Environment tabs
##### Expected Result

Injected values visible in at least the actual Build's Environment tab if not the BuildConfig's Environment tab.

**Comment by bparees** [comment] 2016-06-10 04:38
@csrwng what was our reasoning for just updating the build definition env variable in the pod, instead of updating the build object or buildconfig itself?  concerns that users would undo the override?  We could always do the override everywhere.

**Comment by csrwng** [comment] 2016-06-10 14:10
@bparees @sdodson the reason was that we wanted to preserve the original intent of the user in the build object. For example, if your policy changes later (you setup a new proxy). For example you export your build object to another cluster or clone your build after you've changed settings. If the setting is a build default, we won't change what's in the build already and the  setting will be wrong.

**Comment by sdodson** [comment] 2016-06-10 15:03
Hmm, with that in mind I'm not sure what the right thing to do is. It definitely makes sense not to include it in the buildconfig but I think it should actually be part of the build so that if you export the build it's exactly as it was executed.

**Comment by csrwng** [comment] 2016-06-10 15:42
@sdodson not sure... you may want to re-run an existing build and not a new one from build config (that's what oc start-build --from-build=BUILD does). Admittedly, it would be a less common use case. I'm thinking that maybe we should record in the Status part of the build what it actually ran with. That way you know what was actually used but don't change the original intent of the build. @bparees thoughts?

**Comment by bparees** [comment] 2016-06-10 17:05
@csrwng sounds reasonable.

**Comment by csrwng** [comment] 2016-06-10 17:40
@smarterclayton would you support changing the build status API struct to include env values that were actually used during the build?

**Comment by smarterclayton** [comment] 2016-06-10 18:54
If this is for things that are used by the build, they should be set into the build spec.  Not build status.

**Comment by bparees** [comment] 2016-06-10 18:57
@smarterclayton we're trying to avoid putting them in the spec because of the following scenario:

1) admin sets up a builddefaulter that sets env FOO=BAR
2) user launched a build, build runs with FOO=BAR
3) admin changes defaulter to FOO=BAR2
4) user "rebuilds" the build from (2), but because FOO=BAR is already in the spec, they don't get the new default of FOO=BAR2.  (the builddefaulter won't override existing env vars because it's a defaulter, not an overrider)

**Comment by csrwng** [comment] 2016-06-10 19:07
I guess it makes a little bit more sense if s/FOO/HTTP_PROXY/

**Comment by smarterclayton** [comment] 2016-06-10 20:21
The use case is pretty familiar, I'm just really hesitant to add a whole API feature for something like this.  I would slightly prefer a build defaults spec field.

**Comment by smarterclayton** [comment] 2016-06-10 20:21
This definitely feels more spec than status.

**Comment by bparees** [comment] 2016-06-10 20:31
> I would slightly prefer a build defaults spec field.

i kinda hate anything that's going to become a duplicate of all the fields that already exist in the build spec, which is what that (or the status solution) are going to become as we add more things that can be defaulted.

**Comment by smarterclayton** [comment] 2016-06-10 20:48
What other things would we default / fill out?

**Comment by bparees** [comment] 2016-06-10 20:53
force pull (currently an override), incremental, triggers (github, generic, configchange)...  i'd have to look at the build spec to see what else.

**Comment by smarterclayton** [comment] 2016-06-10 21:14
Those are all things I would expected to get defaulted on the object, and
on rebuild be reused.

**Comment by bparees** [comment] 2016-06-10 22:37
> Those are all things I would expected to get defaulted on the object, and
on rebuild be reused.

So you're making the argument that once the build is created, it should not pick up "changed" default values?  (but it will pick up *new* default values).  because if that's the case, we can just modify the build spec itself, we don't need a separate "default" spec.

**Comment by jupierce** [comment] 2016-07-13 14:05
Just a thought that it could be useful to treat environment variables and proxy information differently. 

Proxy information being persisted in a build configuration seems counter-intuitive to me -- like persisting proxy information as part of a browser bookmark -- it artificially inhibits migration between environments. I think the real concern here is that the information is hard to come across. 

Couldn't we have a BuildEnvironment plugin which was solely responsible for the proxy settings? The values would never leak into the build configurations and we could render the values in the UIs. For example:
- Web console: under Project Settings as a new "Server Settings" area of the Build Configuration tab.
- CLI: oc status, oc describe bc, or as informational build stdout message.

Removing proxies makes the behavior of the remaining plugins predictable an unproblematic, from my limited perspective. 
- BuildDefaults: Values wind up encoded into the build unless overridden. Effectively a convenience method to avoid repeating yourself.
- BuildOverrides: Values always affect the build.

**Comment by bparees** [comment] 2016-07-13 14:27
> Couldn't we have a BuildEnvironment plugin which was solely responsible for the proxy settings? The values would never leak into the build configurations and we could render the values in the UIs. For example:

what you're describing is basically what the builddefaulter and overrider already do today.  we could have the UI and CLI tools munge together the override/default config settings along with the build/buildconfig object, to display to the user "what you're going to get" instead of "what you defined"

**Comment by jupierce** [comment] 2016-07-13 15:33
@bparees Agreed. I was primarily arguing that any implementation of Defaults/Overrides makes more sense to me if the proxy information is extracted into a new plugin. Secondarily that the "simple" approach of stamping the build with the contemporaneous Defaults (i.e. without the need to munge) becomes fairly intuitive if we do.

**Comment by csrwng** [comment] 2016-08-02 14:02
@bparees @jupierce did we agree on how to proceed with this issue (short/longer term)? In the short term, can we simply resolve it in the UI? If a build exists and the pod that it ran with exists, then we can extract the info from the pod and highlight the differences ? (actual vs spec). We could do this in the web console and the 'oc describe' output.

**Comment by bparees** [comment] 2016-08-03 15:10
@csrwng UI gymnastics doesn't feel like the right answer.  adding explicit "values from override/defaults" fields to the build seems like the right answer, much as i don't want to duplicate a bunch of fields.

**Comment by csrwng** [comment] 2016-08-03 16:53
@bparees and I'm guessing we would like this change for 3.3 ? :)

**Comment by bparees** [comment] 2016-08-03 17:52
@csrwng i don't think we want to try to do that, no.

**Comment by csrwng** [comment] 2016-09-30 03:59
@bparees sending this one to you since what you're working on would hopefully fix this.

**Comment by bparees** [comment] 2016-09-30 14:45
@csrwng i'm not actually going to be fixing this as part of what i'm doing, but the right fix for this in the future is, imho:  we need to get more discipline around spec vs status, and builddefaults/overrides should only affect status, not spec.  Then the user can see what they asked for (spec) and what they got (status).  And they won't be able to change the status, so they won't be able to modify the values set by an override.

would need to be part of a v2 api of course.

wdyt?

**Comment by csrwng** [comment] 2016-09-30 16:10
sgtm

**Comment by bparees** [comment] 2018-01-19 23:30
trello'd https://trello.com/c/oLPEjyle

**Closed by bparees** 2018-01-19 23:30 UTC
Labels: component/build, kind/enhancement, priority/P2
