### ISSUE TITLE
[flake] [Conformance][Area:Networking][Feature:Router] router headers The HAProxy router should set Forwarded headers appropriately

### ISSUE THREAD

**Issue by simo5** [openshift/origin#19887] opened 2018-05-30 17:15 UTC
release-3.9 gcp e2e test reliably fail on this test with a timeout:
```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/headers.go:42
Expected error:
    <*errors.errorString | 0xc4210c04d0>: {
        s: "host command failed: error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl [kubectl --server=https://internal-api.prtest-20891fe-179.origin-ci-int-gce.dev.rhcloud.com:8443 --kubeconfig=/tmp/cluster-admin.kubeconfig exec --namespace=extended-test-router-headers-zlt9n-vq2hq execpod -- /bin/sh -c \n\t\tset -e\n\t\tfor i in $(seq 1 180); do\n\t\t\tcode=$( curl -k -s -o /dev/null -w '%{http_code}\\n' --header 'Host: router-headers.example.com' \"http://172.30.154.4\" ) || rc=$?\n\t\t\tif [[ \"${rc:-0}\" -eq 0 ]]; then\n\t\t\t\techo $code\n\t\t\t\tif [[ $code -eq 200 ]]; then\n\t\t\t\t\texit 0\n\t\t\t\tfi\n\t\t\t\tif [[ $code -ne 503 ]]; then\n\t\t\t\t\texit 1\n\t\t\t\tfi\n\t\t\telse\n\t\t\t\techo \"error ${rc}\" 1>&2\n\t\t\tfi\n\t\t\tsleep 1\n\t\tdone\n\t\t] []  <nil> 503\n503\n503\n503\n503\n503\n503\n503\n502\n command terminated with exit code 1\n [] <nil> 0xc421d5fa70 exit status 1 <nil> <nil> true [0xc42152ee90 0xc42152eea8 0xc42152eec0] [0xc42152ee90 0xc42152eea8 0xc42152eec0] [0xc42152eea0 0xc42152eeb8] [0x9891a0 0x9891a0] 0xc421410300 <nil>}:\nCommand stdout:\n503\n503\n503\n503\n503\n503\n503\n503\n502\n\nstderr:\ncommand terminated with exit code 1\n\nerror:\nexit status 1\n\n",
    }
    host command failed: error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl [kubectl --server=https://internal-api.prtest-20891fe-179.origin-ci-int-gce.dev.rhcloud.com:8443 --kubeconfig=/tmp/cluster-admin.kubeconfig exec --namespace=extended-test-router-headers-zlt9n-vq2hq execpod -- /bin/sh -c 
    		set -e
    		for i in $(seq 1 180); do
    			code=$( curl -k -s -o /dev/null -w '%{http_code}\n' --header 'Host: router-headers.example.com' "http://172.30.154.4" ) || rc=$?
    			if [[ "${rc:-0}" -eq 0 ]]; then
    				echo $code
    				if [[ $code -eq 200 ]]; then
    					exit 0
    				fi
    				if [[ $code -ne 503 ]]; then
    					exit 1
    				fi
    			else
    				echo "error ${rc}" 1>&2
    			fi
    			sleep 1
    		done
    		] []  <nil> 503
    503
    503
    503
    503
    503
    503
    503
    502
     command terminated with exit code 1
     [] <nil> 0xc421d5fa70 exit status 1 <nil> <nil> true [0xc42152ee90 0xc42152eea8 0xc42152eec0] [0xc42152ee90 0xc42152eea8 0xc42152eec0] [0xc42152eea0 0xc42152eeb8] [0x9891a0 0x9891a0] 0xc421410300 <nil>}:
    Command stdout:
    503
    503
    503
    503
    503
    503
    503
    503
    502
    
    stderr:
    command terminated with exit code 1
    
    error:
    exit status 1
    
    
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/headers.go:85
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19856/test_pull_request_origin_extended_conformance_gce_39/179/

**Comment by simonpasquier** [comment] 2018-06-01 11:29
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/8596/test_pull_request_openshift_ansible_extended_conformance_gce_39/339/

**Comment by jpeeler** [comment] 2018-06-06 13:59
Based on a quick glance at https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce_39/, it looks like the last time this test was successful was on April 27th. The next execution failed (and all times since) on May 30th. I'm not sure if there are missing logs, but there are less than a dozen of commits after that last successful run.

**Comment by jwforres** [comment] 2018-06-07 18:16
@openshift/sig-networking

**Comment by Miciah** [comment] 2018-06-11 16:22
Looks like `router-http-echo-server.yaml` defines a deployment config that uses `socat` to run a `perl` command, but the deployment config specifies the `openshift/origin-base` image, which has no `perl` command.

**Comment by jpeeler** [comment] 2018-06-11 16:47
I think you meant curl instead of perl.

**Comment by jpeeler** [comment] 2018-06-11 17:47
I'm looking here, which seems to be what's reporting the 127 error:
https://github.com/openshift/origin/blob/a96a520e292b5034ab11360f7bdd51349d43cbb8/test/extended/router/scoped.go#L149-L166

Perl is installed as a dependency of git. If I'm wrong about this, I'll know soon enough. Test in progress now.

**Comment by Miciah** [comment] 2018-06-11 17:47
I did an `oc rsh` into the pod and ran `which perl`; there was no `perl`.

**Comment by Miciah** [comment] 2018-06-11 18:04
https://github.com/openshift/origin/commit/4333db3960e1f134bbf606bd5a8ea7f4fd062c93 dropped the Git dependency, but that's 3.10, not 3.9.  openshift/origin-base:v3.9 does have `perl`.  For some reason, my devenv is using openshift/origin-base:latest; is CI doing the same?

**Comment by jpeeler** [comment] 2018-06-11 18:35
As you both suspected, adding curl doesn't fix the problem.

https://github.com/openshift/origin/blob/release-3.9/test/extended/testdata/router-http-echo-server.yaml#L23

CI calls hack/build-base-images.sh which uses the Dockerfiles from the images directory and tags it as latest. It does look like CI might be pulling the latest image, even though a local one exists:

Jun 11 15:45:22.527: INFO: At 2018-06-11 15:45:16 +0000 UTC - event for router-http-echo-1-77hrf: {kubelet prtest-20891fe-261-ig-n-6zsk} Pulled: Successfully pulled image "openshift/origin-base"

I assume that output would be different if the locally built image was being used.

**Comment by knobunc** [comment] 2018-06-11 18:37
The goal was to have an http endpoint that echoed back everything sent
without adding anything to the image.  We could replace the perl with
python perhaps.

-ben

**Comment by Miciah** [comment] 2018-06-11 18:39
`router-http-echo-server.yaml` does not specify an image pull policy.  The default image pull policy when using the "latest" tag is "Always"; otherwise it's "PullIfNotPresent".

We don't need Python; Bash should suffice.  https://github.com/openshift/origin/pull/19963 is a tentative fix.

**Comment by jpeeler** [comment] 2018-06-11 18:42
@Miciah So if the default pull policy is always and the image doesn't specify a version implying latest, then I think the best fix is to change the image pull policy to IfNotPresent. What do you think?

**Comment by Miciah** [comment] 2018-06-11 18:51
@jpeeler, if we set an explicit image pull policy of IfNotPresent but kept (implicitly) using the latest tag, wouldn't that just mean we'd end up pulling the wrong image once instead of pulling it many times? We should probably explicitly specify the v3.y tag when testing the release-3.y branch.

**Comment by jpeeler** [comment] 2018-06-11 20:08
The CI process builds images and tags them as latest, but they are based on the content of the 3.9 branch. I assume the idea is to not have to go and retag everything with specific versioning/tagging once a branch is cut.

**Comment by jpeeler** [comment] 2018-06-11 20:35
I really don't have a strong preference between those two really. I just want to see the next CI run pass so the root cause is finally confirmed. I have a feeling that if the image isn't built and tagged properly, that some other job would fail way sooner. But changing to Never makes sense.

**Comment by Miciah** [comment] 2018-06-14 08:28
Oops.  #19963 was for the master branch, but this issue is for the release-3.9 branch and thus needs #19990.

**Comment by Miciah** [comment] 2018-06-14 18:58
Meh.  I shouldn't have put that "Fixes" line in the commit message.

**Comment by jpeeler** [comment] 2018-06-15 17:11
Looks like it's fixed now!

**Closed by jpeeler** 2018-06-15 17:11 UTC
Labels: component/routing, kind/test-flake, priority/P1, sig/networking
