### ISSUE TITLE
PUT request that modifies route certificate fails

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#15772] opened 2017-08-14 20:19 UTC
This looks like an API breaking change in 3.6. If I do a PUT on a route and change the `spec.tls.certificate`, I'm told the field is immutable. But `oc edit` allows me to change the value. 

The error breaks the web console route editor in 3.6.

@knobunc Let me know if I'm wrong and the field should be immutable, but I believe we were able to change it in previous releases.

@smarterclayton @andrewklau 

See https://github.com/openshift/origin-web-console/issues/1930

##### Version
3.6.0

##### Steps To Reproduce
1. Edit a route in the web console (or edit the route YAML in the web console).
2. Only change the route certificate.

You'll see an error saying the field is immutable. If you inspect the web console PUT request in developer tools, the only value changed in the request body is `spec.tls.certificate`.

**Comment by smarterclayton** [comment] 2017-08-14 20:28
Are you using the new endpoint or the old endpoint?

**Comment by smarterclayton** [comment] 2017-08-14 20:29
And are you posting empty field, or doing a patch with no field provided?

**Comment by spadgett** [comment] 2017-08-14 20:35
Old endpoint 

I can reproduce using the same object returned by the API, just changing the certificate value. No empty fields added

**Comment by smarterclayton** [comment] 2017-08-14 21:53
For normal users, certificates are now immutable.

**Comment by smarterclayton** [comment] 2017-08-14 21:54
You should be getting a 422 with a forbidden field.

**Comment by spadgett** [comment] 2017-08-14 22:50
@smarterclayton Thanks. I'm getting a 422 with the following response body.

Debating making the field read only in the web console, although it would mean users who can edit the certificate won't be able to through the console.

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Route \"node-edge\" is invalid: spec.tls.certificate: Invalid value: \"foo\": field is immutable",
  "reason": "Invalid",
  "details": {
    "name": "node-edge",
    "kind": "Route",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: \"foo\": field is immutable",
        "field": "spec.tls.certificate"
      }
    ]
  },
  "code": 422
}
```

**Comment by smarterclayton** [comment] 2017-08-14 23:03
Some clusters may allow it for all users.  You need the "update" verb on
resource "routes/custom-host" and group "route.openshift.io" to change a
route host/cert once created.  It's only the most restrictive clusters that
need this.  It was made the default behavior because it was technically an
oversight when we made spec.host immutable.

**Comment by andrewklau** [comment] 2017-08-15 02:52
Confirmed, adding the `update` verb to the `routes/custom-host` allows a user to edit it again on the web console. I couldn't find any reference release note for this change though.

**Comment by spadgett** [comment] 2017-08-15 15:41
@smarterclayton bump for updating the error message to say why it's immutable and possibly changing the default for update (per our conversation)

**Comment by smarterclayton** [comment] 2017-08-15 16:08
I don't remember why I didn't give "update" to users by default - I *think* it was because of the custom host being immutable which was our current behavior.  @abhgupta @Miciah see the thread above.

I'll definitely improve the message for update.

**Comment by Kamshak** [comment] 2017-08-29 16:39
@smarterclayton is there a way to get the update permission somehow in the dev preview? I've tried using a local role but there seems to be a rolebindingrestriction that prevents actually using the role

**Comment by rajatchopra** [comment] 2018-01-18 23:24
pull #18177 to allow admin to update routes/custom-host by default.
Also see discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1524707

**Comment by liggitt** [comment] 2018-01-19 17:17
> For normal users, certificates are now immutable.

how is that reasonable? certificates expire.

> pull #18177 to allow admin to update routes/custom-host by default.

gating updating the certificate on an update host permission doesn't make sense to me

**Comment by rajatchopra** [comment] 2018-01-19 19:29
@liggitt 
Would you prefer something like this: https://github.com/openshift/origin/pull/18195
This removes TLS update out of routes/custom-host resource and keeps it in 'routes' resource only.

**Comment by liggitt** [comment] 2018-01-20 06:36
> Would you prefer something like this: #18195

the check in that PR is a duplicate of the check the apiserver already does. it's still unclear to me why we are preventing updates of the certificate.

secondly, even if we did restrict that, it should not be coupled to the same permission that allows updating the host field.

**Comment by rajatchopra** [comment] 2018-01-22 19:04
@liggitt 
Fixed the duplicate in the PR.
TLS is not coupled to routes/custom-host now (through #18195).

I agree that TLS update should not need that much privilege, but we can discuss that as follow up. The current behaviour is that not even the project admin can modify the fields, and that needs to be fixed immediately.

**Closed** 2018-06-22 02:01 UTC
Labels: component/networking, kind/bug, lifecycle/rotten, priority/P2
