### ISSUE TITLE
"BuildConfig --> spec --> output --> to --> name" must be checked

### ISSUE THREAD

**Issue by fkirill** [openshift/origin#4762] opened 2015-09-23 04:53 UTC
Hello,
if you made a mistake in setting the name of output image stream name in build config, build is just silently doesn't start without any diagnostics/logs whatsoever.

After changing "test/test3:latest" to "test3:latest" (by mistake it was image name instead of image stream name).

I guess, while creating such an object may be valid, the build start should fail with a meaningful error message (like 'target image stream test/test3:latest not found').

Here is YAML for the build config
<pre><code>
......
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: test3
      name: test3
    spec:
      output:
      to:
        kind: ImageStreamTag
        name: test/test3:latest             <b><<<<<------- The problem is here</b>
    source:
      type: Git
      git:
        uri: http://192.168.1.254:3000/gogsadmin/test3.git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java-maven-builder:latest
    triggers:
    - github:
        secret: x47Cn_v-jGF65Zp20wHU
      type: GitHub
    - generic:
        secret: MNRJYV6XYLC4C4CHwnZ_
      type: Generic
    - type: ConfigChange
    - type: ImageChange
......
</code></pre>

**Comment by mfojtik** [comment] 2015-09-23 10:45
@rhcarvalho FYI

**Comment by rhcarvalho** [comment] 2015-09-23 11:22
I think this will be fixed if we resolve the ImageStream reference when we create a build out of a BuildConfig, because then the build will fail immediately. @bparees FYI too ^^
I'll point to my PR here once I create it.

**Comment by liggitt** [comment] 2015-09-23 12:18
I think it would be ok to make sure the reference can resolve when creating the build, but I think the build spec should still contain the symbolic reference. That is used by various parts of the system (at least the web console, and maybe parts of the CLI like `oc status`) to correlate the build with the image stream, which is hard to do if the symbolic information is resolved away

**Comment by bparees** [comment] 2015-09-23 15:03
the intent was to allow this condition so you can create the imagestream later and then the build will proceed (we'll retry for a while).

with @rhcarvalho's changes, i'd still expect us to retry for a while before failing the build.  @rhcarvalho i've talked about this before on this topic, we need to retry events that trigger builds if we couldn't resolve the imagestream, just like how we retry those events for a while in the face of other errors.

**Comment by smarterclayton** [comment] 2015-09-25 14:24
Is there an issue for that that you could link here?

**Comment by rhcarvalho** [comment] 2015-09-29 09:16
@bparees since we didn't change where the ImageStream reference is resolved in my PR, could you please label and prioritize this?

**Comment by bparees** [comment] 2015-09-29 10:06
closing as dupe of https://github.com/openshift/origin/issues/4362

**Closed by bparees** 2015-09-29 10:06 UTC
Labels: component/build, priority/P2
