### ISSUE TITLE
[E2E] [DIND] intra-pod communication tests should work OOTB.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#6577] opened 2016-01-07 20:15 UTC
When running the end to end kube networking `intra-pod` communications test, we get instant failure.    - - Ive created this cluster on DIND.
- I suspect a simlar error would happen in other environments.
- curious: if the exact same error happens in EC2 deployments?
- curious: should intra-pod communication tests work on openshift?

Be warned that @marun mentioned the lack of secrets service account mounting might  be b/c its not needed for an  openshift app, i.e. its a security "feature", rather than a bug :) ?  

In any case , I 'll reproduce what I saw here, because 
- the networking test is very powerful for debugging a "real" working kube cluster from a "running apiserver and controller manager".
- we want an end-to-end binary and verification of upstream e2es running in openshift clusters.
-  even If the only conclusion from this Issue is that networking.go intrapod tests are not valid in openshift in its current state, then that is ok. 

**The details**

The root cause from my digging into it a little, is  due to missing service accounts.  That is, 
```
bash-4.3# docker logs 34693d80cd13
2016/01/07 17:10:41 Unable to create client; error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

We consider this an important test for kube basic functionality, so would be to know  if :
- there was simply a configuration switch we can turn on to get this working, i.e., service accounts might not be mounted in openshift by default?
- or, is there is a deeper reason for the missing certs ? If so maybe  we can work with upstream to make the networking test machinery more flexible, so that it can support  different intra-pod communication paradigms.

This is reproducible via DIND clusters, after applying #6541 , 
```
export OPENSHIFT_DIND_DEV_CLUSTER=true
export OPENSHIFT_MEMORY=4000
export OPENSHIFT_SDN_NODE_ON_MASTER=true
vagrant up
vagrant ssh
make e2e
_output/local/bin/linux/amd64/e2e.test --provider=local --kubeconfig=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/openshift-master.kubeconfig --ginkgo.focus="intra-pod"
```

Then we can enter  one of the nodes:

```
[vagrant@openshift-dind-host vagrant]$ docker exec -t -i ce4731479256 /bin/bash
```

And look in the container that tried to run:

```
bash-4.3# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
bash-4.3# docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                      PORTS               NAMES
255eb79d15b9        gcr.io/google_containers/nettest:1.6   "/webserver -service="   6 minutes ago       Exited (1) 6 minutes ago                        k8s_webserver.a3289770_nettest-o0wv5_e2e-tests-nettest-y74lk_42e4fadd-b562-11e5-bc63-02420b9e4eaf_0e027af6
45f01227ad8f        openshift/origin-pod:v1.1              "/pod"                   6 minutes ago       Exited (0) 6 minutes ago                        k8s_POD.e127fd63_nettest-o0wv5_e2e-tests-nettest-y74lk_42e4fadd-b562-11e5-bc63-02420b9e4eaf_b8bac4e1
34693d80cd13        gcr.io/google_containers/nettest:1.6   "/webserver -service="   11 minutes ago      Exited (1) 11 minutes ago                       k8s_webserver.16269777_nettest-xx55t_e2e-tests-nettest-nnz1t_8e8a4264-b561-11e5-bc63-02420b9e4eaf_7ef45279
eae5dda0cca7        openshift/origin-pod:v1.1              "/pod"                   11 minutes ago      Exited (0) 11 minutes ago                       k8s_POD.e127fd63_nettest-xx55t_e2e-tests-nettest-nnz1t_8e8a4264-b561-11e5-bc63-02420b9e4eaf_033ecb73
```

And grabbing the logs, we get the output pasted at the top with the unmounted /var/run/... error.

**Comment by jayunit100** [comment] 2016-01-07 20:16
cc the usual suspects that might be interested in this @marun @liggitt @eparis @timothysc @pmorie

**Comment by timothysc** [comment] 2016-01-07 21:13
I suspect the default config is wrong for DIND

**Comment by marun** [comment] 2016-01-07 21:25
@timothysc I think I ran into the same issue with a vm-based devcluster, but haven't tested in that configuration for some time.  Verifying that the failure is not dind-specific would definitely be a good next step.

**Comment by jayunit100** [comment] 2016-01-08 14:55
To summarize where im at so far.

- @marun I think your right that there is an earlier failure in both.  Howerver, the failure is subtle difference once you dig into the container logs:
- On a VM based cluster: I'm currently getting X509 errors `2016/01/08 14:34:25 Unable to get server version: Get https://172.24.0.1:443/version: x509: certificate is valid for 10.1.236.12, 172.30.0.1, 192.2.4.238, not 172.24.0.1`.
- On DIND cluster, I get mounting certs errors `2016/01/07 17:10:41 Unable to create client; error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`.

**Comment by jayunit100** [comment] 2016-01-08 15:48
Lets resolve The above issue before treading deeper into networking.  Without EmptyDir tests passing, there is no point in testing intra-pod communication (because, iirc intra-pod  requires certificate mounting for containers in EmptyDir).

**Comment by timothysc** [comment] 2016-01-08 23:02
The internal cert failure on native install is disconcerting, b/c it allows external ips but not the introspective endpoint that is needed for resolution.  @liggitt do you have any thoughts on this one?  

```2016/01/08 14:34:25 Unable to get server version: Get https://172.24.0.1:443/version: x509: certificate is valid for 10.1.236.12, 172.30.0.1, 192.2.4.238, not 172.24.0.1.```

**Comment by liggitt** [comment] 2016-01-09 00:15
Which connection is complaining about that - node to master? Do you have the config files and certs captured so I can look at them? What IP are you expecting the node to use to talk to the master, and is that the IP the master is being told to use as its masterURL?

**Comment by timothysc** [comment] 2016-01-09 01:54
We're expecting it to connect via the introspective service ip: 

$ oc get services
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)                 SELECTOR   AGE
kubernetes   172.24.0.1   <none>        443/TCP,53/UDP,53/TCP   <none>     1d

everything was setup via openshift-ansible.

**Comment by liggitt** [comment] 2016-01-09 02:08
The service ip should already be in the cert. Can you include the JSON definition of the kubernetes service? @sdodson, any ideas why the service IP wasn't included?

**Comment by timothysc** [comment] 2016-01-09 04:43
$ oc get -o json service kubernetes
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "kubernetes",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/services/kubernetes",
        "uid": "da470ebc-b590-11e5-8272-fa163ea585d3",
        "resourceVersion": "7",
        "creationTimestamp": "2016-01-07T22:49:04Z",
        "labels": {
            "component": "apiserver",
            "provider": "kubernetes"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "https",
                "protocol": "TCP",
                "port": 443,
                "targetPort": 443
            },
            {
                "name": "dns",
                "protocol": "UDP",
                "port": 53,
                "targetPort": 53
            },
            {
                "name": "dns-tcp",
                "protocol": "TCP",
                "port": 53,
                "targetPort": 53
            }
        ],
        "portalIP": "172.24.0.1",
        "clusterIP": "172.24.0.1",
        "type": "ClusterIP",
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}

**Comment by liggitt** [comment] 2016-01-09 04:46
the cert contains 172.30.0.1 (which would be the service IP with the default services subnet of 172.30.0.0/16), but this machine has that set to 172.24.0.0/14

**Comment by liggitt** [comment] 2016-01-09 04:52
This line is correct (https://github.com/openshift/openshift-ansible/blob/31a18b4e6096451bd81603b92a2d4cf7d21cecef/roles/openshift_master/templates/master.yaml.v1.j2#L100):
```
 servicesSubnet: {{ openshift.master.portal_net }}
```

and from what I can see, this line correctly computes the service IP:
https://github.com/openshift/openshift-ansible/blob/59169a04580c8ae9a2594544dc75b994602da7ea/roles/openshift_facts/library/openshift_facts.py#L543

and that fact is what is used when creating the certs:
https://github.com/openshift/openshift-ansible/blob/c473a90f4abe887a1a94819e2feac8dcd29dc839/roles/openshift_master_ca/tasks/main.yml#L30

@sdodson, am I missing something?

**Comment by sdodson** [comment] 2016-01-11 16:29
@jayunit100  I'm pretty sure that the ansible installer isn't even involved here. Is that correct? If it is involved can you show me how you're using it?

**Comment by sdodson** [comment] 2016-01-11 16:31
Nevermind, i see Tim say it was.

**Comment by sdodson** [comment] 2016-01-11 20:33
For ansible installs there's https://github.com/openshift/openshift-ansible/issues/1161 and the fix in https://github.com/openshift/openshift-ansible/pull/1162

I'm not familiar enough with the e2e process or DIND to say which of those are leading to the certs created there not having the proper kube service ip, however from IRC conversations it sounds like if you stick to the defaults you don't run into problems. I'm not sure who this issue should be re-assigned to.

**Comment by marun** [comment] 2016-01-11 22:57
Given that I'm the assignee for the probably root cause of the failure (#6589), it may make sense for me to take this one as well.

**Closed** 2016-03-05 20:07 UTC
Labels: area/tests, priority/P2

**Comment by marun** [comment] 2016-03-07 14:01
This is fixed for non-dind, but won't work for dind without docker 1.10.
