### ISSUE TITLE
[builds][Conformance] s2i build with a quota

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9338] opened 2016-06-15 08:26 UTC
Seen in #9021.
```
• Failure [69.299 seconds]
[builds][Conformance] s2i build with a quota
/data/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:59
  Building from a template
  /data/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:58
    should create an s2i build with a quota and run it [It]
    /data/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:57

    Expected
        <string>: I0614 23:53:27.133009       1 builder.go:53] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"s2i-build-quota-1","namespace":"extended-test-s2i-build-quota-3y7bv-0wmhu","selfLink":"/oapi/v1/namespaces/extended-test-s2i-build-quota-3y7bv-0wmhu/builds/s2i-build-quota-1","uid":"2bf0ff19-328b-11e6-a502-0e7951897745","resourceVersion":"623","creationTimestamp":"2016-06-14T23:53:20Z","labels":{"buildconfig":"s2i-build-quota","name":"s2i-build-quota","openshift.io/build-config.name":"s2i-build-quota","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"s2i-build-quota","openshift.io/build.number":"1"}},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{},"secrets":null},"revision":{"type":"Git","git":{"commit":"780e46c4f5586fb8db504220ecff1c572a88d391","author":{"name":"Origin Jenkins","email":"noreply@redhat.com"},"committer":{"name":"Origin Jenkins","email":"noreply@redhat.com"},"message":"Merge branch 'bug1327108' of github.com:soltysh/origin into tpr_bug1327108_soltysh"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"centos/ruby-22-centos7"}}},"output":{},"resources":{"limits":{"cpu":"60m","memory":"200Mi"}},"postCommit":{},"triggeredBy":null},"status":{"phase":"New","config":{"kind":"BuildConfig","namespace":"extended-test-s2i-build-quota-3y7bv-0wmhu","name":"s2i-build-quota"}}}
         
        I0614 23:53:27.137903       1 builder.go:61] Build: &api.Build{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"s2i-build-quota-1", GenerateName:"", Namespace:"extended-test-s2i-build-quota-3y7bv-0wmhu", SelfLink:"/oapi/v1/namespaces/extended-test-s2i-build-quota-3y7bv-0wmhu/builds/s2i-build-quota-1", UID:"2bf0ff19-328b-11e6-a502-0e7951897745", ResourceVersion:"623", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63601545200, nsec:0, loc:(*time.Location)(0x606e7c0)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"openshift.io/build-config.name":"s2i-build-quota", "openshift.io/build.start-policy":"Serial", "buildconfig":"s2i-build-quota", "name":"s2i-build-quota"}, Annotations:map[string]string{"openshift.io/build-config.name":"s2i-build-quota", "openshift.io/build.number":"1"}}, Spec:api.BuildSpec{CommonSpec:api.CommonSpec{ServiceAccount:"builder", Source:api.BuildSource{Binary:(*api.BinaryBuildSource)(0xc8204293e0), Dockerfile:(*string)(nil), Git:(*api.GitBuildSource)(nil), Images:[]api.ImageSource(nil), ContextDir:"", SourceSecret:(*api.LocalObjectReference)(nil), Secrets:[]api.SecretBuildSource(nil)}, Revision:(*api.SourceRevision)(0xc820070548), Strategy:api.BuildStrategy{DockerStrategy:(*api.DockerBuildStrategy)(nil), SourceStrategy:(*api.SourceBuildStrategy)(0xc8200e11e0), CustomStrategy:(*api.CustomBuildStrategy)(nil), JenkinsPipelineStrategy:(*api.JenkinsPipelineBuildStrategy)(nil)}, Output:api.BuildOutput{To:(*api.ObjectReference)(nil), PushSecret:(*api.LocalObjectReference)(nil)}, Resources:api.ResourceRequirements{Limits:api.ResourceList{"cpu":resource.Quantity{Amount:0.060000000, Format:"DecimalSI"}, "memory":resource.Quantity{Amount:209715200.000000000, Format:"BinarySI"}}, Requests:api.ResourceList(nil)}, PostCommit:api.BuildPostCommitSpec{Command:[]string(nil), Args:[]string(nil), Script:""}, CompletionDeadlineSeconds:(*int64)(nil)}, TriggeredBy:[]api.BuildTriggerCause(nil)}, Status:api.BuildStatus{Phase:"New", Cancelled:false, Reason:"", Message:"", StartTimestamp:(*unversioned.Time)(nil), CompletionTimestamp:(*unversioned.Time)(nil), Duration:0, OutputDockerImageReference:"", Config:(*api.ObjectReference)(0xc82038d5e0)}}
        I0614 23:53:27.229070       1 builder.go:68] Master version "v1.3.0-alpha.1-307-g780e46c", Builder version "v1.3.0-alpha.1-307-g780e46c"
        I0614 23:53:27.231286       1 builder.go:153] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:209715200, CPUShares:61, CPUPeriod:100000, CPUQuota:6000, MemorySwap:209715200}
        I0614 23:53:27.294491       1 glog.go:50] With force pull false, setting policies to [if-not-present]
        The value of ALLOWED_UIDS is [1-]
        The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
        I0614 23:53:27.294552       1 cfg.go:45] Locating docker auth for image centos/ruby-22-centos7 and type PULL_DOCKERCFG_PATH
        I0614 23:53:27.296382       1 cfg.go:57] Problem accessing /root/.docker/config.json: stat /root/.docker/config.json: no such file or directory
        I0614 23:53:27.296400       1 cfg.go:45] Locating docker auth for image s2i-build-quota-1 and type PUSH_DOCKERCFG_PATH
        I0614 23:53:27.296450       1 cfg.go:57] Problem accessing /root/.docker/config.json: stat /root/.docker/config.json: no such file or directory
        I0614 23:53:27.409354       1 glog.go:50] error inspecting image centos/ruby-22-centos7:latest: no such image
        Image "centos/ruby-22-centos7:latest" not available locally, pulling ...
        Pulling Docker image centos/ruby-22-centos7:latest ...
        Creating a new S2I builder with build config: "Builder Name:\t\t\tRuby 2.2\nBuilder Image:\t\t\tcentos/ruby-22-centos7\nBuilder Image Version:\t\t6af4d6c1d43a5f207139814b6366cbb9af53731b\nBuilder Base Version:\t\taac5e76\nSource:\t\t\t\tfile:///tmp/s2i-build392506188/upload/src#780e46c4f5586fb8db504220ecff1c572a88d391\nOutput Image Tag:\t\textended-test-s2i-build-quota-3y7bv-0wmhu/s2i-build-quota-1:2d0c694e\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAME=s2i-build-quota-1,OPENSHIFT_BUILD_NAMESPACE=extended-test-s2i-build-quota-3y7bv-0wmhu\nIncremental Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull Policy:\t\tif-not-present\nPrevious Image Pull Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered Build:\t\t\tdisabled\nWorkdir:\t\t\t/tmp/s2i-build392506188\nDocker NetworkMode:\t\tcontainer:3e4f399a226dce41621e392f66361266a5ae89cc340c4951bc8584b6de96fa1b\nDocker Endpoint:\t\tunix:///var/run/docker.sock\n"
        Using locally available image "centos/ruby-22-centos7:latest"
        Using locally available image "centos/ruby-22-centos7:latest"
        Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
        I0614 23:54:13.439335       1 glog.go:50] Starting S2I build from [extended-test-s2i-build-quota-3y7bv-0wmhu s2i-build-quota-1]/%!s(MISSING) BuildConfig ...
        I0614 23:54:13.439365       1 sti.go:142] Preparing to build extended-test-s2i-build-quota-3y7bv-0wmhu/s2i-build-quota-1:2d0c694e
        Receiving source from STDIN as archive ...
        I0614 23:54:13.634994       1 install.go:251] Using "assemble" installed from "<source-dir>/.s2i/bin/assemble"
        I0614 23:54:13.635093       1 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
        I0614 23:54:13.635133       1 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
        I0614 23:54:13.635303       1 ignore.go:58] .s2iignore file does not exist
        I0614 23:54:13.635319       1 sti.go:151] Clean build will be performed
        I0614 23:54:13.635326       1 sti.go:154] Performing source build from file:///tmp/s2i-build392506188/upload/src#780e46c4f5586fb8db504220ecff1c572a88d391
        I0614 23:54:13.635333       1 sti.go:165] Running "assemble" in "extended-test-s2i-build-quota-3y7bv-0wmhu/s2i-build-quota-1:2d0c694e"
        I0614 23:54:13.635345       1 sti.go:467] Using image name centos/ruby-22-centos7
        I0614 23:54:13.635371       1 sti.go:319] No user environment provided (no environment file found in application sources)
        I0614 23:54:13.635685       1 sti.go:569] starting the source uploading ...
        Both scripts and untarred source will be placed in '/tmp'
        Creating container with options {Name:"" Config:&{Hostname: Domainname: User: Memory:0 MemorySwap:0 MemoryReservation:0 KernelMemory:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] StopSignal: Tty:false OpenStdin:true StdinOnce:true Env:[OPENSHIFT_BUILD_NAME=s2i-build-quota-1 OPENSHIFT_BUILD_NAMESPACE=extended-test-s2i-build-quota-3y7bv-0wmhu] Cmd:[/bin/sh -c tar -C /tmp -xf - && /tmp/scripts/assemble] DNS:[] Image:centos/ruby-22-centos7:latest Volumes:map[] VolumeDriver: VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[]} HostConfig:&{Binds:[] CapAdd:[] CapDrop:[KILL MKNOD SETGID SETUID SYS_CHROOT] GroupAdd:[] ContainerIDFile: LxcConf:[] Privileged:false PortBindings:map[] Links:[] PublishAllPorts:false DNS:[] DNSOptions:[] DNSSearch:[] ExtraHosts:[] VolumesFrom:[] NetworkMode:container:3e4f399a226dce41621e392f66361266a5ae89cc340c4951bc8584b6de96fa1b IpcMode: PidMode: UTSMode: RestartPolicy:{Name: MaximumRetryCount:0} Devices:[] LogConfig:{Type: Config:map[]} ReadonlyRootfs:false SecurityOpt:[] CgroupParent: Memory:209715200 MemorySwap:209715200 MemorySwappiness:0 OOMKillDisable:false CPUShares:61 CPUSet: CPUSetCPUs: CPUSetMEMs: CPUQuota:6000 CPUPeriod:100000 BlkioWeight:0 Ulimits:[] VolumeDriver: OomScoreAdj:0}} ...
        Attaching to container "ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b" ...
        Starting container "ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b" ...
        I0614 23:54:14.293281       1 glog.go:50] Waiting for container "ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b" to stop ...
        I0614 23:54:14.387834       1 sti.go:603] MEMORY=209715200
        I0614 23:54:14.387853       1 sti.go:603] MEMORYSWAP=209715200
        I0614 23:54:14.389421       1 sti.go:603] QUOTA=-1
        I0614 23:54:14.391235       1 sti.go:603] SHARES=61
        I0614 23:54:14.391252       1 sti.go:603] PERIOD=100000
        I0614 23:54:14.392763       1 sti.go:603] 10:net_cls:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392776       1 sti.go:603] 9:hugetlb:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392787       1 sti.go:603] 8:blkio:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392793       1 sti.go:603] 7:devices:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392799       1 sti.go:603] 6:perf_event:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392804       1 sti.go:603] 5:memory:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392810       1 sti.go:603] 4:cpuacct,cpu:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392815       1 sti.go:603] 3:freezer:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392821       1 sti.go:603] 2:cpuset:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.392827       1 sti.go:603] 1:name=systemd:/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope
        I0614 23:54:14.393351       1 sti.go:603] 126 95 253:5 /rootfs / rw,relatime - xfs /dev/mapper/docker-202:2-600768-5c01f5ea929c6bb417c371f0350fd41f16106295538a736da2d8032abb515711 rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",nouuid,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota
        I0614 23:54:14.393384       1 sti.go:603] 129 126 0:42 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
        I0614 23:54:14.393450       1 sti.go:603] 130 126 0:43 / /dev rw,nosuid - tmpfs tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.393458       1 sti.go:603] 131 130 0:65 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",gid=5,mode=620,ptmxmode=666
        I0614 23:54:14.393466       1 sti.go:603] 132 130 0:41 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw,seclabel
        I0614 23:54:14.393472       1 sti.go:603] 133 126 0:76 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro,seclabel
        I0614 23:54:14.393478       1 sti.go:603] 134 133 0:66 / /sys/fs/cgroup ro,nosuid,nodev,noexec,relatime - tmpfs tmpfs ro,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.393484       1 sti.go:603] 135 134 0:20 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime master:9 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
        I0614 23:54:14.393490       1 sti.go:603] 284 134 0:22 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime master:10 - cgroup cgroup rw,cpuset
        I0614 23:54:14.393497       1 sti.go:603] 285 134 0:23 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime master:11 - cgroup cgroup rw,freezer
        I0614 23:54:14.393503       1 sti.go:603] 287 134 0:24 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/cpuacct,cpu ro,nosuid,nodev,noexec,relatime master:12 - cgroup cgroup rw,cpuacct,cpu
        I0614 23:54:14.393510       1 sti.go:603] 288 134 0:25 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime master:13 - cgroup cgroup rw,memory
        I0614 23:54:14.393516       1 sti.go:603] 289 134 0:26 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime master:14 - cgroup cgroup rw,perf_event
        I0614 23:54:14.393521       1 sti.go:603] 290 134 0:27 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime master:15 - cgroup cgroup rw,devices
        I0614 23:54:14.393527       1 sti.go:603] 291 134 0:28 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,blkio
        I0614 23:54:14.393534       1 sti.go:603] 292 134 0:29 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime master:17 - cgroup cgroup rw,hugetlb
        I0614 23:54:14.393540       1 sti.go:603] 293 134 0:30 /system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope /sys/fs/cgroup/net_cls ro,nosuid,nodev,noexec,relatime master:18 - cgroup cgroup rw,net_cls
        I0614 23:54:14.393546       1 sti.go:603] 294 126 202:2 /var/lib/docker/containers/ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b/secrets /run/secrets rw,relatime master:1 - xfs /dev/xvda2 rw,seclabel,attr2,inode64,noquota
        I0614 23:54:14.393552       1 sti.go:603] 295 126 202:2 /var/lib/docker/containers/947c4f609475ce058e625568c8432e62e2ba7fd7f1cc2170f0c08a4563f35b04/resolv.conf /etc/resolv.conf rw,relatime - xfs /dev/xvda2 rw,seclabel,attr2,inode64,noquota
        I0614 23:54:14.393558       1 sti.go:603] 296 126 202:2 /var/lib/docker/containers/947c4f609475ce058e625568c8432e62e2ba7fd7f1cc2170f0c08a4563f35b04/hostname /etc/hostname rw,relatime - xfs /dev/xvda2 rw,seclabel,attr2,inode64,noquota
        I0614 23:54:14.393565       1 sti.go:603] 297 126 253:2 /pods/2c06ab56-328b-11e6-a502-0e7951897745/etc-hosts /etc/hosts rw,relatime - xfs /dev/mapper/docker--vg-openshift--xfs--vol--dir rw,seclabel,attr2,inode64,grpquota
        I0614 23:54:14.393588       1 sti.go:603] 298 130 0:40 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",size=65536k
        I0614 23:54:14.393595       1 sti.go:603] 111 129 0:42 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
        I0614 23:54:14.393600       1 sti.go:603] 112 129 0:42 /fs /proc/fs ro,nosuid,nodev,noexec,relatime - proc proc rw
        I0614 23:54:14.393614       1 sti.go:603] 113 129 0:42 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
        I0614 23:54:14.393622       1 sti.go:603] 151 129 0:42 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
        I0614 23:54:14.393627       1 sti.go:603] 161 129 0:42 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
        I0614 23:54:14.393633       1 sti.go:603] 162 129 0:43 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.393639       1 sti.go:603] 184 129 0:43 /null /proc/timer_stats rw,nosuid - tmpfs tmpfs rw,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.417741       1 sti.go:603] TARGET                           SOURCE                                                                                                              FSTYPE OPTIONS
        I0614 23:54:14.417764       1 sti.go:603] /                                /dev/mapper/docker-202:2-600768-5c01f5ea929c6bb417c371f0350fd41f16106295538a736da2d8032abb515711[/rootfs]           xfs    rw,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",nouuid,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota
        I0614 23:54:14.417797       1 sti.go:603] |-/proc                          proc                                                                                                                proc   rw,nosuid,nodev,noexec,relatime
        I0614 23:54:14.417807       1 sti.go:603] | |-/proc/bus                    proc[/bus]                                                                                                          proc   ro,nosuid,nodev,noexec,relatime
        I0614 23:54:14.417813       1 sti.go:603] | |-/proc/fs                     proc[/fs]                                                                                                           proc   ro,nosuid,nodev,noexec,relatime
        I0614 23:54:14.417819       1 sti.go:603] | |-/proc/irq                    proc[/irq]                                                                                                          proc   ro,nosuid,nodev,noexec,relatime
        I0614 23:54:14.417827       1 sti.go:603] | |-/proc/sys                    proc[/sys]                                                                                                          proc   ro,nosuid,nodev,noexec,relatime
        I0614 23:54:14.417833       1 sti.go:603] | |-/proc/sysrq-trigger          proc[/sysrq-trigger]                                                                                                proc   ro,nosuid,nodev,noexec,relatime
        I0614 23:54:14.417841       1 sti.go:603] | |-/proc/kcore                  tmpfs[/null]                                                                                                        tmpfs  rw,nosuid,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.417847       1 sti.go:603] | `-/proc/timer_stats            tmpfs[/null]                                                                                                        tmpfs  rw,nosuid,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.417855       1 sti.go:603] |-/dev                           tmpfs                                                                                                               tmpfs  rw,nosuid,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.417862       1 sti.go:603] | |-/dev/pts                     devpts                                                                                                              devpts rw,nosuid,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",gid=5,mode=620,ptmxmode=666
        I0614 23:54:14.417877       1 sti.go:603] | |-/dev/mqueue                  mqueue                                                                                                              mqueue rw,nosuid,nodev,noexec,relatime,seclabel
        I0614 23:54:14.417886       1 sti.go:603] | `-/dev/shm                     shm                                                                                                                 tmpfs  rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",size=65536k
        I0614 23:54:14.417892       1 sti.go:603] |-/sys                           sysfs                                                                                                               sysfs  ro,nosuid,nodev,noexec,relatime,seclabel
        I0614 23:54:14.417903       1 sti.go:603] | `-/sys/fs/cgroup               tmpfs                                                                                                               tmpfs  ro,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c601,c827",mode=755
        I0614 23:54:14.417910       1 sti.go:603] |   |-/sys/fs/cgroup/systemd     cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
        I0614 23:54:14.417917       1 sti.go:603] |   |-/sys/fs/cgroup/cpuset      cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,cpuset
        I0614 23:54:14.417926       1 sti.go:603] |   |-/sys/fs/cgroup/freezer     cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,freezer
        I0614 23:54:14.417932       1 sti.go:603] |   |-/sys/fs/cgroup/cpuacct,cpu cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,cpuacct,cpu
        I0614 23:54:14.417937       1 sti.go:603] |   |-/sys/fs/cgroup/memory      cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,memory
        I0614 23:54:14.417943       1 sti.go:603] |   |-/sys/fs/cgroup/perf_event  cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,perf_event
        I0614 23:54:14.417949       1 sti.go:603] |   |-/sys/fs/cgroup/devices     cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,devices
        I0614 23:54:14.417956       1 sti.go:603] |   |-/sys/fs/cgroup/blkio       cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,blkio
        I0614 23:54:14.417962       1 sti.go:603] |   |-/sys/fs/cgroup/hugetlb     cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,hugetlb
        I0614 23:54:14.417968       1 sti.go:603] |   `-/sys/fs/cgroup/net_cls     cgroup[/system.slice/docker-ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b.scope]                 cgroup ro,nosuid,nodev,noexec,relatime,net_cls
        I0614 23:54:14.417973       1 sti.go:603] |-/run/secrets                   /dev/xvda2[/var/lib/docker/containers/ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b/secrets]     xfs    rw,relatime,seclabel,attr2,inode64,noquota
        I0614 23:54:14.417979       1 sti.go:603] |-/etc/resolv.conf               /dev/xvda2[/var/lib/docker/containers/947c4f609475ce058e625568c8432e62e2ba7fd7f1cc2170f0c08a4563f35b04/resolv.conf] xfs    rw,relatime,seclabel,attr2,inode64,noquota
        I0614 23:54:14.417985       1 sti.go:603] |-/etc/hostname                  /dev/xvda2[/var/lib/docker/containers/947c4f609475ce058e625568c8432e62e2ba7fd7f1cc2170f0c08a4563f35b04/hostname]    xfs    rw,relatime,seclabel,attr2,inode64,noquota
        I0614 23:54:14.417991       1 sti.go:603] `-/etc/hosts                     /dev/mapper/docker--vg-openshift--xfs--vol--dir[/pods/2c06ab56-328b-11e6-a502-0e7951897745/etc-hosts]               xfs    rw,relatime,seclabel,attr2,inode64,grpquota
        Invoking PostExecute function
        I0614 23:54:14.507259       1 sti.go:319] No user environment provided (no environment file found in application sources)
        I0614 23:54:14.512630       1 labels.go:44] Unable to fetch source informations, the output image labels will not be set
        Committing container with dockerOpts: {Container:ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b Repository:extended-test-s2i-build-quota-3y7bv-0wmhu/s2i-build-quota-1 Tag:2d0c694e Message: Author: Run:0xc820063500}, config: {Hostname: Domainname: User:1001 Memory:0 MemorySwap:0 MemoryReservation:0 KernelMemory:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:false AttachStderr:false PortSpecs:[] ExposedPorts:map[] StopSignal: Tty:false OpenStdin:false StdinOnce:false Env:[OPENSHIFT_BUILD_NAME=s2i-build-quota-1 OPENSHIFT_BUILD_NAMESPACE=extended-test-s2i-build-quota-3y7bv-0wmhu] Cmd:[/usr/libexec/s2i/run] DNS:[] Image: Volumes:map[] VolumeDriver: VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[io.openshift.builder-version:6af4d6c1d43a5f207139814b6366cbb9af53731b license:GPLv2 io.openshift.expose-services:8080:http io.openshift.s2i.scripts-url:image:///usr/libexec/s2i io.openshift.tags:builder,ruby,ruby22 io.s2i.scripts-url:image:///usr/libexec/s2i name:CentOS Base Image vendor:CentOS build-date:2016-06-02 io.openshift.build.image:centos/ruby-22-centos7 io.k8s.description:Platform for building and running Ruby 2.2 applications io.k8s.display-name:extended-test-s2i-build-quota-3y7bv-0wmhu/s2i-build-quota-1:2d0c694e io.openshift.builder-base-version:aac5e76]}
        I0614 23:54:18.734515       1 sti.go:296] Successfully built extended-test-s2i-build-quota-3y7bv-0wmhu/s2i-build-quota-1:2d0c694e
        I0614 23:54:18.734543       1 glog.go:50] Removing container "ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b" ...
        I0614 23:54:18.792449       1 glog.go:50] Removed container "ae3da1203ce2ae1a522aeceac443160ddc1c4a669f78330920dad8421fa5400b"
        I0614 23:54:18.792623       1 cleanup.go:31] Removing temporary directory /tmp/s2i-build392506188
        I0614 23:54:18.792642       1 fs.go:156] Removing directory '/tmp/s2i-build392506188'
        Build complete, no image push requested
    to contain substring
        <string>: QUOTA=6000
```

Full log is [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2062/consoleFull).

@bparees or @miminar I'm not quite sure which of the two of you can have a look at it.

**Comment by bparees** [comment] 2016-06-15 15:24
dupe of https://github.com/openshift/origin/issues/8427 but @mrunalp should be alerted it's still happening.

**Closed by bparees** 2016-06-15 15:24 UTC
Labels: component/build, kind/test-flake, priority/P2
