### ISSUE TITLE
Vagrant cluster configuration fails

### ISSUE THREAD

**Issue by scollier** [openshift/origin#1569] opened 2015-04-02 11:48 UTC
I am on a Fedora 21 host with a libvirt / vagrant configuration:

$ rpm -qa | grep vagrant
vagrant-1.7.2-3.fc21.1.noarch
vagrant-libvirt-0.0.24-3.fc21.noarch
rubygem-vagrant-libvirt-0.0.20-2.fc20.noarch

$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)

Top of the branch I'm working on:

commit 11f00abc77ffd25d73aaa4c58cd92be461ce8fce
Merge: 9c90068 dc21506
Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>
Date:   Wed Apr 1 19:44:39 2015 -0400

    Merge pull request #1560 from smarterclayton/allow_project_change_with_empty_namespcae
    
    Merged by openshift-bot

When I run the following command, it does not work:

$ git clone github.com/openshift/origin; cd origin; export OPENSHIFT_DEV_CLUSTER=1; export OPENSHIFT_NUM_MINIONS=2 ; vagrant up

It fails with the following error for each node:

==> master: Creating shared folders metadata...
==> master: Setting hostname...
==> minion-2: An error occurred. The error will be shown after all tasks complete.
==> minion-1: An error occurred. The error will be shown after all tasks complete.
==> master: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'master'
machine. Please handle this error then try again:

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

service network restart

Stdout from the command:

Restarting network (via systemctl):  [FAILED]

Stderr from the command:

Job for network.service failed. See "systemctl status network.service" and "journalctl -xe" for details.

An error occurred while executing the action on the 'minion-1'
machine. Please handle this error then try again:

The VMs are running though:

$ vagrant status
Current machine states:

master                    running (libvirt)
minion-1                  running (libvirt)
minion-2                  running (libvirt)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

If you take a look at the master VM, for example, you can see that the interface is not correct:

$ ls /etc/sysconfig/network-scripts/ | grep ifcfg
ifcfg-enp0s3

But that interface does not exist on the VM.  On the VM, it's eth0.

The single node dev env deploys Okay:

$ vagrant status
Current machine states:

openshiftdev              running (libvirt)

**Comment by vchepeli** [comment] 2015-04-16 07:14
Same error for me, do not why it tries to restart networking service with no rights
Bringing machine 'master' up with 'libvirt' provider...
Bringing machine 'minion-1' up with 'libvirt' provider...
Bringing machine 'minion-2' up with 'libvirt' provider...
==> master: Uploading base box image as volume into libvirt storage...
==> minion-1: An error occurred. The error will be shown after all tasks complete.
==> minion-2: Creating image (snapshot of base box volume).
Progress: 0%==> minion-2: Creating domain with the following settings...
==> minion-2:  -- Name:              openshift-origin_minion-2
Progress: 0%==> minion-2:  -- Domain type:       kvm
==> minion-2:  -- Cpus:              2
==> minion-2:  -- Memory:            1024M
==> minion-2:  -- Base box:          fedora_inst
==> minion-2:  -- Storage pool:      default
Progress: 0%==> minion-2:  -- Image:             /var/lib/libvirt/images/openshift-origin_minion-2.img
==> minion-2:  -- Volume Cache:      default
==> minion-2:  -- Kernel:            
==> minion-2:  -- Initrd:            
==> minion-2:  -- Graphics Type:     vnc
==> minion-2:  -- Graphics Port:     5900
==> minion-2:  -- Graphics IP:       127.0.0.1
==> minion-2:  -- Graphics Password: Not defined
==> minion-2:  -- Video Type:        cirrus
==> minion-2:  -- Video VRAM:        9216
==> minion-2:  -- Command line : 
Progress: 0%==> minion-2: Starting domain.
Progress: 0%==> minion-2: Waiting for domain to get an IP address...
==> master: Creating image (snapshot of base box volume).
==> master: Creating domain with the following settings...
==> master:  -- Name:              openshift-origin_master
==> master:  -- Domain type:       kvm
==> master:  -- Cpus:              2
==> master:  -- Memory:            1024M
==> master:  -- Base box:          fedora_inst
==> master:  -- Storage pool:      default
==> master:  -- Image:             /var/lib/libvirt/images/openshift-origin_master.img
==> master:  -- Volume Cache:      default
==> master:  -- Kernel:            
==> master:  -- Initrd:            
==> master:  -- Graphics Type:     vnc
==> master:  -- Graphics Port:     5900
==> master:  -- Graphics IP:       127.0.0.1
==> master:  -- Graphics Password: Not defined
==> master:  -- Video Type:        cirrus
==> master:  -- Video VRAM:        9216
==> master:  -- Command line : 
==> master: Starting domain.
==> master: Waiting for domain to get an IP address...
==> master: Waiting for SSH to become available...
    master: 
    master: Vagrant insecure key detected. Vagrant will automatically replace
    master: this with a newly generated keypair for better security.
    master: 
    master: Inserting generated public key within guest...
    master: Removing insecure key from the guest if its present...
    master: Key inserted! Disconnecting and reconnecting using new SSH key...
==> master: Starting domain.
==> master: Waiting for domain to get an IP address...
==> master: Waiting for SSH to become available...
==> master: Creating shared folders metadata...
==> master: Setting hostname...
==> master: An error occurred. The error will be shown after all tasks complete.
==> minion-2: Removing domain...
==> minion-2: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.
An error occurred while executing the action on the 'master'
machine. Please handle this error then try again:
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
service network restart
Stdout from the command:
Restarting network (via systemctl):  [FAILED]
Stderr from the command:
Job for network.service failed. See "systemctl status network.service" and "journalctl -xe" for details.
An error occurred while executing the action on the 'minion-1'
machine. Please handle this error then try again:
There was error while creating libvirt storage pool: Call to virStoragePoolCreateXML failed: operation failed: pool 'default' already exists with uuid b7051f4d-aec8-4bc5-b821-6a058a6343d0
An unexpected error occurred when executing the action on the
'minion-2' machine. Please report this as a bug:
The specified wait_for timeout (2 seconds) was exceeded
/usr/share/gems/gems/fog-core-1.22.0/lib/fog/core/wait_for.rb:11:in `wait_for'
/usr/share/gems/gems/fog-core-1.22.0/lib/fog/core/model.rb:65:in `wait_for'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/wait_till_up.rb:38:in `block (2 levels) in call'
/usr/share/vagrant/lib/vagrant/util/retryable.rb:17:in `retryable'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/wait_till_up.rb:33:in `block in call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/util/timer.rb:9:in `time'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/wait_till_up.rb:31:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/start_domain.rb:26:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/create_network_interfaces.rb:102:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/create_networks.rb:76:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/provision.rb:80:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/create_domain.rb:137:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/handle_box_image.rb:38:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/handle_storage_pool.rb:21:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
/usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
/usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
/usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
/usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
/usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by dcbw** [comment] 2015-04-24 20:40
This error happens because with libvirt, the network interface is recognized by udev as a virtual one, and is renamed to 'eth0' from its original 'enp0s25' or whatever it is.  But dracut has written out an initial network configuration file that references enp0s25, and when the sysvinit 'network' service starts it fails because enp0s25 cannot be found.  This makes vagrant fail.

There's a couple other hacks you need to make Fedora 21 + libvirt work, which I've detailed here: https://github.com/dcbw/origin/commit/a57a926ffd5b8df006892b75fc0359d1c9e68010

I'll reproduce that commit message here too:

1) Because udev renames network devices from their original enpXsY to
eth0 (since they are virtual and not hardware), the interface given
by the ifcfg-* file does not exist when 'service network restart'
is run, and that command fails, which fails provisioning.

fix /usr/share/vagrant/plugins/guests/redhat/cap/change_host_name.rb:

  def restart_networking
+   sudo 'rm -f /etc/sysconfig/network-scripts/ifcfg-enp*'
    sudo 'service network restart'

2) recent Fedora also use /etc/hostname instead of
/etc/sysconfig/network for hostname storage, so the same procedure
used for RHEL7 updating the hostname must be done for Fedora 20+ too.

Fix /usr/share/vagrant/plugins/guests/redhat/cap/change_host_name.rb:

    update_etc_hosts
  else
+   update_hostname_rhel7
    update_sysconfig

3) This patch creates static IP configuration files for the main
network interface, which ensures that the interface has an IP known
to OpenShift.

4) make sure that your host firewall doesn't block NFS access.  You
might need to do something like:
    sudo firewall-cmd --permanent --add-service=nfs
    sudo firewall-cmd --permanent --add-service=rpc-bind
    sudo firewall-cmd --permanent --add-service=mountd
    sudo firewall-cmd --reload
See: http://nts.strzibny.name/vagrant-nfs-exports-on-fedora-21/

5) You might have to start the master first, or use --no-parallel.
Since the 'libvirt' provider allows parallel provisioning, the
minions will race with the master to access the certificates which
may not yet have been created by the master.

**Comment by rajatchopra** [comment] 2015-05-11 22:45
Should be fixed with the new fedora21 images after this fix went in:
https://github.com/openshift/vagrant-openshift/pull/258
Short summary: ifcfg-enp0s3 is deleted, and udev rules enforce older naming scheme.

**Comment by scollier** [comment] 2015-05-11 23:21
Thanks.  I'll give it a test and report back.

**Comment by dcbw** [comment] 2015-05-12 22:52
Also note that vagrant-1.7.2 from Fedora 21 doesn't correctly detect a Fedora 21 guest.  Once you have these two vagrant changes:

https://github.com/mitchellh/vagrant/commit/760b9daab77c26df1a43af8f9c12254589d219d4
https://github.com/mitchellh/vagrant/commit/b776fe74b88f6ac8deac6a91f4e886e205a2f3de

things should go much more smoothly along with Rajat's fix.

**Closed** 2015-05-15 17:59 UTC
Labels: component/install, component/networking, kind/bug, priority/P2
