### ISSUE TITLE
 Openshift Origin: The global template library is missing

### ISSUE THREAD

**Issue by garyyang6** [openshift/origin#17390] opened 2017-11-20 17:32 UTC
[provide a description of the issue]
I installed openshift-origin-server-v3.6.1-008f2d5-linux-64bit.tar.gz at CentOS 7. The global template library is missing when I logon to the web console.

The Browse Catalog should show global template library. Please see https://docs.openshift.org/latest/dev_guide/templates.html#uploading-a-template at the section,  "2. Select a template from the list of templates in your project, or provided by the global template library:"
Logon to https://localhost:8443. Create a project. But, the global template library is not there. The global template library is missing.

##### Version
[provide output of the `openshift version` or `oc version` command]
./openshift version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
docker version
Client:
Version: 1.12.6
API version: 1.24
Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
Go version: go1.8.3
Git commit: 85d7426/1.12.6
Built: Tue Oct 24 15:40:21 2017
OS/Arch: linux/amd64
Server:
Version: 1.12.6
API version: 1.24
Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
Go version: go1.8.3
Git commit: 85d7426/1.12.6
Built: Tue Oct 24 15:40:21 2017
OS/Arch: linux/amd64
##### Steps To Reproduce
1. [step 1]
Installed openshift-origin-server-v3.6.1-008f2d5-linux-64bit.tar.gz at CentOS 7.
2. [step 2]
Start openshift server.
##### Current Result
Global template library
##### Expected Result
I should see the global template library.
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by simo5** [comment] 2017-11-20 18:55
Duplicate of #17371

**Closed** 2017-11-20 20:10 UTC
