### ISSUE TITLE
github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:15: executing 'oc get -n test pods -l name=database' expecting any result and text 'Running'; re-trying every 0.2s until completion or 60.000s

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15469] opened 2017-07-26 06:41 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4834/

**Comment by pweil-** [comment] 2017-07-26 19:16
duplicate of https://github.com/openshift/origin/issues/14090

**Closed by pweil-** 2017-07-26 19:16 UTC
Labels: kind/test-flake
