### ISSUE TITLE
idling and unidling idling with a single service and DeploymentConfig [Conformance]

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#12235] opened 2016-12-12 22:27 UTC
```
idling and unidling idling with a single service and DeploymentConfig [Conformance] 
  should idle the service and DeploymentConfig properly
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:261

[BeforeEach] [Top Level]
  /data/src/github.com/openshift/origin/test/extended/util/test.go:45
[BeforeEach] idling and unidling
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:133
STEP: Creating a kubernetes client
Dec  9 21:44:03.678: INFO: >>> kubeConfig: /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig

STEP: Building a namespace api object
Dec  9 21:44:03.949: INFO: configPath is now "/tmp/extended-test-cli-idling-9vl8w-v9yik-user.kubeconfig"
Dec  9 21:44:03.949: INFO: The user is now "extended-test-cli-idling-9vl8w-v9yik-user"
Dec  9 21:44:03.949: INFO: Creating project "extended-test-cli-idling-9vl8w-v9yik"
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] with a single service and DeploymentConfig [Conformance]
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:257
STEP: Building a namespace api object
Dec  9 21:44:04.189: INFO: configPath is now "/tmp/extended-test-cli-idling-9vl8w-wj8zi-user.kubeconfig"
Dec  9 21:44:04.189: INFO: The user is now "extended-test-cli-idling-9vl8w-wj8zi-user"
Dec  9 21:44:04.189: INFO: Creating project "extended-test-cli-idling-9vl8w-wj8zi"
STEP: Waiting for a default service account to be provisioned in namespace
[JustBeforeEach] idling and unidling
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:245
STEP: Creating the resources
Dec  9 21:44:04.335: INFO: Running 'oc create --config=/tmp/extended-test-cli-idling-9vl8w-wj8zi-user.kubeconfig --namespace=extended-test-cli-idling-9vl8w-wj8zi -f /data/src/github.com/openshift/origin/test/extended/testdata/idling-echo-server.yaml -o name'
STEP: Creating the idling file
STEP: Waiting for the endpoints to exist
STEP: Waiting for endpoints to be up
[AfterEach] idling and unidling
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134
STEP: Collecting events from namespace "extended-test-cli-idling-9vl8w-wj8zi".
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:04 -0500 EST - event for idling-echo: {deploymentconfig-controller } DeploymentCreated: Created new replication controller "idling-echo-1" for version 1
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:04 -0500 EST - event for idling-echo-1-deploy: {default-scheduler } Scheduled: Successfully assigned idling-echo-1-deploy to 172.18.9.234
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:09 -0500 EST - event for idling-echo-1-deploy: {kubelet 172.18.9.234} Created: Created container with docker id 458af1e7d27d; Security:[seccomp=unconfined]
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:09 -0500 EST - event for idling-echo-1-deploy: {kubelet 172.18.9.234} Pulled: Container image "openshift/origin-deployer:9e80c1c" already present on machine
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:10 -0500 EST - event for idling-echo-1-deploy: {kubelet 172.18.9.234} Started: Started container with docker id 458af1e7d27d
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:11 -0500 EST - event for idling-echo-1: {replication-controller } SuccessfulCreate: Created pod: idling-echo-1-hmk0s
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:11 -0500 EST - event for idling-echo-1: {replication-controller } SuccessfulCreate: Created pod: idling-echo-1-89esl
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:11 -0500 EST - event for idling-echo-1-89esl: {default-scheduler } Scheduled: Successfully assigned idling-echo-1-89esl to 172.18.9.234
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:11 -0500 EST - event for idling-echo-1-hmk0s: {default-scheduler } Scheduled: Successfully assigned idling-echo-1-hmk0s to 172.18.9.234
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:14 -0500 EST - event for idling-echo-1-hmk0s: {kubelet 172.18.9.234} Pulling: pulling image "openshift/node"
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:44:15 -0500 EST - event for idling-echo-1-89esl: {kubelet 172.18.9.234} Pulling: pulling image "openshift/node"
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:45:51 -0500 EST - event for idling-echo-1-89esl: {kubelet 172.18.9.234} Pulled: Successfully pulled image "openshift/node"
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:45:51 -0500 EST - event for idling-echo-1-hmk0s: {kubelet 172.18.9.234} Pulled: Successfully pulled image "openshift/node"
Dec  9 21:46:04.803: INFO: At 2016-12-09 21:46:01 -0500 EST - event for idling-echo-1-89esl: {kubelet 172.18.9.234} Created: Created container with docker id db955712daee; Security:[seccomp=unconfined]
Dec  9 21:46:04.813: INFO: POD                         NODE          PHASE    GRACE  CONDITIONS
Dec  9 21:46:04.813: INFO: docker-registry-1-8ekm2     172.18.9.234  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:43:31 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:43:41 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:43:31 -0500 EST  }]
Dec  9 21:46:04.814: INFO: router-2-3iuru              172.18.9.234  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:02 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:22 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:02 -0500 EST  }]
Dec  9 21:46:04.814: INFO: pod-0                       172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST ContainersNotReady containers with unready status: [busybox]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST  }]
Dec  9 21:46:04.814: INFO: pod-1                       172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST ContainersNotReady containers with unready status: [busybox]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST  }]
Dec  9 21:46:04.814: INFO: pod-2                       172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST ContainersNotReady containers with unready status: [busybox]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:03 -0500 EST  }]
Dec  9 21:46:04.814: INFO: update-demo-nautilus-qakjw  172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:51 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:51 -0500 EST ContainersNotReady containers with unready status: [update-demo]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:46 -0500 EST  }]
Dec  9 21:46:04.814: INFO: update-demo-nautilus-tgy0t  172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:51 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:51 -0500 EST ContainersNotReady containers with unready status: [update-demo]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:46 -0500 EST  }]
Dec  9 21:46:04.814: INFO: example-1-deploy            172.18.9.234  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:43:58 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:00 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:43:58 -0500 EST  }]
Dec  9 21:46:04.814: INFO: example-1-e2fis             172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:00 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:00 -0500 EST ContainersNotReady containers with unready status: [ruby mongodb]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:00 -0500 EST  }]
Dec  9 21:46:04.814: INFO: idling-echo-1-89esl         172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:11 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:11 -0500 EST ContainersNotReady containers with unready status: [idling-tcp-echo idling-udp-echo]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:11 -0500 EST  }]
Dec  9 21:46:04.814: INFO: idling-echo-1-deploy        172.18.9.234  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:05 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:13 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:04 -0500 EST  }]
Dec  9 21:46:04.814: INFO: idling-echo-1-hmk0s         172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:11 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:11 -0500 EST ContainersNotReady containers with unready status: [idling-tcp-echo idling-udp-echo]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:44:11 -0500 EST  }]
Dec  9 21:46:04.814: INFO: endpoint-1                  172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:50 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:50 -0500 EST ContainersNotReady containers with unready status: [test]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:35 -0500 EST  }]
Dec  9 21:46:04.814: INFO: endpoint-2                  172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:50 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:50 -0500 EST ContainersNotReady containers with unready status: [test]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:35 -0500 EST  }]
Dec  9 21:46:04.814: INFO: weighted-router             172.18.9.234  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:40 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:40 -0500 EST ContainersNotReady containers with unready status: [router]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-12-09 21:45:35 -0500 EST  }]
Dec  9 21:46:04.814: INFO: 
Dec  9 21:46:04.816: INFO: 
Logging node info for node 172.18.9.234
Dec  9 21:46:04.819: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
Dec  9 21:46:04.819: INFO: 
Logging kubelet events for node 172.18.9.234
Dec  9 21:46:04.820: INFO: 
Logging pods the kubelet thinks is on node 172.18.9.234
Dec  9 21:46:04.832: INFO: example-1-deploy started at 2016-12-09 21:43:58 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container deployment ready: true, restart count 0
Dec  9 21:46:04.832: INFO: docker-registry-1-8ekm2 started at 2016-12-09 21:43:31 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container registry ready: true, restart count 0
Dec  9 21:46:04.832: INFO: pod-1 started at 2016-12-09 21:44:03 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container busybox ready: false, restart count 0
Dec  9 21:46:04.832: INFO: idling-echo-1-deploy started at 2016-12-09 21:44:05 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container deployment ready: true, restart count 0
Dec  9 21:46:04.832: INFO: weighted-router started at 2016-12-09 21:45:40 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container router ready: false, restart count 0
Dec  9 21:46:04.832: INFO: idling-echo-1-hmk0s started at 2016-12-09 21:44:11 -0500 EST (0+2 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container idling-tcp-echo ready: false, restart count 0
Dec  9 21:46:04.832: INFO: 	Container idling-udp-echo ready: false, restart count 0
Dec  9 21:46:04.832: INFO: endpoint-1 started at 2016-12-09 21:45:50 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container test ready: false, restart count 0
Dec  9 21:46:04.832: INFO: update-demo-nautilus-qakjw started at 2016-12-09 21:45:51 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container update-demo ready: false, restart count 0
Dec  9 21:46:04.832: INFO: router-2-3iuru started at 2016-12-09 21:44:02 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container router ready: true, restart count 0
Dec  9 21:46:04.832: INFO: pod-0 started at 2016-12-09 21:44:03 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container busybox ready: false, restart count 0
Dec  9 21:46:04.832: INFO: pod-2 started at 2016-12-09 21:44:03 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container busybox ready: false, restart count 0
Dec  9 21:46:04.832: INFO: idling-echo-1-89esl started at 2016-12-09 21:44:11 -0500 EST (0+2 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container idling-tcp-echo ready: false, restart count 0
Dec  9 21:46:04.832: INFO: 	Container idling-udp-echo ready: false, restart count 0
Dec  9 21:46:04.832: INFO: endpoint-2 started at 2016-12-09 21:45:50 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container test ready: false, restart count 0
Dec  9 21:46:04.832: INFO: example-1-e2fis started at 2016-12-09 21:44:00 -0500 EST (0+2 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container mongodb ready: false, restart count 0
Dec  9 21:46:04.832: INFO: 	Container ruby ready: false, restart count 0
Dec  9 21:46:04.832: INFO: update-demo-nautilus-tgy0t started at 2016-12-09 21:45:51 -0500 EST (0+1 container statuses recorded)
Dec  9 21:46:04.832: INFO: 	Container update-demo ready: false, restart count 0
W1209 21:46:04.838246   15058 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
Dec  9 21:46:18.065: INFO: 
Latency metrics for node 172.18.9.234
Dec  9 21:46:18.065: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:1m35.114514s}
Dec  9 21:46:18.065: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:1m23.642835s}
Dec  9 21:46:18.065: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.9 Latency:1m3.419558s}
Dec  9 21:46:18.065: INFO: {Operation:runContainerInPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:36.189257s}
Dec  9 21:46:18.065: INFO: {Operation: Method:pleg_relist_latency_microseconds Quantile:0.99 Latency:28.478252s}
Dec  9 21:46:18.065: INFO: {Operation:GetPods Method:container_manager_latency_microseconds Quantile:0.99 Latency:25.087461s}
Dec  9 21:46:18.065: INFO: {Operation:list_containers Method:docker_operations_latency_microseconds Quantile:0.99 Latency:25.087185s}
Dec  9 21:46:18.065: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:14.932631s}
Dec  9 21:46:18.065: INFO: {Operation: Method:pod_worker_start_latency_microseconds Quantile:0.99 Latency:14.499175s}
Dec  9 21:46:18.065: INFO: {Operation:createPodInfraContainer Method:container_manager_latency_microseconds Quantile:0.99 Latency:13.933873s}
Dec  9 21:46:18.065: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:12.191778s}
Dec  9 21:46:18.065: INFO: {Operation:create_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:10.373333s}
STEP: Dumping a list of prepulled images on each node
Dec  9 21:46:18.067: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "extended-test-cli-idling-9vl8w-v9yik" for this suite.
Dec  9 21:46:23.107: INFO: namespace: extended-test-cli-idling-9vl8w-v9yik, resource: bindings, ignored listing per whitelist
STEP: Destroying namespace "extended-test-cli-idling-9vl8w-wj8zi" for this suite.
Dec  9 21:46:43.150: INFO: namespace: extended-test-cli-idling-9vl8w-wj8zi, resource: bindings, ignored listing per whitelist
[AfterEach] idling and unidling
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:250
STEP: Cleaning up the idling file


• Failure in Spec Setup (JustBeforeEach) [159.485 seconds]
idling and unidling
/data/src/github.com/openshift/origin/test/extended/idling/idling.go:466
  idling [JustBeforeEach]
  /data/src/github.com/openshift/origin/test/extended/idling/idling.go:274
    with a single service and DeploymentConfig [Conformance]
    /data/src/github.com/openshift/origin/test/extended/idling/idling.go:262
      should idle the service and DeploymentConfig properly
      /data/src/github.com/openshift/origin/test/extended/idling/idling.go:261

      Expected error:
          <*errors.errorString | 0xc8200d1780>: {
              s: "timed out waiting for the condition",
          }
          timed out waiting for the condition
      not to have occurred

      /data/src/github.com/openshift/origin/test/extended/idling/idling.go:244
```

**Comment by mmilata** [comment] 2016-12-13 11:07
Similar: #10988, #12137

**Comment by smarterclayton** [comment] 2017-02-17 20:44
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/669/testReport/junit/(root)/Extended/idling_and_unidling_idling_with_a_single_service_and_DeploymentConfig__Conformance__should_idle_the_service_and_DeploymentConfig_properly/

**Comment by DirectXMan12** [comment] 2017-03-06 20:59
The original issue (from December 12th) looks like it was caused by no endpoints being available.  Basically, before we start the test, we wait for the endpoints object to be populated so that we can actually run idle.  If pods fail to come up as ready in 3 minutes, then you'd see this failure.

As for the issue from Feb 17, I was under the impression that switching to a `patch` operation was supposed to fix issues like that?

**Comment by DirectXMan12** [comment] 2017-03-06 21:46
cc @juanvallejo

**Comment by DirectXMan12** [comment] 2017-03-08 18:40
actually, unless I'm reading it wrong, that failure came from https://github.com/openshift/origin/pull/12974, which is based on an older branch that does not have the patch code.  I think we can probably close this, unless anyone has any objections

**Comment by juanvallejo** [comment] 2017-03-08 20:45
I am okay with closing for now, and re-opening if we see this happen again.

**Closed by juanvallejo** 2017-03-08 20:45 UTC
Labels: component/deployments, kind/test-flake, priority/P1
