### ISSUE TITLE
etcdhelper: loads of garbage output

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#16091] opened 2017-08-31 19:50 UTC
<details>
<summary>Seen in cleanup:</summary>

```
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v2alpha1.batch"?/apis/apiregistration.k8s.io/v1beta1/apiservices/v2alpha1.batch*$8c73712c-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruezbatchv2alpha1 *8��@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.storage.k8s.io"G/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.storage.k8s.io*$8c74d716-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez#storage.k8s.iov1beta1 *8��@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
!v1beta1.rbac.authorization.k8s.io"R/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.rbac.authorization.k8s.io*$8c74738f-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez.rbac.authorization.k8s.iov1beta1 *8��@
                                                                                             L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.policy"?/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.policy*$8c741b37-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruezpolicyv1beta1 *8̅@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.extensions"C/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.extensions*$8c736d0d-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez
extensionsv1beta1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.certificates.k8s.io"L/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.certificates.k8s.io*$8c73562a-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez(certificates.k8s.iov1beta1 *8��@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.authorization.k8s.io"M/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.authorization.k8s.io*$8c7279f7-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez)authorization.k8s.iov1beta1 *8��@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.authentication.k8s.io"N/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.authentication.k8s.io*$8c722edc-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez*authentication.k8s.iov1beta1 *8��@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�

v1beta1.apps"=/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.apps*$8c70ed79-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruezappsv1beta1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1beta1.apiextensions.k8s.io"M/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.apiextensions.k8s.io*$8c703f1e-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez)apiextensions.k8s.iov1beta1 *8��@	L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.user.openshift.io"E/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.user.openshift.io*$8c74fddb-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez user.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.template.openshift.io"I/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.template.openshift.io*$8c74e7d2-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez$template.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.storage.k8s.io"B/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.storage.k8s.io*$8c748131-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruezstorage.k8s.iov1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.security.openshift.io"I/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.security.openshift.io*$8c747a07-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez$security.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.route.openshift.io"F/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.route.openshift.io*$8c746e78-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez!route.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.quota.openshift.io"F/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.quota.openshift.io*$8c746c6b-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez!quota.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.project.openshift.io"H/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.project.openshift.io*$8c7418a4-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez#project.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.oauth.openshift.io"F/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.oauth.openshift.io*$8c741416-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez!oauth.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.networking.k8s.io"E/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.networking.k8s.io*$8c73eebe-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez!networking.k8s.iov1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.network.openshift.io"H/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.network.openshift.io*$8c73cc8b-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez#network.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.image.openshift.io"F/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.image.openshift.io*$8c736753-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez!image.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.build.openshift.io"F/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.build.openshift.io*$8c7363ea-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez!build.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.batch"9/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.batch*$8c72ed20-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruezbatchv1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.autoscaling"?/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.autoscaling*$8c73021f-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez
                                                    autoscalingv1 *8܈@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.authorization.openshift.io"N/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.authorization.openshift.io*$8c72d639-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez*authorization.openshift.iov1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.authorization.k8s.io"H/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.authorization.k8s.io*$8c722d8b-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez$authorization.k8s.iov1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.authentication.k8s.io"I/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.authentication.k8s.io*$8c7142bd-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez%authentication.k8s.iov1 *8��@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1.apps.openshift.io"E/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.apps.openshift.io*$8c7132f2-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruez apps.openshift.iov1 *8�M@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
WARN: error decoding value k8s
,
apiregistration.k8s.io/v1beta1
APIService�
�
v1."4/apis/apiregistration.k8s.io/v1beta1/apiservices/v1.*$8c7042c6-8e84-11e7-84cd-54ee753e26442�͡�Z1
)kube-aggregator.kubernetes.io/automanagedtruezv1 *8Ќ@L
J
	AvailableTru�͡�"Local*&Local APIServices are always available": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"
```

</details>

@deads2k says:
 12:47:50       deads| skuznets: I though mo had a fix for that.  Something about registering every type into a scheme

/assign @enj

**Comment by enj** [comment] 2017-08-31 19:52
Duplicate of https://github.com/openshift/origin/issues/15516

**Closed by enj** 2017-08-31 19:52 UTC
Labels: area/usability, component/internal-tools, kind/bug, priority/P2
