### ISSUE TITLE
openshift ex validate node-config fails

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9840] opened 2016-07-14 04:23 UTC
```
Running hack/test-cmd.sh:232: executing 'openshift ex validate node-config /tmp/openshift/test-cmd//openshift.local.config/node-172.18.13.130/node-config.yaml' expecting success and text 'SUCCESS'...
FAILURE after 0.612s: hack/test-cmd.sh:232: executing 'openshift ex validate node-config /tmp/openshift/test-cmd//openshift.local.config/node-172.18.13.130/node-config.yaml' expecting success and text 'SUCCESS': the output content test failed
Standard output from the command:
SUCCESS: Validation succeded for file: /tmp/openshift/test-cmd//openshift.local.config/node-172.18.13.130/node-config.yaml

Standard error from the command:
Command "node-config" is deprecated, This command is deprecated and will be removed. Use 'oadm diagnostics NodeConfigCheck --node-config=path/to/config.yaml' instead.
[ERROR] PID 16383: hack/lib/cmd.sh:230: `return "${return_code}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/cmd.sh:230: `return "${return_code}"`
[INFO] 		  2: hack/test-cmd.sh:232: os::cmd::expect_success_and_text
[INFO]   Exiting with code 1.
[INFO] Stacked plot for log subset "iops" written to /tmp/openshift/test-cmd//logs/iops.pdf
[INFO] Stacked plot for log subset "paging" written to /tmp/openshift/test-cmd//logs/paging.pdf
[INFO] Stacked plot for log subset "cpu" written to /tmp/openshift/test-cmd//logs/cpu.pdf
[INFO] Stacked plot for log subset "queue" written to /tmp/openshift/test-cmd//logs/queue.pdf
[INFO] Stacked plot for log subset "memory" written to /tmp/openshift/test-cmd//logs/memory.pdf
[INFO] Dumping etcd contents to /tmp/openshift/test-cmd//artifacts/etcd_dump.json
```

seems like we're getting the string we expected but maybe a bad return code because of the deprecation warning?  certainly doesn't seem like something that should be a flake though... @stevekuznetsov any ideas?

**Comment by bparees** [comment] 2016-07-14 04:25
actually the message implies the output content test failed which is even weirder since the output looks to contain SUCCESS.

**Comment by stevekuznetsov** [comment] 2016-07-14 13:01
I think this is a dupe of #9371

**Closed by stevekuznetsov** 2016-07-14 13:01 UTC
Labels: kind/test-flake, priority/P2
