### ISSUE TITLE
extended tests: image_ecosystem/sample_repos output mismatch

### ISSUE THREAD

**Issue by wozniakjan** [openshift/origin#19361] opened 2018-04-16 08:09 UTC
Weekend failures, suspect a broken test

```html
Expected
     <!-- large html -->
     <span class="code" id="count-value">60</span>
     <!-- rest of large html -->
to contain substring
     <span class="code" id="count-value">1</span>

/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/sample_repos.go:117
```

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/447
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/448
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/449

**Comment by coreydaley** [comment] 2018-04-16 12:58
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/449/

**Comment by bparees** [comment] 2018-04-16 13:55
this is a dupe of https://github.com/openshift/origin/issues/17649

**Closed by bparees** 2018-04-16 13:55 UTC
Labels: area/tests, kind/test-flake, sig/developer-experience
