### ISSUE TITLE
FAILURE after 1.195s: test/cmd/admin.sh:253: executing 'oc process -f test/extended/testdata/roles/policy-roles.yaml -v NAMESPACE='cmd-admin' | oc create -f -' expecting success: the command returned the wrong error code

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11616] opened 2016-10-27 14:26 UTC
```
FAILURE after 1.195s: test/cmd/admin.sh:253: executing 'oc process -f test/extended/testdata/roles/policy-roles.yaml -v NAMESPACE='cmd-admin' | oc create -f -' expecting success: the command returned the wrong error code
Standard output from the command:
role "basic-user" created
policybinding "cmd-admin:default" created

Standard error from the command:
Error from server: role "basic-user" not found
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/7791/consoleFull#165233259156c25df4e4b05b79524e5d52

**Comment by liggitt** [comment] 2016-10-27 14:29
dupe of https://github.com/openshift/origin/issues/11024

**Closed by liggitt** 2016-10-27 14:29 UTC
Labels: area/tests, component/auth, kind/test-flake, priority/P2
