### ISSUE TITLE
Git clone via SSH not working if proxy is set.

### ISSUE THREAD

**Issue by bachp** [openshift/origin#12085] opened 2016-12-01 08:55 UTC
Currently there is a check that actively refuses to do a git clone via SSH if a HTTP proxy is set.
This makes sense for repositories that need to be accesses via Proxy.
However for repositories that are accessible without proxy (the ones in no_proxy). This limitation should not apply.

##### Version
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://openshift.mynetwork:443
openshift v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Install OpenShift with ansible and setting a proxy via:
```
openshift_http_proxy=http://proxy.mynetwork:3128
openshift_https_proxy=http://proxy.mynetwork:3128
openshift_no_proxy='.mynetwork,'
```
2. Create a build with an ssh url to a server in the no proxy range: `git@server.without.proxy.mynetwork:pages.git`

##### Current Result

Git clone via SSH fails with the following message:
```
The Build "pages-21" is invalid: spec.source.git.uri: Invalid value: "git@server.without.proxy.mynetwork:pages.git": only http:// and https:// GIT protocols are allowed with HTTP or HTTPS proxy set
```

##### Expected Result

The git clone can be done via SSH as no access trough the proxy is required

##### Additional Information
As a work around I disabled `gitHTTPProxy` and `gitHTTPSProxy` in my master-config.yaml.
However this prevents me from cloning from github.com via https.

**Comment by bachp** [comment] 2016-12-01 10:26
I just noticed that there is a [`gitNoProxy`](https://docs.openshift.org/latest/install_config/build_defaults_overrides.html) variable but there seems to be no way of setting this via ansible.

I will check if setting this variable sovles my issue and if yes I will come up with a PR to add this to the ansible playbook.

**Comment by bparees** [comment] 2016-12-01 13:54
dupe of https://bugzilla.redhat.com/show_bug.cgi?id=1397475

**Closed by bparees** 2016-12-01 13:54 UTC
Labels: component/build, priority/P2
