### ISSUE TITLE
flake: StatefulSet scaling down before scale up panicked

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13106] opened 2017-02-24 18:04 UTC
https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/134/testReport/junit/(root)/Extended/_k8s_io__StatefulSet__k8s_io__Basic_StatefulSet_functionality_Scaling_down_before_scale_up_is_finished_should_wait_until_current_pod_will_be_running_and_ready_before_it_will_be_removed/

```
[91m[1m•! Panic [129.309 seconds][0m
[k8s.io] StatefulSet
[90m/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:826[0m
  [k8s.io] Basic StatefulSet functionality
  [90m/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:826[0m
    [91m[1mScaling down before scale up is finished should wait until current pod will be running and ready before it will be removed [It][0m
    [90m/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:270[0m

    [91m[1mTest Panicked[0m
    [91minterface conversion: runtime.Object is *unversioned.Status, not *api.Pod[0m
    /usr/lib/golang/src/runtime/panic.go:443

    [91mFull Stack Trace[0m
    	/usr/lib/golang/src/runtime/panic.go:443 +0x4e9
    github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e.glob.func70.2.6.1(0xc8208ce900, 0x5, 0x7f1ea22ee980, 0xc82007c900, 0xc81ff95d01, 0x0, 0x0)
    	/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:255 +0x68b
    github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/watch.Until(0x8bb2c97000, 0x7f1ea230d220, 0xc82096a870, 0xc8206b4da8, 0x1, 0x1, 0x0, 0x0, 0x0)
    	/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/watch/until.go:69 +0x335
    github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e.glob.func70.2.6()
    	/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:268 +0xed2
    github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc820958a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/data/src/github.com/openshift/origin/test/extended/util/test.go:112 +0x9c4
    github.com/openshift/origin/test/extended.TestExtended(0xc82021cfc0)
    	/data/src/github.com/openshift/origin/test/extended/extended_test.go:32 +0x36
    testing.tRunner(0xc82021cfc0, 0x586a760)
    	/usr/lib/golang/src/testing/testing.go:473 +0x98
    created by testing.RunTests
    	/usr/lib/golang/src/testing/testing.go:582 +0x892
```

**Comment by smarterclayton** [comment] 2017-02-24 18:05
Failure sure this was fixed upstream

**Comment by smarterclayton** [comment] 2017-03-06 17:07
@derekwaynecarr

**Comment by brenton** [comment] 2017-05-01 17:27
https://github.com/openshift/origin/issues/13942 is a duplicate of this.  However, it seems people are working the issue there so I'm going to close this.

**Closed by brenton** 2017-05-01 17:27 UTC
Labels: kind/test-flake, needs-upstream, priority/P1
