### ISSUE TITLE
etcd "required revision has been compacted" message in logs every second

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#11886] opened 2016-11-11 16:12 UTC
After stopping/starting my origin all-in-one development build, I'll occasionally see the logs fill up with the following messages:

```
W1111 08:02:11.309506     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:12.315995     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:13.320450     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:14.325507     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:15.330595     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:16.334827     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:17.340910     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
W1111 08:02:18.345379     690 reflector.go:330] github.com/openshift/origin/pkg/unidling/controller/controller.go:192: watch of *api.Event ended with: etcdserver: mvcc: required revision has been compacted
```

##### Version

oc v1.4.0-alpha.1+0093383-83
kubernetes v1.4.0+776c994
docker 1.12.3 docker-common-1.12.3-5.git9a594b9.fc25.x86_64
Linux limelight 4.8.6-300.fc25.x86_64

Latest commit message:

```
commit 0093383161bac0ee50a97b31c29bdd684f3fdc04
Merge: 7db04ad 8242e1e
Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>
Date:   Mon Nov 7 16:34:12 2016 -0500

    Merge pull request #11723 from xiangpengzhao/fix-validator
    
    Merged by openshift-bot
```

##### Steps To Reproduce
1. ??? (seems to happen sporadically some time after using origin for awhile)

Workaround is to delete the `openshift.local.etcd` directory, but of course you lose all your state (configured projects) which might be undesirable.

##### Current Result

* Error messages in logs every second

##### Expected Result

* No error message at all (is this even an error?)
* Some sort of exponential backoff mechanism (why are we retrying every second?)

##### Additional Information

Here's a tarball containing all my `openshift.local.*` directories, as I'm deleting the etcd directory to apply the workaround. Should hopefully be able to reproduce using this?  I'll also try rebuilding as I guess my code is a few days old.

[openshift-local.tar.gz](https://github.com/openshift/origin/files/586199/openshift-local.tar.gz)

**Comment by liggitt** [comment] 2016-11-11 16:15
Dupe of #10773 fixed in https://github.com/openshift/origin/pull/11866

**Comment by jawnsy** [comment] 2016-11-11 16:15
Thanks, Jordan. I did a search for the error message but didn't find that one.

**Closed by liggitt** 2016-11-11 16:15 UTC
