### ISSUE TITLE
`osc describe pod <pod>` doesn't show exposed ports

### ISSUE THREAD

**Issue by rhuss** [openshift/origin#2588] opened 2015-05-29 10:05 UTC
I find the exposed ports of a pod to be a very important information. Currently I only can get it via `osc get pods <pod> -o json` but would like to have an easier way.

**Comment by fabianofranz** [comment] 2015-09-28 18:24
@liggitt dupe of https://github.com/openshift/origin/issues/2949

**Closed** 2015-09-28 18:55 UTC
Labels: area/usability, component/cli, kind/enhancement, priority/P3
