### ISSUE TITLE
Origin Ansible installation failed. Unable to recognize existing docker installation

### ISSUE THREAD

**Issue by snyamars** [openshift/origin#10691] opened 2016-08-28 09:08 UTC
Trying to install origin 1.3 using ansible installation. Docker version (1.12.1, build 23cf638) is pre-installed on the AWS machine. However, ansible installation fails while trying to install docker.

##### Version
https://github.com/openshift/openshift-ansible

##### Steps To Reproduce
1. install docker
2. run ansible playbook

##### Current Result
TASK [docker : Install Docker] *************************************************
fatal: [*.compute-1.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "Failure talking to yum: Could not contact any CDS load balancers: rhui2-cds01.us-east-1.aws.ce.redhat.com, rhui2-cds02.us-east-1.aws.ce.redhat.com."}

##### Expected Result
TASK [docker: Install Docker] should be skipped as docker is pre-installed
##### Additional Information
Though the error description is related to non-availability of CDS, it seems to be trying to install docker which is already pre-installed. Not sure if this is the correct behavior.

**Comment by vanloswang** [comment] 2016-08-29 01:31
@snyamars openshift-ansible will install the specified version of docker. for example, origin 1.2 will use the version 1.10.3, and origin 1.1 will use the version 1.9.1.

**Comment by sdodson** [comment] 2016-08-29 12:48
Dupe of #8508

**Closed by sdodson** 2016-08-29 12:48 UTC
Labels: area/usability, component/install, priority/P2
