### ISSUE TITLE
template not found flake in test/cmd/templates.sh

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6453] opened 2015-12-22 01:32 UTC
flake [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8055/console):
```
FAILURE after 7.946s: hack/../test/cmd/templates.sh:56: executing 'oc delete template/template-type-precision' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: templates "template-type-precision" not found
[FAIL] !!!!! Test Failed !!!!
```

**Comment by bparees** [comment] 2016-01-05 15:26
the only way this is possible is either we are running other operations in parallel (eg something started cleaning up the namespace while this test was running), or we have an etcd dataloss bug.

**Comment by liggitt** [comment] 2016-01-05 15:43
Pretty sure this is the etcd error where the delete succeeds, but the server returns a 501 error, so the client retries the delete, which then fails.

**Comment by bparees** [comment] 2016-01-05 15:51
is there an existing issue for that we can reference?

**Comment by liggitt** [comment] 2016-01-05 16:01
Take your pick... it's the root cause for https://github.com/openshift/origin/issues/6065, and I think for https://github.com/openshift/origin/issues/6447

**Comment by deads2k** [comment] 2016-01-12 19:17
dupe of https://github.com/openshift/origin/issues/6447

**Closed by deads2k** 2016-01-12 19:17 UTC
Labels: kind/test-flake, priority/P2
