### ISSUE TITLE
Drop dockerclient in favor of Docker's engine API

### ISSUE THREAD

**Issue by miminar** [openshift/origin#15113] opened 2017-07-10 12:42 UTC
Kube upstream did this a while ago: https://github.com/kubernetes/kubernetes/pull/23800

Pros:
1. reduce dependencies
2. reduce dependencies
3. reduce dependencies
4. [upstream library](https://github.com/moby/moby/tree/master/client) is preferred over [3rd party library](https://github.com/fsouza/go-dockerclient)

Note that https://github.com/docker/engine-api has been deprecated already.

@mfojtik @dmage @legionus FYI

**Comment by bparees** [comment] 2017-07-10 14:24
dupe of https://github.com/openshift/origin/issues/12212

**Closed by bparees** 2017-07-10 14:24 UTC
Labels: component/build, component/restapi, kind/enhancement, priority/P2
