### ISSUE TITLE
Git not found in $PATH

### ISSUE THREAD

**Issue by michelvocks** [openshift/origin#4966] opened 2015-10-06 13:48 UTC
[root@10 ~]# oc start-build nodejs-example --follow
nodejs-example-12
I1006 13:48:10.306637       1 sti.go:74] The value of ALLOWED_UIDS is [1-]
I1006 13:48:10.315116       1 docker.go:211] Image openshift/nodejs-010-centos7@sha256:336f278671e4c9f5d47ea1e4c82301a2f593bc010bcdbfe3ba7389e48a6240b0 available locally
I1006 13:48:10.315176       1 sti.go:96] Creating a new S2I builder with build config: "Builder Name:\t\tNode.js 0.10\nBuilder Image:\t\topenshift/nodejs-010-centos7@sha256:336f278671e4c9f5d47ea1e4c82301a2f593bc010bcdbfe3ba7389e48a6240b0\nBuilder Image Version:\tfadbc01\nBuilder Base Version:\t71a650e\nSource:\t\t\thttps://github.com/openshift/nodejs-ex.git\nOutput Image Tag:\t172.30.155.123:5000/test-project/nodejs-example:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=nodejs-example-12,OPENSHIFT_BUILD_NAMESPACE=test-project,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/nodejs-ex.git\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I1006 13:48:10.317416       1 docker.go:211] Image openshift/nodejs-010-centos7@sha256:336f278671e4c9f5d47ea1e4c82301a2f593bc010bcdbfe3ba7389e48a6240b0 available locally
I1006 13:48:10.321358       1 sti.go:124] Preparing to build 172.30.155.123:5000/test-project/nodejs-example:latest
I1006 13:48:10.321652       1 clone.go:30] Cloning sources and all GIT submodules into "/tmp/sti907983649/upload/src"
I1006 13:48:10.322389       1 clone.go:35] Git clone failed: exec: "git": executable file not found in $PATH
I1006 13:48:10.322407       1 cleanup.go:23] Removing temporary directory /tmp/sti907983649
I1006 13:48:10.322415       1 fs.go:99] Removing directory '/tmp/sti907983649'
F1006 13:48:10.322633       1 builder.go:54] Build error: exec: "git": executable file not found in $PATH

[root@10 ~]# which git
/usr/bin/git

Any idea? Thanks in advance

**Comment by bparees** [comment] 2015-10-06 13:56
can you share your buildconfig definition?

**Comment by mfojtik** [comment] 2015-10-06 13:57
@michelvocks is this the official nodejs image from dockerhub or it is modified/customized version?

**Comment by michelvocks** [comment] 2015-10-06 14:10
@bparees @mfojtik 
Is this the correct output? Sorry im kinda new to openshift

[root@10 ~]# oc get -o yaml buildConfigs
apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    creationTimestamp: 2015-10-06T13:00:09Z
    labels:
      template: nodejs-example
    name: nodejs-example
    namespace: test-project
    resourceVersion: "10648"
    selfLink: /oapi/v1/namespaces/test-project/buildconfigs/nodejs-example
    uid: 2c3b97f0-6c2a-11e5-8f49-00505683a13c
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-example:latest
    resources: {}
    source:
      git:
        uri: https://github.com/openshift/nodejs-ex.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:0.10
          namespace: openshift
      type: Source
    triggers:
    - imageChange:
        lastTriggeredImageID: openshift/nodejs-010-centos7@sha256:336f278671e4c9f5d47ea1e4c82301a2f593bc010bcdbfe3ba7389e48a6240b0
      type: ImageChange
    - github:
        secret: 6GVoeKQ6GDPvVawDrjER4neCpD46aHicO5T5Uxio
      type: GitHub
  status:
    lastVersion: 12
kind: List
metadata: {}

**Comment by michelvocks** [comment] 2015-10-07 08:16
@mfojtik It's the official nodejs image. I just created a new project and added the nodejs-example via the web console.

**Comment by mfojtik** [comment] 2015-10-07 10:28
@bparees can't reproduce this (went through say way using web UI and I ended up with the same buildConfig). The build just runs fine. @michelvocks why you using `start-build` command? The build should start automatically when you create it from the UI.

**Comment by michelvocks** [comment] 2015-10-07 10:50
@mfojtik Right. I just prefered the command line because with the "--follow" command it will automatically print out the logs. When you look at the Web UI you just see that the build failed. 

You guys have any hint or idea what I could try to fix this? Or where I could look to get more details of this issue?

**Comment by michelvocks** [comment] 2015-10-07 11:01
The strange thing is sometimes when I try to build I get these error messages:
E1007 10:54:50.436800       1 git.go:102] Clone failed: fatal: unable to access 'https://github.com/openshift/nodejs-ex/': Could not resolve host: github.com; Unknown error

I found this issue here: https://github.com/openshift/origin/blob/master/docs/debugging-openshift.md
The solution is to restart docker. When I do that and restart the build I get the message again "Git not found".

**Comment by mfojtik** [comment] 2015-10-07 11:42
@michelvocks how do you run openshift?

**Comment by mfojtik** [comment] 2015-10-07 11:43
@michelvocks can you try to re-pull manually the nodejs image on the host you running the build? (docker pull) just to make sure the image itself is not corrupted.

**Comment by bparees** [comment] 2015-10-07 11:45
@mfojtik as you noted it's really openshift/origin-sti-builder that should be re-pulled

**Comment by mfojtik** [comment] 2015-10-07 11:45
@bparees right, was just typing this :)

**Comment by michelvocks** [comment] 2015-10-07 12:03
https://gist.github.com/michelvocks/cf5d2e95f2a099ccdfca

**Comment by mfojtik** [comment] 2015-10-08 14:26
still no luck reproducing this :/

**Comment by mfojtik** [comment] 2015-10-22 11:17
@bparees @michelvocks is this still an issue? I tried to reproduce this on latest master today and still no luck :/

**Comment by bparees** [comment] 2015-11-11 15:50
closing due to age and inability to reproduce.

**Closed by bparees** 2015-11-11 15:50 UTC
Labels: component/build, priority/P3
