### ISSUE TITLE
haproxy restarting

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#9330] opened 2016-06-14 18:17 UTC
Sometimes client->server connection is dropped while data is being exchanged...
Sometimes client get 503 errors.

Investigating the logs, I see those on proxy pod logs:
```
I0614 13:49:21.173937       1 router.go:320] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
I0614 13:59:22.175506       1 router.go:320] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
- HAProxy port 1936 health check ok : 0 retry attempt(s).
.... lots of similar messages
```

This looks similar to #8825. But I don't see the "concurrent map read and map write" message reported there.

##### Version
openshift v3.2.1.1-1-g33fa4ea
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

**Comment by knobunc** [comment] 2016-06-15 12:50
I believe this is caused by excessive router reloads.  This is fixed by:
  https://bugzilla.redhat.com/show_bug.cgi?id=1320233 (issue https://github.com/openshift/origin/issues/7409)

There is an underlying kernel bug that causes haproxy reloads to occasionally drop packets if the incoming connection is placed in the socket for the old process, but that process exits before handling it:
  https://bugzilla.redhat.com/show_bug.cgi?id=1203000

You can work around that bug by making the router install iptables rules:
  https://bugzilla.redhat.com/show_bug.cgi?id=1269488

But, if you have the patch to make the reloads far fewer, the chance of hitting the reload and losing a connection is much, much, smaller.

**Closed by knobunc** 2016-06-15 12:50 UTC
Labels: component/routing, priority/P1

**Comment by jwendell** [comment] 2016-06-15 20:27
Thanks for you reply.

I tried the workaround but it didn't work...

Do you happen to know when the fix merged in #8287 will get into openshift the product? I'm using openshift v3.2.1.1-1-g33fa4ea. Tomorrow we are going to upgrade to 3.2.1.2.

**Comment by donovanmuller** [comment] 2016-08-29 09:23
@jwendell Any luck with this? I get this very frequently with the router. Basically impossible to do any sustained HTTP load tests with this issue.

**Comment by jwendell** [comment] 2016-08-29 12:14
@donovanmuller I did a workaround on my tests for this issue...

**Comment by donovanmuller** [comment] 2016-08-29 12:21
@jwendell care to share? 😄

**Comment by jwendell** [comment] 2016-08-29 12:28
@donovanmuller , sure, it's open source: https://github.com/jboss-openshift/ce-arq/commit/f679ba0c929b9ebf09e9e75854790bd7d002c089

I'm not sure if that's going to work for you. I'm just trying again if I get something different than 200 OK as a response. Really a workaround :)

**Comment by donovanmuller** [comment] 2016-08-29 12:31
@jwendell ah ok, I see now 😬

**Comment by knobunc** [comment] 2016-08-29 14:51
@jwendell @donovanmuller : I updated the fix in https://bugzilla.redhat.com/show_bug.cgi?id=1269488#c29  The 3.2 router will work, but the instructions were incorrect.
