### ISSUE TITLE
Test flake: etcd failed to start in test_pull_requests_origin_web_console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#10308] opened 2016-08-09 18:40 UTC
Jenkins job:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/227/

openshift log:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/227/s3/download/openshift.log

```
Aug 09 14:10:16 ip-172-18-3-5.ec2.internal openshift[3618]: F0809 14:10:16.227835    3618 auth.go:158] client: etcd cluster is unavailable or misconfigured
```

/cc @stevekuznetsov @jwforres

**Comment by stevekuznetsov** [comment] 2016-08-09 18:41
The etcd stuff may be a red herring for the `getsockopt` issues:
```
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 is starting a new election at term 1
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 became candidate at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 received vote from 94d5f8f701dc1d12 at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 became leader at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: raft.node: 94d5f8f701dc1d12 elected leader 94d5f8f701dc1d12 at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: published {Name:openshift.local ClientURLs:[https://172.18.3.5:4001]} to cluster a31f1ef708b864ee
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: setting up the initial cluster version to 2.3
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: set the initial cluster version to 2.3
```

As an aside it seems weird to me to start an external clustered etcd with one member:
```
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 is starting a new election at term 1
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 became candidate at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 received vote from 94d5f8f701dc1d12 at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: 94d5f8f701dc1d12 became leader at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: raft.node: 94d5f8f701dc1d12 elected leader 94d5f8f701dc1d12 at term 2
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: published {Name:openshift.local ClientURLs:[https://172.18.3.5:4001]} to cluster a31f1ef708b864ee
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: setting up the initial cluster version to 2.3
Aug 09 14:10:07 ip-172-18-3-5.ec2.internal openshift[3618]: set the initial cluster version to 2.3
```

**Comment by ncdc** [comment] 2016-08-25 16:44
Looks like this is a dupe of #7243

**Closed by ncdc** 2016-08-25 16:44 UTC
Labels: dependency/kubernetes, kind/test-flake, priority/P2
