### ISSUE TITLE
Travis asset builds are failing due to a bindata diff on favicon

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3320] opened 2015-06-18 20:10 UTC
```
Validating checked in bindata.go is up to date...
--- _output/test/assets/bindata.go	2015-06-17 23:16:34.426383015 +0000
+++ pkg/assets/bindata.go	2015-06-17 22:42:11.000000000 +0000
@@ -12481,7 +12481,7 @@
 	return _images_console_sprite_png, nil
 }
 
-var _images_favicon_png = []byte("\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \b\x03\x00\x00\x00D\xa4\x8a\xc6\x00\x00\x01}PLTE\xff\xff\xff\xff\x00\x00\xff\x00\x00\xff\x00U\xbf@@\xcc33\xdb$$\xdf  \xe3\x1c9\xd1\x17.\xd5++\xdd\"3\xd5\x1c+\xd7\x1b6\xd9&3\xdb$1\xdc#.\xdd\"3\xde!1\xdb$,\xdd\"0\xd8!.\xd9 -\xda\x1f2\xdb\x1e1\xdc#.\xdd\"-\xde!,\xd9!1\xdb\x1f/\xdd\"1\xdb .\xdc#0\xdd\"/\xd9!.\xda!-\xdb 0\xdc#.\xda\"1\xdb!/\xdd\"0\xda\"0\xda\"/\xdc\x1f/\xdb!/\xdb\"0\xdc!.\xda 0\xda\"/\xdb!.\xdb!.\xdc!0\xda /\xdb\".\xdc!/\xda .\xdb\"/\xdb\"/\xda!/\xdb\"/\xdb 0\xdb\"/\xdc\"/\xdb!/\xda!/\xdb!/\xdb!.\xdc\"/\xdc\"/\xda!/\xdb!0\xdb /\xdc\"/\xdb!/\xdc 0\xdb!0\xdb!/\xda\"/\xdb\"/\xdb!/\xdb!/\xdc!/\xda .\xdb\"0\xdb!/\xdb!/\xdc!.\xdb /\xdb\"/\xdb!/\xdc!/\xda!/\xdb!/\xdb /\xdb!.\xdb!/\xdb\"/
Bower versions...
assets#0.0.0 /home/travis/gopath/src/github.com/openshift/origin/assets
```

**Comment by liggitt** [comment] 2015-06-22 12:33
Dupe of #3317?

**Comment by smarterclayton** [comment] 2015-06-22 12:45
It happens even when test builds succeed.

**Comment by liggitt** [comment] 2015-06-22 13:03
ah, ok... added https://github.com/openshift/origin/pull/3373 to get more logging to see what it thinks is different

**Comment by liggitt** [comment] 2015-06-23 14:06
"Fixed" in https://github.com/openshift/origin/pull/3388 by removing imagemin step... we already squash our images pre-checkin, so it wasn't getting us much

**Closed by liggitt** 2015-06-23 14:06 UTC
Labels: area/tests, component/web
