### ISSUE TITLE
[oc cluster up 3.11] Not able to redirect https://<pubilc_hostname>:8443 to https://<pubilc_hostname>:8443/console

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#21153] opened 2018-10-03 06:35 UTC
With 3.11 after running `oc cluster up` doesn't redirect the web console properly.

##### Version
```
$ ./oc version                                   
oc v3.11.0-alpha.0+f7602dd-1284
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.239:8443
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
```
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ ./minishift start --no-provision
$ ./minishift ip
192.168.42.239

$ docker image pull openshift/origin-control-plane:v3.11.0
$ docker create --name tmp docker.io/openshift/origin-control-plane:v3.11.0
$ docker cp tmp:/usr/bin/oc .
$ ./oc cluster up --public-hostname 192.168.42.239
[...]
The server is accessible via web console at:
    https://192.168.42.239:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```

##### Current Result
Try to put `https://192.168.42.239:8443` in the web browser and it redirected to `https://127.0.0.1:8443/console/` instead `https://192.168.42.239:8443/console/`

##### Expected Result
When accessing the `https://192.168.42.239:8443` should be redirected to `https://192.168.42.239:8443/console/` not to `https://127.0.0.1:8443/console/`

**Comment by tiraboschi** [comment] 2018-10-03 09:05
I think it's a duplicate of https://github.com/openshift/origin/issues/20726

**Comment by jwforres** [comment] 2018-10-11 14:02
@openshift/sig-master @openshift/sig-user-interface

**Comment by gbraad** [comment] 2018-10-12 06:06
https://github.com/openshift/origin-web-console/issues/3072

This causes an issue for Minishift or deployment on VM's and remote machines

**Comment by gbraad** [comment] 2018-10-12 07:46
@praveenkumar did you already propose a PR?

**Comment by nstielau** [comment] 2018-10-17 22:30
@praveenkumar does #21234 resolve this?

**Comment by praveenkumar** [comment] 2018-10-18 01:03
@nstielau we are not redirecting but using full URI for console.

**Closed** 2019-03-17 09:26 UTC
Labels: lifecycle/rotten, sig/master, sig/user-interface
