### ISSUE TITLE
extended flake: should create an image from "/data/src/github.com/openshift/origin/test/extended/testdata/test-docker-no-outputname.json" docker template without an output image reference defined

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9766] opened 2016-07-11 10:38 UTC
```
• Failure [149.322 seconds]
[builds][Conformance] build without output image
/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:72
  building from templates
  /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:71
    should create an image from "/data/src/github.com/openshift/origin/test/extended/testdata/test-docker-no-outputname.json" docker template without an output image reference defined [It]
    /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:46

    Expected error:
        <*errors.errorString | 0xc8207dae30>: {
            s: "The build \"test-docker-1\" status is \"Failed\"",
        }
        The build "test-docker-1" status is "Failed"
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:38
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3199/consoleFull

**Comment by bparees** [comment] 2016-07-11 12:45
`F0711 09:56:36.450482       1 helpers.go:108] error: build error: devicemapper: Error running deviceResume dm_task_run failed`

dupe of:
https://github.com/openshift/origin/issues/9548

**Closed by bparees** 2016-07-11 12:45 UTC
Labels: area/tests, component/build, kind/test-flake, priority/P2
