### ISSUE TITLE
flake: Extended.[k8s.io] Downward API volume should set mode on item file [Conformance]

### ISSUE THREAD

**Issue by dmage** [openshift/origin#13462] opened 2017-03-20 15:15 UTC
Seen there: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/322/testReport/junit/(root)/Extended/_k8s_io__Downward_API_volume_should_set_mode_on_item_file__Conformance_/

```
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:68
Mar 20 10:09:34.917: Failed to delete pod "downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4": client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member https://ip-172-18-8-254.ec2.internal:2379 has no leader

/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/pods.go:118
```

```
[BeforeEach] [Top Level]
  /go/src/github.com/openshift/origin/test/extended/util/test.go:47
[BeforeEach] [k8s.io] Downward API volume
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:141
STEP: Creating a kubernetes client
Mar 20 10:09:16.545: INFO: >>> kubeConfig: /etc/origin/master/admin.kubeconfig

STEP: Building a namespace api object
Mar 20 10:09:16.652: INFO: About to run a Kube e2e test, ensuring namespace is privileged
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [k8s.io] Downward API volume
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:39
[It] should set mode on item file [Conformance]
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:68
STEP: Creating a pod to test downward API volume plugin
Mar 20 10:09:16.888: INFO: Waiting up to 5m0s for pod downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 status to be success or failure
Mar 20 10:09:16.890: INFO: Waiting for pod downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 in namespace 'e2e-tests-downward-api-4jcns' status to be 'success or failure'(found phase: "Pending", readiness: false) (2.002164ms elapsed)
Mar 20 10:09:18.893: INFO: Waiting for pod downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 in namespace 'e2e-tests-downward-api-4jcns' status to be 'success or failure'(found phase: "Pending", readiness: false) (2.005001311s elapsed)
Mar 20 10:09:20.895: INFO: Waiting for pod downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 in namespace 'e2e-tests-downward-api-4jcns' status to be 'success or failure'(found phase: "Pending", readiness: false) (4.00738866s elapsed)
Mar 20 10:09:22.899: INFO: Waiting for pod downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 in namespace 'e2e-tests-downward-api-4jcns' status to be 'success or failure'(found phase: "Pending", readiness: false) (6.010976188s elapsed)
STEP: Saw pod success
Mar 20 10:09:24.903: INFO: Trying to get logs from node ip-172-18-8-254.ec2.internal pod downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 container client-container: <nil>
STEP: delete the pod
Mar 20 10:09:34.917: INFO: Failed to delete pod "downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4": client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member https://ip-172-18-8-254.ec2.internal:2379 has no leader

[AfterEach] [k8s.io] Downward API volume
  /go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:142
STEP: Collecting events from namespace "e2e-tests-downward-api-4jcns".
STEP: Found 4 events.
Mar 20 10:09:34.921: INFO: At 2017-03-20 10:09:16 -0400 EDT - event for downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4: {default-scheduler } Scheduled: Successfully assigned downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 to ip-172-18-8-254.ec2.internal
Mar 20 10:09:34.921: INFO: At 2017-03-20 10:09:19 -0400 EDT - event for downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4: {kubelet ip-172-18-8-254.ec2.internal} Pulled: Container image "gcr.io/google_containers/mounttest:0.7" already present on machine
Mar 20 10:09:34.921: INFO: At 2017-03-20 10:09:20 -0400 EDT - event for downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4: {kubelet ip-172-18-8-254.ec2.internal} Created: Created container with docker id c671ae22c5fd; Security:[seccomp=unconfined]
Mar 20 10:09:34.921: INFO: At 2017-03-20 10:09:20 -0400 EDT - event for downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4: {kubelet ip-172-18-8-254.ec2.internal} Started: Started container with docker id c671ae22c5fd
Mar 20 10:09:34.927: INFO: POD                                                      NODE                          PHASE      GRACE  CONDITIONS
Mar 20 10:09:34.927: INFO: docker-registry-1-r02nq                                  ip-172-18-8-254.ec2.internal  Running           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:07:18 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:07:28 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:07:18 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: registry-console-1-2s613                                 ip-172-18-8-254.ec2.internal  Running           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:07:23 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:07:43 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:07:23 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: router-1-5452f                                           ip-172-18-8-254.ec2.internal  Running           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:06:35 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:06:55 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:06:35 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4  ip-172-18-8-254.ec2.internal  Succeeded         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:16 -0400 EDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:16 -0400 EDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:16 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: e2e-test-nginx-job-5b3b8                                 ip-172-18-8-254.ec2.internal  Pending    30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:19 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:19 -0400 EDT ContainersNotReady containers with unready status: [e2e-test-nginx-job]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:18 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: netserver-0                                              ip-172-18-8-254.ec2.internal  Running           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:14 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:14 -0400 EDT ContainersNotReady containers with unready status: [webserver]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:14 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: security-context-d1e61897-0d76-11e7-8b54-0e0930aeeeb4    ip-172-18-8-254.ec2.internal  Pending           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:23 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:23 -0400 EDT ContainersNotReady containers with unready status: [test-container]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-20 10:09:23 -0400 EDT  }]
Mar 20 10:09:34.928: INFO: 
Mar 20 10:09:34.930: INFO: 
Logging node info for node ip-172-18-8-254.ec2.internal
Mar 20 10:09:34.932: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
Mar 20 10:09:34.932: INFO: 
Logging kubelet events for node ip-172-18-8-254.ec2.internal
Mar 20 10:09:34.934: INFO: 
Logging pods the kubelet thinks is on node ip-172-18-8-254.ec2.internal
Mar 20 10:09:34.940: INFO: security-context-d1e61897-0d76-11e7-8b54-0e0930aeeeb4 started at 2017-03-20 10:09:23 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container test-container ready: false, restart count 0
Mar 20 10:09:34.940: INFO: netserver-0 started at 2017-03-20 10:09:14 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container webserver ready: false, restart count 0
Mar 20 10:09:34.940: INFO: router-1-5452f started at 2017-03-20 10:06:35 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container router ready: true, restart count 0
Mar 20 10:09:34.940: INFO: downwardapi-volume-cdd6b887-0d76-11e7-8d61-0e0930aeeeb4 started at 2017-03-20 10:09:16 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container client-container ready: false, restart count 0
Mar 20 10:09:34.940: INFO: e2e-test-nginx-job-5b3b8 started at 2017-03-20 10:09:19 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container e2e-test-nginx-job ready: false, restart count 0
Mar 20 10:09:34.940: INFO: registry-console-1-2s613 started at 2017-03-20 10:07:23 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container registry-console ready: true, restart count 0
Mar 20 10:09:34.940: INFO: docker-registry-1-r02nq started at 2017-03-20 10:07:18 -0400 EDT (0+1 container statuses recorded)
Mar 20 10:09:34.940: INFO: 	Container registry ready: true, restart count 0
Mar 20 10:09:35.088: INFO: 
Latency metrics for node ip-172-18-8-254.ec2.internal
Mar 20 10:09:35.088: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:33.363742s}
Mar 20 10:09:35.088: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:21.60847s}
Mar 20 10:09:35.088: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:21.200592s}
STEP: Dumping a list of prepulled images on each node
Mar 20 10:09:35.090: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "e2e-tests-downward-api-4jcns" for this suite.
Mar 20 10:09:45.284: INFO: namespace: e2e-tests-downward-api-4jcns, resource: bindings, ignored listing per whitelist
```

**Comment by pweil-** [comment] 2017-03-21 17:03
"has no leader" dupe of https://github.com/openshift/origin/issues/13067

**Closed by pweil-** 2017-03-21 17:03 UTC
Labels: kind/test-flake
