### ISSUE TITLE
Multiple deployment pods created on restart

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1649] opened 2015-04-08 18:51 UTC
On restarting OpenShift, a whole bunch of new deploy pods were created and not cleaned up:

```
$ osc get pods
POD                             IP                  CONTAINER(S)        IMAGE(S)                                  HOST                           LABELS                                                                                                                  STATUS              CREATED
deploy-database-18pgcs          172.17.0.17         deployment          openshift/origin-deployer:v0.4.3          openshiftdev.local/127.0.0.1   <none>                                                                                                                  Pending             2 hours
deploy-docker-registry-1yow0v                       deployment          openshift/origin-deployer:latest          openshiftdev.local/127.0.0.1   <none>                                                                                                                  Succeeded           19 seconds
deploy-docker-registry-28qkou                       deployment          openshift/origin-deployer:latest          openshiftdev.local/127.0.0.1   <none>                                                                                                                  Succeeded           17 seconds
deploy-docker-registry-2fcm33                       deployment          openshift/origin-deployer:latest          openshiftdev.local/127.0.0.1   <none>                                                                                                                  Succeeded           17 seconds
deploy-docker-registry-2gk2mm                       deployment          openshift/origin-deployer:latest          openshiftdev.local/127.0.0.1   <none>                                                                                                                  Succeeded           18 seconds
docker-registry-2-bdpjz         172.17.0.32         registry            openshift/origin-docker-registry:latest   openshiftdev.local/127.0.0.1   deployment=docker-registry-2,deploymentconfig=docker-registry,docker-registry=default                                   Running             10 seconds
ruby-sample-build-3                                 sti-build           openshift/origin-sti-builder:latest       openshiftdev.local/127.0.0.1   build=ruby-sample-build-3,buildconfig=ruby-sample-build,name=ruby-sample-build,template=application-template-stibuild   Failed              6 minutes
ruby-sample-build-4                                 sti-build           openshift/origin-sti-builder:latest       openshiftdev.local/127.0.0.1   build=ruby-sample-build-4,buildconfig=ruby-sample-build,name=ruby-sample-build,template=application-template-stibuild   Failed              4 minutes
[vagrant@openshiftdev origin]$ osc get rc
CONTROLLER          CONTAINER(S)               IMAGE(S)                                  SELECTOR                                                                                REPLICAS
database-1          ruby-helloworld-database   openshift/mysql-55-centos7                deployment=database-1,deploymentconfig=database,name=database                           0
docker-registry-1   registry                   openshift/origin-docker-registry:v0.4.3   deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default   0
docker-registry-2   registry                   openshift/origin-docker-registry:latest   deployment=docker-registry-2,deploymentconfig=docker-registry,docker-registry=default   1
[vagrant@openshiftdev origin]$ 
```

It looks like multiple deployments are being triggered (maybe due to the history?)

**Comment by ironcladlou** [comment] 2015-04-08 19:10
@smarterclayton Can you give me some more detail for reproducing this? What I've tried so far is creating a simple deployment and bouncing the server, which seems to be working fine.

**Comment by smarterclayton** [comment] 2015-04-08 19:14
I had two deployments of the docker registry, one that failed (because i was using --images for 0.4.3 which doesn't exist yet).  I then deleted my dc and service and recreated (without deleting the old dc).  I then restarted the server.  The new dc started a deployment-2 (because 1 already existed) but i bet the current version was 0 (not 2).  So that's a place to start looking.

----- Original Message -----

**Comment by ironcladlou** [comment] 2015-04-08 19:59
This bug should serve as a use case to drive the design of #1657.

**Comment by smarterclayton** [comment] 2015-05-15 18:13
Core thing I want to see solved is that we don't create more than one deployment pod per deployment

**Comment by abhgupta** [comment] 2015-05-28 21:35
Fixed with https://github.com/openshift/origin/pull/2357

The deployer pod name is now deterministic and only a single deployer pod can be created for a deployment.

**Closed** 2015-05-28 21:35 UTC
Labels: component/deployments, kind/bug, priority/P1
