### ISSUE TITLE
We should sort builds based on the build number

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#8643] opened 2016-04-27 10:42 UTC
When having 10+ builds, the `oc get builds` will produce this:

``` console
NAME                  TYPE      FROM          STATUS    STARTED          DURATION
ruby-hello-world-1    Source    Git@e79d887   Running   31 seconds ago   31s
ruby-hello-world-10   Source    Git@e79d887   Running   6 seconds ago    6s
ruby-hello-world-11   Source    Git           Pending
ruby-hello-world-2    Source    Git@e79d887   Running   27 seconds ago   27s
ruby-hello-world-3    Source    Git@e79d887   Running   25 seconds ago   25s
ruby-hello-world-4    Source    Git@e79d887   Running   25 seconds ago   25s
ruby-hello-world-5    Source    Git@e79d887   Running   24 seconds ago   24s
ruby-hello-world-6    Source    Git@e79d887   Running   18 seconds ago   18s
ruby-hello-world-7    Source    Git@e79d887   Running   15 seconds ago   15s
ruby-hello-world-8    Source    Git@e79d887   Running   13 seconds ago   13s
ruby-hello-world-9    Source    Git@e79d887   Running   10 seconds ago   10s
```

This looks bad especially now when we will default to `Serial` run policy, that will execute the builds in order. 
The only drawback I can see here is that you can have builds with different names (most likely you will have 1 BC per project).

**Comment by mfojtik** [comment] 2016-04-27 10:43
@fabianofranz @kargakis FYI

**Comment by kargakis** [comment] 2016-04-27 11:04
Builds with different names should be separated. For example, I would expect something like 
```
ruby-hello-world-1    Source    Git@e79d887   Running   31 seconds ago   31s
ruby-hello-world-2    Source    Git@e79d887   Running   27 seconds ago   27s
ruby-hello-world-3    Source    Git@e79d887   Running   25 seconds ago   25s
ruby-hello-world-4    Source    Git@e79d887   Running   25 seconds ago   25s
other-1
other-2
```
Either that or we should sort based on timestamps. Do we guarantee that builds with higher versions are always newer?

**Comment by mfojtik** [comment] 2016-04-27 11:07
@kargakis yes we do AFAIK.

**Comment by mfojtik** [comment] 2016-05-03 13:00
@bparees @fabianofranz I tried to fix this (created custom sort interface that compares build numbers and build names), but I found interesting bug/feature. It seems like the new sorter sorts builds in `oc describe bc/foo` BUT the `oc get builds` completely ignores the `printBuildList` function.
I think there might be a bug in how `kubectl` handles the printers and it use some generic List printer and not the printer we provide. This might apply to any other List resources we have.

@fabianofranz @smarterclayton is this a known issue or it is like that by design?

**Comment by smarterclayton** [comment] 2016-05-03 16:56
Hrm, seems like a bug.  oc get builds should be passing a BuildList to the
printer.

**Comment by fabianofranz** [comment] 2016-05-06 20:11
@mfojtik Likely a bug. I remember fixing a similar issue (in pods if I'm not wrong) where for whatever reason instead of calling `printPodList` we were calling `printPod` multiple times, one for each entry in the list. But that was directly related to the given resource (pod), not generally in printers. Might be something similar.

**Comment by jupierce** [comment] 2016-07-11 20:39
Caused by a call to Flatten in kubectl/cmd/get.go 
https://github.com/openshift/origin/blame/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go#L210
Instead of processing the BuildList as a whole, the printer just iterates over a flat array of builds.

Looks like it has been around for since Sept'15: https://github.com/kubernetes/kubernetes/commit/1f35cf2e5b5e0e97a3a7518008fcd0dc6941b5f9#diff-2de0663ac156325cb3a1ee2f1937b4f1R223

Thoughts?

**Comment by jupierce** [comment] 2016-07-11 21:12
To be clear, commenting out Flatten makes the builds print in a controllable order (currently by creation time). However, it seems certain that removing Flatten will cause a regression somewhere since the change was introduced intentionally in k8s. 
My initial reaction was to add a method to the printing interface to ask the concrete printer whether it could handle a given list object prior to flattening it into an array. It looks like a function exists to do just that: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/resource_printer.go#L390

But "oc get" does not use it.

**Comment by smarterclayton** [comment] 2016-07-11 21:34
Oh wow that's a terrible method.

Kubectl printing is a bit of a mess right now.  We may want to do
sorting more effectively upstream (there are issues open) and we can
probably handle builds as a special case of that.

**Comment by bparees** [comment] 2016-07-12 14:52
Can we just close this issue in deference to an upstream kube issue that oc/kubectl get should return resources sorted by creation time by default which should be sufficient to address this?

or is that not a default behavior k8s would be willing to adopt?

**Comment by smarterclayton** [comment] 2016-07-19 00:25
Kubectl needs to be fixed first before we can fix this here.

**Comment by bparees** [comment] 2016-07-19 03:19
Is there an upstream k8s issue we can block this issue on?

**Comment by jupierce** [comment] 2016-11-30 21:48
@smarterclayton Anything you can point me to which you think will supersede this issue? Alternate approaches which might be considered?

**Comment by bparees** [comment] 2017-03-22 13:57
@smarterclayton bump.  Are there any upstream kube issues to address sorting, or allow us to address it?

**Comment by smarterclayton** [comment] 2017-03-22 16:28
We have no plan to support server side sorting because etcd doesn't allow
it, and we aren't going to do it in the near term on the API server, so the
best option is going to be something specific to builds.  Not sure it
scales well though, so again, not sure I see this going forward soon.

**Comment by bparees** [comment] 2017-03-22 17:00
@smarterclayton earlier you said:

> Kubectl printing is a bit of a mess right now. We may want to do sorting more effectively upstream (there are issues open) and we can probably handle builds as a special case of that.

so what is the story w/ the issues you reference?

**Comment by stevekuznetsov** [comment] 2017-04-08 17:23
Doesn't look like a tooling problem

**Comment by bparees** [comment] 2017-04-08 19:49
from @smarterclayton previously:

> Kubectl printing is a bit of a mess right now.  We may want to do
sorting more effectively upstream (there are issues open) and we can
probably handle builds as a special case of that.

> Kubectl needs to be fixed first before we can fix this here.

from @smarterclayton recently:

> We have no plan to support server side sorting because etcd doesn't allow
it, and we aren't going to do it in the near term on the API server, so the
best option is going to be something specific to builds.  Not sure it
scales well though, so again, not sure I see this going forward soon.

I don't see us doing something here that doesn't also cover at least sorting deployments.  Marking this a p3.

**Comment by bparees** [comment] 2017-04-10 00:48
trello'd https://trello.com/c/o2tpjZu7

**Closed by bparees** 2017-04-10 00:48 UTC
Labels: component/cli, kind/enhancement, priority/P3
