### ISSUE TITLE
Update deploymentconfigs with ICTs if possible as soon as they are created

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#9018] opened 2016-05-25 10:00 UTC
Deployments from ImageStreams do not work and deploy from image " " instead of ImageStream. This is probably a follow up on #8937 which should be fixed now.

##### Version
```
$ oc version
oc v1.3.0-alpha.0-676-ge65adfa
kubernetes v1.3.0-alpha.1-331-g0522e63
```

##### Steps To Reproduce
1. $ oc cluster up
2. $ oc login -u system:admin
3. $ oc create -n openshift -f https://raw.githubusercontent.com/tnozicka/adb-utils/add-os-jenkins-template/services/openshift/templates/jenkins-ephemeral-next-template.json
4. $ echo "developer" | oc login -u developer
5. $ oc new-project pipelineproject
6. Use web UI to instantiate this template in namespace pipelinepriject https://<your-ip>:8443/console/project/pipelineproject/create/fromtemplate?name=jenkins-ephemeral-next&namespace=openshift

##### Current Result
First deployment does not start automatically. After starting it manually it tries to deploy image " " which ends up with same errors as #8937.
```
Failed to pull image " ": API error (500): repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
Back-off pulling image " "
(45 times in the last 11 minutes)
```

##### Expected Result
Deploy from ImageStream, not image " ".

**Comment by kargakis** [comment] 2016-05-25 10:57
The deployment config is waiting for the image to be resolved in order to start (correct). Kicking it manually before the image is resolved is wrong. I created your template but couldn't see where *jenkins-centos7:dev* should come from. There is no image stream precreated somewhere, no build running, or should be the image be imported? @gabemontero @bparees to weigh in

**Comment by kargakis** [comment] 2016-05-25 11:09
FWIW, the jenkins example in our repo combined with examples/image-streams works fine (apart from the fact to if the jenkins image stream is precreated then it will take until the next resync interval for the image to be resolved in the dc template.

**Comment by tnozicka** [comment] 2016-05-25 11:35
@kargakis sorry, this was me having a bad day. I did forget to import ImageStream _jenkins-centos7:dev_ which I had when trying this on ADB before.
3.0. `oc create -n openshift -f https://raw.githubusercontent.com/tnozicka/adb-utils/add-os-jenkins-template/services/openshift/templates/image-streams-centos7.json`

But on the other hand the behaviour was wrong. What I would expect is:
 - Never to deploy from image `" "`
 - When deploying manually say that the ImageStream and which one is missing (instead of deploying from image `" "`)
 - It might be nice to know in web console that the deployment is waiting for something. Currently it says _No events to show._

**Comment by kargakis** [comment] 2016-05-25 11:55
> Never to deploy from image " " 

@smarterclayton @ironcladlou do we want to stop users from deploying things we may know that won't deploy?

> When deploying manually say that the ImageStream and which one is missing (instead of deploying from image " ")

@deads2k we have a warning for this in `oc status` but we filter out cross-namespace links so we don't show it (common case: images come from the openshift namespace, deployments in other projects). I am not sure we have an issue about tracking cross-namespace links but I found https://github.com/openshift/origin/issues/7033.

> It might be nice to know in web console that the deployment is waiting for something. Currently it says No events to show. 

cc: @spadgett @fabianofranz 
We do this in oc status currently

**Comment by smarterclayton** [comment] 2016-05-25 16:07
> @smarterclayton <https://github.com/smarterclayton> @ironcladlou
<https://github.com/ironcladlou> do we want to stop users from deploying
things we may know that won't deploy?

Ultimately we can't know that.  But, we do need to do the following things:

1. Summarize controller failures on the status of the resource (i.e. RCs
that are completely unable to match scale should be writing something to
status that conveys why, not just events, same for D, same for DC, same for
DS, etc)
2. Provide better APIs for "checking" pod specs - like @deads2k's PSP SAR
3. Have admission dry run - that enhances #2 above but doesn't replace it

**Comment by kargakis** [comment] 2016-05-25 16:48
> Summarize controller failures on the status of the resource (i.e. RCs that are completely unable to match scale should be writing something to status that conveys why, not just events, same for D, same for DC, same for DS, etc)

Sounds like Conditions

**Comment by kargakis** [comment] 2016-05-26 16:17
Talked in person with @tnozicka and it seems that his main problem is https://github.com/openshift/origin/issues/9018#issuecomment-221542188. It seems that a big part of the create from template flow is like this: there are precreated images and when we process and create from a template, the deployment config will need to wait for the image controller to sync before it can start a new deployment. This will be fixed by having the image controller look for create events in a deploymentconfig cache, see if that dc points to an existing stream, and enqueue that stream instead of waiting for the resync interval.

**Comment by kargakis** [comment] 2016-05-26 16:20
Opened https://github.com/openshift/origin/issues/9041 for the console part

**Comment by mfojtik** [comment] 2016-07-29 12:29
@tnozicka the caches have been merged, can you please try to reproduce with master version?

**Comment by tnozicka** [comment] 2016-08-02 11:25
@mfojtik sadly the openshift `latest` images on Docker Hub are more than a month old, so I don't suppose they reflect master. I will look into building them from master manually and try it out.

**Comment by kargakis** [comment] 2016-08-03 08:24
@mfojtik we still need /instantiate for this to be fixed. (or we could switch the image change controller to use the shared deploment config cache and an index from DC to IS)

**Comment by mfojtik** [comment] 2016-08-03 09:00
@kargakis I will prefer instantiate

**Comment by tnozicka** [comment] 2016-08-03 11:11
@mfojtik There is still a pause (about 30s, but this is probably related to the 2 min sync interval) before first deployment and after deploying it manually in that time it will deploy from image " " and after few seconds it gets canceled.

Most probably related to @kargakis https://github.com/openshift/origin/issues/9018#issuecomment-237174842. I will wait with further testing.

**Comment by kargakis** [comment] 2016-08-03 11:20
me too - is the code freeze on? I won't get to this earlier than 15/8

**Comment by mfojtik** [comment] 2016-08-03 11:54
@kargakis not yet

**Comment by kargakis** [comment] 2016-08-03 14:37
P2 since it's punted for 1.3.1

**Closed** 2016-08-17 21:10 UTC
Labels: component/deployments, priority/P2
