### ISSUE TITLE
Failed build message while also showing confusing "allocating IP..." running message in Web Console

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#3066] opened 2015-06-10 18:55 UTC
I have a problem where there is problem with my setup where builds are failing to be pushed to the registry.  Though the message gives me the sense that an IP is being allocated.

  "gitVersion": "v0.17.1-804-g496be63",
  "gitCommit": "496be63",

![image](https://cloud.githubusercontent.com/assets/727196/8091231/a15ba4b0-0f80-11e5-816c-b614036d7368.png)

**Comment by liggitt** [comment] 2015-06-10 18:55
Dupe of #2877

**Closed by liggitt** 2015-06-10 18:55 UTC

**Comment by liggitt** [comment] 2015-06-10 18:56
also, the build pod should not be appearing in the UI unless it has labels that are making it be selected by the service... if so, that's concerning and should be fixed. @bparees anything change with the labels applied to build pods recently?

**Comment by bparees** [comment] 2015-06-10 19:03
@liggitt nothing that comes to mind.....

**Comment by sspeiche** [comment] 2015-06-10 19:59
@liggitt @bparees  I just pulled the "latest" and it doesn't show the build pod in the overview

  "gitVersion": "v0.17.1-804-g496be63",
  "gitCommit": "496be63",
