### ISSUE TITLE
Driver Flake:  devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13014] opened 2017-02-20 13:36 UTC
Looks like [this](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance_future/330/testReport/junit/(root)/Extended/_registry__migration__manifest_migration_from_etcd_to_registry_storage_registry_can_get_access_to_manifest__local_/):

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/registry.go:122
Expected error:
    <*errors.errorString | 0xc42142d2f0>: {
        s: "failed to build \"172.30.224.63:5000/extended-test-registry-migration-psd4k-jlm2p/app:latest\" image: devmapper: Error activating devmapper device for 'a721ecc5ef5f87103044fdef40a4ad072d830b333c1a76fa1fac4b23f3d2e6fd-init': devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed",
    }
    failed to build "172.30.224.63:5000/extended-test-registry-migration-psd4k-jlm2p/app:latest" image: devmapper: Error activating devmapper device for 'a721ecc5ef5f87103044fdef40a4ad072d830b333c1a76fa1fac4b23f3d2e6fd-init': devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/registry.go:54
```

<details>
<summary>Click for full output:</summary>

```
Stacktrace

/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/registry.go:122
Expected error:
    <*errors.errorString | 0xc42142d2f0>: {
        s: "failed to build \"172.30.224.63:5000/extended-test-registry-migration-psd4k-jlm2p/app:latest\" image: devmapper: Error activating devmapper device for 'a721ecc5ef5f87103044fdef40a4ad072d830b333c1a76fa1fac4b23f3d2e6fd-init': devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed",
    }
    failed to build "172.30.224.63:5000/extended-test-registry-migration-psd4k-jlm2p/app:latest" image: devmapper: Error activating devmapper device for 'a721ecc5ef5f87103044fdef40a4ad072d830b333c1a76fa1fac4b23f3d2e6fd-init': devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/registry.go:54

Standard Output

[BeforeEach] [Top Level]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:47
[BeforeEach] [registry][migration] manifest migration from etcd to registry storage
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:141
STEP: Creating a kubernetes client
Feb 18 05:54:29.699: INFO: >>> kubeConfig: /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig

STEP: Building a namespace api object
Feb 18 05:54:29.727: INFO: configPath is now "/tmp/extended-test-registry-migration-psd4k-jlm2p-user.kubeconfig"
Feb 18 05:54:29.727: INFO: The user is now "extended-test-registry-migration-psd4k-jlm2p-user"
Feb 18 05:54:29.727: INFO: Creating project "extended-test-registry-migration-psd4k-jlm2p"
STEP: Waiting for a default service account to be provisioned in namespace
[It] registry can get access to manifest [local]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/registry.go:122
STEP: set up policy for registry to have anonymous access to images
Feb 18 05:54:29.805: INFO: Running 'oc policy --config=/tmp/extended-test-registry-migration-psd4k-jlm2p-user.kubeconfig --namespace=extended-test-registry-migration-psd4k-jlm2p add-role-to-user registry-viewer system:anonymous'
role "registry-viewer" added: "system:anonymous"
STEP: pushing image...
Step 1 : FROM scratch
 ---> 
Step 2 : COPY data1 /data1
STEP: Deleting images and image streams in project "extended-test-registry-migration-psd4k-jlm2p"
[AfterEach] [registry][migration] manifest migration from etcd to registry storage
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:142
STEP: Collecting events from namespace "extended-test-registry-migration-psd4k-jlm2p".
STEP: Found 0 events.
Feb 18 05:54:30.675: INFO: POD                      NODE          PHASE    GRACE  CONDITIONS
Feb 18 05:54:30.675: INFO: docker-registry-1-gkdx6  172.18.7.169  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:39:02 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:39:08 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:39:02 -0500 EST  }]
Feb 18 05:54:30.675: INFO: router-2-kw776           172.18.7.169  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:40:32 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:40:53 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:40:32 -0500 EST  }]
Feb 18 05:54:30.675: INFO: history-limit-2-0lc0t    172.18.7.169  Running  30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:53:48 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:53:51 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:53:48 -0500 EST  }]
Feb 18 05:54:30.675: INFO: history-limit-3-zt7n8    172.18.7.169  Running  30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:09 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:13 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:09 -0500 EST  }]
Feb 18 05:54:30.675: INFO: history-limit-4-683l8    172.18.7.169  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:22 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:26 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:22 -0500 EST  }]
Feb 18 05:54:30.675: INFO: history-limit-5-deploy   172.18.7.169  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:28 -0500 EST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:28 -0500 EST ContainersNotReady containers with unready status: [deployment]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:28 -0500 EST  }]
Feb 18 05:54:30.675: INFO: example-1-3g31x          172.18.7.169  Running  30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:53:57 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:08 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:53:57 -0500 EST  }]
Feb 18 05:54:30.675: INFO: hello-openshift          172.18.7.169  Running  30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:24 -0500 EST  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:27 -0500 EST  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-02-18 05:54:24 -0500 EST  }]
Feb 18 05:54:30.675: INFO: 
Feb 18 05:54:30.678: INFO: 
Logging node info for node 172.18.7.169
Feb 18 05:54:30.680: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
Feb 18 05:54:30.680: INFO: 
Logging kubelet events for node 172.18.7.169
Feb 18 05:54:30.681: INFO: 
Logging pods the kubelet thinks is on node 172.18.7.169
Feb 18 05:54:30.687: INFO: router-2-kw776 started at 2017-02-18 05:40:32 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container router ready: true, restart count 0
Feb 18 05:54:30.687: INFO: history-limit-2-0lc0t started at 2017-02-18 05:53:48 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container myapp ready: true, restart count 0
Feb 18 05:54:30.687: INFO: history-limit-4-683l8 started at 2017-02-18 05:54:22 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container myapp ready: true, restart count 0
Feb 18 05:54:30.687: INFO: history-limit-3-zt7n8 started at 2017-02-18 05:54:09 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container myapp ready: true, restart count 0
Feb 18 05:54:30.687: INFO: docker-registry-1-gkdx6 started at 2017-02-18 05:39:02 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container registry ready: true, restart count 0
Feb 18 05:54:30.687: INFO: history-limit-5-deploy started at 2017-02-18 05:54:28 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container deployment ready: false, restart count 0
Feb 18 05:54:30.687: INFO: example-1-3g31x started at 2017-02-18 05:53:57 -0500 EST (0+2 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container ruby ready: true, restart count 0
Feb 18 05:54:30.687: INFO: 	Container ruby2 ready: true, restart count 0
Feb 18 05:54:30.687: INFO: hello-openshift started at 2017-02-18 05:54:24 -0500 EST (0+1 container statuses recorded)
Feb 18 05:54:30.687: INFO: 	Container hello-openshift ready: true, restart count 0
Feb 18 05:54:30.951: INFO: 
Latency metrics for node 172.18.7.169
Feb 18 05:54:30.951: INFO: {Operation:sync Method:pod_worker_latency_microseconds Quantile:0.99 Latency:2m1.684048s}
Feb 18 05:54:30.951: INFO: {Operation:sync Method:pod_worker_latency_microseconds Quantile:0.9 Latency:2m1.684048s}
Feb 18 05:54:30.951: INFO: {Operation:sync Method:pod_worker_latency_microseconds Quantile:0.5 Latency:2m1.014738s}
Feb 18 05:54:30.951: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.99 Latency:2m0.001054s}
Feb 18 05:54:30.951: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.5 Latency:2m0.001054s}
Feb 18 05:54:30.951: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.9 Latency:2m0.001054s}
Feb 18 05:54:30.951: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:1m3.972613s}
Feb 18 05:54:30.951: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.317455s}
Feb 18 05:54:30.951: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:18.110643s}
STEP: Dumping a list of prepulled images on each node
Feb 18 05:54:30.953: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "extended-test-registry-migration-psd4k-jlm2p" for this suite.
Feb 18 05:54:36.072: INFO: namespace: extended-test-registry-migration-psd4k-jlm2p, resource: bindings, ignored listing per whitelist
```

</details>

**Comment by stevekuznetsov** [comment] 2017-02-20 13:36
@runcom could you please triage this

/cc @smarterclayton @bparees

**Comment by jwhonce** [comment] 2017-02-20 16:44
@stevekuznetsov Please provide some additional information.

Output of docker version and info subcommands,   lvs, dmsetup table and status, and journald entries for the period of failure.  Thanks!

**Comment by smarterclayton** [comment] 2017-02-20 17:37
This is from e2e tests.  The e2e run log contains the docker version.  You
can assume that a standard openshift ami has all the info.

On Feb 20, 2017, at 11:44 AM, Jhon Honce <notifications@github.com> wrote:

@stevekuznetsov <https://github.com/stevekuznetsov> Please provide some
additional information.

Output of docker version and info subcommands, lvs, dmsetup table and
status, and journald entries for the period of failure. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13014#issuecomment-281127807>,
or mute the thread

**Comment by stevekuznetsov** [comment] 2017-02-20 18:10
@jwhonce I can't get you system journal entries as the machine on which this happened was deprovisioned, but here are some of the other info:

```
# rpm -qa docker
docker-1.12.5-14.el7.x86_64

# docker version
Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Wed Jan 11 17:53:20 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Wed Jan 11 17:53:20 2017
 OS/Arch:         linux/amd64

# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 19.92 MB
 Data Space Total: 7.457 GB
 Data Space Available: 7.438 GB
 Metadata Space Used: 40.96 kB
 Metadata Space Total: 29.36 MB
 Metadata Space Available: 29.32 MB
 Thin Pool Minimum Free Space: 745.5 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay null host bridge
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.26 GiB
Name: ip-172-18-5-57.ec2.internal
ID: ZXF5:XJQ7:24DD:NPFJ:6X5D:7VHX:XI2J:NWCD:7GTE:Q4MA:6AZV:JSQC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 ci.dev.openshift.redhat.com:5000
 172.30.0.0/16
 127.0.0.0/8
Registries: docker.io (secure)

# lvs
  LV                    VG     Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool           docker twi-a-t--- 6.95g             0.27   0.14                            
  openshift-xfs-vol-dir docker -wi-ao---- 7.50g                                                    

# dmsetup table
docker-docker--pool: 0 14565376 thin-pool 253:1 253:2 1024 5689 1 skip_block_zeroing 
docker-openshift--xfs--vol--dir: 0 15720448 linear 202:17 2048
docker-docker--pool_tdata: 0 14565376 linear 202:17 15779840
docker-docker--pool_tmeta: 0 57344 linear 202:17 30345216

# dmsetup status
docker-docker--pool: 0 14565376 thin-pool 1 10/7168 38/14224 - rw no_discard_passdown queue_if_no_space - 
docker-openshift--xfs--vol--dir: 0 15720448 linear 
docker-docker--pool_tdata: 0 14565376 linear 
docker-docker--pool_tmeta: 0 57344 linear 
```

To stand up a reproducer you could launch the AMI (ami-f1b3a8e6) or install the [`origin-ci-tool`](https://github.com/openshift/origin-ci-tool#installation) and [provision a VM](https://github.com/openshift/origin-ci-tool#provisioning-an-openshift-origin-all-in-one-in-the-cloud):
```
$ oct provision remote all-in-one --stage base --os rhel --provider aws --name jwhonce_testing
```

**Comment by pweil-** [comment] 2017-06-20 07:26
Some logs of a build failing with devmapper issues ending in the same ` Error running deviceCreate (ActivateDevice) dm_task_run failed` error

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/581/testReport/junit/(root)/Extended/_builds__Conformance__build_without_output_image_building_from_templates_should_create_an_image_from_a_docker_template_without_an_output_image_reference_defined/

**Comment by jwhonce** [comment] 2017-06-20 16:38
@pweil- Do you know the version of docker rpm currently being used on that build?

**Comment by stevekuznetsov** [comment] 2017-06-20 16:46
@jwhonce the repo we use for Docker today is [here](https://mirror.openshift.com/enterprise/rhel/dockerextra/x86_64/os/Packages/) and the job we use to update it is [here](https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/aos-cd/job/package-dockertested/). An email is sent out when a new version is brought in. Today we are running `docker-1.12.6-28.git1398f24.el7.x86_64`.

**Comment by rhatdan** [comment] 2017-06-20 19:58
docker-1.12.6-32.git88a4867.el7 Has it I believe.

**Comment by stevekuznetsov** [comment] 2017-06-20 20:03
Hmm -- we're not seeing that in `rhel7next` repositories at https://mirror.openshift.com/enterprise/rhel/rhel7next/os/ -- that's where we're picking up new builds from.

**Comment by jwhonce** [comment] 2017-06-21 17:29
@stevekuznetsov Troy used to be the guy who maintained those mirrors.  I don't know who took over for him in Ops.

**Comment by stevekuznetsov** [comment] 2017-06-21 17:33
IIRC @sdodson there is a job that syncs those from Brew -- just wondering if we have changed the way releases are tagged? The newer builds have not been synced in

**Comment by sdodson** [comment] 2017-06-21 17:44
Those packages are tagged for rhel-7.3-extras-candidate but maybe they're just not doing any more composes of that tag? i can switch you to rhel 7.4 content but that will bring in a pile of other changes and i think you'd also want to move to rhel 7.4 repos for the base packages also.

What do you think we should do?

**Comment by sdodson** [comment] 2017-06-21 17:46
checking as to why there haven't been any newer 7.3 extras composes first

**Comment by stevekuznetsov** [comment] 2017-06-21 17:47
Honestly what we really need is to finish out the testing strategy with @johnbieren and get Origin using Docker straight from the firehose, without intermediate repo shuffling.

**Comment by bparees** [comment] 2017-08-26 03:32
seen again here:

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_builds/128/testReport/junit/(root)/Extended/_builds__Slow__starting_a_build_using_CLI_binary_builds_shoud_accept___from_archive_with_https_URL_as_an_input/

**Comment by jwhonce** [comment] 2017-08-29 15:47
@stevekuznetsov and @johnbieren Where do we stand on getting later builds for @bparees to use for his builds?

**Comment by bparees** [comment] 2017-08-29 16:04
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/5014/testReport/junit/(root)/Extended/_builds__Conformance__s2i_build_with_a_root_user_image_Building_using_an_image_with_a_root_default_user_should_fail_the_build_immediately/

**Comment by bparees** [comment] 2017-08-29 16:05
Note that that wasn't really a build specific failure, the pod couldn't create an init container.  It just happened to be a build pod that included the init container.

**Comment by jim-minter** [comment] 2017-08-31 14:49
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/5182/

**Comment by stevekuznetsov** [comment] 2017-08-31 14:53
@jwhonce

**Comment by bparees** [comment] 2017-10-05 20:04
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16698/test_pull_request_origin_extended_builds/427/

`
devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed,StartedAt:2017-10-05 18:24:08 +0000 UTC,FinishedAt:2017-10-05 18:24:08 +0000 UTC,ContainerID:docker://cdd5bf0b45d0a538e41aa436ea211138f0c8e75de947506fd8c9ee06ae811d49
`

**Comment by jwhonce** [comment] 2017-10-05 22:29
@bparees Do you know if it's possible to see the /etc/sysconfig/docker-storage* files or the `systemctl status docker` of a run with one of these flakes?

**Comment by bparees** [comment] 2017-10-05 22:33
@jwhonce everything that's gathered is here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_builds/427/s3/

if what you need isn't in there, you can work with @stevekuznetsov to update our test jobs+scripts to get it to start gathering what you need.

**Comment by bparees** [comment] 2017-10-11 14:43
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16745/test_pull_request_origin_extended_conformance_install_update/7672/?

**Comment by bparees** [comment] 2017-10-14 15:37
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/239/testReport/junit/(root)/Extended/_Feature_Builds__Slow__completed_builds_should_have_digest_of_the_image_in_their_status__S2I_build_started_with_normal_log_level_should_save_the_image_digest_when_finished__Suite_openshift_/

**Comment by bparees** [comment] 2017-10-18 15:03
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16924/test_pull_request_origin_extended_builds/504/

**Comment by stevekuznetsov** [comment] 2017-10-18 15:18
@jwhonce are we still missing information here?

**Comment by bparees** [comment] 2017-11-02 13:20
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/265/testReport/junit/(root)/Extended/_Feature_Builds__Conformance__oc_new_app__should_succeed_with_a___name_of_58_characters__Suite_openshift_conformance_parallel_/

```
2017-11-02T12:21:00.305954000Z pulling image error : failed to register layer: devmapper: Error activating devmapper device for '5c4b8c87404155111dad7c1811f1a7509a7ed2fcf3c5032f7e9af72c4674b61b': devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed
```

@jim-minter is this the issue you addressed (race condition in systemd and docker?)

**Comment by jim-minter** [comment] 2017-11-09 18:09
@bparees not connected

**Comment by smarterclayton** [comment] 2018-01-24 18:37
We haven't seen this in a while. Closing

**Closed by smarterclayton** 2018-01-24 18:37 UTC
Labels: component/storage, dependency/devicemapper, kind/test-flake, priority/P1, vendor-update

**Comment by bparees** [comment] 2018-01-24 18:41
Well, there's another issue open for what I think is the same thing:
https://github.com/openshift/origin/issues/17787

so we can close this as a dupe of that, but i think it's still happening.  (perhaps it will be resolved by the same thing that fixes https://github.com/openshift/origin/issues/17330, which we're supposed to be getting in our AMIs very soon now)
