### ISSUE TITLE
Error in logs during router reload

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7273] opened 2016-02-12 23:49 UTC
Seeing this while reloads are happening

```
E0212 15:04:51.084807       1 ratelimiter.go:48] error reloading router: wait: no child processes
---
+ config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ haproxy_conf_dir=/var/lib/haproxy/conf
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_be.map -o /var/lib/haproxy/conf/os_edge_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_expose.map -o /var/lib/haproxy/conf/os_edge_http_expose.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_edge_http_redirect.map -o /var/lib/haproxy/conf/os_edge_http_redirect.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_reencrypt.map -o /var/lib/haproxy/conf/os_reencrypt.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_sni_passthrough.map -o /var/lib/haproxy/conf/os_sni_passthrough.map
+ for mapfile in '"$haproxy_conf_dir"/*.map'
+ sort -r /var/lib/haproxy/conf/os_tcp_be.map -o /var/lib/haproxy/conf/os_tcp_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ old_pid=104
+ '[' -n 104 ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 104
```

What's the cause, and should we be outputting this at all (the process is still running).

**Comment by smarterclayton** [comment] 2016-02-12 23:49
@ramr

**Comment by ramr** [comment] 2016-03-07 18:52
Found this clearing my stack of emails from when I was out - this is a duplicate of #7657 (the other way around really but the other issue has the discussion trail).

**Comment by ramr** [comment] 2016-03-14 21:15
@smarterclayton  can you please close this one out - is a dup of #7657 and was closed with -https://github.com/openshift/origin/pull/7805

**Closed** 2016-03-14 21:18 UTC
Labels: component/routing, priority/P2
