### ISSUE TITLE
NFS persistent storage in 1.0.5

### ISSUE THREAD

**Issue by amdonov** [openshift/origin#4503] opened 2015-09-03 12:58 UTC
I'm unable to start pods that use persistent storage claims in 1.0.5. 

I'm using the ansible-based installation process (tag v3.0.0-8) for configuring OpenShift and NFS. I rebuilt my environment multiple times without issue on 1.0.4. Now that 1.0.5 is out, I can successfully create persistent volume claims, but pods that reference them just hang, and the UI state says "pulling". If I replace the persistent volume claim in the deployment configuration with an emptyDir, pods start without error. I'm not seeing anything in the logs. No events are added.

**Comment by pat2man** [comment] 2015-09-03 23:57
Could this be similar to my issue here? https://github.com/openshift/origin/issues/4420

**Comment by amdonov** [comment] 2015-09-04 02:07
Thanks. Yes it's the same issue. I hadn't specifically watched at the openshift-node log when deploying.
I get the following:

Sep 03 22:00:51 master.example.com openshift-node[6915]: E0903 22:00:51.139714    6915 util.go:68] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/util/util.go:62
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/util/util.go:53
Sep 03 22:00:51 master.example.com openshift-node[6915]: /usr/lib/golang/src/runtime/asm_amd64.s:401
Sep 03 22:00:51 master.example.com openshift-node[6915]: /usr/lib/golang/src/runtime/panic.go:387
Sep 03 22:00:51 master.example.com openshift-node[6915]: /usr/lib/golang/src/runtime/panic.go:42
Sep 03 22:00:51 master.example.com openshift-node[6915]: /usr/lib/golang/src/runtime/sigpanic_unix.go:26
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/volume/secret/secret.go:59
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/volume/plugins.go:223
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:83
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:59
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/volume/persistent_claim/persistent_claim.go:82
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:91
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:111
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1201
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:356
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:109
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:118
Sep 03 22:00:51 master.example.com openshift-node[6915]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_thirdpartyhacks/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:153
Sep 03 22:00:51 master.example.com openshift-node[6915]: /usr/lib/golang/src/runtime/asm_amd64.s:2232

**Comment by liggitt** [comment] 2015-09-11 04:04
Closing as dupe of #4420 as per https://github.com/openshift/origin/issues/4420#issuecomment-139338816
Fixed in #4384, will be in 1.0.6

**Closed by liggitt** 2015-09-11 04:04 UTC
Labels: component/storage, priority/P1
