### ISSUE TITLE
TestAuthorizationRestrictedAccessForProjectAdmins / TestAuthorizationSubjectAccessReview flake

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6065] opened 2015-11-24 21:07 UTC
Seen [here](https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4127/consoleFull):
```
Running TestAuthorizationSubjectAccessReview...
failed  TestAuthorizationSubjectAccessReview
...
F1124 08:45:26.030730   12507 run_components.go:393] Unable to initialize namespaces: unable to refresh the security allocation UID blocks: User "system:openshift-master" cannot list all namespaces in the cluster
```

**Comment by rhcarvalho** [comment] 2015-11-26 10:27
One more instance: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7486/console

**Comment by kargakis** [comment] 2015-12-02 20:54
Different flake, same test
```
--- FAIL: TestAuthorizationSubjectAccessReview-4 (14.10s)
	authorization_test.go:488: unexpected error: namespaces "hammer-project" already exists
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7612/consoleFull

**Comment by ncdc** [comment] 2015-12-04 02:25
Here's another flake for this test, from https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4236/consoleFull:

```
F1203 13:59:18.599912   26267 controller.go:87] Unable to perform initial service nodePort check: unable to persist the updated port allocations: servicenodeportallocation "" cannot be updated: another caller has already initialized the resource
```

**Comment by eparis** [comment] 2015-12-04 19:31
And another from https://github.com/openshift/origin/pull/6000:
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4224/console

**Comment by bparees** [comment] 2015-12-11 20:41
and another one:
```
--- FAIL: TestAuthorizationSubjectAccessReview-4 (13.34s)
	authorization_test.go:493: unexpected error: policybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
FAIL
```

from https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4304/console

**Comment by miminar** [comment] 2015-12-14 08:36
Yet another one:

     I1211 10:38:41.309103    8918 create_clientcert.go:52] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080fc240), CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.key", User:"system:openshift-registry", Groups:[]string{"system:registries"}, Overwrite:false, Output:(*os.File)(0xc208068010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:0, sema:0x0}, ca:(*crypto.CA)(0xc208311140)}
    I1211 10:38:41.421921    8918 create_clientcert.go:70] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt and key at /tmp/openshift-integration/openshift.local.config/master/openshift-registry.key
    I1211 10:38:41.421946    8918 create_kubeconfig.go:132] creating a .kubeconfig with: admin.CreateKubeConfigOptions{APIServerURL:"https://127.0.0.1:12000", PublicAPIServerURL:"https://127.0.0.1:12000", APIServerCAFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.key", ContextNamespace:"default", KubeConfigFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.kubeconfig", Output:(*os.File)(0xc208068010)}
    I1211 10:38:41.534274    8918 create_kubeconfig.go:200] Generating 'system:openshift-registry/127-0-0-1:12000' API client config as /tmp/openshift-integration/openshift.local.config/master/openshift-registry.kubeconfig
    F1211 10:38:51.992474    8918 etcd.go:38] Unable delete key: 100: Key not found (/openshift.io) [1009]


builds [7748](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7748/console), [7590](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7590/console), [7577](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7577/console)

**Comment by liggitt** [comment] 2015-12-18 01:55
It certainly seems like more than our one test server is talking to the shared etcd at once. Things like this:
```
I1217 19:02:45.906977   21950 ensure.go:174] No cluster policy found.  Creating bootstrap policy based on: /tmp/openshift-integration/openshift.local.config/master/policy.json
I1217 19:02:45.907069   21950 decoder.go:141] decoding stream as JSON
I1217 19:02:56.916462   21950 trace.go:57] Trace "Create *api.ClusterPolicyBinding" (started 2015-12-17 19:02:46.265136678 -0500 EST):
[30.043µs] [30.043µs] About to create object
[10.651291834s] [10.651261791s] END
E1217 19:02:56.916498   21950 ensure.go:177] Error creating bootstrap policy: clusterpolicybinding ":default" already exists
```

And this:
```
F1211 10:38:51.992474    8918 etcd.go:38] Unable delete key: 100: Key not found (/openshift.io) [1009]
```

**Comment by rhcarvalho** [comment] 2015-12-18 16:09
One more time: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7960/

**Comment by liggitt** [comment] 2015-12-19 20:13
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4431/console
https://github.com/openshift/origin/pull/6418
```
I1219 14:52:03.014415   21047 etcd.go:37] Deleting &etcd.Node{Key:"/kubernetes.io", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes(nil), ModifiedIndex:0x348, CreatedIndex:0x348} (child of &etcd.Node{Key:"", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes{(*etcd.Node)(0xc2086b8060), (*etcd.Node)(0xc2086b80c0)}, ModifiedIndex:0x0, CreatedIndex:0x0})
I1219 14:52:07.248341   21047 etcd.go:37] Deleting &etcd.Node{Key:"/openshift.io", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes(nil), ModifiedIndex:0x34f, CreatedIndex:0x34f} (child of &etcd.Node{Key:"", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes{(*etcd.Node)(0xc2086b8060), (*etcd.Node)(0xc2086b80c0)}, ModifiedIndex:0x0, CreatedIndex:0x0})
F1219 14:52:14.653034   21047 etcd.go:39] Unable to delete key: 100: Key not found (/openshift.io) [1124]
```

**Comment by liggitt** [comment] 2015-12-21 20:12
With added logging, I can see the client getting a 500 error from etcd, then retrying:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8036/consoleFull:
```
I1221 11:21:12.643376   22178 etcd.go:40] Deleting &etcd.Node{Key:"/kubernetes.io", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes(nil), ModifiedIndex:0x333, CreatedIndex:0x333} (child of &etcd.Node{Key:"", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes{(*etcd.Node)(0xc208760060), (*etcd.Node)(0xc2087600c0)}, ModifiedIndex:0x0, CreatedIndex:0x0})
I1221 11:21:13.695552   22178 etcd.go:40] Deleting &etcd.Node{Key:"/openshift.io", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes(nil), ModifiedIndex:0x33a, CreatedIndex:0x33a} (child of &etcd.Node{Key:"", Value:"", Dir:true, Expiration:(*time.Time)(nil), TTL:0, Nodes:etcd.Nodes{(*etcd.Node)(0xc208760060), (*etcd.Node)(0xc2087600c0)}, ModifiedIndex:0x0, CreatedIndex:0x0})
F1221 11:21:21.068044   22178 etcd.go:42] Unable to delete key: 100: Key not found (/openshift.io) [1051]
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8036/artifact/origin/artifacts/e2e/logs/integration-etcd-1450714866-TestAuthorizationSubjectAccessReview.log
```
go-etcd2015/12/21 11:21:06 DEBUG: Shuffle cluster machines[http://127.0.0.1:44001]
go-etcd2015/12/21 11:21:06 DEBUG: get / [http://127.0.0.1:44001]
go-etcd2015/12/21 11:21:06 DEBUG: Connecting to etcd: attempt 1 for keys/?quorum=false&recursive=false&sorted=false
go-etcd2015/12/21 11:21:06 DEBUG: send.request.to http://127.0.0.1:44001/v2/keys/?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/12/21 11:21:06 DEBUG: recv.response.from 
go-etcd2015/12/21 11:21:06 DEBUG: recv.success 
go-etcd2015/12/21 11:21:12 DEBUG: Shuffle cluster machines[http://127.0.0.1:44001]
go-etcd2015/12/21 11:21:12 DEBUG: get / [http://127.0.0.1:44001]
go-etcd2015/12/21 11:21:12 DEBUG: Connecting to etcd: attempt 1 for keys/?quorum=false&recursive=false&sorted=false
go-etcd2015/12/21 11:21:12 DEBUG: send.request.to http://127.0.0.1:44001/v2/keys/?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/12/21 11:21:12 DEBUG: recv.response.from 
go-etcd2015/12/21 11:21:12 DEBUG: recv.success 
go-etcd2015/12/21 11:21:12 DEBUG: delete /kubernetes.io [http://127.0.0.1:44001]
go-etcd2015/12/21 11:21:12 DEBUG: Connecting to etcd: attempt 1 for keys/kubernetes.io?dir=false&recursive=true
go-etcd2015/12/21 11:21:12 DEBUG: send.request.to http://127.0.0.1:44001/v2/keys/kubernetes.io?dir=false&recursive=true | method DELETE
go-etcd2015/12/21 11:21:13 DEBUG: recv.response.from 
go-etcd2015/12/21 11:21:13 DEBUG: recv.success 
go-etcd2015/12/21 11:21:13 DEBUG: delete /openshift.io [http://127.0.0.1:44001]
go-etcd2015/12/21 11:21:13 DEBUG: Connecting to etcd: attempt 1 for keys/openshift.io?dir=false&recursive=true
go-etcd2015/12/21 11:21:13 DEBUG: send.request.to http://127.0.0.1:44001/v2/keys/openshift.io?dir=false&recursive=true | method DELETE
go-etcd2015/12/21 11:21:19 DEBUG: recv.response.from 
go-etcd2015/12/21 11:21:19 WARNING: bad response status code 500
go-etcd2015/12/21 11:21:19 DEBUG: Connecting to etcd: attempt 2 for keys/openshift.io?dir=false&recursive=true
go-etcd2015/12/21 11:21:19 DEBUG: send.request.to http://127.0.0.1:44001/v2/keys/openshift.io?dir=false&recursive=true | method DELETE
go-etcd2015/12/21 11:21:21 DEBUG: recv.response.from 
go-etcd2015/12/21 11:21:21 DEBUG: recv.success 
```

listed processes before and after the integration test are clean, no unexpected openshift processes are running

**Comment by liggitt** [comment] 2015-12-21 21:28
seems to correlate to this bit in the etcd server log:
```
2015/12/21 11:21:11 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/12/21 11:21:19 etcdhttp: got unexpected response error (etcdserver: request timed out)
```

**Comment by kargakis** [comment] 2015-12-22 12:59
the hottest flake in town

**Comment by stevekuznetsov** [comment] 2015-12-22 14:13
The `e2e user can't list` is coming up as quick, though. We should hold flake races...

**Comment by liggitt** [comment] 2015-12-22 15:46
The issue is not specific to one test, it's a response to an etcd server 500 error that is seen about 30-60 seconds into the integration tests. If a client request is in progress when that server error is received, the client gets a 500 error, and reacts by retrying the request. If the request is one that would fail on a retry (like a delete or a conditional update), the test fails.

**Comment by liggitt** [comment] 2015-12-22 22:28
Running a loop with curl doing PUTs against etcd alongside the integration tests, it looks like the etcd server is stuttering, maybe during a garbage collect?
```
< Date: Tue, 22 Dec 2015 22:20:37 GMT
... repeated 237 times
< Date: Tue, 22 Dec 2015 22:20:38 GMT
... repeated 191 times
< Date: Tue, 22 Dec 2015 22:20:39 GMT
... repeated 182 times
< Date: Tue, 22 Dec 2015 22:20:40 GMT
... repeated 175 times
< Date: Tue, 22 Dec 2015 22:20:41 GMT
... repeated 301 times
< Date: Tue, 22 Dec 2015 22:20:42 GMT
... repeated 219 times
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< X-Etcd-Cluster-Id: a176fdba55eb9204
< X-Etcd-Index: 0
< Date: Tue, 22 Dec 2015 22:20:48 GMT
< Content-Length: 100
< 
{ [data not shown]
* Connection #0 to host 127.0.0.1 left intact
{"errorCode":300,"message":"Raft Internal Error","cause":"etcdserver: request timed out","index":0}
< Date: Tue, 22 Dec 2015 22:20:48 GMT
< Date: Tue, 22 Dec 2015 22:20:53 GMT
< Date: Tue, 22 Dec 2015 22:20:56 GMT
... repeated 149 times
< Date: Tue, 22 Dec 2015 22:20:57 GMT
... repeated 337 times
< Date: Tue, 22 Dec 2015 22:20:58 GMT
... repeated 334 times
< Date: Tue, 22 Dec 2015 22:20:59 GMT
... repeated 336 times
< Date: Tue, 22 Dec 2015 22:21:00 GMT
... repeated 329 times

```

**Comment by smarterclayton** [comment] 2015-12-23 18:01
Hrm - maybe try against my 2.2.2 branch?

**Comment by liggitt** [comment] 2016-01-08 21:57
trace logging:

Ran etcd with strace:
```
strace -T -t -e trace=file,fsync etcd ...

16:52:58 fsync(6)                       = 0 <0.012378>
16:52:59 fsync(6)                       = 0 <0.003536>
16:52:59 fsync(6)                       = 0 <0.002344>
16:52:59 fsync(6)                       = 0 <0.009653>
16:52:59 fsync(6)                       = 0 <0.003805>
16:52:59 fsync(6)                       = 0 <0.000937>
16:53:01 fsync(6)                       = 0 <0.001024>
16:53:11 fsync(6)                       = 0 <0.002762>
16:53:11 fsync(6)                       = 0 <0.010583>
16:53:11 fsync(6)                       = 0 <0.005309>
16:53:11 fsync(6)                       = 0 <0.009549>
16:53:11 fsync(6)                       = 0 <0.001290>
16:53:11 fsync(6)                       = 0 <0.002286>
16:53:12 fsync(6)                       = 0 <0.006413>
16:53:16 fsync(6)                       = 0 <0.000926>
16:53:16 fsync(6)                       = 0 <0.000853>
16:53:17 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=25086, si_uid=1000} ---
16:53:17 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=25086, si_uid=1000} ---
16:53:19 fsync(6)                       = 0 <0.001162>
16:53:20 fsync(6)                       = 0 <0.001508>
16:53:21 fsync(6)                       = 0 <0.002100>
16:53:21 fsync(6)                       = 0 <0.010315>
16:53:21 fsync(6)                       = 0 <0.001080>
16:53:21 fsync(6)                       = 0 <0.000933>
16:53:21 fsync(6)                       = 0 <0.004253>
16:53:21 fsync(6)                       = 0 <0.010720>
16:53:21 fsync(6)                       = 0 <0.004427>
16:53:21 fsync(6)                       = 0 <0.003155>
16:53:21 fsync(6)                       = 0 <0.001006>
16:53:21 fsync(6)                       = 0 <0.001726>
16:53:21 fsync(6)                       = 0 <0.003563>
16:53:21 fsync(6)                       = 0 <0.001531>
16:53:21 fsync(6)                       = 0 <0.004133>
16:53:21 fsync(6)                       = 0 <0.002470>
16:53:21 fsync(6)                       = 0 <0.001251>
16:53:21 fsync(6)                       = 0 <0.004707>
16:53:21 fsync(6)                       = 0 <0.001428>
16:53:21 fsync(6)                       = 0 <0.001135>
16:53:21 fsync(6)                       = 0 <0.001134>
16:53:22 fsync(6)                       = 0 <0.012738>
16:53:26 fsync(6)                       = 0 <0.000982>
16:53:27 fsync(6)                       = 0 <0.002269>
16:53:27 fsync(6)                       = 0 <0.003343>
16:53:27 fsync(6)                       = 0 <0.000843>
16:53:27 fsync(6)                       = 0 <0.001534>
16:53:27 fsync(6)                       = 0 <0.001668>
16:53:27 fsync(6)                       = 0 <0.008269>
16:53:27 fsync(6)                       = 0 <0.003643>
16:53:27 fsync(6)                       = 0 <0.000883>
16:53:27 fsync(6)                       = 0 <0.001062>
16:53:27 fsync(6)                       = 0 <0.002762>
16:53:27 fsync(6)                       = 0 <0.009917>
16:53:27 open("/tmp/openshift-integration/etcd/member/snap", O_RDONLY|O_CLOEXEC) = 51 <0.000029>
16:53:27 open("/tmp/openshift-integration/etcd/member/wal", O_RDONLY|O_CLOEXEC) = 51 <0.000020>
16:53:28 fsync(6)                       = 0 <0.002104>
16:53:28 fsync(6)                       = 0 <0.002788>
16:53:28 fsync(6)                       = 0 <0.004591>
16:53:28 fsync(6)                       = 0 <0.001057>
16:53:28 fsync(6)                       = 0 <0.003177>
16:53:32 fsync(6)                       = 0 <0.001171>
16:53:34 fsync(6)                       = 0 <0.001422>
16:53:34 fsync(6)                       = 0 <0.000948>
16:53:34 fsync(6)                       = 0 <0.001091>
16:53:40 fsync(6)                       = 0 <0.000901>
16:53:40 fsync(6)                       = 0 <0.002144>
16:53:40 fsync(6)                       = 0 <0.000933>
```

monitored iops during test-integration.sh run:
```
iostat -dx xvda -k 1

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.00     0.00    0.00    4.00     0.00    22.50    11.25     0.00    0.25    0.00    0.25   0.25   0.10
xvda              0.00     0.00    0.00    5.94     0.00    34.65    11.67     0.00    0.33    0.00    0.33   0.33   0.20
xvda              0.00     0.00    0.00    8.00     0.00    43.00    10.75     0.01    0.75    0.00    0.75   0.75   0.60
xvda              0.00     0.00    0.00    6.00     0.00    35.50    11.83     0.00    0.17    0.00    0.17   0.17   0.10
xvda              0.00     0.00    0.00   17.00     0.00    67.00     7.88     0.01    0.29    0.00    0.29   0.29   0.50
xvda              0.00     6.00    0.00  134.00     0.00  1238.00    18.48     0.08    0.61    0.00    0.61   0.58   7.80
xvda              0.00     2.00    0.00   86.00     0.00   360.50     8.38     0.04    0.48    0.00    0.48   0.48   4.10
xvda              0.00     0.00    0.00  124.75     0.00   426.73     6.84     0.06    0.46    0.00    0.46   0.46   5.74
xvda              0.00     0.00    0.00   13.00     0.00   138.00    21.23     0.01    0.62    0.00    0.62   0.62   0.80
xvda              0.00     0.00    0.00   81.00     0.00   844.50    20.85     0.05    0.59    0.00    0.59   0.59   4.80
xvda              0.00     2.00    0.00  109.00     0.00   668.00    12.26     0.06    0.51    0.00    0.51   0.50   5.50
xvda              0.00     0.00    0.00  150.00     0.00   495.50     6.61     0.07    0.47    0.00    0.47   0.47   7.10
xvda              0.00     0.00    0.00    6.00     0.00    30.00    10.00     0.00    0.33    0.00    0.33   0.33   0.20
xvda              0.00     0.00    0.00   31.00     0.00   171.00    11.03     0.01    0.42    0.00    0.42   0.42   1.30
xvda              0.00     0.00    0.00  150.00     0.00  1331.50    17.75     0.07    0.51    0.00    0.51   0.50   7.50
xvda              0.00     0.00    0.00   48.00     0.00   204.50     8.52     0.03    0.56    0.00    0.56   0.56   2.70
xvda              0.00     0.00    0.00    7.00     0.00    37.50    10.71     0.00    0.43    0.00    0.43   0.43   0.30
xvda              0.00     0.00    0.00   60.00     0.00   470.00    15.67     0.03    0.47    0.00    0.47   0.47   2.80
xvda              0.00     2.00    0.00  126.00     0.00  1076.00    17.08     0.07    0.57    0.00    0.57   0.57   7.20
xvda              0.00     0.00    0.00  154.00     0.00   665.50     8.64     0.07    0.44    0.00    0.44   0.44   6.70
xvda              0.00     0.00    0.00   41.00     0.00   168.00     8.20     0.02    0.59    0.00    0.59   0.59   2.40
xvda              0.00     0.00    0.00   26.00     0.00   163.50    12.58     0.02    0.65    0.00    0.65   0.54   1.40
xvda              0.00     0.00    0.00  140.00     0.00  1258.50    17.98     0.07    0.49    0.00    0.49   0.49   6.90
xvda              0.00     0.00    0.00   74.00     0.00   321.50     8.69     0.04    0.47    0.00    0.47   0.47   3.50
xvda              0.00     0.00    0.00  263.00     0.00   935.00     7.11     0.11    0.41    0.00    0.41   0.41  10.70
xvda              0.00    59.00    0.00  102.00     0.00   695.00    13.63     0.28    2.76    0.00    2.76   0.28   2.90
xvda              0.00     0.00    0.00   13.00     0.00   131.50    20.23     0.01    0.54    0.00    0.54   0.54   0.70
xvda              0.00     0.00    0.00   96.00     0.00  1056.00    22.00     0.06    0.60    0.00    0.60   0.60   5.80
xvda              0.00     0.00    0.00  106.00     0.00   485.00     9.15     0.06    0.57    0.00    0.57   0.57   6.00
xvda              0.00     0.00    0.00  234.00     0.00   793.00     6.78     0.14    0.60    0.00    0.60   0.60  14.10
xvda              0.00     0.00    0.00  112.00     0.00   400.00     7.14     0.07    0.59    0.00    0.59   0.59   6.60
xvda              0.00     0.00    0.00    6.00     0.00    26.00     8.67     0.00    0.17    0.00    0.17   0.17   0.10
xvda              0.00     2.00    0.00  449.00     0.00 55436.00   246.93    48.06   78.05    0.00   78.05   0.75  33.70
xvda              0.00     0.00    0.00  416.00     0.00 41418.50   199.13    39.37  125.94    0.00  125.94   0.89  37.10
xvda              0.00     2.00    0.00  115.00     0.00   729.50    12.69     0.06    0.50    0.00    0.50   0.50   5.70
xvda              0.00     0.00    0.00  206.00     0.00   695.00     6.75     0.09    0.45    0.00    0.45   0.45   9.30
xvda              0.00     0.00    0.00  143.56     0.00   515.84     7.19     0.08    0.54    0.00    0.54   0.53   7.62
xvda              0.00     0.00    0.00   12.00     0.00    50.00     8.33     0.01    0.42    0.00    0.42   0.42   0.50
xvda              0.00     0.00    0.00    9.00     0.00    38.00     8.44     0.00    0.11    0.00    0.11   0.11   0.10
xvda              0.00     0.00    0.00   24.00     0.00   162.00    13.50     0.02    0.83    0.00    0.83   0.75   1.80
xvda              0.00     0.00    0.00  121.00     0.00  1208.00    19.97     0.07    0.60    0.00    0.60   0.60   7.30
xvda              0.00     0.00    0.00   93.00     0.00   375.00     8.06     0.05    0.56    0.00    0.56   0.56   5.20
xvda              0.00     0.00    0.00  219.00     0.00   765.00     6.99     0.09    0.40    0.00    0.40   0.41   8.90
xvda              0.00     0.00    0.00    5.00     0.00    11.00     4.40     0.00    0.20    0.00    0.20   0.00   0.00
xvda              0.00     0.00    0.00    5.00     0.00    18.00     7.20     0.01    1.00    0.00    1.00   1.00   0.50
xvda              0.00     0.00    0.00   12.00     0.00   131.50    21.92     0.01    0.42    0.00    0.42   0.42   0.50
xvda              0.00     0.00    0.00  124.00     0.00  1206.00    19.45     0.05    0.44    0.00    0.44   0.44   5.40
xvda              0.00     0.00    0.00  101.00     0.00   402.00     7.96     0.05    0.50    0.00    0.50   0.50   5.10
xvda              0.00     0.00    0.00  111.88     0.00   381.19     6.81     0.05    0.45    0.00    0.45   0.45   5.05
xvda              0.00     0.00    0.00   13.00     0.00   132.00    20.31     0.01    0.31    0.00    0.31   0.54   0.70
xvda              0.00     0.00    0.00   72.00     0.00   636.00    17.67     0.04    0.56    0.00    0.56   0.51   3.70
xvda              0.00     0.00    0.00    4.00     0.00    10.00     5.00     0.00    0.50    0.00    0.50   0.50   0.20
xvda              0.00     0.00    0.00    2.00     0.00     5.00     5.00     0.00    0.00    0.00    0.00   0.00   0.00
```

**Comment by deads2k** [comment] 2016-01-11 13:53
@liggitt any chance of an executive summary for all those numbers?  Particularly the ones without timestamps.  Does the IO storm relate to anything else time-wise?  Did we see failures in the test?

**Comment by liggitt** [comment] 2016-01-11 14:41
I think the numbers speak for themselves. Poorly. 

I haven't seen a failure yet when stracing. Will try to correlate the three logs better when I have a second.

**Comment by stevekuznetsov** [comment] 2016-01-11 14:52
When we were debugging this flake and also the imagestream timeout flake it would have been really nice to see time stamps on when commands were executed. Do we want to include that information in `os::cmd`?

**Comment by deads2k** [comment] 2016-01-11 15:00
> When we were debugging this flake and also the imagestream timeout flake it would have been really nice to see time stamps on when commands were executed. Do we want to include that information in os::cmd?

I don't feel strongly, we should probably focus in other areas first.  As a for instance, gathering resource utilization is probably more valuable to start.

**Comment by deads2k** [comment] 2016-01-11 15:04
@stevekuznetsov and while I'm wishing, graphing it so I can just click the image in the jenkins artifacts would be nice too.

**Comment by deads2k** [comment] 2016-01-12 19:20
dupe of https://github.com/openshift/origin/issues/6447

**Closed by deads2k** 2016-01-12 19:20 UTC
Labels: kind/test-flake, priority/P2
