### ISSUE TITLE
Pod shall not transition from terminated phase: "Failed" -> "Succeeded"

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17595] opened 2017-12-05 10:03 UTC
```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:1299
2017-12-05 09:50:41.393147976 +0000 UTC: detected deployer pod transition from terminated phase: "Failed" -> "Succeeded"
Expected
    <bool>: true
to be false
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/util.go:727
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17589/test_pull_request_origin_extended_conformance_install/3497/

/sig master
/kind test-flake
/assign mfojtik tnozicka

xref https://bugzilla.redhat.com/show_bug.cgi?id=1534492

**Comment by tnozicka** [comment] 2017-12-05 11:31
@sjenning it seems to already have https://github.com/openshift/origin/pull/17514 

I don't think your condition prevents failed->succeded https://github.com/openshift/origin/blob/21271eb4836769b48102b02dd9170219ada3d9ae/vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go#L286

There few other flakes likely caused by kubelet not respecting pod state transition diagram:
 - https://github.com/openshift/origin/issues/17581
 - https://github.com/openshift/origin/issues/17487

/assign @sjenning 
/unassign @tnozicka @mfojtik 
/priority P0

**Comment by tnozicka** [comment] 2017-12-05 11:36
(previous issue https://github.com/openshift/origin/issues/17011)

**Comment by tnozicka** [comment] 2017-12-11 16:00
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17713/test_pull_request_origin_extended_conformance_install/3886/

@sjenning any progress on this?

**Comment by sjenning** [comment] 2017-12-18 03:52
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17839/test_pull_request_origin_extended_conformance_install/4317/

**Comment by tnozicka** [comment] 2017-12-20 16:53
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17827/test_pull_request_origin_extended_conformance_install/4519/

**Comment by mfojtik** [comment] 2018-01-08 13:47
@sjenning any chance the pod team can investigate this? regardless of flakes, this might affect production deployments where the deployer pod can go from failed to success.

**Comment by tnozicka** [comment] 2018-01-11 10:16
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17773/test_pull_request_origin_extended_conformance_install/5243/

**Comment by sjenning** [comment] 2018-01-22 19:48
I'm looking into this now.  Sorry for the delay.

**Comment by sjenning** [comment] 2018-01-30 16:59
@tnozicka just wondering, have you seen this one lately?  Doesn't look like we have hit this one for a while now.  Did it disappear at the same time we bumped the disk size on the CI instances?

**Comment by tnozicka** [comment] 2018-01-31 10:58
I haven't. @ironcladlou @mfojtik got any flakes looking like this? (Those are usually different tests as the detector is asynchronous and run for every deployment test.)

Any chance that this might be related https://github.com/openshift/origin/pull/18233?

**Comment by tnozicka** [comment] 2018-02-01 16:42
likely not caused by the informers issue I pointed you to as @deads2k just saw it and the watch cache is already fixed on master

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18387/test_pull_request_origin_extended_conformance_install/6640/

**Comment by sjenning** [comment] 2018-02-01 22:28
@tnozicka still trying to get to the root cause on this https://github.com/kubernetes/kubernetes/issues/58711#issuecomment-362402686

**Comment by tnozicka** [comment] 2018-02-08 11:02
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_extended_conformance_install/7087/

**Comment by sjenning** [comment] 2018-02-12 21:39
Opened a PR upstream:
https://github.com/kubernetes/kubernetes/pull/59767

**Comment by smarterclayton** [comment] 2018-02-25 06:23
Did this make it into 3.9?  If so, still happening (below).  If not, we need to get it in before release.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18739/test_pull_request_origin_extended_conformance_install/7966/

**Comment by sjenning** [comment] 2018-02-27 15:28
It did go in about 2 weeks ago
https://github.com/openshift/origin/pull/18585

Looking into it.  If this is legitimately happening even with the check I added, I'm very confused.

**Comment by tnozicka** [comment] 2018-03-01 11:41
I don't think the requested check in apiserver is present.

To check, if I do 
```
curl -k -v -XPATCH -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/json" -H "Content-Type: application/strategic-merge-patch+json" https://172.16.20.11:8443/api/v1/namespaces/test/pods/busyapp-76589968df-xnthx/status -d '{"status": {"phase": "Failed"}}'
```
it gets overwritten back to Running.

This is a serious bug and I feel we need that enforcement in the apiserver as well as the fix.

It feels like the whole kubelet status manager ignores optimistic concurrency with resourceVersion and just does GET before updating the status no matter what resourceVersion was used for computing that status - the precondition might have changed in that case.
https://github.com/openshift/origin/blob/710998e7358752a4c79518804522f1a6cf239838/vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go#L451-L476

**Comment by sjenning** [comment] 2018-03-01 18:27
switching back to this issue

**Comment by sjenning** [comment] 2018-03-01 19:33
I swear, I'm losing it.  I totally forgot that this PR got reopened and merged upstream https://github.com/kubernetes/kubernetes/pull/54530.  I'll pick it right now.

**Closed** 2018-03-07 13:19 UTC
Labels: component/containers, kind/test-flake, priority/P0, sig/containers, sig/master
