### ISSUE TITLE
Unable to start openshift server - no locks available

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1662] opened 2015-04-09 09:54 UTC
```
[root@openshiftdev origin]# openshift start --latest-images
I0409 09:53:54.375732    2158 start_allinone.go:216] Starting an OpenShift all-in-one
I0409 09:54:02.109470    2158 start_master.go:287] Starting an OpenShift master, reachable at 0.0.0.0:8443 (etcd: [https://192.168.121.198:4001])
I0409 09:54:02.109648    2158 start_master.go:288] OpenShift master public address is https://192.168.121.198:8443
2015/04/09 09:54:02 etcdserver: datadir is valid for the 2.0.1 format
2015/04/09 09:54:02 etcdserver: name = openshift.local
2015/04/09 09:54:02 etcdserver: data dir = openshift.local.etcd
2015/04/09 09:54:02 etcdserver: member dir = openshift.local.etcd/member
2015/04/09 09:54:02 etcdserver: heartbeat = 100ms
2015/04/09 09:54:02 etcdserver: election = 1000ms
2015/04/09 09:54:02 etcdserver: snapshot count = 0
2015/04/09 09:54:02 etcdserver: advertise client URLs = https://192.168.121.198:4001
2015/04/09 09:54:02 etcdserver: initial advertise peer URLs = https://192.168.121.198:7001
2015/04/09 09:54:02 etcdserver: initial cluster = openshift.local=https://192.168.121.198:7001
2015/04/09 09:54:02 etcdserver: create wal error: no locks available
```

Seems like it has something to do with the etcd PR.

This is libvirt Vagrant box running F21 with latest master.

**Comment by mfojtik** [comment] 2015-04-09 10:03
@smarterclayton FYI

**Comment by ncdc** [comment] 2015-04-09 10:04
I've been able to. Try wiping your etcd dir perhaps, and make sure you've done at least 1 make clean?

**Comment by mfojtik** [comment] 2015-04-09 10:05
@ncdc did make clean build twice, wiped all etcd dirs after git pull.

**Comment by mfojtik** [comment] 2015-04-09 10:07
(doing vagrant destroy / up right now... that box was pretty old anyway)

**Comment by mfojtik** [comment] 2015-04-09 10:12
no, still the same error, even with the fresh new machine... 2015/04/09 10:11:02 etcdserver: create wal error: no locks available

**Comment by ncdc** [comment] 2015-04-09 10:12
What os? I'm on f21.

**Comment by mfojtik** [comment] 2015-04-09 10:14
@ncdc figured it out :-) It is NFS mount that Vagrant is doing when you use libvirt provider. I tried to start OpenShift on NFS mount and got this error. 

If I do:

```
openshift start --latest-images --etcd-dir='/tmp/openshift.local.etcd'
```

Everything works :-)

**Comment by ncdc** [comment] 2015-04-09 10:15
Great. Funnily enough, when I googled the error, nfs results showed up :-)

**Comment by mfojtik** [comment] 2015-04-09 10:16
@ncdc I feel I should document this somewhere ;-)

**Comment by smarterclayton** [comment] 2015-04-10 03:52
Can we get etcd to return a more verbose error?

**Comment by smarterclayton** [comment] 2015-04-10 03:52
Or, if they're returning the error to us, we should explicitly show it.

**Comment by mfojtik** [comment] 2015-04-10 16:14
@smarterclayton they return just

2015/04/09 09:54:02 etcdserver: create wal error: no locks available

Can we capture this error and give users some suggestions (like you're running on NFS volume, use --etcd-dir... )

**Comment by smarterclayton** [comment] 2015-05-15 18:16
This could be the ulimit problem (we also need to document that ulimit need to be higher, if that's the root cause).

**Comment by mfojtik** [comment] 2015-05-15 20:24
@smarterclayton in my case it was NFS volume (vagrant+libvirt), I am taking to do to document this.

**Comment by smarterclayton** [comment] 2015-05-19 20:27
I believe this is fixed by https://github.com/openshift/origin/pull/2317

**Closed by smarterclayton** 2015-05-19 20:27 UTC
Labels: component/master, priority/P2
