### ISSUE TITLE
Pipelines does not accept parametrised build 

### ISSUE THREAD

**Issue by mangirdaz** [openshift/origin#14369] opened 2017-05-26 12:52 UTC
If I create Pipeline from Build config and try execute This build Using Jenkins API and pass parameteres it will fail:
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    name: test2
  name: test2
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Parallel
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        // Add fancy build parameter.
        properties([
          parameters([
            string(
              defaultValue: "asd",
              description: 'Some description',
              name: 'foo'
            ),
          ])
        ])

        print foo
        if (foo == "true") {
          print "true"
        }
        else {
          print "false"
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: OHaFSFdG3E3n6TM7lkxE7hS0QQfBAQYVMH5TI1bJ
    type: GitHub
  - generic:
      secret: naBnLGoPYh2dYgmMwAyXtrRgW4VPiMxVVn7dyLY8
    type: Generic
status:
  lastVersion: 
```
output:
```
OpenShift Build pipelines/test2-3
[Pipeline] properties
WARNING: The properties step will remove all JobPropertys currently configured in this job, either from the UI or from an earlier properties step.
This includes configuration for discarding old builds, parameters, concurrent builds and build triggers.
WARNING: Removing existing job property 'This project is parameterized'
WARNING: Removing existing job property 'BuildConfigProjectProperty'
[Pipeline] echo

asd
[Pipeline] echo
false
[Pipeline] End of Pipeline
Finished: SUCCESS
```

If I create same pipeline from Jenkins UI it works just fine and accepts parameters from API and UI.

UseCase is we want to trigger Jenkins Build/Pipeline from external CI tool and pass Commit ID or Tag to be used. 

https://issues.jenkins-ci.org/browse/JENKINS-44509 

To trigger job:
curl -k -X POST https://admin-admin:asadasdsad@jenkins-pipelines.ocp.example.com/job/project/job/pipelines-openshift-jee-sample/buildWithParameters?foo=true

native pipeline code:
```groovy
 // Add fancy build parameter.
        properties([
          parameters([
            string(
              defaultValue: "asd",
              description: 'Some description',
              name: 'foo'
            ),
          ])
        ])

        print foo
        if (foo == "true") {
          print "true"
        }
        else {
          print "false"
        }
```

**Comment by mangirdaz** [comment] 2017-05-26 13:03
These warnings are not there if I run it from native pipeline in Jenkins. Our integration removes parametrisation :/

**Comment by mangirdaz** [comment] 2017-05-26 14:22
Sorry for my possible misunderstanding but things @bparees mentioned in trello is about story to cover "updating BC and reflecting changes in Jenkins".

What I'm trying to do is to trigger Jenkins pipeline build with the parameter from outside.
BC would have:
```
  source:
      dockerfile: |
        FROM registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift
        RUN sed -i 's/shared.loader=/shared.loader=\/mnt\/config/,\/mnt\/newrelic/' /opt/webserver/conf/catalina.properties
        RUN rm -rf /deployments/*; curl $ARTIFACT_URL --output /deployments/ROOT.war
      type: Dockerfile
```
Where ARTIFACT_URL is passed from other CI directly to Jenkins API to trigger pipeline. 

I tried to do `oc start-build api -e ARTIFACT_URL=asdasd `
But in this scenario build is started in OCP, but Jenkins pipeline is not aware of its start.

Am I doing something wrong or missing something?

**Comment by gabemontero** [comment] 2017-05-26 14:23
Need to dig more, but this might be a limitation due to the fact that the sync plugin uses the programmatic APIs of the pipeline plugins to create jobs off of the BuildConfig.  Notice that property the sync plugin actually uses, `BuildConfigProjectProperty`, is also removed.

Those messages about removing the properties are coming from the jenkins/pipeline code, not the openshift sync plugin.

I vaguely remember for something about lifting restriction on adding properties in this space, back when we were mapping env vars to job params, via config changes you could make to pipelines, but they might have had security ramifications.

I'm also wondering if the use of our env var support, as @bparees mentioned 

I'll report back when I find out some more.

**Comment by mangirdaz** [comment] 2017-05-26 14:41
> @mangirdaz - to use the new env feature, you need the right version of OCP, not just the sync plugin. What version of OCP are you running?

3.5.5.x
But I still dont get it if this new feature will help me :/

**Comment by gabemontero** [comment] 2017-05-26 15:06
No you need to be on 3.6 to get the new feature.

**Comment by gabemontero** [comment] 2017-05-26 15:07
So in the meantime, let me see if I can rediscover the particulars around parameters and the jenkins/pipeline programmatic APIs and report back.

**Comment by mangirdaz** [comment] 2017-05-26 15:08
Thanks, if something mj on rocket or m.j@ r e d h a t .com if you need more details :)

**Comment by gabemontero** [comment] 2017-05-29 15:33
OK, have been able to do some research:
1) based on my interpretation of https://issues.jenkins-ci.org/browse/JENKINS-37005 this appears to be a known shortcoming with the properties step in non-multibranch
2) For me at least, manually creating a pipeline with:

```
          node() {
              properties([
                 parameters([
                    string(
                       defaultValue: "asd",
                       description: 'Some description',
                       name: 'foo'
                    ),
                 ])
              ])

              print foo
              if (foo == "true") {
                  print "true"
              } else {
                  print "false"
              }
          }

```

results in the same error (i.e. no Pipeline build config).  It is only when I removed 

```
              properties([
                 parameters([
                    string(
                       defaultValue: "asd",
                       description: 'Some description',
                       name: 'foo'
                    ),
                 ])
              ])

```

that I can run the job manually.  @mangirdaz - is that what you did when you say you could run the job manually?   Or did you have that stanza in, but was running in a Jenkins instance where the openshift sync plugin was *NOT* installed ?

3) I confirmed the warning messages are happening during the actual running of the job, and outside of the scope of whatever the sync plugin could do to work around.

Next steps:
a) answer on my question to @mangirdaz - the answer could change these next steps
b) based on those answers, craft some appropriate doc update on using `parameters` with pipeline strategy and/or sync plugin
c) long term @mangirdaz - you'll need to wait for 3.6 to become available so you can use the env var feature as previously discussed 

I'll close this out once we progress through those steps.

**Comment by mangirdaz** [comment] 2017-05-29 20:18
Hey,

I might be not clear here. My goal is to execute parametrised build, wich is in Openshift UI. Try creating this:
```
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    name: test2
  name: test2
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Parallel
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        // Add fancy build parameter.
        properties([
          parameters([
            string(
              defaultValue: "asd",
              description: 'Some description',
              name: 'foo'
            ),
          ])
        ])

        print foo
        if (foo == "true") {
          print "true"
        }
        else {
          print "false"
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: OHaFSFdG3E3n6TM7lkxE7hS0QQfBAQYVMH5TI1bJ
    type: GitHub
  - generic:
      secret: naBnLGoPYh2dYgmMwAyXtrRgW4VPiMxVVn7dyLY8
    type: Generic
status:
  lastVersion: 
```

which will generate jenkins job with parametrized build.
So if I execute this particular job, generated by OCP plugin:
`curl -k -X POST https://admin-admin:asadasdsad@jenkins-pipelines.ocp.example.com/job/project/job/pipelines-openshift-jee-sample/buildWithParameters?foo=true 
` value is not read by the pipeline itself and parameters is being ignored. 

If I recreate same pipeline from Jenkins UI (in this way it does not show in OCP UI) same curl works, and value is read. 

The conclusion is that when build is created using OCP integration it ignores parameters (either via API or jenkis UI).

If things is still not clear, im happy to jump on 10 min bluejeans session to show what Im speaking about.

**Comment by gabemontero** [comment] 2017-05-29 23:13
Yes that is what I did.  I created a BC with Jenkinsfile content.  I only pasted  the Jenkinsfile content in https://github.com/openshift/origin/issues/14369#issuecomment-304687882 for brevity.

And I'm telling you that when I recreate the the same pipeline from the Jenkins UI, it doen't work until I remove the section I noted.

In the end, that point may just be a minor detail.  But to confirm, answer this question, the job you created from the Jenkins UI ... is it the same Jenkins instance that hosted the job you created from OCP?

Again, I think regardless, per the Jenkins issue I noted (https://issues.jenkins-ci.org/browse/JENKINS-37005), and what my investigation has uncovered, there is a general incompatible situation between the sync plugin creating jobs via the Java APIs and the `properties` / `parameters` pipeline steps.  And again, when 3.6 is available, you should have an alternative approach via the env var support to do what you want.

**Comment by mangirdaz** [comment] 2017-05-30 09:16
Job Woks after second execution. When you create job, it does not work. When you run it the second time it is synced to the jenkins and it "becomes" parametrized build. If you create same job via UI and BC after first run, jenkins sees them as same. But they behave differently. 
Which timezone are you in? Lets jump on BJ as I think we speaking about different problems here :)

**Comment by rhcrreeves** [comment] 2017-05-30 11:15
Hi @gabemontero, I just ran the test on my 3.5 lab and I am seeing that:
1) When created through the openshift buildconfig, the job does not correctly utilise the parameters (i.e ignores them) either through the jenkins interface, or through triggering an openshift pipeline run.
2) When created through the jenkins interface directly as a new pipeline, the code @mangirdaz provided works for me and provides the correct output. I did have to specify that the build is parameterised, and created the 'foo' parameter with a default value; but when I ran it it did change the parameter and outputted the expected response.

My expectation is that when we create a job through the openshift pipeline feature OR through the jenkins UI, the behaviour would be the same. Currently it is not.

My jenkins instance is the latest Red Hat official jenkins image, and updated to the latest set of plugins.

**Comment by gabemontero** [comment] 2017-05-30 18:24
OK, a multi-part response:

1) the comment https://github.com/openshift/origin/issues/14369#issuecomment-304821307 from @mangirdaz was helpful, noting things work from the second run forward;

However I still see different results in that the second run *SUCCEEDS* for both a) the job that I create manually in Jenkins, and b) the pipeline strategy build config.  I am seeing *NO* difference in behavior in the both the first and second runs between the manually created job and the pipeline strategy BC.

Here is by full BC:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2017-05-30T18:01:13Z
    labels:
      app: jenkins-pipeline-example
      name: sample-pipeline-withprops
      template: application-template-sample-pipeline
    name: sample-pipeline-withprops
    namespace: myproject
    resourceVersion: "1397"
    selfLink: /oapi/v1/namespaces/myproject/buildconfigs/sample-pipeline-withprops
    uid: f82eda4d-4561-11e7-a703-68f7287398a7
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: FOO1
          value: BAR1
        jenkinsfile: |-
          node() {
              properties([
                 parameters([
                    string(
                       defaultValue: "asd",
                       description: 'Some description',
                       name: 'foo'
                    ),
                 ])
              ])

              print foo
              if (foo == "true") {
                  print "true"
              } else {
                  print "false"
              }
          }
      type: JenkinsPipeline
    triggers: []
  status:
    lastVersion: 2
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
gmontero ~/go/src/github.com/openshift/origin/test/extended/testdata  (master)$ 
```

Here are my build results per `oc get builds` for both the first and second runs of `oc start-build sample-pipeline-withprops`:

```
gmontero ~/go/src/github.com/openshift/origin/test/extended/testdata  (master)$ oc get builds 
NAME                          TYPE              FROM      STATUS     STARTED         DURATION
sample-pipeline-withprops-1   JenkinsPipeline             Failed     2 minutes ago   
sample-pipeline-withprops-2   JenkinsPipeline             Complete   2 minutes ago   
gmontero ~/go/src/github.com/openshift/origin/test/extended/testdata  (master)$ 
```

Here are the Jenkins console logs from the first, failed run using the bc job:
```
OpenShift Build myproject/sample-pipeline-withprops-1
[Pipeline] node
Running on master in /var/lib/jenkins/jobs/myproject-sample-pipeline-withprops/workspace
[Pipeline] {
[Pipeline] properties
WARNING: The properties step will remove all JobPropertys currently configured in this job, either from the UI or from an earlier properties step.
This includes configuration for discarding old builds, parameters, concurrent builds and build triggers.
WARNING: Removing existing job property 'BuildConfigProjectProperty'
WARNING: Removing existing job property 'Do not allow concurrent builds'
WARNING: Removing existing job property 'This project is parameterized'
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: foo for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:224)
	at org.kohsuke.groovy.sandbox.impl.Checker$4.call(Checker.java:241)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:238)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:221)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:28)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:12)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:74)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:165)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

Here is the successful, second run:

```
OpenShift Build myproject/sample-pipeline-withprops-2
[Pipeline] node
Running on master in /var/lib/jenkins/jobs/myproject-sample-pipeline-withprops/workspace
[Pipeline] {
[Pipeline] properties
WARNING: The properties step will remove all JobPropertys currently configured in this job, either from the UI or from an earlier properties step.
This includes configuration for discarding old builds, parameters, concurrent builds and build triggers.
WARNING: Removing existing job property 'BuildConfigProjectProperty'
WARNING: Removing existing job property 'Do not allow concurrent builds'
WARNING: Removing existing job property 'This project is parameterized'
[Pipeline] echo
asd
[Pipeline] echo
false
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

@mangirdaz - what release of the openshift-sync plugin is used in your tests?  I am using 0.1.14.

Also, this is a bit of a reach, but what happens if you try to wrapper your pipeline script with `node() { ... }` ?

2) @rhcrreeves - yes, I understand the expectations; however, as I've noted in some of the earlier comments, and specifically in reference to https://issues.jenkins-ci.org/browse/JENKINS-37005, the `properties` and `parameters` steps from the jenkins pipeline plugin(s) are doing some processing outside the scope of what we can control from the openshift sync plugin.  That coupled with the consistent behavior I at least am seeing with the second job succeeding, I think this is how it will be until the jenkins pipeline stuff changes.  And to also reiterate the prior discussion, the env var support coming in 3.6 should provide a cleaner alternative (no failed run the first time).

**Comment by mangirdaz** [comment] 2017-06-02 10:23
@gabemontero same version.

If you have still pipeline setup, please execute it with `parameters true` As per pipeline logic it should print you "true" and not false. 
This there the issue is. The pipeline runs, but IF it created via openshift it ignores all parameters and uses defaults. 
```
 print foo
              if (foo == "true") {
                  print "true"
              } else {
                  print "false"
              }
```

Im available today on BJ if you want. drop me an email to my mail m.j [et] r e d h a t.com for time

**Comment by gabemontero** [comment] 2017-06-02 18:40
OK!!!!!! With that final piece of elaboration in the latest explanation, I now understand what you were trying to convey, and I see the differing behavior :-)

Starting to debug / diagnose ... I'll report back with findings, where either a) the pipeline plugin APIs allow, the sync plugin to work around this, or b) the reason why we can't work around.

**Comment by mangirdaz** [comment] 2017-06-02 18:49
:) But looks like we have 2 issues here. 
On with sync plugin syncing stuff only after the first run. when you copy stuff in and it's not there in the beginning. 
And second, that parameter are being ignored in OCP pipelines.

**Comment by gabemontero** [comment] 2017-06-02 18:55
I'll know for sure after I determine exactly what is going on, but the first issue is outside sync plugin.  It is a pipeline plugin issue.  The sync plugin should not be involved in the jobs manually created, and we see the same need for a second run there.

But I'll cross reference with the job manually created, not from the pipeline build strategy.  I also plan on constructing a local openshift jenkins image *WITHOUT* the sync plugin to prove that one way or the other as well.

**Comment by gabemontero** [comment] 2017-06-05 20:39
hey @mangirdaz - OK, I have a pre-release fix for you to try if you like.  I'll attach a zip of the plugin hpi file here.
[sync.zip](https://github.com/openshift/origin/files/1053138/sync.zip)


If there are any issues, there is a fair amount of debug getting dump to the jenkins system log.  Please capture and provide that and we'll go from there.

Also, I *CONFIRMED* that the need to run the job twice, where the first run fails but adds to parameters to the job def, is independent of openshift pipeline build strategy and any of our plugins.  I used a jenkins image with none of our plugins installed and the same behavior occurs.

**Closed** 2017-06-06 19:08 UTC
Labels: component/build, kind/question, priority/P2

**Comment by mangirdaz** [comment] 2017-06-10 20:22
Sorry, got dragged to on-site eng. checking now :)

**Comment by gabemontero** [comment] 2017-06-11 23:16
thanks for the confirmation @mangirdaz 

Also note v0.1.18, which contains this fix, of the sync plugin is now available, along with the docker.io/openshift/jenkins-2-centos7:latest  image being updated with v0.1.18.
