### ISSUE TITLE
[Feature:DeploymentConfig] deploymentconfigs keep the deployer pod invariant valid [Conformance] should deal with cancellation of running deployment [Suite:openshift/conformance/parallel]

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#18047] opened 2018-01-10 15:09 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17773/test_pull_request_origin_extended_conformance_install/5243/

```
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[Feature\:DeploymentConfig\]\sdeploymentconfigs\skeep\sthe\sdeployer\spod\sinvariant\svalid\s\[Conformance\]\sshould\sdeal\swith\scancellation\sof\srunning\sdeployment\s\[Suite\:openshift\/conformance\/parallel\]$'

/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:1162
2018-01-10 14:05:35.787721849 +0000 UTC m=+550.720035065: detected deployer pod transition from terminated phase: "Failed" -> "Succeeded"
Expected
    <bool>: true
to be false
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/util.go:725
				
```

**Comment by tnozicka** [comment] 2018-01-11 10:15
dupe of https://github.com/openshift/origin/issues/17595

**Closed by tnozicka** 2018-01-11 10:15 UTC
Labels: kind/test-flake
