### ISSUE TITLE
[Feature:Builds] forcePull should affect pulling builder images ForcePull test case execution docker [Suite:openshift/conformance/parallel] 

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17829] opened 2017-12-15 15:31 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17827/test_pull_request_origin_extended_conformance_gce/13038/

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:78
Expected error:
    <*util.ExitError | 0xc421426030>: {
        Cmd: "oc adm --config=/tmp/cluster-admin.kubeconfig --namespace=extended-test-forcepull-mn9qf-ghxgl policy remove-cluster-role-from-user system:build-strategy-custom extended-test-forcepull-mn9qf-ghxgl-user",
        StdErr: "Error from server (Conflict): Operation cannot be fulfilled on clusterrolebindings.authorization.openshift.io \"system:build-strategy-custom\": the object has been modified; please apply your changes to the latest version and try again",
        ExitError: {
            ProcessState: {
                pid: 18838,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 271888},
                    Stime: {Sec: 0, Usec: 24815},
                    Maxrss: 60124,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 14556,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 1778,
                    Nivcsw: 21,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/forcepull.go:90
```

**Comment by tnozicka** [comment] 2017-12-15 15:59
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17827/test_pull_request_origin_extended_conformance_gce/13038/

**Comment by bparees** [comment] 2017-12-15 16:01
dupe of https://github.com/openshift/origin/issues/17596

**Closed by bparees** 2017-12-15 16:01 UTC
Labels: component/build, kind/test-flake, priority/P1
