### ISSUE TITLE
oc start-build --wait --follow handles a failed build incorrectly

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9452] opened 2016-06-21 02:33 UTC
If you use --wait and the build actually fails in between the client retrying waiting for the build/logs, oc client will error out telling you cannot wait for a failed build.

What should happen is the normal behavior, the build logs should be printed (if any), and --wait should exit with an appropriate failed return code, as it does for a normal build --wait flow.

**Comment by smarterclayton** [comment] 2016-06-21 02:46
We also have the problem that `oc logs bc/foo`, if invoked immediately after a build config is created, will fail because the build does not exist yet.  If we start logging a build config within X seconds of its creation, we should wait for a while for a build to exist (under the principal that the user either expects the build to start, or they are scripting).  If we want to get clever, we can check the trigger state of the build config.

**Comment by bparees** [comment] 2016-08-26 15:26
@oatmealraisin i think the only way you'll be able to recreate this easily is to modify the --wait retry logic to do a sleep before it retries to increase the window.  The scenario is, I think:

1) oc client starts a wait on a build
2) the wait times out
3) the oc client stops waiting (because of the timeout and prepares to retry the wait)
4) the build starts+fails
5) the oc client starts its next attempt at waiting, but the build is already failed and the user is told you can't wait on a failed(complete) build.

What should happen in (5) is that the client should recognize the build is complete and exit w/ an appropriate return code corresponding to the build status.  And if "--follow" was specified it should dump the build logs as well.

**Comment by bparees** [comment] 2016-11-17 16:49
@oatmealraisin you were asking what the behavior should be, i think it's summarized in the description of the issue: "What should happen is the normal behavior, the build logs should be printed (if any), and --wait should exit with an appropriate failed return code, as it does for a normal build --wait flow."

**Comment by oatmealraisin** [comment] 2016-11-17 21:36
@bparees I don't think there's an issue.  I've put sleeps in the follow logic + controller logic to try and reproduce this, but the most I've gotten is `error: The build myproject/ruby-hello-world-4 status is "Failed"`. I can still get logs to be streamed if the pod is created. Perhaps I'm missing something?

**Comment by bparees** [comment] 2016-11-17 21:37
does "oc start-build --wait --follow" print out the logs even if the build failed in the middle of a retry?

**Comment by oatmealraisin** [comment] 2016-11-17 21:55
Should the --wait affect it? I've been using --follow and the logs get streamed as long as the pod gets created [here](https://github.com/openshift/origin/blob/master/pkg/build/controller/controller.go#L202)

This is after a 8 second sleep in the follow loop and a 10 second sleep before the above link

**Comment by bparees** [comment] 2016-11-17 21:57
yes it matters. from my original description, "If you use --wait and the build actually fails in between the client retrying waiting for the build/logs, oc client will error out telling you cannot wait for a failed build."

specifically the incorrect behavior results from the fact that we are trying to "wait" and not just "follow", but you can't "wait" on a failed build.

**Comment by oatmealraisin** [comment] 2016-11-18 15:53
Over scrum we decided that this issue isn't reproducible currently, closing

**Closed by oatmealraisin** 2016-11-18 15:53 UTC
Labels: component/build, kind/bug, priority/P3
