### ISSUE TITLE
S2I push logs still has info message in v1.1

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6280] opened 2015-12-12 05:54 UTC
Not sure if this was fixed since v1.1:

```
--> Cleaning up unused ruby gems ...
I1212 05:54:04.546227       1 sti.go:213] Using provided push secret for pushing 172.30.168.160:5000/demo/ruby-hello-world:latest image
I1212 05:54:04.546313       1 sti.go:217] Pushing 172.30.168.160:5000/demo/ruby-hello-world:latest image ...
I1212 05:54:18.753443       1 sti.go:233] Successfully pushed 172.30.168.160:5000/demo/ruby-hello-world:latest
```

Should have no prefix.

**Comment by kargakis** [comment] 2015-12-13 21:44
Dupe of https://github.com/openshift/origin/issues/5788

**Closed** 2015-12-14 14:19 UTC
