### ISSUE TITLE
Deployments don't work with oc logs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12789] opened 2017-02-03 03:59 UTC
```
$ oc logs deployment/prometheus
error: cannot get the logs from extensions/__internal, Kind=Deployment
```

Should work.

**Comment by pweil-** [comment] 2017-02-07 18:57
removing from blocker list as this is an upstream dependency that is not a regression.

**Comment by soltysh** [comment] 2017-03-02 13:48
I'm setting this for 1.6 milestone since this should be fixed with the next rebase. I'm also setting this to P1 to track it during bug burdown.

**Comment by soltysh** [comment] 2017-06-08 14:31
This is now solved.

**Closed by soltysh** 2017-06-08 14:31 UTC
Labels: component/cli, component/deployments, component/kubernetes, kind/bug, priority/P1
