### ISSUE TITLE
when using scheduler and serviceAffinity, unexpected node placements occur

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1727] opened 2015-04-14 14:56 UTC
Given the following scheduler configuration:

```
{
  "predicates" : [
    {"name" : "PodFitsResources"},
    {"name" : "PodFitsPorts"},
    {"name" : "NoDiskConflict"},
    {"name" : "Region", "argument" : {"serviceAffinity" : { "label" : "region"}}}
  ],"priorities" : [
    {"name" : "LeastRequestedPriority", "weight" : 1},
    {"name" : "ServiceSpreadingPriority", "weight" : 1},
    {"name" : "Zone", "weight" : 1, "argument" : {"serviceAntiAffinity" : { "label" : "zone" }}}
  ]
}
```

When creating a pod with a `NodeSelector` requesting a specific region, pods are placed in the wrong region.

They also fail to start, and I'm not sure if that's related or unrelated.

@abhgupta is aware, this issue is for him.

**Comment by sosiouxme** [comment] 2015-04-15 14:52
The scheduler seems to have a bit of split-brain. It will ignore the region predicate when scheduling and put the pod on whatever node; but that pod will immediately be rejected at the node because the predicate is not matched. I end up with a number of failed placements until it actually lands on a satisfactory node.

I deployed the router and updated it to specify `"nodeSelector": { "region": "infra"}`. Nodes have region tags as below.

```
# osc get nodes
NAME           LABELS        STATUS
172.16.4.164   Schedulable   region=infra,zone=NA       Ready
172.16.4.167   Schedulable   region=primary,zone=east   Ready
172.16.4.168   Schedulable   region=primary,zone=west   Ready
# osc get pods
POD                       IP         CONTAINER(S)   IMAGE(S)                                                                                    HOST                        LABELS                                                                                  STATUS    CREATED
router-2-6t0yf                       router         docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-haproxy-router:v0.4.3.2    172.16.4.167/               deployment=router-2,deploymentconfig=router,router=router                               Failed    14 seconds
router-2-bd8ro                       router         docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-haproxy-router:v0.4.3.2    172.16.4.168/               deployment=router-2,deploymentconfig=router,router=router                               Failed    15 seconds
router-2-y9tpa            10.1.0.5   router         docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-haproxy-router:v0.4.3.2    172.16.4.164/172.16.4.164   deployment=router-2,deploymentconfig=router,router=router                               Running   10 seconds

master logs:

Apr 15 10:34:47 172.16.4.164 openshift-master[10516]: E0415 10:34:47.243644   10516 endpoints_controller.go:93] Failed to find an IP for pod default/router-2-6t0yf
Apr 15 10:34:47 172.16.4.164 openshift-master[10516]: E0415 10:34:47.243680   10516 endpoints_controller.go:93] Failed to find an IP for pod default/router-2-bd8ro
Apr 15 10:34:47 172.16.4.164 openshift-master[10516]: I0415 10:34:47.424638   10516 factory.go:200] About to try and schedule pod router-2-y9tpa
Apr 15 10:34:47 172.16.4.164 openshift-master[10516]: I0415 10:34:47.424660   10516 scheduler.go:106] Attempting to schedule: &{{ } {router-2-y9tpa router-2- default /api/v1beta3/namespaces/default/pods/router-2
[...]
} {OPENSHIFT_MASTER https://172.16.4.164:8443}] {map[] map[]} [] 0xc20afdf5c0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Always ClusterFirst map[region:infra]  false} {Pending []    []}}

example node logs:
Apr 15 10:34:46 172.16.4.167 openshift-node[5263]: I0415 10:34:46.831953    5263 config.go:244] Setting pods for source api : {[{{ } {router-2-6t0yf router-2- default /api/v1beta3/namespaces/default/pods/router-2-6t0yf 8ed515d5-e37c-11e4-85ea-fa163ec8dc60 19212 2015-04-15 10:34:43 -0400 EDT <nil> map[deployment:router-2 deploymentconfig:router router:router] map[deployment:router-2 deploymentConfig:router deploymentVersion:2]} {[] [{router docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-haproxy-router:v0.4.3.2 [] []  [{ 80 80 TCP } { 443 443 TCP }] [{OPENSHIFT_CA_DATA -----BEGIN CERTIFICATE-----
[...]
} {OPENSHIFT_MASTER https://172.16.4.164:8443}] {map[] map[]} [] 0xc2084e8690 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Always ClusterFirst map[region:infra] 172.16.4.167 false} {Failed [] Pod cannot be started due to node selector mismatch   []}}] 0 api}

```

**Comment by abhgupta** [comment] 2015-04-15 23:27
I ran my own tests on pods and replication controllers and this seems to be working fine, at least now. Also, I checked with Clayton and it seems that v1beta3 is the only version that supports  `NodeSelector`. You can try the rc below to test out the scheduler.
```
{
   "kind":"ReplicationController",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"frontend",
      "labels":{
         "name":"frontend"
      }
   },
   "spec":{
      "replicas":2,
      "selector":{
         "name":"frontend"
      },
      "template":{
         "metadata":{
            "labels":{
               "name":"frontend"
            }
         },
         "spec":{
            "containers":[
               {
                  "name":"hello-openshift",
                  "image":"openshift/hello-openshift"
               }
            ],
            "nodeSelector" : {"zone" : "z2"}
         }
      }
   }
}
```

**Comment by sosiouxme** [comment] 2015-04-16 13:02
@abhgupta have you tried the example of modifying router dc? At least in my example the json came out wtih `"apiVersion": "v1beta1"` so maybe that's the problem (I fed it back in with just the labels inserted). Although that doesn't really explain why (per my example above) the scheduler initially ignored the pod nodeSelector and then properly rejected pods according to the nodeSelector *after* they were placed.

We can try with more recent builds... if I'm not mistaken, we're moving to default v1beta3 API for v0.5 if not before?

**Comment by sosiouxme** [comment] 2015-04-16 16:06
@abhgupta just tried the latest build, scheduling a pod as you said works great. The problem I'm having now is that if i just patch the podTemplate in a dc to add a nodeSelector, I still get the above behavior. I even tried changing the "version" in the podTemplate manifest to "v1beta3" from "v1beta2" and it was the same.

If you want to schedule a router to a specific region/zone, how do you do that?

**Comment by abhgupta** [comment] 2015-04-16 17:50
@sosiouxme the scheduler ignored it because they weren't (somehow) present  in the pod when  it checked. However, the error was thrown by the kubelet when it made the exact same check. I am a bit lost here, but its definitely an api version issue and the client api version (scheduler/master vs the kubelet) is perhaps the issue.

**Comment by sosiouxme** [comment] 2015-04-16 18:25
@abhgupta my uninformed hypothesis was that maybe when it's coming from a DC, the scheduler examines it with v1beta2 protocol and doesn't see the nodeSelector; then when the pod is actually scheduled for a node that checks in, it's created with v1beta3 protocol and the nodeSelector appears. Mismatch between pre-create and post-create. But I dunno. Maybe @smarterclayton or @derekwaynecarr can shed some light?

Pretty much everything is going to be deployed via DC, not directly as RCs or pods, so... this kind of needs to work; we were hoping for beta3 :)

**Comment by abhgupta** [comment] 2015-04-16 19:41
Apparently, NodeSelector doesn't work well for API versions prior to v1beta3. The router is created from the deployment config and currently we have v1beta1 being specified for the replication controller.
```
ControllerTemplate v1beta1.ReplicationControllerState
```
We need to enable v1beta2 for deployment related APIs and use v1beta3 for any K8s resources that they refer. The bulk of this work has already been done by @smarterclayton and I should be able to get to this (for deployment APIs) by tomorrow.

Refer https://github.com/openshift/origin/pull/1694

**Comment by brenton** [comment] 2015-04-16 19:55
@abhgupta, Thanks for the update.  We'll wait on branch until tomorrow then.

**Comment by abhgupta** [comment] 2015-04-16 19:58
@sosiouxme the pod is already created when it comes to the scheduler. The pod binding is also not a separate resource any more (that might have explained this). Either ways, we'll get v1beta2 enabled for deployments and hopefully by tomorrow this issue can be put to rest.

**Comment by smarterclayton** [comment] 2015-04-16 21:10
v1beta2 is not going to be able to land for beta3.

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-04-16 21:11
If you need this behavior it would be better to create an UPSTREAM patch and add the fields so they can round trip.

----- Original Message -----

**Comment by abhgupta** [comment] 2015-04-17 01:19
@smarterclayton @sosiouxme Magically, everything works perfectly with the latest Origin code. Not sure what fixed it, but now the NodeSelector is preserved from dc --> rc --> pod.

Same for HostNetwork attribute that @ramr needed.

**Comment by sosiouxme** [comment] 2015-04-17 12:50
I'll verify and close the issue once we get a new build.

**Comment by brenton** [comment] 2015-04-17 13:47
Incoming.  The puddle has been built and the images are building now.

**Comment by sosiouxme** [comment] 2015-04-17 17:13
Maybe this was user error.

If we change above:

`    {"name" : "Region", "argument" : {"serviceAffinity" : { "label" : "region"}}}`

to:

`    {"name" : "RegionAffinity", "argument" : {"serviceAffinity" : {"labels" : ["region"]}}}`

... then it seems to work. Apparently `serviceAffinity` only takes lists of labels. Incidentally, with the incorrect config, a pod with `"nodeSelector": { "region":"infra" }` would leave failed pods deployed everywhere (in previous builds it would fail everywhere except the intended target).

**Comment by abhgupta** [comment] 2015-04-17 17:34
@sosiouxme I have it on my list to review the scheduler section of the beta3 training material today.

**Comment by thoraxe** [comment] 2015-04-17 17:35
So, it's partially user error on my behalf.

Take a look at:
https://github.com/openshift/openshift-docs/blob/9e156209e9fee63af6bacbf2d214fe404bf55497/dev_guide/scheduler.adoc

I assumed that a non-array "label" and an array "labels" were somehow interchangeable. EG if you had only one you said "label" with a non-array and it all just magically figured it out.

So @sosiouxme were you able to verify that the training material works with your fix?

**Comment by sosiouxme** [comment] 2015-04-17 18:17
@thoraxe the training materials don't mention *doing* anything with the regions, so I did my own hacking up of the router and registry DC json to test. That's all I did so I didn't check if anything else breaks with the scheduler config in there.

**Comment by sosiouxme** [comment] 2015-04-17 23:13
@thoraxe I know you seemed to have trouble getting this to work, and I don't know why. What I do know is if you use the incorrect (but correct-*looking*) config, you get this very confusing and unintended behavior with the failed pod placements. While I think the actual intent of getting regions and zones working for the router is fulfilled, I think it makes sense to keep this issue open (or convert to a card) to reflect that if you get something slightly wrong, there's no real validation to tell you that you made a typo or whatever as long as it's valid JSON and the only feedback you get is that the pod fails upon placement.

**Comment by smarterclayton** [comment] 2015-04-17 23:21
We already have an issue for that - link this in the other issue and close this.

It's not getting fixed in 3.0 though, too hard.

**Comment by thoraxe** [comment] 2015-04-18 11:05
Even with @sosiouxme fix it did not work for me. @abhgupta verified and said he is working on it. 

I updated the router DC and I got two pods. One immediately failed and the other remained in pending state with failure to schedule errors on the back end. 

This still seems blocked.

**Comment by abhgupta** [comment] 2015-04-20 17:36
@sosiouxme @thoraxe @smarterclayton I seem to have figured this one out and its not a scheduler issue. The scheduler correctly reads the NodeSelector from the Pod and schedules the pod on the correct node. However, the Kubelet seems to disagree as it sees a mismatch of the node labels with the pod NodeSelector, even though the kubelet uses the same predicate function. 

The reason is the caching of the node information in the kubelet. To set up the node labels, I modified the node (openshift kubectl label ...). However, the cached node information that the kubelet holds does not seem to get updated (even though a watch is configured) and hence the kubelet sees a mismatch. When I restarted the openshift-node service, the kubelet fetched the node info again and was able to correctly launch the pod.

We need to fix the node watch to ensure that the kubelet always has the latest node info. This is something that needs to go upstream or require an UPSTREAM patch. 

Workaround: During install, set the node labels appropriately and restart the openshift-node service before creating any pods.

**Comment by sosiouxme** [comment] 2015-04-20 18:15
That would explain it; I didn't deploy any pods before editing the node labels, and things worked fine.

**Comment by brenton** [comment] 2015-04-20 18:41
I'm OK with restarting the nodes after setting the labels in beta3.  I tried it and it worked for me.  I was able to move pods where I wanted them to land.

@thoraxe, I updated my labels with `osc update` FWIW.

**Comment by abhgupta** [comment] 2015-04-23 22:41
I verified that this is an issue only with Origin and actually works as expected in K8s.

**Comment by smarterclayton** [comment] 2015-04-24 16:45
Work around in place , will be fixed by next rebase.

**Closed by smarterclayton** 2015-04-24 16:45 UTC
Labels: bug
