### ISSUE TITLE
oc describe componentstatuses: no description has been implemented

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#8278] opened 2016-03-29 15:33 UTC
##### Version
oc v1.1.4-322-gb4d216e-dirty
openshift v1.1.4-322-gb4d216e-dirty
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
```console
$ oc describe componentstatuses
```
##### Current Result
```
no description has been implemented for "ComponentStatus"
no description has been implemented for "ComponentStatus"
no description has been implemented for "ComponentStatus"
```

##### Expected Result
Describer should be implemented OR `oc describe` shouldn't list `componentstatuses` as one of the possible options.

**Comment by liggitt** [comment] 2016-03-29 15:34
dupe of https://github.com/openshift/origin/issues/3667

**Closed by liggitt** 2016-03-29 15:34 UTC
