### ISSUE TITLE
Failure provisioning cluster on GCE for extended conformance test

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#14603] opened 2017-06-12 20:40 UTC
Provisioning a cluster for an extended conformance test failed with:

```
TASK [openshift-registry : Deploy latest configuration of registry DC] *********
Monday 12 June 2017  19:11:45 +0000 (0:00:00.510)       0:17:51.852 *********** 
fatal: [ci-prtest-5a37c28-3041-ig-m-w9dm]: FAILED! => {
    "changed": true,
    "cmd": ["oc", "deploy", "docker-registry", "--latest"], 
    "delta": "0:00:00.737551",
    "end": "2017-06-12 15:11:46.602460",
    "failed": true,
    "rc": 1,
    "start": "2017-06-12 15:11:45.864909",
    "stderr_lines": [
        "Flag --latest has been deprecated, use 'oc rollout latest' instead",
        "error: #1 is already in progress (Running).",
        "Optionally, you can cancel this deployment using 'oc rollout cancel dc/docker-registry'."
    ],
    "stdout": ""
}
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/3041/

**Comment by csrwng** [comment] 2017-06-12 20:41
@stevekuznetsov fyi

**Comment by sdodson** [comment] 2017-06-13 13:12
dupe of #14597

**Closed by sdodson** 2017-06-13 13:12 UTC
Labels: area/tests, component/install, kind/test-flake, priority/P1
