### ISSUE TITLE
Extended flake `manifest unknown` when trying to pull base image for build

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8596] opened 2016-04-22 02:25 UTC
In "Extended.[builds][pullsecret][Conformance] docker build using a pull secret Building from a template should create a docker build that pulls using a secret run it"

https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended/lastCompletedBuild/testReport/(root)/Extended/_builds__pullsecret__Conformance__docker_build_using_a_pull_secret_Building_from_a_template_should_create_a_docker_build_that_pulls_using_a_secret_run_it/

```
data/src/github.com/openshift/origin/test/extended/builds/docker_pullsecret.go:61
Apr 21 17:28:36.457: build failed: Command "build-logs" is deprecated, use "oc logs build/<build-name>" instead.
I0421 21:28:30.126818       1 builder.go:46] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"docker-build-pull-1","namespace":"extended-test-docker-build-pullsecret-8vffw-nczyd","selfLink":"/oapi/v1/namespaces/extended-test-docker-build-pullsecret-8vffw-nczyd/builds/docker-build-pull-1","uid":"fb23c7ab-0807-11e6-8f0c-0ec1c4277789","resourceVersion":"4199","creationTimestamp":"2016-04-21T21:28:25Z","labels":{"buildconfig":"docker-build-pull","name":"docker-build-pull","openshift.io/build-config.name":"docker-build-pull"},"annotations":{"openshift.io/build.number":"1"}},"spec":{"serviceAccount":"builder","source":{"type":"Dockerfile","dockerfile":"FROM centos:7","secrets":null},"strategy":{"type":"Docker","dockerStrategy":{"from":{"kind":"DockerImage","name":"172.30.14.166:5000/extended-test-docker-build-pullsecret-8vffw-nczyd/image1@sha256:478607969ab93bfa1f9a74e4e25579dda1cabe206ff6f5aa0da88a9b51b85d4a"},"pullSecret":{"name":"builder-dockercfg-i28qq"},"forcePull":true}},"output":{},"resources":{},"postCommit":{}},"status":{"phase":"New","config":{"kind":"BuildConfig","namespace":"extended-test-docker-build-pullsecret-8vffw-nczyd","name":"docker-build-pull"}}}
 
I0421 21:28:30.159724       1 builder.go:57] Master version "v1.1.6-171-g83248f3", Builder version "v1.1.6-171-g83248f3"
I0421 21:28:30.162948       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0421 21:28:30.174508       1 docker.go:78] Starting Docker build from build config docker-build-pull-1 ...
I0421 21:28:30.174550       1 docker.go:262] Checking for Docker config file for PULL_DOCKERCFG_PATH in path /var/run/secrets/openshift.io/pull
I0421 21:28:30.174583       1 docker.go:267] Using Docker config file /var/run/secrets/openshift.io/pull/.dockercfg
Step 1 : FROM 172.30.14.166:5000/extended-test-docker-build-pullsecret-8vffw-nczyd/image1@sha256:478607969ab93bfa1f9a74e4e25579dda1cabe206ff6f5aa0da88a9b51b85d4a
F0421 21:28:30.348218       1 builder.go:204] Error: build error: manifest unknown: manifest unknown
Trying to pull repository 172.30.14.166:5000/extended-test-docker-build-pullsecret-8vffw-nczyd/image1 ... failed
```

**Comment by smarterclayton** [comment] 2016-04-22 02:25
@mfojtik

**Comment by mfojtik** [comment] 2016-05-09 11:10
@smarterclayton i can't reproduce this locally and I haven't seen this flake for a while. My guess is that the first build failed or registry flaked.

**Comment by smarterclayton** [comment] 2016-06-08 02:44
Happening a lot more recently, bumping priority.

```
I0608 02:41:04.226572       1 glog.go:50] error inspecting image centos/ruby-22-centos7@sha256:9590270a770a210151179ac1869937cac67be071e6fc6fed58043d142b7e072f: no such image
Image "centos/ruby-22-centos7@sha256:9590270a770a210151179ac1869937cac67be071e6fc6fed58043d142b7e072f" not available locally, pulling ...
Pulling Docker image centos/ruby-22-centos7@sha256:9590270a770a210151179ac1869937cac67be071e6fc6fed58043d142b7e072f ...
I0608 02:41:04.592813       1 glog.go:50] An error was received from the PullImage call: manifest unknown: manifest unknown
F0608 02:41:04.605333       1 helpers.go:108] error: build error: unable to get centos/ruby-22-centos7@sha256:9590270a770a210151179ac1869937cac67be071e6fc6fed58043d142b7e072f
```

**Comment by smarterclayton** [comment] 2016-06-08 02:45
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1652/

**Comment by smarterclayton** [comment] 2016-06-08 14:09
What's bizarre is that this is flaky, rather than predictable.  The Docker daemon in the test suite should be  1.10, and the image should be pushed by 1.10 (or at least, consistent).  Instead, it appears that it only sometimes fails.

**Comment by smarterclayton** [comment] 2016-06-08 23:15
We addressed the Docker 1.10 / 1.9 part of this, so this is back to being a regular flake.

**Comment by mfojtik** [comment] 2016-06-24 08:10
@smarterclayton I thought the manifest unknown is the issue with image pushed using 1.10. Is this fixed? Or still flaking regularly?

**Comment by miminar** [comment] 2016-06-24 08:41
@mfojtik I believe we can close this now since our images are build with docker 1.9 / or with 1.10 pushing just schema v1.

**Closed** 2016-06-26 19:53 UTC
Labels: kind/test-flake, priority/P2
