### ISSUE TITLE
Flake: github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:389

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#14897] opened 2017-06-27 06:14 UTC
github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:389: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default' (from github.com_openshift_origin_test_end-to-end_core)

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1143/consoleFull

Stacktrace
```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:389: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default'
FAILURE after 0.016s: test/end-to-end/core.sh:389: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default': the output content test failed
Standard output from the command:
If you don't see a command prompt, try pressing enter.
I0627 04:47:26.039053       1 merged_client_builder.go:123] Using in-cluster configuration
I0627 04:47:26.041609       1 merged_client_builder.go:123] Using in-cluster configuration
I0627 04:47:26.076348       1 cached_discovery.go:134] failed to write cache to /root/.kube/172.30.0.1_443/servergroups.json due to mkdir /root/.kube: permission denied
I0627 04:47:26.077108       1 merged_client_builder.go:123] Using in-cluster configuration

There was no error output from the command.
=== END TEST CASE ===
```

**Comment by pweil-** [comment] 2017-06-27 08:23
@fabianofranz actually, this looks like it may be another instance of the `--attach` issues we've seen in the past like https://github.com/openshift/origin/issues/12558 which was supposedly fixed in https://github.com/openshift/origin/pull/13669 but maybe just for `test-end-to-end-docker.sh`. 

@soltysh PTAL.

**Comment by soltysh** [comment] 2017-06-28 12:15
After IRC discussion with @pweil- I'll lower the prio. I need logs to verify what's going on and none of the current instances has those. It won't block the release in any way and I'll keep my eye open for it.

**Comment by simo5** [comment] 2017-06-30 12:18
flaked on https://github.com/openshift/origin/pull/14745 too

**Comment by kargakis** [comment] 2017-07-11 10:19
@soltysh do you have everything you need in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4259/s3/ to debug this further?

**Comment by bparees** [comment] 2017-07-19 14:28
also saw this here: https://github.com/openshift/origin/issues/15331 with a slightly different output.

**Comment by mfojtik** [comment] 2017-07-19 20:32
@bparees I can see:

```
I0719 15:31:37.212757       1 cached_discovery.go:88] failed to write cache to /root/.kube/172.30.0.1_443/authorization.openshift.io/v1/serverresources.json due to mkdir /root/.kube: permission denied
I0719 15:31:37.219134       1 cached_discovery.go:88] failed to write cache to /root/.kube/172.30.0.1_443/v1/serverresources.json due to mkdir /root/.kube: permission denied
```

@jupierce @kargakis @jhadvig anyone can check what are the permissions there?

**Comment by mfojtik** [comment] 2017-07-20 09:56
@enj can you help investigate this? this seems like a number 1 flake atm.

**Comment by mfojtik** [comment] 2017-07-20 11:34
I propose we disable this test for now to unblock merge/test queue: https://github.com/openshift/origin/pull/15363 objections?

**Comment by bparees** [comment] 2017-07-20 12:37
no objections here, i just hit it again too.

**Comment by soltysh** [comment] 2017-08-04 11:00
There's a discussion about journald limits happening in https://github.com/openshift/origin/issues/14785

**Comment by stevekuznetsov** [comment] 2017-08-22 14:16
Is this just a dupe of the `journald` issue?

**Comment by soltysh** [comment] 2017-08-29 13:33
Yeah, I'll close this one in favor of the other one.

**Closed by soltysh** 2017-08-29 13:33 UTC
Labels: component/cli, kind/test-flake, priority/P0
