### ISSUE TITLE
apiserver was unable to write a JSON response

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#11457] opened 2016-10-20 08:49 UTC
E1020 11:42:00.245333   28519 apiserver.go:516] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E1020 11:42:00.245428   28519 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
I1020 11:42:00.245480   28519 logs.go:41] http: multiple response.WriteHeader calls
E1020 11:42:00.248638   28519 apiserver.go:516] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E1020 11:42:00.248666   28519 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
I1020 11:42:00.248686   28519 logs.go:41] http: multiple response.WriteHeader calls
E1020 11:42:00.249498   28519 apiserver.go:516] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E1020 11:42:00.249526   28519 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
I1020 11:42:00.249543   28519 logs.go:41] http: multiple response.WriteHeader calls
E1020 11:42:00.249507   28519 apiserver.go:516] apiserver was unable to write a JSON response: http: request method or response status code does not allow body
E1020 11:42:00.249649   28519 errors.go:63] apiserver received an error that is not an unversioned.Status: http: request method or response status code does not allow body
I1020 11:42:00.249678   28519 logs.go:41] http: multiple response.WriteHeader calls

##### Version
oc v1.4.0-alpha.0+7405f17-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

openshift v1.4.0-alpha.0+7405f17-dirty
kubernetes v1.4.0+776c994
etcd 3.1.0-alpha.1

##### Steps To Reproduce
Shows up every time in the server logs when running the server.

**Comment by mfojtik** [comment] 2016-10-21 10:45
this is caused by @kargakis returning 204 which is considered (and reported) as error in kubernetes. This will need to be fixed upstream.

**Comment by kargakis** [comment] 2016-10-21 10:46
Should be fixed in master

**Comment by kargakis** [comment] 2016-10-21 10:50
https://github.com/openshift/origin/pull/11441

**Comment by mfojtik** [comment] 2016-10-21 10:55
verified this is fixed in latest master, closing this issue.

**Closed by mfojtik** 2016-10-21 10:55 UTC
Labels: component/restapi, kind/bug, priority/P2

**Comment by PI-Victor** [comment] 2016-10-21 13:19
thanks guys
