### ISSUE TITLE
flow: Permission denied on 1.5, ok on 1.3

### ISSUE THREAD

**Issue by mguillem** [openshift/origin#15723] opened 2017-08-10 09:44 UTC
[Flow](https://github.com/facebook/flow) can be used on OpenshiftOrigin 1.3 but it fails with EACCES (Permission denied) on 1.5

##### Version
Failing with:
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

working fine with:
openshift v1.3.1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce

1. Create file `Dockerfile`
```
FROM centos/s2i-base-centos7

RUN mkdir /tmp/test-flow \ 
  && cd /tmp/test-flow \
  && curl -L -o flow.zip https://github.com/facebook/flow/releases/download/v0.52.0/flow-linux64-v0.52.0.zip \
  && unzip flow.zip \
  && touch .flowconfig
  
RUN cd /tmp/test-flow && ./flow/flow
```
2. Create file `pb-flow.bc.yml`
```
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: pb-flow 
spec:
  source:
    type: Binary
  strategy:
    dockerfile: 
      dockerfilePath: Dockerfile
    type: Docker
```
3. Run following in the folder where the files have been created:
```
oc create -f .
oc start-build pb-flow --from-dir=. -F
```

##### Current Result
```
Step 3 : RUN cd /tmp/test-flow && ./flow/flow
 ---> Running in ec51e42b5313
flow is still initializing; this can take some time. [processing] -Launching Flow server for /tmp/test-flow
Spawned flow server (pid=9)
Logs will go to /tmp/flow/zStmpzStest-flow.log
Error: Failed to start server. exited prematurely with code 2.
Could not start Flow server!
error: build error: The command '/bin/sh -c cd /tmp/test-flow && ./flow/flow' returned a non-zero code: 78
error: the build mg-test/pb-flow-1 status is "Failed"
```
##### Expected Result
```
Step 3 : RUN cd /tmp/test-flow && ./flow/flow
 ---> Running in 9f66342bfc1b
flow is still initializing; this can take some time. [processing] -Launching Flow server for /tmp/test-flow
Spawned flow server (pid=9)
Logs will go to /tmp/flow/zStmpzStest-flow.log
Started a new flow server: \No errors!
 ---> 8694ba283e7f
```

##### Additional Information
On OpenShift 1.5 it works correctly when running in privileged mode but it shouldn't be needed.

Starting `flow` with `strace` provides following information:
```
syscall_319(0x6ef53d, 0, 0x13, 0xb67ef8, 0x7f8ab7751ee8, 0x10d) = 0x5
ftruncate(5, 27927785472)               = -1 EACCES (Permission denied)
write(2, "Unix.Unix_error(Unix.EACCES, \"ft"..., 46) = 46
```

**Comment by pweil-** [comment] 2017-08-10 19:02
@php-coder

**Comment by simo5** [comment] 2017-08-15 12:23
@adelton can you look into this one ?

**Comment by adelton** [comment] 2017-08-16 15:10
On Fedora 26 with

```
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

when run as `developer`, I don't see the failing result:

```
Uploading directory "." as binary input for the build ...
build "pb-flow-1" started
Receiving source from STDIN as archive ...
Step 1/4 : FROM centos/s2i-base-centos7
 ---> 1da255da93ef
Step 2/4 : RUN mkdir /tmp/test-flow   && cd /tmp/test-flow   && curl -L -o flow.zip https://github.com/facebook/flow/releases/download/v0.52.0/flow-linux64-v0.52.0.zip   && unzip flow.zip   && touch .flowconfig
 ---> Running in 227058e06835
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0    556      0 --:--:--  0:00:01 --:--:--   557
100 2353k  100 2353k    0     0   649k      0  0:00:03  0:00:03 --:--:-- 1059k
Archive:  flow.zip
   creating: flow/
  inflating: flow/flow               
  inflating: flow/flow.js            
 ---> 5e75e23dc007
Removing intermediate container 227058e06835
Step 3/4 : RUN cd /tmp/test-flow && ./flow/flow
 ---> Running in 499406cdc977
flow is still initializing; this can take some time. [processing] -Launching Flow server for /tmp/test-flow
Spawned flow server (pid=7)
Logs will go to /tmp/flow/zStmpzStest-flow.log
Started a new flow server: \flow is still initializing; this can take some time. [processing] |No errors!
 ---> 60b505d62162
Removing intermediate container 499406cdc977
Step 4/4 : ENV "OPENSHIFT_BUILD_NAME" "pb-flow-1" "OPENSHIFT_BUILD_NAMESPACE" "innovation-2017"
 ---> Running in b2b2713ce3d5
 ---> 4ccee6f1c371
Removing intermediate container b2b2713ce3d5
Successfully built 4ccee6f1c371
Build complete, no image push requested
```

@mguillem, could you add some details about the setup you use -- OS, docker version, anything which might be relevant?

**Comment by voanhduy1512** [comment] 2017-08-21 03:20
I have the same problem 

```
openshift v3.4.1.37
kubernetes v1.4.0+776c994
```

I create a small c project https://github.com/voanhduy1512/memfd, which use `memfd_create` and `ftruncate`, to reproduce the problem. 

This code runs fine on new openshift cluster, but not on my production one. I think there is must be a security option setup somewhere that prevent `ftruncate`.

I hope that would give more information that help you debugging.

**Comment by TheoHelfenberger** [comment] 2017-08-22 14:42
@adelton 
I am answering on behalf of @mguillem. Here are the details of our installation. 
Hope this information helps

```
OS:
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-514.16.1.el7.x86_64

Openshift:
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

Docker:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4

```

**Comment by mguillem** [comment] 2017-08-29 07:57
Some new information: it is perhaps related to the underlying OS. It is only failing (so far) when the cluster is installed on CentOS servers and not on Fedora:

- our old Openshift 1.3 is installed on Fedora 25 servers and flow is running without problem.
- the first test with OpenShift 3.5 was with servers running with CentOS
- yesterday we've setup a cluster with OpenShift 3.6 on CentOS and the problem was still existing
- now we've setup a cluster with OpenShift 3.6 on Fedora 26 servers and the flow test described in this ticket is successful.

Otherwise I've tested with different versions of minishift and flow was always working correctly.

**Comment by adelton** [comment] 2017-09-05 14:20
@mguillem, looking at that

```
syscall_319(0x6ef53d, 0, 0x13, 0xb67ef8, 0x7f8ab7751ee8, 0x10d) = 0x5
ftruncate(5, 27927785472)               = -1 EACCES (Permission denied)
write(2, "Unix.Unix_error(Unix.EACCES, \"ft"..., 46) = 46
```

strace output, I wonder: could you look at the output before that and find out what is that filehandle 5?

Since the problem is OS specific and not OpenShift version specific, I wonder if it could also be reproduced with docker directly, taking OpenShift completely out of the picture? IOW, will `docker build` pass for you on that CentOS machine?

**Comment by voanhduy1512** [comment] 2017-09-05 15:45
@adelton file handle 5 is in memory file created by using `memfd_create` system call. I have same problem likes @mguillem and after go through flow source code, i created a small c program above to reproduce the problem. Unfortunally i dont have access to prod environment so cant run it directly without openshift

**Comment by adelton** [comment] 2017-09-05 16:59
Could you share that small reproducer?

**Comment by voanhduy1512** [comment] 2017-09-05 17:07
Here is the sample https://github.com/voanhduy1512/memfd
I posted it in https://github.com/openshift/origin/issues/15723#issuecomment-323637735.

**Comment by mguillem** [comment] 2017-09-06 05:27
@voanhduy1512 
which OS do you have on the servers on which you can reproduce the problem?

@adelton 
we have deleted the cluster with CentOS where we had the problem. I guess that the information is not needed anymore as @voanhduy1512 has already provided it.

**Comment by voanhduy1512** [comment] 2017-09-06 06:16
I am using Redhat Atomic 7.4. But again I don't have access to production so I reproduce the problem when running that code inside openshift

On 6 Sep 2017 12:27, Marc Guillemot <notifications@github.com> wrote:

@voanhduy1512<https://github.com/voanhduy1512>
which OS do you have on the servers on which you can reproduce the problem?

@adelton<https://github.com/adelton>
we have deleted the cluster with CentOS where we had the problem. I guess that the information is not needed anymore as @voanhduy1512<https://github.com/voanhduy1512> has already provided it.

**Comment by adelton** [comment] 2017-09-06 07:48
> I posted it in #15723 (comment).

Ah, sorry, I've missed it.

I've reproduced the issue on RHEL 7.4 with

```
docker-1.12.6-55.gitc4618fb.el7.x86_64
selinux-policy-3.13.1-166.el7_4.4.noarch
container-selinux-2.21-2.gitba103ac.el7.noarch
```

with just plain `docker run`:

```
# docker build -t memfd .
Sending build context to Docker daemon 62.46 kB
Step 1 : FROM centos/s2i-base-centos7
Trying to pull repository registry.access.redhat.com/centos/s2i-base-centos7 ... 
Trying to pull repository docker.io/centos/s2i-base-centos7 ... 
latest: Pulling from docker.io/centos/s2i-base-centos7
74f0853ba93b: Pull complete 
efbcc481846e: Pull complete 
79087c77df35: Pull complete 
[...]
Step 4 : RUN gcc /tmp/test_memfd/test.c -o /tmp/test_memfd/test && chmod +x /tmp/test_memfd/test
 ---> Running in 9c81f932160e
 ---> 26c734238910
Removing intermediate container 9c81f932160e
Step 5 : CMD /tmp/test_memfd/test
 ---> Running in 0994719e565f
 ---> 10657afd9aea
Removing intermediate container 0994719e565f
Successfully built 10657afd9aea
```

```
# docker run --rm -ti memfd
ftruncate(): Permission denied
# docker run --privileged --rm -ti memfd
success
```

It's an SELinux issue, with AVC denial

```
time->Wed Sep  6 03:43:21 2017
type=PROCTITLE msg=audit(1504683801.941:719): proctitle="/tmp/test_memfd/test"
type=SYSCALL msg=audit(1504683801.941:719): arch=c000003e syscall=77 success=no exit=-13 a0=3 a1=400 a2=400 a3=7ffd33ebfe40 items=0 ppid=5684 pid=5700 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts2 ses=4294967295 comm="test" exe="/tmp/test_memfd/test" subj=system_u:system_r:svirt_lxc_net_t:s0:c155,c299 key=(null)
type=AVC msg=audit(1504683801.941:719): avc:  denied  { open } for  pid=5700 comm="test" name=6D656D66643A536572766572206D656D6664 dev="tmpfs" ino=147683 scontext=system_u:system_r:svirt_lxc_net_t:s0:c155,c299 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file
```

In Permissive, things pass.

**Comment by mguillem** [comment] 2017-09-06 07:57
@adelton can you explain what is the concrete consequence of your findings for us?

**Comment by adelton** [comment] 2017-09-06 08:01
It looks like an issue on the OS level, in SELinux policy, way under Kubernetes / OpenShift, so it will have to be addressed there.

I will do more investigation about different versions of RHEL / SELinux policy (starting them as I write this) to see if it should be treated as regression. I'll put link to bugzilla here when I file it.

But currently it looks like something that is not related to OpenShift per se, so from tracking point of view, it might make sense to close this issue once we track it against SELinux policy.

**Comment by mguillem** [comment] 2017-09-06 08:17
Thanks @adelton for the explanation.

**Comment by adelton** [comment] 2017-09-06 09:15
I've now filed https://bugzilla.redhat.com/show_bug.cgi?id=1488814.

**Comment by eparis** [comment] 2017-09-06 13:58
Since this will be better tracked and resolved in bugzilla I am going to close the issue. Please feel free to add yourself to the bugzilla cc list for further updates.

**Closed by eparis** 2017-09-06 13:58 UTC
Labels: component/auth, kind/question, priority/P3

**Comment by adelton** [comment] 2017-10-11 09:34
For the record, patching `container-selinux-2.21-2.gitba103ac.el7.src.rpm` with

```
# cat ~/rpmbuild/SOURCES/bz1488814.patch
diff -ru container-selinux-ba103acc2c20164e3b566e966c280364bc0d99f5.orig/container.te container-selinux-ba103acc2c20164e3b566e966c280364bc0d99f5/container.te
--- container-selinux-ba103acc2c20164e3b566e966c280364bc0d99f5.orig/container.te	2017-08-08 16:14:11.000000000 -0400
+++ container-selinux-ba103acc2c20164e3b566e966c280364bc0d99f5/container.te	2017-10-11 05:25:32.294362007 -0400
@@ -745,3 +745,5 @@
 	allow svirt_lxc_net_t self:capability mknod;
 #	allow svirt_lxc_net_t self:cap_userns mknod;
 ')
+
+fs_tmpfs_filetrans(svirt_lxc_net_t, svirt_sandbox_file_t, { dir file })
```

and rebuilding and updating fixes the problem.
