### ISSUE TITLE
update-all.sh and verify-all.sh

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5607] opened 2015-11-02 21:24 UTC
I really want `update-all.sh` and `verify-all.sh` scripts like upstream to make it easy to run everything.  Not everyone does glob matching with string substitution on the command line.

**Comment by stevekuznetsov** [comment] 2015-11-02 22:11
dupe of https://github.com/openshift/origin/issues/3899

**Closed** 2015-11-03 03:36 UTC
Labels: area/tools, priority/P3
