### ISSUE TITLE
cannot deploy to internal docker registry

### ISSUE THREAD

**Issue by mvlach** [openshift/origin#9085] opened 2016-05-30 15:06 UTC
##### Version
[root@origin-docker openshift-origin-server-v1.2.0-2e62fab-linux-64bit]# oc version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. I have installed the 1.2.0. release of OpenShift Origin. SELinux enforcing
2. Then I export the PATH, KUBECONFIG, CURL_CA_BUNDLE and chmod the configuration
3. After this I install the docker registry
oadm registry
oc get svc/docker-registry -o yaml | grep clusterIP:
clusterIP: 172.30.61.241

4. set permission: oadm policy add-cluster-role-to-user cluster-admin mvlach
5. oc login -u mvlach
6. oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json -n openshift
7. oc new-app php~https://github.com/marekjelen/service-frontend

##### Current Result

```
I0530 14:54:57.908111       1 source.go:197] Downloading "https://github.com/marekjelen/service-frontend" ...
I0530 14:54:59.506296       1 install.go:251] Using "assemble" installed from "image:///usr/libexec/s2i/assemble"
I0530 14:54:59.506362       1 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
I0530 14:54:59.506384       1 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
---> Installing application source...
I0530 14:55:05.230912       1 sti.go:267] Using provided push secret for pushing 172.30.61.241:5000/default/service-frontend:latest image
I0530 14:55:05.230954       1 sti.go:271] Pushing 172.30.61.241:5000/default/service-frontend:latest image ...
E0530 14:55:05.234431       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
E0530 14:55:10.237287       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
E0530 14:55:15.240109       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
E0530 14:55:20.242897       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
E0530 14:55:25.246104       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
E0530 14:55:30.249314       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
E0530 14:55:35.252345       1 dockerutil.go:86] push for image 172.30.61.241:5000/default/service-frontend:latest failed, will retry in 5s ...
I0530 14:55:40.252608       1 sti.go:276] Registry server Address: 
I0530 14:55:40.252651       1 sti.go:277] Registry server User Name: serviceaccount
I0530 14:55:40.252661       1 sti.go:278] Registry server Email: serviceaccount@example.org
I0530 14:55:40.252669       1 sti.go:283] Registry server Password: <<non-empty>>
F0530 14:55:40.252682       1 builder.go:204] Error: build error: Failed to push image. Response from registry is: unable to ping registry endpoint https://172.30.61.241:5000/v0/
v2 ping attempt failed with error: Get https://172.30.61.241:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://172.30.61.241:5000/v1/_ping: tls: oversized record received with length 20527
```

nohup.log (origin start)
```
E0530 10:54:04.227483    2069 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
E0530 10:59:04.257503    2069 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
W0530 11:03:59.193358    2069 manager.go:408] Failed to update status for pod "_()": pods "pod-diagnostic-test-ofwha" not found
W0530 11:04:00.166428    2069 kubelet.go:1995] Orphaned volume "bbd8b0d1-2677-11e6-9a26-0401f8d1a701/default-token-rf9y9" found, tearing down volume
E0530 11:04:04.288344    2069 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
```

##### Additional Information
```
[root@origin-docker openshift-origin-server-v1.2.0-2e62fab-linux-64bit]# oadm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/appl/openshift-origin-server-v1.2.0-2e62fab-linux-64bit/openshift.local.config/master/admin.kubeconfig'
Info:  Using context for cluster-admin access: 'default/139-59-158-225:8443/mvlach'

[Note] Running diagnostic: ConfigContexts[default/139-59-158-225:8443/mvlach]
       Description: Validate client config context is complete and has connectivity
       
Info:  The current client config context is 'default/139-59-158-225:8443/mvlach':
       The server URL is 'https://139.59.158.225:8443'
       The user authentication is 'mvlach/139-59-158-225:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [openshift openshift-infra default]
       
[Note] Running diagnostic: ConfigContexts[default/139-59-158-225:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
Info:  For client config context 'default/139-59-158-225:8443/system:admin':
       The server URL is 'https://139.59.158.225:8443'
       The user authentication is 'system:admin/139-59-158-225:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [default openshift openshift-infra]
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
Info:  Output from the diagnostic pod (image openshift/origin-deployer:v1.2.0):
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       Info:  Service account token successfully authenticated to master
       Info:  Service account token was authenticated by the integrated registry.
       
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       [Note] Summary of diagnostics execution (version v1.2.0):
       [Note] Completed with no errors or warnings seen.
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
Info:  clusterrolebinding/cluster-admins has more subjects than expected.
       
       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.
       
Info:  clusterrolebinding/cluster-admins has extra subject {User  mvlach    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions
       
[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router
       
WARN:  [DClu2001 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:129]
       There is no "router" DeploymentConfig. The router may have been named
       something different, in which case this warning may be ignored.
       
       A router is not strictly required; however it is needed for accessing
       pods from external networks and its absence likely indicates an incomplete
       installation of the cluster.
       
       Use the 'oadm router' command to create a router.
       
[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)
       
Info:  Found a node with same IP as master: origin-docker

[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master
       
[Note] Summary of diagnostics execution (version v1.2.0):
[Note] Warnings seen: 1
```

**Comment by mvlach** [comment] 2016-05-30 16:06
I reinstall the whole OS and install docker from the official site. Now the problem with 
```
failed to find pid of "docker": exit status 1
```
disappear.

But, I'm still unable to pull images to the registry. When I forward port 5000 (-L 5000:172...:5000) 
```
[root@openshift-origin openshift-ansible]# curl http://172.30.69.98:5000/v1
404 page not found
```

**Comment by miminar** [comment] 2016-06-24 12:25
@mvlach Sorry for the delay.

You should be able to access the registry at `http://172.30.69.98:5000/healthz` or `http://172.30.69.98:5000/v2/`

**Comment by mvlach** [comment] 2016-06-24 13:40
Hi, the progress is that I correcly install the docker registry. The main problem was the insecure registry. Now I have problem with running builded image:
```
oc new-app php~https://github.com/marekjelen/service-frontend
```
the log in the deployment is

```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00058: Error retrieving pid file /opt/rh/httpd24/root/var/run/httpd/httpd.pid
AH00059: Remove it before continuing if it is corrupted.
```

**Comment by miminar** [comment] 2016-06-24 14:06
I see. In that case you'd rather talk to a producer of the base image or the application or consult their documentation. @marekjelen could know.

Anyway, this is no longer an OpenShift issue. I'm closing this now.

**Closed by miminar** 2016-06-24 14:06 UTC
Labels: component/imageregistry, kind/question, priority/P2

**Comment by nsams** [comment] 2016-10-25 15:56
@mvlach I'm also getting this error:

> AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> (13)Permission denied: AH00058: Error retrieving pid file /opt/rh/httpd24/root/var/run/httpd/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

How did you solve that? it's really strange as permissions are set correctly.

**Comment by kaushik-s** [comment] 2017-03-06 07:34
@mvlach I am also getting this error. How did u solve it.. Can you help

AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00058: Error retrieving pid file /opt/rh/httpd24/root/var/run/httpd/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

**Comment by nsams** [comment] 2017-03-06 07:39
@kaushik-s I had the error on ubuntu and I think it is somehow related to AppArmor. However uninstalling AppArmor didn't help.

Changing the storage driver used by docker did work around the issue for me.

**Comment by andrewklau** [comment] 2017-03-20 04:54
@nsams I believe this is related to selinux within the container preventing the user from writing to  /opt/rh/httpd24/root/var/run/httpd/

If you switch to root, delete this folder and recreate it as the default user again the issue is resolved. Appears to happen if your Docker host is running something like Ubuntu instead of a rhel based distribution with selinux enabled.

What storage driver did you use to bypass this though?

**Comment by nsams** [comment] 2017-03-21 09:04
> What storage driver did you use to bypass this though?

--storage-driver=overlay

**Comment by rhatdan** [comment] 2017-03-21 12:29
You should use overlay2 not overlay, it performs better, I think we should remove overlay as an option.
