### ISSUE TITLE
Inconsistent resource format for osc update

### ISSUE THREAD

**Issue by wshearn** [openshift/origin#2693] opened 2015-06-02 15:15 UTC
In beta 3 how you pass the resource to osc update is inconsistent depending on which flag you pass in.

```
[root@172 ~]# osc update deploymentConfig/router -f ./router.json 
deploymentConfigs/router
[root@172 ~]# osc update deploymentConfig router -f ./router.json 
deploymentConfigs/router
[root@172 ~]# osc update deploymentConfig/router --patch='{"apiVersion": "v1beta1", "metadata": { "labels": { "patch": "test" }}}'
Error: Must provide resource and name command line params
see 'osc update -h' for help.
[root@172 ~]# osc update deploymentConfig router --patch='{"apiVersion": "v1beta1", "metadata": { "labels": { "patch": "test" }}}'
router
[root@172 ~]# 
```

**Comment by kargakis** [comment] 2015-06-02 15:17
There is discussion upstream about removing the `--upstream` flag for now. 

Btw this is dupe of https://github.com/openshift/origin/issues/1642

**Comment by sdodson** [comment] 2015-06-02 15:20
Fixed in beta4 builds FWIW.

```
[root@ose3-master ~]# oscv ersion
osc v0.5.2.2-14-gef0f6ad
kubernetes v0.17.1-804-g496be63
[root@ose3-master ~]# osc update deploymentConfig/router --patch='{"apiVersion": "v1beta1", "metadata": { "labels": { "patch": "test" }}}'
router
[root@ose3-master ~]# osc update deploymentConfig router --patch='{"apiVersion": "v1beta1", "metadata": { "labels": { "patch": "test" }}}'
router
```

**Closed** 2015-06-04 13:55 UTC
