### ISSUE TITLE
CI: [ERROR] Can not determine install and upgrade version for the `atomic-openshift-utils` package

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17594] opened 2017-12-05 09:20 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17513/test_pull_request_origin_extended_conformance_install_update/9781/

```
########## STARTING STAGE: INSTALL ANSIBLE ATOMIC-OPENSHIFT-UTILS ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9a08eb5ab7381e7e8f541bc30516c4d1750145e8
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9a08eb5ab7381e7e8f541bc30516c4d1750145e8
++ export PATH=/var/lib/jenkins/origin-ci-tool/9a08eb5ab7381e7e8f541bc30516c4d1750145e8/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/9a08eb5ab7381e7e8f541bc30516c4d1750145e8/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace/.config
++ mktemp
+ script=/tmp/tmp.aPwpfJFi9x
+ cat
+ chmod +x /tmp/tmp.aPwpfJFi9x
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.aPwpfJFi9x openshiftdevel:/tmp/tmp.aPwpfJFi9x
+ ssh -F ./.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "timeout 600 /tmp/tmp.aPwpfJFi9x"'
+ cd /data/src/github.com/openshift/aos-cd-jobs
+ pkg_name=origin
+ echo origin
+ echo 'openshift-ansible openshift-ansible-callback-plugins openshift-ansible-docs openshift-ansible-filter-plugins openshift-ansible-lookup-plugins openshift-ansible-playbooks openshift-ansible-roles'
++ cat OPENSHIFT_ANSIBLE_BUILT_VERSION
+ sudo python sjb/hack/determine_install_upgrade_version.py atomic-openshift-utils-3.9.1-1.git.0.f700944.el7.noarch --dependency_branch master
[ERROR] Can not determine install and upgrade version for the `atomic-openshift-utils` package
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: INSTALL ANSIBLE ATOMIC-OPENSHIFT-UTILS [00h 00m 54s] ##########
```

**Comment by tnozicka** [comment] 2017-12-05 11:01
at least twice in a row - this seems permanently broken and blocking CI
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17513/test_pull_request_origin_extended_conformance_install_update/9783/

**Comment by tnozicka** [comment] 2017-12-05 12:43
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17513/test_pull_request_origin_extended_conformance_install_update/9790/

permanently failing

**Comment by ingvagabund** [comment] 2017-12-05 16:11
So this atomic-openshift-utils-* are available:

atomic-openshift-utils-3.0.98-1.git.0.248113a.el7aos.noarch
atomic-openshift-utils-3.2.57-1.git.0.96a2896.el7.noarch
atomic-openshift-utils-3.3.138-1.git.0.21e2ccb.el7.noarch
atomic-openshift-utils-3.4.152-1.git.0.8635b40.el7.noarch
atomic-openshift-utils-3.5.146-1.git.0.fee1c99.el7.noarch
atomic-openshift-utils-3.6.173.0.78-1.git.0.b499fd4.el7.noarch
atomic-openshift-utils-3.7.0-0.143.0.el7.noarch
atomic-openshift-utils-3.7.11-1.git.0.42a781f.el7.noarch
atomic-openshift-utils-3.9.1-1.git.0.85598ea.el7.noarch

The ``sjb/hack/determine_install_upgrade_version.py`` is looking for some 3.8.* rpm, can't find any. Thus the reason the script fails.

**Comment by stevekuznetsov** [comment] 2017-12-05 16:14
Dupe of https://github.com/openshift/origin/issues/17263

There is no 3.8 release.

This job is non-blocking.

/close

**Closed by stevekuznetsov** 2017-12-05 16:14 UTC
Labels: area/tests, kind/test-flake, priority/P0
