### ISSUE TITLE
Console: pods which were in pending too long sometimes stay shaded yellow after transitioning to running.

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#2815] opened 2015-06-04 18:46 UTC
Pretty much what it sounds like.  @liggitt

**Comment by liggitt** [comment] 2015-06-04 18:47
if you look at container status, are all the containers happy? can you include the API data for the pod in question?

**Comment by spadgett** [comment] 2015-06-05 15:55
@pmorie Any of these container statuses trigger a warning.

*Looping Container*

Pod running
Container restart count > 2
Last started < 5 minutes ago

*Failed Container*

Pod running
Container terminated
Container exit code != 0

*Unprepared Container*

Pod running
Container running
Container ready == false
Container started > 5 minutes ago

**Comment by spadgett** [comment] 2015-06-05 16:05
We opened issue #2380 to show a message about the cause of the warning.

**Comment by pmorie** [comment] 2015-06-05 16:11
It would be awesome to have a config item for the 'last started > X minutes
ago' criteria for X.

**Comment by spadgett** [comment] 2015-06-10 18:09
@pmorie have you been able to reproduce?

**Comment by jwforres** [comment] 2015-08-18 17:08
@pmorie bump

**Comment by spadgett** [comment] 2015-08-18 18:06
We do have another issue for the warning style being mysterious, #4195

**Comment by jwforres** [comment] 2015-08-18 19:23
I just want to make sure there isn't some edge case we've missed and that these pods should still be yellow. If @pmorie can recreate it :)

**Comment by jwforres** [comment] 2015-09-03 20:46
@pmorie closing this given that we are fixing #4195

**Comment by spadgett** [comment] 2015-10-08 18:32
One thing I've noticed: if a pod is restarting and then gets healthy, it will stay yellow for another 5 minutes, even after things are OK. Usually, if a pod is restarting, it doesn't take long to fail. And when it does, the server backs off for a few minutes, and the pod will be yellow from the failed container check.

I think we should lower the time frame for last restart or perhaps get rid of the looping container check altogether?

**Comment by liggitt** [comment] 2015-10-08 18:35
I've seen a status on pods of something about CrashLoopBackoff... wonder if we should use that instead.

**Comment by liggitt** [comment] 2015-10-08 18:41
I've seen it in `oc get pods`, though that may be pulling from an event, which would make it less usable

**Comment by spadgett** [comment] 2015-10-08 19:24
Yeah CrashLoopBackoff is the reason property in the container state obj when a pod crashes. We show it in the UI details sidebar. I've seen it a lot recently, unfortunately. Those pods get flagged yellow anyway because of their state.

**Comment by spadgett** [comment] 2015-10-08 21:14
Caught one:

```
        "containerStatuses": [
          {
            "name": "heapster",
            "state": {
              "waiting": {
                "reason": "CrashLoopBackOff"
              },
              "terminated": {
                "exitCode": 255,
                "reason": "Error",
                "startedAt": "2015-10-08T21:09:54Z",
                "finishedAt": "2015-10-08T21:10:24Z",
                "containerID": "docker://47072f03b2241ed0b6039ae37ab8a341a9dc4dedc9f98e17df921c19712cb524"
              }
            },
            "lastState": {
              "terminated": {
                "exitCode": 255,
                "reason": "Error",
                "startedAt": "2015-10-08T21:09:54Z",
                "finishedAt": "2015-10-08T21:10:24Z",
                "containerID": "docker://47072f03b2241ed0b6039ae37ab8a341a9dc4dedc9f98e17df921c19712cb524"
              }
            },
            "ready": false,
            "restartCount": 7,
            "image": "mwringe/origin-metrics-heapster:devel",
            "imageID": "docker://ed6724a87dcadb8bcf40806f1aa0083b6a304c246c501da6b3d958e54d677cc7",
            "containerID": "docker://47072f03b2241ed0b6039ae37ab8a341a9dc4dedc9f98e17df921c19712cb524"
          }
        ]
```

This would be a warning anyway:

```
  .filter('isContainerFailed', function() {
    return function(containerStatus) {
      // If this logic ever changes, update the message in podWarnings
      return containerStatus.state.terminated && containerStatus.state.terminated.exitCode !== 0;
    };
  })
```

**Comment by spadgett** [comment] 2015-10-09 22:21
@pmorie or @liggitt reopen? I think we should relax some of these checks.

**Closed** 2015-11-03 09:54 UTC
Labels: component/web, kind/bug, priority/P3
