### ISSUE TITLE
k8s framework test flake "should create services for rc"

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9549] opened 2016-06-24 15:38 UTC
```
• Failure [126.813 seconds]
[k8s.io] Kubectl client
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:505
  [k8s.io] Kubectl expose
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:505
    should create services for rc [Conformance] [It]
    /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:798

Jun 24 10:56:17.585: No pods matched the filter.

/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:669
```

seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2568/consoleFull

**Comment by kargakis** [comment] 2016-06-25 00:43
Dupe of https://github.com/openshift/origin/issues/9444

**Closed by kargakis** 2016-06-25 00:43 UTC
Labels: dependency/kubernetes, kind/test-flake, priority/P2
