### ISSUE TITLE
new-build: complains about circular reference when creating a new build from Dockerfile

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#7910] opened 2016-03-09 20:19 UTC
Either we need to create distinct imagestreams by default or not complain about the circular imagestream reference.

**Comment by csrwng** [comment] 2016-03-09 20:20
@bparees

**Comment by bparees** [comment] 2016-03-09 20:23
@rhcarvalho i think you're working on something related to this and/or have an issue for it?

**Comment by rhcarvalho** [comment] 2016-03-10 16:24
@bparees the issue is https://github.com/openshift/origin/issues/7718. Though I'm not sure they're duplicates.

Perhaps @csrwng has encountered a different case, @csrwng could you provide an example?

What I can say is that

```
oc new-build -D 'FROM centos'
```

Was meant to error on circular ref because both input and output would be the IST "centos:latest".
Clayton was for the error and opposed to generating arbitrary names to avoid the collision.

In the example above, the proper usage should include a `--to` flag:

```
oc new-build -D 'FROM centos' --to build-output:latest
```

**Comment by csrwng** [comment] 2016-03-10 16:30
@rhcarvalho The case I encountered is in our extended tests. I guess we need to fix the test. Will paste a URL when I come back.

**Comment by rhcarvalho** [comment] 2016-03-10 16:34
@csrwng so this' a dupe of  #7718. It was a regression, I'm working on a fix and better test cases to avoid new regressions in that area.

**Comment by bparees** [comment] 2016-03-10 16:44
yeah we should not have to change the test case, so the fix for #7718 should make the test work again.

closing this as a dupe.

**Closed by bparees** 2016-03-10 16:44 UTC
Labels: component/build, priority/P2

**Comment by csrwng** [comment] 2016-03-10 17:47
Just for reference, the test cases that were failing are these:
https://github.com/openshift/origin/blob/master/test/extended/builds/dockerfile.go#L37
https://github.com/openshift/origin/blob/master/test/extended/builds/dockerfile.go#L60

**Comment by csrwng** [comment] 2016-03-10 17:48
Reading the comments on #7718, it doesn't look like that fix would fix the test cases above.

**Comment by rhcarvalho** [comment] 2016-03-10 18:43
@csrwng the first case builds from `FROM openshift/origin-base`, I'm not sure if that used to work before the regression. I believe in that case you have circular builds, input and output being IST "origin-base:latest".

The second case is `FROM centos:7`, this has worked and is correct, input comes from IST "centos:7", output goes to IST "centos:latest".

Thanks for the pointers to those tests, I'll make sure they will be working.
