### ISSUE TITLE
Majority of builds failed when image streams pushed on large cluster

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15143] opened 2017-07-11 16:53 UTC
Tracking issue to cover the general issue of large numbers of failures when the cluster becomes saturated with builds.

Todo:

- [ ] triage failure causes
- [ ] spawn issues
- [ ] identify specific changes to builds

![distribution](https://www.dropbox.com/s/kvafagafs09e42z/Screenshot%202017-07-11%2012.56.46.png?raw=1)

tracking issues:
https://github.com/openshift/origin/issues/15127 (registry failure)
https://github.com/openshift/origin/issues/15151 (better message when build pod can't be created) - DONE
https://github.com/openshift/origin/issues/15152 (retry build status update) - DONE
https://github.com/openshift/origin/issues/15032 (report when assemble container was OOM killed)
https://github.com/openshift/origin/issues/15169 (more details when fetchsource fails) - DONE
https://github.com/openshift/origin/issues/15171 (failure to get build pod logs)
https://github.com/openshift/origin/issues/15178 (retry more image push failures) - DONE

**Comment by smarterclayton** [comment] 2017-07-11 16:57
https://github.com/openshift/origin/issues/15127 is one of the primary failure causes

**Comment by bparees** [comment] 2017-07-11 17:47
all the "error" builds are reporting a reason of "BuildPodDeleted".  Can you confirm for a couple of them that the build pods are indeed missing/deleted?  And do we have any theories on what would have deleted the build pods?

**Comment by smarterclayton** [comment] 2017-07-11 18:18
@derekwaynecarr @eparis

**Comment by bparees** [comment] 2017-07-11 19:29
created https://github.com/openshift/origin/issues/15151 to improve error reporting when a build pod can't be created.

**Comment by smarterclayton** [comment] 2017-07-11 19:42
```
  40 <no value>
 443 Assemble script failed.
  57 Build failed because of post commit hook.
   2 Failed to commit container.
   1 Failed to create build pod: pods "X-2-build" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=1,limits.memory=512Mi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi.
   1 Failed to create build pod: pods "X-4-build" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=1,limits.memory=512Mi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi.
   1 Failed to create build pod: pods "X-7-build" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=1,limits.memory=512Mi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi.
   1 Failed to create build pod: pods "X-8-build" is forbidden: exceeded quota: compute-resources-timebound, requested: limits.cpu=1,limits.memory=512Mi, used: limits.cpu=2,limits.memory=1Gi, limited: limits.cpu=2,limits.memory=1Gi.
   1 Failed to fetch source for build.
1203 Failed to fetch the input source.
  13 Failed to pull builder image.
   1 Failed to pull runtime image.
2572 Failed to push the image to the registry.
  65 Generic Build failure - check logs for details.
   11 The referenced output image stream XXX does not exist.
  63 The supplied context directory does not exist.
```

**Comment by smarterclayton** [comment] 2017-07-11 20:03
Of the 65 builds with `Generic Build failure - check logs for details.`, the error appears to be failures related to updating build status *and* push authorization failures.  Every single one of the 11 I observed had the following last segment:

```
...
Starting S2I Java Build .....
S2I source build with plain binaries detected
Copying binaries from /tmp/src to /deployments ...
... done

Pushing image 172.30.208.107:5000/XXX/XXX:latest ...
error: Unable to update build status: Get https://172.30.0.1:443/oapi/v1/namespaces/XXX/builds/XXX: dial tcp 172.30.0.1:443: getsockopt: connection refused
Registry server Address:
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: Unable to update build status: Get https://172.30.0.1:443/oapi/v1/namespaces/XXX/builds/XXX: dial tcp 172.30.0.1:443: getsockopt: connection refused
error: build error: Failed to push image: unauthorized: authentication required
```

It looks like several failures, not sure which one triggered that output.  Definitely push failures, but also status update failures.  Connection refused from a master *might* have been a restart during the setup - I think it's possible that build status updates perhaps should retry on that error.  But sticky sessions on the build could be causing this too.

**Comment by smarterclayton** [comment] 2017-07-11 20:06
No build logs remaining for `Failed to commit container.`

**Comment by bparees** [comment] 2017-07-11 20:07
we do retry build status update on conflict, guess we need to expand the set of conditions:
https://github.com/openshift/origin/blob/master/pkg/build/builder/common.go#L185

**Comment by smarterclayton** [comment] 2017-07-11 20:07
```
$ python ./manage.py collectstatic --noinput
Ignore this warning if you're not serving static files with Django.
Running post commit hook ...
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
  File "./manage.py", line 11
    print "hi"
             ^
SyntaxError: Missing parentheses in call to 'print'
error: build error: container "XXX" returned non-zero exit code: 1
```

**Comment by smarterclayton** [comment] 2017-07-11 20:08
There should be a helper for connection refused, and you should be looking at the Temporary() error login in `net/http` which tells you whether it can be retried.

**Comment by bparees** [comment] 2017-07-11 20:14
build status update retry issue: https://github.com/openshift/origin/issues/15152

**Comment by smarterclayton** [comment] 2017-07-11 20:25
Failures with `Assemble script failed.`

```
[WARNING] The requested profile "openshift" could not be activated because it does not exist.
Copying Maven artifacts from /tmp/src/target to /deployments ...
Running: cp *.jar /deployments
cp: cannot stat '*.jar': No such file or directory
Aborting due to error code 1 for copying artifacts from /tmp/src/target to /deployments
error: build error: non-zero (13) exit code from registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift@sha256:671f386241987946c189838af8ed4aca2b83a56d63bfff638fbfb47d5b1b8248
```

```
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /home/jboss/source/target/classes
/usr/bin/mvn: line 9:    33 Killed                  $M2_HOME/bin/mvn "$@"
Aborting due to error code 137 from Maven build
error: build error: non-zero (13) exit code from registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift@sha256:5bea953bbbed6ea9048c0d837e4025cae7eca90470d2e469fd2d319561126c79
```

```
---> Installing application source ...
---> Building your Node application from source
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated gcloud@0.10.0: gcloud has been renamed to google-cloud. To get new features and bug fixes, you must use the new package.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/libexec/s2i/assemble: line 51:    12 Killed                  npm install
error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:b6e89ef453af578cb85c859396af92f9912a0544d6564a2d4b3546c7d63893a0
```

```
> weak@1.0.1 install /opt/app-root/src/node_modules/weak
> node-gyp rebuild

make: Entering directory `/opt/app-root/src/node_modules/weak/build'
CXX(target) Release/obj.target/weakref/src/weakref.o
/usr/libexec/s2i/assemble: line 51:    12 Killed                  npm install
error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:b6e89ef453af578cb85c859396af92f9912a0544d6564a2d4b3546c7d63893a0
```

Look like a lot of OOM kills

**Comment by bparees** [comment] 2017-07-12 04:59
here's a slightly different take on slicing the builds:

```
Processing 14124 builds
interesting builds: 6765
new:1351
pending: 2
running:0
success: 1347
fail: 2835
error: 128
canceled: 2


FAILED
Reason=PostCommitHookFailed:Build failed because of post commit hook. Count=29
Reason=PushImageToRegistryFailed:Failed to push the image to the registry. Count=2330
Reason=FetchSourceFailed:Failed to fetch the input source. Count=272
Reason=AssembleFailed:Assemble script failed. Count=116
Reason=: Count=5
Reason=GenericBuildFailed:Generic Build failure - check logs for details. Count=60
Reason=InvalidContextDirectory:The supplied context directory does not exist. Count=16
Reason=PullBuilderImageFailed:Failed to pull builder image. Count=7


ERROR
Reason=BuildPodDeleted:The pod for this build was deleted before the build completed. Count=128


NEW
Reason=CannotCreateBuildPod:Failed creating build pod. Count=1326
Reason=InvalidOutputReference:Output image could not be resolved. Count=23
Reason=: Count=2


PENDING
Reason=: Count=2

```

"interesting builds" are those that:
1) were created after the upgrade
2) are associated with a buildconfig that had at least one successful build before the upgrade
3) were triggered by an imagechangetrigger (to filter out builds that might have been manually kicked off by a user under conditions not conducive to success).

**Comment by bparees** [comment] 2017-07-12 05:01
of that list, i think these are the candidates to drill down on:

Reason=FetchSourceFailed:Failed to fetch the input source. Count=272
Reason=AssembleFailed:Assemble script failed. Count=116

Certainly it's possible the repos have been deleted since the successful build (which would explain failure to fetch source).  Less sure what would cause so many AssembleFailed, though maybe many of those are the OOM kills @smarterclayton noted.

**Comment by smarterclayton** [comment] 2017-07-12 13:58
The majority of assemble failed were legitimate build failures - those that
never worked.  I'll look for OOMdicators on the pods.

Definitely a bug that the controller doesn't say that the new build is
because of quota, and it should.

On Jul 12, 2017, at 1:01 AM, Ben Parees <notifications@github.com> wrote:

of that list, i think these are the candidates to drill down on:

Reason=FetchSourceFailed:Failed to fetch the input source. Count=272
Reason=AssembleFailed:Assemble script failed. Count=116

Certainly it's possible the repos have been deleted since the successful
build (which would explain failure to fetch source). Less sure what would
cause so many AssembleFailed, though maybe many of those are the OOM kills
@smarterclayton <https://github.com/smarterclayton> noted.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15143#issuecomment-314644740>,
or mute the thread

**Comment by bparees** [comment] 2017-07-12 15:23
>  I'll look for OOMdicators on the pods.

we now have https://github.com/openshift/origin/issues/15032 to track trying to identify when a container is OOMed and note it in the build, however if it's a case where something like maven OOMs itself because it didn't set its heap properly, we'll probably never be able to identify those cases (since it would require introspecting the build logs on a framework by framework basis).


> Definitely a bug that the controller doesn't say that the new build is because of quota, and it should. 

yes that is https://github.com/openshift/origin/issues/15151

**Comment by bparees** [comment] 2017-07-12 15:33
Of the fetch source failures, so far I've confirmed a number of them are either private repos or non-existent.  A number of them reference invalid refs (so the clone succeeds but the checkout fails).  We could probably put more info in the message indicating what part of the fetch source failed.

However there are at least a few where the repo is cloneable and the ref is valid or unset, will need to dig into logs on those.

**Comment by smarterclayton** [comment] 2017-07-12 16:07
Can you spawn an issue for the "no such container"?

**Comment by bparees** [comment] 2017-07-12 17:25
> Can you spawn an issue for the "no such container"?

no such container?  is that a failure mode you've seen?

**Comment by bparees** [comment] 2017-07-12 17:28
spawned issue for augmenting our fetchsource message to indicate what failed about fetching source: https://github.com/openshift/origin/issues/15169

**Comment by smarterclayton** [comment] 2017-07-12 17:40
See my comments earlier in the thread...

On Jul 12, 2017, at 1:28 PM, Ben Parees <notifications@github.com> wrote:

spawned issue for augmenting our fetchsource message to indicate what
failed about fetching source: #15169
<https://github.com/openshift/origin/issues/15169>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15143#issuecomment-314839914>,
or mute the thread

**Comment by bparees** [comment] 2017-07-12 18:01
no such container logging issue: https://github.com/openshift/origin/issues/15171

**Comment by smarterclayton** [comment] 2017-07-12 18:53
All `New` state builds were because the `activeDeadlineSeconds` defaulting was not on.  There's an open question whether *all* builds should have activeDeadlineSeconds on by default.

**Comment by smarterclayton** [comment] 2017-07-12 20:31
Second batch of 338 cleared, 153 failed, here are 73 that failed due to push (registry was being restarted during upgrade)

```
error: build error: Failed to push image: After retrying 6 times, Push image still failed
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: After retrying 6 times, Push image still failed
error: build error: Failed to push image: Put https://172.30.208.107:5000/v2/XX/XX/manifests/latest: EOF
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: After retrying 6 times, Push image still failed
error: build error: Failed to push image: Put https://172.30.208.107:5000/v2/XX/XX/manifests/latest: EOF
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
```

**Comment by bparees** [comment] 2017-07-31 21:24
@derekwaynecarr @mfojtik i've assigned you guys to this issue because you own one of the open tracking issues in the description.

**Comment by bparees** [comment] 2017-08-28 19:06
removing myself from this as the last remaining item is tracked in a separate issue:
https://github.com/openshift/origin/issues/15032

i think in general this issue can be closed out given that we have all the tracking issues in place.

**Comment by bparees** [comment] 2017-10-25 20:40
only remaining issue from the tracking list is https://github.com/openshift/origin/issues/15171

so i am closing this and i guess we'll see what happens w/ the next mass build.

**Closed by bparees** 2017-10-25 20:40 UTC
Labels: component/build, priority/P1

**Comment by hrishin** [comment] 2018-05-16 10:08
@bparees 
Are we sure this issue is fixed? In openshift.io, we are still observing the similar pattern once users run 2 or more builds simultaneously. Sometimes build gets fail due to quota limit or sometimes we don't know the exact reason for build failure. Usually, OpenShift clients receive connection timeout response.

**Comment by bparees** [comment] 2018-05-16 13:34
@hrishin "2 or more simultaneous builds" is not anywhere near the scale of builds that were causing the problems that resulted in this issue being opened.

if clients are receiving connection timeouts that is usually indicative of an overloaded api server (or a bad network connection).

I suggest you open a new issue and provide the exact steps you're performing (how are you starting the builds?  is it two builds for one buildconfig, or two builds for two different buildconfigs?  are your buildconfigs configured with the parallel or serial policy?) and the logs from the builds.  Also include the buildconfig yaml, build yaml, and build-pod yaml.

And even better, enable loglevel 5 on your builds when you run them: https://docs.openshift.org/latest/dev_guide/builds/basic_build_operations.html#accessing-build-logs

**Comment by hrishin** [comment] 2018-05-17 08:49
> "2 or more simultaneous builds" is not anywhere near the scale of builds that were causing the problems that resulted in this issue being opened.

makes sense.

> if clients are receiving connection timeouts that is usually indicative of an overloaded api server (or a bad network connection).

Would investigate in the context OSO.

> And even better, enable loglevel 5 on your builds when you run them: https://docs.openshift.org/latest/dev_guide/builds/basic_build_operations.html#accessing-build-logs

:+1:  thanks for the pointer.
