### ISSUE TITLE
NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod

### ISSUE THREAD

**Issue by samsong8610** [openshift/origin#4565] opened 2015-09-08 02:12 UTC
After update to v1.0.5 from v1.0.4, there are many errors about openshift-ovs-subnet network plugin in the log, details as bellow:

    I0908 00:00:02.664705   27798 kubelet.go:1779] Periodic sync
    I0908 00:00:02.665887   27798 kubelet.go:1439] Desired pods: docker-registry-1-n4537_default, router-1-01etx_default, pod-pv-sam2_default
    I0908 00:00:02.672995   27798 volumes.go:95] Used volume plugin "kubernetes.io/empty-dir" for registry-storage
    I0908 00:00:02.674013   27798 volumes.go:95] Used volume plugin "kubernetes.io/secret" for default-token-9rteb
    I0908 00:00:02.675690   27798 kubelet.go:2298] Generating status for "docker-registry-1-n4537_default"
    I0908 00:00:02.673551   27798 volumes.go:95] Used volume plugin "kubernetes.io/secret" for router-token-0xv2p
    I0908 00:00:02.677917   27798 kubelet.go:2298] Generating status for "router-1-01etx_default"
    I0908 00:00:02.688907   27798 manager.go:293] Container inspect result: {ID:f4946e715b7778d941a86cffa5125c476f54e61c3a621766700c77b71dae53df Created:
    I0908 00:00:02.694495   27798 volumes.go:156] Making a volume.Cleaner for /var/lib/origin/openshift.local.volumes/pods/8d61c03b-510c-11e5-961c-fa163e
    I0908 00:00:02.694544   27798 volumes.go:193] Used volume plugin "kubernetes.io/empty-dir" for 8d61c03b-510c-11e5-961c-fa163e733eba/kubernetes.io~emp
    I0908 00:00:02.694600   27798 volumes.go:156] Making a volume.Cleaner for /var/lib/origin/openshift.local.volumes/pods/8d61c03b-510c-11e5-961c-fa163e
    I0908 00:00:02.694619   27798 volumes.go:193] Used volume plugin "kubernetes.io/secret" for 8d61c03b-510c-11e5-961c-fa163e733eba/kubernetes.io~secret
    I0908 00:00:02.694733   27798 volumes.go:156] Making a volume.Cleaner for /var/lib/origin/openshift.local.volumes/pods/8d8c265e-510c-11e5-961c-fa163e
    I0908 00:00:02.694753   27798 volumes.go:193] Used volume plugin "kubernetes.io/secret" for 8d8c265e-510c-11e5-961c-fa163e733eba/kubernetes.io~secret
    I0908 00:00:02.697374   27798 manager.go:293] Container inspect result: {ID:9c3c4e30da3e993f0f83f7a2ea62ac119d57fecf03d852bf2a621dcb9895f42f Created:
    I0908 00:00:02.700957   27798 manager.go:293] Container inspect result: {ID:ba97de38b3a4885329fbf4d632033654179d9b83ec6ea2c2e8ec070cd15764f9 Created:
    I0908 00:00:02.704849   27798 manager.go:293] Container inspect result: {ID:88c5d99dd45a4ed829690185ceb31395699e54ca4de174fd10031bb7d30c6fe1 Created:
    I0908 00:00:02.708114   27798 exec.go:149] Status 'exec' network plugin output: + lock_file=/var/lock/openshift-sdn.lock
    + action=status
    + pod_namespace=default
    + pod_name=router-1-01etx
    + net_container=ba97de38b3a4885329fbf4d632033654179d9b83ec6ea2c2e8ec070cd15764f9
    + case "$action" in
    + echo 'Bad input: status' default router-1-01etx ba97de38b3a4885329fbf4d632033654179d9b83ec6ea2c2e8ec070cd15764f9
    Bad input: status default router-1-01etx ba97de38b3a4885329fbf4d632033654179d9b83ec6ea2c2e8ec070cd15764f9
    + exit 1
    , exit status 1
    E0908 00:00:02.708268   27798 manager.go:313] NetworkPlugin redhat/openshift-ovs-subnet failed on the status hook for pod 'router-1-01etx' - exit status 1

The openshift-ovs-subnet plugin v1.0.5 doesn't support status action, but the master branch of openshift-sdn repository support. Replacing /usr/libexec/kubernetes/kubelet-plugins/net/exec/redhat~openshift-ovs-subnet/openshift-ovs-subnet with openshift-sdn/ovssubnet/controller/kube/bin/openshift-ovs-subnet can fix this.

    [fedora@node1 ~]$ sudo dnf list installed |grep openshift
    openshift.x86_64                     1.0.5-4.git.5411.3eee7d2.el7.centos @System
    openshift-node.x86_64                1.0.5-4.git.5411.3eee7d2.el7.centos @System
    openshift-sdn-ovs.x86_64             1.0.5-4.git.5411.3eee7d2.el7.centos @System
    tuned-profiles-openshift-node.x86_64 1.0.5-4.git.5411.3eee7d2.el7.centos @System

**Comment by dcbw** [comment] 2015-09-10 19:12
Looks like origin updated Kubernetes to a version that has the status hook, but openshift-sdn wasn't updated to a version that was compatible with that Kubernetes.

**Comment by liggitt** [comment] 2015-09-10 19:13
See https://github.com/openshift/origin/issues/4170

**Comment by liggitt** [comment] 2015-09-10 19:15
pretty sure this can be closed as a dupe of #4170

**Comment by dcbw** [comment] 2015-09-10 19:38
The fix for this bug was merged a few days ago into origin master as part of #4170 so this can be closed.

**Comment by liggitt** [comment] 2015-09-10 19:57
Fix merged in https://github.com/openshift/origin/pull/4586

**Closed by liggitt** 2015-09-10 19:57 UTC
Labels: component/networking, priority/P2
