### ISSUE TITLE
Unable to parse docker version "1.26": illegal version string "1.26"

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14279] opened 2017-05-22 15:47 UTC
I see the `Unable to parse docker version "1.26": illegal version string "1.26"` error in OpenShift logs.

##### Version
```console
$ openshift version
openshift v3.6.0-alpha.1+a666b7c-745-dirty
kubernetes v1.6.1+5115d708d7
etcd 3.1.0
$ oc version
oc v3.6.0-alpha.1+a666b7c-745-dirty
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
Unable to connect to the server: x509: certificate signed by unknown authority
```

##### Steps To Reproduce
1. `cd examples/sample-app`
2. `sudo `which openshift` start --public-master=127.0.0.1 --volume-dir=$PWD/volumes &>logs/openshift.log`

##### Current Result
```
E0522 17:37:54.975306   12527 container_manager_linux.go:90] Unable to parse docker version "1.26": illegal version string "1.26"
W0522 17:37:55.066851   12527 container_manager_linux.go:750] CPUAccounting not enabled for pid: 12131
W0522 17:37:55.066868   12527 container_manager_linux.go:753] MemoryAccounting not enabled for pid: 12131
W0522 17:37:55.066960   12527 container_manager_linux.go:750] CPUAccounting not enabled for pid: 12527
W0522 17:37:55.066965   12527 container_manager_linux.go:753] MemoryAccounting not enabled for pid: 12527
```

##### Expected Result
There is no such error.

##### Additional Information
```console
$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-9.git14cc629.fc27.x86_64
 Go version:      go1.8.1
 Git commit:      14cc629/1.13.1
 Built:           Thu Apr 13 18:28:00 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-9.git14cc629.fc27.x86_64
 Go version:      go1.8.1
 Git commit:      14cc629/1.13.1
 Built:           Thu Apr 13 18:28:00 2017
 OS/Arch:         linux/amd64
 Experimental:    false
$ rpm -qa | grep docker
docker-common-1.13.1-9.git14cc629.fc27.x86_64
docker-rhel-push-plugin-1.13.1-9.git14cc629.fc27.x86_64
docker-1.13.1-9.git14cc629.fc27.x86_64
$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
```

**Comment by dcbw** [comment] 2017-05-24 18:45
Backport of upstream https://github.com/kubernetes/kubernetes/pull/44068 seems required.

**Comment by derekwaynecarr** [comment] 2017-05-24 18:46
That backport came in https://github.com/openshift/origin/pull/14158

**Comment by stevekuznetsov** [comment] 2017-05-24 18:47
Docker API version is not and has not been a Semantic Version. Not sure that is the correct backport -- that was just to not parse the Docker package version as semantic.

**Comment by derekwaynecarr** [comment] 2017-05-24 18:52
I would like to fix 1.13, but for reference, docker 1.12.6 is the actually supported version at this time.

**Comment by stevekuznetsov** [comment] 2017-05-24 18:56
From the changes by @soltysh  in https://github.com/openshift/origin/pull/14158 we see [this change](https://github.com/openshift/origin/pull/14158/files#diff-89fdbae8233121a5d16d6f849685ceb5R88):

```diff
-	version, err := utilversion.ParseSemantic(v.Version)
+	version, err := utilversion.ParseSemantic(v.APIVersion)
```

Which is incorrectly parsing the API version of Docker as a semantic version -- it is not. Why is that working upstream?

**Comment by derekwaynecarr** [comment] 2017-05-24 19:00
looks like an error in the port from upstream.

**Comment by soltysh** [comment] 2017-06-02 14:04
Should be fixed right now.

**Comment by soltysh** [comment] 2017-06-07 11:24
It looks like it's still not fixed, I'm getting:
```
E0607 11:20:46.278094   19536 docker_manager.go:2159] Failed to create pod infra container: RunContainerError; Skipping pod "kapua-broker-1-deploy_redhat-iot(452e2961-4b73-11e7-a79c-0ec6a458e57a)": runContainer: docker: failed to parse docker version "17.03.1-ce": illegal zero-prefixed version component "03" in "17.03.1-ce"
```
on recent master.

**Comment by soltysh** [comment] 2017-06-07 11:46
It looks like [this line](https://github.com/openshift/origin/blob/6473593c449ab84cfdf57361e41eae5b78e766ee/vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_manager.go#L1098) need to be switched to `utilversion.ParseGeneric(version)` as well, trying...

**Comment by soltysh** [comment] 2017-06-07 11:51
@derekwaynecarr are you aware of any changes that happened upstream, I'm missing here?

**Comment by soltysh** [comment] 2017-06-07 11:59
I think I spoke too soon, since I'm using `oc cluster up` for that it picked the `v3.6.0-alpha.1` which does not have that fix in place. Double checking this...

**Comment by oprudkyi** [comment] 2017-06-07 12:55
Since https://github.com/openshift/origin/issues/13865 is closed, copying here what was wrong with new docker in that issue :
even if openshift is able to run, new pods aren't created with error 
```
open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by soltysh** [comment] 2017-06-07 14:11
The problem is that `oc cluster up` is picking the last released version of OpenShift. Since only 3.6 has the necessary fix and latest released version at the time of speaking is [v3.6.0-alpha.1](https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.1) which does not have that fix there are two possible fixes:

1. downgrade to older docker (1.12 worked for me)
2. use `oc cluster up --version=latest` which specifies to use the latest available images which have that fix.

**Closed by soltysh** 2017-06-07 14:11 UTC
Labels: component/kubernetes, kind/bug, priority/P1

**Comment by soltysh** [comment] 2017-06-09 18:02
Now that https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.2 is released the `oc cluster up` downloaded from there will use the newest released images, as well.

**Comment by caleblloyd** [comment] 2017-06-27 12:42
@soltysh I don't think this has been fixed yet.

Openshift Version:

```
$ oc version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+bbb9647-550
kubernetes v1.6.1+5115d708d7
```

Docker Version: 

```
$ docker version
Client:
 Version:      17.06.0-ce-rc5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:13:24 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc5
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:12:15 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Still getting this error:

```
$ oc new-app --docker-image=nginx
$ oc get pods
NAME             READY     STATUS    RESTARTS   AGE
nginx-1-deploy   0/1       Error     0          4m
$ oc logs nginx-1-deploy
error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by soltysh** [comment] 2017-06-27 14:24
@caleblloyd how do you run openshift, if through docker, make sure to use alpha-2 images. It's the server that needs to be fixed.

**Comment by caleblloyd** [comment] 2017-06-27 14:46
@soltysh I tried both `oc cluster up --version=latest` and `oc cluster up --version="v3.6.0-alpha.2"` and both yield the error mentioned

**Comment by soltysh** [comment] 2017-06-28 12:07
It looks like in your case it's this: https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root because I've just tried with:

```
[1046] vagrant@dev:~ 
$ oc version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
```
and 
```
$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:23:59 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:23:59 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
on my fedora 25 machine and it worked just fine, but with that scc tweak as described in the link. The reason for that is that [nginx](https://github.com/nginxinc/docker-nginx/blob/c769ad8ab21dfb374fa33d8fb9d0822d0fa8d2e5/mainline/stretch/Dockerfile#L39) is trying to expose port 80, which is a root operation and you need to set appropriate access right to do so. Personally, I always check with `oc run hello --image=openshift/hello-openshift` which runs a simple go web server returning `Hello OpenShift!` on port 8080.

**Comment by caleblloyd** [comment] 2017-06-29 16:13
@soltysh thank you.  I did get OpenShift working fine inside of a Ubuntu 16.04 VM using Docker 17.06-ce.

The problem `open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
` that I am encountering only happens inside of an LXD container now, and is unrelated to this issue so I have opened https://github.com/openshift/origin/issues/14959
