### ISSUE TITLE
integration failure:  TestProjectRequestError

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17780] opened 2017-12-14 13:20 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_integration/11977/#githubcomopenshiftorigintestintegrationrunner-testintegration

/assign mfojtik deads2k 
Assuming it's caused by the rebase
/sig master

**Comment by deads2k** [comment] 2017-12-14 13:49
/assign enj

@enj Slow namespace cleanup maybe?  Can you at least sort out what's stuck?

**Comment by soltysh** [comment] 2018-01-03 16:40
This is happening very frequently, I'll dig into it when I'm back home. But I'm bumping this to P1 and closing the other bug.

**Comment by soltysh** [comment] 2018-01-04 09:53
It looks like I can reproduce this locally, at least from time to time... digging in more..

**Comment by mfojtik** [comment] 2018-01-04 10:04
@ironcladlou seems like from the log that the namespace is stuck in terminating, which suggests a GC issue.

**Comment by ironcladlou** [comment] 2018-01-04 19:44
So far the evidence I've been able to gather from debugging points to a race between the test wait code and the namespace controller finalizing the namespace. I'm going to dig a little more into the namespace controller's informer event handling to see if I can explain the occasional processing lag.

**Comment by ironcladlou** [comment] 2018-01-04 20:38
More details...

Given time *Ts* (successful run) and *Tf* (failed run) in seconds:

| *Ts* | *Tf* | |
|--:|--:|--|
|0 | 0 | projectrequest registry issues DELETE against namespace *N* due to invalid template contents |
6 | 8 | namespace controller processes *N*, and enqueues deletion 5 seconds in the future (deletion grace period defaults to 5 seconds)
| 11 | 13 |namespace controller deletes *N*'s contents and finally *N* itself

The test is waiting 10 seconds for the projectrequest call to result in complete deletion of the namespace. Looks like the variance in time between the DELETE and the namespace controller creates a very narrow window of success. We could investigate the delay further, but in the meantime simply increasing the test timeout (as in https://github.com/openshift/origin/pull/17984) seems pragmatic.

**Comment by ironcladlou** [comment] 2018-01-04 20:52
New fix: https://github.com/openshift/origin/pull/17991

**Closed** 2018-01-04 21:32 UTC
Labels: area/tests, kind/test-flake, priority/P1, sig/master
