### ISSUE TITLE
coloring for readability of oc status

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#8741] opened 2016-05-04 18:16 UTC
When you get a wall of project contents from `oc status` like the below, it's pretty difficult to see what's going on at a glance. This isn't even that complicated an example.

```
In project apiman on server https://192.168.121.5:8443

http://apiman-apiman.router.default.svc.cluster.local (svc/apiman)
  rc/apiman runs fabric8/apiman:2.3-SNAPSHOT
    rc/apiman created 4 days ago - 0/1 pods growing to 1

https://apiman.example.com (reencrypt) (svc/apiman-console)
  dc/apiman-console deploys istag/apiman-console:latest 
    deployment #1 deployed 3 days ago - 1 pod

svc/apiman-es-cluster (headless):9300
  dc/apiman-es-p8qgdvo2 deploys istag/apiman-elasticsearch:latest <-
    bc/apiman-elasticsearch docker build of https://github.com/sosiouxme/origin-apiman#master 
    deployment #2 deployed 37 hours ago - 1 pod
    deployment #1 deployed 3 days ago

https://api-gateway.example.com (reencrypt) (svc/apiman-gateway)
  dc/apiman-gateway deploys istag/apiman-gateway:latest 
    deployment #1 deployed 3 days ago - 1 pod

svc/apiman-storage - 172.30.89.159:9200 -> restapi
  dc/apiman-es-p8qgdvo2 deploys istag/apiman-elasticsearch:latest <-
    bc/apiman-elasticsearch docker build of https://github.com/sosiouxme/origin-apiman#master 
    deployment #2 deployed 37 hours ago - 1 pod
    deployment #1 deployed 3 days ago

dc/apiman-curator deploys istag/apiman-curator:latest <-
  bc/apiman-curator docker build of https://github.com/sosiouxme/origin-apiman#master 
  deployment #2 deployed 37 hours ago - 1 pod
  deployment #1 deployed 3 days ago

bc/apiman-deployer docker build of https://github.com/sosiouxme/origin-apiman#master
  build #4 succeeded 37 hours ago - 41d700a: Some post-deployment validations. (Bruno Barcarol Guimarães <bbgstb@gmail.com>)

rc/apiman-gateway runs fabric8/apiman-gateway:2.3-SNAPSHOT
  rc/apiman-gateway created 4 days ago - 0/1 pods growing to 1

5 warnings identified, use 'oc status -v' to see details.
```

##### Expected Result

Some terminal escapes to add some coloring (only if there is an actual terminal, of course). For example, bold the first line of every stanza and make "thing" names a brighter color so they're easier to pick out. While we're at it, maybe group like things together; for instance, the three routes above, the two services, the DCs, BCs, RCs, and so on, and maybe put a section title on them.

**Comment by kargakis** [comment] 2016-05-04 18:39
Dupe of https://github.com/openshift/origin/issues/4183

**Closed by kargakis** 2016-05-04 18:39 UTC

**Comment by sosiouxme** [comment] 2016-05-05 17:12
Heh. I guess my search-fu is not adequate. I did search.
