### ISSUE TITLE
db deployments not working at all

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9842] opened 2016-07-14 05:20 UTC
oc create -f examples/image-streams/image-streams-centos7.json -n openshift

wait for imagestreams to import

and then `oc new-app -f examples/db-templates/postgresql-ephemeral-template.json`

the postgresql deployment never happens and if you force it via:
`$ oc deploy postgresql`

you get

`postgresql deployment #1 waiting on image or update`

despite the referenced postgresql tag being present.

it seems likely this is user error given how bad it is, but i don't see how, so apologies if it is.

**Comment by bparees** [comment] 2016-07-14 05:21
@kargakis @smarterclayton

**Comment by bparees** [comment] 2016-07-14 05:29
you can see an example of the failures here:
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/321/consoleFull

(all those tests failed because the DB deployment never happened, which caused the app pods to fail to deploy because of their pre-hooks that setup the db)

**Comment by kargakis** [comment] 2016-07-14 08:50
Dupe of https://github.com/openshift/origin/issues/9018. The image stream needs to be reconciled in order for the image to be picked up by the deployment config. I would love to have that issue as P1.
Fixed in https://github.com/openshift/origin/pull/9349

**Comment by bparees** [comment] 2016-07-14 14:05
not convinced this is a dupe yet, i've got a DC that's been sitting for several minutes and hasn't deployed even though the imagestreamtag has been imported. (was imported before the DC was created).

**Comment by kargakis** [comment] 2016-07-14 14:50
> not convinced this is a dupe yet, i've got a DC that's been sitting for several minutes and hasn't deployed even though the imagestreamtag has been imported. (was imported before the DC was created).

This is a different issue: the image change controller isn't relisting anymore after two minutes (and probably every other controller that uses the RetryController framework?) cc: @deads2k @smarterclayton

**Comment by smarterclayton** [comment] 2016-07-14 14:51
Did we flub the resync change?  David, did you review any of that upstream?

On Thu, Jul 14, 2016 at 10:50 AM, Michail Kargakis <notifications@github.com

**Comment by deads2k** [comment] 2016-07-14 18:21
> Did we flub the resync change?  David, did you review any of that upstream?

No, but looking into it now, it would seem that our RetryController uses a FIFO, which anonymously includes a store, which uses a threadsafe store, which helpfully drops the resync on the floor.

**Comment by bparees** [comment] 2016-07-14 18:25
the most bothersome thing to me about this is we apparently do not have a test case that will block the merge queue when ICT deployments are broken.  we should fix that.

**Comment by smarterclayton** [comment] 2016-07-14 18:35
Pretty sure that we do, it's just that there are races.  It's probably
better for resync to be broken so we fix the races, instead of letting
resync magically fix our bugs.

**Comment by deads2k** [comment] 2016-07-14 18:37
> No, but looking into it now, it would seem that our RetryController uses a FIFO, which anonymously includes a store, which uses a threadsafe store, which helpfully drops the resync on the floor.

hrm, gocode failure.  Its there, just didn't show up for implementors. :(

**Comment by bparees** [comment] 2016-07-14 18:41
> Pretty sure that we do, it's just that there are races.

hmm... i'm able to recreate this with 100% reliability on my system.

**Comment by kargakis** [comment] 2016-07-14 19:03
> hmm... i'm able to recreate this with 100% reliability on my system.

@smarterclayton is talking about deployment-related flakes. This is not related specifically to deployments.

**Comment by deads2k** [comment] 2016-07-14 19:08
I can reproduce it too.

**Comment by deads2k** [comment] 2016-07-14 19:13
Think I got it.  See https://github.com/openshift/origin/pull/9861

**Comment by smarterclayton** [comment] 2016-07-14 19:13
Yeah, general statement: Any code dependent on resync is broken.  That's
why we have retry and delaying queue.

**Comment by bparees** [comment] 2016-07-14 19:33
> @smarterclayton is talking about deployment-related flakes. This is not related specifically to deployments.

regardless of what it's related to or what else it affects, it affects deployments 100% of the time on my system and we don't have tests that caught it in our merge queue.

**Closed** 2016-07-15 18:06 UTC
Labels: kind/bug, priority/P0
