### ISSUE TITLE
The builds are broken on Docker 1.10.2

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7549] opened 2016-02-23 10:40 UTC
When using the latest Docker (note: installed from docker.org yum repos, not official centos repos), both S2I and Docker builds will fail with this error:

Docker build:
```
 ---> Running in 3ce1ba9b6292
builder.go:204] Error: build error: Cannot start container 3ce1ba9b6292ff467d1e9bb1ceb8923d7d4a80f17e295b7fa306c7a2eff80c7b: [9] System error: write /sys/fs/cgroup/memory/docker/3ce1ba9b6292ff467d1e9bb1ceb8923d7d4a80f17e295b7fa306c7a2eff80c7b/memory.limit_in_bytes: invalid argument
```

S2I build:
```
install.go:236] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
builder.go:204] Error: build error: API error (500): Cannot start container ea7c76f432b8a704843535c09c77c1598688b96ad1b07a641d6bd4b96a178566: [9] System error: write /sys/fs/cgroup/memory/docker/ea7c76f432b8a704843535c09c77c1598688b96ad1b07a641d6bd4b96a178566/memory.limit_in_bytes: invalid argument
```

Dunno if this is due to cgroup changes we did or something is badly broken in latest docker.
Keep in mind that this is probably low prio because I don't think we are getting 1.10.2 docker anytime soon, but we should keep eyes on this.

EDIT: This was done on centos7.1.

**Comment by mfojtik** [comment] 2016-02-23 10:41
@bparees @smarterclayton FYI

**Comment by mfojtik** [comment] 2016-02-23 10:52
also it might be possible that there is something missing here: https://docs.docker.com/engine/installation/linux/centos/

**Comment by smarterclayton** [comment] 2016-02-23 13:00
Well, we need to fix it in case anyone tries to upgrade to 1.10.2 in the open source community, or if it points to a bug in our cgroup handling.  Giving it p1 to triage.

**Comment by mfojtik** [comment] 2016-02-23 13:02
@vbatts any clues about what can be configured wrong for docker? The systemd service installed by that evil script from docker seems to just run `docker -H fd://` without any other additional parameters. I wonder if something has to be setup before you want to use CGroups.

**Comment by mfojtik** [comment] 2016-02-23 13:22
FYI: https://github.com/docker/docker/issues/20603#issuecomment-187695448

**Comment by dbalakirev** [comment] 2016-02-23 13:30
@mfojtik so as wrote in that ticket I happen to have this issue. But with RHEL 7.2 and of course docker engine 1.10.2.

**Comment by mfojtik** [comment] 2016-02-23 13:31
@dbalakirev I can reproduce it on centos7 with docker engine 1.10.2 :-)

**Comment by bparees** [comment] 2016-02-23 14:37
this is one of the things I reported in https://github.com/openshift/origin/issues/6822#issuecomment-175160853

**Comment by bparees** [comment] 2016-02-23 14:38
ok not exactly the same, very similar.

**Comment by bparees** [comment] 2016-02-23 14:39
@mfojtik does this error occur if you simply run a raw "docker build" command on your host, passing the various limits via the docker build flags?

**Comment by dbalakirev** [comment] 2016-02-23 14:42
Just be sure I checked: using 1.9.1 the build moves on.

**Comment by mfojtik** [comment] 2016-02-23 14:47
@bparees `docker build --memory=512MB` works as expected.

**Comment by bparees** [comment] 2016-02-23 15:48
@mfojtik so either there is an issue in the dockerclient making the docker daemon call, or in the docker daemon when it sets up a container based on the api call w/ cgroup values....

**Comment by mfojtik** [comment] 2016-02-23 15:49
@bparees I was checking if the cgroups are enabled properly (I even add something to grub2 config to enable them), but no luck. Also the docker daemon does not report anything in his log about missing cgroups or something (it used to few months ago).

**Comment by fredoche** [comment] 2016-02-23 16:30
Hi, 

We have a similar issue. Since we added --exec-opt native.cgroupdriver=cgroupfs to docker options, builds fail  with the following error: 

`Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:9223372036854775807, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:9223372036854775807}
...
Error: build error: [8] System error: write /sys/fs/cgroup/memory/docker-daemon/docker/bc814b06e8f4e96ab2b3f47c5c22a60ba50dcc9b5af92852ff0685568bb78b59/memory.limit_in_bytes: invalid argument`

We're using 
openshift 1.1.2
docker 1.9.1 from rebuilt from fedora 23 srpms
centos 7.2

We are using a workaround in the buildconfig spec, which then allows successful builds :
```
spec:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
```

**Comment by sbadakhc** [comment] 2016-02-24 21:04
Using the modified buildconfig spec but still no joy.

https://github.com/sbadakhc/openshift-ci-pipeline/blob/master/examples/slave/s2i-slave-template.json

```
"resources": {
          "limits": {
            "cpu": "500m",
            "memory": "1Gi"
```

**Comment by bparees** [comment] 2016-02-24 21:08
@sbadakhc which docker version and what exact error do you get?

**Comment by sbadakhc** [comment] 2016-02-24 21:11
@bparees 

https://github.com/openshift/sti-ruby/issues/94

**Comment by bparees** [comment] 2016-02-24 21:20
@sbadakhc thanks.  i'm going to close that other issue.

@mrunalp @danmcp @smarterclayton i'm raising this back to p1 as we have users on docker 1.8 and docker 1.9 having these cgroup issues as well.  It's not 100% clear they are all exactly the same error, but they are all some variation on issues writing to /sys/fs/cgroup/memory/docker-daemon/docker

(some are invalid argument, some are permission denied/write error, some are accessing `memory.limit_in_bytes` and others are accessing `memory.memsw.limit_in_bytes`)

My only theory that would put this on the s2i/build code is if the "9223372036854775807" (maxint_64) value is exceeding some cgroup limit, but we only use that value because we read an even *larger* value from the cgroup filesystem in the first place.

**Comment by vbehar** [comment] 2016-02-25 07:49
Yes, we found that the issue is caused by running docker (1.9) with the option `--exec-opt native.cgroupdriver=cgroupfs`. We needed this as a workaround to fix this bug : https://github.com/docker/docker/issues/17653#issuecomment-155609224 

And as `cgroupfs` is the default value in docker 1.10 - https://github.com/docker/docker/issues/17653#issuecomment-158795632 - people are mostly having the issue when upgrading to docker 1.10

as a global workaround, we "deactivated" cgroup limits in the builder by passing `nil` instead of `cgLimits` in https://github.com/openshift/origin/blob/v1.1.2/pkg/build/builder/cmd/builder.go#L145 and then regenerated new builder images (for the docker-builder and sti-builder).

As it's working when specifying resources limits in the buildconfig, but not when there are no resources limits, maybe we could just pass cgLimits to docker when there are limits defined in the buildconfig ? to avoid the issue with default values (the `memory.limit_in_bytes: invalid argument`). What do you think ?

**Comment by sbadakhc** [comment] 2016-02-25 13:27
@vbehar @bparees thanks for your efforts.  My feeling is that making the config change in one place is preferable than updating multiple build configs.  Passing the option cgLimits to docker would make trouble shooting easier.  I'm not seeing many build configs out there explicitly declare resource limits and rightfully so.

I will try out the options above and get to you.

**Comment by bparees** [comment] 2016-02-25 18:56
@vbehar 
> As it's working when specifying resources limits in the buildconfig, but not when there are no resources limits, maybe we could just pass cgLimits to docker when there are limits defined in the buildconfig ? to avoid the issue with default values (the memory.limit_in_bytes: invalid argument). What do you think ?

It's an interesting idea, but it's not my preferred solution because it's possible the build pod could have cgroup limits applied to it via some mechanism that is not represented in the Build object's resources section, and if that happens, we'd end up launching an unlimited assembly container, effectively circumventing the intent that was expressed when cgroup limits were put on the builder container. 

Also we've seen at least some cases where issues crop up even when resource limits are being applied, so this may fix your issue but i don't think it completely solves it.  If it turns out the no limit problem is separate from the other issue, we can play with how we handle the no limit case (eg instead of setting maxint_64 as the limit, use a lower value, if that is the problem.  But again I think it's more likely a bug in cgroup since there are plenty of environment where maxint_64 is being accepted).

@sbadakhc 
>  My feeling is that making the config change in one place is preferable than updating multiple build configs. Passing the option cgLimits to docker would make trouble shooting easier.

sorry i'm not quite following your suggestion.  I understand you don't want to have to go set a resource limit on every buildconfig as a workaround for the issues that seem to occur when no limit is set, but i'm not clear on what you're suggesting we do instead.

**Comment by sbadakhc** [comment] 2016-02-25 19:12
@bparees

Apologies, I'm getting my head around the issue so excuse me for not being very clear.  If we have a case where I can simply pass extra options to docker to fix the issue then what would be preferable to to:

A) Modifying every build config as a workaround.
B) Changing the no limit case when it works for other environments

Not sure if the options exist but probably worth investigating?

**Comment by bparees** [comment] 2016-02-25 19:18
@sbadakhc sure, if there is a docker daemon flag we can set to fix this, we'll definitely pursue that, at least as a documented workaround.  Sounds like what @vbehar suggested is that workaround at least for some environments, but I know i've also seen this issue occur as an intermittent problem in some environments, so i don't think the flag will solve 100% of the cases we've seen.

**Comment by sbadakhc** [comment] 2016-02-25 19:22
@bparees 

Agreed.  I will continue investigating options in the mean time.  Thanks for the feedback.

**Comment by fredoche** [comment] 2016-02-26 09:56
FWIW Here's the one liner that helped us get through this. It bypasses some of the cgroup code inside the builders.
https://github.com/AXA-GROUP-SOLUTIONS/origin/commits/v1.1.2-ignore-cgroup

**Comment by sbadakhc** [comment] 2016-02-29 15:35
@fredoche thanks for the link.  @bparees also brought this to my attention.  This works on my vm installations but the problem still exists on the container deployment of Openshift origin.  I would have to rebuild the origin container and apply the update you have referenced.  Are there any docs on how to rebuild the openshift origin container?

**Comment by vbatts** [comment] 2016-03-07 16:38
@mfojtik Sorry. I'm not familiar with this issue.

**Comment by webdizz** [comment] 2016-03-09 08:37
Any updates on this? I'm starting with OpenShift Origin using Vagrant and by default Docker 1.10.2 is installed.

**Comment by livelace** [comment] 2016-03-13 14:53
I join to previous orator, when all be fine ? :)

**Comment by vbehar** [comment] 2016-03-16 08:30
Here we maintain our patch through origin versions : https://github.com/AXA-GROUP-SOLUTIONS/origin/branches and deploy our custom builder images to all nodes, but it would be better to have a real solution to this problem ;-)

**Comment by mrunalp** [comment] 2016-03-16 17:55
https://github.com/projectatomic/docker/pull/71 should probably fix this issue. The fix will be available in 1.10.3

**Comment by bparees** [comment] 2016-03-22 13:31
@mrunalp we're also seeing 

`
F0322 02:09:45.188964 1 builder.go:204] Error: build error: API error (500): Cannot start container 2a7da6dc87c1d24fed96b687a89b9121308cbce1e984ac0cc2508ecc6b6a4646: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-2a7da6dc87c1d24fed96b687a89b9121308cbce1e984ac0cc2508ecc6b6a4646.scope/memory.limit_in_bytes: invalid argument
`

in docker 1.9, was the same fix applied there?

**Comment by mrunalp** [comment] 2016-03-22 14:08
This should be covered by two fixes in -23. Let me know if we still see this after updating to that version. Thanks.

**Comment by bparees** [comment] 2016-03-22 15:21
@mrunalp appears to be still broken despite our AMI having 1.9.1 -  23 now:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13398/artifact/origin/artifacts/test-end-to-end-docker/logs/container-ruby-sample-build-1-build-sti-build.log

Docker version 1.9.1, build f97fb16/1.9.1
docker-1.9.1-23.el7.x86_64

**Comment by smarterclayton** [comment] 2016-03-22 15:44
Let's sync on IRC when you get in - this is blocking the merge queue right
now (we are only succeeding 25% of the time)

**Comment by mrunalp** [comment] 2016-03-22 15:47
Sure.

**Comment by mrunalp** [comment] 2016-03-22 20:36
Isolated to the issue to cgroups/kernel.
We are trying to set the value to the default value which isn't allowed unless we set the soft limit first.
I am figuring out an appropriate patch that won't break across kernel versions.
On the AMI instance:
```
[root@ip-172-18-1-21 mytest.service]# echo '9223372036854775807' > memory.limit_in_bytes 
-bash: echo: write error: Invalid argument
[root@ip-172-18-1-21 mytest.service]# echo '9223372036854775806' > memory.limit_in_bytes                                                                                                                                                                                                  
-bash: echo: write error: Invalid argument
[root@ip-172-18-1-21 mytest.service]# echo '9223372036854775800' > memory.limit_in_bytes                                                                                                                                                                                                  
-bash: echo: write error: Invalid argument
[root@ip-172-18-1-21 mytest.service]# echo '922337203685477580' > memory.limit_in_bytes                                                                                                                                                                                                   
[root@ip-172-18-1-21 mytest.service]# echo '9223372036854775807' > memory.limit_in_bytes 
-bash: echo: write error: Invalid argument
[root@ip-172-18-1-21 mytest.service]# echo '9223372036854775807' > memory.memsw.limit_in_bytes 
[root@ip-172-18-1-21 mytest.service]# echo '9223372036854775807' > memory.limit_in_bytes                                                                                                                                                                                                  
[root@ip-172-18-1-21 mytest.service]# 


```

**Comment by mrunalp** [comment] 2016-03-22 20:41
I will get input from kernel engineers and then fix it accordingly in docker/libcontainer.

**Comment by mrunalp** [comment] 2016-03-22 20:45
I don't see the same issue on Fedora 23 or Rawhide.

**Comment by iguyking** [comment] 2016-03-23 22:55
This broke my environment when I ran a yum update today.   I have docker version: docker-1.9.1-0.1.origin.23.el7.centos.x86_64 & origin version origin-master-1.1.4-0.git.0.9d8230b.el7.centos.x86_64.  Do we have any workarounds for the time being?

**Comment by vbehar** [comment] 2016-03-24 07:56
@iguyking you can patch with https://github.com/openshift/origin/pull/8202, build the "builder" docker images (`openshift/origin-sti-builder` and `openshift/origin-docker-builder`) and then deploy them on your nodes manually (`docker save` / `docker load` for example)

**Comment by derdanu** [comment] 2016-03-24 16:02
Same here with centos7 worked 2 days ago. Now a fresh Installation is not possible atm with the same versions of docker/origin as @iguyking.

**Comment by smarterclayton** [comment] 2016-03-24 16:11
I'll cut a 1.1.5

On Mar 24, 2016, at 12:02 PM, Daniel Falkner <notifications@github.com>
wrote:

Same here with centos7 worked 2 days ago. Now a fresh Installation is not
possible atm with the same versions of docker/origin as @iguyking
<https://github.com/iguyking>.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/7549#issuecomment-200902184>

**Comment by digi691** [comment] 2016-03-24 16:29
I ran into this issue as I just started a project to start testing openshift origin and I ran into this issue.  To get my builds working, I downgraded docker to docker-1.9.1-0.origin.19.el7.centos.x86_64 and now everything works. The question I have, is there a way in the byo install via openshift/ansible to pin a specific version when deploying?

**Comment by smarterclayton** [comment] 2016-03-24 16:33
Pin OpenShift?  Should be @sdodson?

**Comment by sdodson** [comment] 2016-03-24 18:17
@smarterclayton or @bparees can either of you summarize the version matrix that's ok?

**Comment by smarterclayton** [comment] 2016-03-24 18:21
1.1.4 only works up to the 1.9.1-19 release.

**Comment by sdodson** [comment] 2016-03-24 18:24
Is that https://bugzilla.redhat.com/show_bug.cgi?id=1320302 If I can just provide a version of docker that includes the fix for that bug I'd prefer doing that.

**Comment by bparees** [comment] 2016-03-24 18:33
@sdodson i'm not sure about that bug, 1.9.1-23 was the version that fixed all the cgroup flake problems we had, but manifested a new problem that we solved via:
https://github.com/openshift/origin/pull/8202

**Comment by zmhassan** [comment] 2016-03-27 20:24
@bparees . I'm experiencing the same problem with cgroups. I'm using centos 7. 

```bash 
 F0327 19:44:59.154433       1 builder.go:204] Error: build error: API error (500): Cannot start container 4d83d07a426cc97232eb49bcc4292205d2307240cb4d6060632d1d018e896a20: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-4d83d07a426cc97232eb49bcc4292205d2307240cb4d6060632d1d018e896a20.scope/memory.limit_in_bytes: invalid argument
```

**Comment by derdanu** [comment] 2016-03-27 20:45
This will be fixxed in 1.1.5. See Post from @smarterclayton. Downgrade docker to -19 works for me atm on a fresh centos7.

yum downgrade docker-forward-journald docker
yum downgrade docker-forward-journald docker

You have to downgrade two versions as docker -23 even is broken with origin 1.1.4

**Comment by zmhassan** [comment] 2016-03-28 07:44
Awesome. Thanks. I'll give this a try.

**Comment by sdodson** [comment] 2016-03-28 13:26
I've deleted all builds from the copr newer than 1.9.1-0.origin.19.el7.
`yum clean expire-cache && yum distribution-synchronization docker\*`  should downgrade you.

**Comment by zmhassan** [comment] 2016-03-28 17:05
@sdodson  I've managed to downgrade using the method outlined by derdanu. Now my environment on all 3 hosts looks like this:
```bash
[root@node1 ~]# docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-0.origin.19.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      185277d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-0.origin.19.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      185277d/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

**Comment by mfojtik** [comment] 2016-04-01 07:24
We are still broken on latest Docker [1] on Centos7. If you install Docker manually (not RPM) from official Docker web site, the build will end with:

```
F0401 07:22:28.375455       1 builder.go:204] Error: build error: API error (500): Cannot start container 648dbc64cb3bfa76342b42ab23e1f748dc0b6d81b6a9202c0dd6cd75a538db1c: [9] System error: write /sys/fs/cgroup/memory/docker/648dbc64cb3bfa76342b42ab23e1f748dc0b6d81b6a9202c0dd6cd75a538db1c/memory.limit_in_bytes: invalid argument
```

[1] `docker version`:
```
[root@localhost origin]# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Comment by mfojtik** [comment] 2016-04-01 07:25
@smarterclayton downgrade works well, but I'm not sure we want to release and make folks installing latest Docker manually broken.

**Comment by mfojtik** [comment] 2016-04-01 07:31
@smarterclayton @mrunalp I managed to workaround this for the latest Docker. All you need to do is to edit the `/usr/lib/systemd/system/docker.service` file and change `ExecStart` to:

```
ExecStart=/usr/bin/docker daemon --exec-opt native.cgroupdriver=systemd -H fd://
```

IOW. use the `systemd` driver instead of cgroupsfs. After this, I can build, push, etc.

**Comment by dragon9783** [comment] 2016-04-05 03:40
LGTM

**Comment by sdodson** [comment] 2016-04-05 13:41
@mfojtik I think the better solution to that is to add  `daemon --exec-opt native.cgroupdriver=systemd` to `/etc/sysconfig/docker` in the `OPTIONS` variable, no?

**Comment by mfojtik** [comment] 2016-04-05 13:43
@sdodson the crappy Docker Engine installer you btw. run as `curl -fsSL https://get.docker.com/ | sh` (!) does not create systemd service that is reading the defaults from /etc/sysconfig...

**Comment by sdodson** [comment] 2016-04-05 13:49
:crying_cat_face:

**Comment by mrunalp** [comment] 2016-04-05 19:23
This should be fixed the change that @bparees made.

**Comment by bparees** [comment] 2016-04-05 19:25
@mrunalp i assume you're referring to https://github.com/openshift/origin/pull/8202, is that the final answer here, or do we still want to get to the bottom of why that fix was even necessary?

(we can lower the severity though)

**Comment by bparees** [comment] 2016-04-05 20:17
closing based on comments in #8202

**Closed by bparees** 2016-04-05 20:17 UTC
Labels: component/build, priority/P2

**Comment by mfojtik** [comment] 2016-04-14 13:21
@bparees @mrunalp good news! it seems like Docker 1.11.0 works without any workaround, out of box.
