### ISSUE TITLE
Jenkins testing (v2) should pass a smoke test after an s2i build

### ISSUE THREAD

**Issue by dmage** [openshift/origin#18858] opened 2018-03-06 11:16 UTC
https://ci.openshift.redhat.com/jenkins/job/push_jenkins_images/139/

```
Jenkins testing (v2) 
  should pass a smoke test after an s2i build
  /data/src/github.com/openshift/jenkins/2/test/jenkins_test.go:181
STEP: running s2i build
Checking if image "registry.access.redhat.com/openshift3/jenkins-2-rhel7-candidate" is available locally ...
Checking if image "registry.access.redhat.com/openshift3/jenkins-2-rhel7-candidate" is available locally ...
panic: test timed out after 30m0s
```
<summary>
<details>

```
goroutine 1875 [running]:
testing.startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 29 minutes]:
testing.(*T).Run(0xc420358000, 0x84b9b2, 0x4, 0x86c338, 0x480dc6)
	/usr/lib/golang/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc420358000)
	/usr/lib/golang/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc420358000, 0xc4201e3de0)
	/usr/lib/golang/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420237260, 0xb17c30, 0x1, 0x1, 0x2cd)
	/usr/lib/golang/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420433f18, 0xc4201e3f70)
	/usr/lib/golang/src/testing/testing.go:921 +0x111
main.main()
	github.com/openshift/jenkins/2/test/_test/_testmain.go:44 +0xdb

goroutine 5 [syscall, 29 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [syscall, 25 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x4775, 0xc42016aed0, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4201da510, 0xc4201da510, 0x0, 0x0)
	/usr/lib/golang/src/os/wait_waitid.go:31 +0xa5
os.(*Process).wait(0xc4201da510, 0xc42043ff20, 0xc420467578, 0x60)
	/usr/lib/golang/src/os/exec_unix.go:22 +0x42
os.(*Process).Wait(0xc4201da510, 0x0, 0x0, 0x86c7f8)
	/usr/lib/golang/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc4204674a0, 0x0, 0x0)
	/usr/lib/golang/src/os/exec/exec.go:446 +0x62
os/exec.(*Cmd).Run(0xc4204674a0, 0xc42043ff20, 0xc42016b228)
	/usr/lib/golang/src/os/exec/exec.go:289 +0x5c
github.com/openshift/jenkins/2/test.glob..func2.7()
	/data/src/github.com/openshift/jenkins/2/test/jenkins_test.go:203 +0x34f
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420274d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:110 +0x9c
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc420274d20, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x13e
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc4202371a0, 0xa5e1c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0x7f
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc420081930, 0x0, 0xa5e1c0, 0xc420076cf0)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x5a9
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc420081930, 0xa5e1c0, 0xc420076cf0)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0xe3
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc4202937c0, 0xc420081930, 0x0)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:198 +0x10d
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc4202937c0, 0x86c301)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:168 +0x32c
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc4202937c0, 0x12)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:64 +0xdc
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc4200102d0, 0x7fc42beca0f0, 0xc4203580f0, 0x85527c, 0x12, 0xc4202aaf60, 0x1, 0x1, 0xa64dc0, 0xc420076cf0, ...)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x283
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0xa5f080, 0xc4203580f0, 0x85527c, 0x12, 0xc42003df50, 0x1, 0x1, 0xf)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:218 +0x276
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo.RunSpecs(0xa5f080, 0xc4203580f0, 0x85527c, 0x12, 0x5371b3)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:199 +0x1e5
github.com/openshift/jenkins/2/test.Test(0xc4203580f0)
	/data/src/github.com/openshift/jenkins/2/test/jenkins_test.go:22 +0x64
testing.tRunner(0xc4203580f0, 0x86c338)
	/usr/lib/golang/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:789 +0x2de

goroutine 8 [chan receive, 29 minutes]:
github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc4202937c0)
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:220 +0xd7
created by github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/data/src/github.com/openshift/jenkins/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:59 +0x60

goroutine 18 [select, 29 minutes, locked to thread]:
runtime.gopark(0x86cbe0, 0x0, 0x84d9b0, 0x6, 0x18, 0x1)
	/usr/lib/golang/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420038f50, 0xc420370060)
	/usr/lib/golang/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1

goroutine 11 [IO wait, 25 minutes]:
internal/poll.runtime_pollWait(0x7fc42bec1f70, 0x72, 0x0)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42037c098, 0x72, 0xffffffffffffff00, 0xa60400, 0xa5c4c0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42037c098, 0xc42009f000, 0x1000, 0x1000)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42037c080, 0xc42009f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42037c080, 0xc42009f000, 0x1000, 0x1000, 0x42f05b, 0xc420388a40, 0x45a6a0)
	/usr/lib/golang/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e4b8, 0xc42009f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc42009dc20, 0xc42009f000, 0x1000, 0x1000, 0xc4202e2640, 0xc42038c058, 0x458740)
	/usr/lib/golang/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc420275320)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc420275320, 0x1, 0x0, 0x0, 0x0, 0xc420341920, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42009dc20)
	/usr/lib/golang/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 12 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc42009dc20)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 647 [select, 29 minutes]:
net/http.(*persistConn).writeLoop(0xc42009dd40)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 646 [select, 29 minutes]:
net/http.(*persistConn).readLoop(0xc42009dd40)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 390 [select, 29 minutes]:
net/http.(*persistConn).writeLoop(0xc42009cea0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 658 [select, 29 minutes]:
net/http.(*persistConn).writeLoop(0xc420436ea0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 389 [select, 29 minutes]:
net/http.(*persistConn).readLoop(0xc42009cea0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1215 [select, 27 minutes]:
net/http.(*persistConn).readLoop(0xc420327320)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 381 [select, 29 minutes]:
net/http.(*persistConn).writeLoop(0xc420412d80)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 380 [select, 29 minutes]:
net/http.(*persistConn).readLoop(0xc420412d80)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 385 [select, 29 minutes]:
net/http.(*persistConn).writeLoop(0xc420412ea0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 384 [select, 29 minutes]:
net/http.(*persistConn).readLoop(0xc420412ea0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 662 [select, 29 minutes]:
net/http.(*persistConn).writeLoop(0xc4204370e0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1168 [select, 27 minutes]:
net/http.(*persistConn).readLoop(0xc42031c7e0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 661 [select, 29 minutes]:
net/http.(*persistConn).readLoop(0xc4204370e0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 625 [select, 29 minutes]:
net/http.(*persistConn).readLoop(0xc420436ea0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1507 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc42031c360)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1211 [select, 27 minutes]:
net/http.(*persistConn).readLoop(0xc4203270e0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1212 [select, 27 minutes]:
net/http.(*persistConn).writeLoop(0xc4203270e0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1169 [select, 27 minutes]:
net/http.(*persistConn).writeLoop(0xc42031c7e0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1506 [select, 25 minutes]:
net/http.(*persistConn).readLoop(0xc42031c360)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1216 [select, 27 minutes]:
net/http.(*persistConn).writeLoop(0xc420327320)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1839 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc420326a20)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1438 [select, 25 minutes]:
net/http.(*persistConn).readLoop(0xc42031c120)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1439 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc42031c120)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1494 [select, 25 minutes]:
net/http.(*persistConn).readLoop(0xc42009d0e0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1495 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc42009d0e0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1838 [select, 25 minutes]:
net/http.(*persistConn).readLoop(0xc420326a20)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1848 [select, 25 minutes]:
net/http.(*persistConn).readLoop(0xc4204a67e0)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1890 [IO wait, 25 minutes]:
internal/poll.runtime_pollWait(0x7fc42bec1370, 0x72, 0x1)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420420978, 0x72, 0xffffffffffffff01, 0xa60400, 0xa5c4c0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420420978, 0xc4201ae001, 0x8000, 0x8000)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420420960, 0xc4201ae000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:126 +0x18a
os.(*File).read(0xc4203f8460, 0xc4201ae000, 0x8000, 0x8000, 0xc4203ece60, 0x6f5e9a, 0xc4200165f8)
	/usr/lib/golang/src/os/file_unix.go:216 +0x4e
os.(*File).Read(0xc4203f8460, 0xc4201ae000, 0x8000, 0x8000, 0x6d, 0x0, 0x0)
	/usr/lib/golang/src/os/file.go:103 +0x6d
io.copyBuffer(0xa5e1c0, 0xc420076cf0, 0xa5ec40, 0xc4203f8460, 0xc4201ae000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:392 +0x123
io.Copy(0xa5e1c0, 0xc420076cf0, 0xa5ec40, 0xc4203f8460, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:362 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x435118, 0x86ca68)
	/usr/lib/golang/src/os/exec/exec.go:264 +0x4d
os/exec.(*Cmd).Start.func1(0xc4204674a0, 0xc420395960)
	/usr/lib/golang/src/os/exec/exec.go:380 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/golang/src/os/exec/exec.go:379 +0x646

goroutine 1849 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc4204a67e0)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53

goroutine 1852 [select, 25 minutes]:
net/http.(*persistConn).readLoop(0xc4204a6900)
	/usr/lib/golang/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1186 +0xa2e

goroutine 1853 [select, 25 minutes]:
net/http.(*persistConn).writeLoop(0xc4204a6900)
	/usr/lib/golang/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1187 +0xa53
exit status 2
```
</details>
</summary>
FAIL	github.com/openshift/jenkins/2/test	1800.014s

**Comment by bparees** [comment] 2018-03-06 15:18
our current theory is this is caused by docker 1.13.

**Comment by bparees** [comment] 2018-03-06 15:19
@dmage for future reference this probably should have been opened against the jenkins repo, but thank you for being on top of it!

**Comment by gabemontero** [comment] 2018-03-06 21:40
So based on https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_jenkins_images/117/ being hung and with s2i --loglevel=5, we see s2i stuck after taring all the files 

So the notion of a container not getting started that @bparees and @derekwaynecarr have been discussing *may* have been in play 

where the container receiving that tar'ed data was the container that should have been started

**Comment by gabemontero** [comment] 2018-03-07 17:12
While I've been working on adding some debug to the jenkins image test, @bparees as a repro with invoking `s2i` where it appears a combo of the most recent `s2i` and docker 1.13 has the flake

I have not seen any issues with the latest `s2i` and docker 1.12 after repeated test runs on my laptop, fwiw

**Comment by bparees** [comment] 2018-03-07 17:51
dupe of https://github.com/openshift/origin/issues/18862

**Closed by bparees** 2018-03-07 17:51 UTC
Labels: kind/test-flake

**Comment by gabemontero** [comment] 2018-03-07 18:34
Looks like https://github.com/openshift/source-to-image/pull/855 and the switch back to docker-engine is how we are driving the solution here.
