### ISSUE TITLE
DNS [It] should answer endpoint and wildcard queries for the cluster [Conformance]

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9224] opened 2016-06-08 14:30 UTC
```
   9015 Jun 08 08:12:12 ESC[91mESC[1m• Failure [309.059 seconds]ESC[0m
   9016 Jun 08 08:12:12 DNS
   9017 Jun 08 08:12:12 ESC[90m/data/src/github.com/openshift/origin/test/extended/dns/dns.go:291ESC[0m
   9018 Jun 08 08:12:12   ESC[91mESC[1mshould answer endpoint and wildcard queries for the cluster [Conformance] [It]ESC[0m
   9019 Jun 08 08:12:12   ESC[90m/data/src/github.com/openshift/origin/test/extended/dns/dns.go:290ESC[0m
   9020 Jun 08 08:12:12 
   9021 Jun 08 08:12:12   ESC[91mExpected
   9022 Jun 08 08:12:12       <*errors.errorString | 0xc820a8dc50>: {
   9023 Jun 08 08:12:12           s: "gave up waiting for pod 'dns-test-8482f323-2d71-11e6-8391-0edad30cf911' to be 'running' after 5m0s",
   9024 Jun 08 08:12:12       }
   9025 Jun 08 08:12:12   to be nilESC[0m
   9026 Jun 08 08:12:12 
   9027 Jun 08 08:12:12   /data/src/github.com/openshift/origin/test/extended/dns/dns.go:138

  12415 Jun 08 08:24:58 ESC[91mESC[1m[Fail] ESC[0mESC[90mDNS ESC[0mESC[91mESC[1m[It] should answer endpoint and wildcard queries for the cluster [Conformance] ESC[0m
  12416 Jun 08 08:24:58 ESC[37m/data/src/github.com/openshift/origin/test/extended/dns/dns.go:138ESC[0m
```

**Comment by kargakis** [comment] 2016-06-09 09:30
Dupe of https://github.com/openshift/origin/issues/9192

**Closed by kargakis** 2016-06-09 09:30 UTC
Labels: component/networking, kind/test-flake, priority/P2
