### ISSUE TITLE
Flake in travis on upstream test TestRequestAttachRemoteCommand

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4157] opened 2015-08-13 21:36 UTC
```
ok  	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/record	0.741s	coverage: 93.5% of statements
--- FAIL: TestRequestAttachRemoteCommand-2 (0.09s)
	remotecommand_test.go:238: 0: expected an error
FAIL
coverage: 85.4% of statements
```

**Comment by stevekuznetsov** [comment] 2015-08-14 00:34
Duplicate of #4050

**Comment by liggitt** [comment] 2015-08-14 03:28
https://travis-ci.org/openshift/origin/jobs/75542244#L317

**Comment by liggitt** [comment] 2015-08-17 02:43
https://travis-ci.org/openshift/origin/jobs/75877523#L1452

**Comment by liggitt** [comment] 2015-08-25 05:36
Same root cause as #4239

**Comment by liggitt** [comment] 2015-09-02 19:55
closing, leavingf #4239 open to track. @ncdc's PR in flight upstream will resolve this

**Closed by liggitt** 2015-09-02 19:55 UTC
Labels: area/tests, kind/test-flake, priority/P2
