### ISSUE TITLE
$rootScope.$apply() in DataService.get() causes looping errors

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#4247] opened 2015-08-18 19:16 UTC
There is a call to `$rooteScope.$apply()` in DataService.get() that can cause Angular to throw `$digest` errors:

`Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.8/$rootScope/inprog?p0=%24digest`

A string of promises in controller code is an example of what can trigger this error.  A slimmed down example of what can potentially cause this:

```javascript

AuthService
  .withUser()
  .then(function(user) {
     return DataService
                  .get('projects', projectName, context)
                  .then(function(project) {
                    angular.extend($scope, {
                      project: project
                    });
                    return project;
                  });
  })
  .then(function(user) {
     return DataService
                  .get('builds', buildName, context)
                  .then(function(build) {
                    angular.extend($scope, {
                      build: build
                    })
                    return build;
                  });
  });
```

The block of code that causes the issue (lines 277-292 of data.js):

```javascript
if (obj) {
  $rootScope.$apply(function(){
    deferred.resolve(obj);
  });
}
else {
  $rootScope.$apply(function(){
    // simulation of API object not found
    deferred.reject({
      data: {},
      status: 404,
      headers: function() { return null; },
      config: {}
    });
  });
} 
```

Eliminating the `$rootScope.$apply()` calls does not initially seem to cause issues, but it may be in order to have QE do a regression test.  The block would now look like:

```javascript
if (obj) {
  deferred.resolve(obj);
}
else {
    // simulation of API object not found
  deferred.reject({
      data: {},
      status: 404,
      headers: function() { return null; },
      config: {}
  });
} 
```

The [docs for root scope](https://docs.angularjs.org/error/$rootScope/inprog?p0=$digest) discourage using `$rootScope.$apply()` in this way, particularly under the heading "Digest Phases".  

I propose eliminating these lines unless there is good reason to keep them.  

@jwforres @spadgett any concerns with this change?

**Comment by liggitt** [comment] 2015-08-18 20:19
The promise returned from `get` should always be resolved inside a digest, otherwise all the consumers have to do their own $apply for any changes they make to take effect.

The second half of the function resolves the deferred from a call to `$http`, which does an `apply` for you.

**Comment by liggitt** [comment] 2015-08-18 20:22
https://github.com/angular/angular.js/blob/master/src/ng/http.js#L1279-L1284

**Comment by benjaminapetersen** [comment] 2015-08-18 21:22
@liggitt Using a couple different normal promise resolution chains I can easily trigger this digest loop error. Here is another example I ran into using `$q.all()`:

```javascript
// this will also throw Error: [$rootScope:inprog] $digest already in progress
// however, if I comment out the $scope.$apply in DataService.get(), there is no issue.
$q
  .all([
    DataService.get(/* stuff */),
    DataService.get(/* stuff */)
  ])
  .then(_.spread(function(first, second) {
    angular.extend($scope, {/* stuff */});
  }));

``` 

The lines in the [Angular docs](https://docs.angularjs.org/error/$rootScope/inprog?p0=$digest) seem to indicate that $rootScope.$apply should be pretty explicit, something the controllers should be responsible (if needed).  This makes sense, since it is the controllers job to ensure data gets to view via $scope.

> Digest Phases

> Angular keeps track of what phase of processing we are in, the relevant ones being $apply and
> $digest. Trying to reenter a $digestor $apply while one of them is already in progress is typically a sign
> of programming error that needs to be fixed. So Angular will throw this error when that occurs.

> In most situations it should be well defined whether a piece of code will be run inside an $apply, in
> which case you should not be calling $apply or $digest, or it will be run outside, in which case you
> should wrap any code that will be interacting with Angular scope or services, in a call to $apply.

I can see how handling this internally is convenient at times, but it seems to be fragile since I've broken it a number of different ways.  I'd suggest doing this work in the `.then()` functions:

```javascript
.then(_.spread(function(first, second) {
  // if needed. should not always be necessary
  $scope.$apply(function() {
    angular.extend($scope, {/* stuff */});
  });
}));
```
Its a little less automagic, but Angular crashes if the digest loop is triggered when you don't want it to.

**Comment by liggitt** [comment] 2015-08-18 21:27
whatever we do, we have to resolve returned promises consistently inside or outside a digest loop, otherwise callbacks will be unsure whether they need to trigger an apply to make their changes take effect. $http triggers a resolution, so I feel like anything else we do in `get` needs to as well

**Comment by spadgett** [comment] 2015-08-18 21:29
Agree with @liggitt. It would be very easy to miss this in the controllers because it works sometimes and sometimes not depending on the code path. There's no error as well when not in a digest loop, just the UI won't update.

Can we just check if a digest is in progress?

```
if (!$rootScope.$$phase) $rootScope.$apply();
```

Like the $http code @liggitt linked to.

**Comment by spadgett** [comment] 2015-08-18 21:38
Actually, this might be better:

```
$timeout(function() {
  // anything you want can go here and will safely be run on the next digest.
})
```

http://stackoverflow.com/questions/12729122/prevent-error-digest-already-in-progress-when-calling-scope-apply

**Comment by liggitt** [comment] 2015-08-18 21:39
That probably simulates $http (which involves a sync) better

**Comment by spadgett** [comment] 2015-08-18 21:43
Reading further in the thread I linked, we might try `$scope.$evalAsync()`.

**Comment by liggitt** [comment] 2015-08-18 22:08
That could be good. Looks like $http is doing something similar, actually.

**Comment by benjaminapetersen** [comment] 2015-08-19 14:43
Right, $http wraps $q and is hooked into the digest loop internally.  In a controller you can `$http.then(function() { angular.extend($scope, {})  });` or use `$q.when($http)` or `$q.all([$http, $resource.$promise])`.  All will allow you to get your `$scope` updates and not worry about the digest loop.   

As an aside, I don't think services should really know anything about $scope, $scope should be the contract between a controller & a view for passing data.  

The extra `$q.defer()` in `DataService.get()` may be creating some complexity as well. I'd rather do something like:

```javascript
if(cached)
   return $q.when(cached);
else {
   return $http(/*...*/);
}
```
Both are then-able, and $scope should update fine.

These options still feel a bit hacky to me, but `$timeout` seems most promising.  I would not use `$rootScope.$$phase`, nor do I want to do more $scope work in a service via `$scope.$evalAsync()`.

**Comment by benjaminapetersen** [comment] 2015-08-19 15:56
Initially swapping for `$timeout` seems to work well without breaking other things.  I'm inclined to a fork_ami for this and have QE check it, since `.get()` is so fundamental.

@liggitt does that seem reasonable to you?

**Comment by benjaminapetersen** [comment] 2015-08-21 13:56
@liggitt feel free to assign this one to me. thanks!

**Comment by benjaminapetersen** [comment] 2015-08-26 14:59
Been looking more into this.  I think Sam's suggestion of `$rootScope.$evalAsync()` is closer to the mark.  Checking the source, perhaps `$rootScope.$applyAsync()` would be best, since it adds the item to the queue then tells angular to `scheduleApplyAsync()`.  `$evalAsync` seems to try a little harder to force a `$digest`, but I don't think we want to do that.

I'll do some testing & perhaps update the PR if this is a better route.

**Comment by liggitt** [comment] 2015-09-02 16:00
@jwforres @benjaminapetersen priority on this? Are there any places this is currently broken, or is this a techdebt improvement?

**Comment by spadgett** [comment] 2015-09-02 16:40
@liggitt looks like the calling code where @benjaminapetersen originally saw the problem is still in the logs pull.

**Comment by liggitt** [comment] 2015-09-02 16:45
ok, let's reference it as a prereq from there

**Comment by spadgett** [comment] 2015-09-02 16:54
Yeah, he made the change in that PR as well:

https://github.com/openshift/origin/pull/4322/files#diff-269727b54e63c302555b820ce26b397cR278

**Closed** 2015-09-25 16:48 UTC
Labels: area/techdebt, component/web, kind/bug, priority/P3
