### ISSUE TITLE
`hack/install-travis.sh` failing on download rate limit

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8171] opened 2016-03-21 13:34 UTC
Seeing the following on Travis runs [here](https://travis-ci.org/openshift/origin/jobs/117445878):
```
# cd .; git clone https://go.googlesource.com/tools /home/travis/gopath/src/golang.org/x/tools
Cloning into '/home/travis/gopath/src/golang.org/x/tools'...
remote: Daily bandwidth rate limit exceeded for IP 52.0.240.122.
fatal: protocol error: bad pack header
package golang.org/x/tools/cmd/cover: exit status 128
package golang.org/x/tools/cmd/vet: cannot find package "golang.org/x/tools/cmd/vet" in any of:
	/home/travis/.gimme/versions/go1.5.3.linux.amd64/src/golang.org/x/tools/cmd/vet (from $GOROOT)
	/home/travis/gopath/src/golang.org/x/tools/cmd/vet (from $GOPATH)
make: *** [install-travis] Error 1
```

@danmcp this seems like a Travis infra issue - we're exceeding rate limits?

**Comment by liggitt** [comment] 2016-03-21 13:35
dupe of https://github.com/openshift/origin/issues/8166

**Closed by liggitt** 2016-03-21 13:35 UTC
