### ISSUE TITLE
Panic when starting with loglevel=9

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#5128] opened 2015-10-14 18:38 UTC
```
vagrant@localhost:~/go/src/github.com/openshift/origin (always-chcon-node-volume-dir) sudo _output/local/bin/linux/amd64/openshift start --master-config=foo/master/master-config.yaml --node-config=foo/node-localhost.localdomain/node-config.yaml --loglevel=9
panic: interface conversion: http.RoundTripper is *unversioned.DebuggingRoundTripper, not *http.Transport

goroutine 1 [running]:
github.com/openshift/origin/pkg/cmd/server/etcd.EtcdClient(0xc8203841c0, 0x1, 0x4, 0xc8200c71a0, 0x11, 0xc8200bfe30, 0x21, 0xc8200bfe90, 0x21, 0x4c600a, ...)
        /home/vagrant/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/etcd/etcd.go:103 +0x2f5
github.com/openshift/origin/pkg/cmd/server/origin.BuildMasterConfig(0x0, 0x0, 0x0, 0x0, 0xc8200f2d40, 0xc, 0xc8200f2d50, 0x4, 0xc8200c70e0, 0x1c, ...)
        /home/vagrant/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/master_config.go:131 +0x49
github.com/openshift/origin/pkg/cmd/server/start.(*Master).Start(0xc82060b6d8, 0x0, 0x0)
        /home/vagrant/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:377 +0x$
```

The log above is on a branch, but the parent is commit 3de66f7.

**Comment by ncdc** [comment] 2015-10-14 18:44
@smarterclayton @liggitt @deads2k

**Comment by liggitt** [comment] 2015-10-14 18:50
dupe of https://github.com/openshift/origin/issues/4340

**Comment by ncdc** [comment] 2015-10-14 18:51
Thanks

**Closed by liggitt** 2015-10-14 18:50 UTC

**Comment by deads2k** [comment] 2015-10-14 18:53
Oh what a lovely hard cast we've found.
