### ISSUE TITLE
post-rebase: JSONPath output changed from '<nil>' to 'nil'

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10920] opened 2016-09-15 02:39 UTC
```
-os::cmd::expect_success_and_text 'oc get bc/centos -o=jsonpath="{.spec.output.to}"' '^<nil>$'
+os::cmd::expect_success_and_text 'oc get bc/centos -o=jsonpath="{.spec.output.to}"' '^nil$'
```

That's better (although I would quibble that it should be null to match JSON).  Need to note it.

**Comment by bparees** [comment] 2016-09-15 11:52
@smarterclayton so are you making the change to the test as part of the rebase, or what's supposed to happen with this issue?

**Comment by smarterclayton** [comment] 2016-09-15 21:13
We need to understand why it changed, communicate it to users who may be
broken by the change if it is truly intentional.

**Comment by jupierce** [comment] 2016-11-21 22:15
@bparees @smarterclayton This is caused by the fmt.Stringer interface implicitly taking over printing this reference due to some generated protobuf code: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/v1/generated.pb.go#L12715

**Comment by jupierce** [comment] 2016-11-22 14:38
The method is generated by the stringer plugin for gogoprotobuf. It happens for all messages, so there are almost certainly more jsonpaths affected. @smarterclayton it looks like you were active in this module. Thoughts on changing the value back to <nil>?
https://github.com/gogo/protobuf/blob/master/plugin/stringer/stringer.go#L148

**Comment by smarterclayton** [comment] 2016-11-22 15:26
This seems like a bug in the JSONPath printer.  It's unclear to me that
JSONPath should be relying on .String() on these particular objects
(jsonpath should be decomposing all objects into map[string]interface{}, so
calling .String() seems incorrect on a struct).

**Comment by jupierce** [comment] 2016-11-22 16:37
I can only speak to the code path I was tracing. It uses reflection to walk a real instance of the v1.BuildConfig structure (not a map[string]interface{}). It ultimately calls evalToText to serialize the results into a string (https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/util/jsonpath/jsonpath.go#L490)
```
func (j *JSONPath) evalToText(v reflect.Value) ([]byte, error) {
	iface, ok := template.PrintableValue(v)
	if !ok {
		return nil, fmt.Errorf("can't print type %s", v.Type())
	}
	var buffer bytes.Buffer
	fmt.Fprint(&buffer, iface)
	return buffer.Bytes(), nil
}
```

For this use case / .spec.output.to calls evalToText with an *ObjectReference=nil Value . This is wrapped in an interface and passed to Fprint. Fprint ultimately finds that Stringer is implemented by ObjectReference and defers to it.

**Comment by smarterclayton** [comment] 2016-11-22 19:17
Sounds wrong.

On Nov 22, 2016, at 11:37 AM, Justin Pierce <notifications@github.com>
wrote:

I can only speak to the code path I was tracing. It uses reflection to walk
a real instance of the v1.BuildConfig structure (not a
map[string]interface{}). It ultimately calls evalToText to serialize the
results into a string (
https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/util/jsonpath/jsonpath.go#L490
)

func (j *JSONPath) evalToText(v reflect.Value) ([]byte, error) {
	iface, ok := template.PrintableValue(v)
	if !ok {
		return nil, fmt.Errorf("can't print type %s", v.Type())
	}
	var buffer bytes.Buffer
	fmt.Fprint(&buffer, iface)
	return buffer.Bytes(), nil
}

For this use case / .spec.output.to calls evalToText with an
*ObjectReference=nil Value . This is wrapped in an interface and passed to
Fprint. Fprint ultimately finds that Stringer is implemented by
ObjectReference and defers to it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10920#issuecomment-262292203>,
or mute the thread

**Comment by jupierce** [comment] 2016-11-22 21:17
@smarterclayton The implementation or my interpretation? I can at least lend credence to the interpretation. 

With a change to origin/vendor/k8s.io/kubernetes/pkg/api/v1/generated.pb.go

```
func Stack() []byte {
	buf := make([]byte, 1024)
	for {
		n := runtime.Stack(buf, false)
		if n < len(buf) {
			return buf[:n]
		}
		buf = make([]byte, 2*len(buf))
	}
}

func (this *ObjectReference) String() string {
	if this == nil {
		return string(Stack())
	}
	s := strings.Join([]string{`&ObjectReference{`,
		`Kind:` + fmt.Sprintf("%v", this.Kind) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`UID:` + fmt.Sprintf("%v", this.UID) + `,`,
		`APIVersion:` + fmt.Sprintf("%v", this.APIVersion) + `,`,
		`ResourceVersion:` + fmt.Sprintf("%v", this.ResourceVersion) + `,`,
		`FieldPath:` + fmt.Sprintf("%v", this.FieldPath) + `,`,
		`}`,
	}, "")
	return s
}
```

(i.e. return a stack trace instead of "nil")

Running the use case results in:
```
[jupierce@localhost origin]$ oc get bc/centos -o=jsonpath="{.spec.output.to}"
goroutine 1 [running]:
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api/v1.Stack(0x0, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api/v1/generated.pb.go:12718 +0x80
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api/v1.(*ObjectReference).String(0x0, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api/v1/generated.pb.go:12728 +0x48
fmt.(*pp).handleMethods(0xc82057a410, 0x76, 0x0, 0x1)
	/usr/lib/golang/src/fmt/print.go:730 +0x62a
fmt.(*pp).printArg(0xc82057a410, 0x3469b20, 0x0, 0x76, 0x0, 0x0)
	/usr/lib/golang/src/fmt/print.go:806 +0x4a9
fmt.(*pp).doPrint(0xc82057a410, 0xc82042efc8, 0x1, 0x1, 0x0)
	/usr/lib/golang/src/fmt/print.go:1273 +0x24d
fmt.Fprint(0x7fcef00a1de8, 0xc820f188c0, 0xc82042efc8, 0x1, 0x1, 0x1, 0x0, 0x0)
	/usr/lib/golang/src/fmt/print.go:222 +0x67
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/jsonpath.(*JSONPath).evalToText(0xc820c6e3f0, 0x3469b20, 0xc82051ee60, 0x196, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/jsonpath/jsonpath.go:496 +0x2d7
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/jsonpath.(*JSONPath).PrintResults(0xc820c6e3f0, 0x7fcef01231c0, 0xc820036010, 0xc820f2f3e0, 0x1, 0x1, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/jsonpath/jsonpath.go:122 +0xf0
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/jsonpath.(*JSONPath).Execute(0xc820c6e3f0, 0x7fcef01231c0, 0xc820036010, 0x35ec300, 0xc82051ec80, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/jsonpath/jsonpath.go:70 +0x131
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl.(*JSONPathPrinter).PrintObj(0xc820eb9380, 0x7fcef01304d8, 0xc82051ec80, 0x7fcef01231c0, 0xc820036010, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:2457 +0x289
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc820926000, 0x7fcef01231c0, 0xc820036010, 0x7fcef01231c0, 0xc820036018, 0xc820527440, 0xc820779ec0, 0x1, 0x2, 0xc820617bc0, ...)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:366 +0x208c
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc820527440, 0xc820779ec0, 0x1, 0x2)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:103 +0xa7
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc820527440, 0xc820779d40, 0x2, 0x2, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc820643680, 0xc820527440, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820643680, 0x0, 0x0)
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
	/home/jupierce/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:33 +0x1a6

```

**Comment by bparees** [comment] 2016-11-28 15:17
@smarterclayton at this point it sounds like an upstream issue, assuming anything is to be done, should we close this and open an issue there?

**Comment by smarterclayton** [comment] 2016-11-28 16:00
Yes I think so.

**Comment by smarterclayton** [comment] 2016-11-28 16:01
I don't know that the change is wrong, but I don't think the change was
intentional and needs to be decided.  And it probably shouldn't even be
nil, it should be "null" (which is more consistent with JSONPath).

**Comment by bparees** [comment] 2017-03-22 14:34
this now outputs nothing at all:

```
sample-app (master)$ oc get bc/centos -o=jsonpath="{.spec.output.to}"
sample-app (master)$ 
```

**Closed by bparees** 2017-03-22 14:34 UTC
Labels: area/tests, priority/P2
