### ISSUE TITLE
imageConfig.format not working as expected with origin

### ISSUE THREAD

**Issue by bkkhoo** [openshift/origin#13065] opened 2017-02-22 21:20 UTC
according to doc (https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-image-config
View Less), we should be able able to set the imageConfig.format option in /etc/origin/master/master-config.yaml and /etc/origin/node/node-config.yaml to something like the following:
registry.blah.com/openshift/origin-${component}:${version}

with the above configuration, openshift should pull system component images from registry.blah.com, instead of falling to docker.io.

i tested the imageConfig.format setting on my cluster.

when i created a redis app with 'oc new-app redis', the following was observed:
1) openshift pulled the origin-pod image using the imageConfig.format option
2) openshift ignored the imageConfig.format option when pulling the origin-deployer image

the imageConfig.format setting is not working as expected.

when testing the same setup using setting with openshift enterprise version 3.3.1.7, both ose-pod and ose-deployer images were pulled from the register setting in imageConfig.format.

issue with openshift origin ?

##### Version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.osop.rhcloud.com:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. on all nodes, change imageConfig.format option in /etc/origin/master/master-config.yaml and /etc/origin/node/node-config.yaml to something like the following (registry.blah.com is bogus unreachable registry):
registry.blah.com/openshift/origin-${component}:${version}
2. restart master-api and node services on all node
3. create new app:
oc new-app redis
4. the deployer pod should fail to deploy, since the node cannot pull the origin-pod from the bogus registry
5. manually pull the origin-pod image from docker.io:
docker pull docker.io/openshift/origin-pod:v1.3.1
6. tag the the origin-pod image with the bogus registry (this is to make it available so that it will proceed on):
docker tag docker.io/openshift/origin-pod:v1.3.1 registry.blah.com/openshift/origin-pod:v1.3.1
7. the deployer pod deployed successfully, but the origin-deployer image is pulled from docker.io instead of fro the bogus registry.blah.com

##### Current Result
1) openshift pulled the origin-pod image using the imageConfig.format option
2) openshift ignored the imageConfig.format option when pulling the origin-deployer image

##### Expected Result
1) openshift pull the origin-pod image using the imageConfig.format option
2) openshift should also pull the imageConfig.format option when pulling the origin-deployer image

##### Additional Information
test done:
=========
i tested imageConfig.format option in the origin clusterm, using the following imageConfig.format:
registry.blah.com/openshift1/origin-${component}:${version}

on this cluster, the host registry.blah.com is purposely set to be unreachable to see the error events.

after using 'oc new-app redis' to create a new app, i am seeing the following error event for the redis-1-deploy pod:
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----					-------------	--------	------		-------
  2m		2m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned redis-1-deploy to bkhoo-node01.osop.rhcloud.com
  2m		34s		4	{kubelet bkhoo-node01.osop.rhcloud.com}			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for registry.blah.com/openshift/origin-pod:v1.3.1, this may be because there are no credentials on this request.  details: (unable to ping registry endpoint https://registry.blah.com/v0/\nv2 ping attempt failed with error: Get https://registry.blah.com/v2/: dial tcp: lookup registry.blah.com on 172.19.16.22:53: no such host\n v1 ping attempt failed with error: Get https://registry.blah.com/v1/_ping: dial tcp: lookup registry.blah.com on 172.19.16.22:53: no such host)"

  1m	10s	6	{kubelet bkhoo-node01.osop.rhcloud.com}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"registry.blah.com/openshift/origin-pod:v1.3.1\""

i manually pulled and tagged the origin-pod image on the node:
docker pull docker.io/openshift/origin-pod:v1.3.1
docker tag docker.io/openshift/origin-pod:v1.3.1 registry.blah.com/openshift/origin-pod:v1.3.1

once the origin-pod image is made available on the node, openshift proceed to pull the origin-deployer image from:
openshift/origin-deployer:v1.3.1 (which resulted in docker.io registry)

instead of from:
registry.blah.com/openshift/origin-deployer:v1.3.1

The following showed the error event for the redis-1-deploy pod:
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----					-------------	--------	------		-------
  4m		4m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned redis-1-deploy to bkhoo-node01.osop.rhcloud.com
  4m		1m		5	{kubelet bkhoo-node01.osop.rhcloud.com}			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for registry.blah.com/openshift/origin-pod:v1.3.1, this may be because there are no credentials on this request.  details: (unable to ping registry endpoint https://registry.blah.com/v0/\nv2 ping attempt failed with error: Get https://registry.blah.com/v2/: dial tcp: lookup registry.blah.com on 172.19.16.22:53: no such host\n v1 ping attempt failed with error: Get https://registry.blah.com/v1/_ping: dial tcp: lookup registry.blah.com on 172.19.16.22:53: no such host)"

  4m	35s	16	{kubelet bkhoo-node01.osop.rhcloud.com}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"registry.blah.com/openshift/origin-pod:v1.3.1\""

  17s	17s	1	{kubelet bkhoo-node01.osop.rhcloud.com}	spec.containers{deployment}	Normal	Pulling	pulling image "openshift/origin-deployer:v1.3.1"

**Comment by miminar** [comment] 2017-03-09 11:38
I couldn't reproduce this on recent master (pre 1.6). I'll try the same with 1.5.

**Comment by miminar** [comment] 2017-03-09 12:16
I can reproduce neither on `v1.5.0-alpha.3` with Docker `docker-common-1.12.6-6.gitae7d637.fc25.x86_64`. I'll try with 1.4 as well.

**Comment by miminar** [comment] 2017-03-09 14:58
I failed to reproduce even on v3.4.1.10 with Docker `docker-common-1.10.3-55.gite03ddb8.fc24.x86_64`.

@pweil- Is this a severe issue that needs to be fixed in 3.3?

**Comment by pweil-** [comment] 2017-03-09 15:05
@miminar I'm lowering severity but as 3.3 is still used by many people I'm curious as to why OCP would be pulling correctly but Origin is not.

**Comment by miminar** [comment] 2017-03-13 07:56
@bkkhoo Can you please include a version of your docker daemon? I smell this is a Docker problem.

**Comment by bkkhoo** [comment] 2017-03-13 15:09
[root@bkhoo-master01 ~]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-57.el7.x86_64
 Go version:      go1.6.2
 Git commit:      79ebcd8-unsupported
 Built:           Thu Oct 20 14:37:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-57.el7.x86_64
 Go version:      go1.6.2
 Git commit:      79ebcd8-unsupported
 Built:           Thu Oct 20 14:37:17 2016
 OS/Arch:         linux/amd64

**Comment by bparees** [comment] 2018-02-06 20:18
@miminar any other thoughts or should we close this as can't recreate?

**Closed** 2018-07-07 00:44 UTC
Labels: component/apps, kind/bug, lifecycle/rotten, priority/P2
