### ISSUE TITLE
terminal emulation with oc rsh (or exec) is broken: possibly missing SIGWINCH handling

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#6869] opened 2016-01-28 12:54 UTC
Interactive terminal applications (e.g. less) don't scroll correctly, print on the wrong part of the terminal or behave erratically in other ways. 

They do work with a 80x24-terminal, so I assume SIGWINCH signals are not handled correctly (or at all).

I can reproduce with e.g. `less /etc/services` on any container running.

It does work with `docker exec` btw, so this is somewhere within openshift/kubernetes.

Aside: It sets TERM=dump (as is docker exec) instead of using the TERM environment of the terminal it is running from.

**Comment by ncdc** [comment] 2016-02-01 14:33
Dupe of #2284

**Closed by ncdc** 2016-02-01 14:33 UTC
Labels: component/cli, priority/P2
