### ISSUE TITLE
Error getting logs in v3.7.0-alpha.1

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16118] opened 2017-09-03 20:44 UTC
```
$ oc start-build bc/kubernetes-autoscaler-binary --follow
build "kubernetes-autoscaler-binary-3" started
Cloning "https://github.com/openshift/kubernetes-autoscaler.git" ...
	Commit:	9df00a75fb688f1ffac739632c2cf9c8a17849cc (Autoscale over unmanaged instance groups)
	Author:	Clayton Coleman <ccoleman@redhat.com>
	Date:	Sat Sep 2 12:05:33 2017 -0400
--> FROM openshift/origin-release:golang-1.8
--> COPY . /go/src/k8s.io/autoscaler
--> RUN cd /go/src/k8s.io/autoscaler/cluster-autoscaler &&     make build-binary
rm -f cluster-autoscaler
go get github.com/tools/godep
GOOS=linux godep go build -o cluster-autoscaler
--> ENV "OPENSHIFT_BUILD_NAME"="kubernetes-autoscaler-binary-3" "OPENSHIFT_BUILD_NAMESPACE"="ci" "OPENSHIFT_BUILD_SOURCE"="https://github.com/openshift/kubernetes-autoscaler.git" "OPENSHIFT_BUILD_COMMIT"="9df00a75fb688f1ffac739632c2cf9c8a17849cc"
--> LABEL "io.openshift.build.commit.ref"="master" "io.openshift.build.commit.message"="Autoscale over unmanaged instance groups" "io.openshift.build.source-location"="https://github.com/openshift/kubernetes-autoscaler.git" "io.openshift.build.name"="kubernetes-autoscaler-binary-3" "io.openshift.build.namespace"="ci" "io.openshift.build.commit.author"="Clayton Coleman \u003cccoleman@redhat.com\u003e" "io.openshift.build.commit.date"="Sat Sep 2 12:05:33 2017 -0400" "io.openshift.build.commit.id"="9df00a75fb688f1ffac739632c2cf9c8a17849cc"
--> Committing changes to ci/kubernetes-autoscaler-binary-3:e84c4924 ...
--> Done
Pushing image docker-registry.default.svc:5000/ci/kubernetes-autoscaler:binaries ...
Pushed 0/4 layers, 0% complete
Pushed 1/4 layers, 25% complete
error streaming logs (unexpected EOF), waiting for build to complete
```

Build then completed successfully

**Comment by bparees** [comment] 2017-09-03 22:20
any chance you can get level 5 logs from the api server while recreating this?

need to see what's happening in here:
https://github.com/openshift/origin/blob/master/pkg/build/registry/buildlog/rest.go#L166-L321

it's possible you're hitting the new context timeout logic i just added, maybe because the server isn't treating this as a long running request?

https://github.com/openshift/origin/blob/master/pkg/build/registry/buildlog/rest.go#L191

**Comment by bparees** [comment] 2017-09-04 04:16
(for my reference: https://github.com/openshift/origin/commit/c083b520b477cb05a2fdfab9b408f2ad3d31aa67)

**Comment by bparees** [comment] 2017-09-05 03:28
doesn't seem to be an issue w/ long running requests, i just stubbed out a 9 minute build and the log streaming had no issue.  So if you can consistently recreate this, i'll still need to see the master logs.

**Comment by smarterclayton** [comment] 2017-09-05 04:17
It was a very short build

On Sep 4, 2017, at 11:28 PM, Ben Parees <notifications@github.com> wrote:

doesn't seem to be an issue w/ long running requests, i just stubbed out a
9 minute build and the log streaming had no issue. So if you can
consistently recreate this, i'll still need to see the master logs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/16118#issuecomment-327062384>,
or mute the thread

**Comment by bparees** [comment] 2017-09-05 04:24
well i guess it's also possible you hit a legit issue w/ streaming logs from a container and the build logs endpoint just proxied that through.  Admittedly i've never seen that, either before or after the init containers change.

**Comment by smarterclayton** [comment] 2017-09-05 13:16
`unexpected EOF` is an actual IO error from golang (it's used in specific cases).  If you are using any buffering / io wrapper layers, you may not be handling this correctly on your own (or in the logging stack, or on the node).

**Comment by smarterclayton** [comment] 2017-09-05 13:16
search for `UnexpectedEOF`

**Comment by bparees** [comment] 2018-02-01 21:14
on further analysis, this EOF is coming from the client as it reads the log stream from the apiserver:
https://github.com/openshift/origin/blob/ddd1f926d749c914e479b2c54e385137a99873c2/pkg/oc/cli/cmd/startbuild.go#L425

Ultimately I think a connection got closed prematurely somewhere.  I was (sort of) able to reproduce this by cntrl-c'ing the api server while streaming logs:

```
error streaming logs (unexpected EOF), waiting for build to complete
Unable to connect to the server: read tcp 127.0.0.1:37550->127.0.0.1:8443: read: connection reset by peer
```

Based on that analysis and the fact that this does not seem to be a recurring issue, i'm closing this.

**Closed by bparees** 2018-02-01 21:14 UTC
Labels: component/build, kind/bug, priority/P2
