### ISSUE TITLE
Pipeline ignores "-n" flag on slave pod

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#15656] opened 2017-08-07 15:42 UTC
When using `oc` commands with `-n` flag to specify the project in an OpenShift pipeline, all `-n` flags are ignored and objects get created in the same project where Jenkins is running.

##### Steps to Reproduce
```
minishift start --openshift-version v3.6.0
minishift addon enable xpaas

oc login -u developer
oc new-project app-dev
oc new-project app-cicd
```
Via web console, go to `app-cicd` project and add to project using the YAML script:
```
apiVersion: v1
kind: BuildConfig
metadata:
  name: sample-pipeline
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
           // define commands
           stage ('Build') {
             sh "oc delete is,bc -l app=mapit -n app-dev"
             sh "oc new-build --name=mapit --image-stream=redhat-openjdk18-openshift --binary=true --labels=app=mapit -n app-dev"
             sh "oc get bc -n app-dev"
             sh "oc get bc -n app-cicd"
           }
        }
    type: JenkinsPipeline
```

Both 'oc get' commands in the pipeline, return the same result and list the buildconfigs in the `app-cicd` project where Jenkins is running.

##### Version
oc v3.5.5.31
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

**Comment by bparees** [comment] 2017-08-09 19:32
@csrwng i feel like this came up before, any recollection?

**Comment by csrwng** [comment] 2017-08-09 19:34
When we last looked at it, I think it was because somehow Jenkins was adding the "-n {namespace}" parameter itself before the arguments passed in the pipeline. It'd be good to add a --loglevel=10 to the invocations to see what's actually going on in the command.

**Comment by bparees** [comment] 2017-08-09 19:36
> When we last looked at it, I think it was because somehow Jenkins was adding the "-n {namespace}" parameter itself before the arguments passed in the pipeline.

was that just with the client plugin?  I can't even imagine how that would be happening with just a shell operation.

**Comment by csrwng** [comment] 2017-08-09 19:38
Yeah, I think it was the client plugin. I don't remember if there's anything on the slave causing issues with the 'oc' binary. Another possibility is that in this case the maven slave has an outdated version of the binary and that this problem has since been fixed.

**Comment by gabemontero** [comment] 2017-08-11 14:27
Don't see how it would be the client plugin, but am investigating.  Have reproduced locally.

And it is just when running in a slave.  If I change the script so that it runs on master, it behaves as expected.

**Comment by gabemontero** [comment] 2017-08-11 14:48
Running with loglevel 10, this has caught my eye:

`I0811 14:28:12.203215      94 merged_client_builder.go:145] Using in-cluster namespace
`

Seeing what that actually means...

**Comment by csrwng** [comment] 2017-08-11 15:33
@gabemontero that means it's picking put the namespace from the namespace file mounted in  /var/secrets/... [some subdirectory].

It seems that it's a bug if that file takes priority over a namespace specified in the command line.

**Comment by gabemontero** [comment] 2017-08-11 15:42
That was my suspicion - thanks for the confirm @csrwng !

So, the oc in the maven slave images is:

```
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

Whereas the jenkins centos image is at:

```
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
```

My guess is there was some bug fixed between 1.5 and 1.6.

Regardless, the slave base Dockerfiles in github.com/openshift/jenkins need to be updated.  They are still pulling in the 1.5 oc.  

Right @bparees ?

**Comment by gabemontero** [comment] 2017-08-11 15:45
Just the centos one I mean ... I'm assuming the atomic-openshift-clients yum pkg points to the 3.6 clients when that image is built.

Where is the right repo to pull the one that has recently been cooked @bparees ?  ci.openshift sufficient ?

**Comment by bparees** [comment] 2017-08-11 15:46
@gabemontero no repo, this needs to be updated:
https://github.com/openshift/jenkins/blob/master/slave-base/Dockerfile#L14

it's a direct download from the github release.

**Comment by bparees** [comment] 2017-08-11 15:46
and while you're at it, you might as well move the jenkins master image to the 3.6.0 final release.

**Comment by bparees** [comment] 2017-08-11 15:47
and then we really need to finish off this PR so we don't have this problem anymore:
https://github.com/openshift/jenkins/pull/319

**Comment by gabemontero** [comment] 2017-08-11 15:53
Sorry ... by "repo", I meant the registry to pull the rhel version of the docker slave image, confirm the oc binary is at a 3.6 level.

**Comment by bparees** [comment] 2017-08-11 15:57
registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7

**Comment by gabemontero** [comment] 2017-08-11 16:01
On Fri, Aug 11, 2017 at 11:46 AM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> no repo, this needs to be
> updated:
> https://github.com/openshift/jenkins/blob/master/slave-base/Dockerfile#L14
>
right that is what I was referring to at the end of
https://github.com/openshift/origin/issues/15656#issuecomment-321847610

**Comment by gabemontero** [comment] 2017-08-11 16:02
rhel slave base is 

```
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
```

looks like we are OK

**Closed** 2017-08-11 17:03 UTC
Labels: component/build, kind/bug, priority/P2

**Comment by gabemontero** [comment] 2017-08-11 17:12
@siamaksade the push jenkins image to docker hub job seems to be working again ... if that continues, the image should be up there within the hour I would think.

**Comment by siamaksade** [comment] 2017-08-16 14:42
@gabemontero Vertified that works on v3.6.173.0.5. Thanx

**Comment by gabemontero** [comment] 2017-08-16 14:47
On Wed, Aug 16, 2017 at 10:42 AM, Siamak Sadeghianfar <
notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> Vertified that works on
> v3.6.173.0.5. Thanx
>

Cool - thanks for the confirm - glad to help !
