### ISSUE TITLE
Triggering build with invalid branch will cause the invoke to fail and return a code 500

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#11736] opened 2016-11-02 17:25 UTC
Following from #11077, Wang has pointed out the following at https://bugzilla.redhat.com/show_bug.cgi?id=1373330 :

Triggering build with invalid branch will cause the invoke to fail and return a code 500 , internal error,. Should we return code 400, i.e. a bad request?

This is effectively a question of where we want to stand on the API backwards compatibility vs otherwise correctness continuum.

Reviewing the return paths, you could argue that there are points where we should be returning 400 bad request, 401 unauthorized, 404 not found and 500 internal error.  Almost certainly the same would apply to the GitHub trigger.  However today it's all 500s.

NB: this issue is not a regression due to #11077 being merged, it's the same behaviour as before that is being questioned.

@smarterclayton please could you provide a view on whether you want this behaviour to change?

@bparees @wanghaoran1988 fyi

**Comment by wanghaoran1988** [comment] 2016-11-03 02:45
I think we should follow the k8s [api conventions](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#http-status-codes)

**Comment by smarterclayton** [comment] 2016-11-03 14:09
Adding new error classes is usually the problem (200->500).  Returning a
more correct error is fine and appropriate.  Any internal error can be made
more specific

On Nov 2, 2016, at 1:25 PM, Jim Minter <notifications@github.com> wrote:

Following from #11077 <https://github.com/openshift/origin/pull/11077>,
Wang has pointed out the following at
https://bugzilla.redhat.com/show_bug.cgi?id=1373330 :

Triggering build with invalid branch will cause the invoke to fail and
return a code 500 , internal error,. Should we return code 400, i.e. a bad
request?

This is effectively a question of where we want to stand on the API
backwards compatibility vs otherwise correctness continuum.

Reviewing the return paths, you could argue that there are points where we
should be returning 400 bad request, 401 unauthorized, 404 not found and
500 internal error. Almost certainly the same would apply to the GitHub
trigger. However today it's all 500s.

NB: this issue is not a regression due to #11077
<https://github.com/openshift/origin/pull/11077> being merged, it's the
same behaviour as before that is being questioned.

@smarterclayton <https://github.com/smarterclayton> please could you
provide a view on whether you want this behaviour to change?

@bparees <https://github.com/bparees> @wanghaoran1988
<https://github.com/wanghaoran1988> fyi

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11736>, or mute the thread

**Comment by bparees** [comment] 2016-11-03 14:14
sounds good, thanks @smarterclayton

**Closed** 2016-11-10 14:27 UTC
Labels: api-approved, component/build, priority/P2
