### ISSUE TITLE
OpenShift 3 Application Lifecycle Sample: Build of frontend fails

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#5137] opened 2015-10-15 11:36 UTC
I have OpenShift V3 installed with ansible. I have master with 2 nodes. I tried to create the 'OpenShift 3 Application Lifecycle Sample'. (I already did it on a project where OpenShift was running in a Docker container and it worked fine). Now it fails with the following error:
```
Couldn't create initial deployment: DeploymentConfig "frontend" is invalid: triggers[0].imageChange.tag: invalid value 'latest', Details: no image recorded for test/origin-ruby-sample:latest
```
The build fails so there isn't a deployment. There aren't build-logs because it looks there was no build. I thought the problem was accessing Docker Hub to get the image but I'm able to login on Docker from my console + I can pull the ruby-20-centos7-image manually.
The build+deploy of the database works fine. I have just the same problem with my cake-php-mysql-example. The database is also fine but the frontend fails with the same error. Even the cake-php example without database is failing. 

I don't know if it's useful to show the logs of the docker registry:
with ```docker ps``` I don't see the container or pod.
But I can see some registry errors but I don't know or this is the issue:
```[root@ip-10-0-0-145 centos]# docker ps -a | grep origin-sti-builder
1a6700c12384        openshift/origin-sti-builder:v1.0.6                                                                       "/usr/bin/openshift-   7 minutes ago       Exited (255) 6 minutes ago                       k8s_sti-build.dded7a99_cakephp-example-1-build_rommel_c3ba0ce8-73cd-11e5-aa41-0216048cc4cf_f2dc621d ```
```

I1016 06:18:54.176694       1 sti.go:74] The value of ALLOWED_UIDS is [1-]
I1016 06:18:54.193289       1 docker.go:211] Image openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f available locally
I1016 06:18:54.193346       1 sti.go:96] Creating a new S2I builder with build config: "Builder Name:\t\tApache 2.4 with PHP 5.5\nBuilder Image:\t\topenshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f\nBuilder Image Version:\t74bd3cb\nBuilder Base Version:\t71a650e\nSource:\t\t\thttps://github.com/openshift/cakephp-ex.git\nOutput Image Tag:\t172.30.153.158:5000/rommel/cakephp-example:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=cakephp-example-1,OPENSHIFT_BUILD_NAMESPACE=rommel,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/cakephp-ex.git\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I1016 06:18:54.195991       1 docker.go:211] Image openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f available locally
I1016 06:18:54.201165       1 sti.go:124] Preparing to build 172.30.153.158:5000/rommel/cakephp-example:latest
I1016 06:18:54.228984       1 clone.go:30] Cloning sources and all GIT submodules into "/tmp/sti772251206/upload/src"
I1016 06:18:58.282655       1 docker.go:211] Image openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f available locally
I1016 06:18:58.282680       1 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I1016 06:18:58.282700       1 download.go:57] Using image internal scripts from: image:///usr/libexec/s2i/assemble
I1016 06:18:58.282708       1 download.go:57] Using image internal scripts from: image:///usr/libexec/s2i/run
I1016 06:18:58.285626       1 docker.go:211] Image openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f available locally
I1016 06:18:58.285644       1 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I1016 06:18:58.285660       1 download.go:57] Using image internal scripts from: image:///usr/libexec/s2i/save-artifacts
I1016 06:18:58.285672       1 sti.go:199] Using assemble from upload/src/.sti/bin
I1016 06:18:58.285679       1 sti.go:199] Using run from image:///usr/libexec/s2i
I1016 06:18:58.285683       1 sti.go:199] Using save-artifacts from image:///usr/libexec/s2i
I1016 06:18:58.285706       1 sti.go:132] Clean build will be performed
I1016 06:18:58.285710       1 sti.go:135] Performing source build from https://github.com/openshift/cakephp-ex.git
I1016 06:18:58.285714       1 sti.go:145] Running S2I script in 172.30.153.158:5000/rommel/cakephp-example:latest
I1016 06:18:58.285720       1 sti.go:345] Using image name openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f
I1016 06:18:58.285729       1 sti.go:349] No .sti/environment provided (no environment file found in application sources)
I1016 06:18:58.365292       1 docker.go:361] Both scripts and untarred source will be placed in '/tmp'
I1016 06:18:58.365319       1 docker.go:497] Creating container using config: {Hostname: Domainname: User: Memory:0 MemorySwap:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[OPENSHIFT_BUILD_NAME=cakephp-example-1 OPENSHIFT_BUILD_NAMESPACE=rommel OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/cakephp-ex.git] Cmd:[/bin/sh -c tar -C /tmp -xf - && /tmp/scripts/assemble] DNS:[] Image:openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f Volumes:map[] VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[]}
I1016 06:18:59.875205       1 docker.go:508] Attaching to container
I1016 06:18:59.877756       1 docker.go:514] Starting container
I1016 06:19:00.279043       1 docker.go:448] Waiting for container
I1016 06:19:00.640130       1 sti.go:407] ---> Installing application source...
I1016 06:19:04.834283       1 docker.go:450] Container wait returns with 0 and <nil>
I1016 06:19:04.834301       1 docker.go:457] Container exited
I1016 06:19:04.834317       1 docker.go:536] Invoking postExecution function
I1016 06:19:04.834334       1 sti.go:234] No .sti/environment provided (no environment file found in application sources)
I1016 06:19:04.834354       1 docker.go:570] Committing container with config: {Hostname: Domainname: User: Memory:0 MemorySwap:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:false AttachStderr:false PortSpecs:[] ExposedPorts:map[] Tty:false OpenStdin:false StdinOnce:false Env:[OPENSHIFT_BUILD_NAME=cakephp-example-1 OPENSHIFT_BUILD_NAMESPACE=rommel OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/cakephp-ex.git] Cmd:[/usr/libexec/s2i/run] DNS:[] Image: Volumes:map[] VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[io.openshift.build.source-location:https://github.com/openshift/cakephp-ex.git io.k8s.display-name:172.30.153.158:5000/rommel/cakephp-example:latest io.openshift.build.image:openshift/php-55-centos7@sha256:da3b410e6995915c180251d1b7f6521aa6b6ad5706672d23ae207e4a56d6450f io.openshift.build.commit.author:Jakub Hadvig <jhadvig@redhat.com> io.openshift.build.commit.date:Tue Oct 6 10:49:36 2015 +0200 io.openshift.build.commit.id:6afa98d io.openshift.build.commit.ref:master io.openshift.build.commit.message:Merge pull request #19 from jhadvig/hot_deploy2]}
I1016 06:19:27.630225       1 sti.go:265] Successfully built 172.30.153.158:5000/rommel/cakephp-example:latest
I1016 06:19:27.666138       1 cleanup.go:23] Removing temporary directory /tmp/sti772251206
I1016 06:19:27.666153       1 fs.go:99] Removing directory '/tmp/sti772251206'
I1016 06:19:27.702557       1 sti.go:149] Using provided push secret for pushing 172.30.153.158:5000/rommel/cakephp-example:latest image
I1016 06:19:27.702582       1 sti.go:151] Pushing 172.30.153.158:5000/rommel/cakephp-example:latest image ...
F1016 06:19:51.270680       1 builder.go:54] Build error: Failed to push image: Error pushing to registry: Server error: unexpected 400 response status trying to initiate upload of rommel/cakephp-example
[root@ip-10-0-0-145 centos]# 
```

**Comment by rhcarvalho** [comment] 2015-10-16 11:47
Hi @lorenzvth7 could you describe the steps to reproduce it?
What version of OpenShift are you running (`openshift version && oc version`)?

**Comment by lorenzvth7** [comment] 2015-10-16 11:50
oc v1.0.6-2-ge2a02a8
kubernetes v1.1.0-alpha.0-1605-g44c91b1
But I thinks the issue was a broken docker-registry. I've set up a whole new cluster and it's working fine now. Firstly I tried to delete the registry and create it again. But that did not work. I did not really knew how to delete your registry tidy.

**Comment by rhcarvalho** [comment] 2015-10-16 11:54
Ah, ok. I'm happy that it's working for you now. If you cannot reproduce the problem could you please close the issue?

**Comment by lorenzvth7** [comment] 2015-10-16 11:56
Yes I will close it in a minute. But can you maybe specify a way how to delete your registry when it's broken?

**Comment by rhcarvalho** [comment] 2015-10-16 12:25
@lorenzvth7 if you can afford restarting the server, you can do this:

1. Delete the existing registry:
    ```
$ oc delete all -l docker-registry -n default                                    
deploymentconfig "docker-registry" deleted
service "docker-registry" deleted
pod "docker-registry-1-j6m3y" deleted
``` 

2. Recreate the registry using `oadm registry`


Because the new registry service IP will be different, you'll need to restart the server to have your next builds and deployments succeed.

**Comment by lorenzvth7** [comment] 2015-10-16 12:25
Thanks, that's enough!

**Closed** 2015-10-16 12:26 UTC
Labels: component/build, priority/P3
