### ISSUE TITLE
[Feature:DeploymentConfig] deploymentconfigs viewing rollout history [Conformance] should print the rollout history 

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#17875] opened 2017-12-19 14:30 UTC
Test failure; name looks similar to recent issues https://github.com/openshift/origin/issues/15792 https://github.com/openshift/origin/issues/10989 but no idea if related.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17857/test_pull_request_origin_extended_conformance_gce/13247/

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134
Dec 19 12:35:59.681: EOF
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:591
				
[BeforeEach] [Top Level]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:53
[BeforeEach] [Feature:DeploymentConfig] deploymentconfigs
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134
STEP: Creating a kubernetes client
Dec 19 12:35:55.115: INFO: >>> kubeConfig: /tmp/cluster-admin.kubeconfig
STEP: Building a namespace api object
[...]
```

**Comment by tnozicka** [comment] 2017-12-20 16:33
dupe of https://github.com/openshift/origin/issues/17805#issuecomment-352000745

**Closed by tnozicka** 2017-12-20 16:33 UTC
Labels: kind/test-flake, sig/master
