### ISSUE TITLE
When delete a project, the empty directory of the namespace are not deleted in the etcd

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#12254] opened 2016-12-14 09:31 UTC
When delete a project, the empty directory of the namespace are not deleted in the etcd
##### Version
```
openshift v1.5.0-alpha.0+595b6bd-376
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

##### Steps To Reproduce
1. lunch an all in one openshift cluster
2. Create some resources like buildconfigs, deployments
3. delete the project
4. check the etcd:
    ```
    $ etcdctl --cert-file /openshift.local.config/master/master.etcd-client.crt --key-file=/openshift.local.config/master/master.etcd-client.key --ca-file /openshift.local.config/master/ca.crt --endpoint https://127.0.0.1:4001 ls /openshift.io/builds/
    ```

##### Current Result
```
$ etcdctl --cert-file /openshift.local.config/master/master.etcd-client.crt --key-file=/openshift.local.config/master/master.etcd-client.key --ca-file /openshift.local.config/master/ca.crt --endpoint https://127.0.0.1:4001 ls /openshift.io/builds/
/openshift.io/builds/haowang
/openshift.io/builds/haowang1
```

##### Expected Result
the sub dir should be delete under the different resources directory.

**Comment by liggitt** [comment] 2017-01-15 05:23
Dupe of https://github.com/openshift/origin/issues/7032

Wontfix since this isn't an issue with etcd3, which is imminent

**Closed by liggitt** 2017-01-15 05:23 UTC
Labels: component/kubernetes, kind/bug, priority/P3
