### ISSUE TITLE
osc process fails with pipe

### ISSUE THREAD

**Issue by anderssv** [openshift/origin#2680] opened 2015-06-02 09:52 UTC
This command works:

```$ osc process -f application-template-dockerbuild.yaml | osc create -f -```

While doing a pipe to osc process fails:

```
$ cat application-template-dockerbuild.yaml | osc process -f - | osc create -f -
error: cannot convert input to Template: %!(EXTRA *reflect.rtype=*api.List)
error: no objects passed to create
```

On 0.5.3 . I'm guessing this is because it's yaml?

**Comment by mfojtik** [comment] 2015-06-02 11:31
@anderssv there should be no difference between JSON and YAML, this seems like the template has some syntax problem... are you able to create it without using pipe? (`osc process -fapplication-template-dockerbuild.yaml`)

**Comment by anderssv** [comment] 2015-06-02 12:19
@mfojtik yes, it works without the pipe. I see I have a space in my command (first command in the first comment) after '-f', but that should make no difference? Retested, so it seems to be working without the space here too.

**Comment by mfojtik** [comment] 2015-06-05 08:31
@smarterclayton @bparees this is indeed a bug in process. The problem is that when you pipe template to process it is converted to List and it should not be as you need to get parameters as well (the template is not just a simple List)...

I wonder whether we should disable streaming to process or fix it so instead of converting to list it will wait till EOF and then convert the whole content to Template.

**Comment by mfojtik** [comment] 2015-06-05 08:34
Additionally this:

```go
obj, err := resource.NewBuilder(mapper, typer, f.ClientMapperForCommand()).
  NamespaceParam(namespace).RequireNamespace().
  FilenameParam(filename).
  Do().
  Object()
```

seems to decode the stream with Template as `*api.List`

**Comment by bparees** [comment] 2015-06-05 13:38
seems like should be fixing it.

**Comment by mfojtik** [comment] 2015-06-08 17:53
@anderssv the pipe should work now. additionally you can pass multiple templates to process.

@bparees I think we can close this now.

**Comment by bparees** [comment] 2015-06-08 18:08
@anderssv please confirm this resolves your issue.  thanks.

**Comment by anderssv** [comment] 2015-06-09 13:19
Is this in the 0.5.4 release or do I need to download the source to test?

**Comment by mfojtik** [comment] 2015-06-09 13:29
@anderssv it was merged yesterday, so you will have to download the build from source to test this.

@bparees actually we have a test case for this in test-cmd.sh

**Comment by bparees** [comment] 2015-06-12 14:43
closing as fixed, please reopen if you still see issues.

**Closed by bparees** 2015-06-12 14:43 UTC
Labels: component/cli, kind/bug, priority/P2
