### ISSUE TITLE
Registry memory use grows steadily when large numbers of pushes are in progress

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15127] opened 2017-07-11 01:43 UTC
During a large scale build event the registry is observed to continue to grow memory usage unbounded until it OOMs at around 50gb (on this particular set of machines).  It's possible we're caching too much data, or generating too much garbage, or failing to cache data.

![memory](https://www.dropbox.com/s/vor1jgfnx83he1e/Screenshot%202017-07-10%2020.48.02.png?raw=1)

**Comment by smarterclayton** [comment] 2017-07-11 01:43
@openshift/scale-performance-review @miminar @mfojtik we need to capture profiles but this is an extremely suspicious memory usage curve.

**Comment by miminar** [comment] 2017-07-11 09:22
The upstream [in-memory](https://github.com/docker/distribution/blob/master/registry/storage/driver/inmemory/driver.go) cache is being used that never evicts any entries. That needs to be fixed. Related issue is #10217

**Comment by dmage** [comment] 2017-07-11 11:57
cc @legionus

**Comment by smarterclayton** [comment] 2017-07-11 16:58
How can we cap / expire from this cache.  We need a minimal change that does not cache forever.  This means we grow until we blow up and never release.

**Comment by smarterclayton** [comment] 2017-07-11 17:00
Some options - less simplistic cache (perhaps using one that releases items when under memory pressure), fixed cache size, etc.

**Comment by pecameron** [comment] 2017-07-11 17:40
Is this a buffering problem? Is the data just being staged to be written? In this case flow control is needed. Also, a cache has to evict seldom referenced items as capacity is neared. A cache likes to operate at near capacity holding the likely to be needed again items.

**Comment by smarterclayton** [comment] 2017-07-11 17:43
Also, it's likely in memory cache should not cache blobs above a certain size.  That might be the minimal fix.

**Comment by smarterclayton** [comment] 2017-07-11 18:41
Currently a blocker for roll-out of new large clusters, @mfojtik top priority for a small / limited fix for 3.6

**Comment by pweil-** [comment] 2017-07-11 18:55
@dmage please take a look asap since @mfojtik is on PTO right now.  Looks like you were out of blockers anyway, don't want you to be bored :smile:

**Comment by dmage** [comment] 2017-07-11 19:07
It would be helpful to get /debug/pprof/heap profile (and binary file for it) from the registry. I think the problem isn't in the digest cache (17 GB of descriptors?!). And I'm not sure that I can to reproduce a  large scale build event on my laptop.

**Comment by smarterclayton** [comment] 2017-07-11 19:30
we can't, the processes all restarted or need a restart in order to get that data.  I'll continue to look but you'll have to simulate lots of concurrent pushes of unique images

**Comment by smarterclayton** [comment] 2017-07-11 19:32
It's definitely not steady state leakage or caused by pulls, because post restart they all sit at about 100m.  It's definitely changes caused by pushes.

**Comment by smarterclayton** [comment] 2017-07-11 21:41
We have some evidence that the cache is releasing items at steady
state - it's possible that purge is there but isn't running fast
enough to catch up.

**Comment by mfojtik** [comment] 2017-07-12 07:49
@dmage can you check if the internal in which the purge is running is tweakable?

**Comment by dmage** [comment] 2017-07-12 08:21
Is your evidence dropped lines in prometheus? If so, then I still need to investigate which cache causes this problem. The cache which @miminar talks about has no pruning. Moreover, you need to upload about 10 million blobs to make 17 GiB of descriptors. I don't believe that this is possible to do with our registry in 15 minutes.

**Comment by dmage** [comment] 2017-07-12 12:18
On my installation (local file storage) the most memory consumed by creating router (compiling regexps) on each request: https://github.com/openshift/origin/blob/de7602b32119b5829c2c6a83d7e0dafef94912de/vendor/github.com/docker/distribution/registry/handlers/app.go#L744
It's not good, but the garbage collector should release it on next cycle. So it should not grow that much.

**Comment by smarterclayton** [comment] 2017-07-12 14:09
You should also verify this isn't something related to the s3 plugin.  You
can ask on aos for someone to show you the registry config if there are
multiple settings

On Jul 12, 2017, at 8:18 AM, Oleg Bulatov <notifications@github.com> wrote:

On my installation (local file storage) the most memory consumed by
creating router (compiling regexps) on each request:
https://github.com/openshift/origin/blob/de7602b32119b5829c2c6a83d7e0dafef94912de/vendor/github.com/docker/distribution/registry/handlers/app.go#L744
It's not good, but the garbage collector should release it on next cycle.
So it should not grow that much.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15127#issuecomment-314751691>,
or mute the thread

**Comment by dmage** [comment] 2017-07-12 14:18
```
$ go tool pprof -inuse_space ./_output/local/bin/linux/amd64/dockerregistry http://127.0.0.1:6060/debug/pprof/heap
Fetching profile from http://127.0.0.1:6060/debug/pprof/heap
Saved profile in /home/dmage/pprof/pprof.dockerregistry.127.0.0.1:6060.alloc_objects.alloc_space.inuse_objects.inuse_space.016.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top15
13783.97kB of 13783.97kB total (  100%)
Dropped 899 nodes (cum <= 68.92kB)
Showing top 15 nodes out of 121 (cum >= 553.04kB)
      flat  flat%   sum%        cum   cum%
 4049.86kB 29.38% 29.38%  4049.86kB 29.38%  github.com/openshift/origin/vendor/golang.org/x/net/http2.(*ClientConn).frameScratchBuffer
 2502.74kB 18.16% 47.54%  2502.74kB 18.16%  runtime.hashGrow
 1536.30kB 11.15% 58.68%  4039.03kB 29.30%  runtime.mapassign
 1024.05kB  7.43% 66.11%  2613.85kB 18.96%  github.com/openshift/origin/pkg/dockerregistry/server.digestToRepositoryCache.RememberDigest
  553.04kB  4.01% 70.12%   553.04kB  4.01%  runtime.makechan
  528.17kB  3.83% 73.96%   528.17kB  3.83%  regexp.(*bitState).reset
     515kB  3.74% 77.69%      515kB  3.74%  strings.NewReplacer
  514.63kB  3.73% 81.43%   514.63kB  3.73%  regexp/syntax.appendRange
  512.07kB  3.71% 85.14%   512.07kB  3.71%  runtime.rawstringtmp
  512.05kB  3.71% 88.86%   512.05kB  3.71%  regexp/syntax.(*parser).op
  512.02kB  3.71% 92.57%   512.02kB  3.71%  container/list.(*List).PushFront
  512.02kB  3.71% 96.29%   512.02kB  3.71%  github.com/openshift/origin/pkg/dockerregistry/server.(*repositoryBucket).Add
  512.02kB  3.71%   100%   512.02kB  3.71%  vendor/golang_org/x/net/http2/hpack.addDecoderNode
         0     0%   100%   516.64kB  3.75%  github.com/openshift/origin/pkg/api/install.init
         0     0%   100%   553.04kB  4.01%  github.com/openshift/origin/pkg/client.init
(pprof) 
```
Only 13 MiB... But `RememberDigest` looks suspicious.

**Comment by smarterclayton** [comment] 2017-07-12 15:07
The evidence is the graph - it grows steadily and peaks at 50gb when the
machine dies (due to something else being oom killed because of the
registry).  Some memory is not being released on concurrent pushes.

**Comment by smarterclayton** [comment] 2017-07-12 15:10
How many unique images did you push to this registry?

**Comment by dmage** [comment] 2017-07-12 16:10
<details>
<summary>2000 images</summary>

```
$ cat Dockerfile 
FROM busybox
RUN cat /proc/sys/kernel/random/uuid >/random-image-payload
#RUN head -c20971520 /dev/urandom >/random-image-payload
#RUN head -c20971520 /dev/urandom >/random-image-payload
#RUN head -c20971520 /dev/urandom >/random-image-payload
#RUN head -c20971520 /dev/urandom >/random-image-payload
$ cat stress.sh 
#!/bin/bash -efu
registry=127.0.0.1:5000
N=200
#seq 0 $((N-1)) | xargs -n 1 -I "{}" oc new-project "project{}"
docker login -u $(oc whoami) -p $(oc whoami -t) $registry
for i in {1..100}; do
    tag=$registry/project$((RANDOM % N))/img-$(date +%s%N)
    docker build --no-cache -t "$tag" .
    docker push "$tag"
    docker rmi "$tag"
done
$ seq 20 | parallel -N0 -j20 --lb ./stress.sh
```
</details>

**Comment by smarterclayton** [comment] 2017-07-12 16:53
since those images are effectively tiny, it's possible the issue is
correlated to image size.

**Comment by smarterclayton** [comment] 2017-07-12 16:59
If we have to test this by triggering new builds in the affected cluster and gathering profile data from registry, we can (but that's going to take a chunk of time so it's a parallel action)

**Comment by dmage** [comment] 2017-07-12 17:11
Again, I've tested it using local storage. There are interesting constants in S3 driver:
https://github.com/docker/distribution/blob/f86db6b22663a27ba4d278220b7e34be528b1e79/registry/storage/driver/s3-aws/s3.go#L58
https://github.com/docker/distribution/blob/f86db6b22663a27ba4d278220b7e34be528b1e79/registry/storage/driver/s3-aws/s3.go#L62
https://github.com/docker/distribution/blob/f86db6b22663a27ba4d278220b7e34be528b1e79/registry/storage/driver/s3-aws/s3.go#L729
So `driver.copy` can consume up to 3200 MB. And the blob commit virtually is the `driver.copy` call.
And if you have a lot of concurrent commits...

**Comment by smarterclayton** [comment] 2017-07-12 17:15
So *concurrent* blob uploads can each reach up to 3200MB?

**Comment by dmage** [comment] 2017-07-12 17:21
Oops, no, it copies data using S3 server-side copy UploadPartCopy, so it doesn't allocates memory for chunks.

**Comment by dmage** [comment] 2017-07-12 17:37
A blob upload can consume [10 MiB](https://github.com/docker/distribution/blob/f86db6b22663a27ba4d278220b7e34be528b1e79/registry/storage/driver/s3-aws/s3.go#L52), it's not so impressive.

**Comment by dmage** [comment] 2017-07-12 19:10
docker/distribution#1533

**Comment by smarterclayton** [comment] 2017-07-12 19:24
> In general, it might be good to test the current code base under this kind of load then try it with a buffer pool implementation. It may be also worthwhile to track down the caller of io.copyBuffer (likely through io.Copy or elsewhere), since we are seeing large allocation happen there. If we can move both of these to buffer pool, the max RSS should decrease, since less garbage will be generated.

If we think this is culprit we probably need to create a representative test case and then investigate a pooling patch.  We can't afford OOM during high build events and while the GC is good, it appears GC is not good enough.

**Comment by smarterclayton** [comment] 2017-07-12 22:32
Profile from production when a big build spike came in - we peaked at 8gb on one of the instances, here's the cumulative allocation from it:

```
go tool pprof --alloc_space /tmp/dockerregistry /tmp/mem
Entering interactive mode (type "help" for commands)
(pprof) top30
963234.95MB of 1023161.91MB total (94.14%)
Dropped 1410 nodes (cum <= 5115.81MB)
Showing top 30 nodes out of 79 (cum >= 6415.81MB)
      flat  flat%   sum%        cum   cum%
856658.62MB 83.73% 83.73% 856787.77MB 83.74%  github.com/openshift/origin/vendor/github.com/docker/distribution/registry/storage/driver/s3-aws.(*writer).Write
81564.75MB  7.97% 91.70% 81963.37MB  8.01%  github.com/openshift/origin/vendor/github.com/docker/distribution/registry/storage/driver/s3-aws.(*writer).flushPart
 9225.73MB   0.9% 92.60%  9225.73MB   0.9%  regexp.onePassCopy
 7212.26MB   0.7% 93.31% 865039.85MB 84.55%  io.copyBuffer
 6078.19MB  0.59% 93.90%  6078.69MB  0.59%  math/big.putNat
 1025.53MB   0.1% 94.00%  7119.74MB   0.7%  math/big.nat.divLarge
  314.07MB 0.031% 94.03%  6414.31MB  0.63%  math/big.(*Int).GCD
  292.18MB 0.029% 94.06%  7225.46MB  0.71%  regexp/syntax.(*compiler).compile
  241.03MB 0.024% 94.08% 25975.88MB  2.54%  github.com/openshift/origin/vendor/github.com/gorilla/mux.newRouteRegexp
  129.01MB 0.013% 94.09%  5764.57MB  0.56%  regexp/syntax.Parse
  125.02MB 0.012% 94.11% 25456.77MB  2.49%  regexp.compile
   66.51MB 0.0065% 94.11%  8917.37MB  0.87%  github.com/openshift/origin/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.(*signingCtx).build
   57.51MB 0.0056% 94.12% 26054.38MB  2.55%  github.com/openshift/origin/vendor/github.com/gorilla/mux.(*Router).Path
   38.51MB 0.0038% 94.12%  8573.11MB  0.84%  crypto/tls.(*ecdheKeyAgreement).generateServerKeyExchange
   36.51MB 0.0036% 94.13%  9973.99MB  0.97%  crypto/tls.(*serverHandshakeState).doFullHandshake
   28.01MB 0.0027% 94.13%  7147.75MB   0.7%  math/big.nat.div
   28.01MB 0.0027% 94.13%  5195.52MB  0.51%  crypto/tls.(*Conn).clientHandshake
   25.01MB 0.0024% 94.13%  7971.85MB  0.78%  crypto/rsa.decrypt
   22.01MB 0.0022% 94.14%  8441.59MB  0.83%  crypto/rsa.SignPKCS1v15
      18MB 0.0018% 94.14% 986037.22MB 96.37%  net/http.(*conn).serve
```

If we want to stop unbounded growth, it looks like our only options are 

1. try and tune the GC to be more aggressive (unlikely?)
2. have the s3-aws driver pool allocations

**Comment by dmage** [comment] 2017-07-12 23:20
Thank you for the profile! I will investigate why do they have such complicated code for Write and how we can reduce memory allocations.

**Comment by dmage** [comment] 2017-07-13 13:18
The writer has 2 buffers (readyPart, pendingPart) which by default can grow up to 10 MB. In worst cast an image push can take 5 (layers at the same time)*2 (buffers)*10 MB = 100 MB. 170 concurrent pushes can take 17 GB. It's in case we have perfect GC.

**Comment by mfojtik** [comment] 2017-07-13 13:19
@dmage @smarterclayton suggested to re-use the cache if we can (kind of thin pool)

**Comment by smarterclayton** [comment] 2017-07-13 14:40
A couple of other thoughts:

1. we are saturated in network bandwidth upstream at 80mb/s right now.
 that means that allocating more than 80mb/s doesn't make sense.  we may
want to track the rate at which the driver is uploading data and compare it
to the rate at which we are allocating buffers - if one is greater than the
other, we should be waiting
2. it's acceptable to slow down the rate of chunk creation by temporarily
delaying them, or to create smaller buffers when we are at a higher rate
(i.e. create the smallest possible buffer size when we are above the
network rate)
3. it's acceptable to also exert back pressure on clients in terms of high
concurrency, but it would be *better* if we didn't have to do that (i.e.
the back pressure is exerted naturally by the driver based on the upload
rate)
4. ben already has some retries in the builder, we will add more, and at
WORST we can add a new retry type (registry returns 429 and we try again).
 however, this only works for our clients, not for end users, so this would
be fixing only a specific set of problems and not applicable to everyone

Re flow control if you want to have a deeper discussion Jordan and I are
available to talk

**Comment by dmage** [comment] 2017-07-13 16:52
I've tried to add sync.Pool for driver buffers, but it reduces memory consumption only for 15%.
Also I've tried to remove these buffers completely and to stream the body directly from the client to S3, but unfortunately you need to compute SHA256 of the body:
 *  [X-Amz-Content-Sha256](https://github.com/aws/aws-sdk-go/blob/a53a77724a72a34f765ceca0af769a3adc94dee4/aws/signer/v4/v4.go#L667)
 *  [makeSha256Reader](https://github.com/aws/aws-sdk-go/blob/a53a77724a72a34f765ceca0af769a3adc94dee4/aws/signer/v4/v4.go#L711)
So it wants to read input at least twice.

Therefore it seems it unavoidable to have pretty large buffer for each request.

We need to add threshold for used memory or number of concurrent requests. If we already have more than N requests, we can delay/drop new one. Still not sure which metric and which action would be better.

**Comment by smarterclayton** [comment] 2017-07-14 04:14
How did you calculate the 15% savings (i.e., how parallel were your pushes)?

You may have to use something like vegeta to simulate truly massive
concurrency.

As far as rate, I'd prefer to tie allocation to some near multiple of the
rate we are uploading.  If we're getting 80mb/s up, we should be allocating
near 80mb/s.  Or simply cap at some multiple of our expected memory
ceiling.  We definitely do not want to have more simultaneous chunks
running than 60-80% of min(mem limit, available mem), so this may just be
two separate rate limits.  "Allocate near network rate" and "don't allocate
more than we have".

Another test that may be relevant - if we set a *fixed* number of blocks we
allocate at any one time that is a small multiple of bandwidth, do we get
the same upload rate to s3 - i.e. How much parallelism to s3 before we see
diminishing returns?  If we only need 20 parallel blocks to saturate our
network connection, then there's no point to running >20 at once.



On Jul 13, 2017, at 12:52 PM, Oleg Bulatov <notifications@github.com> wrote:

I've tried to add sync.Pool for driver buffers, but it reduces memory
consumption only for 15%.
Also I've tried to remove these buffers completely and to stream the body
directly from the client to S3, but unfortunately you need to compute
SHA256 of the body:

   - X-Amz-Content-Sha256
   <https://github.com/aws/aws-sdk-go/blob/a53a77724a72a34f765ceca0af769a3adc94dee4/aws/signer/v4/v4.go#L667>
   - makeSha256Reader
   <https://github.com/aws/aws-sdk-go/blob/a53a77724a72a34f765ceca0af769a3adc94dee4/aws/signer/v4/v4.go#L711>
   So it wants to read input at least twice.

Therefore it seems it unavoidable to have pretty large buffer for each
request.

We need to add threshold for used memory or number of concurrent requests.
If we already have more than N requests, we can delay/drop new one. Still
not sure which metric and which action would be better.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15127#issuecomment-315137412>,
or mute the thread

**Comment by smarterclayton** [comment] 2017-07-14 04:18
I'm seeing a fair number of sites saying max parallel chunk upload of
32 or 64 is sufficient to saturate ec2 to s3.

Maybe we should rate limit with a fixed rate that we calculate based
on either men limits or an env var.

**Comment by smarterclayton** [comment] 2017-07-14 06:37
If number of parallel blocks peaks throughout at a low number, then a more
advanced control algorithm variant would be a bucket limiter for number of
parallel blocks.  A background process would measure the rate of block
upload.  It would periodically allow a few more or a few less blocks and
measure whether the rate of upload went up or down and then adjust the
bucket limiter up or down.  Ie let it self tune for maximum throughput, and
put downward pressure on number of blocks by adding an inverse term
(expected gain - total blocks / factor).  There may be some stock code
already in our vendor tree that implements a control loop like that.  That
could be an exploratory topic later

On Jul 13, 2017, at 12:52 PM, Oleg Bulatov <notifications@github.com> wrote:

I've tried to add sync.Pool for driver buffers, but it reduces memory
consumption only for 15%.
Also I've tried to remove these buffers completely and to stream the body
directly from the client to S3, but unfortunately you need to compute
SHA256 of the body:

   - X-Amz-Content-Sha256
   <https://github.com/aws/aws-sdk-go/blob/a53a77724a72a34f765ceca0af769a3adc94dee4/aws/signer/v4/v4.go#L667>
   - makeSha256Reader
   <https://github.com/aws/aws-sdk-go/blob/a53a77724a72a34f765ceca0af769a3adc94dee4/aws/signer/v4/v4.go#L711>
   So it wants to read input at least twice.

Therefore it seems it unavoidable to have pretty large buffer for each
request.

We need to add threshold for used memory or number of concurrent requests.
If we already have more than N requests, we can delay/drop new one. Still
not sure which metric and which action would be better.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15127#issuecomment-315137412>,
or mute the thread

**Comment by liggitt** [comment] 2017-07-15 18:28
seems like we want something similar to what was added in https://github.com/docker/distribution/pull/1906 - defaultMultipartCopyMaxConcurrency

I'm not sure if that limits across pushes or just within a single push, though

**Comment by smarterclayton** [comment] 2017-07-15 19:46
We would definitely need cross pushes with 1k+ concurrent pushes (1-5
layers)

On Jul 15, 2017, at 2:28 PM, Jordan Liggitt <notifications@github.com>
wrote:

seems like we want something similar to what was added in
docker/distribution#1906 <https://github.com/docker/distribution/pull/1906>
- defaultMultipartCopyMaxConcurrency

I'm not sure if that limits across pushes or just within a single push,
though

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15127#issuecomment-315552980>,
or mute the thread

**Comment by harshavardhana** [comment] 2017-09-11 07:05
Would it possible for folks here to validate the work in this regard without writing a new driver? 

// cc @krishnasrinivas https://github.com/krishnasrinivas/distribution/commit/26aa7e82868ecd991bb4dfb6846900771b6da942

**Comment by legionus** [comment] 2017-09-11 09:31
@harshavardhana Reusing the buffers will not solve the memory problem, because increased memory consumption occurs with parallel pushes. This means the buffer will be used аor each request even if later they are re-used.

**Comment by bparees** [comment] 2017-10-03 17:55
Rate limiting capabilities were added (but must be manually configured/enabled) to address this.  We also have a trello card to default rate limiting on when using the s3 driver:  https://trello.com/c/wpOMfa0X

so i am closing this issue.

**Closed by bparees** 2017-10-03 17:55 UTC
Labels: area/performance, component/imageregistry, priority/P1
