### ISSUE TITLE
osc describe locks up with new binary

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#1410] opened 2015-03-23 05:26 UTC
brought down the following build:
https://ci.openshift.redhat.com/jenkins/job/openshift3_ami/1093/artifact/origin/artifacts/release/

There was a previous installation on my machine. I did the following before replacing the binary

Erase the docker-registry service
Remove any Docker containers running
   docker ps
   docker kill “container id”
Delete the OpenShift directory
   rm -r $HOME/openshift
Then follow directions above “Installing and Running OpenShift”

I then added the registry service back with the following command:
cd $HOME/openshift
sudo chmod +r ./openshift.local.certificates/openshift-client/key.key
./openshift ex registry --create --credentials="${KUBECONFIG}"

When I do ./osc get services I can see the service listed (along with the kubernetes services)

But when I do:

./osc describe service docker-registry

the command just stays processing and I have to ctrl-c to get out of it. Here is what I see in the logs:

I0322 21:56:20.863721    2168 proxier.go:556] Opened iptables from-containers portal for service "kubernetes" on TCP 172.30.17.2:443
I0322 21:56:20.868044    2168 proxier.go:567] Opened iptables from-host portal for service "kubernetes" on TCP 172.30.17.2:443
I0322 21:56:20.872756    2168 proxier.go:556] Opened iptables from-containers portal for service "kubernetes-ro" on TCP 172.30.17.1:80
I0322 21:56:20.877745    2168 proxier.go:567] Opened iptables from-host portal for service "kubernetes-ro" on TCP 172.30.17.1:80
I0322 22:01:19.974790    2168 factory.go:32] about to watch IRs: 38
I0322 22:02:42.426541    2168 proxier.go:556] Opened iptables from-containers portal for service "docker-registry" on TCP 172.30.17.151:5000
I0322 22:02:42.431211    2168 proxier.go:567] Opened iptables from-host portal for service "docker-registry" on TCP 172.30.17.151:5000
E0322 22:06:19.840498    2168 iowatcher.go:93] Unable to decode an event from the watch stream: local error: unexpected message
E0322 22:06:19.980295    2168 iowatcher.go:93] Unable to decode an event from the watch stream: local error: unexpected message
I0322 22:06:20.124643    2168 factory.go:32] about to watch IRs: 38
E0322 22:06:20.166341    2168 iowatcher.go:93] Unable to decode an event from the watch stream: local error: unexpected message
E0322 22:06:20.166395    2168 iowatcher.go:93] Unable to decode an event from the watch stream: local error: unexpected message
E0322 22:06:20.931561    2168 iowatcher.go:93] Unable to decode an event from the watch stream: local error: unexpected message

**Comment by thesteve0** [comment] 2015-03-23 05:32
Did this again and get the same lock up with 'osc describe kubernetes' as well. 

CPU is at 100%. OSC get services has no problem.

**Comment by sosiouxme** [comment] 2015-03-23 17:38
does sound like a duplicate of #1364, fix is merging...

**Closed** 2015-03-23 18:03 UTC
