### ISSUE TITLE
infra flake "Failure talking to yum: [Errno 2] No such file or directory: '/var/cache/yum/x86_64/7/epel/gen/primary_db.sqlite'"

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#15801] opened 2017-08-16 17:43 UTC
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/6077/consoleFull#-3225954895849c75fe4b0052e114d805c

    TASK [Ensure openshift-ansible installer package deps are installed] ***********
    ...
    failed: [ci-prtest-5a37c28-6077-ig-n-0zz5] (item=python-dbus) => {"failed": true, "item": "python-dbus", "msg": "Failure talking to yum: [Errno 2] No such file or directory: '/var/cache/yum/x86_64/7/epel/gen/primary_db.sqlite'"}

some background task doing something with yum behind the installer's back maybe?

**Comment by jupierce** [comment] 2017-08-16 23:20
Seems to affect yum in general: https://bugzilla.redhat.com/show_bug.cgi?id=1479533 . The problem is spurious and looks like retrying the operation will help.

**Comment by jupierce** [comment] 2017-08-16 23:21
Adding @sdodson since openshift-ansible will need to perform the retry.

**Comment by sdodson** [comment] 2017-08-24 12:42
Dupe of #14772 and we've removed epel so this particular issue should never happen again but we're still prone to external failures and we're working to add retries to all of the yum tasks as they're prone to failure due to external systems.

**Closed by sdodson** 2017-08-24 12:42 UTC
Labels: component/internal-tools, kind/test-flake, priority/P1
