### ISSUE TITLE
TLS handshake EOF error in Origin 1.3

### ISSUE THREAD

**Issue by allen13** [openshift/origin#11017] opened 2016-09-20 16:17 UTC
Getting TLS handshake EOF error
I0920 16:10:37.239042   16846 server.go:2161] http: TLS handshake error from 192.0.2.101:37408: EOF

No obvious issues with functionality but errors are never good. 

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
centos 7.2
docker 1.10

##### Steps To Reproduce
1. openshift server

I also ran this with my custom config but I figured it would simply things if I could show that the error happens with the default all-in-one setup

**Comment by liggitt** [comment] 2016-09-20 16:20
Did you access the server from a browser or CLI that prompted to accept a connection to a server with an unknown signer? That's normally the cause of that log message, and is perfectly normal

**Comment by liggitt** [comment] 2016-09-20 16:22
Given the error is expected in the above cases, closing unless functional issues are noticed

**Closed by liggitt** 2016-09-20 16:22 UTC

**Comment by allen13** [comment] 2016-09-20 16:24
It happens in complete isolation on a clean install of cent 7 with no input. This did not happen in previous versions. It seems like inter-server chatter is the cause.
