### ISSUE TITLE
TestWebhookGitHubPushWithImageStream flakes in Travis

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4309] opened 2015-08-21 16:45 UTC
Seeing [this](https://travis-ci.org/openshift/origin/jobs/76630760#L8004):
```
--- FAIL: TestWebhookGitHubPushWithImageStream-16 (6.69s)
	webhookgithub_test.go:278: Wrong response code, expecting 200, got %!s(int=500): {
		  "kind": "Status",
		  "apiVersion": "v1",
		  "metadata": {},
		  "status": "Failure",
		  "message": "Internal error occurred: could not generate a build: buildconfig \"pushbuild\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
		  "reason": "InternalError",
		  "details": {
		    "causes": [
		      {
		        "message": "could not generate a build: buildconfig \"pushbuild\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again"
		      }
		    ]
		  },
		  "code": 500
		}!
FAIL
```

@ncdc

**Comment by liggitt** [comment] 2015-08-21 17:13
dupe of #4245

**Closed by liggitt** 2015-08-21 17:13 UTC
