### ISSUE TITLE
PVC binding is racy

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4829] opened 2015-09-28 18:33 UTC
It is possible to get two PersistentVolumeClaims bound to the same PersistentVolume. Two methods, starting with no PVs or PVCs:

1. Create a PV, and then two PVCs at the same time.
2. Create the PVCs, then create a PV.

I have seen this consistently. If I create the PV first and space out creating the two PVCs by a few seconds, it correctly binds one and not the other.

**Comment by markturansky** [comment] 2015-10-01 12:16
There is a BZ for this, too.  I will attempt to reproduce.

**Comment by markturansky** [comment] 2015-10-13 14:20
This is fixed by the new controller written for 3.1 (to be merged after the current rebase is complete):

https://github.com/kubernetes/kubernetes/pull/14537

**Comment by pweil-** [comment] 2015-10-27 21:39
It looks like this is linked to https://github.com/kubernetes/kubernetes/pull/14537 which was expected to be patched by https://github.com/openshift/origin/pull/5217.  #5217 is not going in to 3.1 based on the comments.  The upstream is still under review as well.

Since this is p0 are we expecting to pull in just the controller piece of this, another solution, or re-prioritize?

**Comment by markturansky** [comment] 2015-10-27 23:16
I am reproducing upstream in Kube so that I can get a clean commit into OpenShift.  I believe I understand where the race is.

**Comment by pweil-** [comment] 2015-10-28 12:56
:+1:

**Comment by markturansky** [comment] 2015-10-28 15:10
https://github.com/kubernetes/kubernetes/pull/16432

**Comment by markturansky** [comment] 2015-10-28 18:12
#5467 patch into Origin

**Closed** 2015-11-04 21:20 UTC
Labels: component/storage, kind/bug, priority/P0
