### ISSUE TITLE
oc get pods --all-namespaces should not return an error

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7238] opened 2016-02-11 23:26 UTC
This command should display all pods that I can access instead of returning an error

```
Error from server: User "yann.moisan" cannot list all pods in the cluster
```

**Comment by liggitt** [comment] 2016-02-12 02:39
--all-namespaces specifically maps to an unnamespaced API call, which requires cluster level permissions. We would not make that *sometimes* return results that were not actually from all namespaces.

**Comment by liggitt** [comment] 2016-02-12 02:42
The API is not generally designed to return ACL filtered results. There is actually only a single API like that, which is listing projects.

**Comment by YannMoisan** [comment] 2016-02-12 07:57
Let me explain what I want to achieve :

I use one project by environment, so I have

```
foobar-int
foobar-preprod
foobar-prod
```

My use case is to select all pods with a given selector on my projects.

I'd like to be able to run `oc get pods --all-namespaces -l "app=foobar"`

**Comment by vbehar** [comment] 2016-02-12 08:03
or `oc get pods --my-namespaces -l "app=foobar"` ;-)

**Comment by vbehar** [comment] 2016-02-12 08:07
or `oc get pods -n p1,p2 -l "app=foobar"` if `-n` could supports multiple namespaces - yes, I just saw https://github.com/openshift/origin/pull/7216#issuecomment-182990276 ;-)

**Comment by sspeiche** [comment] 2017-02-16 18:58
This is becoming increasingly importance as customers have typically split responsibility on the cluster: Operators (keep the infrastructure alive), DevOps Engineers (make sure the apps are running on OpenShift) and Developers (write the stuff, they are sometimes the DevOps Engineers).

The problem is the DevOps Engineers have access to MANY projects, if not all, but a few of the infrastructure ones (like openshift-infra, etc). 

Since they support so many projects, they often want to use `--all-namespaces` (or `--all-namespaces --skiperrors`) to be able to look at all pods on the cluster for example.

It would be great to just have `oc get pods --all-namespaces` just work on projects the user has access to.

**Comment by liggitt** [comment] 2017-02-16 19:03
without API support for cross-namespace ACL-filtered listing, I don't think this will happen.

**Comment by fabianofranz** [comment] 2017-02-16 19:05
About the CLI usability perspective, although having two flags that do *almost* the same thing can be error prone, I like @vbehar idea of `--my-namespaces`, with the addition of suggesting it to the user in case he tried `--all-namespaces` and got permission errors.

That said @liggitt couldn't we just make the implementation of `--my-namespaces` the same of `--all-namespaces`, but suppressing permission the errors?

**Comment by liggitt** [comment] 2017-02-16 19:07
> couldn't we just make the implementation of --my-namespaces the same of --all-namespaces, but suppressing permission the errors?

no, `--all-namespaces` does a single LIST API call at the cluster scope, it doesn't do *n* API calls for all the namespaces

**Comment by sspeiche** [comment] 2017-02-16 19:39
So this sounds like either:
a) won't fix, work around is to first do `oc get projects` and then feed `oc get pods -n $`
b) someone can open an API request to support this

So which direction would be advisable?

**Comment by juanvallejo** [comment] 2018-03-13 15:36
> So this sounds like either:
> a) won't fix, work around is to first do oc get projects and then feed oc get pods -n $
> b) someone can open an API request to support this

This sounds like an API request. Closing, please re-open if further discussion is needed

**Closed by juanvallejo** 2018-03-13 15:36 UTC
Labels: component/cli, lifecycle/rotten, priority/P2

**Comment by guiqui** [comment] 2023-09-15 07:18
It really sucks that the K8 API does not filter and we need to do a request per namespace.
What happens if you don't have cluster-level access the the namespaces, you are not able to query what namespaces you have rights to.
