### ISSUE TITLE
HPA values incorrect post 1.5 upgrade

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#13907] opened 2017-04-27 07:20 UTC
Post v1.5.0 upgrade the HPA values that were 70% are now showing as 700% in the web console

In the API `targetCPUUtilizationPercentage` is showing at 140%

When setting the HPA in the webconsole back to 70% the `targetCPUUtilizationPercentage` is now 35%

**Comment by andrewklau** [comment] 2017-04-27 07:22
@smarterclayton could you check this before cutting a new release?

**Comment by spadgett** [comment] 2017-04-27 12:32
@andrewklau Do you have a cluster resource override set in master-config.yaml?

https://docs.openshift.org/latest/admin_guide/overcommit.html#configuring-masters-for-overcommitment

**Comment by andrewklau** [comment] 2017-04-27 12:45
@spadgett yep, but this didn't happen with v1.4.1

**Comment by andrewklau** [comment] 2017-04-27 12:52
I checked on a different cluster that didn't have cluster resource override, the issue doesn't exist there. So only when cluster resource override in in play.

**Comment by spadgett** [comment] 2017-04-27 13:34
When a `cpuRequestToLimitPercent` value is set and request is calculated from limit, we hide CPU request everywhere in the web console and only show CPU limit. This includes HPA target utilization, which we show as a percentage of CPU limit. The value in the API is relative to CPU request, so the numbers might be different.

For example, if `cpuRequestToLimitPercent` is set to 50, the API will show target utilization 70% (of CPU request) whereas the UI will show it as 35% (of CPU limit). The problem is that this is confusing for anyone who also uses the CLI or API directly. We could do a better job of labeling and explaining this in the web console.

I don't know why the value was shown as 700% though, and the behavior should be the same for 1.4.1 and 1.5.

**Comment by andrewklau** [comment] 2017-04-27 13:39
Confusing but definitely make sense now. Thanks!

So I guess the only real bug was for some reason every HPA after the upgrade went from 70% to 700%

**Comment by jwforres** [comment] 2017-05-25 15:46
@fabianofranz we have a UX inconsistency issue here.  I have a feeling there is nothing we can do here from the CLI because I don't think the CLI has a way to check how the cluster override settings are configured

Some options I can think of
1) Switch the console to always show it relative to request to be consistent with the CLI
2) Show both numbers in the console with a label on each for what they are relative to
3) update the header in the CLI to specify "Request Target" instead of just "Target", but i worry about the length of that header compared to the content

**Comment by fabianofranz** [comment] 2017-05-26 21:09
> update the header in the CLI to specify "Request Target" instead of just "Target", but i worry about the length of that header compared to the content

You refer to `get` and probably `describe`, correct? Should be [pretty simple](https://github.com/kubernetes/kubernetes/blob/9ebfe9662fd60e6c59e8c8559704e196476f2c65/pkg/printers/internalversion/printers.go#L96) to do, but upstream.

**Comment by fabianofranz** [comment] 2017-05-26 21:14
BTW the logic for how the `TARGETS` column value is built in `get` is [here](https://github.com/kubernetes/kubernetes/blob/9ebfe9662fd60e6c59e8c8559704e196476f2c65/pkg/printers/internalversion/printers.go#L1703), in case it helps. 

@smarterclayton server-side get? :)

**Comment by andrewklau** [comment] 2017-06-06 11:45
btw, an update on the actual original reason for this issue. The jump occurred because I had changed the 
 `cpuRequestToLimitPercent` and `limitCPUToMemoryPercent` so it must have updated the HPA targets accordingly.

**Comment by spadgett** [comment] 2017-06-06 11:50
@andrewklau Ah, that would do it :) Thanks for letting us know.

So the only remaining issue is the UX inconsistency between the CLI and web console when cluster resource override is on.

**Comment by smarterclayton** [comment] 2017-06-06 13:06
I'm not terribly inclined to wait for serverside get for this, because
I want that admission controller to die, because we shouldn't need it.
It's the problem, not HPA.  We need to fix the fact that we lie to end
users.

**Comment by spadgett** [comment] 2017-07-24 12:08
This is now tracked in Bugzilla as well.

https://bugzilla.redhat.com/show_bug.cgi?id=1474196

**Comment by jwforres** [comment] 2017-11-02 18:22
Don't need to track this twice, closing in favor of bugzilla

**Closed by jwforres** 2017-11-02 18:22 UTC
Labels: area/usability, component/cli, component/web, kind/bug, priority/P3

**Comment by spadgett** [comment] 2018-01-16 23:28
The discrepancy between web console and CLI will be fixed by https://github.com/openshift/origin-web-console/pull/2671 since it will stop converting the values to a percentage of limit.
