### ISSUE TITLE
oc cluster up not using unique certs

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11651] opened 2016-10-28 20:43 UTC
If you run oc cluster up a second time, you'll find on logging in that the browser does not like the generated cert because it shares a serial number w/ an existing cert.

the workaround is to wipe out your config (/var/lib/origin by default), but it should be using a unique serial number each time it starts, if it is generating a new cert.

**Comment by liggitt** [comment] 2016-10-28 21:37
Or a unique signer. How is cluster up generating certs?

**Comment by bparees** [comment] 2016-10-28 22:31
it's entirely likely i misdescribed the problem :)

**Comment by csrwng** [comment] 2016-10-28 23:39
Cluster up generates certs along with the rest of the config with `openshift start --write-config`. @liggitt based on this issue it looks like that doesn't result in new certs every time. Is that right? Should we switch to explicitly calling the command to generate certs?

**Comment by liggitt** [comment] 2016-10-28 23:47
It should. Does it have access to all the original files, including the serial.txt file?

**Comment by csrwng** [comment] 2016-10-29 00:30
It should. But if the files already exist, no new certs are generated? The intent is to re-generate certs and config unless you specify --use-existing-config

**Comment by csrwng** [comment] 2016-11-01 23:42
@bparees so testing this on my RHEL machine it looks like from run to run we're just keeping the same certs, and it's something I never looked into since it's "just worked" (tm) before. I would like to understand what is causing the new certs to be generated on your machine. I also tried on a Fedora VM to see if I could get the same result as you, but I couldn't reproduce there either. If you can reproduce consistently, it'd be great to see a diff of the config directory from run to run on your machine.

**Comment by bparees** [comment] 2016-11-02 01:33
@csrwng I think the issue is that my machine changed ips in between cluster ups?  but now i don't remember for sure.  I also have a recollection of recreating it just by doing cluster down/cluster up w/o changing IPs so i may have to do some recreate work to reestablish the conditions.

**Comment by jorgemoralespou** [comment] 2016-11-04 11:26
@csrwng @bparees yes, the ip issue with cert is really problematic and likely the cause.

That's why we (EVG) try to always be prescriptive on the ip (either 127.0.0.1 or a virtual loopback IP created on the host) so changing from network to network should not matter.

Then, the problem is that if you want to keep profiles, like we do (in oc-cluster wrapper script) then we might find that there's multiple clusters created with same ip, and hence same config, that will have different certs on the local KUBECONFIG, so user will not be able to log unless he removes the config.

This is a problem we've been stumbling on, and that for us is making us have KUBECONFIGs per profile, with the additional difficulty that it creates.

**Comment by csrwng** [comment] 2017-06-27 18:04
Changing IPs is no longer an issue. Closing this

**Closed by csrwng** 2017-06-27 18:04 UTC
Labels: component/install, kind/bug, priority/P2
